### ISSUE TITLE
Installing with Homebrew doesn't work

### ISSUE THREAD

**Issue by paulrberg** [foundry-rs/foundry#100]
## Description

I used the command from [dapptools.rs](https://dapptools.rs):

```sh
$ brew install dapptools-rs
```

But I got this error:

```text
Warning: No available formula or cask with the name "dapptools-rs".
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

## Environment

- homebrew v3.2.16-28-gd93d19a
- macOS@11.6

**Comment by odyslam** [comment]
yeah, we are waiting for a release to kickstart the whole process.

**Comment by lucas-manuel** [comment]
Should we close this? Also what is the status with dapptools-rs/dapptools.rs? Should we deprecate both?

**Comment by onbjerg** [comment]
Closing this since it's technically a duplicate of #20
