### ISSUE TITLE
contract file parsing and solc errors

### ISSUE THREAD

**Issue by odyslam** [foundry-rs/foundry#1002]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

latest

### What command(s) is the bug in?

forge build

### Operating System

macOS (amd)

### Describe the bug

Creating an issue to dump the relevant problems as I find them.

The issue appears to be in OS (like macos) that is case insensitive, thus capitalized and non-capitalized smart contracts are the same. The problem arises when the file appears to be capitalised, but for some reason solc sees it uncapitalized. 

In the following example, we see solc showing the same file with 2 different versions (capitalised, not capitalised).

<img width="752" alt="image" src="https://user-images.githubusercontent.com/13405632/159262180-606cec17-81d9-4d21-9b86-d3f28773dd52.png">

**Comment by mattsse** [comment]
can you push a branch where I can see the content of those files?

**Comment by onbjerg** [comment]
Ping @odyslam - can you provide an example we can check out? :smile:

**Comment by mattsse** [comment]
think we can close this
