### ISSUE TITLE
Mode to export csv of fuzz inputs and return values

### ISSUE THREAD

**Issue by transmissions11** [foundry-rs/foundry#1022]
### Component

Forge

### Describe the feature you would like

running `forge test --export` would output a csv mapping fuzz inputs of each test function (or a specific if you use --match) to their corresponding return values 

### Additional context

when doing anything involving complex fixed point math it's often desired to benchmark against a more precise impl done outside of solidity. using ffi is slow and manually setting up loops is tedious and doesn't often highlight the edge cases of a function we care about. outputting a csv would allow anyone to easily plug the data into a tool like mathematica, matlab, another language, etc to benchmark against a precise version and build more accurate arithmetic functions :D

**Comment by transmissions11** [comment]
possibly related to #991

**Comment by onbjerg** [comment]
Can you elaborate on what you mean by return value? The revert reason, if any?

**Comment by mds1** [comment]
Ah sorry, like the literal test function return value. Right now afaik no one adds return values to their test methods because there's no use for doing so, but this method would change that. For example:

```solidity
// say we're testing a math function to compute e^x
function testExp(uint256 x) public returns (uint y) {
  y = myMathLib.exp(x);
  // maybe some assertions here
} 
```

The above fuzz test would output a csv (or json) file with the first column being the run number, the second being the values of `x` during each fuzz fun, and the third column being the value of `y` returned from `testMyMethod`

**Comment by dmfxyz** [comment]
Adding my interest to this. Deterministic fuzzing would be great for testing gas improvements to functions with very dynamically sized inputs e.g. [merkle-proof generation, verification, and comparison](https://github.com/dmfxyz/murky/blob/main/src/test/GenericMerkle.t.sol#L31). FFI is a work around but would be nice to keep everything within the foundry ecosystem.

**Comment by onbjerg** [comment]
Is your use case covered by #2038? :smile:

**Comment by transmissions11** [comment]
for me it is yes, i did some analysis with a csv yesterday and it was wonderful
