### ISSUE TITLE
No gas-report for property-based tests

### ISSUE THREAD

**Issue by 0xalfalfa** [foundry-rs/foundry#1023]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (22323e2 2022-03-23T00:09:43.397848305+00:00)

### What command(s) is the bug in?

forge test --gas-report

### Operating System

Linux

### Describe the bug

Property-based tests do not seem to generate data for gas-reports. 

- If there are only property-based (fuzzying) tests defined, the --gas-report flag does not generate a gas-report output at all.
- If there are property-based tests and tests without function arguments, only the calls to the later generate data for the gas-report.

Expected behaviour:

Why not use the large number of fuzzing function calls for the gas report?

**Comment by onbjerg** [comment]
This is probably fixed with REVM #918

**Comment by onbjerg** [comment]
This is not fixed with REVM. It's not super trivial to do this since we need to collect traces for all fuzz cases which could end up slowing down Forge a lot. Will think about this more

**Comment by hbarcelos** [comment]
Couldn't you sample only a small % of the fuzz cases to generate the gas reports? Maybe 2% could be enough.

**Comment by lucas-manuel** [comment]
Close-able? @mds1

**Comment by mds1** [comment]
Yep this is now implemented
