### ISSUE TITLE
Ugly console log for Windows

### ISSUE THREAD

**Issue by ayanamidev** [foundry-rs/foundry#1029]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

0.2.0 ( latest )

### What command(s) is the bug in?

forge test

### Operating System

Windows

### Describe the bug

![Capture (4)](https://user-images.githubusercontent.com/91770832/159801458-9f041478-e685-4716-8cad-49bba79f1e8c.PNG)

Running `forge test` on Windows produces ugly console output which is not very formatted unlike the one from Linux

**Comment by mattsse** [comment]
thanks for this!
can you share some details of the terminal you used?

I think we should somehow check if the terminal supports colors, maybe the atty crate supports this

**Comment by onbjerg** [comment]
It's because your terminal does not support ANSI escape sequences

**Comment by 0xAyanami** [comment]
@mattsse @onbjerg It would be a plain cmd console from Windows.

Trying from Powershell

![Capture (5)](https://user-images.githubusercontent.com/91770832/159816674-93056010-ed32-4aa6-b9e2-26ca94481c4a.PNG)

From Git bash

![Capture (6)](https://user-images.githubusercontent.com/91770832/159816686-5c262f61-2af7-424d-997a-01db71e8b028.PNG)

I assume that UNIX like bash system is the only working command line tool for this console output

**Comment by onbjerg** [comment]
Fixed in #1450
