### ISSUE TITLE
Flag to use new nonce

### ISSUE THREAD

**Issue by EzraWeller** [foundry-rs/foundry#1051]
### Component

Forge

### Describe the feature you would like

Be able to manually use a new nonce when creating transactions with `forge create` (and probably also all other transactions, could apply to cast as well).

### Additional context

This is coming up because I am using `forge create` to deploy to Polygon and getting this error:
`(code: -32000, message: replacement transaction underpriced, data: None)`
(working in [this repo](https://github.com/R-Group-Devs/squadz-contracts))

**Comment by mattsse** [comment]
ref #937
