### ISSUE TITLE
move include_fuzz_test to config struct

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#1088]
this will require some minor refactoring because this is actually the first config val directly included in the `TestArgs` struct, so I'll rewrite the macro that does all the config magic,
moving this to a followup

_Originally posted by @mattsse in https://github.com/gakonst/foundry/pull/1086#discussion_r836218095_

**Comment by onbjerg** [comment]
No longer applicable since the flag doesn't exist anymore (not needed)
