### ISSUE TITLE
Forge test: call traces not decoded after upgrading to 0.2.0

### ISSUE THREAD

**Issue by ArcadiaFinance** [foundry-rs/foundry#1100]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (613da19 2022-03-28T15:06:43.699738100+00:00)

### What command(s) is the bug in?

forge test -vvv

### Operating System

Windows

### Describe the bug

Provided two contracts:

> regTest.sol

```
pragma solidity ^0.8.10;

contract RegressionOriginal {

    address public toDecodeAddr;

    function decodeThiss(uint256 amountDecode, address toDecode) public returns (address[] memory, uint256, uint256[] memory) {
        address[] memory addArr = new address[](2);
        addArr[0] = msg.sender;
        addArr[1] = toDecode;

        toDecodeAddr = toDecode;

        uint256[] memory uintArr = new uint256[](2);
        uintArr[0] = gasleft();
        uintArr[1] = amountDecode;

        return (addArr, gasleft(), uintArr);
    }
}
```

and 

> regTest2.sol

```
pragma solidity ^0.8.10;

contract NotRegressionTheOriginal {

    address public toDecodeAddr;

    function decodeThis(uint256 amountDecode, address toDecode) public returns (address[] memory, uint256, uint256[] memory) {
        address[] memory addArr = new address[](2);
        addArr[0] = msg.sender;
        addArr[1] = toDecode;

        toDecodeAddr = toDecode;

        uint256[] memory uintArr = new uint256[](2);
        uintArr[0] = gasleft();
        uintArr[1] = gasleft();

        return (addArr, gasleft(), uintArr);
    }
}
```

combined with a test contract,

> regTest.t.sol

```
pragma solidity >0.8.10;

import "../../lib/ds-test/src/test.sol";

import "../regTest.sol";
import "../regTest2.sol";

contract RegressionTest is DSTest {
  
  function testDecodes(uint256 fuzzUint, address fuzzAddr) public {
    RegressionOriginal contractOrig = new RegressionOriginal();

    contractOrig.decodeThiss(fuzzUint, fuzzAddr);
    fail();
  }

  function testContractsAreNotEqual() public {
    assertTrue(keccak256(type(NotRegressionTheOriginal).creationCode) != keccak256(type(RegressionOriginal).creationCode));
  }

}
```

---

Installing forge/cast from source or through foundryup, using the latest v0.2.0 shows issues with decoding the `contractOrig.decodeThiss` call. In my case it shows two unexpected behaviors:

1) The function call is not decoded, along with the input being not decoded.
2) The wrong contract is shown in `<contractName>::<function>`.

`regTest.t.sol` tests for both contracts not being the same (although highly similar, note the additional `s` in `decodeThiss` and the `uintArr[1]` difference).

![image](https://user-images.githubusercontent.com/102544091/160454031-368a3d26-87ff-4470-a369-64994326c082.png)

running `forge clean` does not solve this issue.

More peculiar, when you:
1) delete the 'regTest2.sol' file and 
2) remove the references in the `regTest.t.sol` to that file

> regTest.t.sol

```
pragma solidity >0.8.10;

import "../../lib/ds-test/src/test.sol";

import "../regTest.sol";
//import "../regTest2.sol";

contract RegressionTest is DSTest {
  
  function testDecodes(uint256 fuzzUint, address fuzzAddr) public {
    RegressionOriginal contractOrig = new RegressionOriginal();

    contractOrig.decodeThiss(fuzzUint, fuzzAddr);
    fail();
  }

  // function testContractsAreNotEqual() public {
  //   assertTrue(keccak256(type(NotRegressionTheOriginal).creationCode) != keccak256(type(RegressionOriginal).creationCode));
  // }

}
```

the decoding of the function & function input works. The correct contractname is also referenced in the call trace.

![image](https://user-images.githubusercontent.com/102544091/160455704-6eebe48d-0b26-4d65-83da-50112da8c5da.png)

After adding back the original `regTest2.sol` file (and running `forge clean` as desired), the unwanted behavior returns. This is even without having the contract in `regTest2.sol` referenced in the test file:

![image](https://user-images.githubusercontent.com/102544091/160455039-2f4d3ae4-1966-4f8d-8ed0-0d4731010328.png)

Upon downgrading to v0.1.0 using `cargo install --git https://github.com/gakonst/foundry --rev 22323e21c3e00d9eccc5914589c23f2a0115413b --bins --locked` , the unexpected behavior does not show. I.e., all function calls are decoded correctly and the contract names are referred to as expected.

As I assume it might be something cache related, I hope to be able to reproduce it on another machine "from scratch", but haven't had the chance to yet.

**Comment by onbjerg** [comment]
This is due to how we identify contracts - they are identified using fuzzy matching of the bytecode, and the bytecode of both of these contracts are very similar

**Comment by ArcadiaFinance** [comment]
Understood. This was the smallest repro example I could create. 

I notice on our main project that almost all of the calls are not decoded (and the contract names aren't shown either) on 0.2.0. Just a solmate's `ERC20.transferFrom` and a sporadic `ERC20.mint` seems to come through.

![image](https://user-images.githubusercontent.com/102544091/160459140-f4bbfa29-7b1b-4789-a588-9382320dfa36.png)

![image](https://user-images.githubusercontent.com/102544091/160459511-8973ec16-7d95-4799-ae1c-5a47c3ea322b.png)


The project does work with factories & proxies, perhaps a similar rootcause?

**Comment by onbjerg** [comment]
Should work with proxies - are the bytecodes of all your contracts very similar? I think the threshold is 10%

**Comment by ArcadiaFinance** [comment]
>Should work with proxies - are the bytecodes of all your contracts very similar? I think the threshold is 10%

We have a series of contracts that do inherit the same abstract contract, but only about 5 of them inherit that same contract (from around ~30 which don't get decoded). The other contracts are very different, asides from an occasional shared openzeppelin's Ownable for example.
In our tests, we do create many instances of the same contracts. For example, a series of ERC20's that are based on the same contract, a series of ERC721's, series of ERC1155's, series oracles, ...

> Also, do traces for your main project decode properly with 0.1.0?

Yes! All traces for all calls, including contract names, function names and input decodes work perfectly on 0.1.0.

**Comment by jparklev** [comment]
> @jparklev if you have any more minimal example it'd help! thanks!

I went to produce a minimal example and was having some trouble, so I went back to my original, cleaned the cache, and now it works as expected. Not sure how I got into the state before, maybe a vestige of a previous version in my cache? At any rate, will come back here and try to track it down if I run into it again.

(what I was seeing was that the trace wasn't decoding solmate ERC20 token function sigs or events)

**Comment by joshieDo** [comment]
faced the same issue when I had artifacts/cache from `forge 0.1.0`. once i cleared the cache, everything showed perfectly

**Comment by brockelmore** [comment]
is this still an issue @ArcadiaFinance @jparklev? Or has it been fixed?

**Comment by gakonst** [comment]
I assume this is no longer an issue, feel free to reopen

**Comment by Thomas-Smets** [comment]
Hi @brockelmore, @gakonst, Thomas from Arcadia here.
Seems that it is no longer an issue, thanks for the efforts looking into it!
