### ISSUE TITLE
Function Modifier or an Opcode to mark a test as skipped conditionally

### ISSUE THREAD

**Issue by vminkov** [foundry-rs/foundry#1123]
### Component

Forge

### Describe the feature you would like

It would be nice to have a Forge provided modifier that lets one mark a test as skipped `[SKIP]` depending on some custom condition. The specific use case we need it for is to mark which tests are run on different mainnet forks

The code that we currently use looks like this (below) but it marks the skipped tests as passed `[PASS]` 

```
  uint256 BSC_MAINNET = 56;
  uint256 ETH_KOVAN = 42;
  uint256 ETH_RINKEBY = 4;
  uint256 EVMOS_TESTNET = 9000;

  /// custom modifier for running tests conditionally
  modifier shouldRun(bool run) {
    if (run) {
      _;
    }
  }

 // filter function for a specific chain
  function forChains(uint256 id0) public view returns (bool) {
    return block.chainid == id0;
  }

 // filter function for multiple chains
  function forChains(uint256 id0, uint256 id1) public view returns (bool) {
    return block.chainid == id0 || block.chainid == id1;
  }


  // TEST CASES


  function testSomething() public {
    // this test will be run on all chains
  }
 
  function testSomethingElse() public shouldRun(forChains(BSC, ETH_KOVAN)) {
    // this test will be skipped on EVMOS_TESTNET and ETH_RINKEBY
  }
```

I would imagine that we're provided by the forge env either a modifier like `shouldRun(forChains(...))` or some assembly opcode to return from the test marking it as skipped `[SKIP]` and then we can craft the modifier in the same way

```
  modifier shouldRun(bool run) {
    if (run) {
      _;
    }
    else {
      assembly {
        some_op_code_to_mark_test_as_skipped()
      }
    }
  }
```

### Additional context

![image](https://user-images.githubusercontent.com/2662912/160651050-17cb2403-e4b8-47e8-ac4d-9b1c2ba70e31.png)

**Comment by onbjerg** [comment]
I wonder if this is needed anymore since we now have fork-related cheatcodes to choose what fork to use on a per-test level? Wdyt @vminkov?

**Comment by mds1** [comment]
I still think this feature is useful in some cases. For example with hardhat, I'd sometimes scaffold out a bunch of unimplemented tests and mark them as skipped to signal that they're not implemented. Having them pass/fail didn't feel correct since it might be a while until all tests are implemented.

Instead of a cheatcode, another idea is a special test name prefix, like `function skipTest*()` instead of the usual `function test*()`. (Either cheatcode or function name is fine with me, no preference here)

**Comment by vminkov** [comment]
For our use case the fork-related cheatcodes are good enough alternative. It is still useful to mark a test case as skipped when the reasons for its failure are not related to the code that is tested, but to the fork RPC URL being invalid, for example.

**Comment by mattsse** [comment]
> Instead of a cheatcode, another idea is a special test name prefix, like function skipTest*() instead of the usual function test*(). (Either cheatcode or function name is fine with me, no preference here)

I think this would be the best fix here, since we identify tests via naming convention, simply adding `skip`, or `ignore` feels more appropriate than adding a `vm.skip()` call.

**Comment by gakonst** [comment]
I thought the OP wanted to skip tests on certain conditions like the chain id, which the `skiptest` idea I think does not address

**Comment by mds1** [comment]
Probably should have left this comment in this issue instead, so linking to it here https://github.com/foundry-rs/foundry/pull/2606#issuecomment-1205435913

**Comment by alcueca** [comment]
I've got another use case for this feature, which I originally described in #3845, and that now I'm moving here.

When coding a test harness for live contracts, it is not possible to know in advance the state the the smart contracts will be in. Therefore, some tests will make sense, and others will not.

For example, we might have a set of tests that make sense on a given uninitialized contract, but once the contract is initialized it would make more sense to skip those tests and move on to the next ones in the same file.

The workaround described above still works, but the PASS in the output might still lead to confusion as to what is the current state of my contracts.

I would very much prefer if the test would show as SKIP, and maybe even in the summary at the end ("67 passed, 32 skipped, 0 failed", for example). `vm.skip(bool)` would work just fine.

Additional context
In [this test file](https://github.com/yieldprotocol/strategy-v2/blob/6bb7c7f73340537053c6a147b207b91139741c4f/test/StrategyHarness.t.sol#L237), this test only makes sense in the contract is in an EJECTED state after the setup function.

**Comment by mds1** [comment]
Copying some nice from https://github.com/foundry-rs/foundry/issues/4918 here, cc @shazow
- Two new cheats: `vm.skip(bool skip)` and `vm.skip(bool skip, string calldata reason)`, where the latter prints a reason string
- Ensure the `skip` call can be made at the test level or `setUp` level

cc @Evalir, might be an easy one and this is often requested
