### ISSUE TITLE
Tests pass with failed assertion in external call 

### ISSUE THREAD

**Issue by FrankieIsLost** [foundry-rs/foundry#1149]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (09d53c2 2022-03-31T00:32:45.902442+00:00)

### What command(s) is the bug in?

forge test

### Operating System

macOS (M1)

### Describe the bug

Tests are passing even though assertion fails 
![Screen Shot 2022-03-31 at 12 58 28 AM](https://user-images.githubusercontent.com/88221686/161006566-82666b24-b704-4421-b54c-a307a03de7ae.png)

## How to reproduce 

Run ` forge test -vv` with the following test contract: 

```
contract TestMain is DSTest {

    TestUtil util = new TestUtil();

    function testInternalCall() public { 
        shouldFailInternal();
    }

    function shouldFailInternal() public {
        assertTrue(false);
    }

    function testExternalCall() public { 
        util.shouldFailExternal();
    }
}

contract TestUtil is DSTest { 
    function shouldFailExternal() public { 
        assertTrue(false);
    }
}

```

## Expected Result 

Both tests should fail 

## Actual Result 

Only the test where the assertion fails in an internal call fails. Test where assertion fails in external call passes. 

## Severity 

This is likely a high sev bug. Code bases with complex tests are likely to refactor their testing into multiple contracts. This bug can cause tests to fail silently.

**Comment by onbjerg** [comment]
This is not a bug - `assertTrue(false)` does not revert, it just sets `failed = true` in the contract. We **only** check `failed` on test contracts, not the contracts that it itself deployed.

You should:

- use inheritance to get around this, or
- have your `TestUtil` contract revert, or
- override `failed`

I don't think iterating over all members of the test contract to check `failed` on every address is something we want to do - it's expensive and likely to produce other weird behavior. This is also not how DappTools behaves

**Comment by d-xo** [comment]
related: https://github.com/dapphub/dapptools/issues/768

**Comment by gakonst** [comment]
Yeah we could have a specific address / storage slot which we treat as the global?

**Comment by brockelmore** [comment]
https://github.com/dapphub/ds-test/pull/30

implementing a fix upstream that should fix this
