### ISSUE TITLE
`forge test --debug` does not respect `--use`

### ISSUE THREAD

**Issue by d-xo** [foundry-rs/foundry#1155]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (09d53c2 2022-03-31T00:31:39.994883040+00:00)

### What command(s) is the bug in?

forge test --debug

### Operating System

Linux

### Describe the bug

`forge test --debug` does not respect the `--use` flag and instead tries to redownload the solc binary via svm-rs (which are currently not compatible with nixos: https://github.com/roynalnaruto/svm-rs/issues/36):

```
$ export SOLC=/nix/store/q72kbq1kl03jhpyv04zv29d0kv67gczk-solc-static-0.8.10/bin/solc-0.8.10

$ forge test --use $SOLC
[⠊] Compiling...
[⠔] Compiling 3 files with 0.8.10
Compiler run successful

$ forge test --use $SOLC --debug testExample
[⠊] Compiling...
No files changed, compilation skipped
[⠊] Compiling...
[⠔] installing solc version "0.8.10"
[⠒] Successfully installed solc 0.8.10
Error:
   0: "/home/me/.svm/0.8.10/solc-0.8.10": No such file or directory (os error 2)

Location:
   cli/src/cmd/utils.rs:118

Backtrace omitted.
Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by onbjerg** [comment]
The bug is in `forge run` (`forge test --debug` just uses `forge run` which is also why there is a double compilation) for anyone willing to pick this up

**Comment by brockelmore** [comment]
@onbjerg @d-xo  is this still an issue? i cant repro because i dont have nix

**Comment by onbjerg** [comment]
You could repro without Nix if you use a version lower than what is auto-detected by Forge, but it should be fixed in https://github.com/gakonst/ethers-rs/issues/1202
