### ISSUE TITLE
Not being able to compile because of "Discovered incompatible solidity versions in following"

### ISSUE THREAD

**Issue by StErMi** [foundry-rs/foundry#1163]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

0.2.0

### What command(s) is the bug in?

forge build

### Operating System

macOS (amd)

### Describe the bug

I'm migrating https://www.damnvulnerabledefi.xyz/ v2 to forge as both a CTF exercise and a learning exercise (for Forge).

I'm attempting to migrate the [Puppet-v2 challenge](https://github.com/tinchoabbate/damn-vulnerable-defi/tree/v2.0.0/contracts/puppet-v2)  and when I attempt to build the code I get this error:

```
[⠃] Compiling...2022-04-01T06:28:20.723718Z ERROR ethers_solc::resolver: failed to resolve versions
[⠊] Compiling...
Error: 
   0: Discovered incompatible solidity versions in following
      : src/test/puppet-v2/PuppetV2Test.t.sol (^0.6.0) imports:
          lib/forge-std/src/stdlib.sol (>=0.6.0 <0.9.0)
          src/test/utils/Utilities.sol (>=0.8.0)
          src/test/BaseTest.sol (0.8.10)
          src/DamnValuableToken.sol (^0.8.0)
          lib/forge-std/src/Vm.sol (>=0.6.0)
          lib/ds-test/src/test.sol (>=0.4.23)
          lib/forge-std/src/Vm.sol (>=0.6.0)
          lib/ds-test/src/test.sol (>=0.4.23)
          lib/forge-std/src/Vm.sol (>=0.6.0)
          lib/forge-std/src/console.sol (>=0.4.22 <0.9.0)
          src/test/utils/Utilities.sol (>=0.8.0)
          lib/openzeppelin-contracts/contracts/token/ERC20/ERC20.sol (^0.8.0)
          lib/openzeppelin-contracts/contracts/token/ERC20/IERC20.sol (^0.8.0)
          lib/openzeppelin-contracts/contracts/token/ERC20/extensions/IERC20Metadata.sol (^0.8.0)
          lib/openzeppelin-contracts/contracts/utils/Context.sol (^0.8.0)
          lib/openzeppelin-contracts/contracts/token/ERC20/IERC20.sol (^0.8.0)
```

If you want to reproduce this clone the [puppet-v2 branch](https://github.com/StErMi/forge-damn-vulnerable-defi/tree/puppet-v2) from my repo and just hit `forge build`.

This specific challenge involves a mix of external contracts like WETH9 + Uniswap v2 core + Uniswap v2 periphery.

The testing file that will break everything is [PuppetV2Test.t.sol](https://github.com/StErMi/forge-damn-vulnerable-defi/blob/puppet-v2/src/test/puppet-v2/PuppetV2Test.t.sol)

I've already moved `WETH9` from being a solidity contract (in the original CTF) to be an artifact deployed using `deployCode` but as soon you uncomment this line

```import "../../puppet-v2/PuppetV2Pool.sol";```

and attempt to build, you will see the above error.

**Comment by mattsse** [comment]
your source file is incompatible with its imports
`src/test/puppet-v2/PuppetV2Test.t.sol (^0.6.0)` is only compatible with 0.6 while this `src/test/utils/Utilities.sol (>=0.8.0)` requires at least 0.8.0
so there's no solc version that's compatible

**Comment by StErMi** [comment]
> your source file is incompatible with its imports `src/test/puppet-v2/PuppetV2Test.t.sol (^0.6.0)` is only compatible with 0.6 while this `src/test/utils/Utilities.sol (>=0.8.0)` requires at least 0.8.0 so there's no solc version that's compatible
> 
> upgrading `src/test/puppet-v2/PuppetV2Test.t.sol` to 0.8.0 should fix it though

`src/test/puppet-v2/PuppetV2Test.t.sol` is using `pragma solidity 0.8.10;`  not `^0.6.0`

`src/puppet-v2/PuppetV2Pool.sol` is using `pragma solidity ^0.6.0;`. If the Pool is the problem, I'm afraid that I cannot change that. That is part of the CTF, so I would say that there's a specific reason why Tincho made the contract use `solc <0.8` but I need to solve the CTF before saying so.

**Comment by outdoteth** [comment]
+1 what's the best pattern here?

**Comment by mattsse** [comment]
I'm actually not sure, but I believe pinning the solc version explicitly would fix
See `solc` option https://github.com/foundry-rs/foundry/tree/master/config#foundrytoml

**Comment by outdoteth** [comment]
pinning gives an error still. But I found a workaround... or well.. the design of foundry is so good that i guess it's already possible like this:

```
// MockUniswapV3Factory.sol

pragma solidity 0.7.6;
import "v3-core/UniswapV3Factory.sol";
```

```
// Fixture.sol

pragma solidity ^0.8.0;

import "forge-std/Test.sol";
import "v3-core/interfaces/IUniswapV3Factory.sol";

abstract contract Fixture is Test {
    IUniswapV3Factory internal uniswapV3Factory;

    constructor() {
        uniswapV3Factory = IUniswapV3Factory(deployCode("UniswapV3Factory.sol"));
    }
}
```

Remove explicit solc version pinning in foundry.toml and then when doing forge build it will auto use the correct compiler version for each contract thanks to [this](https://github.com/foundry-rs/foundry/pull/4)

then

```
forge test
```

everything *seems* to work. Haven't actually tested this yet lol and tried to interact with the uni contract.

**Comment by outdoteth** [comment]
It would be good to specify an array of solc versions i think tho. I don't feel comfortable removing the pinning and just relying on auto-detection. Being explicit is always better so if it was possible to do this i would:

```
# foundry.toml
[default]
solc_version = ["0.8.13", "0.7.6"]

[ci]
fuzz-runs = 10_000
```

**Comment by vsevdrob** [comment]
**Receiving the same issue as above is described**:
```bash
mbp:chainlink-foundry-mix mac$ forge build
[⠃] Compiling...2022-04-21T15:46:26.394877Z ERROR ethers_solc::resolver: failed to resolve versions
[⠊] Compiling...
Error: 
   0: Discovered incompatible solidity versions in following
      : src/test/PriceConsumerV3.t.sol (>=0.8.7 <0.8.12) imports:
          lib/ds-test/src/test.sol (>=0.5.0)
          src/PriceConsumerV3.sol (>=0.8.7 <0.8.12)
          src/test/mocks/MockV3Aggregator.sol (^0.6.0)
          lib/openzeppelin-contracts/contracts/access/Ownable.sol (^0.8.0)
          lib/chainlink-brownie-contracts/contracts/src/v0.8/interfaces/AggregatorV3Interface.sol (^0.8.0)
          lib/chainlink-brownie-contracts/contracts/src/v0.6/interfaces/AggregatorV2V3Interface.sol (^0.6.0)
          lib/openzeppelin-contracts/contracts/utils/Context.sol (^0.8.0)
          lib/chainlink-brownie-contracts/contracts/src/v0.6/interfaces/AggregatorInterface.sol (^0.6.0)
          lib/chainlink-brownie-contracts/contracts/src/v0.6/interfaces/AggregatorV3Interface.sol (^0.6.0)

Location:
   cli/src/compile.rs:99

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```
**Version**:
```bash
mbp:chainlink-foundry-mix mac$ forge --version
forge 0.2.0 (321960f 2022-04-21T00:04:58.244311+00:00)
```

**Comment by mattsse** [comment]
these are the offenders in your case
`lib/chainlink-brownie-contracts/contracts/src/v0.6/* (^0.6.0)` which is incompatible 

consider using the v0.8 versions of chainlink-brownie-contracts instead @vsevdrob

**Comment by test9955667** [comment]
> It would be good to specify an array of solc versions i think tho. I don't feel comfortable removing the pinning and just relying on auto-detection. Being explicit is always better so if it was possible to do this i would:
> 
> ```toml
> # foundry.toml
> [default]
> solc_version = ["0.8.13", "0.7.6"]
> 
> [ci]
> fuzz-runs = 10_000
> ```

running into some pretty nasty issues when specifying multiple solc versions with a panic:
"data did not match any variant of untagged enum SolcReq" 

Found myself at this thread because I am importing univ3 contracts down to 0.5.0 with a ton of incompatibility errors. will play around with it but worst case scenario i replace the interfaces with higher pragma minimal interfaces and gutting the libraries because I'm only using 4

**Comment by test9955667** [comment]
still panics the same when I specify a single version instead of throwing compiler error, strange. 
I do have quite a messy amt of versioned sol imports so will focus on cleaning that up in the meantime

**Comment by gakonst** [comment]
> Since this problem makes it very hard to deal with incompatible versions, we should consider adding an option that makes it possible to exclude Semver enforcement.

sorry not sure I follow here, what would we do by excluding semver enforcement?

**Comment by aiwowo1** [comment]
Hello, got the same issue. tried to find the offender but it seems all in range. Any help would be appreciated. 

```
[⠃] Compiling...2022-05-10T15:14:21.660641Z ERROR ethers_solc::resolver: failed to resolve versions
[⠊] Compiling...
Error:
   0: Discovered incompatible solidity versions in following
      : test/MyTestContract.t.sol (>=0.5.0 <= 0.9.0) imports:
          lib/forge-std/src/Test.sol (>=0.6.0 <0.9.0)
          contracts/UniswapV2Pair.sol (=0.5.16)
          lib/forge-std/src/Vm.sol (>=0.6.0)
          lib/forge-std/lib/ds-test/src/test.sol (>=0.5.0)
          lib/forge-std/src/console.sol (>=0.4.22 <0.9.0)
          lib/forge-std/src/console2.sol (>=0.4.22 <0.9.0)
          contracts/interfaces/IUniswapV2Pair.sol (>=0.5.0)
          contracts/UniswapV2ERC20.sol (=0.5.16)
          contracts/libraries/Math.sol (=0.5.16)
          contracts/libraries/UQ112x112.sol (=0.5.16)
          contracts/interfaces/IERC20.sol (>=0.5.0)
          contracts/interfaces/IUniswapV2Factory.sol (>=0.5.0)
          contracts/interfaces/IUniswapV2Callee.sol (>=0.5.0)
          contracts/interfaces/IUniswapV2ERC20.sol (>=0.5.0)
          contracts/libraries/SafeMath.sol (=0.5.16)

  Location:
     cli/src/compile.rs:99
  
  Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
  Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by 0xdomrom** [comment]
+1 Really hoping for there to be an option to compile different contracts with different versions.

Even a super explicit mapping of `ContractName: version` in a file somewhere would be amazing since you'd only have to set it once

**Comment by gakonst** [comment]
You cannot import a contract with an incompatible Solidity version in another contract! The 'right' way to do this, is via `deployCode`, e.g. see [here](https://github.com/gakonst/v3-periphery-foundry/blob/main/contracts/foundry-tests/utils/Deploy.sol#L35-L36).

**Comment by onbjerg** [comment]
Going to close this issue since it is not possible given how solc works right now, so it's not really a bug we can address. We'll take a look at this feature once solc supports bytecode imports :)

**Comment by megabyte0x** [comment]
What's the result of the discussion? Is there any solution to this?

**Comment by AuditorPraise** [comment]
@onbjerg any update?
