### ISSUE TITLE
Option to ignore warnings from dependencies in foundry.toml

### ISSUE THREAD

**Issue by pmdaly** [foundry-rs/foundry#1200]
### Component

Forge

### Describe the feature you would like

Some of my projects have dependencies I can't change.  Due to implementations of some of the abstract contracts, there are unused imports that cause warnings.  These warnings spam my stdout and aren't relevant to my projects.  I'd like the ability to silence warnings from dependencies.

**Comment by Alef-gabriel** [comment]
I can take this?

**Comment by mattsse** [comment]
sure!
I think this would require parsing the error message and check where they originated from

**Comment by Alef-gabriel** [comment]
Hello guys I tried to replicate your issue but I couldn't. Could you share exactly what I do?

**Comment by guidanoli** [comment]
@Alef-gabriel I am having this exact problem.
To replicate, try [this project](https://github.com/ensdomains/ens-contracts). It should raise several warnings:

```
Warning (2519): This declaration shadows an existing declaration.
  --> ../node_modules/@ensdomains/ens-contracts/contracts/registry/ENSRegistry.sol:20:9:
   |
20 |         address owner = records[node].owner;
   |         ^^^^^^^^^^^^^
Note: The shadowed declaration is here:
   --> ../node_modules/@ensdomains/ens-contracts/contracts/registry/ENSRegistry.sol:143:5:
    |
143 |     function owner(
    |     ^ (Relevant source part starts here and spans across multiple lines).

[...]
```

**Comment by wottpal** [comment]
@guidanoli Did you find any solution to this?

**Comment by mattsse** [comment]
@loocapro perhaps you want to take this?

I believe this can be solved with:
* an option in the foundry config to enable this: https://github.com/foundry-rs/foundry/blob/00cec1d2445ad9b8917a377cb6f9b755728eb9da/crates/config/src/lib.rs#L636-L636
* some helpers in the `ProjectCompileOutput` type so we can ignore warnings that originate from  certain files: https://github.com/foundry-rs/compilers/blob/9d91a56dadfe0f86d21c875f306e7150098ebac2/src/compile/output/mod.rs#L465-L467 which is invoked here: https://github.com/foundry-rs/foundry/blob/00cec1d2445ad9b8917a377cb6f9b755728eb9da/crates/common/src/compile.rs#L207-L208
we can leverage the ProjectPaths type which has access to all library paths for example

The current workflow wrt to ignored errors is:
configure ignored error types in foundry.toml, which is then configured in the `foundry_compilers::Project`: 
https://github.com/foundry-rs/foundry/blob/00cec1d2445ad9b8917a377cb6f9b755728eb9da/crates/config/src/lib.rs#L636-L636
I think we want to enhance that setting to also make it possible to ignore paths

**Comment by mattsse** [comment]
but for this specific error @wottpal you can silence this via:

`ignored_error_codes = ["shadowing"]`, though this apply to all files atm

**Comment by wottpal** [comment]
> but for this specific error @wottpal you can silence this via:
> 
> `ignored_error_codes = ["shadowing"]`, though this apply to all files atm

Great, that already removes a lot of warnings when having ens contracts as a dependency in `node_modules`. Thanks!

But some are still persisting:

```
Compiler run successful with warnings:
Warning (1878): SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.
--> node_modules/@ensdomains/ens-contracts/contracts/ethregistrar/IBaseRegistrar.sol

Warning (1878): SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.
--> node_modules/@ensdomains/ens-contracts/contracts/ethregistrar/StringUtils.sol

Warning (1878): SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.
--> node_modules/@ensdomains/ens-contracts/contracts/registry/ENS.sol

Warning (1878): SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.
--> node_modules/@ensdomains/ens-contracts/contracts/registry/ENSRegistry.sol

Warning (1878): SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.
--> node_modules/@ensdomains/ens-contracts/contracts/reverseRegistrar/IReverseRegistrar.sol

Warning (1878): SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.
--> node_modules/@ensdomains/ens-contracts/contracts/root/Controllable.sol

Warning (3420): Source file does not specify required compiler version! Consider adding "pragma solidity ^0.8.22;"
--> node_modules/@ensdomains/ens-contracts/contracts/ethregistrar/IBaseRegistrar.sol

Warning (2462): Visibility for constructor is ignored. If you want the contract to be non-deployable, making it "abstract" is sufficient.
  --> node_modules/@ensdomains/ens-contracts/contracts/registry/ENSRegistry.sol:28:5:
   |
28 |     constructor() public {
   |     ^ (Relevant source part starts here and spans across multiple lines).
```

And ofc I could just ignore the specific error code, but actually I would like to get those for all files under `src/`, just not `node_modules/` :)

**Comment by mattsse** [comment]
here's a list of supported aliases:

https://github.com/foundry-rs/foundry/blob/00cec1d2445ad9b8917a377cb6f9b755728eb9da/crates/config/src/error.rs#L202-L214

but the error code works as well

**Comment by loocapro** [comment]
> @loocapro perhaps you want to take this?

Sure, I can take it!

**Comment by mattsse** [comment]
this is now supported via new config setting `ignored_warnings_from = [path]`,


will add to book

**Comment by ferencdg** [comment]
and how can I ignore 'notes' during compilation? even if I disable all warnings I can still see those notes

**Comment by 0xMaxyz** [comment]
> and how can I ignore 'notes' during compilation? even if I disable all warnings I can still see those notes

disable them  by linter config in `foundry.toml` file
e.g.
```toml
[lint]
exclude_lints=["named-struct-fields"]
```

**Comment by roshanrags** [comment]
@mattsse thoughts on whether the ignored warnings should or should not count towards the 256 warnings limit?
