### ISSUE TITLE
`vm.assume` cleanup

### ISSUE THREAD

**Issue by mds1** [foundry-rs/foundry#1202]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### Describe the bug

_(this didn't really feel like a bug or a feature request, so just put it as a bug)_

The [foundry implementation](https://github.com/gakonst/foundry/blob/09d53c2c8d473db6f2e7579e2f8e58ff55e2640b/config/src/lib.rs#L892-L893) has default config values for the rejection parameters reversed from the [proptest defaults](https://github.com/AltSysrq/proptest/blob/bc2d867a7cd06060e0b565b72fce1d94cc2fe943/proptest/src/test_runner/config.rs#L147-L148). This is actually ok and works out in our favor, because we only use global rejects with `vm.assume`. Relevant docs on proptest's local vs global rejects are [here](https://altsysrq.github.io/proptest-book/proptest/tutorial/filtering.html).

Additionally, when hitting the reject limit, tests fail with `Too many global rejects` bubbled up from proptest. I have been unable to trigger the [`ASSUME: Too many rejects`](https://github.com/gakonst/foundry/blob/33f1df0ec7e17799342ee78e5e1ffb07e9ea086d/evm/src/fuzz/mod.rs#L89) failure reason, so not sure if that codepath is still used.

Potential paths forward:
1. Remove local rejects from the config file/docs and rename the global rejects param to just `max_fuzz_rejects`, or
2. Keep both parameters, and just update the docs to mention that local rejects are currently unused but may be in the future.

Only option 1 actually results in source code changes, whereas 2 is just a documentation change.

**Comment by colinnielsen** [comment]
+1 on this. I'd like to be able to fuzz 50k times in a CI build but I run into the `Too many global rejects` error as well.

**Comment by mds1** [comment]
Currently you can still increase the max number of rejects using [`fuzz_max_global_rejects`](https://book.getfoundry.sh/reference/config.html#fuzz_max_global_rejects)

But if you are hitting that frequently, consider manually bounding your inputs with modulo or changing the input types to your method to a smaller type—a high number of rejects may significantly slow down tests

**Comment by colinnielsen** [comment]
Gotcha, thank you!

**Comment by mds1** [comment]
@onbjerg Any thoughts on which path forward you prefer? We don't use `prop_filter` which is how local filters are created, so my thinking is:
- Remove `fuzz_max_local_rejects`
- Remove `fuzz_max_globa_rejects` (or keep it but add a deprecation warning for backwards compatibility?)
- Add `fuzz_max_test_rejelcts` so it's more clear what it does, and make that the only documented param

**Comment by onbjerg** [comment]
I think that makes sense, although for anyone picking this up it would make sense to specify what `fuzz_max_test_rejects` is actually under the hood. We should also try to get the `ASSUME: Too many rejects` thing back. I think it should be relatively simple, probably just a brain fart on my part

**Comment by 0xYYY** [comment]
<img width="520" alt="Screenshot 2022-09-08 at 00 49 03" src="https://user-images.githubusercontent.com/86655648/188934973-6e49f8dd-8374-4a2d-ad75-03a58102bbf7.png">

As for the error message, does this help?
