### ISSUE TITLE
Consider not passing precompile addresses as fuzz input

### ISSUE THREAD

**Issue by onbjerg** [foundry-rs/foundry#1228]
Some developers find their tests failing because the fuzzer gives them precompile addresses as inputs. We should consider not doing this - is there a legitimate reason to ever have a precompile address as input?

Ref #1159

**Comment by mds1** [comment]
Was chatting with @transmissions11 about this, and don't think it's a good idea for a few reasons:

1. There could be some obscure edge case in your contracts with those addresses, and we don't want to miss that by excluding them.
2. Precompile addresses are valid inputs an attacker can send to your contract, so they should not be excluded from testing.
3. A forge-std helper can wrap `vm.assume` to ensure the address passed from the fuzzer isn't a precompile, without affecting the core fuzzer, so this doesn't really need to be integrated natively anyway.

**Comment by mds1** [comment]
@onbjerg Had this come up recently in a repo. Any objections if I PR in a `noPrecompiles` modifier or function into forge-std and use that to close this issue?

**Comment by mds1** [comment]
> We would need some way to support different flavors I'd assume though. E.g. Optimism's precompiles

Yep, I just created https://github.com/foundry-rs/forge-std/issues/134 which has a suggested approach on how to do that
