### ISSUE TITLE
Consider accepting globs or multiple patterns for --match-contract and --match-test

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#1230]
### Component

Forge

### Describe the feature you would like

> consider globs for --match-contract and --match-test, too, but support passing in multiple of them. Right now using --match-test (and because of that also --debug) for fuzz tests is kind of annoying: --match-test "testSomeFuzz\(uint256\)"

https://github.com/gakonst/foundry/pull/1229#pullrequestreview-935683259

**Comment by mattsse** [comment]
> and would passing multiple globs as a comma-separated arg be sufficient?

I feel like it should, this should be trivial to add since `,` is an illegal char in solidity so we can safely combine multiple options.

happy to mentor if anyone wants to pick this up

**Comment by sakulstra** [comment]
as it's not mentioned here: i guess same feature would be desirable for `--match-path` as well

I'm currently trying to test two files as different locations (so just two relative paths), but i think there's currently not really a way.

**Comment by DaniPopes** [comment]
All the `--match*` flags are already regexes, and the implementation PR has been closed: https://github.com/foundry-rs/foundry/pull/3916
