### ISSUE TITLE
Support for XDG base directory specification

### ISSUE THREAD

**Issue by bingen** [foundry-rs/foundry#1262]
### Component

Foundryup

### Describe the feature you would like

Instead of hardcoding `.foundry` folder in installation script, it would nice to support [XDG specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)

**Comment by onbjerg** [comment]
This is low priority and also a breaking change

**Comment by x86y** [comment]
handled by #4738 ? @bingen

**Comment by bingen** [comment]
Thanks @x86y !

**Comment by Evalir** [comment]
Closing—#4738 handled this!
