### ISSUE TITLE
`vm.expectEmit` -- add parameter specifying the contract that will emit the event

### ISSUE THREAD

**Issue by strollinghome** [foundry-rs/foundry#1264]
### Component

Forge

### Describe the feature you would like

I would like to be able to specify _which_ contract will emit an expected event. For example, if I'm calling `ContractA` which calls `ContractB`, I would like to be able to specify which events will come from `ContractA` and which events will come from `ContractB`.

**Comment by lattejed** [comment]
@strollinghome the above PR should cover your use case. If you have any questions or comments let me know.
