### ISSUE TITLE
Allow `forge install` to specify folder name

### ISSUE THREAD

**Issue by bingen** [foundry-rs/foundry#1267]
### Component

Forge

### Describe the feature you would like

`git submodule` allows to specify the destination folder. It seems that `forge install` gets always the repo name (without the owner). This is sometimes too ambiguous. It would be nice to be able to specify the name of the folder that gets created under  `lib` and pass it to `git submodule add` command.

**Comment by pyk** [comment]
We can use something like this:

```
forge install <alias>@forge:<github org>/<github repo>
```

Where `alias` is the destination folder. It's similar to `npm install`.

**Comment by onbjerg** [comment]
@ is already taken for refs: `<owner>/<repo>@<commit or branch or tag>`

**Comment by pyk** [comment]
@onbjerg ah okay, I've used `=` to set the alias in #1315. please let me know what u think. ty!
