### ISSUE TITLE
cast mktx / sign transactions without broadcasting

### ISSUE THREAD

**Issue by saucepoint** [foundry-rs/foundry#1273]
### Component

Cast

### Describe the feature you would like

It would be nice if `cast` can sign and prepare transactions without broadcasting them.

This will be especially useful for hardware wallets where a signed transaction is created (via hardware device prompts) and the transaction is broadcasted at a later time

### Additional context

`seth mktx` returns a raw hash which can be used with `seth publish` (and `cast publish`)

https://github.com/dapphub/dapptools/tree/master/src/seth#seth-mktx

**Comment by onbjerg** [comment]
Ref https://github.com/gakonst/foundry/issues/1060

**Comment by saucepoint** [comment]
@onbjerg you can assign me the issue, i'll have an honest attempt at it over the next few days

**Comment by sambacha** [comment]
> Ref https://github.com/gakonst/foundry/issues/1060

These are similar issues, except my issue is only asking for cast to provide the transaction details and leave the rest to the external wallet provider.


Fwiw most wallets do not allow you to return the signed transaction. They immediately broadcast it. You will most likely have to rely on eth_sign to get that functionality

**Comment by sambacha** [comment]
> @sambacha I'm not sure I understand #1060 then, I've left a comment.

This is working for cast, but not for forge
