### ISSUE TITLE
support for deno?

### ISSUE THREAD

**Issue by sunw31** [foundry-rs/foundry#1277]
### Component

Other (please describe)

### Describe the feature you would like

deno is next-generation node.js

deno support wasm、rust-ffi、wgpu

maybe 1+1 > 2

**Comment by onbjerg** [comment]
I think this defeats the purpose of eliminating context switching. Leaving this up to @gakonst

**Comment by gakonst** [comment]
@sunw31 what usage do you have in mind for Deno? Doesn't seem like it necessarily fits in the Foundry context scope?
