### ISSUE TITLE
Support for proxy verification?

### ISSUE THREAD

**Issue by pyk** [foundry-rs/foundry#1281]
### Component

Forge

### Describe the feature you would like

Etherscan support proxy verification, do we need to support it via `forge verify-proxy` ?

### Additional context

https://docs.etherscan.io/api-endpoints/contracts#verify-proxy-contract

**Comment by mattsse** [comment]
I see that's another etherscan "action", I believe we don't have that yet in `ethers-etherscan`  so we'd need to add that call first

**Comment by pyk** [comment]
@mattsse Yes I'm planning to add that first on `ethers-etherscan` then imlement it to `forge` if foundry want implement `forge verify-proxy`

**Comment by onbjerg** [comment]
@pyk I'm assigning you to this issue since I gathered from your comment that you are working on it. Please let me know if you are not working on it and I will unassign you :smile:

**Comment by pyk** [comment]
btw guys, when I try to implement this and deploy minimal proxy on arbiscan it get auto-verified (in testnet and mainnet). So I think this feature is unnecessary coz the proxy contract is automatically verified.

I will close this for now.

**Comment by prestwich** [comment]
> btw guys, when I try to implement this and deploy minimal proxy on arbiscan it get auto-verified (in testnet and mainnet). So I think this feature is unnecessary coz the proxy contract is automatically verified.

this happens for well-known proxies, but even slight variations cause automatic detection to fail. A large set of proxies will not be automatically verified but can be verified by API request

**Comment by strumswell** [comment]
I am wondering now why this has been closed as auto-detection seems to fail pretty often. Even ignoring this fact, a manual action for verifying a proxy and its implementation would be super helpful imo. Upstream ethers seems to provide a method for this as well for two months now: https://github.com/gakonst/ethers-rs/blame/28bb3c02a585c52fb56ee5b3c8a359602597187c/ethers-etherscan/src/verify.rs#L182

**Comment by ChiTimesChi** [comment]
Agree with the above, having a `forge verify-proxy` would be really helpful. Right now the workaround solution for me is to use the ehterscan's API directly to trigger the proxy verification (which is not done automatically when both implementation and proxy are verified, at least for OZ's `TransparentUpgradeableProxy`
