### ISSUE TITLE
Use etherscan getsourcecode to pre-flight verification requests to avoid consuming user API limits

### ISSUE THREAD

**Issue by prestwich** [foundry-rs/foundry#1282]
### Component

Forge

### Describe the feature you would like

Contract verification has (documented and anecdotal) stricter API metering than any other etherscan method. We should consider using [getsourcecode](https://docs.etherscan.io/api-endpoints/contracts#get-contract-source-code-for-verified-contract-source-codes) to check whether a contract is already verified before submitting the verification request

**Comment by mattsse** [comment]
good call, I think we should add this as a function in ethers-etherscan

**Comment by xeno097** [comment]
I see that this issue has been open for a while and is assigned to @mattsse, if possible I'd like to work on this. I hope I'm not rude if this was already being worked on.

**Comment by mds1** [comment]
I don't think this is actively being worked on, so reassigned to you @xeno097. 

@mattsse lmk if you have any objections here or any notes on this issue
