### ISSUE TITLE
Show target file first in multi-file verification

### ISSUE THREAD

**Issue by wminshew** [foundry-rs/foundry#1283]
### Component

Forge

### Describe the feature you would like

After successfully verifying a multi-file contract, the target file should be listed first and if possible the remaining file should be listed in decreasing relevance

### Additional context

After successfully verifying a multi-file contract, the target file should be listed first. Currently it looks as if foundry lists the files alphabetically (see [this recent verification on master](https://ropsten.etherscan.io/address/0x7c47728c1920041431800f47f0cdecf186ee1abb#code))

for files 2-n, not sure how they do it but based on my very limited experience hh seemed to do a good job of some kind of reverse relevance sorting (see [older verification w hh](https://etherscan.io/address/0x2ed6c4B5dA6378c7897AC67Ba9e43102Feb694EE#code))

debated whether to label this as a bug or feature, but feature ultimately felt more appropriate

**Comment by mattsse** [comment]
thanks, I think we can reverse engineer this by trying out some variations.
But etherscan knows the contract in question so curious why it doesn't put it first...

**Comment by onbjerg** [comment]
@pyk You're working on this, yeah?

**Comment by pyk** [comment]
@onbjerg yes ser 👍

**Comment by mattsse** [comment]
will be closed by https://github.com/gakonst/ethers-rs/pull/1169

**Comment by onbjerg** [comment]
Closed by merging #1394, should be shipped in the nightly tonight :)
