### ISSUE TITLE
flaky unit tests: cast::finds_block and config::can_extract_config_values

### ISSUE THREAD

**Issue by dcposch** [foundry-rs/foundry#1285]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

64087b5

### What command(s) is the bug in?

cargo test

### Operating System

macOS (amd)

### Describe the bug

I just forked foundry to make my first PR.

The contributor guide is useful. However, on a fresh checkout, two of the unit tests fail:

```
$ cargo --version
cargo 1.59.0 (49d8809dc 2022-02-10)
$ git log -n1 --oneline
64087b5
```

running tests:

```
$ RUST_BACKTRACE=1 cargo test

[...]

failures:
    cast::finds_block
    config::can_extract_config_values

test result: FAILED. 36 passed; 2 failed
```

details below.

**Comment by dcposch** [comment]
### `config::can_extract_config_values` requires `ETHERSCAN_API_KEY` to be unset

see https://github.com/gakonst/foundry/blob/64087b59c0ac9abb4b5e04d8c84e8bab47f4c6c3/cli/tests/it/config.rs#L71

diffing:

```
< etherscan_api_key: Some("..."),
---
> etherscan_api_key: None,
```

**Comment by dcposch** [comment]
### `cast::finds_block` requires `ETH_RPC_URL` to be unset

looks like the test skips by default

https://github.com/gakonst/foundry/blob/64087b59c0ac9abb4b5e04d8c84e8bab47f4c6c3/cli/tests/it/cast.rs#L12-L15

when an RPC endpoint is set, it tries to find a block by timestamp.

i cant get that to work even when running the test manually using the released binaries. is `cast find-block` working?

```
$  cast find-block --rpc-url <valid RPC URL> 1647843609
1 
```

this should print `6574364`, the block number closest to that timestamp.

**Comment by dcposch** [comment]
after removing those two env variables, tests pass. this is not necessarily a bug, but seems fragile.

overall the new developer experience seems good to me.

**Comment by onbjerg** [comment]
Re `cast::finds_block` it actually skips if `ETH_RPC_URL` is *unset*, not if it is set. The intention is that you can run unit tests and integration tests that do not touch an RPC without failing the entire test suite locally

In CI these tests are ran in separate workflow jobs with their own configuration set

**Comment by dcposch** [comment]
@onbjerg yes, i should've phrased it more clearly. if `ETH_RPC_URL` is set, then the unit tests fail bc of an issue in finds_block.

**Comment by onbjerg** [comment]
I don't think this is the case anymore, so I'm closing it. Feel free to ping if this is not the case :)
