### ISSUE TITLE
Event data not decoded anymore

### ISSUE THREAD

**Issue by leonardoalt** [foundry-rs/foundry#1309]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e85435a 2022-04-14T00:06:25.800261822+00:00)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

When I run `forge test -vvvv`, the event data used to be decoded and shown nicely, like in https://github.com/leonardoalt/dl_symb_exec_sol

```
[687208634] SymbExecTest::test_symb_run_unreachable()
    ├─ emit UnreachableBranch(pc: 382)
    ├─ emit UnreachableBranch(pc: 425)
    ├─ emit UnreachableBranch(pc: 468)
    ├─ emit UnreachableBranch(pc: 550)
    └─ ← ()
```

The same command on the same repo now gives me (with solc 0.8.10):
```
[644522094] SymbExecTest::test_symb_run_unreachable() 
    ├─  emit topic 0: 0xd53db689eb18f6139abb6f9e12451eb80c57984e8130bb07952e69ec5dc5f0da
    │           data: 0x000000000000000000000000000000000000000000000000000000000000017e
    ├─  emit topic 0: 0xd53db689eb18f6139abb6f9e12451eb80c57984e8130bb07952e69ec5dc5f0da
    │           data: 0x00000000000000000000000000000000000000000000000000000000000001a9
    ├─  emit topic 0: 0xd53db689eb18f6139abb6f9e12451eb80c57984e8130bb07952e69ec5dc5f0da
    │           data: 0x00000000000000000000000000000000000000000000000000000000000001d4
    ├─  emit topic 0: 0xd53db689eb18f6139abb6f9e12451eb80c57984e8130bb07952e69ec5dc5f0da
    │           data: 0x0000000000000000000000000000000000000000000000000000000000000226
    └─ ← ()
```

Any idea what caused the change?

To reproduce: clone the repo and run `forge test --match symb_run -vvvv`.

**Comment by mattsse** [comment]
@onbjerg I just debugged this a bit, it seems like the event `UnreachableBranch` is not included in the event set of the `CallTraceEncoder`. 

the event is defined outside of the test, in a separate library which probably caused this? not sure yet where we populate the event set

**Comment by onbjerg** [comment]
We should get the deployment traces for the libraries here:

https://github.com/foundry-rs/foundry/blob/64cbc981c358fee7d52b51172a07cc31af20bfd5/forge/src/runner.rs#L214-L226

Then when we do the identify step this is called by the decoder in the test command:

https://github.com/foundry-rs/foundry/blob/64cbc981c358fee7d52b51172a07cc31af20bfd5/evm/src/trace/identifier/local.rs#L27-L48

And that should add the event

**Comment by mattsse** [comment]
it's definitely not included in the set in this case.

**Comment by leonardoalt** [comment]
I also tested this separately in a fresh repo, and if an event was defined inside a contract, the data would be decoded. If the event was in a library, not decoded. I thought then that this had to do with `solc` not exporting the events of a library, but then I remembered that it did use to work in this repo, and I haven't changed the repo.

**Comment by onbjerg** [comment]
@mattsse My best guess is that it's the bytecode matching, similar to the other issue :/

**Comment by mattsse** [comment]
perhaps it has something to do with the fact that the lib is merely a container for the event,

```solidity
library SymbExec {
	event UnreachableBranch(uint pc);
}
```

**Comment by onbjerg** [comment]
@mattsse Ah, right. So no runtime bytecode and we hit

https://github.com/foundry-rs/foundry/blob/64cbc981c358fee7d52b51172a07cc31af20bfd5/evm/src/trace/identifier/local.rs#L55-L58

**Comment by mattsse** [comment]
happens here

https://github.com/foundry-rs/foundry/blob/ad86fae33857f489823cbafd5767b649b3bf6db8/evm/src/trace/decoder.rs#L242

and the event in question is not included in the set

**Comment by onbjerg** [comment]
Yeah, but what I mean is: runtime bytecode of the library is 0, so when the local identifier tries to identify the contract, it says there are no matches since a runtime bytecode of 0 could mean anything. You could have multiple contracts that are just empty containers, so we can't really make a good guess

**Comment by mattsse** [comment]
what if we gather _all_ events of the output?

**Comment by onbjerg** [comment]
Yeah that's what I mean, sorry if I wasn't clear 😅
