### ISSUE TITLE
Test is running out of gas, didn't use to

### ISSUE THREAD

**Issue by leonardoalt** [foundry-rs/foundry#1310]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e85435a 2022-04-14T00:06:25.800261822+00:00)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

In the repo https://github.com/leonardoalt/dl_symb_exec_sol, my tests were running fine before, the README has the log from back then:
```
[PASS] test_symb_run_unreachable() (gas: 687208634)
```

When I run it now with the same compiler version from then (0.8.10), I get:
```
[FAIL. Reason: OutOfGas] test_symb_run_unreachable() (gas: 9223372036854754743)
```

Again no idea what's happening

**Comment by onbjerg** [comment]
Looking at this rn

**Comment by onbjerg** [comment]
Ok, turns out it was because the memory limit for REVM was too small

**Comment by friday-james** [comment]
> Ok, turns out it was because the memory limit for REVM was too small

how can this be fixed?

**Comment by jdbertron** [comment]
Can you explain what REVM is ? Where do I change that ?
