### ISSUE TITLE
Add --etherscan-api-key flag to `forge test` to make the etherscan trace feature more apparent. 

### ISSUE THREAD

**Issue by anticlimactic** [foundry-rs/foundry#1323]
### Component

Forge

### Describe the feature you would like

`forge create` allows one to pass `--etherscan-api-key` in to use the cmd. 

I propose adding the `--etherscan-api-key` to `forge test` to keep the API consistent and make it more obvious as to how to get access to better traces with etherscan (i.e. I can just type `forge test -h` and figure it out vs. having to go through docs etc)

**Comment by mattsse** [comment]
we definitely can add an arg for this but I believe it should already be picked up if the env var is set, @onbjerg ?

**Comment by anticlimactic** [comment]
It does pick it up. I am only proposing this because it took me forever to figure it out (but maybe that's just me).

**Comment by onbjerg** [comment]
Closed in #1349
