### ISSUE TITLE
dead link to foundry book at https://onbjerg.github.io/foundry-book

### ISSUE THREAD

**Issue by SCBuergel** [foundry-rs/foundry#1328]
### Component

Other (please describe)

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

README.md

### Describe the bug

Multiple sections in the [main README.md](https://github.com/transmissions11/foundry/blob/master/README.md), the [forge README.md](https://github.com/transmissions11/foundry/blob/master/forge/README.md) or the [cast README.md](https://github.com/transmissions11/foundry/blob/master/cast/README.md) contain links to the `Foundry Book` hosted at https://onbjerg.github.io/foundry-book which seems to be a dead link.

**Comment by onbjerg** [comment]
You've linked to t11s' README - those links are not present in the README of this repo anymore
