### ISSUE TITLE
File change detection is flaky at times

### ISSUE THREAD

**Issue by transmissions11** [foundry-rs/foundry#1344]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (b3fe652 2022-04-17T23:07:33.947066+00:00)

### What command(s) is the bug in?

forge test

### Operating System

macOS (M1)

### Describe the bug

Sometimes I will change a file and that edit is not picked up by `forge test` which will then not recompile that contract. I have no reliable way to reproduce this, but was asked to open as issue just to track :)

**Comment by onbjerg** [comment]
Ref https://github.com/foundry-rs/foundry/discussions/1299

**Comment by aathan** [comment]
And #1244 -- I think this is the very same problem.

**Comment by onbjerg** [comment]
Consolidated into https://github.com/foundry-rs/foundry/issues/1666
