### ISSUE TITLE
Feature request: ignore_tests and include_tests config options

### ISSUE THREAD

**Issue by transmissions11** [foundry-rs/foundry#1346]
### Component

Forge

### Describe the feature you would like

The ability to set a specific set of tests to include/ignore in a config profile would be very helpful for my workflow, where i often have slow ffi tests that i only want to run every once in a while, and a set of fast unit tests that i want to run every time i type `forge test`

if this was implemented i could have an `ffi` profile that runs ffi tests along with my other tests, and ignore them in the default profile for daily use

**Comment by transmissions11** [comment]
i think these would basically just be config option equivalents of `--no-match-test` and `--match-test`

https://github.com/foundry-rs/foundry/blob/b3fe6527e69bd674c8ca287a97107d6c6aa3209b/cli/src/cmd/forge/test.rs#L45-L50

**Comment by onbjerg** [comment]
Ref #1123 (not entirely the same, but similar use case)

**Comment by lattejed** [comment]
I'll take a look at this 👋

**Comment by lattejed** [comment]
So I've copied all of the matching flags from `test` to the `Config` file, swapping kebab for snake case, e.g., `--match-test` is `match_test` in `foundry.toml`.

Profiles work so you can store different matching setups in the config file and select them with `FOUNDRY_PROFILE`

If *both* config entry and flag are present, the flag takes precedence. 

The full list:

```
match_test
no_match_test
match_contract
no_match_contract
match_path
no_match_path
```
