### ISSUE TITLE
Config profile

### ISSUE THREAD

**Issue by wiasliaw** [foundry-rs/foundry#1347]
### Component

Other (please describe)

### Describe the feature you would like

- Currently, cli use default config profile to load config. Can it pass argument to load other `.toml` or merge with `foundry.toml`? or to load `.env` in root folder? Using `export RPC=""` is a little bit annoying.

- Usage example:
  - separate sensitive config with `foundry.toml`

```toml
# env.toml

ETH_RPC_URL="https://eth-goerli.alchemyapi.io/v2/XXXXXX"
```

```sh
# example for forking
forge test --profile env.toml
```

**Comment by mattsse** [comment]
there should exist a `--config-path <path>` option

**Comment by wiasliaw** [comment]
Oh, I found it. Some of the cli have that option. Can `verify-contract` and `verify-check` support, too?

**Comment by mattsse** [comment]
> Oh, I found it. Some of the cli have that option. Can `verify-contract` and `verify-check` support, too?

good idea, tracking this in new issue
