### ISSUE TITLE
dyld[48338]: symbol not found in flat namespace '_libusb_claim_interface'

### ISSUE THREAD

**Issue by 0xYao** [foundry-rs/foundry#1352]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (b3fe652 2022-04-18T00:12:45.381840+00:00)

### What command(s) is the bug in?

./target/debug/forge --version

### Operating System

macOS (M1)

### Describe the bug

After building the source code using `cargo build`, I ran `./target/debug/forge --version` to check if the code compiles properly, but it returns `dyld[48338]: symbol not found in flat namespace '_libusb_claim_interface'` as seen in the title.

Note: I have `libusb` installed already.

**Comment by onbjerg** [comment]
How did you install libusb? My current thinking is that maybe you build Foundry for a specific target platform, but your libusb is for another target platform, if that makes sense. Do you have Rosetta installed?

Maybe someone with an M1 can help debug here (cc @gakonst?), I don't have an M1 myself

**Comment by gakonst** [comment]
`brew install libusb` typically works here. can you try `brew uninstall libusb` and then re-installing? maybe related https://stackoverflow.com/a/51384999

**Comment by 0xYao** [comment]
> How did you install libusb? My current thinking is that maybe you build Foundry for a specific target platform, but your libusb is for another target platform, if that makes sense. Do you have Rosetta installed?
> 
> Maybe someone with an M1 can help debug here (cc @gakonst?), I don't have an M1 myself

I thought about that too. `cargo` is the arm64 version and I compiled the source with `cargo build` so the artifacts should be arm64 too. `libusb` is also the arm64 version so I don't think there is a platform mismatch here.

**Comment by 0xYao** [comment]
Yes, I have Rosetta installed.

**Comment by 0xYao** [comment]
> How did you install libusb? My current thinking is that maybe you build Foundry for a specific target platform, but your libusb is for another target platform, if that makes sense. Do you have Rosetta installed?
> 
> Maybe someone with an M1 can help debug here (cc @gakonst?), I don't have an M1 myself

Good call, I checked again today. Turns out I have `libusb` in `/usr/local/Cellar`, so brew installed that for x86_64. I resolved the issue with the following commands: 

```bash
# only do this if you are certain you don't have any important libraries there ❗
rm -rf /usr/local/Cellar
# in the foundry root folder
cargo clean
cargo build
./target/debug/forge --version
# it should now output something like forge 0.2.0 (3c3221e 2022-04-18T20:51:02.159301+00:00)
```
