### ISSUE TITLE
expectRevert not working as expected

### ISSUE THREAD

**Issue by 0xAlcibiades** [foundry-rs/foundry#1360]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (b3fe652 2022-04-18T00:12:45.381840+00:00)

### What command(s) is the bug in?

forge test

### Operating System

macOS (M1)

### Describe the bug

See this test: 

```solidity
    function testSetFeeTo() public {
        assertEq(engine.feeTo(), FEE_TO);
        VM.expectRevert();
        engine.setFeeTo(ALICE);
    }
```

From here:
https://github.com/Alcibiades-Capital/valorem-options-contracts/blob/tabula_rasa/src/test/OptionSettlement.t.sol#L146

Produces the failure output:
```
[11837] OptionSettlementTest::testSetFeeTo()
    ├─ [2383] OptionSettlementEngine::feeTo() [staticcall]
    │   └─ ← 0x36273803306a3c22bc848f8db761e974697ece0d
    ├─ [0] VM::expectRevert()
    │   └─ ← ()
    ├─ [736] OptionSettlementEngine::setFeeTo(0x000000000000000000000000000000000000000a)
    │   └─ ← "AccessControlViolation(0xb4c79dab8f259c7aee6e5b2aa729821864227e84, 0x36273803306a3c22bc848f8db761e974697ece0d)"
    └─ ← "AccessControlViolation(0xb4c79dab8f259c7aee6e5b2aa729821864227e84, 0x36273803306a3c22bc848f8db761e974697ece0d)"
```
    
When the revert should be expected. The same happens when using the `bytes4` selector.

**Comment by 0xAlcibiades** [comment]
Discovered on; https://github.com/Alcibiades-Capital/valorem-options-contracts/pull/32

Reproduced more simply on; https://github.com/Alcibiades-Capital/valorem-options-contracts/pull/33

**Comment by onbjerg** [comment]
`expectRevert` with no parameters expects a `revert()` (i.e. a revert with no message). You should expect the `AccessControlViolation` error. See the [book](https://book.getfoundry.sh/cheatcodes/expect-revert.html) for examples and docs, more specifically, you probably want something like the example in the book:

```solidity
cheats.expectRevert(
    abi.encodeWithSelector(MyContract.CustomError.selector, 1, 2)
);
```

**Comment by 0xAlcibiades** [comment]
```    function testSetFeeTo() public {
        assertEq(engine.feeTo(), FEE_TO);
        vm.expectRevert(abi.encodeWithSelector(IOptionSettlementEngine.AccessControlViolation.selector, address(this), FEE_TO));
        engine.setFeeTo(ALICE);
        vm.startPrank(FEE_TO);
        engine.setFeeTo(ALICE);
        vm.stopPrank();
        assertEq(engine.feeTo(), ALICE);
    }``` - yup, that worked.

**Comment by 0xAlcibiades** [comment]
The bad assumption here was that a blank revert would catch any revert, but it seems like there needs to be an exact match with the memory segment returned.
