### ISSUE TITLE
install `foundry-rs/forge-std` when run `forge init`

### ISSUE THREAD

**Issue by wp-lai** [foundry-rs/foundry#1364]
### Component

Forge

### Describe the feature you would like

Since `forge-std` provides more functionality beyond `ds-test`, `foundry-rs/forge-std` can replace `dapphub/ds-test` as the default library installed when `forge init`.

**Comment by onbjerg** [comment]
Thoughts on this @gakonst @brockelmore @mattsse? I don't mind either way, seems like it makes sense considering we are transitioning the book to be forge-std-first

**Comment by gakonst** [comment]
The main concern was that it would make `forge init` not offline-compatible, and it wasn't clear if we want to bundle forge-std inside the binary.

**Comment by onbjerg** [comment]
Currently forge init is offline compatible in the sense that ds-test is just not installed if you are offline (`--offline`), so the change would just be to replicate that for forge-std instead

**Comment by gakonst** [comment]
Ah, I like that. Let's go with it.
