### ISSUE TITLE
fuzzing: test failed with stdError.arithmeticError

### ISSUE THREAD

**Issue by harryranakl** [foundry-rs/foundry#1374]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (712664c 2022-04-15T03:36:46.860545+00:00)

### What command(s) is the bug in?

forge test

### Operating System

macOS (amd)

### Describe the bug

```
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.0;

import {DSTest} from "@ds-test/test.sol";
import {Test, stdError} from "@forge-std/Test.sol";

import {ERC20Mock} from "../mocks/ERC20Mock.sol";
import {console} from "../utils/Console.sol";


contract ERC20Test is DSTest, Test {
    ERC20Mock m20;

    address initialAccount;

    function setUp() public {
        initialAccount = msg.sender;
        m20 = new ERC20Mock('ERC20MOCKBENCH','E20B', initialAccount, 1e18);
    }

    function testMintFuzz(uint256 t) public {
        if(t < m20.totalSupply()){
            m20.mint(msg.sender, t);
            m20.burn(msg.sender, t);
            assertLt(t,m20.totalSupply());
        } else {
            vm.expectRevert(stdError.arithmeticError);
            m20.mint(msg.sender, t);

        }
    }

    function testMintFail() public {
        uint256 t = 115792089237316195423570985008687907853269984665640564039456584007913129639936;
        vm.expectRevert(stdError.arithmeticError);
        m20.mint(msg.sender, t);
    }
}
```

---------------
testMintFail() -  passed  
testMintFuzz()-  failed 
Failed tests:
[FAIL. Reason: Call did not revert as expected. Counterexample: calldata=0xe49b37830000000000000000000000000000000000000000000000000de0b6b3a7640000, args=[1000000000000000000]] testMintFuzz(uint256) (runs: 25, μ: 27971, ~: 27971)

**Comment by onbjerg** [comment]
Sorry, can you add additional context? The arithmetic error is for overflows, which I don't think this test would encounter?

**Comment by harryranakl** [comment]
both tests show [FAIL. Reason: Arithmetic over/underflow], that why used vm.expectRevert(stdError.arithmeticError) to pass the tests, but only testMintFail passed and testMintFuzz failed.
probably you can test the above contract to see it happening

**Comment by onbjerg** [comment]
Can you provide the full project somewhere? I don't have your mock files etc.

Also, you can still overflow here:

```
            m20.mint(msg.sender, t);
            m20.burn(msg.sender, t);
            assertLt(t,m20.totalSupply());
```

If `t` is `uint256` your total supply will overflow since it starts at `1e18`(?)

**Comment by harryranakl** [comment]
repo link : https://github.com/harryranakl/erc20-benchmarks

**Comment by harryranakl** [comment]
got it thanks, suppose to check against 1e18

**Comment by harryranakl** [comment]
modified version: pass
```
    function testMintFuzz(uint256 t) public {
        if(t > type(uint256).max - 1e18) {
            // totalSupply would overflow here
            vm.expectRevert(stdError.arithmeticError);
            m20.mint(msg.sender, t);
            return;
        } 
        m20.mint(msg.sender, t);
        assertLt(t,m20.totalSupply());
    }
```
