### ISSUE TITLE
`--extra-output-files abi` does not produce an ABI file

### ISSUE THREAD

**Issue by onbjerg** [foundry-rs/foundry#1380]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (321960f 2022-04-21T00:07:54.007830262+00:00)

### What command(s) is the bug in?

forge build

### Operating System

Linux

### Describe the bug

Running `forge build --extra-output-files abi` succeeds, but does not produce an extra file with the ABI in the `out` folder.

This behavior is consistent even if `forge clean` is run before `forge build`.

Ref #1272

**Comment by jeffward01** [comment]
Currently I am experiencing this same issue on Windows 11 Pro

**Comment by holic** [comment]
> Currently I am experiencing this same issue on Windows 11 Pro

Maybe related to this? https://github.com/foundry-rs/foundry/issues/6241
