### ISSUE TITLE
forge fails to verify multi-file contracts on windows

### ISSUE THREAD

**Issue by except** [foundry-rs/foundry#1382]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What command(s) is the bug in?

forge verify-contract

### Operating System

Windows

### Describe the bug

Likely an issue with the way Windows handles paths compared to Unix platforms.

**Comment by onbjerg** [comment]
I've verified this behavior, but I'm unsure where the bug is. I suspect it might be in paths we submit to Etherscan in the Solidity standard input description

**Comment by Bavragor** [comment]
Yes seems like verifying multi file contracts is still not possible on Windows. Flattening the contract helps though.

**Comment by mattsse** [comment]
any idea what we're missing?

maybe that's a metadata issue? we just switched to base-path and only relative paths and fixed another windows bug, so just to be sure verifying doesn't work with current nightly on windows?

**Comment by except** [comment]
> Yes seems like verifying multi file contracts is still not possible on Windows. Flattening the contract helps though.

The fix worked for me though, maybe you haven't updated to the latest version?

**Comment by mattsse** [comment]
thanks for letting us know @except 

optimistically closing this, but please let us know if you're still having issues @Bavragor
