### ISSUE TITLE
Add submodule install path option for `forge update`

### ISSUE THREAD

**Issue by zoey-t** [foundry-rs/foundry#1391]
### Component

Forge

### Describe the feature you would like

Hi
It would be nice if I can specify the installation path for `forge update`.  Right now it only installs packages to `lib` folder. I can only specify the path using the git command. Forge is not available to do so yet.

**Comment by pyk** [comment]
Hi @zoey-t, Foundry have option to specify alias now as per https://github.com/foundry-rs/foundry/pull/1315

You can do something like this:

```
forgedev install soulmate=Rari-Capital/solmate
```

The dependency will installed to `lib/soulmate`. Is this cover your usecase?

**Comment by zoey-t** [comment]
> 

Hi Thanks for the quick reponse! What about folders other than `lib`? For example, I want to download it under `contract` folder

**Comment by onbjerg** [comment]
Then you'd need to configure that in `foundry.toml` by setting `libs`

**Comment by cartman-dev** [comment]
@onbjerg In forge 0.2.0 (d5bb4c0 2022-05-07T00:03:45.414698214+00:00), I am not able to change the installation folder for libs.

foundry.toml
```
[default]
src = 'contracts'
test = 'forge'
out = 'artifacts'
libs = ['forgelib']
remappings = [
    '@chainlink/=node_modules/@chainlink/',
    '@openzeppelin-3/=node_modules/@openzeppelin-3/',
    '@openzeppelin/=node_modules/@openzeppelin/',
]
```

console
```
❯ forge install foundry-rs/forge-std
Installing forge-std in "./lib/forge-std" (url: Some("https://github.com/foundry-rs/forge-std"), tag: None)
    Installed forge-std
```

Expected result: forge-std installed in `forgelib` folder.
Actual result: forge-std installed in  `lib` folder.
