### ISSUE TITLE
Bad import error message

### ISSUE THREAD

**Issue by aathan** [foundry-rs/foundry#1404]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (64087b5 2022-04-13T00:10:42.429318924+00:00)

### What command(s) is the bug in?

forge build

### Operating System

Linux

### Describe the bug

```
$ forge build
[⠊] Compiling...
[⠒] Unable to resolve import: "./SomeFile.sol"
import "./Whitelist.sol" with remappings:
```

is the result of

```
import "./SomeFile.sol"
import "./Whitelist.sol";
```

No information about which file contains the malformed import statement!

**Comment by mattsse** [comment]
can you try with the latest nightly?
what does your workspace look like: `tree .`

**Comment by gakonst** [comment]
Can you also please share a minimal repo that reproduces it, if latest nightly doesn't solve it @aathan ?

**Comment by aathan** [comment]
I'm in crunch mode so can't really devote a ton of time to building simple test cases. Just write a file that has two import statements where the first one is missing a semicolon with a pragma 0.8.13. The new version emits:

```
forge test -vvv --fork-url http://127.0.0.1:8545/ -m testRewarder
[⠊] Compiling...
Error:
   0: Failed to resolve file: ".../lib/ds-test/src/test.sol"
      import "forge-std/Vm.sol": No such file or directory (os error 2).
       Check configured remappings.
 ```
 
 this tells me what couldn't get imported and the import statement, but again, no reference to the file doing the actual importing.
 
Thanks for all your hard work on Foundry by the way.

**Comment by aathan** [comment]
I'm in crunch mode so can't really devote a ton of time to building simple test cases. Just write a file that has two import statements where the first one is missing a semicolon with a pragma 0.8.13. The new version emits:

forge test -vvv --fork-url http://127.0.0.1:8545/ -m testSomething
[⠊] Compiling...
Error:
   0: Failed to resolve file: ".../lib/ds-test/src/test.sol"
      import "forge-std/Vm.sol": No such file or directory (os error 2).
       Check configured remappings.
this tells me what couldn't get imported and the import statement, but again, no reference to the file doing the actual importing.

Thanks for all your hard work on Foundry by the way.

**Comment by aathan** [comment]
I'm leaving this here because it's in the general class of "show more information about what file's failing", though I think you're going to ask me to open a distinct issue on this but:

```
[⠢] Compiling...
[⠃] Compiling 1 files with 0.8.13
[⠒] Solc finished in 511.30ms
Compiler run successful

Running 1 test for src/test/SomethingTest.sol:SomethingTest
[FAIL. Reason: Division or modulo by 0] testSomething() (gas: 25094)
Traces:
  [25094] SomethingTest::testSomething()
    └─ ← "Division or modulo by 0"
```
 
 Here this trace is actually caused by a division by zero in a library that the test is `using for...` a storage variable in the test class itself. Strangely, the tree does not show the call *into* the internal function that caused the div 0 error. Rather, it shows it as if it's occurring directly in the test function.
 
I.e. SomethingTest.sol:

```
contract Foo is DSTest {
  using Library for X;
  X x;
  
   function testSomething() { ... x.causeDivZero(); }
 }
 ```
 
 The Library implements causeDivZero() internal function.

**Comment by aathan** [comment]
Similarly, does the solc compiler really not show the name of the function that can't be declared view? I don't have time right now to figure out all the necessary solc flags to map all the imports to directories etc to run it raw...

```
   0: Compiler run failed
      error[8961]: TypeError: Function cannot be declared as view because this expression (potentially) modifies the state.
         --> /home/.../foo.sol:584:49:
          |
      584 |             _...() :
          |                                                 ^^^^^^^^^^^^^^^^^^^^
 ```

**Comment by gakonst** [comment]
> Here this trace is actually caused by a division by zero in a library that the test is using for... a storage variable in the test class itself. Strangely, the tree does not show the call into the internal function that caused the div 0 error. Rather, it shows it as if it's occurring directly in the test function.

Yeah this makes sense, traces only work with external calls, whereas an internal library function is inlined and does not appear in traces.

**Comment by aathan** [comment]
Is it literally inlined? I ask because the Solidity docs imply a JUMP to a copy of the library code. I guess the optimizer may end up inlining that? At some point I'll dive into the implementation of the simulated EVM etc but what I'm leading to is: Who's generating the trace data from which that tree is built, and is there no opportunity to resolve the internal calls?

**Comment by mattsse** [comment]
this `".../lib/ds-test/src/test.sol"` indicates that there's one `.` too many, so `No such file or directory (os error 2).` is correct

I think we can makes this error more descriptive ref #275

**Comment by aathan** [comment]
The ... is my removal of doxing information I should have put something like <private directory names not for the internet> there.

**Comment by onbjerg** [comment]
The issue with resolving internal calls is that it requires a lot of information that may be inherently unreliable after the optimizer is applied. Some functions are inlined, some are merged, some are semi-merged and some jumps do not correspond to actual function calls (e.g. the signature matching routine at the start of the contract). The traces are only generated for creates/calls/delegatecalls/staticcalls and callcode.

**Comment by onbjerg** [comment]
Closing as per above, let us know if this is still an issue for you :smile:
