### ISSUE TITLE
forge init fails in Docker container due to lack of Git

### ISSUE THREAD

**Issue by kacperzuk** [foundry-rs/foundry#1411]
### Component

Forge, Other (please describe)

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (5490c4a 2022-04-25T10:46:12.972666458+00:00) 

### What command(s) is the bug in?

forge init

### Operating System

Linux

### Describe the bug

I've built foundry Docker image from `master` branch (5490c4a0fef0a83827e4d5642730ea9ceff641b2) using:
```
docker build -t foundry:latest .
```

However, this image fails on `forge init`:
```
> docker run foundry "forge init --no-git /test"
Initializing /test...
Installing ds-test in "/test/lib/ds-test", (url: https://github.com/dapphub/ds-test, tag: None)
Error:
   0: No such file or directory (os error 2)

Location:
   cli/src/cmd/forge/install.rs:107

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

This is due to `forge init` trying to run `git`, which is missing in the image. After this patch to Dockerfile it works correctly:
```
--- Dockerfile  2022-04-25 13:30:16.624326460 +0200
+++ Dockerfile-git      2022-04-25 13:30:45.170368985 +0200
@@ -15,10 +15,10 @@
 ENV GLIBC_KEY_FILE=/etc/apk/keys/sgerrand.rsa.pub
 ENV GLIBC_RELEASE=https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.35-r0/glibc-2.35-r0.apk

-RUN apk add linux-headers gcompat
+RUN apk add linux-headers gcompat git
 RUN wget -q -O ${GLIBC_KEY_FILE} ${GLIBC_KEY} \
     && wget -O glibc.apk ${GLIBC_RELEASE} \
     && apk add glibc.apk --force
```

This patch still doesn't allow running init without `--no-git` due to unconfigured git, but I think this isn't something that is expected to work:
```
Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'unknown@7a491a9c0095.(none)')
```

Is git not installed on purpose to reduce image size or is it something that's considered a bug? If it's on purpose, would it be a good idea to add a note about this to https://book.getfoundry.sh/tutorials/foundry-docker.html ? In either case I'd be happy to submit a PR.

**Comment by gakonst** [comment]
I think packaging git is fine personally, so supportive of a PR for that, should be simple. We probably just forgot

**Comment by dmfxyz** [comment]
I lean a bit the other way and think that git should remain excluded from the base image build.  I don't see a use-case except when users should already be extending the image. For example:
```
docker run foundry "forge init --no-git /test"
```
unless I'm missing something, all this would do is init a repo and exit the docker container immediately. 

Preferred usage pattern for developing within Docker would be one of two things:
- Mount the local filesystem to Docker
- Build a development image off of the base image and install any dependencies needed

If you look at, say, the `rust:alpine` or `python:alpine` images, they do not ship with git. I don't lean too strongly, but would advise against. Happy to add documentation to the book page.

**Comment by kacperzuk** [comment]
@dmfxyz unfortunately `forge init --no-git /test` fails, as it still uses `git ls-remote` when installing dependencies:

```
> docker run foundry "forge init --no-git /test"
Initializing /test...
Installing ds-test in "/test/lib/ds-test", (url: https://github.com/dapphub/ds-test, tag: None)
Error:
   0: No such file or directory (os error 2)

Location:
   cli/src/cmd/forge/install.rs:107

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

Personally I agree that users should handle it themselves by building a new development image, it just makes sense to mention in the docs that git is required and not provided in ghcr.io/foundry-rs/foundry, given that the error message itself doesn't mention git.

**Comment by dmfxyz** [comment]
@kacperzuk cool, agree we should mention it in the book since the error is very nebulous. Thanks for calling it out. 

Do you want to make the PR into the foundry book?

**Comment by dmfxyz** [comment]
Here: https://github.com/foundry-rs/book/pull/245, I think we can close once this is merged.
