### ISSUE TITLE
Remappings broken

### ISSUE THREAD

**Issue by Jinchans** [foundry-rs/foundry#1417]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (fd3be14 2022-03-25T12:55:03.072762500+00:00)

### What command(s) is the bug in?

remappings = ['@openzeppelin/=lib/openzeppelin-contracts/']

### Describe the bug

remappings = ['@openzeppelin/=lib/openzeppelin-contracts/']

error:

Desktop\foundry-solidity\lib/openzeppelin-contracts/contract/token/ERC20/IERC20.sol": The system cannot find the path specified. (os error 3).
       Check configured remappings.

**Comment by mattsse** [comment]
thanks,
paths are hard, and it looks like you're on windows.

solc expects unix style paths, but I think we need to be a bit smarter when combining the remappings with the actual project path to find the file on windows.

**Comment by Jinchans** [comment]
yeah I got it now all good just a guide for pathing would be nice

**Comment by mattsse** [comment]
> yeah I got it now all good just a guide for pathing would be nice

good idea,
what does your remapping look like now, simply `\` instead of `/`?
