### ISSUE TITLE
Testing forge. Artifacts not found.

### ISSUE THREAD

**Issue by bitcoinmeetups** [foundry-rs/foundry#1419]
Hello,

I'm BM. A very nice and polite guy.

I started testing foundry forge today. Looks interesting.

Issue:

I built the contract. Contract passes. Get json files in out directory. However when I try to deploy I get "no artifact found" error each time.

In general, what is best practice for quickly building and deploying a test contract? I can provide more info and output but maybe you have a link to a helloworld build and deploy in the book somewhere. I didn't see it though after reading for an hour or two.

**Comment by mattsse** [comment]
thanks for raising this,

how do you run `forge create`? it expects the path to contract as `src/FileName.sol:ContractName`?

could you check if this matches an artifact compiled with `forge build`?

**Comment by bitcoinmeetups** [comment]
This is how I do it at the moment (yes I have read that documentation but I still can't get it to connect to the artifacts).

1. Make a new directory called forgetest3
2. Init it with forge init. However, then I get an almost empty contract in the src folder so I delete it.
3. Copy one of my previous flattened contracts called TEST2_flatten.sol to forgetest3/src
4. Input forge build
5. Output:
Compiler run successful (with warnings)
warning[2462]: Warning: Visibility for constructor is ignored. If you want the contract to be non-deployable, making it "abstract" is sufficient.
    --> /home/pi/web3/f3/src/TEST2_flatten.sol:1735:5:
     |
1735 |     constructor() public
     |     ^ (Relevant source part starts here and spans across multiple lines).

6. Now I have a corresponding folder in the out directory called TEST2_flatten.sol. That directory is full of json files, presumably the artifacts.
7. Input: forge create --rpc-url https://polygon-mainnet.g.alchemy.com/v2/123 --private-key 123 src/TEST2_flatten.sol:TEST2_flatten
8. Output: No files changed, compilation skipped
Error:
   0: No artifact found for `/home/pi/web3/f3/src/TEST2_flatten.sol:TEST2_flatten`

Location:
   cli/src/cmd/utils.rs:81

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

**Comment by mattsse** [comment]
thanks, this is helpful. what's the name of the contract you want to deploy?
Could you perhaps share your cache file? (you can remove the bytecode if you want)

**Comment by bitcoinmeetups** [comment]
Source of the TEST2_flatten.sol contract (as far as I remember this template used to work last time I tried to build and deploy it with the goweb/web3 tool.

https://github.com/bitcoinmeetups/gituploads/blob/master/TEST2_flatten.sol

**Comment by bitcoinmeetups** [comment]
Here is the cache file:

https://github.com/bitcoinmeetups/gituploads/blob/master/solidity-files-cache.json

**Comment by mattsse** [comment]
oh I see the issue,
there's now `TEST2_flatten` contract in the solidity file.
`forge create` expects `<solidity file>:<contract name>` because there can be multiple contracts in a single file, like your `TEST2_flatten.sol`

**Comment by onbjerg** [comment]
Closing because this is solved

As @mattsse pointed out above, you must specify the contract via: `<path>:<contract name>`. For example, if you wanted to deploy the `CAT` contract in your flattened file, you would specify `./src/TEST2_flatten.sol:CAT` :smile:
