### ISSUE TITLE
Add string formatting to console.log

### ISSUE THREAD

**Issue by borxes** [foundry-rs/foundry#1429]
### Component

Forge

### Describe the feature you would like

Hardhat supports formatting in its console.log implementation.
E.g. `console.log("Trying to send %s tokens to %s", amount, to);`

Formatting makes debug prints more readable and convenient.

**Comment by Genysys** [comment]
I'd like to take this up

**Comment by onbjerg** [comment]
Status on this @Genysys? :smile:

**Comment by mattsse** [comment]
I believe we chatted about this briefly,

a bare-bones approach would be to regex + replace `%s` placeholders with params, that's what hardhat does.

**Comment by onbjerg** [comment]
Unassigned you @Genysys since I haven't heard back from you, but please let me know if you are still interested in taking a stab at this and I will reassign you! :smile:
