### ISSUE TITLE
Default chain ID

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#1431]
### Component

Forge, Cast, Other (please describe)

### Describe the feature you would like

currently `forge` use 99 as default chain ID (inherited from dapptools), geth --dev and ganache use `1337`, hardhat uses `31337`

#1037 also currently uses `1337`.

I think we should unify this for forge + anvil and not introduce a completely new chain, this leaves us with 3 options
- 1337
- 99
- 31337

1337 is already marked as `Dev` chain in the `Chain` enum type.

**Comment by gakonst** [comment]
Let's go with 1337 given it's the most supported one? I don't really worry about replay attacks

**Comment by mds1** [comment]
I'd suggest using 31337 for the following reasons:
- There are many projects migrating from hardhat to foundry, and using 31337 will make that much easier. From what I can tell, 31337 would simplify things for a larget subset of foundry users than 99 or 1337.
- I don't know of many projects that use forge which also use ganache or `geth --dev`, i.e. I'm not sure what compatibility benefits we get from chain ID 1337.
- Using 99 is only useful for backwards compatibility with dapptools, but dapptools is no longer under active development so I don't think this should be weighed to heavily.

**Comment by gakonst** [comment]
> There are many projects migrating from hardhat to foundry, or using both simultaneously, and using 31337 will make that much easier. From what I can tell, 31337 would simplify things for a larger subset of foundry users than 99 or 1337.

this is a great point - more convincing than mine. yeah no prob that works better
