### ISSUE TITLE
Help VSCode resolve imports when forge project is inside a monorepo

### ISSUE THREAD

**Issue by holic** [foundry-rs/foundry#1438]
### Component

Other (please describe)

### Describe the feature you would like

This may be more of a VSCode Solidity plugin issue than foundry, but @gakonst asked me to report it so here I am! See also https://github.com/juanfranblanco/vscode-solidity/issues/335

I have a monorepo that looks something like
```
.vscode/
packages/
    app/
        ...
    contracts/
        lib/
        src/
        foundry.toml
        remappings.txt
```
where `packages/contracts/` is a forge project.

If I open VSCode to that directory, my Solidity imports resolve just fine. If I open VSCode to the monorepo/workspace root, VSCode can't find the Solidity imports, even though I have `remappings.txt` set up and Solidity plugin pointing at it.

![image](https://user-images.githubusercontent.com/508855/165661022-72e71350-83e4-46b0-9a85-65598e163f7a.png)

I can set up a repo to reproduce this issue if helpful!

**Comment by onbjerg** [comment]
It should work if you follow the instructions here: https://github.com/juanfranblanco/vscode-solidity#openzeppelin-default, i.e. try setting:

```json
"solidity.packageDefaultDependenciesDirectory": "packages/app/lib"
```

In the config for the VSCode plugin

**Comment by holic** [comment]
To clarify, did you mean `packages/contracts/lib`?

**Comment by onbjerg** [comment]
Yes

**Comment by holic** [comment]
All good! I had tried that (and variations on that) but no luck finding one that would work.

The error message is a little weird, not sure if this is helpful:
<img width="710" alt="image" src="https://user-images.githubusercontent.com/508855/165662761-fe487694-afac-4935-8f91-7ab730c3da15.png">

**Comment by onbjerg** [comment]
Try moving the remappings.txt to the root of your project - at least that's what their README says you should

**Comment by holic** [comment]
> Try moving the remappings.txt to the root of your project - at least that's what their README says you should

That does seem to do the trick in VSCode, but then forge is unhappy. And having the same file in two spots doesn't seem great. Is it possible to specify the path to the remappings file in `foundry.toml`? I didn't see anything in Foundry Book.

**Comment by onbjerg** [comment]
You can move the foundry.toml up to the root (remember to specify src, out and lib), we don't support specifying the remappings file name in foundry.toml, only the remappings directly.

We should work to get some better Foundry support in the VSCode extension, or at least some accomodations in place in the extension that would allow better integration

**Comment by holic** [comment]
> My best guess for why this is happening is because they are not resolving remappings with respect to where the remappings file is located

Makes sense! Seems like maybe not a foundry thing but more of a Solidity VSCode thing after all?

**Comment by holic** [comment]
Another option is just to write imports as local ones, e.g. 
```solidity
import "../lib/openzeppelin-contracts/contracts/access/Ownable.sol";
```

Any downsides to this?

**Comment by gakonst** [comment]
While these solutions 'work' I think it's best if we resolve remappings properly in VS Code, so would recommend we try fixing in the plugin perhaps?

**Comment by onbjerg** [comment]
Closing since moving remappings.txt and foundry.toml to root worked and better support is tracked in https://github.com/juanfranblanco/vscode-solidity/issues/335
