### ISSUE TITLE
cast interface doesn't generate interface from build artifact

### ISSUE THREAD

**Issue by SusheendharVijay** [foundry-rs/foundry#1439]
### Component

Cast

### Describe the feature you would like

Right now `cast interface` only works on abi's from etherscan or abi files. 
`cast interface "./out/Contract.sol/Contract.json"` will give an error.

 It would be nice if it could also generate interfaces from the forge build artifacts (`out/Contract.sol/Contract.json`), where we already have the abi for the compiled contracts. 

### Additional context

Can just use the abi from artifact file. 
Artifact file: 
![image](https://user-images.githubusercontent.com/22870103/165692321-7f08ba66-fcfd-4c97-93b0-e386c24eccf1.png)

After a quick look at the code, If I understand correctly we are deserializing to a `Abi` type only, so attempting to deserialize to a type consistent with artifacts in case the first attempt fails would solve the issue.

https://github.com/foundry-rs/foundry/blob/14ee6c67921e942f978b3da80f4b6049612ee64a/cast/src/lib.rs#L664-L675

wdyt @onbjerg , @mattsse , @odyslam, is it worth adding?

**Comment by mds1** [comment]
Note that you can workaround this with `cast interface <(cat ./out/Contract.sol/Contract.json | jq .abi)`. A more generalized version is `cast interface <(forge inspect Contract abi)` which will generate the artifacts if not present. But I agree not having to use a workaround like this would be preferable.

(@gakonst using this as the issue you [requested](https://twitter.com/gakonst/status/1519610516813066241), thanks @SusheendharVijay for beating me too it 🙂)

**Comment by onbjerg** [comment]
Makes sense to me that we would also support Forge-style artifacts 👍

**Comment by onbjerg** [comment]
Closed in #1451
