### ISSUE TITLE
Argument --optimize-runs is not recognized

### ISSUE THREAD

**Issue by IntelMin** [foundry-rs/foundry#1443]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What command(s) is the bug in?

forge test --optimize --optimize-runs 1000000 -v

### Describe the bug

Today, I have experienced an issue while running `forge test` by Github ci actions.

It tried to run the following command:

```
forge test --optimize --optimize-runs 1000000 -v
```

And the error occurs:

```
forge clean && forge test --optimize --optimize-runs [10](https://github.com/my-project/my-repo/runs/6214574813?check_suite_focus=true#step:4:10)00000 -v
error: Found argument '--optimize-runs' which wasn't expected, or isn't valid in this context

	Did you mean '--optimizer-runs'?

	If you tried to supply `--optimize-runs` as a value rather than a flag, use `-- --optimize-runs`

USAGE:
    forge test --optimize --optimizer-runs <OPTIMIZER_RUNS>

For more information try --help
make: *** [Makefile:10: test] Error 2
Error: Process completed with exit code 2.
```

Argument `--optimize-runs` was changed to `--optimizer-runs` on the recent commit?

**Comment by mattsse** [comment]
correct, this was changed to `--optimizer-runs` which is consistent across all tools now

**Comment by IntelMin** [comment]
What is the best way to update `forge` to that latest version on my local cli?
