### ISSUE TITLE
Unable to send transactions using `cast send`on Arbitrum One and Arbitrum Testnet

### ISSUE THREAD

**Issue by ntchjb** [foundry-rs/foundry#1461]
### Component

Cast

### Have you ensured that all of these are up to date?

- [x] Foundry
- [X] Foundryup

### What version of Foundry are you on?

cast 0.2.0 (dda0189 2022-04-30T00:13:42.850610+00:00)

### What command(s) is the bug in?

cast send --chain "arbitrum" --rpc-url "https://arb1.arbitrum.io/rpc" --ledger --hd-path "m'/44'/60'/3'/0/0" --value 0.001ether [Receiver Address]

### Operating System

macOS (M1)

### Describe the bug

When `cast send` is used to send an arbitrary transaction e.g. send some ether to someone, it always fail on Arbitrum One and Arbitrum testnet chains. The Error after sent `eth_sendRawTransaction` request is as follow.

```
(code: -32000, message: invalid chain id for signer, data: None)
```

I'm not sure whether transaction encoding format used by Arbitrum is different from other chains.

**Comment by onbjerg** [comment]
Does your ledger support Arbitrum One? It seems this error is directly from your ledger

**Comment by ntchjb** [comment]
Yes. I tested sending the same transaction to Arbitrum One using ethers.js + Ledger and remix + Metamask stacks, and it was successful. I use Ledger Nano S with Ethereum App for signing.

The error above came from RPC node after `eth_sendRawTransaction` RPC call was sent.

**Comment by ntchjb** [comment]
I have found the issue. It is about `v` value of ECDSA signature that its value is incorrect when chain ID is large, which has been described by this PR: https://github.com/gakonst/ethers-rs/pull/1198.

I also have proposed a solution in this PR, https://github.com/gakonst/ethers-rs/pull/1204, which is the same solution used by Ledger's JavaScript Library.

**Comment by gakonst** [comment]
ethers was bumped here, https://github.com/foundry-rs/foundry/commit/609a556a409a698ae9b55d9f9bb2e1f2c1676ef3 with the fixes, could you please check if it solves the issue @ntchjb ?

**Comment by ntchjb** [comment]
I tested on Arbitrum testnet and Rinkeby and it was successful 🎉 . I am going to close the issue for now, but feel free to re-open it if the issue still persist.

```sh
cast send --chain="arbitrum-testnet" --rpc-url="https://rinkeby.arbitrum.io/rpc" --gas=2000000 --ledger --hd-path="m'/44'/60'/3'/0/0" 0x0000000000000000000000000000000000000066 "register(address)" 0xaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaac

cast send --chain="rinkeby" --rpc-url="https://rinkeby.infura.io/v3/<api>" --gas=2000000 --ledger --hd-path="m'/44'/60'/3'/0/0" --value=0.001ether vitalik.eth
```

**Comment by gakonst** [comment]
I _think_ the `--chain` argument might not be required because you get it from the RPC URL! LGTM Otherwise :)

**Comment by ntchjb** [comment]
Ah yes, I used this command before found the cause of this issue just for controlling variables.
