### ISSUE TITLE
Print return value for `forge run`

### ISSUE THREAD

**Issue by pcaversaccio** [foundry-rs/foundry#1475]
### Component

Forge

### Describe the feature you would like

Print the return values for `returns` functions when using `forge run`.

### Additional context

An example function:
```solidity
function greater(uint256 a) view external returns (uint256 gasUsed) {
    uint256 startGas = gasleft();
    require(a > 0, "!a > 0");
    gasUsed = startGas - gasleft();
}
```

Now if I e.g. run:
```bash
forge run --optimize --optimizer-runs 200 --use 0.8.13 --via-ir GasTesting.sol --sig "greater(uint256)" 0x64
```

it should print the value of `gasUsed`.

**Comment by JoshuaTrujillo15** [comment]
Working on this. What is the preferred printing format? Currently, I'm printing the returned data using

`println!("{:?}", returned_data)`

```
[⠘] Compiling...
[⠊] Compiling 1 files with 0.8.13
[⠒] Solc 0.8.13 finished in 100.44ms
Compiler run successful
Script ran successfully.
Gas used: 220
Result: b"\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1d"
== Logs ==
```

**Comment by pcaversaccio** [comment]
Awesome, thx for working on this issue - well I would suggest having something like the following:
```bash
[⠘] Compiling...
[⠊] Compiling 1 files with 0.8.13
[⠒] Solc 0.8.13 finished in 100.44ms
Compiler run successful
Script ran successfully.
Gas used: 220
== Result ==
0: <type>: <variable_name> <return_value>
1: <type>: <variable_name> <return_value>
⋮
== Logs ==
```

So let's say you have a function like that:
```solidity
function bar(uint256 x) external view returns (bool result, uint256 gasUsed) {
    uint256 startGas = gasleft();
    assembly {
        result := iszero(x)
    }
    gasUsed = startGas - gasleft();
    return (result, gasUsed);
}
```

The output could look like this (similar to Remix):

```bash
[⠘] Compiling...
[⠊] Compiling 1 files with 0.8.13
[⠒] Solc 0.8.13 finished in 100.44ms
Compiler run successful
Script ran successfully.
Gas used: 220
== Result ==
0: bool: result true
1: uint256: gasUsed 18
== Logs ==
```

@onbjerg what do you think?

**Comment by JoshuaTrujillo15** [comment]
So on digging into how the function is getting called, there doesn't seem to be a straight forward way of getting the function's return types, since `run` is just encoding the calldata using arguments from the command line then passing it to the runtime bytecode. The way this is being done doesn't seem to involve fetching the contract ABI.

One way to enable return data decoding could be to include an option such as `--decode (<return_types>)` to decode the return data.

**Comment by pcaversaccio** [comment]
@JoshuaTrujillo15 since we compile the contract before running the script, we could simply retrieve the ABI beforehand under the hood using `solc Contract.sol --combined-json abi,bin` (adding the flag `--abi`)? The `bin` code is anyhow used somehow to deploy the contract locally iirc.

**Comment by onbjerg** [comment]
> So on digging into how the function is getting called, there doesn't seem to be a straight forward way of getting the function's return types, since `run` is just encoding the calldata using arguments from the command line then passing it to the runtime bytecode. The way this is being done doesn't seem to involve fetching the contract ABI.
> 
> One way to enable return data decoding could be to include an option such as `--decode (<return_types>)` to decode the return data.

If you pass `--sig "myFunc(uint256)(uint256)"` it will be parsed into a function that takes a `uint256` and returns a `uint256` - this information should be possible to get in `forge run`. For raw calldata it will not be possible

**Comment by JoshuaTrujillo15** [comment]
I found a way to get the function ABI without adding any additional commands. The `Token` enum that gets printed below seems to print numbers as hexadecimal, but not in an appropriate hexadecimal format. This seems to be because of how `fmt` is implemented for `Token`.
```
== Result ==
0: bool      true
1: int256    ff
2: uint256   2
3: address   0000000000000000000000000000000000000003
4: bytes32   0000000000000000000000000000000000000000000000000000000000000004
5: bytes     
6: string    test
7: uint8[]   []
```
It seems the best way to get this formatted is to run a match against every `Token` type and append the appropriate prefix, since some types such as string just print naturally, but this may be overkill for a single feature. Thoughts?

**Comment by pcaversaccio** [comment]
I don't think running a match against every `Token` type and appending the appropriate prefix _and_ converting them appropriately (e.g. `hex` to `int`) significantly impacts the overall speed. I don't see another way tbh (changing the implemented `fmt` approach is not the way to go IMHO). Also, we probably need to test thoroughly every type to assure that e.g. strings are always naturally printed. @onbjerg @gakonst you know much more about the inner workings of Foundry - what would be your recommendation here?

**Comment by pcaversaccio** [comment]
@zk-tarts that's awesome input! just tested it and it works: 

![image](https://user-images.githubusercontent.com/25297591/167905643-e1137369-d194-482d-9569-efee052c97f7.png)

do you know by chance what are the output formats within the logs for e.g. `string`, arrays & co.?

**Comment by zk-tarts** [comment]
> do you know by chance what are the output formats within the logs for e.g. `string`, arrays & co.?
string outputs as a quoted string, arrays should be output as the the comma seperated values surrounded by square brackets

**Comment by gakonst** [comment]
> I don't think running a match against every Token type and appending the appropriate prefix and converting them appropriately (e.g. hex to int) significantly impacts the overall speed. I don't see another way tbh (changing the implemented fmt approach is not the way to go IMHO). Also, we probably need to test thoroughly every type to assure that e.g. strings are always naturally printed. @onbjerg @gakonst you know much more about the inner workings of Foundry - what would be your recommendation here?

Believe that's what Brock did here, it's kinda gross but it works well: https://github.com/foundry-rs/foundry/blob/master/utils/src/lib.rs#L750-L773

**Comment by onbjerg** [comment]
As @gakonst said you can use `format_token` to display the return values etc. You can get the output tokens using [this](https://docs.rs/ethers/latest/ethers/abi/struct.Function.html#method.decode_output) function from ethers-rs

>Also, we probably need to test thoroughly every type to assure that e.g. strings are always naturally printed

This is tested in ethers-rs (and ethabi?), not sure if there is much value in duplicating that here.

**Comment by JoshuaTrujillo15** [comment]
Awesome, thank you all for your help! I'll have a PR up soon. 🤘

**Comment by pcaversaccio** [comment]
LFG 💥

**Comment by gakonst** [comment]
Fixed in https://github.com/foundry-rs/foundry/pull/1592
