### ISSUE TITLE
Add `forge cache ls`

### ISSUE THREAD

**Issue by onbjerg** [foundry-rs/foundry#1476]
### Component

Forge

### Describe the feature you would like

Now that we have `forge cache clean` (https://github.com/foundry-rs/foundry/pull/1407), it would be natural to have a `forge cache ls` that lists what is in the cache currently.

Proposed usage would be `forge cache ls <chain...>` to show something like:

```
- mainnet (2.2 MiB)
  - block 123 (1 MiB)
  - block 456 (1.2 MiB)
- optimism (1 KiB)
  - block 3 (1 KiB)
```

You can specify `chain` (default `all`) to filter the output. Can accept multiple values.

### Additional context

There are two primary uses for `forge cache clean`:

- You have an error you can't grok, so you try to clean the RPC cache to see if that is the issue
- You want to clear disk space, in which case `forge cache ls` is helpful in determining what you want to keep and what you don't want to keep

**Comment by 0xvv** [comment]
I'm working on it, i still need to filter files in case the cache contrains some and get the sizes of the folders, should be done tomorow !

Also emojis... yay or nay ? 

![Screenshot from 2022-05-06 02-32-00](https://user-images.githubusercontent.com/104269768/167047918-9467fc03-8f74-4491-9b2e-27ce42bc03ab.png)

**Comment by onbjerg** [comment]
I'd say no to the emojis to keep it consistent - I also don't know if all platforms (looking at Windows) support emojis in their terminal :smile:
