### ISSUE TITLE
Add a subcommand to `forge cache` that cleans Etherscan cache

### ISSUE THREAD

**Issue by onbjerg** [foundry-rs/foundry#1477]
### Component

Forge

### Describe the feature you would like

Currently `forge cache clean` only clears RPC cache, but it would be beneficial to also be able to clear the Etherscan verification status cache.

### Additional context

The Etherscan cache is stored in `~/.foundry/cache/<chain>/etherscan`.

The size of the Etherscan cache should also be present in https://github.com/foundry-rs/foundry/issues/1476

**Comment by kris524** [comment]
Hello, can I pick this issue? If there is any  additional info I might need let me know

**Comment by mattsse** [comment]
> Hello, can I pick this issue? If there is any additional info I might need let me know

sure! 
awesome, I think this should can reuse a lot of the existing code and perhaps we add an `--etherscan` option to target the etherscan cache

**Comment by kris524** [comment]
So I spent some time yesterday trying to figure it out. I forgot to mention this is my first ever issue and not sure where to start. I couldn't find that specific path. I will try again today, but if there are any references/links I might need to set my environment up let me know

**Comment by adaddeo** [comment]
@kris524 see this commit for relevant files https://github.com/foundry-rs/foundry/commit/3dfa6e1a8bf8cc5929f40882e5871e4e89eae4b6

**Comment by onbjerg** [comment]
@kris524 You might not have those folders because they are only created if you run a test that forks from a remote chain *and* from a specific block.

**Comment by bcral** [comment]
@kris524 How's the work going?  I'm willing to take over this issue if you'd like.  Thanks!

**Comment by kris524** [comment]
Go ahead, I've been too busy

**Comment by onbjerg** [comment]
@bcral Each chain cache directory may have an `etherscan` directory that is used for caching Etherscan verifications. We just need a way to delete them per-chain (or optionally all of them)

**Comment by mattsse** [comment]
wouldn't it be easier to store under `etherscan/<chain>` instead of `<chain>/etherscan` ?

**Comment by mattsse** [comment]
> In addition, I checked other issues, but I don't see anything about clearing cache data by chain. Something like forge cache clean <chain_name>? Did is miss this issue, or is this something to include with this one?

the already exists, the cache command accepts optional arguments (forge cache clean --help), check the cache command in cache.rs which accepts chains.

> Is the desire here to be able to independently clear only the etherscan data from the ~/.foundry/cache/chain/ folder without deleting everything else?

yes

> As @onbjerg mentioned in the last comment, probably a command like: forge cache clean <chain_name> --etherscan to clear a specific chain's etherscan, and something like: forge cache clean --etherscan to clear all etherscan data regardless of chain?

exactly, adding an `--etherscan` flag would be the best solution.

additional relevant code: is https://github.com/foundry-rs/foundry/blob/master/evm/src/trace/identifier/etherscan.rs#L31

@onbjerg perhaps we should structure the cache layout as

```
cache/
    - rpc/{mainnet,...}
    - etherscan/{mainnet,...}
```
?

**Comment by onbjerg** [comment]
Yeah that would make sense
