### ISSUE TITLE
Add `forge debug` subcommand which runs a transaction in the debugger using state from a different chain

### ISSUE THREAD

**Issue by lithp** [foundry-rs/foundry#1482]
### Component

Forge

### Describe the feature you would like

This is a request for design advice on a PR I would like to write. I've already written something hacky and want to get input on what the interface should look like before I start cleaning it up.

I have an integration test suite which interacts with a private chain and recently the tests broke. I had a geth trace but no interactive debugger to inspect it with. I realized forge _already_ has all the necessary pieces to let me debug this transaction, they're just not wired up yet!

I added a `forge debug` subcommand which accepts the parameters you would send `eth_call` and runs the transaction, backfilling state using a fork backend, then opens the trace in the tui. This works great!

Some things I would like input on:

- Is `forge debug` a good name for this command? Maybe you would prefer it be an extra flag passed to `forge run`, since this behavior is very similar to the existing `forge run`.

- I had a hard time getting sourcemaps to work correctly. The "right" answer seems to be adding support in `ethers_solc::Project` for reading from an exsiting directory instead of doing a fresh compile every time. The user can run solc and deploy contracts using their existing process and forge will later load contracts and sourcemaps from those output directories. Does this sound like a reasonable approach? At this point you don't even really need to be in a local forge project directory, maybe it's better to do this as a cast command?

- I had a hard time getting forge to recognize which addresses corresponded to which contracts. If I'm reading the code correctly `LocalTraceIdentifier` is supposed to compare the deployed bytecode with the known bytecodes and come up with the matching contract but that doesn'twork at all for me. Am I using it wrong or is this known to not work?

- Are there any additional difficulties you foresee?

**Comment by onbjerg** [comment]
Check out `cast run` - is that what you're asking? :)

**Comment by lithp** [comment]
You have got to be kidding me, [added 12 days ago](https://github.com/foundry-rs/foundry/commit/92427e73b75e41c50d1d0afef85ae32454cd1cfe), all I had to do was run `foundryup`!? 😅 

I'll take a look at it and come back to this issue

**Comment by lithp** [comment]
Thanks again, closing this, I'll open a more targeted issue against cast!
