### ISSUE TITLE
Contract name and filename collisions

### ISSUE THREAD

**Issue by antonper** [foundry-rs/foundry#1488]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a97090d 2022-05-02T00:04:10.711117948+00:00)

### What command(s) is the bug in?

forge build

### Operating System

Linux

### Describe the bug

File structure:
```
├── src
│   ├── a.sol
│   └── inner
│       └── a.sol
```

src/a.sol
```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

contract A {
  function bar() public {
  }
}
```
src/inner/a.sol
```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

contract A {
  function bar() public {
  }
}
contract B {
  function foo() public {
  }
}

```

After running `forge build` I have following file structure:
```
├── out
│   └── a.sol
│       ├── A.json
│       └── B.json
```

The content of out json files corresponds to `inner/a.sol`. No data will be in `out` folder for the `src/a.sol` file.
Similar thing happens if `A` inside `inner/a.sol` is an interface. This is a bit unusual to define same contracts in files with same names, but may be something like a warning is a good option here.

**Comment by mattsse** [comment]
sorry for the wait, investigating this and add a fix to prevent collisions where num((filename, contractname)) > 1

**Comment by mattsse** [comment]
bumping, trying to fix this asap

**Comment by mattsse** [comment]
this was fixed with https://github.com/gakonst/ethers-rs/issues/1487
