### ISSUE TITLE
Alternative source dirs of dependencies are not picked up by remappings

### ISSUE THREAD

**Issue by adhusson** [foundry-rs/foundry#1492]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a152664 2022-05-04T17:45:52.953502+00:00)

### Operating System

macOS (M1)

### Describe the bug

With the following structure:

```
.
├── foundry.toml
├── lib
│   ├── dep
│   │   ├── foundry.toml
│   │   ├── src
│   │   │   └── dep.sol
├── src
│   └── try2.sol
```

Running `forge config` gives:
```
# (...)
remappings = [
    'dep/=lib/dep/src/',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
]
```

However, if in `./lib/dep/foundry.toml` I replace `src = 'src'` with `src = 'src2'`, running `forge config` gives:
```
# (...)
remappings = [
    'dep/=lib/dep/src/',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'src2/=lib/dep/src2/',
]
```

Which means that I cannot use `import "dep/dep.sol";`

**Comment by mattsse** [comment]
I see, thanks for flagging
