### ISSUE TITLE
`forge inspect <Contract> method-identifiers` prints null

### ISSUE THREAD

**Issue by wp-lai** [foundry-rs/foundry#1497]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8478c08 2022-05-05T00:13:22.824937+00:00)

### What command(s) is the bug in?

forge inspect <contract> method-identifiers

### Operating System

macOS (amd)

### Describe the bug

`forge inspect <Contract> method-identifiers` prints null

**Comment by onbjerg** [comment]
If you run `forge clean` first it works.

cc @mattsse it seems `forge inspect` does not rebuild when fields are missing from existing artifacts. Any idea why?

To reproduce bug:

- Build a project
- `forge inspect SomeContract method-identifiers`
- Output is `null`

However, if you run `forge clean` before `forge inspect`, or if you build with `forge build --extra-output evm.methodIdentifiers`, it works.

**Comment by wp-lai** [comment]
When I `forge init` a new repo, `forge inspect SomeContract method-identifiers` outputs the right info.
However, after I update forge using `foundryup`, the output for method-identifiers becomes null. 
Also when I cd into other folders that builded using a previous forge version, the output for method-identifiers is null.
And yes, run `forge clean` before `forge inspect`, it works.

**Comment by onbjerg** [comment]
@meetmangukiya Another good issue to take on - I think this might be related to a lot of other `forge build` issues and is mostly in ethers-rs. I suspect it might be related to how we decide what to recompile or not - maybe some settings are not factored into what to recompile?

**Comment by meetmangukiya** [comment]
This can be closed now
