### ISSUE TITLE
dependency lib&src tracking does not follow symlinks

### ISSUE THREAD

**Issue by adhusson** [foundry-rs/foundry#1498]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8478c08 2022-05-05T06:20:40.607851+00:00)

### Operating System

macOS (M1)

### Describe the bug

If the dependency in the lib directory is a symlink to a directory, forge infers default `lib` and `src` directories. It should follow the symlink and read any existing `foundry.toml`.

**Comment by mattsse** [comment]
> forge infers default lib and src directories. 

of what directory?

**Comment by onbjerg** [comment]
Fixed in #1501
