### ISSUE TITLE
Forge test ignores the test path set in foundry.toml

### ISSUE THREAD

**Issue by haythem96** [foundry-rs/foundry#1499]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (107f477 2022-04-28T00:08:47.183276+00:00)

### What command(s) is the bug in?

forge test

### Operating System

macOS (amd)

### Describe the bug

- I have a contract inside the `contracts` dir that have a function that start with `test..()`
- A solidity test file meant to be run by foundry inside `contracts/foundry-test/` dir
- `test = 'contracts/foundry-test'` in foundry.toml

When running `forge test` I expected that it should run the solidity files inside `contracts/foundry-test` only, but still it run the `test..()`.

**Comment by onbjerg** [comment]
To clarify: Your issue is that contracts in `contracts` that start with `test` are also run, where you only want contracts in `contracts/foundry-test` to be run?

**Comment by haythem96** [comment]
> To clarify: Your issue is that contracts in `contracts` that start with `test` are also run, where you only want contracts in `contracts/foundry-test` to be run?

Yes correct

**Comment by onbjerg** [comment]
This should have been fixed a while ago now, please let me know if it still does not work for you :smile:
