### ISSUE TITLE
Add a flag for disabling git committing when running "forge install"

### ISSUE THREAD

**Issue by paulrberg** [foundry-rs/foundry#1504]
### Component

Forge

### Describe the feature you would like

In my project I'm using a [husky](https://github.com/typicode/husky) git hook to check that all commit messages adhere to [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/) before they are allowed.

After I run `forge install`, forge fails with the following error in my project:

```text
⧗   input: forge install: forge-std
✖   subject may not be empty [subject-empty]
✖   type may not be empty [type-empty]

✖   found 2 problems, 0 warnings
ⓘ   Get help: https://github.com/conventional-changelog/commitlint/#what-is-commitlint

husky - commit-msg hook exited with code 1 (error)
```

It would be helpful to be able to disable this behavior. There should several situations in which users may prefer forge not to auto-created git commits for them - it seems like a sensible thing to do to enable an escape hatch.

**Comment by mattsse** [comment]
there should be already a `--no-commit` flag for `forge install`

**Comment by paulrberg** [comment]
Oh sorry, I missed it!
