### ISSUE TITLE
Feature: Custom Precompiles for Anvil 

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#1505]
### Component

Anvil

### Describe the feature you would like

Custom
Precompiles

for...

ANVIL

### Additional context

please add `anvil` as a component for requests

**Comment by sambacha** [comment]
Example: having @mds1 multicall deployments or @pcaversaccio CREATE2 factories potentially

**Comment by sambacha** [comment]
This is in practice much harder to do

**Comment by DaniPopes** [comment]
Ref https://github.com/foundry-rs/foundry/issues/748
