### ISSUE TITLE
Unable to Verify Contract on Moonriver

### ISSUE THREAD

**Issue by adamxyzxyz** [foundry-rs/foundry#1534]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

0.2.0

### What command(s) is the bug in?

forge verify-contract

### Operating System

macOS (M1)

### Describe the bug

Hello,

I am unable to verify contracts that I deploy to moonriver. I am able to deploy them correctly, but they will not verify. I receive these errors:

```
   0: Failed to create etherscan client
   1: Chain moonriver not supported
```

Is this an error on my part? Or is Moonriver for whatever reason not supported yet?

**Comment by mattsse** [comment]
thanks for flagging,
just missing url for their etherscan, I guess it's this https://moonbeam.moonscan.io/

**Comment by adamxyzxyz** [comment]
yep that is for moonbeam, moonriver is this one:

https://moonriver.moonscan.io/

**Comment by adamxyzxyz** [comment]
I'm I good to try again now?

**Comment by gakonst** [comment]
yep - should work now
