### ISSUE TITLE
replace eth_sendUnsignedTransaction with eth_sendTransaction

### ISSUE THREAD

**Issue by dape111** [foundry-rs/foundry#1541]
### Component

Anvil

### Describe the feature you would like

I think it would be better to replace `eth_sendUnsignedTransaction` with `eth_sendTransaction` as web3 libraries has functions that matches with `eth_sendTransaction`.

**Comment by onbjerg** [comment]
Both work. As far as I know, `eth_sendUnsignedTransaction` just skips signature verification all together

**Comment by dape111** [comment]
> Both work. As far as I know, `eth_sendUnsignedTransaction` just skips signature verification all together

It would be better to make `eth_sendTransaction` skip signature verification UX wise just like Hardhat, I am getting `ValueError: {'code': -32602, 'message': 'No Signer available'}`

**Comment by onbjerg** [comment]
Are you setting `from` to one of the dev accounts? If so, it should sign for you. I don't think Hardhat skips signature verification as that would break with the JSONRPC spec for Ethereum, I think it just does the standard behavior of signing

If `eth_sendTransaction` with from set to one of the dev accounts does not sign for you, then I think that's a bug 😞

**Comment by dape111** [comment]
> Are you setting `from` to one of the dev accounts? If so, it should sign for you. I don't think Hardhat skips signature verification as that would break with the JSONRPC spec for Ethereum, I think it just does the standard behavior of signing
> 
> If `eth_sendTransaction` with from set to one of the dev accounts does not sign for you, then I think that's a bug 😞

I am setting it to an account that was impersonated, in hardhat it would skip signature verification when `eth_sendTransaction` is called.

**Comment by adamxyzxyz** [comment]
any update on this?
