### ISSUE TITLE
Expect revert not behaving as expected

### ISSUE THREAD

**Issue by FredCoen** [foundry-rs/foundry#1552]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

➜   0.2.0 (a97090d 2022-05-02T00:06:08.934182+00:00)

### What command(s) is the bug in?

forge test --match-path src/tests/functional/\*.sol -vvvvv --fork-url <rpc>

### Operating System

macOS (M1)

### Describe the bug

Expect a revert with a given reason does not seem to work. The test fails for that reason anyway

```
vm.expectRevert('ERC721: owner query for nonexistent token');
position.ownerOf(0);
```

Test fails with:
Position Contract::ownerOf(0) [staticcall]
    │   └─ ← "ERC721: owner query for nonexistent token"
    └─ ← "ERC721: owner query for nonexistent token"
    
Using a simple expectRevert without any reason fails the same way

**Comment by marc-aurele-besner** [comment]
Hi,
expectRevert take in bytes not string
so:
vm.expectRevert(bytes("ERC721: owner query for nonexistent token"));

**Comment by FredCoen** [comment]
nope same thing unfortunately, also the conversion to bytes should be implicit

**Comment by onbjerg** [comment]
Can you provide a minimal example?

**Comment by FredCoen** [comment]
@onbjerg my bad error on my side forge working as expected

**Comment by AdamCuculich** [comment]
@FredCoen What was the issue? I'm running into the same problem.

**Comment by FredCoen** [comment]
logic was flawed on my side. It should work as stated above @AdamCuculich

**Comment by haythem96** [comment]
Facing similar issue, what was the flawed logic on ur side @FredCoen ?

**Comment by Rossnkama** [comment]
@haythemsellami  Revert Expects that the next TX will revert.

This will fail:
```
function testCannotAddWhenMaxUINT() public {
	vm.expectRevert(stdError.arithmeticError);
	// Fails as this next TX below doesn't revert
	bank.add(AccountType.Savings, UINT256_MAX); 
	bank.add(AccountType.Savings, 1);
}
```

This will pass:
```
function testCannotAddWhenMaxUINT() public {
	bank.add(AccountType.Savings, UINT256_MAX);
	// Passes, we're testing the overflow prone TX under the check reverts
	vm.expectRevert(stdError.arithmeticError);
	bank.add(AccountType.Savings, 1);
}
```

**Comment by shryder** [comment]
For anyone that runs into the same issue as I did:

```
vm.expectRevert("Total supply cannot exceed max supply");
token.mint(address(0x1337), token.maxSupply() - token.totalSupply() + 1);
```

This will not behave as you think it should because foundry expects the (next) call to `token.maxSupply()` to revert, not `token.mint(...)`.

Should separate the calls instead like this:

```
uint maxSupply = token.maxSupply();
uint totalSupply = token.totalSupply();

vm.expectRevert("Total supply cannot exceed max supply");
token.mint(address(0x1337), maxSupply - totalSupply + 1);
```
