### ISSUE TITLE
Anvil's CPU usage is suspiciously high when it's idle

### ISSUE THREAD

**Issue by ubunteroz** [foundry-rs/foundry#1561]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (85f69d9 2022-05-09T00:04:25.613861+00:00)

### What command(s) is the bug in?

anvil -f https://bsc-dataseed.binance.org

### Operating System

macOS (M1)

### Describe the bug

I used Anvil to fork BSC mainnet from latest block number. No problem when interacting with forked chain, everything was fine, Anvil ran very fast compared to Ganache. But I noticed that my M1 Macbook Air was getting warm when idle. After checking Activity Monitor, I saw that Anvil used 160% CPU when doing nothing.

**Comment by mattsse** [comment]
thanks, this is indeed happening in fork mode, probably related to #1549
