### ISSUE TITLE
Trace fails to match interface functions and events

### ISSUE THREAD

**Issue by dekz** [foundry-rs/foundry#1563]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (85f69d9 2022-05-09T00:04:25.613861+00:00)

### What command(s) is the bug in?

forge test -vvvv -f MAINNET_FORK

### Operating System

macOS (M1)

### Describe the bug

Expected a Forge trace to match against signatures and events contained in an `interface`. 

On the current version the signatures fail to match and the bytes4 is printed instead.

```
[PASS] testExample() (gas: 7688)
Traces:
  [7688] ContractTest::testExample()
    ├─ [2480] 0xb4e1…c9dc::70a08231(000000000000000000000000b4c79dab8f259c7aee6e5b2aa729821864227e84) [staticcall]
    │   └─ ← 0x0000000000000000000000000000000000000000000000000000000000000000
    └─ ← ()
```

If instead this interface is converted to a stubbed contract, and that contract is deployed, then the signatures match as expected.

```
[PASS] testStub() (gas: 7666)
Traces:
  [7666] ContractStubTest::testStub()
    ├─ [2480] 0xb4e1…c9dc::balanceOf(ContractStubTest: [0xb4c79dab8f259c7aee6e5b2aa729821864227e84]) [staticcall]
    │   └─ ← 0
    └─ ← ()
```

Repro project can be found here: https://github.com/dekz/foundry-interface-match

**Comment by onbjerg** [comment]
We currently can't do this because we do the matching based on bytecode. To support this we would have to parse the test contract and determine it that way, but that would be way more complex (for imo, little gain), not cover all edge cases (e.g. if the interface uses an address in a storage variable) and even produce wrong guesses as well. Not sure what the best path forward is here.

**Comment by dekz** [comment]
Work around is to either:  
* Modify interface to a stubbed contract (and deploy in test) so it finds the match
* Export an `ETHERSCAN_API_KEY` to use the `EtherscanIdentifier` in various places.

**Comment by onbjerg** [comment]
Sure, if these are forked tests then the recommended way is to set `ETHERSCAN_API_KEY`, but the repro you shared did not suggest it was forked tests :smile:

**Comment by mds1** [comment]
I'm running into this now and from a user perspective it definitely feels like a bug that should be fixed—it's confusing that my interface is defined and visible in the `out` folder but the trace doesn't decode it's methods, and the workarounds aren't ideal. This makes debugging harder when you have lots of interfaces, as traces become not very readable. 

> We currently can't do this because we do the matching based on bytecode. To support this we would have to parse the test contract and determine it that way, but that would be way more complex (for imo, little gain), not cover all edge cases (e.g. if the interface uses an address in a storage variable) and even produce wrong guesses as well. Not sure what the best path forward is here.

Could we add fallback to attempt decoding by ABI when bytecode matching fails? Something like this:
- Take the ABIs from all artifacts and merge them into a single vector of functions. If there's duplicate sigs across ABIs, those can be safely ignored. If there's function selector collisions, just keep the first and log a warning so the user knows decoding may be inaccurate for some selectors. This is basically a mini 4byte.directory of all local, known signatures.
- Attempt match by bytecode like we currently do
- If no match is found, fallback to using the set of all functions to try decoding

**Comment by onbjerg** [comment]
@dekz There's been some changes to tracing and new identifiers have been added, is this still an issue for you?

**Comment by onbjerg** [comment]
Closing - let me know if this is still an issue for you :)

**Comment by dekz** [comment]
sorry mate just saw this, thanks so much, I'll give it a whirl today and report back if there are any issues.
