### ISSUE TITLE
Unify names of supported chains

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#1564]
### Component

Forge

### Describe the feature you would like

Currently we're using

https://github.com/foundry-rs/foundry/blob/ed4eb2de59ced6c8fc2ce84a101ec9d408b7a552/cli/src/opts/mod.rs#L40-L57

in several places, ideally, this should be a single function that's then set as argument in the clap attribute, if possible

**Comment by onbjerg** [comment]
Any reason we didn't use `#[derive(ArgEnum)]` (see [here](https://github.com/clap-rs/clap/blob/v3.1.7/examples/derive_ref/README.md#overview))? :thinking:

**Comment by mattsse** [comment]
lol TIL

let's try that.

this would be an easy pick up if anyone's looking for an easy issue

**Comment by shawnharmsen** [comment]
I'd like to take this one today, will add PR soon
