### ISSUE TITLE
forge: improve verification UX

### ISSUE THREAD

**Issue by rkrasiuk** [foundry-rs/foundry#1567]
### Component

Forge

### Describe the feature you would like

This issue is a tracker for contract verification UX improvements. Continuation of #695 

- [x] add ability to lookup build metadata (commit hash) for given solc version
- [x] read compiler version & optimizer runs from foundry config
- [x] add watch flag to allow contract verification & confirmation with a single command

**Comment by mattsse** [comment]
also, I wrote a `retry` routine for the verify integration tests that does everything in one step, perhaps we can incorporate this as well, via a  `--watch` flag or something

**Comment by onbjerg** [comment]
Another big UX thing we could do is `--verify` on `forge create` :)

**Comment by mattsse** [comment]
exactly, so

`forge create --verify` would also execute
`forge verify --watch`

a rough version of this is already used in the `verify` tests with a retry loop that tries to submit the verify after create and pings the etherscan server until a verify result is available

**Comment by mattsse** [comment]
vote close @rkrasiuk
