### ISSUE TITLE
`forge test --match-contract` always throws, when no matching tests are found

### ISSUE THREAD

**Issue by ChiTimesChi** [foundry-rs/foundry#1575]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (752dd63 2022-05-10T00:03:36.474260356+00:00)

### What command(s) is the bug in?

forge test --match-contract

### Operating System

Linux

### Describe the bug

My usecase is having a lot of tests in forked environment, so I have one common big-ass script for running tests in environment based by their contract name (used both for local testing, and in the CI):
```bash
# Test contracts ending with exactly "Test" don't require any forking
forge test --match-contract "$1.*Test$" -vvv || exit 1
# Test contracts ending with exactly "TestAvax" require Avalanche RPC and block number: 2022-04-25
forge test --match-contract "$1.*TestAvax$" --fork-url $AVAX_API --fork-block-number 13897000 -vvv || exit 1
# Test contracts ending with exactly "TestEth" require Ethereum RPC and block number: 2022-04-24
forge test --match-contract "$1.*TestEth$" --fork-url $ALCHEMY_API --fork-block-number 14650000 -vvv || exit 1
# More like this below
```
Post-update this script fails if there are no contracts matching the filter. 

Possible solutions:
- Introduce additional flag for `forge test` (or env varialbe) that would make it exit silently instead of throwing error, when no tests matching the filter are found.
- Exit silently, only when regular expression contains `.*`

**Comment by 0xYYY** [comment]
Perhaps throwing error isn't necessary in the first place? Showing a message that no tests were ran and providing a suggestion may be sufficient. wdyt? @mattsse
