### ISSUE TITLE
`forge build --extra-output=<SELECTOR>` cannot pass multiple selectors

### ISSUE THREAD

**Issue by wp-lai** [foundry-rs/foundry#1579]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (0977421 2022-05-11T00:05:39.854564+00:00)

### What command(s) is the bug in?

forge build

### Operating System

macOS (M1)

### Describe the bug

I want to have both `evm.gasEstimates` and `evm.methodIdentifiers` as extra output when compile my project.
I can do it by adding `extra_output = ["evm.gasEstimates", "evm.methodIdentifiers"]` in `foundry.toml`. 
But it seems I cannot do it by using `forge build --extra-output="evm.gasEstimates","evm.methodIdentifiers"`

**Comment by mattsse** [comment]
thanks for flagging, this should be fixed easily, probably something's off with the args parser settings here
