### ISSUE TITLE
`cast storage` incompatible with Hardhat and underlying spec

### ISSUE THREAD

**Issue by jamierumbelow** [foundry-rs/foundry#1590]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

0.2.0

### What command(s) is the bug in?

cast storage

### Operating System

macOS (Apple Silicon)

### Describe the bug

`cast storage` appears to be incompatible with Hardhat, and the underlying RPC spec.

When calling `eth_getStorageAt`, the parameter validation in `isRpcQuantityString` (src/internal/core/jsonrpc/types/base-types.ts:127) uses the following regex to validate the 1st-place parameter (the storage location):

    /^0x(?:0|(?:[1-9a-fA-F][0-9a-fA-F]*))$/

This regex won't match values with leading zeros. Thus, the following is a valid string:

    0x1

And this is not:

    0x0000000000000000000000000000000000000000000000000000000000000001

This leads to the following frustrating error:

    $ cast storage 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2 0x1
    
    Error:
      0: (code: -32602, message: Errors encountered in param 1: Invalid value "0x0000000000000000000000000000000000000000000000000000000000000001" supplied to : QUANTITY, data: None)

The [spec](https://eips.ethereum.org/EIPS/eip-1474#quantity) appears to reject leading zeros, so it looks like Hardhat is implementing the spec correctly and `cast` is left-padding the quantity incorrectly.

[This comment](https://github.com/foundry-rs/foundry/issues/385#issuecomment-1008013886) implies that it's the other way round, so I'm not sure what the correct outcome here is.

I'm [cross-posting this at the Hardhat repository](https://github.com/NomicFoundation/hardhat/issues/2698) too, in case it makes more sense for them to deviate from the spec.

**Comment by onbjerg** [comment]
Interesting, going by the EIP it does seem like you are correct. Specifically they mark `0x00` as invalid (because of leading zeros) and `0x0` as valid. I think this might be an ethers-rs issue, though, since we use that for formatting. I'm unsure if there is a supported way to truncate leading zeros.

**Comment by kmbarry1** [comment]
Hitting this as well.

**Comment by mattsse** [comment]
going by the spec, this is an ethers serialization issue for `Quantity` values, so we'd not a util serialize function that removes leading zeros @gakonst ?

**Comment by gakonst** [comment]
Yep - let's track on ethers.
