### ISSUE TITLE
Anvil fork node `block.timestamp` always returns 1

### ISSUE THREAD

**Issue by solimander** [foundry-rs/foundry#1593]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

anvil 0.1.0 (4604a42 2022-05-12T00:04:28.605557+00:00)

### Operating System

macOS (Apple Silicon)

### Describe the bug

`block.timestamp` is always `1` when interacting with contracts via an Anvil fork node (`anvil --fork-url https://eth-mainnet.alchemyapi.io/v2/api_key_here`).

As an example, call `getCurrentBlockTimestamp` on the [multicall contract](https://etherscan.io/address/0xeefBa1e63905eF1D7ACbA5a8513c70307C1cE441) to reproduce this behavior.

**Comment by solimander** [comment]
Thanks for the quick PR, @mattsse! The fix works great when forking at the current head, but is invalid when `--fork-block-number` is provided. Instead, the block timestamp of the forked block should be used.

**Comment by mattsse** [comment]
thanks for raising, will get this fixed
