### ISSUE TITLE
Produce bindings for enums

### ISSUE THREAD

**Issue by oblique** [foundry-rs/foundry#1596]
### Component

Forge

### Describe the feature you would like

I would like forge to generate Rust enums of the following Solidity code:

```solidity
pragma solidity ^0.8.13;

contract Foo {
    enum Bar {
        A,
        B,
        C
    }

    function doSomething(Foo foo) public view {}
}
```

The above should generate something like this:

```rust
#[derive(Debug, Clone, Copy)]
#[repr(u8)]
enum Bar {
    A,
    B,
    C,
}

impl Bar {
    fn from_u8(val: u8) -> Option<Bar> {
        match val {
            0 => Some(Bar::A),
            1 => Some(Bar::B),
            2 => Some(Bar::C),
            _ => None,
        }
    }

    fn to_u8(&self) -> u8 {
        *self as u8
    }
}
```

### Additional context

As I understand this is a limitation because only the `abi` field is used from the json file.

This information can be retrieved from `ast` field, but `abigen` does not accept this kind of input.

**Comment by onbjerg** [comment]
Is this a feature request for `forge bind`, or a feature request for `abigen`? `abigen` is not in this repository, it's in ethers-rs

**Comment by oblique** [comment]
It is for `forge bind`.

**Comment by jaeaster** [comment]
+1 would be very nice to access these enums with types in rust

**Comment by mattsse** [comment]
I don't think enum variants are included in the abi itself.

```solidity
contract Foo {
    enum Bar {
        A,
        B,
        C
    }

    function doSomething(Bar bar) public view {}
}

```

```json
	"abi": [
		{
			"inputs": [
				{
					"internalType": "enum Foo.Bar",
					"name": "bar",
					"type": "uint8"
				}
			],
			"name": "doSomething",
			"outputs": [],
			"stateMutability": "view",
			"type": "function"
		}
	]

```

so we only know that there's an enum but don't know anything about the variants

**Comment by jaeaster** [comment]
This is true. As @oblique mentioned, the enum variants can be found in the `ast` section of the forge output, but not `abi`

**Comment by mattsse** [comment]
right, so we'd need to check if the json input contains the ast field and start extracting enums from that. then use them if we see them in abi

**Comment by zerosnacks** [comment]
Bindings for `enum`s are now produced when running `forge bind --alloy`, marking as resolved
