### ISSUE TITLE
anvil: support tx priority 

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#1599]
### Component

Anvil

### Describe the feature you would like

Currently if  multiple transactions are ready for
block inclusion they're only sorted by their id.

to make this adjustable, a `priority` metric is required, this should be a numeric value: fees paid to the miner.

**Comment by kushalbabel** [comment]
`priority` should be automatically be assigned through configuration. One configuration should be `fifo` which is essentially the current tx order. The second configuration should be `gasprice`.
It would be great if there is an additional configuration `manual`, where the user needs to specify a numeric priority with each transaction (but there is a default priority if not specified)

Example in hardhat : https://hardhat.org/hardhat-network/reference/#transaction-ordering
