### ISSUE TITLE
Consider using user gas price in fork mode

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#1601]
### Component

Anvil

### Describe the feature you would like

currently, the `env` `tx` are using the `gas_price` from the fork `eth_gasprice`,

should we instead use the config `gas_price`?

this gas_price is always present which makes it difficult to detect whether the user modified the gas_price, only by comparing to the default `gas_price`.

always using the config gas price, would also break some assumptions I think, so not entirely sure what to do here.

most practical, would be to use the user defined `gasprice` if it deviates from the `Config::default` perhaps?

or we make `gasPrice` and Option<u64>, which would require some additional code changes

wdyt @gakonst @onbjerg 

### Additional context

ref #1383

>Hello,
I just fetched the newest forge and it seems that the gas_price parameter in foundry.toml is ignored. Current mainnet gas price is used instead.

>My foundry.toml:

`
[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src/', 'forge-std/=lib/forge-std/src/']
eth-rpc-url = 'RPC_URL'
fork_block_number = 14411926
gas_price = 40000000000
`

_Originally posted by @benesjan in https://github.com/foundry-rs/foundry/issues/1383#issuecomment-1125218989_

**Comment by gakonst** [comment]
> most practical, would be to use the user defined gasprice if it deviates from the Config::default perhaps?
> or we make gasPrice and Option, which would require some additional code changes

I think the "right" solution is to make it an `Option`, but acknowledge it can be a pain, so if you think it's sound to do, let's go with a check "if gas_price != Config::default".
