### ISSUE TITLE
Add line/column number for test failure

### ISSUE THREAD

**Issue by holic** [foundry-rs/foundry#1609]
### Component

Forge

### Describe the feature you would like

When a test fails, it would be great if, in addition to what kind of failure (revert, expectation failed, etc.), it would also spit out the line/column in the test file that it failed on. This would match the norms in other testing suites I've used. I can read the trace in `-vvv` to get this but it's not as intuitive/quick.

**Comment by onbjerg** [comment]
Requires us to do a PC-IC mapping (expensive) like we do for debugging, but also somehow backtrack from the internal code of e.g. `assertEq` in DSTest (and others like Forge Std?) to the call site, so definitely non trivial

**Comment by onbjerg** [comment]
Rolling up into https://github.com/foundry-rs/foundry/issues/2328
