### ISSUE TITLE
Fix solang breaking issues in fmt

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#1611]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### Describe the bug

There were quite a few changes in Solang, especially the AST model, which broke the `fmt` box in a non-trivial way.

as a stopgap `fmt` was disabled in #1610

before we can reenable it, the `formatter` and `visitor` need to updated.

cc @shekhirin @rkrasiuk

**Comment by gakonst** [comment]
ref https://github.com/foundry-rs/foundry/pull/1612

**Comment by mattsse** [comment]
closed by #1612
