### ISSUE TITLE
anvil_reset not resetting account nonces

### ISSUE THREAD

**Issue by kushalbabel** [foundry-rs/foundry#1626]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (b33422f 2022-05-14T23:44:53.523516601Z)

### What command(s) is the bug in?

 anvil --fork-url http://localhost:8545 --fork-block-number 14000000 --port 8544 --order fifo

### Operating System

Linux

### Describe the bug

Account nonces are not being reset to 0, when calling `anvil_reset`. i.e., transactions with nonce 0 are not being included in the mined block after the following sequence of calls : `anvil_reset` ,  `evm_setAutomine` (to false) , `hardhat_setBalance`  ,  `eth_sendRawTransaction`  and `evm_mine`
Previous fix that tried resetting everything : https://github.com/foundry-rs/foundry/pull/1614

**Comment by kushalbabel** [comment]
@mattsse

**Comment by mattsse** [comment]
does the address in question have a nonce > 0 in the original chain?

or are nonces on the fork not reset?

**Comment by kushalbabel** [comment]
The address in question has nonce = 0 on the original chain. 
The nonces on the fork are not reset.
Here's how to reproduce it:

Server : `anvil --fork-url http://localhost:8545 --fork-block-number 14000000 --port 8544 --order fifo`

Client : 
`
curl -X POST -H 'Accept: */*' -H 'Accept-Encoding: gzip, deflate' -H 'Connection: keep-alive' -H 'Content-Length: 143' -H 'Content-Type: application/json' -H 'User-Agent: python-requests/2.22.0' -d '{"jsonrpc": "2.0", "method": "anvil_reset", "params": [{"forking": {"jsonRpcUrl": "http://localhost:8545", "blockNumber": 14000000}}], "id": 1}' http://localhost:8544/
`

Out[3]: `{'jsonrpc': '2.0', 'id': 1, 'result': None}`

`
curl -X POST -H 'Accept: */*' -H 'Accept-Encoding: gzip, deflate' -H 'Connection: keep-alive' -H 'Content-Length: 75' -H 'Content-Type: application/json' -H 'User-Agent: python-requests/2.22.0' -d '{"jsonrpc": "2.0", "method": "evm_setAutomine", "params": [false], "id": 1}' http://localhost:8544/
`

Out[4]: `{'jsonrpc': '2.0', 'id': 1, 'result': None}`

`
curl -X POST -H 'Accept: */*' -H 'Accept-Encoding: gzip, deflate' -H 'Connection: keep-alive' -H 'Content-Length: 141' -H 'Content-Type: application/json' -H 'User-Agent: python-requests/2.22.0' -d '{"jsonrpc": "2.0", "method": "hardhat_setBalance", "params": ["0x05E3bD644724652DD57246bae865d4A644151603", "0x3635c9adc5dea00000"], "id": 1}' http://localhost:8544/
`

Out[5]: `{'jsonrpc': '2.0', 'id': 1, 'result': None}`

`
curl -X POST -H 'Accept: */*' -H 'Accept-Encoding: gzip, deflate' -H 'Connection: keep-alive' -H 'Content-Length: 315' -H 'Content-Type: application/json' -H 'User-Agent: python-requests/2.22.0' -d '{"jsonrpc": "2.0", "method": "eth_sendRawTransaction", "params": ["0x02f87201018203e885222ca72a9283e4e1c09442bd55c6502e586d66020ece3fda53cb73d73b6d888ac7230489e8000080c001a0ea7ef215784c929f527111e05b94d314abfb9fcff0a2e51c7332a0f5642b9266a04d8322be0166befb42962c2ad6a15ef641c326774cf547f17f8917ac1bf3aed6"], "id": 1}' http://localhost:8544/
`

`
curl -X POST -H 'Accept: */*' -H 'Accept-Encoding: gzip, deflate' -H 'Connection: keep-alive' -H 'Content-Length: 64' -H 'Content-Type: application/json' -H 'User-Agent: python-requests/2.22.0' -d '{"jsonrpc": "2.0", "method": "evm_mine", "params": [1], "id": 1}' http://localhost:8544/
`

Out[7]: `{'jsonrpc': '2.0', 'id': 1, 'result': '0x0'}`

`
curl -X POST -H 'Accept: */*' -H 'Accept-Encoding: gzip, deflate' -H 'Connection: keep-alive' -H 'Content-Length: 91' -H 'Content-Type: application/json' -H 'User-Agent: python-requests/2.22.0' -d '{"jsonrpc": "2.0", "method": "eth_getBlockByNumber", "params": ["0xd59f81", true], "id": 1}' http://localhost:8544/
`  


Out[8]:
`
{'jsonrpc': '2.0',
 'id': 1,
 'result': {'baseFeePerGas': '0x3b9aca00',
  'difficulty': '0x0',
  'extraData': '0x',
  'gasLimit': '0x1c9c380',
  'gasUsed': '0x5208',
  'hash': '0xc7f4a1e64f55a308a74e3c54dd44446b635882a7a9f9d4a037e0416dde2323ad',
  'logsBloom': '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
  'miner': '0x0000000000000000000000000000000000000000',
  'mixHash': '0x0000000000000000000000000000000000000000000000000000000000000000',
  'nonce': '0x0',
  'number': '0xd59f81',
  'parentHash': '0x9bff49171de27924fa958faf7b7ce605c1ff0fdee86f4c0c74239e6ae20d9446',
  'receiptsRoot': '0xacc0e2639ea755553beb4b48123fe5d662d7a0d5a30b4f04c99af102ad607faf',
  'sealFields': ['0x0000000000000000000000000000000000000000000000000000000000000000',
   '0x0000000000000000'],
  'sha3Uncles': '0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347',
  'size': '0x26e',
  'stateRoot': '0x0000000000000000000000000000000000000000000000000000000000000000',
  'timestamp': '0x1',
  'totalDifficulty': None,
  'transactions': [{'accessList': [],
    'blockHash': '0xc7f4a1e64f55a308a74e3c54dd44446b635882a7a9f9d4a037e0416dde2323ad',
    'blockNumber': '0xd59f81',
    'chainId': '0x1',
    'from': '0x05e3bd644724652dd57246bae865d4a644151603',
    'gas': '0xe4e1c0',
    'gasPrice': '0x3b9acde8',
    'hash': '0xf2d860d6dd6fe37bc8e094441f0c1408e3432e00f244e3356b0fed01a7bab02e',
    'input': '0x',
    'maxFeePerGas': '0x222ca72a92',
    'maxPriorityFeePerGas': '0x3e8',
    'nonce': '0x0',
    'r': '0x9c0b89a5d0bce12665fb3918d0936e81d73a7b1c7f3e6dae2d9161922753a487',
    's': '0x421da8bef7cb845431f6ec0dd40aa7d37f5abaf48da1fa62de2efa5508b3d063',
    'to': '0x42bd55c6502e586d66020ece3fda53cb73d73b6d',
    'transactionIndex': '0x0',
    'type': '0x2',
    'v': '0x0',
    'value': '0x8ac7230489e80000'}],
  'transactionsRoot': '0x9d2ee2f7e97691aeb4693c2004dd33ca3c02d1f948ad19e1c5096be654e55d6b',
  'uncles': []}}
`
 **Transaction mined in this block with nonce 0. 
When I repeat the same commands, transaction does not get mined unless I set the nonce in `eth_sendRawTransaction` params to 1.**

**Comment by kushalbabel** [comment]
Also able to reproduce with your Alchemy url. I'm here : forge 0.2.0 (https://github.com/foundry-rs/foundry/commit/b33422f4468261ba74939bc36e236bcf6ccceb5f 2022-05-14T23:44:53.523516601Z) . 

`curl -X POST -H 'Content-Type: application/json' -d '{"jsonrpc": "2.0", "method": "anvil_reset", "params": [{"forking": {"jsonRpcUrl": "https://eth-mainnet.alchemyapi.io/v2/Lc7oIGYeL_QvInzI0Wiu_pOZZDEKBrdf", "blockNumber": 14000000}}], "id": 1}' http://localhost:8544/`

`curl -X POST -H 'Accept: */*' -H 'Accept-Encoding: gzip, deflate' -H 'Connection: keep-alive' -H 'Content-Length: 75' -H 'Content-Type: application/json' -H 'User-Agent: python-requests/2.22.0' -d '{"jsonrpc": "2.0", "method": "evm_setAutomine", "params": [false], "id": 1}' http://localhost:8544/`

`curl -X POST -H 'Accept: */*' -H 'Accept-Encoding: gzip, deflate' -H 'Connection: keep-alive' -H 'Content-Length: 141' -H 'Content-Type: application/json' -H 'User-Agent: python-requests/2.22.0' -d '{"jsonrpc": "2.0", "method": "hardhat_setBalance", "params": ["0x05E3bD644724652DD57246bae865d4A644151603", "0x3635c9adc5dea00000"], "id": 1}' http://localhost:8544/`

`curl -X POST -H 'Accept: */*' -H 'Accept-Encoding: gzip, deflate' -H 'Connection: keep-alive' -H 'Content-Length: 315' -H 'Content-Type: application/json' -H 'User-Agent: python-requests/2.22.0' -d '{"jsonrpc": "2.0", "method": "eth_sendRawTransaction", "params": ["0x02f87201018203e885222ca72a9283e4e1c09442bd55c6502e586d66020ece3fda53cb73d73b6d888ac7230489e8000080c001a0ea7ef215784c929f527111e05b94d314abfb9fcff0a2e51c7332a0f5642b9266a04d8322be0166befb42962c2ad6a15ef641c326774cf547f17f8917ac1bf3aed6"], "id": 1}' http://localhost:8544/`

`curl -X POST -H 'Accept: */*' -H 'Accept-Encoding: gzip, deflate' -H 'Connection: keep-alive' -H 'Content-Length: 64' -H 'Content-Type: application/json' -H 'User-Agent: python-requests/2.22.0' -d '{"jsonrpc": "2.0", "method": "evm_mine", "params": [1], "id": 1}' http://localhost:8544/`

`curl -X POST -H 'Content-Type: application/json' -d '{"jsonrpc": "2.0", "method": "anvil_reset", "params": [{"forking": {"jsonRpcUrl": "https://eth-mainnet.alchemyapi.io/v2/Lc7oIGYeL_QvInzI0Wiu_pOZZDEKBrdf", "blockNumber": 14000000}}], "id": 1}' http://localhost:8544/`

`curl -X POST -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0","method":"eth_getTransactionCount","params":["0x05e3bd644724652dd57246bae865d4a644151603", "latest"],"id":1}' http://localhost:8544/`

returns `{"jsonrpc":"2.0","id":1,"result":"0x1"}`

**Comment by mattsse** [comment]
tried all commands on the current master 34d2414, which yields 

```console
curl -X POST -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0","method":"eth_getTransactionCount","params":["0x05e3bd644724652dd57246bae865d4a644151603", "latest"],"id":1}' http://localhost:8544/
```
```
{"jsonrpc":"2.0","id":1,"result":"0x0"}
```

**Comment by kushalbabel** [comment]
Thanks a lot @mattsse :)

**Comment by mattsse** [comment]
gg closing now
