### ISSUE TITLE
Support rotating API keys for fork tests

### ISSUE THREAD

**Issue by jpopesculian** [foundry-rs/foundry#1643]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

master 23dc073

### What command(s) is the bug in?

cargo test --locked --workspace --all-features --lib --bins

### Operating System

Linux

### Describe the bug

fork tests seem to be failing on the CI but work locally https://github.com/foundry-rs/foundry/runs/6468348691?check_suite_focus=true

**Comment by mattsse** [comment]
> (code: 429, message: Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemyapi.io/guides/rate-limits, data: None)'

got rate-limited by alchemy, let's turn this issue into a feature request to rotate API keys similar to ethers https://github.com/gakonst/ethers-rs/pull/1017

**Comment by webthethird** [comment]
@mattsse Any chance you could explain how one would use this feature when using `forge test`?

**Comment by webthethird** [comment]
Got it. I could probably hack together something similar though to use in my forge tests. Thanks!
