### ISSUE TITLE
Bad Checksum solc 0.8.14

### ISSUE THREAD

**Issue by matteosantama** [foundry-rs/foundry#1648]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (aea417b 2022-05-17T17:11:06.835167Z)

### What command(s) is the bug in?

forge build

### Operating System

macOS (Apple Silicon)

### Describe the bug

I installed Foundry with

```
cargo install --git https://github.com/foundry-rs/foundry foundry-cli anvil --bins --locked
```

and ran `forge init my-project`. I then encounter an error when trying to build

```
❯ forge build
[⠊] Compiling...
[⠢] installing solc version "0.8.14"The application panicked (crashed).
Message:  checksum not available: "0.8.14"
Location: /Users/matteosantamaria/.cargo/git/checkouts/svm-rs-cd2fa967df1e48a1/1eb7f4e/src/lib.rs:197

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
[1]    69987 abort      forge build
```

Seems like the same error reported in #993, which was thought to be resolved

**Comment by matteosantama** [comment]
The issue stems from [svm-rs](https://github.com/roynalnaruto/svm-rs)

```
❯ svm list
Global version not set

Installed Versions

Available to Install
["0.8.9", "0.8.10", "0.8.11", "0.8.12"]
```

I was able to get `forge build` to work by specifying `solc_version = '0.8.12'` in the `foundry.toml`

**Comment by mattsse** [comment]
new svm release should be included in tmrws nightly once we bump svm-rs cc @roynalnaruto
