### ISSUE TITLE
stdlib support

### ISSUE THREAD

**Issue by gakonst** [foundry-rs/foundry#165]
# Requested feature

It'd be nice if we could import popular contracts in our Solidity without needing to install them as libraries. An example of that in the wild is Hardhat's console.sol being available as `import hardhat/console.sol`.

# Suggested solution

We’d `include_str` the solidity for some contracts in the binary, and when parsing the solidity imports in ethers-solc, we’d see if any of these are imported as ``import ‘std/Vm.sol’` and inject them (cc @mattsse ). 

Example usage: Cheatcodes, maybe Solmate or some subset of it, ..?

That’d make it very easy to run forge test Foo.sol where inside it imports popular stuff, for writing quick testing ‘scripts’ effectively. It also saves you from having to maintain a ds-test submodule lib

**Comment by mattsse** [comment]
that should be doable, however, we should add some precautions, like comparing checksums, in the event a user imports a modified version of console.sol for example

**Comment by gakonst** [comment]
ref #234 since it'd benefit from the stdlib

**Comment by laizy** [comment]
1. From a contract developer's view, those are just some utility contracts provided by a test framework, used for testing and debug. So I prefer use `import ‘forge/Vm.sol` to `import ‘std/Vm.sol`.
2. It will cause IDE autocomplete not working, so I prefer generating those files in `lib/forge` dir when calling `forge init`, or at least providing a subcomand to generate those files.

**Comment by brockelmore** [comment]
Some ideas for what to include:
1. Vm interface
2. builtin errors as bytes, i.e. `bytes[] public arithmeticError = abi.encodeWithSignature("Panic(uint256)", 0x11)`, etc
3. `stdlib.find(target, sig, inputs)` -> find the slot of a variable
4. `stdlib.write(target, sig, inputs, value)` -> find the slot of a variable & write to it (see [HEVMHelpers](https://github.com/brockelmore/HEVMHelpers))

will continue to brain dump as i think of more

**Comment by odyslam** [comment]
It would be very cool to be able to dynamically remove all elements of this lib from the contracts. Basically to be able to add testing/helper functions all around the place and then be certain that you will not leave something behind when deploying.

For example, I have personally deployed contract with `ds-test` included and I was reading that in total the deployed `console.sol` has accumulated around $56K in gas costs.

**Comment by brockelmore** [comment]
one cool hack i wanted a long time ago was being able to convert an internal function to public explicitly for a test. For example:
```
function complicatedMath(uint256 a, uint256 b) internal returns (uint256) {
...
}
```

and somehow we would convert it into public for a test contract without affecting the actual contract. maybe a cheatcode that would fiddle with the AST and deploy the new version

**Comment by odyslam** [comment]
@brockelmore This would be in place of having a "user" contract that inherits from that smart contract and exposes the function? 

so, basically, we want part of the std lib tooling to have a flexible AST modifier implementation

**Comment by brockelmore** [comment]
eh not sure, just throwing out ideas 🤷

**Comment by lucas-manuel** [comment]
Some more ideas:
- `erc20_mint` and other common `hevm.store` operations
- `constrictToRange` functions for fuzzing/symbolic execution
- [`startMeasuringGas/stopMeasuringGas`](https://github.com/Rari-Capital/solmate/blob/fab107565a51674f3a3b5bfdaacc67f6179b1a9b/src/test/utils/DSTestPlus.sol#L16) from Solmate

**Comment by mds1** [comment]
> `constrictToRange` functions for fuzzing/symbolic execution

Not yet merged to main, but we added a [`bound`](https://github.com/Rari-Capital/solmate/blob/51b2a9e28bdbbf2ce1bfe22947cd2af6dd09d3b5/src/test/utils/DSTestPlus.sol#L102-L121) method to Solmate's `DSTestPlus` for this, where you specify the min and max (both inclusive) and it wraps the input to that range. Agreed it'd be nice to have that integrated directly though since it's a common need

**Comment by brockelmore** [comment]
yall can check out some stuff im working on [here](https://github.com/brockelmore/forge-std/). Has compiler injected panics, and writing to arbitrary slots. check out tests for some examples. Not saying that repo should be used long term but is def my hacking on what a std lib may include

**Comment by onbjerg** [comment]
Should we close this since we now just install Forge Std as part of `forge init`?
