### ISSUE TITLE
Unable to call function on local testnet contract

### ISSUE THREAD

**Issue by matteosantama** [foundry-rs/foundry#1650]
### Component

Cast, Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (aea417b 2022-05-17T17:11:06.835167Z)

### What command(s) is the bug in?

cast call

### Operating System

macOS (Apple Silicon)

### Describe the bug

I'm not sure if this is a bug or if I'm just using the tools incorrectly (sorry, still a bit new to crypto development).

I've written a simple contract 

```solidity
contract Contract {

    constructor () payable {
    }

    function take(string calldata _msg) external {
        if (keccak256(abi.encodePacked(_msg)) == keccak256("foo")) {
            uint256 _balance = address(this).balance;
            payable(msg.sender).transfer(_balance);
        }
    }
}
```

I started anvil, and deployed my contract with `forge create --private-key <secret_key_from_anvil>  src/Contract.sol:Contract --value 1ether`

When I run `cast balance 0x5fbdb2315678afecb367f032d93f642f64180aa3` (the address of the created contract) I see the 1eth that was deposited. However, I can't invoke the `take` function

```
❯ cast call 0x5fbdb2315678afecb367f032d93f642f64180aa3 take "foo"
The application panicked (crashed).
Message:  Must set ETHERSCAN_API_KEY
Location: /Users/matteosantamaria/foundry/cast/src/tx.rs:162

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
[1]    93822 abort      cast call 0x5fbdb2315678afecb367f032d93f642f64180aa3 take "foo"
```

Is this the correct way to call the function? I don't see why an `ETHERSCAN_API_KEY` would be necessary to call a contract on a local test chain.

**Comment by matteosantama** [comment]
If this is indeed the right way to invoke the function, I am happy to submit a PR. But I want to check I'm using the right command before I start debugging

**Comment by mattsse** [comment]
cc @onbjerg _requiring_ an etherscan key to be set seems indeed excessive and should be optional here?

**Comment by mattsse** [comment]
ah, I see now, the etherscan is invoked because we failed to parse the function sig `take`, and etherscan is fallback, 

could you try `take(string)` instead?

**Comment by matteosantama** [comment]
yes that work! thanks
