### ISSUE TITLE
remappings create incompatibilities between libarires

### ISSUE THREAD

**Issue by TimDaub** [foundry-rs/foundry#1657]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

0.1.0

### What command(s) is the bug in?

generally

### Operating System

macOS (Intel)

### Describe the bug

- consider how in this project, my remappings map openzeppelin's library as "openzeppelin-contract": https://github.com/whitecube-online/balot/blob/3ed4f8a8c08bd59fad1f404597e3c1c2f7312499/remappings.txt#L1
- However, another library chose to remap to "@openzeppelin": https://github.com/botdad/chain-claim/blob/d9bee752457e400ab3eac9988b6c7a755e7ff925/remappings.txt#L1

Now, e.g. if I have a project setup with `'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/'` but then integrate e.g. botdad's chain-claim, I'll be forced to use the `@openzeppelin` remapping.

- Currently, that's manageable for me as I'm only integrating one library that has this incompatibility between remappings. But image now e.g. solmate used a different remapping and I also wanted to integrate it: thing would start get really tricky...

**Comment by onbjerg** [comment]
Rolling up into https://github.com/foundry-rs/foundry/issues/1855 as they are the same issue
