### ISSUE TITLE
Forge - Error with struct MethodNotice

### ISSUE THREAD

**Issue by pedrommaiaa** [foundry-rs/foundry#1662]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (c0667c5 2022-05-18T00:14:33.408951Z)

### What command(s) is the bug in?

forge build --extra-output abi --extra-output userdoc --extra-output devdoc --extra-output evm.methodIdentifiers --force

### Operating System

macOS (Apple Silicon)

### Describe the bug

Failing to compile with the following error:

```
Error:
   0: invalid type: string "<@notice string here>", expected struct MethodNotice at line 1 column 5492
```

It looks like it's giving this error for all `@notice` comments, If I delete the notice comment it complains about another one.

**Comment by pedrommaiaa** [comment]
This is the command used with [crytic-compile](https://github.com/crytic/crytic-compile/blob/master/crytic_compile), you can check it [here](https://github.com/crytic/crytic-compile/blob/master/crytic_compile/platform/foundry.py#L60).

**Comment by mattsse** [comment]
stupid question, but where's the project dir in that repo? @pedrommaiaa

**Comment by pedrommaiaa** [comment]
Thank you @mattsse! Do you know when this should be up on forge?

**Comment by mattsse** [comment]
will bump ethers in a sec
