### ISSUE TITLE
Forge caching issues

### ISSUE THREAD

**Issue by onbjerg** [foundry-rs/foundry#1666]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (05e72b6 2022-05-19T00:03:30.647862736Z)

### What command(s) is the bug in?

forge build

### Operating System

Linux

### Describe the bug

This is a consolidation of bugs that are suspected to be cache related:

- https://github.com/foundry-rs/foundry/issues/1629
- https://github.com/foundry-rs/foundry/issues/1344

## Issue 1

- [ ] Check if solved

**Bug**: Sometimes `forge test` does not run any test files.

**Workaround**: You can run `forge clean` before `forge test`

## Issue 2

- [ ] Check if solved

**Bug**: Sometimes a file is changed and that edit is not picked up by `forge test`, which will then not recompile that contract. There is no reliable way to reproduce this currently.

**Comment by shogochiai** [comment]
"issue 2" happened to me as well.

`forge 0.2.0 (4fcd7e0 2022-05-26T00:08:37.693306Z)`

I have two test files, and the ignored one is a collection of failing specs that use `expectRevert()`

A change made for the other test file is immediately detected and can be tested.

**Comment by mattsse** [comment]
from tg 

> I can’t remember/figure out exactly when it happens but often I’d notice that only changed/recompiled test files are being run

it sounds like we're not getting all Tests on recompile

will try to pin this down now

**Comment by 0xYYY** [comment]
encounter an issue probably related to this

2-line change from master branch: https://github.com/foundry-rs/foundry/compare/master...0xYYY:no-tests

1. add an invalid line in `testdata/cheats/Cheats.sol`, should cause compilation failure.
2. add a check in `forge/src/multi_runner.rs` test `test_cheats`: `assert!(suite_result.len() > 0);`
3. run `cargo test test_cheats` will fail with
```
     Running unittests (target/debug/deps/forge-b71ceab7b7a80d10)

running 1 test
test multi_runner::tests::test_cheats ... FAILED

failures:

---- multi_runner::tests::test_cheats stdout ----
thread 'multi_runner::tests::test_cheats' panicked at 'assertion failed: suite_result.len() > 0', forge/src/multi_runner.rs:1018:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    multi_runner::tests::test_cheats

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 6 filtered out; finished in 2.70s

error: test failed, to rerun pass '-p forge --lib'
``` 
4. remove the line in `testdata/cheats/Cheats.sol` and run `cargo test test_cheats` again, all tests pass

**Comment by onbjerg** [comment]
We haven't had caching issues in a long time, so I'm assuming this is resolved for now :smile:

**Comment by zhiqiangxu** [comment]
I still met this issue with latest version:

```bash
% forge --version
forge 0.2.0 (1710187 2024-08-20T00:18:53.474556000Z)
```

But it's hard to reproduce, as it's gone after a manual `forge clean`.
