### ISSUE TITLE
Integrate signature database into forge and cast

### ISSUE THREAD

**Issue by samczsun** [foundry-rs/foundry#1672]
### Component

Forge, Cast

### Describe the feature you would like

1. Swap `cast 4byte`, `cast 4byte-decode`, and `cast 4byte-event` to use the new signature database. This would allow multiple lookups based on function/event selectors or names (with globbing support), and smarter decoding (by checking the `filtered` field). For example, notice how all the spoofed ERC20 selectors are [filtered](https://sig.eth.samczsun.com/api/v1/signatures?all=true&function=0xa9059cbb&function=0x23b872dd)

2. Add a command to `forge` which would automatically upload the ABI to the signature database. This would make it easier for people who use Foundry to either manually contribute their functions for use by others, or automate it with a GitHub action.

The case for switching from 4byte to my alternative is simply that I provide a more accessible API, light curation for selectors with near-canonical meanings (f.ex ERC20), and a larger dataset with data I've collected myself. The reference can be found [here](https://sig.eth.samczsun.com/reference).

**Comment by gakonst** [comment]
I am supportive of this, also 4byte has had reliability issues for a while.

**Comment by marktoda** [comment]
Love the new signature database -- pushed up a change for 1): https://github.com/foundry-rs/foundry/pull/1674. Working on 2) but bit more involved

**Comment by SamWilsn** [comment]
How would you feel about an offline database? [`etk-4byte`](https://crates.io/crates/etk-4byte) packs the entire 4byte database into a crate. It needs a bit of polish to cut down on startup time, but if there's interest, I can implement that.

**Comment by mattsse** [comment]
> How would you feel about an offline database? [`etk-4byte`](https://crates.io/crates/etk-4byte) packs the entire 4byte database into a crate. It needs a bit of polish to cut down on startup time, but if there's interest, I can implement that.

that's an additional 10MB https://github.com/quilt/etk/blob/master/etk-4byte/src/database.br

I think we should rather think about a way to dl this to `./foundry/cache/4byte` or something than to embed this

**Comment by SamWilsn** [comment]
I didn't mean to suggest that the current implementation in `etk-4byte` is a good one :rofl:

Changing it to a download+cache implementation is what I was implying by "polish."

**Comment by sambacha** [comment]
> ### Component
> Forge, Cast
> 
> ### Describe the feature you would like
> 1. Swap `cast 4byte`, `cast 4byte-decode`, and `cast 4byte-event` to use the new signature database. This would allow multiple lookups based on function/event selectors or names (with globbing support), and smarter decoding (by checking the `filtered` field). For example, notice how all the spoofed ERC20 selectors are [filtered](https://sig.eth.samczsun.com/api/v1/signatures?all=true&function=0xa9059cbb&function=0x23b872dd)
> 2. Add a command to `forge` which would automatically upload the ABI to the signature database. This would make it easier for people who use Foundry to either manually contribute their functions for use by others, or automate it with a GitHub action.
> 
> The case for switching from 4byte to my alternative is simply that I provide a more accessible API, light curation for selectors with near-canonical meanings (f.ex ERC20), and a larger dataset with data I've collected myself. The reference can be found [here](https://sig.eth.samczsun.com/reference).
> 
> ### Additional context
> _No response_

you can automate this already with a webhook if ur using `ethereum-lists/4bytes` using [https://github.com/apps/4bytebot](https://github.com/apps/4bytebot)

How big is your data set? I have one that covers all test networks and  event log signatures as well. 

Can you provide a webhook endpoint @samczsun?

**Comment by samczsun** [comment]
The dataset is as big as the stats endpoint claims it to be and should contain approximately every valid signature from ethereum mainnet. I'm currently importing signatures from any other evm-compatible chain I can find.

I don't support webhook endpoints and I don't have plans to at this point because there's no good way to do it. 4byte does it by throwing the Solidity source code through some [magical regex](https://github.com/pipermerriam/ethereum-function-signature-registry/blob/094a2307711bb73edac958a0769499198cbe03fa/func_sig_registry/utils/solidity.py#L70-L86) which is extremely brittle and also won't work with any non-primitive type (think contract types, structs, etc) because if you really wanted to resolve all of those references (including stuff like importing from GitHub), you basically have to compile the code anyways. Since I don't know how to compile your codebase (and I don't want to just `npx hardhat compile` arbitrary repositories), it's much easier if you
1) Flatten the source code like you would with Etherscan, then submit it as a code import
2) Just compile it yourself, and submit it as an ABI import. This is what #1676 will do

(If you have any ideas for how to handle webhooks, I'm all ears. I can't think of any reliable approaches though)

**Comment by marktoda** [comment]
Hey @samczsun noticing some strange filtering from the `api/v1/signatures` route suddenly - just starting today:
```
❯ curl https://sig.eth.samczsun.com/api/v1/signatures\?function\=0xa9059cbb
{"ok":true,"result":{"event":{},"function":{"0xa9059cbb":[]}}}
❯ curl https://sig.eth.samczsun.com/api/v1/signatures\?function\=0xa9059cbb\&all\=true
{"ok":true,"result":{"event":{},"function":{"0xa9059cbb":[{"name":"many_msg_babbage(bytes1)","filtered":true},{"name":"transfer(address,uint256)","filtered":false},{"name":"transfer(bytes4[9],bytes5[6],int48[11])","filtered":true},{"name":"func_2093253501(bytes)","filtered":true}]}}}
```

Seems it is filtering out `transfer(address,uint256)` when `all=false` even though it is not tagged as filtered. Any idea on why this might be?

**Comment by samczsun** [comment]
Oops, not sure what happened there. Will get it fixed shortly

**Comment by samczsun** [comment]
Should be fixed now

**Comment by marktoda** [comment]
Thanks!

**Comment by gakonst** [comment]
Fixed in https://github.com/foundry-rs/foundry/pull/1676 and https://github.com/foundry-rs/foundry/pull/1674
