### ISSUE TITLE
feat: automatically detect `test` and `script` folders for remappings

### ISSUE THREAD

**Issue by mds1** [foundry-rs/foundry#1673]
### Component

Forge

### Describe the feature you would like

I have test files that import other test files, and prefer using absolute path imports since they are more readable and don't break as often. To do that, I have to add `remappings = ["test/=test/"]`

With scripting on the way, a root `scripts` folder with a deploy file will be common, and many users will likely use this to deploy their test suite and therefore will want to import from the script folder. Therefore when testing out #1208 my remappings are now `remappings = ["test/=test/", "scripts/=scripts/"]`

It feels a bit silly to have to declare those remappings for common, root-level directories, so the feature request here is to include those in the automatic detection to remove the need for that. More generally, it my be worth considering automatically detecting all root level folders.

**Comment by mattsse** [comment]
we do something similar with the `src` folder already where we be default allow a `src/=src/` remapping so users can use absolute paths from the `src/` dir as imports.

seems like we can solve this by simply extending this with `test` and `scripts`?

**Comment by mds1** [comment]
> seems like we can solve this by simply extending this with `test` and `scripts`?

Yep, that is exactly the solution I had in mind!
