### ISSUE TITLE
Since today, cargo install fails to run on GitHub Actions

### ISSUE THREAD

**Issue by TimDaub** [foundry-rs/foundry#1679]
### Component

Other (please describe)

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

latest?

### What command(s) is the bug in?

cargo install --git https://github.com/gakonst/foundry --bin forge --locked

### Operating System

Linux

### Describe the bug

- The following has started to happen across multiple repositories using the same script: https://github.com/rugpullindex/ERC4973/runs/6526963505?check_suite_focus=true#step:7:1
- Script: https://github.com/rugpullindex/ERC4973/blob/master/.github/workflows/main.yml

**Comment by mattsse** [comment]
we migrated from https://github.com/gakonst/foundry/ to https://github.com/foundry-rs/foundry/ so please update the links

closing this as this seems to be a redirect issue, but please lmk if there's an issue after updating the urls

**Comment by mattsse** [comment]
nevermind, this is an issue because we now have multiple bins in our workspace

**Comment by mattsse** [comment]
there's now an additional argument required:

`cargo install --git https://github.com/foundry-rs/foundry --locked foundry-cli`

will update the readme
