### ISSUE TITLE
Allow Solidity variables to be replaced using Foundry

### ISSUE THREAD

**Issue by Amirjab21** [foundry-rs/foundry#1680]
### Component

Forge

### Describe the feature you would like

This is a feature that is most helpful when I fork a contract but would like to replace some of the variables (without the contract having an explicit function to change the variable)

**Comment by onbjerg** [comment]
You can already do this using `vm.store`: https://book.getfoundry.sh/cheatcodes/store.html

Let me know if this is not sufficient; you can also take a look at https://book.getfoundry.sh/reference/forge-std/std-storage.html if you use Forge Std :)

**Comment by hcheng826** [comment]
@onbjerg is there a way to replace a `constant` or `immutable` variable? `vm.store` doesn't work as they are not in storage slot. Or is there a way to `mockCall` to override the constructor?

My use case is that I deploy a new contract in the constructor and save the contract address as immutable variable. While in my unit test, I want to override the implementation of that contract

```
pragma solidity ^0.8.0;

contract DataExtractor {
    function extractData(bytes32 dataId) public pure returns (uint256) {
        return uint256(dataId);
    }
}

contract DataFetcher {
    address public immutable dataExtractor;

    constructor() {
        dataExtractor = address(new DataExtractor());
    }

  // other functions that uses dataExtractor
}
```
