### ISSUE TITLE
feat: Stack traces for contracts deployed with vm.getCode

### ISSUE THREAD

**Issue by jameswenzel** [foundry-rs/foundry#1690]
### Component

Forge

### Describe the feature you would like

This is probably not at all trivial, but: it would be very helpful to include informative stack traces in test output and code source in the debugger when using `vm.getCode`, and that code comes from a Forge output folder. 

### Additional context

Our test suite relies on deploying pre-compiled contracts: one set using 0.8.13 and via_ir=true, and another using 0.8.7 and via_ir=false. Neither configuration is really appropriate for the test suite – IR compilation is slow, and 0.8.13 has more convenience methods.
We were able to partially work around this by [conditionally deploying some contracts normally](https://github.com/ProjectOpenSea/seaport/blob/463bf8add301c7b3a326093122303dcc9658f0d0/test/foundry/utils/BaseConsiderationTest.sol#L40) in the Seaport test suite, but this is not always possible, especially if a set of contracts requires a different compiler version or cannot be compiled with the test suite configuration.

**Comment by onbjerg** [comment]
I'm not entirely sure what is being asked here/what is missing, can you elaborate? Are the traces not decoding properly, or do you want some extra info in them?

**Comment by jameswenzel** [comment]
@onbjerg Ah, apologies, you're right. I just realized this is/was due to using the IR-pipeline, not because of `vm.getCode`. Sounds like there's no way to get source mapping for those besides compiling without IR.
Should probably close this 😅

**Comment by elanzalaco** [comment]
Hi @jameswenzel 
I'm encountering the same issue when using `deployCode` I don't get stack traces which makes things like gas reports empty as they do not show unknown functions. 

To give more context, we are using viaIR and deploying from precompiled out-optimised folder similar to Seaport. 

I saw your edit " import the precompiled contracts" but I wasn't able to get that to show stack traces.

How did you get around this, if at all?
