### ISSUE TITLE
feat: Reading environment variables from forge test

### ISSUE THREAD

**Issue by jameswenzel** [foundry-rs/foundry#1691]
### Component

Forge

### Describe the feature you would like

In certain circumstances, it would be very helpful if Forge tests could read pre-configured variables (either from `foundry.toml` or sourced from the bash environment) for conditional/context-specific logic, without the need to use the potentially unsafe `vm.ffi` cheatcode.

### Additional context

The Seaport test suite [uses `vm.ffi`](https://github.com/ProjectOpenSea/seaport/blob/463bf8add301c7b3a326093122303dcc9658f0d0/test/foundry/utils/BaseConsiderationTest.sol#L40) with what is essentially a no-op to conditionally compile+deploy a set of contracts normally in order to surface stack traces and source code in the debugger when a specific Foundry profile is active.

We have included a warning about the dangers of using `ffi`, but it would be even better if we did not have to use it at all.

**Comment by mattsse** [comment]
how about `env_{string, uint,int}("string") -> {string, uint,int}` cheatcodes?

**Comment by jameswenzel** [comment]
Cheatcodes would be great!
