### ISSUE TITLE
Transaction underpriced

### ISSUE THREAD

**Issue by bitcoinmeetups** [foundry-rs/foundry#1703]
forge create --rpc-url https://polygon-mainnet.g.alchemy.com/v2/NDF-tLzxxxxxxxxxxxx --constructor-args "bushman" "BSH" --private-key af180013952262434794a2cd8xxxxxxb src/NFT.sol:NFT results in "transaction underpriced" error.

Is that a generic term for "insufficient funds in the wallet"? Or is it referring to something else? I was assuming that Polygon would be rather cheap to deploy to.

Is there a way to estimate the deployment cost before creating, if that is the issue?

**Comment by mattsse** [comment]
> Is that a generic term for "insufficient funds in the wallet"

that's rather an issue with gasprice ref https://github.com/ethers-io/ethers.js/issues/2828

perhaps that's an issue with the rpc so an insufficient gasprice was set.

deploying on Mumbai works?

**Comment by robertu7** [comment]
Same issue with Polygon Mainnet (mumbai is OK), guess it's related issue with https://github.com/ethers-io/ethers.js/issues/2828#issuecomment-1073423774.

I am using `forge create xxx --legacy` for temp workaround.

**Comment by ZeroEkkusu** [comment]
@mattsse I haven't found a more recent issue on this. The problem may be the minimum 30 gwei priority fee on Polygon Mainnet (as described in https://github.com/ethers-io/ethers.js/issues/3370). Is this something that can be patched in Foundry?

**Comment by robriks** [comment]
running into the same issue, can confirm that adding --legacy tack, ie:

```forge create <stuff> --legacy```

is an acceptable current workaround for anyone also encountering this issue

**Comment by ZeroEkkusu** [comment]
@robriks, is it happening again? Have you updated Foundry?

**Comment by robriks** [comment]
updating foundry fixed this. thanks for checking in!

**Comment by mattsse** [comment]
this has since been fixed with dedicated polygon gas station

**Comment by Anmol-Dhiman** [comment]
![image](https://github.com/foundry-rs/foundry/assets/82818771/b764646d-2b82-4224-858f-5ed74f097f05)
getting the same error with polygon mumbai testnet

**Comment by smarsx** [comment]
Using Mumbai, I'm still intermittently having issues with gas estimation. I can usually get transactions posted using --legacy or --skip-simulation and --gas-estimate-multiplier
