### ISSUE TITLE
Forge test crashes due to broken pipe

### ISSUE THREAD

**Issue by naps62** [foundry-rs/foundry#1709]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (c0667c5 2022-05-18T00:11:45.21540785Z)

### What command(s) is the bug in?

forge test (but probably applies to others)

### Operating System

Linux

### Describe the bug

I'm trying to parse the output for some 3rd party tooling.
When running `forge test --json`, there's a lot of noise around the actual json content, so I need to pipe it into other commands in other to filter out the noise

Currently trying to run `forge test --json | head -n 2 | tail -n 1`. This should give me the 2nd line of output, which should consistently match the json

However, this triggers the following error:
```
❯ forge test --match-path test/AnotherContract.t.sol --match-contract ContractTest --json | head -n 1                                                                       
No files changed, compilation skipped                                                 
The application panicked (crashed).                                                   
Message:  failed printing to stdout: Broken pipe (os error 32)                        
Location: library/std/src/io/stdio.rs:1164                                            
                                                                                      
Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.      
Run with RUST_BACKTRACE=full to include source snippets.                              
zsh: IOT instruction (core dumped)  forge test --match-path test/AnotherContract.t.sol --match-contract  --json |                                                           
zsh: done                           head -n 1    
```

**Comment by gakonst** [comment]
Which part is noisy? Maybe we should adjust the json output in some way.

**Comment by naps62** [comment]
By noisy I meant that it can't be directly piped to other tooling that expects JSON input (e.g.: the VS Code yes runner I was setting up)

The first line will always be the "No files changed. Compilation skipped"
And in case of test failures, there's other output afterwards as well if I recall correctly (can't check right now, at the airport)

I considered seeing if it was trivial to suppress that output in some way (maybe using the existing TTY flag). But for now I just went with piping the output to `sed` for filtering

**Comment by mattsse** [comment]
we can already suppress compiler related output

https://github.com/foundry-rs/foundry/blob/master/cli/src/compile.rs#L208

so what if we add a `--silent` flag, if present we don't show compiler output?
