### ISSUE TITLE
`cast wallet new keystore.json` panics

### ISSUE THREAD

**Issue by peter-ciccolo** [foundry-rs/foundry#1712]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (fc534d9 2022-05-23T00:08:08.582332Z)

### What command(s) is the bug in?

cast wallet new

### Operating System

macOS (Intel)

### Describe the bug

This command is suggested in the foundry book.
https://book.getfoundry.sh/reference/cast/cast-wallet-new.html

In general `cast wallet new` does not seem to work with empty or nonexistent keystore files, though it usually manifests in different errors.

**Comment by nikkolasg** [comment]
Just fell on this as well, msg is:
```
The application panicked (crashed).
Message:  called `Option::unwrap()` on a `None` value
Location: cli/src/utils.rs:91

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Aborted (core dumped)
```

**Comment by onbjerg** [comment]
Related to #926
