### ISSUE TITLE
`forge fmt` deletes all inline comments

### ISSUE THREAD

**Issue by marktoda** [foundry-rs/foundry#1724]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (44f26a8 2022-05-25T00:04:15.359167797Z)

### What command(s) is the bug in?

forge fmt

### Operating System

Linux

### Describe the bug

Running `forge fmt` deletes all of my inline comments. I love the formatter (especially the `--check` output), but can't use it in write mode currently because of this issue. This may be tracked somewhere already, but couldn't find it

example `forge fmt --check` output showing the intention to delete inline comment
```
855 848  |     }
856 849  | 
857 850  |     function testXYZ(uint128 seed, uint8 count) public {
858      |-        // note lorem ipsum
860 852  |         uint256[] memory tokenIds = new uint256[](count);
861 853  |         uint256[] memory amounts = new uint256[](count);
--------------------------------------------------------------------------------
```

**Comment by mattsse** [comment]
comments are still wip, see #1682

**Comment by marktoda** [comment]
ah, nice. thanks
