### ISSUE TITLE
`Forge verify-contract ...` returns a broken etherscan link after it runs

### ISSUE THREAD

**Issue by dd0sxx** [foundry-rs/foundry#1735]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (135cb12 2022-02-28T00:39:31.066361+00:00)

### What command(s) is the bug in?

forge verify-contract

### Describe the bug

When running forge verify-contract, it returns a broken link in the terminal after success.
It appears as if the address of the verified contract gets sliced, rendering the link useless.

This should be an easy fix to return the etherscan link in full without slicing the contract 

for reference, this is the link that was returned to me: `https://goerli.etherscan.io//address/0x0967…15c8#code`. If you follow it you can see that it leads to a "contract not found" page on Etherscan

**Comment by onbjerg** [comment]
This is a simple bug in ethers-rs where it uses display formatting instead of debug formatting

**Comment by onbjerg** [comment]
You are not on the latest version of Forge. Please run:

```
curl -L https://foundry.paradigm.xyz | bash
foundryup
```

The latest version is forge 0.2.0 (4fcd7e0 2022-05-27T00:04:10.635343079Z)
