### ISSUE TITLE
Remappings Edge Case with JS Monorepos

### ISSUE THREAD

**Issue by tynes** [foundry-rs/foundry#1739]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (c0667c5 2022-05-18T00:11:45.21540785Z)

### What command(s) is the bug in?

forge build

### Describe the bug

I am working in a JS monorepo and am getting an error when trying to import contracts from a different package in the monorepo with the error: `File outside of allowed directories`.

In JS monorepos, there is a `node_modules` at the base of the directory for shared dependencies between packages and then each package can have a `node_modules` folder for dependencies specific for that package. I'm able to set `nohoist` to keep certain packages in the package's `node_modules` which solves the problem of `forge` not having access to the base `node_modules`, since that will explicitly prevent a dependency from being hoisted to the base, but I still cannot import contracts in other packages in the monorepo. 

The packages look like this:

```
packages/
  |- contracts/
  |- contracts-bedrock/
```

`contracts-bedrock` imports `contracts`, and the JS monorepo set up a symlink in `contracts-bedrock/node_modules` that points to `packages/contract`.

My remappings looks like:
```
remappings = [
  '@eth-optimism/contracts/=node_modules/@eth-optimism/contracts/contracts',
  'solmate/=node_modules/@rari-capital/solmate/src',
  'forge-std/=node_modules/forge-std/src',
  'ds-test/=node_modules/ds-test/src'
]
```

My workspace nohoist config looks like:
```
[
  "@eth-optimism/contracts-bedrock/ds-test",
  "@eth-optimism/contracts-bedrock/forge-std",
  "@eth-optimism/contracts-bedrock/@rari-capital/solmate",
  "@eth-optimism/contracts-bedrock/@eth-optimism/contracts"
]

```

Could it be possible to either expose the `solc --allow-paths` through `foundry.toml` config or automatically add values if a symlink is detected and add the resolved absolute path of the symlink?

**Comment by gakonst** [comment]
@tynes can you try using the new allow paths Config value?

**Comment by tynes** [comment]
This just works now, I think it was https://github.com/gakonst/ethers-rs/pull/1317. I didn't have to configure `allow_paths`, thank you for the quick turnaround!
