### ISSUE TITLE
Anvil crashes with: `Failed to get storage`

### ISSUE THREAD

**Issue by sunwrobert** [foundry-rs/foundry#1746]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (fc534d9 2022-05-23T00:04:01.500526763Z)

### What command(s) is the bug in?

anvil --fork-url

### Operating System

Linux

### Describe the bug

Hi foundry team, I'm from the OpenSea team. We're currently in the process of trying to migrate from hardhat in our e2e tests to anvil and are running into some issues. It appears that anvil crashes during our testing with a pretty obscure error. 

Full trace: 
```
project-polygon-mainnet-1  | thread 'fork-backend-thread' panicked at 'Failed to get storage for 0x8f3c…a063 at 63793490285618327566453423202919073693767156451540437757185495221258080913552
project-polygon-mainnet-1  | error sending request for url (https://polygon-mainnet.g.alchemy.com/v2/XXXXXXXXXXX): connection error: connection reset', /home/runner/work/foundry/foundry/evm/src/executor/fork/backend.rs:302:33
project-polygon-mainnet-1  | note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
project-polygon-mainnet-1  | ./scripts/run_polygon.sh: line 5:    10 Aborted                 (core dumped) anvil --host 0.0.0.0 --fork-url="https://polygon-mainnet.g.alchemy.com/v2/XXXXXXXXXXXXXXXXX" --fork-block-number=28798565 --port=8545
```

Any idea what's going on here? 

Would also be great if we could have a direct contact for assistance in this migration if that would be possible. Thanks!

**Comment by mattsse** [comment]
> `error sending request for url (https://polygon-mainnet.g.alchemy.com/v2/XXXXXXXXXXX): connection error: connection reset'`

looks like you hit a connection reset error.
we currently panic/crash in fork mode if we can't connect because that's the safe way.

since alchemy updated how they count their units, we've been Hit with a lot of 429 rate limit errors, we're about to integrate a rate aware provider that automatically does retries.

**Comment by sunwrobert** [comment]
Are you also aware of any read timeouts? Have been getting a decent amount of errors regarding that. Don't think it's completely related to the above as was seeing read timeout logs at times where there weren't any crashes

**Comment by mattsse** [comment]
wdym by "read timeouts"?

**Comment by sunwrobert** [comment]
Our client that hits our RPC node (anvil), for example getting the latest block, just times out, due to anvil not sending us a response back. This only happens later on in our test cycle. Sorry I don't have more concrete numbers.

**Comment by mattsse** [comment]
there was an issue that could lead to situation like that, which was fixed in https://github.com/foundry-rs/foundry/pull/1689 68acdf52de5a5a951419ad788ad4e9ba508c6011

the version you referenced predates that fix, should be included in nightly though

**Comment by sunwrobert** [comment]
Seem to still be hitting that issue, but would love to try again when the rate aware provider you mentioned before gets implemented. Any idea on when that would be?

**Comment by gakonst** [comment]
@sunwrobert the rate limiting should be present in the latest version, can you give it another try?

**Comment by sunwrobert** [comment]
The rate limiting seems to have fixed it. I do still have other issues but will open a separate issue for those. Thanks!
