### ISSUE TITLE
Bug: foundry reports successful creation of a repo when using --template to nonexisting url

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#1747]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### Operating System

macOS (Intel)

### Describe the bug

running this command just report a failure, but instead reports it as sucessful 
```bash
$ forge init --template github.com/sambacha/zen-template
Initializing /Users/sbacha/foundry-boilerplate from https://github.com/github.com/sambacha/zen-template...
Cloning into '/Users/sbacha/foundry-boilerplate'...
remote: Not Found
fatal: repository 'https://github.com/github.com/sambacha/zen-template/' not found
    Initialized forge project.
```

**Comment by mattsse** [comment]
cc @0xYYY looks like we're missing another git check somewhere

**Comment by sambacha** [comment]
> cc @0xYYY looks like we're missing another git check somewhere
💯 thx!
