### ISSUE TITLE
Updating foundry decreased pseudo-randomness?

### ISSUE THREAD

**Issue by 0xBeans** [foundry-rs/foundry#1753]
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (4fcd7e0 2022-05-27T00:04:39.67082Z)

### What command(s) is the bug in?

forge test --gas-report -vvv

### Operating System

macOS (Apple Silicon)

### Describe the bug

I used to be on fairly old version of foundry (probably at least a month old) and updated it yesterday - this caused a couple tests to fail.

I have this function which essentially takes a `uint256 dna` and replaces 14 bits of it with pseudo-random bits at a specific 'slot'. Essentially every 14 bits of the dna is associated with a certain 'trait' (a 'slot') and this function rerolls that certain slot.

```
    function rerollTrait(uint256 tokenId, uint256 traitBitShiftMultiplier)
        external
    {
        uint256 currDna = dna[tokenId];

        unchecked {
            uint256 newTraitDna = (uint256(
                keccak256(
                    abi.encodePacked(
                        msg.sender,
                        block.difficulty,
                        block.timestamp,
                        _seed++,
                        tokenId
                    )
                )
            ) % 10000) << (14 * traitBitShiftMultiplier);

            uint256 newBitMask = ~(BIT_MASK << (14 * traitBitShiftMultiplier));

            currDna &= newBitMask;
            currDna |= newTraitDna;
        }

        dna[tokenId] = currDna;
    }
```

This function splits the dna into its slots and returns an array of the traits that correspond to the dna.

```
    function getTraitIndexes(uint256 dna)
        external
        view
        returns (uint256[NUM_TRAITS] memory traitIndexes)
    {
        // splits the dna into 14 bit slots
        uint256[NUM_TRAITS] memory traitDnas = splitDna(dna);

        for (uint256 i = 0; i < NUM_TRAITS; i++) {
            // from the 14 bit slots, grab the trait it refers to
            uint256 traitIndex = getTraitIndex(traitDnas[i], i);
            traitIndexes[i] = traitIndex;
        }
    }
```

This is my test

```
    function testRerollTrait() public {
        // mint a few tokens first 

        uint256 tokenid = 0;
        uint256 traitBitshift = 2;

        uint256[9] memory oldDnaIndexes = contract.getTraitIndexes(
            contract.dna(tokenid)
        );

        contract.rerollTrait(tokenid, traitBitshift);
  
        // dna should be different after we rolled traits
        uint256[9] memory newDnaIndexes = contract.getTraitIndexes(
            contract.dna(tokenid)
        );

        assertEq(oldDnaIndexes[0], newDnaIndexes[0]);
        assertEq(oldDnaIndexes[1], newDnaIndexes[1]);
        require(oldDnaIndexes[2] != newDnaIndexes[2]); // make sure proper slot got rerolled, THIS FAILS IN TEST
        assertEq(oldDnaIndexes[3], newDnaIndexes[3]);
        assertEq(oldDnaIndexes[4], newDnaIndexes[4]);
        assertEq(oldDnaIndexes[5], newDnaIndexes[5]);
        assertEq(oldDnaIndexes[6], newDnaIndexes[6]);
        assertEq(oldDnaIndexes[7], newDnaIndexes[7]);
        assertEq(oldDnaIndexes[8], newDnaIndexes[8]);
    }
```

When running this test, `oldDnaIndexes` should return something like `[1,2,0,0,5,6,7,2]` and  `newDnaIndexes` should return  `[1,2,3,0,5,6,7,2]` where the 3rd index shouldve changed.

This test passed on the older version of foundry I was running but when I updated it, it failed (both arrays returned are the exact same). I rewrote the test in hardhat and it passes, so the discrepancy was confusing.

It turns out, if I `vm.warp()` to random large timestamps before I `rerollTrait()`, the test begins passing. This is strange since `_seed` used in `keccak256()` is incremented every time a trait is rerolled (or a mint happens) and this should add enough entropy for the hash to be completely different (it works in hardhat). However, now, the newest version of foundry doesnt behave the same unless I add more randomness via `vm.warp()`

Not sure exactly what changed or if this is expected behavior?

Thanks :)

**Comment by onbjerg** [comment]
I don't think the pseudo-randomness was decreased, but `block.difficulty` (I think), `block.timestamp` and `block.number` now default to 1 instead of 0, which may be the reason it fails?

**Comment by 0xBeans** [comment]
Quite possibly, but it is strange though since `_seed` is constantly incremented... keccack256() should still be quite different with that small change

vm.warp() makes my test pass though, so Ill close the issue. Just found it quite strange
