### ISSUE TITLE
Broken link for code for Foundry book - EIP-721

### ISSUE THREAD

**Issue by 0xSchellen** [foundry-rs/foundry#1765]
### Component

Other (please describe)

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (c38f71b 2022-05-29T14:55:29.6122431Z)

### Operating System

Windows

### Describe the bug

Hi! I´m reading the wonderful foundry book and doing the excellent tutorials.

Just noted that the link for the code is broken at the end of page: https://book.getfoundry.sh/tutorials/testing-eip712.html

Thanks!

**Comment by gakonst** [comment]
Cc @kulkarohan

**Comment by kulkarohan** [comment]
@0xSchellen just fixed! sorry about that
