### ISSUE TITLE
bug: `prank` takes effect on local event emissions

### ISSUE THREAD

**Issue by OliverNChalk** [foundry-rs/foundry#1768]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6ca977f 2022-05-29T02:05:46.434519993Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

## Details

Does not work:
![image](https://user-images.githubusercontent.com/11343499/170893628-ecf22cd5-a13a-44b0-b36b-3a3240fe0a7a.png)

Works:
![image](https://user-images.githubusercontent.com/11343499/170893615-f01c6eae-b13e-45a2-8c52-a9d560781308.png)

`prank` is not used up by calls to `vm` which is my alias for `HEVM_ADDRESS`/cheatcodes.

- As such, it stands to reason that the event emission is being treated as a `CALL`?
- I would have thought emitting an event is a `JUMP` and would not have used up `prank`?

## Proposed Next steps

- [ ] Confirm/deny this is expected behavior
- [ ] **Optionally** open a PR handling the case of local event emissions consuming `prank`
- [ ] **Optionally** document this behavior in the `book` or `Vm.sol` inside `forge-std`

**Comment by gakonst** [comment]
Isn't the prank used by the owner() call you're making? Pranks are not consumed by log emission

**Comment by OliverNChalk** [comment]
That's embarassing, gotta check my eyesight it seems - closed

**Comment by gakonst** [comment]
all good - thx for flagging!
