### ISSUE TITLE
Ensure remappings use `/` on windows

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#1777]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### Describe the bug

As seen here #1776 remappings are constructed with `\` 

this should be mitigated with the `path-slash` crate, we already use on ethers-solc.

best place to use this would be in the config's remappings provider as a post process step

**Comment by j-vp** [comment]
Probably related to this issue as well (and maybe #1776): `forge remove` & `forge update` can't find the submodules.

In the example below; `update` doesn't fetch the newest Script cheatcodes, and `remove`ing cannot find "lib\\forge-std"

![image](https://user-images.githubusercontent.com/104004836/171165727-09eee0e8-e302-44a5-92f7-bf9606f57fce.png)

**Comment by mattsse** [comment]
thanks for flagging, let's track all of these in a new issue for windows path compatibility
