### ISSUE TITLE
Best in class Gas Reporting

### ISSUE THREAD

**Issue by w1nt3r-eth** [foundry-rs/foundry#1795]
### Component

Forge

### Describe the feature you would like

Make it easy for the Foundry users to identify & optimize gas usage of their contracts.

Currently, the gas is reported as a single number next to the test cases or function names.

|inline|summary|
|-|-|
|<img width="825" alt="image" src="https://user-images.githubusercontent.com/93895766/171267747-775cecf8-6270-4637-a014-281366ab7247.png">|<img width="825" alt="image" src="https://user-images.githubusercontent.com/93895766/171267840-6551c5c7-5b09-4c8e-88e5-4fa487dc1578.png">|

This doesn't help new users understand what's taking up all the gas in the transaction. The lack of insights pushes users to adopt questionable hacks (e.g. `unchecked`) vs optimizing the heavy operations (like `SSTORE`).

Here are a few ideas on how to improve gas reporting visuals:

## Opcodes Histogram

Group every opcode executed in the transaction by the opcode itself (maybe `SSTORE`/`SLOAD` need flags like hot/cold) and plot the total cumulative gas consumption. Feels like this would be the easiest to implement as it only requires `debug_traceTransaction` and a hashmap.

The disadvantage here is that it's not obvious how to find the expensive operations in the contract without having a good idea of how Solidity & EVM work.

![image](https://user-images.githubusercontent.com/93895766/171268206-f9842503-fb21-4962-abc8-e7fe2cd6fa66.png)

## Flame Graph

This is a screenshot from Tenderly's gas profiler tool. It gives a good idea of which functions are contributing the most to gas consumption. Ideally, the lowest level should show heavy opcodes.

This probably requires an untrivial amount of work connecting gas usage to (obfuscated) function names.

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/93895766/171268822-eca72fc3-0ff3-4bb0-b998-61a82269ce9f.png">

## Export Systrace

Systrace is commonly used to debug the performance of large & complicated systems. Its ecosystem has a bunch of tools for processing and visualizations, so if we could export a compatible JSON file we could get a lot of this functionality for free.

This is very advanced, but also very hard to use for a regular user.

![image](https://user-images.githubusercontent.com/93895766/171293330-397b298e-c0a4-4dcc-8b87-104f85b8e183.png)

## Compare Before & After

A typical flow optimizing gas is to make a change and compare reports between previous and current runs. This is error-prone and fragile. We could store gas profiles in a temporary location and show if the numbers improved or got worse vs the last run.

With Opcodes Histogram or Flame Graph, we could use some color to highlight the differences in a very visual (and motivating) way.

## Tenderly Integration

Tenderly has decent visualizations and tools, but getting it to work with hardhat is a lot of pain. Thinking of an ideal DX here, maybe passing a flag to `forge` command could send the tx (along with everything else needed, like source code) to Tenderly and print out a URL to view the trace.

**Comment by mattsse** [comment]
thanks for this write up.

in order to support this, we need some kind of `Metrics/Diagnostic` type that keeps track of all the info. To some degree, this exists here

https://github.com/foundry-rs/foundry/blob/master/forge/src/gas_report.rs

to track this a bit more fine-grained we'd need a custom `revm::Inspector` I think. 

visualizing this is then just additional work.

ref #1737

**Comment by onbjerg** [comment]
Ref https://github.com/foundry-rs/foundry/issues/137

**Comment by zerosnacks** [comment]
Closing in favor of https://github.com/foundry-rs/foundry/issues/7761 for flamegraphs + https://github.com/foundry-rs/foundry/pull/8222 for lifting of required information for flamegraphs

Related tickets:
- https://github.com/foundry-rs/foundry/issues/2065 for improvements to gas snapshotting
