### ISSUE TITLE
weird remapping `lib/=lib/` required in some codebases

### ISSUE THREAD

**Issue by naps62** [foundry-rs/foundry#1797]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (54ec8e3 2022-05-31T00:04:13.132504939Z)

### What command(s) is the bug in?

forge build

### Operating System

Linux

### Describe the bug

In some codebases, an extra `lib/=lib/` remapping is required to overwrite what seems to be a wrong remapping introduced by forge

Example repo for reproduction: 
https://github.com/timeless-fi/swapper
Remove `lib/=lib/` from foundry.toml and run `forge build` to reproduce the error

**Initial investigation (by myself, may be off here)**

In the above example repo `forge remappings` will show `lib/=lib/timeless/src/lib/`, which seems to be the cause of the compilation issues.
Forge them seems to merge these default remappings with the ones from `remappings.txt`, which is why adding a weird `lib/=lib/` fixes the compilation, since it overwrites the default one

**Comment by naps62** [comment]
Ok, I got as far as narrowing it down to this section:
https://github.com/foundry-rs/foundry/blob/0e258fb191ad32db70a8a461763053990dc88789/config/src/lib.rs#L1772-L1775

with some print statements, I get that the following call is being made there:

```
insert_closest("lib/, "/home/naps62/contrib/timeless-fi/swapper/lib/timeless/src/lib/")
...

**Comment by mattsse** [comment]
thanks so much for this.

this is indeed happening in `Remapping::find_many`, I guess the `src/lib/` combination trips up the detection algo, will tune and also add an additional check here
