### ISSUE TITLE
Option to simulate a reorg for a local fork mode

### ISSUE THREAD

**Issue by krasi-georgiev** [foundry-rs/foundry#1799]
### Component

Anvil

### Describe the feature you would like

Add an api to simulate a block reorg for local fork mode

### Additional context

When writing tests for bots and libraries It would help to simulate reorgs to see how the library/bot handles it.

**Comment by mattsse** [comment]
I think this some hybrid of `reset` and snapshot perhaps?

what should anvil do on a `reorg(block)` call?

**Comment by krasi-georgiev** [comment]
Something like this?

head block is 1, calling reors(1) would create block 2 with block 1 as an uncle including all TX from block 1

later could even expand it as
head block is 1, calling reors(1,[]txs{1,2}) would create block 2 with block 1 as an uncle including only TX 1 and 2 from block 1

**Comment by sambacha** [comment]
you can do this with the admin commands as well see https://github.com/spalladino/reorg-tester

**Comment by krasi-georgiev** [comment]
Would it be possible to do the same in Anvil? this will simplify testing reorgs.

**Comment by krasi-georgiev** [comment]
@mattsse what do you think?

**Comment by mattsse** [comment]
sorry, missed this update, 

> head block is 1, calling reors(1) would create block 2 with block 1 as an uncle including all TX from block 1 

that should be possible

so we need:

- [ ] reorg rpc call that accepts
   - [ ] block where to reorg (default 1)
   - [ ] tx filter object

I think we can start with 1 block reorg, but how should it behave if we're on block 5 and want to do a 3 block reorg for example?

**Comment by krasi-georgiev** [comment]
maybe to keep things simple can just start by allowing to reorg only the last block and if there is a request for longer reorgs can revisit again.

**Comment by agnarsong** [comment]
There hasn't been any follow-up on this issue for 22 years. It seems to have been forgotten.

**Comment by ameya-deshmukh** [comment]
@mattsse any chance I could take this up? This would be very helpful for a lot of applications imo.
