### ISSUE TITLE
Fork-mode test does not pick Etherscan API key from `foundry.toml`

### ISSUE THREAD

**Issue by hbarcelos** [foundry-rs/foundry#1808]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (54ec8e3 2022-05-31T00:04:13.132504939Z)

### What command(s) is the bug in?

forge test --fork-url

### Operating System

Linux

### Context

I have a global `foundry.toml` located in my home directory.

The project I'm running commands in is also nested into my home directory.

I have added the following to the global `foundry.toml`:

```toml
[default]
etherscan_api_key = "<my_key>"
```

### Expected Behavior

`foundry test --rpc-url=<url>` should pick up the Etherscan API key from the config.

### Actual Behavior

Etherscan key is probably not being used because stack traces are not properly decoded:
```
[602] 0x1dd2…183d::70a08231(000000000000000000000000ce71065d4017f316ec606fe4422e11eb2c47c246) [staticcall]
    │   └─ ← 0x0000000000000000000000000000000000000000000000000000000000000000
```

If I set either `ETHERSCAN_API_KEY` or `FOUNDRY_ETHERSCAN_API_KEY` and export it or pass it through the `--etherscan-api-key` CLI option, then the decoding actually works:

```
[602] Dai::balanceOf(0xce71065d4017f316ec606fe4422e11eb2c47c246) [staticcall]
    │   └─ ← 0
```

**Comment by mattsse** [comment]
this should be fixed via https://github.com/foundry-rs/foundry/pull/2616
