### ISSUE TITLE
Feat: support `forge install --branch` and `forge uninstall`

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#1810]
### Component

Forge

### Describe the feature you would like

```shell
forge install github.com/Rari-Capital/solmate -b v7
```

should be like
```shell
git submodule--helper add -b v7 https://github.com/Rari-Capital/solmate.git vendor
```

```shell
forge uninstall Rari-Capital/solmate
```

**Comment by sambacha** [comment]
so runnin the command above actually introduces a bug

```
$ git status
fatal: not a git repository: lib/solmate/../../.git/modules/lib/solmate
```

**Comment by 0xYYY** [comment]
currently installing a specific branch is possible with `forge install github.com/Rari-Capital/solmate@v7`

**Comment by sambacha** [comment]
> currently installing a specific branch is possible with `forge install Rari-Capital/solmate@v7`

i understood that to be a tag not a branch. Either way it should be changed to reflect the flag -b imho.

**Comment by onbjerg** [comment]
Already supported with `@` - anything after is a Git ref, so it can be a commit, a branch or a tag

**Comment by sambacha** [comment]
> Already supported with `@` - anything after is a Git ref, so it can be a commit, a branch or a tag

but branches can be the same as a tag name - they are not the same

**Comment by onbjerg** [comment]
I don't see a plausible scenario where you have a tag and a branch with the same name that are out of sync indefinitely - do you have an example?

**Comment by sambacha** [comment]
> I don't see a plausible scenario where you have a tag and a branch with the same name that are out of sync indefinitely - do you have an example?

Tags are versioned releases whereas branches are both a versioned release and includes compilation artifact. The reason compilation artifact is included in branches and not tags is to reduce merge conflicts etc. History is continued on tags, whereas branches are basically moribund
