### ISSUE TITLE
Forge --sizes missing contracts

### ISSUE THREAD

**Issue by sakulstra** [foundry-rs/foundry#1815]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [x] Foundryup

### What command(s) is the bug in?

forge build --sizes

### Operating System

Linux

### Describe the bug

I checked out [this repository](https://github.com/bgd-labs/example-aave-v2-listing) on master and ran `make build`(forge build --sizes --force) which returns:
```
╭───────────────────┬───────────┬─────────────╮
│ Contract          ┆ Size (kB) ┆ Margin (kB) │
╞═══════════════════╪═══════════╪═════════════╡
│ AaveGovHelpers    ┆ 0.141     ┆ 24.435      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ AaveV2Helpers     ┆ 1.772     ┆ 22.804      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ ENSListingPayload ┆ 2.449     ┆ 22.127      │ <------------------the contract i'm intersted in
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ console           ┆ 0.141     ┆ 24.435      │
╰───────────────────┴───────────┴─────────────╯
```
On [my branch](https://github.com/bgd-labs/example-aave-v2-listing/pull/1) where I wanted to check size implications of a certain lib it now returns:
```

╭───────────────────┬───────────┬─────────────╮
│ Contract          ┆ Size (kB) ┆ Margin (kB) │
╞═══════════════════╪═══════════╪═════════════╡
│ AaveAddressBookV2 ┆ 17.282    ┆ 7.294       │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ AaveGovHelpers    ┆ 0.107     ┆ 24.469      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ DataTypes         ┆ 0.107     ┆ 24.469      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ console           ┆ 0.107     ┆ 24.469      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ console2          ┆ 0.107     ┆ 24.469      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ stdError          ┆ 1.017     ┆ 23.559      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ stdMath           ┆ 0.107     ┆ 24.469      │
├╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌┼╌╌╌╌╌╌╌╌╌╌╌╌╌┤
│ stdStorage        ┆ 0.619     ┆ 23.957      │
```
Running with `forge build --sizes --force --via-ir`
Missing the contract i wanted to check for size implication.

**Comment by ryanli-me** [comment]
encountered the same issue while trying to separate some logic into a linked library. The contract we are concerned about disappeared from the table.

**Comment by onbjerg** [comment]
Interesting, maybe it's only with libraries and contracts that use libraries?

**Comment by onbjerg** [comment]
Closing this per @mattsse's comment. Let us know if this is still an issue for you on the latest nightly though, and we can re-examine :smile:
