### ISSUE TITLE
`forge script --broadcast` cannot handle large amounts of broadcasted transactions

### ISSUE THREAD

**Issue by j-vp** [foundry-rs/foundry#1816]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (0342bc2 2022-06-02T12:05:16.9019022Z)

### What command(s) is the bug in?

forge script src/script/paperTradingCompetition/DeployScript.sol --rpc-url $rpcUrl -vvvv --broadcast --private-key $PrivKey

### Operating System

Windows

### Describe the bug

Using `forge script --broadcast` on a large script causes unexpected results.

In our protocol, our 'script' broadcasts around 400 transactions. This includes about 100 contract deployments (including testnet mock contracts😅) , the rest are function calls.

Foundry runs through the simulations correctly:

![image](https://user-images.githubusercontent.com/104004836/171627953-4ea41071-5282-420a-88ed-712ede2265b1.png)

and seemingly generates the transactions correctly:
![image](https://user-images.githubusercontent.com/104004836/171628265-f0427e29-4966-4ac7-a536-04ac25a0d7aa.png)

Upon starting broadcast, it logs that it sends 2-4 transactions, then errors with a list of transaction hashes that haven't been broadcasted.

![image](https://user-images.githubusercontent.com/104004836/171626430-5daf90c0-1d36-438e-9b4c-93ecf248a7b5.png)

The error message suggests to launch the same command with `--resume`.
After doing so, a similar thing happens: 2-4 transactions are logged, then it errors.

![image](https://user-images.githubusercontent.com/104004836/171626753-9d85fdc1-abbc-4700-98bb-054169fcc71d.png)

Strangely, more transactions **are** broadcasted (between 30 and ~200 per run, can't find the logic behind it). For example, see the deploy history of https://rinkeby.etherscan.io/txs?a=0x362e058e129e4b7c4c8b161d3c121661de1c9d07 . The above screenshots caused all transactions in blocks 10782135 to 10782157 (which are about 75 txes).

After another new `--broadcast` command, I notice that some of the transactions which are "sent but not logged" fail. I assume that after the simulations, broadcasted txes aren't supposed to fail? This was a single `forge script --broadcast` command, which logged 4 transactions sent, but actually broadcasted ~200 transactions (without any `--resume`). These are the transactions between blocks 10782260 and 10782279 at https://rinkeby.etherscan.io/txs?a=0x362e058e129e4b7c4c8b161d3c121661de1c9d07 .

Running the `--broadcast` with `--slow` does seem to not cause it to timeout/..., although it isn't practical in our case to wait 400 blocks. I haven't ran it to completion yet, as it takes a bit too long to wait for it.

Not sure if related, but Infura shows a lot of 'invalid' rpc calls:
![image](https://user-images.githubusercontent.com/104004836/171628647-2f38e65e-6e7c-46e1-b33a-5de9bf325bcb.png)

Only foundry scripting uses this endpoint.

**Comment by joshieDo** [comment]
Maybe we should be sending batches of 20-50 instead. And try to call `--resume` by ourselves a couple times, before showing the error to the user.

**Comment by j-vp** [comment]
> It doesn't show in your screenshot, but you should be getting a message saying `Add --resume ...` . After you call with `--resume`, do you still have it happening ?
> 
> I tried with 100 transactions, and it worked fine: `--broadcast` will eventually "fail", but then `--resume` resolves everything. Even if you have to call `--resume` a couple times 😅

The second large screenshot is after a `--resume`. Here again 2 transactions were logged, and approx.. 30 were sent out at the time. Hard to start pinpointing it, but some transactions which are broadcasted-but-not-logged seem to fail when being broadcasted, although being simulated correctly. Is there anywhere a log/verbosity where I can see which transaction calls which function or deploys which contract?

**Comment by j-vp** [comment]
Trying some more `--resume` commands. Eventually 371 transactions get through.
78 transactions don't get through, no matter how many `--resume`s I try. They're nicely listed in the broadcast/../run-latest.json though. It prints no new transactions, and instantly returns the following error:

![image](https://user-images.githubusercontent.com/104004836/171655527-364c34be-c3c2-4b30-bc74-8f73da84216d.png)



![image](https://user-images.githubusercontent.com/104004836/171655682-3b6a9760-f53b-45e5-90fc-b78a8b449d26.png)

**Comment by j-vp** [comment]
After some more tests done with #1824 , this issue seems to be resolved. Thanks Joshie, the progress bar is also a neat feat!
