### ISSUE TITLE
How can I check the balance of a specific token at a specific address?

### ISSUE THREAD

**Issue by bitcoinmeetups** [foundry-rs/foundry#1818]
Hello,

I'm MB. A very nice and polite guy.

How can I check the balance of a specific token at a specific address?

Let's say Dai token at 0x0xxxxxx (Polygon).

Looking for the easiest method using forge or cast.

**Comment by mattsse** [comment]
see the example https://book.getfoundry.sh/reference/cast/cast-call.html#examples 

`cast call` also has a `--chain` flag  and `--rpc-url` for providing the rpc endpoint

**Comment by j-vp** [comment]
[https://book.getfoundry.sh/cast/index.html](https://book.getfoundry.sh/cast/index.html) shows a very similar example.

cast:
`cast call 0x6b175474e89094c44da98b954eedeac495271d0f "balanceOf()(address)" --rpc-url https://eth-mainnet.alchemyapi.io/v2/<apikey>`

if you want to use it in a forge test, you can use `--fork-url` ([see here](https://book.getfoundry.sh/forge/forking-mode.html?highlight=fork#forking-mode)). In your test, import the balanceOf function in an interface, and call it in your test to the address of your token.

```
pragma solidity ^0.8.13;

interface IERC20 {
  function balanceOf(address) external view returns (uint256);
}

contract getBalance {
  ...
  
  function fetchBalance(address tokenAddress, address holder) public view returns (uint256 balance) {
    balance = IERC20(tokenAddress).balanceOf(holder);
  }

  ...
}
```

**Comment by bitcoinmeetups** [comment]
This input:

cast call 0x02E4b884Df5bB66B13bf7B04a957F45acF39025F "balanceOf()(0x92c819e24Cb020e35Fce434a3
3E39Fd5C85AB2aA)" --rpc-url https://polygon-mainnet.g.alchemy.com/v2/NDF-tLzxxxxxxxx

Generates this error message:

Error: UnrecognisedToken 12:54 `0x0x92c819e24Cb020e35Fce434a33E39Fd5C85AB2aA`

Removing the initial 0x from the input also doesn't work.
