### ISSUE TITLE
Sourcify support

### ISSUE THREAD

**Issue by jjhesk** [foundry-rs/foundry#1822]
### Component

Forge

### Describe the feature you would like

I have checked a several ways to verify codes for [blockscout](https://github.com/blockscout/blockscout/releases/tag/v4.1.3-beta) v4.1.3 or above. There is no api-key needed for [verification](https://docs.blockscout.com/for-users/verifying-a-smart-contract/contracts-verification-via-sourcify). Currently there is a way to upload the standard json for the process however the json that created from the regular `forge` does not work. 

It should be nice to have blockscout specific solution for source verifications with this flag `--blockscout`

for example:
```
forge create --rpc-url "https://rpc1.oasischain.io" \
  --private-key "...." vault/stakingpoolv3/Woac.sol:Woac \
  --verify --legacy --blockscout

```

**Comment by onbjerg** [comment]
Blockscout uses Sourcify, so we should just support that

**Comment by gakonst** [comment]
@robertabbott check this out

**Comment by gakonst** [comment]
Fixed in #1872

**Comment by douglasqian** [comment]
+1

**Comment by rkrasiuk** [comment]
@onbjerg blockscout exposes etherscan like api, so current verification flow should work. see the description of https://github.com/gakonst/ethers-rs/pull/1343

**Comment by jerydam** [comment]
did i have to install anything to make blockscout work with foundry,
this is the error that I'm seeing

error: unexpected argument '--blockscout' found

  tip: to pass '--blockscout' as a value, use '-- --blockscout'

Usage: forge create --constructor-args <ARGS>... --verify <--rpc-url <URL>|--flashbots|--jwt-secret <JWT_SECRET>> <--interactive|--private-key <RAW_PRIVATE_KEY>|--mnemonic <MNEMONIC>|--mnemonic-passphrase <PASSPHRASE>|--mnemonic-derivation-path <PATH>|--mnemonic-index <INDEX>> <--gas-limit <GAS_LIMIT>|--gas-price <PRICE>|--priority-gas-price <PRICE>|--value <VALUE>|--nonce <NONCE>|--legacy> <CONTRACT>

For more information, try '--help'.
