### ISSUE TITLE
Anvil returns nothing when queried for past emitted smart contract events.

### ISSUE THREAD

**Issue by Ben-D-Anderson** [foundry-rs/foundry#1823]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e0a5372 2022-06-02T00:12:18.781761724Z)

### What command(s) is the bug in?

anvil

### Operating System

Linux

### Describe the bug

I am using the `web3py` python library and interacting with a smart contract deployed on `anvil`. The code is very similar to what is written [here](https://web3py.readthedocs.io/en/v5/contracts.html#event-log-object). The `filter#get_new_entries` method works perfectly, however `filter#get_all_entries` always returns an empty list, regardless of how many entries have actually happened. This even happens when the `fromBlock` is set to be the first block.

I know this is an `anvil` issue because the same issue is not found when using `hardhat`. Anvil is run with no parameters and no config, so all the defaults are used.

I also wrote Java code to listen for events using the `Web3j` library, and this could also not access past events when used with `anvil`.

From looking at other issues, I noted [this issue](https://github.com/foundry-rs/foundry/issues/1515) which may be of relevance to this issue. It is noted to be fixed, however [the fix](https://github.com/foundry-rs/foundry/pull/1556) just updated some tests and (as far as I can tell) not the source code of anvil. They suggest the issue could have been caused by the address topic in some way, however I don't use any topics with my two code tests other than the `fromBlock` parameter.

**Comment by mattsse** [comment]
not familiar with filtering in web3py, 
do you know what's the actual payload of `get_all_entries`?

**Comment by Ben-D-Anderson** [comment]
Yes, `eth_newFilter` and `eth_getFilterLogs`are used.

My code to create the contract filter is as follows:
```
event_filter = contract.events.Purchase.createFilter(fromBlock="0x0")
```
Note that I have also tried `"0"`, `"earliest"` etc. in the `fromBlock` field.

I tried debugging the python library and I believe it sends the following payload when creating the filter:
```
{'topics': ['0xd3aa7599e4b0c574b10dc23d7bf5acf28f2193861951c1ba95a90f8a68073fa0'], 'address': '0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512', 'fromBlock': '0x0', 'toBlock': 'latest'}
```
The `address` field's value is the address of the smart contract. I have no idea what the random address in the `topic` field is, sorry I'm not particularly well versed in blockchain technology. The `topic` address doesn't seem to appear anywhere in the `anvil` output, smart contract source code or my python code.

Then as far as I can tell, when `get_all_entries` is called, it sends the address `0x4e697876646e5941504f316a33634e72` to the `getFilterLogs` endpoint. I am guessing this is the identifier of the filter.

**Comment by mattsse** [comment]
If you could provide a python script which would allow me to replicate this, that'd be helpful

**Comment by Ben-D-Anderson** [comment]
Using your own smart contract abi file, the following code should resemble my setup (note: you must replace `EVENT_NAME` with the name of the event in your smart contract):
```python3
import sys
from web3 import Web3

if len(sys.argv) != 4:
    print("Usage: python3 event_listener <rpc> <contract_address> <contract_abi_file>", flush=True)
    exit()

provider = Web3.HTTPProvider(sys.argv[1])
web3 = Web3(provider)

contract_address = Web3.toChecksumAddress(sys.argv[2])
contract_abi = '[]'
with open(sys.argv[3], 'r') as f:
    contract_abi = f.read().strip()
contract = web3.eth.contract(address=contract_address, abi=contract_abi)

#replace 'EVENT_NAME' with event name
event_filter = contract.events.EVENT_NAME.createFilter(fromBlock='0x0')
for event in event_filter.get_all_entries():
    print(Web3.toJSON(event), flush=True)
```
The above code should print out all events that have been emitted by the contract (I tested it unsuccessfully on `anvil` but successfully on `hardhat`).
I don't have python code to the emit the events, only java code - so you'll have to manually emit the events somehow or write the code to do that.
