### ISSUE TITLE
using `forge script` with alchemy outputs error 429

### ISSUE THREAD

**Issue by beskay** [foundry-rs/foundry#1826]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e0a5372 2022-06-02T00:12:18.781761724Z)

### What command(s) is the bug in?

forge script

### Operating System

Linux

### Describe the bug

Running `forge script <PATH> --tc <contract> -vvv --rpc-url $ETH_RPC_URL --broadcast --private-key $PK` with Alchemy outputs 
```
Error: 
   0: ["(code: 429, message: Your app has exceeded its compute units per second capacity. If you have retries enabled, you can safely ignore this message. If not, check out https://docs.alchemyapi.io/guides/rate-limits, data: None)"]
```
Judging by [this](https://github.com/gakonst/ethers-rs/pull/1302) recent PR that bug should be fixed, but Im still getting that error.

Steps to reproduce:
1. Head over to my [repo](https://github.com/beskay/solidity-challenges)
2. Clone it
3. Run `forge script ./scripts/deploy.sol --tc Deploy -vvv --rpc-url $ETH_RPC_URL --broadcast --private-key $PK`

**Comment by onbjerg** [comment]
It seems you are being rate limited - are you entirely out of capacity, or is it just going too fast? The PR you linked to might not be used in `forge script`

**Comment by beskay** [comment]
Yes, Alchemy rate limits me. 

Im not out of capacity though, its just going too fast. If I add --slow it works (as expected).

**Comment by mattsse** [comment]
retry and rate limits are now handled in script
