### ISSUE TITLE
use Retry provider in forge script

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#1829]
### Component

Forge

### Describe the feature you would like

#1826 shows we can run into ratelimit issues in forge script

we should be able to solve this by using 

https://github.com/foundry-rs/foundry/blob/7e9eba5656c9371679e8963fb83900f0961982c8/anvil/src/eth/backend/fork.rs#L393

for the provider in forge script

**Comment by gakonst** [comment]
Of note that we may want to be more aggressive with how we submit requests and maybe nto want to have a exponential backoff but a linear backoff retry

**Comment by gakonst** [comment]
Closing - fixed in #1824
