### ISSUE TITLE
Issue warning on remappings to directories that do not exist

### ISSUE THREAD

**Issue by peter-ciccolo** [foundry-rs/foundry#1835]
### Component

Forge

### Describe the feature you would like

`remapping.txt` appears to silently accept some types of malformed lines.

```
> echo foobar > ./remapping.txt
> forge remappings
[forge panics here]
```

```
> echo "foo=bar" > ./remapping.txt
> forge remappings

foo=bar/
```

AFAICT this mapping won't be used (because there is no slash at the end of `foo`), but it's not clear this is the case. Would be nice if this flavor of mistake was detected, especially since it's easy to make.

**Comment by onbjerg** [comment]
Can you please post the panic? This should not cause a panic - I also don't think it uses `remapping.txt`, just `remappings.txt` but I'm not sure

**Comment by peter-ciccolo** [comment]
Yes, sorry, it's `remappings.txt` indeed.

Panic:
```
config error: no prefix found in Remapping Provider
The application panicked (crashed).
Message:  failed to extract foundry config
Location: config/src/lib.rs:355
```

**Comment by onbjerg** [comment]
Ah right - but this does indeed mean that we don't accept malformed remappings already, right? The error is: "config error: no prefix found in Remapping Provider"

Is this issue about improving that message (I agree it's a bit vague)?

**Comment by peter-ciccolo** [comment]
No, the issue is the second example.

`foo=bar`

Will be silently accepted, but I don't think it does anything. (Specifically, it interacts poorly with autodetected `foo/=baz`)

**Comment by onbjerg** [comment]
That remapping is not malformed, it just points to something that doesn't exist - it's still valid, since the format is valid. We can add a check to see if the destination exists, but I don't think it should result in an error. At most I think it should be a warning

**Comment by peter-ciccolo** [comment]
Fair enough. I think a warning would be helpful.

**Comment by peter-ciccolo** [comment]
To clarify, what is the difference between `foo=bar/` and `foo/=bar/`? If there is none, I think these remappings should not be allowed to cooexist.

**Comment by gakonst** [comment]
Hmm I guess we could throw an error for malformed remappings that do not have a trailing `/`, although I thought we internally append that trailing `/` to fix things if it doesn't exist? cc @mattsse

**Comment by onbjerg** [comment]
The difference is that with the `foo=bar/` remapping `foo/something.sol` would be rewritten as `bar//something.sol`, and for `foo/=bar/` it would be rewritten as `bar/something.sol` - it's a dumb string replace.

The implication of not supporting remappings w/o trailing slash is that this remapping would not work:

`ERC20.sol=some/library/ERC20.sol` (which means you can now import `ERC20.sol` instead of using the full path)

**Comment by gakonst** [comment]
OK - convinced, great argument @onbjerg. Closing then.
