### ISSUE TITLE
Tests "disappear" from watcher

### ISSUE THREAD

**Issue by devtooligan** [foundry-rs/foundry#1836]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (da73576 2022-06-04T00:18:01.078301Z)

### What command(s) is the bug in?

forge test -w

### Operating System

macOS (Apple Silicon)

### Describe the bug

Sometimes tests disappear from the watcher.  In this example (see gif below), all I did was delete a commented line in a test contract and hit save.

Test summary went from this:

![Screen Shot 2022-06-04 at 9 52 05 AM](https://user-images.githubusercontent.com/71567643/172017300-f55645c8-bfa0-46b2-9326-d122f0ae6ff9.png)

to this:

![Screen Shot 2022-06-04 at 9 53 07 AM](https://user-images.githubusercontent.com/71567643/172017308-f1f68bda-3981-48d2-9a6d-c4953117c285.png)

For some reason, the watcher is now only reporting on the test contract that I just updated (by deleting a comment).

If I switch to a different test file and update.  Then the focus of the watcher goes to that new file and all other tests are ignored:

![Screen Shot 2022-06-04 at 9 49 41 AM](https://user-images.githubusercontent.com/71567643/172017205-fc28ecbe-f454-4890-b44e-32b77574c936.png)

The solution is to ^c and restart forge -w.

See gif below, and please let me know if there's any more helpful info I can provide.

![disappearing_tests1](https://user-images.githubusercontent.com/71567643/172017031-80ec019b-dbfa-4299-892d-ab740caba04b.gif)

**Comment by mattsse** [comment]
this could be due to how we rerun tests on changed files,
if you want to always run _all_ tests I'd recommend running with `-w --run-all`

**Comment by gakonst** [comment]
Yeah I think this is desired behavior - `--watch` will only rerun things that have changed
