### ISSUE TITLE
Crash when calling blockhash

### ISSUE THREAD

**Issue by naps62** [foundry-rs/foundry#1848]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8f04865 2022-06-01T18:00:10.960060401Z)

### What command(s) is the bug in?

forge script

### Describe the bug

I'm Trying to find a way to solve [Ethernaut #03](https://ethernaut.openzeppelin.com/level/0x4dF32584890A0026e56f7535d0f2C6486753624f) using forge scripting

This exercise requires me to send 10 different transactions, that should go into 10 separate blocks (otherwise they're reverted). They also check `blockchash(block.number - 1)` for all of them. When forge script tries to simulate my execution, I'm running into problems with the `blockhash` call

Here's a snippet of my solution:

```
contract Ethernaut03 is Ethernaut {
    address constant factory =
        address(0x4dF32584890A0026e56f7535d0f2C6486753624f);

    function run() public {
        vm.startBroadcast();
        ICoinFlip flip = ICoinFlip(createNewInstance(factory));

        for (uint256 i = 0; i < 10; ++i) {
            console.log(block.number);
            console.logBytes32(blockhash(block.number - 1));

            // trigger a tx, with a guess for the current block
            flip.flip(guess());

            vm.roll(block.number + 1);
        }
   }
}
```

Without `vm.roll`, each call to `flip.flip` would end up in the same block (meaning the 2nd call would fail).
With `vm.roll`, it actually panics with:

```
The application panicked (crashed).
Message:  Failed to get block hash for 10803750
block 10803750 not found
Location: /home/naps62/.foundry/foundry-rs/foundry/evm/src/executor/fork/backend.rs:320
```

**Comment by onbjerg** [comment]
I understand the use case, but it can't work like this: there is no way for us to know blockhashes in the future, so the crash is to be expected

**Comment by naps62** [comment]
@onbjerg Thanks. My issue is not necessarily with this not being supported. It's more about getting a random crash with no clear explanation. What you just explained sounds like something that a proper error message should explain to me

As for a feature, it's not fully clear to me what a proper one would be (which is why I structured the issue this way)

obviously I can't expect forge to find the real hashes of future mainnet blocks. My main problem is then how to deal with scripts that use `--slow` in order to consume different blockhashes, but which forge will first try to simulate (either crashing, or ending up simulating with fake blockhashes and cause unrealistic results)

I'm fine with opening a separate issue, but I don't necessarily want to ask for a specific feature, because I don't know what the sensible approach would be
