### ISSUE TITLE
Dependencies Remappings - config error: stream did not contain valid UTF-8 in Remapping Provider

### ISSUE THREAD

**Issue by danielturato** [foundry-rs/foundry#1849]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (3fc1491 2022-06-06T09:52:25.986569Z)

### What command(s) is the bug in?

forge remappings

### Operating System

Windows

### Describe the bug

I attempted to do:
```bash
forge remappings > remappings.txt
```
which works and outputs the following:
```
ds-test/=lib\forge-std\lib\ds-test\src/
forge-std/=lib\forge-std\src/
```
But if you now do forge build or forge test, I get this:
```
(base) PS D:\insurance-project> forge remappings > remappings.txt
(base) PS D:\insurance-project> forge build
config error: stream did not contain valid UTF-8 in Remapping Provider
The application panicked (crashed).
Message:  failed to extract foundry config
Location: config\src\lib.rs:355

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
(base) PS D:\insurance-project> forge test
Error: 
   0: stream did not contain valid UTF-8 in Remapping Provider

Location:
   cli\src\cmd\forge\test.rs:291

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
(base) PS D:\insurance-project> 
```

Also, if you just simply execute forge remappings standalone, you receive the same error:
```
(base) PS D:\insurance-project> forge remappings
config error: stream did not contain valid UTF-8 in Remapping Provider
The application panicked (crashed).
Message:  failed to extract foundry config
Location: config\src\lib.rs:355
Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

Without a remappings.txt file, forge build & test work fine.

**Comment by onbjerg** [comment]
Can you try adding a second slash to the backwards slashes? I think it is interpreting them as escaped characters:

```
ds-test/=lib\\forge-std\\lib\ds-test\\src/
forge-std/=lib\\forge-std\\src/
```

Alternatively, just use forward slashes:


```
ds-test/=lib/forge-std/lib/ds-test/src/
forge-std/=lib/forge-std/src/
```

**Comment by danielturato** [comment]
> Can you try adding a second slash to the backwards slashes? I think it is interpreting them as escaped characters:
> 
> ```
> ds-test/=lib\\forge-std\\lib\ds-test\\src/
> forge-std/=lib\\forge-std\\src/
> ```
> 
> Alternatively, just use forward slashes:
> 
> ```
> ds-test/=lib/forge-std/lib/ds-test/src/
> forge-std/=lib/forge-std/src/
> ```

Thanks for the suggestions. However, I've attempted both with escaping the slashes + forwards slashes, but still produce same error:
```
(base) PS D:\insurance-project\contracts> forge build
config error: stream did not contain valid UTF-8 in Remapping Provider
The application panicked (crashed).
Message:  failed to extract foundry config
Location: config\src\lib.rs:355

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
(base) PS D:\insurance-project\contracts> forge build
config error: stream did not contain valid UTF-8 in Remapping Provider
The application panicked (crashed).
Message:  failed to extract foundry config
Location: config\src\lib.rs:355

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by gakonst** [comment]
@danielturato are you on latest master? `foundryup -b master1

**Comment by jeissoni** [comment]
Something similar happened to me.

My development environment is on Windows

What I did was change "\" to "/" then from the file explorer open the file and change how the file is being encoded when saving. It seems that when creating the file the encoding is UTF-16, it should be changed to UTF-8. I made this change from the open file and saving, at the bottom of the popup you can change the encoding of the file
