### ISSUE TITLE
getting missing implementation error in contract

### ISSUE THREAD

**Issue by SamShakespeare** [foundry-rs/foundry#1862]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (25241a6 2022-06-07T14:52:47.6081639Z)

### What command(s) is the bug in?

forge test

### Describe the bug

getting missing implementaion error, but all implementations are included in main contract
![image](https://user-images.githubusercontent.com/85254282/172423980-797045af-6e8d-4f7c-a6b3-b79d1afe8bf2.png)
here is th contract implementation:
![image](https://user-images.githubusercontent.com/85254282/172424226-f2e17d35-8b5a-4ae1-974a-e917f7e1340f.png)

the return variable ttlFYakuza is a private uint256

any help on why i would be getting this error? it does not give me an error on remix, so confused. thank you

**Comment by mattsse** [comment]
hmm

can you provide a minimal example, like the UGNFT contract, and the interface with the function? so we can investigate this

**Comment by SamShakespeare** [comment]
interface:
![image](https://user-images.githubusercontent.com/85254282/172430177-7d13e2b3-9dd1-4e18-ab8d-d3bd60b67730.png)

**Comment by mattsse** [comment]
It would be helpful if I didn't have to type it from the picture lol

**Comment by SamShakespeare** [comment]
i know lol it wouldnt let me upload .sol file

**Comment by SamShakespeare** [comment]
ill send as .txt

**Comment by SamShakespeare** [comment]
// SPDX-License-Identifier: Apache-2.0
pragma solidity 0.8.13;

interface IUGNFTs {
 
    struct FighterYakuza {
        bool isFighter;
        bool isGen0;
        uint8 level;
        uint8 rank;
        uint8 courage;
        uint8 cunning;
        uint8 brutality;
        uint8 knucks;
        uint8 chains;
        uint8 switchblade;
        uint8 machete;
        uint8 katana;
        uint16 scars;
        uint32 imageId;
        uint32 lastLevelUpgradeTime;
        uint32 lastRankUpgradeTime;
        uint32 lastRaidTime;
    }  
    //weapons scores used to identify "metal"
    // steel = 10, bronze = 20, gold = 30, platinum = 50 , titanium = 80, diamond = 100
    
    struct Weapon {
        uint8 durability;
        uint8 attack;
    }

    struct ForgeFightClub {
        bool isRevealed;
        uint8 boost;
        uint8 size;
        uint8 level;
        uint16 id;
        uint32 lastLevelUpgradeTime;
        uint32 lastSizeUpgradeTime;
        uint32 lastBoostTime;
        uint128 mintedBlockNumber;
        string name;
        string yakuzaFamily;
    }

    struct RingAmulet {
        uint8 level;
        uint32 lastLevelUpgradeTime;
        address owner;
    }

    function safeBatchTransferFrom(address _from, address _to, uint256[] calldata _ids, uint256[] calldata _amounts, bytes calldata _data) external;
    function levelUpFighters(uint256[] calldata, uint256[] calldata) external; // onlyAdmin
  //  function setTraitRank(uint16 , uint8 ) external; // onlyAdmin
  //  function setTraitCourage(uint16 , uint8 ) external; // onlyAdmin
  //  function setTraitCunning(uint16 , uint8 ) external; // onlyAdmin
  //  function setTraitBrutality(uint16 , uint8 ) external; // onlyAdmin
    function mintRingAmulet(address, bytes memory, uint256, bool ) external;//onlyAdmin  
    function checkUserBatchBalance(address user, uint256[] calldata tokenIds) external view returns (bool);
    function isFighter(uint256 tokenId) external view returns (bool);
    function getRing(uint256 ) external view returns (RingAmulet memory);
    function getAmulet(uint256 ) external view returns (RingAmulet memory);
    function getFighters(uint256[] calldata) external view returns (FighterYakuza[] memory);
    function levelUpRingAmulets(uint256[] calldata , uint256[] calldata ) external;
    function addAdmin(address) external; // onlyOwner 
    function removeAdmin(address) external; // onlyOwner
   // function getFighterIDsForUser(address) external view returns (uint256[] memory);
    function getTotalFighterYakuza()  external view returns (uint256);
}

**Comment by SamShakespeare** [comment]
// SPDX-License-Identifier: Apache-2.0
pragma solidity 0.8.13;

import "./ERC1155/tokens/UGPackedBalance/UGMintBurnPackedBalance.sol";

import "./ERC1155/utils/Ownable.sol";
import "./interfaces/IUGNFTs.sol";
import "@openzeppelin/contracts/utils/Strings.sol";
//import "./ERC1155/tokens/ERC1155/ERC1155Metadata.sol";



contract UGNFTs is ERC1155MintBurnPackedBalance, IUGNFTs, Ownable {

  //IUGame public uGame;
  /*///////////////////////////////////////////////////////////////
                            TOKEN BASE  IDS
//////////////////////////////////////////////////////////////*/


uint32 constant FIGHTER = 100000;
uint16 constant RING = 5000;
uint16 constant AMULET = 10000;
uint16 constant FIGHT_CLUB = 20000;
uint16 constant FORGE = 15000;
uint8 constant GOLD = 5;

uint128 constant RING_MAX_SUPPLY = 4000;
uint128 constant AMULET_MAX_SUPPLY = 4000;

/*///////////////////////////////////////////////////////////////
                                YAKUZA FAMILIES
//////////////////////////////////////////////////////////////*/
string constant YAKUZA_FAMILY_1 = "YAMAGUCHI";
string constant YAKUZA_FAMILY_2 = "SUMIYOSHI";
string constant YAKUZA_FAMILY_3 = "INAGAWA";

  /*///////////////////////////////////////////////////////////////
                                 FIGHTERS
  //////////////////////////////////////////////////////////////*/  

  mapping(uint256 => FighterYakuza) idToFYakuza;
  mapping(uint256 => ForgeFightClub) idToFightClub;
  mapping(uint256 => ForgeFightClub) idToForge;
  mapping(uint256 => RingAmulet) idToRingAmulet;
  //maps     user  =>     base Type  =>  linked list tokenId => tokenId
  uint256 private constant GUARD = 1;

  

 
  uint16 private ttlRings;
  uint16 private ttlAmulets;
  uint256 private ttlFYakuzas;
  uint16 private ttlFightClubs;
  uint16 private ttlForges;
  //holds user balances of steel, bronze and gold weapons
  //mapping(address => uint256) private lowerWeaponsBalances;
  //holds user balances of platinum, titanium and diamond weapons
  //mapping(address => uint256) private upperWeaponsBalances;

  //maps user  => [address][bin][packed weapons balance]
  //mapping(address => mapping(uint256 => mapping(uint256 => uint256))) public weaponsBalances;
  //mapping(address => mapping(uint256 => uint256)) public weaponsBalances;

  /*///////////////////////////////////////////////////////////////
                              PRIVATE VARIABLES
  //////////////////////////////////////////////////////////////*/
  mapping(address => bool) private _admins;
  string private _tokenRevealedBaseURI;

  /*///////////////////////////////////////////////////////////////
                          FighterYakuza NAMES
  //////////////////////////////////////////////////////////////*/

  uint256 public nameFee;
  mapping(uint256 => string) public idToFighterNames;

  /*///////////////////////////////////////////////////////////////
                                EVENTS
   //////////////////////////////////////////////////////////////*/
  event LevelUp(uint256 tokenId, uint256 timestamp);
  event NameChange(uint256 tokenId);
  event UpdatedNameFee(uint256 namefee);
  event TokenMinted(address indexed owner, uint256 indexed tokenId);
  event TokenBurned(address indexed owner, uint256 indexed tokenId);

   /*///////////////////////////////////////////////////////////////
                                ERRORS
  //////////////////////////////////////////////////////////////*/
  error Unauthorized();
  error InvalidTokenID(uint256 tokenId);
  error MismatchArrays();
  error MaxSupplyReached();


  // set the initial name and base URI
 // constructor(string memory _name, string memory _baseURI)  {
  //  owner = msg.sender;
  
  //}


  /*///////////////////////////////////////////////////////////////
                    CONTRACT MANAGEMENT OPERATIONS
  //////////////////////////////////////////////////////////////*/

  modifier onlyAdmin() {
    if(!_admins[msg.sender]) revert Unauthorized();
    _;
  }

  modifier onlyFighter(uint32 tokenId) {
    if(tokenId >= FIGHTER + ttlFYakuzas ||
        tokenId <= FIGHTER) revert InvalidTokenID({tokenId: tokenId});
    _;
  }

   function addAdmin(address addr) external onlyOwner {
    _admins[addr] = true;
  }

  function removeAdmin(address addr) external onlyOwner {
    delete _admins[addr];
  }

  /*///////////////////////////////////////////////////////////////
                    MINT AND BURN FUNCTIONS
  //////////////////////////////////////////////////////////////*/
  function batchMintFYakuza(
    address _to, 
    uint256[] calldata tokenIds,
    FighterYakuza[] calldata oldFighters
  ) external  {
    if(tokenIds.length != oldFighters.length) revert MismatchArrays();

    uint256[] memory _ids = new uint256[](oldFighters.length);
    uint256[] memory _amounts = new uint256[](oldFighters.length);

    FighterYakuza memory newFighter;
    
    for(uint i = 0; i< oldFighters.length; i++){
      _ids[i] = tokenIds[i] + FIGHTER;
      _amounts[i] = 1;
      newFighter.isFighter = oldFighters[i].isFighter;
      newFighter.rank = oldFighters[i].isFighter ? 0 : oldFighters[i].rank;
      newFighter.courage = oldFighters[i].courage;
      newFighter.cunning = oldFighters[i].cunning;
      newFighter.brutality = oldFighters[i].brutality;
      newFighter.level = oldFighters[i].level;
      newFighter.scars = oldFighters[i].isGen0 ? 50 : 0 ;
      newFighter.lastLevelUpgradeTime = uint32(block.timestamp);
      newFighter.lastRaidTime =  uint32(block.timestamp);
      newFighter.lastRankUpgradeTime =  uint32(block.timestamp);
      newFighter.imageId = uint32(tokenIds[i]);

      idToFYakuza[uint32(_ids[i])] = newFighter;
      ttlFYakuzas ++;
     // _addFighterToOwner(_to, _ids[i]);
    }
    ttlFYakuzas ++;
    //update fighter balance for user
    _updateIDUserTotalBalance(_to, FIGHTER_INDEX, tokenIds.length, Operations.Add); // Add amount to recipient
    _batchMint( _to,  _ids, _amounts, "");
  }

  function mintRingAmulet(address _to, bytes memory _data, uint256 _level, bool isRing) external  {
    uint16 _id;
    //string memory name;
    if(isRing){
      if(ttlRings >= RING_MAX_SUPPLY) revert MaxSupplyReached();
      _id = ++ttlRings + RING;
      //update ring balance for user
      _updateIDUserTotalBalance(_to, RING_INDEX, 1, Operations.Add);

    } else {
      if(ttlAmulets >= AMULET_MAX_SUPPLY) revert MaxSupplyReached();
      _id = ++ttlAmulets + AMULET;
      //update amulet balance for user
      _updateIDUserTotalBalance(_to, AMULET_INDEX, 1, Operations.Add);
    }
    //string memory _name = string(abi.encodePacked(name,' ',Strings.toString(_id))) ;

    RingAmulet memory traits;
    traits.level = uint8(_level);
    traits.lastLevelUpgradeTime = uint32(block.timestamp);
    idToRingAmulet[_id] = traits;

    _mint( _to,  _id, 1,  _data);

    //if(isRing) _addRingToOwner(_to, _id);//add to linked list
    //if(!isRing) _addAmuletToOwner(_to, _id);//add to linked list
  }

  function mint(address _to, uint256 _id, uint256 _amount, bytes memory _data) public onlyAdmin {
   _mint( _to,  _id, _amount,  _data);
  }

  function batchMint(address _to, uint256[] memory _ids, uint256[] memory _amounts, bytes memory _data)
    public onlyAdmin
  {
    _batchMint( _to,  _ids, _amounts,  _data);

    //NEED TO UPDATE TOTAL SUPPLY BALANCES
    
  }

  function levelUpRingAmulets(uint256[] calldata tokenIds, uint256[] calldata levels) external onlyAdmin {
    if(tokenIds.length != levels.length) revert MismatchArrays();
    RingAmulet memory traits;
    for(uint i =0; i<tokenIds.length;i++){
      //tokenId must be a Ring or Amulet
      if(tokenIds[i] > AMULET + ttlAmulets ||
        tokenIds[i] <= RING) revert InvalidTokenID({tokenId: tokenIds[i]});
      traits = idToRingAmulet[tokenIds[i]];
      traits.level += uint8(levels[i]);
      traits.lastLevelUpgradeTime = uint32(block.timestamp);
      idToRingAmulet[tokenIds[i]] = traits;
      emit LevelUp(tokenIds[i], block.timestamp);
    }
  }

  function levelUpFighters(uint256[] calldata tokenIds, uint256[] calldata levels) external onlyAdmin {
    if(tokenIds.length != levels.length) revert MismatchArrays();
    FighterYakuza memory fy;
    for(uint i =0; i<tokenIds.length;i++){
      if(tokenIds[i] >= FIGHTER + ttlFYakuzas ||
        tokenIds[i] <= FIGHTER) revert InvalidTokenID({tokenId: tokenIds[i]});
      fy = idToFYakuza[tokenIds[i]];
      fy.level += uint8(levels[i]);
      fy.lastLevelUpgradeTime = uint32(block.timestamp);
      idToFYakuza[tokenIds[i]] = fy;
      emit LevelUp(tokenIds[i], block.timestamp);
    }
  }

  function setRaidTraits(uint32[] calldata tokenIds, uint16[] calldata _scars) external onlyAdmin {
    if(tokenIds.length != _scars.length) revert MismatchArrays();
    FighterYakuza memory FY;
    for(uint i =0; i<tokenIds.length;i++){
      if(tokenIds[i] >= FIGHTER + ttlFYakuzas ||
        tokenIds[i] <= FIGHTER) revert InvalidTokenID({tokenId: tokenIds[i]});
      FY = idToFYakuza[tokenIds[i]];
      FY.scars = _scars[i];
      FY.lastRaidTime = uint32(block.timestamp);
      //need to handle broken weapons scores etc
      idToFYakuza[tokenIds[i]] = FY;
    }
  }

  function getFighterIDsForUser(address user) external view returns (uint256[] memory){
    //get balance of fighters
    uint256 numFighters = getValueInBin(userTotalBalances[user], USER_TOTAL_BALANCES_BITS_SIZE, FIGHTER_INDEX);
    uint256[] memory _tokenIds = new uint256[](numFighters);
    //loop through user balances until we find all the fighters
    uint count;
    for(uint i; count<numFighters && i<FIGHTER + ttlFYakuzas; i++){
      if(balanceOf(user, FIGHTER + i) ==1){
        _tokenIds[count] = FIGHTER + i;
        count++;
      }
    }
    return _tokenIds;
  }

  function getRingIDsForUser(address user) external view returns (uint256[] memory){
    //get balance of fighters
    uint256 num = getValueInBin(userTotalBalances[user], USER_TOTAL_BALANCES_BITS_SIZE, RING_INDEX);
    uint256[] memory _tokenIds = new uint256[](num);
    //loop through user balances until we find all the fighters
    uint count;
    for(uint i; count<num && i<RING + ttlRings; i++){
      if(balanceOf(user, RING + i) ==1){
        _tokenIds[count] = RING + i;
        count++;
      }
    }
    return _tokenIds;
  }

  function getAmuletIDsForUser(address user) external view returns (uint256[] memory){
    //get balance of fighters
    uint256 num = getValueInBin(userTotalBalances[user], USER_TOTAL_BALANCES_BITS_SIZE, AMULET_INDEX);
    uint256[] memory _tokenIds = new uint256[](num);
    //loop through user balances until we find all the fighters
    uint count;
    for(uint i; count<num && i<AMULET + ttlAmulets; i++){
      if(balanceOf(user, AMULET + i) ==1){
        _tokenIds[count] = AMULET + i;
        count++;
      }
    }
    return _tokenIds;
  }

   function getFighters(uint256[] calldata tokenIds) external view returns (FighterYakuza[] memory){
    FighterYakuza[] memory FY = new FighterYakuza[](tokenIds.length);
    for (uint i = 0; i < tokenIds.length; i++) {
      FighterYakuza storage fighter = idToFYakuza[tokenIds[i]];
      FY[i] = fighter;
    }
    return FY;
  }

  function setFighters(uint256[] calldata tokenIds, FighterYakuza[] calldata fighters) external onlyAdmin {
    if(tokenIds.length != fighters.length) revert MismatchArrays();
    for (uint i = 0; i < tokenIds.length; i++) {
      idToFYakuza[tokenIds[i]] = fighters[i];
    }
  }

  function isFighter(uint256 tokenId) external view returns (bool) {
    if(tokenId > FIGHTER + ttlFYakuzas ||
    tokenId < FIGHTER) revert InvalidTokenID({tokenId: tokenId});
    FighterYakuza memory FY = idToFYakuza[tokenId];
        
    return FY.isFighter;
  }


  function getRing(uint256 tokenId) external view returns (RingAmulet memory) {
    if(tokenId > RING + ttlRings || tokenId <= RING) revert InvalidTokenID({tokenId: tokenId});
    RingAmulet memory ring = idToRingAmulet[tokenId];
    return (ring);
  }

  function getAmulet(uint256 tokenId) external view returns ( RingAmulet memory) {
    if(tokenId > AMULET + ttlAmulets || tokenId <= AMULET) revert InvalidTokenID({tokenId: tokenId});
    RingAmulet memory amulet = idToRingAmulet[tokenId];
    return ( amulet);
  }

  function getTotalFighterYakuza() external view returns (uint256){
    return ttlFYakuzas;
  }

 /*

    // Take care with this one, as rank is used in the Arena - if the rank of the NFT changes while the NFT is in the Arena it's not good :-p
  function setTraitRank(uint16 tokenId, uint8 rank) external onlyAdmin onlyFighter(tokenId) {
    FighterYakuza memory traits = idToFYakuza[tokenId];
    traits.rank = rank;
    traits.lastRankUpgradeTime = uint32(block.timestamp);
    idToFYakuza[tokenId] = traits;
  }

  function setTraitCourage(uint16 tokenId, uint8 courage) external onlyAdmin onlyFighter(tokenId) {
    FighterYakuza memory traits = idToFYakuza[tokenId];
    traits.courage = courage;
    idToFYakuza[tokenId] = traits;
  }

  function setTraitCunning(uint16 tokenId, uint8 cunning) external onlyAdmin onlyFighter(tokenId) {
    FighterYakuza memory traits = idToFYakuza[tokenId];        
    traits.cunning = cunning;
    idToFYakuza[tokenId] = traits;
  }

  function setTraitBrutality(uint16 tokenId, uint8 brutality) external onlyAdmin onlyFighter(tokenId) {
    FighterYakuza memory traits = idToFYakuza[tokenId];
    traits.brutality = brutality;
    idToFYakuza[tokenId] = traits;
  }
*/

  function safeTransferFrom(address _from, address _to, uint256 _id, uint256 _amount, bytes memory _data)
    public override
  {
    // Requirements
    require((msg.sender == _from) || isApprovedForAll(_from, msg.sender), " INVALID_OPERATOR");
    require(_to != address(0)," INVALID_RECIPIENT");
    // require(_amount <= balances);  Not necessary since checked with _viewUpdateBinValue() checks

    if(_id > RING && _id <= RING + ttlRings) {
        _updateIDUserTotalBalance(_to, RING_INDEX, _amount, Operations.Add);
        _updateIDUserTotalBalance(_from, RING_INDEX, _amount, Operations.Sub);
        //_addRingToOwner(_to, _ids[i]);
       // removeRingFromOwner(_from, _ids[i]);
      }
      if(_id > AMULET && _id <= AMULET + ttlAmulets){
        _updateIDUserTotalBalance(_to, AMULET_INDEX, _amount, Operations.Add);
        _updateIDUserTotalBalance(_from, AMULET_INDEX, _amount, Operations.Sub);
      
      }
      if(_id > FIGHTER && _id < FIGHTER + ttlFYakuzas) {
        _updateIDUserTotalBalance(_to, FIGHTER_INDEX, _amount, Operations.Add); // Add amount to recipient
        _updateIDUserTotalBalance(_from, FIGHTER_INDEX, _amount, Operations.Sub); // Add amount to recipient
    
      }

    _safeTransferFrom(_from, _to, _id, _amount);
    _callonERC1155Received(_from, _to, _id, _amount, gasleft(), _data);
  }

  function safeBatchTransferFrom(address _from, address _to, uint256[] calldata _ids, uint256[] calldata _amounts, bytes memory _data)
    public override (ERC1155PackedBalance, IUGNFTs)
  {
    // Requirements
    require((msg.sender == _from) || isApprovedForAll(_from, msg.sender), " INVALID_OPERATOR");
    require(_to != address(0)," INVALID_RECIPIENT");
    for(uint i = 0; i < _ids.length; i++){
      if(_ids[i] > RING && _ids[i] <= RING + ttlRings) {
        _updateIDUserTotalBalance(_to, RING_INDEX, _amounts[i], Operations.Add);
        _updateIDUserTotalBalance(_from, RING_INDEX, _amounts[i], Operations.Sub);
        //_addRingToOwner(_to, _ids[i]);
       // removeRingFromOwner(_from, _ids[i]);
      }
      if(_ids[i] > AMULET && _ids[i] <= AMULET + ttlAmulets){
        _updateIDUserTotalBalance(_to, AMULET_INDEX, _amounts[i], Operations.Add);
        _updateIDUserTotalBalance(_from, AMULET_INDEX, _amounts[i], Operations.Sub);
      
      }
      if(_ids[i] > FIGHTER && _ids[i] < FIGHTER + ttlFYakuzas) {
        _updateIDUserTotalBalance(_to, FIGHTER_INDEX, _amounts[i], Operations.Add); // Add amount to recipient
        _updateIDUserTotalBalance(_from, FIGHTER_INDEX, _amounts[i], Operations.Sub); // Add amount to recipient
    
      }
    }
    _safeBatchTransferFrom(_from, _to, _ids, _amounts);
    _callonERC1155BatchReceived(_from, _to, _ids, _amounts, gasleft(), _data);
  }

  function checkUserBatchBalance(address user, uint256[] calldata tokenIds) external view returns (bool){
    for (uint i = 0; i < tokenIds.length;i++){
      uint256 bal = balanceOf(user, tokenIds[i]);
      if(bal == 0) return false;
    }
    return true;
  }

 
/*
  function tokenURIs(uint256[] tokenIds) public view override blockIfTokenJustMinted(tokenId) blockIfChangingAddress blockIfChangingToken(tokenId) returns (string memory) {
    string memory jsonString;

    FighterYakuza memory traits = idToFYakuza[tokenId];
    if (_exists(tokenId)) {
      jsonString = string(abi.encodePacked(
      jsonString,
      Strings.toString(traits.imageId),',',
      Strings.toString((traits.isFighter)? 1 : 0),',',
      Strings.toString((traits.isGen0)? 0 : 1),',',
      Strings.toString(traits.cunning),',',
      Strings.toString(traits.brutality),','
      ));

      jsonString = string(abi.encodePacked(
      jsonString,
      Strings.toString(traits.courage),',',
      Strings.toString(traits.level),',',
      Strings.toString(traits.lastLevelUpgradeTime),',',
      Strings.toString(traits.rank),',',
      Strings.toString(traits.lastRankUpgradeTime)
      ));
    }

    return string(abi.encodePacked(
      _tokenRevealedBaseURI,
      "?traits=",
      jsonString
    ));
  }
*/
  /*///////////////////////////////////////////////////////////////
                       ERC165 FUNCTIONS
  //////////////////////////////////////////////////////////////*/

  /**
   * @notice Query if a contract implements an interface
   * @param _interfaceID  The interface identifier, as specified in ERC-165
   * @return `true` if the contract implements `_interfaceID` and
   */
  function supportsInterface(bytes4 _interfaceID) public override(ERC1155PackedBalance) virtual pure returns (bool) {
    if (_interfaceID == 0xd9b67a26 ||
        _interfaceID == 0x0e89341c) {
      return true;
    }
    return super.supportsInterface(_interfaceID);
  }

  
  /***********************************|
  |       Unsupported Functions       |
  |__________________________________*/

  fallback () external {
    revert("UGNFTs: INVALID_METHOD");
  }
}

**Comment by SamShakespeare** [comment]
sorry i put up whole contract, i hope its not too much, and i appreciate your help
a

**Comment by SamShakespeare** [comment]
just for record, i have found a workaround. if i make the ttlFYakuzas variable 'public' then add this line to interfface it works: 
function ttlFYakuzas() external view returns (uint256);

 (just overriding getter function in interface i guess)

**Comment by SamShakespeare** [comment]
that being said thats only one of my 2 errors, the other is the same and i cant figure out a fix

**Comment by SamShakespeare** [comment]
I have reduced the contract function to this and still getting implementation error:

 function getFighterIDsForUser(address user) external view returns (uint256){
    //get balance of fighters
    uint256 numFighters =100;     return numFighters;
  }

**Comment by SamShakespeare** [comment]
sorry to be clear: interface signature: 

    function getFighterIDsForUser(address) external view returns (uint256);

and contract implementation:

function getFighterIDsForUser(address user) external view returns (uint256){
   
   if (user != address(0x00)) return 100;
  }

**Comment by SamShakespeare** [comment]
brooooooo my baaaad!! I had another copy of the contract in the src folder it was referring to that.. sorry and I hope i didnt waste too much of your time!!
