### ISSUE TITLE
Base fee causes error in forked Rinkeby network on first transaction

### ISSUE THREAD

**Issue by unparalleled-js** [foundry-rs/foundry#1863]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (3fc1491 2022-06-06T00:14:30.023454Z)

### What command(s) is the bug in?

anvil --mnemonic "test test test test test test test test test test test junk" --accounts 10 --derivation-path "m/44'/60'/0'" --fork-url https://eth-rinkeby.alchemyapi.io/v2/key-that-i-did-not-paste

### Operating System

macOS (Intel)

### Describe the bug

Steps to repro:

Step 1: Launch anvil using a forked Rinkeby network
Step 2: Make any transaction and set the base fee to the base fee of the "latest" block (e.g. the default way to do it?)
Step 3: Notice the transaction fails
Step 4: Make transaction again
Step 5: Notice everything works as expected after first transaction (consistently)

Reasons maybe:

The base fee on the latest block from Rinkeby is minute, e.g. `14` last I checked
Every subsequent block in Anvil uses 1000000000.  If I manually set my base fee to 1000000000 on the first transaction, it will succeed.

**NOTE**: When using Hardhat, I do not have this problem.

**Comment by unparalleled-js** [comment]
That would make sense, but then the problem is that rinkeby's non-existent >0 base fee causes transaction errors but I am not sure why.

Possibly unrelated, but I am also unable to deploy (using RPCs / Anvil only) when using a forked network and an account from the mnemonic. The transaction always fails and does not give any reason.

**Comment by mattsse** [comment]
mind trying again with this PR https://github.com/foundry-rs/foundry/pull/1865 ?

**Comment by unparalleled-js** [comment]
> mind trying again with this PR #1865 ?

Amazing! this seems to fix the problem entirely :)
Sorry for the delay - that was my first time installing Foundry from source

**Comment by gakonst** [comment]
@mattsse I think like in that other case we had encountered (around the EVM gasprice when forking), we should be making the anvil `basefee` config an `Option`, and if we're forking and the `basefee` is `None` use the remote network's basefee, otherwise use ours. So I like the solution here https://github.com/foundry-rs/foundry/pull/1865/files unless you think we should not do it for some other reason

**Comment by mattsse** [comment]
> unless you think we should not do it for some other reason

currently, we have `gas_price` and `base_fee` as separate values, we should initialize them to the same value (basefee of last block) then, right?

**Comment by gakonst** [comment]
Yep, I think so.
