### ISSUE TITLE
Weird error when sending a Tx with cast

### ISSUE THREAD

**Issue by mmenoxx** [foundry-rs/foundry#1866]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (3fc1491 2022-06-06T00:12:33.657656525Z)

### What command(s) is the bug in?

cast send --rpc-url=$RPC_URL --private-key=$PRIVATE_KEY

### Operating System

Linux

### Describe the bug

When sending the following Tx on a local Anvile node:

`cast send --rpc-url=$RPC_URL --private-key=$PRIVATE_KEY --value 0.08ether 0x5fbdb2315678afecb367f032d93f642f64180aa3 "mintTo(address)" 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266`

The following error is raised:
```
Error: 
   0: specified chain_id is different than the signer's chain_id
```

**Comment by davisshaver** [comment]
I've run into this as well. FWIW, I was able to reproduce the issue with `foundryup` but then when I installed `nightly-1616380f254f7c0d83ac75c7d4056f0401b5e417` the error went away. This PR seems like possibly related: https://github.com/foundry-rs/foundry/pull/1839

**Comment by mattsse** [comment]
oh, sorry about that, that's an oversight

https://github.com/gakonst/ethers-rs/pull/1356 will fix this

**Comment by mmenoxx** [comment]
@mattsse I updated to the very last version with foundryup and retested, and I still have the same problem/error
