### ISSUE TITLE
Revert messages are missing

### ISSUE THREAD

**Issue by unparalleled-js** [foundry-rs/foundry#1871]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (3fc1491 2022-06-06T00:14:30.023454Z)

### What command(s) is the bug in?

anvil

### Operating System

macOS (Intel)

### Describe the bug

Transactions will revert messages are missing revert messages.

I have a method and modifier like:

```solidity
    modifier onlyOwner() {
        require(msg.sender == owner, "!authorized");
        _;
    }
    function getSecret() public onlyOwner view returns(uint256 secret) {
        return 123;
    }
```

The response data I am getting looks like:
```
{'jsonrpc': '2.0', 'id': 23, 'error': {'code': -32003, 'message': 'execution reverted: ', 'data': '0x'}}
```
which is maybe what I would expect had I not included a revert message.

`!unathorized` is missing from the response.

I believe this is a regression, as this was working a month or so ago.

**Comment by unparalleled-js** [comment]
I am using `web.py` to facilitate requests but see this response data via breakpoints

**Comment by gakonst** [comment]
@mattsse are we correctly returning reverts from anvil?

**Comment by isvidler** [comment]
+1 to this bug. Was able to reproduce this by deploying a contract with a simple `revert("revert string");` call.

Using `anvil` in forked mode and using Ethers.js to make the call.

Anvil version: anvil 0.1.0 (1616380 2022-06-05T00:17:15.393047Z)

**Comment by unparalleled-js** [comment]
When deploying to a forked network, this bug is still present I think

**Comment by unparalleled-js** [comment]
Ah, okay I am getting this error on estimating gas.
Can we also include the revert message when estimating gas?

**Comment by unparalleled-js** [comment]
Also, `web.py` is not triggering exceptions from my reverts when I specify gas in

[self.web3.eth.get_transaction(txn_hash).keys()](https://github.com/ethereum/web3.py/blob/master/web3/_utils/method_formatters.py#L577-L605)

**Comment by mattsse** [comment]
thanks for providing this link
will have a look what's up with eth_estimate and reverts

**Comment by unparalleled-js** [comment]
I tried the PR and web3.py still is not catching the reverts for some reason. hmmmmmmm.

**Comment by mattsse** [comment]
haven't tested this in python because I never get it working

but curious why this condition is not met:

https://github.com/ethereum/web3.py/blob/c741e55b8ac95fed72a7135e7bb0e9f0d4a40431/web3/_utils/method_formatters.py#L628-L629

seems like this should for:

```
JsonRpcError {
                    code: 3,
                    message: "execution reverted: Not enough Ether provided.",
                    data: Some(
                        String(
                            "0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000001a4e6f7420656e6f7567682045746865722070726f76696465642e000000000000",
                        ),
                    ),
                },

```

**Comment by unparalleled-js** [comment]
I am debugging this.. One thing I noticed is that `web3.py` expects the key `"error"` key instead of `"result"` when errors occur... Am I reading this correctly?

**Comment by unparalleled-js** [comment]
So this might be related, I don't know:

My `eth_estimateGas` call works on Hardhat but fails on Anvil with exception:

```
{
    "jsonrpc": "2.0",
    "id": 0,
    "error": {
        "code": -32602,
        "message": "unknown field `id`, expected one of `from`, `to`, `gasPrice`, `maxFeePerGas`, `maxPriorityFeePerGas`, `gas`, `value`, `data`, `nonce`, `accessList`, `type`"
    }
}
```

**Comment by mattsse** [comment]
oh so somewhere in eth_estimateGas we're missing a proper conversion

**Comment by unparalleled-js** [comment]
Ok never mind the part about the ID field... I am in the midst of debugging and just confused

**Comment by unparalleled-js** [comment]
Ok I am working on a more bare-bones reproduction script to try and debug stuff.
I got this:

```python
from solcx import compile_source
from web3 import HTTPProvider, Web3
from web3.exceptions import ContractLogicError

# Mnemonic       : "test test test test test test test test test test test junk"
# Derivation path: "m/44'/60'/0'/{acct-index}"
ACCOUNT = "0x1e59ce931B4CFea3fe4B875411e280e173cB7A9C"
PKEY = "0xdd23ca549a97cb330b011aebb674730df8b14acaee42d211ab45692699ab8ba5"

SOURCE_CODE = """
pragma solidity ^0.8.2;

contract NumberStorage {
    uint256 public number;

    function setNumber(uint256 num) public {
        require(num != 0, "RevertStringFooBar");
        number = num;
    }
}
""".strip()


def main():
    # Connect to node (either Hardhat node or Anvil)
    web3 = Web3(HTTPProvider("http://127.0.0.1:8545/"))
    web3.eth.default_account = ACCOUNT

    # Compile simple contract
    compiled_sol = compile_source(SOURCE_CODE, output_values=["abi", "bin"])
    _, contract_interface = compiled_sol.popitem()
    bytecode = contract_interface["bin"]
    abi = contract_interface["abi"]
    contract =  web3.eth.contract(abi=abi, bytecode=bytecode)

    # Deploy contract and create instance
    params = {"maxFeePerGas": 3242352352352, "maxPriorityFeePerGas": 2000000000}
    tx_hash = contract.constructor().transact(params)
    tx_receipt = web3.eth.wait_for_transaction_receipt(tx_hash)
    instance = web3.eth.contract(address=tx_receipt.contractAddress, abi=abi)

    # Transact in a way that should succeed
    tx_hash = instance.functions.setNumber(5).transact(params)
    tx_receipt = web3.eth.wait_for_transaction_receipt(tx_hash)
    print("Success")

    # Transact in a way that should fail
    try:
        tx_hash = instance.functions.setNumber(0).transact()
    except ContractLogicError as err:
        print(f"Failed: {err}")


if __name__ == "__main__":
    main()
```

When I use Hardhat, this is the output of the script:

```
Success
Failed: execution reverted: Error: VM Exception while processing transaction: reverted with reason string 'RevertStringFooBar'
```

When I connect to Anvil however, this is the output:

```
Success
Failed: execution reverted: 
```

For some reason, the revert message is not there!

**Comment by gakonst** [comment]
@mattsse should we introduce an extra decoding step - per the above analysis?

**Comment by mattsse** [comment]
yeh, need to debug this.

> Anvil is hitting the Geth condition now as a result to this PR
> However - the "Geth" case seems to assume the error message is already decoded as a string.

this is not clear to me, what's the "error message" here? the expected revert reason or the 'message' object

in what RPC call does this happen @[unparalleled-js](https://github.com/unparalleled-js)?
