### ISSUE TITLE
Field "to" not present in transaction receipt for contract creating transactions

### ISSUE THREAD

**Issue by fala13** [foundry-rs/foundry#1874]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (2d22d51 2022-06-08T00:06:46.392116828Z

### What command(s) is the bug in?

anvil

### Operating System

Linux

### Describe the bug

Link to issue on brownie tracker: https://github.com/eth-brownie/brownie/issues/1549

Deploying contracts via brownie using anvil currently fails due to field "to" not being present in transaction receipt received from anvil.

Field "to" should be present in transaction receipt, set to null when it's a contract creation transaction.

**Comment by gakonst** [comment]
bug is here: https://github.com/gakonst/ethers-rs/blob/master/ethers-core/src/types/transaction/response.rs#L389-L390, should probably add a `#[serde(default)]` @mattsse ?

**Comment by mattsse** [comment]
ah I misread it, #1876

it's missing completely, so yeah we need to fix upstream ethers, on it.

**Comment by mattsse** [comment]
after having another look at the ethers code, I was wondering why it's not included because by default serde deserializes `None` as null

checked against anvil test in #1876 

```console
curl -X POST --header 'content-type: application/json' --data '{"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x2aa3a1aefa199c991a4544e7319b360af2d4f346db71e4c0af26e0047b595887"],"id":1}' --url http://localhost:8546/
```

```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "blockHash": "0x08a54bb05bef8c24406f00898e4d1ea27c834b265b0dbce21d2718043884a4b9",
    "blockNumber": "0x2",
    "contractAddress": "0xe7f1725e7734ce288f8367e1bb143e90bb3f0512",
    "cumulativeGasUsed": "0x0",
    "effectiveGasPrice": "0xee6b2800",
    "from": "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266",
    "gasUsed": "0x3c5d3",
    "logs": [],
    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "root": null,
    "status": "0x1",
    "to": null,
    "transactionHash": "0x2aa3a1aefa199c991a4544e7319b360af2d4f346db71e4c0af26e0047b595887",
    "transactionIndex": "0x0"
  }
}
```

and `to` is null here, so not sure what we're missing

**Comment by gakonst** [comment]
it seems like this is not an issue based on our 2 tests, closing and please re-open if you think we misunderstood
