### ISSUE TITLE
ffi doesn't retrieve typescript execution output

### ISSUE THREAD

**Issue by Timidan** [foundry-rs/foundry#1882]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (2d22d51 2022-06-08T00:06:46.392116828Z)

### What command(s) is the bug in?

forge test --ffi

### Operating System

Linux

### Describe the bug

Trying to generate function selectors in typescript then passing the abi encoded data to ffi doesn't work. The typescript code is [https://gist.github.com/Timidan/6c3151f82eb9b3d7954e5ee7631897be](here). when executed standalone, the script outputs 
![image](https://user-images.githubusercontent.com/25876969/172616451-581e3a42-8e28-42e9-add0-dacf6cb455cb.png) after removing the leading function selector.. but executing via `ffi` gives this error

```string[] memory cmd = new string[](4);
        cmd[0] = "npx";
        cmd[1] = "hardhat";
        cmd[2] = "run";
        cmd[3] = "scripts/genSelectors.ts";
        bytes memory res = vm.ffi(cmd);
```
[5667] ContractTest::testExample() 
    ├─ [0] VM::ffi(["npx", "hardhat", "run", "scripts/genSelectors.ts"]) 
    │   └─ ← "Invalid character 'G' at position 0"
    └─ ← "Invalid character 'G' at position 0"

Am i passing in the wrong args?

Thanks!

**Comment by mds1** [comment]
The first line of output from your script is `Generating typings for...`. Forge expects the _only_ output from your script to be the ABI-encoded return data. You'll need to add a silent/quiet flag to your ffi commands to suppress the text output.

**Comment by Timidan** [comment]
checked it out and realized hardhat doesn't have a `quiet` or `silent` flag...closest solution is to convert to js and use `node` for execution...that won't use typchain..Thanks a lot

**Comment by Timidan** [comment]
Awesme...It Works...ended up converting to js...thanks a lot @mds1
