### ISSUE TITLE
Verify contracts deployed within a contract when scripting and broadcasting

### ISSUE THREAD

**Issue by strollinghome** [foundry-rs/foundry#1893]
### Component

Forge

### Describe the feature you would like

When running a script to deploy and verify contracts, I would like to also verify contracts that are deployed within another contract. See the example below.

The contracts are

```
contract A {
    address public bAddress;

    constructor() {
        bAddress = address(new B()); 
    }
}

contract B {}
```

Script to deploy
```
// ... imports ...

contract DeployContractsAB {
    function run() {
        vm.broadcast();
        A a = new A();
    }
}
```

Currently, only contract `A` would get verified. The feature request is to also verify contract `B` in this scenario.

**Comment by wminshew** [comment]
per https://github.com/foundry-rs/foundry/pull/2840 I believe this should be closed now
