### ISSUE TITLE
Ability to mine/wait for blocks in scripts

### ISSUE THREAD

**Issue by naps62** [foundry-rs/foundry#1902]
### Component

Forge

### Describe the feature you would like

This is a follow-up on #1848 , which got closed even thought the bug (rust panic) still persists

In scripts, we can use `--slow` to force transactions to happen across different blocks. However, if those transactions rely on data such as `blockhash(block.number - 1)`, forge will actually fail to simulate them, because no actual blocks and blockhashes are being created during that time. e.g., the following fails in a script, but works in a unit test:

```
        for (uint256 i = 0; i < 10; ++i) {
           vm.broadcast();
           submitTransaction();
            vm.roll(block.number + 1); // need to roll because `submitTransaction` didn't actually create a new block
            console.logBytes32(blockhash(block.number - 1));
        }
```

The specific error I get is : 
```
Message:  Failed to get block hash for 10826800
block 10826800 not found
```

It would be very useful to be able to request our forked instance (anvil?) to simulate a new block being mined, which is the behaviour necessary here, and what suposedly `--slow` should enforce

### Additional context

My real-world scenario here is actually trying to solve [Ethernaut #03](https://ethernaut.openzeppelin.com/level/0x4dF32584890A0026e56f7535d0f2C6486753624f) on-chain using a forge script.
The script must:
* deploy the ethernaut level instance
* solve it, which requires submitting 10 different transactions across 10 different blocks

The current blocker for this is that each call relies on `blockhash(block.number - 1)`, which doesn't seem to exist while simulating the script

**Comment by onbjerg** [comment]
Marking this as hard because I think it will be - feel free to correct @joshieDo

**Comment by foufrix** [comment]
Hi, @naps62 did you manage to make it work with a while loop? I'm having exactly the same issue as you and launched it 10 times by hand to solve that, I'm pretty sure there could be a cleaner way to do that.
