### ISSUE TITLE
Update to newest version of solang-parser

### ISSUE THREAD

**Issue by jpopesculian** [foundry-rs/foundry#1905]
### Component

Forge

### Describe the feature you would like

`fmt` is currently on version 0.1.13 and solang-parser is now on 0.1.14

**Comment by mattsse** [comment]
ethers companion here https://github.com/gakonst/ethers-rs/pull/1369

**Comment by onbjerg** [comment]
Seems to be solved going by Cargo.toml - let me know if this is not the case

**Comment by rkrasiuk** [comment]
yup, was addressed in [this PR](https://github.com/foundry-rs/foundry/pull/1909). sorry, forgot to reference the issue
