### ISSUE TITLE
forge script --verify error

### ISSUE THREAD

**Issue by dcposch** [foundry-rs/foundry#1927]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (123ad0a 2022-06-12T00:08:28.302961Z)

### What command(s) is the bug in?

forge verify

### Operating System

macOS (Intel)

## Steps to reproduce

Deploy Silver Portal: https://github.com/dcposch/silverportal/tree/master/packages/portal-contracts

The command under `Deployment` in the README works, but adding `--verify` fails.

## Expected result

Same deployment + automatic verification on https://ropsten.etherscan.com

## Actual result

<img width="524" alt="Screen Shot 2022-06-12 at 11 34 42 AM" src="https://user-images.githubusercontent.com/169280/173248118-f61f8dff-443e-40e1-8796-f0a3eb51daf2.png">

Running with RUST_BACKTRACE:

<details>

```
$ RUST_BACKTRACE=full forge script PortalDeploy -f $ETH_RPC_URL_ROPSTEN --private-key $ETH_DEPLOYER_PRIVATE_KEY --verify
[⠒] Compiling...
No files changed, compilation skipped
Error: 
   0: missing field `tx` at line 1 column 7336

Location:
   /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/convert/mod.rs:550

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   2: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   3: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   4: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   5: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   6: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   7: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   8: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   9: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
```

</details>

**Comment by onbjerg** [comment]
Do you have `ETHERSCAN_API_KEY` set?

**Comment by mattsse** [comment]
just a hunch @joshieDo but this looks like a serde issue with the `sequence::TransactionWithMetadata` as this is the only type that has a field `tx`

**Comment by joshieDo** [comment]
Yeah, seems like you're verifying from a broadcast log from an older version. It now uses another format (`TransactionWithMetadata`) which is not backwards compatible

**Comment by gakonst** [comment]
Closing as this is not an issue that can be fixed, need to redeploy

**Comment by dcposch** [comment]
makes sense, thanks. may be worth printing an version error.

**Comment by dcposch** [comment]
redeployed and `--verify` works now. thanks!
