### ISSUE TITLE
Apply imported remappings on imported files only

### ISSUE THREAD

**Issue by adhusson** [foundry-rs/foundry#1933]
### Component

Forge

## Current behaviour

Currently, an imported remapping applies globally. e.g. the following happens
```console
$ forge init
$ mkdir src/ds-test && touch src/ds-test/MyDsTest.sol
$ echo 'import "ds-test/MyDsTest.sol";' > src/Contract2.sol
$ forge build
  (...) Failed to resolve file: "(...)/lib/forge-std/lib/ds-test/src/MyDsTest.sol": No such file or directory (os error 2).
        Check configured remappings.
```

This is manageable with 1 level of dependency but will cause surprises with nested dependencies.

## Suggestion

Only apply the remapping when compiling files of the imported dependency (I don't know how forge invokes `solc`, maybe that's not an option). Optionally also rewrite deep imports (like `import dependency/remapped_dir/Contract.sol` from the root level.

**Comment by adhusson** [comment]
Yes sorry, fixed version:

```console
$ forge init
$ mkdir ds-test && touch ds-test/MyDsTest.sol
$ echo 'import "ds-test/MyDsTest.sol";' > src/Contract2.sol
$ forge build
```

You'll get a warning if you rename `ds-test` to something else but it will work.

Maybe more realistically, in my actual case the dependency had a remapping like `src/...=...`, which clashed one level above. It's also easy to imagine remappings like `utils/=...` being used both in a dependency and in an importing package.

**Comment by 0ld-tech** [comment]
The solution for me was just doing forge update.....

**Comment by onbjerg** [comment]
cc @mattsse, I think you did some "local remapping" work or something similar to fix issues like these? I vaguely remember that at least, so this should be fixed?

**Comment by mattsse** [comment]
yeah this should be fixed now
