### ISSUE TITLE
`forge inspect <contract> functionSelectors`

### ISSUE THREAD

**Issue by tynes** [foundry-rs/foundry#1939]
### Component

Forge

### Describe the feature you would like

It would be really nice to be able to quickly list off the function selectors for a contract. The usecase here is to have a script in CI that ensures that there are no clashing function selectors between two particular contracts, this is required for an upcoming upgrade to be safe.

I'm pretty sure they are included in the compiler output, perhaps the [ast](https://github.com/gakonst/ethers-rs/blob/4ba8adf87c40d160e999d403f168282f2fd000ee/ethers-solc/test-data/ast/ast-erc4626.json#L452), but I'm unable to find an easy command to access this information.

I believe a lot of the implementation already exists in `forge upload-selectors`

Its possible to do this with a bash script with `forge inspect`, `jq` and `cast` but I'm sure that other people would find this useful as well.

**Comment by mds1** [comment]
+1 this would be a really helpful feature

**Comment by onbjerg** [comment]
I think this already exists:

```sh
$ forge inspect LilENS methodidentifiers
{
  "lookup(string)": "f67187ac",
  "register(string)": "f2c298be",
  "update(string,address)": "2cff89c9"
}
```

Unless I am misunderstanding? :smile:

**Comment by tynes** [comment]
This is what I am looking for, couldn't find the exact command. Thanks again!
