### ISSUE TITLE
`forge snapshot --exit-code`

### ISSUE THREAD

**Issue by tynes** [foundry-rs/foundry#1942]
### Component

Forge

### Describe the feature you would like

In CI, we enforce that gas snapshots are always up to date. I feel like having this built into `foundry` would be useful to many people. We use the following command:

```
forge snapshot && git diff --exit-code .gas-snapshot
```

This ensures that there is no diff in the `.gas-snapshot` and exits non zero if there is a diff. The `forge snapshot --exit-code` could check if there is a diff and exit non zero if there is a diff

**Comment by onbjerg** [comment]
This should already exist see `forge snapshot --check`: 

![image](https://user-images.githubusercontent.com/8862627/173424240-b97bbc89-ab0e-43e1-82c8-f0d379a1a188.png)

Let me know if this is not correct and I will reopen :smile:

**Comment by tynes** [comment]
Ah thank you, sorry for spam!
