### ISSUE TITLE
Allow impersonating contracts

### ISSUE THREAD

**Issue by unparalleled-js** [foundry-rs/foundry#1943]
### Component

Anvil

### Describe the feature you would like

For feature-parity sake with Hardhat, I would like to be able to impersonate contracts. This helps migrate tests from hardhat to foundry.

Currently when I try to do this, there is an issue with `code`.
However - even when I set the code to be empty, I have issues with estimating fees.

**Comment by mattsse** [comment]
what version are you on there was a fix for this this weekend https://github.com/foundry-rs/foundry/pull/1912

**Comment by unparalleled-js** [comment]
> what version are you on? there was a fix for this this weekend #1912

I built Anvil from master branch.
when I  try to estimate the gas, I get the error: `gas exceeds allowance: 0`
and when I specify gas, I get an error `'Insufficient funds for gas * price + value'`

**Comment by unparalleled-js** [comment]
Yes, that did it!
so one thing I noticed is that in `Hardhat` my reverts would fail _first_ before the balance checking stuff whereas in `Anvil`, this failed first, which is how I found this issue or go into this situation (during migration)

It totally is not a big deal though! And now I am writing better tests because of it :)

**Comment by ThomasdenH** [comment]
How does impersonating contracts work? I tried doing the following:
```typescript

  const provider = new ethers.providers.JsonRpcProvider();
  const timeLock = "0x3b870db67a45611CF4723d44487EAF398fAc51E3";
  await provider.send("anvil_impersonateAccount", [
    "0x3b870db67a45611CF4723d44487EAF398fAc51E3",
  ]);
  const signer = provider.getSigner(timeLock);
  const fyToken = new Contract(
    "0x53358d088d835399F1E97D2a01d79fC925c7D999",
    fyTokenAbi,
    signer
  );
  const tx1 = await fyToken.setFlashFeeFactor(1);
```

However, this gives the error
```json
{
  "jsonrpc": "2.0",
  "id": 47,
  "error": {
    "code": -32603,
    "message": "EVM error RejectCallerWithCode"
  }
}
```

```
error={"code":-32603},
requestBody="{\"method\":\"eth_estimateGas\",\"params\":[{\"from\":\"0x3b870db67a45611cf4723d44487eaf398fac51e3\",\"to\":\"0x53358d088d835399f1e97d2a01d79fc925c7d999\",\"data\":\"0x159c03dd0000000000000000000000000000000000000000000000000000000000000001\"}],\"id\":47,\"jsonrpc\":\"2.0\"
```

**Comment by naddison36** [comment]
I also hit this error. Thanks @ThomasdenH for the workaround of setting the code of the impersonated contract to an empty string.

For anyone else looking for this workaround, here's how I did it using Hardhat API calls

``` typescript
// impersonates a specific account
export const impersonate = async (addr: string, fund = true): Promise<Signer> => {
    // Dynamic import hardhat module to avoid importing while hardhat config is being defined.
    // The error this avoids is:
    // Error HH9: Error while loading Hardhat's configuration.
    const { network, ethers } = await import("hardhat")
    await network.provider.request({
        method: "hardhat_impersonateAccount",
        params: [addr],
    })
    // this is needed for Anvil which does not allow a contract to be impersonated.
    // The following sets the contract's code to a zero number of bytes so the contract can be impersonated.
    // https://github.com/foundry-rs/foundry/issues/1943
    await network.provider.request({
        method: "hardhat_setCode",
        params: [addr, ""],
    })
    if (fund) {
        // Give the account 10 Ether
        await network.provider.request({
            method: "hardhat_setBalance",
            params: [addr, "0x8AC7230489E80000"],
        })
    }
    return ethers.provider.getSigner(addr)
}

```

**Comment by mattsse** [comment]
#2090 should remove the code temporarily 

do you run into issues where this doesn't work properly? @naddison36

**Comment by gakonst** [comment]
@naddison36 is this on latest foundry? it should be working, the PR Matt linked above will set the code for impersonated accounts to empty temporarily  🤔

**Comment by naddison36** [comment]
I did a build from `master` this morning
```bash
foundryup -b master
anvil -V
anvil 0.1.0 (f77e317 2022-08-09T21:46:11.465583Z)
```

If I try and impersonate a Gnosis Safe contract without setting it's code to zero I `ProviderError: EVM error RejectCallerWithCode`

If I set the safe's code to 0x it works
```typescript
await network.provider.request({
    method: "hardhat_setCode",
    params: [addr, "0x"],
})

**Comment by naddison36** [comment]
I can confirm this has now been fixed. Thanks

**Comment by rpedroni** [comment]
Thanks @ThomasdenH for the workaround, was stuck on impersonating an account that I wasn't aware was multisig
