### ISSUE TITLE
Coverage: Abstract contract coverage

### ISSUE THREAD

**Issue by onbjerg** [foundry-rs/foundry#1965]
There is no coverage for abstract contracts because they do not have bytecode or source maps of their own.

This requires a big-ish rewrite of some of the logic that finds coverage items and anchors

**Comment by onbjerg** [comment]
Yes, any project with an abstract contract will fail currently

**Comment by JasoonS** [comment]
I'm in the same boat as @frimoldi  as far as I can see.

**Comment by onbjerg** [comment]
Your test contract inherits from an abstract contract, so the analysed code uses an abstract contract and thus breaks

**Comment by frimoldi** [comment]
Not quite. I was able to run `forge coverage` by getting rid of the `/scripts` contract.

Seems like abstract contracts on **tests** are ok?

**Comment by onbjerg** [comment]
Might be unrelated to this then; abstract contracts are definitely not supported as they should be right now. For example, if you have an abstract contract in your actual code base, in the worst case it will prevent you from using `forge coverage`, and in the best case it will just not generate any coverage info at all for the contract

If you had posted the original error message w/ some additional context I could give you more insight but it's hard to do without :/
