### ISSUE TITLE
Coverage: HTML reporter

### ISSUE THREAD

**Issue by onbjerg** [foundry-rs/foundry#1966]
We should add an HTML reporter to `forge coverage` in the same style as `solidity-coverage`

**Comment by elenadimitrova** [comment]
Is there an interim workaround for this? i.e. does foundry write analysis from `forge coverage`?

**Comment by onbjerg** [comment]
`forge coverage --report lcov` and then use `genhtml` from the standard LCOV suite of tools

**Comment by Melvillian** [comment]
> `forge coverage --report lcov` and then use `genhtml` from the standard LCOV suite of tools

Just adding a little more detail here for people unfamiliar with `genhtml`, here's the command I use:

`forge coverage --report lcov && genhtml lcov.info -o report --branch-coverage`

**Comment by zerosnacks** [comment]
Ticket can likely be closed considering https://github.com/foundry-rs/foundry/pull/5046 with an initial implementation was rejected.

Implemented suggested refactor from #5046 in https://github.com/foundry-rs/foundry/pull/6821.

**Comment by zerosnacks** [comment]
Closing ticket as implementation was rejected
