### ISSUE TITLE
Coverage: Unhandled AST nodes

### ISSUE THREAD

**Issue by onbjerg** [foundry-rs/foundry#1968]
There are a few AST nodes that are not handled by the coverage visitor:

Unhandled:
- `YulSwitch`
- `YulForLoop`
- `YulFunctionDefinition`
- `YulVariableDeclaration`
- `YulFunctionCall`
- `TupleExpression`

I'm not sure what this one is:
- `ElementaryTypeNameExpression`

I'm not sure how to handle these:
- `MemberAccess`
- `NewExpression`

**Comment by gakonst** [comment]
cc @seanyoung @jpopesculian @rkrasiuk any ideas on `ElementaryTypeNameExpression`, `MemberAccess`, `NewExpression`?

**Comment by seanyoung** [comment]
`NewExpression` occurs in these three forms which have different parse trees.
```
(new D{value: 1})();
(new D){value: 1}();
new D{value: 1}();
```

`MemberAccess` occurs here in `s.f1`:
```
struct S { int f1; };
function f(S s) returns (int) { return s.f1; }
```

I don't think `ElementaryTypeNameExpression` is a thing, that's ethereum solidity.

@LucasSte knows about the yul expressions.

**Comment by LucasSte** [comment]
> There are a few AST nodes that are not handled by the coverage visitor:
> 
> Unhandled:
> 
> * `YulSwitch`
> * `YulForLoop`
> * `YulFunctionDefinition`
> * `YulVariableDeclaration`
> * `YulFunctionCall`

Do you need any help with these nodes? I didn't quite understand the context here.

**Comment by onbjerg** [comment]
No, I think I know how to handle those, I'm mostly unsure about the `new` keyword :smile:
