### ISSUE TITLE
cross platform test seem to hang mostly on apple aarch64 job

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#1984]
### Component

Forge, Anvil

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### Describe the bug

the aarch64 apple cross platform test seems to hang regularly at this test,

https://github.com/foundry-rs/foundry/runs/6903774179?check_suite_focus=true

 but sometimes others 

https://github.com/foundry-rs/foundry/runs/6905730226?check_suite_focus=true

> test cmd::can_emit_multiple_extra_output has been running for over 60 seconds
> test script::can_deploy_100_txes_concurrently has been running for over 60 seconds
> test script::can_deploy_broadcast_wrap has been running for over 60 seconds

> test cmd::can_emit_multiple_extra_output has been running for over 60 seconds
> test script::can_deploy_100_txes_concurrently has been running for over 60 seconds
> test script::can_deploy_broadcast_wrap has been running for over 60 seconds
> test script::can_deploy_100_txes_concurrently ... ok
> test script::can_deploy_mixed_broadcast_modes has been running for over 60 seconds
> test script::can_deploy_broadcast_wrap ... ok
> test cmd::can_emit_multiple_extra_output ... ok
> test script::can_deploy_no_arg_broadcast has been running for over 60 seconds
> test script::can_deploy_script_with_lib has been running for over 60 seconds

looks like this might be related to deploy/script tests so perhaps an anvil issue

**Comment by onbjerg** [comment]
Ah, I think I have an idea why this job specifically is still slow - we're cross compiling from x86 so I'm pretty sure all of these tests are being run under emulation lol

**Comment by onbjerg** [comment]
Yeah I think that's fine, cross-platform we mostly test for platform behavior anyway like paths etc.
