### ISSUE TITLE
Single command foundry deploy

### ISSUE THREAD

**Issue by ShravanSunder** [foundry-rs/foundry#1988]
### Component

Forge

### Describe the feature you would like

It would be extremely useful to have a `foundry deploy` command that works similar to `hardhat deploy`
It would work like this:
- load and run all `foundry scripts` (.sol script files) in a `deploy` folder. (run then in order based on name such as 00_deploy_uniswap)
- Run the script based on sender or mneomonic_path / index
- capture all the brodcasts for `create` transaction and the deployed `address`. 
- output them into a single export file so that they can be used by a front export.  The existing broadcast file would not be modified.

I'm learning rust, i'm willing to work on this.    @gakonst  Let me know if the proposal makes sense?  Would be happy to try it out.

**Comment by gakonst** [comment]
I think I'm leaning against having multiple scripts for a single deployment, due to how our --resume functionality works.

@joshieDo cc

**Comment by joshieDo** [comment]
I honestly don't understand much of the added value here as well. Why just not divide those steps between different functions/contracts and unify them under one `deploy()` function ?

> Run the script based on sender or mneomonic_path / index
> capture all the brodcasts for create transaction and the deployed address.
You already have this on the current iteration
> output them into a single export file so that they can be used by a front export. The existing broadcast file would not be modified.
you can always backup the latest broadcast file, and even if the latest gets overwritten, we always keep the previous log in the `broadcast/` folder.

**Comment by ShravanSunder** [comment]
Hey all, thanks for the comments.  I think the point about unifying under one deploy function makes a lot of sense.  And so does filtering broadcast.  

I'll try out the suggested method and close this case for now!

**Comment by gakonst** [comment]
Yep - I think the script feature is basically done at this point and covers every use case. Big big kudos to @brockelmore and @joshieDo
