### ISSUE TITLE
Provide a shields.io badge

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/foundry#1995]
### Describe the feature you would like

It would be nice to offer a [shields.io](https://shields.io) badge for Foundry, which would contain the logo currently found in the README:

![foundry-logo](https://user-images.githubusercontent.com/8782666/174073841-c4382c81-72b2-48fe-aff6-f90b3cbd3c66.png)

This would make it easier for devoted users to signal their allegiance to Foundry in their project READMEs.

**Comment by sambacha** [comment]
https://github.com/sambacha/foundry-badge - can submit the badge to [simpleicons repo ](https://simpleicons.org/) and have the foundry logo embedded similar to ethereum/solidity logo. however it may have too much detail and not downsize appropriately 

Here are some examples

The `use template` button when clicked will take you to generating a new repo from the template repo

Unfortunately TOML isn't a format that shields offers parsing abilities for, only yaml / json and ... xml.  

_Dash badge_

[![Foundry - ^0.8.0](https://img.shields.io/badge/Foundry-^0.8.0-black?logo=ethereum&logoColor=white)](https://book.getfoundry.sh/)

_Query parameter badge_

[![Foundry - ^0.8.0](https://img.shields.io/static/v1?label=Foundry&message=^0.8.0&color=black&logo=ethereum&logoColor=white)](https://book.getfoundry.sh/)


_Dash badge_

[![Foundry - ^0.8.0](https://img.shields.io/badge/Foundry-^0.8.0-black?logo=solidity&logoColor=white)](https://book.getfoundry.sh/)

_Query parameter badge_

[![Foundry - ^0.8.0](https://img.shields.io/static/v1?label=Foundry&message=^0.8.0&color=black&logo=solidity&logoColor=white)](https://book.getfoundry.sh/)
      

_Social buttons_

[![foundry-rs - foundry](https://img.shields.io/static/v1?label=foundry-rs&message=foundry&color=blue&logo=github)](https://github.com/foundry-rs/foundry "Go to GitHub repo")
[![stars - foundry](https://img.shields.io/github/stars/foundry-rs/foundry?style=social)](https://github.com/foundry-rs/foundry)
[![forks - foundry](https://img.shields.io/github/forks/foundry-rs/foundry?style=social)](https://github.com/foundry-rs/foundry)


_Repo metadata_

[![Release version](https://github.com/foundry-rs/foundry/workflows/Release%20version/badge.svg)](https://github.com/foundry-rs/foundry/actions?query=workflow:"Release+version")
[![GitHub tag](https://img.shields.io/github/tag/foundry-rs/foundry?include_prereleases=&sort=semver&color=blue)](https://github.com/foundry-rs/foundry/releases/)
[![License](https://img.shields.io/badge/License-(Apache--2.0_OR_MIT)-blue)](#license)
[![issues - foundry](https://img.shields.io/github/issues/foundry-rs/foundry)](https://github.com/foundry-rs/foundry/issues)

_Call-to-Action buttons_

<div align="center">

_Social buttons_

[![foundry-rs - foundry](https://img.shields.io/static/v1?label=foundry-rs&message=foundry&color=blue&logo=github)](https://github.com/foundry-rs/foundry "Go to GitHub repo")
[![stars - foundry](https://img.shields.io/github/stars/foundry-rs/foundry?style=social)](https://github.com/foundry-rs/foundry)
[![forks - foundry](https://img.shields.io/github/forks/foundry-rs/foundry?style=social)](https://github.com/foundry-rs/foundry)


_Repo metadata_

[![Release version](https://github.com/foundry-rs/foundry/workflows/Release%20version/badge.svg)](https://github.com/foundry-rs/foundry/actions?query=workflow:"Release+version")
[![GitHub tag](https://img.shields.io/github/tag/foundry-rs/foundry?include_prereleases=&sort=semver&color=blue)](https://github.com/foundry-rs/foundry/releases/)
[![License](https://img.shields.io/badge/License-(Apache--2.0_OR_MIT)-blue)](#license)
[![issues - foundry](https://img.shields.io/github/issues/foundry-rs/foundry)](https://github.com/foundry-rs/foundry/issues)

_Call-to-Action buttons_

<div align="center">

[![Use this template](https://img.shields.io/badge/Foundry-Use_Template-black)](https://github.com/foundry-rs/forge-template/generate)

## License

Released under [(Apache-2.0 OR MIT)](/LICENSE) by [@foundry-rs](https://github.com/foundry-rs).

**Comment by sambacha** [comment]
Obviously, a coverage badge would be great fit :)

**Comment by PriyankMkwna** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/foundry).

### My background and how it can be leveraged
I am a blockchain and DeFi developer . I am having experience of 8 months . I am currently working in a DeFi startup . Also I have developed algorithmic stablecoin that is pegged to INR . My experience in Web developement will help me to solve this issue .

### How I plan on tackling this issue
I am gonna take  the API from shields.io . Then I will download foundry logo and convert it to Base64 format .By using the API of shield.io , I am gonna host that logo as badge .
