### ISSUE TITLE
package to `apt` and `brew`

### ISSUE THREAD

**Issue by gakonst** [foundry-rs/foundry#20]
as title

**Comment by OdysLam** [comment]
On it @gakonst . 

The brew is fairly straightforward. Apt will prob require us to have a binary apt repo that users will add and then use apt-get install. 

The reason is that different Linux distros have different repo update cycles, leading to users lagging behind if they user Debian or Ubuntu.

**Comment by OdysLam** [comment]
- [ ] Brew - Create formula
- [ ] Brew - Create bottle
- [ ] Brew - Merge PR into main brew formula repo 
- [ ] Create APT/RPM/DEB binary repo
- [ ] RPM package
- [ ] DEB package
- [ ] AUR package
- [ ] Setup CI/CD

**Comment by lucas-manuel** [comment]
Whats the status here? Should we close/update for foundry?

**Comment by gakonst** [comment]
We don't have releases yet, so we keep open I think

**Comment by onbjerg** [comment]
AUR too please :heart: _ :heart: I use Arch btw

**Comment by lucas-manuel** [comment]
Close-able? @mds1

**Comment by mds1** [comment]
Closing in favor of https://github.com/foundry-rs/foundry/issues/494 to track all release changes for v1
