### ISSUE TITLE
Contracts Created via CREATE2 aren't automatically being verified by etherscan

### ISSUE THREAD

**Issue by JasoonS** [foundry-rs/foundry#2005]
Additionally, it would be a very cool feature if foundry would verify any contracts created by other contracts during a script too.

_Originally posted by @JasoonS in https://github.com/foundry-rs/foundry/issues/1999#issuecomment-1158519148_

**Comment by gakonst** [comment]
cc @joshieDo not sure if we didn't support it or if there's a bug

**Comment by joshieDo** [comment]
We do support it, and I don't seem able to reproduce it. All transactions below were verified with `--broadcast --verify`. The first 2 were quite fast. The mumbai one (which was the one you used I think) was slow, but it did in the end

https://testnet.snowtrace.io/address/0x84936ac950f7621c7ffd190edce36b7cedb36088#code
https://kovan-optimistic.etherscan.io/address/0xff12d35ae900bb00825728624399599b3178a407#code
https://mumbai.polygonscan.com/address/0xff12d35ae900bb00825728624399599b3178a407#code

Can you try cleaning the cache and try again?

**Comment by JasoonS** [comment]
Thanks, I ran it again and cleared the cache first and ran with the `--force` flag and it worked. But only after upgrading to solidity 0.8.15 (from 0.8.13). Strange.

I guess this isn't an issue anymore.
