### ISSUE TITLE
vm.artifact() cheatcode

### ISSUE THREAD

**Issue by odyslam** [foundry-rs/foundry#2006]
### Component

Forge

## Forge script
As an easy win before we have full json/csv read/write support, we could have a cheatcode that adds values to an artifacts output, part of the final output of a forge script run. 

That, coupled with the `--json` flag, could allow an easy and reliable way to export data from a forge script, without having to parse the raw output and regex the required data. 

Signature (like the env cheatcode):
- `vm.artifactString(string memory key, string memory value)`
- `vm.artifactAddress(string memory key, address value)`
- etc.

### Additional context

During deployments, there is a need to:
- read a config file
- do deployment/init
- store artifacts (e.g addresses)

We can input data via env variables. We can't export data.

**Comment by mds1** [comment]
> As an easy win before we have full json/csv read/write support, we could have a cheatcode that adds values to an artifacts output, part of the final output of a forge script run.

Hm, why not just skip directly to adding `readFile`/`writeFile` cheatcodes? It feels like as soon as that's introduced this becomes deprecated and can't be removed until a breaking change, and I'm not sure if this is actually any easier to implement.

Ref #1359

**Comment by odyslam** [comment]
@mds1 I optimize for speed. Whatever devs feel it's easier to implement. IMHO this is a big need for the user story of deployments, so having sth sooner than later is a big plus. 

I am not opinionated in what solution is best, provided the same time horizon

**Comment by gakonst** [comment]
Can you please give an end to end example of the use case? I still do not understand what the user story is here

**Comment by onbjerg** [comment]
@gakonst I think the Ody wants us to add this cheatcode because it might be faster to implement than `readFile`/`writeFile`, so the use case is the same as #1359. Personally I think `readFile`/`writeFile` probably has lower complexity (no need to figure out what the artifact file is, no need for ethers-solc patches) and makes more sense long term

**Comment by gakonst** [comment]
Yeah I'm on the same page. `read/write` cheats for `File` seems quite easy. for `Json` and `Csv` it might require some more thought on how to expose them as Solidity types, but I think also worth doing.

**Comment by odyslam** [comment]
The assumption was the file read/write would take longer, but I was obviously wrong 🙃
