### ISSUE TITLE
Installation error on Windows

### ISSUE THREAD

**Issue by Leutwiler** [foundry-rs/foundry#2021]
### Component

Other (please describe)

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What command(s) is the bug in?

cargo install --git https://github.com/foundry-rs/foundry foundry-cli anvil --bins --locked

### Operating System

Windows

### Describe the bug

The first time I've tried to install Foundry some months ago on Windows 10, I've faced the following error message:

`failed to run custom build command for ring v0.16.20`

This message appeared during the installation process after running the Windows installation command which is shown in the Foundry Book:
```
cargo install --git https://github.com/foundry-rs/foundry foundry-cli anvil --bins --locked
```

When I first saw this bug, I decided to go to the Foundry Support telegram group and ask how it could be fixed. By that time, @onbjerg helped me and these were the recommendations that he said that I should try in order to be able to install Foundry (the methods are presented in the real sequence).

1) Make sure to have Rust installed

2) Make sure to have Msvc build tools installed: https://docs.microsoft.com/en-us/windows/dev-environment/rust/setup#install-visual-studio-recommended-or-the-microsoft-c-build-tools

3) Try the following command:  rustup set default-host x86_64-pc-windows-msvc

Before going to the fourth recommendation, which actually was the one that solved my problem when I had it, Oliver asked for my `rustup show`, which returned:
```
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\andrey\.rustup

installed toolchains
--------------------

stable-x86_64-pc-windows-gnu (default)
stable-x86_64-pc-windows-msvc

active toolchain
----------------

stable-x86_64-pc-windows-gnu (default)
rustc 1.59.0 (9d1b2106e 2022-02-23)
```
4) Try the following command: rustup default stable-x86_64-pc-windows-msvc

This fourth step solved the problem! After typing the above line, I wrote the `cargo install` command again and everything worked fine.

I don't exactly know how much every step is correlated to one another, that's why I'm providing the full explanation instead of just sending the fourth step in this issue :)

I decided to open this issue because yesterday another person had the same issued I had had in the past and he asked for a solution in our telegram group. I don't know exactly what causes this error, but as there are still many Windows users out there, I think this bug should be fixed, so it doesn't scare away newcomers who run Windows.

You can see the complete error message in this picture which was recently posted by other person who had the same issue (Evergreen) on the Foundry Support telegram group:
![image](https://user-images.githubusercontent.com/93873392/174452967-73c59f20-3e66-4ae5-829b-68849f835986.png)

**Comment by onbjerg** [comment]
I think the issue is that some people might be using the GNU toolchain without having those tools installed, so the general advice/requirements would be:

1. Install Rust using rustup
2. Make sure to have MSVC build tools installed (Rust needs this)
3. Install the MSVC toolchain: `rustup default x86_64-pc-windows-msvc`

More generally though, we should get Windows builds working again so no one has to compile from source if they don't want to
