### ISSUE TITLE
Add ipc support for anvil

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#2023]
### Component

Anvil

### Describe the feature you would like

add support for sending requests via ipc for
- [ ] unix
- [ ] windows (named pipes)

adding this on UNIX should be fairly simple by creating a new file at the configured location and connecting via `tokio::UnixStream`

ref https://github.com/servo/ipc-channel

**Comment by mirekskrabal** [comment]
Hi! Do you plan to implement this feature any time soon?

We are developing a python-based security/testing framework (detectors, lsp server, testing framework, fuzzing), see https://github.com/Ackee-Blockchain/woke. We want to use Anvil as the main devchain and would like to connect to it via IPC for performance.
