### ISSUE TITLE
cast sig bug

### ISSUE THREAD

**Issue by justforfunya** [foundry-rs/foundry#2025]
### Component

Cast

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### Operating System

Linux

### Describe the bug

$ cast sig "aggregate((address,bytes)[])"
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: Message("Expected input args parentheses at `aggregate((address,bytes)[])`")
Location: cli/src/cast.rs:651

**Comment by mattsse** [comment]
our current abi parser has some issues with tuple arrays...
but a fix for that should land shortly

**Comment by onbjerg** [comment]
Ref #1521 and #670
