### ISSUE TITLE
perf: reuse forked backend in script command

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#2028]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### Describe the bug

during script, we end up creating multiple instances of a fork backend, that's why the tests take so long lol

here 

https://github.com/foundry-rs/foundry/blob/e4a29157b04ada49d7e21e339b5ed6cf131d58e9/cli/src/cmd/forge/script/executor.rs#L33

and

https://github.com/foundry-rs/foundry/blob/e4a29157b04ada49d7e21e339b5ed6cf131d58e9/cli/src/cmd/forge/script/executor.rs#L78

which is invoked by `handle_broadcastable_transactions`  

https://github.com/foundry-rs/foundry/blob/e4a29157b04ada49d7e21e339b5ed6cf131d58e9/cli/src/cmd/forge/script/cmd.rs#L147

if I understand it correctly, the first `ScriptRunner::execute` is for executing the script contract and then we execute/simulate the transactions, right @joshieDo

**Comment by joshieDo** [comment]
i think it can be closed given 2475 has been merged?
