### ISSUE TITLE
Making requests really fast on Fork mode causes Block Hash error

### ISSUE THREAD

**Issue by unparalleled-js** [foundry-rs/foundry#2036]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e4a2915 2022-06-20T00:04:23.839115Z)

### What command(s) is the bug in?

anvil --fork-url <url>

### Describe the bug

* Start Anvil process in Fork mode
* Make scripts that makes requests using an HTTP connection against the Anvil process (such as when using web3.py)
* Notice Anvil process errors out

```
thread 'fork-backend-thread' panicked at 'Failed to get block hash for 14998061
block 14998061 not found', /Users/runner/work/foundry/foundry/evm/src/executor/fork/backend.rs:310:33
stack backtrace:
   0:        0x107d76319 - __mh_execute_header
   1:        0x107ac81eb - __mh_execute_header
   2:        0x107d4bba8 - __mh_execute_header
   3:        0x107d7958d - __mh_execute_header
   4:        0x107d7a330 - __mh_execute_header
   5:        0x107d79eb4 - __mh_execute_header
   6:        0x107d79e29 - __mh_execute_header
   7:        0x107d79de5 - __mh_execute_header
   8:        0x107e01c93 - __mh_execute_header
   9:        0x1077abd47 - __mh_execute_header
  10:        0x1077f1e6e - __mh_execute_header
  11:        0x1077ba1d3 - __mh_execute_header
  12:        0x1077bc575 - __mh_execute_header
  13:        0x107d7b189 - __mh_execute_header
  14:     0x7ff8196ba4e1 - __pthread_start
```

possible related to https://github.com/foundry-rs/foundry/issues/1902

**Comment by mattsse** [comment]
by default, we fork off the "latest" block,

but this error occurs when requesting the block hash of the latest block fails, basically the `Block` response has no hash field yet.

which would indicate that there's some latency somewhere within the provider's client I think

perhaps we should select the "latest" block that already has a hash when queried via `eth_getBlockByHash`?

**Comment by mattsse** [comment]
closing this optimistically since addressed in #2057 which hopefully has fixed this, lmk if you're still seeing this

**Comment by unparalleled-js** [comment]
@mattsse I am still experiencing this issue!
It happens just randomly but only when using forked networks.

Some conditions cause it happen more than others, such as different ways of managing the output of the Anvil subprocess... 
It seems like a timing issue. Maybe I am transacting too fast?

**Comment by unparalleled-js** [comment]
Here is some logs I am seeing:

```
INFO     foundry_stdout_subprocessProviderLogger:providers.py:1017 b"thread 'fork-backend-thread' panicked at 'Failed to get block hash for 15104476\n"
INFO     foundry_stdout_subprocessProviderLogger:providers.py:1017 b"block 15104476 not found', /home/runner/work/foundry/foundry/evm/src/executor/fork/backend.rs:310:33\n"
```
