### ISSUE TITLE
Make cast block behave as `seth block` by removing the `--block` required argument

### ISSUE THREAD

**Issue by sameul2012** [foundry-rs/foundry#2050]
### Component

Forge

### Describe the feature you would like

What this error means? How to solve it?

error: Found argument 'latest' which wasn't expected, or isn't valid in this context

![image](https://user-images.githubusercontent.com/106046511/174818454-486037d8-7036-42cf-8e67-7c640d8ffa7f.png)

**Comment by mattsse** [comment]
you're missing the `--block` argument

this makes me wonder why this is even required, that's also not 1:1 to `seth block` https://github.com/dapphub/dapptools/tree/master/src/seth#seth-block

**Comment by mds1** [comment]
> this makes me wonder why this is even required, that's also not 1:1 to seth block https://github.com/dapphub/dapptools/tree/master/src/seth#seth-block

Yea this has always bugged me when using this command, I'm guessing it was oversight whenever `cast block` was introduced
