### ISSUE TITLE
Impersonate accounts on `forge script --broadcast` to Anvil

### ISSUE THREAD

**Issue by ThomasdenH** [foundry-rs/foundry#2051]
### Component

Forge

### Describe the feature you would like

Anvil currently has the functionality to impersonate accounts (`anvil_impersonatingAccount`). However, (I think) it's currently impossible to impersonate accounts from `forge script`. For example, for deploying a contract you may need approval from some existing admin contract. Currently `vm.broadcast(adminContractAddress)` fails because the contract is not unlocked.

**Comment by jameswenzel** [comment]
+1, would be very useful for integration tests that fork mainnet

**Comment by jordaniza** [comment]
+1 to keep scripts consistent across tests and forks!

**Comment by zaqk** [comment]
+1 this would be extremely helpful

**Comment by ethanhunsaker** [comment]
+1 would love this feature

**Comment by rpedroni** [comment]
Extremely useful :)
Current workaround is impersonating through anvil, updating the contract I interact with the script to give my calling pk the required privileges and then running forge

**Comment by ZrowGz** [comment]
+1 this would be amazing. The impersonate account doesn't quite work as optimally as it could and this would be very powerful for creating functional deployments on anvil. Would be important for the impersonated interactions to be persistent unlike `vm.startBroadcast(impersonated-account);`

**Comment by rpedroni** [comment]
@mattsse @mds1 can we consider this closed based on #3614 ?

**Comment by mattsse** [comment]
This should be supported now, if `--unlocked` then we send via `eth_sendTransaction`

will update docs shortly.

But we can consider this closed. If there are new problems then lets track those separately.
