### ISSUE TITLE
what this error of 'requires an argument' means?

### ISSUE THREAD

**Issue by sameul2012** [foundry-rs/foundry#2052]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### Operating System

macOS (Intel)

### Describe the bug

When I try to run the docker, got below error:

![image](https://user-images.githubusercontent.com/106046511/174836515-6f6f1351-7cf5-4395-8cf5-a3961537692f.png)

Although docker pull worked fine, how to use the image, downloaded?

**Comment by mattsse** [comment]
this is ht e `-c` argument of `sh` which expects an argument

closing this as unrelated, also consider using the support channel for issues like these, thanks

**Comment by sameul2012** [comment]
Yes, thanks for reply, could you help to indicate where should I get help about this issue?
`sh` need one `-c` argument, what this means?

**Comment by deniztoprak** [comment]
You are probably trying to run the container without any command. You should run the foundry container as an executable instead and provide the commands. Take a look at the official doc:

https://book.getfoundry.sh/tutorials/foundry-docker
