### ISSUE TITLE
feat: expand snapshot functionality

### ISSUE THREAD

**Issue by mds1** [foundry-rs/foundry#2056]
### Component

Forge

### Describe the feature you would like

_Inspired by [this](https://twitter.com/msolomon44/status/1539266598594174978) twitter convo_ 

### Feature Spec

Right now `forge snapshot` saves the gas usage of each test to a file called `.gas-snapshot`. This is useful for things like gas golfing, or ensuring that a changeset does not increase gas costs. Similar functionality can be applied to other properties of a codebase.

I propose modifying `forge snapshot` as follows:

Instead of being a single command, it now has subcommands to snapshot various things:
- `forge snapshot gas` behaves like `forge snapshot` currently does.
- `forge snapshot size` is equivalent to running `forge build --sizes` and saving the output table.
- `forge snapshot <fieldName>` would let you snapshot any solc field name supported by `forge inspect`. By default this would snapshot the field for all contracts in the `src` directory

Instead of saving to the project root, these commands save a file called `<property>.snapshot` to a folder named something like `snapshot`, `snap`, or `ss`. Examples:
- `forge snapshot gas` results in `snapshot/gas.snapshot`
- `forge snapshot storage-layout` results in `snapshot/storage-layout.snapshot`

The `--check`, `--diff`, and `--snap` options should be supported for each subcommand and behave the same as they do now. Some subcommands may have additional options, such as:
- `--include-fuzz-tests` for gas snapshots, or always including fuzz tests and just specifying the seed here
- `--asc` and `--desc` should be supported for ones where sorting makes sense, such as gas and size snapshots.

### Open questions
1.  Are we ok with implementing this breaking change to snapshot behavior without waiting for a specific breaking change foundry release? Let's get thoughts from snapshot users, but IMO this is useful enough and a small enough breaking change that we should be ok with it.
2. `forge inspect` supports multiple variants for a given property. For example, you can [see](https://book.getfoundry.sh/reference/forge/forge-inspect.html#forge-inspect) that `forge inspect MyContract storage`, `forge inspect MyContract storageLayout`, `forge inspect MyContract storage-layout`, and `forge inspect MyContract storage_layout` all print the storage layout. We'd want to standardize on which name we use for the output files. My suggestion is using the JSON field name output by solc, which for this example I believe is `storage`.

**Comment by maurelian** [comment]
Only comment is that we'd definitely love to see this given I was [speccing](https://github.com/ethereum-optimism/optimism/pull/2810#issuecomment-1162018672) out a similar script for ourselves around the time this issue was created. For now I will likely follow the [approach](https://github.com/nomad-xyz/monorepo/pull/344/files#diff-720f0d51666dbb1ee24061d5b74c8f5177105d4291135151b73f9c429c69c28e) used by nomad.

**Comment by mds1** [comment]
Some other ideas for gas snapshots specifically can be found in https://github.com/foundry-rs/foundry/issues/137

**Comment by zerosnacks** [comment]
Considering the growing popularity of https://github.com/marktoda/forge-gas-snapshot (used in Uniswap V4, Balancer V3, Euler V2) I've proposed to add native functionality for its feature set.

There is rough consensus on moving ahead with the following changes:

- Add new `read-write` access rights to a folder in the project root `.snapshots`, meant to be checked into `.git`
- Enable the (over)writing of individual `snaps` into the `.snapshots` folder (`.snapshots/<name>.snap) through a number of cheatcodes:
  - Clear:
    - `vm.snapStart(string calldata name)`
    - `vm.snapEnd()` (ends the most recently opened snap)
  
  - Possibly:
    - `vm.snap(string calldata name, uint256 value)`
    - `vm.snapSize(string calldata name, address target)`
  
  - Optionally (if possible):
    - `vm.snap(string calldata name, function() external fn)` (snapshot a given external closure)
    - `vm.snap(string calldata name, function() internal fn)` (snapshot a given internal closure)

Some of my concerns:

- The current existence of the `vm.snapshot` cheatcode relating to capturing state snapshots: https://github.com/foundry-rs/foundry/blob/af97b2c75cbcfaba23462998ae75ca082bcca1f2/crates/cheatcodes/spec/src/vm.rs#L522-L558
- We have a lot of cheatcodes dealing with gas: `lastCallGas`, `pauseGasMetering`, `resumeGasMetering`, the `Gas` struct.
- Not a huge fan of the `snap*` naming but the cheatcode has to be short and memorable as developers will likely add it throughout their tests (https://github.com/search?q=repo%3AUniswap%2Fv4-core%20snapStart&type=code)

@mds1 curious on your thoughts about this proposal

**Comment by marktoda** [comment]
Thanks for proposing this @zerosnacks - I'm (obviously) very in favor of upstreaming this into Foundry. For a bit more context, the primary reason we prefer this type of snapshotting at Uniswap is to get maximal granularity, allowing us to check how the gas of specific flows change over time in version control.

Generally I think the approach makes sense. A couple ideas -
- Possible to automatically generate the snapshot name? For example `testContractName.testFunction` as a default if not overridden with a specific string. Would have loved to do this with the library if we had introspection
- Possibly merge all snaps into files by test contract? The file-per-snap gets a bit unwieldy, you can see we have [dozens](https://github.com/Uniswap/v4-core/tree/main/.forge-snapshots) of files in v4 snaps dir
- Potentially add `vm.snapLastCall` which wraps `lastCallGas`? Single call is a very common use case and would be nice to skip the wrapping steps
