### ISSUE TITLE
not work signature identifier for traces when use forge test

### ISSUE THREAD

**Issue by l0ca1** [foundry-rs/foundry#2062]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (935c113 2022-06-22T00:17:48.239446Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Intel)

### Describe the bug

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.12;

import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {DSTest} from "ds-test/test.sol";

contract Contract is DSTest {
    address owner;
    modifier OnlyOwner() {
        require(msg.sender == owner);
        _;
    }
    receive() external payable {}
    fallback() external payable {}
    constructor() payable {
        owner = msg.sender;
    }
    function test() public {
        IERC20(0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2).balanceOf(
            address(this)
        );
    }
}
```
signature:`0x70a08231 -> balanceOf(address)`

when use `forge script contracts/Contract.sol -vvvvv --tc Contract --sig "test()"` :
![image](https://user-images.githubusercontent.com/23295562/174938790-1087a0b2-2948-479a-b50d-06f241c219e2.png)

but use `forge test --match-contract Contract --fork-url $MAINNET_RPC --fork-block-number 149724xx -vvvv`:
![image](https://user-images.githubusercontent.com/23295562/174938896-91ef99f2-0bf5-40d8-a20a-ef315a3fc053.png)

**Comment by l0ca1** [comment]
cli/src/cmd/forge/test.rs add this code can work:
```
decoder.add_signature_identifier(SignaturesIdentifier::new(
	Config::foundry_cache_dir(),
)?);
```

**Comment by joshieDo** [comment]
I added only to `cast run` and `forge script`, since I don't think it fits `forge test`. One would only turn on tracing when trying to figure out when a test is failing no? More than that, one should just use `forge script` no? Also, if you have a big test suit it could slow it down depending on how many requests we make.

But I don't have a very strong opinion about the matter.

**Comment by onbjerg** [comment]
Fixed in the latest nightly
