### ISSUE TITLE
Enable writing gas reports for specific contracts to `.snapshot`

### ISSUE THREAD

**Issue by wilsoncusack** [foundry-rs/foundry#2065]
### Component

Forge

### Describe the feature you would like

Problem: 
Currently, changes in `.snapshot` do not necessarily reflect gas changes a developer cares about. Snapshots directly reflect the gas use of the test functions, and only indirectly reflect the gas used by the contract being tested. 

If a developer changes a test and the contract being tested in the same diff, they lose signal in the `.snapshot` as to the gas effect of their changes. 

We see many developers solve this by creating super minimal tests with names like `testXGas` so that they always have some indication of *exclusively* the changing gas use in the contract being tested. 

In fact, for me personally, I generally *only* care about the snapshot of these functions. The gas snapshot of all the other functions is mostly just noise. 

`Proposed solution`
A very useful tool is `forge test --gas-report` it shows the gas use of each function in each contract! This is great, and could be super powered by (1) enabling writing this gas report to the snapshot (2) enabling passing arguments as to which contracts we exclusively want gas reports for. 

The command might look something like 
```
forge snapshot --gas-report --contracts MyContract
```
This command could run existing snapshot functionality and additionally write the gas report of the specified contracts to the end of the snapshot. Though, for me personally, if writing the gas-report to snapshot existed, I could do without the existing snapshot functionality entirely, I think. Possibly still nice for quickly checking gas of something, though.

**Comment by onbjerg** [comment]
As mentioned in another snapshot/gas report issue/request recently we used to talk about just merging `forge snapshot` and the gas report feature because they both have strengths and shortcomings: snapshots have `--check`, `--diff` and disk saving (which gas reports lack) and gas reports have more info and less noise in the readings

**Comment by wilsoncusack** [comment]
> As mentioned in another snapshot/gas report issue/request recently we used to talk about just merging `forge snapshot` and the gas report feature because they both have strengths and shortcomings: snapshots have `--check`, `--diff` and disk saving (which gas reports lack) and gas reports have more info and less noise in the readings

Ok got it, thanks. Feel free to close if this is a duplicate.

**Comment by wilsoncusack** [comment]
@gakonst I'm happy to work on this if we can get consensus on what to implement :)

**Comment by mds1** [comment]
Maybe some optimizoors disagree (and I'd be curious to hear their thoughts first), but my suggestion would be:
- deprecate the existing `forge snapshot` behavior for the reasons mentioned above (it's sensitive to test file changes)
- replace it with `forge snapshot <subcommand>` as spec'd out in https://github.com/foundry-rs/foundry/issues/2056, where `forge snapshot gas` uses the gas-report behavior and supports `--diff` and `--check` options

**Comment by wilsoncusack** [comment]
Sorry @mds1 just saw your reply. That sounds reasonable to me! I'd propose default new snapshot is just to write gas-report.

**Comment by zerosnacks** [comment]
Related repo: https://github.com/marktoda/forge-gas-snapshot/
In use for Uniswap V4: https://github.com/Uniswap/v4-core/tree/main/.forge-snapshots

Would be great to upstream this into Foundry
