### ISSUE TITLE
feat: make checksum addresses the default in traces and outputs

### ISSUE THREAD

**Issue by mds1** [foundry-rs/foundry#2071]
### Component

Forge, Cast, Anvil

### Describe the feature you would like

Right now most (all?) addresses printed to the terminal are lowercased. Often I want to copy that address in solidity, which requires checksummed addresses, so I need to checksum it manually using e.g. `cast --to-checksum-address`.

In general, some tools/apps require checksum addresses, some support both, and I've never seen one that requires lowercase. So in my opinion always using checksum addresses is more convenient without any downsides.

**Comment by mattsse** [comment]
definitely @ptisserand 

there's already the `to_checksum` function 

https://github.com/gakonst/ethers-rs/blob/a41ae901e58fbe45e5ec037d57f6e75a85ef1cc9/ethers-core/src/utils/mod.rs#L267

So either use that function everywhere

or do something like

```rust
trait AddressExt {
  fn to_checksum_address(&self) -> String
}


impl AddressExt for Address {...}
```

so you can call it directly on an `Address`

**Comment by ptisserand** [comment]
Thanks for your feedback @mattsse, can I pick this issue?

**Comment by gatesyp** [comment]
Looks like this has already been merged -- can we close this issue?
