### ISSUE TITLE
Improve etherscan-api-key cli arguments

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#2074]
### Component

Forge

### Describe the feature you would like

we also support verifying via blockscout so we should

- [ ] add an alias to `etherscan-api-key` argument, like `verify-api-key` or smth
- [ ] add env support for {FOUNDRY_}{etherscan/verify}-api-key env var

**Comment by Genysys** [comment]
Can I pick this up?

**Comment by onbjerg** [comment]
Yep, feel free!

**Comment by onbjerg** [comment]
Assigned to @mattsse since it is being fixed in #2616
