### ISSUE TITLE
Investigate failing windows CI job

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#2078]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### Describe the bug

> thread 'multi_runner::tests::test_cheats' panicked at 'called `Result::unwrap()` on an `Err` value: Io(SolcIoError { io: Os { code: 193, kind: Uncategorized, message: "%1 is not a valid Win32 application." }, path: "C:\\Users\\runneradmin\\.svm\\0.6.12\\solc-0.6.12" })', forge\src\test_helpers.rs:45:36

https://github.com/foundry-rs/foundry/runs/7006059778?check_suite_focus=true

perhaps this is some solc win32 snafu, perhaps with the 0.6.12 version

from googling "%1 is not a valid Win32 application.", this could be an issue with the PATH var or a general windows OS related issue https://stackoverflow.com/questions/185042/how-do-i-resolve-1-is-not-a-valid-win32-application

**Comment by onbjerg** [comment]
That's weird, it was passing yesterday.. Did we update a dependency or something?

**Comment by mattsse** [comment]
ah failed directly after reenabling windows tests 

https://github.com/foundry-rs/foundry/runs/6983526650?check_suite_focus=true

**Comment by onbjerg** [comment]
Lmao it passed in the PR :man_facepalming: I'll check it out

**Comment by mattsse** [comment]
there's only 64bit support

https://github.com/roynalnaruto/svm-rs/blob/50b1d676544f4d449be92381ba693af3ae4dc5ad/src/platform.rs#L23

however the runner is 64bit, right? so the 32bit msg is confusing, no experience with windows though, like none at all

**Comment by sambacha** [comment]
> Seems like a lot of old Windows releases were shipped in .zip files which is not the case for any other platform, 0.6.12 among them 😮‍💨
> 
> Working on a fix here: [roynalnaruto/svm-rs#50](https://github.com/roynalnaruto/svm-rs/pull/50)

up to version 0.7.1 was shipped solidity-windows.zip, afterwards, they packaged as .exe

[see https://github.com/solcbin/index/blob/master/solidity.index.json](https://github.com/solcbin/index/blob/master/solidity.index.json)
