### ISSUE TITLE
Option to preserve directories in `out` artifacts

### ISSUE THREAD

**Issue by holic** [foundry-rs/foundry#2079]
### Component

Forge

### Describe the feature you would like

Forge writes out Solidity artifacts in a flat structure. Is it possible to allow for maintaining the directory structure (or at least the top level directories like `src` `lib` and `test`) inside the artifacts `out`?

I am using TypeChain to generate TS types for contracts and when I point it at the `out` directory, I get a lot of typed files for Solidity that I'll never end up using (mostly test stuff). I am able to exclude files with `.t.sol` extensions but it doesn't help for transitive dependencies like `Test.sol` and `Vm.sol` and `console.sol` from `forge-std`.

My typechain command looks something like:
```bash
typechain --target ethers-v5 "out/**/!(*.t|test).sol/!(*.abi).json" --out-dir types
```

I'd rather not have to maintain a list of every contract/solidity file to generate types for and update that as I add more to the list. A slightly more nested directory structure in `out` would help with this and could use a glob like:
```bash
typechain --target ethers-v5 "out/src/**/!(*.abi).json" --out-dir types
```

Also open to other ideas!

### Additional context

Here's an example repo using forge: https://github.com/holic/web3-scaffold

And a recent PR that moves from `ds-test` to `forge-std`: https://github.com/holic/web3-scaffold/pull/20

I've opted to generate types (and compile down to JS) + check them into the repo for ease of use when importing them into/using them from the app package. I have a CI script that ensures the built files are up to date with the source files. (This was all previously done at deploy time but added too much time to the deploy step, which happens more often than editing Solidity).

**Comment by onbjerg** [comment]
Ref #1488

**Comment by mattsse** [comment]
this is a reasonable request and probably the best solution for #1488

I think I can make this happen on ethers-solc which is responsible for emitting artifacts. 
I'll make this optional first and then we can decide whether we make this or some adjacent layout the default

**Comment by holic** [comment]
Rad, thanks ya'll 🙏

**Comment by tynes** [comment]
We use typechain with https://github.com/foundry-rs/hardhat which creates hardhat style artifacts that typechain can consume

**Comment by onbjerg** [comment]
Note here: This should be an optional mode

**Comment by hellowodl** [comment]
> We use typechain with https://github.com/foundry-rs/hardhat which creates hardhat style artifacts that typechain can consume

In order to not tempt coworkers into using Hardhat functionality when there's an alternative within Foundry itself, I've opted to write a script that generates & executes a TypeChain command based upon the files available in ./src/

```js
import { glob } from "glob";
import { basename, normalize } from "node:path";

const files = (await glob("./src/**/*.sol")).map((str) => basename(str));

const { stdout, stderr } = Bun.spawn([
  "npx",
  "typechain",
  "--target=ethers-v6",
  normalize(`./out/{${files.join(",")}}/*.json`),
]);
```
It's written with Bun, though it should be fairly simple to convert it to node.

**Comment by zerosnacks** [comment]
Typechain has been deprecated and successors like Viem have Foundry support out of the box

Marking this as not planned.
