### ISSUE TITLE
using the geth library to get latest block after calling `evm_mine` returns an error `hex string of odd length`

### ISSUE THREAD

**Issue by krasi-georgiev** [foundry-rs/foundry#2088]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9b2d95d 2022-06-23T00:13:03.193579407Z)

### Operating System

Linux

### Describe the bug

steps to replicate

```
anvil --fork-url https://eth-mainnet.alchemyapi.io/v2/....
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"evm_mine","id":67}' http://localhost:8545

client, err := ethclient.Dial("http://localhost:8545")
if err != nil {
	panic(err)
}

_, err = client.BlockByNumber(context.Background(), nil) // panic: hex string of odd length
if err != nil {
	panic(err)
}
```

the same works fine with hardhat

**Comment by mattsse** [comment]
thanks for flagging

this will be fixed by https://github.com/gakonst/ethers-rs/pull/1396
