### ISSUE TITLE
[anvil] Simulate flashbot endpoint for local forks.

### ISSUE THREAD

**Issue by krasi-georgiev** [foundry-rs/foundry#2089]
### Component

Anvil

### Describe the feature you would like

the salmonella and different variation are a good example of why it would be great to allow testing TX as if they were sent to the flashbot endpoints.

Ideally can replicate the exact API of flashbot so that software written to interact with flashbot can run it against a local fork without any special handling.

Currently, there is no way to run flashbot TX tests on mainnet and this feature would be quite useful I think

**Comment by onbjerg** [comment]
You can use Flashbots's simulation endpoint to run tests against mainnet :)

**Comment by mattsse** [comment]
not sure I fully understand this yet,

as @onbjerg mentioned flashbots has the bundle simulation endpoint which is basically an `eth_Call` iirc.

but sounds like the feature you want is for anvil to support flashbots' rpc endpoints so you can send this locally and mimic mev-geth's bundle execution?

**Comment by krasi-georgiev** [comment]
I was thinking to have `eth_sendBundle` and `eth_callBundle` exactly like the flashbot API, but maybe not a good idea as this will just polite the API with all these custom implementations. I will close for now and will re-open if this turns out to be a big issue again.


https://docs.flashbots.net/flashbots-auction/searchers/advanced/rpc-endpoint

**Comment by sambacha** [comment]
> I was thinking to have `eth_sendBundle` and `eth_callBundle` exactly like the flashbot API, but maybe not a good idea as this will just pollute the API with all these custom implementations. I will close for now and will re-open if this turns out to be a big issue again.
> 
> [docs.flashbots.net/flashbots-auction/searchers/advanced/rpc-endpoint](https://docs.flashbots.net/flashbots-auction/searchers/advanced/rpc-endpoint)

this may help: https://github.com/manifoldfinance/bundle-simulator

**Comment by Theo-** [comment]
Hi, we'd like to request this feature as well. Bundles are a big part of Ethereum and are hard to test with Anvil.
