### ISSUE TITLE
forge test --debug crashes: "Target not found?"

### ISSUE THREAD

**Issue by Icezelion** [foundry-rs/foundry#2092]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (7b9d3ad 2022-06-17T21:57:41.4016897Z)

### What command(s) is the bug in?

forge test

### Operating System

Windows

### Describe the bug

I'm trying to debug a test for a contract using `forge test` but i can't do so for some reason, `forge debug` runs just fine:

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

contract Contract {
    uint256 public count = 0;

    function plus() public {
        count += 1;
    }
}
```

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import "forge-std/Test.sol";
import "src/Contract.sol";


contract ContractTest is Test {
    Contract c;
    
    function setUp() public {
        c = new Contract();
    }

    function testCount() public {
        assertEq(c.count(), 0);
        c.plus();
        assertEq(c.count(), 1);
    }
}
```

Trying to run: `forge test --debug "testCount"` gives me this:

```
C:\Users\proto\Desktop\foundry-play>forge test --debug testCount
[⠔] Compiling...
[⠊] Compiling 1 files with 0.8.15
[⠒] Solc 0.8.15 finished in 1.49s
Compiler run successful
[⠔] Compiling...
Nothing to compile
The application panicked (crashed).
Message:  Target not found?
Location: cli\src\cmd\forge\script\build.rs:163

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

while using `forge debug --debug test/Contract.t.sol --sig "testCount()"` works just fine, not sure if i am missing something here?

**Comment by mattsse** [comment]
can you foundryup and try again?

**Comment by onbjerg** [comment]
Same error as #2085 and both of them use `forge script` by proxy (`forge test --debug` calls `forge debug` which is a wrapper around `forge script`)

**Comment by mattsse** [comment]
I am not sure why this is happening or what the error is.
how can we fix this?

**Comment by mattsse** [comment]
ah sorry missed that this is on windows.

just to confirm, standalone forge build and test work as expected and even forge debug

so it's just the forge test --debug combination that's not working?

we should be able to pin this down by comparing how we determine the target in forge debug vs forge test --debug

**Comment by onbjerg** [comment]
Well the other issue was also on Windows and used `forge script` directly - `forge test --debug` calls `forge debug`, which calls `forge script`. The debugger in `forge script` does not seem to work in some cases on Windows as described in the other issue - I think the case was if you specified *both* path *and* contract name, which is exactly what `forge test --debug` always does

**Comment by onbjerg** [comment]
Can you check the nightly that will be released in a few hours? None of us really use Windows so it's sort of a pain to figure out what the underlying cause is.

**Comment by NewCoNam** [comment]
I am also experience same problem after the nightly version using WSL
`forge debug --debug src/contracts/core/interfaces/IVault.sol --sig "inManagerMode()"
[⠒] Compiling...
[⠔] Compiling 2 files with 0.6.12
[⠃] Solc 0.6.12 finished in 254.54ms
Compiler run successful
The application panicked (crashed).
Message:  Target not found?
Location: cli/src/cmd/forge/script/build.rs:168

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Aborted (core dumped)`
