### ISSUE TITLE
feat: restrict default allowed paths for file reading/writing

### ISSUE THREAD

**Issue by mds1** [foundry-rs/foundry#2096]
### Component

Forge

### Describe the feature you would like

In https://github.com/foundry-rs/foundry/pull/2038, cheatcodes were introduced to read and write to system files. It seems they have no restrictions on the paths they can read from / write to, meaning someone can trick you into executing a malicious test suite that overwrites important system files.

By default, we should limit those cheatcodes to only working within the foundry project directory. Additionally, we should either:
- add a config option to extend the allowed system paths, or
- treat it similarly to ffi with a special `--io` flag that allows writing to/from anywhere on the system

cc @shekhirin

**Comment by mds1** [comment]
That seems reasonable to me

**Comment by shekhirin** [comment]
That's a very good addition given that `--ffi` isn't needed for these filesystem cheatcodes, thanks!

**Comment by shekhirin** [comment]
@onbjerg you can assign this one to me
