### ISSUE TITLE
Install (and download) missing dependencies automatically

### ISSUE THREAD

**Issue by shekhirin** [foundry-rs/foundry#2098]
### Component

Forge

### Describe the feature you would like

I tried to run tests for the repo I've just cloned and it failed due to missing dependencies:
```console
➜  mev-example git:(curve20220521) ✗ forge test --fork-url $ETH_RPC_URL --fork-block-number 14811888 -vvv
[⠊] Compiling...
Error:
Failed to resolve file: "/Users/shekhirin/Projects/mev-example/lib/forge-std/src/Test.sol": No such file or directory (os error 2).
 Check configured remappings.
```

After installing them, all worked as expected:
```console
➜  mev-example git:(curve20220521) ✗ forge install
➜  mev-example git:(curve20220521) forge test --fork-url $ETH_RPC_URL --fork-block-number 14811888 -vvv
[⠒] Compiling...
[⠔] Compiling 16 files with 0.8.14
[⠒] Solc 0.8.14 finished in 1.35s
Compiler run successful

Running 1 test for test/MEV.t.sol:MEVSimulation
[PASS] testMEV() (gas: 2043432)
Test result: ok. 1 passed; 0 failed; finished in 476.13ms
```

---

I think there's two ways we can improve it:
1. Improve error message because current tells us only about remappings check.
2. Install and download missing dependencies behind the scenes like `cargo` does it:
    <img width="1004" alt="image" src="https://user-images.githubusercontent.com/5773434/175359233-1b42930f-f593-4966-9eb3-d7db1739b2fb.png">

**Comment by shekhirin** [comment]
> this will require a bit of work, basically managing a registry

i think `forge install` invocation before every command that may require deps would work as an MVP?

**Comment by onbjerg** [comment]
If we end up doing a dependency section in `foundry.toml` I'd ask if we could design it in a way where git is *one* way to install (the only supported way currently) so we can expand it later if needed. There's been quite a few issues/discussions about doing an alternative to Git submodules, so allowing for that in a dependencies section would future proof us a bit

**Comment by onbjerg** [comment]
@shekhirin Opened a PR for the quickfix in #2617, moved the discussion around better package management into #2618
