### ISSUE TITLE
[coverage] lcov report: branch line number is incorrect

### ISSUE THREAD

**Issue by izlatkin** [foundry-rs/foundry#2105]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

latest

### What command(s) is the bug in?

forge coverage

### Operating System

Linux

### Describe the bug

Looks like the value of `BRDA` is incorrect in `lcov.info`

`forge coverage  --report lcov`

Examples:
<img width="598" alt="image" src="https://user-images.githubusercontent.com/16242682/175424259-8b4a34a3-8ab0-4053-aa7c-34163087fd26.png">
<img width="701" alt="image" src="https://user-images.githubusercontent.com/16242682/175425320-68a05505-211d-4548-b7b4-051fc8496e2e.png">

**Comment by onbjerg** [comment]
Already fixed, will be out with latest nightly - please note however that `forge coverage` is *not* in a dependable state right now as there are a lot of edge cases and missing features.
