### ISSUE TITLE
coverage fails with 'yul if statement had no body'

### ISSUE THREAD

**Issue by maurelian** [foundry-rs/foundry#2111]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9b2d95d 2022-06-23T00:22:22.617534Z)

### What command(s) is the bug in?

forge coverage

### Operating System

macOS (Apple Silicon)

### Describe the bug

First, so glad to see coverage shipped, thanks @onbjerg!

This is possibly related to #1968, but I'm opening a fresh issue to keep things clean. Below I will discuss the issue in the context of the Optimism monorepo, but I've also created a minimal repro example [here](https://github.com/maurelian/solidity-sandbox/blob/main/src/test/12_yul.sol#L10-L16). 

**Issue:**

When I run `forge coverage` in [this dir](https://github.com/ethereum-optimism/optimism/tree/develop/packages/contracts-bedrock) of our repo, it fails with `yul if statement had no body`.

I searched through all of the assembly block in solidity code within that directory, and could only find [one instance](https://github.com/ethereum-optimism/optimism/blob/79f31007470b582ab79718e5e021687e42f92865/packages/contracts-bedrock/contracts/libraries/rlp/Lib_RLPReader.sol#L158) of a yul `if` statement, which does look like it has a body. 

What's odd is that I was unable to get past the issue by rewriting it as a `switch`/`case` statement (which did work OK in the minimal repro I linked above). So perhaps the issue is in a dependency (I will go check now).

**Comment by onbjerg** [comment]
Interesting, I'll take a look. Perhaps the AST for `YulIf` is read wrong. Will just note here (as I've done for other coverage issues) that coverage is not dependable right now since there are a lot of edge cases and some missing features :) Thanks for taking it for a spin

**Comment by onbjerg** [comment]
Ok I figured it out - essentially I had moved the `body` data from one part of the underlying data structure to another part. The original place where it was residing was not super strongly typed so I had no idea :smile: Will submit a fix shortly

**Comment by maurelian** [comment]
> Will just note here (as I've done for other coverage issues) that coverage is not dependable right now since there are a lot of edge cases and some missing features :) Thanks for taking it for a spin

Certainly! We're excited about this feature, and very happy to help improve it. Thanks for the quick response! :)
