### ISSUE TITLE
Forge create ignores the --value parameter

### ISSUE THREAD

**Issue by CodeSandwich** [foundry-rs/foundry#2123]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9010e8b 2022-06-21T00:09:06.371658411Z)

### What command(s) is the bug in?

forge create

### Operating System

Linux

### Describe the bug

I have an extremely boiled down contract:
```solidity
// nonZero.sol
pragma solidity ^0.8.13;

contract NonZero {
    constructor() payable {
        require(msg.value != 0, "VALUE ZERO");
    }
}
```
I'm trying to deploy it using a command:
```bash
forge create --private-key "$KEY" --value 1 'nonZero.sol:NonZero'
```
I'm getting an error:
```
execution reverted: VALUE ZERO
```

This means that the `--value` parameter must be ignored.

#### ~~But sometimes it work~~

**It doesn't.**

~~This is weird because in a different script I've been able to run an almost identical command with a similar smart contract and it worked perfectly with `$CON` getting 1 wei:~~

### The full error
```
[⠊] Compiling...
[⠢] Compiling 1 files with 0.8.15
[⠆] Solc 0.8.15 finished in 7.56ms
Compiler run successful
Error: 
   0: ProviderError(JsonRpcError(JsonRpcError { code: 3, message: "execution reverted: VALUE ZERO", data: Some(String("0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000a56414c5545205a45524f00000000000000000000000000000000000000000000")) }))

Location:
   cli/src/cmd/forge/create.rs:234

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by onbjerg** [comment]
I would assume it works in the second example because you don't check `msg.value`?

**Comment by CodeSandwich** [comment]
I've tried it again and you're right, the "working" example doesn't really work, `selfdestruct` always sends 0 wei to `forced`. I could swear that I've beaten an Ethernaut level using it :thinking:
