### ISSUE TITLE
General error vs panic pass

### ISSUE THREAD

**Issue by onbjerg** [foundry-rs/foundry#2131]
We should do a general pass of all commands and evaluate if some of the panics we encounter should in fact be errors, given we have two different error handlers, one for each case.

For example, if a contract cannot be deployed because of a revert, then it's *probably* user error and we should provide better information to the user on how to resolve that issue instead of panicking.

In general we should avoid panicking as much as possible

This is a pretty big issue, but mostly opened for tracking.

**Comment by DaniPopes** [comment]
This is done
