### ISSUE TITLE
`forge coverage`:  Win '/' domain separators causes 0% coverage reports

### ISSUE THREAD

**Issue by j-vp** [foundry-rs/foundry#2136]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (5385486 2022-06-27T00:03:53.397337486Z)

### What command(s) is the bug in?

`forge coverage`

### Describe the bug

There is a difference in output when running a `forge coverage` on Windows vs on Linux. I believe this is due to the difference in directory separators on win/unix systems.

Windows:

- quasi-alternating `/` and `\`:

![image](https://user-images.githubusercontent.com/104004836/175921350-2f525f4f-766e-4532-be36-073ca18e1ea2.png)

- coverage reports wrongfully at 0%:

![image](https://user-images.githubusercontent.com/104004836/175921555-f76b5f13-f097-4d5a-8c15-bd370caf85e1.png)

- it doesn't appear to be the case that a directory with '/' has (no) coverage and vice-versa:

![image](https://user-images.githubusercontent.com/104004836/175921965-9296ea0a-d5e2-4057-a520-2074f5dcf714.png)

Linux:

![image](https://user-images.githubusercontent.com/104004836/175921430-ddd1409c-8858-4ea2-b962-62104973f6d0.png)

![image](https://user-images.githubusercontent.com/104004836/175921574-bf97b7d5-6b4b-4615-8f41-c211bc41322b.png)

Both screenshots come from the same machine, same files, ... The tests are not in the same order upon runs on the different machines, this might be another small tweak.

**Comment by j-vp** [comment]
A `forge clean` unfortunately doesn't seem to help:

![image](https://user-images.githubusercontent.com/104004836/176378935-5f201527-cfc6-4300-8d41-72df2838e31d.png)

**Comment by mattsse** [comment]
closed by #2536 there is no `\` under Windows anymore
paths are now consistent `/`, just like solc handles it
