### ISSUE TITLE
Running `forge script` using `$ADMIN_PRIVATE_KEY` returns `Out of gas` error

### ISSUE THREAD

**Issue by bblanc42** [foundry-rs/foundry#2137]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (5385486 2022-06-27T00:08:00.235751Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Intel)

### Describe the bug

I was trying to do some local testing by forking Arbitrum network. I did,
```
$anvil --fork-url https://arbitrum-mainnet.infura.io/v3/$API_KEY
``` 
And I also ran the follow script command,
```
forge script script/Contract.s.sol:ContractScript \
  --fork-url http://localhost:8545 \
  --private-key $ADMIN_PRIVATE \
  --broadcast
```
`$ADMIN_PRIVATE` is the first key returned from the anvil command output, which is `0xac...80`. However, I ran into
```
Script ran successfully.

==========================

Estimated total gas used for script: 3996881

Estimated amount required: 0.007993762 ETH

==========================

###
Finding wallets for all the necessary addresses...
##
Sending transactions [0 - 0].

Transactions saved to: broadcast/Contract.s.sol/42161/run-latest.json

Error:
ProviderError(JsonRpcError(JsonRpcError { code: -32003, message: "Out of gas: required gas exceeds allowance: 0", data: None }))
```
I verified that running locally `anvil --hardfork latest` and `anvil --fork-url https://mainnet.infura.io/v3/$APT_KEY` worked. I suspect this is due to account not having ETH on Arbitrum. Can someone please help me out? Thank you.

**Comment by joshieDo** [comment]
This might be related to the fact that for arbitrum, we ask for a gas estimation from the network. However, we're setting it to 0 before sending the request as explained on the line below. It works fine on live, but I guess anvil doesn't like it ?
https://github.com/foundry-rs/foundry/blob/03b6f2c458634859ee1c35bbcb74f0dff75f27e1/cli/src/cmd/forge/script/broadcast.rs#L342-L343

**Comment by bblanc42** [comment]
> This might be related to the fact that for arbitrum, we ask for a gas estimation from the network. However, we're setting it to 0 before sending the request as explained on the line below. It works fine on live, but I guess anvil doesn't like it ?
> 
> https://github.com/foundry-rs/foundry/blob/03b6f2c458634859ee1c35bbcb74f0dff75f27e1/cli/src/cmd/forge/script/broadcast.rs#L342-L343

Thank you! Sounds like an easy fix? Otherwise is there a way to get around this?

**Comment by mattsse** [comment]
>  // If we don't, some RPCs might just return our estimated gas anyway.

tbh @joshieDo  I don't really get what this means, can you be more specific?
