### ISSUE TITLE
Forking invalid block causes application panic

### ISSUE THREAD

**Issue by antojoseph** [foundry-rs/foundry#2140]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (d89f6af 2022-06-24T00:15:17.805518Z)

### What command(s) is the bug in?

forge test --contracts ./src/test/exp.sol--fork-url https://eth-mainnet.alchemyapi.io/v2/[api-key-here] --fork-block-number 18501049 -vv

### Operating System

macOS (Intel)

### Describe the bug

I realised i was trying to fork a block on the wrong network, but it might be useful to fix the crash.   You can reproduce the crash by trying to fork a block that doesn't exist using the below command.

```
forge test --contracts ./src/test/exp.sol --fork-url https://eth-mainnet.alchemyapi.io/v2/[api-key-here] --fork-block-number 18501070 -vv

[⠰] Compiling...
No files changed, compilation skipped
The application panicked (crashed).
Message:  block not found
Location: evm/src/executor/fork/init.rs:27

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry
```

**Comment by onbjerg** [comment]
Not a bug per se, but should probably be an error instead of a panic
