### ISSUE TITLE
cast index won't allow address as value type

### ISSUE THREAD

**Issue by zobront** [foundry-rs/foundry#2141]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (5385486 2022-06-27T00:04:55.418541Z)

### What command(s) is the bug in?

cast index

### Operating System

macOS (Apple Silicon)

### Describe the bug

cast index errors if value_type=address.

SUCCESSFUL: cast index address uint256 0xD0074F4E6490ae3f888d1d4f7E3E43326bD3f0f5 2
ERROR: cast index address address 0xD0074F4E6490ae3f888d1d4f7E3E43326bD3f0f5 2

SUCCESSFUL: cast index uint256 uint256 2 2
ERROR: cast index uint256 address 2 2

**Comment by onbjerg** [comment]
Okay, so investigating this it seems like the interface is just wrong. The second parameter is not the value type, as that doesn't matter at all for storage slot computation - it's actually the slot type. It looks like this was just ported directly from `seth`, so I'll have to figure out why that second parameter exists, but if you do

```
$ cast index address uint256 0xD0074F4E6490ae3f888d1d4f7E3E43326bD3f0f5 2
0x9525a448a9000053a4d151336329d6563b7e80b24f8e628e95527f218e8ab5fb
```

You're actually getting the storage slot for *any* mapping at slot 2 with an address key, where the key is `0xD0074F4E6490ae3f888d1d4f7E3E43326bD3f0f5`.
