### ISSUE TITLE
Cast can ABI-encode bytecode

### ISSUE THREAD

**Issue by CodeForcer** [foundry-rs/foundry#2142]
### Component

Cast

### Describe the feature you would like

I would like Cast to be able to provide ABI encoding of a file or stdout in line with ethers-js default AbiEncoder:
https://gist.github.com/CodeForcer/dc6f05f7ea33c796e8aeb7c8031d1ce0

Currently, I believe there is no Foundry-native way to translate compiled output from Solc directly into a format which can be read into Solidity bytecode with the FFI cheatcode.

The following command is very close to equivalent, but gives the wrong output with a few bytes changed:
`cast abi-encode "f(bytes)" $(solc --yul yul/Example.yul --bin | tail -1)`

This feature would really improve the developer experience for people working with Yul

**Comment by onbjerg** [comment]
I'm not entirely sure what you mean - the bytecode should not be ABI encoded if you just want to deploy it, it should just be directly useable with `CREATE` and `CREATE2`? The ABI spec is only for describing how data types are encoded in calldata, it does not have anything to do with contract bytecode itself.

Can you provide some more context around what you are trying to achieve and why it doesn't work?

**Comment by CodeForcer** [comment]
@onbjerg FFI only decodes bytes things that are ABI encoded, as per the documentation:
https://book.getfoundry.sh/cheatcodes/ffi.html

For example, reading the following stdout from Solc fails:
`0x600a600d600039600a6000f3fe600035608052366080f3`

(Generated using `solc --yul yul/Example.yul --bin | tail -1 | (echo -n 0x && cat)`)

Whereas the following succeeds:
`0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000016600a80600c6000396000f3fe600035608052366080f300000000000000000000`

(Generated from the same Yul code using the Gist I shared above)

My use case is to hot-compile Yul code in the middle of tests, so I want to begin the test with `forge test` and then use FFI to compile so Yul code with Solc, then retrieve and deploy the result for use in tests.

**Comment by onbjerg** [comment]
That's weird, I'm not sure why it would result in different output, and I'd assume that the bytecode from solc is valid bytes, but I might be wrong on that one.

Can you not use https://book.getfoundry.sh/cheatcodes/get-code.html which is specifically built for getting bytecode from artifacts? It probably requires that you put the output of solc into a file, but the file can be very simple - we just need the bytecode keys, either in a Hardhat format or in a Foundry format.

**Comment by 0xYYY** [comment]
`ae.js`:
```javascript
#!/usr/bin/env node

const ethers = require("ethers");

let bytecode = "0x" + process.argv[2];
process.stdout.write(ethers.utils.defaultAbiCoder.encode(["bytes"], [bytecode]));
```

```
❯ BYTECODE=600a600d600039600a6000f3fe600035608052366080f3

❯ cast ae "f(bytes)" $BYTECODE | tr -d "\n" > a

❯ node ae.js $BYTECODE > b

❯ diff a b

❯ cat a
0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000017600a600d600039600a6000f3fe600035608052366080f3000000000000000000%

❯ cat b
0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000017600a600d600039600a6000f3fe600035608052366080f3000000000000000000%
```
When tested with the provided bytecode, `cast` and `ehters.js` produce the exact same output for me.

**Comment by 0xYYY** [comment]
> For example, reading the following stdout from Solc fails: 
> `0x600a600d600039600a6000f3fe600035608052366080f3`
> (Generated using `solc --yul yul/Example.yul --bin | tail -1 | (echo -n 0x && cat)`)


> Whereas the following succeeds: `0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000016600a80600c6000396000f3fe600035608052366080f300000000000000000000`
> 
> (Generated from the same Yul code using the Gist I shared above)



Also, the provided bytecode (`0x600a600d600039600a6000f3fe600035608052366080f3`, 23 bytes), doesn't seem to match with the ABI-encoded one below (22 bytes)?
```
0000000000000000000000000000000000000000000000000000000000000020
0000000000000000000000000000000000000000000000000000000000000016
600a80600c6000396000f3fe600035608052366080f300000000000000000000
```

**Comment by mattsse** [comment]
> Can you not use https://book.getfoundry.sh/cheatcodes/get-code.html which is specifically built for getting bytecode from artifacts? It probably requires that you put the output of solc into a file, but the file can be very simple - we just need the bytecode keys, either in a Hardhat format or in a Foundry format.

yeh this should be supported by this cheat code, if not we need to tweak it, but that's what the cheatcode is for @CodeForcer

**Comment by CodeForcer** [comment]
@onbjerg 

Cast command on Yul file
```
> cast abi-encode "f(bytes)" $(solc --yul yul/Example.yul --bin | tail -1 | (echo -n 0x && cat)) 
0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000017600a600d600039600a6000f3fe600035608052366080f3000000000000000000
```

Gist shared above
```
> node yul.js Example
0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000016600a80600c6000396000f3fe600035608052366080f300000000000000000000
```

Straight compilation with Solc
```
> solc --yul yul/Example.yul --bin

======= yul/GenericSelector.yul (EVM) =======

Binary representation:
600a600d600039600a6000f3fe600035608052366080f3
```

As you mentioned I can definitely achieve this by writing to a file first (or using a JS script like I currently am), but that's not as clean as being able to do it with a single command in memory

**Comment by onbjerg** [comment]
If you decode the two outputs above you get:

Cast: `600a600d600039600a6000f3fe600035608052366080f3`
Your script: `600a80600c6000396000f3fe600035608052366080f3`

It would seem that Cast matches the output straight from Solc, but the output from your script is different than what Solc outputs. Are you sure Cast is not correct here, and if so, what part is failing you?

**Comment by CodeForcer** [comment]
@onbjerg perhaps this is an issue with FFI parsing the output of cast?

The following logs `0x`
```
function deployContract(string memory fileName) public returns (address) {
    string[] memory inputs = new string[](10);
    string memory fileWithPath = string.concat("yul/", string.concat(fileName, ".yul"));
    inputs[0] = "cast";
    inputs[1] = "abi-encode";
    inputs[2] = '"f(bytes)"';
    inputs[3] = "$(solc";
    inputs[4] = "--yul";
    inputs[5] = fileWithPath;
    inputs[6] = "--bin";
    inputs[7] = "|";
    inputs[8] = "tail";
    inputs[9] = "-1)";
    bytes memory rawParse = vm.ffi(inputs);
    console.logBytes(rawParse);
```

Whereas the command logs:
```
> cast abi-encode "f(bytes)" $(solc --yul yul/Example.yul --bin | tail -1)
0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000017600a600d600039600a6000f3fe600035608052366080f3000000000000000000
```

**Comment by onbjerg** [comment]
FFI doesn't spawn the command inside bash so I would assume it just executes the wrong command?

Can you try either:

```solidity
string[] memory inputs = new string[](3);
inputs[0] = "bash";
inputs[1] = "-c";
inputs[2] = 'cast abi-encode "f(bytes)" $(solc --yul yul/Example.yul --bin | tail -1)';
```

or splitting the commands up (i.e. one FFI call for `solc ...`, one for `cast ...`)

**Comment by CodeForcer** [comment]
@onbjerg thank you for your help, I've solved this with the following (adapted from your suggestion)
```
string memory stringCommand = string.concat('cast abi-encode "f(bytes)" $(solc --yul yul/', string.concat(fileName, ".yul --bin | tail -1)"));

string[] memory inputs = new string[](3);
inputs[0] = "bash";
inputs[1] = "-c";
inputs[2] = stringCommand;

bytes memory bytecode = abi.decode(vm.ffi(inputs), (bytes));
```

Really appreciate the help of everyone who replied here (@0xYYY @mattsse also), this makes my developer experience a lot better - Foundry with cheatcodes is by far the most painless way to dev on Yul IMO

**Comment by CodeForcer** [comment]
PS: Published an example repo to help any future devs who get stuck here
https://github.com/CodeForcer/foundry-yul
