### ISSUE TITLE
Debugger Crashes at a certain point

### ISSUE THREAD

**Issue by Genysys** [foundry-rs/foundry#2143]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (5385486 2022-06-27T00:04:55.418541Z)

### What command(s) is the bug in?

forge test --debug "testSafeMintWithRio"

### Operating System

macOS (Apple Silicon)

### Describe the bug

I am trying to debug a failing test with by running the following command:

I am able to follow calls on the stack until it gets to a point and emits this error:

```
panicked at 'byte index 6994 is out of bounds of `// SPDX-License-Identifier: MIT
// OpenZeppelin Contracts v4.4.1 (security/Pausable.sol)

pragma solidity ^0.8.0;

import "../utils/Context.sol";

/**
 * @dev Contract module which allows children to implement an emergency stop
 * mechanism that can be tri`[...]', library/core/src/str/mod.rs:107:9
Abort trap: 6
```

This can be reproduced by:

* git clone  https://github.com/realiotech/realioverse-contracts.git
* git checkout feat/refactor
* forge test --debug "testSafeMintWithRio"

**Comment by joshieDo** [comment]
Are you sure that the forge version you mention is the one being used? I'm asking because I've noticed that for the past few days, the debugger hasn't been able to show the sources. I'll push a fix soon, but I'm left wondering about this one....

I also run it with my local fixed branch and wasn't able to reproduce this. Is the `testSafeMintWithRio` supposed to fail?

**Comment by Genysys** [comment]
Thanks @joshieDo . What happened was I was using an old version of Foundry, so before opening the ticket I did foundry up again . I think version, the debugger does not show the contract names, which #2146 fixes. However, the original issue is present i.e. the debugger crashes.

```
panicked at 'byte index 6994 is out of bounds of `// SPDX-License-Identifier: MIT
// OpenZeppelin Contracts v4.4.1 (access/Ownable.sol)

pragma solidity ^0.8.0;

import "../utils/Context.sol";

/**
 * @dev Contract module which provides a basic access control mechanism, where
 * there is an acc
 ```

**Comment by onbjerg** [comment]
Bump

**Comment by onbjerg** [comment]
Closing since we can't reproduce and haven't heard back. Let us know if this is still an issue for you and we will revisit :smile:

**Comment by 0xbok** [comment]
I am having a similar issue, opened it here: https://github.com/foundry-rs/foundry/issues/3463
