### ISSUE TITLE
`forge coverage` appears to still ignore optimizer settings

### ISSUE THREAD

**Issue by JasoonS** [foundry-rs/foundry#2147]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9dcc095 2022-06-28T00:03:46.153858156Z

### What command(s) is the bug in?

forge coverage

### Operating System

Linux

### Describe the bug

The optimizer settings I have in my `foundry.toml` appear to be ignored by the coverage command.

I think this is the case (haven't lookend into code) since my project compiles perfectly with `forge build` etc, but gets stack to deep issues when I run `forge coverage` (ie I haven't been able to test coverage yet :crying_cat_face: ). When I remove the optimizer from the config I get the error at the exact same stack to deep error in the same place.

The command line arguments for the optimiser are also not helping. eg `forge coverage --optimize --optimizer-runs 1000`.

**Comment by JasoonS** [comment]
I turned off the optimiser in my `foundry.toml` and took this screenshot as an illustration: 
![image](https://user-images.githubusercontent.com/6032276/176169821-4f324f11-982a-4706-aa88-de856e6e8a7e.png)

**Comment by onbjerg** [comment]
Coverage explicitly disables the optimizer because it fuddles with source maps, so this is by design. After I've fixed the edge cases I'll try to see if we can get it working with the optimizer on, but I wouldn't count on it :(

**Comment by JasoonS** [comment]
Aw super sad :(

Btw, the `forge coverage --help` command lists the optimization flags still. Mabye we can rename this issue to track that, it is a simple one :+1: 



It is really really difficult to get my code within the stack limit.

Awesome work on this though, really appreciate it. :pray: :pray:

**Comment by mattsse** [comment]
> Btw, the forge coverage --help command lists the optimization flags still.

this will be common pitfall

@onbjerg I guess this is due to recycled clap args? so we need to roll another build args struct for coverage that disables/hides it?

**Comment by onbjerg** [comment]
Yeah it's because we just do `#[clap(flatten)]`. I think this is also the case for a bunch of other commands still

**Comment by JasoonS** [comment]
I thought maybe it would be an easy first rust issue for me, but I couldn't work this out. I think there is a bit too much overhead I don't know about to help on this.

Anyway, at least I have the code cloned locally for some future low-hanging fruit ;)
