### ISSUE TITLE
How can I send an NFT with forge?

### ISSUE THREAD

**Issue by bitcoinmeetups** [foundry-rs/foundry#2148]
Hello,

I'm MB. A very nice and polite guy.

How can I send an NFT with forge?

Example:

I already have 10 NFT's of the same type with contract 0xabc in wallet 0xdef.

How can I send one of those NFT's to another wallet 0xghi?

**Comment by onbjerg** [comment]
You would use `cast send` and call the appropriate function with the correct parameters. See the book: https://book.getfoundry.sh/reference/cast/cast-send.html, where there is also an example of calling a function at the bottom of the page

**Comment by bitcoinmeetups** [comment]
Doesn't work as usual. Here are the details:

Here's the contract with the NFT I'm trying to send:

https://polygonscan.com/address/0x24Cd801e18Bf1EC584F3a4fE277B0c279E6d4CC0

Here's the address that I'm trying to send from:

0x24Cd801e18Bf1EC584F3a4fE277B0c279E6d4CC
0

Here's the address that I'm trying to send to:

0x58332f21b2c5b37ed590f4dff98f3d36609eba3e

If I try to use cast send or for that matter doing anything in general with forge or cast I get syntax errors or indecipherable errors. The book examples frankly don't work and they are too complicated to get started with. When you read them, it works for you. When new users read the examples and documentation it won't work because you have information that we do not have and you presume that we can get started without it.

Anyway, if possible please show me how to send the NFT above if it can even be done with cast in a normal timeframe.

**Comment by bitcoinmeetups** [comment]
Based on what you previously said perhaps it should be something like this, although this don't work:

cast send 0x24Cd801e18Bf1EC584F3a4fE277B0c279E
6d4CC "deposit(address,uint256)" 0x58332f21b2c
5b37ed590f4dff98f3d36609eba3e 1

**Comment by onbjerg** [comment]
If the examples are not good I would encourage you to open an issue in the book so we can improve them.

The address you linked on Polygon does not appear to be a contract, so I don't really know what method you are supposed to call. Can you expand on why it doesn't work/what error you get?

**Comment by bitcoinmeetups** [comment]
Hi there. I had some points before but I was also working in a room without proper cooling so I was a bit overheated. I will try to get this to work again now as I have improved the cooling in the room.

**Comment by bitcoinmeetups** [comment]
Hi there. I had some points before but I was also working in a room without proper cooling so I was a bit overheated. I will try to get this to work again now as I have improved the cooling in the room.

**Comment by bitcoinmeetups** [comment]
Ok, this is the input I have now:

#Account address: 0x24Cd801e18Bf1EC584F3a4fE277B0c279E6d4CC0
#Send to address: 0x58332f21b2c5b37ed590f4dff98f3d36609eba3e

cast send 0x24Cd801e18Bf1EC584F3a4fE277B0c279E6d4CC0 "deposit(address,uint256)" 0x58332f21b2c
5b37ed590f4dff98f3d36609eba3e 1 --private-key 0x1f82be1f6fcf5b6191ac7b2d8ae9dc3a0aba35c49d4b9
b4xxxxxxxx --rpc-url https://polygon-rpc.com --gas-limit 30000

This output a transaction underpriced error.

1. How can I fix the transaction underpriced error?
2. Where should I place the contract address in the above input?

**Comment by onbjerg** [comment]
It's described here: https://book.getfoundry.sh/reference/cast/cast-send?highlight=cast-send#cast-send

The contract address should go first, so assuming the addresses are correct, it looks OK to me. The transaction is most likely marked as underpriced because you are setting a gas limit of 30,000 which is not a lot - any tx is at least 21,000 gas. I would raise the gas limit to a more reasonable value, which depends on the contract you are talking to.

**Comment by bitcoinmeetups** [comment]
It doesn't seem to matter what gas limit I use. I always get transaction underpriced error. 

Current input (I put updated to Village contract address as I am trying to send a Village NFT):

cast send 0xA3B35F13d89d6E956c7aA3F11af2172a0e9063e6 "deposit(address,uint256)" 0x58332f21b2c5b37ed590f4dff98f3d36609eba3e 1 --private-key 1f82be1f6fcf5b6191ac7b2d8ae9dc3a0aba3xxxxxxx --rpc-url https://polygon-rpc.com --gas-limit 3000000 --gas-price 10000000

**Comment by bitcoinmeetups** [comment]
Polygonscan. This is the address I'm trying to send from. The private key is correct.

https://polygonscan.com/address/0x24Cd801e18Bf1EC584F3a4fE277B0c279E6d4CC0

**Comment by bitcoinmeetups** [comment]
Not sure why this is not working. But I think I've run into this transaction underpriced issue a lot in the past. Is there something wrong about this error message? Polygon transactions are usually really cheap so underpriced should not be an issue.

**Comment by bitcoinmeetups** [comment]
If I add --legacy then I get a transaction hash. But the transaction still fails. Polygonscan just says fail so I'm not sure why.

https://polygonscan.com/tx/0xd7d1257767c4cd373a6388ebc89e1dae0114e33db71b79a649b9925cf093b5bf

**Comment by onbjerg** [comment]
Ah, Polygon does not have EIP1559, I guess that's why. Not sure why it fails, that has to be something with your input. Unfortunately the contract you are interacting with is not verified, so I can't help you debug. I'd prefer we do these kinds of support/help requests in discussions or on the support Telegram, though

**Comment by bitcoinmeetups** [comment]
error messages

4> sudo modprobe tcp_ledbat
modprobe: FATAL: Module tcp_ledbat not found in directory /lib/modules/5.15.32-v8+
4> sudo modprobe tcp_lp                                                                          modprobe: FATAL: Module tcp_lp not found in directory /lib/modules/5.15.32-v8+
