### ISSUE TITLE
forge coverage: could not find anchors for branches

### ISSUE THREAD

**Issue by grandizzy** [foundry-rs/foundry#2162]
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (5279f69 2022-06-29T00:03:58.834625889Z)

### What command(s) is the bug in?

forge coverage

### Operating System

Linux

### Describe the bug

This used to work with yesterday build but after foundryup coverage started to fail with

```
Analysing contracts...
Error: 
could not find anchors for branches: we do not have the bytecode for MyContract
```

Same in GH Actions CI

**Comment by onbjerg** [comment]
Can you post the source for `MyContract`

**Comment by grandizzy** [comment]
Unfortunately I cannot at this stage but I'll try to strip out logic and reproduce with a simpler contract

**Comment by onbjerg** [comment]
Does your contract compile? Is it a library or an abstract contract?

**Comment by grandizzy** [comment]
yeah, it compiles and coverage was working fine before https://github.com/foundry-rs/foundry/commit/5279f69ae7a210487e83755a611d05996beca0ee (I reverted this one and retested). It's not an abstract contract but it does inherit from 3 abstract contracts, I am working to simplify this and see where it breaks

**Comment by onbjerg** [comment]
What type of function is the branch contained in?

**Comment by grandizzy** [comment]
All functions in contract are `external`

**Comment by VeryCB** [comment]
I have the same issue with my contract:

What version of Foundry are you on?
forge 0.2.0 (a5ea746 2022-07-03T00:12:33.358047Z)

What command(s) is the bug in?
forge coverage

Operating System
macOS 12.4

Error:
```sh
Analysing contracts...
Error:
could not find anchor: no matching instruction in range PermissionControl:1159:172:7
```

Contract source code: https://gist.github.com/VeryCB/ad1623b7c5850d0459ed0f8f793a56ff

**Comment by onbjerg** [comment]
Yeah, it's an internal function it's failing on. It's a known issue being worked on

**Comment by maurelian** [comment]
Also seeing this on our code. 

```
git clone git@github.com:ethereum-optimism/optimism.git
cd packages/contracts-bedrock
yarn
forge coverage
```

`could not find anchor: no matching instruction in range ResourceMetering:2511:173:4`

**Comment by antoncoding** [comment]
I got it work by changing all `internal` functions (that only used by functions in inheriting contracts, but not any functions in the same contract) to `public`, and it ran successfully

**Comment by DanielVF** [comment]
I'm also seeing "could not find anchor: no matching instruction in range". Yes, plenty of internal functions on the contract it is erroring on.

**Comment by jordaniza** [comment]
I ended up having to watch *nested* function calls. Speculating here, but I am assuming:

```ts
vm.expectRevert(bytes("ERR MESSAGE"));
contract.doStuff(param1, someOtherFunctionToGetParam2());
```
In the above example I think `someOtherFunctionToGetParam2()` is being watched by `expectRevert` instead of `doStuff`

Rewriting as:

```ts
uint param2 = someOtherFunctionToGetParam2();
vm.expectRevert(bytes("ERR MESSAGE"));
contract.doStuff(param1, param2);
```
Addressed my problem

**Comment by onbjerg** [comment]
The first version resulted in a panic by `forge coverage`? @jordaniza

**Comment by jordaniza** [comment]
Apologies, on the wrong issue - deleted the comment

**Comment by Genysys** [comment]
This was working until today when i updated foundry. 

Now getting 

```
realioverse-contracts $forge coverage
[⠊] Compiling...
[⠰] Compiling 31 files with 0.8.15
[⠒] Solc 0.8.15 finished in 1.43s
Compiler run successful
Analysing contracts...
Error: 
could not find anchor: no matching instruction in range LandNFT:10746:31:1
```

MRE:

* git clone https://github.com/realiotech/realioverse-contracts.git  
* git checkout git checkout feat/refactor
* forge coverage

**Comment by onbjerg** [comment]
Most likely you hadn't updated in a week or two since coverage has not had any change yesterday

**Comment by benesjan** [comment]
Hello,
I am facing the same issue when trying to run `forge coverage` on [this repo](https://github.com/AztecProtocol/aztec-connect-bridges). This is the error I receive:
`could not find anchor: no matching instruction in range StakingBridge:3019:2:42`

**Comment by grandizzy** [comment]
Confirm it's working fine now, thank you!

**Comment by benesjan** [comment]
@grandizzy Everything works now. Thank you 👍
