### ISSUE TITLE
variables reevaluate block.timestamp when called

### ISSUE THREAD

**Issue by FredCoen** [foundry-rs/foundry#2167]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (49f35c7 2022-06-30T00:06:55.326479Z)

### Operating System

macOS (Apple Silicon)

### Describe the bug

```

uint256 a = block.timestamp;
console2.log(a);
vm.warp(a+1);
console2.log(a);

```
  
 This snippet prints 1 and 2 to the console. Seems block.timestamp gets reevaluated instead of using the stored value  for a from the stack? Is this expected behaviour?

**Comment by FredCoen** [comment]
i see thanks @onbjerg is that the case even without the optimization pipeline?

**Comment by onbjerg** [comment]
I don't think so, but I'm not sure - this was reported once before in this issue: https://github.com/foundry-rs/foundry/issues/1373 There is some additional context in there, but no clear solution
