### ISSUE TITLE
feat(forge): support suppressing the file output of `forge script`

### ISSUE THREAD

**Issue by OliverNChalk** [foundry-rs/foundry#2174]
### Component

Forge

### Describe the feature you would like

It would be great to be able to suppress the file output of `forge script` for the purposes of dry-runs. The use case I have for this is preventing file writes during an e2e test - I'd like to have devs be able to run these tests locally without polluting the `broadcast/` folder.

The `--silent` flag relates to the `solc` output as far as I can tell. So unsure how best to expose this option to the user.

**Comment by mattsse** [comment]
superseded by #4009
will be closed by #4160
