### ISSUE TITLE
UnrecognisedToken 0:11 `constructor` when `abi-encode` is called

### ISSUE THREAD

**Issue by bblanc42** [foundry-rs/foundry#2176]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### Describe the bug

According to the docs [here](https://book.getfoundry.sh/forge/deploying.html), we are supposed to use `abi-encode constructor(...)` to verify our contracts. However, [@0xYYY](https://github.com/0xYYY) was able to help me out by discovering that the code was changed [here](https://github.com/gakonst/ethers-rs/blob/de1020c91e85ecb78e4c6ea12f61f30d28296602/ethers-core/src/abi/human_readable/lexer.rs#L336). The correct way to call abi-encode on our constructor is now, `abi-encode f(...)`.

We can either update the docs or fix the code.

**Comment by onbjerg** [comment]
I think the best path forward is to change the human readable parser to take either a `Token::Function` or a `Token::Constructor`, thoughts @mattsse?
