### ISSUE TITLE
Add RetryArgs to ScriptArgs

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#2181]
### Component

Forge

### Describe the feature you would like

`forge verify` accepts `retry: RetryArgs,` to configure how often to retry.

this is currently missing in `ScriptArgs`

- [ ] add `retry: RetryArgs` to `ScriptArgs` (requires `verify`)
- [ ] use `retry` when executing the verify command internally

**Comment by iFrostizz** [comment]
I'd like to have a try on this one please, if no one already started working on it.

**Comment by onbjerg** [comment]
Assigned you, let us know if you need help (by opening a draft PR and asking questions there) or if you want to be unassigned for whatever reason :smile:
