### ISSUE TITLE
feat: `vm.toString(address)` should return a checksum address

### ISSUE THREAD

**Issue by mds1** [foundry-rs/foundry#2183]
### Component

Forge

### Describe the feature you would like

The cheatcode `function toString(address) external returns (string memory);` returns the address as all lowercase. Related to the effort in https://github.com/foundry-rs/foundry/issues/2071 to default to checksum addresses, this cheatcode should also return a checksum address.

cc @odyslam

**Comment by odyslam** [comment]
Adding a quick change the UIfmt trait. PR should be posted in a few minutes
