### ISSUE TITLE
forge coverage: "No such file or directory (os error 2)"

### ISSUE THREAD

**Issue by gigamesh** [foundry-rs/foundry#2186]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (0d44687 2022-07-01T00:27:19.177599Z)

### What command(s) is the bug in?

forge coverage

### Operating System

macOS (Intel)

### Describe the bug

`forge coverage` results in this error saying a file isn't found, but I've confirmed it exists at that location. 🤔 

```
❯ forge coverage
[⠒] Compiling...
[⠢] Compiling 4 files with 0.8.7
[⠆] Compiling 69 files with 0.8.14
[⠰] Compiling 1 files with 0.8.4
[⠒] Solc 0.8.4 finished in 16.49ms
[⠰] Solc 0.8.7 finished in 2.23s
[⠃] Solc 0.8.14 finished in 10.15s
Compiler run successful
Analysing contracts...
Error: 
failed to read from "node_modules/.pnpm/@openzeppelin+contracts-upgradeable@4.4.2/node_modules/@openzeppelin/contracts-upgradeable/interfaces/IERC165Upgradeable.sol": No such file or directory (os error 2)

Context:
- No such file or directory (os error 2)
```

**Comment by onbjerg** [comment]
Can you provide a minimal reproducible example?

**Comment by gigamesh** [comment]
Here you go: https://github.com/gigamesh/temp-protocol

**Comment by gigamesh** [comment]
Hi @onbjerg - any ideas?

We recently completely swapped our tests from hardhat to forge before realizing that we'd be losing code coverage reports so any updates would be super appreciated! 🙏

**Comment by onbjerg** [comment]
Hi @gigamesh, as mentioned elsewhere coverage is not stable (and is not released as such), so it will take a while for me to turn around on this as there are other bugs that are a bit more pressing re: coverage. I'm currently doing a big change to coverage, so maybe it will "fix itself" after that.

I'm unsure why it can't read that path specifically, I haven't spend a lot of time debugging it yet, so I don't have a very in-depth response for you right now, apologies

**Comment by gigamesh** [comment]
No worries - thanks for the response!

**Comment by onbjerg** [comment]
Is this still present? If yes, is this related to the .pnmp issue filed recently?

**Comment by elenadimitrova** [comment]
I am now able to run `forge coverage` on the same project so we might close this if @gigamesh agrees.

**Comment by onbjerg** [comment]
I'll close it then, feel free to ping me if the behavior is still present @gigamesh and I'll reopen :smile:

**Comment by fedealconada** [comment]
> I am now able to run `forge coverage` on the same project so we might close this if @gigamesh agrees.

Have have you fixed this issue @elenadimitrova ? Experiencing the same... cc @onbjerg

**Comment by onbjerg** [comment]
Please give more context on your project, e.g. how is it structured (monorepo?), are you using package managers like pnpm or npm etc.

**Comment by gigamesh** [comment]
@onbjerg It's working for us now aside from if/else branches getting reported as partially covered, but we can manually check those. thank you!

**Comment by gigamesh** [comment]
> How have you fixed this issue @gigamesh ? Experiencing the same... cc @elenadimitrova @onbjerg

@fedealconada Be sure to run `foundryup` to make sure you're on the latest. If you still have the same error it's likely being caused from a different source than the one I reported.

**Comment by fedealconada** [comment]
> Please give more context on your project, e.g. how is it structured (monorepo?), are you using package managers like pnpm or npm etc.
> 
> Also provide your Forge version

@onbjerg ty for answering! We are using yarn for dependecy management, we have multiple packages handled with `yarn workspaces` and I'm using `forge 0.2.0`. Repo is [this](https://github.com/sense-finance/sense-v1) one.

**Comment by onbjerg** [comment]
forge 0.2.0 doesn't say much, I need the commit hash after the version number as well. All nightlies after early this year use 0.2.0 as their version number

**Comment by robriks** [comment]
For anyone running into this issue, double check if your `~/.svm` has become corrupted!

Especially so if you are using Apple M1 or M2 silicon, as compiling smart contracts written in `Solidity 0.8.5` or older can fail when the [z3 theorem prover](https://github.com/Z3Prover/z3) isn't installed, although it seems most Macbooks will handle this by default. I believe the issue in my case is that I run Linux in a VM on Apple silicon, so the z3 theorem prover was not present.

Here is the blurb from the Foundry Book docs about how this can arise, though in my case it was very sneaky as it only errored with "No such file or directory (os error 2)" and doesn't blame the compiler.
![image](https://github.com/foundry-rs/foundry/assets/80549215/beaee3fe-7e3c-4da4-a9d5-9ecea3145f25)

Reproducible example of broken, unrunnable scripts for Linux VMs:
https://github.com/0xStation/groupos/tree/debug

**Comment by stefanMadzharov** [comment]
> For anyone running into this issue, double check if your `~/.svm` has become corrupted!
> 
> Especially so if you are using Apple M1 or M2 silicon, as compiling smart contracts written in `Solidity 0.8.5` or older can fail when the [z3 theorem prover](https://github.com/Z3Prover/z3) isn't installed, although it seems most Macbooks will handle this by default. I believe the issue in my case is that I run Linux in a VM on Apple silicon, so the z3 theorem prover was not present.
> 
> Here is the blurb from the Foundry Book docs about how this can arise, though in my case it was very sneaky as it only errored with "No such file or directory (os error 2)" and doesn't blame the compiler. ![image](https://private-user-images.githubusercontent.com/80549215/277786600-beaee3fe-7e3c-4da4-a9d5-9ecea3145f25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NjgzNjMsIm5iZiI6MTcwODU2ODA2MywicGF0aCI6Ii84MDU0OTIxNS8yNzc3ODY2MDAtYmVhZWUzZmUtN2UzYy00ZGE0LWE5ZDUtOWVjZWEzMTQ1ZjI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDAyMTQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkZDI4MjBhOGRhMTY1NWI0NGY4MWFkNDkyMDM2OTNmMDI1YTBhNDMzNWIwZTk4NzI2NzdmYjgxNTRkYzMzNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GgRHuJX4rOyh_kGVSvMzqTpO5uJAdWggeRx4M2MSv0E)
> 
> Reproducible example of broken, unrunnable scripts for Linux VMs: https://github.com/0xStation/groupos/tree/debug

I have almost absolutely the exact problem you are describing - I am using `solidity 0.8.20`. On top of that I'm developing in a docker container and thus have a Linux VM on top of Apple Silicon. The error also corresponds to yours: `No such file or directory (os error 2)`.
I tried installing z3 in the container as well as on the host but the issue is still the same. Would you mind explaining what you did to fix it in a bit more detail?

**Comment by robriks** [comment]
A quick and dirty fix that often works is to flush the .svm and force it to be redownloaded:
`~$ rm ~/.svm`

As always try running `foundryup` as well to ensure you're on latest

The issue could arise from a number of different possibilities like incorrectly mapped dependency locations or nonexistent files for a specific dependency version or even a library symlink issue that was present in older Foundry versions.
