### ISSUE TITLE
Forge can fork intra-block during tests

### ISSUE THREAD

**Issue by CodeForcer** [foundry-rs/foundry#2191]
### Component

Forge

### Describe the feature you would like

A very common testing scenario is to evaluate the effect of a transaction behind some other transaction (known as "the offender").

There is no easy way to do this in Forge right now, which makes it difficult to onboard from Hardhat where you can do something like:
```
export async function forkIntraBlock(
  txHash: string,
  network: Network,
  ethers: HardhatEthersHelpers,
  archiveRpcUrl: string
): Promise<void> {
  const provider = new JsonRpcProvider(archiveRpcUrl)
  const response = await provider.getTransaction(txHash)
  const tx = getRawTransaction(response)
  const receipt = await provider.getTransactionReceipt(txHash)

  await network.provider.request({
    method: 'hardhat_reset',
    params: [
      {
        forking: {
          jsonRpcUrl: archiveRpcUrl,
          blockNumber: receipt.blockNumber - 1,
        },
      },
    ],
  })

  await ethers.provider.sendTransaction(tx)
}
```

Some developers may wish to have the complete intra-block state, but generally it's enough to fork at a block and apply only the offender transaction.

**Comment by gakonst** [comment]
I wonder if we'd want something like an additional cheatcode on top of the new forking cheats which do "vm forkroll to block and apply tx" @mattsse. 

@CodeForcer what does the ideal UX look like for you inside Solidity? Would also help to understand how you're consuming the code

**Comment by krasi-georgiev** [comment]
@CodeForcer do you mean that with `hardhat_reset` you can somehow insert a TX behind some other TX into a block? 
According to the hardhat docs, the `hardhat_reset` resets the state at a given block and I don't see any references to how you can insert TX into an existing block.

**Comment by onbjerg** [comment]
@krasi-georgiev I think it's possible in the sense that you `hardhat_reset` to a given block and manually replay the transactions yourself (with `eth_sendTransaction`)

**Comment by mds1** [comment]
Closed by https://github.com/foundry-rs/foundry/pull/3262 which lets you select specific tx hashes. There's also now `vm.transact` which executes a tx on top of current state
