### ISSUE TITLE
nicer API for writing pure Rust tests

### ISSUE THREAD

**Issue by gakonst** [foundry-rs/foundry#22]
We already support non-Solidity tests as shown here, but gotta make the API better: https://github.com/gakonst/dapptools-rs/blob/master/dapp/src/multi_runner.rs#L191-L227. 

The nicest way to write Solidity tests, would be to write an ethers-rs middleware that instead of doing RPC requests (https://github.com/gakonst/ethers-rs/blob/master/ethers-providers/src/provider.rs#L124), it’d do direct EVM calls. I think this is doable and tbh is ~equivalent to Solidity tests. All dapp test really does is continuously call all sol functions starting with test* by directly calling the EVM, so really just an abstraction

**Comment by guanqun** [comment]
hey @gakonst, I did some hacking and come up with a forked mode provider for evmodin: https://github.com/guanqun/ethers-forked-evm-provider

so I can write the unit test easily, see this example here: 

https://github.com/guanqun/ethers-forked-evm-provider/blob/master/tests/provider.rs#L9-L39

**Comment by guanqun** [comment]
My main use case is for forked mode, so it's quite specialized.

**Comment by mattsse** [comment]
closing this since we now have

https://github.com/foundry-rs/foundry/blob/master/forge/tests/it/config.rs

and all the forgetest! macros utils
