### ISSUE TITLE
Cannot reinstall a dependency after manually removing it from the `lib` folder

### ISSUE THREAD

**Issue by ckoopmann** [foundry-rs/foundry#2207]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (f016135 2022-07-04T00:15:02.930499Z)

### What command(s) is the bug in?

forge install / forge remove

### Operating System

macOS (Intel)

### Describe the bug

# How to produce the described behaviour ?

1. Initialize sample project with `forge init`
2. Manually remove the `lib/forge-std` file with `rm lib/forge-std`
3. Remove the library from the git staging area by running `git add lib/forge-std` (this will break `forge update` in addition to `install` and `remove` which stop working after step 2)

# Observed behaviour

There seems no way to reinstall the manually deleted library again using `forge` commands since: 

1. `forge install foundry-rs/forge-std` fails wtih `A git directory for 'lib/forge-std' is found locally`
2. `forge remove lib/forge-std` fails with `No such dependency`
3. `forge update lib/forge-std` fails with `pathspec 'lib/forge-std' did not match any file(s) known to git`

The only way to resolve this situation seems to be to add the module again using git submodule by running:
`git submodule add --force --name lib/forge-std https://github.com/foundry-rs/forge-std lib/forge-std`

After that the above mentioned forge commands work again as expected.

# Expected behaviour

I'd expect to be able to resolve this situation with `forge` commands only. Specifically I'd expect to `forge remove lib/forge-std` to still remove the submodule / file from the git index even if the directory / file in the `lib` folder was removed. Alternatively I'd expect `forge install` to provide a `--force` option to force install the library again.

# Example repo:
The following repo is an example in the above described broken state:
https://github.com/ckoopmann/forge-issue-manual-dependency-removal

**Comment by ckoopmann** [comment]
Adding a `--force` option to the `forge install` command and passing it on to the `git submodule` call [here](https://github.com/foundry-rs/foundry/blob/fcf2f31e7288f120cc2e7558c61d4e5a771b235c/cli/src/cmd/forge/install.rs#L207) would probably the easiest way to "fix" this issue such that the user is able to recover from it using `forge` commands only.

I'd be happy to open a PR for this if desired.

**Comment by ckoopmann** [comment]
Also I'd suggest maybe indicating when an error message comes from git etc. and not forge / foundry itself. 
The full error message of the `forge install` command I found somewhat misleading / confusing since it seems to suggest that there is a `--force` option on `forge install` already:
<img width="603" alt="image" src="https://user-images.githubusercontent.com/15629702/177262559-ec8df7fe-c1c7-485c-9748-23f63ed66b06.png">

**Comment by calldata** [comment]
`forge update lib/forge-std` works for me.

**Comment by ckoopmann** [comment]
> `forge update lib/forge-std` works for me.

My bad, to fully mess up and break `forge update` as well as the other two commands you'll have to remove the library from git's staging are as well by running `git add lib/forge-std` (after the `rm` command).

To make the issue more reproducible I added a little github action that reproduces it:
https://github.com/ckoopmann/forge-issue-manual-dependency-removal/runs/7246839659?check_suite_focus=true

**Comment by ckoopmann** [comment]
I opened a small pr that fixes this issue by letting a user reinstall the library using `forge install ...` in above described situation:
https://github.com/foundry-rs/foundry/pull/2242

**Comment by RichardPalladino** [comment]
Amazing!  This was exactly what I needed to fix my issue.  Thanks a lot.
