### ISSUE TITLE
Limit `vm.prank` to nonstatic calls

### ISSUE THREAD

**Issue by adhusson** [foundry-rs/foundry#2209]
### Component

Forge

### Describe the feature you would like

Feature: change `vm.prank` so that only non-static calls are pranked.

Alternative feature: add `vm.trick` with the above semantics.

### Context

Often a call is of the form `contract.fn(arg1,contract2.viewFn(),arg3)`. Evaluation order means that the following does not prank the call to `fn`:

```
vm.prank(superAdmin);
contract.fn(arg1,contract2.viewFn(),arg3);
```

instead one must write
```
vm.startPrank(superAdmin);
contract.fn(arg1,contract2.viewFn(),arg3);
vm.stopPrank();
```

or, alternatively:

```
type tempVar = contract2.viewFn();
vm.prank(superAdmin);
contract.fn(arg1,tempVar,arg3);
```

Both take more space and mean you can't write the code as you would outside of a test context.

**Comment by onbjerg** [comment]
Unsure if this would break anything/if there is any good reason to allow pranks for staticcalls in the first place, calling @gakonst @mds1 @transmissions11 as they might have some nice insights

**Comment by mds1** [comment]
I personally don't love special-casing static calls for a few reasons:
- The workarounds given aren't that bad or clunky.
- Sometimes you may want to `prank` staticcalls. For example the Optimism contracts sometimes check `msg.sender == address(0)` for some calls to simplify calling them off-chain, and you'd need to `prank` a staticcall to test that functionality: https://github.com/ethereum-optimism/optimism/blob/3b0afde67267339280fad284b13a1cccc3b47d94/packages/contracts/contracts/chugsplash/L1ChugSplashProxy.sol#L77-L99
- Adding another cheatcode feels like it adds clutter and code complexity for minimal benefit

**Comment by adhusson** [comment]
Makes sense. Would `vm.prank(address,address,bool prankStaticCalls)` add little enough clutter?

**Comment by gakonst** [comment]
I am on the @mds1 camp here, I don't feel terrible about the workaround, and would rather not add another cheatcode. Acknowledge the concern, but prefer to keep as is.

**Comment by transmissions11** [comment]
++

**Comment by adhusson** [comment]
Leaving this here to anyone that mind find it useful, I did a workaround which saves the current prank and restores it (to add to testing contracts):

```solidity
/* *** Pranking save/restore ***

  Does not support nesting.

  Returns msg.sender, used to capture the current prank value.
  The recipe is: save prank address, do a call, reprank.
  except if prank address is current address. Then just don't reprank and the result will be the same
*/
struct SavedPrank {
  uint mode; // 0 is do nothing, 1 is do prank, 2 is do startPrank
  address addr;
}

SavedPrank savedPrank;

function echoSender() external view returns (address) {
  return msg.sender;
}

/* save current prank address if any
    inside a `startPrank`, can `suspend` pranking */
function savePrank(bool suspend) internal {
  savedPrank.mode = 0;
  savedPrank.addr = this.echoSender();
  if (savedPrank.addr != address(this)) { // pranking a different address
    if (savedPrank.addr != this.echoSender()) { // in a onetime vm.prank
      savedPrank.mode = 1;
    } else if (suspend) { // in vm.startPrank, will suspend
      savedPrank.mode = 2;
      vm.stopPrank();
    }
  }
}

// sugar for simple save
function savePrank() internal {
  savePrank(false);
}

/* restore prank */
function restorePrank() internal {
  if (savedPrank.mode == 1) {
    vm.prank(savedPrank.addr);
  } else if (savedPrank.mode == 2) {
    vm.startPrank(savedPrank.addr);
  }
}
  ```
