### ISSUE TITLE
Pin a specific dependency version

### ISSUE THREAD

**Issue by 0xPhaze** [foundry-rs/foundry#2211]
### Component

Forge

### Describe the feature you would like

# Issue
Currently, when installing a specific version/branch of a dependency, this version is lost when running `forge update`.
Example:
```
forge install rari-capital/solmate@v7
forge update
```
=> checks out to master
I would expect the checked out branch to remain the same.

# Example Scenario
I currently am depending on solmate@v7's LibString.sol and have multiple of my own dependencies in my projects, which I frequently update. Every time I want to update, I currently run:
```
forge update
forge remove solmate
forge install rari-capital/solmate@v7
```

I realize that I also could just update the packages individually. Still, I would expect forge not to switch branches when updating.

**Comment by 7sne** [comment]
Can I pick it up? 😌 @onbjerg

**Comment by dsam82** [comment]
Oh, @7sne I actually have a solution ready for this.
