### ISSUE TITLE
Label issues is ambiguous 

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#2231]
### Component

Other (please describe)

### Describe the feature you would like

Labeling issues as Ignore is ambiguous: ignore for what reason?

Example: there are both PRs that have been merged and closed with this label. That really confuses me as to the semantics of this label. Either its meaningful or its not. Basically i am just ignoring the ignore label. 

also it may dissuade future contributors with the impression that there work is not valued for what ever reasons.

**Comment by onbjerg** [comment]
It excludes it from the automated changelog and is for things that are not user facing such as refactoring, internal changes or features that are not enabled yet. This is also evident in the label description. If you have better ideas for names feel free to suggest, but I don't think this should be an issue we track, probably just a discussion on Telegram if anything

**Comment by sambacha** [comment]
> It excludes it from the automated changelog and is for things that are not user facing such as refactoring, internal changes or features that are not enabled yet. This should also be evident from the label description, but I've updated it slightly to disambiguate it. If you have better ideas for names feel free to suggest, but I don't think this should be an issue we track, probably just a discussion on Telegram if anything

Thanks for the earnest response.

Parity has a few labels that may be worthwhile 

e.g.
P7-nicetohave 
Z1-mentor 


You can manage issues now via the GitHub CLI, here is how I grabbed their list of issue labels 

```bash
gh label list --sort name -R paritytech/substrate -L 100 --json name,description,color
```

Maybe overkill - 

| color  | description                                                                                        | name                       |
|--------|----------------------------------------------------------------------------------------------------|----------------------------|
| 666666 | Pull request needs code review.                                                                    | A0-pleasereview            |
| bfdadc | Pull request needs to be tested on a live validator node before merge.                             | A1-needsburnin             |
| c7def8 | Pull request is reviewed well, but should not yet be merged.                                       | A1-onice                   |
| C6C7F8 | Pull request requires no code review (e.g., a sub-repository hash update).                         | A2-insubstantial           |
| eeeeee | Does not elevate a release containing this beyond "low priority".                                  | C1-low 📌                  |
| eebb00 | Elevates a release containing this PR to "medium priority".                                        | C3-medium 📣               |
| aa0000 | Elevates a release containing this PR to "high priority".                                          | C7-high ❗️                 |
| 000000 | Elevates a release containing this PR to "critical priority".                                      | C9-critical ‼️             |
| fbca04 | Documentation needs fixing, improving or augmenting.                                               | I5-documentation 📄        |
| dbea04 | Code needs refactoring.                                                                            | I6-refactor 🧹             |
| 34C302 | An enhancement to provide a smaller (system load, memory, network or disk) footprint.              | I7-footprint 👣            |
| 009B40 | An enhancement to provide better overall performance in terms of time-to-completion for a task.    | I7-optimisation ⏱          |
| 006b75 | An additional feature request.                                                                     | I8-enhancement 🎁          |
| 0C7BAD | A specific issue for grouping tasks or bugs of a specific category.                                | I9-meta 📦                 |
| 0052cc | A specific release.                                                                                | I9-release 🏷              |
| f495e6 | A task worth setting up a bounty and can be fixed by potential contributors.                       | Z2-bounty                  |
| fcFdf2 | Issue is in principle valid, but it is not relevant anymore or can not reproduced.                 | Z3-stale                   |
| f4fdfa | Issue describes a behavior which turns out to work as intended. Closer should explain why.         | Z5-intended                |
| f8fbf8 | Issue is a duplicate. Closer should comment with a link to the duplicate.                          | Z7-duplicate               |
| f7f7fa | Issue is in principle valid, but this project will not address it. Closer should explain why.      | Z8-wontfix                 |
| fcf3f8 | Issue is invalid. Closer should comment why.                                                       | Z9-invalid                 |

**Comment by onbjerg** [comment]
Pretty much all of these already exist in some variant with a different name, so unsure how that solves your original issue with the ignore label?

**Comment by onbjerg** [comment]
Closing this since I think we're OK here, feel free to ping me on Telegram if you have suggestions for a better label name. In the future we will probably have an "opt-in" changelog label instead of an "opt-out" because we're going to write the changelog manually for new releases
