### ISSUE TITLE
debug_traceTransaction fails with brownie

### ISSUE THREAD

**Issue by DrawnWren** [foundry-rs/foundry#2238]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (4367ce1 2022-07-07T00:35:04.586326225Z)

### Operating System

Linux

### Describe the bug

When using brownie's ``TransactionReceipt.call_trace()`` method -- anvil returns a ``-32601``. 

The brownie ``debug_traceTransaction`` code looks like:
```
web3.provider.make_request(  # type: ignore
        "debug_traceTransaction",
        (approve["transactionHash"].hex(), {"disableStorage": True}),
    )
```
and the anvil response is:
```
{'jsonrpc': '2.0', 'id': 41, 'error': {'code': -32601, 'message': 'Method not found'}}
```

**Comment by onbjerg** [comment]
It is not currently supported, ref https://github.com/foundry-rs/foundry/issues/1737 (closing this as a duplicate)
