### ISSUE TITLE
Checksum mismatch for version 0.8.15

### ISSUE THREAD

**Issue by smallyunet** [foundry-rs/foundry#2240]
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e4a2915 2022-06-20T00:04:28.469233Z)

### What command(s) is the bug in?

forge build

### Operating System

macOS (Apple Silicon)

### Describe the bug

```
❯ forge build
[⠊] Compiling...
[⠘] installing solc version "0.8.15"
[⠃] Failed to install solc 0.8.15: Checksum mismatch for version 0.8.15
Error: 
   0: Checksum mismatch for version 0.8.15

Location:
   cli/src/compile.rs:100

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

And I already install the solc:
```
❯ solc --version
solc, the solidity compiler commandline interface
Version: 0.8.15+commit.e14f2714.Darwin.appleclang
```

**Comment by mattsse** [comment]
> forge 0.2.0 (https://github.com/foundry-rs/foundry/commit/e4a29157b04ada49d7e21e339b5ed6cf131d58e9 2022-06-20T00:04:28.469233Z)

this has been fixed, try foundryup
