### ISSUE TITLE
Slow down or retry RPC requests in tests

### ISSUE THREAD

**Issue by pakim249CAL** [foundry-rs/foundry#2247]
### Component

Forge

### Describe the feature you would like

Testing from a fresh storage cache is inconsistent for complex forking tests on an alchemy fork, as occasionally we hit the compute unit per second limit. I think these requests should be retried, or an option available to slow down requests so that we can avoid this problem.

**Comment by onbjerg** [comment]
What versions are you on?

**Comment by pakim249CAL** [comment]
Sorry about that. I do think it was a version issue.
