### ISSUE TITLE
config error: no prefix found in Remapping Provider

### ISSUE THREAD

**Issue by jubasnp471** [foundry-rs/foundry#2251]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (dd7c88f 2022-07-08T00:06:14.769137084Z)

### What command(s) is the bug in?

forge build

### Operating System

Linux

### Describe the bug

Message:  failed to extract foundry config
Location: config/src/lib.rs:374

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry
![Screenshot from 2022-07-08 20-34-11](https://user-images.githubusercontent.com/108630290/178024428-d2ecf7a0-e12a-4dd8-aed3-1fb47152e829.png)
![Screenshot from 2022-07-08 20-34-00](https://user-images.githubusercontent.com/108630290/178024433-7cb68c33-e734-43ac-8a31-f39fcdc4626a.png)

**Comment by onbjerg** [comment]
Can you post the relevant files (foundry.toml and remappings.txt) please?

**Comment by jubasnp471** [comment]
[remappings.txt](https://github.com/foundry-rs/foundry/files/9073377/remappings.txt)

this is ,toml
[default]
src = 'src'
out = 'out'
libs = ['lib']

**Comment by onbjerg** [comment]
Your remappings are not correct, remappings are in the format `<src>=<target>`, e.g. if you have a file `lib/forge-std/src/Test.sol` and you want to import it as `forge-std/Test.sol`, then the remapping would be `forge-std/=lib/forge-std/src/`
