### ISSUE TITLE
automatically detect evm version when forking at a certain block height

### ISSUE THREAD

**Issue by banteg** [foundry-rs/foundry#2252]
### Component

Anvil

### Describe the feature you would like

it would be less surprising for a user if anvil used the evm which was in place at the fork block height when forking, instead of the latest one. this requires adding a mapping of known chain ids to block heights to evm version running since that height.

### Additional context

you can see a similar feature implemented in ape-foundry here
https://github.com/ApeWorX/ape-foundry/pull/9

**Comment by sambacha** [comment]
Why not just test for certain OPCCODES

If stateroot hash is present the. < Byzantium 

```groovy

        def call = [
                to  : "0xdAC17F958D2ee523a2206206994597C13D831ec7",
                from: "0xEF65ffB384c99a00403EAa22115323a555700D79",
                data: "0xa9059cbb0000000000000000000000003f5ce5fbfe3e9af3971dd833d26ba9b5c936f0be000000000000000000000000000000000000000000000000000000004856fb60"
        ]
        def act = client.execute("test_foo", [call, "0x100000"])
        then:
        act.result == null
        act.error != null
        with(act.error) {
            code == -32000
            message == "invalid opcode: opcode 0xfe not defined"
        }
```
