### ISSUE TITLE
Estimate the gas cost of deploying a contract

### ISSUE THREAD

**Issue by hbarcelos** [foundry-rs/foundry#2253]
### Component

Forge, Cast

### Describe the feature you would like

Coming from dapp.tools, I miss a [`seth estimate --create`](https://github.com/dapphub/dapptools/tree/master/src/seth#seth-estimate) equivalent.

It would be great to add this option to `cast estimate` or maybe a `--estimate` flag for `forge create` to be able to get the estimated gas costs to deploy a contract.

**Comment by OmkarB** [comment]
@onbjerg would love to tackle this if it's available.

**Comment by onbjerg** [comment]
Assigned, let me know if you want to be unassigned for any reason :)
