### ISSUE TITLE
`forge script` and `forge snapshot` aliases are the same

### ISSUE THREAD

**Issue by StErMi** [foundry-rs/foundry#2254]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (dd7c88f 2022-07-08T00:23:23.289481Z)

### What command(s) is the bug in?

forge

### Operating System

macOS (Intel)

### Describe the bug

If you type `forge` to get the help menu, you'll see

```bash
[...]
script              Run a smart contract as a script, building transactions that can be sent onchain. [aliases: s]
snapshot            Create a snapshot of each test's gas usage. [aliases: s]
[...]
```

Running `forge s` it will try to run `forge script` as far as I see.

**Comment by mattsse** [comment]
since `script` came after snapshot, should we remove the `script`'s alias @onbjerg ?

put perhaps `script` is used more widely?

**Comment by moricho** [comment]
Hi 👋 
I created a patch PR for this:  https://github.com/foundry-rs/foundry/pull/2269

> since script came after snapshot, should we remove the script's alias
> 
> put perhaps script is used more widely?

Agree with this. I made a PR to follow the above suggestion for now, but if there is any other better solution I would fix the PR.
