### ISSUE TITLE
panic with 'spec not supported' when specifying `--hardfork muir_glacier`

### ISSUE THREAD

**Issue by banteg** [foundry-rs/foundry#2260]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ce52d85 2022-07-10T00:11:05.440274Z)

### What command(s) is the bug in?

anvil

### Operating System

macOS (Apple Silicon)

### Describe the bug

steps to reproduce
1. `anvil --port 7545 --fork-url http://127.0.0.1:8545 --fork-block-number 12175070 --hardfork muirglacier`
2. turn off automine
3. replay all txs from the next block
4. mine a block
5. revm panics
    > thread 'tokio-runtime-worker' panicked at 'Spec Not supported', /Users/runner/.cargo/git/checkouts/revm-bf744d8ffabcbad9/51f3f8f/crates/revm/src/evm.rs:162:14

an ape script to reproduce can be found here
https://gist.github.com/banteg/13147218f9424988a8814f7c3f0ea5d1

it appears we hit this line
https://github.com/bluealloy/revm/blob/51f3f8feb5625ca39a16492d569f6985e69121a7/crates/revm/src/evm.rs#L162

the fix appears to be to fall back to the previous evm version supported by the underlying vm when a user specifies it, i.e. `muir_glacier -> istanbul`, `constantinople, petersburg -> byzantium` (or `byzantine` as it's called in `revm`).

or this can be fixed by adding a more complete spec to revm.

**Comment by onbjerg** [comment]
Also an issue for Forge (same reasons)

**Comment by mattsse** [comment]
> the fix appears to be to fall back to the previous evm version supported by the underlying vm when a user specifies it, i.e. muir_glacier -> istanbul, constantinople, petersburg -> byzantium (or byzantine as it's called in revm).

since this is a revm limitation, should we downgrade this accordingly when selecting the hardfork @onbjerg?

**Comment by gakonst** [comment]
cc @rakita for visibility / any thoughts

**Comment by gakonst** [comment]
sounds good - thanks for letting us know!

**Comment by onbjerg** [comment]
Ping @rakita was this fixed recently?

**Comment by gakonst** [comment]
or @banteg to check the repro again

**Comment by rakita** [comment]
didnt look at this

**Comment by onbjerg** [comment]
@rakita what is the status on this? Some way I can help? :)

**Comment by rakita** [comment]
@onbjerg can you integrate https://github.com/bluealloy/revm/pull/191 ? `Result<Option>>` is added in `Database` as requested in discord, it broke foundry in a few places.

**Comment by mattsse** [comment]
thanks!

will migrate breaking changes

**Comment by mattsse** [comment]
this has landed with #2967
