### ISSUE TITLE
incorrect eip-1559 implementation

### ISSUE THREAD

**Issue by banteg** [foundry-rs/foundry#2262]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (7941935 2022-07-11T00:09:05.617669537Z)

### What command(s) is the bug in?

anvil

### Operating System

Linux

### Describe the bug

foundry doesn't seem to implement [this part of eip-1559 specification](https://github.com/ethereum/EIPs/blob/f6db72a05b8f5e4fe5ab24c38494dec6ff974a5f/EIPS/eip-1559.md?plain=1#L187-L194) correctly.

if you fork from mainnet block 13184859 and replay the very first transaction from block 13184860, you'll get an error saying `{'code': -32003, 'message': 'max fee per gas less than block base fee'}`

looking into it further, you can see this:
- block `number=13184859 gas_limit=29999972 gas_used=12257311 base_fee=63739886069`
- block `number=13184860 gas_limit=30000000 gas_used=29996605 base_fee=62283069776`
- transaction `maxFeePerGas: 62283069776 maxPriorityFeePerGas: 0` matches block 13184860 base fee

but foundry seems to compare it to values from 13184859, which is incorrect implementation.

**Comment by mattsse** [comment]
this is likely the same issue as https://github.com/foundry-rs/foundry/issues/2255 and should be fixed by https://github.com/foundry-rs/foundry/pull/2268

**Comment by gakonst** [comment]
@banteg pls `foundryup -b master` and let us know if fixed :D

**Comment by banteg** [comment]
tried it, doesn't work for me

**Comment by banteg** [comment]
works for me, thank you!
