### ISSUE TITLE
YulException on deal in --via-ir mode

### ISSUE THREAD

**Issue by sakulstra** [foundry-rs/foundry#2275]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

foundryup: installed - forge 0.2.0 (7bc3e60 2022-07-12T00:04:40.748127213Z) foundryup: installed - cast 0.2.0 (7bc3e60 2022-07-12T00:04:40.748127213Z) foundryup: installed - anvil 0.1.0 (7bc3e60 2022-07-12T00:04:40.766134156Z)

### What command(s) is the bug in?

forge test --via-ir  --rpc-url=${MAINNET_RPC}

### Operating System

Linux

### Describe the bug

Hey, i'm trying to deal some DAI to an address in `--via-ir` mode (not sure if that's related)

But if i `deal(DAI, DAI_WHALE, 10000 ether);` it breaks with:
```sh
forge test -vvv --rpc-url=${MAINNET_RPC} --fork-block-number 15008553 --via-ir
[⠊] Compiling...
[⠒] Compiling 1 files with 0.8.11
[⠰] Solc 0.8.11 finished in 24.11s
Error: 
Compiler run failed
YulException: Variable _2 is 1 too deep in the stack [ _2 expr_mpos_3 _6 _18 _1 _16 expr_component_mpos_1 _10 RET var_ins_mpos _4 _7 _3 _14 var_i expr_1 _27 ]



make: *** [Makefile:10: test] Error 1
```

Interestingly when i change the code to first deal ETH it compiles.
```
address internal constant DAI = 0x6B175474E89094C44Da98b954EedeAC495271d0F;
address internal constant DAI_WHALE = 0xbEbc44782C7dB0a1A60Cb6fe97d0b483032FF1C7;

function setUp() public {
       deal(DAI_WHALE, 10000 ether);
       deal(DAI, DAI_WHALE, 10000 ether);
}
```

**Comment by mattsse** [comment]
hmm this a solc error, not too familiar with stack limitations with `--via-ir`, 
maybe this is some yul weirdness where the variable needs to be loaded first separately @onbjerg ?

**Comment by sambacha** [comment]
try adding the `--optimize` flag to your command and see if it still happens @sakulstra

**Comment by sakulstra** [comment]
@sambacha same error as before
```
forge test -vv --rpc-url=${mainnetrpc} --fork-block-number 15127191 --via-ir --optimize
[⠊] Compiling...
[⠑] Compiling 1 files with 0.8.11
[⠊] Solc 0.8.11 finished in 26.68s
Error: 
Compiler run failed
YulException: Variable _2 is 1 too deep in the stack [ _2 expr_mpos_3 _6 _18 _1 _16 expr_component_mpos_1 _10 RET var_ins_mpos _4 _7 _3 _14 var_i expr_1 _27 ]
```

**Comment by sakulstra** [comment]
@sambacha added
```
[default]
optimizer = true
optimizer_runs = 200
libs = ['lib']
via_ir = true
optimizerSteps = ''
```
but still i get the exact same error

**Comment by mattsse** [comment]
the optimizerSteps are configured like this:

https://book.getfoundry.sh/reference/forge/forge-build.html?highlight=optimizerSteps#additional-optimizer-settings

**Comment by sambacha** [comment]
> the optimizerSteps are configured like this:
> 
> 
> 
> https://book.getfoundry.sh/reference/forge/forge-build.html?highlight=optimizerSteps#additional-optimizer-settings

In the link to the updated book there is a link to a twitter thread where the empty string for the selection is recommended

**Comment by sakulstra** [comment]
@mattsse In fact i am now getting different errors which i guess is a good sign:
```
forge test -vvv --rpc-url=<> --fork-block-number 15127191 --via-ir
[⠊] Compiling...
[⠒] Compiling 47 files with 0.8.11
[⠢] Compiling 3 files with 0.8.10
[⠆] Compiling 4 files with 0.6.12
[⠢] Solc 0.8.10 finished in 24.33ms
[⠔] Solc 0.6.12 finished in 857.64ms
[⠊] Solc 0.8.11 finished in 7.05s
Error: 
Compiler run failed
YulException: Cannot swap Slot JUNK with Slot RET: too deep in the stack by 1 slots in [ JUNK RET[read_from_storage_split_offset_uint256] _2 expr_19204_component_1_mpos expr_19170_address RET[finalize_allocation] var_ins_19123_mpos _6 _4 var_self_19099_slot _5 _7 _3 _1 _8 var_i expr_11 RET ]
```

When i completely disable the optimizer it will result in:
```
Error: 
Compiler run failed
YulException: Variable var_m_7723_mpos is 7 slot(s) too deep inside the stack.
```

**Comment by onbjerg** [comment]
Closing since I don't think we can do anything about stack to deep errors even in the Yul IR optimizer mode, other than maybe refactor how `deal` works, but that is in the Forge Std repository. Let me know if I am wrong here and I will reopen
