### ISSUE TITLE
Proxy deployments/ upgrates baked into foundry

### ISSUE THREAD

**Issue by FredCoen** [foundry-rs/foundry#2279]
### Component

Forge

### Describe the feature you would like

Upgradability is hard to safely manage with forge at the moment. I created a repo here that should help to show how to deploy/upgrade different proxy patterns correctly [here](https://github.com/FredCoen/Proxy_implementations_with_forge). It is WIP currently.

Ideally forge would automate common proxy pattern deployment / upgrades similar to the OZ hardhat upgrades plugin. 

When deploying it should check:

- Validate that the implementation is [upgrade safe](https://docs.openzeppelin.com/upgrades-plugins/faq#what-does-it-mean-for-a-contract-to-be-upgrade-safe)

- Deploy a [proxy admin](https://docs.openzeppelin.com/upgrades-plugins/faq#what-is-a-proxy-admin) for your project (if needed)

- Check if there is an [implementation contract](https://docs.openzeppelin.com/upgrades-plugins/faq#what-is-an-implementation-contract) deployed with the same bytecode, and deploy one if not

- Create and initialize the proxy contract

When upgrading it should check:

- Validate that the new implementation is [upgrade safe](https://docs.openzeppelin.com/upgrades-plugins/faq#what-does-it-mean-for-a-contract-to-be-upgrade-safe) and is [compatible](https://docs.openzeppelin.com/upgrades-plugins/faq#what-does-it-mean-for-an-implementation-to-be-compatible) with the previous one

- Check if there is an [implementation contract](https://docs.openzeppelin.com/upgrades-plugins/faq#what-is-an-implementation-contract) deployed with the same bytecode, and deploy one if not

**Comment by onbjerg** [comment]
Unsure about this feature, thoughts @gakonst?

**Comment by mds1** [comment]
I'm not too familiar with the OZ hardhat plugin, but from what I recall it seems very useful. I have a repo now where we have UUPS upgradeable contracts and Beacon contracts for factories, and it is tedious / a lot of work to get confidence in the setup. We've written some scripts to check storage layout, function sigs, etc. (repo is currently private otherwise I'd share). The checks and UX vary depending on how which upgrade pattern you use, and I think a lot of it can be put in forge-std.

Some scattered thoughts around the UX I'm aiming for and what we could include to help with this:
- All logic contracts should include `uint256 public constant VERSION = 0`, where of course 0 is then incremented by 1 with each version.
- When running a deploy script, read in the latest addresses of all logic contracts from deploy logs using #2153 
    - For each, check if the contract's ABI contains `VERSION`, and if so check if the deployed version matches the version in the local contracts. If so, that contract is up to date.
    - If it doesn't match, there's an upgrade that needs to be applied, so deploy the logic and queue the upgrade tx (or log the upgrade tx calldata in some specified format for e.g. a gnosis safe or governance proposal).
    - If there are no deploys found on the live network, deploy the current implementation (note the implied requirement that any implementation should be deployable directly, without requiring a previous implementation to be deployed first and then have the upgrade applied).
- I'd like for deploys to a live network to also include the commit hash in the output JSON file. The goal here is to ensure there's clear traceability between commit hashes and deployed contract addresses. Open to other ideas on how to do this, such as git tags on `forge script` executions to live networks or something.
- Detect if the proxy is UUPS, Transparent, Beacon, etc. and run the appropriate upgrade-safety checks, and revert if they fail.
    - We'd need a new cheatcode here to access the ABI (to check function selector clashes / presence of e.g. an `upgradeTo` method). Currently I do this in a shell script.
    - Implementation of #2056 would help with verifying storage layout, though we may want a way to trigger snapshot checks from within a forge script

**Comment by gakonst** [comment]
I think most of this should go to forge-std or something like forge-upgradeable which are ports of the JS logic which do "deploy, call initialize, ensure initialize is called".

There's some native logic which we could add around storage layout footguns etc, but I am not sure how that solution would look like.

**Comment by gakonst** [comment]
I think most of this should go to forge-std or something like forge-upgradeable which are ports of the JS logic which do "deploy, call initialize, ensure initialize is called".

There's some native logic which we could add around storage layout footguns etc, but I am not sure how that solution would look like.

**Comment by gakonst** [comment]
I think most of this should go to forge-std or something like forge-upgradeable which are ports of the JS logic which do "deploy, call initialize, ensure initialize is called".

There's some native logic which we could add around storage layout footguns etc, but I am not sure how that solution would look like.

**Comment by gakonst** [comment]
I think most of this should go to forge-std or something like forge-upgradeable which are ports of the JS logic which do "deploy, call initialize, ensure initialize is called".

There's some native logic which we could add around storage layout footguns etc, but I am not sure how that solution would look like.

**Comment by gakonst** [comment]
I think most of this should go to forge-std or something like forge-upgradeable which are ports of the JS logic which do "deploy, call initialize, ensure initialize is called".

There's some native logic which we could add around storage layout footguns etc, but I am not sure how that solution would look like.

**Comment by onbjerg** [comment]
Deleted a bunch of duplicate comments :cowboy_hat_face: I also feel like this should be built outside of main Forge. We can add additional info into Forge that 3rd party tools could use, e.g. `forge inspect` for storage layouts etc., but I don't think adding this into Forge makes a lot of sense. I'd be worried that we end up having a bunch of these specialized vendor-tools that we would have to maintain

**Comment by gakonst** [comment]
yeah - same page.

**Comment by HashHaran** [comment]
> I'm not too familiar with the OZ hardhat plugin, but from what I recall it seems very useful. I have a repo now where we have UUPS upgradeable contracts and Beacon contracts for factories, and it is tedious / a lot of work to get confidence in the setup. We've written some scripts to check storage layout, function sigs, etc. (repo is currently private otherwise I'd share). The checks and UX vary depending on how which upgrade pattern you use, and I think a lot of it can be put in forge-std.
> 
> Some scattered thoughts around the UX I'm aiming for and what we could include to help with this:
> 
> * All logic contracts should include `uint256 public constant VERSION = 0`, where of course 0 is then incremented by 1 with each version.
> * When running a deploy script, read in the latest addresses of all logic contracts from deploy logs using [feat: JSON parsing cheatcodes #2153](https://github.com/foundry-rs/foundry/issues/2153)
>   
>   * For each, check if the contract's ABI contains `VERSION`, and if so check if the deployed version matches the version in the local contracts. If so, that contract is up to date.
>   * If it doesn't match, there's an upgrade that needs to be applied, so deploy the logic and queue the upgrade tx (or log the upgrade tx calldata in some specified format for e.g. a gnosis safe or governance proposal).
>   * If there are no deploys found on the live network, deploy the current implementation (note the implied requirement that any implementation should be deployable directly, without requiring a previous implementation to be deployed first and then have the upgrade applied).
> * I'd like for deploys to a live network to also include the commit hash in the output JSON file. The goal here is to ensure there's clear traceability between commit hashes and deployed contract addresses. Open to other ideas on how to do this, such as git tags on `forge script` executions to live networks or something.
> * Detect if the proxy is UUPS, Transparent, Beacon, etc. and run the appropriate upgrade-safety checks, and revert if they fail.
>   
>   * We'd need a new cheatcode here to access the ABI (to check function selector clashes / presence of e.g. an `upgradeTo` method). Currently I do this in a shell script.
>   * Implementation of [feat: expand snapshot functionality #2056](https://github.com/foundry-rs/foundry/issues/2056) would help with verifying storage layout, though we may want a way to trigger snapshot checks from within a forge script

To me personally upgrade-safety checks and storage layout checks seem to be the most important of what you have said. Automatic deployment management based on version change seem like a good to have. Rest of the features that Open Zeppelin hardhat upgrades plugin provides can be written in a forge script and exposed as a library.

Any progress on accessing the ABI from inside forge script to do this? Any other ideas to do such checks in the forge is also welcome.

May be some core functionalities required to do this can be done in forge while the checks and management of different proxy patterns can be done in a third party library. The third party library can evolve as proxy patterns and solidity evolves, while foundry sticks only to the core solidity development functionalities.

In the meanwhile I think the best option is to set up hardhat parallel to foundry and use the open zeppelin hardhat upgrades plugin. Take a look at this [repository ](https://github.com/HashHaran/foundry-upgrade-hardhat) if curious about this approach.
