### ISSUE TITLE
Ledger HW QoL

### ISSUE THREAD

**Issue by joleeee** [foundry-rs/foundry#2289]
### Component

Cast

### Describe the bug

# Check that signed transactions from hardware wallets have the correct --from
This would be a failsafe for when the hardware wallet signs a transaction from a different account than the one specifed with --from.

*RE: talk in foundry telegram*

I had an issue a while back where i specified a --from in `cast send` but the transaction was signed with another account. I don't think the ledger even shows what account you're using, only the target, but thats not something that can be fixed in foundry. My solution is to derive the sender from the signed message, and then assert it is the same as the --from.

Moreover we spoke about some other QoL improvements. Here is the full list
- cast sometimes (always when account is not the first idx?) signs/sends txs from the wrong account
- missing linux udev rules (as with any program)
- seth takes a while to iterate until it finds the wallet i think
- explain --mnemonic-path in `cast send --help`,
    - give an example? some nice frontend?

As for the udev rules, it would be nice if it would prompt you to copy a `curl | sudo tee /etc/udev/...`, or at the very least link you to [the ledger site](https://support.ledger.com/hc/en-us/articles/115005165269-Fix-USB-connection-issues-with-Ledger-Live), here is the [arch aur package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ledger-udev) which has a script for it

@gakonst let me know the issue with the wrong sender is because foundry doesn't iterate through the accounts until it finds the correct once, so assuming this would be added in the future, i left in the slightly unrelated point relating to seth. Maybe it could be cached or something :smile:

**Comment by joshieDo** [comment]
Thanks!!

Sending from the wrong account might be related to:

* `--trezor` and `--ledger` use a default derivation path if `--hd-path` is not provided. I'm guessing `--mnemonic-path` and `--mnemonic-index` work similarly.
* Commands which use `--from` do not look for a pairing address in any of the foundry commands as far as I know. On `forge script` we match what we need against what we have. And fail, if we can't match. But I'm guessing that we don't make that check for `cast send`. 

I'd rather make the check and fail, than search for a valid address to be honest.

--

Regarding `udev` ... I'd rather handle the failure better, and tell the user to make sure `udev` rules are installed to be honest.

**Comment by joleeee** [comment]
If not automatically by --from then it would be nice if some other util existed for finding the derivation. Then just
```sh
cast send --hd-path $(cast somesubcmd --find-hd-path 0x12..34)
```
and maybe a shorthand `cast send --find-from`?

**Comment by onbjerg** [comment]
Was this fixed in #2290

**Comment by joleeee** [comment]
The original problem was half-solved in that it now panics if there is a mismatch between --from and the actual hw sender, but thats more like a failsafe. Other half-related things were also brought up here

**Comment by onbjerg** [comment]
Ping @joshieDo unsure if the rest of this issue was fixed?

**Comment by joshieDo** [comment]
The main issue is solved afaik. Others are more like suggestions/feature requests

**Comment by mds1** [comment]
Going to close this since the main issue was solved. I'm not sure if the other suggestions were implemented yet or not, but if those are still desired let's get each one into it's own issue so we can track/prioritize individually
