### ISSUE TITLE
Forge script exits unsuccessfully when passing a custom raw calldata signature with the --sig flag: `sig is invalid`

### ISSUE THREAD

**Issue by DaniPopes** [foundry-rs/foundry#2292]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (7bc3e60 2022-07-12T00:04:40.748127213Z)

### What command(s) is the bug in?

forge script

### Operating System

Linux

### Describe the bug

![Example](https://user-images.githubusercontent.com/57450786/178615302-fa472226-1e82-4647-b716-b7a39cf37852.png)

Tests and script pass successfully, but then it fails and doesn't broadcast the transactions.

Error is in this function:

https://github.com/foundry-rs/foundry/blob/16b4ef693624368e02e3501dd137214faf9bbe76/cli/src/cmd/forge/script/sequence.rs#L125-L143

**Comment by onbjerg** [comment]
cc @joshieDo `forge run` used to support calldata as well as function signatures, and it also seems to still work except for some stuff in `sequence.rs` that requires it to be a human readable signature. We should be able to lookup the function if calldata is passed

**Comment by onbjerg** [comment]
No, there isn't

**Comment by FredCoen** [comment]
thanks, do you think it will be part of version 1.0?

**Comment by FredCoen** [comment]
thanks @onbjerg ! in the meantime there is no other way to get dynamic inputs into scripts right>

**Comment by FredCoen** [comment]
@onbjerg do you reckon this will this be fixed in v1.0.0 ? Or has this been pushed back? Thanks
