### ISSUE TITLE
`forge init` should clean up itself on failure

### ISSUE THREAD

**Issue by ehildenb** [foundry-rs/foundry#2303]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (7941935 2022-07-11T00:09:05.617669537Z)

### What command(s) is the bug in?

`forge init`

### Operating System

Linux

### Describe the bug

I ran `forge init` in a Git repo with some other changes in the git repo:

![Screenshot from 2022-07-13 11-50-43](https://user-images.githubusercontent.com/12721972/178800781-e9e0d670-92ac-4989-859f-0e08516a6600.png)

It fails, because it says "you have changes in your worktree", but suggests that I run `forge init --no-commit` as a substitute.

But the second run of `forge init --no-commit` fails too, because the first run of `forge init` dumped a bunch of files in the current directory.

The first run of `forge init` should check _first_ if there will be git problems, then _not_ dump a bunch of files if there will be those problems, so that the second run with the suggested argument `--no-commit` will work.

**Comment by ehildenb** [comment]
Files in question: 
![Screenshot from 2022-07-13 12-05-25](https://user-images.githubusercontent.com/12721972/178801074-61173706-4c43-4aac-95ba-ff46599e88bb.png)

**Comment by onbjerg** [comment]
The `--no-commit` flag is for `forge install` (which `forge init` runs for you). Agreed that we should check this before doing anything.
