### ISSUE TITLE
Revert with no reason, TX appears to succeed when looking at stack trace on forked mainnet.

### ISSUE THREAD

**Issue by adamxyzxyz** [foundry-rs/foundry#2310]
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (16b4ef6 2022-07-13T00:15:34.493056Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

I am running tests against the curve SUSD pool on a forked version of mainnet. My contract calls the function remove_liquidity_one_coin with all of the proper parameters and approvals in place. For whatever reason, the test fails and I get a revert. 

When I test with a stack trace, the stack trace leads to nowhere, and I can see that the emitted transfer event of sending the curve zap pool sending USDC back to my contract goes through successfully.

At this point I am just trying to nail down where exactly this error is originating from. I have included a picture of the stack trace at the bottom. The empty () simply leads back to the start of the test, not a particular function call.

![image](https://user-images.githubusercontent.com/66784124/178846518-f358627c-6198-4348-8d0c-d2d353bd4f57.png)

**Comment by adamxyzxyz** [comment]
This easiest way to reproduce this error would be to quickly write a test where you write a balance of sCrv to yourself, and attempt to call remove_liquidity_one_coin on the sUsd Zap Pool: 0xFCBa3E75865d2d561BE8D220616520c171F12851

**Comment by Genysys** [comment]
Do you need to pass a provider url for the tests to run ? I ran into something similar the other day

**Comment by adamxyzxyz** [comment]
yes I am passing a forked mainnet url via --fork-url

**Comment by adamxyzxyz** [comment]
it was an error with my interface, it is fixed now.
