### ISSUE TITLE
`forge init` produces confusing license files

### ISSUE THREAD

**Issue by ehildenb** [foundry-rs/foundry#2311]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (16b4ef6 2022-07-13T00:05:41.265337096Z)

### What command(s) is the bug in?

`forge init`

### Operating System

Linux

### Describe the bug

`forge init` produces a directory called `lib/forge-std`, which has two licenses present, `LICENSE-APACHE`, and `LICENSE-MIT`. It appears that the copyright holder is the same in both cases. This is mildly confusing.

**Comment by ehildenb** [comment]
In addition, the actual file I want to use `src/Test.sol`, has a different license, the Unlicense: https://github.com/foundry-rs/forge-std/blob/master/src/Test.sol

Can I copy it into my BSD-like project?

**Comment by onbjerg** [comment]
I would open up this issue in https://github.com/foundry-rs/forge-std. The license files are from that repository. For that reason I am closing the issue here, since it is not fixable in this repo. :smile:

**Comment by ehildenb** [comment]
@onbjerg can you transfer this issue to that repo then? I do not have the permissions.

**Comment by onbjerg** [comment]
I don't have permission to do so, you'll have to reopen it in that repository unfortunately
