### ISSUE TITLE
Pinning Foundry version in a Dockerfile

### ISSUE THREAD

**Issue by ehildenb** [foundry-rs/foundry#2312]
### Component

Foundryup

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (16b4ef6 2022-07-13T00:05:41.265337096Z)

### What command(s) is the bug in?

`foundryup`

### Operating System

Linux

### Describe the bug

I am trying to run `foundryup` in a `Dockerfile` so I can test a tool I'm integrating with it on CI.

This is what I have:

```
USER user:user
WORKDIR /home/user

RUN curl -L https://foundry.paradigm.xyz | bash && foundryup --version nightly-16b4ef693624368e02e3501dd137214faf9bbe76 
ENV PATH=/home/user/.foundry/bin:$PATH
```

There are 2 problems:

- [ ] `foundryup` cannot detect what shell is running in the Dockerfile (image below), and so exits with non-zero exit-code. So I have to add an `_ || true` to the `RUN` line which means I'll be ignoring real errors (I'm setting up the environment on the next line anyway).
- [ ] Not many versions of `foundry` are being tagged, which means that pegging a specific version on CI will be difficult, which makes our development process more painful.

![Screenshot from 2022-07-13 20-07-42](https://user-images.githubusercontent.com/12721972/178882538-8755b5a8-a8a8-48f6-977d-6ef77757ec37.png)

**Comment by ehildenb** [comment]
I have found that this works for the Dockerfile:

```
ARG K_COMMIT
FROM ghcr.io/foundry-rs/foundry:nightly-3c49efe58ca4bdeec4729490501da06914446405 as FOUNDRY

ARG K_COMMIT
FROM runtimeverificationinc/kframework-k:ubuntu-focal-${K_COMMIT}

COPY --from=FOUNDRY /usr/local/bin/forge /usr/local/bin/forge
COPY --from=FOUNDRY /usr/local/bin/anvil /usr/local/bin/anvil
COPY --from=FOUNDRY /usr/local/bin/cast /usr/local/bin/cast
```

This allows us to (i) pin a version of `foundry` in the Dockerfile, and (ii) use our own image directly. This is using Docker multistage builds: https://docs.docker.com/develop/develop-images/multistage-build/

**Comment by onbjerg** [comment]
You can use our official image which (as far as I know) retains all the tags: https://github.com/foundry-rs/foundry/pkgs/container/foundry

As for replicating this behavior with `foundryup`, this is not something we want to do yet - we're aiming to stabilize, but until then we will retain 3 nightlies only, so I am going to close this as a "won't fix". We are also aiming to replace the current `foundryup` (written in Bash) with a native version with new features, so we are not actively adding new ones to the existing version. Let me know if I misunderstood something!
