### ISSUE TITLE
Use MSRV instead of `rust-toolchain` file.

### ISSUE THREAD

**Issue by adoerr** [foundry-rs/foundry#2314]
### Component

Other (please describe)

### Describe the feature you would like

The current `rust-toolchain` files pins `rustc` to a stable version (1.62).

Reason for this is probably that we want to use features that have been introduced with that very version. For this, using a so called minimal supported Rust version (MSRV) is more appropriate. This is also nicely supported by the [rust-version field](https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field) of the `cargo` manifest [package] section.

A `rust-toolchian` file messes around with the local environment  by installing the pinned version. Currently this means that I have `1.62` installed twice :disappointed: and sure enough some tools get tripped  by that more or less.

IMO, a `rust-toolchain` file only makes sense if a very specific *nightly* version of `rustc` is needed. For version limiting stable `rustc`, using a MSRV is more appropriate and less intrusive.

### Additional context

Repository quality-of-life issue

**Comment by onbjerg** [comment]
cc @prestwich as I recall you wanted a `rust-toolchain` file? I don't feel strongly either way

**Comment by prestwich** [comment]
there was a specific compilation issue with a dependency on newer rust versions, altho I can't remember exactly details

**Comment by adoerr** [comment]
Perhaps the issue is gone, since the `rust-toolchain` version got bumped to the current stable version just a couple of days ago :thinking:
