### ISSUE TITLE
Cast send tx by Calldata

### ISSUE THREAD

**Issue by sunnybinb** [foundry-rs/foundry#2315]
### Component

Cast

### Describe the feature you would like

The command cast send can be send transaction just by rpc and calldata subcommand.

### Additional context

MacBook-Pro ~ % cast send [calldata] -rpc

**Comment by onbjerg** [comment]
Something like `cast send <calldata> --raw`

**Comment by zobront** [comment]
Diving into this and realizing I'm not 100% clear what @sunnybinb is trying to accomplish:
- If the tx data is already signed, then is the goal here just to have `cast send --raw` alias `cast publish`?
- If the tx data isn't already signed, then where are we expecting to get the signer (and to, value, nonce, etc)?

**Comment by meetmangukiya** [comment]
I think the idea is to just bypass calldata encoding, just set `tx.data` to whatever the user gives as argument. The tx would still need signing and all other tx fields still need to be populated just like it does currently for `cast send`.

**Comment by zobront** [comment]
Got it. I was confused because this is already in the `cast send` documentation:

> The signature (sig) can be:
> - ...
> - A selector and encoded calldata: 0xcdba2fd40000000000000000000000000000000000000000000000000000000000007a69

But looking at the code, looks like that isn't actually implemented. Thank you!

**Comment by meetmangukiya** [comment]
Actually does seem like arbitrary calldata is supported. Not sure what the OP meant now 😅 . https://github.com/foundry-rs/foundry/blob/master/cast/src/tx.rs#L187-L189

**Comment by onbjerg** [comment]
Oh, in that case we can close?

**Comment by onbjerg** [comment]
Unassigned you @zobront, let me know if you are still working on it though

**Comment by zobront** [comment]
I am. Sorry for the delay. I’ll have new PR ready in the next few days.

**Comment by zobront** [comment]
@onbjerg Sorry, responded from email and thought this comment was on another issue. 

Correct, nothing to do on this issue, you can unassign and close it down.

**Comment by onbjerg** [comment]
Wait, this was solved?

**Comment by meetmangukiya** [comment]
I think it is unless there is more clarification from OP https://github.com/foundry-rs/foundry/issues/2315#issuecomment-1189694421

**Comment by onbjerg** [comment]
Oh, right. Just checked the code and this does seem to be implemented

**Comment by rpedroni** [comment]
Can confirm this works, in case we want to close this

**Comment by rpedroni** [comment]
Example
`cast send 0x10fd9348136dcea154f752fe0b6db45fc298a589 0xa60fe71d3437353535323932350000000000000000000000000000000000000000000000 --private-key 0x<pk>`
