### ISSUE TITLE
Unable to run Foundry Scripts against Hardhat mainnet fork

### ISSUE THREAD

**Issue by 0xfarhaan** [foundry-rs/foundry#2318]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (3c49efe 2022-07-14T00:14:23.444892Z)

### What command(s) is the bug in?

forge script script/DeploymentScript.s.sol:DeploymentScript --rpc-url $TESTNET_RPC_URL  --private-key $PRIVATE_KEY

### Operating System

macOS (Apple Silicon)

### Describe the bug

Hey folks! So our team is running a hardhat node on an EC2 instance that is a fork of mainnet to do out testing. I am unable to run the foundry script with the command above when passing in the RPC url of our test node. I get the following error:

```
ProviderError(SerdeJson { err: Error("invalid type: null, expected u64", line: 1, column: 26), text: "{\"jsonrpc\":\"2.0\",\"id\":null,\"error\":{\"code\":-32600,\"message\":\"Invalid request\",\"data\":{\"message\":\"Invalid request\"}}}" })
```

Our node is running correctly and accepting txns from our brownie project as we would expect. My suspicion is the rpc call foundry is generating isn't playing nice with the hardhat node. 

I also tried the command with the --hh flag to see if it helped but no luck on that front also.

**Comment by farhaan-ali** [comment]
Just to add the scripts run fine on my local instance of Anvil with no problem.

**Comment by farhaan-ali** [comment]
seems to be the chain ID call

```
2022-07-14T14:16:35.923439Z TRACE rpc{method="eth_chainId" params="null"}: ethers_providers::transports::retry: should not retry err=SerdeJson { err: Error("invalid type: null, expected u64", line: 1, column: 26), text: "{\"jsonrpc\":\"2.0\",\"id\":null,\"error\":{\"code\":-32600,\"message\":\"Invalid request\",\"data\":{\"message\":\"Invalid request\"}}}" }
Error: 
ProviderError(SerdeJson { err: Error("invalid type: null, expected u64", line: 1, column: 26), text: "{\"jsonrpc\":\"2.0\",\"id\":null,\"error\":{\"code\":-32600,\"message\":\"Invalid request\",\"data\":{\"message\":\"Invalid request\"}}}" })
```

**Comment by mattsse** [comment]
thanks for raising this, 

this was indeed a bug in the Retry Provider
