### ISSUE TITLE
Reevaluate and document `cast-async` flag

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#2338]
### Component

Cast

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### Describe the bug

the --cast-async flag is currently undocumented and it is not clear what it is for

maybe this is some ported legacy flag (dapp)?

```console
cast send --help

        --cast-async
            [env: CAST_ASYNC=]

```

looking at where it's used

https://github.com/foundry-rs/foundry/blob/7c96807294f51c121f1a2d614b55055bc7cb126c/cli/src/cast.rs#L408-L409

it's clear what it does: not waiting for the receipt.

imo we should reevaluate the naming here as well, maybe something like `--no-wait` `--async`?

**Comment by mds1** [comment]
In `seth` the flag was just called `--async`, so I'd support renaming it to that. cc @tynes who might have thoughts too

https://github.com/dapphub/dapptools/blob/cb2e4cabd7268dd6fad16d0a49e8690160ef40fc/src/seth/libexec/seth/seth-send#L16
