### ISSUE TITLE
setStorageAt / balanceOf succeeds on Hardhat, fails on anvil

### ISSUE THREAD

**Issue by thomasj02** [foundry-rs/foundry#2341]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (c247243 2022-07-15T00:04:58.638841575Z)

### What command(s) is the bug in?

anvil -f

### Operating System

Linux

### Describe the bug

I'm trying to use Anvil to fork BNB Chain mainnet.
The following code succeeds in hardhat, but fails in anvil (it seems as if the storage slot is not set). I also tried changing `hardhat_setStorageAt` to `anvil_setStorageAt` but it gives the same result

```
from web3 import Web3
import eth_abi
import requests
import json

busd_address = "0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56"

hardhat_url = "http://localhost:8545"


w3 = Web3(Web3.HTTPProvider("http://localhost:8545"))
busd_abi = json.load(open("interfaces/BUSD.json"))
busd_contract = w3.eth.contract(address=busd_address, abi=busd_abi)

def set_busd_balance(address, balance):
    account = Web3.toChecksumAddress(address)
    slot = 1
    abi_encoded = eth_abi.encode_abi(['address', 'uint256'], [account, slot])
    map_slot = Web3.solidityKeccak(["bytes"], ["0x" + abi_encoded.hex()]).hex()

    value = Web3.toHex(balance)
    while len(value) < 64+2:
        value = "0x0" + value[2:]
    set_storage_request = {"jsonrpc": "2.0", "method": "hardhat_setStorageAt", "id": 1,
        "params": [busd_address, map_slot, value]}
    requests.post(hardhat_url, json.dumps(set_storage_request)).json()


def test_busd_balance_slot():
    account = "0x0000000000000000000000000000000000000000"
    set_busd_balance(account, 12345)

    balance = busd_contract.caller().balanceOf(account)
    assert balance == 12345


test_busd_balance_slot()
```

**Comment by onbjerg** [comment]
When you say it fails, do you get any more info? An error message?

**Comment by thomasj02** [comment]
I mean the test itself fails (`assert balance == 12345`) and balanceOf returns the same value as if setStorageAt didn't get called

**Comment by onbjerg** [comment]
Ah, right, it doesn't need to be mined.

**Comment by mattsse** [comment]
thanks for raising this

I would appreciate it if you could dump the output of `json.dumps(set_storage_request)` or even as `curl` command

**Comment by thomasj02** [comment]
Sure, here's the json:

`{"jsonrpc": "2.0", "method": "hardhat_setStorageAt", "id": 1, "params": ["0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56", "0xa6eef7e35abe7026729641147f7915573c7e97b47efa546f5f6e3230263bcb49", "0x0000000000000000000000000000000000000000000000000000000000003039"]}`

**Comment by mattsse** [comment]
sorry it took so long, this slipped through...

fixed with #2592 thanks for reporting

**Comment by thomasj02** [comment]
Can you confirm that the test I originally reported as failing passes for you? With `anvil 0.1.0 (92f8951 2022-08-08T00:03:54.482691017Z)` I now see it reporting a balance of 0. This is different than the balance reported before #2592 but is not the value of the storage slot that gets set

**Comment by mattsse** [comment]
yeah added this roundtrip test

https://github.com/foundry-rs/foundry/blob/63ed1099a74fded7c3a7182b5a508bd7d16743d3/anvil/tests/it/anvil_api.rs#L25-L41

**Comment by liamaharon** [comment]
Hi @mattsse, I'm experiencing a similar issue to Tom here. 

I'm unable to call `balanceOf` after using `setStorage`, I've modified his Python script to demonstrate this using only RPC requests which I hope will be easier for you to replicate in Rust tests.

Here's my modified script. First I call `setStorage`, then `getStorage` and finally `balanceOf`.

```python
from web3 import Web3
import eth_abi
import requests
import json

busd_address = "0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56"
hardhat_url = "http://localhost:8545"
w3 = Web3(Web3.HTTPProvider("http://localhost:8545"))
busd_abi = json.load(open("interfaces/BUSD.json"))
busd_contract = w3.eth.contract(address=busd_address, abi=busd_abi)


def test_anvil_set_storage(address, balance):
    account = Web3.toChecksumAddress(address)
    slot = 1
    abi_encoded = eth_abi.encode_abi(['address', 'uint256'], [account, slot])
    map_slot = Web3.solidityKeccak(["bytes"], ["0x" + abi_encoded.hex()]).hex()

    value = Web3.toHex(balance)
    while len(value) < 64+2:
        value = "0x0" + value[2:]

    # Set Storage
    set_storage_request = {
        "jsonrpc": "2.0",
        "method": "hardhat_setStorageAt",
        "id": 1,
        "params": [busd_address, map_slot, value],
    }
    res = requests.post(
        hardhat_url,
        json=set_storage_request
    ).json()
    print('\nsetStorage response')
    print(res)

    # Get Storage
    get_storage_request = {
        "jsonrpc": "2.0",
        "method": "eth_getStorageAt",
        "id": 1,
        "params": [
            "0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56",
            "0xa6eef7e35abe7026729641147f7915573c7e97b47efa546f5f6e3230263bcb49",
            None
        ]
    }
    res = requests.post(
        hardhat_url,
        json=get_storage_request
    ).json()
    print('\ngetStorage response')
    print(res)

    # Balance of
    balanceOf_request = {
        "method": "eth_call",
        "params": [
            {
                "from": None,
                "to": busd_address,
                "data": "0x70a082310000000000000000000000000000000000000000000000000000000000000000"
            }, "latest"
        ],
        "id": 1,
        "jsonrpc": "2.0"
    }
    res = requests.post(
        hardhat_url,
        json=balanceOf_request
    ).json()
    print('\nbalanceOf response')
    print(res)

    return int(res['result'], 16)


def main():
    account = "0x0000000000000000000000000000000000000000"
    balance = test_anvil_set_storage(account, 12345)
    assert balance == 12345
    print('\nSuccess!')


main()
```

Here is the output running it against the BSC chain forked with *Hardhat*: 

```
setStorage response
{'jsonrpc': '2.0', 'id': 1, 'result': True}

getStorage response
{'jsonrpc': '2.0', 'id': 1, 'result': '0x0000000000000000000000000000000000000000000000000000000000003039'}

balanceOf response
{'jsonrpc': '2.0', 'id': 1, 'result': '0x0000000000000000000000000000000000000000000000000000000000003039'}

Success!
```

Here is the output running it against the BSC chain forked with *Avil*: 

```
setStorage response
{'jsonrpc': '2.0', 'id': 1, 'result': None}

getStorage response
{'jsonrpc': '2.0', 'id': 1, 'result': '0x0000000000000000000000000000000000000000000000000000000000003039'}

balanceOf response
{'jsonrpc': '2.0', 'id': 1, 'result': '0x'}
Traceback (most recent call last):
  File "/**/anvil_script.py", line 83, in <module>
    main()
  File "/**/anvil_script.py", line 78, in main
    balance = test_anvil_set_storage(account, 12345)
  File "/**/anvil_script.py", line 73, in test_anvil_set_storage
    return int(res['result'], 16)
ValueError: invalid literal for int() with base 16: '0x'
```

For some reason when using Anvil the `balanceOf` call is not returned correctly if `setStorage` is called any time before. I have discussed this with Tom and he experiences the same issue with his script.

**Comment by mattsse** [comment]
was able to reproduce this with a bsc fork.

unclear at this point why the ethcall returns no output for `balanceOf` https://www.bscscan.com/address/0xe9e7CEA3DedcA5984780Bafc599bD69ADd087D56#code
