### ISSUE TITLE
Restrict interaction with GitHub repo to users who have had an account for X amount of time

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#2346]
### Component

Other (please describe) - Also would be nice to add a 'meta' tag for these sorts of issues 

### Describe the feature you would like

Restrict interaction with GitHub repo to users who have had an account for X amount of time. I have seen 3 issues with user accounts that are bots. Head off the spam now, as this will invariably be a target as foundry is crypto-related so it's even at a higher risk than normal popular repos.

### Additional context

Solution: [docs.github.com/en/communities/moderating-comments-and-conversations/limiting-interactions-in-your-repository](https://docs.github.com/en/communities/moderating-comments-and-conversations/limiting-interactions-in-your-repository)

or alt. create a github action similar to [github.com/marketplace/actions/faceless-issues](https://github.com/marketplace/actions/faceless-issues) but without the comment disclosing about the avatar check and an additional check to see how many repos, commits or whatever other heuristic is relevant

**Comment by onbjerg** [comment]
Can you link the spam issues? I haven't seen any and I'd rather not restrict before it becomes an issue (if it does) mostly because we also have to account for people that create accounts on GitHub to file issues on Foundry (who are not bots).

**Comment by sambacha** [comment]
> Can you link the spam issues? I haven't seen any and I'd rather not restrict before it becomes an issue (if it does) mostly because we also have to account for people that create accounts on GitHub to file issues on Foundry (who are not bots).

Accounts that comment on the repo without having any history are harvesting data. I can provide examples later not at my workstation. 

Also, anyone using foundry has a github account, alternatively they can post in telegram and someone can report it for them, though this is the exceptional case.


Thanks for creating the meta label too

**Comment by onbjerg** [comment]
Meta label has existed it's just not surfaced in the forms :smile: I still think this would be premature action since I haven't seen any spam myself. As for harvesting data, you don't really need a bot for that since all of this is public, so it's not a concern to me in this case

**Comment by onbjerg** [comment]
Closing this as per above, we can discuss on Telegram in the Foundry channel if you want to, but I haven't seen any spam issues and I don't think it's a good assumption at this point that everyone has a GitHub account

**Comment by sambacha** [comment]
> Closing this as per above, we can discuss on Telegram in the Foundry channel if you want to, but I haven't seen any spam issues and I don't think it's a good assumption at this point that everyone has a GitHub account

https://twitter.com/stephenlacy/status/1554697086158876674

**Comment by onbjerg** [comment]
Does not matter if we block them or not. They can clone the repository without an account, create a GitHub account and do the exact same thing. Restricting them from being here does not ban them off of GitHub. Please don't necro issues for unrelated reasons
