### ISSUE TITLE
Not loading env vars

### ISSUE THREAD

**Issue by DefiCake** [foundry-rs/foundry#2357]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (44f3a4b 2022-07-17T00:13:18.493764624Z)

### What command(s) is the bug in?

forge script , forge test

### Operating System

Linux

### Describe the bug

I have the following .env:

`UINT_VALUE=115792089237316195423570985008687907853269984665640564039457584007913129639935`

And this Makefile:

```
-include .env

install :; forge install foundry-rs/forge-std && forge install dapphub/ds-test

test :; forge test
```

And a test file:

```
function testEnvironment() public {
		string memory key = "UINT_VALUE";
		uint256 expected = type(uint256).max;
		// vm.setEnv(key, "115792089237316195423570985008687907853269984665640564039457584007913129639935");
		uint256 output = hevm.envUint(key);
		assert(output == expected);
	}
```

Running `make test` does not work unless I change my Makefile to:

```
-include .env

install :; forge install foundry-rs/forge-std && forge install dapphub/ds-test

test :; UINT_VALUE=${UINT_VALUE} forge test
```

Sourcing .env in my CLI and running `forge test` does not work either. The only thing that works is inlining the env var prior to running `forge`. 

```
source .env
echo $UINT_VALUE  => 115792089237316195423570985008687907853269984665640564039457584007913129639935
forge test => ERROR
UINT_VALUE=${UINT_VALUE} forge test => WORKS!
```

The error I 'm getting:

```
Failed tests:
[FAIL. Reason: environment variable not found] testEnvironment() (gas: 3444)
```

**Comment by mattsse** [comment]
what's the error?

**Comment by DefiCake** [comment]
> what's the error?

Failed tests:
[FAIL. Reason: environment variable not found] testEnvironment() (gas: 3444)

**Comment by onbjerg** [comment]
This is not an error in Foundry, the Makefile is just wrong I think. I've always had to do something like:

```
-include .env
export
```

**Comment by onbjerg** [comment]
Closing as per above comment
