### ISSUE TITLE
forge audit to check/list all ffi usage

### ISSUE THREAD

**Issue by OliverNChalk** [foundry-rs/foundry#2360]
### Component

Forge

### Describe the feature you would like

Prompted by #2326, it would be good if there was a way to sanity check the ffi usage within a given project. @mds1 pointed out this could be achieved via `grep -r \\.ffi`. A `forge audit` command could do something similar but leverage `remappings` to determine where to search for ffi usage.

Would be good to discuss scope & possible solution space.

**Comment by mattsse** [comment]
how about `forge geiger` that lists all `unsafe` calls?

**Comment by PatrickAlphaC** [comment]
Bump

**Comment by mattsse** [comment]
@rkrasiuk I think scanning the AST for certain calls would be rather straightforward, right?

**Comment by rkrasiuk** [comment]
yes, sir. it should roughly look like
```
FunctionCall(
  _,
  MemberAccess(
    _, Variable(Identifier { loc: _, name: "Vm" }), Identifier { loc: _, name: "ffi" }
  ),
  [ /* args */]
)
```

**Comment by mattsse** [comment]
with the existing visitors, this should be very easy to write a scanner for calls, right? we just need a list of calls and some matching code?

**Comment by rkrasiuk** [comment]
yup, you can write the matched function into some output buffer and that should be it
