### ISSUE TITLE
Tests on a fork are taking much more time than when using a previous Forge version

### ISSUE THREAD

**Issue by Rubilmax** [foundry-rs/foundry#2366]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (44f3a4b 2022-07-18T00:10:06.735136619Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

When running a test using a mainnet fork and an RPC, I experience an increased execution time compared to a previous `forge` version, built from source from the commit `1eb6756bd445443c40ebe1c4df1b8fc5d2dbd137` using:

```bash
foundryup -C 1eb6756bd445443c40ebe1c4df1b8fc5d2dbd137
```

It seems like some changes drastically impacted the execution time of tests, the difference being of ~30sec for a single test.

**Comment by mattsse** [comment]
any chance your API key is getting rate limited? we have built in retry support which could cause this
