### ISSUE TITLE
Anvil fork on ethers-rs failed

### ISSUE THREAD

**Issue by siewchongche** [foundry-rs/foundry#2372]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (44f3a4b 2022-07-18T00:10:06.735136619Z)

### Operating System

Linux

### Describe the bug

```
use ethers::utils::Anvil;
use eyre::Result;

#[tokio::main]
async fn main() -> Result<()> {
    let anvil = Anvil::new()
        .fork("https://mainnet.infura.io/v3/c60b0bb42f8a4c6481ecd229eddaca27")
        .spawn();

    Ok(())
}
```
return error
`thread 'main' panicked at 'Timed out waiting for anvil to start. Is anvil installed?', /home/siew/.cargo/registry/src/github.com-1ecc6299db9ec823/ethers-core-0.13.0/src/utils/anvil.rs:180:17`

But if run on terminal with anvil
`anvil -f https://mainnet.infura.io/v3/c60b0bb42f8a4c6481ecd229eddaca27`
without issue.

Infura RPC URL copy from https://github.com/gakonst/ethers-rs/blob/master/examples/ens.rs

**Comment by onbjerg** [comment]
This should be reported in the ethers-rs repository, not here
