### ISSUE TITLE
Sign and verify arbitrary payloads

### ISSUE THREAD

**Issue by CodeSandwich** [foundry-rs/foundry#2379]
### Component

Cast

### Describe the feature you would like

We can sign and verify **messages** using `cast wallet sign`, they get the `\x19Ethereum Signed Message:\n` prefix before being hashed. It'd be great to be able to do the same with arbitrary payloads.

This could be used to tinker around with all kinds of signed things:
- ERC-712 messages. Currently there's no way to create or verify a `permit` payload.
- Raw transactions. There's no way to verify an arbitrary supposedly signed transaction. There's also no way to manually build a transaction because it can't be signed.

It's crucial to be able to provide a raw 256-bit payload (hash) to be signed. Being able to provide a payload which needs to be hashed first would be a nice addition, but not necessary, it'd save a call to `cast keccak`.

**Comment by onbjerg** [comment]
Maybe we should add a flag like `--raw` or `--headerless`?

**Comment by CodeSandwich** [comment]
That would be awesome, `--raw` could accept a 256-bit payload to be directly signed and `--headerless` an arbitrary length payload to be hashed and then signed.

**Comment by marcuspang** [comment]
Hey @CodeSandwich, I implemented the `--raw` and `--headerless` flags as mentioned over at #5248. I also added a `--raw` flag for `cast wallet verify`. Is this what you had in mind for the feature?

**Comment by CodeSandwich** [comment]
Hi @marcuspang, yes, that's exactly it!

**Comment by marcuspang** [comment]
I believe this issue is resolved with https://github.com/foundry-rs/foundry/pull/7180 using the `--no-hash` flag. Although one would need to hash the message themselves first.
