### ISSUE TITLE
Anvil: Address already in use

### ISSUE THREAD

**Issue by supernovahs** [foundry-rs/foundry#2382]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (44f3a4b 2022-07-18T00:10:06.735136619Z)

### What command(s) is the bug in?

anvil

### Operating System

Linux

### Describe the bug

Ran `anvil ` and it worked. 
But when I closed it, and try to re-run it , the compiler says Address already in use. Even though it's not. 

Here's the full compiler message
`thread 'main' panicked at 'error binding to 127.0.0.1:8545: error creating server listener: Address already in use (os error 98)', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.18/src/server/server.rs:87:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted (core dumped)`

**Comment by onbjerg** [comment]
Can you run `sudo lsof -i -P -n | grep LISTEN` and find port 8545 and tell me what process is using it?

**Comment by supernovahs** [comment]
anvil     248229     supernovahs    9u  IPv4 1872227      0t0  TCP 127.0.0.1:8545 (LISTEN)

**Comment by onbjerg** [comment]
It looks like it's still running - any chance you are running it in another window, or you are using Foundry Hardhat? You can kill the process manually and it should be fine again. I'm on Linux and I don't have this issue, so seems to be local to you in some capacity

**Comment by supernovahs** [comment]
I am not running in another window nor in foundry hardhat .
Manually killing worked. Thanks
Now it seems to work fine.

**Comment by aiman9411** [comment]
In my case, I'm using macOS and received this error message when I was about to deploy my contract to local testnet:
`error sending request for url (http://localhost:8545/): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known`

When I run `anvil --port 8545`, I received the similar message:
`thread 'main' panicked at 'error binding to 127.0.0.1:8545: error creating server listener: Address already in use (os error 48)', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.14.18/src/server/server.rs:87:17`

I killed the process manually but then still received similar error message. Any idea to help me with this?
