### ISSUE TITLE
base_fee is incorrect from latest block

### ISSUE THREAD

**Issue by unparalleled-js** [foundry-rs/foundry#2387]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (114413c 2022-07-19T00:09:13.401146Z)

### What command(s) is the bug in?

anvil

### Operating System

macOS (Intel)

### Describe the bug

My transaction is:

1. from an impersonated account in fork mode
2. is the first transaction made
3. is a transfer txn (no contracts involved)
4. sets its gas from estimation

When running with `RUST_BACKTRACE=full`, the txn fails with `max fee per gas less than block base fee`
When running without `RUST_BACKTRACE=full`, the txn succeeds.

(`eth_sendTransaction` is the RPC that fails)

**Comment by mattsse** [comment]
hmm, 
any chance you can dump the request payload as json before sending to `eth_sendTransaction`?

**Comment by unparalleled-js** [comment]
> hmm, any chance you can dump the request payload as json before sending to `eth_sendTransaction`?

I am attempting to do this but now hitting the block hash error again. It either works, gives me the block hash error, or fails with a max fee error. Nothing is very consistent so it is hard to reproduce. Breakpoints or adding / adjusting logging always changes the outcome which makes me believe there is just some race conditions happening. Also, this seems to only be an issue with the fork provider.

**Comment by mattsse** [comment]
what block are we talking? a new block produced by anvil? or the forked block itself?

what's the provider? alchemy, infura? 

do you send requests concurrently?

**Comment by unparalleled-js** [comment]
The very first transaction made in Fork mode using Alchemy as the provider causes the error when that transaction comes from an impersonated (unlocked) account

**Comment by unparalleled-js** [comment]
Impersonation is always involved. When it happens later on, that is the point of failure it seems.

**Comment by mattsse** [comment]
I see,
do you have a script that lets me reproduce this?

will also check if we missed something after we checked for an impersonated acc

**Comment by unparalleled-js** [comment]
Sorry have been busy! But am going to make the repro script now

**Comment by mattsse** [comment]
bumping @unparalleled-js :)

is this still happening?

**Comment by unparalleled-js** [comment]
Yes. I am rather defeated. My chain keeps getting into bad states and I don't know why, I am using the same scripts I use for Hardhat, EthTester, and geth.

Thinking I may abandon using HTTP with Anvil and try to make rust bindings instead but I don't have capacity for that yet.

Oh. I was working on a repro script but that only uses web.py instead of our framework but haven't had a ton of time there either.

**Comment by onbjerg** [comment]
Closing, should be fixed in the latest nightly, reopen if it's still an issue with some additional context :smile:
