### ISSUE TITLE
Don't keep `CALLER` balance as `U256::MAX`

### ISSUE THREAD

**Issue by mds1** [foundry-rs/foundry#2390]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### Describe the bug

Here, we set the balance of `CALLER` and other addresses  to `U256::MAX` to make sure they can execute deploys.
https://github.com/foundry-rs/foundry/blob/7e12adbc30d56174320d12be52f94a34d7405c69/forge/src/runner.rs#L69-L71

A few lines below, we set the balances to the user-specified initial balance.
https://github.com/foundry-rs/foundry/blob/7e12adbc30d56174320d12be52f94a34d7405c69/forge/src/runner.rs#L128-L131

However, `CALLER` is left out of there, so if a fuzz test chooses the `CALLER` address and that test sends ETH to that address, the test reverts with balance overflow.

Proposed fix is to set the `CALLER` balance after L132 to either 0, or to `self.initial_balance`. I believe either should be suitable since `CALLER` isn't used afterwards AFAIK.

This is partially related to #2322 in that I don't think the default balance of an account should ever be kept at `U256::MAX`, so in that PR I'd suggest using the default `self.initial_balance` that's typically used instead.

**Comment by onbjerg** [comment]
Unsure, I don't know what that address is being used for. I think it's for script?

**Comment by onbjerg** [comment]
Reopened because I don't think it resolved https://github.com/foundry-rs/foundry/issues/2390#issuecomment-1189526352

**Comment by mds1** [comment]
Yep, thanks. Interestingly, @jferas and I both did not see fuzz failures with either of those two addresses until recently, but I don't recall seeing a change that would cause them to start being included in the fuzz dict.

So I think the scope of this issue may be three items:
1. Reduce the initial balance of `0x3fAB184622Dc19b6109349B94811493BF2a45362` to something smaller.
2. Make these addresses constants
3. Decide if these addresses should really be in the fuzz dict or not

**Comment by onbjerg** [comment]
Hmm, I think `self.sender` and `self.test_address` could both be valid inputs(?) and should not be excluded. For `CALLER` I think we should just reduce the balance of that account to 0.

**Comment by mds1** [comment]
> Hmm, I think `self.sender` and `self.test_address` could both be valid inputs(?) and should not be excluded.

Yea I think I lean this way also, just want to make sure they have more realistic default balances in that case

> For `CALLER` I think we should not have any balance on it before it is actually used - as far as I remember it is only used to call `failed()` on the test contracts?

Ah ok, yea that seems like a reasonable approach to me then. Perhaps we keep the balance zero, set it to nonzero to call `failed()`, then reset back to zero after the call?

**Comment by onbjerg** [comment]
>Ah ok, yea that seems like a reasonable approach to me then. Perhaps we keep the balance zero, set it to nonzero to call failed(), then reset back to zero after the call?

Yea that's what I meant

**Comment by joshieDo** [comment]
> 0x3fAB184622Dc19b6109349B94811493BF2a45362

Does it still have issues with the latest version? Current master branch should handle that.

https://github.com/foundry-rs/foundry/blob/f0fa5da3c53858dbf9ac602ffeb633e15c39b9a3/evm/src/executor/mod.rs#L108-L120

**Comment by onbjerg** [comment]
The ask is to set it to 0 again after deployment :smile:

**Comment by klkvr** [comment]
Closed by https://github.com/foundry-rs/foundry/pull/2322 and https://github.com/foundry-rs/foundry/pull/8331
