### ISSUE TITLE
Bit Shifting in Cast

### ISSUE THREAD

**Issue by HrikB** [foundry-rs/foundry#2394]
### Component

Cast

### Describe the feature you would like

Bit shifting right or left for numbers as large as `uint256`

**Comment by onbjerg** [comment]
Can you elaborate a bit on the use case and the UX you want?

**Comment by HrikB** [comment]
As I've been doing a lot more exploration into low-level EVM, I have been playing around a lot with the byte form of data and sometimes my assembly code will require right and left shifting. Given that cast has such an extensive set of utilities, it seems like bit shifting would fit right in. 

In terms of UX, something like `(Dec or Hex) [>>, <<] (Dec or Hex) --output [dec, hex]` would be great.
So `42 << 250 --output hex` should yield `0xa800000000000000000000000000000000000000000000000000000000000000`
And `0xa800000000000000000000000000000000000000000000000000000000000000 >> 250 --output hex` would yield `0x2a`.

Support for `uint256` would be great since I haven't found any online tools that support numbers that large. 

Additionally, while I haven't had the need for this myself, to make the tool holistic, it might be great to include support for signed integers as well. So perhaps another option `--(un)signed`.

**Comment by mds1** [comment]
Just curious to better understand your use case—would you use this in scripts for something? Or is this just for quickly testing things as an alternative to [solidity-shell](https://github.com/tintinweb/solidity-shell)?

**Comment by mds1** [comment]
If this does get implemented, I'd suggest matching the opcode UX, e.g. `cast shl <shift> <value>` and `cast shr <shift> <value>`: https://www.evm.codes/#1b

**Comment by iFrostizz** [comment]
> If this does get implemented, I'd suggest matching the opcode UX, e.g. `cast shl <shift> <value>` and `cast shr <shift> <value>`: https://www.evm.codes/#1b

Yeah, thanks for the input that's definitely better and not hitting the issue faced in the PR !

**Comment by iFrostizz** [comment]
Does it makes sense to choose the base of the output number ? Like shouldn't we display it in the same base it has been inputted ?

**Comment by HrikB** [comment]
Honestly think it could go either way. It'd be nice to have to option to choose the base of the output but it's not necessary. I def think it should default to same base tho. If you implement the `--output` flag, it should be optional imo.

**Comment by iFrostizz** [comment]
Good point

**Comment by onbjerg** [comment]
Closed in #2416, thanks @iFrostizz :)
