### ISSUE TITLE
Feature: Foundry 1.0.0-0.00

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#2396]
## Feature Requests
Paginated command line menu
Support for http imports for contracts 
Support for a vendor directory for deps
Support for outputting dependency mapping into json format
Support for content addressable cache
Secured upstream supply chain as much a possible
A CI build that doesnt include libusb 
Shasum and GPG signed releases

Also
correctly init macOS bash_profile
Output JSON without the unnecessary non JSON comment 
Better diagnostic TUI 
Anvil supporting OTEL/Zipkin tracing 
Protobuf support for defining fuzz targets  
Non monolithic docker image 
Non alpine docker image 
Saving deployments like remix scenarios 
Possibility of replaying deployments from said scenarios 
Proxy / upgrade support for OZ

And
Reimplement solidity compiler in rust

**Comment by onbjerg** [comment]
Please file separate issues for these, it's going to be extremely hard to track and discuss individual features when they are listed here (and some of them lack context for me + some of them are dupes of existing requests)
