### ISSUE TITLE
`forge fmt` minor unexpected formatting results

### ISSUE THREAD

**Issue by Hyodar** [foundry-rs/foundry#2398]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (cce3a44 2022-07-20T00:34:27.703293Z)

### What command(s) is the bug in?

forge fmt

### Operating System

Windows

### Describe the bug

Hello there!

Nothing major but I believe the formatting is a bit odd in some cases. Two cases I noticed:

* Opening brace goes to the next line when the line is long (but not too long!):

  _Before_:
  ```
          if (something() || somethingElse() || anotherThing() || someOtherThin()) {
              return false;
          }
  ```
  _After_:
  ```
          if (something() || somethingElse() || anotherThing() || someOtherThin())
          {
              return false;
          }
  ```
  Curiously, if the last function in the expression is `someOtherTh()`, which would still make the line length go past 80, the line stays the same, and if it's `someOtherThing()`, it works as expected by moving the expression to the next line.

* Binary operators seem to always be positioned at the same column when breaking long expressions into multiple lines:

  This one I'm less sure than the first one about whether it's a bug or just something that's not currenty implemented but will be.

  _Before_:
  ```
  bool somethingElse = something == 2 || something == 3 || something == 5 || something == 7 || something == 11;
  ```
  _After_:
  ```
  bool somethingElse = something
      == 2
      || something
      == 3
      || something
      == 5
      || something
      == 7
      || something
      == 11;
  ```

That's it. By the way, I've been trying out forge and it's been a great experience. Good work!

**Comment by sambacha** [comment]
Here is a similar example but even more extreme: https://github.com/sambacha/dappspec/blob/master/solidity/src/Recommendations/Large-Integers.md

![](https://camo.githubusercontent.com/699a9c26e17b51b2d09467e28082053656ffad7adb8c399d9b4498eb188893d4/68747470733a2f2f642e70722f692f664654674c6c2e6a706567)

**Comment by onbjerg** [comment]
cc @rkrasiuk / @jpopesculian unsure if this is still the case

**Comment by ewilz** [comment]
I was hoping that the linter would allow one line conditionals. Going to append this here as a comment for now instead of making a new issue. 

<img width="535" alt="image" src="https://user-images.githubusercontent.com/5539720/187267522-b711f187-0bb7-4d7d-b80b-8bdc4227647f.png">

**Comment by rkrasiuk** [comment]
@ewilz currently we support this only in yul blocks. feel free to open a feature request for fmt config option

**Comment by mds1** [comment]
Everything here appears to be resolved now, so closing this
