### ISSUE TITLE
Feature: Signed Releases 

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#2400]
### Component

Forge, Cast, Anvil, Foundryup, Other (please describe)

### Describe the feature you would like

Signed releases by core contributors 

GPG Signed git tag
SHA256SUM of binaries

### Additional context

Foundry is being used to compile code that handles money, it is and will increasingly become a target for malicious actors. Right now there is no assurance that nightly releases have any sort of verifiable component to them. 

part of https://github.com/foundry-rs/foundry/issues/2396

**Comment by grandizzy** [comment]
binaries are not attested on gh https://github.com/foundry-rs/foundry/attestations

**Comment by sambacha** [comment]
> binaries are now attested on gh [foundry-rs/foundry/attestations](https://github.com/foundry-rs/foundry/attestations)

awesome thanks!
