### ISSUE TITLE
Feature: custom rpc method, `eth_multicall` for Anvil

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#2406]
### Component

Anvil

### Describe the feature you would like

 Call implements `eth_call`. Executes a new message call immediately without creating a transaction on the block chain.

[see https://github.com/covalenthq/erigon/commit/7a70eb6ccb99eb242b066e23026de41f3bf70561](https://github.com/covalenthq/erigon/commit/7a70eb6ccb99eb242b066e23026de41f3bf70561)

### Additional context

part of https://github.com/foundry-rs/foundry/issues/2396

**Comment by onbjerg** [comment]
Closing this since you can use bath RPC requests to achieve the same result. We might add multicall support to other Foundry tools at some point (e.g. `cast`)

**Comment by sambacha** [comment]
> Closing this since you can use bath RPC requests to achieve the same result. We might add multicall support to other Foundry tools at some point (e.g. `cast`)

Batch RPC Requests are not the same as multicall. Batch waits for the last RPC Request to finish to return, multicall can return as they are finished

**Comment by taylorjdawson** [comment]
How else can you test the multicall functionality in a local devnet (not testnet)?
