### ISSUE TITLE
`forge fmt` fail to parse code when struct have comment

### ISSUE THREAD

**Issue by thasarito** [foundry-rs/foundry#2409]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (cce3a44 2022-07-20T00:15:31.034352Z)

### What command(s) is the bug in?

forge fmt

### Operating System

macOS (Apple Silicon)

### Describe the bug

Running `forge fmt` with file that have comment inside struct like this

```solidity
struct Foo {
  /// @notice bar
  uint256 bar;
  /// @notice baz;
  uint256 baz;
}
```

will throw `Failed to parse Solidity code` error.

**Comment by 7sne** [comment]
Can I pick it up if it's relevant?

**Comment by onbjerg** [comment]
I'd assume this error is in [solang-parser](https://crates.io/crates/solang-parser) since that's the parser we use for the formatter

**Comment by CodeSandwich** [comment]
It seems that that as of `forge 0.2.0 (63ed109 2022-08-09T00:03:50.892098571Z)` this issue is solved.
