### ISSUE TITLE
Tweak (fmt): Increase the line length default to 120

### ISSUE THREAD

**Issue by jpopesculian** [foundry-rs/foundry#2411]
### Component

Forge

### Describe the feature you would like

https://github.com/ethereum/solidity/pull/12681

Recommended line length has been increased for the next version of solidity, and we should update accordingly. The tests for fmt will need to be updated to accommodate

**Comment by sambacha** [comment]
The solidity style guide is incorrect, 100 is the true preferred value

**Comment by Vectorized** [comment]
Let's stick to 120. The upcoming style guide has not changed. 

I do not support changing the value to 100, despite personally using it.

Of course if you do statistical analysis, the mean is 100.

**Comment by sambacha** [comment]
> Let's stick to 120. The upcoming style guide has not changed.
> 
> I do not support changing the value to 100, despite personally using it.
> 
> Of course if you do statistical analysis, the mean is 100.

just to let you know, this isn't a LOC count value; you can have over 120 characters and still not trigger the formatter if, for example, the function uses really long words, etc. So the original solidity issue is incorrect in its conclusion as its motivation statement referenced directly LOC w.r.t monitor sizes. 

[reference comment in issue](https://github.com/ethereum/solidity/pull/12681#issue-1139515157)

**Comment by gakonst** [comment]
Let's go with 120 :)
