### ISSUE TITLE
"--offline" not respected when used in conjunction with "--use"

### ISSUE THREAD

**Issue by paulrberg** [foundry-rs/foundry#2412]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (cce3a44 2022-07-20T00:15:31.034352Z)

### What command(s) is the bug in?

forge build --offline --use "0.8.15"

### Operating System

macOS (Apple Silicon)

### Describe the bug

When running this command:

> forge build --offline --use "0.8.15"

On a computer on which I don't have v0.8.15 of solc installed, I would expect Forge not to install the compiler version for me when I add the `--offline` flag. But that is not the behavior that I'm observing. Forge proceeds with pulling the compiler from remote.

This is in contradiction to what the docs for `forge build --offline` say:

> Do not access the network. Missing solc versions will not be installed.

**Comment by mattsse** [comment]
nice catch, I believe `use`, and potential installation is handled separately, but should take `--offline` into account
