### ISSUE TITLE
Mumbai Testnet Deployment Errors

### ISSUE THREAD

**Issue by smak0v** [foundry-rs/foundry#2421]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (cce3a44 2022-07-20T00:14:55.494548Z)

### What command(s) is the bug in?

forge script script/Donatello.s.sol:DonatelloDeploy --rpc-url $MUMBAI_RPC_URL  --private-key $PRIVATE_KEY --broadcast --verify --etherscan-api-key $POLYGONSCAN_API_KEY --gas-limit $GAS_LIMIT -vvvv;

### Operating System

macOS (Intel)

### Describe the bug

I'm trying to deploy my contract to a Mumbai Testnet. And every time I got a new error (see the screen, 3 times - 3 errors)
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/26391964/180169561-437bdd13-4d0e-4255-8c76-04bd5ff2d34c.png">

**Comment by mattsse** [comment]
could you please check that the `MUMBAI_RPC_URL` is an archive node? because this looks like an issue with the node you're using

**Comment by smak0v** [comment]
I'm using this one: https://matic-mumbai.chainstacklabs.com

**Comment by peter-ciccolo** [comment]
Have you tried any alternatives? e.g. 

- https://rpc-mumbai.matic.today
- https://rpc-mumbai.maticvigil.com
- https://matic-testnet-archive-rpc.bwarelabs.com

The mumbai testnet nodes are not the most reliable in my experience.

**Comment by smak0v** [comment]
Yes, you are right. This one is working good: https://rpc-mumbai.maticvigil.com/
Thank you!

**Comment by mattsse** [comment]
was this resolved by switching to another node @smak0v ?

**Comment by smak0v** [comment]
Yes, switching to a new node helped me.
