### ISSUE TITLE
eth_subscribe not working

### ISSUE THREAD

**Issue by jpiabrantes** [foundry-rs/foundry#2423]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

0.2.0

### Operating System

macOS (Apple Silicon)

### Describe the bug

`eth_subscribe` gives the following error:
```sh
{'jsonrpc': '2.0', 'id': 1, 'error': {'code': -32602, 'message': 'data did not match any variant of untagged enum EthRpcCall'}}
```

Here's the code:
```python
async with connect("ws://localhost:8545") as ws:
    await ws.send(json.dumps({
        "jsonrpc": "2.0",
        "id": 1,
        "method": "eth_subscribe",
        "params": ["newHeads"]
    }))
    subscription_id = json.loads(await ws.recv())["result"]
    print(subscription_id)
    while True:
        message = await ws.recv()
        print(json.loads(message))
        # this prints: {'jsonrpc': '2.0', 'id': 1, 'error': {'code': -32602, 'message': 'data did not match any variant of untagged enum EthRpcCall'}}
```

**Comment by mattsse** [comment]
this looks like `eth_subscribe` installs correctly because you get the `subscription_id `?

what does 

`message = await ws.recv()` do exactly?

could you please try running with `RUST_LOG=rpc=warn anvil ...` this should log the rpc call that failed

**Comment by jpiabrantes** [comment]
thank you for this @mattsse

I was able to debug with `RUST_LOG=rpc=warn anvil` it was an error on my code! Sorry for the spam :(
