### ISSUE TITLE
Could not instantiate forked environment Error when Deploying to Skale Network

### ISSUE THREAD

**Issue by yohanelly95** [foundry-rs/foundry#2426]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (cce3a44 2022-07-20T00:15:31.034352Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

Deploying a contract to Skale chain is always failing. 

The command I am running ```forge script scripts/Deploy.s.sol:DelegatorScript --fork-url https://staging-v2.skalenodes.com/v1/whispering-turais
 --private-key ${PRIV_KEY} --broadcast --legacy```. 

The error: 
![Screenshot 2022-07-21 at 6 41 36 PM](https://user-images.githubusercontent.com/33081891/180221770-1235cc03-63bf-4849-ac6e-a1a768c5f760.png)

 What my `Deploy.s.sol` looks like :  
 
 ```import "forge-std/Script.sol";
import "forge-std/Test.sol";
import "forge-std/console.sol";
import {A} from "contracts/A.sol";
import {B} from "contracts/Core/B.sol";
import {C} from "contracts/Core/C.sol";
import {D} from "contracts/Core/D.sol";
import {E} from "contracts/Core/E.sol";
import {F} from "contracts/Core/F.sol";
import {G} from "contracts/Core/G.sol";
import {H} from "contracts/Core/parameters/H.sol";
import {I} from "contracts/randomNumber/I.sol";
import {J} from "contracts/tokenization/J.sol";
import {K} from "contracts/tokenization/K.sol";

contract DeployScript is Script, Test {
    function setUp() public {}

    function run() public {
        vm.startBroadcast();
        G governance = new G();
        B blockM = new B();
        address gov = address(governance);
        governance.grantRole("0x0000000000000000", address(blockM));
        vm.stopBroadcast();
    }
}```

**Comment by mattsse** [comment]
hmm the node works fine as

```console
curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method": "eth_getBlockByNumber", "params": ["latest", false],"id":67}' https://staging-v2.skalenodes.com/v1/whispering-turais
```

works as expected.

this seems to be a tls issue, did this only happen once or is this reproducible? if so then there's something off with the tls setup
