### ISSUE TITLE
Forge Crashes running forked tests

### ISSUE THREAD

**Issue by Genysys** [foundry-rs/foundry#2427]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (4e141e7 2022-07-21T00:11:34.699666Z)

### What command(s) is the bug in?

forge test -f $INFURA -vvvvv --match-contract LandNFT --match-test testSafeMintWithETH

### Operating System

macOS (Apple Silicon)

### Describe the bug

This comes up occasionally when I am running forked tests. 

```bash
Compiler run successful
The application panicked (crashed).
Message:  could not instantiate forked environment: 
Failed to get block for block number: 15186082
latest block number: 15186082
Location: evm/src/executor/opts.rs:68

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Abort trap: 6
```

**Comment by mattsse** [comment]
looks like an rpc issue
does

```console
curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method": "eth_getBlockByNumber", "params": ["latest", false],"id":67}' "$INFURA"
```

work?

**Comment by Genysys** [comment]
Yes it does

**Comment by mattsse** [comment]
does this happen consistently? maybe just a flake and the node didn't feel like sending the block -.-

**Comment by Genysys** [comment]
Sounds reasonable. Closing this and will keep monitoring the situation. It
might be helpful to handle the error and not panic.
