### ISSUE TITLE
Unable to get env vars to load

### ISSUE THREAD

**Issue by HrikB** [foundry-rs/foundry#2430]
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

I am unable to load enviroment variables from .env into my foundry.toml the RPC-endpoint settings of https://github.com/foundry-rs/foundry/blob/master/config/README.md

In my test:
![image](https://user-images.githubusercontent.com/23041116/180233958-9bd00a3a-cf21-4579-93e5-1b1784cc633f.png)

In my foundry.toml
![image](https://user-images.githubusercontent.com/23041116/180234031-29e0ff35-440c-4850-8d23-96c314f8de90.png)

Console
![image](https://user-images.githubusercontent.com/23041116/180234325-fd441fd8-e8b3-4b71-8fa6-7ed24d5a659e.png)

Inside my .env, I have set both `INFURA_API_KEY` and `FOUNDRY_INFURA_API_KEY` to correct api key.

**Comment by mattsse** [comment]
can you paste the error hex code, that should be encoded error message.

what does `forge config` print for `rpc_endpoints`?

**Comment by HrikB** [comment]
I did run `source .env`. 

```
[2909] LootboxTest::setUp() 
    ├─ [0] VM::rpcUrl("rinkeby") 
    │   └─ ← 0x0bc445031644df03923eb2ab981d332f4354ceab11a95efce72a938e57beaadf0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000004a4661696c656420746f207265736f6c766520656e76207661722060494e465552415f4150495f4b4559603a20656e7669726f6e6d656e74207661726961626c65206e6f7420666f756e6400000000000000000000000000000000000000000000
    └─ ← 0x0bc445031644df03923eb2ab981d332f4354ceab11a95efce72a938e57beaadf0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000004a4661696c656420746f207265736f6c766520656e76207661722060494e465552415f4150495f4b4559603a20656e7669726f6e6d656e74207661726961626c65206e6f7420666f756e6400000000000000000000000000000000000000000000
```

Forge config (after running `source .env`):
![image](https://user-images.githubusercontent.com/23041116/180248055-84ec7c29-d20f-4243-bba5-10c2944bcd21.png)

**Comment by HrikB** [comment]
Seems like it can't find the envvar in .env

**Comment by mattsse** [comment]
can you please double check that `INFURA_API_KEY` is set when you run forge?

**Comment by HrikB** [comment]
Yes and ‘FOUNDRY_INFURA_API_KEY’ is set but only inside the .env. If I run ‘echo $INFURA_API_KEY’ it returns nothing until I run ‘source .env’ at which point the echo returns the right value. But ‘forge test’ and ‘forge confit’ still can’t findit

**Comment by mattsse** [comment]
can't reproduce with latest forge

<img width="385" alt="image" src="https://user-images.githubusercontent.com/19890894/180252733-77d721fc-38dc-43e2-857d-f0da906720f8.png">

**Comment by HrikB** [comment]
Can you also show me your .env and foundry.toml?

**Comment by mattsse** [comment]
```toml
[rpc_endpoints]
rinkeby = "https://mainnet.infura.io/v3/${INFURA_API_KEY}"
```

```solidity
contract ContractTest is Test {
    function setUp() public {}

    function testExample() public {
        string memory url = vm.rpcUrl("rinkeby");
        console.log(url);
    }
}
```

your error is most likely in your env file, forge doesn't know env files only considers set vars, that's what

```INFURA_API_KEY="123456" forge test -vvv``` does

**Comment by onbjerg** [comment]
Please ensure your `.env` file **exports** the environment variables if you use `source`, otherwise the environment variables will be local to your shell and *not* propagate automatically to any processes you spawn.

For example:

**Doesn't work (.env does *not* export env vars)**

```sh
$ cat .env
FOO=bar
$ source .env

# FOO is local to your shell, but no program you spawn can use it
$ echo $FOO 
bar
```

**Works (.env *does* export env vars)**

```sh
$ cat .env
export FOO=bar
$ source .env
# FOO is available in your shell, but child processes will also have access to it
$ echo $FOO 
bar
```

**Comment by HrikB** [comment]
Yes! This was the problem. I needed to add `export` in front of my variable. Works amazingly now. It would great, for others' sake, if that little snippet was added to docs.
