### ISSUE TITLE
Gas reports ignoring toml selection

### ISSUE THREAD

**Issue by Genysys** [foundry-rs/foundry#2431]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What command(s) is the bug in?

forge test --gas-report -f $INFURA

### Operating System

macOS (Apple Silicon)

### Describe the bug

In my `foundry.toml` file, I specify the contracts I want to generate gas reports for. 

```bash
gas_reports = ["LandBank", "LandNft", "Marketplace"]
```

Unfortunately , it ignores it and prints out every contracts (including including interfaces).

**MRE**:

* git clone https://github.com/realiotech/realioverse-contracts.git
* git checkout git checkout feat/refactor
* forge test --gas-report -f $INFURA

**Comment by dsam82** [comment]
@mattsse I may have found the cause of this issue while investigating #2287, should I make a PR? or you've already resolved this?

**Comment by mattsse** [comment]
@dsam82 that'd be awesome!

haven't looked into it yet, please share your findings or open PR

thank you!
