### ISSUE TITLE
couldn't deploy: Execution reverted @ `cli/src/cmd/forge/script/runner.rs:68`

### ISSUE THREAD

**Issue by skaunov** [foundry-rs/foundry#2432]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (4e141e7 2022-07-21T00:08:59.558233829Z)

### What command(s) is the bug in?

forge script

### Operating System

Linux

### Describe the bug

This was received with `Contract.sol` identical to <https://gist.github.com/CJ42/892f229e06bf07e3e34c3a8472369f8b#file-myvestingwallet-sol> with only `import` corrected.
```console
$ RUST_BACKTRACE=full forge script src/Contract.sol:MyVestingWallet --fork-url http://localhost:8545 --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --broadcast
[⠊] Compiling...
No files changed, compilation skipped
The application panicked (crashed).
Message:  couldn't deploy: Execution { reverted: true, reason: "Revert", gas: 101442, stipend: 0, logs: [], traces: None, debug: None, labels: {}, transactions: None, state_changeset: None }
Location: cli/src/cmd/forge/script/runner.rs:68

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: __libc_start_main<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Aborted (core dumped)
```

**Comment by onbjerg** [comment]
It is not your contract that couldn't be deployed, it's your script: most likely something in your script constructor is reverting

**Comment by skaunov** [comment]
I see. Was confused by this output.

**Comment by onbjerg** [comment]
Will keep that in mind for #2131 which should improve error messages across the board :)
