### ISSUE TITLE
Pretty printed ABI from Forge Inspect

### ISSUE THREAD

**Issue by maurelian** [foundry-rs/foundry#2433]
### Component

Forge

## Issue
`forge inspect <ContractName> abi` only prints a json formatted abi. 

That wouldn't be an issue, if it were possible to easily pipe the output to `jq` however the warnings printed at the beginning of the output prevent that work working. 

## Suggested Feature

A `--pretty` formatting (similar to what's available for `storageLayout`) of the output would be great to have.

### Additional context

Current output looks like this (I see now that the warnings are pretty easy to resolve):

```shell
$ forge inspect --pretty L1CrossDomainMessenger abi
warning: Unknown section [ci] found in foundry.toml. This notation for profiles has been deprecated and may result in the profile not being registered in future versions. Please use [profile.default] instead or run `forge config --fix`.
warning: Unknown section [default] found in foundry.toml. This notation for profiles has been deprecated and may result in the profile not being registered in future versions. Please use [profile.default] instead or run `forge config --fix`.
warning: Unknown section [default] found in node_modules/excessively-safe-call/foundry.toml. This notation for profiles has been deprecated and may result in the profile not being registered in future versions. Please use [profile.default] instead or run `forge config --fix`.
[
  {
    "inputs": [
      {
        "internalType": "contract OptimismPortal",
        "name": "_portal",
        "type": "address"
      }
    ],
    ...
```

**Comment by onbjerg** [comment]
Not following entirely: do you want `--pretty` to print a table? If so, any thoughts on events vs functions in this output? :smile:

**Comment by sambacha** [comment]
He wants something along the lines of:

forge $cmd | tail -n +2 | tee $outputFile

**Comment by onbjerg** [comment]
No, removing the warnings seems secondary - the only reason the warnings are wanted to be gone is because the output is not pipeable into jq, so it is not possible to construct a prettified output yourself. I'm fairly confident it is about wanting a table?

**Comment by mds1** [comment]
One idea is to have `--pretty` print the interfaces the same way that `cast interface` does, e.g. as a Solidity interface. Though `cast interface` doesn't handle structs well and just prints tuples with generic variable names of `a`, `b`, etc.

**Comment by maurelian** [comment]
A table would be fine. 
So would something like `cast interface`.
Ideally it has all of the info available in an abi entry, just easier to read.

**Comment by timofeli** [comment]
@maurelian is this still open and in need of work? If yes, can I pick it up?

**Comment by maurelian** [comment]
> @maurelian is this still open and in need of work? If yes, can I pick it up? 

@timofeli  I'm just a user. @gakonst wdyt?

**Comment by gakonst** [comment]
Yes! Go for it @timofeli

**Comment by drortirosh** [comment]
I think that in general, warnings should be sent to stderr, not stdout

**Comment by zerosnacks** [comment]
Marking this as resolved, `forge inspect Counter abi` now outputs in pretty print format

**Comment by pstephenwille** [comment]
this is pretty helpful
`forge inspect ./src/TicTacToe.sol:TicTacToe abi > ttt.abi.json`
