### ISSUE TITLE
`forge script --verify` fails with "Etherscan could not detect the deployment"

### ISSUE THREAD

**Issue by hbarcelos** [foundry-rs/foundry#2435]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (4e141e7 2022-07-21T00:08:59.558233829Z)

### What command(s) is the bug in?

forge script

### Operating System

Linux

### Describe the bug

I have a fairly simple contract which I'm trying to deploy though a script:

Contract:

```solidity
pragma solidity ^0.8.14;

contract Example {
  uint256 public immutable a;

  constructor(uint256 a_) {
    a = a_;
  }
}
```

Script:
```solidity
pragma solidity ^0.8.14;

import "forge-std/Script.sol";
import {Example} from "./Example.sol";

contract ExampleDeploy is Script {
  function run() external returns (Example) {
    vm.startBroadcast();

    Example tpl = new Example(1);

    vm.stopBroadcast();

    return tpl;
  }
}

```

Then I try to execute the script like:

```bash
export ETHERSCAN_API_KEY=MY_API_KEY
forge script ExampleDeploy --fork-url=http://localhost:8545 -vvv --verify --broadcast
```

The contract is deployed, however the source code verification fails as I the following error:

```
> Error: 
> Etherscan could not detect the deployment.
```

I have tried executing this script several times and the failure rate is 100%, always on the verification step.

**Comment by joshieDo** [comment]
Which network? Do you actually see it deployed on the etherscan in question ?

**Comment by hbarcelos** [comment]
Oops, I forgot to specify: I'm using Goerli.

Yes, the contract was deployed to Goerli, however the verification failed.

**Comment by joshieDo** [comment]
If you call again without the `--broadcast` flag, and only with the `--verify`, does it still happen ? I noticed that Goerli etherscan can be quite slow updating sometimes...

**Comment by 0xPhaze** [comment]
I've been running into the same issue. 
I'm still trying to verify on rinkeby. Pretty much happened exactly with the new recent update for me.
Before it would at least wait a bit (or have some retries), now it just instantly spits out the error.
Been swapping out `--broadcast` with `--resume` after running the script to get it to verify.

**Comment by hbarcelos** [comment]
> If you call again (once you see it on etherscan) without the `--broadcast` flag, and only with the `--verify`, does it still happen ? I noticed that Goerli etherscan can be quite slow updating sometimes...
> 
> I tried it now, and that's what happened.
> 
>     1. Gave me that error
> 
>     2. Had to wait around 2 minutes for the contract to show up on etherscan
> 
>     3. Called just with the --verify flag and it worked.

Yeah, omitting the `--broadcast` flag and calling it again makes the verification go through.

Would it be possible to embed this mechanism within the command?

As it is the command will exit with non-zero code, which can lead to all sorts of issues with shells running them.

**Comment by 0xCalibur** [comment]
I have something similar happening for a contract as simple as the op has. Not much error details except "Etherscan could not detect the deployment". using `--resume` instead `--broadcast` make it go thru the second run on my Mac.

Unfortunately on Windows, it always says and using `--resume` instead `--broadcast`  doesn't change anything.
```
Start Contract Verification
Transactions saved to: broadcast\Contract.s.sol\1\run-latest.json
```

The contracts are deployed correctly, it's just the verification process that seems to fails without giving any clues.

**Comment by onbjerg** [comment]
Has this been fixed recently? @joshieDo

**Comment by joshieDo** [comment]
Linked the above PR that taclkes this issue. However, not if the indexer takes 2 mins. But I think waiting 25 seconds for a contract should be enough. wdyt
