### ISSUE TITLE
Forge Script - Referencing an env variable outside of setUp or a function causes a panic.

### ISSUE THREAD

**Issue by TheRightChoyce** [foundry-rs/foundry#2438]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (160cc81 2022-07-22T00:04:32.424398Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Intel)

### Describe the bug

Sample code:

```
contract Deployer is Script {
  Contract contract = Contract(vm.envAddress("CONTRACT_ADDRESS"));

  function run() public {
    // never gets here.
  }

}
```

Will result in:

```
The application panicked (crashed).
Message:  couldn't deploy: Execution { reverted: true, reason: "environment variable not found", ....
Location: cli/src/cmd/forge/script/runner.rs:66

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry
```

There was an easy workaround which is to just ensure everything gets initialized in the setUp function, but reporting because of the bug/crash!

**Comment by onbjerg** [comment]
How do you set the environment variable? It should work where you are using it; we literally just read it from the environment

**Comment by TheRightChoyce** [comment]
In this case, I was using Solenv to load some env vars in the setUp function, but referencing them in the variable declarations as above.

It was easy to just initialized everything in the setUp function. Mostly filed this  because I got the "This is a bug" message as part of the crash : )

**Comment by onbjerg** [comment]
Ah, ok. Yeah, the behavior is expected; if the environment variable is loaded in `setUp` but you try to reference it outside of functions it will not work, since variable declarations etc. are processed during contract creation (which is before `setUp` is called). Will close this in favor of #2131 since the task in that issue is to be more aware of when we panic and when we bubble errors up :)
