### ISSUE TITLE
Docs in Forge CLI README are outdated

### ISSUE THREAD

**Issue by paulrberg** [foundry-rs/foundry#2442]
### Component

Forge

### Describe the feature you would like

The docs in [cli/README.md](https://github.com/paulrberg/foundry/blob/0da572cc771e96273424b6e060da6fab3d76511b/cli/README.md) do not reflect the latest state of the Forge CLI anymore. For example, the `use` flag for the `build` subcommand is not documented.

**Comment by onbjerg** [comment]
Imo we should consider just removing it entirely and keep user docs in the book, reserving documents in this repo for technical stuff targeted at contributors. Don't think it makes too much sense duplicating the docs

**Comment by paulrberg** [comment]
Very much agree - maintaining this would be a chore, long-term.

**Comment by mattsse** [comment]
yeh, very much in favor of rm this and only maintain the book
