### ISSUE TITLE
Feature: support bespoke natspec for testing directives 

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#2444]
### Component

Forge

### Describe the feature you would like

It would be nice for a custom natspec directive support for testing purposes, e.g

~~~javascript
//! @emit <% func name > [ emit log for func name ]
~~~

as another example I use a custom natspec directive to label emission events  
https://github.com/sambacha/dappspec/blob/master/hacking/RULES.txt

This would help potentially making code easier to audit and understand, especially if forge is able to read such directives and inject the behavior etc. 

the custom comment directive is arbitrary: using an actual natspec custom directive with forge as the prefix would be another possibility, similar to how OpenZeppelin uses them for its upgradable contracts

part of https://github.com/foundry-rs/foundry/issues/2396

### Additional context

~~~solidity
    
    abstract contract ERC2771Context is Context {
    /// @custom:oz-upgrades-unsafe-allow state-variable-immutable
    address private immutable _trustedForwarder;

    /// @custom:oz-upgrades-unsafe-allow constructor
    constructor(address trustedForwarder) {
        _trustedForwarder = trustedForwarder;
    }

**Comment by onbjerg** [comment]
Imo there is no real reason to add this when we already have cheatcodes and the natspec approach is probably more error prone (no editor integration) and less flexible (no setup, no complex logic). It would also overly fragment the approaches to testing requiring additional support + maintenance for something that would likely not be used that much. For those reasons I'll close this issue as "not planned" but @gakonst / @mattsse are free to reopen if they disagree

**Comment by sambacha** [comment]
> Imo there is no real reason to add this when we already have cheatcodes and the natspec approach is probably more error prone (no editor integration) and less flexible (no setup, no complex logic). It would also overly fragment the approaches to testing requiring additional support + maintenance for something that would likely not be used that much. For those reasons I'll close this issue as "not planned" but @gakonst / @mattsse are free to reopen if they disagree

good points, appreciate the feedback
