### ISSUE TITLE
Feature: Anvil Plugin Module for supporting custom RPC methods 

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#2446]
### Component

Anvil

## `anvil` plugin system

TLDR: Enable a plugin system to support creating new RPC methods without having to overly burden the maintenance of `anvil` 

This is pretty broad, however, it may be worthwhile instead of endless feature requests 

### Additional context

cc @mat

**Comment by onbjerg** [comment]
Closing this as out of scope
