### ISSUE TITLE
Consider changing names of autogenerated contracts to avoid syntax errors

### ISSUE THREAD

**Issue by krzkaczor** [foundry-rs/foundry#2451]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

latest

### What command(s) is the bug in?

init

### Describe the bug

Right now `--init` will generate a smart contract named "Contract" (https://github.com/foundry-rs/foundry/blob/master/cli/assets/ContractTemplate.sol). This is fine right now as this contract is not used anywhere. However, during my first interaction with foundry, right after `--init`, the first thing I wanted to try was adding a test. 

Unfortunately, I quickly run into syntax errors with quite unhelpful messages:

```solidity
Contract contract = new Contract()
```

Is a syntax error because `contract` is a keyword. A simple solution would be to rename `Contract` to `SampleContract`. I would propose doing the same for the script and test file for consistency. 

I can work on this change if there is a consensus that it's worth it.

**Comment by mds1** [comment]
+1 seems like a good idea to me, I never loved the default name of `Contract` for the same reason

**Comment by mattsse** [comment]
I think that's reasonable, 

should we make the template contract actually do something, like `Greeter.sol`, or only rename it.

what would be some alternatives, `SampleContract`, `ExampleContract`, `HelloWorldContract`?

**Comment by onbjerg** [comment]
We could add a simple `Counter` contract or something so the test also does something. Need to go over the book after this change since I think a lot of the docs probably reference the initial structure

**Comment by Tirthnp** [comment]
I would like to try doing this if you don't mind @onbjerg

**Comment by onbjerg** [comment]
Feel free :)

**Comment by Tirthnp** [comment]
@onbjerg  Can you please look at the following changes where I changed Contract.sol to Counter.sol. Is guess that's what we want? I can change the name to whatever is decided. Also, do I need to add some kind of default test for Counter.sol ?
https://github.com/foundry-rs/foundry/compare/master...Tirthnp:foundry:changeDefaultContractName%232451

**Comment by krzkaczor** [comment]
@Tirthnp i would suggest tweaking tests and scripts too so they actually do something.

**Comment by onbjerg** [comment]
Please open up a draft PR so we can keep discussion related to your code changes separate from the issue itself :)
