### ISSUE TITLE
`vm.expectRevert` doesn't work (or documentation is wrong)

### ISSUE THREAD

**Issue by duncancmt** [foundry-rs/foundry#2459]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (60b1919 2022-07-24T00:07:17.540473656Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

According to [the docs](https://book.getfoundry.sh/forge/cheatcodes), writing a test with `vm.expectRevert()` and then a failing call is the correct way to assert failure under a certain condition. However, when I do that, the test always fails with the message of the failing call. I think it's quite likely that I'm doing something wrong here, but the documentation seems pretty clear to me that this is supposed to work.

```solidity
// SPDX-License-Identifier: MIT
pragma solidity 0.8.15;

import "forge-std/Test.sol";

contract Mock {
  function fail() external pure {
    revert("fail");
  }
}

contract TestTest is Test {
  Mock internal mock;

  function setUp() external {
    mock = new Mock();
  }

  function test() external {
    vm.expectRevert();
    mock.fail();
  }
}
```

```
[⠘] Compiling...
No files changed, compilation skipped

Running 1 test for test/TestTest.t.sol:TestTest
[FAIL. Reason: fail] test() (gas: 8576)
Test result: FAILED. 0 passed; 1 failed; finished in 2.50ms

Failed tests:
[FAIL. Reason: fail] test() (gas: 8576)

Encountered a total of 1 failing tests, 0 tests succeeded
```

Adding a `vm.prank` call as in the example changes nothing. Switching to `vm.expectRevert(abi.encodeWithSignature("Error(string)", "fail"))` also changes nothing.

**Comment by duncancmt** [comment]
Ahh, I see now that `expectRevert(bytes calldata)` is looking for the error string, not the ABI encoded reason. I suggest that this be clarified in the documentation that `expectRevert()` is looking for an empty reason, `expectRevert(bytes4)` is looking for exactly a selector and nothing else, and that the signature be changed to `expectRevert(string calldata)` instead.

**Comment by onbjerg** [comment]
This is already stated in the docs for expectRevert: https://book.getfoundry.sh/cheatcodes/expect-revert

**Comment by duncancmt** [comment]
Thanks for that. I do think that

> **With `bytes`:** Asserts that the next call reverts with the specified bytes.

is misleading because it's discarding the `Error(string)` selector and ABI decoding the string.

Thanks again for answering my question!

**Comment by onbjerg** [comment]
I'm not sure I follow, can you expand on that? `vm.expectRevert` works with strings and there is an example on how to do that later down the page

**Comment by duncancmt** [comment]
The doc states that to catch a custom error with arguments, one should:
```solidity
vm.expectRevert(
    abi.encodeWithSelector(MyContract.CustomError.selector, 1, 2)
);
```

However, it seems that selector 0x08c379a0 (`Error(string)`) is special-cased because the following fails:

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.15;

import "forge-std/Test.sol";

contract Mock {
  function fail() external pure {
    bytes memory reason = abi.encodeWithSignature("Error(string)", string("fail"));
    assembly ("memory-safe") {
      revert(add(0x20, reason), mload(reason))
    }
    // This could just as easily be `revert("fail");`, but I wrote it out using
    // `abi.encodeWithSignature` to demonstrate that even though the
    // `vm.expectRevert` argument is identical, it is not caught.
  }
}

contract TestTest is Test {
  Mock internal mock;

  function setUp() external {
    mock = new Mock();
  }

  function test() external {
    vm.expectRevert(abi.encodeWithSignature("Error(string)", string("fail")));
    mock.fail();
  }
}
```
But if that signature is anything other than `Error(string)`, the test passes. Try substituting `"AnotherError(string)"` for `"Error(string)"` in both places to see what I mean.

---

It seems logical that if
```solidity
vm.expectRevert(abi.encodeWithSignature("AnotherError(string)", "bar"));
```
works, then
```solidity
vm.expectRevert(abi.encodeWithSignature("Error(string)", "bar"));
```
would also work (assuming that the correct error is subsequently thrown). However, because 0x08c379a0 is special-cased, `Error(string)` cannot be caught the way you'd expect.

**Comment by onbjerg** [comment]
Oh right, but that is not really a custom error if it's a Solidity built-in :smile:

**Comment by duncancmt** [comment]
Yeah, I'm not saying that the behavior is wrong, just that it's surprising if you know how revert reasons are encoded. Likewise, Solidity's inability to catch custom errors or handle invalidly encoded data with `try {} catch` is surprising, so maybe it's just a bad time all around :P
