### ISSUE TITLE
Tighter ABI integration in Cast

### ISSUE THREAD

**Issue by peter-ciccolo** [foundry-rs/foundry#2461]
### Component

Cast

### Describe the feature you would like

Custom errors are (hopefully) the future for Solidity, but tooling to support them is lacking across the ecosystem. I would like to be able to pass a param like `--contract` to `cast send` and, if the txn fails, have the data interpreted as a custom error under the assumption that the called contract code matched the code for the passed contract.

Edit (onbjerg): Similarly, we could use the contract ABI to decode other things

**Comment by onbjerg** [comment]
Changed the title slightly; I think in general we should have better ABI support in Cast for things like this

**Comment by zerosnacks** [comment]
Optimistically marking as resolved as there is support for custom errors in traces

Feel free to re-open if this is still an actionable ticket

**Comment by folex** [comment]
Hello! Is there any way to tell `cast` to decode methods and events from an ABI / solidity code on filesystem?

My use case is that I do `cast run`, and see the nice method-event call structure, eg:

```
    │   ├─ [4264] 0x7CDC2c080f0A9d35b6f91Ae38c7E1722b50BDEf6::087b97ba(2f8a25bc1ed2971b4d63647240c51c025be2f3a4c510f2710052e1e3d9196a95000000000000000000000000b52b84d74c8aa3f8a0cfe6da71fb80d8e60e2fb8) [delegatecall]
    │   │   ├─  emit topic 0: 0x69320c1eb39a752844ba207d2f98bd240d07dabf1449b4c1bd432daea12b744a
    │   │   │       topic 1: 0x2f8a25bc1ed2971b4d63647240c51c025be2f3a4c510f2710052e1e3d9196a95
    │   │   │           data: 0x000000000000000000000000b52b84d74c8aa3f8a0cfe6da71fb80d8e60e2fb8
    │   │   └─ ← [Stop]
    │   ├─ [4476] 0x7CDC2c080f0A9d35b6f91Ae38c7E1722b50BDEf6::a963e5f4(2f8a25bc1ed2971b4d63647240c51c025be2f3a4c510f2710052e1e3d9196a950000000000000000000000000000000000000000000000000000000013d92d40) [delegatecall]
    │   │   ├─  emit topic 0: 0xdd848dc9639c1bd25e20cfc64807b34179257bd6236df1e88b957e369d70bdeb
    │   │   │       topic 1: 0x2f8a25bc1ed2971b4d63647240c51c025be2f3a4c510f2710052e1e3d9196a95
    │   │   │           data: 0x0000000000000000000000000000000000000000000000000000000013d92d40
    │   │   └─ ← [Return]
```

But I wish I could see method names, event topics and fields named by the ABI / code. Is it possible rn? If not, shall I submit another issue? This one seems to me to cover almost the same request.

Thank you for your amazing tooling, it makes my work so much easier and more effective. 🙏 💟
