### ISSUE TITLE
Support static calls to state changing methods in forge scripts

### ISSUE THREAD

**Issue by ckoopmann** [foundry-rs/foundry#2463]
### Component

Forge

### Describe the feature you would like

It'd be great to be able to call a state changing (i.e. non-view) method on a contract to get it's return value without affecting contract state.

Basically it'd be doing the same thing as the [`eth_call` method ](https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_call). 

Note that this is different from just calling the method outside a `broadcast`-block since afaik those calls would still affect the simulated state during the scripts runtime.

The syntax could look something like this:
```
vm.startStaticCall();
uint returnValue = contract.stateChangingMethod();
vm.stopStaticCall();
```

### Additional context

Examples of this functionality in existing libraries:
- [ethers.js](https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_call)
- [web3.js](https://web3js.readthedocs.io/en/v1.2.6/web3-eth-contract.html#methods-mymethod-call)

**Comment by onbjerg** [comment]
You can achieve this using `vm.snapshot()` and `vm.revertTo()`: https://book.getfoundry.sh/cheatcodes/snapshots
