### ISSUE TITLE
Contract denylist for gas reports

### ISSUE THREAD

**Issue by paulrberg** [foundry-rs/foundry#2464]
### Component

Forge

### Describe the feature you would like

The [`gas_reports`](https://github.com/foundry-rs/foundry/blob/64fe4acc97e6d76551cea7598c201f05ecd65639/config/src/lib.rs#L134) config option can be used to allowlist a specific set of contracts, or use it as a pass-through flag (`*`) to enable gas reports for all contracts.

It is not currently possible to denylist (i.e. blacklist) some contracts, though this would be quite useful in practice. It's often the case that you want to get an overview of all the contracts that you wrote, but exclude certain testing dependencies.

We could name this `gas_reports_ignore` or `gas_reports_denylist`.

**Comment by derch28** [comment]
I'd like to work on this :) @onbjerg

**Comment by derch28** [comment]
I think [this](https://github.com/derch28/foundry/commit/7bb4125f8150305522c99d6524e68cfe71d0c79a) would add the feature.

I can't figure out how to write tests for it. So any help testing it would be appreciated.

**Comment by onbjerg** [comment]
Please open up a draft PR so we can address it there :)

**Comment by onbjerg** [comment]
Closed in #2528
