### ISSUE TITLE
Can use --match-path

### ISSUE THREAD

**Issue by 0xmikko** [foundry-rs/foundry#2477]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (64fe4ac 2022-07-26T00:12:15.317793Z)

### What command(s) is the bug in?

forge t  --match-path ./contracts/test/pathfinder/*

### Operating System

macOS (Apple Silicon)

### Describe the bug

mikael@Studio contracts-v2 % forge t  --match-path ./contracts/test/pathfinder/*
error: Found argument './contracts/test/pathfinder/UniswapV2PathFinder.t.sol' which wasn't expected, or isn't valid in this context

USAGE:
    forge test [OPTIONS]

I tried different combionation, there is not clear example what I should provide as glob

**Comment by mattsse** [comment]
thanks for flagging, this highlighted an issue with the glob matcher #2480

also unescaped glob gets expanded, could you try

`forge t --match-path "contracts/test/pathfinder/*"`

**Comment by 0xmikko** [comment]
Thanks, the way you've showed works
