### ISSUE TITLE
To show an informative error with zero balance

### ISSUE THREAD

**Issue by smak0v** [foundry-rs/foundry#2479]
### Component

Other (please describe)

### Describe the feature you would like

It would be cool to see an informative error message when a user in the tests have a zero balance and trying to attach some ETH to the transaction. For now transaction only reverts without any message. It is hard to find such a bug without informative message.
The same issue for a transactions where user is trying to attach more ETH that he have on his balance.

### Additional context

<img width="1792" alt="Screenshot 2022-07-26 at 16 37 09" src="https://user-images.githubusercontent.com/26391964/181020537-c94646d7-1c38-4319-b29d-98da36016261.png">

In this case Carol have 0 ETH on her balance.

**Comment by onbjerg** [comment]
What's your Forge version? This should be fixed.

**Comment by smak0v** [comment]
forge 0.2.0 (cce3a44 2022-07-20T00:14:55.494548Z)

**Comment by onbjerg** [comment]
Please update your installation, this was fixed in the nightly on the 24th
