### ISSUE TITLE
Forge scripts that include access to blockhash break when run with `--slow` option.

### ISSUE THREAD

**Issue by ckoopmann** [foundry-rs/foundry#2489]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a4b04ca 2022-07-27T00:12:33.444246Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Intel)

### Describe the bug

Forge scripts that contain operations that access `blockhash` break if run with `--slow` option, due to failing rpc requests for blockhashes of future blocks in the on-chain simulation step. Resulting in the following error:
<img width="497" alt="image" src="https://user-images.githubusercontent.com/15629702/181178927-08ed6c72-fa3a-4a93-a158-33b410ba578e.png">

See [this repo](https://github.com/ckoopmann/FoundryIssueBlockHash) for an example.

This error seems to have been introduced in #2481 . (Compare ci runs for nightly version [before](https://github.com/ckoopmann/FoundryIssueBlockHash/runs/7533902585?check_suite_focus=true) and [after](https://github.com/ckoopmann/FoundryIssueBlockHash/runs/7533902528?check_suite_focus=true) this merge).

**Comment by joshieDo** [comment]
Whats the desirable output of a future `block.hash` though? Is zero or one fine?

**Comment by onbjerg** [comment]
Is this solved by #2502 @mattsse?

**Comment by mattsse** [comment]
yep!

**Comment by ckoopmann** [comment]
@onbjerg @mattsse Are you sure this is fixed ? 
I upgraded foundry to [nightly-2f4dc6cc514ff816589144622f1d6e183dddb13b](https://github.com/foundry-rs/foundry/releases/tag/nightly-2f4dc6cc514ff816589144622f1d6e183dddb13b)  in my example CI and the issue seems to persist:
https://github.com/ckoopmann/FoundryIssueBlockHash/runs/7573962676?check_suite_focus=true
