### ISSUE TITLE
forge remapping crash

### ISSUE THREAD

**Issue by 0xcryptoshark** [foundry-rs/foundry#2496]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a4b04ca 2022-07-27T00:12:36.261849Z)

### What command(s) is the bug in?

forge re

### Operating System

macOS (Apple Silicon)

### Describe the bug

config error: expected an equals, found a colon at line 5 column 37
The application panicked (crashed).
Message:  failed to extract foundry config
Location: config/src/lib.rs:389

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   2: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   3: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   4: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   5: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   6: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   7: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   8: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   9: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  10: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  11: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  12: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  13: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  14: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
[1]    78285 abort      RUST_BACKTRACE=full forge re

**Comment by mattsse** [comment]
> expected an equals, found a colon at line 5 column 37

could you please double check that location and share the foundry.toml?

**Comment by 0xcryptoshark** [comment]
foundry.toml:
[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
"solidity.compileUsingRemoteVersion": "v0.8.13"


# See more config options https://github.com/foundry-rs/foundry/tree/master/config%       

Where I can find the file config/src/lib.rs?

**Comment by 0xcryptoshark** [comment]
my bad. the solidity line should not be there
