### ISSUE TITLE
forking mode 

### ISSUE THREAD

**Issue by gakonst** [foundry-rs/foundry#25]
https://github.com/brockelmore/rust-cevm/commit/30eefd0dde797554a2548ce4b44ed64d4b48c44c pretty clean
https://github.com/brockelmore/rust-cevm/search?q=fork+backend

if we can parallelize requests with `join`s, multithreaded tokio runtime etc. to get very high performance that'd be great

**Comment by gakonst** [comment]
Base RPC support was added in #42. Leaving this open for implementing the other forking methods above.

**Comment by mds1** [comment]
Seems this can be closed since we now have forking
