### ISSUE TITLE
Silently skipping compilation when inherited function from a separate file is not marked as virtual

### ISSUE THREAD

**Issue by laurenceday** [foundry-rs/foundry#2507]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (34d2414 2022-05-16T12:30:23.0948462Z)

### What command(s) is the bug in?

forge build

### Operating System

Windows

### Describe the bug

Given the following file that inadvertently skips the `virtual` keyword from the definition of `f()` in the `Inheritee` contract -

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

contract Inheritee {

    function f() external pure returns (uint) {
        return 1337;
    }

}

contract Inheritor is Inheritee {

    function f() external pure override returns (uint) {
        return 42;
    }

}
```

\- if you run `forge build` on this, you correctly get the error:

```sh
 error[4334]: TypeError: Trying to override non-virtual function. Did you forget to add "virtual"?
```

However, if you place these two contracts into separate files (e.g. `Inheritor.sol` and `Inheritee.sol`), attempting to run `forge build` will elide this error, produce `cache/solidity-files-cache.json` and then conclude:

```sh
$ forge build
[⠊] Compiling...
[⠒] Compiling 2 files with 0.8.13
[⠢] Solc 0.8.13 finished in 8.11ms
No files changed, compilation skipped
```

`forge build --force` produces the same result.

I've added the two files (simple as they are) in a repro repo [here](https://github.com/laurenceday/forge-inheritance-compilation-skip).

**Comment by mattsse** [comment]
your forge version looks severely outdated.

I wasn't able to reproduce this with the current version.

could you try again after running `foundryup`

**Comment by laurenceday** [comment]
Well, I feel silly given it used to be my job to catch people out on this exact thing - looks like my run of `foundryup` before filing this had failed on my Windows machine and I just blipped past it

Issue no longer reproducible - many thanks for the assist!
