### ISSUE TITLE
forge script --json always returns a zero status

### ISSUE THREAD

**Issue by Inphi** [foundry-rs/foundry#2508]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (2f4dc6c 2022-07-29T00:03:54.821792323Z)

### What command(s) is the bug in?

forge script --json Contract

### Operating System

Linux

### Describe the bug

Errors in a solidity script caused by reverts, asserts, etc, induce a non-zero exit code. However, running the script with the `--json` option always returns zero.
```bash
$ forge script AlwaysReverts --json && echo "success"
[⠰] Compiling...
[⠔] Compiling 4 files with 0.8.14
[⠃] Compiling 6 files with 0.8.9
[⠊] Solc 0.8.9 finished in 1.27s
[⠆] Solc 0.8.14 finished in 1.29s
Compiler run successful

{"logs":[],"gas_used":299261,"returns":{}}
success

$ forge script AlwaysReverts && echo exited
[⠰] Compiling...
[⠑] Compiling 5 files with 0.8.9
[⠃] Solc 0.8.9 finished in 1.24s
Compiler run successful


Script failed.
Gas used: 299261

== Return ==
Error:
Script failed.
```

This is a surprising behavior and I'd expect the exit status when adding `--json` to work the same way without the option.

**Comment by mds1** [comment]
Confirmed that `forge test --json` exits with an error, but `forge script --json` does not. Going to add this to https://github.com/foundry-rs/foundry/issues/4444 to track
