### ISSUE TITLE
Add threshold levels to forge snapshot --check

### ISSUE THREAD

**Issue by devtooligan** [foundry-rs/foundry#2509]
### Component

Forge

### Describe the feature you would like

We thought adding `forge snapshot --check` to our CI was a great idea.  It forces the dev to acknowledge and review any changes to the gas profile.  But it didn't turn out to be that helpful.  Pretty much every change affects the gas profile a little.  So what ended up happening was that devs never reviewed it, and it just became an annoyance solved by quickly running forge snapshot and pushing a new commit without even looking at it.

One idea to improve this feature might be to add some sort of thresholds.  For example, in foundry.toml user selects the minimum change (nominal or percentage) that must be met before the snapshot check fails.  example:

```
// foundry.toml
minimum_snapshot_gas_increase_percent=5
minimum_snapshot_gas_increase_value=500
minimum_snapshot_gas_decrease_percent=5
minimum_snapshot_gas_decrease_value=1000
```

Anyways, open to other ideas on how to solve the problem.  This is something that was mentioned on Twitter and gakonst asked for a ticket.

**Comment by mattsse** [comment]
thanks, you already have an honorable mention here #2484 lol

+1 on making this a config option

closing this here as this is a dup of #2484 

trying to get this over the line shortly.
