### ISSUE TITLE
Bug: anvil --config-out anvil.json upon completion starts anvil 

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#2512]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What command(s) is the bug in?

anvil --config-out anvil.json

### Describe the bug

when running

```console
usr:~ $ anvil --config-out anvil.json
```

I expect `anvil` to output the config to the json file, then quit. Anvil will correctly output to the json file, then it will actually start. I expect anvil not to start when running this command.

**Comment by mattsse** [comment]
this was the issue https://github.com/foundry-rs/foundry/issues/1718
and was added here https://github.com/foundry-rs/foundry/pull/1854

I see that this makes it impossible to only get the config without starting it, if we separate  running/dumping config it would mean that running + getting config is now a 2step process.

I am not sure what disadvantages this would have or what would be the best solution here, don't have strong feelings about this.

The question may be why you only want to get the json config and not start it.

**Comment by sambacha** [comment]
fair enough, i just thought it odd that generating a config would also start it, just making sure this is intended behavior, we can close this.
