### ISSUE TITLE
Multi Chain Deployment

### ISSUE THREAD

**Issue by joshieDo** [foundry-rs/foundry#2519]
### Component

Forge

### Describe the feature you would like

It would be cool to have a multi chain deployment, now that we have multi fork capabilities on the `vm`. [pending #2301]

I was working on a MVP, but there are a couple gotchas and decisions to be made. So I decided to start writing them here.

### Execution
1. Currently `vm.broadcast()` takes the `caller` as the signer. However, multi fork backends make the `caller`'s nonce persistent across forks. Ideally it should be non-persistent by default and tied to each backend.
2. Library Linking. This is kind of a chicken-egg problem. Not all forks may require the predeployed libraries coming from the build output, and we only know the ones that might need it once we run everything. Addresses and linkage have to be handled/calculated on a per-fork basis.

### Broadcast
1. Which log structure:
    1.1 One single file: `broadcast/multi/Contract.s.sol/[latest | timestamp]/[sig].json` 
    1.2 One folder/multiple files: `broadcast/multi/Contract.s.sol/[latest | timestamp]/[chain_id]/[sig].json` There'd be one extra file dictating the sequence.
2. Which broadcasting behaviour.
    2.1  Deploy to every chain in parallel. And we log it `Map<chain, ScriptSequence>`?
    2.2  Deploy sequentially regarding to chains. Example: chain1 -> chain2 -> chain1 -> chain3. And we log it `Vec<ScriptSequence>`
   
### Verification
1. Should we add a `vm.addEtherscanKey(forkId, key_str)` ?   Doesn't seem UX friendly to add and match `--etherscan-keys` to the command line.
    1.1. If we do... how do we handle `--verify` without any broadcast flag? We could run `setUp` every time, just to collect these keys. What if the code has changed since then?
    1.2 If not 1.1... then what?

**Comment by onbjerg** [comment]
Afaik Etherscan keys are universal, so a key from mainnet also works on Rinkeby?

**Comment by wiasliaw** [comment]
IDK if using forking cheatcode can deploy to multiple chain.

```toml
# foundry.toml
[rpc_endpoints]
optimism = "https://opt-goerli.g.alchemy.com/v2/<api key>"
goerli = "https://eth-goerli.g.alchemy.com/v2/<api key>"
```

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import "../lib/forge-std/src/Script.sol";

contract Try {}

contract MultipleDeployment is Script {
    function run() external {
        vm.startBroadcast();

        // create and select for optimism
        vm.createSelectFork(vm.rpcUrl("optimism"));
        address t1 = address(new Try());
        console.log(t1);

        // create and select fork for goerli
        vm.createSelectFork(vm.rpcUrl("goerli"));
        address t2 = address(new Try());
        console.log(t2);

        vm.stopBroadcast();
    }
}
```

**Comment by bbonanno** [comment]
I think this also needs the ability to link the same library to different addresses on a per chain basis

This would be also great for fork testing, as you most probably need to point your code to different instances of the library when you fork different networks

**Comment by rhlsthrm** [comment]
Is there any way to verify contracts with multiple API keys while deploying through this multi-chain strategy?
