### ISSUE TITLE
forge install incorrectly claims staged git

### ISSUE THREAD

**Issue by aathan** [foundry-rs/foundry#2525]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (028e888 2022-07-30T00:03:45.078239085Z)

### What command(s) is the bug in?

forge install

### Operating System

Linux

### Describe the bug

There are no staged files but forge install does not agree. Should it care about untracked files? If so, should the message it emits be different?

```
$ forge install https://github.com/OpenZeppelin/openzeppelin-contracts
Installing openzeppelin-contracts in "/somedir/lib/openzeppelin-contracts" (url: Some("https://github.com/OpenZeppelin/openzeppelin-contracts"), tag: None)
Error:
There are changes in your working/staging area. Commit them first or add the `--no-commit` option.
$ git status
On branch master
Untracked files:
   (use "git add <file>..." to include in what will be committed)
   ...various untracked files...

nothing added to commit but untracked files present (use "git add" to track)
```

**Comment by onbjerg** [comment]
The solution is presented to you: add the `--no-commit` flag. Untracked files will be affected by how committing works

**Comment by aathan** [comment]
Fair enough yes, "working/" is included in the message. Frankly, I thought that's probably an imprecise warning string in Foundry rather than believing its literal meaning that something about forge's "commit" behavior would care about un-staged un-tracked files in the working dirs. I.e., those are not really "changes" (vs potential new additions etc).

Perhaps a rewording of the message is warranted?

"This command requires clean working and staging areas, including no untracked files. Modify .gitignore and/or add/commit  first, or add the `--no-commit` option."
