### ISSUE TITLE
`recordLogs` cheatcode reverts with `Invalid data`

### ISSUE THREAD

**Issue by SamWilsn** [foundry-rs/foundry#2532]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (0e6c8fb 2022-05-21T03:23:31.545158869Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

Tried to record logs in a test, got this:

```
  [3008] ContractTest::testApprove()
    ├─ [0] VM::41af2f52()
    │   └─ ← 0x0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000c496e76616c696420646174610000000000000000000000000000000000000000
    └─ ← "Invalid data"
```

**Comment by mattsse** [comment]
> forge 0.2.0 (https://github.com/foundry-rs/foundry/commit/0e6c8fb0154b67e192bc5a358a9aef66a0846f33 2022-05-21T03:23:31.545158869Z)

could you please try with current nightly after running `foundryup`

**Comment by SamWilsn** [comment]
Yep, that was the problem.
