### ISSUE TITLE
Forge scripting doesn't detect max code size exceeded

### ISSUE THREAD

**Issue by 0xPhaze** [foundry-rs/foundry#2535]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9ed1c37 2022-08-01T00:09:10.803586Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

Foundry does not detect when contracts exceed the contract size limit when deploying to a live network. The transaction is sent nonetheless, but fails.
One might argue that this should be set by the user, however I do imagine this being problematic when deploying to mainnet.

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/103113487/182136968-eb6d8752-d523-4b1f-9518-68b4bdd12803.png">

**Comment by mejango** [comment]
same.

**Comment by onbjerg** [comment]
That warning (it's not an error) is ignored by default by `forge build` @joshieDo, but it makes sense to probably manually check it for forge script?
