### ISSUE TITLE
random `Revert` on multichain with latest nightly

### ISSUE THREAD

**Issue by sakulstra** [foundry-rs/foundry#2539]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

nightly-9ed1c37f49de428a3c653a343c3ffab0dd7c3790

### What command(s) is the bug in?

foundry test

### Operating System

Linux

### Describe the bug

I've been using foundries `createSelectFork` to create an E2E test including a bridge between mainnet on polygon.

When I use `nightly-028e8884a1319987db1b2d9672ebf4ef922a524b` everything works fine.
Once I switch to latest nightly `nightly-9ed1c37f49de428a3c653a343c3ffab0dd7c3790` the tests start to randomly fail.

The error is a bit weird as it seems to just happen randomly not related to s specific function call:
```sh
    ├─ [339] 0x1824…4f06::5c60da1b() 
    │   └─ ← 0x00000000000000000000000081387c40eb75acb02757c1ae55d5936e78c9ded3
    ├─ [339] 0x6878…b9c8::5c60da1b() 
    │   └─ ← 0x00000000000000000000000052a1ceb68ee6b7b5d13e0376a1e0e4423a8ce26e
    ├─ [0] VM::stopPrank() 
    │   └─ ← ()
    ├─ [306] MiMaticPayload::PRICE_FEED() [staticcall]
    │   └─ ← 0xd8d483d813547cfb624b8dc33a00f2fcbcd2d428
    └─ ← "EvmError: Revert"
```

I expect it to be somehow related to https://github.com/foundry-rs/foundry/commit/af3c9d3e53b8bc718d6f531a704d59d6cddaf032 can't pinpoint the exact issue though.

Here's a reproduction: https://github.com/bgd-labs/example-v3-bridge-listing (just run forge test on the two nightlies, latest one will fail)

**Comment by onbjerg** [comment]
It's probably related to how persistence changed recently: https://book.getfoundry.sh/forge/fork-testing#separated-and-persistent-storage

Does that section help you?

**Comment by sakulstra** [comment]
@onbjerg I think this is not related.

I adjusted the test so it passes on latest nightly: https://github.com/bgd-labs/example-v3-bridge-listing/blob/master/src/test/PolygonMiMaticE2E.t.sol#L182 (commenting out parts of the code).

It doesn't make sense that i fails though and it also doesn't fail on previous versions.
- the current fork selected is polygon: https://github.com/bgd-labs/example-v3-bridge-listing/blob/master/src/test/PolygonMiMaticE2E.t.sol#L116
- the addresses involved are either created on polygon https://github.com/bgd-labs/example-v3-bridge-listing/blob/master/src/test/PolygonMiMaticE2E.t.sol#L93 or constants
- a test interacting witht he same addresses a few lines before works https://github.com/bgd-labs/example-v3-bridge-listing/blob/master/src/test/PolygonMiMaticE2E.t.sol#L176

The error thrown doesn't contain any valuable infor to act upon I think - to me it's not clear at all where the revert is coming from as everything is `green`:
```sh
├─ [260] MiMaticPayload::ATOKEN_IMPL() [staticcall]
    │   └─ ← 0xa5ba6e5ec19a1bf23c857991c857db62b2aa187b
    ├─ [284] MiMaticPayload::SDTOKEN_IMPL() [staticcall]
    │   └─ ← 0x52a1ceb68ee6b7b5d13e0376a1e0e4423a8ce26e
    ├─ [305] MiMaticPayload::VDTOKEN_IMPL() [staticcall]
    │   └─ ← 0x81387c40eb75acb02757c1ae55d5936e78c9ded3
    ├─ [0] VM::startPrank(0x8145edddf43f50276641b55bd3ad95944510021e) 
    │   └─ ← ()
    ├─ [339] 0xebe5…775d::5c60da1b() 
    │   └─ ← 0x000000000000000000000000a5ba6e5ec19a1bf23c857991c857db62b2aa187b
    ├─ [339] 0x1824…4f06::5c60da1b() 
    │   └─ ← 0x00000000000000000000000081387c40eb75acb02757c1ae55d5936e78c9ded3
    ├─ [339] 0x6878…b9c8::5c60da1b() 
    │   └─ ← 0x00000000000000000000000052a1ceb68ee6b7b5d13e0376a1e0e4423a8ce26e
    ├─ [0] VM::stopPrank() 
    │   └─ ← ()
    ├─ [306] MiMaticPayload::PRICE_FEED() [staticcall]
    │   └─ ← 0xd8d483d813547cfb624b8dc33a00f2fcbcd2d428
    └─ ← "EvmError: Revert"
```

**Comment by sakulstra** [comment]
might be related to https://github.com/foundry-rs/foundry/issues/2549

**Comment by onbjerg** [comment]
Yes, #2549 is related to this as well. I'm pretty sure this is because of persistence, but I don't know enough about how it works to help you. cc @mattsse (also check out #2549)

**Comment by mattsse** [comment]
thanks for reporting @sakulstra , will investigate

**Comment by sakulstra** [comment]
@mattsse closing in favor of https://github.com/foundry-rs/foundry/issues/2549 - had to alter my code as there was some time pressure so to checkout the broken code it's no longer master but https://github.com/bgd-labs/aave-v3-bridge-listing-template/commit/2548d4be5eec6fc358cd14e0157ce024283bba17 

If interesting this is the change i needed to apply to make things work again https://github.com/bgd-labs/aave-v3-crosschain-listing-template/commit/580a3a578dbffc40955a71610f28fd8ecc00f77e (essentially making public methods internal)
