### ISSUE TITLE
`forge build` does not give the output needed to make progress

### ISSUE THREAD

**Issue by ehildenb** [foundry-rs/foundry#2540]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9ed1c37 2022-08-01T00:07:48.156201922Z)

### What command(s) is the bug in?

`forge build`

### Operating System

Linux

### Describe the bug

`forge build`, when remappings are not working, is not providing very helpful input on how to fix them.

Here is some sample interaction:

![Screenshot from 2022-08-01 09-59-16](https://user-images.githubusercontent.com/12721972/182190594-ce305aa2-6d6d-4c9a-ac1a-ff73f19f66fc.png)

Here, Foundry is telling me to "check configured remappings", but providing no concrete steps to take. At the very least, it could print out the file with the import that it's trying to resolve? Notice it's only printing out what it thinks is the resolved file directory, but not the actual file that the import came from.

**Comment by onbjerg** [comment]
Seems related to #2526 and is solved in ethers-rs now. The change will be reflected in Foundry when #2538 is merged

**Comment by ehildenb** [comment]
Thank you https://github.com/foundry-rs/foundry/issues/2526#issuecomment-1200307021 indeed seems to be the extra info I need!
