### ISSUE TITLE
More helpful output on test failure

### ISSUE THREAD

**Issue by ehildenb** [foundry-rs/foundry#2544]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9ed1c37 2022-08-01T00:07:48.156201922Z)

### What command(s) is the bug in?

`forge test`

### Operating System

Linux

### Describe the bug

I am writing some tests that use forking capabilities of Foundry.

My forking capability tests are broken, they aren't doing the right thing, and cause Foundry to panic.

![Screenshot from 2022-08-01 11-25-45](https://user-images.githubusercontent.com/12721972/182209623-79419323-bf33-4fc6-93fd-f3b859136650.png)

However, the last output before panicking is talking about my Prank tests, not about my Fork tests. But deleting the file `ForkTest.t.sol` causes the tests to be fine, so the problem is there (in the fork tests).

Can the output be made more helpful on panic? Maybe to say which test it's panicking on?

Attached is a zip directory this is happening in: 

[foundry.zip](https://github.com/foundry-rs/foundry/files/9237649/foundry.zip)

**Comment by onbjerg** [comment]
For now we'll try to improve the error messages, but we should also explore if we can avoid panicking by extending REVM's `Database` trait

**Comment by onbjerg** [comment]
This should now be handled more gracefully
