### ISSUE TITLE
Let deployment scripts support some kind of convenient deployment tracking/export facilities like `hardhat-deploy`

### ISSUE THREAD

**Issue by Gilgames000** [foundry-rs/foundry#2550]
### Component

Forge

### Describe the feature you would like

Hi! It would be cool if forge deployment scripts supported some kind of convenient deployment tracking/export facilities like [hardhat-deploy's export functionality](https://github.com/wighawag/hardhat-deploy#6-hardhat-export).

As of now, the data/state is already being tracked in `out/` and `broadcast/` indeed! But it's all scattered around. What hardhat-deploy's export does is aggregate the essential deployment data, for a specific chain or for all, into a single file. You can then just drop this json file in your web app and have access to all the deployed contracts' ABI and addresses on the specified chains. It's just kinda handy and easier to automate updates.

**Comment by tynes** [comment]
I was thinking of implementing this as part of https://github.com/foundry-rs/hardhat

A hardhat task that wraps `forge script` and then it would generate the hardhat deploy style artifacts. The idea is to make it easy to migrate from hardhat deploy to forge script

**Comment by ind-igo** [comment]
Would be awesome! I wrote this discussion post months ago but got busy with work obligations, but this should definitely be pursued. https://github.com/foundry-rs/foundry/discussions/114

**Comment by PierrickGT** [comment]
> I was thinking of implementing this as part of https://github.com/foundry-rs/hardhat
> 
> A hardhat task that wraps `forge script` and then it would generate the hardhat deploy style artifacts. The idea is to make it easy to migrate from hardhat deploy to forge script

@tynes are you still working on implementing this feature? It would indeed be super useful!

**Comment by tynes** [comment]
No, i've decided that its not the ideal approach and instead opened this issue https://github.com/foundry-rs/foundry/issues/3911

Would rather have a higher level `deploy` command built into forge itself instead of hacking the hh plugin to work

**Comment by mds1** [comment]
Any objections to closing this in favor of #3911 as the canonical issue to spec out some higher-level functionality over `forge script`? I think one issue to discuss such a feature makes it easier to keep track of things
