### ISSUE TITLE
Anvil returning "unable to complete request" when called from bash script.

### ISSUE THREAD

**Issue by harsh-98** [foundry-rs/foundry#2558]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (028e888 2022-07-30T00:12:28.524716Z)

### What command(s) is the bug in?

./foundry/anvil -f $1 --fork-block-number $2 

### Operating System

macOS (Apple Silicon)

### Describe the bug

Getting `Fork Error: JsonRpcClientError(ProviderError(JsonRpcError(JsonRpcError { code: -32000, message: "Unable to complete request at this time.", data: None })))` error for some of the requests. This only happens when the anvil binary is run in the bash script. 

When run in 2 separate terminals, it is working as expected. And this is happening every single time. 

Another thing to note, it is always failing for the same RPC query. All other queries are returning responses as expected.

**Comment by mattsse** [comment]
this looks like an issue with the provider used for forking

can you share some details please,

what's the query?
what's the bash script doing, launching anvil or executing the request?
can you share the command?

**Comment by harsh-98** [comment]
You are indeed right. I tried with infura and it worked. 
It was failing with alchemy. So, I checked if the quota for queries per minute was causing this or if some requests were failing. But on the alchemy dashboard, there aren't any errors and all requests are passing as usual.
Thanks again.

**Comment by mattsse** [comment]
could just be a flake on alchemy's side
