### ISSUE TITLE
Customize delay in `forge script`

### ISSUE THREAD

**Issue by adhusson** [foundry-rs/foundry#2565]
### Component

Forge

### Describe the feature you would like

`forge script` waits 7 seconds by default before asking for transaction receipts. It is not a good initial value for running tests since a local anvil node will be able to respond right away.

Adding `--delay` parameter would do the trick. I was told that by default the delay is 100ms when the node is `localhost`, which I think comes from [these lines in anvil/src/lib.rs](https://github.com/foundry-rs/foundry/blob/8016f26e160cb574c8c4f6e97d76e1386f956902/cli/src/utils.rs#L211-L213). But what I'm talking about seems more related to the definition of [PendingTransaction](https://github.com/gakonst/ethers-rs/blob/master/ethers-providers/src/pending_transaction.rs#L73) and [DEFAULT_POLL_INTERVAL](https://github.com/gakonst/ethers-rs/blob/master/ethers-providers/src/stream.rs#L29). I don't know Rust at all though so I may be totally off. 

An alternative solution would be to effectively implement the "100ms delay in forge script for localhost" rule.

**Comment by onbjerg** [comment]
This is going to be solved by #2559 but will not include user config (the poll interval will be lowered for dev nodes though)

**Comment by onbjerg** [comment]
This is now handled automatically
