### ISSUE TITLE
Fork test support set transaction index

### ISSUE THREAD

**Issue by kaolula** [foundry-rs/foundry#2569]
### Component

Forge

### Describe the feature you would like

I very like foundry,debug solidity is very great,but when i want to debug solidity behind a transaction,I didn't find a way to achieve.

Now
```
 forge test --match-path test/Cool.t.sol -vv --fork-url=XXX --fork-block-number 15223111
```
Expectation
```
 forge test --match-path test/Cool.t.sol -vv --fork-url=XXX --fork-block-number 15223111  --tx-index 10
```

**Comment by onbjerg** [comment]
Duplicate of https://github.com/foundry-rs/foundry/issues/2191
