### ISSUE TITLE
Fuzz input error on int128

### ISSUE THREAD

**Issue by moose-code** [foundry-rs/foundry#2570]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (01325bc 2022-08-03T00:04:34.894101923Z)

### What command(s) is the bug in?

forge test -vv

### Operating System

Linux

### Describe the bug

![image](https://user-images.githubusercontent.com/20556729/182557406-d141d77e-4a7d-4a35-a8c3-c7a97f7c9450.png)
The fuzzer is giving an input of 170141183460469231731687303715884105728 for the int128 field (counter example taken from a fuzz test in our pipeline) but the max value for a int128 is 170141183460469231731687303715884105727.

Think this may be related to #2560

**Comment by onbjerg** [comment]
Closing as a duplicate of #2560, but thank you for the extra context! It does indeed seem like the new signed int strategy goes out of bounds if you use anything that is not int256
