### ISSUE TITLE
Setting `--fuzz-seed` does not fix gas consumption of fuzzing tests

### ISSUE THREAD

**Issue by Rubilmax** [foundry-rs/foundry#2571]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (01325bc 2022-08-03T00:04:34.894101923Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

given the following simple test case:

```solidity
function testFuzz(uint256 a) public {
    if (a % 3 == 0) a / 2;
    else if (a % 3 == 1) a - 1;
    else console.log("test");
}
```

Running `forge test --gas-report --fuzz-seed 0` gives non-deterministic gas consumption:
```
> forge test --gas-report --fuzz-seed 0
[PASS] testFuzz(uint256) (runs: 256, μ: 1609, ~: 410)
> forge test --gas-report --fuzz-seed 0
[PASS] testFuzz(uint256) (runs: 256, μ: 1097, ~: 410)
> forge test --gas-report --fuzz-seed 0
[PASS] testFuzz(uint256) (runs: 256, μ: 1305, ~: 497)
```

Wouldn't the expected behavior be the following: given a fuzzing seed, fuzzing inputs are deterministically chosen and thus fuzzing test cases are always run in the same order, which (given a constant start state) leads to the same gas consumption?

**Comment by onbjerg** [comment]
Please open up a separate feature request for the sidenote so we can track separately

**Comment by mattsse** [comment]
with `--fuzz-seed` the fuzzer generates determinist values, just confirmed this manually.

without the console.log the avg gas consumption stays constant, need to check why the median varies.

**Comment by onbjerg** [comment]
unsure, it should be the exact same given the same inputs. not sure what would vary since each fuzz test should have its own db and each tx is executed serially :thinking: will check it out

**Comment by mattsse** [comment]
I basically compared all gas values in

https://github.com/foundry-rs/foundry/blob/af3c9d3e53b8bc718d6f531a704d59d6cddaf032/evm/src/fuzz/mod.rs#L224

and there some differences from run to run for

```solidity
    function testFuzz(uint256 a) public {
        if (a % 3 == 0) {
            a / 2;
        } else if (a % 3 == 1) {
            a - 1;
        }
    }
```

however the input values are always consistent with fuzz seed

**Comment by mattsse** [comment]
interesting, I dumped all uint values the strategy and they were always identical

oh I must have made an error somewhere because my uint256 dump only has 153 values which is ofc less than the default 256

**Comment by onbjerg** [comment]
oh! you probably dumped them in one of the two strategies. there's one that generates values and then there's one that picks random values from state. I have a hunch the state one is messing up. do you remember where you logged?

**Comment by mattsse** [comment]
yeh 
in this closure here

https://github.com/foundry-rs/foundry/blob/723536fb5ae0f11c8ffc9f7d80e196ee7744e0b6/evm/src/fuzz/strategies/param.rs#L27
