### ISSUE TITLE
int96 fuzzing support

### ISSUE THREAD

**Issue by 0xdavinchee** [foundry-rs/foundry#2572]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (01325bc 2022-08-03T00:04:48.802271Z)

### What command(s) is the bug in?

export FOUNDRY_FUZZ_RUNS=10000 && forge test --match testInt96 -vvvvv

### Operating System

macOS (Apple Silicon)

### Describe the bug

I have recently encountered an issue with fuzzing int96 parameters, our current workaround is using int256 and bounding it between the min and max values of int96.

In a newly initialized `forge init`. 
Added a function in `Contract.t.sol`:
`function testInt96(int256 flowRate) public {}`

Ran: `export FOUNDRY_FUZZ_RUNS=10000 && forge test --match testInt96 -vvvvv`

Error: 
```
[FAIL. Reason: EvmError: Revert. Counterexample: calldata=0x9fb3171a0000000000000000000000000000000000000000800000000000000000000000, args=[39614081257132168796771975168]] testFlowDataEncoding(int96) (runs: 438, μ: 276, ~: 276)
Traces:
  [238] ConstantFlowAgreementV1Properties::testFlowDataEncoding(39614081257132168796771975168)
    └─ ← "EvmError: Revert"

Test result: FAILED. 0 passed; 1 failed; finished in 18.07ms

Failed tests:
[FAIL. Reason: EvmError: Revert. Counterexample: calldata=0x9fb3171a0000000000000000000000000000000000000000800000000000000000000000, args=[39614081257132168796771975168]] testFlowDataEncoding(int96) (runs: 438, μ: 276, ~: 276)
```

**Comment by onbjerg** [comment]
Duplicate of #2560
