### ISSUE TITLE
Formatting of the comment of the first member of a struct is badly indented

### ISSUE THREAD

**Issue by CodeSandwich** [foundry-rs/foundry#2573]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (01325bc 2022-08-03T00:04:34.894101923Z)

### What command(s) is the bug in?

forge fmt

### Operating System

Linux

### Describe the bug

After running `forge fmt` the comment of the first members of a struct is always one indentation too shallow:
```solidity
    struct MyStruct {
    // first 1
    // first 2
        uint256 field1;
        // second
        uint256 field2;
    }
```
It doesn't matter if the comment is single- or multi-line, the entire comment has invalid indentation. All the following fields are correctly indented.

**Comment by onbjerg** [comment]
@rkrasiuk / @jpopesculian was this fixed recently?

**Comment by rkrasiuk** [comment]
nope, it wasn't. just tested on latest release, issue's still there
