### ISSUE TITLE
Fmt removes underscores from number literals

### ISSUE THREAD

**Issue by CodeSandwich** [foundry-rs/foundry#2574]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (01325bc 2022-08-03T00:04:34.894101923Z)

### What command(s) is the bug in?

forge fmt

### Operating System

Linux

### Describe the bug

After running `forge fmt` all underscores are erased from number literals. E.g.
```solidity
uint256 million = 1_000_000;
```
is formatted into
```solidity
uint256 million = 1000000;
```
which degrades readability.

**Comment by mattsse** [comment]
cc @rkrasiuk @jpopesculian

**Comment by onbjerg** [comment]
@rkrasiuk feel free to ping me or open an issue in the book if you add more config stuff so we can ensure that part is updated, still need to write formatter chapter other than that
