### ISSUE TITLE
Read an environment variable to define `--fuzz-seed` default value

### ISSUE THREAD

**Issue by Rubilmax** [foundry-rs/foundry#2577]
### Component

Forge

### Describe the feature you would like

Hi!

It would be handy to be able to tweak `--fuzz-seed` via an environment variable, for example `FOUNDRY_FUZZ_SEED` (matching foundry's environment variable naming convention)

**Comment by mattsse** [comment]
this should work by default

in fact 

`FOUNDRY_FUZZ_SEED=100 forge config`

gives

```
fuzz_seed = '0x64'
```

**Comment by Rubilmax** [comment]
Checked and confirmed, sorry for the inconvenience. I think I concluded this was not working because of gas reports being non-deterministic when fuzz seed is constant (cf. #2571)
