### ISSUE TITLE
Print unit names in `forge test` failures report

### ISSUE THREAD

**Issue by gas1cent** [foundry-rs/foundry#2581]
### Component

Forge

### Describe the feature you would like

We have multiple test cases with the same name but in different units. Typical examples:
- testEmitEvent
- testRevertIfPaused

When a test with a "popular" name fails, it's not immediately obvious what unit we should look at, so the next step after encountering the failure is almost always `forge test --match-test`. I would like to see the unit name in the output instead, for instance:
> [FAIL. Reason: Log != expected log. Counterexample: calldata=0xe3ea2b1d0000000000000000000000000000000000000000000000000000000000800000, args=[8388608]] UnitDeploySomething.testEmitEvent(int24) (runs: 10, μ: 89131, ~: 50072)

Please consider adding this. Thank you 🌈

### Additional context

#2328 might help too.

**Comment by onbjerg** [comment]
It prints the unit name at the top of the report. E.g.:

```
Running 7 tests for src/test/WETH.t.sol:WETHTest
[PASS] testDeposit() (gas: 63535)
[PASS] testDeposit(uint256) (runs: 256, μ: 48079, ~: 65880)
[PASS] testFallbackDeposit() (gas: 63249)
[PASS] testFallbackDeposit(uint256) (runs: 256, μ: 45623, ~: 65604)
[PASS] testPartialWithdraw() (gas: 73281)
[PASS] testWithdraw() (gas: 54360)
[PASS] testWithdraw(uint256,uint256) (runs: 256, μ: 56533, ~: 78076)
Test result: ok. 7 passed; 0 failed; finished in 216.11ms
```

Is this specifically about the summary of the failed tests or do you want the output to be different entirely?

**Comment by gas1cent** [comment]
I see what you mean. The output forge prints while running the tests indeed mentions the units. What I refer to is the final output that we get if there is a failure:
![Screen Shot 2022-08-04 at 21 41 05](https://user-images.githubusercontent.com/86567384/182915771-7d6acfd9-50e0-4a37-88cc-7c3d846ad7ce.png)

So if there are a few hundred tests in a dozen contracts and you got a failure early on, you would need to scroll all the way up in order to find the failing unit. Ctrl+f is not super effectie in that case because as I mentioned before, we tend to have similar names for tests that assert similar things. I hope this makes sense and sheds some light on the use case. Thanks again.
