### ISSUE TITLE
Cannot check balance

### ISSUE THREAD

**Issue by bitcoinmeetups** [foundry-rs/foundry#2585]
cast balance 0x02E4b884Df5bB66B13bf7B04a957F45acF39025F
Error:
error sending request for url (http://localhost:8545/): error trying to connect: tcp connect error: Connection refused (os error 111)

Context:
- Error #0: error trying to connect: tcp connect error: Connection refused (os error 111)
- Error #1: tcp connect error: Connection refused (os error 111)
- Error #2: Connection refused (os error 111)

**Comment by onbjerg** [comment]
You need to specify an RPC URL, i.e. a URL to an Ethereum node. You can either specify it like this:

```
cast balance 0x02E4b884Df5bB66B13bf7B04a957F45acF39025F --rpc-url <url here>
```

Or by setting the `ETH_RPC_URL` environment variable :)
