### ISSUE TITLE
`forge script`: contractName is not filled in broadcast logs

### ISSUE THREAD

**Issue by adhusson** [foundry-rs/foundry#2593]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (01325bc 2022-08-03T00:04:48.802271Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

1. Create new project with `forge init`.
2. Add `import "src/Contract.sol"` and add `new Contract()` in `script/Contract.s.sol`.
3. Run `anvil`
4. Run `forge script --rpc-url http://127.0.0.1:8545 --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --broadcast ContractScript`
5. Check that in `broadcast/Contract.sol/31337/run-latest.json`, `contractName` fields are `null`.

**Comment by onbjerg** [comment]
The contract is too similar to other contracts in the project since it has almost no code, making it hard to figure out what contract it is. Try adding some stuff in your contract and it should work :)

**Comment by adhusson** [comment]
I just changed the code (see below) and contractName is still null.

```solidity
contract Contract {
  uint x;
  address y;
  constructor() {
    x = 32131902381203;
  }
  function setAddress(address _y) public {
    y = _y;
  }
  function getAddress() public returns (address) {
    return y;
  }
}
```

**Comment by adhusson** [comment]
update after talking with @joshieDo: adding `-vvvv` fixes the issue.

**Comment by gakonst** [comment]
Oh I see. So we were not detecting the contract name if not in verbose mode?

**Comment by joshieDo** [comment]
Yeah, we're getting that kind of information from the traces (which requires verbose mode). Although not mentioned here, `function` fields are also `null` as a consequence.

We could get the local contract names by looking into the  `StateChangeSet`. However, we still wouldn't be able to get external contract names and functions without looking into the traces.
