### ISSUE TITLE
`forge fmt` introduces trailing whitespace in multiline comments

### ISSUE THREAD

**Issue by hansbergren** [foundry-rs/foundry#2597]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (01325bc 2022-08-03T00:04:48.802271Z)

### What command(s) is the bug in?

forge fmt

### Operating System

macOS (Apple Silicon)

### Describe the bug

I would expect this block comment to be formatted as shown:
```
    /**
     * Does this add a whitespace error?
     *
     * Let's find out.
     */
```

However, when I run `forge fmt`, it adds a trailing whitespace behind the middle asterisk:
```diff
    /**
     * Does this add a whitespace error?
-    *
+    *  
     * Let's find out.
     */
 ```
 
 `git` warns me that this is a whitespace error.
 
 Happy to contribute a PR if I'm pointed to the relevant code.

**Comment by mattsse** [comment]
closed by #2600
