### ISSUE TITLE
Mean is panicking on empty arrays

### ISSUE THREAD

**Issue by Rubilmax** [foundry-rs/foundry#2611]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9b0575e 2022-08-04T00:04:01.463358166Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

In [calc.rs#L12](/foundry-rs/foundry/tree/master/common/src/calc.rs#L12), this fix should be applied:

```diff
pub fn mean<T>(values: &[T]) -> U256
where
    T: Into<U256> + Copy,
{
-    values.iter().copied().fold(U256::zero(), |sum, val| sum + val.into()) / values.len();
+    let len = values.len();
+    if len > 0 {
+        values.iter().copied().fold(U256::zero(), |sum, val| sum + val.into()) / len
+    } else {
+        U256::zero()
+    }
}
```

**Comment by Rubilmax** [comment]
Is it possible to have write permission on side branches, so I could submit Pull Requests?

**Comment by onbjerg** [comment]
Not sure what you mean? Anyone can submit a pull request
