### ISSUE TITLE
Bug found when doing forge build

### ISSUE THREAD

**Issue by JJtheAndroid** [foundry-rs/foundry#2626]
forge build
foundry config error: no prefix found in Remapping Provider
The application panicked (crashed).
Message:  failed to extract foundry config
Location: config\src\lib.rs:415

This is a bug.

**Comment by mattsse** [comment]
thanks!

could please add the contents of `remappings.txt` and `foundry.toml` if you have them

does this happen in a specific project?

**Comment by JJtheAndroid** [comment]
It seems that if I create a remappings.txt before installing dependencies, the bug appears. This was my remappings.txt

@openzeppelin/=lib/openzeppelin-contracts/

**Comment by onbjerg** [comment]
Can you still provide the full `foundry.toml`, `remappings.txt` and the command you issued? Otherwise it is going to be hard for us to reproduce unfortunately

**Comment by onbjerg** [comment]
The error message has been improved, since we can't reproduce we will close this issue, but feel free to ping if the issue persists!
