### ISSUE TITLE
Cheatcode `vm.setNonce` does not allow for a nonce value of `type(uint64).max`

### ISSUE THREAD

**Issue by pcaversaccio** [foundry-rs/foundry#2628]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (0dc266d 2022-08-05T00:05:53.884289904Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

The cheatcode `vm.setNonce` does not allow for a nonce value of `type(uint64).max`. It's the max threshold that is actually allowed in theory. If I substract 1 from the max value it works smoothly. Maybe there are some internal reasons for that but I thought I would quickly raise the issue.

![image](https://user-images.githubusercontent.com/25297591/183027642-a92f3b82-4333-4f0c-a776-6a1cd202342d.png)

EDIT: The screenshot is from using the Windows version (built from source) but usually I use WSL Ubuntu for foundry and also there is the same error.

**Comment by mattsse** [comment]
this happens because the vm increases the nonce here

https://github.com/bluealloy/revm/blob/77487187521ca920b4078b1a908b2630e3ee2818/crates/revm/src/subroutine.rs#L179

@onbjerg I think we should just reject a nonce of u64::MAX, as this isn't a realistic scenario anyways

**Comment by pcaversaccio** [comment]
I would appreciate not rejecting `u64::MAX` since I actually have a test against this (RLP encoding scheme for address computation via `CREATE`). The theoretical limit given by clients is `type(uint64).max`. That's why I test it.

**Comment by mattsse** [comment]
wait, did you run this in release mode or debug?

**Comment by mds1** [comment]
> I would appreciate not rejecting `u64::MAX` since I actually have a test against this (RLP encoding scheme for address computation via `CREATE`). The theoretical limit given by clients is `type(uint64).max`. That's why I test it.

If the cheatcode rejects a value of `u64::MAX`, you could set the nonce to `u64::MAX - 1` then send a tx to bump the nonce to `u64::MAX`. (I have no preference on the resolution of this issue, just throwing out an idea that may help 🙂)

**Comment by pcaversaccio** [comment]
in release mode. @mds1 I'm currently using this approach here already: https://github.com/pcaversaccio/snekmate/blob/main/test/utils/CreateAddress.t.sol#L218. I mean obviously, it's an edge case, but if you check the other tests for `uint56` etc. you will see why I encountered it. I want to test the RLP encoding scheme against the uint64 max value.

**Comment by pcaversaccio** [comment]
@mattsse yes exactly - you can clone my repo and remove the `-1` and you will see it. I mean I can live with the current solution but to make everything exact we would need probably need a cleanup hook somehow.

**Comment by mattsse** [comment]
ok, I finally read the example contract.
you set the nonce of `create` to max and then deploy with that address?

**Comment by pcaversaccio** [comment]
yes: I have [function](https://github.com/pcaversaccio/snekmate/blob/main/src/utils/CreateAddress.vy#L34) that computes the address (based on the nonce & address) and I compare this against the deployed contract address. The RLP encoding is different, given the nonce byte length.

**Comment by mattsse** [comment]
finally managed to get python+vyper installed properly

I wish for once in my life I could get Python to work right away -.-

I wasn't able to reproduce this with a `--release` build but could reproduce with debug:


```console
forge test -m testComputeAddressNonceUint64 -vvv --ffi                                                                                      ! main 
[⠢] Compiling...
[⠢] Compiling 24 files with 0.8.15
[⠔] Solc 0.8.15 finished in 5.09s
Compiler run successful

Running 1 test for test/utils/CreateAddress.t.sol:CreateAddressTest
[PASS] testComputeAddressNonceUint64() (gas: 738242)
Test result: ok. 1 passed; 0 failed; finished in 1.05s
                                                                                                                                                      
~/git/rust/foundry-integration-tests/testdata/snekmate  v18.7.0
❯ ~/git/rust/foundry/target/debug/forge test -m testComputeAddressNonceUint64 -vvv --ffi                                                      ! main 
[⠊] Compiling...
[⠃] Compiling 24 files with 0.8.15
[⠢] Solc 0.8.15 finished in 5.07s
Compiler run successful
The application panicked (crashed).
Message:  attempt to add with overflow
Location: /Users/Matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/revm-1.8.0/src/subroutine.rs:179

```

the reason for this is that rust's primitive types don't overflow in release mode, instead they wrap.
only in debug mode an overflow results in a panic, which happens here

https://github.com/bluealloy/revm/blob/77487187521ca920b4078b1a908b2630e3ee2818/crates/revm/src/subroutine.rs#L179

check this minimal example

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=16c9e6288f5c7887d730e8ba651221d6

and compare `DEBUG` `RELEASE` toggle

so this overflow shouldn't happen with a release build


can you try with forge from foundryup?

**Comment by pcaversaccio** [comment]
you are completely right - problem is that I use for Windows a built from source while for WSL I use the `foundryup` version. Is there I fast way to get the `foundryup` version on Windows instead of building from source?

**Comment by mds1** [comment]
Wait, is a nonce of `type(uint64).max` even allowed? Seems like no based on https://eips.ethereum.org/EIPS/eip-2681:

> Consider any transaction invalid, where the nonce exceeds or equals to `2^64-1`.

So @pcaversaccio I don't think you need to even handle/test that case, since it can never occur

**Comment by pcaversaccio** [comment]
@mds1 you are right: 
![image](https://user-images.githubusercontent.com/25297591/183120897-436dd8a9-e0b4-4abf-8d98-643f2413b7b3.png)

interesting - in Geth they define it as `uint64`: https://github.com/ethereum/go-ethereum/blob/master/core/types/transaction.go#L280

Maybe they have someone else a check for that equality.

**Comment by pcaversaccio** [comment]
awesome thx - so I think we can close that issue @mattsse?

**Comment by mattsse** [comment]
yeh let's close.

re static builds for windows, not sure if we ship them yet, cc @onbjerg

**Comment by onbjerg** [comment]
We do, foundryup just doesn't install them for you
