### ISSUE TITLE
Auto dep install breaks build

### ISSUE THREAD

**Issue by tynes** [foundry-rs/foundry#2633]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (0dc266d 2022-08-05T00:05:53.884289904Z)

### What command(s) is the bug in?

forge build

### Operating System

Linux

### Describe the bug

Attempting to auto install packages that are not autodetected is breaking our CI build (introduced in https://github.com/foundry-rs/foundry/commit/54191b6aada33a8a7c3593d135caa8179f167855). Since it is a monorepo, we use github refs with commit hashes in the `package.json` to manage the solidity dependencies. We install all of the dependencies first and then when running build, it says that it detects missing dependencies and then fails. I believe that the failure may be due to `git` not being installed on the machine in CI, but the dependencies were installed via `yarn` so I feel like it shouldn't try to install them.

Is there any way that we could make this a configurable feature?

**Comment by mattsse** [comment]
@onbjerg I think we need to make `has_missing_dependencies` a bit smarter:

https://github.com/foundry-rs/foundry/commit/54191b6aada33a8a7c3593d135caa8179f167855#diff-584cf95bca62c6fe76e213c6d050986d08a053a64fb8363ebd0dabf53ebab0afR151

rn it only checks submodule status, but there could be any kind of submodule.

`-6458fb2780a3092bc756e737f246be1de6d3d362 lib/solidity-bytes-utils`

it should check that `lib/solidity-bytes-utils` is in lib folder

also should bypass this if git is not available I think

**Comment by tynes** [comment]
Note that the problem does not appear to be fixed by installing `git`

```
Error: 
Your project has missing dependencies that could not be installed. Please ensure git is installed and available.

Context:
- error: pathspec '/home/circleci/project/packages/contracts-bedrock/lib' did not match any file(s) known to git
```

https://app.circleci.com/pipelines/github/ethereum-optimism/optimism/5504/workflows/c88477f9-4eed-47ae-a9b4-76221d63d989/jobs/91359

**Comment by mattsse** [comment]
can you try to rerun with #2634

`foundryup --pr 2634` 

hope that works in circle

**Comment by tynes** [comment]
Thank you for the quick fix! :) Am running in CI, will report back the results

**Comment by tynes** [comment]
This does fix the problem - https://github.com/ethereum-optimism/optimism/pull/3182

Perhaps this should still be behind a feature flag as to cases where dep detection doesn't work and git is installed?

**Comment by mattsse** [comment]
yeah this should be skippable or not hard error and warn instead
