### ISSUE TITLE
Unrecognized token

### ISSUE THREAD

**Issue by bitcoinmeetups** [foundry-rs/foundry#2641]
This input:

cast call 0x02E4b884Df5bB66B13bf7B04a957F45acF39025F "balanceOf()(0x92c819e24Cb020e35Fce434a3
3E39Fd5C85AB2aA)" --rpc-url https://polygon-mainnet.g.alchemy.com/v2/NDF-tLzxxxxxxxx

Generates this error message:

Error: UnrecognisedToken 12:54 0x0x92c819e24Cb020e35Fce434a33E39Fd5C85AB2aA

Removing the initial 0x from the input also doesn't work

**Comment by bitcoinmeetups** [comment]
The goal is to check the balance of Astral at that specific address

**Comment by bitcoinmeetups** [comment]
The goal is to check the balance of Astral at that specific address

**Comment by iFrostizz** [comment]
From the book:
https://book.getfoundry.sh/reference/cast/cast-call#examples

Not sure why you are adding parenthesis, and the balanceOf layout seems to be wrong

**Comment by bitcoinmeetups** [comment]
I think someone suggested that I should try that syntax for the input before. And I think that the other ways of inputting also don't work. I will test it again with some other ways as soon as possible and I will let you know if it worked or not.

In general, I find that many of the examples in the book actually don't work in reality. Plus the basic stuff that everyone needs are not listed on the first page but hidden somewhere deep in the book.

Anyway I will test again soon. But I think it doesn't work even if I put the address in the first parenthesis and uint256 in the second one. I think I have tried that already but I will check again.

**Comment by bitcoinmeetups** [comment]
Is this how you mean?

cast call 0x02E4b884Df5bB66B13bf7B04a957F45acF39025F "balanceOf(0x92c819e24Cb020e35Fce434a33E
39Fd5C85AB2aA)(uint256)" --rpc-url https://polygon-mainnet.g.alchemy.com/v2/NDF-txxxxxxxx

This input also generates: unrecognized token. But the syntax seems identical to the example in the book to me. 0x92etc is the contract address.

**Comment by bitcoinmeetups** [comment]
Is this how you mean?

cast call 0x02E4b884Df5bB66B13bf7B04a957F45acF39025F "balanceOf(0x92c819e24Cb020e35Fce434a33E
39Fd5C85AB2aA)(uint256)" --rpc-url https://polygon-mainnet.g.alchemy.com/v2/NDF-txxxxxxxx

This input also generates: unrecognized token. But the syntax seems identical to the example in the book to me. 0x92etc is the contract address.

**Comment by bitcoinmeetups** [comment]
Swapping the contract address and the account address around also generates the same error message: unrecognized token or unrecognized token 0x0xetc. Removing the initial 0x doesn't seem to work.

**Comment by iFrostizz** [comment]
No, like
`cast call 0x02E4b884Df5bB66B13bf7B04a957F45acF39025F "balanceOf(address)(uint256)" 0x92c819e24Cb020e35Fce434a33E39Fd5C85AB2aA --rpc-url https://polygon-mainnet.g.alchemy.com/v2/NDF-txxxxxxxx`

**Comment by bitcoinmeetups** [comment]
cast call 0x02E4b884Df5bB66B13bf7B04a957F45acF39025F "balanceOf(address)(uint256)" 0x92c819e2
4Cb020e35Fce434a33E39Fd5C85AB2aA --rpc-url https://polygon-mainnet.g.alchemy.com/v2/NDF-tLz0xxxxx

That gives this error message:

Error:                                                                                       could not decode output. did you specify the wrong function return data type perhaps?                                                                                                     Context:                                                                                     - Invalid name: please ensure the contract and method you're calling exist! failed to decode empty bytes. if you're using jsonrpc this is likely due to jsonrpc returning `0x` in case contract or method don't exist

**Comment by iFrostizz** [comment]
You swapped the contract and the EOA address.

```cast call 0x92c819e24Cb020e35Fce434a33E39Fd5C85AB2aA "balanceOf(address)(uint256)" 0x02E4b884Df5bB66B13bf7B04a957F45acF39025F --rpc-url https://polygon-mainnet.g.alchemy.com/v2/NDF-txxxxxxxx```

**Comment by bitcoinmeetups** [comment]
Hi, found it. It wasn't about the swapped address, at least not only. I remembered that error message from somewhere and it's because the alchemy rpc is not always reliable. In the end I got it to work like this:

cast call 0x92c819e24Cb020e35Fce434a33E39Fd5C85AB2aA "balanceOf(address)(uint256)" 0x02E4b884
Df5bB66B13bf7B04a957F45acF39025F --rpc-url https://polygon-rpc.com

So basically CAST - CALL - CONTRACT ADDRESS - FUNCTION NAME - ACCOUNT ADDRESS - RPC

Polygon-rpc seems most reliable at the moment. 

Thanks for the help and feedback : )

**Comment by onbjerg** [comment]
Closing since it is solved.

**Comment by Madgeniusblink** [comment]
Hey guys I am getting a similar error

cast send --private-key $PRIVATE_KEY $CONTRACT "mint(address,uint256,uint256,bytes)(0xDF5D99a96ad05C7DCFb8f83F1aAe14D6039e16D4, 1, 1, '0x')" --rpc-url $MUMBAI_RPC_URL
Error: 
UnrecognisedToken 36:78 `0x0xDF5`

any ideas?
