### ISSUE TITLE
`forge inspect --help` does not list fileds

### ISSUE THREAD

**Issue by Sabnock01** [foundry-rs/foundry#2650]
### Component

Forge

### Describe the feature you would like

When running `forge inspect --help` it would be nice to see a list of the available fields that can be used without having to check [this page in the book](https://book.getfoundry.sh/reference/forge/forge-inspect)

Is there a particular reason why they're not included? I would like to try to work on it and submit the PR myself if there's no issue.

**Comment by mattsse** [comment]
no reason,

could be added easily
