### ISSUE TITLE
Anvil is freeze when running in sub process

### ISSUE THREAD

**Issue by kubmichael** [foundry-rs/foundry#2652]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### Operating System

Linux

### Describe the bug

I have code that is trying to run anvil fork as separate process, I am running this code from inside Docker. My problem is that anvil is freeze (most of the time is freeze on evm_mine command), when I am trying to run same code without docker, for example at Mac, anvil is working as expected.

For building docker image I tried to use compiled binaries from official foundry docker image or to build it by myself in similar way as here [link]( https://github.com/foundry-rs/foundry/blob/master/Dockerfile)

Thanks

**Comment by mattsse** [comment]
there was a fix that's probably related https://github.com/foundry-rs/foundry/pull/2648
which will land in the next nightly docker build.
could you please try again once it's build

**Comment by kubmichael** [comment]
> Can you provide a bit more context on how you spawn Anvil and what RPC request(s?) that trigger a freeze? Also, how do you know it froze?

I am running anvil something like this: ./anvil --port .... &
I have test script, I used it for tests with hardhat, now I want to migrate, when I am  running it against anvil in docker, script stop and also anvil stop to log things, script is falling with error code=TIMEOUT, version=web/5.6.1

**Comment by kubmichael** [comment]
> there was a fix that's probably related #2648 which will land in the next nightly docker build. could you please try again once it's build

I took latest and my tests passed, thanks for help, closing issue
