### ISSUE TITLE
Support auto installing new solc 0.8.16 

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#2662]
### Component

Forge

### Describe the feature you would like

this problem is just a precaution to show that we are aware of the new version 0.8.16, which has to be created manually for M1 and then merged via `svm-rs` -> `ethers-solc` -> `foundry`

ref needs https://github.com/roynalnaruto/svm-rs/issues/58

cc @roynalnaruto

**Comment by roynalnaruto** [comment]
- [ ] solc-builds: https://github.com/roynalnaruto/solc-builds/commit/c69b85eb8a997d03861206290c2d7ebd113e9f02
- [ ] svm-rs: https://github.com/roynalnaruto/svm-rs/pull/57
- [ ] ethers-solc: https://github.com/gakonst/ethers-rs/pull/1579

**Comment by hansbergren** [comment]
Is this in the latest nightly? I'm still getting an error when trying to compile `0.8.16` (even though `0.8.16` is actually installed on my local machine).

```
❯ forge build
[⠊] Compiling...
[⠑] installing solc version "0.8.16"
[⠘] Failed to install solc 0.8.16: Unknown version provided
Error:
Unknown version provided

❯ svm list
0.8.16 (current)

Installed Versions
0.8.15
0.8.16
```

**Comment by mattsse** [comment]
Could you please check that forge --version matches todays date

If this is indeed happening with current nightly please open a new issue with your OS
