### ISSUE TITLE
`forge test` fail on tests that run `create2`

### ISSUE THREAD

**Issue by ryanli-me** [foundry-rs/foundry#2665]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (63ed109 2022-08-09T00:20:50.211015Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

The same test script has been running fine in CI until the CI picked up a new version of foundry last Wednesday that broke tests that cover code with `create2`. The code after `create2` are not run and the test shows a large gas usage. 

<img width="227" alt="CleanShot 2022-08-08 at 20 30 58@2x" src="https://user-images.githubusercontent.com/5056640/183557971-dbeb89fe-8cb2-49cf-8890-5ece240d47a6.png">

**Comment by gakonst** [comment]
Can you please give an example?

**Comment by ryanli-me** [comment]
Hey @gakonst, I did some digging, our test broke 6 days ago. I'm pretty sure it's related to this commit where an empty account gets etched some bytecode. https://github.com/foundry-rs/foundry/commit/3df9536132bd213b5de3a6ebab0825302061b61e.

In my test, I'm mocking a function call on an address that will be the result of `create2`.
1. With a `mockCall`, the test reverts at `create2`
2. Without the `mockCall` the test goes past `create2` and breaks because the mock is missing.

Maybe I shouldn't be mocking on that `create2` contract address?

**Comment by onbjerg** [comment]
Yeah, you shouldn't be mocking an empty account if you plan to deploy on top of it, however I'd like to see an example of your test to see if it might make sense? If so we should extend `vm.mockCall` with a flag to skip the etching

**Comment by ryanli-me** [comment]
yeah, it was my unit test where the function being tested will lazy deploy a contract and call a function on it. I think it kinda make sense either way. I just stopped mocking it and rely on the contract being actually deployed.
