### ISSUE TITLE
Support open zeppelin upgradable smart contract deployments

### ISSUE THREAD

**Issue by mfornet** [foundry-rs/foundry#2666]
### Component

Forge

### Describe the feature you would like

Extend `forge create` command to support the deployment of [upgradable contracts](https://docs.openzeppelin.com/upgrades-plugins/1.x/writing-upgradeable) out of the box, automatizing all boilerplate steps.

Similar to this previous issue: https://github.com/foundry-rs/foundry/issues/693. On [this comment](https://github.com/foundry-rs/foundry/issues/693#issuecomment-1122014755) the developer created its own shell script to handle deployment and upgrades.

Check [this tutorial](https://forum.openzeppelin.com/t/uups-proxies-tutorial-solidity-javascript/7786) about how deployments/upgrades are handled in hardhat.

## Proposal

Deploying an upgradable contract can be done in the following way:

```
forge create [--kind <UPGRADE_PATTERN_TYPE>] [--upgrade] <CONTRACT>
```

`kind` should be [one of](https://docs.openzeppelin.com/upgrades-plugins/1.x/api-hardhat-upgrades#common-options):
- uups
- transparent
- beacon

`upgrade` should be used only when upgrading the contract. It shouldn't be used when deploying it for the first time.

### Additional context

- [OpenZeppelin Hardhat plugin](https://github.com/OpenZeppelin/openzeppelin-upgrades/tree/master/packages/plugin-hardhat)

**Comment by gakonst** [comment]
Hmmm not sure how to go about this. What do you think about doing this in forge-script and having a Solidity library that does all the checks? Sorta like https://github.com/odyslam/foundry-upgrades/?

**Comment by onbjerg** [comment]
This was already discussed and marked out of scope in https://github.com/foundry-rs/foundry/issues/2279 and https://github.com/foundry-rs/foundry/issues/693
