### ISSUE TITLE
Coverage Report seems incorrect

### ISSUE THREAD

**Issue by Genysys** [foundry-rs/foundry#2668]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (63ed109 2022-08-09T00:20:50.211015Z)

### What command(s) is the bug in?

forge coverage

### Operating System

macOS (Apple Silicon)

### Describe the bug

My coverage report seems off.  Issues include:

-  contracts/src/test/utils/Utilities.t.sol should be ignored as it is a test utility and is in the test folder.
- contracts/src/LandNft.sol   : appears twice
- contracts/src/Marketplace.sol   : only possesses boilerplate code and should not have 100 % coverage

```bash
[⠊] Compiling...
[⠢] Compiling 32 files with 0.8.15
[⠰] Solc 0.8.15 finished in 2.20s
Compiler run successful
Analysing contracts...
Running tests...
+------------------------------------------+-------------------+-------------------+----------------+-----------------+
| File                                     | % Lines           | % Statements      | % Branches     | % Funcs         |
+=====================================================================================================================+
| contracts/src/LandBank.sol               | 0.00% (0/4)       | 0.00% (0/4)       | 0.00% (0/4)    | 0.00% (0/2)     |
|------------------------------------------+-------------------+-------------------+----------------+-----------------|
| contracts/src/LandNFT.sol                | 100.00% (88/88)   | 100.00% (101/101) | 28.95% (11/38) | 100.00% (11/11) |
|------------------------------------------+-------------------+-------------------+----------------+-----------------|
| contracts/src/LandNft.sol                | 0.00% (0/88)      | 0.00% (0/101)     | 0.00% (0/38)   | 0.00% (0/11)    |
|------------------------------------------+-------------------+-------------------+----------------+-----------------|
| contracts/src/Marketplace.sol            | 100.00% (106/106) | 100.00% (128/128) | 5.41% (4/74)   | 100.00% (12/12) |
|------------------------------------------+-------------------+-------------------+----------------+-----------------|
| contracts/src/test/utils/Utilities.t.sol | 0.00% (0/11)      | 0.00% (0/17)      | 100.00% (0/0)  | 0.00% (0/3)     |
|------------------------------------------+-------------------+-------------------+----------------+-----------------|
| Total                                    | 65.32% (194/297)  | 65.24% (229/351)  | 9.74% (15/154) | 58.97% (23/39)  |
+------------------------------------------+-------------------+-------------------+----------------+-----------------+
```

Repo:

- https://github.com/realiotech/realioverse-contracts/tree/feat/refactor
- forge coverage

**Comment by gakonst** [comment]
cc @onbjerg

**Comment by onbjerg** [comment]
>contracts/src/test/utils/Utilities.t.sol should be ignored as it is a test utility and is in the test folder.

If there is a contract in that file that does not have a `test` function it will be considered a fixture and have a coverage report

>contracts/src/LandNft.sol : appears twice

Does your project produce source trees with two different versions? I.e. one version uses Solc 0.7, one version uses Solc 0.8? In that case, this is expected, but we should probably mark that that is the reason

>contracts/src/Marketplace.sol : only possesses boilerplate code and should not have 100 % coverage

Can you elaborate what you mean by "boilerplate code"? If the contract is inherited, it will also generate a coverage report.

**Comment by onbjerg** [comment]
Bump on this - the linked code does not even compile for me

**Comment by Genysys** [comment]
Apologies my adhd got the best of me. 

> If there is a contract in that file that does not have a `test` function it will be considered a fixture and have a coverage report. If we just ignore all files in folders named `test` or `Utilities.t.sol` we would not be able to generate coverage reports for projects that build libraries (e.g. Solmate) since most of the functionality is tested using mocks.
Understood

> Does your project produce source trees with two different versions? I.e. one version uses Solc 0.7, one version uses Solc 0.8? In that case, this is expected, but we should probably mark that that is the reason
 Not my sources, but forge-std uses 0.7 to 0.9 . All my contracts expect 0.8.15

> Can you elaborate what you mean by "boilerplate code"? If the contract is inherited, it will also generate a coverage report.

The tests only contain signatures for now and are empty.

```
 function test_Sell() public {}

    function test_Buy() public {}

    function test_CreateAuction() public {}

    function test_Bid() public {}
```

With this , I get 100 % coverage for Marketplace.sol

**Comment by onbjerg** [comment]
@Genysys Can you update the branch to reflect a state I can compile it in? I am currently unable to do so because some files are missing - some of the tests try to import `LandNft.sol` but only `LandNFT.sol` exists, and trying to import that gives me a lot of errors because the user defined errors the project uses are defined in `LandNFT.sol` and `Marketplace.sol`

**Comment by Genysys** [comment]
Please try this branch :
https://github.com/realiotech/realioverse-contracts/tree/coverage_error_repro

**Comment by onbjerg** [comment]
I do not see `Marketplace.sol` in there, is something wrong with the report for `LandNFT.sol`?

**Comment by KittyFu307** [comment]
Is there any guid to use forge coverage

**Comment by onbjerg** [comment]
No, not yet

**Comment by gakonst** [comment]
@KittyFu307 `forge coverage --report lcov && genhtml lcov.info -o report --branch-coverage && open report/index.html` or just `forge coverage`!

**Comment by KittyFu307** [comment]
@gakonst Thanks! That helps me a lot. And another question Is the forge coverage still under development? When will it be completed?

**Comment by onbjerg** [comment]
@Genysys After #2927 the report looks reasonable to me on the branch you linked in https://github.com/foundry-rs/foundry/issues/2668#issuecomment-1215692287. Remember to set the fork url for coverage too.

This is what I did:

```
$ forge coverage -f $ETH_RPC_URL
+------------------------------------------+-----------------+-----------------+-----------------+----------------+
| File                                     | % Lines         | % Statements    | % Branches      | % Funcs        |
+=================================================================================================================+
| contracts/src/LandBank.sol               | 0.00% (0/4)     | 0.00% (0/4)     | 0.00% (0/4)     | 0.00% (0/2)    |
|------------------------------------------+-----------------+-----------------+-----------------+----------------|
| contracts/src/LandNFT.sol                | 77.27% (68/88)  | 79.21% (80/101) | 57.89% (22/38)  | 81.82% (9/11)  |
|------------------------------------------+-----------------+-----------------+-----------------+----------------|
| contracts/src/Marketplace.sol            | 4.72% (5/106)   | 3.91% (5/128)   | 5.41% (4/74)    | 8.33% (1/12)   |
|------------------------------------------+-----------------+-----------------+-----------------+----------------|
| contracts/src/test/utils/Utilities.t.sol | 0.00% (0/11)    | 0.00% (0/17)    | 100.00% (0/0)   | 0.00% (0/3)    |
|------------------------------------------+-----------------+-----------------+-----------------+----------------|
| Total                                    | 34.93% (73/209) | 34.00% (85/250) | 22.41% (26/116) | 35.71% (10/28) |
+------------------------------------------+-----------------+-----------------+-----------------+----------------+
```

`ETH_RPC_URL` is a mainnet node, and one of the tests are failing. Unsure if it is supposed to be a mainnet node or not.

Generating an LCOV report and opening it:

```
$ forge coverage -f $ETH_RPC_URL --report lcov
$ genhtml lcov.info -o report --branch-coverage 
$ open report/index.html
```

Shows me that the only uncovered functions (for LandNFT) are `setDevFund` and `tokenURI` which I could not find tests for. There are some uncovered branches, and the ones I've checked so far seem to line up with missing tests.

Similarly, for `Marketplace.sol` it seems that the only covered function is `setLandBank` which lines up with the tests.

Let me know if the report still looks wonky after the nightly tonight!

**Comment by KittyFu307** [comment]
您好，我是付诗琨，您的邮件我已收到，我会尽快查看并给您回复，谢谢。

**Comment by Genysys** [comment]
Please try again
