### ISSUE TITLE
CI can't find sol file , but works locally

### ISSUE THREAD

**Issue by Genysys** [foundry-rs/foundry#2669]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (63ed109 2022-08-09T00:20:50.211015Z)

### What command(s) is the bug in?

forge test --gas-report 

### Operating System

Linux

### Describe the bug

[This](https://github.com/realiotech/realioverse-contracts/runs/7747079158?check_suite_focus=true) job fails , but works locally. I am not sure why this happens and would love some assistance with it

**Comment by mattsse** [comment]
hmm I wonder if there's something off with the root path, could you try two things:

* log the cwd in CI script
* add a foundry.toml file `forge config --basic > foundry.toml` or provide `--root .`

**Comment by Genysys** [comment]
Thanks for responding so quickly. The repo already has a `foundry.toml` file. I will explore the other options

**Comment by Genysys** [comment]
[Here](https://github.com/realiotech/realioverse-contracts/runs/7747556631?check_suite_focus=true) is the new run. I have provided the `--root .` argument , and it seems to be in the right directory. However , I still get the same erro.

**Comment by mattsse** [comment]
looks weird, can you log `forge config` in CI

btw this file https://github.com/realiotech/realioverse-contracts/blob/fix/ci/contracts/src/LandNft.sol is called `LandNft` 

but is used as `"../LandNFT.sol"`

**Comment by Genysys** [comment]
Thanks I had a dirty git cache. closing this now
