### ISSUE TITLE
forge bind generates incorrect bindings

### ISSUE THREAD

**Issue by Genysys** [foundry-rs/foundry#2675]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (63ed109 2022-08-09T00:20:50.211015Z)

### What command(s) is the bug in?

forge bind

### Operating System

macOS (Apple Silicon)

### Describe the bug

The binding generated seems to omit the [serde_json](https://github.com/gakonst/ethers-rs/blob/a958b4fd28709a995c57ef5535cbee1e4e4be543/ethers-core/src/utils/mod.rs#L43) report which leads to loads of errors. 

Repo:

* https://github.com/realiotech/realioverse-contracts/runs/7750620977?check_suite_focus=true

**Comment by mattsse** [comment]
your pinned ethers is outdated by ~2months

https://github.com/realiotech/realioverse-contracts/blob/fix/ci/Cargo.lock#L761

try bumping lock file with `cargo update -p ethers`
