### ISSUE TITLE
`cast calldata` will not encode an empty string array with length 1

### ISSUE THREAD

**Issue by NoahZinsmeister** [foundry-rs/foundry#2681]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (63ed109 2022-08-09T00:20:50.211015Z)

### What command(s) is the bug in?

cast calldata

### Operating System

macOS (Apple Silicon)

### Describe the bug

the command `cast calldata "propose(string[])" \[\]` produces the correct calldata of `0xcde2baba00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000`, matching `abi.encodeWithSignature("propose(string[])", new string[](0));`. this encodes the empty array, `[]`.

however, there's no way to encode the length-1 array `[""]`. `abi.encodeWithSignature("propose(string[])", new string[](1));` produces `0xcde2baba0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000`, but neither `cast calldata "propose(string[])" \[""\]` nor `cast calldata "propose(string[])" \[,\]` nor any other variant i could think of correctly produce this result.

compare this behavior to e.g. `cast calldata "propose(bytes[])" \[0x\]`, which matches `abi.encodeWithSignature("propose(bytes[])", new bytes[](1));` as expected.

**Comment by mattsse** [comment]
just to summarize, `\[""\]` should be equivalent to `new string[](1)`

but currently does not match `0xcde2baba0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000` ?

**Comment by mattsse** [comment]
ah ok found the bug lol

fixing rn

**Comment by NoahZinsmeister** [comment]
thanks @mattsse !
