### ISSUE TITLE
`cast run` crashes when execution transactions from a hardhat node

### ISSUE THREAD

**Issue by pedroyan** [foundry-rs/foundry#2687]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (63ed109 2022-08-09T00:03:50.892098571Z)

### What command(s) is the bug in?

cast run

### Operating System

Linux

### Describe the bug

When running `cast run` with a transaction from a hardhat node, `cast` crashes

![image](https://user-images.githubusercontent.com/11574849/183791206-bd886a55-f466-4156-a1f0-1fffe1d85b88.png)

Running command with `RUST_LOG=backend,node,miner` outputs:
![image](https://user-images.githubusercontent.com/11574849/183791378-18e5d4f2-2fa8-42a2-a36f-798c7b837aaf.png)

**Comment by onbjerg** [comment]
Probably related to us not padding some parameters correctly for Hardhat

**Comment by pedroyan** [comment]
@onbjerg I think your hypothesis is correct, given how the `ethers` maintainers fixed their issue when interfacing with hardhat

https://github.com/ethers-io/ethers.js/issues/2982

**Comment by pedroyan** [comment]
I'm also getting this problem when deploying some contracts using `forge`. If I were to guess what's happening, I think the `foundry` cli tools are not adhering to the [RPC spec](https://playground.open-rpc.org/?schemaUrl=https://raw.githubusercontent.com/ethereum/execution-apis/assembled-spec/openrpc.json&uiSchema%5BappBar%5D%5Bui:splitView%5D=false&uiSchema%5BappBar%5D%5Bui:input%5D=false&uiSchema%5BappBar%5D%5Bui:examplesDropdown%5D=false) that says the storage slot in `eth_getStorageAt` should have a length of 66 (0x + 32 bytes).

The current workaround is to revert the `hardhat` node to a version that came before this pr (https://github.com/NomicFoundation/hardhat/pull/2581), which accepts arguments that do not strictly follow the spec

**Comment by aathan** [comment]
I came to report this same thing (errors using the script functionality to deploy to hardhate) and realized this is related to the report I made *in hardhat#2581*. Not sure if this callsite is the same one that was involved in that older issue. Would be lovely to not have to hold back hardhat version.

**Comment by mattsse** [comment]
this is a bit confusing because this spec does say it's a QUANTITY

https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_getstorageat

https://www.quicknode.com/docs/ethereum/eth_getStorageAt

**Comment by aathan** [comment]
I see you've been talking to the HH guys but I honestly believe they made a mistake with the spec. I'm going to post over there...

**Comment by pedroyan** [comment]
@aathan you really did the lord's work here by chasing this down on multiple repos in the Ethereum space (including raising this to the ethereum team on [their spec](https://github.com/ethereum/execution-apis/issues/303)), and thanks to that, made the ecosystem a little better for everyone :)

@mattssee - feel free to close this now if you want! Just tested the script that was throwing this error against `Hardhat v2.11.2` (which includes https://github.com/NomicFoundation/hardhat/pull/3177) and confirmed that's no longer the case

**Comment by mattsse** [comment]
awesome, thank you so much @aathan

**Comment by gakonst** [comment]
indeed - great work tracking this down @aathan, thank you!
