### ISSUE TITLE
`forge coverage` is also generating reports on contracts inside node_modules

### ISSUE THREAD

**Issue by HrikB** [foundry-rs/foundry#2689]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9b0575e 2022-08-04T00:04:01.463358166Z)

### What command(s) is the bug in?

forge coverage

### Operating System

Linux

### Describe the bug

`forge coverage` is also generating reports on contracts inside node_modules. Is there any way to exclude certain directories from being inside the coverage report?

![image](https://user-images.githubusercontent.com/23041116/183850050-61b4604d-ce2a-4531-88f5-8cc18ca37476.png)

**Comment by onbjerg** [comment]
These should be excluded if `node_modules` is part of `libs` in `foundry.toml`. Please ensure that is the case, otherwise please provide a minimal reproducible example.

**Comment by HrikB** [comment]
![image](https://user-images.githubusercontent.com/23041116/184018194-3cb208d3-dd3b-4f1e-93a8-df9ba8121bd4.png)
My node_modules is in a different directory as it is inside a monorepo. Perhaps using a route like this is causing the error?

**Comment by onbjerg** [comment]
Can you try updating Forge as well? It is 6 days out of date

**Comment by HrikB** [comment]
Done: forge 0.2.0 (49558db 2022-08-10T00:11:55.304734589Z)

The issue still persists though

**Comment by zerosnacks** [comment]
Tentatively marking as `resolved` as I'm unable to reproduce it

Feel free to re-open with a minimal reproduction example / reproduction steps
