### ISSUE TITLE
Improve gas estimation for create transactions

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#2700]
### Component

Forge

### Describe the feature you would like

followup for https://github.com/foundry-rs/foundry/pull/2676

- [ ] estimate gas for `executor.deploy`

**Comment by mds1** [comment]
@mattsse What did you have in mind here? Is this related to item 3 in https://github.com/foundry-rs/foundry/issues/2002#issuecomment-1158936417? Unsure if we should keep this open and track it in #4444

**Comment by zerosnacks** [comment]
Marking as `resolved` as I think it is likely resolved or, if not, will be handled by other tickets detailing specific issues with individual chains or configurations

Feel free to re-open if this is still an issue we should address
