### ISSUE TITLE
`forge script --ledger` deployment fails

### ISSUE THREAD

**Issue by dekz** [foundry-rs/foundry#2709]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6cd6618 2022-08-11T00:05:44.416299Z)

### What command(s) is the bug in?

forge script --ledger

### Operating System

macOS (Apple Silicon)

### Describe the bug

I can successfully use `cast send --ledger` but am unable to use `forge script --ledger` with error of:

```
Error:
hidapi error: hid_error is not implemented yet
```

Can confirm that cast send works exactly as expected, so could be my misuse of `forge script`.

I'm using the following command

```
forge script script/abcd/Deploy.s.sol -f $ETH_RPC_URL -vvvv --ledger --hd-paths "m/44'/60'/0'/1" --legacy --broadcast --sender "0xABCD"
```

I can confirm that `0xABCD` is at the hd-path `m/44'/60'/0'/1`

Immediately switching over to `cast send` and there is no issue at all.

```
cast send 0xABCD --hd-path "m/44'/60'/0'/1" --ledger --value 0 --legacy
```

Successfully sends a transaction to itself from itself using the ledger

**Comment by gakonst** [comment]
@joshieDo i think we've seen this before? Was it because maybe smart contract interactions are not set to TRUE in the Ledger?

**Comment by joshieDo** [comment]
I think this might be because of missing udev rules. [link](https://github.com/LedgerHQ/udev-rules/pull/19)

Did you have ledger live working in your machine before running this ?

**Comment by joshieDo** [comment]
> Was it because maybe smart contract interactions are not set to TRUE in the Ledger?

I didn't even know that being a thing. @dekz  Can you confirm?

Sometimes this error occurs when another process takes ownership of the device and doesn't let go. But given `Immediately switching over to cast send and there is no issue at all.`, it's probably not related.

**Comment by dekz** [comment]
> Was it because maybe smart contract interactions are not set to TRUE in the Ledger?

Not sure what this option is, are you refering to [blind signing](https://www.ledger.com/academy/enable-blind-signing-why-when-and-how-to-stay-safe)? In which case this is enabled, and `cast send --ledger` is able to perform the transaction I wanted `forge script --ledger` to execute (by manually sending the arguments from `forge script` into `cast send`).

My script is essentially a contract `CREATE` then an interaction. I've whittled this down to just a `CREATE` and still see this error with `forge script --ledger`.

I'll try simpler and simpler scripts to see if anything is successful.

**Comment by joshieDo** [comment]
I don't have a ledger with me at the moment, in a few days I can try it out as well. What version is your ledger on?

**Comment by dekz** [comment]
```
Ledger Firmware / Secure Element: 2.1.0
Microcontroller: 1.12
Bootloader: 0.11

Ethereum App: 1.9.18
Blind singing: Enabled
```

**Comment by dekz** [comment]
Just trying a basic test, deploying a simple contract.

`MyContract.sol`
```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.6.5;

contract MyContract {
    function getBlockNumber()
        public
        view
        returns (uint256)
    {
        return block.number;
    }
}

```

`Deploy.s.sol`
```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.6.5;

import "forge-std/Script.sol";
import "forge-std/Test.sol";

import "./MyContract.sol";

contract DScript is Script, Test {
    function run() public {
        emit log_named_address("msg.sender", msg.sender);
        vm.startBroadcast();
        MyContract myContract = new MyContract();
        vm.stopBroadcast();

        emit log_named_uint("blockNumber", myContract.getBlockNumber());
    }
}

```

```
λ forge script script/Deploy.s.sol -f $ETH_RPC_URL -vvvv --ledger --hd-paths "m/44'/60'/0'/2" --legacy --broadcast --verify --sender "0xABCD"

[⠰] Compiling...
[⠃] Compiling 2 files with 0.6.12
[⠒] Solc 0.6.12 finished in 410.01ms
Compiler run successful
Traces:
  [97165] DScript::run()
    ├─ emit log_named_address(key: "msg.sender", val: 0xABCD)
    ├─ [0] VM::startBroadcast()
    │   └─ ← ()
    ├─ [25475] → new MyContract@"0x6765…52ea"
    │   └─ ← 127 bytes of code
    ├─ [0] VM::stopBroadcast()
    │   └─ ← ()
    ├─ [175] MyContract::getBlockNumber() [staticcall]
    │   └─ ← 31827097
    ├─ emit log_named_uint(key: "blockNumber", val: 31827097)
    └─ ← ()


Script ran successfully.

== Logs ==
  msg.sender: 0xABCD
  blockNumber: 31827097
==========================
Simulated On-chain Traces:

  [80879] → new MyContract@"0x6765…52ea"
    └─ ← 127 bytes of code


==========================

Estimated total gas used for script: 105142

Estimated amount required: 0.003154260001892556 ETH

==========================

###
Finding wallets for all the necessary addresses...

Transactions saved to: /Users/jacob/projects/foundry-repro/broadcast/Deploy.s.sol/137/run-latest.json

Error:
hidapi error: hid_error is not implemented yet
```

**Comment by joshieDo** [comment]
finally got a hold of my ledger and was able to reproduce it. sorry it took so long, issue linked

**Comment by dekz** [comment]
Thanks legends, I'll try it shortly and get back to you if there are any other issues.

**Comment by dekz** [comment]
Confirmed working and I was able to use both `forge script --ledger --hd-paths` and `cast send --ledger --hd-path` successfully. 

thanks again @joshieDo .
