### ISSUE TITLE
feat: deploy raw contract bytecode with `cast send --create` 

### ISSUE THREAD

**Issue by evmcheb** [foundry-rs/foundry#2710]
### Component

Cast

### Describe the feature you would like

It would cool to be able to deploy contracts from a raw hex string

proposed format
`cast send 0x6080.... --create`
or
`cast send 0x0000000000000000000000000000000000000000 0x6080.... --create`

**Comment by onbjerg** [comment]
Related to https://github.com/foundry-rs/foundry/issues/2315

**Comment by mattsse** [comment]
closed by #2871
