### ISSUE TITLE
bug: forge fmt comment order change

### ISSUE THREAD

**Issue by rkrasiuk** [foundry-rs/foundry#2713]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What command(s) is the bug in?

forge fmt

### Describe the bug

`forge fmt` changes the order of comments
source:
```solidity
import "ds-test/test.sol";

/*//////////////////////////////////////////////////////////////
    Here we test that the fuzz engine can include a contract created during the fuzz
        in its fuzz dictionary and eventually break the invariant. 
    Specifically, can Judas, a created contract from Jesus, break Jesus contract
        by revealing his identity.
/*//////////////////////////////////////////////////////////////
```
output:
```solidity
import "ds-test/test.sol"; /////////////////////////////////////////////////////////////

/*//////////////////////////////////////////////////////////////
    Here we test that the fuzz engine can include a contract created during the fuzz
        in its fuzz dictionary and eventually break the invariant. 
    Specifically, can Judas, a created contract from Jesus, break Jesus contract
        by revealing his identity.
/*/
```
ref: https://github.com/foundry-rs/foundry/pull/2635#discussion_r941591273
cc @jpopesculian

**Comment by jpopesculian** [comment]
strange... its probably related to a bug in postfix, prefix parsing, not thinking its on a newline because of the comment before. ill take a look today

**Comment by jpopesculian** [comment]
@rkrasiuk which version of fmt is being used? I had to change some stuff in the disable branch which should fix this issue. I mean it formats it to

```solidity
import "ds-test/test.sol";

/*//////////////////////////////////////////////////////////////
    Here we test that the fuzz engine can include a contract created during the fuzz
        in its fuzz dictionary and eventually break the invariant.
    Specifically, can Judas, a created contract from Jesus, break Jesus contract
        by revealing his identity.
/*/
/////////////////////////////////////////////////////////////
```

Which probably isn't optimal but also not the worst thing to fix by hand...

**Comment by rkrasiuk** [comment]
@jpopesculian yup, i can confirm that the latest nightly outputs the format above as well as multiple releases before. unfortunately, i hit foundryup before checking the version, sry ❤️ . should've put it into bug description in the first place

**Comment by gakonst** [comment]
closing optimsitically- feel free to reopen if it comes up again
