### ISSUE TITLE
0.8.16 issues on M1 Mac

### ISSUE THREAD

**Issue by Elyx0** [foundry-rs/foundry#2721]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e71033d 2022-08-11T13:39:22.281674Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

```bash
[⠊] Compiling...
[⠒] installing solc version "0.8.16"
[⠆] Successfully installed solc 0.8.16
Error:
Solc Error: dyld[74016]: Library not loaded: /opt/homebrew/opt/z3/lib/libz3.dylib
  Referenced from: /Users/me/.svm/0.8.16/solc-0.8.16
  Reason: tried: '/opt/homebrew/opt/z3/lib/libz3.dylib' (no such file), '/usr/local/lib/libz3.dylib' (no such file), '/usr/lib/libz3.dylib' (no such file)
```

0.8.15 is/went fine.

Also did
```
solc-select install 0.8.16
solc-select use 0.8.16
```

no changes. 

Replied in https://github.com/ethereum/solidity/issues/3168#issuecomment-1212020352 to see if it was coming from there

**Comment by Genysys** [comment]
Solved [here](https://github.com/foundry-rs/foundry/issues/2712#issuecomment-1211959929)

**Comment by mattsse** [comment]
solc on M1 now requires `brew install z3` ref #2712

**Comment by pagreczner** [comment]
I was on an M1 Pro with OS `11.x`  and was unable to resolve this issue with `z3` or `libusb` installs, compiling from source, or using the install script.

But, what finally worked was updating the OS entirely to `12.5.1` and was then able to successfully run `forge build` and `forge test`.

Leaving this note here in case this helps anyone else who comes here searching for a solution to the similar problem I had.

**Comment by mafellows** [comment]
Can confirm. Upgrading from `11.x` to `13.2` fixed thee issue.

**Comment by williamquao** [comment]
**[Errno 86] Bad CPU type in executable**

On newer solc-select versions, this might show as solc binaries for macOS are Intel-only. **Please install Rosetta on your Mac to continue.**

solc requires Rosetta to be installed. To see whether you have Rosetta installed on your Mac, run

`pgrep -q oahd && echo Rosetta is installed || echo Rosetta is NOT installed
`If it is not installed, it can be installed with the command

`/usr/sbin/softwareupdate --install-rosetta --agree-to-license`

`solc-select install <version>`
