### ISSUE TITLE
`cast interface` from ABI doubles the `struct` keyword in output file from './out/' input file

### ISSUE THREAD

**Issue by Elyx0** [foundry-rs/foundry#2722]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e71033d 2022-08-11T13:39:22.281674Z)

### What command(s) is the bug in?

cast interface -n IMyfile -o contracts/interfaces/IMyfile.sol ./out/Myfile.sol/Myfile.json

### Operating System

macOS (Apple Silicon)

### Describe the bug

```sol
struct Bid {
    address a;
    address b;
    address c;
    address d;
    uint256 e;
}
```
in the main contract `MyFile.sol` becomes in the interface

<img width="728" alt="fe6f5bf1aa4185e069dc7b612d206eb6" src="https://user-images.githubusercontent.com/706218/184160199-1e54ed4a-0f31-4d46-9909-d45d7cdf302c.png">

after I `cast interface` on the ABI of `'./out/Myfile.sol/Myfile.json`

**Comment by Elyx0** [comment]
It also adds the `struct` keyword on other places where I'm not sure it makes sense for an interface:
```sol
    function getCheckpoint(address who) view external returns (struct ValidatorBalanceCheckpoint memory);
    function getPreferences(address who) view external returns (struct ValidatorPreferences memory);
    function getStatus(address who) view external returns (struct Status memory);
```

**Comment by mds1** [comment]
What is the full contents of `MyFile.sol` that you're passing to `cast interface`? I'm unable to reproduce this using `forge 0.2.0 (6cd6618 2022-08-11T00:09:12.927606Z)`

**Comment by Elyx0** [comment]
@mds1 https://gist.github.com/Elyx0/39303f5c1f5bfc231f98105f7588be71

**Comment by mds1** [comment]
Thanks. Confirmed I can reproduce with the ABI in that JSON file. It does seem to be a valid ABI but not yet sure of the cause

**Comment by Elyx0** [comment]
Revisiting this, why can't the interface figure out the `struct` variable names instead of single letters?
https://gist.github.com/Elyx0/39303f5c1f5bfc231f98105f7588be71#file-fastlaneauction-json-L1142-L1175

```c
    struct Bid {
        address a;
        address b;
        address c;
        address d;
        uint256 e;
    }
    ```
Same for `enums` they should be preserved instead of being transformed to `uint8` aka expecting:
```c
    enum statusType {
        INVALID, // 0
        VALIDATOR, // 1 
        OPPORTUNITY // 2
    }
    struct Status {
        uint128 activeAtAuctionRound;
        uint128 inactiveAtAuctionRound;
        statusType kind;  
    }
    ```

**Comment by mds1** [comment]
@Elyx0 Do you mind opening a separate issue for that?
