### ISSUE TITLE
[Bug-Anvil] Command completions issue - FISH and ZSH Shell

### ISSUE THREAD

**Issue by m0ham3dx** [foundry-rs/foundry#2733]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

anvil 0.1.0 (66ef1ae 2022-08-11T15:42:20.732180293Z)

### What command(s) is the bug in?

anvil completions fish > $HOME/.config/fish/completions/anvil.fish

### Operating System

Linux

### Describe the bug

When adding Shell Completions via the following commands as mentioned [here](https://book.getfoundry.sh/config/shell-autocompletion)

```sh
mkdir -p $HOME/.config/fish/completions
forge completions fish > $HOME/.config/fish/completions/forge.fish
cast completions fish > $HOME/.config/fish/completions/cast.fish
anvil completions fish > $HOME/.config/fish/completions/anvil.fish
source $HOME/.config/fish/config.fish
```

Command completions for `anvil` fails . 

Issue has been reproduced in the following gif -
![AnvilCompletions](https://user-images.githubusercontent.com/82266083/184252211-33ca5281-105d-4f80-891d-2b60e6a63462.gif)

Issue also persists when doing completions with zsh via the commands 

```sh
autoload -U compinit
compinit -i

forge completions zsh > /usr/local/share/zsh/site-functions/_forge
cast completions zsh > /usr/local/share/zsh/site-functions/_cast
anvil completions zsh > /usr/local/share/zsh/site-functions/_anvil

```

**Comment by m0ham3dx** [comment]
> I'm not sure what the error is? If you type `anvil ` (with a space) and autocomplete again all of the options show up as expected for me on Fish:
> 
> ![image](https://user-images.githubusercontent.com/8862627/184356090-8f52e356-f3f8-4fef-905e-edebffd02961.png)
> 
> There are no subcommands on Anvil other than `completions` and `help`

Oh thanks for the clarification , in this case this is not a bug. I assumed mistakenly that the `options` are the `sub-commands` and they shouldve been listed.  Im closing this since I can that option is enabled

**Comment by Caranell** [comment]
Not really sure if it's a related problem, but when trying to add anvil completions I get error

```
➜  ~ anvil completions zsh > /usr/local/share/zsh/site-functions/_anvil

error: Found argument 'completions' which wasn't expected, or isn't valid in this context

USAGE:
    anvil [OPTIONS]

For more information try --help

```
