### ISSUE TITLE
`cast storage` return error on big <SLOT> number

### ISSUE THREAD

**Issue by skaunov** [foundry-rs/foundry#2738]
### Component

Cast

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (66ef1ae 2022-08-11T15:42:20.650087337Z)

### What command(s) is the bug in?

cast storage

### Operating System

Linux

### Describe the bug

While playing around with `capturetheether` before `ropsten` decommission got an error from `cast` when it shouldn't be one.
First tried to get storage as usual. Second tried to quote the number just to be sure. And last one close to the example from <https://book.getfoundry.sh/reference/cast/cast-storage> just to be sure that it works in more trivial case.
```console
$ cast storage --rpc-url https://ropsten.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161 0x1106F158A2d2fd4b3Cd80a13dAFeA7d37E17b30d 35707666377435648211887908874984608119992236509074197713628505308453184860937
error: Invalid value "35707666377435648211887908874984608119992236509074197713628505308453184860937" for '<SLOT>': number too large to fit in target type

For more information try --help
$ cast storage --rpc-url https://ropsten.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161 0x1106F158A2d2fd4b3Cd80a13dAFeA7d37E17b30d "35707666377435648211887908874984608119992236509074197713628505308453184860937"
error: Invalid value "35707666377435648211887908874984608119992236509074197713628505308453184860937" for '<SLOT>': number too large to fit in target type

For more information try --help
$ cast storage --rpc-url https://ropsten.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161 0x1106F158A2d2fd4b3Cd80a13dAFeA7d37E17b30d 0
0x0000000000000000000000000000000000000000000000000000000000000000
```

**Comment by onbjerg** [comment]
Improved the error message in #2741

**Comment by skaunov** [comment]
Hope it will help! AFAIR, I tried another command giving it hex argument, and it accepted only decimal. Which formed intuition that I should convert to dec. =)
