### ISSUE TITLE
`forge script` integration tests frequently stall

### ISSUE THREAD

**Issue by onbjerg** [foundry-rs/foundry#2743]
The integration tests for `forge script` frequently stall or are extremely slow in CI (>500-1000 seconds) which is a huge annoyance. We should investigate fixing it.

**Comment by mattsse** [comment]
I'll take a look at where we spend the most time in the script command to identify the bottleneck

**Comment by mattsse** [comment]
appears to be fixed since we migrated to nextest + running script test in sequence
