### ISSUE TITLE
Gas Reports on Fuzz Tests

### ISSUE THREAD

**Issue by 0xfoobar** [foundry-rs/foundry#2751]
### Component

Forge

### Describe the feature you would like

Log gas reports for tests with fuzzing parameters. I have a codebase that's completely fuzz tests and it would be great to get the gas reports without having to rewrite everything with static method params.

**Comment by mds1** [comment]
We should default to using deterministic seed when gas reports are enabled, similar to what is now done with snapshots as of https://github.com/foundry-rs/foundry/pull/2591

**Comment by onbjerg** [comment]
Duplicate of #1023
