### ISSUE TITLE
`forge coverage` branches visualization in the LCOV report

### ISSUE THREAD

**Issue by HrikB** [foundry-rs/foundry#2758]
### Component

Forge

### Describe the feature you would like

When I run `forge coverage --report lcov` and the display the static files generated from that using `genhtml -o report lcov.info`, I only get visualizations for Lines and Functions:
![image](https://user-images.githubusercontent.com/23041116/184495298-42fe2dbd-83d1-4a59-8f1a-e73c935fb2f9.png)

Visualizations for branches would be really useful since I want to be able to cover all execution paths.

(Also I think branches is the only metric that is accurate... but I will open another issue for that)/

**Comment by onbjerg** [comment]
Use `--branch-coverage` on `genhtml`.

**Comment by gte620v** [comment]
This no longer seems to work on lcov v2+.  I upgraded lcov and the same contracts that worked on lcov 1.x now return the following error when I run genhtml with the `--branch-coverage` option.

```
abc.sol has branchcov but no linecov data
```

**Comment by yan-man** [comment]
getting the same issue with `--branch-coverage` - ABC.sol has branchcov but no linecov data, on lcov v2+ too. 

on hardhat v2.17.2
node 18 
hardhat-foundry 1.1.1

**Comment by DaniPopes** [comment]
See https://github.com/foundry-rs/foundry/issues/8281; fully fixed by https://github.com/foundry-rs/foundry/pull/9438
