### ISSUE TITLE
[Bug] `cast lookup-address`

### ISSUE THREAD

**Issue by brianleect** [foundry-rs/foundry#2764]
### Component

Cast

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

0.2.0

### What command(s) is the bug in?

cast lookup-address 0x30c9223d9e3d23e0af1073a38e0834b055bf68ed

### Operating System

Linux

### Describe the bug

Actual output
```
The application panicked (crashed).
Message:  could not abi-decode bytes to address tokens: InvalidName("please ensure the contract and method you're calling exist! failed to decode empty bytes. if you're using jsonrpc this is likely due to jsonrpc returning `0x` in case contract or method don't exist")
Location: /home/runner/.cargo/git/checkouts/ethers-rs-c3a7c0a0ae0fe6be/2c33acb/ethers-providers/src/provider.rs:1417

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: __libc_start_main<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Aborted (core dumped)
```

Expected output
`Error: ens name not found: 30c9223d9e3d23e0af1073a38e0834b055bf68ed.addr.reverse`

Suspect issue is linked to https://ethereum.stackexchange.com/questions/72507/ens-name-reverse-is-not-working-on-ethereum-address.

**Comment by Sabnock01** [comment]
This looks like it could be an issue with `ethers-rs` instead of Foundry.

**Comment by joshieDo** [comment]
seems like the domain `ox63616e.eth` has its resolver set to the WETH contract

**Comment by Tirthnp** [comment]
Is it possible for me to try look at this issue ?

**Comment by joshieDo** [comment]
Imo, this is solved with the above fix on `ethers-rs`. Instead of panicking, it now returns:

```
Error: 
ens name not found: `ox63616e.eth` resolver (0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2) is invalid.
```
