### ISSUE TITLE
Forge Script Bug

### ISSUE THREAD

**Issue by mostarz93** [foundry-rs/foundry#2770]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

0.2.0

### What command(s) is the bug in?

forge script

### Describe the bug

When running a script, i get the following error:

The application panicked (crashed).
Message:  Function signature not found in the ABI
Location: cli/src/cmd/forge/script/mod.rs:411

**Comment by joshieDo** [comment]
this usually happens when you call the script either with a missing `run()` signature, or with a wrongly passed one with `--sig`. Created a PR to provide a better error
