### ISSUE TITLE
incorrect etherscan api key significantly degrates `forge test` performance

### ISSUE THREAD

**Issue by fubhy** [foundry-rs/foundry#2772]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

I'm seeing significantly reduced test performance after upgrading to the latest nightly release. I'm currently trying to pin-point the offending commit by bisecting & building the commits from the last few days and will report back once I find the actual commit hash at which this starts occurring.

The test output still reports the same milisecond-level test performance but instead of all tests flying by and the entire test suite completing in a few seconds, it seems that every individual test case takes much longer to start (multiple seconds). So the slowdown appears to be not in the actual test execution but in the bootstrap phase.

**Comment by fubhy** [comment]
@mattsse The offending commit seems to be `e3857364d266395b59b356f8d33ca9051869bf1f`: https://github.com/foundry-rs/foundry/commit/e3857364d266395b59b356f8d33ca9051869bf1f

```
6fc06c5539efb86b0204331f8a5749a60390389a: SAD
f0725255f4879b9d78f299208fbcc39a370ae6ec: SAD
3b4adef9db3c012efd5b9c7024ac005c4f21d2de: SAD
26e3f576971a4029255ed4f49c20e6ec42b9cd3b: SAD
0eed03d32a3d661629fde8953231cb8ee43adf73: SAD
0f18d24002d1031c97703721f0671ae0ec8ea421: SAD
a6fb5f0f033f6eb33200a2524f6453921a6dd035: SAD
05c1716bc36e8d2bb91187f50c7b54a08946bc22: SAD
b538bb83424df55156ba9964584a0e3528353036: SAD
985cff080fca6991cc771f805ec2fbaee94a4034: SAD
e3857364d266395b59b356f8d33ca9051869bf1f: SAD
1822c8a52b3c1bde62fcf060da38f1cb242bf088: HAPPY
```

**Comment by fubhy** [comment]
Confirmed also that checking out latest `master` (`6fc06c5539efb86b0204331f8a5749a60390389a`) and just reverting `e3857364d266395b59b356f8d33ca9051869bf1f` fixes the performance degradation.

**Comment by mattsse** [comment]
hmm, the only thing e3857364d266395b59b356f8d33ca9051869bf1f changed wrt to test is how the `EtherscanIdentifier` is set up.

The only thing I can think of is this, which should behave the same as before: no etherscan client if no API key configured. But this is a one time cost. so this would only impact individual tests if the setup is now different.

https://github.com/foundry-rs/foundry/commit/e3857364d266395b59b356f8d33ca9051869bf1f#diff-6fc9cb9e02fceb57ef92c35ec7bb209636e4ead12ea08e699505f1b34f31aa89R26-R31


I don't notice any degradation when running it against some repos. How can I reproduce this?

**Comment by fubhy** [comment]
I'll create a reproduction repository. Gimme a few minutes!

**Comment by fubhy** [comment]
Oooooooooooookay... First of all, sorry for potentially wasting your time (maybe? there might still be something wrong here)... I just created the minimal repro - and while doing that, I realized that our old hardhat setup includes a .env file that might overlap with the combination of this PR and the one that recently added support for loading .env files (in https://github.com/foundry-rs/foundry/pull/2587). 

Our existing, foundry-unrelated .env file also has a `ETHERSCAN_API_KEY` value.

Now, when that value is set (.env contains `ETHERSCAN_API_KEY`), then the slowdown occurs when the `ETHERSCAN_API_KEY` is actually not valid (in my case, it was set to a https://polygonscan.com/) API key.

If it's a proper ETHERSCAN_API_KEY, it only delays the full test run very briefly for the first test case. But if it's an invalid API key, it slows it down on every single test case run.

Does that help?

So the repro is simply to put an invalid `ETHERSCAN_API_KEY` in your `.env` file.

**Comment by mattsse** [comment]
that's great insight. 

sorry you had to go through this, let's improve this.

> then the slowdown occurs when the ETHERSCAN_API_KEY is actually not valid 

that makes sense, I think the ideal solution would be if we can somehow check if the key is valid

**Comment by gakonst** [comment]
https://github.com/gakonst/ethers-rs/commit/1af17deeb55435001184150ad0254acda59fd090 per this PR we can now check if the key is valid, and we should prevent the client from retrying?

**Comment by onbjerg** [comment]
A small note here wrt the millisecond time reported: The time is the actual time spent on the test itself, the slowness here is in the reporting/CLI output which is not included in those figures

**Comment by fubhy** [comment]
@onbjerg It would be great if the `forge test` command would print a total runtime output.

**Comment by gakonst** [comment]
> The time is the actual time spent on the test itself, the slowness here is in the reporting/CLI output which is not included in those figures

@onbjerg is the reporting actually taking a long time? should we profile it? or is it the reporting doing the etherscan resolution which is what's causing the slowness due to the etherscan retrying requests?

**Comment by onbjerg** [comment]
@gakonst It's the Etherscan resolution which happens in the reporting since that's where we identify contracts/format the traces
