### ISSUE TITLE
Trx to new contract failed with UNPREDICTABLE_GAS_LIMIT error

### ISSUE THREAD

**Issue by yoavigra** [foundry-rs/foundry#2775]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### Describe the bug

Hi, we are using the latest docker Anvil version, and we notice a difference between hardhat and anvil behavior when sending trx to newly deployed contract:

we deploy contact using ethers contract factory:
<img width="944" alt="image" src="https://user-images.githubusercontent.com/23295337/184637365-c87b7a08-7dba-4f49-ac29-6d228830da4d.png">

when we send trx to the contract, we see that the trx got reverted with the following error :
Error: cannot estimate gas; transaction may fail or may require manual gas limit

the same code works when we switched using hardhat

**Comment by mattsse** [comment]
> Error: cannot estimate gas; transaction may fail or may require manual gas limit

this sounds like this happens because estimation fails?

> when we send trx to the contract, we see that the trx got reverted with the following error :

do you mean the create tx, or tx to that deployed contract?

any way for me to reproduce this?

could you try running with verbose logs `RUST_LOG=backend,api anvil`

**Comment by yoavigra** [comment]
Thx @mattsse for the quick response. ill add the flag and add the logs.
We deployed the contract successfully, connect to it with a signer and then we create a trx (that got reverted) by calling one of our contract's method.

**Comment by yoavigra** [comment]
From the logs, we can see that the contract was deployed successfully:
[2m2022-08-15T13:09:01.496450Z[0m [35mTRACE[0m [2mbackend[0m[2m:[0m New contract deployed: at Some(0x1343248cbd4e291c6979e70a138f4c774e902561)

and here are the logs for the reverted trx:
m2022-08-15T13:09:04.923828Z[0m [35mTRACE[0m [2mbackend[0m[2m:[0m transaction_by_hash=0x45f04a836cb9b189dd7ee8038b49389896a549bca523eeb6f553dded9d135356
[2m2022-08-15T13:09:04.923993Z[0m [35mTRACE[0m [2mbackend::fork[0m[2m:[0m transaction_by_hash=0x45f04a836cb9b189dd7ee8038b49389896a549bca523eeb6f553dded9d135356
[2m2022-08-15T13:09:04.953616Z[0m [35mTRACE[0m [2mbackend[0m[2m:[0m [0x45f04a836cb9b189dd7ee8038b49389896a549bca523eeb6f553dded9d135356] executing
[2m2022-08-15T13:09:04.953688Z[0m [35mTRACE[0m [2mbackend[0m[2m:[0m [0x45f04a836cb9b189dd7ee8038b49389896a549bca523eeb6f553dded9d135356] executed with out=Call(b""), gas =21432
[2m2022-08-15T13:09:04.953696Z[0m [35mTRACE[0m [2mbackend::executor[0m[2m:[0m transacted [0x45f04a836cb9b189dd7ee8038b49389896a549bca523eeb6f553dded9d135356], result: Stop gas 21432
[2m2022-08-15T13:09:04.962833Z[0m [35mTRACE[0m [2mbackend[0m[2m:[0m creating new block with 1 transactions
[2m2022-08-15T13:09:04.962890Z[0m [35mTRACE[0m [2mbackend[0m[2m:[0m [0x45f04a836cb9b189dd7ee8038b49389896a549bca523eeb6f553dded9d135356] executing
[2m2022-08-15T13:09:04.962952Z[0m [35mTRACE[0m [2mbackend[0m[2m:[0m [0x45f04a836cb9b189dd7ee8038b49389896a549bca523eeb6f553dded9d135356] executed with out=Call(b""), gas =21432
[2m2022-08-15T13:09:04.962964Z[0m [35mTRACE[0m [2mbackend::executor[0m[2m:[0m transacted [0x45f04a836cb9b189dd7ee8038b49389896a549bca523eeb6f553dded9d135356], result: Stop gas 21432
[2m2022-08-15T13:09:04.963034Z[0m [35mTRACE[0m [2mbackend[0m[2m:[0m Mined block 15166318 with 1 tx [0x45f04a836cb9b189dd7ee8038b49389896a549bca523eeb6f553dded9d135356]
[2m2022-08-15T13:09:04.963049Z[0m [35mTRACE[0m [2mbackend::fees[0m[2m:[0m updated base fee 2035532466
[2m2022-08-15T13:09:06.986596Z[0m [35mTRACE[0m [2mbackend[0m[2m:[0m creating new block with 0 transactions
[2m2022-08-15T13:09:06.986684Z[0m [35mTRACE[0m [2mbackend[0m[2m:[0m Mined block 15166319 with 0 tx []
[2m2022-08-15T13:09:06.986700Z[0m [35mTRACE[0m [2mbackend::fees[0m[2m:[0m updated base fee 1781090907
[2m2022-08-15T13:09:08.988220Z[0m [35mTRACE[0m [2mbackend[0m[2m:[0m transaction_by_hash=0x45f04a836cb9b189dd7ee8038b49389896a549bca523eeb6f553dded9d135356
[2m2022-08-15T13:09:09.015122Z[0m [35mTRACE[0m [2mbackend[0m[2m:[0m call return Revert out: Call(b"") gas 26097
[2m2022-08-15T13:09:09.016035Z[0m [35mTRACE[0m [2mbackend[0m[2m:[0m creating new block with 0 transactions
[2m2022-08-15T13:09:09.016122Z[0m [35mTRACE[0m [2mbackend[0m[2m:[0m Mined block 15166320 with 0 tx []
[2m2022-08-15T13:09:09.016139Z[0m [35mTRACE[0m [2mbackend::fees[0m[2m:[0m updated base fee 1558454543

**Comment by mattsse** [comment]
so the call definitely reverts

> call return Revert out: Call(b"") gas 26097

any reason the call of the contract would revert?

**Comment by yoavigra** [comment]
We continue to actively investigate why this call might fail. the fact is that the same exact code running on hardhat, so we assume it might be related to the fact we are using one of the provided hardhat accounts (0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266) as a signer. ill update when we will have additional insights

**Comment by mattsse** [comment]
> 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266

that's also an anvil dev account (anvil uses same mnemonic as hh)

**Comment by kubmichael** [comment]
@mattsse , hey, is there are any updates on this issue or do you want some additional info from us that can help to investigate ?

**Comment by mattsse** [comment]
would need more context, ideally a repro, because this is an error that's thrown in `ethers-js`

skimmed ethers-js and this is thrown when gas_limit is null:

[if (tx.gasLimit == null) {](https://github.com/ethers-io/ethers.js/blob/01b5badbb616b29fd8b69ef7c3cc3833062da3d7/packages/abstract-signer/src.ts/index.ts#L295-L307)

which makes me think that there's something off with the gas limit endpoint,

could you perhaps try test this via ethers if retrieving the gas limit works

**Comment by kubmichael** [comment]
@mattsse, hey sorry for late response, issue can be related to bug that we observed during deploy contract, 
```
   const ctr = new ethers.ContractFactory(abi, bytecode, account);
   var deployed = await ctr.deploy(a, a, 1000000);  //  deployed.address - no contract deployed here
   const a = await deployed.deployTransaction.wait() //a.contractAddress - contains contract code
```
it can be related to mining policies, because we didn't see issue with auto mine mode, but it  reproducible almost 100% with interval mining, but it is also can be coincidence
Hope it helps or if it is different issue, I can open a new one
10x

**Comment by zerosnacks** [comment]
Marking as stale, feel free to re-open with a minimal reproduction.
