### ISSUE TITLE
debug_traceCall support

### ISSUE THREAD

**Issue by rajivpo** [foundry-rs/foundry#2782]
### Component

Anvil

### Describe the feature you would like

[`debug_traceCall`](https://geth.ethereum.org/docs/rpc/ns-debug#debug_tracecall) is useful for getting a structured execution trace of `eth_call`, specifically when it comes to tx simulation. Unique challenges include the ability to enable users to leverage [custom tracers written in js](https://geth.ethereum.org/docs/rpc/ns-debug#javascript-based-tracing) and state/block overrides, the latter of which is not present in `debug_traceTransaction`.  

### Additional context

I'm currently using a custom JS tracer, mostly to format data prior to a response as opposed to doing fancy stuff across multiple opcodes, but not leveraging state/block overrides.

Not sure how many others would benefit from this feature. hardhat does not yet support `debug_traceCall` either, but does have support for `debug_traceTransaction`. I'm aware of #1737 but figured I'd put this out there as well. 

If this isn't prioritized, an alternative could be to run geth in clique mode with a custom `genesis.json` and then execute traces accordingly (h/t @tynes for the idea)

**Comment by sambacha** [comment]
second this

**Comment by aditya520** [comment]
Would love to have that!

**Comment by samhatem** [comment]
would love this as well

**Comment by nathanhleung** [comment]
Agreed, this would be a great feature to have.

**Comment by Billy1900** [comment]
One more requirement, I got the trace like this:
```json
{
    "depth": 1,
    "gas": 29978936,
    "gasCost": 3,
    "op": "PUSH1",
    "pc": 0,
    "stack": []
},
```
however, when I use `debug_traceTransaction`, I got 
```json
{
    "depth": 0,
    "error": "",
    "gas": 39469,
    "gasCost": 3,
    "memory": [],
    "op": "PUSH1",
    "pc": 0,
    "stack": [],
    "storage": {}
},
```

can we add storage and memory part?

**Comment by antazoey** [comment]
> can we add storage and memory part?

It get storage and memory when I request like this:

```
"debug_traceTransaction", [txn_hash, {"stepsTracing": True, "enableMemory": True}]
```

**Comment by antazoey** [comment]
Wait, didn't https://github.com/foundry-rs/foundry/pull/3990 resolve this issue?

**Comment by Evalir** [comment]
pretty sure it did haha! thanks for flagging @antazoey — closing

**Comment by Billy1900** [comment]
> > can we add storage and memory part?
> 
> I get storage and memory when I request like this:
> 
> ```
> "debug_traceTransaction", [txn_hash, {"stepsTracing": True, "enableMemory": True}]
> ```
> 
> Edit: Also, I am running my Anvil node with the `--steps-tracing` flag

I am trying to trace a transaction which is not committed so I only want to use `debug_traceCall`, can I get the same data like via `debug_traceTransaction`?
