### ISSUE TITLE
`Undefined` error on `assertEq` could be more clear

### ISSUE THREAD

**Issue by lazaralex98** [foundry-rs/foundry#2783]
```solidity
function testBalanceOf() public {
    uint balance = 10;
    assertEq(balance, 1);
}
```

The above test fails with reason `[FAIL. Reason: Undefined.] ` which is very **misleading**, given that nothing is undefined. IMO it **should say something to the effect of "bad assertion"** or "var not equal to asserted value".

Also, I'm new to Foundry so maybe there's a reason for this, but I think **it'd be super useful to have the error logging point to a line in the file**. Knowing what test the error happened in is useful, but the test could be big and I'd like to know what line it actually failed on.

```bash
Running 1 test for test/PickleCoin.t.sol:PickleCoinTester
[FAIL. Reason: Undefined.] testBalanceOf() (gas: 14813)
Test result: FAILED. 0 passed; 1 failed; finished in 3.10ms
```

For slightly more context, this below obvi passes:
```solidity
function testBalanceOf() public {
    uint balance = 1;
    assertEq(balance, 1);
}
```

**Comment by gakonst** [comment]
The ideal fix here would be @brockelmore's :
>  I think the best solution would be upon failed() returning true, in forge we set the reason to something like Test Assertion Failed
