### ISSUE TITLE
Add file support for  password for keystore 

### ISSUE THREAD

**Issue by henry-hz** [foundry-rs/foundry#2794]
### Component

Cast

### Describe the feature you would like

Today, to use cast with keystore, we have to add the parameter --password. To be able to migrate from seth, having a password stored on file and pointing to this file using an environment variable would be great and make cast more compatible with .sethrc config:
```
# point to the keystore directory
export ETH_KEYSTORE=/home/me/.ethereum/keystore

# point to the password file     ---> [this feature request]
export ETH_PASSWORD=/home/me/.ethereum/keystore/password-file.txt
```

**Comment by konstantinzolotarev** [comment]
@henry-hz Probably could be closed.

**Comment by PatrickAlphaC** [comment]
+1 to closing this issue.
