### ISSUE TITLE
Output metadata by default for Sourcify verification

### ISSUE THREAD

**Issue by kuzdogan** [foundry-rs/foundry#2795]
### Component

Forge

### Describe the feature you would like

With the Sourcify verification support https://github.com/foundry-rs/foundry/pull/2748 it is still required for users to tell the compiler explicitly to output the metadata file with

```
extra_output_files = ["metadata"]
```

The metadata and it appended hash to the bytecode enables Sourcify to get a ["perfect verification"](https://docs.sourcify.dev/docs/full-vs-partial-match/), which is a byte-by-byte match of the source files and compilation settings. Since most of the frameworks don't output the metadata by default, the file after compilation goes missing. When developers make a small change, the newly generated metadata file will be different, making a perfect verification impossible. That the file goes missing, and the lack of knowledge of the metadata have been the main obstacles to the ecosystem-wide adoption of perfect verification. 

By outputting it by default, users can be saved from an additional step and can use this output in the artifacts later even if they don't use the `verify-contract --verifier sourcify` feature.

Other frameworks such as Truffle and recently Hardhat already output the metadata by default
https://github.com/NomicFoundation/hardhat/pull/1863

cc: @rkrasiuk

**Comment by rkrasiuk** [comment]
@mattsse wdyt?

**Comment by mattsse** [comment]
makes sense.

I think we should just fix this in foundry itself:

https://github.com/foundry-rs/foundry/blob/f817db31ab97a62fa635237da424c0e7105ce489/config/src/lib.rs#L827

alternatively we can modify the default outpuselection of ethers-solc:

https://github.com/gakonst/ethers-rs/blob/16f686df265c6cfad4ce0ebba55d803be77a3e24/ethers-solc/src/artifacts/output_selection.rs#L110-L114

the former would be simpler imo

**Comment by rkrasiuk** [comment]
what if the user wouldn't want metadata for whatever reason? there wouldn't be a way for the user to disable it, right?

**Comment by mattsse** [comment]
right, but I don't think there are any downsides to this?
kinda hard to opt out of defaults.

**Comment by rkrasiuk** [comment]
true, true. implementing then

**Comment by mds1** [comment]
How does this relate to setting `bytecode_hash = "none"` in `foundry.toml`? Does using that setting mean you can no longer get "perfect verification" in sourcify?

**Comment by mattsse** [comment]
iirc, same is true for etherscan verify I believe

**Comment by kuzdogan** [comment]
@mds1 yes you can't get a perfect match without the hash in the on-chain bytecode. @mattsse Etherscan just ignores that field and doesn't even correctly decode IPFS hashes.

You might find interesting this blog post I recently wrote but haven't announced yet as a deeper dive how it works: https://docs.sourcify.dev/blog/verify-contracts-perfectly/
