### ISSUE TITLE
Optimize traces fuzz tests

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#2796]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### Describe the bug

currently we record traces for _all_ fuzz runs.

depending on the size of the call and the fuzz case runs (256) default, this can grow very large very quickly. 

https://github.com/foundry-rs/foundry/blob/f817db31ab97a62fa635237da424c0e7105ce489/evm/src/fuzz/mod.rs#L57-L58

https://github.com/foundry-rs/foundry/blob/f817db31ab97a62fa635237da424c0e7105ce489/evm/src/fuzz/mod.rs#L345-L356

But only the last traces are selected for the final `TestResult`:

https://github.com/foundry-rs/foundry/blob/f817db31ab97a62fa635237da424c0e7105ce489/forge/src/runner.rs#L521-L528

we should only store 1 set of traces per Fuzztest or perhaps only record failed calls. the former could be implemented easily but only including the last CallTraceArena

**Comment by joshieDo** [comment]
Since tracing slows down execution (right?), what about executing with tracing disabled off, and only get the traces when a failure occurs (by replaying with tracing enabled)? Do we need the traces for anything if everything succeeds?

**Comment by gakonst** [comment]
> Since tracing slows down execution (right?), what about executing with tracing disabled, and only get the traces when a failure occurs (by replaying with tracing enabled)?

We also will need to rerun with traces if enough `-v` flags are passed when it's successful as well right? 

So maybe for fuzz tests we just always execute with tracing disabled by default, and rerun the failing case (if it failed) else rerun the last case (if it succeeded and we asked for traces via cli)?

**Comment by onbjerg** [comment]
@gakonst @mattsse I need the traces for identifying contracts across fuzz runs which is also the rationale I gave in my PR that changed the behavior

Sucks that it used that much memory, but it seems like we can't really avoid passing around `known_contracts` and continually identifying like we did before when we used Sputnik
