### ISSUE TITLE
'forge create' should work with keystore directory

### ISSUE THREAD

**Issue by henry-hz** [foundry-rs/foundry#2797]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (f817db3 2022-08-16T00:03:50.309804091Z)

### What command(s) is the bug in?

forge create --keystore ./my-directory --password mypass

### Describe the bug

forge create only works with hardcoded file, as:
```
forge create --keystore ./my-directory/my-keystore-file  --password mypass
```
but using as
```
forge create --keystore ./my-directory  --password mypass
```
we get:
```
Error:                                                                                                                                
IO: Is a directory (os error 21)
```

**Comment by henry-hz** [comment]
The keystore was working (but still pointing to a file, not to the directory)

```
cast send --keystore keystore-55a9 --from 0x4828699dcbe7d449ce209af47ed285eba9a555a9                  00:32:55
Enter keystore password:

blockHash               0x51e12243658095e6b9fa469064eec1b993d2ae37f24f3cb6fcc6592e97b90d3f
blockNumber             8650328
contractAddress         0x55533eBf74F77ac0D7B60e8Af740fEb2E956DD7a
```
but after foundryup now: 
[foundryup: installed - cast 0.2.0 (d1c84e3 2023-03-13T00:07:48.790822528Z)]

```
cast send --keystore keystore-55a9 --from 0x4828699dcbe7d449ce209af47ed285eba9a555a9               6s 00:36:02
Error: 
(code: -32601, message: The method eth_sendTransaction does not exist/is not available, data: None)
```

**Comment by zerosnacks** [comment]
Marking as `wontfix` as I do not see the use case of passing a keystore directory and we handle the error gracefully now for both `cast send` and `forge create`.

When passing a keystore directory the following descriptive error is thrown: `Keystore path `"/home/zerosnacks/.foundry/keystores/"` is a directory. Please specify the keystore file directly.`

https://github.com/foundry-rs/foundry/issues/2797#issuecomment-1467074532 has been either resolved or the error is not reproducible
