### ISSUE TITLE
Document how to test upgradeable smart contracts

### ISSUE THREAD

**Issue by grp06** [foundry-rs/foundry#2800]
### Component

Forge

### Describe the feature you would like

Any serious solidity project is going to be built to be upgradeable. And with Foundry's existing tools, there isn't a clear-cut way to test contracts that use proxies. 

It feels limiting to simply point out anything related to supporting upgrades as "out of scope" https://github.com/foundry-rs/foundry/issues/2666#issuecomment-1209802183 or as just a "specialized vendor tool" https://github.com/foundry-rs/foundry/issues/2279#issuecomment-1186295707

Testing upgradeable smart contracts seems important enough that if you're not going to support it, your docs should directly address this in your docs and guide users how to use Forge to do this.

**Comment by joshieDo** [comment]
> Any serious solidity project is going to be built to be upgradeable.

I'd highly disagree, and there are a ton of really serious projects which don't have it. 

In any case, have you tried out https://github.com/odyslam/foundry-upgrades/ ? What do you think is lacking there? I haven't personally used it.

**Comment by tynes** [comment]
> > Any serious solidity project is going to be built to be upgradeable.
> 
> I'd highly disagree, and there are a ton of really serious projects which don't have it.
> 

Definitely agree with this, contracts that are not upgradable are important for the future of the ecosystem.

Many systems do need upgradability built in as projects work towards product market fit - here are some examples of proxy tests:
- https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/contracts/test/Proxy.t.sol
- https://github.com/ethereum-optimism/optimism/blob/e4ef92a63c3aceeda2a2306429b04df4a25c97c8/packages/contracts-bedrock/contracts/test/OptimismPortal.t.sol#L591
- https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/contracts/test/ProxyAdmin.t.sol

Are you looking for tooling to manage upgrades with `forge script`? People have talked about writing libraries that can handle that, its also possible to do that in Typescript with the `foundry-rs/hardhat` plugin with hardhat tasks

**Comment by jordaniza** [comment]
@grp06 does this help https://github.com/jordaniza/OZ-Upgradeable-Foundry

**Comment by onbjerg** [comment]
Closing this since we've had other issues where we decided we don't want to specifically integrate with any upgradeable proxies *natively* in Forge, so we won't have `forge upgrade` etc. commands.

In terms of documenting how to test proxies, I think that's more of a book issue if anything, so it should be discussed in that repository.

Outside of that I also think that we cannot account for every type of smart contract out there in our canonical documentation, so if any community docs (as linked above) work, we should just refer to them when possible.

**Comment by HashHaran** [comment]
> ### Component
> Forge
> 
> ### Describe the feature you would like
> Any serious solidity project is going to be built to be upgradeable. And with Foundry's existing tools, there isn't a clear-cut way to test contracts that use proxies.
> 
> It feels limiting to simply point out anything related to supporting upgrades as "out of scope" [#2666 (comment)](https://github.com/foundry-rs/foundry/issues/2666#issuecomment-1209802183) or as just a "specialized vendor tool" [#2279 (comment)](https://github.com/foundry-rs/foundry/issues/2279#issuecomment-1186295707)
> 
> Testing upgradeable smart contracts seems important enough that if you're not going to support it, your docs should directly address this in your docs and guide users how to use Forge to do this.
> 
> ### Additional context
> _No response_

While the deployment and management of contracts involved in different proxy patterns can be done with forge scripts, it's hard to do upgrade safety checks in them. For this reason I have used a hardhat parallel set up with my foundry project to use open zeppelin upgrades plugin. Check if [this ](https://github.com/HashHaran/foundry-upgrade-hardhat) helps.

**Comment by MatinR1** [comment]
Hey all!
We have worked on upgradeability mechanism testing using Foundry's Forge for UUPS-type proxies.
It's possible to test different functionalities of implementation-proxy pairs using Forge.

I'd be glad to check this link out:
https://github.com/MatinR1/UpgradeableTest/blob/master/test/UpgradeabilityTest.t.sol

**Comment by PatrickAlphaC** [comment]
This was very helpful, thanks!
