### ISSUE TITLE
Allowing for "untouching" touched/hot storage slots

### ISSUE THREAD

**Issue by benesjan** [foundry-rs/foundry#2817]
### Component

Forge

### Describe the feature you would like

Since tests are executed in 1 tx it happens that gas profiling returns lower gas costs than what would happen in mainnet environments because plenty of the slots are touched/hot. This would not happen on mainnet where various calls would most likely be executed in separate txs.

It would be useful to be able to reset the list of touched/hot slots so that tests can be better used for mainnet gas cost estimation.

**Comment by onbjerg** [comment]
Duplicate https://github.com/foundry-rs/foundry/issues/1340
