### ISSUE TITLE
forge create Artifact not found with cached project

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#2825]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### Describe the bug

As reported here 

> I still can't get forge create to work. This is with a basic template, with a blank contract "contract Contract { }"

> forge create --rpc-url http://localhost:8545 --private-key ac.....80 src/Contract.sol:Contract
[⠆] Compiling...
> No files changed, compilation skipped
> Error: 
> could not find artifact: Contract

https://t.me/foundry_support/21310

this likely has something to do with cached artifacts

**Comment by nxt3d** [comment]
I got it to work, can close this.
