### ISSUE TITLE
Corrupted compilation artifacts in case of contracts name collision

### ISSUE THREAD

**Issue by montyly** [foundry-rs/foundry#2843]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6b3db2a 2022-08-19T00:24:19.967244Z)

### What command(s) is the bug in?

forge build

### Describe the bug

If two contracts are in files that share the same filename/contract name, foundry will generate corrupted compilation artifacts (one of the contract overwrites the other).

I was the impression that it was solved when https://github.com/foundry-rs/foundry/issues/1488 was fixed, but I am still experimenting the issue with the latest `forge`.

I created a repo to show the issue https://github.com/montyly/foundry-collision
```
% forge --version
forge 0.2.0 (6b3db2a 2022-08-19T00:24:19.967244Z)
```

- `src/a.sol:A` has a `foo` function https://github.com/montyly/foundry-collision/blob/ce58230b551d8baccefbdcde07be52efaf3da7eb/src/a.sol#L1-L3
- `src/inner/a.sol:A` has a `bar` function https://github.com/montyly/foundry-collision/blob/master/src/inner/a.sol
- Only one compilation artifacts is generated for `A` (in this example, it contains `bar`) : https://github.com/montyly/foundry-collision/blob/master/out/a.sol/A.json#L2-L9

This issue is a major blocker for many slither/echidna users, so it would be great if we could have a fix.

**Comment by montyly** [comment]
Great, thanks for the quick fix @mattsse

**Comment by montyly** [comment]
Actually there are still collision possible. For example, if two files have the same name without the case sensitivy, but different with:
- `src/a.sol`: https://github.com/montyly/foundry-collision/blob/7fe6e6550bc9ad19e6623c56b5a9b66426c7a099/src/a.sol
- `src/inner/A.sol` https://github.com/montyly/foundry-collision/blob/7fe6e6550bc9ad19e6623c56b5a9b66426c7a099/src/inner/A.sol

Then the collision still occur. In the repo `out/src/A.sol` https://github.com/montyly/foundry-collision/blob/7fe6e6550bc9ad19e6623c56b5a9b66426c7a099/out/a.sol/A.json#L3-L9 (`src/a.sol` compilation artifacts are overridden by `src/inner/A.sol`)

Tested with the latest forge:
```
forge --version
forge 0.2.0 (29ff0b0 2022-08-20T00:05:53.843766Z)
```

I haven't tested if `a.sol` and `A.sol` are both within the same directory, but I am assuming the issue will be the same (only for case sensitive system)

**Comment by mattsse** [comment]
right, forgot about case-sesnistivity...

but this is now a simple fix.

thanks for flagging again
