### ISSUE TITLE
feat: `vm.parse*()` helpers for reading files

### ISSUE THREAD

**Issue by mds1** [foundry-rs/foundry#2847]
### Component

Forge

### Describe the feature you would like

`vm.readLine` always reads in as a string, and therefore converting to other types like bytes32 requires dropping into assembly and removing the ascii encoding. This can be greatly simplified by a set of `parse*` cheatcodes that take a string and return the specified type. The full set of functions would be:

```
function parseBool(string calldata) external returns (bool);
function parseUint(string calldata) external returns (uint256);
function parseInt(string calldata) external returns (int256);
function parseAddress(string calldata) external returns (address);
function parseBytes32(string calldata) external returns (bytes32);
function parseBytes(string calldata) external returns (bytes memory);
```

--------

A side effect of this is that we have the option of removing the `envBool`, `envUint`, etc. overloads and just havng a single `env` cheatcode that always return a string, and then use these methods to convert from string to the appropriate type. This would be a breaking change. Additionally, we probably still want to keep the env overloads that return arrays since they involve parsing a delimiter.

**Comment by shekhirin** [comment]
I can work on this one

**Comment by shekhirin** [comment]
@mds1 I think it can be closed as done?

**Comment by mds1** [comment]
Ah yep seems it didn't get linked, thanks. Closed by https://github.com/foundry-rs/foundry/pull/2854
