### ISSUE TITLE
`forge test -vvv` keeps no trace of failed fuzzed test, picks random trace

### ISSUE THREAD

**Issue by j-vp** [foundry-rs/foundry#2848]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

`forge 0.2.0 (6b3db2a 2022-08-19T13:22:07.65532Z)`

### What command(s) is the bug in?

`forge test -vvv`

### Describe the bug

When a fuzzed test fails, the traces are shown from one random iteration, never the failed iteration. This has 2 consequences.

1) In a test run where a few iterations succeed, and a subsequent one fails, the traces seem to show a random trace of a successful fuzzed iteration. As such, it's hard to pinpoint the exact problem through the traces. The error message shows the arguments on which it fails, yet the test with that argument is not shown in the traces.
2) In a test run where the first iteration of a fuzzed test fails, no traces are shown. This makes me believe that on a failed test, no traces are kept (and thus, no traces can be shown).

The expected behavior would be to have the trace of the failed iteration shown.

To reproduce, I have a small repro here: [https://github.com/j-vp/foundry-2848](https://github.com/j-vp/foundry-2848). This is a slightly modified version of the `forge init` project.

Upon launching a few `forge test -vvv`'s, you'll notice that sometimes it doesn't show a trace and sometimes it does. When it doesn't show a trace, it will have `args=[0]` and `runs: 0`.
When it does show a trace, it will be a trace of a successful run and `runs` will be `>0`.

In the screenshot below, note the trace of a passed iteration, and the `runs: 0` when no trace is shown.

![image](https://user-images.githubusercontent.com/104004836/185644259-e256f355-e9e4-4c5d-8b94-3ca385a99f9a.png)

**Comment by onbjerg** [comment]
Regression from #2819

**Comment by mattsse** [comment]
right, we should favor failed over successful runs
