### ISSUE TITLE
condition not caught by invariant/fuzzer

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#2851]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### Describe the bug

![telegram-cloud-photo-size-2-5188374473173220884-y](https://user-images.githubusercontent.com/19890894/185662217-37e6376f-e021-4d5d-966d-f2f8c8b03972.jpg)

**Comment by joshieDo** [comment]
I'm not sure invariant is the best for this scenario scenario. We have `x` on the dictionary, but we need `x+1`, so we're stuck on somehow getting `x+1` in the middle of the uint256 space.

Also, does normal fuzzing even reach `number = 0` ?

--

If we wanted to reach this, we could probably come up with a strategy that adds `x - n`, `x + n` to the dictionary... but that seems too niche.

**Comment by mds1** [comment]
Just curious, where is this example from? I'm inclined to say we shouldn't worry too much about trying to tune the fuzzer to find this particular example—it's a bit contrived and I haven't seen much solidity code with similar logic, so you could argue it's is more of an academic issue than a practical issue.

I think a more worthwhile (but also bigger) effort is ensuring foundry can match echidna's performance, which we haven't demonstrated yet. The echidna [readme](https://github.com/crytic/echidna#trophies) has a "Trophies" section showing real issues it's found, and a "Research" section reproducing examples from papers. Some of those research examples are _similar_ to the above, but I think simpler in that there's not the `- 1` and therefore collecting PUSH bytes should solve it. 

All of the echidna test cases (excluding "trophies", including "research" and other tests) can be found here: https://github.com/crytic/echidna/tree/master/tests/solidity

It would be great if we setup all of those test cases as part of foundry CI and make sure fuzz/invariant tests can reliably catch those

**Comment by mattsse** [comment]
@gakonst can probably provide some context and the expectations here

**Comment by onbjerg** [comment]
Imo this kind of test case is what symbolic execution is more geared for. The kind of fuzzer we have is borderline a blackbox fuzzer, so it's essentially just bruteforcing its way there. We have a dictionary as well but the chance of hitting that particular number is still very low.

**Comment by grandizzy** [comment]
Awesome write-up analysing this issue here https://hackmd.io/@SaferMaker/EVM-Sym-Exec

**Comment by brockelmore** [comment]
<img width="822" alt="Screenshot 2024-06-06 at 10 35 16 AM" src="https://github.com/foundry-rs/foundry/assets/31553173/f5a82769-bddf-4952-b9bf-9c7b9623dca8">


By the way this is caught by the fuzzer now. should probably close this

**Comment by grandizzy** [comment]
> <img alt="Screenshot 2024-06-06 at 10 35 16 AM" width="822" src="https://private-user-images.githubusercontent.com/31553173/337375757-f5a82769-bddf-4952-b9bf-9c7b9623dca8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2OTU4MjAsIm5iZiI6MTcxNzY5NTUyMCwicGF0aCI6Ii8zMTU1MzE3My8zMzczNzU3NTctZjVhODI3NjktYmRkZi00OTUyLWI5YmYtOWM3Yjk2MjNkY2E4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDE3Mzg0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2YmI3ZmQyZmRiNmM4NDc0ZmRlNTY1Y2ViMzNkY2EwYWRkODY0ODRlOGUwYjZjMTE2NzQ2NDFjOWUyNjIyNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3tRpkzvN8KMcRf69JRGZAd7uu8YOddinSiz9WwOA6-M">
> 
> By the way this is caught by the fuzzer now. should probably close this

Awesome! Do you have the test handy to share, would love to have it as a regression test. Also planning to create a benchmark project (smth similar with https://github.com/grandizzy/fuzz-benchmarks/) and run daily checks. thank you!

**Comment by brockelmore** [comment]
```solidity
// SPDX-License-Identifier: MIT OR Apache-2.0
import "forge-std/Test.sol";
pragma solidity ^0.8.1;

contract Backdoor {
    uint public number = 1;
    function backdoor(uint256 newNumber) payable public {
        uint x = newNumber - 1;
        if (x == 6912213124124531) {
            number = 0;
        }
    }
}

contract BackdoorTest is Test {
    Backdoor back;

    function setUp() public {
        back = new Backdoor();
    }


    function invariantNotZero() public {
        assertEq(back.number(), 1);
    }
}
```

**Comment by grandizzy** [comment]
thank you! confirm it is caught with fuzzer default settings :tada:

**Comment by brockelmore** [comment]
Closing
