### ISSUE TITLE
feat: `verify-contract`

### ISSUE THREAD

**Issue by Bapi-Reddy** [foundry-rs/foundry#287]
The etherscan feature verify-contract isn't implemented for forge compiled contracts. It is currently configured for `dapp` compiled output.  Also in `forge create` the verify tag isn't implemented or linked with existing `verify-contract` implementation

**Comment by wilsoncusack** [comment]
sounds like this is maybe a bug `verify-contract` ?

**Comment by sambacha** [comment]
you could also upload to sourcify via ipfs://Qme7ECr3oXnVjPemmKJgUvKWhRvTwLoQ3t95NQiD1RMaxR and its verified if your deploying on mainnef

**Comment by onbjerg** [comment]
Fixed?

**Comment by onbjerg** [comment]
Going to close this as fixed - check the docs [here](https://book.getfoundry.sh/forge/deploying.html) and [here](https://book.getfoundry.sh/reference/forge/forge-verify-contract.html). Let me know if you are still encountering issues! :blush:
