### ISSUE TITLE
`forge cast call` on a RPC endpoint with HTTPS returns `invalid peer certificate: UnknownIssuer`

### ISSUE THREAD

**Issue by frank-part** [foundry-rs/foundry#2873]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (7e9e6a5 2022-08-22T00:04:53.96787182Z)

### What command(s) is the bug in?

forge cast call

### Operating System

Linux

### Describe the bug

I'm using an RPC endpoint with a self-signed certificate. I'm seeing the following error when I make the call: "invalid peer certificate: UnknownIssuer"

 I've placed the rootca into the following folders, but I'm not sure where cast reads trusted CAs from, or how to set a custom CA or client certificate for the command.
* `/usr/local/share/ca-certificates/`
* `/etc/ssl/certs/`

**Comment by mattsse** [comment]
related https://github.com/denoland/deno/issues/2301
