### ISSUE TITLE
Unbounded memory growth on anvil

### ISSUE THREAD

**Issue by kahuang** [foundry-rs/foundry#2880]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (92f8951 2022-08-07T00:05:07.680722Z)

### What command(s) is the bug in?

anvil --block-time 1

### Operating System

macOS (Intel)

### Describe the bug

I'm observing unbounded memory growth when running anvil with 1s block times. It's gotten up to 2GiB (and because I'm running these in k8s they oom and restart), but shows no signs of leveling out.

This repros on linux and mac, and I have some traces below which were generated on mac. I used https://crates.io/crates/cargo-instruments to generate these traces. Here was the exact command, run in the foundry repo:

`cargo +nightly instruments --time-limit 60000  --template Allocations --bin anvil -- --block-time 1`

Which generated the below trace.

[anvil_Allocations_2022-08-22_104618-550.trace.zip](https://github.com/foundry-rs/foundry/files/9395570/anvil_Allocations_2022-08-22_104618-550.trace.zip)

It seems a lot of the memory is being held in the in-memory-db from block creation.
<img width="390" alt="Screen Shot 2022-08-22 at 11 01 48 AM" src="https://user-images.githubusercontent.com/1594551/185957395-6ba64fc9-a7c5-4888-b296-c0e118fb7c6d.png">

It'd be great if there were some limit here (and maybe persisting to disk if necessary?) that could be configurable

**Comment by mattsse** [comment]
yeh basically we store an entire snapshot of the block in memory, which grows until out of mem.

this can grow quite large with interval mining,

do you now after which block height did you notice problems?

we should definitely limit this and either purge or write to disk

**Comment by kahuang** [comment]
I don't have logs but anecdotally about 1-1.5hrs so between 4K-6k blocks?

**Comment by mattsse** [comment]
yeh that's quite a lot.

I'll limit this to something more sensible and outsource older state to disk, so we still have full state diffs.

this is not very efficient since lots of duplicates, a better solution would probably be a triedb

**Comment by kahuang** [comment]
I'm a +1 for limit + persist to disk as necessary

**Comment by kahuang** [comment]
Ty for fast turnaround!

**Comment by mattsse** [comment]
this should solve it, if you still experience problems lmk so we can either further reduce the block limit or optimize what is stored on disk

**Comment by kahuang** [comment]
Confirming that this works now, and moves the state growth to disk vs memory which is a big improvement. Not urgent, but it'd be nice from a cost-savings perspective to have the db storage optimized at some point
