### ISSUE TITLE
bug: forge build with tests generates two folders with same name ( test.sol,Test.sol)  which causes typechain import error 

### ISSUE THREAD

**Issue by Naim-Bijapure** [foundry-rs/foundry#2894]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (b1f6a6c 2022-08-23T00:11:49.822421184Z)

### Operating System

Linux

### Describe the bug

With solidity test files forge build generates two files with same name only a difference of first capital letter . eg: test.sol and Test.sol. 
like show in below image. 

![2022_August_23_13-26-29](https://user-images.githubusercontent.com/22323693/186104165-028e0e88-a39f-497f-a53c-7451ce659da2.png)

which causes typechain to import issues with similar names on typescript types. 
its giving error like below image. 

typechain cant differentiate between two same names. 
ideally 1 test name should be ds_test.sol something !! . 
(tried this by changing manually it worked. )

![2022_August_23_13-30-01](https://user-images.githubusercontent.com/22323693/186104962-77dddebe-61ad-4cf8-b4f6-bec0713f9c50.png)

**Comment by zerosnacks** [comment]
Typechain has been deprecated, marking this as `wontfix`
