### ISSUE TITLE
feat: to give a option to disable *.metadata.json file generation  in  artifices. 

### ISSUE THREAD

**Issue by Naim-Bijapure** [foundry-rs/foundry#2895]
### Component

Forge

### Describe the feature you would like

Required an option to disable the *.meatadata.json files. 
as this files are not getting processed by typechain. typechain throwing invalid abi file error. 
for now manually deleting this *.metadata.json file on typechain type build process. 

![2022_August_23_13-45-58](https://user-images.githubusercontent.com/22323693/186108223-9b4792f2-a705-4dd5-b6fe-5bc762bf63bd.png)

**Comment by onbjerg** [comment]
Sort of also adjacently feels like a bug that typechain should address separately :smile:

**Comment by Naim-Bijapure** [comment]
@onbjerg  make sense !. 
but also on forge, there is  --extra-output-files <SELECTOR> like an option available. 
the flexibility of which files to keep also great feature. 

right now typechain taking .json file blindly from nested directories.

**Comment by tynes** [comment]
Enforcing this to always be on broke the foundry hardhat plugin as well. Not super opinionated about it being on or off by default, but I do think it should be possible to turn off if not desired. Right now I don't think its possible to turn off.

@Naim-Bijapure you should be able to use a regex with typechain to ignore the metadata files

**Comment by Naim-Bijapure** [comment]
look like this issue is fixed. 
https://github.com/foundry-rs/foundry/pull/2982

*.metadata.json file moved into single json file.
