### ISSUE TITLE
Change made by `vm.deal(address,uint256)` at the end of `setUp()` is no longer present at the beginning of a test

### ISSUE THREAD

**Issue by benesjan** [foundry-rs/foundry#2898]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (b1f6a6c 2022-08-23T00:07:04.829899Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

After updating forge my tests started failing. I realized that it is because of issue I described in the headline. When I print the balance at the end of `setUp` it's 0. At the beginning of a test it's non-zero.

The bug was introduced in the latest release. Release nightly-7e9e6a5d6b30ad3f543857198234edcdbceb724a is working as expected.

I am working on an open source project so the bug can be reproduced by running `forge test --match-contract Subsidy` on master branch in [this repo](https://github.com/AztecProtocol/aztec-connect-bridges).

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/13470840/186116718-08a16141-d234-4f0a-abc4-955a3466a12a.png">

**Comment by mattsse** [comment]
this could be related to the revm bump yesterday, investigating

**Comment by mattsse** [comment]
@benesjan thanks for flagging, this was indeed a smol regression introduced yesterday.

should be resolved by #2901
