### ISSUE TITLE
seth feature parity

### ISSUE THREAD

**Issue by gakonst** [foundry-rs/foundry#29]
# Problem & Context

Currently, [`cast`](https://github.com/gakonst/foundry/blob/master/cast/src/lib.rs) and its [cli](https://github.com/gakonst/foundry/blob/master/cli/src/cast.rs) are not at feature parity with seth. 

All of Seth's commands can be found [here](https://github.com/dapphub/dapptools/tree/master/src/seth#commands), and the so far implemented `cast` commands can be found [here](https://github.com/gakonst/foundry/blob/master/cast/README.md). 

# Solution

Pick any of the commands that are not implemented, and go for it!

Some reference PRs on how this was done for other commands for newcomers can be seen below:
- https://github.com/gakonst/foundry/pull/266
- https://github.com/gakonst/foundry/pull/261
- https://github.com/gakonst/foundry/pull/260
- https://github.com/gakonst/foundry/pull/242
- https://github.com/gakonst/foundry/pull/223

**Comment by odyslam** [comment]
@gakonst let's make this a good first issue and rename it to cast.

**Comment by gakonst** [comment]
Checklist of implemented commands here: https://github.com/gakonst/foundry/blob/master/cast/README.md

**Comment by gakonst** [comment]
Yes! These are small self-contained commands, so shouldn't require much. Take a look at the PRs linked in the OP for guidance. Also happy to review.

**Comment by ravindranrahul** [comment]
Update: I'm working on this. I'm an absolute beginner, please allow me some time.

**Comment by odyslam** [comment]
> Update: I'm working on this. I'm an absolute beginner, please allow me some time.

I have started working on this as well. Perhaps we can coordinate and not implement the same functionality. 

I have opened a draft PR while I work on it #284 and I note what I work on. Perhaps you can do as well or write a reply there?

**Comment by mds1** [comment]
I'll add comments to this issue for features that I've noticed are missing as I attempt to replace `seth` with `cast` during my normal usage:

- `cast call` does not support the `--block <block>` flag for querying historical data
- as noted in the readme, `cast run-tx` is not supported—I used the `--trace` and `--debug` modes often

**Comment by SusheendharVijay** [comment]
I'm working on `cast index`, after implementing exaclty what seth does, we can discus how to improve the syntax.

**Comment by tynes** [comment]
There are 2 reasons why I still use `seth` over `cast`

1. `--rpc-url` defaults to `http://localhost:8545` without needing to set an env var, so I can omit adding it when I port forward my remote geth node
2. The table response is pretty printed (ie hex strings are turned into integers, easier for human consumption)

**Comment by onbjerg** [comment]
- [ ] `cast send --create` is missing as well

**Comment by onbjerg** [comment]
Seems like the last two remaining items are `cast send --create` and I256 support?

**Comment by tynes** [comment]
> Seems like the last two remaining items are `cast send --create` and I256 support?

`cast ls` and `cast accounts` are missing as well. It's convenient to know which wallets you currently have access to. I do think the commands can be improved upon

**Comment by mds1** [comment]
Other features missing, from comparing the outputs of `seth` and `cast`
- `--from-ascii`
- `bundle-source`, though I don't think we need this one
- `logs`
- `mktx`
- `sign`
- `solc`

I'm not sure how many of these are used so we may not care about getting exact parity.

**Comment by gakonst** [comment]
sign exists under "cast wallet"

**Comment by onbjerg** [comment]
>solc

What is this one?

>--from-ascii

We do have this one :smile:

**Comment by mds1** [comment]
Ah, `--from-ascii` doesn't show up when running `cast -h`, but yes just confirmed it is there under an alias for `--from-utf8`

[`solc`](https://github.com/dapphub/dapptools/blob/master/src/seth/libexec/seth/seth-solc) lets you "compile a single file using a default --standard-json input"

**Comment by onbjerg** [comment]
Not sure we want that necessarily? :thinking:

**Comment by mds1** [comment]
I've personally never used it and would be ok not adding it proactively, and perhaps we wait until its requested and discuss then?

**Comment by onbjerg** [comment]
Ok so to sum up:

- [ ] `cast accounts`/`cast ls` (they could just be merged into `cast wallet ls`?)
- [ ] `cast send --create`
- [ ] `cast logs`
- [ ] `cast mktx`

Optionally also `cast bundle-source` but there probably isn't a lot of usage for that command. Seems like `seth bundle-source` was primarily used to get source maps for `seth run-tx` and the DappTools debugger, but we should try to make this automatic *or* push Etherscan to include source maps in their API.

**Comment by tynes** [comment]
There is another command that could be useful - `seth rpc` which doesn't seem to completely work when passing args, but it does work when the RPC accepts no arguments. This would be useful to call RPCs that don't already have `cast` commands. I think something like this would be helpful to cut out the `curl -H ...` boilerplate.

```bash
cast rpc <rpc-method> <arg 1> <arg 2> ...
```

Delineating between types here would need to be handled, for example strings vs numbers. `geth` will only accept numbers at times, not strings of numbers. So strings would need to be explicit, like `'"3"'` would be a string  and `"3"` or `3` would be a number. The response json could return the jsonrpc `result` field and it could be easily composed with `jq`

**Comment by henry-hz** [comment]
Hi :)  Does cast run remote debugging with custom source ? In the example below, it's possible to start the debugger in FUSE network without the need of Etherscan.

```
seth run-tx --debug 0xc3b63ab002d4a16fe95566a9c0816fab6cf07ac9867bd5ad1319095cef13b9a2 --source out/dapp.sol.json
```

**Comment by onbjerg** [comment]
I'm not entirely sure I understand - you want to optionally use local sources for decoding with `cast run`? I don't think this is currently possible - feel free to open up a feature request so we can track it better :)

**Comment by henry-hz** [comment]
@onbjerg exactly, many side-chains does not have direct support to retrieve the source code from etherscan, so adding the source code of the deployed contract on the path is how seth is doing.

**Comment by gakonst** [comment]
Makes sense - we don't have support for this yet, let's track in a separate feature issue (pls open one @henry-hz) and we can discuss there

**Comment by henry-hz** [comment]
Ok!
Done

https://github.com/foundry-rs/foundry/issues/1723

**Comment by onbjerg** [comment]
Closing, everything in here is implemented except `cast mktx` which is unplanned, and `cast events`/`cast accounts` that have separate issues
