### ISSUE TITLE
`forge script` allow for `try ... catch ... `

### ISSUE THREAD

**Issue by 0xPhaze** [foundry-rs/foundry#2905]
### Component

Forge

### Describe the feature you would like

It would be nice to allow for `try ... catch ...` statements in deploy scripts for simpler integration tests and deploy setups. Currently the script fails even when wrapping calls.

**Comment by mds1** [comment]
I was just able to run a script that had a try catch, so marking this completed. @0xPhaze if you still have this issue we can reopen, just provide steps to reproduce

```solidity
pragma solidity ^0.8.13;

import "forge-std/Script.sol";
import {Counter} from "src/Counter.sol";

contract CounterScript is Script {
    function setUp() public {}

    function run() public {
        vm.startBroadcast();
        Counter counter = new Counter();
        try counter.increment() {
            // I modified increment to always revert
        } catch {
            console.log("still worked"); // this got logged, script was successful
        }
    }
}
```
