### ISSUE TITLE
Expand the use of `vm.expectRevert`

### ISSUE THREAD

**Issue by pedrommaiaa** [foundry-rs/foundry#2909]
### Component

Forge

### Describe the feature you would like

`vm.expectRevert` only works with the next call.  Would be great if when specified with an error message e.g. `vm.expectRevert(bytes("SAFE_DEPOSIT_FAILED"))` vm.expectRevert could trace all the subsequent error messages until it reaches the one specified (or not in the case where it doesn't revert as expected).

### Additional context

In the image bellow I was using a library to call the `deposit()` function, I was expecting the call to fail, which would consequently make the function call from the library fail as well. I wanted to use `vm.expectRevert` to confirm that the function call from the library would fail as expected but  because `vm.expectRevert` could only catch the `"Arithmetic over/underflow"` error in this case there's not really a way for me ensure that the last error is `"SAFE_DEPOSIT_FAILED"`.

<img width="340" alt="Screen Shot 2022-08-23 at 4 28 56 PM" src="https://user-images.githubusercontent.com/100535780/186260215-c8684f14-ab41-4e62-bbd6-0f63017636ac.png">

**Comment by onbjerg** [comment]
That's not true; it would catch `TRANSFER_FROM_FAILED`. To be more precise, it only works for the next call *at the same depth* at which `expectRevert` was called, so it won't trigger on calls made from other calls, if that makes sense.

I'm not entirely sure where the `SAFE_DEPOSIT_FAILED` message comes from, but it looks like it is coming from the test itself? If so, this is not something we would be able to catch easily and would likely be an antipattern anyway. Can you post a snippet illustrating what the test is doing?

**Comment by pedrommaiaa** [comment]
It makes sense that it would be an anti-pattern. I found a work around the issue that I was having so I will close this for now.
