### ISSUE TITLE
Remember address of log emitters in `Log` (used in `getRecordedLogs`)

### ISSUE THREAD

**Issue by adhusson** [foundry-rs/foundry#2921]
### Component

Forge

### Describe the feature you would like

The `recordLogs/getRecordedLogs` functions would be more useful if `Log` had an `address emitter` field. Unless I'm missing something, as of now the feature doesn't let me fully implement #1906.

**Comment by onbjerg** [comment]
Should be added here: https://github.com/foundry-rs/foundry/blob/09a848cc7b7422ed4a2ec78ae1a72e7658ea22f7/evm/src/executor/inspector/cheatcodes/mod.rs#L230-L234 and the corresponding Solidity types.

We would likely need to swap out `RawLog` for something else since the `RawLog` type does not include the emitter address.

**Comment by Tirthnp** [comment]
@onbjerg I would like to work on this if it's available

**Comment by onbjerg** [comment]
Yep, feel free.

**Comment by Tirthnp** [comment]
I have two questions, What should we use instead of `RawLog`? What's the best way to test it?

**Comment by onbjerg** [comment]
You'd add a test in `testdata/cheats` similar to the ones already there - there is already a file for `getRecordedLogs` so you'd just extend/change that. There isn't really a nice alternative to `RawLog` in ethers, so you'd need to create a wrapper type like

```rs
struct Log {
  emitter: Address,
  inner: RawLog,
}
```

or something like that. You could also use a map of `address -> vec<RawLog>` but that would erase the order in which logs were emitted which we probably want to keep

**Comment by adhusson** [comment]
Any updates on this?

**Comment by odyslam** [comment]
If I understand the issue and the code correctly, the code checks the origin of an event emission against a user-defined address. 

Thus, should this issue close? @onbjerg @mattsse @gakonst

**Comment by mds1** [comment]
Completed by #3639
