### ISSUE TITLE
`forge test`/`forge script`: throw when ffi fails

### ISSUE THREAD

**Issue by 0xPhaze** [foundry-rs/foundry#2932]
### Component

Forge

### Describe the feature you would like

I would expect the script to halt and throw when `vm.ffi` fails. Currently it (almost) silently continues and prints "Script ran successfully."

**Comment by mattsse** [comment]
@onbjerg this came up here https://github.com/foundry-rs/foundry/pull/2520 as well.

from a DX perspective it'd be more convenient to simply print the error, even though it may not match the order of the test output

**Comment by cxkoda** [comment]
I'm facing a similar problem where all I'm interested in is the exit code of an external program.
For me it would be best if `ffi` returned something like `(bytes memory result, uint8 errno)`. Might be worth considering to generalize it even further and give the caller full control over the all outputs by returning something like  `(bytes memory stdout, bytes memory stderr, uint8 errno)` via a dedicated cheatcode? But that's a different discussion.

**Comment by mattsse** [comment]
I can see that this is useful, maybe we add a `tryFfi` cheatcode that returns both stdout and sterr @onbjerg ?

**Comment by gakonst** [comment]
Yeah supportive of `tryFfi` and returning the error code.
