### ISSUE TITLE
forge script not working for the Evmos Mainnet/Testnet environment

### ISSUE THREAD

**Issue by floberlin** [foundry-rs/foundry#2934]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9b0575e 2022-08-04T00:04:53.139072Z)

### What command(s) is the bug in?

forge script script/<name>.s.sol --rpc-url https://eth.bd.evmos.dev:8545 --private-key <pk> --broadcast

### Operating System

macOS (Apple Silicon)

### Describe the bug

I recently tried to deploy my forge script to Evmos. It does work flawlessly on Goerli, but not on the Evmos chains. For the exact same command I get different errors:

forge script script/<name>.s.sol --rpc-url https://eth.bd.evmos.dev:8545 --private-key <pk> --broadcast

The application panicked (crashed).
Message:  Unable to create fork: 
Failed to get block for block number: 4870151
latest block number: 4870151
Location: evm/src/executor/backend/mod.rs:287

No files changed, compilation skipped
The application panicked (crashed).
Message:  Failed to get account for 0x0000…0002
ProviderError(JsonRpcError(JsonRpcError { code: -32000, message: "rpc error: code = Unknown desc = cannot query with height in the future; please provide a valid height: invalid height", data: None }))
Location: evm/src/executor/fork/backend.rs:271

Error: 
ProviderError(JsonRpcError(JsonRpcError { code: -32000, message: "invalid nonce; got 49, expected 48: invalid sequence: invalid sequence", data: None }))

Workaround: Deploy the smart contracts manually which just worked fine.

**Comment by joeblau** [comment]
I ran into the same issue trying to deploy on EVMOS. I was able to solve this also by deploying the contract manually instead of using a script.

**Comment by zerosnacks** [comment]
Was able to deploy without an issue using:

```
forge script script/Counter.s.sol --rpc-url https://evmos-testnet-json.qubelabs.io --broadcast --keystore <KEYSTORE>
```

Transaction: https://www.mintscan.io/evmos-testnet/tx/0xd99e29a5a982f72eb7dca301afa1280ee31cfb0e6000208ddbda023c607e86e7?height=25729130&sector=message

Marking as resolved
