### ISSUE TITLE
Forge

### ISSUE THREAD

**Issue by wsdt** [foundry-rs/foundry#2942]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

ghcr.io/foundry-rs/foundry:nightly-b1f6a6cb023ce221e42d3c115c2f3fb05c2bf86f

### What command(s) is the bug in?

forge build

### Operating System

Linux

### Describe the bug

Using the docker build `ghcr.io/foundry-rs/foundry:nightly-b1f6a6cb023ce221e42d3c115c2f3fb05c2bf86f` (also tried the master, and others), 

but always receiving errors that the DSTest and Test assert-methods conflict with each other when trying to do an `assertEq` for example. 

Example: 
```solidity

// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.7;

import "forge-std/Test.sol";
import "../src/YourContract.sol";
import "forge-std/console2.sol";

contract YourContractTest is Test {
    YourContract wavectA;
   
    function setUp() public {
        
    }


    function testInit() public {
        assertEq("test","test");
   }
}
```

This fails saying, that there are overlaps for every assert-method.

**Comment by mattsse** [comment]
"test" is an ambiguous type here

"test" can be string and bytes

```solidity
     function testInit() public {
        string memory s = "test";
        bytes memory a = "test";
        assertEq(s, string(a));
   }
```
