### ISSUE TITLE
Unexpected Revert on Test

### ISSUE THREAD

**Issue by bthreader** [foundry-rs/foundry#2943]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (66ef1ae 2022-08-11T15:42:20.650087337Z)

### What command(s) is the bug in?

test

### Operating System

Linux

### Describe the bug

Reverting on a transfer command on a very simple contract. The contract is basically just a bank account where anyone can "topup" or "withdraw" from the balance:

```
contract Example {

    function topUp() external payable {}

    function withdraw(uint256 amount) external {
        require(
            amount <= address(this).balance,
            "Cannot withdraw more than is within the contract"
        );
        
        payable(msg.sender).transfer(amount);
    }
}
```

This is the test:

```
contract ExampleTest is Test {

    Example public account;
    address public acc1;

    constructor () {
        acc1 = address(0x1);
        account = new Example();
    }

    function testItWorks() public {
        vm.deal(acc1, 25);
        vm.startPrank(acc1);
        account.topUp{ value : 25 }();
        account.withdraw(25);
        vm.stopPrank();
    }
}
```

account.withdraw causes a reversion (unexpected), here are the traces:

```
Traces:
  [52308] ExampleTest::testItWorks() 
    ├─ [0] VM::deal(0x0000000000000000000000000000000000000001, 25) 
    │   └─ ← ()
    ├─ [0] VM::startPrank(0x0000000000000000000000000000000000000001) 
    │   └─ ← ()
    ├─ [96] Example::topUp{value: 25}() 
    │   └─ ← ()
    ├─ [34422] Example::withdraw(25) 
    │   ├─ [0] PRECOMPILE::ecrecover{value: 25}() 
    │   │   └─ ← 
    │   └─ ← "EvmError: Revert"
    └─ ← "EvmError: Revert"
```

 I have tried running with --debug but cannot seem to find what's causing the issue. I have deployed the contract and it works as expected. I'm confused because I have implemented similar functionality in other contracts and testing has gone fine.

Please let me know if I have made any errors with my testing and/or writing the contract.

Thanks,
Ben

**Comment by onbjerg** [comment]
You can't use `address(n)` where `n <= 10` since those are precompile addresses.
