### ISSUE TITLE
fuzzing should have a flag that avoids addresses with contracts

### ISSUE THREAD

**Issue by varunsrin** [foundry-rs/foundry#2946]
### Component

Forge

### Describe the feature you would like

When writing a fuzz test where the input is an address and the address sends money, the fuzz will usually fail if it the address is one of: 

```solidity
        address(0xCe71065D4017F316EC606Fe4422e11eB2c47c246), // FuzzerDict
        address(0x4e59b44847b379578588920cA78FbF26c0B4956C), // CREATE2 Factory (?)
        address(0xb4c79daB8f259C7Aee6E5b2Aa729821864227e84), // address(this)
        address(0x185a4dc360CE69bDCceE33b3784B0282f7961aea), // ???
        address(0x7109709ECfa91a80626fF3989D68f67F5b1DD12D) // ???
        address(0x9) // or other precompiles like 0x4
```

There are two problems: 

1. When some runs start failing, it's not immediately obvious to the user why these addresses fail and it takes some sleuthing around to figure it out 

2. Then you have to trial and error lots of times to figure out all the addresses that would fail and then exclude them. 

For 1, whenever we release fuzzer docs it would be nice to explain this somewhere that shows up in a google search result. 

For 2, it might be useful to have a flag that allows you to just avoid these as inputs. I don't think avoiding them should be the default behavior, because there may be cases when you genuinely want to fuzz them.

**Comment by onbjerg** [comment]
Previously we've discussed excluding them but ultimately it makes sense to include them since they're valid inputs (cc @mds1). The hard-to-debug failures related to these addreses + fuzzing is usually due to the address being passed into a cheatcode like `prank` which is what #1159 is about.

Given this, I vote to close the issue - what do you think?

**Comment by transmissions11** [comment]
agree with @onbjerg, filtering out contracts by default or even as an option is an antipattern. your code should handle contract addresses properly or explicitly state it does not via assume

**Comment by varunsrin** [comment]
on further reflection, i agree that it shouldn't be a flag. forcing you to `vm.assume` explicitly in code is much better for readability. 

i have some thoughts on #1159, will move discussion there.
