### ISSUE TITLE
Check verification status fails

### ISSUE THREAD

**Issue by nanjiangwill** [foundry-rs/foundry#2948]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (56dc746 2022-08-26T00:07:43.474069Z)

### What command(s) is the bug in?

forge verify-contract --chain-id 4 GUID ETHERSCAN_API_KEY

### Describe the bug

I successfully verify my contract with the following command: `forge verify-contract --chain-id 4 --compiler-version v0.8.10+commit.fc410830 <ADDRESS> src/<Contract>:<Token> <ETHERSCAN_API_KEY>` and I got "Response: OK" with GUID. However, when I tried to check the verification status with the command above, it would return 
`error: Invalid value "<GUID>" for '<ADDRESS>': Invalid character 'z' at position 3`

Can anyone answer this question?

**Comment by onbjerg** [comment]
The command you're looking for is `forge verify-check <GUID> --chain-id 4 --etherscan-key <key>

**Comment by nanjiangwill** [comment]
the error is still here 
`error: Found argument '--etherscan-key' which wasn't expected, or isn't valid in this context. If you tried to supply --etherscan-key as a value rather than a flag, use -- --etherscan-key`

**Comment by onbjerg** [comment]
Try `forge verify-check --chain-id 4 --etherscan-key <key> <GUID>`

**Comment by nanjiangwill** [comment]
I successfully verify my contract and get 
```
Submitted contract for verification:
        Response: `OK`
        GUID: `XXX`
        URL: XXX
```

But after I check the status, it says
`Waiting for verification result...
Contract verification failed:
Response: NOTOK
Details: Fail - Unable to verify`

**Comment by onbjerg** [comment]
Both responses are from the same API and both are from Etherscan, so we have no control over that. It seems like your contract was not verified and that the first response (from `forge verify-contract`) just means the verification request was accepted.

**Comment by joshieDo** [comment]
If your contract source code and/or compiler has changed in-between the time you deployed and the time you verify, you may be getting different bytecode leading to a verification error.

If that's not the issue, you might be forgetting to pass your libraries to the `verify-contract` command
