### ISSUE TITLE
Coverage report is showing uncovered code which has been tested correctly

### ISSUE THREAD

**Issue by kkx** [foundry-rs/foundry#2952]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6b3db2a 2022-08-19T00:24:19.967244Z)

### What command(s) is the bug in?

forge coverage

### Operating System

macOS (Apple Silicon)

### Describe the bug

forge coverage is not detecting correctly some require statements. 

this is what we get in coverall.io  after generating the lcov report.
<img width="1274" alt="Screenshot 2022-08-26 at 11 27 13" src="https://user-images.githubusercontent.com/1530467/186873619-88bea053-f828-4500-bd3f-f847ea55aa12.png">

However, we have implemented a test to especially cover this case
<img width="1343" alt="Screenshot 2022-08-26 at 11 29 25" src="https://user-images.githubusercontent.com/1530467/186874177-5faad67d-cba4-4320-85f8-7f4df20fffb0.png">

All tests are passed but it seems the coverage report is not generating correctly.

**Comment by onbjerg** [comment]
You are out of date, please update Foundry. A patch was recently released which fixes this. Let me know if it's still an issue after updating.
