### ISSUE TITLE
Fuzzing no longer deterministic 

### ISSUE THREAD

**Issue by RensR** [foundry-rs/foundry#2959]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (56dc746 2022-08-26T00:05:24.870934Z)

### What command(s) is the bug in?

forge snapshot

### Operating System

macOS (Apple Silicon)

### Describe the bug

Forge fuzz testing gas usage is no longer deterministic. Running `forge snapshot --diff` yields a different result each time. This breaks our CI as it relies on the snapshot diff.

**Comment by mattsse** [comment]
this was just fixed here https://github.com/foundry-rs/foundry/pull/2950

will land in next nightly.

sorry about that

**Comment by rkrasiuk** [comment]
yup, it was

**Comment by gakonst** [comment]
@transmissions11 fyi

**Comment by transmissions11** [comment]
amazing fix times as always, thank you kings
