### ISSUE TITLE
bug: invariant test log/traces not shown

### ISSUE THREAD

**Issue by mds1** [foundry-rs/foundry#2962]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (56dc746 2022-08-26T00:07:43.474069Z)

### What command(s) is the bug in?

forge test

### Describe the bug

Using the test contract, I am unable to view any of the console.logs for successful tests. Like fuzz tests, we should the trace of the last successful run if all runs pass.

```solidity
contract NonceCounter {
  uint256 public nonce = 1;

  function increment() public {
    nonce++;
  }
}

contract Test3 is Test {
  NonceCounter nonceCounter;
  uint256 lastNonce;

  function setUp() public {
    nonceCounter = new NonceCounter();
  }

  function invariant_NonceGoUp() external {
    console2.log('lastNonce: ', lastNonce);

    uint256 currentNonce = nonceCounter.nonce();
    console2.log('currentNonce: ', nonceCounter.nonce());

    require(currentNonce > lastNonce, "Invariant violated: Nonce did not increase");
    lastNonce = currentNonce;
  }
}
```

**Comment by shekhirin** [comment]
Should be fixed by https://github.com/foundry-rs/foundry/pull/3451
<img width="967" alt="image" src="https://user-images.githubusercontent.com/5773434/194334897-d99df02f-1a03-4831-9f00-d88ac6bddfd8.png">

**Comment by mds1** [comment]
Hmm how come in that screenshot the console logs for nonces 1–15 are not logged? Each call of the invariant test should increment it by 1, so it looks like that trace only shows the trace for the last run in the sequence? It also doesn't seem to show the calls to `increment()` in the trace

**Comment by mds1** [comment]
In other words, I'd expect two repeating parts of the trace:
- trace of setUp
- trace of execution of `invariant_NonceGoUp` (depth=0)
- trace of execution of first call made by fuzzer
- trace of execution of `invariant_NonceGoUp` (depth=1)
- trace of execution of second call made by fuzzer
- etc.

**Comment by lucas-manuel** [comment]
Yes this would be very helpful for debugging.
