### ISSUE TITLE
bug: invariant test chooses contract senders which are rejected due to EIP-3607

### ISSUE THREAD

**Issue by mds1** [foundry-rs/foundry#2963]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (56dc746 2022-08-26T00:07:43.474069Z)

### What command(s) is the bug in?

forge test

### Describe the bug

Using the same test contract as https://github.com/foundry-rs/foundry/issues/2962, sometimes the sender will be a contract chosen from the dictionary. In that case the call reverts with `[FAIL. Reason: EvmError: RejectCallerWithCode]` due to EIP-3607, similar to https://github.com/foundry-rs/foundry/pull/2090

IMO the ideal solution here is to bypass 3607 since the `msg.sender` can have code, and this is referring to the fact that `tx.origin` cannot have code which isn't too relevant for invariant tests.

**Comment by gakonst** [comment]
Yeah implementing the same fix as #2090 here makes sense.

**Comment by gakonst** [comment]
@mattsse can you pls take a look tomorrow on this? should be simple fix and apparently a big issue for invariant users

**Comment by PaulRBerg** [comment]
Can confirm that this is a big pain when testing invariants.

What is the fix until this issue gets fixed? Exclude all known contracts with [`excludeSender`](https://github.com/foundry-rs/forge-std/blob/0aa99eb8456693c015350c5e6c4f442ebe912f77/src/InvariantTest.sol#L30)?

**Comment by PaulRBerg** [comment]
Looks like #4181 has been merged. Should this issue be closed now?

**Comment by mattsse** [comment]
it's not on foundryup yet, but I'm cutting a release now manually

**Comment by PaulRBerg** [comment]
Oh, I see, thanks.

**Comment by PaulRBerg** [comment]
@mattsse looks like this is fixed now. I updated via `foundryup` recently, removed my `targetSender` call, and my invariant tests passed.
