### ISSUE TITLE
Output of Metadata by default "broke" compatibility with typechain tool

### ISSUE THREAD

**Issue by tfalencar** [foundry-rs/foundry#2969]
### Component

Forge

### Describe the feature you would like

As of https://github.com/foundry-rs/foundry/pull/2798, typechain can no longer process the "out" abi folder: "Error occured: Not a valid ABI". 

If there is no simple way around this, I would suggest adding a flag/option to disable its output. Alternatively, keep this data in a separate folder, so that it doesn't get mixed with the ABI files in the "glob" typechain parameter.

**Comment by mattsse** [comment]
yeh let's revert this @rkrasiuk

**Comment by tfalencar** [comment]
It looks like hardhat's implementation puts the metadata into a separate folder: artifacts/build-info

https://github.com/NomicFoundation/hardhat/pull/1863
