### ISSUE TITLE
fuzzer does not respect fuzz_runs configuration

### ISSUE THREAD

**Issue by varunsrin** [foundry-rs/foundry#2972]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (65ca7e8 2022-08-26T19:01:34.828764Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

Running `FOUNDRY_FUZZ_RUNS=1000 forge test` or setting `fuzz_runs = 1_000` under [profile.default] in foundry.toml and running `forge test` still results in 256 runs.

Seems to be similar to a previously closed issue: https://github.com/foundry-rs/foundry/issues/590

**Comment by joshieDo** [comment]
New changes have been very recently made: https://github.com/foundry-rs/foundry/pull/2882

Check here the new syntax:
https://github.com/foundry-rs/foundry/blob/master/config/README.md#all-options
