### ISSUE TITLE
Checksum address output in `log_address` event and `broadcast` files

### ISSUE THREAD

**Issue by ckoopmann** [foundry-rs/foundry#2975]
### Component

Forge

### Describe the feature you would like

# Current Behaviour 
Addresses emitted in `log` events as well as `broadcast` json-files are not checksumed.
This leads to compiler errors when copy pasting this address back into a script etc.

While there is a workaround using `forge fmt` this is suboptimal since it introduces another unnecessary command / step and also negates the original purpose of checksums protecting against accidental modification of the value.

# Proposed Behaviour
Emit only checksummed addresses both in log events as well as broadcast json-files. 

### Additional context

Can be seen as an extension of: https://github.com/foundry-rs/foundry/issues/2674

**Comment by tgfukuda** [comment]
Is it ok to try this issue?
