### ISSUE TITLE
Error:  Failed to create wallet from private key: signature error

### ISSUE THREAD

**Issue by 0xc25fee20** [foundry-rs/foundry#2978]
### Component

Forge, Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (bf8a612 2022-08-26T19:22:03.6751305Z)

### What command(s) is the bug in?

forge script script/Counter.s.sol:CounterScript --fork-url http://localhost:8545 --private-key $PRIV_KEY --broadcast

### Operating System

Windows

### Describe the bug

"anvil" is running in the backend and the environment variable "PRIV_KEY" is right with no "^M", "0x" or not. 

It's showing "Connection header did not include 'upgrade'" in the page  when I open http://127.0.0.1:8545/. 

It returns "Error:  Failed to create wallet from private key: signature error" when I type the command "forge script script/Counter.s.sol:CounterScript --fork-url http://localhost:8545 --private-key $PRIV_KEY --broadcast".

**Comment by grp06** [comment]
What was the resolution here? I'm having the same issue with the latest version of forge (0.2.0)

**Comment by gakonst** [comment]
@grp06 does this still happen on latest foundryup?

**Comment by nonogakhi** [comment]
Yes I confirm having the same problem. I got the PK from anvil

**Comment by nonogakhi** [comment]
In my case I was missing the $ to refer the PRIVATE_KEY environment variable from the .env file

**Comment by mattsse** [comment]
I see, perhaps we should check this for the error message?

**Comment by onbjerg** [comment]
Closed in #3270
