### ISSUE TITLE
Bug: cache does not work in some cases

### ISSUE THREAD

**Issue by minaminao** [foundry-rs/foundry#2983]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (7278695 2022-08-27T00:10:44.256931Z)

### What command(s) is the bug in?

forge build

### Operating System

macOS (Intel)

### Describe the bug

The default repo generated by `forge init`:
```
$ forge build
[⠢] Compiling...
[⠢] Compiling 9 files with 0.8.16
[⠔] Solc 0.8.16 finished in 1.95s
Compiler run successful
$ forge build
[⠔] Compiling...
No files changed, compilation skipped
```

My repo https://github.com/minaminao/ctf-blockchain (e.g., commit: 82dcc110e4da3a6c696e0ca70f0ee3f6642ad8f1):
```
$ forge build
Missing dependencies found. Installing now.

[⠘] Compiling...
[⠃] Compiling 2 files with 0.5.17
[⠊] Compiling 14 files with 0.7.6
[⠢] Compiling 241 files with 0.8.16
[⠢] Solc 0.5.17 finished in 37.96ms
[⠑] Solc 0.7.6 finished in 2.03s
[⠘] Solc 0.8.16 finished in 17.86s
Compiler run successful (with warnings)

(warnings)

$ forge build
[⠔] Compiling...
[⠑] Compiling 95 files with 0.8.16
[⠃] Solc 0.8.16 finished in 17.64s
Compiler run successful (with warnings)

(warnings)

$ forge build
[⠑] Compiling...
[⠃] Compiling 101 files with 0.8.16
[⠢] Solc 0.8.16 finished in 18.62s
Compiler run successful (with warnings)

(warnings)

$ forge build
[⠔] Compiling...
[⠆] Compiling 6 files with 0.7.6
[⠃] Solc 0.7.6 finished in 1.72s
Compiler run successful
```

As shown above, the recompilation runs even though no files have been changed, and the target files to be recompiled are different each time.
I do not know the cause of this problem.

**Comment by minaminao** [comment]
After a little experimentation today, it appears that this is due to an unstable automatic selection of the Solidity versions.

**Comment by CarterAppleton** [comment]
We're experiencing this same issue in our repo with multiple sol versions, is there any update on this?

**Comment by CarterAppleton** [comment]
I think this is fixed as of https://github.com/foundry-rs/foundry/pull/4330
