### ISSUE TITLE
Panic when run `vm.revertTo`

### ISSUE THREAD

**Issue by Loverush** [foundry-rs/foundry#2984]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (7278695 2022-08-27T00:28:29.89913Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

```
Message:  called `Option::unwrap()` on a `None` value
Location: /Users/runner/.cargo/git/checkouts/revm-ff7cf6bd6b8a0be0/b8157b7/crates/revm/src/evm_impl.rs:226
```
I make a snapshot and when I call revertTo, it panics

**Comment by Loverush** [comment]
Roughly I done this:
1. run a fork node on BSC mainnet by hardhat
2. set foundry's rpc rul to hardhat node's port
3. run `vm.createSelectFork(RPC, SOME_HEIGHT)` on test's constructor and do some operation (by the way, I did not run this directly on bsc mainnat's rpc endpoint. Because that will not work. Maybe the archive node has some problems. I don't know. Anyway I have to do this on a local fork node)
4. record the snapshot by the end of the snapshot
5. put `vm.revertTo` in setUp
6. forge test => panic

**Comment by mattsse** [comment]
can confirm, this is a bug, fixing it
