### ISSUE TITLE
forge coverage false negative with if statement + return 

### ISSUE THREAD

**Issue by varunsrin** [foundry-rs/foundry#2993]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (f8fe940 2022-08-28T00:04:47.679845Z)

### What command(s) is the bug in?

forge coverage

### Operating System

macOS (Apple Silicon)

### Describe the bug

forge coverage incorrectly detects an if-statement as partially covered despite both branches being triggered by tests. it might be caused by one of the compared values being an item from an array.  

can be reproduced with: 

```solidity
pragma solidity ^0.8.16;

import "forge-std/Test.sol";

contract CoverageContractTest is Test {
    CoverageContract private coverageContract;

    function setUp() public {
        coverageContract = new CoverageContract();
    }

    function testCompareTs() public {
        assertEq(coverageContract.compareTs(1640995199), 1);
        assertEq(coverageContract.compareTs(1640995200), 0);
    }
}

contract CoverageContract {
    uint256[1] private timestamps = [1640995200];

    function compareTs(uint256 timestamp) public view returns (uint256) {
        if (timestamp < timestamps[0]) {
            return 1;
        }

        return 0;
    }
}
```

_edit: updated with simpler examples_

**Comment by yanisepfl** [comment]
Hello,

I am having the exact same issue on my side, using the same Foundry version. 

Looking forward having an explanation / fix on this!
