### ISSUE TITLE
forge verify-contract is unable to verify

### ISSUE THREAD

**Issue by defijesus** [foundry-rs/foundry#2996]
Foundry can't verify this contract. This contract was deployed by running `make deploy`. Trying to verify directly on Etherscan with same build config also doesn't work. Trying to build and verify using Remix also doesn't work. Am I stoned, or is this gods work?

The Foundry version is updated to latest using foundryup.
The platform you are on: M1 Mac
Code snippets: This [repo](https://github.com/defijesus/aave-risk-param-updates-fei) has a single contract with no imports.
Concrete steps to reproduce the bug: make verify

More info:
```
~/.svm/0.8.11/solc-0.8.11 --version
solc, the solidity compiler commandline interface
Version: 0.8.11+commit.d7f03943.Darwin.appleclang
```

papa bless ☀️

**Comment by rkrasiuk** [comment]
@defijesus could you give some more context, please - which version of foundry are you using, how were you deploying the contracts and how did you resolve version incompatibility between contracts?
here's the deployed & verified contract using `forge create --verify ...`
https://goerli.etherscan.io/address/0xa7113f460ef29e93c67cbd0788e7a62af80a7b47#code

**Comment by defijesus** [comment]
Hey, sure thing.

> forge 0.2.0 (307576d 2022-08-29T00:05:05.72678Z)
> cast 0.2.0 (307576d 2022-08-29T00:05:05.72678Z)

I deployed by running the FeiRiskParamsUpdatePayload.s.sol script.

**Comment by rkrasiuk** [comment]
@defijesus same story. after i resolved version incompatibility and stack too deep errors, i ran the following command and got the contract verified
```sh
forge script script/FeiRiskParamsUpdatePayload.s.sol --verify --fork-url <rpc-url> --broadcast --sender <sender> --private-key $PRIVATE_KEY 
```
https://goerli.etherscan.io/address/0xD77644A6B0B5B3e330B30531Df3456c2bBe64F81

**Comment by rkrasiuk** [comment]
ah, it's the usual suspect - `via-ir`

**Comment by defijesus** [comment]
gl & hf 🫡

**Comment by rkrasiuk** [comment]
@defijesus should be fixed now. feel free to reopen if the issue persists
