### ISSUE TITLE
Gas tracks failed

### ISSUE THREAD

**Issue by Pythonberg1997** [foundry-rs/foundry#2999]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (307576d 2022-08-29T00:05:05.72678Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

I report issue#2984. After upgrade by foundryup, `revertTo` works well. But when I use the same config as mentioned in #2984, the gas output are all zero like below:
```
[PASS] testClaimReward() (gas: 0)
[PASS] testReceive(uint256) (runs: 1024, μ: 0, ~: 0)
```

**Comment by Loverush** [comment]
After more tests I found that it's not gas tracking failed. It's the whole test not run at all (so it's always 0)
