### ISSUE TITLE
forge test: `EOF while parsing a value at line 1 column 0`

### ISSUE THREAD

**Issue by 0xSidius** [foundry-rs/foundry#3016]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (fb1f0aa 2022-08-30T00:07:22.068532454Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

Hello,

I upgraded to latest Foundry bins, and seemed to work as usual, however I just started getting the error `EOF while parsing a value at line 1 column 0` with the `forge test` command, compilation works fine.

Tried cleaning artifacts and re-installing Foundry bins and submodules again.

**Comment by 0xSidius** [comment]
@gakonst @onbjerg I was reading through this older issue: https://github.com/foundry-rs/foundry/issues/209 with the same problem (e.g. the actual error output being obscured by `EOF while parsing a value at line 1 column 0`, however for me compilation ends successfully, I can confirm it succeed by running `forge build` or `forge test` with `RUST_LOG=ethers=trace`

![image](https://user-images.githubusercontent.com/100469911/187435279-99fe3850-a71e-4e2e-9e32-7ed0a98b60d9.png)

**Comment by mattsse** [comment]
is there a way to reproduce this?

**Comment by 0xSidius** [comment]
> is there a way to reproduce this?

not that I could find... if I run tests from docker I don't get the error, otherwise I will get it regardless of setup/repo, so I assume it has to do with my machine somehow. I re-installed Rust, re-cloned the repo, etc.

maybe there are other traces I can try? I would like to know what the hidden error is

**Comment by gakonst** [comment]
Try `RUST_LOG=trace`, it might be more verbose but may find you something more. We can't do much without a repro/steps to repro unfortunately :(

**Comment by 0xSidius** [comment]
> Try `RUST_LOG=trace`, it might be more verbose but may find you something more. We can't do much without a repro/steps to repro unfortunately :(

I know, so I tried with the suggested trace and while there are more logs before it, it did not reveal anything extra about the issue (which appears to come immediately after compilation step)

![image](https://user-images.githubusercontent.com/100469911/187639874-61628d27-b779-4582-b8b1-a0e5e5c27901.png)

**Comment by mattsse** [comment]
you're using the etherscan url as rpc url?

**Comment by 0xSidius** [comment]
> you're using the etherscan url as rpc url?

I am not using any env vars, nor configured foundry.toml in that regard. So idk why forge is picking it up like that, and if it's intended behavior

**Comment by mattsse** [comment]
oh I misread this.

so it appears this is a deserialize error of an empty payload that happens as soon as test start.

what's your `forge config`?

**Comment by mattsse** [comment]
could you dump output of `forge config` as well?

**Comment by 0xSidius** [comment]
> could you dump output of `forge config` as well?

```
[profile.default]
src = 'contracts/solidity'
test = 'tests/solidity/foundry'
script = 'script'
out = 'forge_artifacts'
libs = [
    'node_modules',
    'libs/solidity/foundry',
]
remappings = [
    '@openzeppelin/=node_modules/@openzeppelin/',
    'ds-test/=libs/solidity/foundry/forge-std/lib/ds-test/src/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'forge-std/=libs/solidity/foundry/forge-std/src/',
    'hardhat-deploy/=node_modules/hardhat-deploy/',
    'hardhat/=node_modules/hardhat/',
    'solmate/=node_modules/solmate/src/',
]
auto_detect_remappings = true
libraries = []
cache = true
cache_path = 'forge_cache'
broadcast = 'broadcast'
allow_paths = []
include_paths = []
force = false
evm_version = 'london'
gas_reports = ['*']
gas_reports_ignore = []
auto_detect_solc = true
offline = false
optimizer = true
optimizer_runs = 999999
verbosity = 3
etherscan_api_key = '95V63MGEIXS3R4NSBSN7WJAUC2TMA6G4RJ'
ignored_error_codes = [
    1878,
    5574,
]
fs_permissions = []
build_info = false
ffi = false
sender = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
tx_origin = '0x00a329c0648769a73afac7f9381e08fb43dbea72'
initial_balance = '0xffffffffffffffffffffffff'
block_number = 1
gas_limit = 9223372036854775807
block_base_fee_per_gas = 0
block_coinbase = '0x0000000000000000000000000000000000000000'
block_timestamp = 1
block_difficulty = 0
memory_limit = 33554432
extra_output = []
extra_output_files = []
names = false
sizes = false
via_ir = false
no_storage_caching = false
bytecode_hash = 'ipfs'
sparse_mode = false

[profile.default.rpc_storage_caching]
chains = 'all'
endpoints = 'all'

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = 'long'
func_attrs_with_params_multiline = true
quote_style = 'double'
number_underscore = 'preserve'

[fuzz]
runs = 256
max_local_rejects = 1024
max_global_rejects = 65536
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[invariant]
runs = 256
depth = 15
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true
```

**Comment by mattsse** [comment]
is this still happening?

could you please try running again with

`RUST_LOG=forge,foundry_evm,backend forge ...`

and share the logs?

and try after removing the etherscan API key

**Comment by 0xSidius** [comment]
I removed the etherscan api key (it was being picked up and set as env by the Hardhat config), and ofc it's still happening...

this is the output of `forge test` with your traces:

![image](https://user-images.githubusercontent.com/100469911/188460995-9b3efa81-c134-499b-920c-9413de33a8ec.png)

**Comment by mattsse** [comment]
is this public? would need to manually debug this I'm afraid

**Comment by mattsse** [comment]
okay I have an idea,

could you try after nuking `~/.foundry/cache`?

**Comment by 0xSidius** [comment]
> okay I have an idea,
> 
> could you try after nuking `~/.foundry/cache`?

awesome, it worked, ty!

**Comment by mattsse** [comment]
so the issue was a bad cache file, will fix the error and make this a noop

**Comment by miohtama** [comment]
For future reference, I got this error when I ran `forge` in a parent directly, instead of my project directory.

**Comment by joeleonjr** [comment]
Hi! I'm a security researcher @TruffleSecurity. I found a valid API key leaked in a comment in this Issue. I highly recommend rotating the API key immediately (not just deleting the comment). Here's a blog post I wrote on remediating these types of vulnerabilities: https://trufflesecurity.com/blog/remediate-leaked-api-keys-with-key-rotation.<br><br>If you can't find the leaked API key, you can use the following [TruffleHog](https://github.com/trufflesecurity/trufflehog) command to automatically scan for it:<br>`trufflehog github --repo https://github.com/<your_username>/<your_reponame> --issue-comments --only-verified`<br><br>If it's not clear where/what the security issue is, please let me know. I'd be happy to help. Please note that the API key might be in the past edit of a comment.<br><br><br><br>(cc @0xSidius)
