### ISSUE TITLE
Deserialization Error

### ISSUE THREAD

**Issue by sangdon** [foundry-rs/foundry#3019]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (307576d 2022-08-29T00:07:45.577911054Z)

### What command(s) is the bug in?

forge script

### Operating System

Linux

### Describe the bug

Hi There, 

I was running `forge script` over a forked network (from alchemy). In particular, I execute `forge script` for every 4 seconds, and mostly it is okay but sometimes I got the following. 

```
The application panicked (crashed).
Message:  Failed to get account for 0xc7f2…e141
Deserialization Error: expected value at line 1 column 1. Response: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>

Location: evm/src/executor/fork/backend.rs:271

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry
```

I'm not familiar with a bug reporting, but hope this help.

**Comment by mattsse** [comment]
this just looks like an issue with the connection that was established, 

perhaps the provider temporarily blocked requests, wasn't able to handle them

**Comment by mattsse** [comment]
I actually just got the same issue with alchemy

**Comment by rkrasiuk** [comment]
@mattsse shall we close this as extraneous failure or improve error handling the fork provider requests?

**Comment by mattsse** [comment]
can close, I think this was an alchemy issue because I noticed this myself at least twice within 1 min or so
