### ISSUE TITLE
Debugger output on a log file 

### ISSUE THREAD

**Issue by shresthagrawal** [foundry-rs/foundry#3030]
### Component

Cast

### Describe the feature you would like

I am trying to compare two EVM executions using `cast run --debug`; it is hard to do that on the interactive terminal debugger. 

Is there a way to log all the EVM execution opcodes, stack and memory on the terminal/file? So basically what the debugger already shows but without the whole interactive terminal. 

If this is a feature that might not be interesting to add generally to `cast`, feel free to suggest to me a hacky way to get this info

**Comment by rouzwelt** [comment]
any update about this?

**Comment by zerosnacks** [comment]
Marking as covered by https://github.com/foundry-rs/foundry/issues/7364 + https://github.com/foundry-rs/foundry/issues/7112

Related PR: https://github.com/foundry-rs/foundry/pull/7375

**Comment by rouzwelt** [comment]
i would say if it is not going to be persued, at least make the current interactive debugger panel to be able to copy stuff from, atm there is no way to for example copy a part of memory or storage bytes from the debugger, would be nice to have that

**Comment by zerosnacks** [comment]
It is being persued in https://github.com/foundry-rs/foundry/pull/7375 which hopefully will add a keybinding as well to dump to a file from the interactive debugger, not just by flag. See: https://github.com/foundry-rs/foundry/pull/7375#issuecomment-2260301676
