### ISSUE TITLE
vm.expectCall / Spy on a mock

### ISSUE THREAD

**Issue by RickVM** [foundry-rs/foundry#3034]
### Component

Forge

### Describe the feature you would like

Given contract A and contract B

Contract a has a function that calls contract b

```
 function foo() public {
        b.updateStuff();
        // Proceed doing other things
    }
```

I would like a function similar to how mockCall operates, that allows me to test if function a.foo has called function b.updateStuff

```
        vm.expectCall(
            addressOfB,
            abi.encodeWithSelector(
                b.updateStuff.selector
            )
        );
```

### Additional context
You can work around this by emitting events and using expectEmit for now

**Comment by onbjerg** [comment]
Already exists, with that exact name :) https://book.getfoundry.sh/cheatcodes/expect-call
