### ISSUE TITLE
Anvil returns block information from archive node for unmined blocks

### ISSUE THREAD

**Issue by Natanela** [foundry-rs/foundry#3037]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What command(s) is the bug in?

eth_getBlockByNumber

### Describe the bug

Hi, we are using the latest docker Anvil version, and we notice a difference between Hardhat and Anvil behavior when fetching block by number (`eth_getBlockByNumber`) of unmined blocks.

When forking from a specific block number and querying about a block that wasn't mined yet on the fork, Anvil returns the block information from the archive node passed by the `--fork-url` option, while Hardhat returns null.

### Code example
the same code was executed agains Hardhat and anvil forked Ethereum mainnet from block `15006971` without executing any transactions on the fork.

```typescript
  const provider = new ethers.providers.JsonRpcProvider("http://127.0.0.1:8545");

  const currentBlock = await provider.getBlockNumber();
  console.log(`current block ${currentBlock}`);

  const blockNumberInFuture = currentBlock + 10;
  const blockInFuture = await provider.getBlockWithTransactions(blockNumberInFuture);
  console.log(`${blockInFuture.transactions.length}  transactions for block ${blockNumberInFuture}`);
```

**Hardhat output**:
`getBlockWithTransactions` call returns null.
```
current block 15006971
TypeError: Cannot read property 'transactions' of null
```

**Anvil output**:
```
current block 15006971
408 transactions for block 15006981
```
Block 15006981 had indeed [408 transactions on mainnet](https://etherscan.io/block/15006981)

**Comment by mattsse** [comment]
this is indeed a bug due to missing fork check, fixing
