### ISSUE TITLE
feat: support traces and debugging in `cast call`

### ISSUE THREAD

**Issue by mds1** [foundry-rs/foundry#3038]
### Component

Forge

### Describe the feature you would like

Sometimes a call can revert, and being able to see a trace or use the debugger to understand why is useful.  The UX here would be adding `--trace` or `--debug` flags to `cast call`

Right now you can probably work around this by starting anvil from a fork, using `cast send` to send a tx to anvil, then inspecting the failed tx with `cast run`

**Comment by onbjerg** [comment]
imo this is what `cast run` is for

**Comment by Divide-By-0** [comment]
it would be cool to also do this for `cast send`, since sometime when it fails it refuses to even send.

**Comment by yash-atreya** [comment]
@onbjerg I suppose this can be closed. Ref: #5477
