### ISSUE TITLE
Can not change the cast call sender

### ISSUE THREAD

**Issue by KittyFu307** [foundry-rs/foundry#3049]
### Component

Cast

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (20e7386 2022-08-31T00:09:48.876171Z)

### What command(s) is the bug in?

cast call

### Operating System

macOS (Apple Silicon)

### Describe the bug

I was trying to use "cast call" command to call my contracts function, I want to change the caller so that it can match the contract owner. I was trying to use command like this :
```  cast call [address] [function] [param]  -- --sender=[sender address] --private-key=[private-key] ```
but it is not change the cast call sender

**Comment by onbjerg** [comment]
Anything after `-- ` is interpreted as not being an option, so you need to restructure your command like so:

```
cast call --sender <sender addr> <addr> <func> <params>
```
