### ISSUE TITLE
Fresh windows 10 install - ErrorHook issue

### ISSUE THREAD

**Issue by k2riddim** [foundry-rs/foundry#3050]
After using rustup and the following cmd >
- cargo install --git https://github.com/foundry-rs/foundry foundry-cli anvil --bins --locked

when trying cmd > 
- forge init hello_foundry

I get :
Error: cannot install provided ErrorHook, a hook has already been installed

Location:
    cli\src\handler.rs:62:9

**Comment by mattsse** [comment]
any luck debugging this @k2riddim ?

**Comment by k2riddim** [comment]
hey, no sorry, I had to install wsl

**Comment by DaniPopes** [comment]
Could reproduce, Windows 10 with a fresh VS 2022 install and using the same command as OP:
```powershell
PS C:\Users\Daniel> forge -V
Error: cannot install provided ErrorHook, a hook has already been installed

Location:
    cli\src\handler.rs:62:9
PS C:\Users\Daniel> cast -V
Error: cannot install provided ErrorHook, a hook has already been installed

Location:
    cli\src\handler.rs:62:9
PS C:\Users\Daniel> anvil -V
anvil 0.1.0 (76be373 2022-09-06T19:36:52.9230886Z)
PS C:\Users\Daniel> rustup -V
rustup 1.25.1 (bb60b1e89 2022-07-12)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.63.0 (4b91a6ea7 2022-08-08)`
```

Although building from source works just fine:
```powershell
PS C:\Users\Daniel\Documents\GitHub\foundry-rs\foundry> cargo run --bin forge -- -V
    Finished dev [unoptimized] target(s) in 0.59s
     Running `target\debug\forge.exe -V`
forge 0.2.0 (a78aa49 2022-09-06T19:54:43.4517457Z)
```

**Comment by mattsse** [comment]
this doesn't make any sense...

**Comment by DaniPopes** [comment]
`cast install --path .\cli\ foundry-cli --bins --locked`, same command as OP but using local Foundry repo works:
```powershell
    Replaced package `foundry-cli v0.2.0 (https://github.com/foundry-rs/foundry#76be373d)` with `foundry-cli v0.2.0 (C:\Users\Daniel\Documents\GitHub\foundry-rs\foundry\cli)` (executables `cast.exe`, `forge.exe`)
PS C:\Users\Daniel\Documents\GitHub\foundry-rs\foundry> forge -V
forge 0.2.0 (a78aa49 2022-09-06T20:12:12.3499251Z)
```

**Comment by Elyx0** [comment]
What could be added to docs is `rustup update` for windows that fixed it for me

**Comment by mattsse** [comment]
hmm perhaps this is an issue with _older_ rust versions, but still doesn't make much sense, since there's no call before 

https://github.com/foundry-rs/foundry/blob/48d5d79a63acbd5cb454d39fa0c01c297de89559/cli/src/handler.rs#L62

that sets this...

**Comment by juanfranblanco** [comment]
I have replicated this, and I am still having the same issues, tried using different versions of Rust beta and nightly. Also installed from github and using OP commands. Workaround is to use WSL or MINGW64, but not ideal.

**Comment by mattsse** [comment]
this is so weird to me ...

I guess we could make this not a hard error in windows as a workaround

**Comment by mattsse** [comment]
perhaps this is related https://github.com/rust-lang/rust/issues/81408

**Comment by juanfranblanco** [comment]
@mattsse i removed the hook locally and is all good, so your fix does the trick

**Comment by xphoniex** [comment]
I ran into the same issue but instead of a fresh windows 10 os, I'm running linux.

You should be able to reproduce it using a VM or something. Compile from [67ef930](https://github.com/foundry-rs/foundry/commit/67ef930378973965db589b7c5e8c8860ba79f475) and move binaries to the new VM:

```
$ cast
Error: cannot install provided ErrorHook, a hook has already been installed

Location:
cli\src\handler.rs:70:13
```

**Comment by xphoniex** [comment]
I tried by setting `FOUNDRY_DEBUG` still no luck:
```
$ FOUNDRY_DEBUG= ./cast -V
Error: cannot install provided ErrorHook, a hook has already been installed

Location:
    /home/user/.cargo/registry/src/github.com-.../color-eyre-0.6.1/src/config.rs:686.9
```

it also ends up calling [`eyre_hook.install()?`](https://github.com/yaahc/color-eyre/blob/v0.6.1/src/config.rs#L686), any idea how to fix this @mattsse ?

**Comment by leovct** [comment]
Same thing happened to me using a `debian` container: `anvil` works fine but not `forge` and `cast`.
The solution was simply to install `git`.

```Dockerfile
FROM debian:bullseye-slim as foundry-install
RUN apt-get update -y && apt-get install -y curl git unzip wget
RUN curl -L https://foundry.paradigm.xyz | bash
RUN /root/.foundry/bin/foundryup
RUN cp -r /root/.foundry/bin/* /usr/local/bin

FROM debian:bookworm-slim
# RUN apt-get update -y && apt-get install -y git # solution
COPY --from=foundry-install /usr/local/bin /usr/local/bin
```

```sh
$ root@status:/# forge --version
bash: forge: command not found

$ root@status:/# cast --version
Error: cannot install provided ErrorHook, a hook has already been installed

Location:
    cli/src/handler.rs:70:13

$ anvil
# works as expected
```

**Comment by llllvvuu** [comment]
> Same thing happened to me using a `debian` container: `anvil` works fine but not `forge` and `cast`. The solution was simply to install `git`.
> 
> ```dockerfile
> FROM debian:bullseye-slim as foundry-install
> RUN apt-get update -y && apt-get install -y curl git unzip wget
> RUN curl -L https://foundry.paradigm.xyz | bash
> RUN /root/.foundry/bin/foundryup
> RUN cp -r /root/.foundry/bin/* /usr/local/bin
> 
> FROM debian:bookworm-slim
> # RUN apt-get update -y && apt-get install -y git # solution
> COPY --from=foundry-install /usr/local/bin /usr/local/bin
> ```
> 
> ```shell
> $ root@status:/# forge --version
> bash: forge: command not found
> 
> $ root@status:/# cast --version
> Error: cannot install provided ErrorHook, a hook has already been installed
> 
> Location:
>     cli/src/handler.rs:70:13
> 
> $ anvil
> # works as expected
> ```

Thanks, this works on Alpine too. Strange error message but it makes sense since I guess git is used to search for the foundry.toml

**Comment by pipaman** [comment]
This issue is not letting me use the tool in an airgapped computer. It is a pity since the tool is really good.
