### ISSUE TITLE
Contract is not visible on etherscan if deployed through factory contract

### ISSUE THREAD

**Issue by nduchak** [foundry-rs/foundry#3056]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

0.2.0

### What command(s) is the bug in?

cast send --gas-limit 20000000 --json  0x0aaA1E0f026c194E0F951a7763F9edc796c6eDeE newAuthGemJoin\(address\,bytes32\,address\) 0x5DCdbD3cCF9B09EAAD03bc5f50fA2B3d3ACA0121 0x5257413030374154322d41000000000000000000000000000000000000000000 0x88f1953f1839D0A2F81DC30482AE8b631F7DF376

### Operating System

macOS (Intel)

### Describe the bug

When I call contract method which creates another contract this contract is not visible on etherscan (Goerli). 
This issue start only after I update to the latest version

**Comment by rkrasiuk** [comment]
@nduchak did tx actually succeed? if so, could you provide the hash?

**Comment by rkrasiuk** [comment]
huh, i can confirm
Tx: https://goerli.etherscan.io/tx/0xa351a79dfc533b4a0533da622dd741e6b9f72b38ac45fbe71c19b2535e228894
contract page is empty, but if you run `cast code 0xac2eccaf266c74b18b12ba008cd9df755f8eae95`, it will give you the bytecode.
unfortunately, I doubt that we can help you anyhow here. try contacting etherscan support

**Comment by nduchak** [comment]
> huh, i can confirm Tx: https://goerli.etherscan.io/tx/0xa351a79dfc533b4a0533da622dd741e6b9f72b38ac45fbe71c19b2535e228894 contract section is empty, but if you run `cast code 0xac2eccaf266c74b18b12ba008cd9df755f8eae95`, it will give you the bytecode. unfortunately, I doubt that we can help you anyhow here. try contacting etherscan support

Thanks, it was a bug of Etherscan. Now it's working
