### ISSUE TITLE
Forge coverage compilation fails, while compilation works by itself

### ISSUE THREAD

**Issue by FredCoen** [foundry-rs/foundry#3059]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (48d5d79 2022-09-01T00:04:25.075512Z)

### Describe the bug

We are able to compile our foundry project with ```forge build```

However we are unable to run forge coverage as it throws a compilation error screenshoted below.

What is surprising is that it states solc compilation finished but but still throws a compilation error. Is that some forge internal thing?

<img width="1054" alt="Screenshot 2022-09-02 at 10 40 23" src="https://user-images.githubusercontent.com/43670554/188100521-f45d9d1f-91c7-4f58-8689-6f4b9b210e84.png">

**Comment by mds1** [comment]
IIRC `forge coverage` requires the optimizer off for source maps to work properly, and I'd guess your `forge build` has the optimizer on which helps with some stack too deep issues. I'm not sure if there is a workaround for now (maybe via-ir with optimizers off could work for coverage?) so deferring to @onbjerg from here

**Comment by FredCoen** [comment]
via-ir with optimzer off doesn't compile either. What is frustrating is that these stack too deep  compiler errors dont give you the line of code where the attempt to use the stack fails.

In any case I presume we wont be able to get this project compiled without using the optimizer. So my question is will the coverage support this eventually?

**Comment by onbjerg** [comment]
The optimizer is disabled for coverage because it messes with the source mappings. No real fix for it in mind yet, so it is expected that this happens for some.

**Comment by FredCoen** [comment]
Ok so if we want to use ``forge coverage`` we need to fix our project to compile without any optimizing flags turned on. For deployment we will still have the optimizer turned on for savings in code size, execution cost etc...

Is there a risk to run your tests again non optimized bytecode and deploy to production with the optimizer on? As in you are not testing the bytecode which will eventually be deployed.

**Comment by FredCoen** [comment]
yeah i meant the tests would not detect a possible compiler bug

**Comment by onbjerg** [comment]
if you're worried about that you can always run tests and coverage as two separate, parallel jobs in ci :) if you use just `forge coverage` you're probably losing a lot of info - there is no way to use traces etc. currently and i'll likely strip down the options useable on `forge coverage`

**Comment by FredCoen** [comment]
fair point :) thanks!

**Comment by ZeroEkkusu** [comment]
I ran into the same issue today.

> What is frustrating is that these stack too deep compiler errors dont give you the line of code where the attempt to use the stack fails.

@FredCoen you can use `forge build --contracts=path/to/File.sol` to figure out which file is problematic. Set `optimizer = false` in `foundry.toml`, and try one by one. When you find it, see which function is mostly likely to have stack too deep (more variables).

**Comment by FredCoen** [comment]
@ZeroEkkusu thats very helpful thanks.

**Comment by Evalir** [comment]
Done—known behavior and not too many workarounds—several solutions were provided in the issue.
