### ISSUE TITLE
`vm.writeLine` stopped working

### ISSUE THREAD

**Issue by ryanli-me** [foundry-rs/foundry#3066]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e947899 2022-09-02T00:03:54.646841Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

```
The path "xxx" is not allowed to be accessed for write operations.
```

**Comment by mds1** [comment]
This is due to a recent change around permissions, more info here: https://book.getfoundry.sh/cheatcodes/fs

Just update your config file accordingly based on that

**Comment by rkrasiuk** [comment]
@ryanli-me hope that your issue is resolved now after modifying the config. closing now. if the issue persists - feel free to reopen
