### ISSUE TITLE
Unbounded Memory Growth running forge w/ Coverage

### ISSUE THREAD

**Issue by trajan0x** [foundry-rs/foundry#3067]
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (4b9cca1 2022-09-03T00:07:15.538624Z)

### What command(s) is the bug in?

forge coverage  -vvv --report=lcov

### Operating System

macOS (Apple Silicon)

### Describe the bug

Steps to reproduce (works from 0cc0de2ca08c2cd14d5480e8a47c1133147d20dd forward):

1. `git clone https://github.com/transmissions11/solmate` (or any repo I've tried)
2. `forge coverage  -vvv --report=lcov`
3. Memory growth is unbounded until OOM 

![image](https://user-images.githubusercontent.com/83933037/188251613-ed5a5e78-146f-4661-adfc-b4cf331ac95d.png)

Have seen this on both ci (linux) and apple silicon

**Comment by varunsrin** [comment]
seems to be occuring for `forge test -vvv` both locally (os x silicon) and in ci (github actions, ubuntu)

**Comment by trajan0x** [comment]
I've confirmed #3068 fixes this issue (to confirm you can use `foundryup -C 1c415857dd7b617190834dbcb361506f6143fed4`) and follow the steps above.

CI Workflow (#3070) will continue to break until a release is done so will close after that
