### ISSUE TITLE
feat: prefix script outputs with something like `dry-run-*` if `--broadcast` flag is not passed

### ISSUE THREAD

**Issue by mds1** [foundry-rs/foundry#3088]
### Component

Forge

### Describe the feature you would like

Open to other prefix name ideas, but basically right now there's no way to distinguish broadcasted logs from dry runs when looking at JSON files in the `broadcast` file. It's useful to still generate them for local inspection / facilitating writing scripts/tests that read them in.

I also think we should update the default `.gitignore` on `forge init` to include `broadcast/dry-run-*.json` 

Another solution to this problem is a flag to enable/disable saving them, but that's more tedious / easy to mess up and overwrite your `run-latest.json` file

**Comment by rkrasiuk** [comment]
@mds1 what do you think about nesting the `dry-run` folder under `broadcast`? my fear with prefix is that the `broadcast/` dir will get polluted really fast

**Comment by mds1** [comment]
I'm ok with that, that's a good point
