### ISSUE TITLE
vm.rollFork does not work when inside a testing function

### ISSUE THREAD

**Issue by Leonard-Pat** [foundry-rs/foundry#3110]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (fb78b6b 2022-09-07T00:03:44.688975211Z)

### Operating System

Linux

### Describe the bug

It seems like `vm.rollFork();` still does not work inside a testing function only during setup. 
With error
![image](https://user-images.githubusercontent.com/106159231/188835612-44a57af8-32d4-496d-be6b-79f09fd04305.png)

This can be recreated https://github.com/Leonard-Pat/foundrybug by just running forge test (after adding RPC url).
Error occurs on line 62.

**Comment by mattsse** [comment]
thanks again this!

can reproduce, fixing rn
