### ISSUE TITLE
Anvil: `eth_feeHistory` returns one too many elements

### ISSUE THREAD

**Issue by sveitser** [foundry-rs/foundry#3115]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

98de05c4a747a54fa2d6991d76d81f3ab1526cba

### What command(s) is the bug in?

anvil

### Operating System

Linux

### Describe the bug

I think `eth_feeHistory` returns one too many `baseFeePerGas` and `gasUsedRatio` elements. The example below is asking for 1 block of history, and it should return 2 base fee per gas element and 1 gas used ratio element, but returns 3 and 2.

```
curl --verbose -X POST -H "Content-Type: application/json" \
  --data '{"jsonrpc": "2.0", "method": "eth_feeHistory", "params": ["0x1", "latest", []], "id": 1}' http://127.0.0.1:8545

{"jsonrpc":"2.0","id":1,"result":{
  "baseFeePerGas":["0x1318c484","0x10da0bbd","0xedee35e"],
  "gasUsedRatio":[0.029765733333333332,0.029761433333333333],
  "oldestBlock":"0xa","reward":[]}}⏎
```

**Comment by mattsse** [comment]
thanks I believe that was indeed the case with the block range

#3117 should fix this
