### ISSUE TITLE
Account management issue in forking mode

### ISSUE THREAD

**Issue by johnnyonline** [foundry-rs/foundry#3119]
### Component

Forge, Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (fb78b6b 2022-09-07T00:03:44.688975211Z)

### What command(s) is the bug in?

forge test

### Operating System

Windows

### Describe the bug

With the _default account_, I fork mainnet, and deploy a new contract with some address as an argument for the constructor. Then, when trying to interact with that newly deployed contract using the address that was passed as an argument, I get the following error **Reason: Setup failed: Contract 0xCe71065D4017F316EC606Fe4422e11eB2c47c246 does not exist**. If I interact with that newly deployed contract using some other account (not the one that was passed to constructor), everything works as expected.

See code snippet:
```
fortressSwap = new FortressSwap(address(owner));
console.log("fortressSwap address: ", address(fortressSwap));
vm.prank(owner);
fortressSwap.updateOwner(alice); 
```

The _fortressSwap address_ is **0xCe71065D4017F316EC606Fe4422e11eB2c47c246**.

**Comment by mattsse** [comment]
wasn't able to reproduce this entirely but I think I found the bug that you were facing, 
if you're still encountering this, please reopen
