### ISSUE TITLE
foundry.toml not read on windows

### ISSUE THREAD

**Issue by mateomolinari** [foundry-rs/foundry#3120]
Hey there. I've been trying to use the `ignored_error_codes` in `foundry.toml` to ignore a specific error: 5740.
As the docs states, I should add a `ignored_error_codes` in the `foundry.toml` of my project with an array of integers.

</br>

This is my whole `foundry.toml`:

```
[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
ignored_error_codes = [5740]
```

At compiling I still get the same warnings.
`forge config` output shows:

```
ignored_error_codes = [
    1878,
    5574,
]
```

so it is not setting the `ignored_error_codes` I want to set, only the default ones.

</br>

On the other hand I have the following custom remapping in my `remappings.txt`:

```@oz/=lib/openzeppelin-contracts/contracts/```

and the `forge config` output shows it:

```
remappings = [
    '@oz/=lib/openzeppelin-contracts/contracts/',
    'ds-test/=lib\forge-std\lib/ds-test/src/',
    'forge-std/=lib\forge-std\src/',
    'openzeppelin-contracts/=lib\openzeppelin-contracts/',
]
```
</br>

`forge build  --ignored-error-codes 5740` works as expected but it should work through the foundry.toml and I would like to use that.

### Environment:
- Windows 10
- forge 0.2.0 (5279f69 2022-06-29T01:27:21.9149266Z)

**Comment by mattsse** [comment]
hmm,

could you also check `forge config --config-path <path to your foundry.toml>`

**Comment by mateomolinari** [comment]
Same error codes. Nothing changes.

**Comment by mattsse** [comment]
what's your windows setup?

does it work in WSL?

**Comment by mattsse** [comment]
perhaps this is somekind of windows related toml/path issue

what if you change additional entries in the foundry.toml, do they show up in `forge config`, or is this behavior limited to error codes?

**Comment by mateomolinari** [comment]
I was just trying that same thing. It doesn't recognize any changes in `foundry.toml`

**Comment by mateomolinari** [comment]
Just tried the same on Ubuntu 22.04.1 LTS running `forge 0.2.0 (4e11d1f 2022-08-24T00:11:00.431678626Z)` and any changes on `foundry.toml` are successfully updated and applied. It must be an issue with Windows pathing, yes.

**Comment by mattsse** [comment]
hmm, so looks like we're not reading the toml file on windows,

does `forge config --config-path <absolute path>` work?

**Comment by mateomolinari** [comment]
Running with absolute path does not work either.

**Comment by DaniPopes** [comment]
Couldn't reproduce on windows 10.0.19044, can you try again after running `foundryup`?

**Comment by mateomolinari** [comment]
after updating forge on windows, it seems to work just fine.

**Comment by sambacha** [comment]
Can this issue be closed @mattsse
