### ISSUE TITLE
Anvil is killed during deployment because of a possible memory leak.

### ISSUE THREAD

**Issue by akoita** [foundry-rs/foundry#3133]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6abb763 2022-09-08T00:05:15.055944634Z)

### What command(s) is the bug in?

forge script --legacy 

### Operating System

Linux

### Describe the bug

When I try to deploy my contract (composed of a dozen contracts and libraries), I notice that Anvil starts consuming up to 10GB, saturating my RAM and crashing. 

**Memory consumption when Anvil is running**
![Memory consumption when Anvil is running](https://user-images.githubusercontent.com/1005318/189162199-5c76268e-2a25-42d0-adf2-eaa0c2f6b6d9.png)

**Memory consumption during the deployment of my  contract.**
![Memory consumption during the deployment of my  contract. ](https://user-images.githubusercontent.com/1005318/189162672-10afbd4c-8a14-422c-b85e-01c2927594da.png)

**Anvil's crash**
![Anvil's crash](https://user-images.githubusercontent.com/1005318/189165555-86d9b00d-0138-4426-8ebe-bca2b2d5d9e9.png)

**Memory consumption when Ganache (v7.4.3 (@ganache/cli: 0.5.3, @ganache/core: 0.5.3)) is running**
![Memory consumption when Ganache (v7.4.3 (@ganache/cli: 0.5.3, @ganache/core: 0.5.3)
) is running](https://user-images.githubusercontent.com/1005318/189166682-a9523959-b22e-4b45-8062-0051623d58a0.png)

**Memory consumption after the deployment of my  contract with Ganache (v7.4.3 (@ganache/cli: 0.5.3, @ganache/core: 0.5.3)**
![Memory consumption after the deployment of my  contract with Ganache (v7.4.3 (@ganache/cli: 0.5.3, @ganache/core: 0.5.3)
) ](https://user-images.githubusercontent.com/1005318/189166841-07f7b745-d767-4ee2-a9e2-121a08746303.png)

**Comment by shekhirin** [comment]
@mattsse yeah, sounds like steps tracing I recently introduced. I guess it won't make a lot of difference if we start tracking only diffs for storage, memory and stack of each step because it still could blow up RAM usage a lot.

I will open a PR with hotfix introducing cmd option to enable steps tracing (disabled by default) now and then we can implement lazy geth-style traces calculation on `debug_traceTransaction` and `debug_traceCall` requests.

**Comment by mattsse** [comment]
that sounds great.

@akoita is this repo public by any change?

**Comment by akoita** [comment]
> that sounds great.
> 
> @akoita is this repo public by any change?

No, I'm sorry!

**Comment by mattsse** [comment]
optional steps tracing is now on master

you can try install via `foundryup -b master`, but it will be shipped with the next nightly

please let us know if this fixed it

**Comment by akoita** [comment]
Great, I'll keep you posted!

**Comment by aashborn** [comment]
I have installed the version of master branch and I consider the problem solved: I can now deploy my contract and there is no unlimited increase in memory consumption. 
Thanks for the fix!

**Comment by akoita** [comment]
I have installed the version of master branch and I consider the problem solved: I can now deploy my contract and there is no unlimited increase in memory consumption.
Thanks for the fix!

**Comment by mattsse** [comment]
thanks, we'll have another look at memory usage during tracing

**Comment by dezzeus** [comment]
We got kind of the same issue when deploying on _Arbitrum Sepolia_: with a currently latest version of foundry (`forge 0.2.0 (64b0e8f 2023-11-15T14:16:44.154917735Z)`) we got `Traces:
Killed` error and we seems to be able to fix it by removing the `-vvvvv` options from the `forge script` command.
