### ISSUE TITLE
Previously working vm.deployCode from path now claiming the path is not allowed to be accessed for read operations

### ISSUE THREAD

**Issue by 0xmp** [foundry-rs/foundry#3140]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### Describe the bug

Hi, 

I was working on https://github.com/nicolasgarcia214/damn-vulnerable-defi-foundry and recently (today) updated foundry using foundryup. This broke previously working commands like https://github.com/nicolasgarcia214/damn-vulnerable-defi-foundry/blob/c5e4289b62ad4788afba244aaaa0c52fb1d1a185/test/Levels/puppet/Puppet.t.sol#L72:

`uniswapV1ExchangeTemplate = UniswapV1Exchange(
            deployCode("./src/build-uniswap/v1/UniswapV1Exchange.json"));`

which now returns an error that the path "is not allowed to be accessed for read operations". No matter which path I give it, the error is still here. 

I downgraded foundry to a commit from 25 days ago (using `foundryup -C 6fc06c5539efb86b0204331f8a5749a60390389a`) which fixes the issue. It might be related to https://github.com/foundry-rs/foundry/pull/3007.

**Comment by 0xmp** [comment]
Looks like a duplicate of https://github.com/foundry-rs/foundry/issues/3097, closing.

**Comment by mattsse** [comment]
updated docs here https://github.com/foundry-rs/book/pull/608
