### ISSUE TITLE
`forge inspect <contract> errors/events`

### ISSUE THREAD

**Issue by ultrasecreth** [foundry-rs/foundry#3142]
### Component

Forge

### Describe the feature you would like

When working with custom errors, sometimes for whatever reason the chain will spit out the raw bytes instead of the parsed error.
In those cases, it'd be very useful to be able to list the `bytes4` sig of all the errors a contract may throw so then I can parse the raw bytes with cast.
I think that for completeness, I'd do the same for events, which would be useful when sometimes, even if the contract is verified, etherscan shows the raw byes.

Thanks!

**Comment by PaulRBerg** [comment]
+1

> sometimes for whatever reason

One reason is this bug in the invariants: https://github.com/foundry-rs/foundry/issues/4178

**Comment by grandizzy** [comment]
think this can be closed, `forge inspect errors` is available in latest versions

**Comment by PaulRBerg** [comment]
That's amazing, thanks for the heads-up @grandizzy!

**Comment by KholdStare** [comment]
@grandizzy That's awesome - could you link to the PR for the feature? This should also solve this: https://github.com/foundry-rs/foundry/issues/3656 . Thank you.

**Comment by grandizzy** [comment]
> @grandizzy That's awesome - could you link to the PR for the feature? This should also solve this: #3656 . Thank you.

here it is https://github.com/foundry-rs/foundry/pull/5228

**Comment by grandizzy** [comment]
@mattsse this one can be closed
