### ISSUE TITLE
Feature: nix flakes

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#315]
**Nix flakes** should be the way environments and releases are managed. 

No submodules though. Personally I am using dapp2nix https://github.com/icetan/dapp2nix

💊 + ❄️ + 🦀 = 🧙‍♂️

**Comment by brockelmore** [comment]
I have a strong preference against having this be the *primary* way releases and environments are managed. Having used dapptools for 2 years prior to foundry, I really was not a fan. 

That said, if someone wants to actively manage releases for nix users I would be okay with it but definitely don't want to point new users to it. Others may outright shut down the idea fwiw, as my feelings toward nix were common

**Comment by wilsoncusack** [comment]
Second what @brockelmore said! My first attraction to Foundry was that it doesn't use Nix :)

**Comment by sambacha** [comment]
> I have a strong preference against having this be the *primary* way releases and environments are managed. Having used dapptools for 2 years prior to foundry, I really was not a fan of nix. 
> 
> 
> 
> That said, if someone wants to actively manage releases for nix users I would be okay with it but definitely don't want to point new users to it. Others may outright shut down the idea fwiw, as my feelings toward nix were common

I honestly find this very surprising. 

I don't have a problem doing that, but as it stands there is not release or git tag system which releases can be based off of.

**Comment by sambacha** [comment]
> Second what @brockelmore said! My first attraction to Foundry was that it doesn't use Nix :) 

Who hurt you?

**Comment by brockelmore** [comment]
> I honestly find this very surprising. 
> 
> I don't have a problem doing that, but as it stands there is not release or git tag system which releases can be based off of.
> 
> 

heh I think if we ran a poll in the foundry tg my thoughts would be common. Regardless, you're right on the release side of things. I think we are approaching a point where binary and nix releases make sense @gakonst

**Comment by odyslam** [comment]
Thanks to rust, brew and apt binaries are relatively easy. We had a GHA workflow and pipeline that we never released. Perhaps it's time to revive that

**Comment by gakonst** [comment]
Yeah I think not distributing with Nix was an explicit goal, this will get much easier once we set up our release flows once the project is a bit more stable.

Can always have your own Nix flakes @sambacha and we can maybe link to it from the README?

**Comment by sambacha** [comment]
> Yeah I think not distributing with Nix was an explicit goal, this will get much easier once we set up our release flows once the project is a bit more stable.
> 
> Can always have your own Nix flakes in another repo @sambacha and we can maybe link to it from the README?

yes - however there needs to be a versioning policy, at least something like `v0.1.0-nightly-59589` 

[cargo-edit ](https://github.com/killercup/cargo-edit#cargo-set-version) can handle the versioning for `Cargo.toml`

**Comment by sambacha** [comment]
We have https://github.com/shazow/foundry.nix as a work around, if you want to close this issue

**Comment by mds1** [comment]
Closing since there is a workaround
