### ISSUE TITLE
Add SVM support for solc 0.7.6 Mac M1 builds

### ISSUE THREAD

**Issue by 0x70626a** [foundry-rs/foundry#3151]
### Component

Forge

### Describe the feature you would like

`Error: 
"/Users/pbj/.svm/0.7.6/solc-0.7.6": Bad CPU type in executable (os error 86)`

I'm trying to `forge build` a project that uses solidity 0.7.6 on a Mac M1 machine, and get the above error. I confirmed the project compiles fine on Ubuntu. 

I've spoken to @brockelmore about this issue and he's aware of it as well.

**Comment by rkrasiuk** [comment]
@0x70626a i've been compiling uni v3 on m1 just fine. have u tried nuking the `.svm` folder?

**Comment by 0x70626a** [comment]
<img width="2055" alt="image" src="https://user-images.githubusercontent.com/99218061/189403614-aa16b526-3aa9-4eb4-8113-c8981e19d0b0.png">
Just tried that, same issue :(

**Comment by mattsse** [comment]
there was no apple silicon when 0.7.6 was released, only starting with 0.8.5 

https://github.com/roynalnaruto/solc-builds/tree/ff4ea8a7bbde4488428de69f2c40a7fc56184f5e/macosx/aarch64

I'm afraid you'd need to enable rosetta?

**Comment by rkrasiuk** [comment]
@mattsse is correct. i took rosetta for granted 
<img width="635" alt="Screenshot 2022-09-09 at 20 09 55" src="https://user-images.githubusercontent.com/25429261/189406263-9bc6f686-35d9-47da-8b76-244d1db1e7d8.png">

**Comment by rkrasiuk** [comment]
closing the issue then, tell us if you need any further help

**Comment by mattsse** [comment]
let's add this to the book if it's not in there yet

**Comment by 0x70626a** [comment]
Hallelujah! That was it, installed Rosetta and it works now.

In case anybody else runs into this issue, here's how to install rosetta on Mac M1s: `/usr/sbin/softwareupdate --install-rosetta --agree-to-license`
