### ISSUE TITLE
Deprecation of `fuzz.max_global_rejects` config

### ISSUE THREAD

**Issue by 0xYYY** [foundry-rs/foundry#3153]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (f540aa9 2022-09-09T00:05:32.599852Z)

### Operating System

macOS (Apple Silicon)

### Describe the bug

Deprecate config option `max_global_rejects` in favor of `max_test_rejects` under the `[fuzz]` section.

The deprecation was introduced in https://github.com/foundry-rs/foundry/pull/3138 and we should fulfill it in a future release.

Suggest to add this issue to a milestone once the exact version is determined.

**Comment by mds1** [comment]
Since there's currently no versioned releases for breaking changes, we probably should look for the presence of `max_global_rejects` in config files and error/warn if it's found

**Comment by 0xYYY** [comment]
> Since there's currently no versioned releases for breaking changes, we probably should look for the presence of `max_global_rejects` in config files and error/warn if it's found

A deprecation warning was already included in this PR https://github.com/foundry-rs/foundry/pull/3138. (See the screenshot in the Example section.)

**Comment by mds1** [comment]
Ah thanks, forgot about that.

> Would it be acceptable to directly remove `fuzz.max_global_rejects` in a PR in the near future? If so, i'm happy to take this one.

Yea I agree it's been long enough to remove that flag now. I'll assign this issue to you, thanks!
