### ISSUE TITLE
Anvil missing block totalDifficulty information

### ISSUE THREAD

**Issue by mootz12** [foundry-rs/foundry#3154]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (f540aa9 2022-09-09T00:09:51.262286Z)

### Operating System

macOS (Intel)

### Describe the bug

Anvil does not appear to track `totalDifficulty` when mining blocks.

### Reproduction steps
1. Fork ethereum mainnet using default Anvil settings:
```
% anvil --fork-url https://some-forkable-url
```

2. The last recorded block shows a `totalDifficulty`:
```
% cast block 15504216

...
timestamp            1662747868
totalDifficulty      58344397744196789300626
transactions:        [
...
```

3. Perform a payment using the provided accounts:
```
% cast send 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266 --value 1 --from 0x70997970c51812dc3a010c7d01b50e0d17dc79c8
```

7. The produced block does not show a `totalDifficulty`:
```
% cast block 15504217

...
timestamp            1662747957
totalDifficulty      
transactions:        [
...
```

**Comment by mattsse** [comment]
there's no actual mining being done,

what does hardhat/ganache return here?

**Comment by mootz12** [comment]
Yep, I think as long as something "reasonable" populated that would be OK. The package I was using to deploy Vyper contracts (ape-vyper / ape-geth) expected the total difficulty to be present.

I can provide the hardhat output of the same test:
```
 % cast block 15504364 

timestamp            1662750042
totalDifficulty      58346202806952823755627
transactions:        [
```
perform step 3...

```
% cast block 15504365

timestamp            1662750259
totalDifficulty      58346214939090249676013
transactions:        [
```

**Comment by rkrasiuk** [comment]
@mattsse if u wanna go down the hh spiral at any point
https://github.com/ethereumjs/ethereumjs-monorepo/blob/95875500fe6069978e9fb90faae0e0b72be37091/packages/block/src/header.ts#L551

**Comment by mattsse** [comment]
-.-

stopped reading here


https://github.com/ethereumjs/ethereumjs-monorepo/blob/95875500fe6069978e9fb90faae0e0b72be37091/packages/block/src/header.ts#L553-L554

**Comment by mootz12** [comment]
> -.-
> 
> stopped reading here
> 
> https://github.com/ethereumjs/ethereumjs-monorepo/blob/95875500fe6069978e9fb90faae0e0b72be37091/packages/block/src/header.ts#L553-L554

I suppose I could have waited ~ a week to test this 🤣
