### ISSUE TITLE
Forge script crashes when two script contracts have the same name.

### ISSUE THREAD

**Issue by Willyham** [foundry-rs/foundry#3177]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (63c71b4 2022-09-12T00:05:14.033477Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

When two 'script contracts' have the same name, and `forge script` is run for any function in the contract, forge crashes with this error:

```
➜  contracts git:(script-test) ✗ forge script src/deploy/Deploy.t.sol --sig "deploy()"--private-key <>
[⠰] Compiling...
[⠒] Compiling 1 files with 0.8.10
[⠘] Solc 0.8.10 finished in 1.13s
Compiler run successful
The application panicked (crashed).
Message:  called `Option::unwrap()` on a `None` value
Location: cli/src/cmd/forge/script/executor.rs:36

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
[1]    6716 abort      forge script src/deploy/Deploy.t.sol --sig "deploy()" --rpc-url  --private-ke
```

It is likely that having two contracts with the same name in different files is not ideal (or possibly not valid, they compiled fine). However, if that is the case then forge should detect this and print a friendly error. 

Thanks!

**Comment by mattsse** [comment]
are both contracts actually contracts or is one an interface?

**Comment by ameesha1205** [comment]
`The application panicked (crashed).
Message:  called `Option::unwrap()` on a `None` value
Location: /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/revm-1.9.0/src/subroutine.rs:378

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
`

I am writing tests with fork of 2 different chains. Without fork, there is no error but when I use fork, I am getting this error when I include this code:

`uint256 id = (uint256(uint160(address(counter))) << 96) | (chainId1 << 80) | (chainId2 << 64) | 0;`

The test works fine when I comment this line.

**Comment by aewing** [comment]
I ran into this today. Basically what I did was clone a script (Deploy.s.sol) and renamed it (to Mint.s.sol), changed the content, but forgot to change the name of the new contract from `DeployScript` -- leading to the above error and no hint as to why I was seeing it.

**Comment by zerosnacks** [comment]
Optimistically marking as `resolved`

Recreating a setup with a duplicate `CounterScript` now returns:

```
Error: 
Multiple contracts found with the name `CounterScript`
```

Running against a direct path `forge script script/Counter2.s.sol` yields no errors
