### ISSUE TITLE
forge create bug

### ISSUE THREAD

**Issue by taye000** [foundry-rs/foundry#3178]
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: 
Invalid provider url

Context:
- Error #0: builder error: relative URL without a base
- Error #1: relative URL without a base
Location: /home/runner/work/foundry/foundry/common/src/provider.rs:31

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

**Comment by mattsse** [comment]
looks like parsing the URL failed
what url did you provide?

**Comment by taye000** [comment]
Finally solved it, was calling the create-verify inside the wrong directory.

**Comment by KholdStare** [comment]
@taye000 Can you give more information that "solved it" in case others run into this issue?

I am getting the same problem now, and was wondering if you had suggestions to work around it.

Relevant section of foundry.toml:

```toml
[rpc_endpoints]
mumbai = "https://polygon-mumbai.g.alchemy.com/v2/${MUMBAI_ALCHEMY_API_KEY}"

[etherscan]
mumbai = { key = "${POLYSCAN_API_KEY}", chain = 80001, url = "https://api-testnet.polygonscan.com/" }
```

Command and error:
```
$ forge script DeployV1 --rpc-url mumbai --verify --etherscan-api-key mumbai -vvvv --ffi

The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: 
Invalid provider url

Context:
- Error #0: builder error: relative URL without a base
- Error #1: relative URL without a base
Location: /home/kholdstare/.foundry/foundry-rs/foundry/common/src/provider.rs:31

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry
```

**Comment by mattsse** [comment]
sorry about that, the adding aliases introduced a bit of friction, this looks related. checking.

**Comment by mattsse** [comment]
@KholdStare this could be fixed in latest nightly, at the very least the error provides more context now.

If this is still an issue, please open a separate issue
