### ISSUE TITLE
fmt: general comments and feedback

### ISSUE THREAD

**Issue by mds1** [foundry-rs/foundry#3184]
### Component

Forge

### Describe the feature you would like

cc @rkrasiuk 

1. Comment spacing is removed, so if I have a comment line/block with some lines indented (like a bulleted list or a code block in comments), that all becomes left-aligned. This only happens with `/**` style comments, not `//` or `///`

BEFORE
```solidity
// Here is my comment
//   - item 1
//   - item 2

/**
 * @notice Here is my comment
 *       - item 1
 *       - item 2
 * Some equations:
 *     y = mx + b
 */
```

AFTER
```solidity
// Here is my comment
//   - item 1
//   - item 2

/**
 * @notice Here is my comment
 * - item 1
 * - item 2
 * Some equations:
 * y = mx + b
 */
```

2. Comments that exceed `line_length` are not automatically wrapped. This happens with all comment styles. Note that I would not expect end-of-line comments to be automatically wrapped (not sure how rustfmt handles this, but doing what that does seems ok). Example end-of-line comment:
```solidity
uint myVar; // really long comment that exceeds line width, not sure what should happen here.
```

3. Inline comments are moved improperly in mappings

```solidity
// HAD THIS
mapping(address /* asset */ => address /* router */) public router;

// BECAME THIS
mapping(address => /* asset */ address) /* router */ public router;
```

**Comment by rkrasiuk** [comment]
@mds1 @mattsse @gakonst wanna get some input on `2.`, afaik `rustfmt` splits a line comment that exceed max line length into multiple comments. is that a behavior we'd want to replicate or do we wanna leave current comment handling as is?

**Comment by mattsse** [comment]
I think we definitely want custom comment width wrapping, ideally with support for detecting indents before `-`, `*` and `1.`

**Comment by rkrasiuk** [comment]
yeah, that def sounds like a good solution. i'll pick it up after #3244 is merged then

**Comment by mds1** [comment]
Yea agree with @mattsse, that would be great 👌

**Comment by sambacha** [comment]
Line length is not a character count enforcing parameter, i dont know why you would want it like that

**Comment by mds1** [comment]
> Line length is not a character count enforcing parameter, i dont know why you would want it like that

Some lines may be a char or two over, but it's effectively enforced, so makes sense for comments to follow the same convention IMO

--------


@rkrasiuk re (1), looks like some comment spacing may not be preserved properly?

```solidity
/**
contract A {
  function foo() public {
    // does nothing.
  }
}
*/
```

Running `forge fmt` gives:
```solidity
/**
 * contract A {
 * function foo() public {
 * // does nothing.
 * }
 * }
 */
```

But ideally it would give:

```solidity
/**
 * contract A {
 *   function foo() public {
 *     // does nothing.
 *   }
 * }
 */
```

**Comment by sambacha** [comment]
> > Line length is not a character count enforcing parameter, i dont know why you would want it like that
> 
> Some lines may be a char or two over, but it's effectively enforced, so makes sense for comments to follow the same convention IMO
> 
> @rkrasiuk re (1), looks like some comment spacing may not be preserved properly?
> 
> ```solidity
> /**
> contract A {
>   function foo() public {
>     // does nothing.
>   }
> }
> */
> ```
> 
> Running `forge fmt` gives:
> 
> ```solidity
> /**
>  * contract A {
>  * function foo() public {
>  * // does nothing.
>  * }
>  * }
>  */
> ```
> 
> But ideally it would give:
> 
> ```solidity
> /**
>  * contract A {
>  *   function foo() public {
>  *     // does nothing.
>  *   }
>  * }
>  */
> ```

The line enforcement is done by function ast typically, comment readability is dependent upon semantics. 

Are there any other tests with comment styling you have? Will add to this  https://github.com/sambacha/foundry-prettier-fuzz
