### ISSUE TITLE
Support RPC aliases from CLI (--fork-url / --rpc-url) on all commands

### ISSUE THREAD

**Issue by devanonon** [foundry-rs/foundry#3195]
### Component

Forge

### Describe the bug

Currently you can pass an RPC alias to `--rpc-url` for certain CLI commands, as implemented by #3116. AFAIK, it's not implemented on `script` and `test`, maybe others are missing too.

I started working on a quick solution, but haven't had the time to finish. Opening an issue so we don't lose track of it.

**Comment by KholdStare** [comment]
Hey, I see there was a change merged. Foundry crashes for me if I try to use an alias for `--rpc-url` with `script`:

```bash
$ forge script DeployV1 --rpc-url polygonMumbai -vvvv --ffi

The application panicked (crashed).
Message:  Bad fork_url provider: RelativeUrlWithoutBase
Location: /home/kholdstare/.foundry/foundry-rs/foundry/utils/src/lib.rs:610

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: __libc_start_main<unknown>
      at <unknown source file>:<unknown line>

```



I have this configured in my `foundry.toml`:

```toml
[rpc_endpoints]
polygonMumbai = "https://polygon-mumbai.g.alchemy.com/v2/${MUMBAI_ALCHEMY_API_KEY}"
```


Am I doing something wrong?

**Comment by mattsse** [comment]
sorry about that.

thanks for this repro, will fix

**Comment by KholdStare** [comment]
@mattsse Thanks for the fix! Until it's merged, it looks like everything works if I don't use `camelCase` .
