### ISSUE TITLE
Install missing dependencies on forge test

### ISSUE THREAD

**Issue by AlbertoCentonze** [foundry-rs/foundry#3204]
### Component

Forge

### Describe the feature you would like

When you clone a foundry-based repo if you haven't built the contracts with `forge build`, dependencies are not installed automatically. It would be nice if the missing dependencies check was added to `forge test` as well.

**Comment by mattsse** [comment]
that's reasonable, since `forge test` implies `forge build` so we should run the build process like `forge build` does
