### ISSUE TITLE
Anvil's `debug_traceTransaction` behaviour differs from geth

### ISSUE THREAD

**Issue by shekhirin** [foundry-rs/foundry#3206]
### Component

Anvil

### Describe the bug

As of https://github.com/foundry-rs/foundry/pull/3198/commits/6e5a613e21f969bfd82afdd7f55b7cba96c1b2be, Anvil's `debug_traceTransaction` differs from geth in several places which are also on screenshots:
1. <s>Incorrect memory state during `MSTORE`</s> It was fixed for Geth in https://github.com/ethereum/go-ethereum/commit/97f308a98f9f2f557a0815665f6497eac8f469fd but my RPC uses Erigon which doesn't have these changes and still does memory expansion **before** tracing: https://github.com/ledgerwatch/erigon/blob/cd8cad6a8908970fa092aa5e2dcd8f38aedccd89/core/vm/interpreter.go#L316-L323
2. Remaining gas and instruction gas cost calculated incorrectly: https://github.com/foundry-rs/foundry/blob/6e5a613e21f969bfd82afdd7f55b7cba96c1b2be/evm/src/executor/inspector/tracer.rs#L138-L139
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/5773434/190135701-370e66c6-67cf-4ac4-9df2-6cd572c7c9df.png">
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/5773434/190135181-a1144e75-cb24-4007-994a-f52178da07ae.png">

**Comment by gakonst** [comment]
Good catch. Yep we want this to be 1:1 compatible. cc @mattsse to keep this in mind for reth, we want byte compatibility I think with Geth RPC (esp. for debug_traceTransaction) and with Parity's tracing responses
