### ISSUE TITLE
Install Deps for Forge Libs

### ISSUE THREAD

**Issue by maxwolff** [foundry-rs/foundry#3213]
### Component

Forge

### Describe the feature you would like

When "forge install"-ing a repo which itself has contract dependencies it fetches npm (eg, openzeppelin libs), forge install does not recursively install the dependencies.

Instead, you have to `cd lib/my-external-repo/` and then `npm install` 

Would be nice if forge install would do this for me, or maybe expose a flag for it

**Comment by onbjerg** [comment]
Forge does not run `npm install`, it just handles submodules. We do not plan to support npm per https://github.com/foundry-rs/foundry/issues/1847 so I am closing this issue. Let me know if I misunderstood!
