### ISSUE TITLE
Make `--verify` work without `--etherscan-api-key` when [etherscan] is correctly filled

### ISSUE THREAD

**Issue by adhusson** [foundry-rs/foundry#3224]
### Component

Forge

### Describe the feature you would like

Running `forge script (...) --verify` (without `--etherscan-api-key`) should work if forge can unambiguously infer the correct API key / provider to use. Note: as of now, it silently drops verification. It should at least display an error.

For instance, with
```
# foundry.toml
[rpc_endpoints]
polygon = "${POLYGON_URL}"
[etherscan]
polygon = { key = "${ETHERSCAN_API_KEY}", chain=127 }
```

Today you can run `forge script --rpc-url polygon --verify --etherscan-api-key polygon`. But there is one (and only one) `[etherscan]` entry expecting chain id 127. So you should be able to run `forge script --rpc-url polygon --verify`.

**Comment by mattsse** [comment]
I think this is a reasonable request, if not provided and `--rpc-url` is an alias then we should use the same alias for the etherscan table.

**Comment by gakonst** [comment]
agreed

**Comment by mattsse** [comment]
this should be supported now, ref https://github.com/foundry-rs/foundry/pull/3310

closing, but please reopen if you encounter this issue again

**Comment by adhusson** [comment]
Still not working for me, I may be doing something wrong.

Using `forge 0.2.0 (ddaf100 2022-09-24T00:05:44.382307Z)` and with this in `foundry.toml`:

```toml
[rpc_endpoints]
mumbai="${MUMBAI_NODE_URL}"
[etherscan]
mumbai={key="${POLYGON_API_KEY}"}
```

I expect this:
```bash
$ forge script --rpc-url mumbai TestScript --verify --broadcast
# Deploys & Verifies
```

I'm getting the following outputs:

```bash
$ forge script --rpc-url mumbai TestScript --verify --broadcast
# Deploys, does not verify, bad.
```

```bash
$ forge script --rpc-url mumbai TestScript --verify
[⠆] Compiling...
No files changed, compilation skipped
Error:
Invalid provider url: mumbai # bad
```

```bash
$ forge script --rpc-url mumbai TestScript --verify --resume
[⠆] Compiling...
No files changed, compilation skipped
Error:
Invalid provider url: mumbai # bad
```

```bash
$ forge script --rpc-url $MUMBAI_NODE_URL TestScript --verify --resume
# No error, does not verify (bad)
```

```bash
$ forge script --rpc-url $MUMBAI_NODE_URL TestScript --verify --resume --etherscan-api-key $POLYGON_API_KEY
# Verifies (good)
```
