### ISSUE TITLE
Strange intermittent forge test errors

### ISSUE THREAD

**Issue by marktoda** [foundry-rs/foundry#3227]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (359dd77 2022-09-15T00:11:28.060332608Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

Starting today, getting strange intermittent errors on `forge test`. It seems to be related to fork environments. Different sets of errors:

This error occurs 1/3 times:
```
2022-09-15T17:16:42.272914Z ERROR sharedbackend: Failed to send/recv `basic` err=GetAccount(0x1804c8ab1f12e6bbf3894d4083f33e07309d1f38,
(code: -32000, message: header not found, data: None)) address=0x1804c8ab1f12e6bbf3894d4083f33e07309d1f38
2022-09-15T17:16:42.272966Z ERROR sharedbackend: Failed to send/recv `basic` err=GetAccount(0x1804c8ab1f12e6bbf3894d4083f33e07309d1f38,
(code: -32000, message: header not found, data: None)) address=0x1804c8ab1f12e6bbf3894d4083f33e07309d1f38
2022-09-15T17:16:42.272911Z ERROR sharedbackend: Failed to send/recv `basic` err=GetAccount(0x1804c8ab1f12e6bbf3894d4083f33e07309d1f38,
(code: -32000, message: header not found, data: None)) address=0x1804c8ab1f12e6bbf3894d4083f33e07309d1f38
```

Another 1/3 times. Infura seems to be working properly (can fetch block number and blocks via cast no problem):
```
Could not instantiate forked environment with fork url: https://mainnet.infura.io/v3/<projid>

Context:
- Failed to get block for block number: 15540530
latest block number: 15540530
```

Very strange one, tests run but with weird errors and using astronomical gas
```
[FAIL. Reason: Call reverted as expected, but without data] <test>() (gas: 8937393460516731249)
[FAIL. Reason: Call reverted as expected, but without data] <test>() (gas: 8937393460516731231)
[FAIL. Reason: Call reverted as expected, but without data] <test>() (gas: 8937393460516731232)
[FAIL. Reason: EvmError: FatalExternalError] <test>() (gas: 9223372036854754743)

```

**Comment by mattsse** [comment]
this is thrown when we failed to retrieve the account data from the provider,

the actual rpc error message is "message: header not found" I have seen this a few times today, with infura

**Comment by grandizzy** [comment]
The new mainnet URLs were changed from `https://mainnet.infura.io/v3/key` to `https://user:key@eth2-beacon-mainnet.infura.io` but getting same intermittent issues with the new one

**Comment by rkrasiuk** [comment]
@mattsse i think there is no action item for us here, is there?

**Comment by mattsse** [comment]
we're now retrying the request when we see this error:

https://github.com/gakonst/ethers-rs/pull/1706

> header not found

 should be resolved now
