### ISSUE TITLE
Make anvil code size limit configurable

### ISSUE THREAD

**Issue by holic** [foundry-rs/foundry#3232]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (359dd77 2022-09-15T00:04:51.833948Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

Using [SSTORE2](https://github.com/0xsequence/sstore2) and running the below test code allows for contracts to be created that exceed 24576 bytes (contract size limit)

```solidity
pragma solidity ^0.8.9;

import "sstore2/SSTORE2.sol";
import "sstore2/utils/Bytecode.sol";

contract TestSSTORE2 {
    function testWrite() public {
        bytes memory data = bytes(vm.readFile("path/to/large/file"));
        console.log("data length", data.length);

        address memory pointer = SSTORE2.write(data);
        console.log("contract size", Bytecode.codeSize(pointer));
    }
}
```

**Comment by holic** [comment]
My initial anvil script wasn't using `--broadcast`, so I misinterpreted this as anvil having the same behavior as tests. Once I added `--broadcast` to the anvil node, I got an error as expected: `(code: -32003, message: intrinsic gas too high, data: None)`

Updated the above title/description to reflect that I can only exceed contract size limits in tests.

**Comment by holic** [comment]
Actually, revisited the anvil side again, and was not able to throw 600kb at it, but was able to throw 48kb at it with no issues. So maybe this is just because my gas limit of the anvil node is lower than in tests.

**Comment by mattsse** [comment]
> intrinsic gas too high

is thrown if gas exceeds block gas limit

you can manually set --gas-limit for anvil and bump it

**Comment by mattsse** [comment]
sorry for taking so long.

since you're writing an entire file to storage, the tx gas likely exceeds the max block gas limit, but you can bump this manually.

Closing this, lmk if you're still facing issues after increasing anvil's block gas limit

**Comment by holic** [comment]
I don’t think this is a gas limit issue. See https://github.com/ethereum/EIPs/issues/1662

**Comment by mattsse** [comment]
what's the error you get when sending a create tx for a large contract?

**Comment by holic** [comment]
> what's the error you get when sending a create tx for a large contract?

The problem is there isn’t an error when I expected one. I can throw tons of data at it, we’ll over the contract size limit, and get no errors in anvil/tests. 

EIP-170 says anything over ~24kb should be an out of gas error. I can try running this against a testnet and confirm if that’s the error I get for >24kb.

**Comment by mattsse** [comment]
we're not enforcing size limits rn, but I think we should make this configurable.

still don't understand if your issue is that there's _no_ error or whether there's something else wrong?

**Comment by holic** [comment]
> we're not enforcing size limits rn, but I think we should make this configurable.
> 
> still don't understand if your issue is that there's _no_ error or whether there's something else wrong?

The issue is that there is no error. Being able to toggle on/off size limits would be great!

**Comment by holic** [comment]
Is it possible to allow `forge test` to configure in the same way? Ultimately I want to write Solidity tests that will fail if the code size is exceeded.

**Comment by mattsse** [comment]
no but we could add if you open a separate issue

**Comment by CaixiangFan** [comment]
> > we're not enforcing size limits rn, but I think we should make this configurable.
> > still don't understand if your issue is that there's _no_ error or whether there's something else wrong?
> 
> The issue is that there is no error. Being able to toggle on/off size limits would be great!
> 
> I deleted the earlier comments and updated the original issue. Let me know if that’s more clear.

I came into a similar situation. While EIP 170 introduced a limit of 24KB on bytecode size of smart contracts in Ethereum, NOT .sol file size. My 56KB .sol file compiles in Remix with optimization runs set to 200 and the compiled contract bytecode size was only 14KB in my case, which was far below the limit. Not sure if this is the same issue you met.

**Comment by TokenTitan** [comment]
For testing purpose my deployment was failing with `ABC is above the EIP-170 contract size limit (30134 > 24576).`

with the added option of `--code-size-limit 31000` to the `forge script script/deploy.s.sol`

It still fails with `Execution reverted: EvmError: CreateContractSizeLimit (gas: 9223372036854775857)`

**Comment by kamikazebr** [comment]
> While testing my deployment was failing with `ABC is above the EIP-170 contract size limit (30134 > 24576).`
> 
> with the added option of `--code-size-limit 31000` to the `forge script script/deploy.s.sol`
> 
> It still fails with `Execution reverted: EvmError: CreateContractSizeLimit (gas: 9223372036854775857)`

I have same problem.
