### ISSUE TITLE
Refactor `cast wallet vanity` to compute via GPU

### ISSUE THREAD

**Issue by wildmolasses** [foundry-rs/foundry#3243]
### Component

Cast

### Describe the feature you would like

[Profanity](https://github.com/johguse/profanity) is now unsafe and archived; a maintained vanity address generator that uses GPU would be useful. Thank you!

**Comment by marktoda** [comment]
+ would also be cool to be able to grind salts for vanity create2 contract addresses a la https://github.com/0age/create2crunch

**Comment by onbjerg** [comment]
Would note here that we can't lock into GPU only since some people use Cast on servers w/o GPUs

**Comment by mattsse** [comment]
yeah this would need to be an entirely separate thing.

definitely out of scope for cast itself, also as we've seen with profanity, there can be additional issues when it comes to randomness so I wouldn't feel confident shipping something like this without proper security assessments.

**Comment by zerosnacks** [comment]
Update, Profanity was forked by 1inch and is now maintained as Profanity2: https://github.com/1inch/profanity2

Marking this an `not planned` as GPU functionality is not planned
