### ISSUE TITLE
gas snapshot diff - do not exit with error code 1 when new test added

### ISSUE THREAD

**Issue by grandizzy** [foundry-rs/foundry#3246]
### Component

Forge

### Describe the feature you would like

Would be nice to have `forge snapshot --diff` not exit with error code 1 in case there's a new test added but just ignore the fact there's no matching entry (as it already does when a test is removed). This can be useful in CI environments where gas snapshots are taken each run and compared on new commits.

**Comment by mattsse** [comment]
that makes sense, nothing to diff in this case
