### ISSUE TITLE
`cast interface` error when input has a struct

### ISSUE THREAD

**Issue by hexzerodev** [foundry-rs/foundry#3264]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (736e602 2022-09-18T00:05:01.134898Z)

### What command(s) is the bug in?

cast interface

### Operating System

macOS (Apple Silicon)

### Describe the bug

Running `cast interface` with the following json:

```json
{
  "abi": [
    {
      "inputs": [
        {
          "components": [
            {
              "internalType": "string",
              "name": "name",
              "type": "string"
            }
          ],
          "internalType": "struct Contract.Setup",
          "name": "structSetup",
          "type": "tuple"
        },
        {
          "internalType": "address",
          "name": "guard",
          "type": "address"
        }
      ],
      "name": "setup",
      "outputs": [],
      "stateMutability": "payable",
      "type": "function"
    }
  ]
}
```

gives the error `an error occurred when formatting an argument`. Seems like the struct input is causing the error.

Might be related to #3260.

**Comment by gakonst** [comment]
closed in https://github.com/foundry-rs/foundry/pull/3263 - could you verify that the fix works @hexzerodev ?

**Comment by hexzerodev** [comment]
@gakonst that fixed it 👍 Cheers!
