### ISSUE TITLE
`forge flatten` with renamed interface import does not compile

### ISSUE THREAD

**Issue by chad-js** [foundry-rs/foundry#3265]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (084ef3d 2022-09-19T00:04:35.98318Z)

### What command(s) is the bug in?

forge flatten

### Operating System

macOS (Apple Silicon)

### Describe the bug

If I have a contract using a named import of an interface, such as 
```solidity
import { IERC20 as MyIERC20 } from "src/interfaces/IERC20.sol";
```

`forge flatten` on that file results in output that includes the IERC20 interface, and the contract using the named import. Since the contract uses the named import `MyIERC20`, and the flattened file includes `interface IERC20` but not `interface MyIERC20`, `forge build` fails with `DeclarationError: Identifier not found or not unique.`

This seems related to https://github.com/foundry-rs/foundry/issues/1440

**Comment by adhusson** [comment]
Also related to #2545 (maybe the same?).

**Comment by rkrasiuk** [comment]
@chad-js sorry for delay on this. the issue is a little bit different than the above, however, the underlying problem is also non-trivial.
in your opinion, what would be the expected behavior if the same contract is aliased differently across source files
i.e.
```solidity
// file1.sol
import { IERC20 } from "src/interfaces/IERC20.sol";

// file2.sol
import { IERC20 as MyIERC20 } from "src/interfaces/IERC20.sol";

// file3.sol
import { IERC20 as CustomIERC20 } from "src/interfaces/IERC20.sol";
```

**Comment by mds1** [comment]
@rkrasiuk in your above example, can you just drop the renames and then everything is the same IERC20?

But if the IERC20's are from different file paths, it gets more complex. In that case I think we can include the renamed interfaces in the flattened file, such as:
- `interface IERC20 { /* snip */ }` is left unchanged
- `interface MyERC20 { /*snip */}` holds the code that was in it's imported `IERC20` interface
- `interface CustomIERC20 { /*snip */}` holds the code that was in that imported `IERC20` interface

Perhaps I am misunderstanding the complications though?
