### ISSUE TITLE
Anvil - Can not call contract after it has been impersonated

### ISSUE THREAD

**Issue by naddison36** [foundry-rs/foundry#3269]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (084ef3d 2022-09-19T05:53:09.080487Z)

### Operating System

macOS (Apple Silicon)

### Describe the bug

After impersonating a contract using Hardhat calls to a local, forked Anvil node, the contract can no longer be called.

Here's an example of calling the USDC token contract. The first call to `symbol()` works. The second call fails after the USDC contract has been impersonated.

```ts
const accounts = await ethers.getSigners()
const USDC = IERC20Metadata__factory.connect("0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48", accounts[0])
expect(await USDC.symbol(), "symbol before").to.equal("USDC")
await network.provider.request({
  method: "hardhat_impersonateAccount",
  params: [USDC.address],
})
expect(await USDC.symbol(), "symbol after").to.equal("USDC")
```

The Hardhat error is
```
     Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="symbol()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.6.4)
      at Logger.makeError (node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
      at Logger.throwError (node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
      at Interface.decodeFunctionResult (node_modules/@ethersproject/abi/src.ts/interface.ts:427:23)
      at Contract.<anonymous> (node_modules/@ethersproject/contracts/src.ts/index.ts:400:44)
      at step (node_modules/@ethersproject/contracts/lib/index.js:48:23)
      at Object.next (node_modules/@ethersproject/contracts/lib/index.js:29:53)
      at fulfilled (node_modules/@ethersproject/contracts/lib/index.js:20:58)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

The local Anvil node was started with
```
anvil -f https://eth-mainnet.alchemyapi.io/v2/$KEY
```

This test works against the `hardhat` network.

**Comment by mattsse** [comment]
this is a limitation of contract impersonating because we need to bypass EIP-3607
by temporarily removing the contract code of the impersonated contract.

the code is added back if you stop impersonating the contract though

**Comment by naddison36** [comment]
Thanks @mattsse for the information.

I've tested and sending either `anvil_stopImpersonatingAccount` or `hardhat_stopImpersonatingAccount` works.

For anyone else looking at this, be aware that `hardhat_stopImpersonatingAccount` does not work with the Hardhat network so if your tests run against Hardhat or a local Anvil node you'll need to add an if condition to only run `hardhat_stopImpersonatingAccount` against Anvil. For example, the following will work if you have defined `anvil` as a network in your Hardhat config.

```ts
import { ethers, network } from "hardhat"

if (network.name === "anvil") {
    await network.provider.request({
        method: "hardhat_stopImpersonatingAccount",
        params: [USDC.address],
    })
}
```

**Comment by mattsse** [comment]
thanks, would you mind upstreaming this to the anvil book?

https://github.com/foundry-rs/book/tree/master/src/reference/anvil

**Comment by naddison36** [comment]
PR for Anvil book https://github.com/foundry-rs/book/pull/631
