### ISSUE TITLE
Failed to get account ?

### ISSUE THREAD

**Issue by MiguelBits** [foundry-rs/foundry#3273]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (63ed109 2022-08-09T00:03:50.892098571Z)

### What command(s) is the bug in?

forge test --match-contract OracleTest --fork-url https://arb1.arbitrum.io/rpc --fork-block-number 7185900 -vv

### Operating System

Linux

### Describe the bug

Forking arbitrum at specific blocks to get calls from oracles gives this:
```
2022-09-19T15:38:48.297170Z ERROR sharedbackend: Failed to send/recv `basic` err=GetAccount(0x00a329c0648769a73afac7f9381e08fb43dbea72, 
(code: -32000, message: missing trie node 0000000000000000000000000000000000000000000000000000000000000000 (path ) <nil>, data: None)) address=0x00a329c0648769a73afac7f9381e08fb43dbea72
2022-09-19T15:38:48.297251Z ERROR forge::multi_runner: error=Failed to get account for 0x00a329c0648769a73afac7f9381e08fb43dbea72: 0x00a329c0648769a73afac7f9381e08fb43dbea72
```

**Comment by onbjerg** [comment]
Most likely the node you are communicating with does not have the data for the account you are forking from. Try moving the fork block number closer to today's block - there is a limit on how far you can go back if you are not using an archive node, and you are about 18 million blocks behind the latest block.
