### ISSUE TITLE
Unable to compile on CI

### ISSUE THREAD

**Issue by joshualyguessennd** [foundry-rs/foundry#3278]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (359dd77 2022-09-15T00:04:51.833948Z)

### What command(s) is the bug in?

forge build

### Operating System

Linux

### Describe the bug

After successfully compile and test the contract locally I'm unable to run the test on CI 
[https://github.com/realiotech/bastion/actions/runs/3073730430/jobs/4966046203](https://github.com/realiotech/bastion/actions/runs/3073730430/jobs/4966046203)

**Comment by mattsse** [comment]
absolute imports are kinda cursed, and we discourage usage because they will eventually cause problems if you want to verify for example

try replacing `"contracts/src/landNFT.sol"` with a relative import

**Comment by joshualyguessennd** [comment]
```
Compiler run failed
error[6275]: ParserError: Source "contracts/src/landNFT.sol" not found: File not found. Searched the following locations: "/home/runner/work/bastion/bastion".
 --> contracts/src/test/LandBank.t.sol:6:1:
  |
6 | import "../landNFT.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^
 ```
 I have try with a relative import and have the same issue , and tried absolute import to see what breaks build

**Comment by mattsse** [comment]
ah I see, wrong alarm, but still recomend to use relative paths

looks like you set `"/home/runner/work/bastion/bastion"` to contracts

https://github.com/realiotech/bastion/pull/27/files#diff-d0024dcfce8263455f76f35323f55051631264ba689777e927397480a6914ff4R86

**Comment by joshualyguessennd** [comment]
I've tried to remove it too and I have the same issue . the test process doesn't set a working dir . 
https://github.com/realiotech/bastion/actions/runs/3086225202/jobs/4990361482

**Comment by mattsse** [comment]
your import path is wrong

`import "../landNFT.sol";` should be `import "../LandNFT.sol";`

**Comment by joshualyguessennd** [comment]
Thank
