### ISSUE TITLE
Add struct FuzzSelector to Test.sol

### ISSUE THREAD

**Issue by nine-december** [foundry-rs/foundry#3292]
### Component

Forge

### Describe the feature you would like

While invariant testing, filters can be used to establish a boundary in order to help the engine converge. The `targetSelectors()` filter requires the following struct to be previously declared:

```solidity
  struct FuzzSelector {
      address addr;
      bytes4[] selectors;
  }
```

In order to prevent users from creating that struct across tests and to improve UX, it could be helpful to add that struct on the `Test.sol` file.

Also, if specific structures and functions are going to be needed for invariant testing, creating a new (e.g.) `InvariantTest.sol` automatically pushed to `forge-std/src` will help saving resources for those users who only want to perform regular tests allowing invariant testers to independently inherit that contract.

**Comment by mattsse** [comment]
this should probably be moved to forge-std instead.

since this is required, supportive of adding this there.

wdyt @joshieDo ?

**Comment by joshieDo** [comment]
yeah, i agree

**Comment by mds1** [comment]
forge-std now has default helpers for invariant testing, so closing this
