### ISSUE TITLE
Add arbitrary data to each broadcast

### ISSUE THREAD

**Issue by adhusson** [foundry-rs/foundry#3298]
### Component

Forge

### Describe the feature you would like

It would be useful for processes that manage broadcast log files if each tx could have arbitrary data attached. My use case is giving names to deployed contracts.

The interface could look like this:

```solidity
function broadcast(bytes calldata) external;
function broadcast(address, bytes calldata) external;
function broadcast(uint256, bytes calldata) external;
```

and be used like this:
```solidity
vm.broadcast(bytes("BetterContract"));
new Contract();

// struct TxInfo({uint version; string message;})
vm.broadcast(abi.encode(TxInfo({version: 2, message: "updating the oracle"})));
oracle.update();
```

The resulting JSON would look like this:

```json
{
  "transactions": [
    {
      "hash": "0x16cd3c8ce4f1f3d03582e1d1132c90297469b36e5ee74fc9957cdceb4e3f51f6",
      "transactionType": "CREATE",
      "memo": <arbitrary bytes>
     }
   ]
 }
 ```

Or, to be easier to read in the JSON by default, just allow a `string`:
```solidity
function broadcast(string calldata) external;
function broadcast(address, string calldata) external;
function broadcast(uint256, string calldata) external;
```

**Comment by mds1** [comment]
IIUC these feature requests sound like things that fit within the scope of #3911, i.e. we probably don't want to hack these into `forge script` — my impression of this issue is that it's a way to help manage deploy scripts/pipelines over the lifetime of a project, so going to close this as a result
