### ISSUE TITLE
Contract verification for etherscan doesn't work if you load libraries from `node_modules` - "Fail - Unable to verify"

### ISSUE THREAD

**Issue by JasoonS** [foundry-rs/foundry#3299]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6974541 2022-09-20T00:08:48.480626755Z)

### What command(s) is the bug in?

forge script --verify

### Operating System

Linux

### Describe the bug

Exact error message recieved: "Contract verification failed: Response: `NOTOK` Details: `Fail - Unable to verify`"

Changing

```
remappings = [
  '@openzeppelin/=node_modules/@openzeppelin/'
]
```
to
```
remappings = [
  '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
  '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
]
```

Fixed the error (after installing the libraries of course.

Everything else worked, compiling, testing etc, but verification failed. It was able to upload the verification to sourcify too, but it struggled with etherscan.

To test this you'll need to install `@openzeppelin/contracts-upgradeable` or `@openzeppelin/contracts` npm packages. I'm not sure if this issue occurs with other npm packages too - likely.

**Comment by JasoonS** [comment]
The issue has come back and I'm not using any `node_modules`, so that isn't necessarily the root cause.

**Comment by Enigmatic331** [comment]
Hey @JasoonS could you share which contract (and corresponding network) are you trying to verify where the issue came back please? Much thanks.

**Comment by JasoonS** [comment]
Hi @Enigmatic331 - Thanks for your interest. I've somewhat moved on from this issue. But we'll be making our contracts public in the next 3 weeks. I'll share that with you then.

**Comment by zerosnacks** [comment]
Marking this ticket as `stale`

Feel free to re-open if you experience the issue again or have a minimal reproducible example

I think it is unrelated to `node_modules` specifically and more likely related to remappings.
