### ISSUE TITLE
`forge upload-selectors` should upload error types.

### ISSUE THREAD

**Issue by Willyham** [foundry-rs/foundry#3300]
### Component

Forge

### Describe the feature you would like

When running `forge upload-selectors`, forge should upload signatures from error types, such as `error Foo(uint256)`. This enabled us to use `cast 4byte <error>` when receiving errors back from the network.

**Comment by iFrostizz** [comment]
Not sure what you mean, it seems to be working well when running:

```sh
$ cast upload-signature "Foo(uint256)"
> Imported: Function Foo(uint256): 0x1176bd96
> Selectors successfully uploaded to https://sig.eth.samczsun.com

$ cast 4byte 0x1176bd96
> Foo(uint256)
```

**Comment by DaniPopes** [comment]
This is already supported, `forge upload-selectors` uploads the specified contract's full ABI which includes any errors:

`src/Counter.sol`

```solidity
pragma solidity ^0.8.4;

contract Counter {
    error VeryLongError(bytes, bytes, bytes, bytes);
}
```

```sh
$ forge upload-selectors Counter
Imported: Function VeryLongError(bytes,bytes,bytes,bytes): 0x0adccd39
Selectors successfully uploaded to https://sig.eth.samczsun.com
$ cast 4byte 0x0adccd39
VeryLongError(bytes,bytes,bytes,bytes)
```

**Comment by mds1** [comment]
Closing this per @DaniPopes's comment
