### ISSUE TITLE
Error message thrown when compiler version is not set is incorrect (suggests `--compiler-version`, should be `--use`)

### ISSUE THREAD

**Issue by 0xlxy** [foundry-rs/foundry#3306]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (3a462eb 2022-09-22T00:09:28.123972Z)

### What command(s) is the bug in?

forge create

### Operating System

macOS (Apple Silicon)

### Describe the bug

I was deploying a contract via:
```
forge create --rpc-url <rpc_url> --constructor-args <args> --private-key <private_key> src/<name>.sol:<name> --etherscan-api-key <api_key> --verify
```
However, I got: 
Error: 
Compiler version has to be set in `foundry.toml`. If the project was not deployed with foundry, specify the version through `--compiler-version` flag.

According to Georgios' [tweet](https://twitter.com/gakonst/status/1526691363407790080), the compiler version should no longer be needed in order to deploy & verify the contract. Wonder if there's any solution for it. Thanks!

**Comment by XingyuLi20** [comment]
update: it works after adding `solc = "0.8.13"` in `foundry.toml`

**Comment by rkrasiuk** [comment]
@XingyuLi20 could you provide a minimum working example? I've been able to verify without setting the compiler version explicitly

**Comment by XingyuLi20** [comment]
A minimum working example on my end would be adding `solc = "0.8.13"` in `foundry.toml`:
```
[profile.default]
solc = "0.8.13"
src = 'src'
out = 'out'
libs = ['lib']

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
```
and then I could deploy & verify via:
`forge create --rpc-url <rpc_url> --constructor-args <args> --private-key <private_key> src/<name>.sol:<name> --etherscan-api-key <api_key> --verify`.

Would get the error above when verifying if the compiler version is not explicitly stated.

**Comment by clauBv23** [comment]
I had the same issue just now. Had to explicitly define the `solc` compiler on the `.toml`.

Also, the error message didn’t help, it says as mentioned before:

```
Compiler version has to be set in `foundry.toml`. If the project was not deployed with foundry, specify the version through `--compiler-version` flag.
```
but when adding the `--compiler-version` flag  also failed saying :

```
error: unexpected argument '--compiler-version' found

  tip: a similar argument exists: '--evm-version'

```

**Comment by divine-comedian** [comment]
I had this same issue! it says add the compiler-version flag then throws an error when you add it to the command, very confusing.

**Comment by zerosnacks** [comment]
It looks like the main issue here is that the error message suggests `--compiler-version`, which is not a command. Instead users should use `--use $SOLC_VERSION`.

**Comment by zerosnacks** [comment]
Fixed in https://github.com/foundry-rs/foundry/pull/8588 by simply adding an alias to `--use`, this should solve the reported issue as it allows you to pass the `--compiler-version` flag to `forge create`.
