### ISSUE TITLE
lib imports failing

### ISSUE THREAD

**Issue by L0GYKAL** [foundry-rs/foundry#3311]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (3a462eb 2022-09-22T00:05:16.281308046Z)

### What command(s) is the bug in?

forge build

### Operating System

Linux

### Describe the bug

The foundry import remappings don't work on my computer (Linux, Manjaro) but work on another Manjaro computer that I'm using.
I tried recloning the repo but it didn't help.
My best guess is that there is something wrong with the path on this computer.
![image](https://user-images.githubusercontent.com/32228897/191781853-877cf300-8fd0-4e54-9236-8194084761b3.png)
I get this error for every file I'm importing from the `lib`.
Here are the remappings I use:
```
@ds-test/=lib/forge-std/lib/ds-test/src/
@forge-std/=lib/forge-std/src/
@openzeppelin/=lib/openzeppelin-contracts/
@solmate/=lib/solmate/src/
@superfluid-finance/=lib/protocol-monorepo/packages/ethereum-contracts/contracts/
@aave/=lib/aave-v3-core/contracts/
```

**Comment by mattsse** [comment]
just to rule out some common issues:
* all submodules are up-to-date?
* forge-std is `ethglobal-2002/lib/forge-std/`?

what values are set for the `libs` and `remappings` keys if you run `forge config --basic`?

**Comment by L0GYKAL** [comment]
- Submodules shouldn't be a problem because it works well on the other computer and it is the same git version
- forge-sdt is in `ethglobal-2022/contracts/lib/forge-std/`
- for the `forge config --basic` command, here is what I get as libs and remappings: 
![image](https://user-images.githubusercontent.com/32228897/191814107-9d7412f9-8573-40ed-abfc-7ff03db65c28.png)

**Comment by mattsse** [comment]
hmm remappings should show up here, if set

did you set them in foundry.toml? or remappings.txt?

**Comment by AlbertoCentonze** [comment]
I can confirm on my computer the same repository works fine and shows the remapping with `forge config --basic`. We also tried to set the remappings in the `foundry.toml` instead of the `remappings.txt` file but to no avail.

**Comment by L0GYKAL** [comment]
Just found out the problem:
My shell was in `ethglobal-2022` instead of `ethglobal-2022/contracts`.
It looks like it is working fine now

**Comment by AlbertoCentonze** [comment]
I'm almost ashamed of the fact that it took us so long to figure this out. Thanks for your help!

**Comment by mattsse** [comment]
awesome, closing this then
