### ISSUE TITLE
Solidity breaks on `skip` when compiled with `viaIR`

### ISSUE THREAD

**Issue by CodeSandwich** [foundry-rs/foundry#3312]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (3a462eb 2022-09-22T00:05:16.281308046Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

I have a trivial test:
```solidity
import {Test} from "forge-std/Test.sol";

contract SkipTest is Test {
    function testSkip() public {
        uint256 value = block.timestamp;
        emit log_uint(value);
        skip(1);
        emit log_uint(value);
    }
}
```
When compiling with `via_ir = true`, the output is:
```
[PASS] testSkip() (gas: 5134)
Logs:
  1
  2
```
Solidity seems to make an assumption that `block.timestamp` never changes during a call, so it doesn't make sense to actually store it in a variable. It makes perfect sense to optimize away the stack storage of a constant, but it breaks test EVMs with changeable timestamps.

I'm not sure if this is solveable in Foundry, it may be a Solidity issue. OTOH it's overall a good optimization, it breaks only with Foundry's test framework architecture, why should every DeFi user in the world pay gas for that?

**Comment by CodeSandwich** [comment]
A workaround I've found for this is to force the compiler to perform a seemingly non-no-op operation, e.g.
```solidity
uint256 value = uint248(block.timestamp);
```

**Comment by mds1** [comment]
See https://github.com/foundry-rs/foundry/issues/1373 for more info + potential solutions, glad you found another workaround

**Comment by CodeSandwich** [comment]
Thank you! Closing it then as a duplicate.
