### ISSUE TITLE
feat(`forge coverage`): allow inclusion of `coverage` targets outside of the `src` directory

### ISSUE THREAD

**Issue by lucas-manuel** [foundry-rs/foundry#3320]
### Component

Forge

### Describe the feature you would like

When running integration tests in a directory that imports contracts from multiple repos as submodules, (unless I'm missing something) there is currently no way to view the test coverage of the contracts that are imported, as they are not in the FOUNDRY_SRC directory.

It would be great to be able to specify a set of files to analyze for coverage using something like globs in the toml:

```
coverage_targets = [
    "lib/repo1/src/*.sol",
    "lib/repo1/src/proxy/*.sol"
    "lib/repo2/src/*.sol"
]
```

The main benefit is to be able to get coverage reports for contracts imported from submodules. Another benefit thought is that the total coverage report will provide a total percent coverage value in relation to specified files. This would be great for conditional branch protections based on coverage as it would not "dilute" the percent coverage with undesired contracts.

**Comment by lucas-manuel** [comment]
I have a hunch that we could filter compiler output here using globs to achieve this:  https://github.com/foundry-rs/foundry/blob/c2816ca111beec6a33dd89a592bcae1af69800a8/cli/src/cmd/forge/coverage.rs#L121

**Comment by zerosnacks** [comment]
This is now effectively possible by using a combination of `--include-libs` and a custom filter like this `forge coverage --include-libs --no-match-coverage "lib/forge-std"`. Whilst it doesn't cover all cases I think it should suffice.

Marking as `resolved`, feel free to re-open if you don't think it does
