### ISSUE TITLE
deriving github url to checkout dependencies for forge install defaults to HTTPS instead of SSH.

### ISSUE THREAD

**Issue by laudiacay** [foundry-rs/foundry#3321]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (359dd77 2022-09-15T00:04:51.833948Z)

### What command(s) is the bug in?

forge install chainlink/contracts

### Operating System

macOS (Apple Silicon)

### Describe the bug

This command fails in my shell (zsh, git usually set up with ssh credentials)

issue is definitely in this file, wherever it parses chainlink/contracts: https://github.com/foundry-rs/foundry/blob/3a913aba84feb028ad0c5fc23058ab4f4e4eae89/cli/src/cmd/forge/install.rs#L324

I run `forge install chainlink/contracts` and get the following: 
`Installing contracts in "......" (url: Some("https://github.com/chainlink/contracts"), tag: None)`

The problematic bit is the `Some("https...`. It makes me do the github authentication workflow instead of just checking out over ssh. It'd be much nicer if it just checked the repo out over SSH.

**Comment by laudiacay** [comment]
oh, hm, oof...

```
forge install org-*********@github.com:smartcontractkit/chainlink.git
Installing chainlink.git in "/**********/contracts-for-testing/lib/chainlink.git" (url: Some("https://github.com/org-*********@smartcontractkit/chainlink.git"), tag: None)
Error: 
Cloning into '***********/contracts-for-testing/lib/chainlink.git'...
fatal: unable to access 'https://github.com/org-*********@smartcontractkit/chainlink.git/': The requested URL returned error: 400
fatal: clone of 'https://github.com/org-*********@smartcontractkit/chainlink.git' into submodule path '/*********/contracts-for-testing/lib/chainlink.git' failed

```

**Comment by laudiacay** [comment]
Ok, now I see this was intentional... but why?

https://github.com/foundry-rs/foundry/blob/3a79ab08664185366bd0dd1e18fef43823f18200/cli/src/opts/dependency.rs#L76

**Comment by laudiacay** [comment]
Ok, confirmed there's another issue: 

https://github.com/foundry-rs/foundry/blob/3a79ab08664185366bd0dd1e18fef43823f18200/cli/src/opts/dependency.rs#L11

This regex doesn't accept the `org-blahblahblah@whatever-url-and-repo` style SSH links that github started using a while ago.

**Comment by mattsse** [comment]
default is https, because that should always work.

so sounds like the issue is that, if provided in full, it should checkout via githubs ssh links, like `git@github.com:foundry-rs/foundry.git` ?

**Comment by laudiacay** [comment]
No- it just breaks when you have the org-blahblahblah style tags:

```
$ forge install org-25111032@github.com:smartcontractkit/chainlink.git
Installing chainlink.git in "/Users/laudiacay/GolandProjects/chainlink-external-adapter-rs/contracts-for-testing/lib/chainlink.git" (url: Some("https://github.com/org-25111032@smartcontractkit/chainlink.git"), tag: None)
Error: 
Cloning into '/Users/laudiacay/GolandProjects/chainlink-external-adapter-rs/contracts-for-testing/lib/chainlink.git'...
fatal: unable to access 'https://github.com/org-25111032@smartcontractkit/chainlink.git/': The requested URL returned error: 400
fatal: clone of 'https://github.com/org-25111032@smartcontractkit/chainlink.git' into submodule path '/Users/laudiacay/GolandProjects/chainlink-external-adapter-rs/contracts-for-testing/lib/chainlink.git' failed
```

**Comment by laudiacay** [comment]
also, https doesn't always work, and the error just doesn't display at all
```
$ forge install smartcontractkit/chainlink
Installing chainlink in "/Users/laudiacay/GolandProjects/chainlink-external-adapter-rs/contracts-for-testing/lib/chainlink" (url: Some("https://github.com/smartcontractkit/chainlink"), tag: None)
Error: 


```

**Comment by laudiacay** [comment]
It took a while, but I got my stuff installed... I can't go in and fix all the things right now, but... here is a UX POSTMORTEM (!!!) from this experience that I hope might assist anyone who decides to fix these issues.

So: I found three issues here:

First, the regex and parsing is wrong for the org-XXXX usernames on GitHub. A test case for fixing this would just look like parsing `org-25111032@github.com:smartcontractkit/chainlink.git` into `https://github.com/smartcontractkit/chainlink`, instead of `https://github.com/org-25111032@smartcontractkit/chainlink.git` like it currently does, in [this test](https://github.com/foundry-rs/foundry/blob/3a79ab08664185366bd0dd1e18fef43823f18200/cli/src/opts/dependency.rs#L131).

Second, there's a [weird misleading silent non-error message](https://github.com/foundry-rs/foundry/issues/3321#issuecomment-1261314816) when you try to install something already installed. I'm not sure where it's coming from, but it's probably in [this else statement](https://github.com/foundry-rs/foundry/blob/3a913aba84feb028ad0c5fc23058ab4f4e4eae89/cli/src/cmd/forge/install.rs#L147) or below, maybe in install-as-submodule.

Third, if you don't have HTTPS credentials configured and you try to check out from GitHub, you're going to have a bad time because forge forces you to use HTTPS over SSH (and there's no option to configure it otherwise). This will probably be fixed with a refactor of dependency.rs to recognize ssh checkout URLs and leave them untouched, or adding a command-line switch to let it format dependencies into SSH instead of HTTPS.

**Comment by mattsse** [comment]
thanks for this.

I think the fix would be to also accept ssh and org URL variants.
