### ISSUE TITLE
Same synthax for `deal`

### ISSUE THREAD

**Issue by L0GYKAL** [foundry-rs/foundry#3322]
### Component

Forge

### Describe the feature you would like

To give gas tokens to an address we use: `vm.deal(address to, uint256 give)`
But for tokens, it works only when writing `deal(address token, address to, uint256 give)` without the `vm.` prefix.
Could you make `deal` use the same syntax wether it is about gas token or ERC20 token.

**Comment by mds1** [comment]
forge-std has a version of `deal` that behaves identically to `vm.deal`so you can use that instead 

https://github.com/foundry-rs/forge-std/blob/d26946aeef956d9d11238ce02c94b7a22ac23ca8/src/Test.sol#L112-L116

**Comment by L0GYKAL** [comment]
ok, but shouldn't all cheatcodes be called from `vm` so everyone knows it is a cheatcode?

**Comment by mds1** [comment]
`vm.*` cheatcodes like `vm.deal` are part of forge, whereas forge-std's helper methods like `deal` wrap those cheatcodes to make things easier. See https://book.getfoundry.sh/reference/forge-std/ for more info

**Comment by L0GYKAL** [comment]
I do think it is a design flow, because when we write tests we want the "unnatural" calls to start with `vm` so we we look at the code e can read it easily

**Comment by mds1** [comment]
Going to close—giving all of these the same syntax is tracked as part of #3782
