### ISSUE TITLE
`deal` function compatible with aave-tokens

### ISSUE THREAD

**Issue by L0GYKAL** [foundry-rs/foundry#3324]
### Component

Forge

### Describe the feature you would like

It would be great to have the `deal` function working with the aave-tokens.
Currently, the function `deal` gives an error about missing storage when trying to mint aave-tokens (aWETH for example).
Here is the error I'm getting: 
![image](https://user-images.githubusercontent.com/32228897/191935718-66abebe5-76e7-4f61-87fc-765542ca4d30.png)
`[FAIL. Reason: stdStorage find(StdStorage): Slot(s) not found. Counterexample: calldata=0x3c2c6ad7000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000, args=[0x0000000000000000000000000000000000000000, 1, 0]]`
![image](https://user-images.githubusercontent.com/32228897/191935991-45f2c6f3-717a-4472-9467-928986b7aa1b.png)

**Comment by mattsse** [comment]
do you have an example that I can use to debug this?

**Comment by L0GYKAL** [comment]
`// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.0;

import "@forge-std/Test.sol";
import "@forge-std/console.sol";

contract aaveVaultTest is Test {
address aPolUsdc = 0x625E7708f30cA75bfd92586e17077590C60eb4cD;

function setUp() public {
        activateFork(33424436);
        vm.deal(RANDOM, 10 ether);
        //give RANDOM enough to pay for gas
        vm.deal(RANDOM, 10 ether);
        //give random some aPolUSDC
        deal(aPolUsdc, RANDOM, 10 ether);        
    }

}

**Comment by mds1** [comment]
The cause here is that aTokens don't return a static value for `balanceOf`, instead it's dynamically calculated. There's an issue for this in forge-std [here](https://github.com/foundry-rs/forge-std/issues/140), though no one has gotten around to adding support for rebase/dynamic-balance tokens like this
