### ISSUE TITLE
trouble verifying w blockscout (on arbitrum-goerli)

### ISSUE THREAD

**Issue by wminshew** [foundry-rs/foundry#3331]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (3a462eb 2022-09-22T03:37:08.364254Z)

### What command(s) is the bug in?

forge verify-contract

### Operating System

macOS (Intel)

### Describe the bug

I am trying to verify two recently deployed [contracts](https://github.com/0xSplits/splits-vesting ) on `arbitrum-goerli`:
1. https://goerli-rollup-explorer.arbitrum.io/address/0x0a2841630f198745a55C4dab3fE98f77271949E5
2. https://goerli-rollup-explorer.arbitrum.io/address/0x652a2A2876B855d9c30d9265F882F0a486608976

from terminal (I also tried w /api appended to `verifier-url` w no luck):
```
$ forge verify-contract 0x0a2841630f198745a55C4dab3fE98f77271949E5 src/VestingModuleFactory.sol:VestingModuleFactory --chain-id 421613 --compiler-version v0.8.13+commit.abaa5c0e --num-of-optimizations 200 --verifier-url https://goerli-rollup.arbitrum.io --verifier blockscout

2022-09-23T20:57:42.762566Z ERROR etherscan: Failed to deserialize response: EOF while parsing a value at line 1 column 0 response=""

Submitting verification for [src/VestingModuleFactory.sol:VestingModuleFactory] "0x0a2841630f198745a55C4dab3fE98f77271949E5".
2022-09-23T20:57:48.035755Z ERROR etherscan: Failed to deserialize response: EOF while parsing a value at line 1 column 0 response=""
^C
```

I also tried manual verification thru the site but wasn't sure how to manipulate the json in `out/` to get it to succeed (it didn't accept as is -- i tried deleting keys it was complaining about going off the solidity docs to match solc input json but wasn't able to solve it)

note: bug may be due to blockscout service being degraded or something -- the explorer has been very funky the past couple of days (e.g. it isn't even recognizing `0x652a2A2876B855d9c30d9265F882F0a486608976` as a contract)

**Comment by mattsse** [comment]
> 2022-09-23T20:57:42.762566Z ERROR etherscan: Failed to deserialize response: EOF while parsing a value at line 1 column 0 response=""

this is definitely an empty API response, so looks like a server issue?

If you add the `--build-info` flag to `forge build` the entire standard-json compiler input should be emitted to out/build-info. you can try submitting the `input` field of that json manually.

**Comment by mattsse** [comment]
also, 

> https://goerli-rollup.arbitrum.io

I'm not sure what the api url is here

https://goerli-rollup-explorer.arbitrum.io/api-docs

iirc the blockscout api urls usually end with `/api`

**Comment by mattsse** [comment]
we currently don't have native support for arbitrum goerli,

could you please open an issue here https://github.com/gakonst/ethers-rs so we can add it

**Comment by wminshew** [comment]
> iirc the blockscout api urls usually end with `/api`
> 
> yeah I think it's: https://goerli-rollup-explorer.arbitrum.io/api

yes mentioned this in my og post
> from terminal (I also tried w /api appended to verifier-url w no luck):

i'll open an issue in ethers-rs & test manually verifying w `build-info`. I did try this before, but I think bc no code had changed it didn't output anything? might want to change that, not sure
```
λ forge build --build-info

Compiling...
No files changed, compilation skipped
```

thanks for the quick response!

**Comment by wminshew** [comment]
build-info json comes out to ~20mb but the verification flow has a 10mb file size maximum

**Comment by wminshew** [comment]
opened https://github.com/gakonst/ethers-rs/issues/1729

**Comment by wminshew** [comment]
> build-info json comes out to ~20mb but the verification flow has a 10mb file size maximum

`build-info.json` was easy enough to manually pare down. Still not able to verify but at this point pretty convinced I'm running into a blockscout server issue

**Comment by mattsse** [comment]
arbitrum-goerli is now a supported alias.

I'll write a test for this real quick, is there a faucet for arbitrum-goerli?

**Comment by wminshew** [comment]
> I'll write a test for this real quick, is there a faucet for arbitrum-goerli?

not to my knowledge -- I used https://bridge.arbitrum.io/ to bridge over goerli eth (from alchemy or paradigm faucet)

**Comment by mattsse** [comment]
I was able to successfully create and verify with blockscout:

```
forge create --chain arbitrum-goerli --rpc-url "https://goerli-rollup.arbitrum.io/rpc" --private-key "<redacted>" --verify "src/Verify.sol:Verify"   
```

I noticed some glitches on the website, but eventually it displayed the code

**Comment by wminshew** [comment]
> ```
> forge create --chain arbitrum-goerli --rpc-url "https://goerli-rollup.arbitrum.io/rpc" --private-key "<redacted>" --verify "src/Verify.sol:Verify"   
> ```

is there any reason `create --verify` would be different from `create` and then `verify-contract`?

**Comment by mattsse** [comment]
it shouldn't be since `create --verify` is just `create` + `verify-contract` under the hood.

checked both variants #3384

```
forge "verify-contract" "--chain-id" "arbitrum-goerli" "<pk>" "src/Verify.sol:Verify" "FX42Z3BBJJEWXWGYV2X1CIPRSCNN4CRXS4" "--verifier" "blockscout"
```

**Comment by wminshew** [comment]
closing this on account of me being an idiot

> also,
> > https://goerli-rollup.arbitrum.io/
> I'm not sure what the api url is here
> https://goerli-rollup-explorer.arbitrum.io/api-docs
> iirc the blockscout api urls usually end with /api
> yeah I think it's: https://goerli-rollup-explorer.arbitrum.io/api

I was using the subdomain `goerli-rollup` instead of `goerli-rollup-explorer`. Should have known from the bizarre server error.

Sorry for the hassle here

**Comment by mattsse** [comment]
:D been there
