### ISSUE TITLE
cast access-list fails to determine the function signature

### ISSUE THREAD

**Issue by SweetmanTech** [foundry-rs/foundry#3340]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (4367ce1 2022-07-07T00:40:53.513207Z)

### What command(s) is the bug in?

cast access-list 0x4f509FbA9290DBABd0e07Bf78cd01D5c7D6814E9 withdraw --rpc-url https://rpc.ankr.com/eth

### Operating System

macOS (Intel)

### Describe the bug

trying to generate an access list for the `withdraw()` method on this contract: [0x4f509fba9290dbabd0e07bf78cd01d5c7d6814e9](https://etherscan.io/address/0x4f509fba9290dbabd0e07bf78cd01d5c7d6814e9)

```
cast access-list 0x4f509FbA9290DBABd0e07Bf78cd01D5c7D6814E9 withdraw --rpc-url https://rpc.ankr.com/eth
```

### Error
<img width="1440" alt="Screen Shot 2022-09-24 at 10 31 59 PM" src="https://user-images.githubusercontent.com/23249402/192124508-bc4f2376-6449-4c3d-9c7e-2cff0bfae9bd.png">
```
The application panicked (crashed).
Message:  Unable to determine the function signature from `withdraw`. To find the function signature from the deployed contract via its name instead, a valid ETHERSCAN_API_KEY must be set.
Location: /Users/runner/work/foundry/foundry/cast/src/tx.rs:182

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
zsh: abort
```

**Comment by mattsse** [comment]
this is expected here, since `withdraw` is not a valid function signature, try `withdraw()`, this is necessary since we support lookup by name via etherscan so function signatures should be exact, even if they take no args.


improved the error message in #3342
