### ISSUE TITLE
Decoding traces takes a long time

### ISSUE THREAD

**Issue by minaminao** [foundry-rs/foundry#3344]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (906ba37 2022-09-25T00:10:50.903673Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Intel)

### Describe the bug

Reproduce:
- `forge init`
- Add `assert(0 == 1)` (must be an assert statement that **fails**)
- `forge script`

Code:
```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import "forge-std/Script.sol";

contract CounterScript is Script {
    function setUp() public {}

    function run() public {
        vm.broadcast();
        assert(0 == 1);
    }
}
```

Result:
```
$ forge script script/Counter.s.sol:CounterScript
[⠔] Compiling...
[⠰] Compiling 1 files with 0.8.17
[⠔] Solc 0.8.17 finished in 814.23ms
Compiler run successful
Traces:
```
Takes a few minutes to execute.

**Comment by minaminao** [comment]
The following sequence of commands also takes a very long time to execute, although they do not include an assert statement.
- `forge init`
- `forge test -vvvvv`

`forge test -vvvv` is fast.

**Comment by mattsse** [comment]
@joshieDo looks like there's something off with trace decoding in script mode

**Comment by mattsse** [comment]
looks like requests to https://sig.eth.samczsun.com are hanging, will be addressed here https://github.com/foundry-rs/foundry/pull/3352

**Comment by minaminao** [comment]
It can now be executed fast. Thank you.
