### ISSUE TITLE
"vm.startBroadcast" not found

### ISSUE THREAD

**Issue by L0GYKAL** [foundry-rs/foundry#3351]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What command(s) is the bug in?

forge build

### Operating System

Linux

### Describe the bug

`vm.startBroadcast(deployerPrivateKey);`
![image](https://user-images.githubusercontent.com/32228897/192152929-d8a150a9-faef-4c7d-b056-9ba9c272101f.png)
The snippet doesn't work, and in the docs we can see different ways to use the `startBroadcast` function:
- with `vm.startBroadcast`
- with `cheats.startBroadcast`

**Comment by L0GYKAL** [comment]
I also tried `broadcast`, `vm.broadcast`, `cheats.broadcast`
None of them let me compile

**Comment by mattsse** [comment]
is your forge-std up to date?

**Comment by L0GYKAL** [comment]
Here is my forge version: `forge 0.2.0 (906ba37 2022-09-25T00:04:37.878963958Z)`

**Comment by mattsse** [comment]
could you try after updating forge-std dependency

**Comment by rkrasiuk** [comment]
@L0GYKAL did you manage to resolve it? you have to update your submodule

**Comment by L0GYKAL** [comment]
Should I update it by using: `forge update`?

**Comment by L0GYKAL** [comment]
Just checked, something was broken in my project
Sorry for bothering

**Comment by mattsse** [comment]
thanks for letting us know, closing this

**Comment by lXXXw** [comment]
> Just checked, something was broken in my project Sorry for bothering

Hey @L0GYKAL , I'm having the exactly same issue and don't have a clue on what went wrong. would you mind sharing what was broken in your project?

**Comment by lXXXw** [comment]
In the snippet given in [the foundry book](https://book.getfoundry.sh/tutorials/solidity-scripting), it calls `startBroadcast` with a `uint256`
```solidity
        uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");
        vm.startBroadcast(deployerPrivateKey);
```

I see in the lib, the interface `Vm` has these two apis,
```solidity
    // Using the address that calls the test contract, has all subsequent calls (at this call depth only) create transactions that can later be signed and sent onchain
    function startBroadcast() external;
    // Has all subsequent calls (at this call depth only) create transactions that can later be signed and sent onchain
    function startBroadcast(address) external;
```
it looks like it won't accept a `uint256` value. 
What's the correct way of fetching the private key from env and use it with `startBroadcast`?

**Comment by L0GYKAL** [comment]
> > Just checked, something was broken in my project Sorry for bothering
> 
> Hey @L0GYKAL , I'm having the exactly same issue and don't have a clue on what went wrong. would you mind sharing what was broken in your project?

My Forge might not have been up to date but since some GitHub lib were broken I couldn't update forge so I gave up haha

**Comment by lXXXw** [comment]
I see what went wrong. somehow my dependency remapping became
```bash
$ forge remappings
ERC721A/=lib/ERC721A/contracts/
ds-test/=lib/solmate/lib/ds-test/src/
forge-std/=lib/openzeppelin-contracts/lib/forge-std/src/      <----  wrong
openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/
```

It should be
```bash
forge-std/=lib/forge-std/src/
```

And I couldn't find`forge-std` under my lib directory.

Reinstall of that dependency fixed it for me,
```bash
forge install foundry-rs/forge-std
```

```bash
$ forge remappings
ERC721A/=lib/ERC721A/contracts/
ds-test/=lib/forge-std/lib/ds-test/src/
forge-std/=lib/forge-std/src/
openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/
solmate/=lib/solmate/src/
```

And I can use the latest version of `Vm.sol` with the overloaded functions. Thanks @mattsse @L0GYKAL
