### ISSUE TITLE
Forge Script used to run very fast, now takes 5x longer to run with same script on update

### ISSUE THREAD

**Issue by Jovonni** [foundry-rs/foundry#3353]
I recently updated to the most recent forge version, and am observing the below.

### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What command(s) is the bug in?

forge 0.2.0

### Operating System

macOS (Intel)

### Describe the bug

I used to run forge script and it would run very fast, within 3-4 seconds (max). However, now running the same exact contracts take a lot longer when running with same configuration.

It gets hung on
```
Traces:
```

But will eventually finish.

Why does this take so much longer now compared to older versions. I haven't updated my version in about 6 months until today. After updating today, it takes several minutes (```real	3m22.765s```) to run the same exact scripts.

Test command:
```
forge script --tc <contractname> --sig "testfunc()" --fork-url <RPC> --ffi ./script/<contract>.s.sol --chain-id 1
```

Could this have to do with solidity versions? or the amount of dependencies?

If I make a blank script file, it runs fast, but why would my dependencies all of a sudden start making scripts take longer to run compared to older forge versions?

Could it be something in the configuration?

**Comment by mattsse** [comment]
yeh the sig.eth api is down which surfaced this issue, will be resolved after the fix or once the API is back up

sorry about that
