### ISSUE TITLE
Add dry run mode to `forge create`, dumping broadcast to stdout

### ISSUE THREAD

**Issue by nlnw** [foundry-rs/foundry#3356]
### Component

Forge

### Describe the feature you would like

It would be nice to have a flag for "forge create" that allows it to just output the deployment bytecode without actually sending the transaction. That way you have the option to deploy yourself manually later, or batch the deploy across many chains more easily using a different tool.

**Comment by zerosnacks** [comment]
Would this not be largely achievable by `forge inspect $CONTRACT bytecode`?

I think it does make sense to add a dry run mode to `forge create` that would dump this kind of information to stdout
