### ISSUE TITLE
Unable to pass dynamic bytes32 array to function.

### ISSUE THREAD

**Issue by amit-supraoracles** [foundry-rs/foundry#3360]
### Component

Foundryup

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (def1d61 2022-09-23T00:11:51.396013251Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

Hi Foundry !!

I am trying to pass dynamic array to a function but found that creation of dynamic array is not possible in foundry.
Please find link to the sample code here : [GITHUB LINK](https://github.com/amit-supraoracles/foundry_dynamic_array)

Thank you for taking a look !
Eagerly waiting for response on it :)

**Comment by aliberkhsl** [comment]
Hey @amit-supraoracles I don't think it's issue related to Foundry but more like solidity stuff itself other ones would answer better of course

**Comment by mattsse** [comment]
you need to allocate memory when you work with dynamic arrays.
please have a look at how dynamic arrays are allocated

**Comment by amit-supraoracles** [comment]
> you need to allocate memory when you work with dynamic arrays. please have a look at how dynamic arrays are allocated

![Screenshot from 2022-09-27 11-51-07 (1)](https://user-images.githubusercontent.com/84004854/192448913-70c7adfa-ee92-4922-9827-e61f4be9e015.png)

Thanks for your response ...
I tried it ....but seems not working.

**Comment by amit-supraoracles** [comment]
![Uploading Screenshot from 2022-09-27 13-41-14.png…]()

**Comment by amit-supraoracles** [comment]
![Screenshot from 2022-09-27 13-41-14](https://user-images.githubusercontent.com/84004854/192488450-77161dd3-0d5e-4b02-9881-d237dfcd0fd4.png)
