### ISSUE TITLE
Add `rpc` cheatcode: integrate cast rpc as cheatcode

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#3362]
### Component

Forge

### Describe the feature you would like

ref #2051
cast rpc allows sending rpc requests like ` cast rpc eth_getBalance "0xa0ee7a142d267c1f36714e4a8f75612f20a79720" "latest"`

it'd be useful to have this as general purpose cheatcode and also have some dedicated helper functions for eg. `anvil_impersonateAccount`

perhaps we can move this to a new Rpc Interface contract, wdyt @mds1 ?

**Comment by mds1** [comment]
Yea a `vm.rpc` cheat seems useful, in the past I've used ffi to deal tokens on anvil as part of a forge script but this would definitely be more convenient. Two questions:
1. What would be the UX? `vm.rpc(string memory urlOrAlias, string memory method, string memory params)`?  You'd have to format the JSON string manually which is a bit clunky but not terrible.
2. Should this be disabled by default?

**Comment by mattsse** [comment]
an array of strings is probably sufficient, same as `cast rpc` works rn.

since this is POST I think we'd need another permission for this

**Comment by Tudmotu** [comment]
Henlo, is there any way I can help implement this?

**Comment by sam-goldman** [comment]
Would this cheatcode work with the in-process node? It'd be useful to call `eth_estimateGas` without needing to spin up a standalone Anvil node (ref #6590). I'm not familiar with Foundry's internals so I don't know if this is feasible :)

**Comment by Tudmotu** [comment]
@sam-goldman I believe this cheatcode was actually implemented but not documented:
https://github.com/foundry-rs/foundry/blob/master/crates/cheatcodes/src/evm/fork.rs#L221

Did not try it out myself yet.

**Comment by Evalir** [comment]
Correct @Tudmotu — this is implemented, just undocumented. I'd be great if someone takes it up, else I'll add the docs to the book soon :).

**Comment by Evalir** [comment]
Closing as done & documented
