### ISSUE TITLE
`forge build --skip-tests`

### ISSUE THREAD

**Issue by tynes** [foundry-rs/foundry#3366]
### Component

Forge

### Describe the feature you would like

It would be nice to have a flag on `forge build` that skips building the tests. As our test suite grows, it results in the build being more slow. This would be useful for when the artifacts are desired, we use them as part of a build process to build bindings in go. We don't need to build the tests for this case.

There are a few ways to do this - skipping files that have `.t.sol` in the filename, or looking for the `IS_TEST` function in the contract ABI.

Potentially could apply the same thing for scripts

**Comment by mattsse** [comment]
supportive of that.

this can be added very easily
