### ISSUE TITLE
forge fmt incorrectly formats square brackets

### ISSUE THREAD

**Issue by mshrieve** [foundry-rs/foundry#3372]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

nightly-8d8bc28dddfe2395750ea12ff4472520a59398b6

### What command(s) is the bug in?

forge fmt

### Operating System

macOS (Apple Silicon)

### Describe the bug

With the setting `bracket_spacing = true` enabled, `forge fmt` modifies square brackets to have a space on the left-hand side.

e.g. `uint256 allowed = allowance[from][msg.sender];`
becomes `uint256 allowed = allowance[ from][ msg.sender];`

**Comment by gakonst** [comment]
reopening per https://github.com/foundry-rs/foundry/pull/3374#issuecomment-1260447347

**Comment by rkrasiuk** [comment]
@gakonst sry, i didn't notice that you reopened this one. closing in favor of #3391
