### ISSUE TITLE
Conform `forge test --debug` syntax

### ISSUE THREAD

**Issue by 0xPhaze** [foundry-rs/foundry#3376]
### Component

Forge

### Describe the feature you would like

A small nit, but when using the debugger, I think it would be great if we could just use `-m`/`--mt`/`--mc` instead of specifying the test name after `--debug`.

**Comment by 0xPhaze** [comment]
I would find it more natural if `--debug` could be added to any `forge test` and as long as only one test is matched, it's good to go. That includes only having one contract with one function or multiple contracts, but only leaving one option when specifying `--mc`.

**Comment by mds1** [comment]
Agree with @0xPhaze on syntax here, the different `--debug` syntax always trips me up. I often find myself re-running a single test to iron out errors, then trying to jump in the debugger by just adding `--debug` to my last command. So for example using `forge test --mt testX --mc ContractA --debug` should work but error if the combination of matchers gives anything except exactly 1 test (would be nice for it log all the matches in that case too)

**Comment by gakonst** [comment]
What should the behavior be if there's >1 match? Maybe we could have the error log all the matches, and prompt the user to specify:
* `--match-test`,
* `--match-path`,
* `--match-contract`  and/or
* `--sig`

so that there is only 1 match

**Comment by zerosnacks** [comment]
Marking as `resolved`

If there is >1 match it now raises:

```
Error: 
2 tests matched your criteria, but exactly 1 test must match in order to run the debugger.

Use --match-contract and --match-path to further limit the search.
Filter used:
	match-test: `test_Increment`
```

This prompts the user to narrow down:

```
forge test --debug test_Increment --match-contract Counter2
```

```
forge test --debug test_Increment --match-path test/Counter2.t.sol
```

Which works without issue
