### ISSUE TITLE
forge cache ls is broken

### ISSUE THREAD

**Issue by sakulstra** [foundry-rs/foundry#3378]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (226affb 2022-09-27T00:10:46.164877008Z)

### What command(s) is the bug in?

forge cache ls

### Operating System

Linux

### Describe the bug

Forge cache ls breaks panicks

```sh
$ forge cache ls                                                                                                                                                                               
The application panicked (crashed).
Message:  Mismatch between definition and access of `[hash: C714128042486F80]`. Could not downcast to TypeId { t: 8305170577343583588 }, need to downcast to TypeId { t: 9611275717051495212 }

Location: cli/src/cmd/forge/cache.rs:75

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
zsh: IOT instruction (core dumped)  forge cache ls
```

**Comment by mattsse** [comment]
yikes, this is due to a recent clap update.

fixing

**Comment by mattsse** [comment]
sorry about that, we migrated to newer clap-rs which now uses downcasting in some places so this went unnoticed, unfortunately.

since cast/forge --help is borked atm will trigger a release manually once merged

**Comment by sakulstra** [comment]
@mattsse are you sure this was fixed? just updated to latest nightly and it's still panicking on `forge cache ls`

**Comment by mattsse** [comment]
ah sorry didn't cut a release manually, will be shipped in next nightly in a couple hours. definitely fixed on master
