### ISSUE TITLE
Support rpc Url alias in [rpc_endpoints] in anvil

### ISSUE THREAD

**Issue by adhusson** [foundry-rs/foundry#3379]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What command(s) is the bug in?

anvil 0.1.0 (226affb 2022-09-27T00:13:00.191026Z)

### Operating System

macOS (Apple Silicon)

### Describe the bug

with `mumbai = ...` in `[rpc_endpoints]` in `foundry.toml`,

```
anvil --rpc-url mumbai
thread 'main' panicked at 'Failed to establish provider to fork url: Invalid provider url: mumbai

Caused by:
   0: builder error: relative URL without a base
   1: relative URL without a base
```

**Comment by mattsse** [comment]
anvil is kept entirely separate and does not read config.

however there's an argument to be made here that it should try to read it, if present or if a flaf --config is provided
