### ISSUE TITLE
add --standard-json option to verify-contract subcommand

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#3382]
### Component

Forge

### Describe the feature you would like

verifying contracts can be a bit tricky.
It would be useful to have an additional flag that spits out the standard-json input for a contract so it can be verified manually 

ref #3331

**Comment by rkrasiuk** [comment]
@mattsse good point, the only concern i have here is the abundance of options we already have. for instance, the `--flatten` or `--compiler-version` flags are totally ignored when verifying with sourcify

**Comment by mattsse** [comment]
we could add a valueparser for this so we can validate inputs.

I think --standard-json should just be a standalone flag or even subcommand to simply dump the standardjson input

**Comment by WEI-NERD** [comment]
any updates now? Is there a way to use `Foundry` toolkit to get standard json input?

**Comment by mattsse** [comment]
@Evalir I'm not sure if we ever added this, but should be possible to add

**Comment by Evalir** [comment]
Yep should be possible to add. Will look into it!

**Comment by horsefacts** [comment]
I used `--show-standard-json-input` to generate compiler input JSON for Etherscan. I think this one might be completed!

**Comment by Evalir** [comment]
yep this is done. Closing!
