### ISSUE TITLE
`forge fmt`'s ignore does not work if called from a subdirectory

### ISSUE THREAD

**Issue by adhusson** [foundry-rs/foundry#3385]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (226affb 2022-09-27T00:12:59.945754Z)

### What command(s) is the bug in?

forge fmt

### Operating System

macOS (Apple Silicon)

### Describe the bug

Running `forge fmt` from the project root respects the contents of `ignore`, running it from a subdirectory does not. For instance

1. Run `forge init no_ignore`
2. Add `ignore = ['**/*.sol']` to `[fmt]`
3. Mess up formatting in `Counter.sol`
4. If you run `forge fmt` from `no_ignore/`, `Counter.sol` will not be reformatted. If you run `forge fmt` from `no_ignore/src/`, it will be reformatted.

**Comment by gakonst** [comment]
Oh @rkrasiuk it might be related with canonicalizing the glob from the project root, vs cwd?

**Comment by rkrasiuk** [comment]
yup, that's the cause. we've talked about this w/ @adhusson on tg, thanks for opening the issue
