### ISSUE TITLE
expectRevert() should catch any revert

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#3389]
### Component

Forge

### Describe the feature you would like

atm `expectRevert()` expects no reason, instead `expectRevert()` should catch any revert hat happens next.

**Comment by cruzdanilo** [comment]
after this change, how can we expect a no-reason revert?

**Comment by mattsse** [comment]
hmm @DaniPopes is this still possible?

**Comment by DaniPopes** [comment]
Yes, I updated it in the cheatcodes reference: [`expectRevert(bytes(""))`](https://book.getfoundry.sh/cheatcodes/expect-revert#examples)

**Comment by mattsse** [comment]
`expectRevert("")` should also be sufficient, right?

**Comment by DaniPopes** [comment]
not sure since compilation fails on the foundry tests with just an empty string:
![image](https://user-images.githubusercontent.com/57450786/193088586-5ea10479-972c-4a94-adb4-8a60f2db6979.png)

**Comment by mattsse** [comment]
ah right, because there's also `expectRevert(string)`
