### ISSUE TITLE
Format of snapshot output messes slightly with the markdown output for GitHub steps summary

### ISSUE THREAD

**Issue by pcaversaccio** [foundry-rs/foundry#3394]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (98fa895 2022-09-28T00:08:23.30706613Z)

### What command(s) is the bug in?

forge snapshot >> $GITHUB_STEP_SUMMARY

### Operating System

Linux

### Describe the bug

Due to the green&red colouring scheme of the outputs in the snapshot logs (as well as for the test runs), the markdown summary output for `forge snapshot >> $GITHUB_STEP_SUMMARY` is slightly messed up with "�". Example (https://github.com/pcaversaccio/snekmate/actions/runs/3142773919):
![image](https://user-images.githubusercontent.com/25297591/192761518-b07eb221-04bf-4563-a452-c26b90bd6452.png)

I must admit I haven't checked so far the formatting code in the foundry code base, so not sure how complex it is to solve.

**Comment by mattsse** [comment]
you can run with `NO_COLOR=1 forge snapshot`
