### ISSUE TITLE
feat (fmt): sort imports

### ISSUE THREAD

**Issue by mds1** [foundry-rs/foundry#3396]
### Component

Forge

### Describe the feature you would like

There's two levels of sorting here:

First, the filepath level. Personally I like to sort imports as forge-std > dependencies > test > script > src, then alphabetically by path within each of those categories. This is similar to the sort order suggested in python's [style guide](https://peps.python.org/pep-0008/#imports). I'm not sure of conventions in rust or elsewhere, but don't feel too strongly on the exact order here. Maybe we default to sorting imports like rustfmt and let users toggle that off?

Then with named imports. For example, `import {foo, bar} from "src/Contract.sol"` should become `import {bar, foo} from "src/Contract.sol"`.

Probably can have a single `sort-imports` config item that covers both sort options.

**Comment by sambacha** [comment]
Import order can effect build output in some rare instances. 

here is a config using prettier that does sort
https://github.com/sambacha/prettier-config-solidity/pull/55/commits/b37967ca0267ae33a9f88f0dd1724dbf0db5bbee

**Comment by mds1** [comment]
> Import order can effect build output in some rare instances.

Interesting, does it just affect the metadata hash? I'd be surprised if this affects the contract bytecode in some non-trivial way, curious to see more docs/info on this
