### ISSUE TITLE
Support CustomError inheritance in `vm.expectRevert(abi.encodeWithSelector(Parent.myCustomError()))`

### ISSUE THREAD

**Issue by joshpwrk** [foundry-rs/foundry#3410]
### Component

Forge

### Describe the feature you would like

Given parent and child contracts:

```
contract Child {
  error myCustomError()
}

contract Parent is Child {
  function revertingFunction() {
   revert myCustomError();     
  }
}
```

The following throws a compiler error `vm.expectRevert(abi.encodeWithSelector(Parent.myCustomError()))`. With large nested systems, would be very helpful to not force specific call out of Child (e.g. `vm.expectRevert(abi.encodeWithSelector(Child.myCustomError()))`.

**Comment by mattsse** [comment]
I'm not sure I can follow here.
 
Isn't this the same error? Does the selector differ here?

FYI, we also just made `expectRevert()` catch _any_ reverts regardless of selector

**Comment by joshpwrk** [comment]
Ah thanks for the clarification @mds1 - you're right, looks like even though you can inherit a parent and call the error without the parent reference, in Solidity you do need to specify the exact child contract name when pulling the selector (e.g. `Child.myCustomError.selector`). 

I think for now, going with the explicit reference to child will do.
