### ISSUE TITLE
Anvil subprocess hangs with RUST_LOG=node::user=info

### ISSUE THREAD

**Issue by jaeaster** [foundry-rs/foundry#3414]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (d707ebe 2022-09-29T00:13:28.610248Z)

### Operating System

macOS (Apple Silicon)

### Describe the bug

I have a test which spawns an anvil process using ethers-rs and makes many concurrent rpc calls.

The test runs for a couple seconds and then inevitably hangs while awaiting an RPC call. The call could be a simple read of blockchain state or it could be sending a transaction. Here's an example log line from ethers-rs that is the last thing printed before the program hangs; in other words, I've confirmed that my program always hangs just before making an RPC call
```
[DEBUG ethers_providers::pending_transaction] Starting to poll pending tx [REDACTED]
```

It reliably hangs when I enable RUST_LOG=node::user=info, but setting node::user=warn causes the test to run perfectly fine.

e.g.
DEADLOCK ==> `RUST_LOG=info,node::user=info cargo test`

PASSES ==> `RUST_LOG=info,node::user=warn cargo test`

I have two guesses as to the source of deadlock in anvil:
1. locking related to the tracing logger
relevant code: https://github.com/foundry-rs/foundry/blob/master/anvil/src/logging.rs#L35

2. anvil child process stdout buffer becomes full and writing logs to stdout blocks
relevant code: https://github.com/gakonst/ethers-rs/blob/master/ethers-core/src/utils/anvil.rs#L287

Happy to provide more context if needed.

**Comment by jaeaster** [comment]
Related to
> anvil child process stdout buffer becomes full and writing logs to stdout blocks

The docs for Stdio::piped() say:
> Writing more than a pipe buffer’s worth of input to stdin without also reading stdout and stderr at the same time may cause a deadlock. This is an issue when running any program that doesn’t guarantee that it reads its entire stdin before writing more than a pipe buffer’s worth of output. The size of a pipe buffer varies on different targets.

https://doc.rust-lang.org/std/process/struct.Stdio.html#method.piped

Relevant code: https://github.com/gakonst/ethers-rs/blob/master/ethers-core/src/utils/anvil.rs#L225

**Comment by mattsse** [comment]
> Writing more than a pipe buffer’s worth of input to stdin without also reading stdout and stderr at the same time may cause a deadlock. This is an issue when running any program that doesn’t guarantee that it reads its entire stdin before writing more than a pipe buffer’s worth of output. The size of a pipe buffer varies on different targets.

this shouldn't be relevant since there's no stdin here.

can't use stdio::null because we need to parse the keys.

we keep the stdout handle even if we don't need it, so perhaps this is causing the issue if anvil itself logs to sdout, stderr seems to be fine (warn level).

this is an ethers-rs issue and unrelated to anvil itself.

could you perhaps try after dropping this 
https://github.com/gakonst/ethers-rs/blob/master/ethers-core/src/utils/anvil.rs#L287

**Comment by jaeaster** [comment]
Yeah that fixes it - will move to ethers-rs repo

**Comment by mattsse** [comment]
closing here
