### ISSUE TITLE
Unable to build arrays to feed in as function input parameters within test.

### ISSUE THREAD

**Issue by ZrowGz** [foundry-rs/foundry#3415]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (98fa895 2022-09-28T00:16:57.000625Z)

### What command(s) is the bug in?

forge test --match-test $(test) --fork-url ${MAINNET_RPC_URL} -vvvv

### Operating System

macOS (Apple Silicon)

### Describe the bug

Also using forge test --match-contract  and forked.

Attempting to build two arrays within the test, to then feed into the function call as input parameters. I run the forge test command & it compiles no problem. After that it just hangs, doesn't crash, and begins utilizing massive amounts of system resources (6-15gb ram, 500+ gb wired memory, 100% cpu). 

This is the function being called with these inputs:
![Screen Shot 2022-09-29 at 09 01 47](https://user-images.githubusercontent.com/80988768/193081358-34f01c9d-ffb9-4be0-9186-1e53fe2d5ab9.png)

This is the getter function that builds the second array of addresses based on the first (this works too):
![Screen Shot 2022-09-29 at 09 02 44](https://user-images.githubusercontent.com/80988768/193081525-49700126-9977-4a32-bc87-509fa1f8928d.png)

This is all this being put together within the test:
![Screen Shot 2022-09-29 at 09 04 47](https://user-images.githubusercontent.com/80988768/193081939-d66f2513-08cd-4ae1-b9ab-2c6388085627.png)

The arrays build correctly (console logs from that first part, assertEq's don't fail either): 
![Screen Shot 2022-09-29 at 09 05 12](https://user-images.githubusercontent.com/80988768/193082034-651303ea-11ca-4332-a592-5a00b904e3d6.png)

When I uncomment the createMultipleStrategyVault function, it compiles:
![Screen Shot 2022-09-29 at 09 06 59](https://user-images.githubusercontent.com/80988768/193082392-c649a29f-527d-44f6-afa6-d7d5057a96b6.png)

Then eats up system resources until I ctrl+c:
![2022-09-28 18 53 03](https://user-images.githubusercontent.com/80988768/193082702-02647558-cf17-4f73-bfc6-d0610c951d2c.jpg)
![Screen Shot 2022-09-29 at 09 08 44](https://user-images.githubusercontent.com/80988768/193082789-939b5014-5d8c-42c4-9ca9-719dba90c838.png)

I have tried switching the input param values from calldata to memory also, but no change.

**Comment by mattsse** [comment]
thanks for flagging.

could you please dump these functions as clear text here?

this is definitely tracing related (-vvvv)

**Comment by mattsse** [comment]
cc @shekhirin my best guess at this point is that the loop here makes the tracer very memory-hungry.

**Comment by shekhirin** [comment]
> what's the length of _strategyIds here?

seem to be just `1` because of this part?
<img width="238" alt="image" src="https://user-images.githubusercontent.com/5773434/193118120-d9fe91b8-e059-489f-96a3-597bbda323cd.png">

> this is definitely tracing related (-vvvv)

sounds like that, but i'd say it's not related to steps tracing because iiuc any verbosity level in `forge test` doesn't enable steps tracing

**Comment by shekhirin** [comment]
> When I uncomment the createMultipleStrategyVault function, it compiles:

does it run until the end with `createMultipleStrategyVault` commented?

also, is there any expensive computation inside that `createMultipleStrategyVault` function?

**Comment by ZrowGz** [comment]
It turned out the unchecked version of i ++ for the array loop wasn't cutting off once it went through the array.length. 

I removed that unchecked part and just did the normal way, this fixed it. BUT, it still seems like it may have been a bug that it didn't catch the cutoff? Or maybe since it was a dynamic array with 2 values, it thought the length was actually type(uint256).max?

I think that it would have stopped after the two values were looped through.

**Comment by jdbertron** [comment]
Can you elaborate on what you did exactly ?  
"I removed that unchecked part and just did the normal way, this fixed it."  is pretty vague. 
I have a similar situation, and I agree it must be a bug. 
Did you have to add a condition inside the loop to break out of it ?

**Comment by DaniPopes** [comment]
Closing as fixed since OP found a solution, if you encounter a similar issue please open another issue.
