### ISSUE TITLE
Bug: could not compile `foundry-common` due to no field `functions` on type `std::string::String`

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#3416]
### Component

Other (please describe)

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### Operating System

macOS (Intel)

### Describe the bug

When using foundry-common as a dependency I am now running into this: 

```console
error[E0609]: no field `functions` on type `std::string::String`
   --> /Users/sbacha/.cargo/git/checkouts/foundry-f7cca724e93059b0/b25f321/common/src/abi.rs:271:30
    |
271 |     let funcs = metadata.abi.functions.get(function_name).unwrap_or(&empty);
    |                              ^^^^^^^^^ unknown field

For more information about this error, try `rustc --explain E0609`.
error: could not compile `foundry-common` due to previous error

**Comment by mattsse** [comment]
there's a breaking change in this PR https://github.com/gakonst/ethers-rs/pull/1757 which will be added here shortly. 

since you have it as a dependency, you'd need to patch ethers-rs dependency until that lands

**Comment by sambacha** [comment]
> there's a breaking change in this PR [gakonst/ethers-rs#1757](https://github.com/gakonst/ethers-rs/pull/1757) which will be added here shortly.
> 
> since you have it as a dependency, you'd need to patch ethers-rs dependency until that lands

any ETA for that to land? 

Appreciate the heads up!
