### ISSUE TITLE
Wrong failing error with `expectRevert`

### ISSUE THREAD

**Issue by MerlinEgalite** [foundry-rs/foundry#3419]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (98fa895 2022-09-28T00:10:12.389142Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Intel)

### Describe the bug

You can head to this repo: https://github.com/morpho-dao/morpho-tokenized-vaults

The failing test is this one: https://github.com/morpho-dao/morpho-tokenized-vaults/blob/8bed0f75f5491320f8b8ee131db55cd0f91e596f/test/compound/TestSupplyHarvestVault.t.sol#L9

when you uncomment the following lines: https://github.com/morpho-dao/morpho-tokenized-vaults/blob/8bed0f75f5491320f8b8ee131db55cd0f91e596f/test/compound/TestSupplyHarvestVault.t.sol#L25-L34

The lines test that the code reverts when passing the `address(0)` as first input with the `ZeroAddress()` custom error.

Instead, I get the following error:

<img width="846" alt="Screenshot 2022-09-29 at 09 31 23" src="https://user-images.githubusercontent.com/44097430/193225462-138f40e0-1f90-4c77-8169-544b9ae67fe3.png">

To reproduce the test you'll need to:
- Clone the repo
- Run `git submodule update --init --recursive`
- Add an alchemy key to you `env.local` file
- Run `make s-testInitializationShouldRevertWithWrongInputs` 
- See the test failing

**Comment by mattsse** [comment]
I don't think the submodule: `git@github.com:morpho-dao/morpho-v1.git` is public?

**Comment by mds1** [comment]
@mattsse here's another way to reproduce:
- Clone this repo https://github.com/ScopeLift/l2-optimizoooors
- Define the required RPC [env vars](https://github.com/ScopeLift/l2-optimizoooors/blob/3e2d15e0d7c6d11f661768a557e3b7cdbb7f5e24/foundry.toml#L56-L57)
- Uncomment the logic within in [these two tests](https://github.com/ScopeLift/l2-optimizoooors/blob/3e2d15e0d7c6d11f661768a557e3b7cdbb7f5e24/test/Connext.t.sol#L124-L142)
- Run those two tests

**Comment by MerlinEgalite** [comment]
> I don't think the submodule: `git@github.com:morpho-dao/morpho-v1.git` is public?

Ah yes, sorry we'll open source it very soon. I'll try to do a small reproducible test unless @mds1 example works fine!

**Comment by mds1** [comment]
This appears resolved, as my reproduction steps now give the correct error
