### ISSUE TITLE
log_named_bool do not working with forge  test -vv 

### ISSUE THREAD

**Issue by justforfunya** [foundry-rs/foundry#3420]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (7dda095 2022-09-17T00:13:22.208584575Z)

### What command(s) is the bug in?

  forge  test -vv 

### Describe the bug

log_named_bool  does not log anything when  run with  forge  test -vv

**Comment by mattsse** [comment]
I don't think `log_named_bool` even exists?

**Comment by mds1** [comment]
Yea, it does not exist. Another workaround is `log_named_uint("name", bool ? uint256(1) : uint256(0))` or ``log_named_string("name", bool ? "true" : "false")``

Alternatively, we have added additional `log_*` helpers to foundry, and I'd support adding a `log_bool` and `log_named_bool`. @justforfunya if you're interested in PR'ing this, check out these two PRs where we added other log methods 
- https://github.com/foundry-rs/foundry/pull/1916
- Then in forge-std add them here https://github.com/foundry-rs/forge-std/blob/cb69e9c07fbd002819c8c6c8db3caeab76b90d6b/src/Test.sol#L21-L26
