### ISSUE TITLE
Starknet support for Forge

### ISSUE THREAD

**Issue by Bernardstanislas** [foundry-rs/foundry#3422]
### Component

Forge

### Describe the feature you would like

We'd like to carry on with https://github.com/foundry-rs/foundry/pull/739 and draft a support for Starknet contract testing.

Cairo-rs – the Rust implementation of the Cairo VM – is getting [more and more ready](https://twitter.com/ClassLambda/status/1575605473671192576), so it is a good time to work on this integration.

As discussed with @mattsse we have two options for this:
- work on isolating a `Runtime` trait and a `Compiler` trait to be able to swap a `ethers-rs` implementation with a `cairo-rs` implementation
- target only the `forge test` command to get it to work on starknet contracts, hacking our way into the codebase

We'd rather go for the second solution to get a first taste of what it will look like in the better-structured first option.

### Additional context

We are hosting a hacking week in Lisbon at the end of Oct'22 prior to the [starknet.cc conference](https://www.starknet.cc/).
Core ecosystem members will attend and spend some time building on Starknet projects.
Having a Forge-grade test runner for Starknet is an ambitious but achievable subject we'd like to hack on during these few days.

**Comment by zerosnacks** [comment]
Closing as `stale` for now

Largely superseded by https://github.com/foundry-rs/starknet-foundry I feel

Feel free to re-open
