### ISSUE TITLE
Forge test errors with unexpected error type when using vm.expectRevert under certain conditions on mainnet forks

### ISSUE THREAD

**Issue by ape-dev-cs** [foundry-rs/foundry#3424]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (7257375 2022-09-30T00:19:04.033244Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

On some tests where I'm forking Ethereum mainnet and expecting an arithmetic exception (using `vm.expectRevert(stdError.arithmeticError);`), I'm hitting a test failure wherein the test unexpectedly fails with a different exception than the expected one, which is as follows:

`FAIL. Reason: Error != expected error: Contract <address> does not exist != NH{q]`

This address is the address of an EOA which I'm transferring funds to in the method being tested using:

(success, ) = address.call{value: balance}

The address is not, in fact, that of a contract, so I'm confused as to why this bug surfaces at all. Foundry does hit the arithmetic exception in the stack trace, but by the time it's bubbled up it's replaced with the exception I'm hitting. The relevant part of the stack trace is as follows:

```
    ├─ [63840] Transistor::createTransistor{value: 8000000000000000}(1) 
    │   ├─ [0] console::log(8000000000000000) [staticcall]
    │   │   └─ ← ()
    │   ├─ [6329] GnosisSafeProxy::fallback{value: 2000000000000000}() 
    │   │   ├─ [1504] GnosisSafe::fallback() [delegatecall]
    │   │   │   ├─ emit SafeReceived(sender: Transistor: [0xE5DdfD2Af9E515e726130E69B98022E69De6A267], value: 2000000000000000)
    │   │   │   └─ ← ()
    │   │   └─ ← ()
    │   ├─ [0] 0x454cD1e89df17cDB61D868C6D3dBC02bC2c38a17::fallback{value: 2000000000000000}() 
    │   │   └─ ← ()
    │   ├─ [0] 0xc766B8c9741BC804FCc378FdE75560229CA3AB1E::fallback{value: 2000000000000000}() 
    │   │   └─ ← ()
    │   ├─ [2856] ERC20::transferFrom(0xDA9dfA130Df4dE4673b89022EE50ff26f6EA73Cf, Transistor: [0xE5DdfD2Af9E515e726130E69B98022E69De6A267], 6000000000000000000) 
    │   │   └─ ← "Arithmetic over/underflow"
    │   └─ ← "Contract 0xc766B8c9741BC804FCc378FdE75560229CA3AB1E does not exist"
    └─ ← "Error != expected error: Contract 0xc766B8c9741BC804FCc378FdE75560229CA3AB1E does not exist != NH{q"```

If it would be useful for me to push up a minimal reproduction of this bug I can probably do so in the coming day or two.

**Comment by mattsse** [comment]
there's like something off with how we unwind revert in forking mode where we check for an address.

would appreciate a repro
