### ISSUE TITLE
Feature request: add jump to step in debugger

### ISSUE THREAD

**Issue by iFrostizz** [foundry-rs/foundry#3430]
### Component

Forge

### Describe the feature you would like

When debugging contracts at the opcode level, the debugger is very useful.
Sometimes, we are making a small change and would like to jump back to the instruction to see if a wrong layout in the memory / stack / storage is repaired, especially when there is a lot of code to instantiate a contract, foundry assertions, and so on it can take quite a lot of time to jump to the correct instruction.
Solution would be to implement vim-like jump to line with `<line> <Shift-G>`
As it wouldn't make sense to jump to program counter, because the execution will probably go to the same PC more than once, I would propose to explicitly display the "current step" in the debugging interface and to be able to jump to this one.

If that makes sense for you, I would be happy to work on it :)

Thanks for this amazing project

**Comment by mds1** [comment]
I do think a way to quickly jump between instructions would be useful, it can be very tedious currently. 

Other interfaces I've thought about are:
- A `vm.breakpoint(bool)` cheat in source code that sets a breakpoint for the debugger if the condition is met, then have a keyboard shortcut for jumping between breakpoints. One downside is this doesn't carry over to using the debugger for forked networks / txs where you can't easily modify the code
- Within the debugger, press a key to activate "jump to" and enter either (1) a contract (by name or address) and line number, (2) a PC / current step, (3) an opcode name (where (2) is similar to what you're describing)

**Comment by iFrostizz** [comment]
Mh could you clarify why would it be tedious ? Before opening the issue I did saw this step counter in the code, then all the steps are probably cached and we can walk between steps in the debugger, or I probably missed something.
- Good point but yes as you said sometimes we cannot modify the code (forked network), or we also sometimes don't want to modify the code, still in the context of a forked network contract because it would offset the next JUMPDEST pc
- We could jump to PC, but that would require extra work and maybe building trees because as you know with jumps, PC are not following linearly, they can come multiple times, plus how to choose which PC to jump to because it may appear multiple times in the debugger screen
- For jumping to line number, very good point, but not language agnostic, but could be a very interesting feature for sure
- Jumping to opcode name also has kind of the same challenges as PC, for this we could imagine a vim-like search with `/`, that would be nice too, but only effective for opcodes that are not used much, else there would be too much occurrences to be able to jump to the right place

**Comment by mds1** [comment]
Oh sorry I meant the current behavior can be tedious when you want to get back to the same spot in execution multiple times, so I'm supportive of this issue. But I'll defer to @onbjerg @mattsse @brockelmore here as I'm not too familiar with the current debugger implementation to know which is best / most practical

**Comment by brockelmore** [comment]
You can use `<step number> j` and it will step that many number of times. i.e. `100j` will move to step 100.

**Comment by iFrostizz** [comment]
can I open a PR ?

**Comment by mds1** [comment]
Just to clarify since we discussed a few ideas, which exactly do you plan to implement? Also I know @onbjerg was working on refactoring the debugger in https://github.com/foundry-rs/foundry/pull/2692, not sure what the latest is there though

**Comment by iFrostizz** [comment]
Easiest would be the one I proposed, but the breakpoint seems to be a good candidate and kinda complementary to this feature.
We could jump between breakpoints in the debugger, but we could also do
`vm.breakpoint(string)` where we could either input a char, multiple chars, a number as shortcuts. Issue is that it must not collide with other key binding.
Other ideas are very good, but harder to implement (I think) and/or not language agnostic. If you have a strong opinion on those I could reconsider though.

**Comment by iFrostizz** [comment]
Let's wait for the debugger refactor to be merged

**Comment by AllTradesz** [comment]
> Let's wait for the debugger refactor to be merged

#2692 was closed as stale last month, in case you're still interested to work on this. :)

**Comment by iFrostizz** [comment]
> > Let's wait for the debugger refactor to be merged
> 
> @iFrostizz #2692 was closed as stale last month, in case you're still interested to work on this. :)

Good point ! I'll push on my existing PR before opening a new one
