### ISSUE TITLE
Adding cheatcode vm.mint(token, to, amount)

### ISSUE THREAD

**Issue by hananbeer** [foundry-rs/foundry#3435]
### Component

Forge

### Describe the feature you would like

Often it is useful to mint yourself some tokens and you have to come up with some unique ways to get those tokens, probably doing some vm.prank and transfer, but this also requires finding a "victim" address. This is less than ideal. (once or twice I even had tokens "siphoned from the victim" while testing on latest block, ie. victim transferred tokens out)

I propose a generic method for implementing a cheatcode `vm.mint(token, to, amount)` to mint yourself tokens:

- call token.balanceOf
- see what slots are being accessed
- set the slot to amount (where slot value == token.balanceOf(to))

This would require listening to sload (or more complex analysing the contract bytecode) but eventually this will be generic for most if not all tokens.

Alternatively, replacing the tokens code entirely might work better. (with delegatecall to original code if msg.data != balanceOf)

**Comment by rkrasiuk** [comment]
@hananbeer can we close this one per twitter replies? 
https://twitter.com/gakonst/status/1576721992035618818
https://twitter.com/msolomon44/status/1576721884778885120

**Comment by hananbeer** [comment]
yes, my bad
