### ISSUE TITLE
Moonbeam XC20 Support

### ISSUE THREAD

**Issue by gtsui** [foundry-rs/foundry#3436]
### Component

Forge

### Describe the feature you would like

Moonbeam Network has this concept of XC20 which are custom precompiles that are meant to mimic ERC20 interface:

https://docs.moonbeam.network/builders/xcm/xc20/overview/

Unfortunately it looks like when doing mainnet fork tests on forge that XC20 contract addresses are not supported. Is this something that can be added as a new feature and what work needs to be done to make it possible?

Foundry is an awesome project and itd be great for the tool be supported fully for us devs building on Moonbeam Network

**Comment by mattsse** [comment]
you can patch a precompile contract by deploying it at the specific address via. `get(Deployed)Code` + `etch`

https://book.getfoundry.sh/cheatcodes/get-deployed-code

**Comment by DaniPopes** [comment]
We currently only support mainnet precompiles which are implemented in [Revm](https://github.com/bluealloy/revm), and there's no way to configure this in Foundry. See also https://github.com/foundry-rs/foundry/issues/748.
