### ISSUE TITLE
Can't do anything with a fresh project because of solc error

### ISSUE THREAD

**Issue by rafales** [foundry-rs/foundry#3441]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (d7733ee 2022-10-03T00:06:06.841223Z)

### What command(s) is the bug in?

forge build

### Operating System

macOS (Apple Silicon)

### Describe the bug

So I can't use forge in any way and I have no idea how to debug this problem.

```bash
> forge init hello
Initializing /Users/rafal/Code/hello...
Installing forge-std in "/Users/rafal/Code/hello/lib/forge-std" (url: Some("https://github.com/foundry-rs/forge-std"), tag: None)
    Installed forge-std
    Initialized forge project.

~/Code
> cd hello 

~/Code/hello
> forge build
[⠊] Compiling...
[⠒] Installing solc version 0.8.15
[⠃] Successfully installed solc 0.8.15
Error: 
Solc Error: 

```

**Comment by mattsse** [comment]
hmm interesting, unclear why this only happened when installing solc.
