### ISSUE TITLE
`The application panicked (crashed). Message:  No target contract Location: utils/src/lib.rs:146`

### ISSUE THREAD

**Issue by bstchow** [foundry-rs/foundry#3442]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (d7733ee 2022-10-03T00:08:41.50531996Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

Running into the following issue when running `forge test`.

```
The application panicked (crashed).
Message:  No target contract
Location: utils/src/lib.rs:146

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: __libc_start_main<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
/home/runner/work/_temp/obfusedworkername.sh: line 1:  2819 Aborted                 (core dumped) RUST_BACKTRACE=full forge test -vvv --gas-report --force
Error: Process completed with exit code 134.
```

This occurs when running forge test with combinations of the flags `-vvv`, `--optimize`, and `--gas-report`.
This does not occur on my local, it only occurs when running in a GitHub action context.

**Comment by mattsse** [comment]
hmm, this looks like a linking issue.

looks like you're running this from a script, could you check that the root path is correct?

**Comment by bstchow** [comment]
@mattsse Thank you for the quick response. I just double checked our path where we are running `forge test` and it seems correct (the same directory as where I run it in my local).

I should also note this job was running without crashes before. The only common difference between failing jobs and successful jobs is some new Solidity contracts and Solidity Forge tests that we have added.

**Comment by mattsse** [comment]
> is some new Solidity contracts

those are checked in? it works locally but not in CI?

is this public?

it looks like the contract depends on another contract that we don't find in the project graph.

**Comment by bstchow** [comment]
@mattsse Gotcha - I'll take a look at the contract dependencies and see if one of them is incorrectly referenced

**Comment by mattsse** [comment]
also try forge tree 

maybe there's something off with different versions

**Comment by bstchow** [comment]
Hmm `forge tree` doesn't seem to be outputting any error messages

**Comment by bstchow** [comment]
@mattsse The updates you merged into main were extremely helpful.

Now I am able to reproduce the issue locally (I suspect some artifact in my local foundry cache was preventing the error from occurring) and I get a helpful error message:
```
The application panicked (crashed).
Message:  No target contract named FiduHelpers.json:FiduHelpers
Location: utils/src/lib.rs:151
```

However it seems like my path to FiduHelpers.json is correct where it is referenced in a separate solidity files.

FiduHelpers.sol has a `pragma solidity ^0.8.16;` statement at the top of the file, and the contract that imports it also has a `pragma solidity ^0.8.16;` statement at the top of the file.

I noticed Hardhat was compiling the build artifacts into two separate Solidity version named files FIduHelpers.0.8.16.json & FiduHelpers.0.8.17.json, and I guessed that Forge might be doing something similar under the hood during compilation.

I also noticed the following under our solidity-files-cache.json:
```
    "contracts/library/FiduHelpers.sol": {
      "lastModificationDate": 1665076677316,
      "contentHash": "f237dca93231eb55cc4012593c0eea8b",
      "sourceName": "contracts/library/FiduHelpers.sol",
      "solcConfig": {
        "settings": {
          "optimizer": {
            "enabled": true,
            "runs": 200
          },
          "metadata": {
            "bytecodeHash": "ipfs"
          },
          "outputSelection": {
            "*": {
              "": [
                "ast"
              ],
              "*": [
                "abi",
                "evm.bytecode",
                "evm.deployedBytecode",
                "evm.methodIdentifiers",
                "metadata"
              ]
            }
          },
          "evmVersion": "london",
          "libraries": {}
        }
      },
      "imports": [],
      "versionRequirement": "^0.8.16",
      "artifacts": {
        "FiduHelpers": {
          "0.8.17+commit.8df45f5f.Darwin.appleclang": "FiduHelpers.sol/FiduHelpers.0.8.17.json"
        }
      }
    },
```


When I pin `FiduHelpers` to Solidity 0.8.16 by modifying the pragma statement in `FiduHelpers` to `pragma solidity 0.8.16;`, the error no longer occurs.

I also see these changes in the solidity-files-cache.json file:
```
    "contracts/library/FiduHelpers.sol": {
      "lastModificationDate": 1665076829358,
      "contentHash": "9c660b81b0dde7332e6ce49b4c49971e",
      "sourceName": "contracts/library/FiduHelpers.sol",
      "solcConfig": {
        "settings": {
          "optimizer": {
            "enabled": true,
            "runs": 200
          },
          "metadata": {
            "bytecodeHash": "ipfs"
          },
          "outputSelection": {
            "*": {
              "": [
                "ast"
              ],
              "*": [
                "abi",
                "evm.bytecode",
                "evm.deployedBytecode",
                "evm.methodIdentifiers",
                "metadata"
              ]
            }
          },
          "evmVersion": "london",
          "libraries": {}
        }
      },
      "imports": [],
      "versionRequirement": "=0.8.16",
      "artifacts": {
        "FiduHelpers": {
          "0.8.16+commit.07a7930e.Darwin.appleclang": "FiduHelpers.sol/FiduHelpers.json"
        }
      }
    },
```

**Comment by tommyrharper** [comment]
I am getting this same issue now in my Github Action CI:
```
Compiler run successful!
The application panicked (crashed).
Message:  No target contract named contracts/libraries/SafeDecimalMath.sol:SafeDecimalMath
Location: utils/src/lib.rs:[26](https://github.com/Kwenta/token/actions/runs/5560678914/job/15063354666#step:9:27)9
```

Did you work out what this issue is?

**Comment by DaniPopes** [comment]
This is likely fixed, we refactored library linking and we've had many other improvements
