### ISSUE TITLE
Improve compilation artifacts structure for multiple solc version

### ISSUE THREAD

**Issue by montyly** [foundry-rs/foundry#3450]
### Component

Forge

### Describe the feature you would like

Now that foundry supports multiple compiler versions, it creates `out/filename/contractName-<compiler-version>.json` compilation artifacts. However it is difficult to retrieve what compilation units was used for the files. This makes difficult to support for third party tools (slither/echidna/..).

It would be great to clean the directory structure. For example:
- Creating a directory per compilation unit: `out/some_id_of_compilation_unit/filename/...`. Where `some_id_of_compilation_unit` could be the hash of the compilation settings, or something similar
- Create a mapping `some_id_of_compilation_unit -> compiler setting` in a file , to allows third party tools to retrieve this information

Such structure will also allow to be robust if a user wants to use the same compiler version, but with different settings (ex: with/without the new IR pipeline / optimization/ ...)

**Comment by montyly** [comment]
Is there any update on this? It is preventing multiple users from using foundry with slither/echidna/...

**Comment by mattsse** [comment]
sorry for not responding, this slipped through...

could elaborate on what you mean by `compilation unit` here?

> `out/some_id_of_compilation_unit/filename/.... Where some_id_of_compilation_unit could be the hash of the compilation settings, or something similar

I think this could be very confusing if you want to look for a specific Artifact (`Counter.sol` for example) and then you first need to figure out what compilation unit it's part of. 
However, if you have a single solc then there should be only one, right? Which would make it redundant for those cases.

> However it is difficult to retrieve what compilation units were used for the files

can you describe how this is currently being done and what info is required?

The cache currently has a `file, config -> [artifacts]` mapping

**Comment by zerosnacks** [comment]
Marking as `not planned`, `slither` has since added support for multiple compilation targets with foundry: https://github.com/crytic/crytic-compile/pull/348
