### ISSUE TITLE
no coverage data from constructor

### ISSUE THREAD

**Issue by izlatkin** [foundry-rs/foundry#3453]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (5342d1c 2022-09-26T16:07:26.540702Z)

### What command(s) is the bug in?

forge coverage --match constructor_1 --report lcov

### Operating System

macOS (Intel)

### Describe the bug

There is no coverage information from the constructor block (see screenshot)
<img width="693" alt="image" src="https://user-images.githubusercontent.com/16242682/193937885-49ac3c9b-83fa-4520-b78c-ebd8f5ee05df.png">

source: constructor_1.sol

```
contract C {
     uint x;
	constructor(uint b) {
		if (b > 0) {
			x = 1;
			return;
		}
		else {
			x = 2;
			return;
		}
		x = 3;
	}

    function f(uint _x) public {
        uint a = 3;
        if (x > 2) {
            a = 5;
        }
        x = _x;
        assert(a >= 3);
    }

    function set_max(uint _x, uint _y) public {
        if(_x > _y){
            x = _x;
        }else{
            x = _y;
        }
    }
}
```
Test:

```
import "forge-std/Test.sol";
import "../src/constructor_1.sol";

contract constructor_1_Test is Test {
	C c0;
	C c1;
	C c2;
	function setUp() public {
		c0 = new C(1);
		c1 = new C(1);
		c2 = new C(0);
	}
	function test_constructor_1_0() public {
		c0.f(1);
		assertTrue(true);
	}
	function test_constructor_1_1() public {
		c1.f(0);
		assertTrue(true);
	}
	function test_constructor_1_2() public {
		c2.f(1);
		assertTrue(true);
	}
}
```

**Comment by malteish** [comment]
Seeing the same issue: no coverage information on constructors. 
forge 0.2.0 (d707ebe 2022-09-29T00:08:26.243971558Z)

**Comment by h0tw4t3r** [comment]
Same issue

`forge 0.2.0 (6d94a10 2022-11-04T00:23:35.961201Z)`
