### ISSUE TITLE
Add global makePersistent flag within a fork

### ISSUE THREAD

**Issue by ColinPlatt** [foundry-rs/foundry#3458]
### Component

Forge

### Describe the feature you would like

When using vm.createFork (and createSelectFork) and multiple instances of vm.rollFork (but within a single logical fork, i.e. EVM forked at point in time and rolled forward multiple times), the user has to specify to keep the state of each individual contract changed. Ideally there would be a vm flag that allows for *all* contract address states to be brought forward through each rollFork.

Example (current):
vm.CreateFork(MainnetFork, 100)
arbContract0 = new contractArbitrary();
WETH.transfer(arbContract0, 1e18);
vm.makePersistent(address(arbContract0));
vm.makePersistent(address(WETH));

vm. rollFork(101);
assertEq(WETH.balanceOf(address(arbContract0), 1e18);
vm.makePersistent(address(arbContract0));
vm.makePersistent(address(WETH));

vm. rollFork(102);
assertEq(WETH.balanceOf(address(arbContract0), 1e18);
vm.makePersistent(address(arbContract0));
vm.makePersistent(address(WETH));

Suggested:
vm.CreateFork(MainnetFork, 100)
**vm.makeGlobalPersistent(MainnetFork);**
arbContract0 = new contractArbitrary();
WETH.transfer(arbContract0, 1e18);

vm. rollFork(101);
assertEq(WETH.balanceOf(address(arbContract0), 1e18);

vm. rollFork(102);
assertEq(WETH.balanceOf(address(arbContract0), 1e18);

**Comment by mattsse** [comment]
the persistent accounts should remain after `rollFork`, no?

I'm not entirely sure but this should be the case if they're marked as persistent in the setup function

**Comment by ColinPlatt** [comment]
I ran some tests today and it definitely did have issues persisting across
rollFork.

Granted the tests I ran were more exotica than what I described. But
something like a Uniswap addliquidity which created a new token didn't
persist unless you specified, and also the token and weth needed to be
marked.

Here's the test if you're interested:
https://github.com/ColinPlatt/warpToken/blob/53314282e9aba201cc44f0926cdfbdec9c4668e9/test/warpTokenFork.t.sol

**Comment by mattsse** [comment]
there could still be some edge cases, as juggling all the different states is a bit horrible.

I can see how this can require additional calls to makePersistent, there are overloads that accept multiple addresses though: https://github.com/foundry-rs/forge-std/blob/master/src/Vm.sol#L208-L209

I guess this feature could be achieved with a helper function and an address array that (re-)registers all addresses that should be marked as persistent.

**Comment by ColinPlatt** [comment]
Yes there are definitely ways to make it slightly cleaner, I just wonder if having an integrated "keep everything" flag wouldn't be a more logical experience within a single fork, as you would not expect to lose state within a single fork as you move forward in time. 

My test is exotic, but losing state within Uniswap LPs over time is probably a fairly common headache.

Your call though, can close this if you think it's too much of an edge case.

**Comment by mds1** [comment]
Is this requesting a `vm.makeAllPeristent()` cheat that makes all subsequent deploys persistent on all forks, even after changing forks? If so, that feels like a footgun and I'm not sure why you'd want that, and it feels safer to have to manually specific persistent contracts. Going to close this, but happy to be convinced of the use case and reopen (or maybe I misunderstood)
