### ISSUE TITLE
Forge fmt doesn't break lines to preserve line length in function calls (other cases)

### ISSUE THREAD

**Issue by CodeSandwich** [foundry-rs/foundry#3461]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (f19fd81 2022-10-06T00:10:55.884113912Z)

### What command(s) is the bug in?

forge fmt

### Operating System

Linux

### Describe the bug

This is a similar issue to https://github.com/foundry-rs/foundry/issues/3033, but I've found different cases. The fix may be almost the same, but just in case it's something different I'm opening a new issue.

Forge fmt doesn't mind small violations of the line length in function calls. Here are examples:

```solidity
contract NotSoPretty {
    function foo() public pure {
        uint256 baz;
        // These lines have length 121
        baz = bar(1111111111111111111111111111111111111111111111111111111111, 11111111111111111111111111111111111111111);
        baz =
            bar(111111111111111111111111111111111111111111111111111111111111111, 11111111111111111111111111111111111111);
        bar(1111111111111111111111111111111111111111111111111111, 11111111111111111111111111111111111111111111111111111);

        // Extend the lines to 122 and they finally break
        baz =
            bar(1111111111111111111111111111111111111111111111111111111111, 111111111111111111111111111111111111111110);
        baz = bar(
            111111111111111111111111111111111111111111111111111111111111111, 111111111111111111111111111111111111110
        );
        bar(
            1111111111111111111111111111111111111111111111111111, 111111111111111111111111111111111111111111111111111110
        );
    }

    function bar(uint256, uint256) private pure returns (uint256) {
        return 0;
    }
}
```

**Comment by mds1** [comment]
I'm not sure what the actual issue here is, so going to close this. My understanding is that the configured max line width of e.g. 120 is not a hard limit, but a guideline, and sometimes may be exceed by a 1 (or 2?) characters. This is common in other formatters as well

**Comment by CodeSandwich** [comment]
The issue is that `forge fmt` doesn't break lines correctly, in some cases it allows 1 character too long lines. I haven't seen a single formatter treating the line length as a guideline, the maximum line length is always respected. The similar issue https://github.com/foundry-rs/foundry/issues/3033 was treated as a bug and fixed in https://github.com/foundry-rs/foundry/pull/3082. You can see a number of references to that issue, because people expect the formatter to keep the line length and doing otherwise can break other tools.

I can't demand a fix, but please, at least reopen the issue, because it's an actual bug and only if it's flagged as such it has a chance of ever being fixed.

**Comment by mds1** [comment]
I see, thanks for clarifying. There is an issue to make the line length a hard requirement is #4450, so this is being tracked there
