### ISSUE TITLE
ParserError when build. Search imported sol file path wrong

### ISSUE THREAD

**Issue by sealter** [foundry-rs/foundry#3462]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (f19fd81 2022-10-06T00:10:55.884113912Z)

### What command(s) is the bug in?

forge build

### Operating System

Linux

### Describe the bug

I write nft tutorial from foundry book: https://book.getfoundry.sh/tutorials/solmate-nft.

When  building by `forge build`, I get error:

```
[⠢] Compiling...
[⠆] Compiling 4 files with 0.8.10
[⠰] Compiling 6 files with 0.8.17
[⠊] Solc 0.8.10 finished in 7.37ms
[⠒] Solc 0.8.17 finished in 1.47s
Error:
Compiler run failed
error[6275]: ParserError: Source "lib/openzeppelin-contracts/contracts/contracts/utils/Strings.sol" not found: File not found.
 --> src/NFT.sol:5:1:
  |
5 | import "openzeppelin-contracts/contracts/utils/Strings.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

The searching path is wrong `contracts/utils/Strings.sol` not `contracts/contracts/utils/Strings.sol`

My sys is Ubuntu-20.04 in wsl2.

**Comment by mattsse** [comment]
this looks like an issue with the auto remappings detection.

what does `forge remappings` print?

**Comment by sealter** [comment]
> 

`forge remappings` result is:
```
ds-test/=lib/solmate/lib/ds-test/src/
forge-std/=lib/forge-std/src/
openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/
solmate/=lib/solmate/src/
```
I know， my wrong, I wrote `remappings.txt` to `remapping.txt`.  fix it to `remappings.txt` is OK.

Thank you very much.

**Comment by sealter** [comment]
> this looks like an issue with the auto remappings detection.
> 
> what does `forge remappings` print?



> this looks like an issue with the auto remappings detection.
> 
> what does `forge remappings` print?

`forge remappings` result is:
```
ds-test/=lib/solmate/lib/ds-test/src/
forge-std/=lib/forge-std/src/
openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/
solmate/=lib/solmate/src/
```
I know， my wrong, I wrote `remappings.txt` to `remapping.txt`.  fix it to `remappings.txt` is OK.

Thank you very much.
