### ISSUE TITLE
Support for enums in forge bindings

### ISSUE THREAD

**Issue by nikkolasg** [foundry-rs/foundry#3469]
### Component

Forge

### Describe the feature you would like

Enums in solidity are not translated to rust enums in the bindings. The value is currently only "u8" that means we loose the link between solidity and rust and have to manually define our own enums.
Being to directly refer to the solidity enum in our rust bindings would greatly simplify the life of the developer there.

**Comment by mattsse** [comment]
closing as dup of https://github.com/foundry-rs/foundry/issues/1596
