### ISSUE TITLE
feat(`cast`): add `--etherscan-api-key` flag to resolve contract names

### ISSUE THREAD

**Issue by mds1** [foundry-rs/foundry#3473]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What command(s) is the bug in?

cast run

### Describe the bug

```
$ cast run 0x8346762a8c1d7ce70be23c1b68ff920ffb6bca8fd62323e6c1d108f209e0b45d --rpc-url $OPTIMISM_RPC_URL
Executing previous transactions from the block.
Traces:
  [429891] PurgeableSynth::modifyPositionWithTracking(79573547589616810, 0x4b57454e54410000000000000000000000000000000000000000000000000000)
    ├─ [9111] 0xE8c41bE1A167314ABAF2423b72Bf8da826943FFD::requireFuturesMarketActive(0x7345544800000000000000000000000000000000000000000000000000000000) [staticcall]
    │   └─ ← ()
    ├─ [2789] 0xE8c41bE1A167314ABAF2423b72Bf8da826943FFD::requireSynthActive(0x7345544800000000000000000000000000000000000000000000000000000000) [staticcall]
    │   └─ ← ()

(rest of trace omitted for brevity)
```

If you look up [0xE8c41bE1A167314ABAF2423b72Bf8da826943FFD](https://optimistic.etherscan.io/address/0xE8c41bE1A167314ABAF2423b72Bf8da826943FFD#code) you'll notice that contract has a name of `SystemStatus`, but this does not show up in the trace

**Comment by DaniPopes** [comment]
I think the problem here is that the etherscan trace identifier is instantiated using project config / defaults:

https://github.com/foundry-rs/foundry/blob/e9eab884fa02f742b3f4a5944f92a7b6f1844d8e/cli/src/cmd/cast/run.rs#L65-L67

https://github.com/foundry-rs/foundry/blob/e9eab884fa02f742b3f4a5944f92a7b6f1844d8e/cli/src/cmd/cast/run.rs#L175-L176

which defaults to mainnet chain and so most calls to etherscan will return "not verified" responses:

```log
TRACE etherscanidentifier: using etherscan identifier chain=Some(Named(Mainnet)) url="https://api.etherscan.io/api"
TRACE etherscanidentifier: identify 16 addresses
TRACE etherscanidentifier: fetching info for 0x92bac115d89ca17fd02ed9357ceca32842acb4c2
...
 WARN etherscanidentifier: could not get etherscan info: ContractCodeNotVerified(0x92bac115d89ca17fd02ed9357ceca32842acb4c2)
...
```

**Comment by mds1** [comment]
Ah yep you are right. So I think we should both:
- Change the default API endpoint / default API key based on the chain ID of the RPC URL
- Take an `--etherscan-api-key` CLI arg
