### ISSUE TITLE
Add option to treat solc warnings as errors

### ISSUE THREAD

**Issue by KholdStare** [foundry-rs/foundry#3476]
### Component

Forge

### Describe the feature you would like

When running `forge build` or any other command that invokes the `solc` compiler, have an option to treat its warnings as errors.

I tried looking for such a feature in `solc` itself, but such a proposal was rejected by the maintainers here: https://github.com/ethereum/solidity/issues/10277 . They ask "framework" maintainers to treat solc warnings as errors if required.

### Additional context

There is something like this in the hardhat ecosystem: https://github.com/frangio/hardhat-ignore-warnings . Allows to turn certain warnings into errors, or to ignore others.

**Comment by mattsse** [comment]
this is definitely something that can be added easily

**Comment by gakonst** [comment]
Simple matter of switching https://github.com/gakonst/ethers-rs/blob/5c762c44d760ed9dad3900be079062174ada0245/ethers-solc/src/compile/output/mod.rs#L430 to not filter for errors if it's set to treat warning as errors

**Comment by timofeli** [comment]
Hello @KholdStare, is this okay if i pick this up? :) Want to start submitting here

**Comment by KholdStare** [comment]
@timofeli Of course! Thank you.

**Comment by zerosnacks** [comment]
Completed in https://github.com/foundry-rs/foundry/pull/3784/files
