### ISSUE TITLE
environment variable not found

### ISSUE THREAD

**Issue by aiwowo1** [foundry-rs/foundry#3482]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (28312e7 2022-10-13T00:10:05.477412592Z)

### What command(s) is the bug in?

vm.envString

### Operating System

Windows

### Describe the bug

My environment is windows WSL. I can source .env and echo the $TheKey no problem from the terminal but I cannot read it from the forge script test file by using vm.envString("TheKey"). 

It raises up the error:
 
```
  [27166] TestEnv::run()
    ├─ [0] console::log(here) [staticcall]
    │   └─ ← ()
    ├─ [0] VM::envString(TheKey)
    │   └─ ← "Failed to get environment variable `TheKey` as type `string`: environment variable not found"
    └─ ← "Failed to get environment variable `TheKey` as type `string`: environment variable not found"
 
Failed to get environment variable `TheKey` as type `string`: environment variable not found
```

My test file is like this:

```
// SPDX-License-Identifier: GPL-3.0-only
pragma solidity ^0.8.13;

import 'forge-std/Script.sol';

contract TestEnv is Script {

	function run() external {
		console2.log("here");

        console.log(vm.envString("TheKey"));

	}
}
```

**Comment by mattsse** [comment]
perhaps this is a WSL thing, can you try running `TheKey="my key" forge test`

**Comment by aiwowo1** [comment]
Thanks. Not sure if it's WSL thing or actually something need to be addressed. Fact is if I moved the .env file to the script folder where the test file located, It works even without sourcing the .env and echo TheyKey return empty. 
But if I moved the .env file out of the script folder, even source .env and echo TheyKey response with the correct value. It still fail like reported. Anyway, thanks again. I will keep the .env file in the script folder to have it working for now.

**Comment by mattsse** [comment]
what's the working directory you're running from?

**Comment by aiwowo1** [comment]
the file layout is like below:
root/TheWorkingDir/lib/forge-std/
root/TheWorkingDir/script/testEnv.sol

if the .env file is located in the script or the working directory, forge script testEnv.sol works. without source .env
if the .env file is moved out to the root, Error as reported. even source .env or I also tried source ../../.env within the script folder.

**Comment by mattsse** [comment]
thanks, but what's the directory you're executing forge from (pwd)? is this the root folder?

**Comment by aiwowo1** [comment]
no, not in the root. I ran the ` forge script testEnv.sol `  in the script folder.

**Comment by RickVM** [comment]
I was running into this error if I used .env with a different name, e.g. .env.anvil, even after sourcing it in my computers environment. Running on Mac / ZSH.  
Fix for me was simply naming it .env

**Comment by mds1** [comment]
Is this still an issue? If so can you provide steps to reproduce? Going to close optimistically in the meantime

**Comment by oveddan** [comment]
> I run into this error if I use .env with a different name, e.g. .env.anvil, even after sourcing it in my computers environment. Running on Mac / ZSH.
> 
> Fix for me was simply naming it .env

I have this same issue - i want different .env files for each environment.  So for example I try to use `.env.anvil` and it ignore.  If I rename to and load from `.env` it seems to work

**Comment by mds1** [comment]
foundry only autloads env vars from a file named `.env`, so other file names are not supported for autoloading. For those, you can source them first which should do the trick, e.g. `source .env.anvil && forge test`

**Comment by Alex-Klasma** [comment]
I'm getting this same issue, even with a basic file named `.env` in the project root or the `./script` directory.

On the command line, the $PRIVATE_KEY variable is read and outputs, however in the Deploy.s.sol script calling `vm.envUint("PRIVATE_KEY");` doesn't read, gives the same error as above.

```

**Comment by rafaelaazevedo** [comment]
I had the same issue, in the end was just the // in front of the group of the variables. If you want to add any comment in this .env file just use # Also to verify is working use source .env to see if it can read the variables etc
