### ISSUE TITLE
forge init get error: ZOE ERROR (from forge): zoeOpenFile failed to open file (foundry-learn)

### ISSUE THREAD

**Issue by kuchaguangjie** [foundry-rs/foundry#3483]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

ZOE ERROR (from forge): zoeParseOptions: unknown option (--version) ZOE library version 2013-02-16

### What command(s) is the bug in?

forge init

### Operating System

Linux

### Describe the bug

When run `forge init foundry-learn`, get error:
```
ZOE ERROR (from forge): zoeOpenFile failed to open file (foundry-learn)
ZOE library version 2013-02-16
```

**Comment by kuchaguangjie** [comment]
Turns out there is another bin at `/bin/forge` that I don't remember what it does ..
After `sudo rm /bin/forge`, and re-open a new terminal, it worked.

**Comment by Bestiann** [comment]
Thank you for your help! 2 hours couldn 't solve the problem ! thank you!

**Comment by AnouarBF** [comment]
Thank you so much mate! I was stuck for 3 days searching and I found nothing till I came across you help

**Comment by ghost** [comment]
yep it worked cheers mate
