### ISSUE TITLE
"forge test --watch" get error: watchexec::watchexec: runtime error err=Native fs watcher error

### ISSUE THREAD

**Issue by kuchaguangjie** [foundry-rs/foundry#3484]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (28312e7 2022-10-13T00:10:05.477412592Z)

### What command(s) is the bug in?

forge test --watch

### Operating System

Linux

### Describe the bug

when run `forge test --watch`, get error:
```
2022-10-13T07:09:18.631350Z ERROR watchexec::watchexec: runtime error err=Native fs watcher error
2022-10-13T07:09:18.682608Z ERROR watchexec::watchexec: runtime error err=Native fs watcher error
[⠆] Compiling...
No files changed, compilation skipped

Running 2 tests for test/Counter.t.sol:CounterTest
[PASS] testIncrement() (gas: 28312)
[PASS] testSetNumber(uint256) (runs: 256, μ: 27998, ~: 28387)
Test result: ok. 2 passed; 0 failed; finished in 15.80ms
```
And, changing the contract or test doesn't trigger re-run of the test.

**Comment by mattsse** [comment]
do you get this consistently or only sporadically?

**Comment by kuchaguangjie** [comment]
I tested again just now, it worked ...
