### ISSUE TITLE
anvil crashes when executing `eth_getBlockNumber`

### ISSUE THREAD

**Issue by Timidan** [foundry-rs/foundry#3485]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (28312e7 2022-10-13T06:10:43.734727384Z)

### What command(s) is the bug in?

npx hardhat test

### Operating System

Linux

### Describe the bug

anvil is used to fork polygon mainnet on 8545 and hardhat tests are run against it, it panicks and crashes after doing a series of rpc calls.. the test includes a `eth_getProof` request perhaps that may be reason

![image](https://user-images.githubusercontent.com/25876969/195550269-0b26a8fa-4f59-4557-9cd1-f2fdf14f495c.png)

**Comment by mattsse** [comment]
do you by any chance use impersonate account here?

**Comment by Timidan** [comment]
yes

**Comment by Timidan** [comment]
`hardhat_ImpersonateAccount`

**Comment by Timidan** [comment]
oh...i think i should've used `anvil_impersonateAccount` instead

**Comment by mattsse** [comment]
I see, there's a limitation with contract impersonation that likely caused this issue

https://book.getfoundry.sh/reference/anvil/?highlight=anvil_impersonateAccount

this could be fixed by, stop impersonating when you need to access the contract again.

**Comment by Timidan** [comment]
oh...same error with `anvil_impersonateAccount`

**Comment by Timidan** [comment]
okay...works fine now..thanks a lot
