### ISSUE TITLE
cast run bug

### ISSUE THREAD

**Issue by ekmanss** [foundry-rs/foundry#3486]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (28312e7 2022-10-13T00:10:09.318425Z)

### What command(s) is the bug in?

cast run 0x502c6d860d6527b9bea3b5db300a734104d3be81eba5b34c1d0a5b79e2f30399 --rpc-url=https://rpc.ankr.com/bsc_testnet_chapel

### Operating System

macOS (Apple Silicon)

### Describe the bug

$ cast run 0x502c6d860d6527b9bea3b5db300a734104d3be81eba5b34c1d0a5b79e2f30399 --rpc-url=https://rpc.ankr.com/bsc_testnet_chapel
Executing previous transactions from the block.
⠁ [00:00:00] [--------------------------------------------------------------------------------------------------------------------------------] 0/11 tx (0.0s)The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: Execution { reverted: true, reason: "EvmError: OutOfGas", gas_used: 2698703, gas_refunded: 0, stipend: 0, logs: [Log { address: 0xd878290c971908779623b9b35d752c89110698ab, topics: [0x2f8788117e7eff1d82e926ec794901d17c78024a50270940304540a733656f0d, 0xe5a0b4d50f56047f84728557fedbda92f956391bc9d5c762e8461996dd8e7ad7, 0x000000000000000000000000b9e6d4018a676ee0c38bdf5eb2f8a8f8622497cb, 0x000000000000000000000000b9e6d4018a676ee0c38bdf5eb2f8a8f8622497cb], data: Bytes(0x), block_hash: None, block_number: None, transaction_hash: None, transaction_index: None, log_index: None, transaction_log_index: None, log_type: None, removed: None }], traces: None, debug: None, labels: {}, transactions: None, state_changeset: None, script_wallets: [] }
Location: cli/src/cmd/cast/run.rs:131

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
[1]    14239 abort      cast run 0x502c6d860d6527b9bea3b5db300a734104d3be81eba5b34c1d0a5b79e2f30399

**Comment by gakonst** [comment]
Does this transaction call any BSC Specific precompile?

**Comment by ekmanss** [comment]
> Does this transaction call any BSC Specific precompile?

no call Specific precompile code
The error messages returned using different rpc are also different

`cast run 0x502c6d860d6527b9bea3b5db300a734104d3be81eba5b34c1d0a5b79e2f30399 --rpc-url=https://data-seed-prebsc-1-s3.binance.org:8545`

**Comment by mattsse** [comment]
what's the error message?

is this an archive node?

**Comment by DaniPopes** [comment]
It reverts executing the [first transaction in that block](https://testnet.bscscan.com/tx/0x648564f125d68b3d71b9cb08487dee12d3270025e7b76bad5fcfccc9df7ffbbc) with "out of gas" EVM error

**Comment by mattsse** [comment]
> message: missing trie node e886e0acb62d33e1f26418bd6d281c1232adab8049079181f6f2a918d9165172

looks like the node does not have the requested data?

**Comment by ekmanss** [comment]
Message:  called `Result::unwrap()` on an `Err` value: Execution { reverted: true, reason: "EvmError: LackOfFundForGasLimit", gas_used: 0, gas_refunded: 0, stipend: 0, logs: [], traces: None, debug: None, labels: {}, transactions: None, state_changeset: None, script_wallets: [] }
Location: cli/src/cmd/cast/run.rs:131

**Comment by DaniPopes** [comment]
Closing as OP command works now: `cast run 0x502c6d860d6527b9bea3b5db300a734104d3be81eba5b34c1d0a5b79e2f30399 --rpc-url=https://rpc.ankr.com/bsc_testnet_chapel`
