### ISSUE TITLE
Arbitrum Goerli forge script - intrinsic gas too low

### ISSUE THREAD

**Issue by jaeaster** [foundry-rs/foundry#3487]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (28312e7 2022-10-13T00:10:09.318425Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

I have a simple script to deploy a contract. This script executes successfully on Goerli and Arbitrum Rinkeby, but it fails on Arbitrum Goerli with `(code: -32000, message: intrinsic gas too low, data: None)`

I have tried Alchemy RPC + public RPC (https://goerli-rollup.arbitrum.io/rpc/)

Very weird that Arbitrum Rinkeby works, but Arbitrum Goerli does not. They both run Arbitrum Nitro ... perhaps Goerli is running a newer version since Rinkeby is deprecated...?

Also, I tried increasing the gas price and gas limit by many multiples, but that didn't change anything. And I have more than enough ArbGoerli ETH in my EOA.

The transaction requests are identical between rinkeby and goerli, aside from the nonce, but I also tried using a fresh account with nonce = 0 on goerli and that also didn't change anything:
```
      "transaction": {
        "type": "0x00",
        "from": "0x...",
        "gas": "0x1c60d2",
        "value": "0x0",
        "data": "0x...",
        "nonce": "0x0"
      },
```

Full output:
```
==========================

Estimated total gas used for script: 1859794

Estimated amount required: 0.0001859794 ETH

==========================

###
Finding wallets for all the necessary addresses...
##
Sending transactions [0 - 0].

Transactions saved to: broadcast/DeployFactory.s.sol/421613/run-latest.json

Error:
(code: -32000, message: intrinsic gas too low, data: None)

```

Script:
```
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.17;

import "forge-std/Script.sol";
import "../src/Factory.sol";

contract DeployFactory is Script {
    function run() external {
        uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");

        vm.startBroadcast(deployerPrivateKey);
        new Factory();
        vm.stopBroadcast();
    }
}

```

**Comment by jaeaster** [comment]
Also, just tried a simple forge create and that works successfully
`forge create Factory --rpc-url arbitrum-goerli`

**Comment by jaeaster** [comment]
Ok I managed to get the script working...

I had to pass `--skip-simulation`

The estimated gas usage with simulation was 1,859,794

Without simulation, the gas limit was set to ~20M while the gas used was ~14M

So the gas estimation is off. Does forge estimate gas with the local EVM (rEVM?)? Does it call out to the provider?

**Comment by gakonst** [comment]
@joshieDo do you remember if there is an issue with the arbitrum gas calculation logic? this has been increasingly common

**Comment by joshieDo** [comment]
> So the gas estimation is off. Does forge estimate gas with the local EVM (rEVM?)? Does it call out to the provider?

It should be calling out to the provider

**Comment by joshieDo** [comment]
https://github.com/foundry-rs/foundry/blob/fb4a836fc6c4466f95e4fa49a750f48c8e16c9f2/cli/src/cmd/utils.rs#L165-L168

> Very weird that Arbitrum Rinkeby works, but Arbitrum Goerli does not. They both run Arbitrum Nitro ... perhaps Goerli is running a newer version since Rinkeby is deprecated...?

Yeah that explains it.  We only have one Arbitrum testnet, we need to add `Chain::ArbitrumGoerli `

**Comment by philburrrt** [comment]
> Ok I managed to get the script working...
> 
> I had to pass `--skip-simulation`
> 
> The estimated gas usage with simulation was 1,859,794
> 
> Without simulation, the gas limit was set to ~20M while the gas used was ~14M
> 
> So the gas estimation is off. Does forge estimate gas with the local EVM (rEVM?)? Does it call out to the provider?

this fixed the same issue i was having with arbitrum mainnet

**Comment by ratio91** [comment]
`--skip-simulation` solved this issue for me on Mantle as well.
