### ISSUE TITLE
Setting `from` to a contract address with code on view calls results in `RejectCallerWithCode`

### ISSUE THREAD

**Issue by penandlim** [foundry-rs/foundry#3493]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (28312e7 2022-10-13T00:10:09.318425Z)

### What command(s) is the bug in?

anvil

### Operating System

macOS (Apple Silicon)

### Describe the bug

Forwarding from : https://github.com/Destiner/ethcall/issues/146

When doing a static call, if you set `from` to a contract with address, the calls do not show any error or return any data with ethers.js.

And when launching with rust logs enabled like
`RUST_LOG=backend,api anvil -f $RPC_URL`

And using [Multicall3 ](https://github.com/mds1/multicall) with ethcall package results in following output.
```
2022-10-13T02:20:01.419714Z TRACE backendhandler: received request basic address=0xca11bde05977b3631167028862be2a173976ca11
2022-10-13T02:20:01.419745Z TRACE backend: call return RejectCallerWithCode out: None gas 0 on block 15736119
```

I think this issue should be addressed at [ethcall package](https://github.com/Destiner/ethcall/), and not here since setting `from` to contract doesn't seems to be supported by all implementations. But raising awareness since it looks like others similar problems regarding setting `from` as a contract address (#2931 #2090 #1943).

**Comment by zerosnacks** [comment]
Marking as `stale` since `ethcall` has been deprecated and there is no clear actionable item
