### ISSUE TITLE
forge debug cannot display code

### ISSUE THREAD

**Issue by zrankn** [foundry-rs/foundry#3498]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ee88f75 2022-10-04T00:07:32.8134078Z)

### What command(s) is the bug in?

forge debug --debug tokentest.sol --sig "testtrang()" --fork-url https://rpc.ankr.com/bsc

### Operating System

macOS / Windows

### Describe the bug

I want to debug the whole process of the function and watch the process and result of the code running, but when there is a function that calls other contract functions, I can't see the code that calls other contract functions。
And I can't debug tx hash
![photo_2022-10-15_11-31-25](https://user-images.githubusercontent.com/113416635/195967399-39ef86f5-e310-46b0-9e03-9a72bf225af3.jpg)

**Comment by zrankn** [comment]
forge --version
forge 0.2.0 (b554ab1 2022-10-15T00:07:41.079769Z)
Execution error
“Error:
No input files detected.”

**Comment by iFrostizz** [comment]
afaik, forge is not pulling the contract code from etherscan for now.
Easy fix is to download the code and reference to it locally.

**Comment by Ptahliu** [comment]
> afaik, forge is not pulling the contract code from etherscan for now. Easy fix is to download the code and reference to it locally.

How to reference to it locally. Is there a case study?

**Comment by zerosnacks** [comment]
Marking as `duplicate` of https://github.com/foundry-rs/foundry/issues/5435, continuing the conversation there
