### ISSUE TITLE
Anvil Doesn't Respect ChainID

### ISSUE THREAD

**Issue by kristian1108** [foundry-rs/foundry#3511]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (fb4a836 2022-10-18T00:07:33.891597Z)

### What command(s) is the bug in?

anvil --chain-id 10

### Operating System

macOS (Apple Silicon)

### Describe the bug

The Anvil dev chain does not respect the chain-id of a signed transaction. You can run anvil with multiple different chain-ids and successfully submit the same signed transaction to different chains.

Here's some code:

```
const Web3 = require('web3');
const ethers = require("ethers");

async function main() {
	const anvilEndpoint = "http://127.0.0.1:8545";
	const anvilProvider = new Web3.providers.HttpProvider(anvilEndpoint);
	const provider = new ethers.providers.Web3Provider(anvilProvider);


	// YOU CAN UNCOMMENT ALL THIS CODE IF YOU WANT TO RE-SIGN THE TRANSACTION
	// const signer = new ethers.Wallet("0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80", provider);
	//
	// let gas_price = await signer.getGasPrice();
	// let nonce = await signer.getTransactionCount("latest");
	// let gas_limit = 100000;
	//
	// const tx = {
	// 	from: "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266",
	// 	to: "0x1c12650323489bb4c3b31bcfd47bc131abede5f6",
	// 	value: "0x000000000000000000000000000000000000000000000000008e1bc9bf040000",
	// 	nonce: nonce,
	// 	gasLimit: ethers.utils.hexlify(gas_limit),
	// 	gasPrice: gas_price,
	// }
	//
	// console.log(await signer.signTransaction(tx));


	// THIS CODE JUST SUBMITS THE SAME SIGNED TRANSACTION TO THE NETWORK WITH ONE OF THE ANVIL GENESIS ACCOUNTS
	const result = await provider.sendTransaction("0xf86b808477359400830186a0941c12650323489bb4c3b31bcfd47bc131abede5f6878e1bc9bf040000801ca02d87709b7597594a454a34a2f36fa27d7dfcb030e3e3b56b516bbd6d5868098da01d861f7c63f69df4ba794468471cd4afbd7772c46bf5d24ebd87081f0d036bef");
	const balance = await provider.getBalance("0x1c12650323489bb4c3b31bcfd47bc131abede5f6");
	console.log(result);

	// HERE YOU CAN SEE THE TX IS SUCCESSFUL AND THE BALANCE IS UPDATED
	console.log(balance);
}

main().catch((error) => {
	console.error(error);
	process.exitCode = 1;
});
```

If you point this code at multiple different Anvil chains, they all succeed. 

For example:

`anvil --chain-id 11`
`anvil --chain-id 12`
`anvil --chain-id 123`

**Comment by mattsse** [comment]
this check is implemented here

https://github.com/foundry-rs/foundry/blob/870da6f73ee6ede429ed5742bb91eed3121071e3/anvil/src/eth/backend/mem/mod.rs#L1777-L1791

unsure what's wrong

**Comment by mattsse** [comment]
looks like the transaction's v value is 28? meaning the signer does not support https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md

then this makes sense as the chain id is not recovered.
