### ISSUE TITLE
startPrank(<address>) and startBroadcast(<address>) doesn't switch msg.sender on Anvil node in scripts with contract deployment helpers

### ISSUE THREAD

**Issue by JasoonS** [foundry-rs/foundry#3515]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (870da6f 2022-10-19T00:11:16.606063358Z)

### What command(s) is the bug in?

forge script

### Operating System

Linux

### Describe the bug

This issue only occurs on Anvil (we are running it in a docker for local E2E testing with full backend/UI etc). So same scripts have been working to deploy onto public testnets.

Our code isn't public - but the `Script` contract that we use is deploying a contract that helps manage the deployment - but that is only done inside the script and NOT broadcast.

Pseudo code:
```solidity
contract MarketFactory is Test {
  function deployMarketWithBroadcast(
    address deployer,
    // some other parameters
    Vm vm // same thing happens if we don't pass this through.
  ) public returns (uint32 marketIndex) {
    console2.log("Deploying market with", deployer);
    vm.startPrank(deployer);
    console2.log("these addreses should be the same", deployer, msg.sender);
    vm.stopPrank();
    vm.startBroadcast(deployer);
    console2.log("these addreses should be the same", deployer, msg.sender);
    // Do the deployment
    vm.stopBroadcast();
  }
}

contract DeployScript is Test {
  MarketFactory factory;
  constructor () {
    factory = new MarketFactory();
  }
  function run() public {
    factory.deployMarketWithBroadcast(msg.sender, vm)
  }
}
``` 

![image](https://user-images.githubusercontent.com/6032276/196662290-aa7b98fe-32c8-4a01-b62c-3099dd439485.png)
![image](https://user-images.githubusercontent.com/6032276/196662230-4d8ecfed-3661-455a-82b3-b6efbe0d8d25.png)

In the above images `0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266` is the msg.sender (or the account we are doing the deployment with) and `0x5b73C5498c1E3b4dbA84de0F1833c4a029d90519` is the `factory` contract address.
Note, we don't actually want to deploy the Factory on chain, it is just a contract with some utility functions and helpers.

**Comment by mattsse** [comment]
cc @joshieDo

**Comment by joshieDo** [comment]
From the top of my head, the log does seem fine to me. Broadcast and Prank hijacks the msg.sender of any call or creation made. But it has to happen. 

If you call/create a contract inside then you would expect the address of the msg.sender to be the one from the deployer.

**Comment by JasoonS** [comment]
Thanks for the clarification @joshieDo - I'd say (IMO) it is more intuitive for the `msg.sender` to change (even for non call/createion functions) than what you are describing.

I initially flagged this because its behaviour was inconsistent between Anvil and the other networks.

**Comment by joshieDo** [comment]
> I initially flagged this because its behaviour was inconsistent between Anvil and the other networks.

Inconsistent in what way?

**Comment by JasoonS** [comment]
> Inconsistent in what way?

On other networks the `msg.sender` and `deployer` are the same address, but on anvil they are different.

**Comment by mds1** [comment]
Going to close per @joshieDo's comment.

@JasoonS if you still think there is an anvil specific issue lmk and we can reopen. From the above I'm not clear on what anvil is doing different than e.g. a mainnet deploy
