### ISSUE TITLE
`forge coverage` give `Error: Function has no kind` when contracts require multiple compiler versions

### ISSUE THREAD

**Issue by QYuQianchen** [foundry-rs/foundry#3519]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (1da2b65 2022-10-14T00:09:33.152136Z)

### What command(s) is the bug in?

forge coverage

### Operating System

macOS (Apple Silicon)

### Describe the bug
Code repo: https://github.com/hoprnet/hoprnet/tree/feature/4196-sc-toolchain/packages/ethereum/crates/contracts
After running `forge coverage`, it gives the following logs:
```
[⠔] Compiling...
[⠒] Compiling 1 files with 0.4.24
[⠑] Compiling 22 files with 0.6.12
[⠊] Compiling 66 files with 0.8.13
[⠆] Solc 0.4.24 finished in 234.60ms
[⠑] Solc 0.6.12 finished in 432.36ms
[⠊] Solc 0.8.13 finished in 3.96s
Compiler run successful (with warnings)
src/testing/PermittableToken.sol:978:23: Warning: This declaration shadows an existing declaration.
    function _recover(bytes32 _digest, uint8 _v, bytes32 _r, bytes32 _s) internal pure returns (address) {
                      ^-------------^
src/testing/PermittableToken.sol:967:5: The shadowed declaration is here:
    function _digest(bytes memory _typedStruct) internal view returns (bytes32) {
    ^ (Relevant source part starts here and spans across multiple lines).



warning[5667]: src/ERC777/ERC777Snapshot.sol:68:35: Warning: Unused function parameter. Remove or comment out the variable name to silence this warning.
    function _beforeTokenTransfer(address operator, address from, address to, uint256 amount) internal virtual override {
                                  ^--------------^
```
(and a few more warnings, Followed by an error message)
```
Analysing contracts...
Error: 
Function has no kind
```

**Comment by ChiTimesChi** [comment]
@QYuQianchen @rkrasiuk I have faced the same issue. In order to get `forge coverage` to work I updated the pragma in all ancient contracts from `^0.4.x` to `^0.5.0` (`WETH9` etc).

Note that this requires a slight modification of the contracts, as some of the 0.4 syntax can not be used directly in 0.5. I wonder if there's a more elegant fix around.

**Comment by zerosnacks** [comment]
Tentatively marking as `resolved`

Using multiple `solc` versions with `forge coverage` doesn't yield any errors for me

Feel free to re-open with additional details / minimal reproduction if this is still an issue you are facing
