### ISSUE TITLE
`forge fmt` places a space between override and parenthe that follows

### ISSUE THREAD

**Issue by benesjan** [foundry-rs/foundry#3522]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (3858d18 2022-10-20T00:17:55.764192699Z)

### What command(s) is the bug in?

forge fmt

### Operating System

macOS (Apple Silicon)

### Describe the bug

`forge fmt` currently places a gap between override and the bracket that follows. There doesn't seem to be an option `foundry.toml` that disables this behavior.

![telegram-cloud-photo-size-4-5947073681438129191-y](https://user-images.githubusercontent.com/13470840/197051452-c3d11a9e-3db9-484b-bed3-fb5b89130284.jpg)

**Comment by mattsse** [comment]
this should be an easy fix @rkrasiuk ?

**Comment by rkrasiuk** [comment]
yup yup, picking up now

**Comment by rkrasiuk** [comment]
i'll make this an option since we have [a test covering it](https://github.com/foundry-rs/foundry/blob/d896050a3704bec9ad8ba7663cf469ff7415f4b7/fmt/testdata/VariableDefinition/fmt.sol#L15-L24) and nobody raised this so far
