### ISSUE TITLE
libgit not found when building from source

### ISSUE THREAD

**Issue by tynes** [foundry-rs/foundry#3523]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### Operating System

Linux

### Describe the bug

When building from source, I was getting this error after updating my system.

```
.../foundry-rs/foundry/target/release/build/foundry-cli-1fc36a4bcf4e5752/build-script-build: error while loading shared libraries: libgit2.so.1.4: cannot open shared object file: No such file or directory
```

The latest release of libgit2 is 1.5, https://archlinux.org/packages/extra/x86_64/libgit2/ and it looks like foundry specifically needs version 1.4.

Currently running `5.10.148-1-MANJARO`

I was able to get around this problem by installing 1.4 from https://archive.archlinux.org/packages/l/libgit2/ and using `pacman -U` to install 1.4
`
I don't think this is a huge problem since its easy to fix, mostly documenting this for others who may run into the same issue.

**Comment by mattsse** [comment]
perhaps this is related

https://github.com/liuchengxu/vim-clap/issues/811

was this a fresh build? or were there existing artifacts?

**Comment by tynes** [comment]
This is triggered when running `foundryup` so I believe there were existing artifacts

**Comment by zerosnacks** [comment]
Marking as `stale`, feel free to re-open if this is still an issue
