### ISSUE TITLE
feat: support `--via-ir` flag when running `forge coverage`

### ISSUE THREAD

**Issue by colinnielsen** [foundry-rs/foundry#3527]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (d896050 2022-10-21T00:08:06.615745Z)

### What command(s) is the bug in?

forge coverage --via-ir --report lcov

### Operating System

macOS (Apple Silicon)

### Describe the bug

Looks like `COMPILER OPTIONS` are listed when `forge coverage -h` is run, however it appears that the coverage command does not build through the YUL pipeline.
![Screen Shot 2022-10-21 at 5 27 21 PM](https://user-images.githubusercontent.com/33375223/197304663-51924590-3d3b-4436-89f4-914b10a29b94.png)

**Comment by colinnielsen** [comment]
Looks like `forge coverage` also ignores the `via_ir` flag in the `foundry.toml`

**Comment by mattsse** [comment]
this is unfortunately a limitation, because --via-ir transforms the AST so there is no good way of keeping track afterwards.

**Comment by colinnielsen** [comment]
Shoot... Is there a way around this? I'm worried that this feature would be bricked once solidity moves to the IR pipeline.

**Comment by Oighty** [comment]
I've been having this same error without using `--via-ir`. My project compiles fine with `forge build` and `forge test`, but throws `Stack too deep` when running `forge coverage`. Also on Apple Silicon with `forge 0.2.0 (7f4fb5 2022-11-02)`.

**Comment by mattsse** [comment]
> this is unfortunately a limitation, because --via-ir transforms the AST so there is no good way of keeping track of the original AST afterward right now.

we should make this clearer on the website.

**Comment by frank-lim-partior** [comment]
> this is unfortunately a limitation, because --via-ir transforms the AST so there is no good way of keeping track afterwards.

Is the need for tracking AST isolated to the test contracts? Or does it apply to the primary source code as well?

**Comment by 0xRusowsky** [comment]
> this is unfortunately a limitation, because --via-ir transforms the AST so there is no good way of keeping track afterwards.

having this limitation in mind, do we have any alternative to see test coverage when getting `Stack too deep`?

**Comment by paulrberg** [comment]
> we should make this clearer on the website.

@mattsse what do you mean by "website"? The Foundry Book? Because if yes, I don't see any documentation about coverage on there.

Whatever the case, I think that this limitation of the coverage command should be mentioned when running `forge coverage --help`, and that the command itself should not run when `--via-ir` is enabled. The Yul IR pipeline is only going to get more popular with time.

I am not sufficiently experienced with test coverage software to understand why it is difficult (or impossible) to run coverage over IR-optimized code, but I agree with the commend made by @colinnielsen above - if coverage is not made to work with IR, it will eventually become obsolete.

**Comment by haythemsellami** [comment]
My code compile without `--via-ir`, but still getting stack too deep in coverage.
```
forge 0.2.0 (08a629a 2023-06-03T00:04:10.749254000Z)
```

**Comment by haythemsellami** [comment]
> ### Component
> Forge
> 
> ### Have you ensured that all of these are up to date?
> * [x]  Foundry
> * [x]  Foundryup
> 
> ### What version of Foundry are you on?
> forge 0.2.0 ([d896050](https://github.com/foundry-rs/foundry/commit/d896050a3704bec9ad8ba7663cf469ff7415f4b7) 2022-10-21T00:08:06.615745Z)
> 
> ### What command(s) is the bug in?
> forge coverage --via-ir --report lcov
> 
> ### Operating System
> macOS (Apple Silicon)
> 
> ### Describe the bug
> Looks like `COMPILER OPTIONS` are listed when `forge coverage -h` is run, however it appears that the coverage command does not build through the YUL pipeline. ![Screen Shot 2022-10-21 at 5 27 21 PM](https://user-images.githubusercontent.com/33375223/197304663-51924590-3d3b-4436-89f4-914b10a29b94.png)

Also, how to get more output from the CLI command, it does not show to me where the stack too deep error exactly is:

```
[⠰] Compiling...
[⠒] Compiling 100 files with 0.8.20
[⠘] Solc 0.8.20 finished in 4.24s
Error:
Compiler run failed:
Error: Compiler error (/solidity/libyul/backends/evm/AsmCodeGen.cpp:68):Stack too deep. Try compiling with `--via-ir` (cli) or the equivalent `viaIR: true` (standard JSON) while enabling the optimizer. Otherwise, try removing local variables. When compiling inline assembly: Variable headStart is 1 slot(s) too deep inside the stack. Stack too deep. Try compiling with `--via-ir` (cli) or the equivalent `viaIR: true` (standard JSON) while enabling the optimizer. Otherwise, try removing local variables.
```

**Comment by haythemsellami** [comment]
> My code compile without `--via-ir`, but still getting stack too deep in coverage.
> 
> ```
> forge 0.2.0 (08a629a 2023-06-03T00:04:10.749254000Z)
> ```

This is an annoying error and probably will be a big blocker for Foundry adoption.Also, how to get more output from the CLI command, it does not show to me where the stack too deep error exactly is:
```
[⠰] Compiling...
[⠒] Compiling 100 files with 0.8.20
[⠘] Solc 0.8.20 finished in 4.24s
Error:
Compiler run failed:
Error: Compiler error (/solidity/libyul/backends/evm/AsmCodeGen.cpp:68):Stack too deep. Try compiling with `--via-ir` (cli) or the equivalent `viaIR: true` (standard JSON) while enabling the optimizer. Otherwise, try removing local variables. When compiling inline assembly: Variable headStart is 1 slot(s) too deep inside the stack. Stack too deep. Try compiling with `--via-ir` (cli) or the equivalent `viaIR: true` (standard JSON) while enabling the optimizer. Otherwise, try removing local variables.
```

**Comment by smak0v** [comment]
I have the same issue with `forge coverage` command.

<img width="1725" alt="image" src="https://github.com/foundry-rs/foundry/assets/26391964/a4770979-4f03-448a-8996-132122432be2">

**Comment by ethereumdegen** [comment]
> I've been having this same error without using `--via-ir`. My project compiles fine with `forge build` and `forge test`, but throws `Stack too deep` when running `forge coverage`. Also on Apple Silicon with `forge 0.2.0 (7f4fb5 2022-11-02)`.

i have the exact same issue

**Comment by golden-expiriensu** [comment]
Hi, I have the exact same issue, is this fix planned?

**Comment by kevinsslin** [comment]
I can pass `forge build` without `--via-ir`, but still occur the same error while running `forge coverage`
![image](https://github.com/foundry-rs/foundry/assets/86810837/da56ed61-2b12-4df5-8026-76287b1830e2)

**Comment by Pai-Sho** [comment]
Same issue here

**Comment by QEDK** [comment]
Do we have any workarounds for this issue yet?

**Comment by sanbir** [comment]
`forge coverage --ir-minimum` is a life saver! 

I also had to replace all my `assembly { ` with `assembly ("memory-safe") { ` for it to start working.

**Comment by kartojal** [comment]
anyone facing memory leaks with `--ir-minimum`?

`forge coverage --ir-minimum`  causes memory leaks while is compiling a large project, it runs out of memory with a 32gb machine

**Comment by siguint** [comment]
> anyone facing memory leaks with --ir-minimum?
i have the same issue

**Comment by grandizzy** [comment]
`--ir-minimum` should work, mind though that coverage disables optimizer (that is equivalent to setting `optimizer = false` in config file) so you could hit the behavior where test compiles but coverage fails (see https://github.com/foundry-rs/foundry/issues/8840#issuecomment-2341742571). The `Unknown key "inliner` issue was solved with https://github.com/foundry-rs/foundry/pull/9341
Also re memory issues when running coverage - there are big improvements in latest builds, please update and retry.
