### ISSUE TITLE
forge init -> ✖ 'init' is not a valid subcommand. See 'forge --help'

### ISSUE THREAD

**Issue by rkdud007** [foundry-rs/foundry#3528]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge --version 1.3.0

### What command(s) is the bug in?

forge init

### Operating System

macOS (Apple Silicon)

### Describe the bug

I followed this install.  : https://book.getfoundry.sh/getting-started/installation
`curl -L https://foundry.paradigm.xyz | bash`
`foundryup`
`foundryup: installing foundry (version nightly, tag nightly-75ca1a8e9f1a83ab861038f005af00dd36dee056)
foundryup: downloading latest forge, cast and anvil
######################################################################### 100.0%
foundryup: downloading manpages
######################################################################### 100.0%
foundryup: installed - forge 0.2.0 (75ca1a8 2022-10-22T00:06:37.119734Z)
foundryup: installed - cast 0.2.0 (75ca1a8 2022-10-22T00:06:37.119734Z)
foundryup: installed - anvil 0.1.0 (75ca1a8 2022-10-22T00:06:37.20032Z)
foundryup: done`

and when I do forge init, it said ✖ 'init' is not a valid subcommand. See 'forge --help'

I 'll attach my log image

<img width="488" alt="스크린샷 2022-10-22 오후 4 04 32" src="https://user-images.githubusercontent.com/76558220/197325652-1ab52a30-6d4e-4a04-8a97-3d5b082c11ed.png">

**Comment by rkdud007** [comment]
stupid dummy question. Downloaded diff forge before.

**Comment by MekailTheMachine** [comment]
What was your resolution?

**Comment by DaniPopes** [comment]
If you are getting that response, you have a different "Forge" installed from somewhere else. Find it with `which forge`

**Comment by scoolj** [comment]
Hello ,

Delete the directory. 
1.  create another directory - 
``` mkdir foundry-f23```
2.  enter the new directory
``` cd foundry-f23 ```
3. install foundry 
``` curl -L https://foundry.paradigm.xyz | bash && foundryup ```
4.  create a project
```  forge init  <project name >

I am sure this will help.  sorry for your trouble.

**Comment by scoolj** [comment]
Hello ,

Delete the directory. 
1.  create another directory - 
``` mkdir foundry-f23```
2.  enter the new directory
``` cd foundry-f23 ```
3. install foundry 
``` curl -L https://foundry.paradigm.xyz | bash && foundryup ```
4.  create a project
```  forge init  <project name >

I am sure this will help.  sorry for your trouble. 

> ### Component
> 
> Forge
> ### Have you ensured that all of these are up to date?
> 
>     * [x]  Foundry
> 
>     * [x]  Foundryup
> 
> 
> ### What version of Foundry are you on?
> 
> forge --version 1.3.0
> ### What command(s) is the bug in?
> 
> forge init
> ### Operating System
> 
> macOS (Apple Silicon)
> ### Describe the bug
> 
> I followed this install. : https://book.getfoundry.sh/getting-started/installation `curl -L https://foundry.paradigm.xyz | bash` `foundryup` `foundryup: installing foundry (version nightly, tag nightly-75ca1a8e9f1a83ab861038f005af00dd36dee056) foundryup: downloading latest forge, cast and anvil ######################################################################### 100.0% foundryup: downloading manpages ######################################################################### 100.0% foundryup: installed - forge 0.2.0 (75ca1a8 2022-10-22T00:06:37.119734Z) foundryup: installed - cast 0.2.0 (75ca1a8 2022-10-22T00:06:37.119734Z) foundryup: installed - anvil 0.1.0 (75ca1a8 2022-10-22T00:06:37.20032Z) foundryup: done`
> 
> and when I do forge init, it said ✖ 'init' is not a valid subcommand. See 'forge --help'
> 
> I 'll attach my log image
> 
> <img alt="스크린샷 2022-10-22 오후 4 04 32" width="488" src="https://user-images.githubusercontent.com/76558220/197325652-1ab52a30-6d4e-4a04-8a97-3d5b082c11ed.png">

Hello ,

Delete the directory. 
1.  create another directory - 
``` mkdir foundry-f23```
2.  enter the new directory
``` cd foundry-f23 ```
3. install foundry 
``` curl -L https://foundry.paradigm.xyz | bash && foundryup ```
4.  create a project
```  forge init  <project name >

I am sure this will help.  sorry for your trouble.
