### ISSUE TITLE
`warning: unused import: tracing::trace` (during anvil install from source)

### ISSUE THREAD

**Issue by pcaversaccio** [foundry-rs/foundry#3530]
### Component

Foundryup

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (75ca1a8 2022-10-22T10:06:40.3053035Z)

### Operating System

Windows

### Describe the bug

I today quickly installed anvil from source and got this warning (nothing is breaking). Maybe consider removing it:
```bash
warning: unused import: `tracing::trace`
  --> anvil\src\lib.rs:40:5
   |
40 | use tracing::trace;
   |     ^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

    Building [=======================> ] 821/824: anvil, foundry-evm
```

**Comment by DaniPopes** [comment]
looks like it's used only for a Windows build:

https://github.com/foundry-rs/foundry/blob/75ca1a8e9f1a83ab861038f005af00dd36dee056/anvil/src/lib.rs#L274-L277
