### ISSUE TITLE
cast calldata can not work correctly with nested tuple 

### ISSUE THREAD

**Issue by XD-OK** [foundry-rs/foundry#3532]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

cast 0.2.0 (d896050 2022-10-21T00:08:06.615745Z)

### What command(s) is the bug in?

cast calldata

### Operating System

macOS (Apple Silicon)

### Describe the bug

this work 
`cast calldata 'hi((uint256,(address)[]))' '(2,[(5c9d55b78febcc2061715ba4f57ecf8ea2711f2c)])'`
output
`0x4b85584e00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000010000000000000000000000005c9d55b78febcc2061715ba4f57ecf8ea2711f2c`

but this not work

`cast calldata 'hi(((address)[],uint256))' '([(5c9d55b78febcc2061715ba4f57ecf8ea2711f2c)],2)'`

output

` Error: 
Failed to parse tokens
Context:
 Uint parse error: InvalidCharacter `

and this work
`cast calldata 'hi(((address)[],uint256))' '([(5c9d55b78febcc2061715ba4f57ecf8ea2711f2c)] 2)'
`

that's confused, while it's a much more complicated struct than the  above example

and another suggestion: cast  decode output  better could be used as cast encode input 

update:
these can not work too
`
cast abi-encode "hi(((uint256,(address)[]),uint256))" '((2,[(0x0000000000000000000000000000000000000000)]),3)'
cast abi-encode "hi((uint256,(uint256,(address)[])))" '(3,(2,[(0x0000000000000000000000000000000000000000)]))'`

**Comment by mattsse** [comment]
thanks for raising this.

there was indeed an issue with array parsing inside tuples, fixed here: https://github.com/rust-ethereum/ethabi/pull/282

**Comment by zerosnacks** [comment]
Assuming this has been resolved since
