### ISSUE TITLE
`forge script --ledger` returns "Ledger device not available" error

### ISSUE THREAD

**Issue by c-metadexlabs** [foundry-rs/foundry#3536]
**Component**
Forge

**Have you ensured that all of these are up to date?**
 :ballot_box_with_check: Foundry
 :ballot_box_with_check: Foundryup

**What version of Foundry are you on?**
forge 0.2.0 (d896050 2022-10-20T15:10:25.6227974Z)

**What command(s) is the bug in?**
forge script --ledger

**Operating System**
Windows 11 Professionnel 22H2

**Describe the bug**

i'm using the following command : 

`forge script script/DeployToMumbai.s.sol:DeployToMumbaiScript --ledger --hd-paths "m/44'/60'/0'/0" --rpc-url $ALCHEMY_MUMBAI_RPC_URL --broadcast -vvvv`

and get this error : 

> Error:
> **Ledger device not available.**
> 
> Context:
> - Response too short. Expected at least 2 bytes. Got []

My ledger is seen by my computer.

> Ethereum App: 1.9.20
> Blind singing: Enabled

**Comment by mattsse** [comment]
hmm, this error is thrown when we get an empty response from the ledge device after exchanging the APDU command.

this could be a windows issue since https://github.com/summa-tx/bitcoins-rs/tree/main/ledger mentions it's not supported.

cc @prestwich

**Comment by prestwich** [comment]
that's possible. an empty response would be an odd manifestation of this

a windows update has been in my todos for a long time 😬

**Comment by rpedroni** [comment]
In case it helps, got ledger working for `forge script` with
```
forge script script/DeployScript.s.sol --rpc-url $RPC_URL \
--ledger --sender 0x<HW_WALLET_ADDRESS_0> \
--broadcast
```

This will use the 0-indexed address from your wallet

**Comment by cs-metadexlabs** [comment]
> In case it helps, got ledger working for `forge script` with
> 
> ```
> forge script script/DeployScript.s.sol --rpc-url $RPC_URL \
> --ledger --sender 0x<HW_WALLET_ADDRESS_0> \
> --broadcast
> ```
> 
> This will use the 0-indexed address from your wallet - make sure the `--sender` value matches

On Windows? i already tried using `--sender`, without any success

**Comment by Theezr** [comment]
I had the same problem and forgot i was working in WSL. Maybe it will help someone.

**Comment by klkvr** [comment]
Closing along with https://github.com/foundry-rs/foundry/issues/6516 which was resolved by alloy migration
