### ISSUE TITLE
impersonateAccount call doesn't always auto mine a block

### ISSUE THREAD

**Issue by krasi-georgiev** [foundry-rs/foundry#3537]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9add73c 2022-10-23T00:09:34.410537162Z)

### What command(s) is the bug in?

anvil --fork-url ....

### Operating System

Linux

### Describe the bug

When calling the impersonate account it returns a TX hash, but when trying to retrieve the Receipt it returns not found.

If I evm_mine after every call after the impersonate call it works as expected.

Auto mine is enabled

**Comment by krasi-georgiev** [comment]
Actually I just realised that this happens for all TXs, if you make a TX and try to get there receipt right after that it returns an error not found.

**Comment by mattsse** [comment]
I guess there is a small window where this could be possible since `eth_getTransactionReceipt` returns null if there's no receipt for the given hash.

could you try a timeout? most libraries have some form of retry for this case.

> Also I would expect that a call to an rpc endpoint which results in a TX revert to return the error in the actual call so that the caller can print the error

what rpc endpoint are you referring to here?

> One other thing I noticed is that in the automine mode creating TX fast causes the misses block in a head tracker subscriber

you mean a missing block in the newHead subscription? this sounds like a bug

**Comment by krasi-georgiev** [comment]
I am referring to the `eth_sendTransaction` endpoint, my assumption is that when automine is enabled this call will be blocking until a block is actually mined. 
Additionally, in Hardhat it is quite nice that if the TX reverts the return value of the rpc call also includes the actual revert reason.

**Comment by krasi-georgiev** [comment]
I think with latest foundryup is ok, will re-open if needed

**Comment by krasi-georgiev** [comment]
actually yeah there is still some async happening somewher, I think when automine is enabled sending a TX should be blocking untill it is actually mined and also the error should include any revert reasons.

**Comment by mds1** [comment]
Is this still an issue? I know there's been some fixes around this area so going to close optimistically. If this is still an issue, feel free to reopen with steps to reproduce
