### ISSUE TITLE
Can not infer the sender when impersonating an account

### ISSUE THREAD

**Issue by krasi-georgiev** [foundry-rs/foundry#3538]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9add73c 2022-10-23T00:09:34.410537162Z)

### What command(s) is the bug in?

anvil --fork-url ....

### Operating System

Linux

### Describe the bug

`types.Sender(types.LatestSignerForChainID(big.NewInt(self.client.NetworkID())), tx)`

I use this code from the go-ethereum repo to infer the send of a TX, but when the TX is sent with impersonation this code returns an error  	`invalid transaction v, r, s values`

Is this expected and if yes is there any other way to infer the sender of a TX?

**Comment by mattsse** [comment]
I see, we bypass the signature in these cases, with a random signature which is apparently invalid, will change this to something real.
