### ISSUE TITLE
The address created by create2 in remix is incorrect

### ISSUE THREAD

**Issue by 2547881370** [foundry-rs/foundry#3539]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (3858d18 2022-10-23T12:18:26.3206418Z)

### What command(s) is the bug in?

anvil -f https://bsc-mainnet.nodereal.io/v1/a9d5920ea85349c298ee543d3d4922ac  --chain-id  56 --gas-limit 12000000000000000000 --gas-price 9000000000000000000   --fork-block-number 22070910

### Operating System

Windows

### Describe the bug
close

```
close
```

**Comment by iFrostizz** [comment]
Related to https://github.com/foundry-rs/foundry/issues/3510

**Comment by Evalir** [comment]
Closing, not enough info and this was related to #3510 which has since been fixed.
