### ISSUE TITLE
Public state variables prefixed with 'test' incorrectly run as tests

### ISSUE THREAD

**Issue by giovannidisiena** [foundry-rs/foundry#3541]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9add73c 2022-10-24T00:11:15.963273Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Intel)

### Describe the bug

It appears that forge incorrectly runs public state variables as tests if their names are prefixed with `test`. This can be demonstrated by running the following snippet (adapted from the Foundry book [example](https://book.getfoundry.sh/forge/writing-tests)) with `forge test`:
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.15;
import "forge-std/Test.sol";

contract PublicStateVariableBugTest is Test {
  uint256 public testNumber
  uint256[1] public testNumbers;
}
```

As you can see, there are no tests defined within this contract; however, two 'tests' are in fact run. This behaviour is even more clearly illustrated with public arrays which result in a fuzz test counterexample output:

```Running 2 tests for test/PublicStateVariableBug.t.sol:Test7
[PASS] testNumber():(uint256) (gas: 2430)
[FAIL. Reason: EvmError: Revert Counterexample: calldata=0xd29ab5920000000000000000000000000000000000000000000000000000000000000001, args=[1]] testNumbers(uint256):(uint256) (runs: 1, μ: 2731, ~: 2731)
Test result: FAILED. 1 passed; 1 failed; finished in 4.77ms```

**Comment by rkrasiuk** [comment]
@mattsse afaik we don't parse the AST, but rather take it from the ABI. shall we just filter out view & pure functions?

**Comment by mattsse** [comment]
ah yes of course, because the vars are public, they'll end up as view functions in the ABI.

@giovannidisiena we should make note of this in the book.

closing as this is not technically a bug imo

**Comment by mattsse** [comment]
well let's keep this open perhaps we can improve this regardless.

**Comment by mds1** [comment]
> shall we just filter out view & pure functions?

I don't know if we want to do this, as it forces people to use the `assertEq` helpers and no longer lets them use `require`. But maybe that's good if we don't want people using require? E.g. if you filter out view functions you can't do:

```solidity
function test_PostSetupState() public view {
  uint256 balance = dai.balanceOf(alice);
  require(balance == 100 ether, "balance wasn't set properly");
}
```

`assertEq` modifies state so using that means functions can't be view

**Comment by grandizzy** [comment]
a simpler fix would be to assume it's a test function only if they don't have outputs by adding `&& self.outputs.is_empty()` condition here
https://github.com/foundry-rs/foundry/blob/e01038f35750b4a41b1eda5a4ea3da976027eee2/crates/common/src/traits.rs#L51-L57

This is a breaking change for test functions already declared with return values but I don't think it's a common practice to have such @mds1 wdyt?

**Comment by mds1** [comment]
Sorry, thought I responded here and I definitely remember writing something up... 

> This is a breaking change for test functions already declared with return values but I don't think it's a common practice to have such

I can see a use case for this, so did [this](https://github.com/search?q=%2F%5Cstest%5Cw*%5Cs*%5C%28.*%3F%5C%29%5Cs.*%3F%5Cs.*%3F%5Cs*returns%5Cs*%5C%28.*%3F%5C%29%2F+path%3A*.sol&type=Code&ref=advsearch&l=&l=) search to find test functions that this would break.

A notable one using this pattern is solady, [here](https://github.com/Vectorized/solady/blob/adfad66656a6ef8c65b2a412d849bbf7f7a59842/test/FixedPointMathLib.t.sol#L1072C14-L1072C28). 

I do think it's a useful pattern that is worth preserving, even if not super common, so would prefer to avoid using that as a heuristic. I would say no-op tests are more rare and have little execution cost, so they would not outweigh removing this pattern

**Comment by grandizzy** [comment]
Thank you, makes sense, maybe this one could just be retired then

**Comment by mds1** [comment]
Yea, I'd say let's close for now and we can revisit in the future if we get more reports of this being a hassle
