### ISSUE TITLE
Error message when using `--verify` message without `--broadcast` flag any earlier not helpful

### ISSUE THREAD

**Issue by Czar102** [foundry-rs/foundry#3548]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9d64f1f 2022-10-26T00:08:20.899561012Z)

### What command(s) is the bug in?

forge script

### Operating System

Linux

### Describe the bug

When one hasn't used a script with a `--broadcast` flag before and submits a script without it, but with `--verify`, the error message is:
```
/path/to/project/broadcast/ScriptName.s.sol/1/dry-run/run-latest.json": No such file or directory (os error 2)
```
While the error should be more helpful, such as "Cannot verify contracts: flag `--verify` is set, but `--broadcast` isn't and no past deployment was found.". The current error makes it look like it's a foundry error.

**Comment by ghardin1314** [comment]
+1 on this. Been dealing with it for a while and thought it was an issue with my project setup or something
