### ISSUE TITLE
Use ETH_PASSWORD env var for --password

### ISSUE THREAD

**Issue by hexonaut** [foundry-rs/foundry#3555]
### Component

Cast

### Describe the feature you would like

For backwards compatibility with dapp tools it would be nice to use `ETH_PASSWORD` environment variable to supply a file with the passphrase.

**Comment by mattsse** [comment]
this is cleartext password, right?

**Comment by hexonaut** [comment]
It's supplied by `--password`. References a file which contains the passphrase in cleartext yes.

**Comment by brianmcmichael** [comment]
dapptools had the `ETH_PASSWORD` envvar which read a local plaintext file. Docs should probably encourage the file be chmodded to 0600.

**Comment by konstantinzolotarev** [comment]
For similar behaviour as `seth` it does make sense to add `ETH_PASSWORD` env variable that will reference password file.

But in `cast` option `--password` is different, it relates to raw password (as string, pulled from file). And in `cast` it makes more sense to use `ETH_PASSWORD` not as file path, but as raw password. And for password file better to add new property `--password-file` with `ETH_PASSWORD_FILE`.

I'm not sure what approach is better. What do you think @mattsse

**Comment by konstantinzolotarev** [comment]
@hexonaut Issue could be closed
