### ISSUE TITLE
Pathing Issue with Keystore

### ISSUE THREAD

**Issue by hexonaut** [foundry-rs/foundry#3556]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9d64f1f 2022-10-26T00:15:25.10588Z)

### What command(s) is the bug in?

forge script script/DeployExistingTokenBridge.s.sol:DeployExistingTokenBridge --use solc:0.8.14 --rpc-url $(ETH_RPC_URL) --broadcast --verify -vvvv

### Operating System

macOS (Apple Silicon)

### Describe the bug

Maybe I have this misconfigured, but I can't seem to load my keystore private key. Here is my environment:

```
[local] dss-bridge (dss-bridge-deploy-scripts) $ echo $ETH_FROM
0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
[local] dss-bridge (dss-bridge-deploy-scripts) $ echo $ETH_KEYSTORE
/Users/sam/Library/Ethereum/keystore/
```

I have tested and this works fine with cast: `cast send $ETH_FROM`

The forge script command stops after I supply the passphrase with the error:

```
###
Finding wallets for all the necessary addresses...
Enter keystore password:

Transactions saved to: /Users/sam/dev/makerdao/xdomain/packages/dss-bridge/broadcast/DeployExistingTokenBridge.s.sol/31337/run-latest.json

Error: 
IO: Is a directory (os error 21)
```

The command works fine if I supply the private key as a CLI arg.

**Comment by gakonst** [comment]
@roynalnaruto FYI in case this is a eth-keystore-rs bug

**Comment by mds1** [comment]
Looks like this was closed by https://github.com/foundry-rs/foundry/pull/3568, so closing this
