### ISSUE TITLE
Anvil RPC cache not working on docker

### ISSUE THREAD

**Issue by Natanela** [foundry-rs/foundry#3563]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8d8bc28 2022-09-26T17:49:28.998299391Z)

### What command(s) is the bug in?

anvil

### Operating System

Linux

### Describe the bug

When running anvil in docker (foundry:latest) we see that RPC cache is not created and not being used for other forks created on the same docker.
From looking at the file system - the path `~/.foundry/cache/rpc/` doesn't exit

the command we are running:
`anvil -f https://eth-mainnet.alchemyapi.io/v2/xxxxx-xxxxxxxxxxxx-xxx_xxxxxx_xx --fork-block-number 15811946`

**Comment by mattsse** [comment]
is this the container path?

what if you map your host volume to the container?
