### ISSUE TITLE
anvil_reset bug?

### ISSUE THREAD

**Issue by 2547881370** [foundry-rs/foundry#3566]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (3858d18 2022-10-23T12:18:26.3206418Z)

### Describe the bug

When I replayed a transaction, I encountered a strange phenomenon. There is a judgment inside the transaction: it needs to run under the specified block, otherwise it will be REVERT, so I set the block height when fork. 22556410, the simulation is successful;

At this time, the fork node is still running, I want to use anvil_reset to reset to the original block height of 22556410, and continue to replay the same transaction, but the transaction fails;

I'm wondering what's causing this, doesn't anvil_reset reset the state of the entire Evm?

```
// fork options
anvil -f https://bsc-mainnet.nodereal.io/v1/a9d5920ea85349c298ee543d3d4922ac  --chain-id  56 --gas-limit 12000000000000000000 --gas-price 9000000000000000000   --fork-block-number 22556410
```

```
// anvil_reset

pro.send("anvil_reset",
            [
             {
               chainId : 56,
               forking: {
                 jsonRpcUrl: "https://bsc-mainnet.nodereal.io/v1/a9d5920ea85349c298ee543d3d4922ac",
                 blockNumber: 22556410,
               },
             },
           ]
         )

// blockNumber = 22556410
let blockNumber= await pro.send('eth_blockNumber'); 
```

**Comment by mattsse** [comment]
yes the state is cleared, is this unexpected behaviour?

**Comment by Evalir** [comment]
Closing—stale and expected behavior.
