### ISSUE TITLE
Incorrect coverage report

### ISSUE THREAD

**Issue by 0xask3** [foundry-rs/foundry#3570]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (cbf77c2 2022-10-27T00:04:38.685478Z)

### What command(s) is the bug in?

forge coverage

### Operating System

macOS (Apple Silicon)

### Describe the bug

The coverage report seems inaccurate. I am trying to run coverage with a forked network and the coverage report generated seems incorrect. It says I have 100% line coverage (which is correct) but 83% function coverage, which doesn't even make sense. Generated lcov report also doesn't show any missed parts too. 
![Screenshot 2022-10-29 at 3 14 52 PM](https://user-images.githubusercontent.com/76556605/198824990-c9698971-1ace-4b2e-ab16-0e5150ab7a01.jpeg)

**Comment by grimreaper619** [comment]
Ignore the other two, only HODLOracle.sol have this issue

**Comment by Evalir** [comment]
Closing, stale and there are quite a few issues pointing out limitations in coverage.

**Comment by DaniPopes** [comment]
Similar to https://github.com/foundry-rs/foundry/issues/5623
