### ISSUE TITLE
forge

### ISSUE THREAD

**Issue by tony101-cloud** [foundry-rs/foundry#3574]
### Component

Forge

### Describe the feature you would like

why can forge compile multiple solidity version just like hardhat

**Comment by rkrasiuk** [comment]
@tony101-cloud `forge build` supports compilation of multiple solidity versions. could you describe the issues you are experiencing?

**Comment by tony101-cloud** [comment]
It gives discovered incompatible solidity versions or source files requires different compiler version

**Comment by onbjerg** [comment]
If you import a Solidity file compiled with one version (defined by `pragma version <version>`) into a file with another version constraint, and those two constraints are incompatible, then compilation will fail. This is a limitation of solc.
