### ISSUE TITLE
Foundry recompiles even if nothing changes

### ISSUE THREAD

**Issue by Timidan** [foundry-rs/foundry#3583]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (28312e7 2022-10-13T06:10:43.734727384Z)

### What command(s) is the bug in?

forge build

### Operating System

Linux

### Describe the bug

Foundry recompiles the whole contracts everytime even if there is no change to the code. Steps to reproduce

clone [this repo's branch](https://github.com/aavegotchi/aavegotchi-realm-diamond/tree/cartridge_receipts-_and_discounts)

run `forge build`

then run `forge build` again

it recompiles even though there is no change to the contracts

**Comment by mds1** [comment]
Your foundry version is almost 3 weeks old, can you run `foundryup` and see if this still happens? I tried to reproduce but seems to be a remappings error on that branch

```
[⠊] Compiling...
Error:
Failed to resolve file: "/Users/mds/Documents/projects/aavegotchi-realm-diamond/node_modules/@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable.sol": No such file or directory (os error 2).
    --> "/Users/mds/Documents/projects/aavegotchi-realm-diamond/contracts/Alchemica/AlchemicaToken.sol"
        "@openzeppelin/contracts-upgradeable/access/OwnableUpgradeable.sol"
    Check configured remappings.
```

**Comment by Timidan** [comment]
i just updated to `forge 0.2.0 (0e1d52d 2022-10-31T00:07:38.133914649Z)` and same issue

please use this branch instead [here](https://github.com/aavegotchi/aavegotchi-realm-diamond/tree/RELM-1869-add-batch-transfer-tokens-function-to-alchemica-facet)

**Comment by mds1** [comment]
Got it, I was able to reproduce (had to make one change to fix a compiler error on that branch).

I'm not sure what the cause it, but maybe related to the use of both node_modules and lib? I haven't used foundry+hardhat repos personally so will defer to @mattsse here

**Comment by Timidan** [comment]
hmm...a compiler error?...weird

i also thought the main issue would be the fact that hardhat is also used
