### ISSUE TITLE
testFail tests do not report the revert reason

### ISSUE THREAD

**Issue by norswap** [foundry-rs/foundry#3586]
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (0e1d52d 2022-10-31T00:04:54.74416Z)

### What command(s) is the bug in?

forge test -vvvv

### Operating System

macOS (Apple Silicon)

### Describe the bug

When running a test that is supposed to fail (`testFailXXX`), the reason for the revert is not given, appearing only as `"EvmError: Revert"`.

Meanwhile, on test that are supposed to succeed, the exact same revert will list the reason if available (e.g. `"ERC20: insufficient allowance"`).

It's pretty useful to see the actual revert reason as a sanity check that the test fails for the expected reason. It seems like it should be possible to make the behaviour symmetric between `testXXX` and `testFailXXX`.

**Comment by norswap** [comment]
In this particular case I considered it, but I was testing that a function reverted if the contract wasn't initialized. Since the initialization set some addresses, it meant that the function would fail anyway by making a call to address 0 and so an explicit `require` is not needed.

The revert in this case has no message, so I could use `vm.expectRevert("")`. I guess it is better than `testFail` because at least the test won't pass if failing for something that has a message. I will make this change!

**Comment by zerosnacks** [comment]
Marking as `stale / wontfix` as `testFail` is an antipattern
