### ISSUE TITLE
forge verify-contract error: "contract with duplicate name Vault. please pass the path instead

### ISSUE THREAD

**Issue by MiguelBits** [foundry-rs/foundry#3591]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9d1a543 2022-09-08T13:14:05.2163638Z)

### What command(s) is the bug in?

forge verify-contract 0x38589723f8a024cfed58f58ad36f56e45b941119 src/Vault.flattened.sol:Vault $arbiscanApiKey --watch

### Describe the bug

Error:
"contract with duplicate name `Vault`. please pass the path instead"
how to proceed?
even providing full windows path gives same error!

**Comment by mattsse** [comment]
oh interesting, can you confirm that there are two contracts with that name in your project?

looks like something's off with how we try to find the contract from cache. we need to check this since we don't know the compiler version it was compiled with.

could you try providing the compiler version as argument as well? then we shouldn't need to check the cache.

**Comment by mattsse** [comment]
@rkrasiuk I'm not sure about this check, which seems to be causing this

https://github.com/foundry-rs/foundry/blob/b0e0e3781b7b2ffb89040de3f2c4ae4e942c4988/cli/src/cmd/forge/verify/etherscan.rs#L214-L216

wdyt?

**Comment by rkrasiuk** [comment]
ah, well, the problem is that judging from the command, @MiguelBits flattened first and then is running verify.
so, this line should be causing a problem
https://github.com/foundry-rs/foundry/blob/b0e0e3781b7b2ffb89040de3f2c4ae4e942c4988/cli/src/cmd/forge/verify/etherscan.rs#L219

@MiguelBits have you tried running with `--flatten` without flattening beforehand?

**Comment by MiguelBits** [comment]
Even without the flattening this happens with my original Vault.sol

**Comment by rkrasiuk** [comment]
other than Vault in `Vault.flattened.sol`, do you have any other contracts named `Vault` in your repo? if not, could you please run
`rm src/Vault.flattened.sol && forge clean && forge b && forge v 0x38589723f8a024cfed58f58ad36f56e45b941119 Vault $arbiscanApiKey --watch`

**Comment by MiguelBits** [comment]
also this is happening because I need to verify contracts that are not verified because VaultFactory.sol generates these Vault.sol contrscts, which are not coming out verified

**Comment by MiguelBits** [comment]
No I dont have two Vault contracts
solidity 0.8.15
Ran the command same is happening

**Comment by MiguelBits** [comment]
`$ forge v 0x38589723f8a024cfed58f58ad36f56e45b941119 Vault $arbiscanApiKey --watch --compiler-version 0.8.15
`  
same thing :(

**Comment by rkrasiuk** [comment]
@MiguelBits any chance you could share the source repo or some minimum repro?

**Comment by MiguelBits** [comment]
@rkrasiuk added you as a viewer to the repo, https://github.com/Y2K-Finance/Earthquake

**Comment by rkrasiuk** [comment]
@MiguelBits thanks, so there is a duplicate `Vault` contract in your repo. it's in `src/interfaces/IVault.sol`. that would fix a problem short term while we look into the path resolution issue

**Comment by MiguelBits** [comment]
I deleted that file, and then tried the command. Gave the same issue

**Comment by rkrasiuk** [comment]
you'd have to clear cache as well. you can run `forge clean` for that

**Comment by MiguelBits** [comment]
Ahhhh got it, I have to forge build after deleting

**Comment by MiguelBits** [comment]
Let me get back to you after trying

**Comment by MiguelBits** [comment]
yes gives a different error now: 
``` Submitting verification for [src/Vault.sol:Vault] Ok("0x38589723F8a024cFed58f58Ad36F56e45B941119").
Encountered an error verifying this contract:
Response: `NOTOK`
Details: `Invalid API Key ```

getting close to verifying this maybe

**Comment by rkrasiuk** [comment]
@MiguelBits looking at the command you've pasted before, you are also missing a chain id arg if you're trying to verify on arbitrum

**Comment by MiguelBits** [comment]
Yes must be something on the commands now, thank you for support I am trying to figure verifying the bytecode now
```forge verify-contract --chain-id 42161 --num-of-optimizations 1000000 --watch --constructor-args $(cast abi-encode "constructor(address,address,address,address,uint256)" 0xaC0D2cF77a8F8869069fc45821483701A264933B 0xaC0D2cF77a8F8869069fc45821483701A264933B 0x65c936f008BC34fE819bce9Fa5afD9dc2d49977f 0x447deddf312ad609e2f85fd23130acd6ba48e8b7 1668384000) --compiler-version v0.8.15+commit.e14f2714 0x69b614f03554c7e0da34645c65852cc55400d0f9 src/rewards/PausableStakingRewards.sol:StakingRewards $arbiscanApiKey

Submitting verification for [src/rewards/PausableStakingRewards.sol:StakingRewards] "0x69B614f03554C7E0DA34645c65852CC55400d0F9".
Submitted contract for verification:
        Response: `OK`
        GUID: `kbu3lpjgvdafsiknk6jq2gfmbrt2htzqcls42qyyz8xlnvd7yr`
        URL:
        https://arbiscan.io/address/0x69b614f03554c7e0da34645c65852cc55400d0f9
Waiting for verification result...
Contract verification failed:
Response: `NOTOK`
Details: `Fail - Unable to verify`

```

**Comment by MiguelBits** [comment]
I just deployed those contracts without Factory, only by themselves and it verified. FYI for anyone who cant verify contracts deployed from factories
