### ISSUE TITLE
feat: add Arbiscan contract verification support

### ISSUE THREAD

**Issue by PierrickGT** [foundry-rs/foundry#3597]
### Component

Forge

### Describe the feature you would like

Currently, it's only possible to verify contracts deployed on Arbitrum Goerli on https://goerli-rollup-explorer.arbitrum.io
It fails to verify contracts on https://goerli.arbiscan.io

Feature: support Arbiscan contract verification

### Additional context

I've setup the following `foundry.toml` config to enable verification on Arbiscan:
```
[etherscan]
arbitrum-goerli = { key = "${ARBITRUM_ETHERSCAN_API_KEY}", url = "https://api-goerli.arbiscan.io/api" }
```

Despite this configuration and even when passing those parameters to the CLI command `forge verify-contract`, it default to verifying on Blockscout.

**Comment by mattsse** [comment]
what if you pass the "--verifier etherscan" argument?

looks we have mapped the default to blockscout https://goerli-rollup-explorer.arbitrum.io/

here https://github.com/gakonst/ethers-rs/blob/50c7ff1d8eb93bb31de47ad0a323afe25abdd739/ethers-core/src/types/chain.rs#L171

**Comment by PierrickGT** [comment]
> --verifier-url

Ah you're right, it does work if I pass `--verifier-url https://api-goerli.arbiscan.io/api`.
Thanks!

**Comment by PierrickGT** [comment]
> What `--verifier-url` value should I pass to verify in Arbiscan?

`https://api.arbiscan.io/api`
