### ISSUE TITLE
Add a flag that displays the transaction hash and/or trace of a `cast send` even if the transaction is failing.

### ISSUE THREAD

**Issue by ZrowGz** [foundry-rs/foundry#3606]
### Component

Cast

### Describe the feature you would like

Add a flag to: `cast send <ADDRESS> "foo()" like `--txn-trace` and/or `--txn-hash` that will display a trace or the transaction hash for the send, even if the transaction is failing.

Or it could just always provide the transaction hash, even if it fails. Being able to locate where in the execution it was failing allowed me to track down the issue & do some account impersonating to correct the hiccup at the external contract.

### Additional context

I was getting an error & failed transaction using `cast send ...` and the error simply gave the error string. It didn't display the failed transaction hash. 

Hooked it up to a frontend and ran it from metamask, where I was able to retrieve the transaction hash & then run `cast run 0xTxnHash` to get the trace, showing me where in the function call the issue was arising. 

Example of what I was seeing when the txn failed: 
![Screen Shot 2022-11-03 at 11 33 09](https://user-images.githubusercontent.com/80988768/199805831-912c5cf6-569a-4d63-9ed7-e4f63fe33b5b.png)

**Comment by zerosnacks** [comment]
For future reference: the transaction hash should be displayed at all times, the transaction trace at higher verbosity. Should not be locked behind a new flag.

`cast send` should display the pending transaction hash as soon as it is broadcasted, right now we only display the result upon inclusion in the block

**Comment by zerosnacks** [comment]
There are two error modes, possibly more

a simulation error, no transaction is submitted on-chain

```
$ cast send 0x750f3141BdB2e7C770379b307d0A59a0dECF342C --rpc-url <RPC_URL> "increment()"
Error: 
server returned an error response: error code 3: execution reverted, data: "0x8615f5ee"
```

and a failure on chain

```
cast send 0x750f3141BdB2e7C770379b307d0A59a0dECF342C --rpc-url <RPC_URL> "increment()"

blockHash               0x2ddccc9ea1b4cdfa4a44d41b5e6b9a970a7ea870ea4a85c2b5760e748bc7deed
blockNumber             6922249
contractAddress         
cumulativeGasUsed       5367163
effectiveGasPrice       4100898111
from                    0xDCC004c7Cd4275E9b83106F609163095670700db
gasUsed                 21339
logs                    []
logsBloom               0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
root                    
status                  0 (failed)
transactionHash         0x372ef5bd029593b986f51f4308b36ea9ede35436ddb631fb67c9e55f90a47513
transactionIndex        58
type                    2
blobGasPrice            
blobGasUsed             
authorizationList       
to                      0x750f3141BdB2e7C770379b307d0A59a0dECF342C
```

**Comment by grandizzy** [comment]
optimistically closing per comments above - there were many improvements since ticket was opened, please reopen if you still find the error message not explicit enough. thank you!
