### ISSUE TITLE
Forge fmt sometimes fails to parse documents that subtract from an integer literal written in scientific notation 

### ISSUE THREAD

**Issue by jameswenzel** [foundry-rs/foundry#3608]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What command(s) is the bug in?

forge fmt

### Operating System

macOS (Apple Silicon)

### Describe the bug

`forge fmt` fails to parse documents that contain _specifically_ subtraction _from_ a numeric literal written in scientific notation without a leading space in front of the `-` operator.

I have tried and been unable to recreate with: other builtin operators; regular numeric literals, variables, etc; different kinds of spacing.  

`forge fmt` will fail to parse

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.17;

import "forge-std/Test.sol";

contract ScientificNotationTest is Test {
    function testFormat() public {
        uint256 b = 500;
        uint256 a = 1e18-b;
    }
}
```
as well as

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.17;

import "forge-std/Test.sol";

contract ScientificNotationTest is Test {
    function testFormat() public {
        uint256 b = 500;
        uint256 a = 1e18- b;
    }
}
```

whereas `forge fmt` seems to happily format any other combination of operator and spacing.

**Comment by mds1** [comment]
This should now be resolved, closing
