### ISSUE TITLE
Compilation error when importing foundry-cli in another project

### ISSUE THREAD

**Issue by odyslam** [foundry-rs/foundry#3619]
### Component

Other (please describe)

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

latest

### Describe the bug

- I can build foundry on the machine from the latest master
- When importing foundry-cli to another project, I can't compile (foundry-cli = { git = "https://github.com/foundry-rs/foundry" })
- Error: https://pastebin.com/5uj9N8Nx

**Comment by mattsse** [comment]
what's your rust version? try after running `rustup update`

**Comment by odyslam** [comment]
@mattsse already tried it. Using latest

**Comment by odyslam** [comment]
Okay, I figured out, it was something with how `indicatif` dependency is resolved. Something tells me that the version in foundry-cli is wrong, but it's not surfaced because another dependency is constraining it ( I think svm-rs). 

Here is the cargo.lock file in my project:

**Comment by odyslam** [comment]
I believe we need to restrict `indicatif` to exactly `0.17.0-rc.11`
