### ISSUE TITLE
Anvil logs eating up disk space

### ISSUE THREAD

**Issue by holic** [foundry-rs/foundry#3623]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8b0af47 2022-11-06T00:06:24.552295Z)

### What command(s) is the bug in?

anvil

### Operating System

macOS (Apple Silicon)

### Describe the bug

My Macbook was suddenly warning me about low disk and asked to me clear space. I cleared out a few hundred gigs from various project folders (mostly node_modules), but then got another low disk warning a day or two later. When I looked at my disk usage, it was steadily decreasing every few seconds.

I later found that this was all due to anvil running with interval mining turned on and a block time of 1s (I know that this is edge-case-y but I am trying to mimic block times for a custom Optimism node used for [OPCraft](https://dev.optimism.io/opcraft-autonomous-world/)).

After some more digging with `ncdu`, I found that anvil was creating _gigabytes_ worth of 8-9mb JSON files, buried in a folder under `/private/var/folders`:
![image](https://user-images.githubusercontent.com/508855/200196093-cffb68f6-1129-4019-83df-8268f50f678f.png)
![image](https://user-images.githubusercontent.com/508855/200196100-2aaf5cab-5f41-4ea0-bf3f-04d328a3d980.png)

I'd like to ask for a few things here:
- is it possible to reduce the amount of data being logged by anvil?
- can anvil use a directory name that makes it clear that these logs come from anvil? and that they're safe to delete/prune?
- can a CLI command be added to safely flush whatever the configured log directory is?

**Comment by mattsse** [comment]
thanks for raising this

> but then got another low disk warning a day or two later. 

oh, with 1s blocktime that's quite a lot of blocks :)

> can anvil use a directory name that makes it clear that these logs come from anvil? and that they're safe to delete/prune?

> can a CLI command be added to safely flush whatever the configured log directory is?

yes will add this.

**Comment by holic** [comment]
Thank you! Is there a possibility of reducing log storage requirements as well?

**Comment by holic** [comment]
Had this happen a couple more times recently while leaving Anvil running over night:

<img width="475" alt="image" src="https://user-images.githubusercontent.com/508855/214635613-f62c79e7-9b34-432e-bd75-238e4a1de174.png">

🙈

**Comment by mattsse** [comment]
yikes, I'm working on making pruning smarter

you can use the `--prune-history` flag to discard old state entirely

**Comment by holic** [comment]
That makes sense if I am starting/stopping regularly, but I often leave it running/in the background while building my app. It'd be great if pruning could be configured to check on an interval and clear things older than a certain age (e.g 1h or 1 day or whatever). Or even just limit the number of log files stored.

I could probably wire up something with `logrotate` in the meantime, but would be nice to have this in anvil itself.

**Comment by holic** [comment]
I know gzipped json isn't immediately readable, but I also wonder about storing them gzipped (for space savings).

**Comment by mattsse** [comment]
> (e.g 1h or 1 day or whatever). Or even just limit the number of log files stored.

agreed

**Comment by holic** [comment]
I see now that `--prune-history` just doesn't keep historical logs (the flag naming was a little misleading). Maybe something like "only keeps x blocks of history" (where x is configurable) matches more closely with other node providers.

**Comment by holic** [comment]
Another thought: I'm generally more interested in logs if it's a failed tx (to better understand what went wrong), so maybe a way to opt into logs for certain tx types?

**Comment by michprev** [comment]
I wonder, would it be possible to automatically clear logs when terminating an anvil process? Would there by any drawback of doing this?

**Comment by holic** [comment]
Thanks @mattsse! To clarify, do these new defaults exist without any flags?

**Comment by mattsse** [comment]
yes no longer required, checks are in place by default.

will ship through foundryup in a couple of hours
