### ISSUE TITLE
`forge test` does not ensure termination

### ISSUE THREAD

**Issue by yehjxraymond** [foundry-rs/foundry#3629]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (44f3a4b 2022-07-18T00:09:43.728981Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

`forge test` does not ensure that the program terminates. There was an infinite loop in one of the smart contract that I'm testing and it gets stuck at `Compiler run successful (with warnings)` when `forge test` is ran.

To replicate the issue, create a test or contract under test that doesn't terminate, ie:
```
...
    function testLoop() public {
        while (true) {
            // Do nothing
        }
    }
...
```

Running `forge test` will have the terminal stuck at `Compiler run successful (with warnings)` until manually terminated. This may be a problem when testing in CI where the program will consume extra compute hours. 

Suggestion is to allow for test to have a gas limit that can be adjusted by the user or a global timeout for the test. This ensure that the program always terminates and also testers can be more aware of the gas consumed.

**Comment by mds1** [comment]
There is a gas limit, so it will exit once that's hit. It's possible that `while (true) {}` would run forever if it's not evaluating some expression each loop. If you're using GitHub CI you can set timeouts there with `jobs.<job_id>.steps[*].timeout-minutes` and `jobs.<job_id>.timeout-minutes`: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepstimeout-minutes

**Comment by mattsse** [comment]
the default sender's balance is quite high so this would run for a while.

hence, I wouldn't consider this a bug.

**Comment by thedavidmeister** [comment]
@mattsse hmm, i've got a loop seeming to run forever, no gas limit being hit even if i prank some address, and i can't see a way to set a gas limit with a cheatcode

in my case i'm trying to test that i DO hit always gas limit under certain conditions, so having it loop forever is not helpful
