### ISSUE TITLE
Exclude Special Addresses in Fuzzing Dictionary

### ISSUE THREAD

**Issue by hexcowboy** [foundry-rs/foundry#3630]
### Component

Forge

### Describe the feature you would like

Described by @mds1 

> We can consider excluding special foundry addresses from the fuzz dictionary. This would be all addresses that behave differently in foundry than they do on live chains, which includes:
> 
>  - VM address
>  - Console address
>  - Are there others?
> 
> Create2Deployer and precompiles are valid inputs an attacker can pass in real life, so we wouldn't want to exclude those.

- VM Address: `0x7109709ECfa91a80626fF3989D68f67F5b1DD12D` ([ref](https://github.com/dapphub/dapptools/blob/master/src/hevm/README.md#cheat-codes))
- Console address: `0x000000000000000000636F6e736F6c652e6c6f67` ([ref](https://github.com/foundry-rs/forge-std/blob/5bafa16b4a6aa67c503d96294be846a22a6f6efb/src/console2.sol#L10))

### Additional context

https://github.com/foundry-rs/foundry/issues/3625

**Comment by mds1** [comment]
Similar to #3631 you could implement this with an `assumeNoSpecialAddress` function in forge-std. However it's very common to need to exclude these addresses as inputs, and I can't think of a reason why you'd want them as inputs, so I think implementing this in foundry is the better choice here

**Comment by hexcowboy** [comment]
see https://github.com/foundry-rs/forge-std/pull/270
