### ISSUE TITLE
[BUG -cast] Prefix of 0x - when generating vanity wallets via cast wallet vanity 

### ISSUE THREAD

**Issue by m0ham3dx** [foundry-rs/foundry#3635]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (c8431ed 2022-11-07T00:08:05.346696623Z)

### What command(s) is the bug in?

cast wallet vanity --starts-with / --ends-with

### Operating System

Linux

### Describe the bug

# Description 

- When generating a vanity address using `cast wallet vanity --starts-with or --ends-with` a prefix of `0x` is added to the private key. 

# Repro 
![image](https://user-images.githubusercontent.com/82266083/200410255-c8204681-fb66-41ea-b0b0-5abee1471286.png)

- Following is the screen shot of the command and the issue

[screen shot](https://i.ibb.co/92kg0G6/image.png)

**Comment by mattsse** [comment]
since this is hex, I wouldn't consider this a bug per se, but this is at least inconsistent with `wallet new`.

given that `wallet vanity` came last, perhaps we should drop the 0x here as well.

I really don't have strong feelings about the 0x prefix, wdyt @rkrasiuk ?

**Comment by rkrasiuk** [comment]
same, i don't mind either way as long as its consistent. on it
