### ISSUE TITLE
Able to custom maxPriorityFeePerGas on Solidity-Scripting

### ISSUE THREAD

**Issue by rkdud007** [foundry-rs/foundry#3642]
### Component

Forge

### Describe the feature you would like

I cannot find how to use  [forge-script options](https://book.getfoundry.sh/reference/forge/forge-script?highlight=Solidity%20Scripting#options) and [Solidity Scripting](https://book.getfoundry.sh/tutorials/solidity-scripting) to handle maxPriorityFeePerGas or maxFeePerGas (eip-1559).

I made a [similar issue](https://github.com/NomicFoundation/hardhat/issues/3298) & [pr](https://github.com/NomicFoundation/hardhat/pull/3331) on hardhat. 

for better gas optimization for dev, I think forge-scripting with eip-1559 adopt is quite important feature.

### Additional context

I attached some links above.

**Comment by Sabnock01** [comment]
@Evalir is this resolved by #5585 ?

**Comment by mds1** [comment]
It seems now we have a `--priority-gas-price` flag which handles the `maxPriorityFeePerGas` field, and a `--with-gas-price` flag handles the `maxFeePerGas` field for 1559 transactions, so seems this can be closed. Thanks!

**Comment by Sabnock01** [comment]
> It seems now we have a `--priority-gas-price` flag which handles the `maxPriorityFeePerGas` field, and a `--with-gas-price` flag handles the `maxFeePerGas` field for 1559 transactions, so seems this can be closed. Thanks!

We should probably just implement `TransactionOpts` for `forge script` instead of reinventing the wheel with these flags. That can maybe be its own issue.
