### ISSUE TITLE
Anvil freezes in sub-process

### ISSUE THREAD

**Issue by Theo-** [foundry-rs/foundry#3648]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (0c61e40 2022-11-08T16:46:49.405733Z)

### What command(s) is the bug in?

anvil

### Operating System

macOS (Apple Silicon)

### Describe the bug

When running Anvil in a sub process (for example spawned by a Go process), calling `evm_mine` makes Anvil freeze for 5 to 9 seconds. I'm trying to mine a block with about 20 transactions.

A similar issue was reported here: https://github.com/foundry-rs/foundry/issues/2652

**Comment by mattsse** [comment]
hmm interesting.

you're calling evm_mine as rpc call from the program that spawned the anvil process?

**Comment by Theo-** [comment]
I'll try and get an example, but basically I'm grabbing 20 signed transactions from 20 different signers, stacking them onto a forked chain (forked server is 200ms away) and mining a block.

**Comment by Theo-** [comment]
@mattsse here is a single go script to reproduce the issue (it mines the current block).

```go
package main

import (
	"context"
	"fmt"
	"os/exec"
	"strconv"
	"time"

	"github.com/ethereum/go-ethereum/ethclient"
	"github.com/ethereum/go-ethereum/rpc"
	log "github.com/sirupsen/logrus"
)

// put your fork url here
const FORK_URL = "http://xxxxx"

func main() {
	// Create an IPC based RPC connection to a remote node
	conn, err := ethclient.Dial(FORK_URL)
	if err != nil {
		log.Fatalf("Failed to connect to the Ethereum client: %v", err)
	}

	// get the latest block
	block, err := conn.BlockByNumber(context.TODO(), nil)

	if err != nil {
		log.Fatalf("Failed to get latest block: %v", err)
	}

	port := 21000

	forkBlockNumber := block.Number().Uint64() - 1

	// fork anvil at the previous block
	args := []string{
		"-a", "0", "--no-mining", "--fork-block-number", strconv.Itoa(int(forkBlockNumber - 1)), "-p", strconv.Itoa(port), "--chain-id", "137", "-f", FORK_URL,
	}

	ganacheCmd := exec.Command("anvil", args[:]...)

	log.WithField("command", ganacheCmd.String()).Info("starting ganache")

	// kill ganache when done
	defer func() {
		log.WithFields(log.Fields{
			"pid": ganacheCmd.Process.Pid,
		}).Info("killing ganache")

		err := ganacheCmd.Process.Kill()

		if err != nil {
			log.WithError(err).Error("failed to kill ganache")
		}
	}()

	err = ganacheCmd.Start()

	log.WithFields(log.Fields{
		"pid":  ganacheCmd.Process.Pid,
		"fork": FORK_URL,
	}).Debug("Started ganache")

	// wait a bit
	time.Sleep(1 * time.Second)

	// connect to anvil
	rpc, _ := rpc.Dial(fmt.Sprintf("http://localhost:%d", port))
	anvil := ethclient.NewClient(rpc)

	startTxSend := time.Now()

	// pass the current block's transaction to anvil
	for _, tx := range block.Transactions() {
		err := anvil.SendTransaction(context.Background(), tx)

		if err != nil {
			log.WithError(err).Error("failed to send transaction")
		}
	}

	log.WithFields(log.Fields{
		"in":  time.Since(startTxSend),
		"txs": len(block.Transactions()),
	}).Info("Sent transactions to anvil")

	startTime := time.Now()

	// mine the next block
	err = rpc.Call(nil, "evm_mine", nil)

	log.WithFields(log.Fields{
		"in":  time.Since(startTime),
		"err": err,
	}).Info("anvil block mined")
}
```

Here is the output is:

```
INFO[0000] starting ganache                              command="/anvil -a 0 --no-mining --fork-block-number 35416266 -p 21000 --chain-id 137 -f http://FORK_URL"
INFO[0001] Sent transactions to anvil                    in=809.475708ms txs=59
INFO[0016] anvil block mined                             err="<nil>" in=14.887776333s
```

It's also quite slow to send all txs to the anvil instance, considering it's on the same machine. In this case mining the block took 14s+

**Comment by mattsse** [comment]
can confirm that the first run takes ~14s 
that's because we have to fetch the necessary state from the fork endpoint. However, 

consecutive runs against the same block are much faster because the state is cached. 

So the freeze is actually just the amount of time it takes to fetch all the touched slots.

If you have a fork API key with a higher tier then you can set a custom CUPS value, see

anvil --help for `--compute-units-per-second` which we use to budget requests

**Comment by Theo-** [comment]
If is possible to make `--compute-units-per-second` unlimited? I run my own node

**Comment by mattsse** [comment]
is the fork url localhost?

**Comment by Theo-** [comment]
I put the script on the node, and cranked up the cpu limit, now blocks mine in < 100ms. Thanks!

**Comment by mattsse** [comment]
A non-local node that is not operated by a provider is probably more of an unconventional niche setup overall.

However, this should be better supported.

There should be a flag to opt out of ratelimit prevention I think, will add this
