### ISSUE TITLE
Intermittent failures to `deal` on fork

### ISSUE THREAD

**Issue by marktoda** [foundry-rs/foundry#3651]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (2c25b89 2022-11-09T00:07:40.191383165Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

We have a test suite that runs a lot of fork tests which deal ETH to a fresh address, prank that address and run a situational test from that address. For example:
```js
uint256 fromPrivateKey = 0x1234;
address from = vm.addr(fromPrivateKey);
vm.createSelectFork(vm.envString("FORK_URL"), blockNum);
vm.startPrank(from);
vm.deal(from, 1 ether);

// run simple send simulation
address(recipient).call{value: 0.1 ether }("");
```

Intermittently (~1/20 test runs) the `deal` call seems to fail to actually deal ETH to the address. This results in an error: `EvmError: OutOfFund` -- this is a native evm error that the account didn't have enough ETH to pay for gas.

Strangely, if checking the balance first like `assertEq(from.balance, 1 ether)`, the check passes. 

Note that on similar but non-fork tests this intermittent error never happens. Seems to be related to interplay between vm.createSelectFork and vm.deal. Let me know what other info I can provide

**Comment by mattsse** [comment]
there's likely something of with when and how the account for `from` is fetched. It's likely related to the prank call.

Thanks for the repro will try to replicate and fix.
