### ISSUE TITLE
Add config to abort on first fail when performing fuzzing

### ISSUE THREAD

**Issue by xenoliss** [foundry-rs/foundry#3662]
### Component

Other (please describe)

### Describe the feature you would like

When writing fuzzing tests I often find myself waiting for the all fuzzing to end before being able to see the "bug". It sort of make the `debug => fix => run test => debug => fix => run test` process quite painfull when working on a failing test case with fuzzing.

Would be super cool to be able to specify somehow that I'd like the fuzzer to abort fuzzing when a test fails. Could be in the command line as an additional parameter or in the `[fuzz]` section of the `foundry.toml` file.

**Comment by mds1** [comment]
> It sort of make the `debug => fix => run test => debug => fix => run test` process quite painfull when working on a failing test case with fuzzing

You can run `forge test --match-test test_MyTest` to only run the failing case which makes the process easier. Can also just `Ctrl + C` to stop the process once there's a failing run. Going to close this since this feels unnecessary but let me know if I misunderstood 🙂

**Comment by xenoliss** [comment]
Hey, what I meant is, not related to test selection. Say I'm using `--mt` to only run a specific fuzz test, the problem is, if run number 34 fails, I still have to wait for the entire `fuzz.runs` campaign to be ran before seing the failing test (which can take several minutes for complexe test suite with ffi etc.)

**Comment by grandizzy** [comment]
> 

I am experiencing same issues when running large invariant test suite (bunch of invariants / runs and big depth), would be great to have the option to turn off shrinking. Thank you

**Comment by mds1** [comment]
@grandizzy created https://github.com/foundry-rs/foundry/issues/4867 to track
