### ISSUE TITLE
The latest foundryup breaks a worked forge script 

### ISSUE THREAD

**Issue by aiwowo1** [foundry-rs/foundry#3663]
### Component

Forge, Foundryup

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e320eb3 2022-11-10T00:10:11.009337124Z)

### What command(s) is the bug in?

 forge script

### Operating System

Linux

### Describe the bug

hi, the newest foundryup update breaks my forge script which uses   vm.selectFork(mainnetFork);  which has been working before yesterday's foundryup. The error is : 

No associated wallet for addresses: {0xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx...(my test wallet address}. Unlocked wallets: []

the script command I run is: ` forge script ForkDeploy.s.sol --broadcast -vvvv `

in regarding no privateKey provided in the command, I'm using .env and mnemonic to ge the key in side the .sol file

```
contract ForkDeploy is Script {
    function run() external {
        string memory MAINNET_RPC_URL = vm.envString('MAINNET_RPC_URL');
        uint256 mainnetFork = vm.createFork(MAINNET_RPC_URL);
        vm.selectFork(mainnetFork);
        string memory mnemonic = vm.envString('MNEMONIC');
        uint256 privateKey = vm.deriveKey(mnemonic, 0);
        address deployer = vm.addr(privateKey);

        vm.startBroadcast(deployer);

        AmmalgamFactory factory = new AmmalgamFactory(deployer);
        factory.setFeeTo(deployer);

        vm.stopBroadcast();

        console2.log('Factory Address:', address(factory));
    }
}
```

It has been working until yesterday foundryup. The current one remains in the same issue.  

I'm hoping a fix will also solve another problem with the external library that I reported here: #3646

**Comment by mattsse** [comment]
@joshieDo perhaps related to multifork support?

**Comment by joshieDo** [comment]
Most likely, I'll look into the env+priv_key logic. However, broadcasting shouldn't be working with `createFork`, previous to the multi fork PR. 

@aiwowo1 were you actually broadcasting stuff with this script?

**Comment by aiwowo1** [comment]
removing the --broadcast from the command solved this problem:

` forge script ForkDeploy.s.sol -vvvv `

**Comment by mds1** [comment]
Switching forks during a script should be supported, so going to close this, but if there's still an issue please provide steps to reproduce and we can reopen
