### ISSUE TITLE
Add anvil option to opt out of rate-limit prevention

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#3668]
A non-local node that is not operated by a provider is probably more of an unconventional niche setup overall.

However, this should be better supported.

There should be a flag to opt out of ratelimit prevention I think, will add this

_Originally posted by @mattsse in https://github.com/foundry-rs/foundry/issues/3648#issuecomment-1311962646_
      

Perhaps `--no-rate-limits` would be the appropriate flag here

**Comment by Evalir** [comment]
Would love to add this myself! 

I suppose that if `--no-rate-limits` is used we could just set `compute_units_per_second` in anvil to something like `u64::MAX` to avoid throttling?

**Comment by mattsse** [comment]
exactly, this flag would just bump the cups budget to max which would have the same effect
