### ISSUE TITLE
After run `forge flatten` command, then I run forge build, it shows: Multiple SPDX license identifiers found in source file. 

### ISSUE THREAD

**Issue by KittyFu307** [foundry-rs/foundry#3678]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (c5791f5 2022-11-11T00:05:26.949466Z)

### What command(s) is the bug in?

forge flatten

### Operating System

macOS (Apple Silicon)

### Describe the bug

Firstly I run the `forge flatten --output src/a.sol  src/Impl/b.sol ` to flat my contract. 
Then I run `forge build`.
It will give me an error:  ParserError: Multiple SPDX license identifiers found in source file. Use "AND" or "OR" to combine multiple licenses.
<img width="1463" alt="截屏2022-11-13 上午11 21 23" src="https://user-images.githubusercontent.com/61280608/201504060-5c5460fc-beab-421b-8fc2-eb5e0b60f022.png">

**Comment by rkrasiuk** [comment]
@KittyFu307 where are your license identifiers situated within the file? as far as i remember, we strip them only if they located on the very first line

**Comment by KittyFu307** [comment]
> @KittyFu307 where are your license identifiers situated within the file? as far as i remember, we strip them only if they located on the very first line

It's in the first line of my file

**Comment by mattsse** [comment]
could you perhaps provide a repro for this?
all files, without all the contract code
