### ISSUE TITLE
`pattern` config options have no effect

### ISSUE THREAD

**Issue by ZeroEkkusu** [foundry-rs/foundry#3684]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### Describe the bug

I want to filter out tests with `Ffi` in the name by default.

Foundry Book [lists](https://book.getfoundry.sh/reference/config/testing#test_pattern) the following config options, but they have no effect:

- `test_pattern`
- `test_pattern_inverse`
- `contract_pattern`
- `contract_pattern_inverse`

Example:

```toml
test_pattern_inverse = 'Ffi'
```

Meanwhile, `--no-match-test=Ffi` works.

**Comment by mattsse** [comment]
thanks for reporting, will check.

**Comment by grandizzy** [comment]
book was updated with proper options, e.g. https://book.getfoundry.sh/reference/config/testing#no-match-test
Please reopen if you see other inconsistencies, thanks!
