### ISSUE TITLE
Decoding array of structs when calling a function with fails

### ISSUE THREAD

**Issue by benesjan** [foundry-rs/foundry#3689]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (903a073 2022-11-15T00:06:12.539932Z)

### What command(s) is the bug in?

cast call 0xB4319947947781FFe91dDf96A32aF2D4693FEf64 "getAssets()([(address,uint256,string)])"

### Operating System

macOS (Apple Silicon)

### Describe the bug

Trying to call a function which has an array of structs as an output fails with `UnrecognisedToken 12:13 [` error. I opened the issue as a reaction to [this conversation](https://t.me/foundry_support/27516) on Telegram.

**Comment by rkrasiuk** [comment]
@benesjan the proper way to specify the array types would be `type[]`
<img width="1532" alt="Screenshot 2022-11-18 at 10 33 28" src="https://user-images.githubusercontent.com/25429261/202657217-c0d78de6-7dc4-441b-bea6-701f79c5c4c6.png">
