### ISSUE TITLE
erroneous overflow/underflow error in local tests

### ISSUE THREAD

**Issue by sprw121** [foundry-rs/foundry#3690]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (903a073 2022-11-14T00:07:04.292547Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

I'm getting a 
```[FAIL. Reason: Arithmetic over/underflow]```
in local testing, were the same function call seems to succeed in a live environment.

The issue is reproduced in this repo: https://github.com/sprw121/overflow-repro

It's the UniswapV3 FullMath library (https://github.com/Uniswap/v3-core/blob/main/contracts/libraries/FullMath.sol), but I copy paste the one I have locally.

I verified that when I simulate a transaction in tenderly, I DO NOT get the same overflow/underflow (it errors for a different but expected reason). There is an internal call that replicates the test exactly in the second call to computeSwapStep I believe. The details for this tenderly simulation are:

Contract: https://polygonscan.com/address/0x45dda9cb7c25131df268515131f647d726f50608
Function: swap()
Address: <pick your own, doesn't matter>
bool: true
int256: 97425036274
uint256: 2153965902990871670710978874800773
bytes: 0x

BlockNumber: 33948395
TxIndex: 33948395
From: <shouldn't matter, use 0x2791bca1f2de4661ed88a30c99a7a9449aa84174>
Gas: 8000000

**Comment by sprw121** [comment]
@mattsse

I opened this ticket based on our conversation in the other issue thread. Should have everything you need to reproduce easily

**Comment by mattsse** [comment]
this is an evm panic for overflow/underflow inside the evm, this is related to the code itself.

**Comment by sprw121** [comment]
I don't believe this is related to the user code, the parameters I pulled here are pulled from the internal call of a transaction that I know succeeds. I believe this maybe an issue with the evm implementation used by forge.

**Comment by sprw121** [comment]
Here is a screenshot from this call succeeding in a different simulation environment:
<img width="1156" alt="Screen Shot 2022-11-15 at 6 48 10 PM" src="https://user-images.githubusercontent.com/4331652/202032386-efa353af-0aff-457e-ba38-dffaa1723e43.png">

**Comment by mattsse** [comment]
it'd be great if you could prepare the necessary commands to run both variants, local and forked.

**Comment by sprw121** [comment]
I have narrowed this down to a version compatibility issue with difference solidity version in both environments, not the EVM implementation

Sorry for the noise generated by this ticket and the other thread.
