### ISSUE TITLE
Add filesystem metadata and walk cheat codes

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#3695]
### Component

Forge

### Describe the feature you would like

A nice to have feature would to get some file metadata info via a cheatcode, this should roughly mirror: https://doc.rust-lang.org/stable/std/fs/struct.Metadata.html

additionally it'd be nice to return a list of files if the path is a directory, this should probably a separate cheatcode, (perhaps `walk`?)

**Comment by wildmolasses** [comment]
> this should roughly mirror

perhaps a method that looks something like `metadata(fileLocation) -> FileMetadata`

where `FileMetadata` is a struct that roughly mirrors the Metadata struct? e.g.

```
struct {
    fileType
    isDir
    isFile
    isSymlink
    len
    permissions
    modified
    accessed
    created
}
```

In that case, which are needed?

- [ ] fileType
- [ ] isDir
- [ ] isFile
- [ ] isSymlink
- [ ] len
- [ ] permissions
- [ ] modified
- [ ] accessed
- [ ] created

**Comment by mattsse** [comment]
great idea, sgtm!

**Comment by mds1** [comment]
Going to close this issue as completed by #3717

> additionally it'd be nice to return a list of files if the path is a directory, this should probably a separate cheatcode, (perhaps walk?)

Haven't seen any requests for this, but we can open a new issue if there is a need. Most use cases for getting file info are likely around JSON input/output files or deploy scripts, so I can't think of a common use case for a `walk` cheat, so figured I'd close for now
