### ISSUE TITLE
Fatal error on `forge update`, `forge remove` also failing

### ISSUE THREAD

**Issue by douglasqian** [foundry-rs/foundry#3696]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (903a073 2022-11-15T00:09:48.47193Z)

### What command(s) is the bug in?

forge update

### Operating System

macOS (Intel)

### Describe the bug

Hi I'm consistently running into issues with `forge update`. Right now it's frustrating because I have do a lot of manual work to remove & reinstall a submodule because `forge remove` isn't working as expected for me either. I could continue with the current way I'm doing things, but I figured I might as well throw up a post as I haven't seen a Github issue about this but there are a couple instances of this in the Telegram chat.

# Problem

```
$ forge update lib/celo-foundry
Error:
Submodule 'lib/celo-foundry' (https://github.com/spiralsprotocol/celo-foundry) registered for path 'lib/celo-foundry'
Cloning into '/Users/dzq/spirals/protocol/lib/celo-foundry'...
fatal: Needed a single revision
Unable to find current origin/master revision in submodule path 'lib/celo-foundry'
```

Most recommendations I could find online tell me to then just remove the submodule and reinstall it. That's when I run into other issues
```
$ forge remove lib/celo-foundry/
Removing  in "/Users/dzq/spirals/protocol/lib/", (url: Some("https://github.com/lib/celo-foundry/"), tag: None)
Error:
fatal: not removing '/Users/dzq/spirals/protocol/lib/' recursively without -r
```

Attempts to include the `-r` flag are unsuccessful as well
```
$ forge remove -r lib/celo-foundry/
error: Found argument '-r' which wasn't expected, or isn't valid in this context

  If you tried to supply `-r` as a value rather than a flag, use `-- -r`

Usage: forge remove [OPTIONS] [DEPENDENCIES]...

For more information try '--help'

$ forge remove lib/celo-foundry -r
error: Found argument '-r' which wasn't expected, or isn't valid in this context

  If you tried to supply `-r` as a value rather than a flag, use `-- -r`

Usage: forge remove [OPTIONS] [DEPENDENCIES]...

For more information try '--help'

$ forge remove lib/celo-foundry -- -r
Removing celo-foundry in "/Users/dzq/spirals/protocol/lib/celo-foundry", (url: Some("https://github.com/lib/celo-foundry"), tag: None)
Error:
-r: No such dependency
```

# Workaround

For anyone running into something similar, my current workaround is to manually delete the package, remove it from `.gitmodules`, commit those changes, and reinstall.

```
$ rm -rf lib/celo-foundry
$ git commit -m "cleaning up lib/celo-foundry to reinstall"
$ forge install spiralsprotocol/celo-foundry
```

# Other
Here's my output from running `git submodule status`
```
$ git submodule status
 f9b813593cf1260bcd56afb10a543c1d5a399b19 lib/celo-foundry (heads/main)
 33d4895fb629aabf12e0f60740367bd03e702bd1 lib/forge-std (v1.1.0)
 df95e563445821988baf9869fde64d86c36be55f lib/lido-dao (v1.1.0-rc.1-399-gdf95e56)
 109778c17c7020618ea4e035efb9f0f9b82d43ca lib/openzeppelin-contracts (v4.4.1-230-g109778c1)
 84e62846eb20d10a40978927fb50bc7f285c7fdd lib/rocketpool (v1.0.0-51-g84e62846)
 478f9d0248cb5fd425c68a47ed8ce939d576b41a lib/solmate (v6-155-g478f9d0)
 4f1cdc5ffb3d7bfccfd8ab195e2697a9a267b24e lib/staked-celo (heads/master)
 efb47d8a84fcb13ceebd3ceb11b126b323bcc05d lib/yearn-vaults (v0.4.3-1)
```
`lib/celo-foundry` is 1 commit behind main

**Comment by zerosnacks** [comment]
Unable to replicate, assuming this has been resolved over time.

Ran the steps:

- forge install https://github.com/spiralsprotocol/celo-foundry
- forge update lib/celo-foundry
- forge remove lib/celo-foundry
