### ISSUE TITLE
erroneous state set when using vm.createFork

### ISSUE THREAD

**Issue by sprw121** [foundry-rs/foundry#3703]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (b65d58d 2022-11-17T00:05:05.963677Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

This repo reproduces the issue: https://github.com/sprw121/create-fork-repro. 

Note the network in question is polygon, not ethereum mainnet.

The state set by createFork here is inconsistent with the logs emitted from the transaction prior to it. I have tried to delete the ~/.foundry/cache folder but this did not help. It looks like the transactions aren't getting replayed properly, as the state is consistent with the head of the block.

The transactions in question are:
0x62d76e970d9c1c1cc71b1b7063a74ffe80244de65b855bd5d3ea36889d6f4034 (the one that sets the state)
0xbed0c8c1b9ff8bf0452979d170c52893bb8954f18a904aa5bcbd0f709be050b9 (the one immediately following)

The prior 2 transactions also change the state of the pools (I care more about this state), and the createFork is also inconsistent on those transactions. I choose these two as it's the first transaction after this sequence where the state does not change.

You can see the logs at https://polygonscan.com/tx/0x62d76e970d9c1c1cc71b1b7063a74ffe80244de65b855bd5d3ea36889d6f4034#eventlog, the relevant ones are Topics 0xc42079f94a6350d7e6235f29174924f928cc2ac818eb64fed8004e115fbcca67.

Unfortunately in this UI, the logs for contracts  0x847b64f9d3a95e977d157866447a5c0a5dfa0ee5 and 0x50eaedb835021e4a108b7290636d62e9765cc6d7 don't decode correctly.

Here are the relevant decoded logs:

```
0x45dda9cb7c25131df268515131f647d726f50608:
Swap (index_topic_1 address sender, index_topic_2 address recipient, int256 amount0, int256 amount1, uint160 sqrtPriceX96, uint128 liquidity, int24 tick)
sender: 0x49facffbd0c7643eb3ad9cdcb44b95d75d93a978
recipient: 0x200800030b0920400c0100b30bb0fd6bab300050
amount0 :
amount1 :19734536289101492745
sqrtPriceX96 :2158492202962238680259690147925313
liquidity :588702194510526627
tick :204261
```

```
0x847b64f9d3a95e977d157866447a5c0a5dfa0ee5:
Swap (index_topic_1 address sender, index_topic_2 address recipient, int256 amount0, int256 amount1, uint160 sqrtPriceX96, uint128 liquidity, int24 tick)
sender: 0x49facffbd0c7643eb3ad9cdcb44b95d75d93a978
recipient: 0x49facffbd0c7643eb3ad9cdcb44b95d75d93a978
amount0 :
amount1 :26567416250
sqrtPriceX96 :1076133273204200901840477866344
liquidity :1221531661829
tick :52178
```

```
0x50eaedb835021e4a108b7290636d62e9765cc6d7
Swap (index_topic_1 address sender, index_topic_2 address recipient, int256 amount0, int256 amount1, uint160 sqrtPriceX96, uint128 liquidity, int24 tick)
sender: 0x49facffbd0c7643eb3ad9cdcb44b95d75d93a978
recipient: 0x49facffbd0c7643eb3ad9cdcb44b95d75d93a978
amount0 : 143802159
amount1 : 
sqrtPriceX96: 29344980527396021373083957193598046
liquidity: 63106417987627857
tick : 256458
```

**Comment by sprw121** [comment]
If you need access to a polygon archive node, I can provide you access to mine temporarily.

**Comment by mattsse** [comment]
> 0x62d76e970d9c1c1cc71b1b7063a74ffe80244de65b855bd5d3ea36889d6f4034 (the one that sets the state)
0xbed0c8c1b9ff8bf0452979d170c52893bb8954f18a904aa5bcbd0f709be050b9 (the one immediately following)

there's 1 tx in between, but unsure if relevant, looks like it isn't

in any case, I debugged this.

while the event includes the price after the swap. the pool's 0x847b64f9d3a95e977d157866447a5c0a5dfa0ee5 state remained unchanged (empty changeset) after executing the 0x62b transaction, in other words, 0x62b appear to not modify the pool's state.

I guess this has something to do with the fact that the slot0 price is only updated conditionally: https://github.com/Uniswap/v3-core/blob/main/contracts/UniswapV3Pool.sol#L750-L753

**Comment by sprw121** [comment]
> > 0x62d76e970d9c1c1cc71b1b7063a74ffe80244de65b855bd5d3ea36889d6f4034 (the one that sets the state)
> > 0xbed0c8c1b9ff8bf0452979d170c52893bb8954f18a904aa5bcbd0f709be050b9 (the one immediately following)
> 
> there's 1 tx in between, but unsure if relevant, looks like it isn't
> 
> in any case, I debugged this.
> 
> while the event includes the price after the swap. the pool's 0x847b64f9d3a95e977d157866447a5c0a5dfa0ee5 state remained unchanged (empty changeset) after executing the 0x62b transaction, in other words, 0x62b appear to not modify the pool's state.
> 
> I guess this has something to do with the fact that the slot0 price is only updated conditionally: https://github.com/Uniswap/v3-core/blob/main/contracts/UniswapV3Pool.sol#L750-L753

If you look carefully, the price is still updated in the other path: https://github.com/Uniswap/v3-core/blob/main/contracts/UniswapV3Pool.sol#L745

**Comment by sprw121** [comment]
@mattsse 

I have added 7 additional tests to my repo, of a different form than the first. Instead of testing expected state, we test that certain state is different than at the head of the block. 

These are the token balances of the pools and calling contract. All of these should have their balance change during the execution of the state setting transaction. You can see this in the logs.

**Comment by mattsse** [comment]
I see, what's weird is that there's no state change for the poll account after executing 0x62d76e970d9c1c1cc71b1b7063a74ffe80244de65b855bd5d3ea36889d6f4034

these are the changed accounts:

    0x49facffbd0c7643eb3ad9cdcb44b95d75d93a978,
    0x54d36a7181421c4a2dfbf962610853364eb13f33,
    0x200800030b0920400c0100b30bb0fd6bab300050,
    0x50eaedb835021e4a108b7290636d62e9765cc6d7,
    0x1bfd67037b42cf73acf2047067bd4f2c47d9bfd6,
    0x0000000000000000000000000000000000000000, 

@rakita maybe I used revm transact + commit wrong, but after executing https://polygonscan.com/tx/0x62d76e970d9c1c1cc71b1b7063a74ffe80244de65b855bd5d3ea36889d6f4034
the account for 0x847b64f9d3a95e977d157866447a5c0a5dfa0ee5 does not appear in the changeset. Which is, weird since 0x847b64f9d3a95e977d157866447a5c0a5dfa0ee5 emits a swap event indicating the state was modified.

I've added a check + dbg here: https://github.com/foundry-rs/foundry/pull/3705

this is how the tx is transacted:

https://github.com/foundry-rs/foundry/blob/93b0f61ec9210567338bd9977252c85b6574f779/evm/src/executor/backend/mod.rs#L1655-L1661

and the State is committed afterward:

https://github.com/foundry-rs/foundry/blob/93b0f61ec9210567338bd9977252c85b6574f779/evm/src/executor/backend/mod.rs#L1684


This is for test `testStatePool1` of the linked repo.

**Comment by sprw121** [comment]
If additional context is any help: Tx 0x62d76e970d9c1c1cc71b1b7063a74ffe80244de65b855bd5d3ea36889d6f4034 requires state set earlier in the block to execute correctly. However, I'm not sure this is relevant since the state is all the same as at the head of block, indicated no transactions on this state are executing correctly.

I've also used these accounts in other tests that use `vm.createFork`, so it's not (solely) related to the accounts involved.

**Comment by rakita** [comment]
@mattsse that is the same pattern used in revm. `transact` then `commit`:
https://github.com/bluealloy/revm/blob/4ef7446f9c26d91702c349977567255624caabcb/crates/revm/src/evm.rs#L46-L47

**Comment by rakita** [comment]
Is this related to the newest revm?
