### ISSUE TITLE
Enable abi-encode to work with structs / tuples

### ISSUE THREAD

**Issue by PatrickAlphaC** [foundry-rs/foundry#3706]
### Component

Cast

### Describe the feature you would like

If I have a function that takes a struct as input:

```javascript
struct animal {
  string name
  uint256 id
}

function getAnimal(animal myAnimal) public {
```

And I want to encode my arguments:

```bash
cast abi-encode "getAnimal((string,uint256))" bobby 123
````

I get an error:
```
Error: 
Failed to parse tokens

Context:
- Invalid data
```

### Additional context

When you get the function signature of a function that takes a struct as a type, the function signature is generated from adding a second set of parenthesis around the parameters. 

This could also just be a documentation update where we add this as an example.

**Comment by mattsse** [comment]
`cast abi-encode "getAnimal((string,uint256))" "(bobby,123)"`

should work.

def need another example for this

**Comment by PatrickAlphaC** [comment]
I'm idiot. Thanks. I'll make a docs PR.
