### ISSUE TITLE
CREATE2 Deployer not present on this chain. [0x4e59b44847b379578588920ca78fbf26c0b4956c]

### ISSUE THREAD

**Issue by puma314** [foundry-rs/foundry#3708]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (b65d58d 2022-11-17T00:11:25.133141Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Intel)

### Describe the bug

I'm trying to deploy a contract on multiple chains using `create2` with `forge script`. On Optimism mainnet, I'm getting an error that the create2 deployer is not found. 

Here is a minimal reproducible example. Run with `forge script Repro.s.sol --private-key ${PRIVATE_KEY} -vvvv --broadcast --tc Deploy2`

```
// forge script Repo.s.sol --private-key ${PRIVATE_KEY} -vvvv --broadcast --tc Deploy2
// CREATE2 Deployer not present on this chain. [0x4e59b44847b379578588920ca78fbf26c0b4956c]
pragma solidity ^0.8.10;

import "forge-std/Script.sol";
import "forge-std/console.sol";

contract SampleContract {
    uint256 public test;

    constructor() {
        test = 1;
    }
}

contract Deploy2 is Script {
    bytes32 mySalt = bytes32(uint256(1));

	function run() external {

        string memory RPC_URL = "https://mainnet.optimism.io";
        uint256 forkId = vm.createFork(RPC_URL);

        vm.startBroadcast();
        SampleContract sample = new SampleContract{salt: mySalt}();
        vm.stopBroadcast();

	}
}
```

**Comment by gakonst** [comment]
It looks like https://optimistic.etherscan.io/address/0x4e59b44847b379578588920ca78fbf26c0b4956c exists. In that case, it makes me think we may have a bug here given that we already deploy the deployer [here](https://github.com/foundry-rs/foundry/blob/15c022681740307380a8179ec9594c50a5483e7c/cli/src/cmd/forge/script/runner.rs#L48C11-L51)?

Maybe bug is somewhere here? https://github.com/foundry-rs/foundry/blob/15c022681740307380a8179ec9594c50a5483e7c/evm/src/executor/inspector/cheatcodes/util.rs#L201-L207

**Comment by mds1** [comment]
@puma314 it looks like you are using `vm.createFork` but never actually selecting the fork. You can use `vm.createSelectFork` or `vm.selectFork` to do that

**Comment by puma314** [comment]
@mds1 My bad, in the repro script I just added `vm.selectFork(forkId);` and it still gives the same error:

```
Traces:
  [1663723] → new Deploy2@0x5b73C5498c1E3b4dbA84de0F1833c4a029d90519
    ├─ [0] VM::rpcUrlStructs() [staticcall]
    │   └─ ← []
    └─ ← 1003 bytes of code

  [59334] Deploy2::run()
    ├─ [0] VM::createFork(https://mainnet.optimism.io)
    │   └─ ← 0
    ├─ [0] VM::selectFork(0)
    │   └─ ← ()
    ├─ [0] VM::startBroadcast()
    │   └─ ← ()
    ├─ [0] → new <Unknown>@0xDD2C1C2383981eDE39A945bF17F27deB2cfBAf2F
    │   └─ ← 0 bytes of code
    └─ ← "CREATE2 Deployer not present on this chain. [0x4e59b44847b379578588920ca78fbf26c0b4956c]"


Gas used: 59334
Error:
CREATE2 Deployer not present on this chain. [0x4e59b44847b379578588920ca78fbf26c0b4956c]
```

**Comment by gakonst** [comment]
Does it work if you do `createSelectFork`?

**Comment by puma314** [comment]
Nope, it still has the same issue.

**Comment by gakonst** [comment]
ACK - thanks!
