### ISSUE TITLE
Place function params on separate lines using `forge fmt`

### ISSUE THREAD

**Issue by Craigson** [foundry-rs/foundry#3713]
### Component

Forge

### Describe the feature you would like

As a stylistic preference, it'd be nice if `forge fmt` provides an option to format all function declarations with params on separate lines, instead of just relying on `line_length` to deal with declarations longer than `X`.

Currently, with `func_attrs_with_params_multiline` set to `true`, this does not achieve the desired effect.

### Current behavior

Before `forge fmt`:
```solidity
    function deploySomething(
        address one,
        address two,
        address three
    ) external returns (address) {
       ...
    }
```

After `forge fmt`:

```solidity
    function deploySomething( address one, address two, address three) external returns (address) {
       ...
    }
```
---

### Desired behavior

Before `forge fmt`:
```solidity
    function deploySomething( address one, address two, address three) external returns (address) {
       ...
    }
```

After `forge fmt`:
```solidity
    function deploySomething(
        address one,
        address two,
        address three
    ) external returns (address) {
       ...
    }
```

Perhaps this could be achieved with a config property like `func_params_multiline = true`

**Comment by gakonst** [comment]
@rkrasiuk ptal

**Comment by rkrasiuk** [comment]
i can see this option being useful for readability. the way we'd do this though would be changing `func_params_multiline` option to have multiple variants to be able to preserve previous behavior

**Comment by Craigson** [comment]
@rkrasiuk makes sense - I'm generally uncertain as to what the expected behaviour for `func_attrs_with_params_multiline` is though, would you be able to clarify?

wrt "If function parameters are multiline then always put the function attributes on separate lines", are "attributes" strictly referring to visibility (ie `internal`, `public` etc) and `view`?

**Comment by rkrasiuk** [comment]
@Craigson oh, shoot. forgive my memory, we've actually removed this option in favor of `func_attrs_with_params_multiline` in #3252. the options are described here https://github.com/foundry-rs/foundry/blob/1a32b528cb6c83b7dfd2bc0a406c1e825e0867f5/config/src/fmt.rs#L74-L84
and triggered only when the function header doesn't fit in one line

**Comment by rkrasiuk** [comment]
@Craigson is the description of this option clear enough?

**Comment by Craigson** [comment]
@rkrasiuk apologies for delayed reply. It is, thank you. I'm going to give this a try and will add an additional comment, otherwise will close the issue. Thanks

**Comment by gaavar** [comment]
Hello! Just following up on this thread as I was looking for an option to enable multi-line function parameters instead of all parameters put together in the same line.

Is there a specific setting/flag I can enable in `foundry.toml`'s `[fmt]` section for achieving this?
