### ISSUE TITLE
[VSCode extension] Start test via keyboard shortcuts / macro

### ISSUE THREAD

**Issue by StErMi** [foundry-rs/foundry#3714]
### Component

Forge

### Describe the feature you would like

Would be possible to have a VS Code extension that allow me to launch tests via a configurable keyboard shortcut?

- One shortcut to launch full test coverage
- One shortcut to launch tests on the opened `.t.sol` file (run only tests inside the opened file)
- One shortcut to launch test on the currently selected test function (the extension should see in which test my cursor is hover/have clicked into before)

bonus be able to configure multiple shortcuts and specify additional parameters to launch the tests with (like the profile / custom env variables)

**Comment by zerosnacks** [comment]
Marking this as `out of scope` for now but hopefully this is something that can be developed once we have a better idea of what Foundry extensions / plugins may look like.

This should be largely achievable through customization / configuration of keybindings in VSCode

https://users.rust-lang.org/t/keybind-to-rerun-or-debug-last-test-in-vscode/96463

This may also be a useful extension to look into: https://simbolik.runtimeverification.com/
