### ISSUE TITLE
bug: cast wallet address is not composable

### ISSUE THREAD

**Issue by OliverNChalk** [foundry-rs/foundry#3721]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (15c0226 2022-11-18T00:11:16.546830339Z)

### What command(s) is the bug in?

cast wallet address

### Operating System

Linux

### Describe the bug

Currently the output of `cast wallet address` is of the format: `Address: 0x12...34`. This means if one wants to convert a pkey to address on the commandline they must currently do:

```bash
ADDRESS=$(cast wallet address $TEST_PRIVATE_KEY | awk '{ print $2 }')
```

Given the user asked for an address, the `Address:` prefix seems extraneous.

**Comment by mattsse** [comment]
this is reasonable, will remove!
