### ISSUE TITLE
cast send fails to parse nested 2d struct arrays

### ISSUE THREAD

**Issue by biogin** [foundry-rs/foundry#3729]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6d94a10 2022-11-04T00:17:05.450788Z)

### What command(s) is the bug in?

cast send

### Operating System

macOS (Apple Silicon)

### Describe the bug

function signature: **create(TempStruct memory temp) external;**

```
struct StructA {
     uint16 cards;
     uint256 amount;
}
struct TempStruct {
   uint256 [] b;
   uint256 [][] c;
   StructA [][] d;
}
```

`cast send 0x123 create((uint256[],uint256[][],(uint16,uint256)[][])) "([],[],[])"`

Fails with this error:

Error: 
Failed to parse tokens

Context:
- Error #0: Hex parsing error: Invalid character '[' at position 0
- Error #1: Invalid character '[' at position 0

`cast send 0x123 create((uint256[],uint256[][],(uint16,uint256)[][])) "('[]','[]','[]')"`
trying to wrap arrays in quotes results in this error

Error: 
Failed to parse tokens

Context:
- Error #0: Hex parsing error: Invalid character '\'' at position 0
- Error #1: Invalid character '\'' at position 0

**Comment by rkrasiuk** [comment]
@biogin you have to wrap function signature in quotes
```sh
$ cast abi-encode 'create((uint256[],uint256[][],(uint16,uint256)[][]))' "([],[],[])"
0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```

**Comment by rkrasiuk** [comment]
closing this issue, feel free to reopen if the issue persists or ask questions in this thread

**Comment by mattsse** [comment]
let's also add this as an example
