### ISSUE TITLE
Add flag to support alternative gas report layout

### ISSUE THREAD

**Issue by 0xClandestine** [foundry-rs/foundry#3734]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (cb925b1 2022-11-21T00:07:24.422793907Z)

### What command(s) is the bug in?

forge test --gas-report

### Operating System

Windows

### Describe the bug

Terminal has to be much larger than before if you want the output to be readable.

<img width="587" alt="image" src="https://user-images.githubusercontent.com/96172957/203176204-b152be9f-5d7c-46b1-ab9f-93279e448642.png">

**Comment by mds1** [comment]
In https://github.com/foundry-rs/foundry/pull/3666 the tables were modified to be markdown compatible. If people prefer the old style we can add that back with a flag, so definitely share your thoughts! 

> Terminal has to be much larger than before if you want the output to be readable.

Do you mean the font seems smaller, or that it's harder to read across a line now? Also seem like a stray `|` is present at the top? cc @sakulstra

**Comment by sakulstra** [comment]
For me there's no stray `|` :thinking: - no good idea where it could come from (i mean there should be a header line with contract name like on the others). Can you provide a reproduction?

I think fond should be same size as before. Only the table layout should have changed.

**Comment by 0xClandestine** [comment]
> For me there's no stray `|` 🤔 - no good idea where it could come from (i mean there should be a header line with contract name like on the others). Can you provide a reproduction?
> 
> I think fond should be same size as before. Only the table layout should have changed.

Trying to reproduce the `|` issue, it appears to gone... I'm thinking it was a local issue.

<img width="555" alt="image" src="https://user-images.githubusercontent.com/96172957/203183293-435c685b-2741-4bff-848a-67cc9cbff9e6.png">

**Comment by 0xClandestine** [comment]
> In #3666 the tables were modified to be markdown compatible. If people prefer the old style we can add that back with a flag, so definitely share your thoughts!
> 
> > Terminal has to be much larger than before if you want the output to be readable.
> 
> Do you mean the font seems smaller, or that it's harder to read across a line now? Also seem like a stray `|` is present at the top? cc @sakulstra

<img width="509" alt="image" src="https://user-images.githubusercontent.com/96172957/203183438-65cd1247-ac6d-4529-97c2-8366bfe5d511.png">

When compared to the old output both look this way when compressing the terminal window too small. However, it seems like the old output allows for a smaller window before breaking. Nonetheless, this is a nit and could definitely be solved by simply including the flag mentioned above.

**Comment by zerosnacks** [comment]
Going to mark this as `not planned`, feel free to re-open if you feel strongly about this
