### ISSUE TITLE
`structLogs` in `debug_traceTransaction` always empty

### ISSUE THREAD

**Issue by michprev** [foundry-rs/foundry#3735]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (251d7d6 2022-11-22T00:08:20.011022291Z)

### Operating System

Linux

### Describe the bug

When running `anvil` (without arguments) I always get empty `structLogs` attribute in `debug_traceTransaction` reponse. Changing arguments of the `anvil` executable or changing parameters of the `debug_traceTransaction` method does not seem to have any effect.

Example request:
```json
{
  "jsonrpc": "2.0",
  "method": "debug_traceTransaction",
  "params": [
    "0x7bb1901eb4fc9986621686ed019a8bef6250dbcc1975db4e80e951deb6bafacf",
    {
      "enableMemory": true,
      "disableStorage": false,
      "disableStack": false
    }
  ],
  "id": 13
}
```

And the response:
```json
{
  "jsonrpc": "2.0",
  "id": 13,
  "result": {
    "failed": false,
    "gas": 82667,
    "returnValue": "00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002",
    "structLogs": []
  }
}
```

**Comment by michprev** [comment]
Sorry, I completely missed this CLI option. Would it be possible to include the `debug_traceTransaction` method into the [Anvil reference](https://book.getfoundry.sh/reference/anvil/) together with a statement that the `--steps-tracing` is required to get `structLogs`?

**Comment by unparalleled-js** [comment]
It would be nice to know how to do this from RPC alone
