### ISSUE TITLE
Forge create + verify uploads 40 files when the actual contract is 20lines with no dependencies

### ISSUE THREAD

**Issue by Elyx0** [foundry-rs/foundry#3739]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (f523139 2022-11-16T00:07:04.576471Z)

### What command(s) is the bug in?

forge create contracts/helpers/SearcherHelperRepayerEcho.sol:SearcherHelperRepayerEcho --rpc-url $ALCHEMY_APIKEY_POLYGON --gas-price 200gwei --private-key $RELAY_TEST_PRIV_KEY  --etherscan-api-key $POLYGONSCAN_APIKEY --verify

### Operating System

macOS (Apple Silicon)

### Describe the bug

My whole contract is :

```
//SPDX-License-Identifier: Unlicensed
pragma solidity ^0.8.16;
contract SearcherHelperRepayerEcho {
    function fastLaneCall(
            address _sender,
            uint256 _bidAmount,
            bytes calldata _searcherCallData
    ) external payable returns (bool, bytes memory) {
        bool success;
        address to = msg.sender;
        assembly {
            // Transfer the ETH and store if it succeeded or not.
            success := call(gas(), to, _bidAmount, 0, 0, 0, 0)
        }

        require(success, "ETH_TRANSFER_FAILED");
        return (true,bytes("ok"));
    }
}
```

Living in a simple file by itself in `contracts/helpers/SearcherHelperRepayerEcho.sol`

Despite that foundry compiles everything and uploads 39 files alongside

https://polygonscan.com/address/0xeA26974363EC1dBc132C99cF9A29273B17254aE3#code

**Comment by Elyx0** [comment]
I deleted `cache` and it didn't change anything

**Comment by mattsse** [comment]
thanks for flagging this.

@rkrasiuk there seems to be something off with what artifacts are attached, any ideas?

**Comment by joshieDo** [comment]
The contract you mention in the PR does not seem to be there though, how can that happen?

**Comment by mattsse** [comment]
could be that the wrong artifact is used which just happens to also pull in the target contract?

any way to replicate this @Elyx0 ?

**Comment by rkrasiuk** [comment]
+1 on repro, it seems like it submitted all of the source files. I've found the target contract under `PFL_AuctionHandler.t.sol`. is it possible that you have contracts with duplicate contract names in the repo? 
https://polygonscan.deth.net/address/0xb47387995e866908b25b49e8bac7e499170461a6#code

**Comment by Elyx0** [comment]
Yes in a previous commit I had duplicate names at some point, then renamed so they're all unique but it still happened

**Comment by grandizzy** [comment]
optimistically closing this as this part was changed since ticket was opened, please reopen if still an issue. thank you!
