### ISSUE TITLE
Fuzzer produces inputs causing the same code to consistently both pass and fail when running `forge test`

### ISSUE THREAD

**Issue by TomAFrench** [foundry-rs/foundry#3740]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (251d7d6 2022-11-22T00:08:20.011022291Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

## Context

At Balancer we need to test that two methods of joining/exiting a pool are equivalent, a "full" method and a "simple" method which handles a join with a single token). To do this we use forge to generate a set of random inputs which represent a "simple" join, build the equivalent inputs for the "full" join and check to make sure that they both result in the same output.

## Bug

We have the test file [`WeightedMath.t.sol`](https://github.com/balancer-labs/balancer-v2-monorepo/blob/forge-bound-assume-fail/pkg/pool-weighted/test/foundry/WeightedMath.t.sol) which contains two tests `testJoinSwap` and `testExitSwap`.

Both functions immediately call into the `prepareValues ` helper function to get a random valid set of weights for the pool to use. `prepareValues` contains the only `vm.assume` call in the entire contract.

https://github.com/balancer-labs/balancer-v2-monorepo/blob/2181edffb71efda789221aca6a50c1b0d251b9da/pkg/pool-weighted/test/foundry/WeightedMath.t.sol#L46

`prepareValues` only receives values from the fuzzer as inputs so we would assume that if one of the tests fails from too many invalid inputs then the other one should as well. However if we run the test suite we'll consistently see `testJoinSwaps` pass and `testExitSwaps` fail. 

```
$ forge test -m "test(Join|Exit)Swap"
[⠆] Compiling...
No files changed, compilation skipped

Running 2 tests for test/foundry/WeightedMath.t.sol:WeightedMathTest
[FAIL. Reason: The `vm.assume` cheatcode rejected too many inputs (60000 allowed)] testExitSwaps(uint256[20],uint256[20],uint256,uint256,uint256,uint256,uint256) (runs: 8566, μ: 52559, ~: 48780)
[PASS] testJoinSwaps(uint256[20],uint256[20],uint256,uint256,uint256,uint256,uint256) (runs: 10000, μ: 62037, ~: 53058)
Test result: FAILED. 1 passed; 1 failed; finished in 11.75s

Failing tests:
Encountered 1 failing test in test/foundry/WeightedMath.t.sol:WeightedMathTest
[FAIL. Reason: The `vm.assume` cheatcode rejected too many inputs (60000 allowed)] testExitSwaps(uint256[20],uint256[20],uint256,uint256,uint256,uint256,uint256) (runs: 8566, μ: 52559, ~: 48780)

Encountered a total of 1 failing tests, 1 tests succeeded
```

## To reproduce:

Note we require node v14.18.x  in order to install the repo. See [here](https://github.com/balancer-labs/balancer-v2-monorepo#pre-requisites) if you run into any issues.

1. `git clone git@github.com:balancer-labs/balancer-v2-monorepo.git`
2. `git checkout forge-bound-assume-fail`
3. run yarn and init submodules
4. `cd pkg/pool-weighted`
5. `forge test -m "test(Join|Exit)Swap"`

**Comment by zerosnacks** [comment]
Marking issue as resolved, looks like this was resolved here: https://github.com/balancer/balancer-v2-monorepo/pull/2448/files
