### ISSUE TITLE
ERROR_PREFIX is too long

### ISSUE THREAD

**Issue by adhusson** [foundry-rs/foundry#3749]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### Describe the bug

Here the prefix is not truncated to 4 bytes, which makes it harder to catch errors originating from inside foundry:

https://github.com/foundry-rs/foundry/blob/e824c93ab4d6d81ff85c13ec95baa4d84b77dc0c/evm/src/error.rs#L12

**Comment by adhusson** [comment]
I don't know if anything relies on there being more than the first 4 bytes, but using all the bytes makes it incompatible with `vm.expectRevert`.

**Comment by mattsse** [comment]
I see.

do you have an example?

I believe it's safe to simply truncate the `ERROR_PREFIX` to 4bytes, same as custom solc errors.

**Comment by adhusson** [comment]
Yes I think we're saying the same thing :)
