### ISSUE TITLE
Tests failing in forge

### ISSUE THREAD

**Issue by dawksh** [foundry-rs/foundry#3751]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (0e1d52d 2022-10-31T00:04:54.74416Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

The code for setUp is as follows:
```
    contract ClaimTest is Test {
    Claim public claim;
    NFTContract public nftContract = new NFTContract();

    function setUp() external {
        nftContract.mint();
        claim = new Claim(address(nftContract));
    }
}
```
The test command with `-vvvv` flag throws this error
<img width="984" alt="Screenshot 2022-11-23 at 11 36 46 PM" src="https://user-images.githubusercontent.com/20741933/203618045-fe876ee0-da78-4a5a-8601-51d2d3140d2f.png">

**Comment by mattsse** [comment]
can you try after running foundryup?
