### ISSUE TITLE
I used the uniswapV2 project in my project, but I encountered compilation problems, what should I do?

### ISSUE THREAD

**Issue by zh19910202** [foundry-rs/foundry#3756]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (226affb 2022-09-27T07:51:19.423801Z)

### What command(s) is the bug in?

forge build

### Operating System

macOS (Apple Silicon)

### Describe the bug

I used the uniswapV2 project in my project, but I encountered compilation problems, what should I do?
![image](https://user-images.githubusercontent.com/34837173/203728714-9baa007a-d93a-40ac-a2f0-cfb8badbb401.png)

**Comment by Genysys** [comment]
You need to use solc versions from the uniswap tests in the contracts you are writing .. and not 0.8.15.  i,.e `0.6.6`. You might be able to overcome this by using interfaces as opposed to the periphery contracts , which would allow you to use a more recent version

**Comment by zh19910202** [comment]
> You need to use solc versions from the uniswap tests in the contracts you are writing .. and not 0.8.15. i,.e `0.6.6`. You might be able to overcome this by using interfaces as opposed to the periphery contracts , which would allow you to use a more recent version


Thanks for your reply, but the current project may need to use a newer solidity version. In the test script, I want to deploy uniswap to test the interaction function with the existing project. This requirement can be realized in the hardhat framework, and the compilation requirement is realized for the solidity version of different source files. Does foundry have similar configurations and functions?

**Comment by rkrasiuk** [comment]
@zh19910202 you can either provide a fork url to run tests against an already deployed contract on mainnet or you can use `getCode` cheatcode to deploy the code manually. see [book reference](https://book.getfoundry.sh/cheatcodes/get-code)

**Comment by rkrasiuk** [comment]
@zh19910202 you can leave any further questions on this thread if u encounter any problems in the process
