### ISSUE TITLE
 replicate the functionality of `vm.prank` for use outside of foundry tool chains

### ISSUE THREAD

**Issue by NakedKoala** [foundry-rs/foundry#3761]
### Component

Forge

### Describe the feature you would like

I would like to replicate the functionality of `vm.prank` for use outside of foundry tools. I would like to use `vm.prank` in my contract deployed onchain  via `eth_call` ( for simulation purpose )

Is there any combination of copy and deploy the correct portion of forge-std source code & make modification to geth client that would make the above possible ? 

My specific usecase is that I need to perform binarySearch where each iteration I need to rely on `vm.prank` to check if certain condition holds. Hundred of iterations of binarySearch has to finish within 1 second or so and within a single `eth_call`

**Comment by mattsse** [comment]
all the cheatcode logic is embedded in the modified evm forge runs, the closest you get to prank when using an actual node is probably `anvil_impersonate`
