### ISSUE TITLE
`anvil` fork: base fee from `eth_feeHistory` is inconsistent with block base fee after executing transaction

### ISSUE THREAD

**Issue by lekhovitsky** [foundry-rs/foundry#3762]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8e7e0be 2022-11-24T00:13:02.397364Z)

### Operating System

macOS (Apple Silicon)

### Describe the bug

Fork the mainnet:
```bash
anvil --fork-url <MAINNET_RPC_URL> --fork-block-number 16000000 --accounts 1
```

Retrieve base fee directly and via `eth_feeHistory` call:
```bash
cast block-number # 16000000
cast basefee # 11130414489
cast rpc eth_feeHistory '[1, "latest", []]' --raw # {"baseFeePerGas":["0x2976ca599","0x2ad7f734b"], ...} 
cast to-base 0x2976ca599 10 # 11130414489
```
We see that they are consistent now.

Now, let's execute arbitrary transaction:
```bash
cast send 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266 --value 1 \
    --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
```

Let's check base fees again:
```bash
cast block-number # 16000001
cast basefee # 11500745547
cast rpc eth_feeHistory '[1, "latest", []]' --raw # {"baseFeePerGas":["0x257ee3ab8","0x20d0b53dc"], ...}
cast to-base 0x257ee3ab8 10 # 10065164984
```

Numbers are no longer consistent: output from `basefee` command is exactly the base fee of mainnet block [`16000001`](https://etherscan.io/block/16000001), while output from `eth_feeHistory` seems to be the actual result of base fee calculation for a new block containing only a single transaction that we sent.

The unfortunate consequence is that if gas price oracle relies on `eth_feeHistory`, we might send underpriced transactions (which happened to me).

**Comment by mattsse** [comment]
perhaps there's a off-by-one error since `10065164984` is `cast basefee --block pending`?

Tbh I'm having a hard time to make sense of the `eth_feeHistory` [docs](https://ethereum.github.io/execution-apis/api-documentation/)

> BASEFEEPERGAS: An array of block base costs for each gas. This includes returning the next block after the latest block in the range, as this value can be derived from the latest block.

**Comment by lekhovitsky** [comment]
In `eth_feeHistory`, `baseFeePerGas` is an array of base fees for each block in requested range (determined by `blockCount` and `newestBlock` params) as well as of the next block after `newestBlock`, which is a function of `baseFee` and `gasUsedRatio` of the latter:

$$
\text{base fee}_{n+1} = \text{base fee}_n \left( 1 + 0.125  \cdot \frac{\text{ratio}_n - 0.5}{0.5} \right)
$$

I believe `cast basefee` is completely correct:
* in the block 16000001 base fee is known to be `11500745547`
* in the `pending` block, by the formula above with $\text{base fee}_n$ equal to `11500745547` and $\text{ratio}_n$ equal to `0.0007` (21K gas of our transfer tx / 30M block gas limit), it is precisely `10065164984`
 
So must be something with `eth_feeHistory`.

**Comment by lekhovitsky** [comment]
Not sure if helpful, but I've just discovered one more thing it does not as expected:

(run Anvil as before)

```bash
# call eth_feeHistory for 3 blocks -- notice 4 values in baseFeePerGas
cast rpc eth_feeHistory '[3, "latest", []]' --raw # {"baseFeePerGas":["0x2c93e3533","0x2a1e15147","0x2976ca599","0x2ad7f734b"], ...}

# execute a tx
cast send 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266 --value 1 \
    --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80

# call eth_feeHistory for 3 blocks again -- this time, only 2 values
cast rpc eth_feeHistory '[3, "latest", []]' --raw # {"baseFeePerGas":["0x257ee3ab8","0x20d0b53dc"], ...}

**Comment by lekhovitsky** [comment]
Examined how `eth_feeHistory` is [implemented](https://github.com/foundry-rs/foundry/blob/9bd079964cd0bad0ac52be89ab1587218d86ade1/anvil/src/eth/api.rs#L1056) in Anvil.

When forking, `fee_history` output is either the result of fork's `eth_feeHistory` if `newestBlock <= forkBlock`, or the result of computation based on fee history cache (which in the example above is made of a single tx) otherwise.

This behaviour breaks if `oldestBlock <= forkBlock <= newestBlock`, and in this case an ideal behavior would be to "concat" the results of fork's fee history for blocks `oldestBlock..forkBlock` and cache-based calculations for the rest.

**Comment by mattsse** [comment]
> This behaviour breaks if oldestBlock <= forkBlock <= newestBlock, and in this case an ideal behavior would be to "concat" the results of fork's fee history for blocks oldestBlock..forkBlock and cache-based calculations for the rest.

this sounds right, I guess this could be fixed by requesting the missing entries.

> When forking, fee_history output is either the result of fork's eth_feeHistory if newestBlock <= forkBlock, or the result of computation based on fee history cache (which in the example above is made of a single tx) otherwise.

this is how it's implemented. But what's wrong?

**Comment by lekhovitsky** [comment]
> But what's wrong?

Pre-fork, everything is correct. Post-fork, the problem is that the function considers _only_ fee history cache, which is formed purely from transactions sent to the Anvil node, and is thus unaware of any fee history data from the forked chain. So when the requested range happens to contain both pre-fork and post-fork blocks, the result is wrong simply by not having all the input data needed for correct computation.
