### ISSUE TITLE
Contract verification fails on Goerli but passes just fine on Sepolia

### ISSUE THREAD

**Issue by 0xFloop** [foundry-rs/foundry#3769]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6871421 2022-11-25T00:15:01.855568Z)

### Operating System

macOS (Apple Silicon)

### Describe the bug

My contract verifications only fail no matter if I use forge create, forge verify-contract, or a deploying script with --verify. The same exact bytecode in artifacts as etherscan so I'm very confused. Same code and commands work just fine for verifying on Sepolia. I'm wondering if its an issue with Etherscans Goerli verification api. Here is a repo with contract that fails to verify on Goerli but verifies just fine on Sepolia [HERE](https://github.com/0xFloop/failed_verification_repo).

**Comment by gakonst** [comment]
@mattsse @joshieDo ptal next week, contract verification will never stop haunting us

**Comment by mattsse** [comment]
they should be the same.

what command did you run?

will try to debug

**Comment by joshieDo** [comment]
Can you provide more context? The command and the error?

I just tried both from your repo... and both worked. 

It's worth notice that your `foundry.toml`  does not have a sepolia declaration

**Comment by 0xFloop** [comment]
This doesn't make much sense but the Goerli verification is working just fine this morning. Maybe an issue with the etherscan goerli verification api last night? Anyways, I appreciate the help 👍🏼

**Comment by gakonst** [comment]
@0xFloop closing, but please share what command you ran so we can investigate if it is a real issue on our side.

**Comment by 0xFloop** [comment]
yep, the deployment script can be seen within the repo, that was being called with command 
```forge script script/Deploy.s.sol:MyScript --rpc-url $ALCHEMY_TESTNET_RPC_URL --broadcast --verify```

the create command I was running was 
```forge create src/Counter.sol:Counter  --rpc-url $ALCHEMY_TESTNET_RPC_URL --private-key $TEST_PRIVATE_KEY --etherscan-api-key $ETHERSCAN_API_KEY --verify```

and the verify-contract command i was running was 
```forge verify-contract 0x2166f90CC3608620c822BA8B23b32e48C3776846 Counter  --chain goerli --watch```
