### ISSUE TITLE
Clarify dbg! usage

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#3770]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### Describe the bug

@rkrasiuk what's going on here?

https://github.com/foundry-rs/foundry/blob/9c8bfd967e8918eeac836b4ca1915417b2126724/fmt/src/solang_ext/ast_eq.rs#L20-L24

I don't understand what these dbg! do, can we also get rid of the unsafe?

**Comment by rkrasiuk** [comment]
@mattsse i assume, this was a leftover from debugging the ast_eq for formatter tests, removed it in #3776
