### ISSUE TITLE
Deploy CREATE2 deployer on canto chain (7700)

### ISSUE THREAD

**Issue by akshatcx** [foundry-rs/foundry#3772]
### Component

Forge

### Describe the feature you would like

In order to deploy permit2 on the same address (0x0000000052BE00bA3a005edbE83a0fB9aaDB964C) as other chains, we need to have the CREATE2 deployer contract (0x4e59b44847b379578588920ca78fbf26c0b4956c) deployed on canto deterministically. 

Hence could you guys please sign a transaction to deploy this on canto network which we can execute ourselves (https://chainlist.org/chain/7700) or maybe deploy it on the chain and let us know. Would be really helpful

(coming from the error: CREATE2 Deployer not present on this chain.)

**Comment by mattsse** [comment]
I believe by default some CREATE2 is deployed, right @joshieDo 

But you can also use the etch cheatcode to set the code of an arbitrary account

**Comment by joshieDo** [comment]
https://github.com/Arachnid/deterministic-deployment-proxy#latest-outputs

You can follow the instructions here to deploy it

**Comment by akshatcx** [comment]
Hey @joshieDo , thanks for pointing me to it. But it seems like it is not possible to deploy CREATE2 using this because CANTO chain does not support pre EIP-155 transactions :(

error:
```
only replay-protected (EIP-155) transactions allowed over RPC
```

**Comment by akshatcx** [comment]
The transaction mentioned there has to be signed with the canto chain id 7700 as well (what EIP-155 talks about)

**Comment by akshatcx** [comment]
I have deployed another similar proxy to create2 here: https://evm.explorer.canto.io/address/0x914d7Fec6aaC8cd542e72Bca78B30650d45643d7

Is there a way to use this contract instead of the default create2 address (0x4e59b44847b379578588920ca78fbf26c0b4956c)

**Comment by akshatcx** [comment]
@mattsse @mds1

**Comment by akshatcx** [comment]
sounds good, closing in favour of #2638

**Comment by pcaversaccio** [comment]
FYI you can use my CREATE2 deployer which is deployed on Canto prod & testnet.  

- prod deployment https://evm.explorer.canto.io/address/0x13b0D85CcB8bf860b6b79AF3029fCA081AE9beF2
- https://github.com/pcaversaccio/create2deployer
