### ISSUE TITLE
Cannot build Foundry from source on Windows 10 - failed to update submodule `testdata/lib/forge-std`

### ISSUE THREAD

**Issue by Skelectric** [foundry-rs/foundry#3773]
### Component

Other (please describe)

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What command(s) is the bug in?

cargo install --git https://github.com/foundry-rs/foundry foundry-cli anvil --bins --locked

### Operating System

Windows

### Describe the bug

Running the  command to build Foundry from source results in the 'no URL configured for submodule' error

input:

`cargo install --git https://github.com/foundry-rs/foundry foundry-cli anvil --bins --locked`

output:

```
(dev) PS C:\Users\Skelectric> cargo install --git https://github.com/foundry-rs/foundry foundry-cli anvil --bins --locked
    Updating git repository `https://github.com/foundry-rs/foundry`
error: failed to update submodule `testdata/lib/forge-std`

Caused by:
  no URL configured for submodule 'testdata/lib/forge-std'; class=Submodule (17)
    Updating git repository `https://github.com/foundry-rs/foundry`
error: failed to update submodule `testdata/lib/forge-std`

Caused by:
  no URL configured for submodule 'testdata/lib/forge-std'; class=Submodule (17)
     Summary Failed to install foundry-cli, anvil (see error(s) above).
error: some crates failed to install
```

**Comment by mattsse** [comment]
Closed by #3774
