### ISSUE TITLE
fmt line length might wrap import lines

### ISSUE THREAD

**Issue by elmariachi111** [foundry-rs/foundry#3777]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

0.2.0

### What command(s) is the bug in?

forge fmt

### Operating System

Linux

### Describe the bug

When you set a short max line length, the formatter might wrap wide import statements to two lines, e.g.

```
import { CountersUpgradeable } from
    "@openzeppelin/contracts-upgradeable/utils/CountersUpgradeable.sol";
```
if you're using a hardhat setup at the same time, its preprocessor step ([as outlined here](https://book.getfoundry.sh/config/hardhat#instructions)) cannot parse those lines correctly anymore, so hardhat can't resolve libraries anymore.

I'd suggest to have another formatter option / feature that keeps lines together that being with import regardless of the line length and desired max width option.

**Comment by rkrasiuk** [comment]
@gakonst @mattsse do you think it's worth amending the docs? can't make peace with formatter being governed by project settings

**Comment by gakonst** [comment]
Hm this might be a widespread thing and as much as I don't want us to introduce churn, I wonder about:
> I'd suggest to have another formatter option / feature that keeps lines together that being with import regardless of the line length and desired max width option.

How much work do we think this is? Is it a lot of code smell to impl?

**Comment by rkrasiuk** [comment]
@gakonst it wouldn't be much, but we also have `// forgefmt: disable-next-line` for such cases. i'd much rather add this to the docs and recommend using disable rather than auto detect hardhat plugin or introduce a new option. wdyt?

**Comment by gakonst** [comment]
@elmariachi111 WDYT about the above solution? You can disable fmt for these imports in-line, and we can make that clear in the docs. (Feels a bit anti-patterny to disable fmt just for imports always.)

**Comment by mds1** [comment]
Per https://github.com/foundry-rs/book/issues/773, @fvictorio is working on updates so that the hardhat-preprocessor approach is deprecated so this should no longer be an issue. Additionally, you can use the `// forgefmt: disable-*` directives as mentioned
