### ISSUE TITLE
Dropped transactions lead to un-resumable scripts

### ISSUE THREAD

**Issue by prestwich** [foundry-rs/foundry#3780]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (251d7d6 2022-11-21T20:12:54.748601Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### High Level

`forge script` enters an un-resumable state if broadcast transactions are dropped from the mempool

#### Details

Resuming a deployment performs the following steps:
- Load the sequence from the file
- Retrieve and store receipts for any pending transactions found in the `pending` array of the sequence
- Broadcast any sequence transactions for which receipts are not known

See code here:
https://github.com/foundry-rs/foundry/blob/master/cli/src/cmd/forge/script/cmd.rs#L237-L263

When waiting for a transaction, if it has been dropped from the mempool, an error will be generated in [`wait_for_receipts`](https://github.com/foundry-rs/foundry/blob/master/cli/src/cmd/forge/script/receipts.rs#L59-L61). This error will prevent progress to the broadcast step

If a transaction has been dropped from the mempool, then `wait_for_receipts` can never succesfully execute, and the dropped transaction can never be re-broadcast.

### Solution

Instead of invoking `wait_for_receipts` via `wait_for_pending`,a resume should invoke a new function `resume_check_pending` that does the following:

- Attempts to retrieve the pending receipt
- If unsuccessful, attempts to retrieve the tx from mempool
- If unsuccessful, deletes the tx hash from pending so that it will be rebroadcast

This function should NOT use the `PendingTransaction` struct, as that will be less reliable

**Comment by rkrasiuk** [comment]
@prestwich can we close this issue now that #3781 has been merged?

**Comment by prestwich** [comment]
yes
