### ISSUE TITLE
EvmError: OutOfGas no possibility to increase

### ISSUE THREAD

**Issue by vapopov** [foundry-rs/foundry#3796]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6174975 2022-11-30T00:10:59.068726784Z)

### What command(s) is the bug in?

forge script scripts/GMXHistoricalJSON.s.sol

### Operating System

Linux

### Describe the bug

I've written a script which is collecting the historical data from the avalanche blockchain by using fork block and roll block. In my specific case script fails with error of running out of gas for tests (but this is a script).

I've tried to increase the gas value in config but seems like the value in example is maximum value
```
gas_limit = 9223372036854775807
```
So if I try to increase this value, foundry fails to start because of error in config.

**Comment by mattsse** [comment]
can you try: 

```
gas_limit = "18446744073709551615"
```

instead? this is u64::Max as string, see docs for explainer, there's a type limitation in toml library.

**Comment by vapopov** [comment]
@mattsse this one works, thanks!

but why I also opened this issue, this is the question don't you think that for the scripts we should have separate value maybe, and ability to ignore gas at all, in my case I do `vm.rollFork` iteratively, so I do fetch historical data and I don't really need have restriction of the gas, since it will never be run on the some network, only on forks

**Comment by mattsse** [comment]
yeh I think would make sense, mind referencing this in a separate issue?

we probably can add away to fake gas I think
