### ISSUE TITLE
vm.recordLogs does not work with vm.transact

### ISSUE THREAD

**Issue by jameswenzel** [foundry-rs/foundry#3797]
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6174975 2022-11-30T00:15:57.020771Z)

### Describe the bug

This might be more of a feature request than a bug, since I'm not sure how `vm.transact` is implemented under-the-hood. 

Since the premise of `vm.transact` is to replay a transaction onto the fork, I'd expect it to have the same effects as a normal Foundry call - but it seems that ultimately only chain state is updated, without any logs (perhaps even external calls?) being registered by the VM. 

Here is a failing example test, which forks block `16071016`, and replays a transaction from the following block, `16071017`, and [produced 4 logs](https://etherscan.io/tx/0x431173a87438556bfdc0aa3441cdeb006bc238a3cbed351afd75aab9a4962435#eventlog)

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.17;

import {Test, Vm} from "forge-std/Test.sol";

contract TransactionTest is Test {
    function testTransactionLogs() public {
        vm.createSelectFork(stdChains["mainnet"].rpcUrl, 16071016);
        vm.recordLogs();
        vm.transact(0x431173a87438556bfdc0aa3441cdeb006bc238a3cbed351afd75aab9a4962435);
        Vm.Log[] memory logs = vm.getRecordedLogs();
        assertEq(logs.length, 4, "Did not record the correct number of logs");
    }
}
```

I suspect this may be because it's easier to just update only the state from a transaction's side-effects than it is to replay the entire transaction, which might be dependent on previous transactions.

Regardless, it would be very useful if Forge scripts could capture and export the logs of a specific transaction.  I know similar functionality was being explored for cast in #2542 - it would be great to have them accessible in a configurable Forge script that can then export them.

**Comment by mattsse** [comment]
ah I think I know what's happening here.

the logs emitted during `vm.transact` are probably not added to the test's log storage.

should be an easy fix.

**Comment by AdithyaNarayan** [comment]
this one up for grabs? i'd like to shoot my shot
