### ISSUE TITLE
Cannot download Foundry (beginner)

### ISSUE THREAD

**Issue by markusmak** [foundry-rs/foundry#3798]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### Describe the bug

Beginner to programming and foundary general. Does anyone know how to change the permission here?

<img width="567" alt="Screenshot 2022-11-30 at 2 42 27 PM" src="https://user-images.githubusercontent.com/54108129/204893118-2e2db27d-a7f8-45a9-a7ca-106590759b47.png">

**Comment by rkrasiuk** [comment]
hey @markusmak 👋 . have you tried checking file permissions on `~/.zshrc`? you can do it with `ls - l` command. if `rw` flag is not there, run `chmod +rw ~/.zshrc`

**Comment by onbjerg** [comment]
It's owned by root, please make it owned by you: `chown $USER:$USER .zshrc` (substitute `$USER` for your username)
