### ISSUE TITLE
Forge script fails with empty setup function

### ISSUE THREAD

**Issue by sinasab** [foundry-rs/foundry#3799]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a854a0e 2022-12-01T00:08:08.262332Z)

### What command(s) is the bug in?

forge script CounterScript

### Operating System

macOS (Apple Silicon)

### Describe the bug

<img width="624" alt="image" src="https://user-images.githubusercontent.com/3280221/204987194-f219c649-caf4-4d67-9f34-24514aaf231c.png">

Running a simple forge script with an empty setup script fails with the above error.

Minimal repro repository: https://github.com/sinasab/forge-script-setup-bug
This repo was set up via `forge init` and some minimal modifications to `Counter.s.sol`.

**Comment by joshieDo** [comment]
Hm, seems something to do with the [new] default sender.

 If it's a blocker just add `--sender $ADDRESS` or `--private-key $PRIV` and at least in my attempts it worked out.
