### ISSUE TITLE
Keep contract folder structure in the generated ABIs.

### ISSUE THREAD

**Issue by gagiuntoli** [foundry-rs/foundry#3800]
### Component

Forge

### Describe the feature you would like

I have created [this small example](https://github.com/gagiuntoli/forge-build-abi-structureforge-build-abi-structure).

Basically in the `src/` folder I have:

```bash
$ tree src/
src/
├── v1
│   └── counters
│       └── CounterV1.sol
└── v2
    └── counters
        └── CounterV2.sol
```
I would like to have the same folder structure on the folder where the ABIs are stored (`out/`). Currently, when I execute `forge build` I obtain:
```bash
$ tree out/
out/
├── Common.sol
│   └── CommonBase.json
├── Components.sol
│   └── Components.json
├── console2.sol
│   └── console2.json
├── console.sol
│   └── console.json
├── Counter.s.sol
│   └── CounterScript.json
├── Counter.t.sol
│   └── CounterTest.json
├── CounterV1.sol
│   └── CounterV1.json
├── CounterV2.sol
│   └── CounterV2.json
...
```
The folders `v1` & `v2` blew away.

**Comment by clauBv23** [comment]
This feature will be really helpful.
 In general, following the same folder structure instead of storing all the artifacts together would be fantastic.

Currently, it's quite challenging to use wagmi with the existing `out` folder structure.

**Comment by grandizzy** [comment]
same as https://github.com/foundry-rs/foundry/issues/1573, going to close it as dupe and track it there. thank you
