### ISSUE TITLE
Regression after commit e471f102b07f6460c9fdf18f018a7e08e85f33f0

### ISSUE THREAD

**Issue by kubmichael** [foundry-rs/foundry#3803]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### Operating System

macOS (Apple Silicon)

### Describe the bug

Hi, 

it is look like that following commit introduced regression [https://github.com/foundry-rs/foundry/commit/e471f102b07f6460c9fdf18f018a7e08e85f33f0](471f102b07f6460c9fdf18f018a7e08e85f33f0)
After using anvil with it we started to receive following error:

> Transaction hash mismatch from Provider.sendTransaction. (expectedHash="0xf09c32925da0a7332d1aa964094f921ffadb66236af179c67b6f2565d4e83b71", returnedHash="0x2ae43d6577b7431d0796b2589886ff98e1b8c5de7f46d046945f15f718b91cb2", code=UNKNOWN_ERROR, version=providers/5.7.2)

All our transactions are impersonated

It is look like, that MinedTransaction and TypedTransaction has different hashes

**Comment by mattsse** [comment]
> It is look like, that MinedTransaction and TypedTransaction has different hashes

can you expand on that?

what hashes differ, and do you get them?

**Comment by kubmichael** [comment]
> > It is look like, that MinedTransaction and TypedTransaction has different hashes
> 
> can you expand on that?
> 
> what hashes differ, and do you get them?
inside do_mine_block, I just added some code, in order to print transactions that was mined, for debug purpose:
``` 
if let Some(hash) = storage.hashes.get(&n) {
    if let Some(block) = storage.blocks.get(hash) {
       for tx in block.clone().transactions {
                 let _ = storage.transactions.get(&tx.hash());
       }
     }
  }
```
and we never got transactions from storage.transactions()

**Comment by mattsse** [comment]
Sorry, I can't follow.

I still don't understand your issue tbh.

can you link me to the relevant code, please?

> and we never got transactions from storage.transactions()

I would need more context here, sorry

**Comment by mattsse** [comment]
so this is related to ethers.js?

does `await txn.wait()` compute the hash of the transaction under the hood?

or rather what are the input values for this check

```
(expectedHash="0xf09c32925da0a7332d1aa964094f921ffadb66236af179c67b6f2565d4e83b71", returnedHash="0x2ae43d6577b7431d0796b2589886ff98e1b8c5de7f46d046945f15f718b91cb2",
```

**Comment by yhayun** [comment]
This is my high-level assumption, didn't test it:
We've changed how impersonated PendingTransactions hashes are calculated but didn't extend this change to MinedTransactions, so now they're calculated differently, and it causes a mismatch.

Not 100% sure of this cause I didn't deep dive, but it makes sense to me

**Comment by dbeal-eth** [comment]
> so this is related to ethers.js?
> 
> does `await txn.wait()` compute the hash of the transaction under the hood?
> 
> or rather what are the input values for this check
> 
> ```
> (expectedHash="0xf09c32925da0a7332d1aa964094f921ffadb66236af179c67b6f2565d4e83b71", returnedHash="0x2ae43d6577b7431d0796b2589886ff98e1b8c5de7f46d046945f15f718b91cb2",
> ```

this issue does not occur on prior versions of anvil or on any other jsonrpc api like hardhat with the same script. therefore, it is a regression with anvil. @yhayun is probably on the right track.

**Comment by mattsse** [comment]
> change to MinedTransactions

gotcha

checking

**Comment by mattsse** [comment]
> > so this is related to ethers.js?
> > does `await txn.wait()` compute the hash of the transaction under the hood?
> > or rather what are the input values for this check
> > ```
> > (expectedHash="0xf09c32925da0a7332d1aa964094f921ffadb66236af179c67b6f2565d4e83b71", returnedHash="0x2ae43d6577b7431d0796b2589886ff98e1b8c5de7f46d046945f15f718b91cb2",
> > ```
> 
> this issue does not occur on prior versions of anvil or on any other jsonrpc api like hardhat with the same script. therefore, it is a regression with anvil. @yhayun is probably on the right track.

right, but it would be helpful to know where these assert inputs are coming from

**Comment by mattsse** [comment]
hmm, this makes me believe that appending the from address to the hash was a bad change because now the tx can't be easily reproduced.

maybe the better change would have been to use a new random key per impersonated account instead of using a const signature.

**Comment by mattsse** [comment]
so what we probably want is

`Map<ImpersonatedAccount, RandomPk>` so we have unique signatures per impersonated account.

wdyt @yhayun

**Comment by noahlitvin** [comment]
Hi, this regression is breaking our CI pipeline. Earlier today, we were able to pin to version `nightly-61749757a29a3c4a3a3790e718f303d95efeb509` but it doesn't seem to be available now. Would it be possible to make this available again while you get this resolved? Thank you!

cc @mjlescano

**Comment by yhayun** [comment]
> so what we probably want is
> 
> `Map<ImpersonatedAccount, RandomPk>` so we have a unique signature per impersonated account.
> 
> wdyt @yhayun

@mattsse 
Yeah, that could work as long as we propagate it to all the different requests/transaction types.

**Comment by yhayun** [comment]
@mattsse 
Another option is to change how we create hashes everywhere - only use the 'from' value and remove the usage of the signature. When impersonated, we would get the 'from' from the request, and on all the regular flows, we would derive the 'from' value from the signature.
