### ISSUE TITLE
Strange block.timestamp / warp interactions with via-ir

### ISSUE THREAD

**Issue by marktoda** [foundry-rs/foundry#3806]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (f6361e6 2022-12-01T15:11:38.140433224Z) 

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

Block.timestamp and warp seem to have very strange behavior under via-ir. Minimal repro:

foundry.toml:
- via_ir = true

```
    function testWarp() public {
        console2.log("timestamp first", block.timestamp);
        vm.warp(block.timestamp + 100);
        console2.log("timestamp, timestamp + 100", block.timestamp, block.timestamp + 100);
    }
```

Expected output:
```
timestamp first: 1
timestamp, timestamp + 100: 101 201
```

Actual output:
```
timestamp first: 1
timestamp, timestamp + 100: 101 101
```

Super strange - I have no idea why the addition would not apply to block.timestamp

Another repro showing that stack variables get clobbered
```
    function testWarp() public {
        uint256 timestamp = block.timestamp;
        console2.log("timestamp before", timestamp);
        vm.warp(timestamp + 50);
        console2.log("timestamp after", timestamp);
    }
```

Expected output:
```
timestamp before 1
timestamp after 1
```

Actual output:
```
timestamp before 1
timestamp after 51
```

**Comment by marktoda** [comment]
oh also note that setting via_ir = false fixes the issue. Removing the warp also fixes the issue

**Comment by marktoda** [comment]
https://github.com/foundry-rs/foundry/issues/1373

seems so compiler is seeing my block.timestamp + 100 pre-warp and autoresolving my block.timestamp + 100 post-warp to the same value

**Comment by marktoda** [comment]
Can close i suppose but this is super strange behavior :(

**Comment by marktoda** [comment]
Any way we could remove whatever optimizerStep that does this clobbering for test/ contracts?

**Comment by paulrberg** [comment]
@marktoda did you find any workaround, after all?

I just enabled `--via-ir` and bumped into the same problem as you did here .. it looks like there is now an open issue in the Solidity repo (https://github.com/ethereum/solidity/issues/12963#issuecomment-1110070343) to track this strange behavior of Solidity, but what do we do in the meantime? I would prefer not to disable `--via-ir`.

Did you, by chance, override the `optimizerSteps` in your Foundry config? I noticed that if I set it to either `` or `dhfoDgvulfnTUtnIf`, I get the strange behavior reported by you. But if I remove this configuration completely, the `warp` cheatcode works as expected.

**Comment by marktoda** [comment]
Hey @paulrberg !

Honestly my solution was just to redesign the test suite to get around this issue. In our case, changing some constants around to re-evaluate block.timestamp in different expressions allowed the value to change properly, i.e.
```
uint256 startTimestamp = block.timestamp;
... startTimestamp + 10 // 11
uint256 newTimestamp = startTimestamp + 100); // 101
warp(newTimestamp)
... startTimestamp + 50  // 51
```

I did tinker around with optimizerSteps, but couldn't isolate the correct step easily and gave up to do the hacky way out :D

**Comment by paulrberg** [comment]
Thanks for the tips, @marktoda. I will probably end up doing the same, i.e. introduce a few new constants to go around this whacky behavior of `warp`.
