### ISSUE TITLE
Impersonated transactions from = address(0)

### ISSUE THREAD

**Issue by JSRossiter** [foundry-rs/foundry#3808]
### Component

Anvil

### Describe the feature you would like

When sending transactions with an impersonated account getTransaction returns from address as 0x000... I know this is usually derived from the signature, which we can't have, but hardhat does set from (while leaving vrs=0) and it is useful to have.

Maybe related to work in https://github.com/foundry-rs/foundry/issues/3803

**Comment by mattsse** [comment]
> I know this is usually derived from the signature, which we can't have, but hardhat does set from (while leaving vrs=0) and it is useful to have.

set from to what?

**Comment by JSRossiter** [comment]
to the impersonated account address

**Comment by mattsse** [comment]
> but hardhat does set from

sorry, not following yet. There's no address field in a transaction so I don't understand this yet. Do they include an additional field?

**Comment by JSRossiter** [comment]
Psuedo code example:
```
anvil_impersonateAccount(0x12345...)
res = eth_sendTransaction({
  from: 0x12345...
}) // returns transaction hash
transaction = eth_getTransactionByHash(res.result)
```

When I'm using hardhat eth_getTransactionByHash returns an object with `from` set correctly, when using anvil `from` is set to the zero address. I'm using ethers.js, but don't think that's changing behaviour here as from is included in the RPC spec https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_gettransactionbyhash.

**Comment by mattsse** [comment]
ah gotcha, there are multiple transactions types so this is always confusing...

yeah I now think, #3775 was on the right, but what was missing was storing the address separately.

because currently we only store the signed transaction, so the receipt transaction's from field is set to the recovered address, which obviously does not work for impersonated addresses.

## TODO

- [ ] Store Signed tx + address
- [ ] reapply changes in #3775

**Comment by mattsse** [comment]
@JSRossiter any chance this only happens for transactions that are pending (not minded yet)?

**Comment by JSRossiter** [comment]
yes, I was only working with pending transactions

**Comment by mattsse** [comment]
great, then #3813 should fix it

**Comment by mattsse** [comment]
this bug is also related to #3803
