### ISSUE TITLE
Failed to extract foundry config

### ISSUE THREAD

**Issue by bitcoinmeetups** [foundry-rs/foundry#3816]
Hi,

I'm BM, a very nice and polite guy.

This input gives an error message:

forge create --rpc-url https://polygon-mainnet.g.alchemy.com/v2/NDF-tLz0B4Mxxxxxxxxxxxxxx --legacy --private-key af180013952262434794xxxxxxxxxxsrc/GAT.sol:GAT

Error:
failed to extract foundry config:
foundry config error: unexpected character found: `(` at line 1 column 1

OS: Raspberry Pi OS 64-bit
Device: Raspberry Pi 4

**Comment by mattsse** [comment]
What's line 1 in your foundry.toml?

**Comment by bitcoinmeetups** [comment]
(function () {
        'use strict';

        /** Highest positive signed 32-bit float value */

        const maxInt = 2147483647; // aka. 0x7FFFFFFF or 2^31-1

        /** Bootstring parameters */

**Comment by mattsse** [comment]
this is not toml.

unsure why you have what seems to be js in your toml file?

**Comment by bitcoinmeetups** [comment]
This might be caused by a previous system fault. After recovery I noticed that some files were garbled or mixed up.

I created a new directory, made an init and copied the foundry.toml file from there to the main directory. It seems like I can compile again.

Thanks and closed.

-------- Original Message --------
