### ISSUE TITLE
Support loading mnemonic + HD path as encrypted keystore

### ISSUE THREAD

**Issue by GopherJ** [foundry-rs/foundry#3818]
### Component

Cast

### Describe the feature you would like

Currently cast only support generating random keypair, it'll be great to support creating encrypted keystore using existing mnemonic + HD path.

Metamask didn't support exporting as encrypted json. That's why I'm seeking tools to export without re-inventing wheels

**Comment by PatrickAlphaC** [comment]
An API like:

```
cast wallet import <NAME> <KEY>
```

Which then prompts the user for a password, and ecrypts it locally. Somewhere like:

```
~/.cast/wallets/<name>_keystore.json
```

Then, have a command to list stored keystores:

```
cast wallet list
```

And, then, when deploying commands with forge or cast, add the option to prompt the user to decrypt their password:

```
$ forge script script/Deploy.s.sol --rpc-url $RPC_URL --cast-wallet <WALLET_NAME>

enter password to decrypt <WALLET_NAME>
_
```

Or

```
$ cast send [TO] [SIG] [ARGS] --cast-wallet <WALLET_NAME>

enter password to decrypt <WALLET_NAME>
_
```

**Comment by robbiesumner** [comment]
I believe this feature has been added in #5551. Should this issue be closed?

**Comment by Evalir** [comment]
Done on #5551

**Comment by North1922** [comment]
```
$ forge script script/Deploy.s.sol --rpc-url $RPC_URL --cast-wallet <WALLET_NAME>

enter password to decrypt <WALLET_NAME>
_
 ```

However, the --cast-wallet argument is not available in Foundry?

**Comment by PatrickAlphaC** [comment]
@North1922 

You'd do it like this:

```bash
cast wallet import mywallet --interactive
# go through the prompts and import the wallet

# verify it's there with
cast wallet list

# then, use it
forge script scripts/MyScript.s.sol --account mywallet
```

**Comment by North1922** [comment]
I've dealt with this issue. However, I don't understand why the --cast-wallet argument is specified in the example above ?

**Comment by PatrickAlphaC** [comment]
The `--cast-wallet` in the example above was a sample of what I was looking for with this feature, an example API for the CLI. Instead, the foundry team choose to go with `--account`, like used here: https://github.com/foundry-rs/foundry/issues/3818#issuecomment-3761223528
