### ISSUE TITLE
Add --cups and --no-rate-limit options to forge

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#3823]
### Component

Forge

### Describe the feature you would like

in anvil we have

`--no_rate_limit` and `--cups` options to control budgets for the provider in forking mode.

we should add this to forge as well, ideally via `Config` in rpc_endpoints settings

**Comment by Evalir** [comment]
Hi! Happy to take on this over the next few days :).

**Comment by mattsse** [comment]
awesome!

**Comment by Evalir** [comment]
Yeah! Just wanted to confirm real quick:

> ideally via Config in rpc_endpoints settings

Do we want this to be under the `RpcEndpoints` struct or just put it near/under there but still under the `Config` struct (and `EvmArgs` i'd assume)?

**Comment by mattsse** [comment]
Ideally in the `RpcEndpoint` struct. This way we can configure this per API key.

additionally, we also want this in `EvmArgs` since we want to support this via the cli --rpc-url argument as well

**Comment by Evalir** [comment]
Haven't forgotten about this—just on an extended holiday break. Returning next week to get on it :)

**Comment by mattsse** [comment]
@Evalir are you still planning to add this?

this should only require smol changes

1. add these to the `EvmArgs` type

https://github.com/foundry-rs/foundry/blob/0f51e8eb0e63ba9ea36e6e3661261db9241f1cff/anvil/src/cmd.rs#L382-L410


2. Integrate in `EvmOpts` as well
3. Use new values here, via `ProviderBuilder`, see anvil usage of `ProviderBuilder`

https://github.com/foundry-rs/foundry/blob/0f51e8eb0e63ba9ea36e6e3661261db9241f1cff/evm/src/executor/fork/multi.rs#L480-L481

4. Same changes for provider here:

https://github.com/foundry-rs/foundry/blob/0f51e8eb0e63ba9ea36e6e3661261db9241f1cff/evm/src/executor/opts.rs#L78

**Comment by Evalir** [comment]
Yep still planning to! Just've been hands full with other work & some of the reth issues. Will get to this asap!
