### ISSUE TITLE
forge fails with `GLIBC_2.33' not found (required by forge) in github action CI

### ISSUE THREAD

**Issue by KholdStare** [foundry-rs/foundry#3827]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

nightly-2e99f7fdaef6a7aaeb426b02ef87e052cc14f68b

### Operating System

Linux

### Describe the bug

We use the [foundry-toolchain](https://github.com/foundry-rs/foundry-toolchain) github action in our CI and it started failing in the last few hours with failures like this:

```
forge: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by forge)
forge: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by forge)
forge: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by forge)
```

Is there a problem with the nightly release?

I didn't include the proper `forge --version` string, because `forge` can't even run that in our CI. It started failing after the latest release:
  - latest release broken: https://github.com/foundry-rs/foundry/releases/tag/nightly-2e99f7fdaef6a7aaeb426b02ef87e052cc14f68b
  - previous one is fine: https://github.com/foundry-rs/foundry/tree/nightly-f6361e6ddb6af62bbf6e122d0d8b27d2f5f6b42d

**Comment by mattsse** [comment]
this looks like a docker issue that somehow compile and execution libc differs

checking

**Comment by mattsse** [comment]
could you perhaps dump relevant parts of the CI job? 
wasn't able to reproduce this via github action

but I'm retriggering a release now

**Comment by amarcu** [comment]
I`m having the same issue, happens on my local machine after the update as well, running on Ubuntu 20.04.5 LTS(libc official versions is 2.31-0ubuntu9.9)

**Comment by mattsse** [comment]
can you please add your `forge --version`?

**Comment by amarcu** [comment]
> can you please add your `forge --version`? I triggered a new release, it seems to be related to how the release is build

nightly-2e99f7fdaef6a7aaeb426b02ef87e052cc14f68b

**Comment by mattsse** [comment]
I triggered a new release 1h ago, but this is still present?

could you please add the relevant CI output?

**Comment by qwinsi** [comment]
> I triggered a new release 1h ago, but this is still present?
> 
> could you please add the relevant CI output?

still present. The CI test in my repo just failed 2 minutes ago with the same error

**Comment by mattsse** [comment]
is this public?

any chance you can add or link the relevant CI output?

**Comment by qwinsi** [comment]
It failed on "Run Forge Test" step.  Here is the output:
> Run forge test --ffi
forge: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by forge)
forge: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by forge)
forge: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by forge)
Error: Process completed with exit code 1.

**Comment by amarcu** [comment]
> is this public?
> 
> any chance you can add or link the relevant CI output?

https://github.com/fiatdao/delphi-ii/actions

**Comment by mattsse** [comment]
hmm, what's interesting is that the release workflow is run on a different runner `22.04.1` than the CI `20.04.5` both have different software versions installed:

https://github.com/actions/runner-images/blob/ubuntu22/20221127.1/images/linux/Ubuntu2204-Readme.md

https://github.com/actions/runner-images/blob/ubuntu20/20221125.1/images/linux/Ubuntu2004-Readme.md

github just started to migrate ubuntu-latest to 22.04, which happens gradually https://github.com/actions/runner-images/issues/6399

could you perhaps try to change to

`runs-on: ubuntu-22.04` and retrigger a CI job?

**Comment by mattsse** [comment]
I think this is mostly forwards compatible, so I wonder if we should pin the release runner to `20.04` for the time being.

**Comment by mattsse** [comment]
> previous one is fine: https://github.com/foundry-rs/foundry/tree/nightly-f6361e6ddb6af62bbf6e122d0d8b27d2f5f6b42d

This on was run with 20.04 as well:

https://github.com/foundry-rs/foundry/actions/runs/3597605800/jobs/6059525485

only the latest switched to 22.04

**Comment by qwinsi** [comment]
Yeah. After switching to ubuntu-22.04, the CI test is passed.

**Comment by amarcu** [comment]
> Yeah. After switching to ubuntu-22.04, the CI test is passed.

Same for our repo.

**Comment by cryptogakusei** [comment]
I am running into the same issue while using codespaces. I tried the above suggested solution to change to `runs-on: ubuntu-22.04` which doesn't work. Any suggestions how to solve this?

**Comment by henry-hz** [comment]
Also got:
```
forge test -w                                                                                    10:33:33
forge: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by forge)
forge: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by forge)
forge: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by forge)
```

running on debian:

foundryup: installing foundry (version nightly, tag nightly-5206d4e9c8bbabe7b004a6ddc44e35b2f1bc72ee)

**Comment by m0ham3dx** [comment]
Facing similar issue when running ``foundryup` 

A dump of all erorrs = [`https://pastebin.com/raw/iW7V5Em6`](https://pastebin.com/raw/iW7V5Em6)

Solutions which worked --

```ml
git clone https://github.com/foundry-rs/foundry
cd foundry
# install cast + forge
cargo install --path ./cli --profile local --bins --locked --force
# install anvil
cargo install --path ./anvil --profile local --locked --force
```

**Comment by pcaversaccio** [comment]
facing the same error:
- the CI actions file: https://github.com/pcaversaccio/snekmate/blob/main/.github/workflows/test-contracts.yml#L59
- Example CI failure: https://github.com/pcaversaccio/snekmate/actions/runs/3614265257/jobs/6090582873#step:10:1
![image](https://user-images.githubusercontent.com/25297591/205505511-b7448cd1-b533-4c38-a746-d9eb83f39f09.png)

**Comment by gakonst** [comment]
We're on it - thx for the patience and debug info all.

**Comment by gakonst** [comment]
PSA: please add "runs-on: ubuntu-22.04" in your CI. 

It looks like it's fixed it for a few people and the person that said it didn't work above seems to be having a different issue (unclear if related or not).

**Comment by frangio** [comment]
Foundry installation is failing in [slither-action](https://github.com/crytic/slither-action). This is a Docker container action where it's not possible to choose the OS it runs on, so the workaround above doesn't apply. It seems to be based on [Debian Bullseye](https://github.com/crytic/slither-action/blob/230a81be4564bd7c5c4b51b199af246e9db92e5b/Dockerfile#L1) (like Ubuntu 20).

**Comment by gakonst** [comment]
This has also been flagged to Github and they'll take a look tomorrow on business days. Sorry about that folks, out of control unfort.


> Can we also pin the build version to 20.04?

@kristian1108 Where, other than the release file?

> Foundry installation is failing in [slither-action](https://github.com/crytic/slither-action). This is a Docker container action where it's not possible to choose the OS it runs on, so the workaround above doesn't apply. It seems to be based on [Debian Bullseye](https://github.com/crytic/slither-action/blob/230a81be4564bd7c5c4b51b199af246e9db92e5b/Dockerfile#L1) (like Ubuntu 20).

@frangio got it - thanks for flagging. any ideas on workaround or fix?

**Comment by frangio** [comment]
>any ideas on workaround or fix?

I would've suggested updating slither-action to use a more recent Python image as the base, but I see they are all based on Bullseye so I'm guessing the error will persist.

**Comment by mattsse** [comment]
pinned the wrong job in #3828, so release was still on latest, sorry about that.

#3824 pins the right intel linux build job

I guess we need to do the same for docker @gakonst

**Comment by gakonst** [comment]
Yes - let's also do for Docker which is fine for us, but others will need to have their images use a compatible libc. I don't know that we can "force" a libc version on the consumer?

**Comment by mslipper** [comment]
Updating to Ubuntu 22.04 images on CircleCI fixed this issue for us.

**Comment by montyly** [comment]
Hey. We noticed a similar issue in our CI for `dapp` yesterday. @elopez found a workaround with: https://github.com/crytic/crytic-compile/pull/320, the same trick might work for foundry

**Comment by gakonst** [comment]
@frangio can you take a look at the above workaround? saw you disabled foundry and would like to avoid us defaulting to that as a workaround, if we have a real fix for the issue

**Comment by frangio** [comment]
I don't think the workaround applies to users of slither-action, unless added in the action definition itself. @montyly @elopez?

**Comment by elopez** [comment]
Yeah, our problem was similar but related to a nix and setup-python interaction, it probably doesn't help here. If the releases are being built once again on 20.04 it should be back to working now on the action.

As an alternative, have you considered building and shipping static binaries instead, to avoid problems like this one or [the one noted here](https://github.com/foundry-rs/foundry#out-of-date-glibc-error-when-running-forge-from-default-foundryup-install)? It should be relatively easy to do with cargo: https://github.com/elopez/foundry/commit/cb294cf5c33ca8bba4ee98adb9cc659639400c18

**Comment by gakonst** [comment]
Can people confirm that this is fixed on Docker post #3893?

**Comment by frangio** [comment]
Seems fixed for `slither-action` at least!

**Comment by tsarbuig** [comment]
hey guys, I'm building a software with Ethers.rs and having same problem, but I did not understand how to implement the solution here ?

It's written as Solved ? what do we need to do ? I'm building releases with Github Actions, but quite a noob at it...

Thanks a lot :)

**Comment by KholdStare** [comment]
@tsarbuig Add `runs-on: ubuntu-22.04` to the github actions job - that was the temporary fix here for foundry, but it should be fine for everyone now with the latest releases. If you're running into this with ethers.rs I'd suggest raising an issue there and pointing at this thread?

**Comment by tsarbuig** [comment]
> @tsarbuig Add `runs-on: ubuntu-22.04` to the github actions job - that was the temporary fix here for foundry, but it should be fine for everyone now with the latest releases. If you're running into this with ethers.rs I'd suggest raising an issue there and pointing at this thread?

Thanks a lot bro, but the problem is that lots of my users are using Ubuntu 20.04, will it work then ?

I will create an issue :)

**Comment by gakonst** [comment]
May work - pls let us know if it doesn't

**Comment by tsarbuig** [comment]
> May work - pls let us know if it doesn't

Thanks for your help :) 

Sorry, I just tried and : 
- executable is compiled
- but when you run it on Ubuntu 20.04, same error : 

![image](https://user-images.githubusercontent.com/70858574/209672496-f0442e29-13de-4ea3-85f5-25d307338cbc.png)

Please save us 👼

**Comment by gakonst** [comment]
Did you try to install from source?

foundryup -b master?

**Comment by tsarbuig** [comment]
> Did you try to install from source?
> 
> foundryup -b master?

mmh I'm not sure to understand : where should I put this command line ?

**Comment by gakonst** [comment]
Just run it in your terminal order to install foundry from source, instead of the released binaries. That should use your local libc library and I would expect it to work.

**Comment by tsarbuig** [comment]
> Just run it in your terminal order to install foundry from source, instead of the released binaries. That should use your local libc library and I would expect it to work.

unfortunately : 
1/ Showing you the end of the (very, very long) compiling process, in success : 
![image](https://user-images.githubusercontent.com/70858574/209883398-a3b1e37d-ecc4-4fe7-9cce-a1749990293f.png)


2/ Same error : 
![image](https://user-images.githubusercontent.com/70858574/209883413-474eaec2-8c42-4f03-adea-2fc9a6ee511d.png)

**Comment by gakonst** [comment]
What is the output of "uname -a"?

**Comment by tsarbuig** [comment]
> uname -a

![image](https://user-images.githubusercontent.com/70858574/209885017-90f8e4ad-69e5-4875-9fe7-2c048ebff88c.png)

**Comment by tsarbuig** [comment]
@gakonst  what do you think about it ?

**Comment by tsarbuig** [comment]
@gakonst  don't forget me :'(

**Comment by gakonst** [comment]
Haven't had the time to diagnose yet, sorry. Appreciate the patience.

**Comment by tsarbuig** [comment]
> Haven't had the time to diagnose yet, sorry. Appreciate the patience.

ok bro :) take your time, just wanted to be sure you had not forgotten... Thanks a lot for your help ! and happy new year

**Comment by 0xharold** [comment]
FYI: 
I have just faced the same error locally when cloning and installing repo. Once I upgraded from Ubuntu 20.04 to 22.04 (on WSL) everything is back to normal.

**Comment by joiscode121** [comment]
> runs-on: ubuntu-22.04

Hi, were you ever able to solve this?
