### ISSUE TITLE
The application panicked (crashed).

### ISSUE THREAD

**Issue by avenbreaks** [foundry-rs/foundry#3838]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a854a0e 2022-12-01T00:07:36.933689295Z)

### What command(s) is the bug in?

forge script scripts/DeployDevelopment.s.sol --broadcast --fork-url $$ETH_RPC_URL --private-key $$PRIVATE_KEY

### Operating System

Linux

## Setting up (1) EVMs.
The application panicked (crashed).
Message:  to be set.
Location: cli/src/cmd/forge/script/broadcast.rs:519

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
```
   1: __libc_start_call_main<unknown>
      at ./csu/../sysdeps/nptl/libc_start_call_main.h:58
   2: __libc_start_main_impl<unknown>
      at ./csu/../csu/libc-start.c:392
```

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
Aborted (core dumped)
make: *** [Makefile:4: deploy] Error 134

**Comment by mattsse** [comment]
are the double $$ intentional `$$ETH_RPC_URL --private-key $$PRIVATE_KEY`?

**Comment by mds1** [comment]
@avenbreaks can you let us know if this is still an issue and if so, provide a repo to reproduce this with?

**Comment by Evalir** [comment]
Closing, stale.
