### ISSUE TITLE
Deploying to Celo/Celo Alfajores panics and crashes

### ISSUE THREAD

**Issue by snreynolds** [foundry-rs/foundry#3846]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (427c1b5 2022-12-07T00:09:22.004732Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

I'm deploying to celo alfajores using `forge script --broadcast --rpc-url <> --private-key <> <path to script>`.

Specifically deploying the [permit2 contracts](https://github.com/Uniswap/permit2). An example of the scripts I've been running to reproduce the issue:

`forge script --broadcast --rpc-url <> --private-key <> script/DeployPermit2.s.sol:DeployPermit2`
- gets a panic application crashed error

and 
`forge script --broadcast --rpc-url <> --private-key <> --with-gas-price 2797229 script/DeployPermit2.s.sol:DeployPermit2`
- gets a Failed to estimate EIP1559 fees.

**Comment by gakonst** [comment]
Thanks! 

What's the right RPC URL for us to use? Do you have a faucet link?

**Comment by snreynolds** [comment]
i've been using infura but think this also works? https://alfajores-forno.celo-testnet.org/
here is the faucet https://celo.org/developers/faucet

**Comment by gakonst** [comment]
@joshieDo maybe we don't auto detect this as a legacy chain? In foundry or ethers

**Comment by joshieDo** [comment]
Yeah it was the case. 

@snreynolds while the PR goes through,  you can add `--legacy` to your command for it to work meanwhile.

**Comment by gakonst** [comment]
Do we not want to auto-detect that for legacy chains and default to legacy transactions instead of requiring the user to do that?

**Comment by gakonst** [comment]
Merged both!

**Comment by rkrasiuk** [comment]
@gakonst @joshieDo can we close it as resolved?

**Comment by snreynolds** [comment]
Hi all, I know we've closed this. The deploy to alfajores did work (even without the legacy flag) but the verification does not. Would it be helpful for me to open a new issue for this?

**Comment by gakonst** [comment]
Yep pls open new issue, verification should be working as well, but maybe it's flaky?
