### ISSUE TITLE
The variables defined in the local ".env" file should take precedence over global environment variables

### ISSUE THREAD

**Issue by paulrberg** [foundry-rs/foundry#3847]
### Component

Forge

### Describe the feature you would like

Say you are using the [`envString`](https://book.getfoundry.sh/cheatcodes/env-string?highlight=envString#envstring) cheatcode like this:

```solidity
vm.createSelectFork(vm.envString("ETH_RPC_URL"));
```

The trouble is that if you have a global environment variable  `ETH_RPC_URL` (which is useful for `cast`) and also a local variable defined in an `.env` file, Forge will pick that global variable up instead of the local rpc URL defined in the `.env` file.

My feature request is to change this behavior to work in the opposite way - Forge should first look in the local `.env` file for any environment variables.

**Comment by gakonst** [comment]
Is that right? Some people do in-line env var definitions (e.g. in scripts) like `ETH_RPC_URL=<..> forge t --rpc-url $ETH_RPC_URL` or stuff like that, and that seems to break that use case?

**Comment by sakulstra** [comment]
Would agree that this behavior would be quite unexpected and different to the most popular `.env` implementations.

E.g. this is from node `dotenv` docs:

> ### What happens to environment variables that were already set?
> By default, we will never modify any environment variables that have already been set. In particular, if there is a variable in your .env file which collides with one that already exists in your environment, then that variable will be skipped.

**Comment by paulrberg** [comment]
Ah, ok, in this case I will close this issue. I thought that the standard behavior was different.
