### ISSUE TITLE
EvmError: OutOfGas with combination: vm.pauseGasMetering(), vm.rollFork() 

### ISSUE THREAD

**Issue by vapopov** [foundry-rs/foundry#3858]
### Component

Forge, Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9b1fe58 2022-12-08T00:15:07.729566Z)

### What command(s) is the bug in?

forge script scripts/GMXHistoricalJSON.s.sol

### Operating System

macOS (Intel)

### Describe the bug

After applying the `vm.pauseGasMetering()` and using together with `vm.rollFork()` I get error right after any contract call, example of the trace:

```
Traces:
  [2971690] → new GMXHistorical@0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496
    ├─ [0] VM::envUint(START) [staticcall]
    │   └─ ← <env var value>
    ├─ [0] VM::envUint(END) [staticcall]
    │   └─ ← <env var value>
    ├─ [0] VM::envUint(INTERVAL) [staticcall]
    │   └─ ← <env var value>
    ├─ [0] VM::envString(NETWORK) [staticcall]
    │   └─ ← <env var value>
    └─ ← 14266 bytes of code

  [9223372036854775807] GMXHistorical::run()
    ├─ [0] VM::rpcUrl(avax) [staticcall]
    │   └─ ← https://api.avax.network/ext/bc/C/rpc
    ├─ [0] VM::createSelectFork(https://api.avax.network/ext/bc/C/rpc, 22968009)
    │   └─ ← 0
    ├─ [0] VM::rollFork(22968010)
    │   └─ ← ()
    ├─ [0] VM::pauseGasMetering()
    │   └─ ← ()
    ├─ [464448] 0x9ab2De34A33fB459b538c43f251eB825645e8595::allWhitelistedTokensLength() [staticcall]
    │   └─ ← 0x0000000000000000000000000000000000000000000000000000000000000007
    └─ ← "EvmError: OutOfGas"


Gas used: 9223372036854775807
Error:
Script failed.
```

**Comment by brockelmore** [comment]
thanks for narrowing it down. looking into this

**Comment by 0xdeployer** [comment]
Hm seems like pauseGasMetering may not be working when used with vm.writeFile. I've got a loop which writes many files, but I get an out of gas error from that loop even when using pauseGasMetering

**Comment by brockelmore** [comment]
this is actually a out of memory issue. see #3971. solidity doesn't reuse the memory in a loop so you hit the memory expansion limit
