### ISSUE TITLE
Unable to send  wei to an address from an account (address) that's externally  generated. 

### ISSUE THREAD

**Issue by vikram2784** [foundry-rs/foundry#3862]
### Component

Cast

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

cast 0.2.0 (34d279a 2022-12-08T07:48:46.429075528Z)

### What command(s) is the bug in?

cast send

### Operating System

Linux

### Describe the bug

Unable to send  wei to an address from an account (address) that's externally  generated. 

Steps to reproduce with avil and cast:

- Send wei from an internally generated  account to externally generated account **(works)**:

`cast send --private-key  <int_account_priv_key>  --from <int_account_address> --value 1000000000000000000 <contract_address> "transfr(address)"  <ext_account_address>`

- Validate

```
cast balance <ext_account_address>
> 1000000000000000000
```

- Send some wei back to the internally generated  account   from  externally generated account. **(fails)**:

`cast send --private-key <ext_account_priv_key>   --from <ext_account_address> --value 100000 <contract_address> "transfr(address)" <int_account_address>`

ERROR:`(code: -32003, message: Out of gas: required gas exceeds allowance: 30000000, data: None)`

Following is the smart contract used to transfer:
```
// SPDX-License-Identifier: MIT
pragma solidity 0.8.17;
contract Demo {
    function transfr(address addr) external payable {
        payable(addr).call{value: msg.value}("");
    }
}
```

Script to generate external account:

```
# Generate the private and public keys
openssl ecparam -name secp256k1 -genkey -noout | openssl ec -text -noout > key

# Extract the public key and remove the EC prefix 0x04
cat key | grep pub -A 5 | tail -n +2 | tr -d '\n[:space:]:' | sed 's/^04//' > pub

# Extract the private key and remove the leading zero byte
cat key | grep priv -A 3 | tail -n +2 | tr -d '\n[:space:]:' | sed 's/^00//' > priv

# Generate the hash and take the address part
#cat pub | keccak-256sum -x -l | tr -d ' -' | tail -c 41 > address
pub=$(cat pub | openssl dgst -sha3-256 | awk '{print $NF}')
echo ${pub: -40} > address

```

**Comment by grandizzy** [comment]
@vikram2784 please reopen if still an issue with latest anvil, as a lot of things were changed since the ticket was opened. thank you!
