### ISSUE TITLE
`gasleft()` does not seem to return the right values

### ISSUE THREAD

**Issue by simontianx** [foundry-rs/foundry#3863]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (b28119b 2022-11-23T03:06:50.152811Z)

### What command(s) is the bug in?

forge test

### Operating System

Windows

### Describe the bug

The function `gasleft()` does not seem to return the right values. I'm running a contract function given below, and a simple step between two calls of `gasleft()` causes the returned values change for more than 0.14ETH from `9223372036854754539` to `9079256848778892941`. A few questions here:
1. `gasleft()` should return gas amount in Gwei which is 1e9 wei/Gwei, but the returned values seem to be in wei.
2. The returned values just don't seem to be right.

**Comment by simontianx** [comment]
```
  [7531] TestEthernaut::testLocal()
    ├─ emit log_uint(: 9223372036854754539)
    ├─ [1406] GatekeeperOne::enter(0x10000000000009e6)
    │   ├─ emit GasLeft(amount: 9079256848778892941)
    │   └─ ← "EvmError: Revert"
    └─ ← "EvmError: Revert"
    ```

**Comment by mattsse** [comment]
wdyt @rakita 

iirc the GAS opcode was just `Gas::remaining()`

**Comment by rkrasiuk** [comment]
@simontianx 
1. `gasleft()` returns the value of [`GAS` opcode](https://www.evm.codes/#5a?fork=grayGlacier) which is the remaining amount of gas. not to be confused with gas price which is usually described in gweis.
2. the gas reduction indeed seems quite big. could you provide a repro?

**Comment by rakita** [comment]
@rkrasiuk pointed it out. On one hand, we have
* `gas_limit`, `gas`, `used_gas` as an imaginary unit of VM resource.
* `gas_price` as amount of eth/wei that transaction wants to pay per `gas`
* And `fee` is calculated as `gas_price*gas_used`

**Comment by simontianx** [comment]
@mattsse @rkrasiuk @rakita Thanks for the comments and answers. It turns out that `9223372036854754539` is the nominal value returned by `gasleft()` and looks a bit too large to me and somehow I thought it should be scaled to be in gwei instead. I'm getting a better picture now. I'm also wondering if it's possible to control the amount of gas used for a transaction in a test. In some cases, it's desirable to have a better control of the amount of gas available, for example, `vm.gasavail(1000000)`. Thanks.

**Comment by trybye** [comment]
The same issue，the gasleft() is very large

**Comment by rakita** [comment]
@rkrasiuk @mattsse It seems this can be closed as it was confusion and not the problem/bug, `gas` is not related to `price` and can't be translated to gwei.
