### ISSUE TITLE
selfdestruct does not seem to work

### ISSUE THREAD

**Issue by simontianx** [foundry-rs/foundry#3864]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (b28119b 2022-11-23T03:06:50.152811Z)

### What command(s) is the bug in?

selfdestruct

### Operating System

Windows

### Describe the bug

The detailed discussions can be found in this [thread](https://forum.openzeppelin.com/t/what-does-selfdestruct-do-exactly/33633?u=maxareo). Running the same code with `selfdestruct` in remix and foundry presents different behaviors. In Foundry, `selfdestruct` seems to do nothing about destructing the contract but only forwarding funds to a designated wallet address. Please take a look into this.

**Comment by mattsse** [comment]
closing as dup of #1543
