### ISSUE TITLE
Add `rpcUrls` non-throwing variant

### ISSUE THREAD

**Issue by adhusson** [foundry-rs/foundry#3871]
### Component

Forge

### Describe the feature you would like

Add a parameter to `rpcUrl[Structs]*` to not throw when an entry is not found.

## Rationale
By default, foundry lazy-loads all `[rpc_endpoint]` entries, but those 2 cheatcodes prevent loading only the well-defined entries.

## Example interface
```solidity
// Returns all readable working rpc urls and their aliases `[alias, url][]`, and aliases that could not be read `[alias,error]`.
function rpcUrlsNoRevert() external view returns (string[2][] memory urls,string[2][] memory failed);
// Returns all readable rpc urls and their aliases as structs, and aliases that could not be read with the error in the `url` field.
function rpcUrlStructsNoRevert() external view returns (Rpc[] memory urls, Rpc[] memory failed);
```

**Comment by mds1** [comment]
Should we just change the existing `rpcUrls` methods to only return aliases which have defined URLs in the toml? So if there is an env var, but that env var is not set, that alias should not be returned in `vm.rpcUrls`. This would remove the need for https://github.com/foundry-rs/forge-std/pull/247, and feels like better behavior anyway? @mattsse @adhusson wdyt?

**Comment by adhusson** [comment]
Yes foundry-rs/forge-std#247 becoming too unwieldy was my motivation here :) For completeness it seems good to leave a way to detect unreadable aliases but otherwise ok with your suggestion.
