### ISSUE TITLE
bug(fmt): error on 1e9-m[0]

### ISSUE THREAD

**Issue by zapaz** [foundry-rs/foundry#3878]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e9f274d 2022-12-12T00:04:24.380051Z)

### What command(s) is the bug in?

forge fmt

### Operating System

macOS (Apple Silicon)

### Describe the bug

`forge fmt` on this file : 
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

contract FmtBug {
    mapping(uint256 => uint256) public m;

    constructor() {
                1e9-m[0];
    }
}
```

gives this error 

```
Failed to parse Solidity code for .../FmtBug.sol. Leaving source unchanged.
Debug info: [Diagnostic { loc: File(0, 159, 160), level: Error, ty: ParserError, message: "unrecognised token '[', expected \")\", \";\", \"=\"", notes: [] }]
```

Adding spaces around `-` fixes the bug

**Comment by mds1** [comment]
This is now resolved
