### ISSUE TITLE
Permanent releases/tags

### ISSUE THREAD

**Issue by shazow** [foundry-rs/foundry#3881]
### Component

Forge, Cast, Anvil

### Describe the feature you would like

Projects that rely on pinning development environments are getting constantly broken since the foundry project switched to keeping the last N nightly releases rather than permanent release tags.

We've been promised that foundry v1.0 and stable tags are coming any day now for several months now, and I get it--it's a big milestone to lock in.

Until v1.0 is released, could we please get some kind of persistent release snapshotting with nightly? Maybe an easy first take of this is don't delete nightly releases that were done on the 1st of the month? Or on a Monday if we prefer weekly?

### Additional context

Related issue downstream: https://github.com/shazow/foundry.nix/issues/8

The other alternative we're exploring is maintaining yet another separate repo just for archiving foundry nightly releases, but introduces yet another point of trust, point of failure, point of complexity. :)

**Comment by gakonst** [comment]
Yeah supportive / open to once per month given we're pretty stable at this point. Honestly I'd also do versioned releases but don't have time to think of a great process.

**Comment by hellwolf** [comment]
+1 to versioned release! Please!

I could also do pull request to prune-preleases.js, but would rather versioned releases.

**Comment by hellwolf** [comment]
Meanwhile, we could try this: https://github.com/foundry-rs/foundry/pull/3888

**Comment by shazow** [comment]
@hellwolf Thank you for doing that!

@gakonst Should we keep this issue open until we get real tagged releases? Or want me to make a fresh issue for tracking?

**Comment by gakonst** [comment]
Let's do in fresh one as I'll forget otherwise :p
