### ISSUE TITLE
Cheat code similar to `cast index` to use in conjunction with `vm.store`

### ISSUE THREAD

**Issue by webthethird** [foundry-rs/foundry#3882]
### Component

Forge

### Describe the feature you would like

I am planning to use `vm.store` in my differential fuzz testing contracts, to test for bugs that could be caused by some alternative state (relative to the fork I'm fuzzing on). But a lot of the relevant state in the contract I'm testing is stored in mappings, and `vm.store` requires the exact storage slot. I could use `ffi` to run "`cast index` key_type key slot", but `ffi` should only be used as a last resort, right? So it seems to me that something akin to `cast index` would be a useful cheat code, i.e., `vm.compute_index(key_type, key, slot) returns (bytes32)` (or perhaps drop the key_type argument and provide overrides for each type). That way, given a key of an arbitrary type as fuzzing input along with some knowledge about where the mapping is located, I could modify the value for the key without using `ffi` and `cast index`.

**Comment by mds1** [comment]
There are some utilities in forge-std to make this easier (check out the `stdStorage` lib). If those aren't sufficient feel free to PR in some solidity cheats that do the slot calculation (I don't think they key type is actually necessary IIRC)

**Comment by mds1** [comment]
Closing this since forge-std has storage helpers for this use case
