### ISSUE TITLE
Contract is unreachable when impersonating its address

### ISSUE THREAD

**Issue by ronlv10** [foundry-rs/foundry#3886]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### Operating System

macOS (Apple Silicon)

### Describe the bug

When using `anvil_impersonateAccount` on a contract address, I would expect that calls (from user or between contracts) to this contract would work as usual. But turns out that when impersonating a contract address, its code is unreachable. 
Example (using fork from Ethereum mainnet :

```
const ethers = require("ethers");
const PAUSE_ABI = [
  {
    constant: true,
    inputs: [],
    name: "delay",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  }
];

async function main() {
  const pauseAddress = "0xbE286431454714F511008713973d3B053A2d38f3";
  const provider = new ethers.providers.JsonRpcProvider("http://127.0.0.1:8545");
  const pauseContract = new ethers.Contract(pauseAddress, PAUSE_ABI, provider);

  await provider.send("anvil_impersonateAccount", [pauseAddress]);

  console.log(`delay: ${await pauseContract.delay()}`);

}

main().catch((e) => console.log(e));
```
Returns :
```
Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="delay()", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
  reason: null,
  code: 'CALL_EXCEPTION',
  method: 'delay()',
  data: '0x',
  errorArgs: null,
  errorName: null,
  errorSignature: null,
  address: '0xbE286431454714F511008713973d3B053A2d38f3',
  args: [],
  transaction: {
    data: '0x6a42b8f8',
    to: '0xbE286431454714F511008713973d3B053A2d38f3'
  }
}
```

Verified on HardHat and the code snippet works on Hardhat. 

I found https://github.com/foundry-rs/foundry/issues/1943, but not sure why we have to overwrite the contract code (seems like hardhat doesn't do this)
Having the option to impersonate a specific contract is necessary for bypassing authorization (e.g admin contract) but there are some circumstances that we still want the contract to be usable.

**Comment by mattsse** [comment]
This, meaning the call code of an impersonated account with itself, won't work atm:
```
 await provider.send("anvil_impersonateAccount", [pauseAddress]);

 console.log(`delay: ${await pauseContract.delay()}`);
```

because impersonateAccount will temporarily remove the code because of EIP-3607
