### ISSUE TITLE
Envelope type and Deserialization errors when confirming `cast` transactions in MetaMask

### ISSUE THREAD

**Issue by OnlyOneJMJQ** [foundry-rs/foundry#3890]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

cast 0.2.0 (e9f274d 2022-12-13T00:04:35.011347Z)

### What command(s) is the bug in?

cast send, cast rpc

### Operating System

macOS (Apple Silicon)

### Describe the bug

# The Issue
I'm attempting to use `cast` with [Truffle Dashboard](https://trufflesuite.com/docs/truffle/how-to/use-the-truffle-dashboard/) so I can confirm my transactions using MetaMask. These errors could point to a larger EIP-1559 issue, which is why I bring them up here. I tried 3 different methods of sending the transaction, using both Ganache and Goerli networks with the example `Counter` contract:

1. `cast send`: Error regarding envelope type: `(code: -32602, message: Invalid transaction envelope type: specified type "0x02" but including maxFeePerGas and maxPriorityFeePerGas requires type: "0x2", data: None)`
2. `cast send --legacy`: Error regarding "message": `(code: -32603, message: Cannot read properties of undefined (reading 'message'), data: Some(Object {"originalError": Object {}}))`
3. `cast rpc`: Error regarding message, specifically deserialization: `Deserialization Error: missing field "message" at line 1 column 275. Response: {"jsonrpc":"2.0","id":1,"error":{"code":-32600,"data":{"method":"eth_sendTransaction","params":"[{from: \"0xF808714EA67395Eed66931c8E9f88314e78bE31E\", to: \"0x94b1f4b902c074843A7f75Eec0544b88eFfEDEF8\", gas: \"0x76c0\", gasPrice: \"0x9184e72a000\", data: \"0xd09de08a\"}]"}}}`

# Repro Steps

1. Initialize a new foundry project:
`forge init foundry-test`

2. Build the included Counter contract:
`forge build`

3. Start a new ganache instance (or skip steps 4+5 for Goerli):
`ganache`

5. Add the first account to MetaMask, either by creating a new wallet with Ganache's mnemonic or copy/pasting the private key for account 0 into MetaMask's import account flow.

6. Start up Truffle Dashboard. You can do this without installing Truffle:
`npx tdboard`

7. Deploy the contract. This will not touch Dashboard because the private key is already included for signing (expected).
`forge create --rpc-url http://localhost:24012/rpc --private-key <PRIVATE_KEY> Counter`

8. Attempt to use `cast send` to send the transaction:
`cast send --from 0xF808714EA67395Eed66931c8E9f88314e78bE31E 0x94b1f4b902c074843A7f75Eec0544b88eFfEDEF8 "increment()" --rpc-url http://localhost:24012/rpc`
You'll see the transaction appear in Truffle Dashboard (ignore the compilation warning), attempting to approve it results in this error in the console:
`(code: -32602, message: Invalid transaction envelope type: specified type "0x02" but including maxFeePerGas and maxPriorityFeePerGas requires type: "0x2", data: None)`

9. Attempt to use `cast send` with the `legacy` option:
`cast send --from 0xF808714EA67395Eed66931c8E9f88314e78bE31E 0x94b1f4b902c074843A7f75Eec0544b88eFfEDEF8 "increment()" --legacy --rpc-url http://localhost:24012/rpc`
We get further! MetaMask will open in this instance, but the transaction will clear before you have a chance to approve. Error in console:
`(code: -32603, message: Cannot read properties of undefined (reading 'message'), data: Some(Object {"originalError": Object {}}))`

10. Attempt to use `cast rpc` to send the transaction:
`cast rpc -r http://localhost:24012/rpc -w eth_sendTransaction '[{from: "0xF808714EA67395Eed66931c8E9f88314e78bE31E", to: "0x94b1f4b902c074843A7f75Eec0544b88eFfEDEF8", gas: "0x76c0", gasPrice: "0x9184e72a000", data: "0xd09de08a"}]'`
Error in console:
`Deserialization Error: missing field "message" at line 1 column 275. Response: {"jsonrpc":"2.0","id":1,"error":{"code":-32600,"data":{"method":"eth_sendTransaction","params":"[{from: \"0xF808714EA67395Eed66931c8E9f88314e78bE31E\", to: \"0x94b1f4b902c074843A7f75Eec0544b88eFfEDEF8\", gas: \"0x76c0\", gasPrice: \"0x9184e72a000\", data: \"0xd09de08a\"}]"}}}`

I'll note here that I also tried one level down (sending a raw tx), which did work, but of course didn't use MetaMask/Dashboard because it's pre-signed.

**Comment by cbrzn** [comment]
were you able to find a workaround for this? having exactly the same problem when trying to interact with metamask and ethers-rs

**Comment by mattsse** [comment]
tbh all of these errors looke like ganache/metamask related:

> (code: -32602, message: Invalid transaction envelope type: specified type "0x02" but including maxFeePerGas and maxPriorityFeePerGas requires type: "0x2", data: None)

EIP1559 is 0x02 and should include maxFeePerGas and maxPriorityFeePerGas

> Deserialization Error: missing field "message" at line 1 column 275. Response: {"jsonrpc":"2.0","id":1,"error":{"code":-32600,"data":{"method":"eth_sendTransaction","params":"[{from: \"0xF808714EA67395Eed66931c8E9f88314e78bE31E\", to: \"0x94b1f4b902c074843A7f75Eec0544b88eFfEDEF8\", gas: \"0x76c0\", gasPrice: \"0x9184e72a000\", data: \"0xd09de08a\"}]"}}}

this is an error because the response is not valid JSON RPC lacks message field of JSON RPC error

**Comment by cbrzn** [comment]
i guess this can be closed since this is indeed an error in metamask and not in foundry, the mm team opened an issue: https://github.com/MetaMask/metamask-extension/issues/18076 - thanks for your reply @mattsse
