### ISSUE TITLE
anvil_dumpState is not deterministic in the output

### ISSUE THREAD

**Issue by KholdStare** [foundry-rs/foundry#3891]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (d896050 2022-12-01T21:20:45.538002477Z)

### What command(s) is the bug in?

anvil_dumpState

### Operating System

Linux

### Describe the bug

A useful feature was introduced by @dbeal-eth in https://github.com/foundry-rs/foundry/pull/2256 for dumping the current state of the evm and loading it back in. However, the returned hex string is not deterministic. Running it on the same evm state, calling `anvil_dumpState` back to back results in different strings.

I suspect this is due to the fact that the resulting bytes are serialized from a rust `HashMap`:

```
pub struct SerializableState {
    pub accounts: HashMap<Address, SerializableAccountRecord>,
}
```

And according to https://doc.rust-lang.org/std/collections/struct.HashMap.html, the hashmap is randomly seeded. Seems like the solution is either to sort the keys before serializing, or initialize the hashmap with a deterministic seed with e.g. https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.with_hasher . What do you think?

**Why is this even an issue?**

Even though the end-result of loading the dumped state into anvil results in the same state no matter the order of the keys, it's not easy to verify whether two dumped states are identical by just looking at the hex strings. We want to use this as an extra sanity check on our deployments - we deploy our contracts on anvil using `forge script`, then run `anvil_dumpState` and see if it matches the expected result. Right now it is not possible.

**Comment by mattsse** [comment]
good find, ty. 

you're totally right, will change to BTreeMap which is commonly used to sort json objects
