### ISSUE TITLE
`forge coverage` silently fails, showing zero coverage

### ISSUE THREAD

**Issue by OliverNChalk** [foundry-rs/foundry#3900]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8fd5930 2022-12-16T00:10:59.201989698Z)

### What command(s) is the bug in?

forge coverage

### Operating System

Linux

### Describe the bug

If `forge coverage` successfully compiles but the tests error, then it will produce a zero coverage report, which feels wrong. If the tests fail during coverage, which is possible because coverage compiles with different settings, then it should result in the command returning a non-zero exit code rather than silently failing and returning a zero coverage report.

**Comment by llllvvuu** [comment]
> If the tests fail during coverage, which is possible because coverage compiles with different settings

I think this might be happening to me, but I'm not sure how to check. How did you figure this out @OliverNChalk ?
