### ISSUE TITLE
Cast `4byte` should support alternative urls aside from samczsun's directory

### ISSUE THREAD

**Issue by frank-lim-partior** [foundry-rs/foundry#3909]
### Component

Cast

### Describe the feature you would like

The following `cast` functions uses `https://sig.eth.samczsun.com` by default to lookup signature calls.
* `4byte-event` 
* `4byte-decode` 
* `4byte`

I'll like to be able to define self-hosted endpoints via an option like `--sig-url=https://4byte.mysite.com`

Others may want to do it to avoid exposing API calls to the service provider or exposing function selectors to the public. This will also reduce reliance on the site being online.

**Comment by 0xvv** [comment]
Can you explain a bit more ? I don't think there is a standard API for this, `https://www.4byte.directory` uses a totally different one than `https://sig.eth.samczsun.com`, which is currently implemented.

Implementing the ability to query another endpoint with the same API as the latter is not a big change.
But I'm not sure it's good to start implementing multiple APIs for this, cast used to support the 4bytes API but it has been replaced, see https://github.com/foundry-rs/foundry/issues/1672

**Comment by frank-lim-partior** [comment]
I'm only suggesting the ability to use another endpoint. While there isn't a standard API, I'm happy to conform to the API used in `https://sig.eth.samczsun.com`.

**Comment by zerosnacks** [comment]
Marking as `not planned`

https://sig.eth.samczsun.com has since moved to the open source organization [openchain.xyz](https://openchain.xyz/signatures): https://github.com/foundry-rs/foundry/pull/5315/files + https://github.com/foundry-rs/foundry/issues/4177
