### ISSUE TITLE
vm.startBroadcast, vm.startPrank don't change msg.sender in script

### ISSUE THREAD

**Issue by Skelectric** [foundry-rs/foundry#3917]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What command(s) is the bug in?

forge script script/BroadcastTest.sol:BroadcastTest --rpc-url=$env:GOERLI_RPC_URL -vv

### Operating System

Windows

### Describe the bug

I have scripts that are failing simulation (reverting on onlyOwner checks of deployed contracts) because neither the startBroadcast() nor the startPrank() cheatcodes are updating msg.sender. 

```
// SPDX-License-Identifier: Unlicensed
pragma solidity ^0.8.17;

import "forge-std/Script.sol";

contract BroadcastTest is Script {
    function run() external {
        uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");
        address deployer = vm.addr(deployerPrivateKey);

        // Initial 
        console.log("msg.sender should be deployer %s", deployer);
        console.log("msg.sender %s", msg.sender);
        
        // Broadcast
        console.log();
        console.log("nvm.startBroadcast(deployerPrivateKey)...");
        vm.startBroadcast(deployerPrivateKey);
        console.log("msg.sender %s", msg.sender);
        vm.stopBroadcast();
        console.log("vm.stopBroadcast()");

        // Prank
        console.log();
        console.log("vm.startPrank(deployer)...");
        vm.startPrank(deployer);
        console.log("msg.sender %s", msg.sender);
        vm.stopPrank();
        console.log("vm.stopPrank()");
    }
}
```

```
$ forge script script/BroadcastTest.sol:BroadcastTest --rpc-url=$env:GOERLI_RPC_URL -vv     
[⠒] Compiling...
[⠑] Compiling 1 files with 0.8.17
[⠃] Solc 0.8.17 finished in 602.18ms
Compiler run successful
Script ran successfully.

== Logs ==
  msg.sender should be deployer 0xd6E1fE2d44555597828eD5a7401A481a7654A530
  msg.sender 0x1804c8AB1F12E6bbf3894d4083f33e07309d1f38

  nvm.startBroadcast(deployerPrivateKey)...
  msg.sender 0x1804c8AB1F12E6bbf3894d4083f33e07309d1f38
  vm.stopBroadcast()

  vm.startPrank(deployer)...
  msg.sender 0x1804c8AB1F12E6bbf3894d4083f33e07309d1f38
  vm.stopPrank()
```

How have people been working around this?

**Comment by Skelectric** [comment]
Just like in the other issue I brought up last week, i am unable to skip the simulation because the --skip-simulation flag does nothing. 

I can't emphasize enough how broken the workflow is for me right now. Somebody pls halp.

https://github.com/foundry-rs/foundry/issues/3870

**Comment by 0xPhaze** [comment]
Seems like `msg.sender` is not set correctly when using `vm.startBroadcast(key)` at the top-level. It does work correctly when passing in the private key via `--private-key 0xabc..`. The `msg.sender` is however correctly set in external calls / deployments:

```solidity
contract ABC {
    constructor() {
        console.log("ABC msg.sender", msg.sender);
    }
}
```
```
  msg.sender should be deployer 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
  msg.sender 0x1804c8AB1F12E6bbf3894d4083f33e07309d1f38
  
  vm.startBroadcast(deployerPrivateKey)
  msg.sender 0x1804c8AB1F12E6bbf3894d4083f33e07309d1f38
  ABC msg.sender 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
  vm.stopBroadcast()
```

**Comment by Skelectric** [comment]
@0xPhaze that was a huge help, thanks!

**Comment by joshieDo** [comment]
There's some misunderstanding. `prank` and `broadcast` [only change the `msg.sender` of **the following external call** ](https://book.getfoundry.sh/cheatcodes/prank)by design. They do not change the current `msg.sender` of the script execution.

> It does work correctly when passing in the private key via --private-key 0xabc.

It behaves the same. The difference is: when you pass a `--private-key` he sets that key as the default `msg.sender`, the one that calls the script contract `run()`. You can also call it with `--sender`. If you don't set either one, then foundry will call the script contract with a default one (0x1804c8AB1F12E6bbf3894d4083f33e07309d1f38)

**Comment by joshieDo** [comment]
@Skelectric  @0xPhaze  tagging for visibility

**Comment by n00b21337** [comment]
> There's some misunderstanding. `prank` and `broadcast` [only change the `msg.sender` of **the following external call** ](https://book.getfoundry.sh/cheatcodes/prank)by design. They do not change the current `msg.sender` of the script execution.
> 
> > It does work correctly when passing in the private key via --private-key 0xabc.
> 
> It behaves the same. The difference is: when you pass a `--private-key` he sets that key as the default `msg.sender`, the one that calls the script contract `run()`. You can also call it with `--sender`. If you don't set either one, then foundry will call the script contract with a default one (0x1804c8AB1F12E6bbf3894d4083f33e07309d1f38)

So is there a way you would recommend we get public key from private key used for deployment if we don't pass it as parameter and we don't hardcode the address?

**Comment by mds1** [comment]
You can use the `vm.createWallet` cheat to get the public key and address from a private key
