### ISSUE TITLE
Verify from broadcast output

### ISSUE THREAD

**Issue by marktoda** [foundry-rs/foundry#3922]
### Component

Forge

### Describe the feature you would like

It would be sweet if there was an option for `forge verify-contract` to take a broadcast file as input and automatically try to verify any contracts created from it. It could automatically parse constructor args and creation addresses etc. 

This is useful in case we forget to pass the `--verify` flag to `forge script`, or verification fails the first time for some reason. Major time save to avoid looking up the constructor args and creation addresses after-the-fact especially for complex scripts. 

Suggested API:
```
forge verify-contract --from-broadcast /path/to/broadcast.json
```

**Comment by mds1** [comment]
Partly related to https://github.com/foundry-rs/foundry/issues/3911, where deployment artifacts should have all info needed to verify the contract, cause I agree this can be tedious right now

**Comment by joshieDo** [comment]
+1

Also  a reminder that you can call the same script command without `--broadcast` and with `--verify`. It will attempt to verify the latest broadcast.

example:
```bash
forge script ScriptContract --rpc-url $RPC (...) --broadcast 
forge script ScriptContract --rpc-url $RPC (...) --verify
```

**Comment by marktoda** [comment]
Ohhhh I didn't know that -- that's exactly what I wanted to do :D. Thanks!

**Comment by joshieDo** [comment]
`--resume` too, in case your broadcasting failed for whatever reason. (it will just attempt to publish the same transactions, it won't actually re-calculate state)

**Comment by roshanrags** [comment]
Does this still work? It says this for me:
```
error: the following required arguments were not provided:
  --broadcast
```

**Comment by zerosnacks** [comment]
Hi @roshanrags, `--verify` now requires the `--broadcast` flag to be present as we do not simulate verification

```
forge script ScriptContract --rpc-url $RPC --broadcast --resume --verify
```

Should work
