### ISSUE TITLE
Add a vm.isSimulation() cheatcode

### ISSUE THREAD

**Issue by Skelectric** [foundry-rs/foundry#3928]
### Component

Forge

### Describe the feature you would like

I would like for my scripts to skip certain operations in the pre-broadcast simulations. 

```
if (vm.isSimulation() == false) {
    stdJson.write(json, filepath);   
}
```

Without the ability to differentiate whether the script is executing in a simulation at runtime, I can't perform certain operations that require persistent storage because the simulation gets in the way.

**Comment by mattsse** [comment]
this is useful to have imo.

supportive of this.

I think we can add this via bool field that is set before and unset after simulation.

**Comment by mds1** [comment]
One note is we don't have any script-only cheats yet, so what should this return during tests? Perhaps a better way to implement is as part of https://github.com/foundry-rs/foundry/issues/2900, and make the "Script" context more granular

**Comment by mattsse** [comment]
right, forgot about this. #2900 is the right way to do this

**Comment by 0x0elliot** [comment]
so, would you rather even have this implemented? @mattsse

**Comment by zerosnacks** [comment]
Marking as completed by https://github.com/foundry-rs/foundry/pull/7377
