### ISSUE TITLE
Rewrite `format_hardhat_call` as a proc macro

### ISSUE THREAD

**Issue by rkrasiuk** [foundry-rs/foundry#3933]
Rewrite `format_hardhat_call` as a proc macro. Adding any new console log overloads as is would be a waste of time
https://github.com/foundry-rs/foundry/blob/60b19191ce1f7eb9fac5dcccf46442561d922bef/evm/src/executor/abi/fmt.rs#L172

Ref #3932

**Comment by DaniPopes** [comment]
I'd like to take this on, but it looks like we currently don't have any proc macro in general, should I create a new `macro` crate in the workspace for it, or is there another way?

**Comment by rkrasiuk** [comment]
@DaniPopes sgtm. yeah, let's create a separate crate but with a more descriptive name for now
