### ISSUE TITLE
latest ethers-core commit break foundry-config compile

### ISSUE THREAD

**Issue by alexander-camuto** [foundry-rs/foundry#3936]
### Component

Other (please describe)

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

n.a

### Operating System

Linux

### Describe the bug

When compiling `foundry-config`, `Cargo.toml` will pull in the latest `ethers-core` commits if running a clean build. 
```toml
ethers-core = { git = "https://github.com/gakonst/ethers-rs", default-features = false }
``` 
These latest commits to `ethers-core` (currently 8673704955106d39baa1e78c56ba20b0a3d2e69e) cause the compile for `foundry-config` to fail with: 
```bash
error[E0432]: unresolved import `ethers_core::types::ParseChainError`
 --> config/src/chain.rs:2:26
  |
2 | use ethers_core::types::{ParseChainError, U64};
  |                          ^^^^^^^^^^^^^^^
  |                          |
  |                          no `ParseChainError` in `types`
  |                          help: a similar name exists in the module: `ParseI256Error`

``` 

To replicate run: 
```
cd config; cargo update; cargo build
```

**Comment by DaniPopes** [comment]
Can't bump ethers yet, WIP See #3899 and #3935

**Comment by alexander-camuto** [comment]
I have a small fix for foundry-config if that is helpful at all ? Doesn't address issues with other sub-crates though
