### ISSUE TITLE
Invariant testing is very slow on a particular setup

### ISSUE THREAD

**Issue by QGarchery** [foundry-rs/foundry#3938]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8c4294c 2022-12-22T00:03:55.083004205Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

Invariant testing seems to be abnormally slow on some setups. The following tests are made on [this repository](https://github.com/morpho-dao/morpho-data-structures). For future reference, the particular commit is [this one](https://github.com/morpho-dao/morpho-data-structures/commit/84f5cf38bddce046d7cfc95c51c96d3218ea1a5c).

After importing the necessary dependencies with `yarn` a call to `forge test --match-test invariantHeap` does not terminate in reasonable time. When changing the `depth` in `foundry.toml` to be `2` instead of `64`, we get the following time to test:

![invariant-testing](https://user-images.githubusercontent.com/22668539/209187176-c9e0c641-5623-47c7-b136-e70531fa2d22.png)

I tested on other setups, Linux & macOs with the same forge version and it seems to be working fine there.

**Comment by rkrasiuk** [comment]
@joshieDo ptal

**Comment by joshieDo** [comment]
Could not reproduce it...
@QGarchery  Can you run it with the command below for `depth` 2 and provide the logs?
```RUST_LOG=info,trace forge test --match-test invariantHeap```

**Comment by QGarchery** [comment]
The resulting file is 127 MB large, so I put only the first 1000 lines here (`less -r log-head-1000.txt` gives a nice view):
[log-head-1000.txt](https://github.com/foundry-rs/foundry/files/10352445/log-head-1000.txt)

Looking at it, it seems like it's doing a lot of rpc calls. It probably shouldn't because we are testing a data-structure locally. I have a rpc setup globally on my machine, and this is probably why it's doing that. Indeed, after `unset FOUNDRY_ETH_RPC_URL`, the call finishes in 0.4s instead of 79s.

Why are those RPC calls made and is it possible to skip them ? If not, feel free to close this issue

**Comment by mds1** [comment]
When [`FOUNDRY_ETH_RPC_URL`](https://book.getfoundry.sh/reference/config/testing#eth_rpc_url) is set, it tells forge to query the RPC to fetch a value if there is no local value (e.g. fork testing). So you cannot skip the RPC calls if that env var is set. My suggestion is to keep that unset, and use the [`vm.createSelectFork`](https://book.getfoundry.sh/forge/fork-testing#forking-cheatcodes) family of cheats within your test when you need fork tests
