### ISSUE TITLE
Failing to fetch chain ID and fork block number

### ISSUE THREAD

**Issue by zkSoju** [foundry-rs/foundry#3946]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### Operating System

Windows

### Describe the bug

The following functions now fail when using `setup` with the most recent commits. I am using the same RPC URL as I did previously:

https://github.com/foundry-rs/foundry/blob/b78509fb8e11b7f58a0021cd900b7c7a2d3be503/anvil/src/config.rs#L776-L777

https://github.com/foundry-rs/foundry/blob/b78509fb8e11b7f58a0021cd900b7c7a2d3be503/anvil/src/config.rs#L792-L794

It fails with: 
```
thread 'main' panicked at 'Failed to get fork block number: HTTPError(reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("eth-mainnet.g.alchemy.com")), port: None, path: "/v2/TIWiJhtGeXmmhTL2GmBFLUGrKE5vrbZD", query: None, fragment: None }, source: hyper::Error(Connect, "invalid URL, scheme is not http") })', /Users/bigmac/.cargo/git/checkouts/foundry-44353293f4b0a5c1/b78509f/anvil/src/config.rs:794:30
```

**Comment by mattsse** [comment]
hmm does this always result in an error or just sporadically?

should definitely convert the panics into errors here.

**Comment by zkSoju** [comment]
It always results in a panic yeah.

**Comment by mattsse** [comment]
so the error looks like it's not using tls for some reason.
was not able to reproduce this on mac.

likely a windows issue, will cut release after #3951 which should definitely enable it.

**Comment by zkSoju** [comment]
> so the error looks like it's not using tls for some reason. was not able to reproduce this on mac.
> 
> likely a windows issue, will cut release after #3951 which should definitely enable it.

Sounds good! Seems to be fixed on Mac with that merge

**Comment by zkSoju** [comment]
> so the error looks like it's not using tls for some reason. was not able to reproduce this on mac.
> 
> likely a windows issue, will cut release after #3951 which should definitely enable it.

confirmed works on windows now as well
