### ISSUE TITLE
expectEmit: expecting multiple events from 1 call not working?

### ISSUE THREAD

**Issue by snreynolds** [foundry-rs/foundry#3949]
Saw that you can expect multiple events from 1 call as its shown [here](https://book.getfoundry.sh/cheatcodes/expect-emit?highlight=expectEmit#expectemit) but test was failing. 

It would succeed when I just expected the last event but not the first one.

**Comment by Evalir** [comment]
Closing for now—seems stale and `expectEmit` recently got a bit of a rework.
