### ISSUE TITLE
How to combine multiple supposed-to-fail contract calls in one test case?

### ISSUE THREAD

**Issue by 0xDEnYO** [foundry-rs/foundry#3950]
Hey Guys,

I am coding a Testhelper.sol contract which features some standard tests that should be inherited and executed by multiple other test files. We have numerous diamond facets and we want to make sure that they all pass the same tests whilst reducing boilerplate code.
Aggregating and calling positive tests works fine.
But aggregating negative tests does not work since after the first test failed, the tx is reverted already and the following tests will never be executed.
I cannot work with try/catch here since these are internal calls.

In Hardhat I could apply the following principle:
expectRevert(testFailNegative1());
expectRevert(testFailNegative2());
...

But with foundry I have not found a way to have several reverting calls in one test case.

Do you have a suggestion for me how I could implement such a pattern?

file _Testhelper.sol_
```
contract TestHelper {
   function testPositiveA() public {....}
   function testPositiveB() public {....}
   function testFailNegative1() public {....}
   function testFailNegative() public {....}

   function runAllPositiveTests() internal {      // this works fine
     testPositiveA();
     testPositiveB();
   }

  function runAllNegativeTests() internal {
     testFailNegative1();   // fails here (as expected)
     testFailNegative2();  // will never be executed, but should
  }
}
```

file _TestFacet.t.sol_
```
contract TestFacet is Testhelper {

   function testPositiveStandardTests() public {
       runAllPositiveTests();   // this works fine
   }

   function testFailNegativeStandardTests() public {
       runAllNegativeTests();    // this will never execute all negative standard tests but stop after the first one failed
   }
}

**Comment by zerosnacks** [comment]
Closing in favor of https://github.com/foundry-rs/foundry/issues/3723 as it has a larger body of discussion
