### ISSUE TITLE
CI warns of macOS and other issues in 'Release cleanup'

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#3956]
### Component

Commands in CI are to be depreciated , see https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### Operating System

None

### Describe the bug

see: https://github.com/foundry-rs/foundry/actions/runs/3773462118#artifacts

The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Release cleanup
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Release Docker / container
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Release version: .github#L1
**macOS-latest** pipelines will use macOS-12 soon. For more details, see https://github.com/actions/runner-images/issues/6384

**Comment by zerosnacks** [comment]
Assuming this has been resolved as no warning is thrown on recent runs.

Related: 

>24-July-2023 Update: Our telemetry shows significant usage of these commands so we have decided to postpone the removal. To learn more, visit the [latest changelog post](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
