### ISSUE TITLE
Support for Zero Knowledge Proof generation from external source, like Javascript/WASM

### ISSUE THREAD

**Issue by shekohex** [foundry-rs/foundry#3963]
### Component

Forge

### Describe the feature you would like

The title say it all, currently, what stops us at @webb-tools from switching to use foundry for our contract tests (which by the way, from GitHub Actions, it takes up to 56m to complete) is that our protocol is based on Zero Knowledge proof generation/verification, our code for generating these proofs are currently written in Javascript, which wraps some other WASM code from Circom.

So back to the original question, how we can do such thing like Generating ZKP inside solidity? Do we have to write it in say Rust, and expose that as FFI? what the workflow would look like? 

### Additional context

- Example Test: https://github.com/webb-tools/protocol-solidity/blob/56ad8f5e24e8aff09fd25498490824e22f9ef05d/packages/contracts/test/vanchor/vanchor.test.ts#L272
- Our Circom Proving Manager: https://github.com/webb-tools/webb.js/blob/0b864f7f6c46f6f9e246d234c19496a055306fd6/packages/sdk-core/src/proving/circom/proving-manager.ts
- Our Circuits: https://github.com/webb-tools/protocol-solidity/tree/main/circuits

**Comment by joshieDo** [comment]
> 56m to complete

ouch

> for generating these proofs are currently written in Javascript, which wraps some other WASM code from Circom.

You can indeed use `ffi` to call the proof generation script, and then either "consume" it as hex or json, up to you. I don't see why it wouldn't work. Feel free to tag me on the tg channel and I'd be more than happy to help.

**Comment by rkrasiuk** [comment]
@shekohex did you have any luck using ffi for proof generation?

**Comment by krisgrm** [comment]
Any updates on this ?

**Comment by DaniPopes** [comment]
This feels very out of scope. You should just use vm.ffi and CLI wrappers for these kinds of things.
