### ISSUE TITLE
bug(chisel): ending with an assembly block breaks (stack|mem)dump

### ISSUE THREAD

**Issue by transmissions11** [foundry-rs/foundry#3964]
### Component

Chisel

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e9f274d 2022-12-12T00:04:24.380051Z)

### What command(s) is the bug in?

chisel

### Operating System

macOS (Apple Silicon)

### Describe the bug

If the last command is an assembly block, !sd/!md break with the error "Run function is empty."

Here's a simple repro case:

```solidity
λ chisel
Welcome to Chisel! Type `!help` to show available commands.
➜ uint test = 1;
➜ !sd
[0]: 0x01
[1]: 0x33
[2]: 0xc0406226
➜ assembly { test := 2 }
➜ !sd
⚒️ Chisel Error: Run function is empty.
➜ !source
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.17;

import {Cheats} from "forge-std/Vm.sol";

contract REPL {
    Cheats internal constant vm = Cheats(address(uint160(uint256(keccak256("hevm cheat code")))));

    /// @notice REPL contract entry point
    function run() public {
        uint256 test = 1;
        assembly {
            test := 2
        }
    }
}
```

**Comment by transmissions11** [comment]
cc @clabby

**Comment by clabby** [comment]
Good catch! This looks to be an issue with the way Chisel's `runner` & `executor` handles the final statement of the `run()` function (See [here](https://github.com/foundry-rs/foundry/blob/master/chisel/src/executor.rs#L43)). I believe we could add a special case if the final statement is an assembly / unchecked / regular scope block that will fix this up, will look into it when I'm back online for the week.
