### ISSUE TITLE
feat: forge inspect storage for deployed contracts

### ISSUE THREAD

**Issue by zobront** [foundry-rs/foundry#3967]
### Component

Forge

### Describe the feature you would like

currently, `forge inspect` only works for local code. however, it would be useful to access some of the functionality (especially storage layout) for deployed contracts that have been verified on etherscan.

for example, i'd like to be able to call `forge inspect --prety 0x... storage` to get the storage layout of a deployed contract.

**Comment by mds1** [comment]
While not exactly the same as it won't give the storage layout JSON, you can use `cast storage <address>` to get this info in a table format

**Comment by zobront** [comment]
This is exactly what I was looking for, thanks. I'll close issue now.

**Comment by RamanSB** [comment]
I tried this on a contract I deployed locally via Anvil and received the following error: 

```
raman@Ramandeeps-MBP erc20 % cast storage 0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512 
[⠊] Compiling...
No files changed, compilation skipped
No matching artifacts found, fetching source code from Etherscan...
Error: 
You must provide an Etherscan API key if you're fetching a remote contract's storage.
```

Even after providing the Etherscan API key which I don't believe is necessary when checking the storage layout of a locally deployed contract:

```
raman@Ramandeeps-MBP erc20 % cast storage --chain 31337 --rpc-url="http://localhost:8545" --etherscan-api-key $ETHERSCAN_API_KEY 0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512
[⠊] Compiling...
No files changed, compilation skipped
No matching artifacts found, fetching source code from Etherscan...
Error: 
**Chain anvil-hardhat not supported** 
```

**Chain anvil-hardhat not supported** is there any way around this?

**Comment by 0xCK03** [comment]
@RamanSB I'm having same issue. Have you find a solution?

**Comment by 0ShadowKitty0** [comment]
@RamanSB  @0xCK03 this is the issue from your logs: `No matching artifacts found, fetching source code from Etherscan...`
You need contract code to infer storage slots, so either you are on the same project folder that contains your local contract, or cast will try to fetch its source from etherscan.
