### ISSUE TITLE
CI broken on live goerli tests

### ISSUE THREAD

**Issue by joshieDo** [foundry-rs/foundry#3969]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### Operating System

None

### Describe the bug

CI keeps failing on the goerli live test with `Transaction dropped...`. Example: https://github.com/foundry-rs/foundry/actions/runs/3783096285/jobs/6431365456

However, the transaction(s) is not really dropped and is even included in the same block (from the above example).

![image](https://user-images.githubusercontent.com/93316087/209609370-108fbf53-7d86-47a0-8b79-b29557796eaa.png)

Could not reproduce it even once locally. Any ideas @prestwich ?

**Comment by prestwich** [comment]
goerli is the worst network for tx confirmation consistency. Txns will drop out of the txpool, but show up in getTransactionCount requests, and then show up confirmed days later. we stopped working with it whenever possible

> Could not reproduce it even once locally. 

this is odd tho. I would expect it to behave the same in CI. are we compiling with any special flags?

**Comment by joshieDo** [comment]
I tried many times... but the only inconsistency i got was on getting CREATE2 contracts indexed, which would take days sometimes. Everything else pretty much always succeeds. 

> are we compiling with any special flags/features?

Not that I know of

> goerli is the worst network for tx confirmation consistency

What's the best test network for tx confirmation consistency in your opinion? Maybe we can just swap to that one.

**Comment by prestwich** [comment]
> What's the best test network then, in your opinion

sepolia these days i think

**Comment by joshieDo** [comment]
fixed by https://github.com/foundry-rs/foundry/pull/4010
