### ISSUE TITLE
Tx fee exceeds configured cap Polygon Mumbai

### ISSUE THREAD

**Issue by jongregis** [foundry-rs/foundry#3973]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (02cb1c0 2022-12-26T10:50:48.513690086Z)

### What command(s) is the bug in?

script

### Operating System

Linux

### Describe the bug

When running a script on polygon mumbai, I get a massive tx fee when deploying and the error below.
`(code: -32000, message: tx fee (23897849040572194725236092048628893714261946156005195776.00 ether) exceeds the configured cap (100.00 ether), data: None)`

I have been able to deploy on goerli without an issue and have also tried using different rpc endpoints/deploying another contract but the same error persists.

**Comment by m-coleman** [comment]
I am also seeing this error when trying to deploy to mumbai or polygon mainnet with `forge script`:

`(code: -32000, message: tx fee (31817737348228659071582317996769352666291978645262041088.00 ether) exceeds the configured cap (1.00 ether), data: None)`

I'm also able to deploy to other networks no problem

**Comment by Flydexo** [comment]
Same error here

**Comment by mattsse** [comment]
thanks for flagging, how can I reproduce this?

cc @joshieDo

**Comment by mattsse** [comment]
@joshieDo I believe I've found the issue, fixing
