### ISSUE TITLE
Windows CI fails installing WSL

### ISSUE THREAD

**Issue by DaniPopes** [foundry-rs/foundry#3977]
### Component

Other (please describe)

### Have you ensured that all of these are up to date?

- [ ] Foundryup
- [ ] Foundry

### Operating System

None

### Describe the bug

https://github.com/foundry-rs/foundry/actions/runs/3788839912/jobs/6442218919

```log
Installing: Ubuntu 20.04 LTS


An error occurred during installation. Distribution Name: 'Ubuntu 20.04 LTS' Error Code: 0x8000ffff
```

**Comment by gakonst** [comment]
Related? https://github.com/foundry-rs/foundry/pull/3945/files

**Comment by DaniPopes** [comment]
I think it was failing because WSL was already installed? Anyway fixed by using a custom action for installing it in #4015
