### ISSUE TITLE
indicatif progress bars to do not respect output redirecting

### ISSUE THREAD

**Issue by prestwich** [foundry-rs/foundry#3981]
### Component

Other (please describe)

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### Operating System

None

### Describe the bug

Command

```
forge script MyScript --broadcast > /dev/null
```

Expected Output 
```
```

Actual Output
```
## Setting up (1) EVMs.
⠁ [00:00:00] [############################################################################################################################################################################################################################################################################] 1/1 txes (0.0s)```

**Comment by DaniPopes** [comment]
`>` redirects stdout, while I'm assuming the bars are in stderr, so try using `&> /dev/null` to [redirect both stdout and stderr](https://www.gnu.org/software/bash/manual/html_node/Redirections.html#Redirecting-Standard-Output-and-Standard-Error).

**Comment by prestwich** [comment]
do we expect non-error output to be sent to stderr?

**Comment by mattsse** [comment]
I think the reason for the output to stderr is that it can be easily ignored when compiling the output with other commands.

does `--silent` work here? if not we should make it respect the `--silent` option

**Comment by prestwich** [comment]
`--silent` produces a more output than `> /dev/null`

The reason it's so messy is because I'm running a bg process that outputs to stdout

```

⠁ [00:00:00] [#################################################################################################################################] 1/1 txes (0.0s)
Transactions saved to: /Users/james/devel/mev/mev-wallet/lib/mev-weth/broadcast/DeployMevWeth.s.sol/31337/run-latest.json

##
Waiting for receipts.
⠁ [00:00:00] [-----------------------------------------------------------------------------------------------------------------------------] 0/1 receipts (0.0s)eth_getTransactionReceipt
⠉ [00:00:00] [#############################################################################################################################] 1/1 receipts (0.0s)
##### anvil-hardhat
✅ Hash: 0xd512f2fdeb08b5443480dbbbdc1f3087f8783bd5407d4609f77c71eea930cb90
Block: 3
Paid: 0.007976276821226112 ETH (2164928 gas * 3.684315054 gwei)


Transactions saved to: /path/to/project/scripts/Script.s.sol/31337/run-latest.json



==========================

ONCHAIN EXECUTION COMPLETE & SUCCESSFUL.
Total Paid: 0.007976276821226112 ETH (2164928 gas * avg 3.684315054 gwei)

Transactions saved to: /path/to/project/scripts/Script.s.sol/31337/run-latest.json
```

**Comment by DaniPopes** [comment]
> do we expect non-error output to be sent to stderr?

Not an expert on this but I like to think of stdout as the main program output which you can redirect or pipe away, while stderr is for everything else to display to the console, like progress, download bars (cargo, curl, wget off the top of my head)
