### ISSUE TITLE
anvil misreports custom errors as no reason reverts

### ISSUE THREAD

**Issue by prestwich** [foundry-rs/foundry#3985]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### Operating System

None

### Describe the bug

Anvil should report "reverted with a custom error" when unable to pass a revert as a string. Instead it reports "without a reason string"

![photo_2022-12-28_19-29-55](https://user-images.githubusercontent.com/10149425/209888571-d6d79274-aa23-49d1-a774-7b01bfce0633.jpg)

**Comment by mattsse** [comment]
good point

the custom error decoding fn I quickly hacked together probably also needs some work

https://github.com/foundry-rs/foundry/blob/135ee3ec8befec3654507478f1e88b80e2b89c5c/evm/src/decode.rs#L222-L225

**Comment by shawnharmsen** [comment]
Would like to try this one, will add PR soon

**Comment by shawnharmsen** [comment]
oops got distracted by shitcoins, will get back on this asap
