### ISSUE TITLE
Document how `forge script` works

### ISSUE THREAD

**Issue by CodeSandwich** [foundry-rs/foundry#3988]
### Component

Documentation

### Describe the feature you would like

`forge script` is a non-trivial tool and it needs better documentation of what it's actually doing.

The existing docs are very basic, it's just a dry command description, an extremely basic tutorial and a short section about best practices. From the docs I know that there's a local EVM involved, a fork of the network, some messages are packed into transactions and sent, but some logic is executed only locally. It's unclear how it's run, or what exactly happens when `vm.broadcast` is called. Does it send a transaction right away, or does it wait for the script to end assuming that running them on the blockchain will yield the same results? What's the data flow between what's on the local EVM inside the script and what's on the actual blockchain? Can I batch broadcasted transactions to make them safer and cheaper? Can I see the real effects of the broadcasted transactions in the script? Will its results be verified on Etherscan? There's the problem of simulating of transactions, which may end up being frontrun and probably collapse the entire deployment process, why is it like this and how to work with it? How to write unit tests, does `vm.broadcast` have any effects for them?

The questions don't seem to end, but they all are probably easy to answer when you understand how `forge script` runs, it's probably quite simple, but it needs to be documented. TBH I still don't understand how it works, and I don't feel confident writing scripts, that's why I've opened this issue.

**Comment by joshieDo** [comment]
see the linked PR into `book`.

closing it here and moving the discussion there
