### ISSUE TITLE
Stuck running 'forge test'

### ISSUE THREAD

**Issue by stackcleaner** [foundry-rs/foundry#3995]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

forge test
[⠊] Compiling...
[⠰] Installing solc version 0.8.17
[⠔] Failed to install solc 0.8.17: error sending request for url (https://github.com/roynalnaruto/solc-builds/raw/ff4ea8a7bbde4488428de69f2c40a7fc56184f5e/macosx/aarch64/list.json): connection error: timed out
Error: 
error sending request for url (https://github.com/roynalnaruto/solc-builds/raw/ff4ea8a7bbde4488428de69f2c40a7fc56184f5e/macosx/aarch64/list.json): connection error: timed out

**Comment by rkrasiuk** [comment]
@wfq1kx seems like a network error while trying to download `solc` binary, did you manage to fix the issue?

**Comment by mattsse** [comment]
this looks like a dns issue

how often did you try it? can you curl the URL?

**Comment by nicholaspai** [comment]
I've tried a few times, I can load the URL in a web UI successfully. 

`curl "https://github.com/roynalnaruto/solc-builds/raw/ff4ea8a7bbde4488428de69f2c40a7fc56184f5e/macosx/aarch64/list.json"`  doesn't return anything

**Comment by mattsse** [comment]
ah yes, github has redirects try:

`curl -L "https://github.com/roynalnaruto/solc-builds/raw/ff4ea8a7bbde4488428de69f2c40a7fc56184f5e/macosx/aarch64/list.json"`

this is a bit weird and would indicate a dns issue in the HTTP client.

In the meantime you can try installing manually via https://github.com/roynalnaruto/svm-rs or manually downloading the required versions from https://github.com/roynalnaruto/solc-builds
and putting it `~/.svm/0.8.17/solc-0.8.17` like

```
~/.svm/0.8.17/solc-0.8.17 --version

solc, the solidity compiler commandline interface
Version: 0.8.17+commit.8df45f5f.Darwin.appleclang

```

**Comment by nicholaspai** [comment]
`curl -L "https://github.com/roynalnaruto/solc-builds/raw/ff4ea8a7bbde4488428de69f2c40a7fc56184f5e/macosx/aarch64/list.json"` works.

installing via `svm-rs` worked and `forge build` now succeeds, will carry like this! thanks

**Comment by zerosnacks** [comment]
Marking as resolved, please re-open if you still run into this
