### ISSUE TITLE
Weird formatting for event emitting

### ISSUE THREAD

**Issue by 0xtekgrinder** [foundry-rs/foundry#3997]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (cd8da50 2022-12-30T11:15:16.421114784Z)

### What command(s) is the bug in?

forge fmt

### Operating System

Linux

### Describe the bug

The formatting of the last parenthesis when emitting a event is a tab more than the beginning of the `emit` keyword

```solidity
emit NewVesting(
            beneficiary,
            _vestingBeneficiaries.length - 1,
            uint64(block.timestamp),
            endTimestamp
            );
```

Here is the fmt part of my `foundry.toml`.

```toml
[fmt]
line_length = 80
number_underscore = "thousands"
```

**Comment by paulrberg** [comment]
Yeah, I can confirm the same odd behavior reported by @0xtekgrinder. When the event arguments are nested on multiple lines, the final parenthesis `)` gets erroneously indented.

**Comment by PaulRBerg** [comment]
I can no longer reproduce this bug with the latest version of Forge. @rkrasiuk might have implicitly fixed this bug with one of his recent patches.

@0xtekgrinder, can you?

**Comment by 0xtekgrinder** [comment]
@PaulRBerg Doesn't looks like it's fixed, I've also checked the code and it didn't changed also
