### ISSUE TITLE
Data not persisting across delegatecall

### ISSUE THREAD

**Issue by ssadler** [foundry-rs/foundry#4002]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (cd8da50 2022-12-30T11:15:16.421114784Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

I have recently migrated my test suite to forge, and there is one test which is failing due to a storage key that is not persisting correctly:

```solidity

/* Already inside delegatecall */

_storage[key] = val;

console.log("a", _storage[key], address(this));
// a 453347196099381287746848 0x34A1D3fff3958843C43aD80F30b94c510645C316

console.log("b", _storage[key], address(this));
// b 453347196099381287746848 0x34A1D3fff3958843C43aD80F30b94c510645C316

/* delegatecall returns */

console.log("c", _storage[key], address(this));
// c 0 0x34A1D3fff3958843C43aD80F30b94c510645C316                       

console.log("d", _storage[key], address(this));
// d 0 0x34A1D3fff3958843C43aD80F30b94c510645C316                       
```

I'm confident that this is a bug in the VM because it works in the other test environment, and the exact code path where the discrepancy is produced has not changed:

```
addEdgeStorage(from.id, slot, edge);                            
console.log("b", _edges[10000000000001], address(this));        
                                                                   
return (AddEdgeResult.Added, encodeEdge(edge));                 
 
...

(bool ok, bytes memory rdata) = backend.delegatecall(call);
if (ok) {                                                 
  console.log("c", _edges[10000000000001], address(this));
}                                                         
```

**Comment by mattsse** [comment]
sorry, but I'm having a hard time interpreting these examples, could perhaps provide a repro?

**Comment by ssadler** [comment]
> sorry, but I'm having a hard time interpreting these examples, could perhaps provide a repro?

The console.log call is showing that a storage key has been lost, and confirms that the contract address hasn't changed. The second example is showing the code path between `c` and `d`. 

I'll try to get a reproducing example, prob won't be tonight tho :-) happy new year!

**Comment by ssadler** [comment]
My mistake! It's to do with the slots being different. Sorry about the noise.
