### ISSUE TITLE
`forge test` runs test files under `/lib` if they are imported in a `/src` file

### ISSUE THREAD

**Issue by jo-es** [foundry-rs/foundry#4008]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a44159a 2023-01-02T00:04:45.597843Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

`forge test` includes (runs) tests defined in `/lib` files if they are imported in `/src` files. I would expect as long as they are not inherited by tests in `/src` that they are filtered out.

**Comment by mattsse** [comment]
so tests are imported but not used?

could you provide an example?

**Comment by jo-es** [comment]
> so tests are imported but not used?

e.g. for
``` solidity
// lib/dependency/src/test/ERC20.t.sol
contract MockUser {...}

contract TestERC20 {...}
```
```solidity
// ./src/MyContract.sol
import { MockUser } from 'dependency/src/test/ERC20.t.sol'

contract MyContract {}
```
importing a contract from an external test file will result in `ERC20.t.sol` to be compiled and to be included in `/out`.

`forge test` seems to filter for `*.t.sol` in `/out`. So any file that lands in there will be part of the test run.

The fix would be for `forge test` to filter for the path as well.
