### ISSUE TITLE
feat(anvil): dumpState / loadState on a forked anvil

### ISSUE THREAD

**Issue by cheethas** [foundry-rs/foundry#4026]
### Component

Anvil

### Describe the feature you would like

Currently anvil has the capability to load and dump state to a file, enabling persistence. First introduced here: https://github.com/foundry-rs/foundry/pull/3730. 

At Aztec we have an in-house dev net running on an anvil mainnet fork. When adding the `--state` flag, it currently fails as state dumping is not yet implemented for the anvil `fork_db` back-end. I've naively hacked the functionality together here (see: https://github.com/cheethas/foundry/pull/1/files) and it appears to behave as I would expect.

If the above is satisfactory I can open a pull request iterating on my naive solution, however I thought I'd first ask in an issue, as I think there's big gotchas I've overlooked which led to it not being implemented in the pr above.

### Additional context

N/A

**Comment by mattsse** [comment]
right, this is indeed missing, and we should include this.

please submit a PR here so we can review and get it merged.

from what I can tell, this looks pretty good already

**Comment by cheethas** [comment]
closed by #4027
