### ISSUE TITLE
error: failed to run custom build command for `svm-rs-builds v0.1.10` - without any explanation why

### ISSUE THREAD

**Issue by yurivict** [foundry-rs/foundry#4037]
### Component

Other (please describe)

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

rev.159f629

### What command(s) is the bug in?

build

### Operating System

Linux

### Describe the bug

See [build log](https://people.freebsd.org/~yuri/foundry-ethereum-toolkit-g20230104.log).

I think "svm" refers to "solidity". "solidity" is already installed. The build should just use the installed version instead of rebuilding it.

FreeBSD 13.1

**Comment by mattsse** [comment]
>   thread 'main' panicked at 'Failed to fetch releases: ReqwestError(reqwest::Error { kind: Decode, source: Error("expected value", line: 1, column: 1) })', /usr/ports/finance/foundry/work/foundry-159f629/cli/cargo-crates/svm-rs-builds-0.1.10/build.rs:110:57

so it looks like the response was malformed, 

it's online though: https://binaries.soliditylang.org/linux-amd64/list.json

so likely just a fluke

**Comment by yurivict** [comment]
Is it trying to download the binary?
I already have the solc binary.

**Comment by mattsse** [comment]
this error seems to be the result of a bad response.

We haven't seen this in any release builds since, hence closing.

Please reopen if you see this again

**Comment by namn-grg** [comment]
I am facing the same error, how do I resolve this @mattsse

**Comment by yurivict** [comment]
I am also still getting this error.


> this error seems to be the result of a bad response.

What bad response?

Does it try to download anything? Package builders don't allow downloads during build. All dependencies need to be pre-installed.

We already have the "solc" executable. How to tell the build to use it?

**Comment by namn-grg** [comment]
Hey @yurivict, update: I resolved this. Follow this https://stackoverflow.com/questions/74794022/curl-28-failed-to-connect-to-raw-githubusercontent-com-port-443-connection-t.

Setting DNS 8.8.8.8 in the network resolved this for me (Mac air m1). Should work for you also

**Comment by yurivict** [comment]
@namn-grg 
It's good that you resolved this for yourself.
But I am attempting to create the FreeBSD port for foundry, and downloads aren't allowed in package builders.
We need to use the pre-installed solc exexutable.

**Comment by 0xfps** [comment]
@ArpitxGit, hi, did you manage to fix it? I just ran into the same bug installing Foundry on my PC.
