### ISSUE TITLE
cast interface changes case of functions from abi

### ISSUE THREAD

**Issue by snapple42** [foundry-rs/foundry#4039]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

derrickb@derrick-home:/mnt/src/crypto/SimpleDefiDiamond/tmp$ forge --version forge 0.2.0 (a44159a 2023-01-03T00:04:00.577535633Z) derrickb@derrick-home:/mnt/src/crypto/SimpleDefiDiamond/tmp$ cast --version cast 0.2.0 (a44159a 2023-01-03T00:04:00.577535633Z) derrickb@derrick-home:/mnt/src/crypto/SimpleDefiDiamond/tmp$ 

### What command(s) is the bug in?

cast interface

### Operating System

Linux

### Describe the bug

When converting an abi to an interface, some of the variables are changing case:

ABI: struct transHolders
Generated Interface:     function receiveTranslog(TransHolders memory _th) external;

Abi: 
  "inputs": [
      {
        "components": [
          {
            "internalType": "bool",
            "name": "deposit",
            "type": "bool"
          },
          {
            "internalType": "uint256",
            "name": "amount",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "timestamp",
            "type": "uint256"
          },
          {
            "internalType": "address",
            "name": "account",
            "type": "address"
          }
        ],
        "internalType": "struct transHolders",
        "name": "_th",
        "type": "tuple"
      }
    ],
    "name": "receiveTranslog",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },

cast interface output:
    function receiveTranslog(TransHolders memory _th) external;

I've attached the ABI:

[abiSimpleDefiDiamond.txt](https://github.com/foundry-rs/foundry/files/10353980/abiSimpleDefiDiamond.txt)

**Comment by snapple42** [comment]
Also took: 
        "internalType": "struct IDiamondCut.FacetCut []",
and turned it into:
        function updateFacets(FacetCut[] memory _diamondCut) external;

**Comment by snapple42** [comment]
Also discovered it does not generate any custom errors.

Misses:
  {
    "inputs": [],
    "name": "sdAlreadyInitialized",
    "type": "error"
  },

And any other error completely.

**Comment by zerosnacks** [comment]
The generated syntax is now valid for [sol!](https://docs.rs/alloy-sol-macro) invocations.

We don't support old ABIs anymore because they are missing the struct name, see https://github.com/alloy-rs/core/issues/349, but we do support all other ABIs.
