### ISSUE TITLE
Connection refused when run `forge build` in China.

### ISSUE THREAD

**Issue by Confucian-e** [foundry-rs/foundry#4044]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a44159a 2023-01-03T00:04:41.810446Z)

### What command(s) is the bug in?

forge build

### Operating System

macOS (Apple Silicon)

### Describe the bug

I'm in China.
When I run `forge build` it will shows a connection refused error. Looks like the url has been banned in China. But I used proxy and can visit the url by using chrome. 
<img width="946" alt="image" src="https://user-images.githubusercontent.com/46948182/210958509-7dda1e12-6973-4c10-b6cc-c0807cbaa2ba.png">

And another connection error is `unexpected end of file`.
<img width="944" alt="image" src="https://user-images.githubusercontent.com/46948182/210958755-7b136f6e-3600-48b6-a1b1-faaa9044193e.png">

If I use hardhat, I could add proxy codes in `hardhat.config` like this to solve:
![image](https://user-images.githubusercontent.com/46948182/210959039-f5f2e36d-5d31-4b56-9db8-0dea480bb117.png)

It is always hard to dev in China, but there are lots of blockchain developers in China who love foundry, hoping you could solve this. Thank you! 😘

**Comment by Confucian-e** [comment]
Downloading solc manually is somewhat cumbersome.

**Comment by Confucian-e** [comment]
Oh, I find a way to solve that.
Run `export http_proxy=http://127.0.0.1:7890 https_proxy=http://127.0.0.1:7890` first in terminal, then run `forge build`.

**Comment by Confucian-e** [comment]
Of course I would like to add a section on this to the FAQ, should I open a PR?

I edit `.zshrc` file and add these proxy codes. That's really helpful.

**Comment by mattsse** [comment]
> I would like to add a section on this to the FAQ, should I open a PR?

that'd be awesome 🙏

**Comment by Confucian-e** [comment]
I have opened PR. Thank you for your support.
