### ISSUE TITLE
Calls to etched code from contracts not deployed in test (pre-existing on-chain) don't reference the new etched logic.

### ISSUE THREAD

**Issue by ZrowGz** [foundry-rs/foundry#4055]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a44aa13 2023-01-08T00:10:33.192637Z)

### What command(s) is the bug in?

forge test --fork-url https://eth-mainnet.g.alchemy.com/v2/<INSERT_ALCHEMY_KEY> -vvvv

### Operating System

macOS (Apple Silicon)

### Describe the bug

When I `etch` my code to an existing contract address (to simulate using a new version of implementation logic for a clone factory), calls to that from existing clones & from existing contracts that aren't re-deployed in my test, do not reference the etched logic, instead using the actually deployed code.

For this, I'm etching an address with a new version & coopting existing clones, etching them  also. When initializing the new clone, it doesn't contain that new value. 

https://github.com/ZrowGz/foundry-etch-issue.git

Readme from the attached repro repo:
- This should deploy the contracts being tested & etch the code to overwrite the existing logic for those contracts. 
- It also mocks taking control of two pre-existing convex-frax vaults to be able to have their validity checked against the `vaultMap` variable stored in one of the convex contracts. 
- The implementation logic where the cloned vaults originates from is at eth mainnet address: 0x03fb8543E933624b45abdd31987548c0D9892F07
- I etch some new logic to this address.
- Calls from my test directly interact with this fine, but when the call comes from somewhere else, like the on-chain, pre-existing CloneFactory (Convex's Booster), then it uses the logic that is already actually on-chain & NOT the logic I etched to that address.

- There's two hacky ways around this:
    * First, I can just hardcode some values into the contracts before etching; ones that would have been set by the changed initializer function parameters (the last two params do not exist in real-time deployment).
    * Second option, I can go through the process of re-deploying all other contracts that interact with these & rebuilding the state to have matching variable storage (where necessary), but things like `_pid` in the booster's call to the vault initializer.

- Optimally, any logic executed at an address that was etched would be ran as if it were always that way.

- Additionally, I noticed that the state of those & any contract that interacts with it's balances are wiped. It would be dope if etching code to a contract could instead have the option to treat every contract as upgradeable & I could slip the logic in without changing state. I know that's a way bigger lift than the main issue here tho.
![Screenshot 2023-01-08 at 13 18 50](https://user-images.githubusercontent.com/80988768/211219557-8d9124a4-f513-40c3-aac6-145065fe6d53.png)

**Comment by ZrowGz** [comment]
REPRO REPO: https://github.com/ZrowGz/foundry-etch-issue

**Comment by ZrowGz** [comment]
I came across something else that was happening. I wasn't getting this a couple weeks ago:
- When I etch logic to an address, I was getting an error caused by the deletion (in the new code), which was causing it to have the classic proxy upgrade storage slot collision. 

It was like this (I'll add that part of the code into the repro repo):

old/on-chain logic:
```
struct Stake {
  bytes32 id;
  uint256 startTime;
  uint256 endTime;
  uint256 amount;
  uint256 bonus;
}
```

new etched logic:
```
struct Stake {
  uint256 startTime;
  uint256 endTime;
  uint256 amount;
  uint256 bonus;
}
```

When a function was accessing `Stake.endTime` in the new code, the value it was pulling out was actually the `amount` as everything had shifted up. These contracts weren't an upgrade, it was an etch. So the state of that address should have been wiped clean. 

A couple weeks ago, that did not happen. It also didn't preserve the state, with user balances as I had to create new balances in the testing setUp. This time, just like how it didn't overwrite the struct storage with the newly etched version, it also still retained existing user balances.

Perhaps easier than this repro would be to look at the testing repository I had created [here](https://github.com/ZrowGz/frax-transfers-testing.git)

**Comment by grandizzy** [comment]
I cannot reproduce original issue (https://github.com/ZrowGz/foundry-etch-issue) with latest  version, getting below traces

![image](https://github.com/user-attachments/assets/86dbc897-b280-4066-8f92-a0765a590faa)

and the second example fails compiling, @ZrowGz please reopen the issue if you still hit this problem with latest (additionally in a fork env you can use `vm.markPersistent` cheatcode to make sure is not replaced when rolling the fork). Thank you!
