### ISSUE TITLE
 called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by rriescog** [foundry-rs/foundry#4058]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a44aa13 2023-01-09T00:04:40.069116Z)

### What command(s) is the bug in?

forge test --contracts ./src/test/Optimism_exp.sol -vvv

### Operating System

macOS (Intel)

### Describe the bug

To reproduce please execute forge test --contracts ./src/test/Optimism_exp.sol -vvv at https://github.com/SunWeb3Sec/DeFiHackLabs

Thanks.

Here the bug log:
2023-01-09T13:16:15.412630Z ERROR sharedbackend: Failed to send/recv `basic` err=GetAccount(0x0000000000000000000000000000000000000000, 
(code: -32000, message: missing trie node af4866f7567d0d82a7d63fbfcf799b080f096055229690edfddbde3ddf3bfb65 (path ), data: None)) address=0x0000000000000000000000000000000000000000
The application panicked (crashed).
Message:  called `Option::unwrap()` on a `None` value
Location: /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/revm-2.3.1/src/evm_impl.rs:285

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   2: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>

**Comment by mattsse** [comment]
> missing trie node af4866f7567d0d82a7d63fbfcf799b080f096055229690edfddbde3ddf3bfb65

this is likely an issue with the RPC that failed to return the data

**Comment by mattsse** [comment]
closing as this is

> missing trie node

which means the endpoint you're using lacks the requested data
