### ISSUE TITLE
Etherscan verification fails for complex directory structure

### ISSUE THREAD

**Issue by haydenshively** [foundry-rs/foundry#4060]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a44aa13 2023-01-09T00:10:29.992832Z)

### What command(s) is the bug in?

forge script --broadcast --verify

### Operating System

macOS (Apple Silicon)

### Describe the bug

I've created a simple repo to reproduce the issue [here](https://github.com/haydenshively/foundry-verification-bug).
I've got a non-standard repository structure. It works perfectly for every command I've tried, with this one exception:
Etherscan verification fails for any `periphery` contract that depends on files nested inside of `core/src`. i.e., it's fine for `periphery/src/MyHelper.sol` to import `core/src/MyContract.sol`, but if `core/MyContract.sol` imports something from `core/src/<any-other-directory>/<any-other-file.sol>`, verification fails (see error below).

Interestingly, the output build json for `periphery/src/MyHelper.sol` _does_ list `core/src/<any-other-directory>/<any-other-file.sol>` as a source. For some reason it's just not being uploaded to Etherscan. 

```
Submitted contract for verification:
        Response: `OK`
        GUID: `bjzmvh3dmrwgi3r5aizqkhwytv6psxefyzfvekppi84y5hynsp`
        URL:
        https://api-goerli.etherscan.io/apiaddress/0xddcfbbe2c2fbf750c472d354fc08e8d98f01651e
Contract verification status:
Response: `NOTOK`
Details: `Pending in queue`
Contract verification status:
Response: `NOTOK`
Details: `Fail - Unable to verify. Solidity Compilation Error: Source "lib/core/src/libraries/Foo.sol" not found: File not found. Searched the following locations: "".`
Contract failed to verify.
```

**Comment by davidbrai** [comment]
I've had a similar issue, what worked as a temporary fix is applying the following change to my `foundry.toml`:

```diff
[profile.default]
 src = 'contracts'
-libs = ['lib', '../../node_modules']
+libs = ['lib', '/full-path-to-project/my-monorepo/node_modules']
```

**Comment by ryanio** [comment]
+1 i am also having the same issue as @Fiddlekins

**Comment by ryanio** [comment]
Adding `auto_detect_remappings = false` to `foundry.toml` fixed this issue for me!

**Comment by Evalir** [comment]
So, this is expected behavior regarding ambiguous paths: https://book.getfoundry.sh/forge/deploying?highlight=verify-contra#known-issues ; sadly etherscan only really handle relative paths. @ryanio 's fix works!

**Comment by SensationalShubham** [comment]
May I work on this issue, if it's still there?

**Comment by charlescrain** [comment]
> Adding `auto_detect_remappings = false` to `foundry.toml` fixed this issue for me!

This worked for me. No idea why it fixes it but adding a foundry.toml like this:

```toml
[profile.default]
 auto_detect_remappings = false
```
 caused it to work.

**Comment by DJViau** [comment]
I spent some time running `forge remappings` with `auto_detect_remappings = true` and `auto_detect_remappings = false` and comparing the two outputs against the file Etherscan complained about,but for me, leaving `auto_detect_remappings = false` and explicitly adding a remapping from a submodule to my top level foundry.toml did the job.

**Comment by grandizzy** [comment]
we're going to close this as it's a known and documented limitation, more work could be done post v1.0. thank you!
