### ISSUE TITLE
Add gas price estimate in forge script summary

### ISSUE THREAD

**Issue by outdoteth** [foundry-rs/foundry#4064]
### Component

Forge

### Describe the feature you would like

I would like to be able to view the estimated gas price here after running `forge script`:

<img width="399" alt="Screenshot 2023-01-10 at 12 45 19" src="https://user-images.githubusercontent.com/37438950/211593784-578d0574-2d09-44c4-bad9-9d159ebeee45.png">

**Comment by Evalir** [comment]
Happy to take on this! For the formatting, should we show the amount in Gwei, or do something akin to what etherscan does (that is, show the amount in ether and then in gwei)?

**Comment by mds1** [comment]
@outdoteth Is this issue asking to show the gas price that was used to convert the amount of gas used into an ETH estimate?

If so, how does this formatting look for @Evalir to implement? (I also changed the text on the bottom line a bit)

```
Estimated total gas used for script: 500123

Estimated total cost: 0.234 ETH (at 10 gwei)
```

**Comment by outdoteth** [comment]
Hm I think it would be better to have it on it's own separate line. The precision in the screenshot is nice and does not abstract anything away. It becomes a bit hard to read like this imo:

```
Estimated total gas used for script: 500123

Estimated total cost: 0.234234234234234  ETH (at 10 gwei)
```

vs:

```
Estimated total gas used for script: 500123

Estimated gas price: 10 gwei

Estimated total cost: 0.234234234234234  ETH
```

**Comment by Evalir** [comment]
That sounds good to me—I personally like having everything on 3 lines as it seems pretty clear. wdyt @mds1? once we're aligned I can get started on this.
