### ISSUE TITLE
foundryup fails because of `testdata/lib/forge-std`

### ISSUE THREAD

**Issue by KholdStare** [foundry-rs/foundry#4065]
### Component

Foundryup

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What command(s) is the bug in?

foundryup -C a71e084368822d3a658731d4e5e853213767ec91

### Operating System

Linux

### Describe the bug

This commit: https://github.com/foundry-rs/foundry/commit/12ad1c1ffab410fce96d577270cbb167f72fdb6e added a submodule that doesn't go anywhere, now `git submodule update --init --recursive` fails, and specifically fails when running `foundryup` with a previous commit, since it needs to use git.

Here is the error I get:

```
fatal: No url found for submodule path 'testdata/lib/forge-std' in .gitmodules
foundryup: command failed: git submodule update --init --recursive
```

As a suggestion, would it be possible to some kind of limited CI test that foundryup actually works so its functionality doesn't regress in the future?

**Comment by mattsse** [comment]
oh my bad, overlooked that.

the submodule should be removed. nice catch
