### ISSUE TITLE
forge doc doesn't recognise fallback

### ISSUE THREAD

**Issue by odyslam** [foundry-rs/foundry#4069]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge doc PR

### What command(s) is the bug in?

forge doc

### Operating System

None

### Describe the bug
```
Error:
Failed to parse Solidity code for /Users/odysseas/code/nomad/monorepo/packages/contracts-core/contracts/test/utils/MockImpl.sol
Debug info: [Diagnostic { loc: File(18, 410, 418), level: Error, ty: ParserError, message: "unrecognised token 'fallback', expected \"(\", \"case\", \"default\", \"error\", \"leave\", \"revert\", \"switch\", identifier", notes: [] }]
```

for https://github.com/nomad-xyz/monorepo/blob/main/packages/contracts-core/contracts/test/utils/MockImpl.sol

**Comment by rkrasiuk** [comment]
i will add a warning if the parser errors out
