### ISSUE TITLE
FoundryBook: update pattern flags documentation

### ISSUE THREAD

**Issue by QGarchery** [foundry-rs/foundry#4075]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9256265 2023-01-12T00:06:27.184842156Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

The documentation [here](https://book.getfoundry.sh/reference/config/testing) seems to be out of date for the pattern flags `--no-match-contract`, `--match-contract`, `--no-match-test`, and `--match-test`.
For `--match-contract`:
- the environment variable seems to be `FOUNDRY_MATCH_CONTRACT` and not `FOUNDRY_CONTRACT_PATTERN`
- the `foundry.toml` variable seems to be `match_contract` and not `contract_pattern`

**Comment by Rubilmax** [comment]
Related to https://github.com/foundry-rs/foundry/issues/3684
