### ISSUE TITLE
`cast run` should use `mixHash` for `block.difficulty` after merge

### ISSUE THREAD

**Issue by cxkoda** [foundry-rs/foundry#4086]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

cast 0.2.0 (9256265 2023-01-13T00:04:00.237556113Z)

### What command(s) is the bug in?

cast run

### Operating System

Linux

### Describe the bug

If a contract interaction depends on `block.difficulty`, a local execution via `cast run` yields wrong results because the ~`difficulty`~ `mixHash` is not fetched from the node provider. It is `0` by default.

To reproduce see the following contract interaction: https://goerli.etherscan.io/tx/0x57c39e52c6a3a4cafa3075b171cebb299b891300f6de4a711db24e0997d0a4f9#eventlog which logged `block.difficulty` by emitting an event with data `0x8c712d4cab1b6508e03e5c5ba69d496707cd60a585dd7a33d27e34013ab783a4`.
A local execution via
```bash
cast run 0x57c39e52c6a3a4cafa3075b171cebb299b891300f6de4a711db24e0997d0a4f9 --rpc-url $GOERLI_RPC_URL
``` 
yields the following output
```bash
Executing previous transactions from the block.
Traces:
  [1178] DifficultyLogger::log() 
    ├─ emit Difficulty(: 0)
    └─ ← ()

```

**Comment by mattsse** [comment]
> It is 0 by default

this is the fetched block difficulty because difficulty is no longer used in POS, you should not rely on it: https://eips.ethereum.org/EIPS/eip-4399

see also

```
cast rpc eth_getBlockByHash "0x4558ab5459cc322d4516ff360158631bbbc32e50f4c1532229ac631f56731e91" false --rpc-url $GOERLI_RPC_URL | jq

```

**Comment by cxkoda** [comment]
Why should it not be used? The difficulty opcode `0x44` is still in use after EIP4399 and MUST return `mixHash`. The EIP just argues for a repurposing + rename of the opcode, not a deprecation. The deprecation only relates to the field in the block header as far as I have understood. Also you can see from the goerli transaction that it clearly still works there.

**Comment by cxkoda** [comment]
Why should it not be used? The difficulty opcode `0x44` is still in use after EIP4399 and MUST return `mixHash`. The EIP just argues for a repurposing + rename of the opcode, not a deprecation. The deprecation only relates to the field in the block header as far as I have understood. Also you can see from the goerli transaction that it clearly still works there.
I'm sorry, my issue was probably a bit misleading because I wrote that the correct `difficulty` needs to be fetched form the node provider - this should of course be `mixHash`.

**Comment by mattsse** [comment]
right, we should use mixHash instead of difficulty when after merge on a per-chain basis.

this is kinda cursed, tbh.
