### ISSUE TITLE
Support using forge as a rust library

### ISSUE THREAD

**Issue by seunlanlege** [foundry-rs/foundry#4087]
### Component

Forge

### Describe the feature you would like

By exposing some of forge's internals, we can enable rust developers write tests for their solidity code in rust. I've already implemented some of those internals here: (https://github.com/polytope-labs/solidity-merkle-trees/blob/seun/merkle-multi-proof/test/src/helpers.rs#L94-L151).

And i've implemented a test using those internals here: (https://github.com/polytope-labs/solidity-merkle-trees/blob/seun/merkle-multi-proof/test/src/lib.rs).

The only issue to make this support complete is that foundry doesn't seem to deploy user libraries when used as a lib, which is needed for the test contract.

Happy to send a PR to this effect just need some pointers on how to deploy user solidity libs.

**Comment by mattsse** [comment]
all commands should be available if you import the cli crate?

**Comment by seunlanlege** [comment]
> all commands should be available if you import the cli crate?
> 
> 
> 
> accepting PRs that make this more convenient though

Do you mind posting some sort of pseudocode or code references?

I'm of the opinion forge should provide first class support for this.

**Comment by mattsse** [comment]
> I'm of the opinion forge should provide first class support for this.

for what exactly?

sorry I'm having a hard time trying to understand what the actual problem here is, because you can just import the `cli` crate and use all commands.

what am I missing?

**Comment by seunlanlege** [comment]
> > I'm of the opinion forge should provide first class support for this.
> 
> for what exactly?
> 
> sorry I'm having a hard time trying to understand what the actual problem here is, because you can just import the `cli` crate and use all commands.
> 
> what am I missing?

I would like to use it like so: https://github.com/polytope-labs/solidity-merkle-trees/blob/578b600a9ea9eedd52ef9bb32b66e67af3d2fc03/test/src/lib.rs#L54
