### ISSUE TITLE
Display fuzzing results when exiting terminal

### ISSUE THREAD

**Issue by 0xPhaze** [foundry-rs/foundry#4089]
### Component

Forge

### Describe the feature you would like

Sometimes I set the fuzz runs to a high limit and let it run for a while. It would be nice to not have all the fuzz effort wasted and be able to see the output of a longer run, if I accidentally set the fuzz runs too high. Currently when aborting via `CMD + C` the terminal just exits.

Always displaying all the information could be a bit annoying however, so ideally foundry would know to display the results regardless of the abort if say, over a 30 seconds have passed since fuzzing.

Related:
- #990

**Comment by mds1** [comment]
If nothing is printed to the terminal, then up to that point everything was passing. If a test fails the info is shown in the terminal right away. Going to close this since I'm not sure what other results you'd want to see, but feel free to reopen if I'm misunderstanding the request
