### ISSUE TITLE
propagate revert reasons on forked anvil

### ISSUE THREAD

**Issue by dape111** [foundry-rs/foundry#4095]
### Component

Anvil

### Describe the feature you would like

Hello
When calling "evm_mine", 0x0 response is returned and the gas usage and revert message of each tx would show up in console like in pic attached, it would be great if this output where a list of mined txs and their status and revert reason show also on "evm_mine" rpc call since it is not possible to simulate an `eth_call` against that block to get the revert reason if there was a tx in same block that this tx depends on.
Thanks.

![image](https://user-images.githubusercontent.com/101391182/212520667-83cd1715-37b6-4834-a041-a59bc264e2b3.png)

**Comment by mattsse** [comment]
I'm not exactly sure if I understand that correctly.

> it would be great if this output where a list of mined txs and their status

isn't that already the case in the attached picture?

> and revert reason show also on "evm_mine" rpc call 

wdym here exactly? return this in the RPC response?

not entirely sure yet what we'd need to change
