### ISSUE TITLE
Show message if script is taking long due to RPC requests

### ISSUE THREAD

**Issue by devanoneth** [foundry-rs/foundry#4104]
### Component

Forge

### Describe the feature you would like

I had a large script which did a lot of contract calls. I was not getting any feedback for why the script was taking so long but eventually narrowed it down to the requirement for many RPC requests.

It would be nice if in a long-running script, after some time simulating (e.g. 15 seconds), a message was printed to let the user know the issue is that the simulation has lots of ongoing RPC requests. Perhaps a loader would be even better, because no feedback is received until the script has completed.

**Comment by grandizzy** [comment]
scrip is using now indicatif library to display progress, please retest with latest version and reopen if still an issue. thank you!
