### ISSUE TITLE
Native tracers support

### ISSUE THREAD

**Issue by ValentinAndreevich** [foundry-rs/foundry#4110]
### Component

Anvil

### Describe the feature you would like

[debug_traceCall](https://geth.ethereum.org/docs/rpc/ns-debug#debug_tracecall) is useful for getting an execution trace of `eth_call`, expecially when it comes to tx simulation. That will be very nice if you are able to add `callTracer` support as a tracing option.

**Comment by vulntor** [comment]
+1

**Comment by chibitanaka** [comment]
+1, `callTracer` support would be nice

**Comment by mattsse** [comment]
this is being worked on separately on https://github.com/paradigmxyz/reth
where these are already implemented, there will soon be some consolidation efforts to reduce duplicate code.

If someone wants to add this functionality via copy-paste to anvil until this is done, I'm happy to give pointers.

**Comment by lljxx1** [comment]
+1

**Comment by Billy1900** [comment]
One more requirement, I got the trace like this:
```json
{
    "depth": 1,
    "gas": 29978936,
    "gasCost": 3,
    "op": "PUSH1",
    "pc": 0,
    "stack": []
},
```
however, when I use `debug_traceTransaction`, I got 
```json
{
    "depth": 0,
    "error": "",
    "gas": 39469,
    "gasCost": 3,
    "memory": [],
    "op": "PUSH1",
    "pc": 0,
    "stack": [],
    "storage": {}
},
```

can we add storage and memory part?

**Comment by cesarhuret** [comment]
> this is being worked on separately on https://github.com/paradigmxyz/reth where these are already implemented, there will soon be some consolidation efforts to reduce duplicate code.
> 
> If someone wants to add this functionality via copy-paste to anvil until this is done, I'm happy to give pointers.

could you give me some pointers?

**Comment by Billy1900** [comment]
> > this is being worked on separately on https://github.com/paradigmxyz/reth where these are already implemented, there will soon be some consolidation efforts to reduce duplicate code.
> > If someone wants to add this functionality via copy-paste to anvil until this is done, I'm happy to give pointers.
> 
> could you give me some pointers?

what do you mean pointers, the storage and memory like
```json
{
    "depth": 0,
    "error": "",
    "gas": 39469,
    "gasCost": 3,
    "memory": [],
    "op": "PUSH1",
    "pc": 0,
    "stack": [],
    "storage": {}
},
```

**Comment by cesarhuret** [comment]
> > > this is being worked on separately on https://github.com/paradigmxyz/reth where these are already implemented, there will soon be some consolidation efforts to reduce duplicate code.
> > > If someone wants to add this functionality via copy-paste to anvil until this is done, I'm happy to give pointers.
> > 
> > 
> > could you give me some pointers?
> 
> what do you mean pointers, the storage and memory like
> 
> ```json
> {
>     "depth": 0,
>     "error": "",
>     "gas": 39469,
>     "gasCost": 3,
>     "memory": [],
>     "op": "PUSH1",
>     "pc": 0,
>     "stack": [],
>     "storage": {}
> },
> ```

pointers meaning instructions/help on how to implement this into anvil

**Comment by Billy1900** [comment]
> > > > this is being worked on separately on https://github.com/paradigmxyz/reth where these are already implemented, there will soon be some consolidation efforts to reduce duplicate code.
> > > > If someone wants to add this functionality via copy-paste to anvil until this is done, I'm happy to give pointers.
> > > 
> > > 
> > > could you give me some pointers?
> > 
> > 
> > what do you mean pointers, the storage and memory like
> > ```json
> > {
> >     "depth": 0,
> >     "error": "",
> >     "gas": 39469,
> >     "gasCost": 3,
> >     "memory": [],
> >     "op": "PUSH1",
> >     "pc": 0,
> >     "stack": [],
> >     "storage": {}
> > },
> > ```
> 
> pointers meaning instructions/help on how to implement this into anvil

I do not dive deep into how we implement this. But I think you could refer to how `debug_traceTransaction` does. It won't be hard.

**Comment by zerosnacks** [comment]
This is supported as of https://github.com/foundry-rs/foundry/pull/8375

Let me know if this is incorrect
