### ISSUE TITLE
forge fmt: Additional formatting features 

### ISSUE THREAD

**Issue by 0xfarhaan** [foundry-rs/foundry#4116]
### Component

Forge

### Describe the feature you would like

Hey folks from Maple here, we would like to switch to using `forge fmt`, currently we're doing everything manually so this would save us alot of time and we're sure others could benefit too. Also happy to help with implementing! 

Here are a list of options we would like in the formatter to make the switch:

1. A new line at the top and bottom of top level declarations

```solidity
interface interfaceName {

    code;
    code;
    code;

}

contract contractName1 {

    code;
    code;

}
```

2. Ignore section headers (as they currently get reformatted)
```solidity
/**************************************************************************************************************************************/
/*** Helpers                                                                                                                        ***/
/**************************************************************************************************************************************/
```

3. For assertions of the same type, the parameters must be aligned so that the second set of parameters are left justified for each code block (this can be focussed around test helpers to start with)
```solidity
assertEq(mockToken.balanceOf(address(treasury)), 0);    
assertEq(mockToken.balanceOf(address(mpl)),      100);  
assertEq(mockToken.balanceOf(address(holder1)),  0); 
assertEq(mockToken.balanceOf(address(holder2)),  0);    

assertEq(token.fundsBalance(),   60_000);
assertEq(token.pointsPerShare(), expectedPointsPerShare);
```

4. Align the assignment operator for code blocks
```solidity
function increaseCustodyAllowance(address custodian, uint256 amount) external override {
    uint256 oldAllowance      = custodyAllowance[msg.sender][custodian];
    uint256 newAllowance      = oldAllowance.add(amount);
    uint256 newTotalAllowance = totalCustodyAllowance[msg.sender].add(amount);

    PoolLib.increaseCustodyAllowanceChecks(custodian, amount, newTotalAllowance, balanceOf(msg.sender));

    custodyAllowance[msg.sender][custodian] = newAllowance;
    totalCustodyAllowance[msg.sender]       = newTotalAllowance;
}

```

5. Add a space after the opening and before the closing bracket of a tuple
```solidity
( , , uint256 foo, uint256 bar, , uint256 baz, , , ) = functionName();
( success, ) = functionName();
```

6. Left justify align state variables by longest type for each code block
```solidity
uint256 internal nextDelegateOriginationFee;
uint256 internal nextDelegateServiceFee;

uint256 internal start;

// Helper mapping to assert differences in balance
mapping(address => uint256) internal partialAssetBalances;

Asset        internal collateralAsset;
Asset        internal fundsAsset;
Globals      internal globals;
PoolDeployer internal deployer;

FeeManager        internal feeManager;
LoanManager       internal loanManager;
Pool              internal pool;
PoolDelegateCover internal poolCover;
PoolManager       internal poolManager;
WithdrawalManager internal withdrawalManager;
``` 

7. Align imports by the furthest 'from' keyword in each code block
```solidity
import { Address, TestUtils } from "../modules/contract-test-utils/contracts/test.sol";

import { MockERC20 as Asset } from "../modules/erc20/contracts/test/mocks/MockERC20.sol";

import { MapleGlobals as Globals } from "../modules/globals-v2/contracts/MapleGlobals.sol";
import { NonTransparentProxy }     from "../modules/globals-v2/modules/non-transparent-proxy/contracts/NonTransparentProxy.sol";

import { Liquidator }            from "../modules/liquidations/contracts/Liquidator.sol";
import { LiquidatorFactory }     from "../modules/liquidations/contracts/LiquidatorFactory.sol";
import { LiquidatorInitializer } from "../modules/liquidations/contracts/LiquidatorInitializer.sol";

import { MapleLoan as Loan }                       from "../modules/loan-v400/contracts/MapleLoan.sol";
import { MapleLoanFactory as LoanFactory }         from "../modules/loan-v400/contracts/MapleLoanFactory.sol";
import { MapleLoanFeeManager as FeeManager }       from "../modules/loan-v400/contracts/MapleLoanFeeManager.sol";
import { MapleLoanInitializer as LoanInitializer } from "../modules/loan-v400/contracts/MapleLoanInitializer.sol";
```

**Comment by gakonst** [comment]
Open to all of these! Would recommend doing 1 PR per, and thinking about "what does the config look like" for these, as Maple has a pretty unique formatting style which some may not want to use.

**Comment by 0xfarhaan** [comment]
Yup agree a separate PR for each. In terms of config had the following suggestion for each:

1. top_level_spacing: bool
2. ignore_section_headers: bool
3. assertion_alignment: bool (could be further extended with different options later)
4. assignment_alignment: bool
5. tuple_spacing: bool
6. state_variable_alignment: bool
6. import_alignment: {false, "left_justify_from"} (I can foresee options being added here so being specific would help)

**Comment by rkrasiuk** [comment]
@0xfarhaan my recommendation is to delay 2. since #3786 refactors comment handling. otherwise, these requests fall into two categories - spacing and alignment. spacing most likely would have to be handled on-site - embedding logic into visiting tuples and function calls. as for alignment, there could be a nice abstracted helper method for doing this, dunno yet 💭

**Comment by lucas-manuel** [comment]
Hey all, going to make individual issues to discuss these and provide diff examples so we can prioritize and revive this awesome future feature!

**Comment by zerosnacks** [comment]
Marking as duplicate considering the majority of the issues raised have been split out into individual tickets:

- https://github.com/foundry-rs/foundry/pull/4212
- https://github.com/foundry-rs/foundry/issues/5074
- https://github.com/foundry-rs/foundry/issues/5074

@0xfarhaan please create individual tickets for each case not covered by this and you would like to see implemented
