### ISSUE TITLE
`cast run --debug` failed if `ETHERSCAN_API_KEY` is set

### ISSUE THREAD

**Issue by NIC619** [foundry-rs/foundry#4117]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

cast 0.2.0 (4dc05d2 2023-01-18T00:15:05.61036Z)

### What command(s) is the bug in?

cast run --debug 0x72ee56dda15c2cd6c201c0d9bdc0ebd5b3b90d5c0bb88e5c8d014fc25f53a094

### Operating System

None

### Describe the bug

Command to debug a Goerli transaction: `cast run --debug 0x72ee56dda15c2cd6c201c0d9bdc0ebd5b3b90d5c0bb88e5c8d014fc25f53a094` failed when compiling one of the contract.

Error message:
```bash
> cast run --debug 0x72ee56dda15c2cd6c201c0d9bdc0ebd5b3b90d5c0bb88e5c8d014fc25f53a094
Executing previous transactions from the block.
Compiling: Tokenlon 0x085966ee3e32a0da16467569512535d38626b547
Compiling: TransparentUpgradeableProxy 0x142e4eb0b0dada349e483e355c31ff3495b85ff7
Compiling: Spender 0x5508ef5ea37e42952d470582882b5bf3514265e3
Compiling: AllowanceTarget 0x63dd46f09c2eab341b6affa8261024e85cdf4531
Compiling: TetherToken 0xa93ef9215b907c19e739e2214e1aa5412a0401b5
Compiling: WETH9 0xb4fbf271143f4fbf7b91a5ded31805e42b2208d6
Compiling: LimitOrder 0xe2e5e33aec661241b3853a4460f7aaba65e950c3
Compiling: UserProxy 0xe8b436dca7d20151bc09410a71468cf9c6de397e
Compiling: PermanentStorage 0xfa0a2d2a9174ac175e74fff71b9ea53cbeafc064
Error:
Compiler run failed
error[2314]: ParserError: Expected '{' but got 'constant'
  --> TetherToken/Contract.sol:77:35:
   |
77 |     function totalSupply() public constant returns (uint);
   |                                   ^^^^^^^^
```

~~This is the [TetherToken contract](https://goerli.etherscan.io/address/0xa93ef9215b907c19e739e2214e1aa5412a0401b5#code) it was trying to compile. It is verified on etherscan and the compiler version is specified on the etherscan. The error seems like it's compiling the contract with a different compiler. I tried compile the contract with the compiler version specified on etherscan (`v0.4.18+commit.9cf6e910`) and it succeeded.~~

~~**Expected behavior: it should compile the contract with the compiler version specified on etherscan**~~

When `ETHERSCAN_API_KEY` is set, it ran into the error shown above.

**Expected behavior: it should work fine even if `ETHERSCAN_API_KEY` is set**

**Comment by mattsse** [comment]
cc @rkrasiuk this looks solang-parser related I think

**Comment by rkrasiuk** [comment]
this looks like a solc error. also there shouldn't be a case where `cast run` invokes the parser. hmmm

**Comment by rkrasiuk** [comment]
just ran that command against goerli and there were no obvious errors

**Comment by NIC619** [comment]
> just ran that command against goerli and there were no obvious errors

Thanks for the info. I inspect the env variables I set and found that when `ETHERSCAN_API_KEY` is set, it will result in the error shown above. Everything works if `ETHERSCAN_API_KEY` is not set.
