### ISSUE TITLE
Silently ignore custom tags

### ISSUE THREAD

**Issue by PraneshASP** [foundry-rs/foundry#4118]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (4dc05d2 2023-01-18T00:12:40.613647591Z)

### What command(s) is the bug in?

forge doc

### Operating System

Linux

### Describe the bug

I tried to generate docs using `forge doc`. My contract had some comments with custom tags like `@audit`. The command abruptly failed throwing the following error: 

```sh
Failed to parse source: unknown comment tag: audit
```

Can the custom tags be silently ignored when parsing?

**Comment by jaybuidl** [comment]
Same problem here:
```
Failed to parse source: unknown comment tag: authors:
```

**Comment by greenlucid** [comment]
Apparently, it expects custom tags to be preceded by `"custom:"` ?
https://github.com/foundry-rs/foundry/blob/e1eb91208b304ec9c44831db2945cd1d6ac209cb/doc/src/parser/comment.rs#L40

[Natspec in 0.8.17](https://docs.soliditylang.org/en/v0.8.17/natspec-format.html#tags) also expects this

> Custom tags start with @custom: and must be followed by one or more lowercase letters or hyphens. It cannot start with a hyphen however. They can be used everywhere and are part of the developer documentation.

**Comment by rkrasiuk** [comment]
reopening, because it shouldn't prevent doc generation
