### ISSUE TITLE
`forge test` hangs when using `balanceOf` function for mainnet NFT contracts

### ISSUE THREAD

**Issue by megsdevs** [foundry-rs/foundry#4120]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (4dc05d2 2023-01-18T00:12:53.425763Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Intel)

### Describe the bug

`forge test` hangs indefinitely after contract compilation for tests that use the NFT `balanceOf(address)` function for already deployed mainnet contracts during mainnet fork mode.

e.g.
Demonstrated in this repo: https://github.com/megsdevs/Foundry-NFT-Testing.
Command:
```
forge test --fork-url https://rpc.ankr.com/eth --match-contract ShellzOrbTest
```
Sample output:
```
[⠒] Compiling...
[⠊] Compiling 1 files with 0.8.17
[⠢] Solc 0.8.17 finished in 5.47s
Compiler run successful

```
the test hangs indefinitely at this point...

I can get around the issue by not using `balanceOf` or by deploying new NFT contract instances during the test. 

I also know there is not an issue with the real mainnet contracts as i can query `balanceOf` through etherscan: https://etherscan.io/token/0xe17827609ac34443b3987661f4e037642f6bd9ba#readProxyContract#F1 with the example address used in the test "0xea831d27E0E52b4dC32F42A5c4C5cBfd9b6D4a58".

It is preferable to be able to interact with the deployed mainnet contracts during fork testing, so I would love to find any resolution to this issue!

**Comment by gakonst** [comment]
I can repro, couple things:

```
RUST_LOG=forge=trace,foundry_evm=trace,ethers=trace  forge test --fork-url https://rpc.ankr.com/eth --match-contract ShellzOrbTest --match-test testBalance
```

This gives a lot more visibility into what's going on.

This hangs on a _ton_ of `eth_getStorageAt` calls. I am not sure why that would be happening.

```
023-01-18T22:17:54.113763Z TRACE rpc{method="eth_getStorageAt" params="[\"0xe17827609ac34443b3987661f4e037642f6bd9ba\",\"0x81fe90a866a48a634a12852c1be675b683a22307409932a7443b8029347be756\",\"0xfacd8f\"]"}: ethers_providers::provider: tx
2023-01-18T22:17:54.286254Z TRACE rpc{method="eth_getStorageAt" params="[\"0xe17827609ac34443b3987661f4e037642f6bd9ba\",\"0x81fe90a866a48a634a12852c1be675b683a22307409932a7443b8029347be756\",\"0xfacd8f\"]"}: ethers_providers::provider: rx="\"0xffffffff7f7ffff7bf7fff7fefbfbffffffffbbffebffbbfffffffffbf5fffff\""
2023-01-18T22:17:54.286433Z TRACE rpc{method="eth_getStorageAt" params="[\"0xe17827609ac34443b3987661f4e037642f6bd9ba\",\"0x435daec636ce435a90bde0aeec309a303a359a854c5a51b7d6a5a941d6db6094\",\"0xfacd8f\"]"}: ethers_providers::provider: tx
2023-01-18T22:17:54.349716Z TRACE rpc{method="eth_getStorageAt" params="[\"0xe17827609ac34443b3987661f4e037642f6bd9ba\",\"0x435daec636ce435a90bde0aeec309a303a359a854c5a51b7d6a5a941d6db6094\",\"0xfacd8f\"]"}: ethers_providers::provider: rx="\"0x0000000000000000000000005a70ec52e977b50c9fc12ca0aa6d5e26e7c62291\""
<..>
```

This makes me think that the token implementation is buggy / has some kind of infinite loop going on? @megsdevs mentioned that indeed leaving it run for a while completes:

```
[⠊] Compiling...
No files changed, compilation skipped

Running 4 tests for test/ShellzOrb.t.sol:ShellzOrbTest
[PASS] testBalanceOf() (gas: 61256507)
[PASS] testImmutableVariables() (gas: 26613)
[PASS] testOnlyInitializeOnce() (gas: 18230)
[PASS] testOwner() (gas: 24760)
Test result: ok. 4 passed; 0 failed; finished in 464.11s
```

**Comment by megsdevs** [comment]
I'd say you can close this. Upon closer inspection the `balanceOf` function for this particular NFT appears to be very inefficient by looping through every minted token to check the owner rather than keeping a balances mapping like the OZ standard.

<img width="660" alt="Screenshot 2023-01-19 at 03 38 16" src="https://user-images.githubusercontent.com/57240925/213328618-42a2439c-e7ab-46c1-a248-3cc3dd9ed934.png">

**Comment by gakonst** [comment]
SGTM - yeah thought so
