### ISSUE TITLE
Add support for arbitrary type max/mins in Cast

### ISSUE THREAD

**Issue by x676f64** [foundry-rs/foundry#4123]
### Component

Cast

### Describe the feature you would like

Inspired by PaulRBerg to add this feature request. It would be great if we could access arbitrary max/mix type values instead of just uint256/int256. It would be great if we could have access to a feature that basically does `type(uint).(max|min)`

I would propose a format like so:
```
# cast max uint8
255

# cast min int8
-128
```
And something like the following for abbreviations:
```
# cast mau8
255
# cast mi8
-128
```
Bonus points if you could add `--decimal/--dec` and `--hex` flags so we could display it in either format.

**Comment by mds1** [comment]
There is currently `cast --max-uint`, `cast --max-int`, and `cast --min-int` commands, which return values for the 256 bit types. I'd suggest adding an optional arg to that command which specifies the bit size instead of introducing a new command, e.g. `cast --max-uint 128`

**Comment by x676f64** [comment]
> There is currently `cast --max-uint`, `cast --max-int`, and `cast --min-int` commands, which return values for the 256 bit types. I'd suggest adding an optional arg to that command which specifies the bit size instead of introducing a new command, e.g. `cast --max-uint 128`

That would work for me.
