### ISSUE TITLE
Alphabetical sorting of gas snapshot results

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/foundry#4127]
### Component

Forge

### Describe the feature you would like

It would be nice to have an `--alpha` or `--alphabetical` flag in `forge snapshot` that would sort the gas snapshot results alphabetically.

**Comment by mattsse** [comment]
should this be the default?

**Comment by mattsse** [comment]
we can just sort them here:

https://github.com/foundry-rs/foundry/blob/5cdba88f49fadf786bbecfc932281119026a0489/cli/src/cmd/forge/snapshot.rs#L291-L302

**Comment by PaulRBerg** [comment]
> should this be the default?

Sounds good to me!
