### ISSUE TITLE
Chisel - type(int[N]).min is incorrect

### ISSUE THREAD

**Issue by x676f64** [foundry-rs/foundry#4130]
### Component

Chisel

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

chisel 0.1.0

### What command(s) is the bug in?

chisel

### Operating System

None

### Describe the bug

See the following screenshot for some examples.
![image](https://user-images.githubusercontent.com/53136615/213537062-88a547a9-65df-4044-a309-eb6078d438c8.png)

It appears that calculating the minimum value for signed integer types is incorrect.

**Comment by DaniPopes** [comment]
I'll take this on, will require a bit of refactoring in the type parsing logic
