### ISSUE TITLE
Add cast command to generate ethers-rs bindings

### ISSUE THREAD

**Issue by fulminmaxi** [foundry-rs/foundry#4132]
### Component

Cast

### Describe the feature you would like

I'd like to be able to generate ethers-rs bindings for a contract using cast directly. This would greatly improve prototyping speed for scripts and bots as you could just take a contract from etherscan and get rust bindings to it.

**Comment by mattsse** [comment]
do you know about `forge bind`?

**Comment by fulminmaxi** [comment]
Yes, I use forge bind regularly. I opened this issue because having this directly inside cast would be much more convenient for when one is working in Rust only with no solidity project set up

**Comment by mattsse** [comment]
that makes sense,
what would be the ideal DX here? `cast bind <contract.sol>`?

**Comment by fulminmaxi** [comment]
Imho it should have the exact same inputs as `cast interface`, so:
- A solidity file
- An address (to use to pull the ABI from etherscan if it exists)
- An ABI / artefact

While the outputs should resemble `forge bind`, so the choice could be between:
- A file
- A crate
- A module

wdyt?

**Comment by mattsse** [comment]
that makes sense, 

happy to mentor a PR for this otherwise this has lower priority at this point

**Comment by chirag-bgh** [comment]
Hey, I would like to work on this one.

**Comment by mattsse** [comment]
nice will probably end up a mix of `forge bind` and the preprocessing of `cast interface` (to get the ABI object)

it's likely that we can reuse a lot of `forge bind`

feel free to open a draft PR if you're blocked and we can discuss next steps.

**Comment by chirag-bgh** [comment]
sure thanks!
