### ISSUE TITLE
Discussion: Rename "Remove" to "Uninstall" or "Install" to "Add"

### ISSUE THREAD

**Issue by CyrusOfEden** [foundry-rs/foundry#4135]
### Component

Forge

### Describe the feature you would like

Currently we have `forge install` and `forge remove` — we're mixing up conventions and this is a little smelly.

I'd recommend we move to one of the following, based on conventions set up by other package managers:

1. `forge add` and `forge remove`
2. `forge install` and `forge uninstall`

For example, `yarn` uses `add` and `remove`. `npm`, `pip`, and `gem` use `install` and `uninstall`.

I like `add`/`remove` because there's less to type, but I can see the case being made for `install`/`uninstall`.

Backwards compatibility is definitely a concern.

Curious what people's thoughts are here!

**Comment by Evalir** [comment]
Closing—these are huge changes and currently no appetite for these.
