### ISSUE TITLE
Support evm_setTime in anvil, similar to Ganache v7

### ISSUE THREAD

**Issue by jeffywu** [foundry-rs/foundry#4144]
### Component

Anvil

### Describe the feature you would like

Ganache v7 supports an RPC request called evm_setTime which allows the developer to set an arbitrary timestamp for the next block (even if that time is before the current blocktime). This can be useful for testing, since each transaction moves the clock to the current time turning the clock back isn't possible after a single transaction.

**Comment by jeffywu** [comment]
Also support for `evm_setAccountNonce` would be useful as well.

**Comment by mattsse** [comment]
there's `anvil_setNextBlockTimestamp`

we could add an alias for `evm_setTime`, what's the argument of `evm_setTime`?

> 
Also support for evm_setAccountNonce would be useful as well.

there's `anvil_setNonce` as well.
can also set an alias

**Comment by mattsse** [comment]
ah I see `evm_setTime` differs slightly

> vm_setTime to set it to a specific timestamp; it accepts a JavaScript timestamp (Unix epoch) with millisecond precision and returns the number of seconds between the given timestamp and the current time.

**Comment by jeffywu** [comment]
Also, I believe evm_setTime in Ganache does not have a strict requirement that the new time increases from the previous block time. After calling evm_setTime Ganache will increase time relative to the last evm_setTime. 

I'd really like to migrate to anvil from Ganache but based on how all of my test code works the restriction that the block time is always increasing would require a pretty big re-write.

**Comment by mattsse** [comment]
I can add this real quick
