### ISSUE TITLE
Forge script (deploy) ouputs wrong goerli etherscan url api

### ISSUE THREAD

**Issue by 0xSchellen** [foundry-rs/foundry#4150]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (08d4315 2023-01-22T00:04:38.303742334Z)

### What command(s) is the bug in?

forge script script/WBRL.s.sol:WBRLScript --broadcast --verify --rpc-url ${RPC_URL} --sender $FOUNDRY_SENDER

### Operating System

Linux

### Describe the bug

1- Action::  We submit a script to GOERLI:
 forge script script/WBRL.s.sol:WBRLScript --broadcast --verify --rpc-url ${RPC_URL} --sender $SENDER_ADDRESS

results obtained:
Submitting verification for [src/WBRL.sol:WBRL] "0x91566F97219Ae9b7a989006f8Ee0A5AcCAdA38e8".
Submitted contract for verification:
        Response: `OK`
         GUID: `pwmd9jjbdgefuv8wthpkk6imp7a33iivu7yjcki2ns2czfc9ej`
        URL:
        https://api-goerli.etherscan.io/apiaddress/0x91566f97219ae9b7a989006f8ee0a5accada38e8
...
Contract successfully verified
All (1) contracts were verified!

2 - The Problem:
Forge script outputs this wrong etherscan api url:

// https://api-goerli.etherscan.io/apiaddress/0x91566f97219ae9b7a989006f8ee0a5accada38e8

// Correct url is:
// https://goerli.etherscan.io/address/0x91566f97219ae9b7a989006f8ee0a5accada38e8

The use of the wrong goerli etherscan url causes subsequent errors when using: cast storage (all)

**Comment by mattsse** [comment]
thanks for flagging this, see linked PRs for fixes.
