### ISSUE TITLE
Support for multiple events emitted check

### ISSUE THREAD

**Issue by emailtovamos** [foundry-rs/foundry#4153]
### Component

Forge

### Describe the feature you would like

This is more of a question: is it possible to check multiple events that get emitted in a single function in forge test? Currently I can see `expectEmit()` functionality that works well for single events. But if my function has multiple events, I can't test them both without calling the same function twice separately.

**Comment by mds1** [comment]
You can call `expectEmit` multiple times in a row to look for multiple event emissions, check out the bottom of this page of the docs: https://book.getfoundry.sh/cheatcodes/expect-emit#expectemit

**Comment by JacoboLansac** [comment]
Note: multiple expectEmits work only if the events are emitted in the right order in the test. By mistake, I swapped the order of the expectEmits and the tests were not passing until I put them in the right order.

**Comment by Evalir** [comment]
Closing—this can already be done with the current `expectEmit` behavior.

**Comment by yan-man** [comment]
@mds1 just to clarify, the emitted events must be in the exact same order as defined by the multiple expectEmits, correct?
