### ISSUE TITLE
"forge install" sets the latest release tag as the submodule "branch"

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/foundry#4155]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (f7e3677 2023-01-23T00:09:49.722891Z)

### What command(s) is the bug in?

forge install PaulRBerg/prb-math

### Operating System

macOS (Apple Silicon)

### Describe the bug

If no ref is provided at the end of the repo with `@`, `forge install` installs the git submodule from the latest release tag. This is okay (I'm rather indifferent about this).

The problem is that Forge also sets the release tag as the `branch` in the `.gitmodules` file. [Git tags cannot be used as a submodule `branch`](https://stackoverflow.com/q/1777854/3873510). Forge should instead not set the `branch`.

Alternatively, if we are to consider changing Forge's behavior to always install from the default branch of the submodule (`master` or `main` or whatever), then we could use that default branch for the `branch` config option in `.gitmodules`.

**Comment by zerosnacks** [comment]
Hi @PaulRBerg, sorry for the delay - is this still an issue?

Installing `forge install PaulRBerg/prb-math` yields

```
[submodule "lib/prb-math"]
	path = lib/prb-math
	url = https://github.com/PaulRBerg/prb-math
```

it does not set a branch anymore

**Comment by PaulRBerg** [comment]
Yeah it works now.
