### ISSUE TITLE
forge fmt moved the comma in front of comment out parameters 

### ISSUE THREAD

**Issue by aiwowo1** [foundry-rs/foundry#4164]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (f7e3677 2023-01-23T00:04:47.538258979Z)

### What command(s) is the bug in?

forge fmt

### Operating System

Linux

### Describe the bug

forge fmt changed a style which I can't explain. please see the changes everywhere my code has now:

before running forge fmt
function approve(address /*owner*/, uint256 /*amount*/ )

after running 'forge fmt'
function approve(address, /*owner*/ uint256 /*amount*/ )

Notice the comma is moved and it's not what we get used to.

**Comment by mds1** [comment]
Ah just saw this before I created https://github.com/foundry-rs/foundry/issues/4451, will close in favor of that one since the code did not format properly here
