### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by scriptWa** [foundry-rs/foundry#4170]
### Component

Foundryup

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### Operating System

macOS (Apple Silicon)

### Describe the bug

![image](https://user-images.githubusercontent.com/83998916/214492988-4c53364c-293d-42eb-9312-b4f8ee1e787f.png)
Only Cast is installed by running foundryup, Forge and Envil are both not installed, what should be the problem?

**Comment by mattsse** [comment]
looks like a curl error?
can you try again?

**Comment by scriptWa** [comment]
curl -L https://foundry.paradigm.xyz | bash is successful, foundryup installing cast/forge/anvil always end up with only installing cast, forge and anvil are not installed
![image](https://user-images.githubusercontent.com/83998916/214578908-bd8aa862-0b6f-4de9-a9de-09692bc135cc.png)

**Comment by scriptWa** [comment]
I have successfully installed, should be my network problem
