### ISSUE TITLE
Support for no event emission check

### ISSUE THREAD

**Issue by Rubilmax** [foundry-rs/foundry#4180]
### Component

Forge

### Describe the feature you would like

A usecase we've encountered recently in our unit tests would be to check that a specific event was not emitted when testing a specific branch of code. It seems there's no way to do this currently, am I mistaken?

This could take the form of `vm.expectNoEmit` and work just like `vm.expectEmit`

**Comment by mds1** [comment]
Seems to be a duplicate of https://github.com/foundry-rs/foundry/issues/509?
