### ISSUE TITLE
feat(forge): invariant tests instrumentation with function call summaries

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/foundry#4186]
### Component

Forge

### Describe the feature you would like

It would be useful to get a report of the distribution of function calls at the end of a successful invariant test run.

Users currently have to resort to manually instrumenting the function calls by adding storage vars, which clutters the handler contracts with logic that is unrelated to the actual business logic of the protocol. See, for example, the [`numCalls`](https://github.com/lucas-manuel/invariant-examples/blob/d6b4f06d7ebe0bbaebcfd666fb00433d30ab28da/test/handlers/LpHandler.sol#L23) mapping defined in Lucas' `invariant-examples` repo, and also his [`invariant_call_summary`](https://github.com/lucas-manuel/invariant-examples/blob/d6b4f06d7ebe0bbaebcfd666fb00433d30ab28da/test/WrappedTests.t.sol#L87-L101) function.

This is something that should be done by Forge, which is in charge of orchestrating the invariant tests anyway.

**Comment by PaulRBerg** [comment]
If you like this idea, @mds1, should we add it to your todo list in #3412?

**Comment by mds1** [comment]
Duplicate of https://github.com/foundry-rs/foundry/issues/3607? (which is already tracked in #3412)

**Comment by PaulRBerg** [comment]
I missed that issue! Sorry, closing.
