### ISSUE TITLE
feat(forge): config option to ignore contracts deployed in `setUp` function

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/foundry#4187]
### Component

Forge

### Describe the feature you would like

Based on Lucas Manuel's guidance in https://github.com/foundry-rs/book/pull/760, it seems to me that there is a need for a config option that ignores all contracts that get deployed in the `setUp` function of a test contract that contains invariant tests.

The use case is bounded testing with handler contracts and the `fail_on_revert` config option set to `true` - in this context, it doesn't really make sense to automatically add all the contracts deployed in `setUp` to the list of targeted contracts for invariant testing purposes.

Invariant users have to resort to manually adding all known contracts to a denylist (see [`_excludeAllContracts`](https://github.com/maple-labs/maple-core-v2/blob/00f01ae7175885f8d49ac201a1c72465e320b2f6/tests/invariants/BaseInvariants.t.sol#L496-L533) in Maple V2's repo), which must include both production contracts and test contracts. Maintaining this list is a chore, especially in sophisticated projects with lots of dependencies and test contracts.

A much more ergonomic developer experience would be to have a config option in the `invariant` section of the Foundry profile that would disable this default behavior of Forge - i.e. *not* include all contracts deployed in `setUp` by default, and let the user manually add contracts with [`targetContract`](https://github.com/foundry-rs/forge-std/blob/4a79aca83f8075f8b1b4fe9153945fef08375630/src/InvariantTest.sol#L46) and/ or [`targetArtifact`](https://github.com/foundry-rs/forge-std/blob/4a79aca83f8075f8b1b4fe9153945fef08375630/src/InvariantTest.sol#L38).

**Comment by mds1** [comment]
I’m believe that as soon as you add a contract to the array returned by your test contract’s `targetContracts` method, that array is used instead of the default set of contracts deployed in `setUp`. But maybe this is wrong and it’s just additive? cc @lucas-manuel @joshieDo

**Comment by haydenshively** [comment]
It does seem to be additive. This feature would solve #4163

**Comment by PaulRBerg** [comment]
@haydenshively actually, it is not additive. I just ran multiple tests in my private repo now, and using `targetContract` worked, i.e. no calls were made to any contract not added via `targetContract`.

In this case, I'm not sure if a config option would be as useful anymore. Though, it would certainly be worth documenting this - I think Lucas is on it in https://github.com/foundry-rs/book/pull/760.

**Comment by haydenshively** [comment]
Apologies, I should've read more carefully. The context for my issue is identical, but I found that even after targeting a single contract, one must still manually add all known contracts to a denylist via `excludeSender`.

You're definitely right about `targetContract` behavior though.

**Comment by PaulRBerg** [comment]
No worries, @haydenshively. Thanks for following up to confirm.

I think, I will let this issue open for a few more weeks until I get a better handle on invariant testing. Also, other users may chime in to cast their opinion.

If I ultimately realize that this is not useful, I will close the issue.

**Comment by mds1** [comment]
Going to close for now since it's been a few weeks and current thinking is that the `targetContracts` is sufficient to achieve these goals (which I agree with). Can of course reopen if needed

**Comment by PaulRBerg** [comment]
Yeah, `targetContracts` is good enough for now.

Shouldn't you have closed this as "not planned", though?
