### ISSUE TITLE
Serializing JSON: Unable to serialize more than two entries at the same level

### ISSUE THREAD

**Issue by joejordan** [foundry-rs/foundry#4194]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (aeba75e 2023-01-26T03:56:21.4985159Z)

### Operating System

Windows

### Describe the bug

I'm attempting to write a list of deployed addresses for later retrieval using stdJson cheatcodes. The list would be a simple json file with names and a list of addresses, i.e. { address1: 0x0, address2: 0x1, address3: 0x3 }

I'm able to serialize an object with up to two entries, but I can't seem to add a third and a fourth entry at the same json level by following the examples in the Foundry Book.

Here's a snippet to demonstrate the issue:
```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity >=0.8.4;

import { Script } from "forge-std/Script.sol";
import { console2 } from "forge-std/console2.sol";
import { stdJson } from "forge-std/StdJson.sol";

contract FileUtils is Script {
    using stdJson for string;

    function serializeDemo() public {

        string memory json = "INTERNAL_KEY";
        console2.log(json); // output: INTERNAL_KEY
        json.serialize("address1", address(1));
        console2.log(json); // output: INTERNAL_KEY
        json = json.serialize("address2", address(2));
        console2.log(json); // output: {"address2":"0x0000000000000000000000000000000000000002","address1":"0x0000000000000000000000000000000000000001"}
        json = json.serialize("address3", address(3));
        console2.log(json); // output: {"address3":"0x0000000000000000000000000000000000000003"}
        // shouldn't the above output include all three address entries?
    }
}
```

**Comment by mattsse** [comment]
cc @odyslam

**Comment by odyslam** [comment]
@joejordan The issue is that you change the key while serializing, so you serialize the json into many different jsons.

When you do: json = json.serialize(), you set the json string to the output of json.serialize. That means that the next invocation of `json.serialize()` will use the output of the previous json.serialize as a key and not the original string `INTERNAL_KEY`.

The serialize cheatcodes always return the stringified version of the JSON they are serializing so that you can create arbitrary nested json objects.

**Comment by rafales** [comment]
@odyslam 
As someone who currently tries to understand how to read/write json files and work with it - it's a problem of not paying attention to Developer Experience and interface design.

This topic is hard to understand, hard to work with and poorly documented (eg. some functions referenced in docs like `vm.serialize` don't even exist).

Sorry for harsh words but right now I am really frustrated with this thing.

**Comment by joejordan** [comment]
> When you do: json = json.serialize(), you set the json string to the output of json.serialize. That means that the next invocation of `json.serialize()` will use the output of the previous json.serialize as a key and not the original string `INTERNAL_KEY`.

Thanks @odyslam, that helped resolve the original issue.

I was going to ask next about how to write to an existing .json file to path without destroying the existing keys at the same level, but it turns out I was overthinking things. Originally I thought that I would have to first load the existing json file, parse the json, and then find some way to serialize it into the loaded data. Turns out instead that it's a one liner:

```solidity
    /// @notice writes an address to the given json path
    /// @dev assumes file and path in json file exists. 
    function setAddress(string calldata jsonPath, address value) public {
        vm.writeJson(vm.toString(value), getJsonFilePath(), string(abi.encodePacked(".", jsonPath)));
    }
```
The `jsonPath` argument above is an existing path in the json file, i.e. `Marketplace.proxy` if we wanted to write a new proxy address in the below json object. (We append an initial dot to the string because it was required to complete the path.)
```json
{
  "Marketplace": {
    "logic": "0x0B1a87021ec75fBaE919b1e86b2B1335FFC8F4d3",
    "proxy": "0xA4aE77554847958aC0854f06601267c9F9C75dfD",
    "factory": "0x9eb52339B52e71B1EFD5537947e75D23b3a7719B",
    "router": "0xf18774574148852771c2631d7d06E2A6c8b44fCA"
  }
}
```
If I have some time I'll try and update the Foundry book, as I did find the existing documentation somewhat unclear about handling certain situations. Regardless, thank you, @odyslam for adding this invaluable feature to Foundry.

**Comment by odyslam** [comment]
@joejordan would love to hear what you found unclear as a simple bullet point list here. If you don't find the time to update the foundry book, I could do it.

**Comment by joejordan** [comment]
@odyslam I would start by explaining in more detail the absolute basics, and then build on the concepts with examples.

Read a json file with one entry
Write a json file with one entry
Read a json file with 10 entries
Write a json file with 10 entries

Then get into the more complex scenarios like building a complex JSON with different data types, arrays, decoding into structs, etc.

My issue with the documentation was that it was not clear to me initially that the initial string is an internal marker that is used to build upon a collection of JSON entries. I also found the example on the bottom of the serializeJson page confusing, and I think that's what primarily led to me struggling with implementing this feature.

**Comment by spaceh3ad** [comment]
I have created such script maybe it would help someone

```
  function saveJson(
        address[] memory _addresses,
        string[] memory _names,
        string memory _fileName
    ) internal {
        string memory chainIdStr = Strings.toString(block.chainid);
        string memory path = string(
            abi.encodePacked(
                "./deployments/",
                chainIdStr,
                "_",
                _fileName,
                ".json"
            )
        );

        string memory json = "{\n";

        for (uint256 i = 0; i < _addresses.length; i++) {
            json = string(
                abi.encodePacked(
                    json,
                    '  "',
                    _names[i],
                    '": "',
                    Strings.toHexString(_addresses[i]),
                    '"'
                )
            );

            if (i < _addresses.length - 1) {
                json = string(abi.encodePacked(json, ",\n"));
            } else {
                json = string(abi.encodePacked(json, "\n"));
            }
        }

        json = string(abi.encodePacked(json, "}\n"));

        vm.writeFile(path, json);
    }
    
```
