### ISSUE TITLE
feat(forge): flag to print only console logs in traces

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/foundry#4195]
### Component

Forge

### Describe the feature you would like

There are several scenarios where it would be useful to be able to filter out all traces except console logs, just to name a few:

1. Debugging a failing test and focusing on console logs (there are cases where the test set-up proces so many test traces that logs get hidden).
2. Printing an [invariant call summary](https://github.com/lucas-manuel/invariant-examples/blob/d6b4f06d7ebe0bbaebcfd666fb00433d30ab28da/test/WrappedTests.t.sol#L87-L101) and wanting to see only the call summary.

### Additional context

I just bumped into case 2 now, here's how it looks:

<img width="1728" alt="Screenshot 2023-01-26 at 10 06 58 PM" src="https://user-images.githubusercontent.com/8782666/214940662-fb75270a-1569-40c1-9a9d-facb4aabcbcf.png">

The actual call summary is overshadowed by the test traces.

**Comment by 0xPhaze** [comment]
I was also thinking that having the option to filter logs would be nice, but just to make sure: have you tried getting rid of some of those v's in `-vvv` regarding 2.? 

And not sure I understand 1. You want only the console.log traces to be shown? My first thought was to get rid of all console log call traces and only show the traces not relevant to debugging.

**Comment by PaulRBerg** [comment]
> have you tried getting rid of some of those v's in `-vvv` regarding 2.?

Yes. Using only three `v`s does lower the number of information shown but it doesn't but it doesn't do it in full. To use my [Foundry template]() as en example:

```text
Running 1 test for test/Foo.t.sol:FooTest
[FAIL. Reason: Assertion failed.] test_Example() (gas: 30971)
Logs:
  Hello World

Traces:
  [30971] FooTest::test_Example()
    ├─ [0] console::log(Hello World) [staticcall]
    │   └─ ← ()
    ├─ emit Log(err: Error: Assertion Failed)
    ├─ [0] VM::store(VM: [0x7109709ECfa91a80626fF3989D68f67F5b1DD12D], 0x6661696c65640000000000000000000000000000000000000000000000000000, 0x0000000000000000000000000000000000000000000000000000000000000001)
    │   └─ ← ()
    └─ ← ()

Test result: FAILED. 0 passed; 1 failed; finished in 299.00µs

Failing tests:
Encountered 1 failing test in test/Foo.t.sol:FooTest
[FAIL. Reason: Assertion failed.] test_Example() (gas: 30971)
```

My feature request is to be able to hide everything except the console logs.


> You want only the console.log traces to be shown?

Yup. I want to hone in on the variables that I am console logging.

**Comment by mds1** [comment]
This can be done using just two v's, `-vv`, as shown below

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/17163988/221733759-189ee18d-cdf1-4974-bf5f-38619d5c670e.png">

**Comment by PaulRBerg** [comment]
My feature request was to be able to hide everything, including the status of the tests ("PASSED", "FAIL"), except for the console logs.

`-vv` or `-v` don't do that.

**Comment by mds1** [comment]
Oh from the original comment it sounded like hiding traces and not logs. This feels like a bit of a footgun because if you have only logs, you don't know test status, don't know which test(s) logs are from, etc. But you can likely accomplish this with `forge test --silent --json | jq '..|.decoded_logs?'` or something similar (prob need to tweak the jq part a bit)

**Comment by PaulRBerg** [comment]
> This feels like a bit of a footgun

Footgunality is sort of unrelated in this context because you'd first see which test failed, and then you'd hone in on that particular test.

> But you can likely accomplish this with `forge test --silent --json | jq '..|.decoded_logs?'`

Thanks, I'll try that!
