### ISSUE TITLE
scripting: vm.startBroadcast() in setUp() increases nonce by 1

### ISSUE THREAD

**Issue by 0xlosh** [foundry-rs/foundry#4197]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0

### What command(s) is the bug in?

forge script 

### Operating System

Linux

### Describe the bug

Contract.sol
```
contract Contract {
    uint256 public number = 1;
}
```
Contract.s.sol
```
contract ContractScript is Script {
    
    function setUp() public {
        vm.startBroadcast();
    }

    function run() public {
        new Contract();
    }
    
}
```
running 
`forge script script/Contract.s.sol -f goerli --private-key $pk --broadcast`
increases the nonce of the deployer by 1, there is no pending tx/creation after waiting for 1min.

to fix the issue, one have to make a tx from e.g. metamask, i did a self transfer:
![Screenshot 2023-01-27 at 00 05 12](https://user-images.githubusercontent.com/83345377/214971171-227339ca-c621-4e8b-b8fe-0b02f061d753.png)
as you can see in the screenshot above, the contract creation tx appears!

and confirms:
![Screenshot 2023-01-27 at 00 05 39](https://user-images.githubusercontent.com/83345377/214971353-f17f51d0-ef9f-4806-8257-325a318afae9.png)

this only happens when `vm.startBroadcast()` is in `setUp()` as far as i know.

**Comment by zerosnacks** [comment]
`vm.startBroadcast` is `setup` now yields:

```
Traces:
  [101253] → new CounterScript@0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496
    └─ ← [Return] 395 bytes of code

  [2979] CounterScript::setUp()
    ├─ [0] VM::startBroadcast()
    │   └─ ← [Return] 
    └─ ← [Stop] 

  [3011] CounterScript::run()
    ├─ [0] VM::broadcast()
    │   └─ ← [Revert] a broadcast is active already
    └─ ← [Revert] a broadcast is active already


Gas used: 24075
Error: 
script failed: a broadcast is active alread
```

Marking this as resolved by https://github.com/foundry-rs/foundry/pull/5998 as user cannot encounter the reported issue anymore
