### ISSUE TITLE
Add support for Solidity `0.8.18`

### ISSUE THREAD

**Issue by pcaversaccio** [foundry-rs/foundry#4199]
The new Solidity release `0.8.18` should be released this or next week (see [here](https://forum.soliditylang.org/t/feature-preview-user-defined-operators/1435)). I already opened an issue to track the support status in Foundry in one place.

**Comment by mattsse** [comment]
@roynalnaruto heads up

**Comment by roynalnaruto** [comment]
PR open here: https://github.com/roynalnaruto/svm-rs/pull/73

**Comment by pcaversaccio** [comment]
FYI for anyone that is interested in the release notes: https://github.com/ethereum/solidity/releases/tag/v0.8.18

**Comment by nikitastupin** [comment]
Hey everyone! I've uploaded v0.8.18 at https://github.com/nikitastupin/solc/commit/01a11efffb8111db0637d4b47a8360bb66979d82

**Comment by roynalnaruto** [comment]
Related PR: https://github.com/gakonst/ethers-rs/pull/2110

**Comment by pcaversaccio** [comment]
Not sure whether this impacts this issue, but I discovered yesterday an issue with the Linux binary builds of solc `0.8.18`: https://github.com/ethereum/solidity/issues/13921. The binary has been rebuilt and now has another hash.

**Comment by nikitastupin** [comment]
I tried `solc --version` with linux aarch64 build and it didn't have this problem so I assume no need to recompile

**Comment by roynalnaruto** [comment]
@mattsse I don't think so. The SHA256 checksum for the Linux AARCH64 architecture was built by @nikitastupin and I got the checksum locally. Could you also try if that binary's SHA256 checksum is the same as what we have here:

https://github.com/roynalnaruto/svm-rs/blob/master/list/linux-aarch64.json ?

**Comment by roynalnaruto** [comment]
The binaries will be fetched from @nikitastupin 's `solc` repository, so as long as that binary hasn't been updated, the checksum can't fail?

**Comment by mattsse** [comment]
CI errors could be related to https://github.com/ethereum/solidity/issues/13921

in any case we should improve the `svm` `ChecksumMismatch` so it includes the expected and actual, otherwise this isn't very helpful

**Comment by pcaversaccio** [comment]
as a quick input, I like how `solc-select` verifies the checksums: https://github.com/crytic/solc-select/blob/dev/solc_select/solc_select.py#L121. Like that we could easily detect the cache problem re the binaries (see my solc issue for more info on that).

**Comment by leekt** [comment]
Seems there are still issues with parsing the 0.8.18 and this issue exists on solang-parser 
cannot do `forge fmt` and `forge doc` for something like this

```
pragma solidity ^0.8.18;

contract C {
    mapping(address user => uint256) public balances;
}
```

**Comment by mattsse** [comment]
yeh since this is a new language feature, I don't think this is supported yet by https://github.com/hyperledger/solang
please consider opening an issue there

**Comment by leekt** [comment]
done https://github.com/hyperledger/solang/issues/1159
