### ISSUE TITLE
New space/memory limit breaks eth_getBlockByNumber() after 10 blocks

### ISSUE THREAD

**Issue by dominicletz** [foundry-rs/foundry#4201]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [x] Foundry
- [X] Foundryup

### What version of Foundry are you on?

nightly-3ac206ca30835ee9108e2215f362cbdcc19e53a4

### What command(s) is the bug in?

anvil

### Operating System

Linux

### Describe the bug

Running our CI using the foundry github action we're always getting the most recent nightly build. Tonight our tests started breaking because our tests do check previous blocks (up to ~30 blocks of history).

After digging a bit we found that `anvil` now only keeps a history of around 10 blocks after which it forgets all blocks and we can't fetch them anymore using `eth_getBlockByNumber` 

Here some debug output from our tests, showing {<method>, <params>, <result>} of the calls against anvil.
When we reach block 0xf, the block 1 is already gone.
```
{"eth_blockNumber", [], %{id: 1, jsonrpc: "2.0", result: "0xf"}}
{"eth_getBlockByNumber", [1, true], %{id: 1, jsonrpc: "2.0", result: nil}}
```

**Comment by dominicletz** [comment]
Going back to version nightly-aeba75e4799f1e11e3daba98d967b83e286b0c4a from yesterday fixes the issue and the previous blocks are still available.

**Comment by mattsse** [comment]
are you running with interval mode?

just released a new release which increased the defaults to a more reasonable number

could you please re-run and check, perhaps we missed something in the recent PR

**Comment by dominicletz** [comment]
Just tried `3ca8723` fails with the very same issue. Also providing `--no-mining` or not doesn't make a difference.

**Comment by dominicletz** [comment]
@mattsse looks like I can't reopen the issue, but the problem persists.

**Comment by mattsse** [comment]
how can I reproduce this?
