### ISSUE TITLE
Anvil no longer returns event filter logs for impersonated accounts

### ISSUE THREAD

**Issue by jxom** [foundry-rs/foundry#4205]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

anvil 0.1.0 (3ca8723 2023-01-28T00:05:49.406699Z)

### Operating System

None

### Describe the bug

Seems that after https://github.com/foundry-rs/foundry/commit/b980e3cf97888a591e8f33a92fbe9f7cba364826, Anvil no longer returns event filter logs for transactions sent from impersonated accounts.

## Steps to reproduce

1. Impersonate `vitalik.eth`

```
curl http://localhost:8545 -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"anvil_impersonateAccount","params":["0xd8da6bf26964af9d7eed9e03e53415d37aa96045"],"id":0}' 
```

2. Create a new filter

```
curl http://localhost:8545 -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_newFilter","params":[{}],"id":1}'
```

3. Send a couple of transactions that sends 1 USDC to an arbitrary address (uses `transferFrom` on USDC contract).

```
curl http://localhost:8545 -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_sendTransaction","params":[{ "from":"0xd8da6bf26964af9d7eed9e03e53415d37aa96045", "to":"0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48", "data":"0xa9059cbb000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb922660000000000000000000000000000000000000000000000000000000000000001" }],"id":2}'

curl http://localhost:8545 -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_sendTransaction","params":[{ "from":"0xd8da6bf26964af9d7eed9e03e53415d37aa96045", "to":"0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48", "data":"0xa9059cbb000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb922660000000000000000000000000000000000000000000000000000000000000001" }],"id":3}'
```

4. Use the filter ID from step 2. to try obtain logs

```
curl http://localhost:8545 -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getFilterLogs","params":["<INSERT_FILTER_ID_HERE_PLZ>"],"id":4}'
```

Seems that the above RPC call returns an array of no items, however, I'd expect 2 event logs to be populated (previous behavior).

**Comment by mattsse** [comment]
ah sigh this is so cursed -.-

checking

**Comment by jxom** [comment]
❤️
