### ISSUE TITLE
Chisel - No return on uneven division

### ISSUE THREAD

**Issue by x676f64** [foundry-rs/foundry#4207]
### Component

Chisel

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (3ca8723 2023-01-28T00:17:14.977579Z)

### What command(s) is the bug in?

chisel

### Operating System

None

### Describe the bug

Chisel version: chisel 0.1.1 (3ca8723 2023-01-28T00:17:49.95785Z)

Division of uint values that would result in a remainder don't return a result. See the following image as an example. For example, `1000000000000000000/3` doesn't return a value. I would expect the return value to be `333333333333333333`.

![image](https://user-images.githubusercontent.com/53136615/215256317-7b9d5898-5fad-414f-8790-2a73d47b4757.png)

**Comment by DaniPopes** [comment]
You would have to explicitly specify one of the operands as `uint`/`int` with a cast or variables (like `uint(1000) / 3`), or the resulting type of the expression will be a rational number which are currently not supported in chisel inspections

**Comment by x676f64** [comment]
> You would have to explicitly specify one of the operands as `uint`/`int` with a cast or variables (like `uint(1000) / 3`), or the resulting type of the expression will be a rational number which are currently not supported in chisel inspections

Ah thanks. I will close this then
