### ISSUE TITLE
Arrays, mappings and structs behave differently in tests

### ISSUE THREAD

**Issue by financesaucer** [foundry-rs/foundry#4209]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (849fd61 2023-01-27T00:12:54.538364514Z)

### What command(s) is the bug in?

forge test / forge build?

### Operating System

Linux

### Describe the bug

Hello, I just started using foundry for testing my contracts but I found out that arrays, mappings and structs are behaving differently in tests than in actual contracts, to me it seems a problem with forge build because VSCode compiler doesn't see the issues but when I compile before testing it starts to give errors such as:

-It doesnt compile when trying to access arrays, mappings data with [index] but when I use (index) it works.
-To access structs members I need to use them as a tuple.
I.E.

struct MyStruct {
uint data1;
uint data2;
uint data3;
}

so to access data3 value I cant use Contract.MyStruct.data3 but i need to do (,,uint data) = Contract.MyStruct .
I get the same behavior with array of struct.

I have the same problem with solc 0.7.5 and 0.8.17.

**Comment by financesauce** [comment]
Sorry, I think I did setup the tests in the wrong way and didn't inherit the contract that I'm testing so for the arrays part I do get why I need to use the () instead of [], but I still think I should be able to access the external structs member with their name...

**Comment by mattsse** [comment]
could you please provide a full example

unsure if related but

> Note that Solidity does not allow to declare references to value types in storage. These kinds of explicit dangling references are restricted to nested reference types. However, dangling references can also occur temporarily when using complex expressions in tuple assignments:

worth reading the struct section of the docs
https://docs.soliditylang.org/en/v0.8.17/types.html#structs

**Comment by zerosnacks** [comment]
Marking as `stale`, @financesaucer please re-open with a minimal reproduction example if you are still having a problem
