### ISSUE TITLE
Toggle for contract code pane

### ISSUE THREAD

**Issue by lightclient** [foundry-rs/foundry#4231]
### Component

Forge, Cast

### Describe the feature you would like

I like using the debug mode to review traces for handwritten assembly. It would nice if I could hide the code pane so that I could have larger asm, stack, and memory panes.

**Comment by zerosnacks** [comment]
Thanks for your suggestion, added as part of https://github.com/foundry-rs/foundry/issues/927 in a more generalizable way, to allow toggling of individual panes for flexible layout. For now marking this as a duplicate of that.
