### ISSUE TITLE
Chisel --use <path> not working

### ISSUE THREAD

**Issue by e1Ru1o** [foundry-rs/foundry#4239]
### Component

Chisel

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (31f945c 2023-01-30T00:05:12.356073Z)

### Operating System

macOS (Apple Silicon)

### Describe the bug

I have being using `forge --use <path>` to specify the version of `solc` to use. I am now trying to do the same for `chisel` but the paths seems to be ignored so the default installation of `solc` is executed each time. I tried with different paths all being ignored and verified that they work with `forge --use`.

My `chisel` version is:
chisel 0.1.1 (31f945c 2023-01-30T00:05:13.423748Z)

**Comment by mattsse** [comment]
@clabby I think we can just mirror `forge test --use` here

**Comment by e1Ru1o** [comment]
Already working correctly in:
chisel 0.1.1 (50756e5 2023-05-29T00:13:02.068600000Z)
