### ISSUE TITLE
Support int for type in transactions

### ISSUE THREAD

**Issue by antazoey** [foundry-rs/foundry#4240]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

foundryup: installed - anvil 0.1.0 (5c2db0b 2023-01-31T00:18:27.342972Z)

### What command(s) is the bug in?

RPC for sending txn

### Operating System

macOS (Intel)

### Describe the bug

To increase compatibility with web3.py, allow integer for type in transaction.
https://github.com/ethereum/web3.py/blob/master/web3/types.py#L224

This will allow HTTP clients to be simpler and use integers.

**Comment by grandizzy** [comment]
@antazoey could you please clarify the issue / send a way to reproduce? thank you!

**Comment by DaniPopes** [comment]
I'm guessing referring to this:
```python
                if isinstance(txn_dict.get("type"), int):
                    txn_dict["type"] = HexBytes(txn_dict["type"]).hex()
```

The `type` field in transactions is specified as a hex-encoded integer.
