### ISSUE TITLE
JSON: unable to decode arrays

### ISSUE THREAD

**Issue by rafales** [foundry-rs/foundry#4244]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (cd7850b 2023-02-01T00:04:58.420758Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

`jsonParse` seems to be returning improperly encoded data.

```solidity
# this would fail
uint256 ids = jsonRoles.readUintArray(".roles[*].id");

# now this is what happens
bytes memory idBytes = jsonRoles.parseRaw(".roles[*].id");
console2.log("ids bytes:", vm.toString(idBytes));
```

The json looks more or less like this:
```json
{ "roles": [ { "id": 1 }, { "id": 2 } ] }
```

So we want to get an array of `[1, 2]`.

Encoded bytes we got look like this:

```
0x00000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002
```

This is obviously not the right ABI-encoded version of that array.

I have the same issues with using `readStringArray` and `reaedAddressArray`.

**Comment by rafales** [comment]
Btw posting this error report automatically triggered this pipeline https://github.com/foundry-rs/foundry/actions/runs/4065722095

**Comment by rkrasiuk** [comment]
@rafales thanks for the heads up. we'll set up auto archival of stale closed issues

**Comment by rkrasiuk** [comment]
@odyslam ptal at the json cheatcode issue

**Comment by odyslam** [comment]
@rkrasiuk yeah, ack, I will look into it today or tomorrow.
