### ISSUE TITLE
bug(forge): `call_override` to have same size as the number of (unsafe) external calls of the sequence

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/foundry#4245]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (cd7850b 2023-02-01T00:04:58.420758Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

I enabled the [`call_override`](https://book.getfoundry.sh/reference/config/testing#call_override) flag in the `[invariant]` section, and got this error:

```text
The application panicked (crashed).
Message:  to have same size as the number of (unsafe) external calls of the sequence.
Location: evm/src/fuzz/invariant/call_override.rs:70

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
[1]    44947 abort      forge t --mt invariant_
```

Unfortunately, I cannot link to my project, since it's in a private repository. But I do have many calls to external contracts.

**Comment by Philogy** [comment]
Getting a different error but that is also solely caused by flipping the `call_override` option to `true`:
```
The application panicked (crashed).
Message:  called `Option::unwrap()` on a `None` value
Location: evm/src/fuzz/strategies/invariants.rs:36

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
[1]    480596 IOT instruction (core dumped)  forge test
```

To reproduce just clone [this repo](https://github.com/horsefacts/weth-invariant-testing) change `call_override` in `foundry.toml` to `true` and run `forge test`
