### ISSUE TITLE
After forking the mainnet, how do I get the outgoing transaction logs or trace immediately before the next block?

### ISSUE THREAD

**Issue by 2547881370** [foundry-rs/foundry#4246]
### Component

Anvil

### Describe the feature you would like

With interval mining currently enabled, I wonder if I can get the logs or trace of the transaction I am simulating immediately before mining

**Comment by grandizzy** [comment]
@2547881370 could you please provide more details re scenario you are trying to accomplish? Please reopen with such, thank you!
