### ISSUE TITLE
Keep small amount of block state data in memory

### ISSUE THREAD

**Issue by michprev** [foundry-rs/foundry#4252]
### Component

Anvil

### Describe the feature you would like

In my use case, I sometimes need to call `eth_getCode` in the context of older blocks. These blocks are usually up to 10 blocks away from the latest block. To avoid filling the up disk space and to save our SSDs, it would be nice to keep state data for a few latest blocks in memory. Currently, when using `--prune-history` I get error messages like
```
{'code': -32602, 'message': 'BlockOutOfRangeError: block height is 6 but requested was 2'}
```

`--transaction-block-keeper` does not seem to have any effect in this case.

Ideally, the amount of block states to keep in memory should be configurable by the end user.

I am running Anvil with:
```
anvil --prune-history --transaction-block-keeper 10 --base-fee 0 --steps-tracing --silent --port 39787
```

`anvil --version`: `anvil 0.1.0 (cd7850b 2023-02-02T00:07:54.508115898Z)`

**Comment by mattsse** [comment]
we tuned some limits so please try again without prune-history

**Comment by michprev** [comment]
Yes, I am aware of this. In my case, the limit seems to be around 500 MB per Anvil instance. That is around 3500 files. My point is that it does not seem necessary to me to write these logs on the disk at all if we typically need only a few previous state logs. Ideally, the number of state logs kept in memory would be configurable.

The current behavior still may wear out SSDs, especially in the case of high-performance testing/fuzzing.

**Comment by mattsse** [comment]
I see, understood.

what'd be a reasonable limit to keep in memory with `--prune-history`?

**Comment by michprev** [comment]
This may depend from case to case, that is why a user-configurable (command-line?) option feels like the best way to me.

Still, if you want some numbers, 10 blocks history would be a good minimum, 50 blocks history would be sufficient for most cases in my opinion.

**Comment by mattsse** [comment]
so it looks like we need an option to force max in mem history even if --prune-history?

so perhaps `--prune-history` should just take an optional value?

**Comment by michprev** [comment]
Yes, that would be awesome.
