### ISSUE TITLE
"cannot install provided Shell" error when debugging

### ISSUE THREAD

**Issue by The-Wary-One** [foundry-rs/foundry#4253]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (cd7850b 2023-02-01T00:04:58.420758Z)

### What command(s) is the bug in?

forge test --debug <my test>

### Operating System

Linux

### Describe the bug

I running into the same bug as Kushal in the telegram group: "I’m able to successfully run tests, but am getting this error when trying to run the debugger. running on a mac m1". 
I am on Linux.

```bash
$ forge test --debug "testFlow()"
[⠒] Compiling...
No files changed, compilation skipped
Error:
cannot install provided Shell, a shell has already been installed
```

This bug starts in the `nightly-5c2db0babf02e1f1016b1471de3b21593cb06b56` build because i fixed it by running
```bash
foundryup -C 31f945
```

**Comment by Zer0dot** [comment]
Same issue here, just bumping this

**Comment by kadenzipfel** [comment]
can confirm bug on `forge 0.2.0 (5c2db0b 2023-01-31T00:14:50.169296Z)`
