### ISSUE TITLE
Forge remappings support other directory structure

### ISSUE THREAD

**Issue by KuTuGu** [foundry-rs/foundry#4272]
### Component

Forge

### Describe the feature you would like

Currently `forge remappings` command only generate the mapping of dependencies under the `lib` folder.      
Hope it can also support other folder path: `src`, `test`, `script` (also support custom name).        
Otherwise, vscode does not support clicking to jump, can only be solved by manually adding remapping or relative path.    

### Additional context

Desired result:
```
src=src/
test=test/
script=script/
```

**Comment by anhthii** [comment]
+1 for this feature

**Comment by grandizzy** [comment]
this should be solved now with https://github.com/foundry-rs/foundry/pull/9258 please retest and reopen if still an issue. thank you!
