### ISSUE TITLE
feat(forge): "--exact" flag for matching tests

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/foundry#4276]
### Component

Forge

### Describe the feature you would like

The flags `--match-contract` and `--match-test` are globs, which means that they will match two similar test function names like these:

- `testFoo`
- `testFooBar`

However, developers often need to focus on one function in particular. It would be helpful to have another flag `--exact` that, when activated, would not match the `testFooBar` function when the user passes `testFoo` to `--match-test`.

Alternatively, we may consider two separate flags `--match-exact-contract` and `--match-exact-test`, which would achieve the same thing with a single flag rather than two.

**Comment by 0xPhaze** [comment]
Workaround: `forge test --mt testFoo\\b`

**Comment by kamikazebr** [comment]
> Workaround: `forge test --mt testFoo\\b`

That works!! But

Why `testFoo$` or `^testFoo$` dont work? 

Need activate multiline or something like that?

**Comment by mds1** [comment]
`$` does not work because it matches the end of a string, where as `\b` matches word boundaries. The match test flag uses regex, so you can match exact names using that approach. As a result I think this issue can be closed since it's already supported.
