### ISSUE TITLE
Solc installation for `0.7.6` does not execute on m1/m2 mac

### ISSUE THREAD

**Issue by HrikB** [foundry-rs/foundry#4279]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8fe42f9 2023-02-05T21:09:47.759724Z)

### What command(s) is the bug in?

forge build

### Operating System

macOS (Apple Silicon)

### Describe the bug

Installing and executing the solidity compiler for 0.7.6 doesn't seem to be working.

![image](https://user-images.githubusercontent.com/23041116/216855854-a30ab3d6-e673-4b55-af2e-0486fa34666a.png)

**Comment by mattsse** [comment]
there is no native apple silicon for 0.7.6.

See note here https://book.getfoundry.sh/faq?highlight=apple%20silico#im-getting-solc-errors

if you need older versions, please enable rosetta feature
