### ISSUE TITLE
cast: make it easier to get a human-readable balance in `cast balance`, etc.

### ISSUE THREAD

**Issue by holic** [foundry-rs/foundry#4292]
### Component

Cast

### Describe the feature you would like

I often forget the exact incantation required to pass a wei value from `cast balance` back into `cast` to get out the human readable ether value. It'd be nice if there was an `--ether` or `--unit` flag for commands like `cast balance` to make it a little easier to reach for.

Mostly a quality of life thing, so not super urgent!

**Comment by mattsse** [comment]
I'd accept a PR that adds an format argument but you can do
```
cast balance 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2 --rpc-url "<>" | cast fw
3922982.101331091204485894
```

**Comment by chirag-bgh** [comment]
I would like to take this one
