### ISSUE TITLE
feat(forge): disable coverage for assertions

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/foundry#4294]
### Component

Forge

### Describe the feature you would like

Assertions are never meant to fail unless there is a bug, but Forge currently reports partial coverage for `assert` statements:

![Partial coverage for assertions](https://user-images.githubusercontent.com/8782666/217250357-b6a4dbfa-95e0-4993-8501-9518b8e9f2bc.jpeg)

Related issue in the `solidity-coverage` repo: https://github.com/sc-forks/solidity-coverage/issues/269.

**Comment by KholdStare** [comment]
@mattsse @gakonst Any plans to fix this? At the moment whenever auditors run coverage on our code we always have to give the caveat that coverage is under-reported because of assert statements.

Thank you.

**Comment by PaulRBerg** [comment]
Also if [FREI-PI](https://www.nascent.xyz/idea/youre-writing-require-statements-wrong) picks up steam, assertions' coverage will become an even bigger problem.

**Comment by KholdStare** [comment]
I think this is not fixed in spirit yet. `require` should still be a branch Linking to my comment from the PR: https://github.com/foundry-rs/foundry/pull/8413#issuecomment-2223638150

**Comment by grandizzy** [comment]
> I think this is not fixed in spirit yet. `require` should still be a branch. Linking to my comment from the PR: [#8413 (comment)](https://github.com/foundry-rs/foundry/pull/8413#issuecomment-2223638150)

Thank you, will check!
