### ISSUE TITLE
Issues with foundryup on Mac with Apple Silicon

### ISSUE THREAD

**Issue by stevyhacker** [foundry-rs/foundry#4295]
### Component

Foundryup

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8fe42f9 2023-02-05T21:09:47.759724Z)

### What command(s) is the bug in?

foundryup

### Operating System

macOS (Apple Silicon)

### Describe the bug

Updating foundry fails for the latest version on my Mac with Apple Silicon because of an error with the archive format.

```

foundryup: installing foundry (version nightly, tag nightly-ebe1b45187f56b6c024d63c55de2d520cb715639)
foundryup: downloading latest forge, cast, anvil, and chisel
######################################################################################################################################################################################################################################################### 100.0%
tar: Error opening archive: Unrecognized archive format
```

I successfully updated foundry only when I specified this version:

`foundryup --version nightly-8bbde620ab39246f3c89700a19dfe6f347e99f4f
`

**Comment by mattsse** [comment]
yikes, checking
We definitely need an auto issue for when that happens

Any idea how to configure this @DaniPopes?

**Comment by mattsse** [comment]
Looks like Apple silicon failed to some random server error
Triggered release, should be available in 30mins

**Comment by roninjin10** [comment]
I think this is fixed now
