### ISSUE TITLE
dapp create

### ISSUE THREAD

**Issue by gakonst** [foundry-rs/foundry#43]
so that we can deploy contracts

bonus points for etherscan verification (multi or single file?). maybe @paulrberg's code can useful here https://github.com/paulrberg/multisol/

**Comment by gakonst** [comment]
Yep - should behave identically to `dapp create` for the most part. Some docs would be nice, altho the help command should provide some context. Docs for passing arrays and abi encoder v2 structs is what prob needs most work.

**Comment by onbjerg** [comment]
Since all that is left is docs for structs etc I'm closing it here so we can track in https://github.com/foundry-rs/book/issues/415
