### ISSUE TITLE
feat: Add "after-all" hook for testing

### ISSUE THREAD

**Issue by lucas-manuel** [foundry-rs/foundry#4300]
### Component

Forge

### Describe the feature you would like

In `forge` testing it would be very helpful to have a hook that runs at the end of each test. This would allow for:
- Single logging of metrics as outlined in this [issue](https://github.com/foundry-rs/foundry/issues/3607) as an intermediate measure until native internal metrics are implemented.
- Post fuzz campaign testing (e.g., close out all positions and assert all funds are able to exit the system) (both fuzzing and invariant testing).

**Comment by mds1** [comment]
Just noting that contrary to the issue name, this does not have to be exclusive to invariant tests, and can apply to all tests. However in that case some use cases such as logging don't apply. So we may need multiple functions like `afterInvariant`,  `afterFuzz`, and `afterConcrete`. But that feels a but cluttered, so maybe there's a single `afterAll(TestType)` with overloads. Needs some though here

**Comment by lucas-manuel** [comment]
Up to you but I wouldn't mind a one size fits all personally
