### ISSUE TITLE
Forge verify: etherscan: Failed to deserialize response: data did not match any variant of untagged enum ResponseData

### ISSUE THREAD

**Issue by KittyFu307** [foundry-rs/foundry#4302]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (249538f 2023-02-08T00:12:05.805004Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

Hi team, when I try to verify the contract in arbitrum goerli, it will show this error: `etherscan: Failed to deserialize response: data did not match any variant of untagged enum ResponseData`. However I can succeed verify my contract in bsc testnet.

`2023-02-08T07:11:17.698102Z ERROR etherscan: Failed to deserialize response: expected value at line 1 column 1 res="Page not found"`

Is there more detail of this error, thanks
<img width="923" alt="IMG" src="https://user-images.githubusercontent.com/61280608/217460496-bedd49e5-f621-4056-9e65-81bfe1f97335.png">

**Comment by KittyFu307** [comment]
yes

**Comment by mattsse** [comment]
what is it?

**Comment by KittyFu307** [comment]
> > Page not found
> 
> is the API live?

I just apply the api-key in the arbiscan: AKF2S7A8I38JZVGVMGX25VY18SUX6RZ793

**Comment by mattsse** [comment]
ah sorry, I didn't read the issue properly.

https://api.arbiscan.io/api

seems to be working

**Comment by mattsse** [comment]
ah nvm it's arbitrum goerli

and https://goerli-rollup-explorer.arbitrum.io/api is down

**Comment by mattsse** [comment]
this looks like blockscout url

would you like to submit a PR here that changes them to arbiscan?

https://github.com/gakonst/ethers-rs/blob/e20bb715699280402c155a0abbfc82656582242e/ethers-core/src/types/chain.rs#L283-L286

**Comment by KittyFu307** [comment]
I noticed that you have submit a PR, Thank you for your help~

**Comment by KittyFu307** [comment]
sure I found it is: https://api-goerli.arbiscan.io/
