### ISSUE TITLE
Bail after first test failure

### ISSUE THREAD

**Issue by replay-test** [foundry-rs/foundry#4304]
### Component

Forge

### Describe the feature you would like

As the title says, it would be useful to have a flag to stop the process after the first test failure.

**Comment by ameya-deshmukh** [comment]
@onbjerg still open? Would love to take this up.

**Comment by mattsse** [comment]
supportive via extra flag, perhaps --fail-fast ?

**Comment by shawnharmsen** [comment]
I'd like to take a stab at this, pr incoming shortly

**Comment by mds1** [comment]
@ameya-deshmukh if you're still working on this let me know, but it's been a while so reassigned to @shawnharmsen for now
