### ISSUE TITLE
[Bug] code coverage does not work if function is called inside of `assertTrue`

### ISSUE THREAD

**Issue by 0xAurelou** [foundry-rs/foundry#4306]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (3ca8723 2023-01-28T00:08:54.548717256Z)

### Operating System

Linux

### Describe the bug

Following my previous issue:
https://github.com/foundry-rs/foundry/issues/4142 (Still open :upside_down_face: )

Code coverage is still broken in the case you call your function in an assertTrue:

For example if I have a function: ``yolo(uint256 a);``

if I wrote in my test file:

```solidity
assertTrue(yolo(1));
```

When running  ``forge coverage`` it will show me in the code coverage report that my function have not being tested.

:frowning:

**Comment by PaulRBerg** [comment]
Can you share the full target code that you're covering?

I have recently discovered quite a few bugs in the coverage command. Your issue might be a special case of other lower-level bugs.

**Comment by 0xAurelou** [comment]
Sure I will sample some test, hope my issue won't be forget like my last one :cry:

**Comment by KholdStare** [comment]
@0xAurelou Were you able to create a minimal test case?

**Comment by PaulRBerg** [comment]
@KholdStare make sure to see my [list of reported bugs in `forge coverage`](https://github.com/foundry-rs/foundry/issues/1961#issuecomment-1427113699).
