### ISSUE TITLE
Getting "FAIL. Reason: path error:" when using json objects in memory

### ISSUE THREAD

**Issue by gbalabasquer** [foundry-rs/foundry#4307]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (249538f 2023-02-08T00:12:05.805004Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

Using the latest version of `forge` and cloning: https://github.com/makerdao/dss-test you can reproduce this issue.

Set these env variables `FOUNDRY_ROOT_CHAINID = 1`, `MAINNET_RPC_URL`, `OPTIMISM_RPC_URL`, `ARBITRUM_ONE_RPC_URL` and `ARBITRUM_NOVA_RPC_URL`.
Then, run `make test`.

This issue didn't exist in `forge 0.2.0 (cd7850b 2023-02-02T00:05:14.844624Z)`

**Comment by mattsse** [comment]
cc @odyslam

**Comment by gbalabasquer** [comment]
I guess you are already know, but just in case, I found the commit that introduced it: https://github.com/foundry-rs/foundry/commit/4b5303dae3c833c856ff106474a3f0da8e02d22a

**Comment by hexonaut** [comment]
Ah this issue is because I reference JSON fields without the leading `.` just because it's cleaner. This previously was working and now it's not.

**Comment by hexonaut** [comment]
Talked to @odyslam and I think we can close this issue. We were using json pathing incorrectly by not prepending a `.` for accessing root object.

**Comment by gbalabasquer** [comment]
Closing it!

**Comment by Valentin-Seehausen** [comment]
For anyone else wondering how to change their codebase, this is the reference code: https://book.getfoundry.sh/cheatcodes/parse-json#how-to-use-stdjson

Should be something like this:

```
bytes memory transactionDetails = json.parseRaw(".transactions[0].tx");
// Or, if you use a variable:
bytes memory data = json.parseRaw(string.concat(".", name));
```
