### ISSUE TITLE
Is there any play to support deploy multiple contracts with programmable logic?

### ISSUE THREAD

**Issue by Metal-joker** [foundry-rs/foundry#4312]
### Component

Forge, Cast

### Describe the feature you would like

I am currently facing a dilemma when deploying a DApp, which usually requires deploying multiple contracts. Part of the construct args in these contracts are usually another contract that has just been deployed, and there are usually some settings that need to be interacted with the blockchain after the contract is deployed. 
When using Hardhat, you can write a deployment script in js/ts to take care of it, but when using Foundry, I have to keep `forge create`, then copying the address, then `forge create` again, and finally writing some long commands use `cast`. This is not a very good workflow. 
Have I done something wrong or is this how everyone does it? 
Does Foundry have plans to support programmable contract deployment?

**Comment by mds1** [comment]
It sounds like `forge script` is what you are looking for: https://book.getfoundry.sh/tutorials/solidity-scripting

**Comment by jamesmccomish** [comment]
Scripting works well for deployments, but maybe you will still struggle to link old deployments to new ones (for example, to use the address of the latest deployed version of ContractA in the constructor of ContractB some time later)

[This issue](https://github.com/foundry-rs/foundry/issues/3911) gives some good work arounds

**Comment by Metal-joker** [comment]
I'll have a try on it. Thanks guys @mds1 @jamesmccomish

**Comment by flymauntains** [comment]
Thanks for the article, So In case of multiple contracts in one example.sol, how deploy one contract of them?
For example contractA, contractB, contractC is in the same .sol file because dependency.
In this case, how I deploy contractA? Help me.
