### ISSUE TITLE
bug(forge): coverage does not work when the test contract inherits the target contract

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/foundry#4316]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (249538f 2023-02-08T00:12:05.805004Z)

### What command(s) is the bug in?

forge coverage

### Operating System

macOS (Apple Silicon)

### Describe the bug

The `forge coverage` command generates a 0% coverage report when the test contract inherits the target contract:

```text
| File        | % Lines     | % Statements | % Branches  | % Funcs     |
|-------------|-------------|--------------|-------------|-------------|
| src/Foo.sol | 0.00% (0/8) | 0.00% (0/8)  | 0.00% (0/4) | 0.00% (0/4) |
| Total       | 0.00% (0/8) | 0.00% (0/8)  | 0.00% (0/4) | 0.00% (0/4) |
```

**Comment by PedroReyes** [comment]
Hello @PaulRBerg , @PaulRBerg ,

Same problem here. However, I think this is not related to inheritance.

I have two contracts:

```
contract ContractX is ERC20, ContractY , IContractY
contract ContractY is AccessControlEnumerable, ReentrancyGuard 
```

ContractX is not tested but no coverage is displayed at all in the report. However, ContractY is tested and coverage is displayed in the report.

When I saw this issue request I thought, ok, let's test it. I created a ContractY2 and used the same tests than for ContractY.

The result is that ContractY2 was not displayed in the report either.

When I say "not displayed" I mean that both contracts ContractX and ContractY2 are displayed with everything in read and 0% as you can see in the second row of the next image:

![image](https://user-images.githubusercontent.com/4096108/235745810-a4fe9865-8810-4da6-9542-7346c19a7b77.png)

Hopefully it will be fixed soon. Thanks for the good work you are guys doing with Foundry 😊✌

Best regards,
Pedro Reyes.

**Comment by grandizzy** [comment]
looks similar with https://github.com/foundry-rs/foundry/issues/6875 which was solved in https://github.com/foundry-rs/foundry/pull/8214 please reopen if you still see the issue with latest
