### ISSUE TITLE
Forge fmt fails for new solidity 0.8.18 named mappings

### ISSUE THREAD

**Issue by snreynolds** [foundry-rs/foundry#4319]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (249538f 2023-02-09T00:13:54.988187Z)

### What command(s) is the bug in?

forge fmt

### Operating System

macOS (Apple Silicon)

### Describe the bug

Compiling with solidity version 0.8.18 and using the new named mappings syntax. Contracts are compiling but when running forge fmt I am getting this response: 

Failed to parse Solidity code for <Contract>. Leaving source unchanged.
Debug info: [Diagnostic { loc: File(0, 1147, 1152), level: Error, ty: ParserError, message: "unrecognised token 'owner', expected \"=>\"", notes: [] }, Diagnostic { loc: File(0, 1897, 1904), level: Error, ty: ParserError, message: "unrecognised token 'storage', expected \"(\", \"++\", \"--\", \".\", \"[\", \"case\", \"constant\", \"days\", \"default\", \"error\", \"ether\", \"external\", \"gwei\", \"hours\", \"immutable\", \"internal\", \"leave\", \"minutes\", \"override\", \"private\", \"public\", \"revert\", \"seconds\", \"switch\", \"weeks\", \"wei\", \"{\", identifier", notes: [] }, Diagnostic { loc: File(0, 2017, 2018), level: Error, ty: ParserError, message: "unrecognised token ';', expected \"(\", \"++\", \"--\", \".\", \"[\", \"case\", \"constant\", \"days\", \"default\", \"error\", \"ether\", \"external\", \"gwei\", \"hours\", \"immutable\", \"internal\", \"leave\", \"minutes\", \"override\", \"private\", \"public\", \"revert\", \"seconds\", \"switch\", \"weeks\", \"wei\", \"{\", identifier", notes: [] }, Diagnostic { loc: File(0, 2027, 2031), level: Error, ty: The ParserError, message: "unrecognised token 'emit', expected \"(\", \";\", \"@\", \"[\", \"abstract\", \"address\", \"bool\", \"byte\", \"bytes\", \"case\", \"constructor\", \"contract\", \"default\", \"enum\", \"error\", \"event\", \"fallback\", \"false\", \"function\", \"import\", \"interface\", \"leave\", \"library\", \"mapping\", \"modifier\", \"payable\", \"pragma\", \"receive\", \"string\", \"struct\", \"switch\", \"this\", \"true\", \"type\", \"using\", \"}\", Bytes, Int, Uint, address, hexnumber, hexstring, identifier, number, rational, string", notes: [] }, Diagnostic { loc: File(0, 9461, 9462), level: Error, ty: ParserError, message: "unrecognised token '}', expected \"(\", \";\", \"@\", \"[\", \"abstract\", \"address\", \"bool\", \"byte\", \"bytes\", \"case\", \"contract\", \"default\", \"enum\", \"error\", \"event\", \"false\", \"function\", \"import\", \"interface\", \"leave\", \"library\", \"mapping\", \"payable\", \"pragma\", \"string\", \"struct\", \"switch\", \"this\", \"true\", \"type\", \"using\", Bytes, Int, Uint, address, hexnumber, hexstring, identifier, number, rational, string", notes: [] }]

**Comment by mattsse** [comment]
this just landed yesterday https://github.com/hyperledger/solang/issues/1159

@rkrasiuk probably some breaking changes in the AST. formatting the new node is probably straight forward

**Comment by rkrasiuk** [comment]
i can patch with solang from master until the new version is released

**Comment by rkrasiuk** [comment]
gonna ask about the next version release before patching tho
