### ISSUE TITLE
Panics, crashes if using cached output when compiling with 0.8.17 & 0.8.18

### ISSUE THREAD

**Issue by snreynolds** [foundry-rs/foundry#4320]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (249538f 2023-02-09T00:13:54.988187Z)

### What command(s) is the bug in?

forge test, forge build, forge snapshot

### Operating System

macOS (Apple Silicon)

### Describe the bug

Running `forge build --force` compiles contracts with 0.8.17 & 0.8.18 with no issues but running `forge test` or `forge snapshot` or `forge build` after that will panic/crash.

Also doing `forge clean && forge snapshot` gives same error.

```
The application panicked (crashed).
Message:  No target contract named AddressBuilder.json:AddressBuilder
Location: utils/src/lib.rs:152

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

Also this is running with the backtrace

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   2: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   3: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   4: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   5: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   6: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   7: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   8: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   9: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  10: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  11: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  12: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  13: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  14: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  15: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  16: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>

**Comment by mattsse** [comment]
Does this only happen when switching versions?

I see some leftover panics in that code section that should be removed.

Would you happen to have a repro for this?

does the `AddressBuilder.json` artifact exist?

**Comment by snreynolds** [comment]
Yeah you can pull this branch https://github.com/Uniswap/permit2/pull/183

**Comment by snreynolds** [comment]
```
2023-02-10T15:54:44.218372Z TRACE forge::link: linking contract target="AllowanceTransferTest.json:AllowanceTransferTest"
2023-02-10T15:54:44.218774Z TRACE forge::link: get dependency dependency="AddressBuilder.json:AddressBuilder" file="test/utils/AddressBuilder.sol" key="AddressBuilder"
The application panicked (crashed).
Message:  No target contract named AddressBuilder.json:AddressBuilder
Location: utils/src/lib.rs:152

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
[1]    52538 abort      RUST_LOG=forge::link forge test
```

**Comment by mattsse** [comment]
thank you!

checking

**Comment by mattsse** [comment]
this seems to be a multi version bug

I was able to solve the problem by making these changes to your PR

https://github.com/mattsse/permit2/commit/d5d18b8446415890ff14ae3ba1fd0ae543fd8db5

this makes all used pragmas semver compatible with 0.8.18

**Comment by mattsse** [comment]
okay I believe it's related to this

https://github.com/gakonst/ethers-rs/issues/1995

will fix asap

**Comment by snreynolds** [comment]
Ah ok and will that fix enable us to do versioning without carets? Purposefully have locked those contracts to the strict version without the caret.

**Comment by mattsse** [comment]
found the bug,
https://github.com/gakonst/ethers-rs/pull/2136 will fix most of it.

only need to apply some changes to the linking step, but will ship the fix once the PR is merged.
