### ISSUE TITLE
The anvil service has a large number of network problems in the FIN_WAIT2 state

### ISSUE THREAD

**Issue by woshihahaha** [foundry-rs/foundry#4323]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0

### What command(s) is the bug in?

anvil --fork-url xxxxxx --no-rate-limit --chain-id xxxxx --tracing --host 0.0.0.0 --state-interval 60 --dump-state state.json --load-state state.json --code-size-limit 100000

### Operating System

Linux

### Describe the bug

          
<img width="751" alt="image" src="https://user-images.githubusercontent.com/78835349/218022781-7f0a985e-430d-4b25-aa4f-118f78b6b180.png">

Shortly after anvil started the service, a large number of network connections in the FIN_WAIT2 state appeared, causing the port to fail to connect and the service to be unavailable

**Comment by grandizzy** [comment]
@woshihahaha I tried to reproduce this issue but wasn't able to, I fired anvil and then executed bunch of txes against, can see connections in `TIME_WAIT` that are cleaned after 60s as configured in `/proc/sys/net/ipv4/tcp_fin_timeout`
Please check fin timeout value and network setup (to make sure there's no packet loss, it looks like you're using docker?) and report back if this is still an issue. thank you!
