### ISSUE TITLE
Transaction dropped when testing mempool front-running

### ISSUE THREAD

**Issue by michprev** [foundry-rs/foundry#4327]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

anvil 0.1.0 (249538f 2023-02-10T00:12:17.134368906Z)

### What command(s) is the bug in?

anvil --prune-history 100 --base-fee 0 --steps-tracing --silent --port 36445

### Operating System

Linux

### Describe the bug

I am trying to simulate transactions front-running with anvil and [Woke testing framework](https://ackeeblockchain.com/woke/docs/latest/testing-framework/overview/).

The steps are:
- deploy a simple counter contract
- disable automine
- send the first tx with zero gas price
- send the second tx with non-zero gas price
- send the third tx with zero gas price
- enable automine

All transactions are legacy (type 0) transactions.

The problem is that the first transaction is dropped from the mempool and never mined. I have created an example repository - https://github.com/michprev/anvil-tx-dropped-issue.

See `tests/test_counter.py` for the test source code and `log.txt` for the full JSON-RPC communication log.

The steps to reproduce the issue are:
- install Woke `pip install woke` (Python >= 3.7 < 3.11 needed)
- clone the repository, cd into it
- run `woke test tests/test_counter.py`

Will be happy to provide more information if needed.

**Comment by grandizzy** [comment]
@michprev looks like the repro code changed a little bit, could you update to latest wake version?
Also, is this issue still relevant? thank you!

**Comment by grandizzy** [comment]
@michprev actually I just gave this a try and it works OK if you start anvil with `--order fees` flag, here's a sample using following bash script
```bash
sign=$(cast mktx --gas-price $1 --private-key $2 0x14dC79964da2C08b23698B3D3cc7Ca32193d9955 --value 0.21ether)
curl http://localhost:8545   -X POST   -H "Content-Type: application/json"   --data '{"jsonrpc":"2.0","method":"eth_sendRawTransaction","params":["'$sign'"],"id":1}'
```

and anvil started with `anvil --block-time 30 --order fees`

Then submitting 3 txes from 3 different accounts, first one with gas price 2000000002, 2nd with 2000000005 and 3rd with 2000000000
```bash
./send-tx.sh 2000000002 0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6
0x02f870827a69800184773594028252099414dc79964da2c08b23698b3d3cc7ca32193d99558802ea11e32ad5000080c080a09304fe7441c69381159366050c10d84b00198d9cecc5765692eeb480d262fd04a033d074760316c13e97006faa152064a028fc6ffad76cfbe33f6d03526e9990e2
{"jsonrpc":"2.0","id":1,"result":"0x90816d4b5a60549889ae1728f6d711716b832647b5c299699d8d9dc8d4a6adaf"}

./send-tx.sh 2000000005 0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
0x02f870827a69800184773594058252099414dc79964da2c08b23698b3d3cc7ca32193d99558802ea11e32ad5000080c080a029aaa4ced605a107d23d8c25e18b529871cf8e1ffe324de7a1a6f4ec54f0e8faa077d4422777aa66821f4dceaaaf106329af1ff5eeeda12c5bbb2445b4c3f3dd78
{"jsonrpc":"2.0","id":1,"result":"0x404628cf4c28d576a92ab3377d8484a265008e9ce340d8338c4796d4ac4905e5"}

./send-tx.sh 2000000000 0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6
0x02f870827a69800184773594008252099414dc79964da2c08b23698b3d3cc7ca32193d99558802ea11e32ad5000080c001a0fc061b6b5aaefb45f4c71315bee951b90aa0714a70b842e791357b8c937dc953a078297e9995805470166b0283aba62bf499c2c8a674ba91bb8fee4c4e11c9cd55
{"jsonrpc":"2.0","id":1,"result":"0xecae2863426eb167b33218c668ac9789f11e448a0be3edf5e5176d36dee984b0"}
```

the txes are mined based on gas price

```
    Transaction: 0x404628cf4c28d576a92ab3377d8484a265008e9ce340d8338c4796d4ac4905e5
    Gas used: 21000

    Transaction: 0x90816d4b5a60549889ae1728f6d711716b832647b5c299699d8d9dc8d4a6adaf
    Gas used: 42000

    Transaction: 0xecae2863426eb167b33218c668ac9789f11e448a0be3edf5e5176d36dee984b0
    Gas used: 63000

    Block Number: 1
    Block Hash: 0xd5de32caa85a0489c535618853ccf64c3b234bdd6270e8bad35ee61816ad650b
    Block Time: "Thu, 31 Oct 2024 09:41:21 +0000"
```
Going to close ticket for now, please reopen if still an issue with running anvil with fees order. Thank you!
