### ISSUE TITLE
transactions not pass for minutes on forkmainnet then suddenly recovered and passed

### ISSUE THREAD

**Issue by GopherJ** [foundry-rs/foundry#4340]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

550c548a7aa94a45c1f448071307108867848429

### What command(s) is the bug in?

	anvil \ 		$(if $(FORK),--fork-url https://eth-$(FORK).alchemyapi.io/v2/$(ALCHEMY_KEY) --no-rate-limit,) \ 		--chain-id 522 \ 		--tracing \ 		--host 0.0.0.0 \ 		--state-interval 60 \ 		--dump-state state.json \ 		$(if $(wildcard state.json),--load-state state.json,) \ 		--disable-block-gas-limit \ 		--code-size-limit 100000 \

### Operating System

Linux

### Describe the bug

anvil freezes there:

![image](https://user-images.githubusercontent.com/33961674/218426319-f6932704-1f05-475e-85ad-36c3c2fb9cfa.png)

**Comment by GopherJ** [comment]
This happens quite frequently with anvil, it just freezes there without any logs. Then suddenly all transactions passed. Is it caused by dumping state?

**Comment by zerosnacks** [comment]
Hi @GopherJ, sorry for the delay

I'm unfortunately unable to reproduce the bug with the limited reproduction case.

Please re-open the ticket with a minimal reproduction example with instructions if you are still facing this issue.
