### ISSUE TITLE
Arbitrum Goerli contract verification Page Not Found error

### ISSUE THREAD

**Issue by timurguvenkaya** [foundry-rs/foundry#4342]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (60f36a6 2023-02-11T13:08:41.042378Z)

### What command(s) is the bug in?

forge verify-contract 0xd67F7e9992E8cAEcd9e82e73b9b4732D2A59Fc0F UUPSProxy $ARBITRUMSCAN_API_KEY  --chain 421613

### Operating System

macOS (Intel)

### Describe the bug

I'm trying to verify a contract on arbitrum-goerli, but for some reason, I'm getting **page-not-found** error. I had to pass 

It exists on Arbitrumscan: [Link](https://goerli.arbiscan.io/address/0xd67F7e9992E8cAEcd9e82e73b9b4732D2A59Fc0F)
```
Start verifying contract `0xd67f7e9992e8caecd9e82e73b9b4732d2a59fc0f` deployed on arbitrum-goerli

Submitting verification for [src/UUPSProxy.sol:UUPSProxy] "0xd67F7e9992E8cAEcd9e82e73b9b4732D2A59Fc0F".
2023-02-13T12:38:44.737425Z ERROR etherscan: Failed to deserialize response: expected value at line 1 column 1
res="Page not found"

```

**Comment by JasoonS** [comment]
We are getting the same issue.

`forge 0.2.0 (b44b045 2023-02-21T00:11:41.592203605Z)`

**Comment by mattsse** [comment]
https://api-goerli.arbiscan.io/api is live, at least at the time I'm writing this comment.

could you perhaps share the logs you get by running with `RUST_LOG=forge,foundry-cli`

**Comment by timurguvenkaya** [comment]
Now it works on my end. Maybe they had some issues with API

Could you check again also @JasoonS?

**Comment by JasoonS** [comment]
Thanks, also worked for me yesterday. Can close the issue
