### ISSUE TITLE
Change git default branch to main from master

### ISSUE THREAD

**Issue by AtHeartEngineer** [foundry-rs/foundry#4344]
### Component

Other (please describe)

### Describe the feature you would like

Change git default branch to main from master to match github's default branch

**Comment by curryrasul** [comment]
I can do that if it's relevant. 
As I understand I just need to add:
```rust
Command::new("git").args(["branch", "-M", "main"]).current_dir(root).exec()?;
```
here: https://github.com/foundry-rs/foundry/blob/master/cli/src/cmd/forge/init.rs#LL237C9-L237C99
and here: https://github.com/foundry-rs/foundry/blob/master/cli/src/cmd/forge/init.rs#LL237C9-L237C99

Thanks!

**Comment by zerosnacks** [comment]
Marking as resolved by https://github.com/foundry-rs/foundry/pull/5557#issuecomment-1670137088
