### ISSUE TITLE
Add invariant testing filter for `excludeSelectors()`

### ISSUE THREAD

**Issue by horsefacts** [foundry-rs/foundry#4352]
### Component

Forge

### Describe the feature you would like

Most of the invariant test filter helpers have both `target` and `exclude` variants to include or filter contracts/senders/selectors from fuzzing. But there's no corresponding `excludeSelectors` for `targetSelectors`. 

It's probably a safer practice to start by excluding selectors from invariant test handler contracts to avoid forgetting a function or two for large handlers, so it would be useful to have support for `excludeSelectors`.

**Comment by Rubilmax** [comment]
This would be very helpful
