### ISSUE TITLE
Migrate to revm 3.0

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#4356]
### Component

Forge, Anvil

## TODO
* bump revm

revm migrated to ruint while ethers is on primitive-types, so we expect some breaking changes when it comes to the the different H256,U256 types. 

this will likely require some conversion effort

**Comment by m0ham3dx** [comment]
@mattsse - When  you say "conversion effort" do u mean by [`casting`](https://doc.rust-lang.org/rust-by-example/types/cast.html) ?

**Comment by mattsse** [comment]
yeah but what we need to do in a lot of places is convert `ethers::types::U256` to `ruint::256` for example
because everything from ethers uses different types than everything from revm

**Comment by gakonst** [comment]
Yep - this is temporary until we get ruint etc. into Ethers & rebuild ethabi, so ideally we should try to convert everything to U256/H256 etc. at the boundary when we talk to revm inside of the [evm crate](https://github.com/foundry-rs/foundry/tree/master/evm). It might be leak in some places though..

**Comment by nzhl** [comment]
Any detailed plan on this ? possible ETA ?

**Comment by mattsse** [comment]
almost there #4472
hopefully within a week or so

**Comment by Evalir** [comment]
Done :D
