### ISSUE TITLE
Request for tutorials

### ISSUE THREAD

**Issue by crisgarner** [foundry-rs/foundry#436]
List of requested tutorials 
- [x] getting started 
      - Getting Started by Crisgarner:  https://mirror.xyz/crisgarner.eth/BhQzl33tthkJJ3Oh2ehAD_2FXGGlMupKlrUUcDk0ALA
      - Getting Started by Wilson: https://w.mirror.xyz/mOUlpgkWA178HNUW7xR20TdbGRV6dMid7uChqxf9Z58
      - https://youtu.be/wqFnif_6Mbc
      - Foundry Book (https://github.com/onbjerg/foundry-book)
- [x] basic dir structure
      - Foundry Book (https://github.com/onbjerg/foundry-book)
- [x] unit tests
      - Foundry Book (https://github.com/onbjerg/foundry-book)
- [x] fuzz tests
     - Getting Started by Wilson: https://w.mirror.xyz/mOUlpgkWA178HNUW7xR20TdbGRV6dMid7uChqxf9Z58 
     - Foundry Book (https://github.com/onbjerg/foundry-book)
- [x] traces for debugging
      - Foundry Book (https://github.com/onbjerg/foundry-book)
- [x] mainnet forking
      - [Mainnet Forking](https://mirror.xyz/susheen.eth/bRCzT2QLdNINMVk8251udkfjHW_T9ascCQ1DV9hURz0) by @SusheendharVijay
      - Foundry Book (https://github.com/onbjerg/foundry-book)
- [x] cheatcodes
      - WIP by @Crisgarner
      - Foundry Book (https://github.com/onbjerg/foundry-book)
- [ ] snapshot tests / using them to figure out gas optimizations
- [x] debugger
      - Foundry Book (https://github.com/onbjerg/foundry-book)
- [ ] forge run rapid prototyping
- [ ] non-conventional directory structures
- [ ] libraries (Forge Standard Library)

**Comment by odyslam** [comment]
https://github.com/onbjerg/foundry-book

**Comment by SusheendharVijay** [comment]
Hey @crisgarner I can write a quick guide to mainnet forking, simulating a uniswap swap.

**Comment by crisgarner** [comment]
> Hey @crisgarner I can write a quick guide to mainnet forking, simulating a uniswap swap.

Awesome! let me know when it's ready to publish it.

**Comment by BenSparksCode** [comment]
Feature requests for the book - does anyone know how to do this in Foundry?:

- Profiling average gas cost of each function based on tests
- Showing size of compiled contract and settings for an optimizer during compilation

**Comment by onbjerg** [comment]
Hey, open the requests for the book in the book repository so I can keep track :smile: I'll be working more on it this week

**Comment by ZeroEkkusu** [comment]
We should feature the book somewhere on the repo. I haven't seen any mentions of it in the readme files.

Those who need help could find it easily (maybe in the [Getting Help](https://github.com/gakonst/foundry#getting-help) section for now), while others could contribute/keep track of ideas like above there, and ultimately coordinate efforts.

**Comment by SusheendharVijay** [comment]
> > Hey @crisgarner I can write a quick guide to mainnet forking, simulating a uniswap swap.
> 
> Awesome! let me know when it's ready to publish it.

Hey @crisgarner got a bit delayed (omicron 😢 ). But here it is [Mainnet forking with Forge](https://mirror.xyz/susheen.eth/bRCzT2QLdNINMVk8251udkfjHW_T9ascCQ1DV9hURz0). Give it a look and lmk if I need to many any changes. Thanks! 🔥 🔧

**Comment by daodao2007** [comment]
I wrote an introduction to Chinese in https://learnblockchain.cn/article/3502

**Comment by crisgarner** [comment]
Awesome @SusheendharVijay and @daodao2007  just added them to the list of resources

**Comment by onbjerg** [comment]
Going to close this issue to keep the issue tracker clean-ish, but please do submit content and tutorials to the book :smile:
