### ISSUE TITLE
Bump solang to match ethers

### ISSUE THREAD

**Issue by odyslam** [foundry-rs/foundry#4367]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

master

### Operating System

None

### Describe the bug

Currently, it's not possible to use `ethers-rs` and `foundry` as deps in a rust project, because ethers-rs has bumped `solang`, but foundry has not. 

I tried to bump it, but it needs some changes to `forge-doc` and `forge-fmt` that don' seem trivial. For now, opening an issue to keep track of this.

**Comment by mattsse** [comment]
did you try patching it?

I don't think there are breaking changes that affect ethers, so please feel free to open a PR that simply bumps the version

**Comment by odyslam** [comment]
@mattsse, probs a silly question, but what do you mean?

I tried manually updating the solang version to `0.2.2` in forge, but things broke in `fmt` and `docs`. I will try again and return with concrete examples. Perhaps you can help me debug it and bump it :)

**Comment by rkrasiuk** [comment]
@odyslam this was resolved in #4328
