### ISSUE TITLE
Ability to gracefully shutdown a spawned anvil task

### ISSUE THREAD

**Issue by kevincheng96** [foundry-rs/foundry#4377]
### Component

Anvil

### Describe the feature you would like

I am trying to shutdown an anvil task created from `anvil::spawn`. Normally, we would get the `JoinHandle` from spawning a `tokio` task and call `handle.abort()` on it. However, `anvil::spawn` returns a custom `NodeHandle` which doesn't seem to ever expose the underlying `JoinHandle`.

Is there some other way to shutdown the task? If not, it would be helpful to have access to the `JoinHandle` of the task.

**Comment by mattsse** [comment]
I'd accept a PR for this that cleans this up a bit:

https://github.com/foundry-rs/foundry/blob/8be635b6d7541d68cbe9a58ae8b618c4c73c1b5b/anvil/src/lib.rs#L211-L212

this is basically just a select of two joinhandles.

we could just keep them as individual fields in the `NodeHandle` instead.

it also looks like the `NodeService` task doesn't necessarily resolve if the shutdown signal was fired, so perhaps we integrate this via a tokio::select instead

```rust
   select!{
      shutdown,
      service
  }
```

**Comment by hayesgm** [comment]
Curious on your thoughts on this approach [https://github.com/foundry-rs/foundry/compare/master...compound-finance:foundry:poll-on-futures](https://github.com/foundry-rs/foundry/compare/master...compound-finance:foundry:poll-on-futures), basically just surfacing the two JoinHandles from the node service and the anvil server in the `NodeHandle` struct and then just polling on them similar to the `IpcTask`. Overall, I think it's simpler and accomplishes the same goal as the select statement.

**Comment by mattsse** [comment]
this seems fine!

**Comment by hayesgm** [comment]
Thanks, see https://github.com/foundry-rs/foundry/pull/4422

**Comment by zerosnacks** [comment]
Support was added in https://github.com/foundry-rs/foundry/pull/4422

Let me know if this is not the case @kevincheng96
