### ISSUE TITLE
cast call address ...

### ISSUE THREAD

**Issue by siyangyuandegit** [foundry-rs/foundry#4378]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ecddbdb 2023-02-17T00:17:53.55725Z)

### What command(s) is the bug in?

cast call '0x6b175474e89094c44da98b954eedeac495271d0f' "totalSupply()(uint256)" --rpc-url https://eth-mainnet.alchemyapi.io/v2/Lc7oIGYeL_QvInzI0Wiu_pOZZDEKBrdf

### Operating System

macOS (Apple Silicon)

### Describe the bug

The address of the call  is considered to be ens name
Failed to resolve ENS name: ens name not found: 0x6b175474e89094c44da98b954eedeac495271d0f

**Comment by siyangyuandegit** [comment]
cast balance 0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9
this command has the same problem
ens name not found: 0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9

**Comment by coopbri** [comment]
I am having this issue on cast 0.2.0 (build ecddbdb 2023-02-17T00:11:42.4198088Z) with `cast send`:

```
cast send 0xBC4CA0EdA7647A8aB7C2061c2E118A18a936f13D [...]

Error: 
Failed to resolve ENS name: ens name not found: 0xBC4CA0EdA7647A8aB7C2061c2E118A18a936f13D
```

**Comment by DaniPopes** [comment]
update your foundry version with `foundryup`

**Comment by coopbri** [comment]
I did -- there's a reason why I reported it after the issue was closed. Should have clarified in my previous comment. One thing I did not try was a reinstall of Foundry, so I will give that a shot.

**Comment by DaniPopes** [comment]
build `ecddbdb 2023-02-17T00:11:42.4198088Z` is from a day before this was fixed, meaning you didn't update correctly, please try again after updating to the latest version.

**Comment by coopbri** [comment]
Understood, there must be a silent error when running `foundryup` (of course, likely due to a corrupt Foundry install). But again was able to get this to work on another device so I can work around it for now. Thanks for your help!
