### ISSUE TITLE
chisel `!edit` fails if `!traces` enabled

### ISSUE THREAD

**Issue by AllTradesz** [foundry-rs/foundry#4393]
### Component

Chisel

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (cd7850b 2023-02-02T00:55:54.773018765Z)

### What command(s) is the bug in?

chisel !edit

### Operating System

Linux

### Describe the bug

Trying to edit the source of the run function with `!edit` fails in this quite recent build. Rebuilding to latest `master` would take me too long, so just posting so:
```js
alltrdz@beefy-dev:~/repos/beefy-onchain-harvester$ chisel                                            
Welcome to Chisel! Type `!help` to show available commands.                                          
➜ !edit
Traces:
  [135] 0xBd770416a3345F91E4B34576cb804a576fa48EB1::run()                                            
    └─ ← ()

⚒️ Chisel Error: Failed to execute edited contract!
➜ !so
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.17;

import {Cheats} from "forge-std/Vm.sol";

contract REPL {
    Cheats internal constant vm = Cheats(address(uint160(uint256(keccak256("hevm cheat code")))));   

    /// @notice REPL contract entry point
    function run() public {}
}

➜ !t
Disabled traces!
➜ !edit
Successfully edited `run()` function's body!
➜ !so
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.17;

import {Cheats} from "forge-std/Vm.sol";

contract REPL {
    Cheats internal constant vm = Cheats(address(uint160(uint256(keccak256("hevm cheat code")))));

    /// @notice REPL contract entry point
    function run() public {
        uint256 ui = 88;
    }
}

➜ ui
Type: uint
├ Hex: 0x58
└ Decimal: 88
➜ 
```

**Comment by mattsse** [comment]
is this still an issue?

@clabby mind taking a look at this?

**Comment by grandizzy** [comment]
I am not able to replicate this, edit works properly in latest version even with traces off
![image](https://github.com/user-attachments/assets/5cee842e-8b49-48b0-9fc5-3992cb31a1b3)

Please reopen if still an issue, thank you!

**Comment by grandizzy** [comment]
oops, sorry , the issue was traces enabled which still fails, reopening
