### ISSUE TITLE
Working tests failing with "[FAIL. Reason: Invalid data] setUp()" on Windows

### ISSUE THREAD

**Issue by Iaroslav-Mazur** [foundry-rs/foundry#4396]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (cb925b1 2022-11-21T16:24:05.0674358Z)

### What command(s) is the bug in?

forge test

### Operating System

Windows

### Describe the bug

For a newly-installed Foundry project with running tests (confirmed on the other machines), I cannot make the test run successfully: they fail during the setUp() execution, with [FAIL. Reason: Invalid data] setUp().

I'm currently running forge 0.2.0 (cb925b1 2022-11-21T16:24:05.0674358Z) on Windows 11.

The general advice for this issue both in this group and inside the Foundry Discussions on GitHub is to update Foundry. However, when I try doing this (by building from source via cargo install --git https://github.com/foundry-rs/foundry foundry-cli anvil chisel --bins --locked), I keep getting the following error:
![image](https://user-images.githubusercontent.com/22785348/220046802-807f9569-1ae5-485b-808d-238980ccfbf2.png)

What's wrong and how can I fix this?

**Comment by Iaroslav-Mazur** [comment]
The cause of the error, to my shame, is, likely, the lack of the necessary rights to execute the moving of `forge.exe` to another location.
Either that - or the version of rust/rustup that's being used to compile Foundry from source.

I've just tried updating Foundry again, making sure my rust & rustup are up to date, and that I'm running the command line with admin privileges (even though I thought I had the latter assured previously, as well...) - and it worked:
![image](https://user-images.githubusercontent.com/22785348/226322520-821bbcc9-dc1a-4455-83b5-a3f003a6d219.png)

I'm closing this issue for now, and will reopen it if I happen to reproduce it in the future.

**Comment by mds1** [comment]
Closing per the above comment :)
