### ISSUE TITLE
Cannot install OpenZeppelin dependency via `forge install`

### ISSUE THREAD

**Issue by DevABDee** [foundry-rs/foundry#4398]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a44159a 2023-01-02T00:04:03.149129083Z)

### What command(s) is the bug in?

forge install Openzeppelin/openzeppelin-contracts --no-commit

### Operating System

Windows

### Describe the bug

I'm trying to install OZ contracts/dependencies but It's getting stuck (omitting no error). Solmate is installing pretty smoothly. It looks like others are facing the same issue as well: https://github.com/foundry-rs/foundry/issues/4096

**Comment by DevABDee** [comment]
Closing this issue. Don't know how but OZ contracts just got installed after giving it one more try after deleting the folder and cloning the repo again.

**Comment by Trozz00** [comment]
I'm facing the same problem too, i tried to clone the project in anothe workspace but i'm facing the same problem.  when i run the command: "forge install" i get this.

> Error: 
The target directory is a part of or on its own an already initialized git repository,
and it requires clean working and staging areas, including no untracked files.

Check the current git repository's status with `git status`.
Then, you can track files with `git add ...` and then commit them with `git commit`,
ignore them in the `.gitignore` file, or run this command again with the `--no-commit` flag.

**Comment by DevABDee** [comment]
@Trozz00 try this command: `forge install Openzeppelin/openzeppelin-contracts --no-commit`

**Comment by caoyifeng007** [comment]
> @Trozz00 try this command: `forge install Openzeppelin/openzeppelin-contracts --no-commit`

It works for me.

**Comment by Phenzic** [comment]
> @Trozz00 try this command: `forge install Openzeppelin/openzeppelin-contracts --no-commit`

Still got the error 
![Submodule error 3](https://github.com/foundry-rs/foundry/assets/69092079/fa7a230c-d159-4023-ba57-5de580b41bc6)

**Comment by drex007** [comment]
Add it as submodule instead using this command
git submodule add --depth 1 https://github.com/OpenZeppelin/openzeppelin-contracts lib/openzeppelin-contracts
