### ISSUE TITLE
Change method name prank to larp `startLarp(address)` `stopLarp()`

### ISSUE THREAD

**Issue by dangerousfood** [foundry-rs/foundry#4407]
### Component

Forge

### Describe the feature you would like

change the name of `startPrank(address)` to `startLarp(address)` and `stopPrank()` to `stopLarp()`

### Additional context

`larp` good `prank` bad

**Comment by shazow** [comment]
Agree that prank is confusing, maybe even more familiar name for the function would be `sudo`? (Passing in an empty sudo could revert back to the top level sender).

**Comment by grandizzy** [comment]
we're going to stick with prank at least for 1.0 then reconsider
