### ISSUE TITLE
Memory Allocation overflow on `abi.decode()`

### ISSUE THREAD

**Issue by pscott** [foundry-rs/foundry#4409]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (b44b045 2023-02-21T00:22:41.521901Z)

### What command(s) is the bug in?

forge test --optimize --vv

### Operating System

macOS (Apple Silicon)

### Describe the bug

I’m getting the error [FAIL. Reason: Memory allocation overflow] on one of my tests.
it happens when I run abi.decode() like so:

```solidity
// Structre of `Indexed Strategy`
struct IndexedStrategy {
  uint8 i;
  bytes b;
};

...

// Actual code that fails
(
    address v,
    uint256 id,
    Choice choice,
    IndexedStrategy[] memory uvs,
    string memory reason
) = abi.decode(data, (address, uint256, Choice, IndexedStrategy[], string));
```

This code works just fine if I remove `reason`. It also works just fine if I remove `uvs` and keep `reason`.
I get the same error if I interchange `reason` and put it between `id` and `choice` (I thought maybe it had to do with two dynamic args being next to each other).

**Comment by mattsse** [comment]
this is an evm panic.
can you try after increasing the `memory_limit`

```
forge config | grep memory                                                                                                                                                                                                                 
memory_limit = 33554432
```

not sure if that's exposed in cli, if not we should

**Comment by pscott** [comment]
> this is an evm panic ref https://soliditydeveloper.com/solidity-0.8 0x41 can you try after increasing the `memory_limit`
> 
> ```
> forge config | grep memory                                                                                                                                                                                                                 
> memory_limit = 33554432
> ```
> 
> not sure if that's exposed in cli, if not we should

Cheers. Indeed 
```
➜  tmp git:(main) ✗ forge config | rg memory         
memory_limit = 33554432
```

Haven't found a way to increase the memory limit via CLI.
Also I'm not sure why this would trigger `0x41`: my `IndexedStrategy` array holds 1 element and `reason` is set to `""`.. 🤔

**Comment by mattsse** [comment]
unfamiliar with the internals but `Memory allocation overflow` is the mapped error for the evm panic with 0x41

**Comment by mattsse** [comment]
can you try with something ridiculous like 1GB?

@rakita Under what circumstances is the memory limitation in the evm actually violated?

**Comment by pscott** [comment]
`memory_limit = 1000000000` still fails.
I wonder if `memory_limit` is actually taken into account because I have no way of knowing whether the memory limit actually is `1GB` or the default one

**Comment by mattsse** [comment]
hmm, perhaps this is actually unrelated to the revm env setting @rakita?

**Comment by rakita** [comment]
> can you try with something ridiculous like 1GB?
> 
> @rakita Under what circumstances is the memory limit in the evm actually violated?

Do you mean this: https://github.com/bluealloy/revm/blob/main/crates/primitives/Cargo.toml#L60
It is memory inside `Interpreter`, when there is for example MSTORE that wants to write to the memory location with offset of 20gb, this would trigger.

**Comment by mattsse** [comment]
this error is decoded from a revert/panic here

https://github.com/mattsse/foundry/blob/13c1cf724a5657a7c7005560f773ffd9a59d8962/evm/src/decode.rs#L117-L118

for 
> // allocating too much memory or creating too large array

is this unrelated to the memory_limit setting?

**Comment by pscott** [comment]
Nvm.. this error actually gets thrown when you try to decode something invalid (in my case, I forgot to add the last argument when ENCODING, so decoding was failing).

Would have expected another error to pop, not a weird memory overflow error but.. such is life.

sorry for wasting your time :(

**Comment by mattsse** [comment]
nice!

good to know, thanks for sharing
