### ISSUE TITLE
Command for local source verification against deployed contract bytecode

### ISSUE THREAD

**Issue by k1rill-fedoseev** [foundry-rs/foundry#4410]
### Component

Forge

### Describe the feature you would like

During our deployment and release process, we would like to have more transparency about contents of deployed contracts.
Currently, there is no straightforward way to verify that source code of the deployed contract matches with the locally compiled one.

Ideally, we would like to have an ability to quickly verify the deployed contract bytecode and its metadata hash against bytecode of a locally compiled contract. This would be a nice addition to the existing `forge verify-contract` CLI.

For example, such CLI could behave in the following way:
```
$ forge verify-bytecode --rpc-url <RPC> <ADDRESS> <CONTRACT> --constructor-args <ARGS>
Compiler run successful!
Compiler version: solc v0.8.18
Optimizer settings: 200 runs

Full match!
Local bytecode hash: 0x<hash>
Deployed bytecode hash: 0x<hash>
Local metadata hash: 0x<hash>
Deployed metadata hash: 0x<hash>
```

**Comment by zerosnacks** [comment]
Resolved by https://github.com/foundry-rs/foundry/pull/7319
