### ISSUE TITLE
Unable to run forge install and build 

### ISSUE THREAD

**Issue by mariaxu1019** [foundry-rs/foundry#4425]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0

### What command(s) is the bug in?

forge install transmissions11/solmate Openzeppelin/openzeppelin-contracts

### Operating System

macOS (Apple Silicon)

### Describe the bug

I am following the Creating an NFT with Solmate tutorial and got stuck on forge build saying the application crashed. I tried deleting the folder hello_foundry and starting over. However, now I am stuck on forge install and the bug is "The target directory is a part of or on its own an already initialized git repository". Does anyone have any ideas on how I can completely wipe what I did before and restart the tutorial or just how to fix this issue? Thanks

**Comment by mattsse** [comment]
managing deps as gitmodules continues to be a pain.

I'd recommend to wipe the project folder entirely and try again:

```
forge init
forge install transmissions11/solmate
forge install Openzeppelin/openzeppelin-contracts
```

**Comment by mariaxu1019** [comment]
How do I wipe the project folder entirely? I deleted it from my computer but it didn't seem to work. Used forge init --force instead to initialize

**Comment by dvncan** [comment]
I am having the same error and I found the steps that cause the error are building or testing before installing all libs. 
1. init
2. run test
3. modify (create new) test
4. forge install (fail)  

so i started a new project and 
1. init
2. forge install (worked)

**Comment by Evalir** [comment]
Closing—solution provided in the issue.
