### ISSUE TITLE
tx.origin are overwritten in forge script

### ISSUE THREAD

**Issue by teddav** [foundry-rs/foundry#4434]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (c5dd9a6 2023-02-26T00:12:08.486636Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

I'm using `forge script` to run transactions and deploy contracts. Usually everything works well but I'm running into an issue where the tx.origin seems to be changing in the middle of a script.
Here is my code:
```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.18;

import "forge-std/Script.sol";

import { console, Script } from "forge-std/Script.sol";

contract MyScript is Script {
    string network = "local";

    function setUp() public {
        vm.createSelectFork(network);
        uint256 pk = vm.envUint("PRIVATE_KEY");
        vm.startBroadcast(pk);
    }

    function run() public {
        ExternalContract ext = new ExternalContract();

        MyContract my = new MyContract();
        my.test(address(ext));

        vm.stopBroadcast();
    }
}

contract MyContract {
    function test(address _external) public {
        ExternalContract ext = ExternalContract(_external);

        console.log(tx.origin);
        ext.extFunc();
        console.log(tx.origin);
    }
}

contract ExternalContract {
    function extFunc() public {}
}
```

The first log shows the correct value: the address generated from the `PRIVATE_KEY` but the second log prints `0x1804c8AB1F12E6bbf3894d4083f33e07309d1f38`

I have `anvil` running and the script is connecting to it.
The command i'm running is `forge script ./script/myscript.s.sol --tc MyScript`
And I have the networks setup in `foundry.toml`:
```
fs_permissions = [{ access = "read", path = ".env"}]

[rpc_endpoints]
local = "http://127.0.0.1:8545"
```

**Comment by mds1** [comment]
Hmm this does seem like a bug, cc @joshieDo. 

Ran both below examples with `PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 forge script ./script/Counter.s.sol --tc MyScript` which is the first anvil private key, but just running it locally, not against a fork, and you'll see the logs differ as shown.

But if you run both of the examples as ` forge script ./script/Counter.s.sol --tc MyScript --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80` instead, `tx.origin` is correctly logged as 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 in all cases

## Example 1

A slightly simpler version of the above, which shows different tx.origin logs.

```solidity
contract MyScript is Script {
    function run() public {
        uint256 pk = vm.envUint("PRIVATE_KEY");
        vm.startBroadcast(pk);
        ExternalContract ext = new ExternalContract();
        MyContract my = new MyContract();
        my.myFunc(ext);
        vm.stopBroadcast();
    }
}

contract MyContract {
    function myFunc(ExternalContract ext) public {
        console.log("MyContract.myFunc-1                          ", tx.origin);
        ext.extFunc();
        console.log("MyContract.myFunc-2                          ", tx.origin);
    }
}

contract ExternalContract {
    function extFunc() public {
        console.log("MyContract.myFunc -> ExternalContract.extFunc", tx.origin);
    }
}
```

```
  MyContract.myFunc-1                           0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
  MyContract.myFunc -> ExternalContract.extFunc 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
  MyContract.myFunc-2                           0x1804c8AB1F12E6bbf3894d4083f33e07309d1f38
```

## Example 2

Moving the contract deploying within the `myFunc` method and the logs show the foundry default sender

```solidity
contract MyScript is Script {
    function run() public {
        uint256 pk = vm.envUint("PRIVATE_KEY");
        vm.startBroadcast(pk);
        MyContract my = new MyContract();
        my.myFunc();
        vm.stopBroadcast();
    }
}

contract MyContract {
    function myFunc() public {
        ExternalContract ext = new ExternalContract();

        console.log("MyContract.myFunc-1                          ", tx.origin);
        ext.extFunc();
        console.log("MyContract.myFunc-2                          ", tx.origin);
    }
}

contract ExternalContract {
    function extFunc() public {
        console.log("MyContract.myFunc -> ExternalContract.extFunc", tx.origin);
    }
}
```

```
== Logs ==
  MyContract.myFunc-1                           0x1804c8AB1F12E6bbf3894d4083f33e07309d1f38
  MyContract.myFunc -> ExternalContract.extFunc 0x1804c8AB1F12E6bbf3894d4083f33e07309d1f38
  MyContract.myFunc-2                           0x1804c8AB1F12E6bbf3894d4083f33e07309d1f38
```

**Comment by SuperHero123123** [comment]
I still have this problem. After calling callback function in my contract, tx.origin changes back to 0x1804c8AB1F12E6bbf3894d4083f33e07309d1f38(default user?)
