### ISSUE TITLE
Option to decode return data in `cast call`

### ISSUE THREAD

**Issue by ckoopmann** [foundry-rs/foundry#4435]
### Component

Cast

### Describe the feature you would like

# Current behaviour 

The returned data is displayed in it's raw hex encoded form, making it hard to read. (See screenshot).
<img width="1132" alt="image" src="https://user-images.githubusercontent.com/15629702/221453844-ca4c6580-f0cd-4d35-a6a2-330495aa6e49.png">

# Desired behaviour

It'd be great to give the user the option to have the returned data decoded if the contract abi is available (for example on etherscan). 
For this purpose I'd suggest:
1. Adding a `--decode` flag that results in the data being decoded if the abi is available.
2. Optional: `--return-type` argument that lets the user manually specify the return type for decoding.

In the example given above the `cast call` command should return the decoded string "WETH" when passed the `--decode` flag.

**Comment by ckoopmann** [comment]
I'd love to implement this if judged desirable. 
Should be rather straightforward to implement imo as we have similar decoding happening elsewhere already. (For example in the traces shown by `cast run`).

**Comment by k1rill-fedoseev** [comment]
Seems like the following already does what you want:
```
$ cast call --rpc-url https://cloudflare-eth.com 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2 "symbol() (string)"
WETH
```

**Comment by mds1** [comment]
Yep exactly what @k1rill-fedoseev said! This is already supported. Another example is `cast call $weth "balanceOf(address)(uint256)" vitalik.eth`

**Comment by ClementWalter** [comment]
How to handle `struct`? I have a function that return a struct defined as 

```
struct MyStruct {
    uint256 id;
    address owner;
    bytes value;
}
```

the raw output from `call` is for example:

```
0000000000000000000000000000000000000000000000000000000000000020
0000000000000000000000000000000000000000000000000000000000000000
000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266
0000000000000000000000000000000000000000000000000000000000000060
0000000000000000000000000000000000000000000000000000000000000020
00000000000000000000000000000000000000000000000000000000000004d2
```

but adding `(uint256,address,bytes)` doesn't work 

```
Error: 
could not decode output. did you specify the wrong function return data type perhaps?

Context:
- Invalid data
```

**Comment by mds1** [comment]
For a struct you need to represent it as a tuple, try `((uint256,address,bytes))` instead, e.g. `foo()((uint256,address,bytes))`
