### ISSUE TITLE
Add `eth_maxPriorityFeePerGas` to Anvil Node

### ISSUE THREAD

**Issue by rzmahmood** [foundry-rs/foundry#4436]
### Component

Anvil

### Describe the feature you would like

Hey team, wanted to ask if it was possible to add eth_maxPriorityFeePerGas to the Anvil Node? My team is using the Golang Geth generated bindings to interact with the chain, but we are adding integration tests using an ephemeral chain. We tried hardhat node but they don't implement this method as it's Geth Specific. 
When we tried to deploy a contract using the geth bindings pointing to a hardhat node, it fails for this reason. 

Would be great if the anvil team could take an edge here, even if it's hardcoded to any value for testing

**Comment by mattsse** [comment]
supportive of that.

if no one picks it, I'll be able to add this within the next few days

**Comment by samlaf** [comment]
Just found this. Does cast not support calling this?
```
>>> anvil --help | grep price
 --gas-price <GAS_PRICE>
       The gas price
```
don't see any way to call the eth_maxPriorityFeePerGas endpoint, and have to use curl instead. Am I missing something?
