### ISSUE TITLE
meta(inspectors): tracking issue for inspectors refactor

### ISSUE THREAD

**Issue by mds1** [foundry-rs/foundry#4445]
### Component

Forge

### Describe the feature you would like

WIP, goal is to refactor the inspectors to reusable things (maybe we could pull them inside of revm e.g. for calltracing)

**Comment by zerosnacks** [comment]
Would the https://github.com/paradigmxyz/revm-inspectors crate sufficiently cover the design goal of this ticket or are there more actionable items (cc @DaniPopes)? If not we can close it I think.
