### ISSUE TITLE
forge cast call on a RPC endpoint with HTTPS returns invalid peer certificate: UnknownIssuer

### ISSUE THREAD

**Issue by anthony-yeong-partior** [foundry-rs/foundry#4446]
### Component

Forge, Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (0078471 2023-02-27T00:04:02.311166787Z)

### What command(s) is the bug in?

cast call --rpc-url="https://something:8545"

### Operating System

Linux

### Describe the bug

This is similar reported in #2873

Installed the latest with:
curl -L https://foundry.paradigm.xyz | bash

However, unable to call RPC endpoint with a self-signed certificate. Getting following error:
```
Error:
error sending request for url (https://something:8545/): error trying to connect: invalid peer certificate contents: invalid peer certificate: UnknownIssuer

Context:
- Error #0: error trying to connect: invalid peer certificate contents: invalid peer certificate: UnknownIssuer
- Error #1: invalid peer certificate contents: invalid peer certificate: UnknownIssuer
```

Rootca has been placed in /usr/local/share/ca-certificates/ and /etc/ssl/certs/ - and ran "sudo update-ca-certificates".

Have tried exporting each of the following but all returned same results:
SSL_CERT_FILE=/etc/ssl/certs
SSL_CERT_FILE=/etc/ssl/certs/rootca.pem
SSL_CERT_FILE=/usr/local/share/ca-certificates/
SSL_CERT_FILE=/usr/local/share/ca-certificates/rootca.pem

Note: Verified rootca is placed properly by running "curl https://something:8545"

**Comment by zerosnacks** [comment]
Resolved by https://github.com/foundry-rs/foundry/pull/4792
