### ISSUE TITLE
Error in plugin hardhat-foundry: User-configured sources path (./contracts) doesn't match path configured in foundry (contracts)

### ISSUE THREAD

**Issue by 0xKarl98** [foundry-rs/foundry#4448]
### Component

Other (please describe)

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e4a2915 2022-06-19T02:24:29.337547Z)

### Operating System

macOS (Intel)

### Describe the bug

I have checked the corresponding files according to this error ,  i.e. hardhat.config.ts & foundry.toml 

here is hardhat.config.ts : 
'''paths: {
    sources: "./contracts",
    tests: "./test",
    artifacts: "./artifacts",
    cache: "./cache",
  },
'''

here is foundry.toml :
'''
default = { libs = ["node_modules", "lib"] }
[profile.default]
src = './contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path  = './cache_forge'
'''

i have ensured both of them are using './contracts ' , but the error still persists .

**Comment by matYang** [comment]
FYI I ran into the same issue with VS code Hardhat plugin, uninstall & reload & reinstalling the plugin solved the issue for me

**Comment by matYang** [comment]
I was seeing this error as well with the VS Code Solidity (by Nomic) plugin, uninstalling, reloading, and then reinstalling the plugin worked for me.

**Comment by grandizzy** [comment]
please reopen this in https://github.com/foundry-rs/hardhat repo if still an issue. Thank you!
