### ISSUE TITLE
Is it possible to easily deploy a bin file only using forge?

### ISSUE THREAD

**Issue by bitcoinmeetups** [foundry-rs/foundry#4449]
Hi there,

I'm BM, a very nice and polite guy.

Is it possible to easily deploy a bin file only using forge?

Mockup:

forge deploy file1.bin 

Something like that.

**Comment by mattsse** [comment]
I believe you can use pipe it to cast send if file is hex or hex first and then `cast send --create $data`

**Comment by Evalir** [comment]
Closing. Stale and solution provided.
