### ISSUE TITLE
Know on which test forge is stuck

### ISSUE THREAD

**Issue by AlbertoCentonze** [foundry-rs/foundry#4452]
### Component

Forge

### Describe the feature you would like

When I'm running some unit tests on foundry I often get stuck on one for some reason (bad fuzzing, slow rpc, ecc). Since I have hundreds of tests, it would be nice to know on which test I'm stuck. Currently this output 
![image](https://user-images.githubusercontent.com/11707683/222000685-90d9ddd9-9667-44d5-9e0a-37583adb27d3.png)
is shown only when all the tests in the contracts have passed (or failed). This doesn't let me know which contract I should check.

### Additional context

In case you're wondering why I don't figure out on the fly that my tests are getting stuck is because I'm using watcher mode.

**Comment by mattsse** [comment]
that makes sense, I'll add a warning like:

```
 SLOW [> 60.000s] <test> slow
```

**Comment by AlbertoCentonze** [comment]
The most important thing in my opinion would be to have the warning during the execution of the test and not after it's done. And most importantly know which test is causing the issue

**Comment by mattsse** [comment]
yes that's why I'm suggesting emitting a warning if a test exceeded like 60s and is still running

**Comment by AlbertoCentonze** [comment]
Amazing thanks!

**Comment by AlbertoCentonze** [comment]
Also a nice to have would be for slow tests with fuzzing, to know at which run of the fuzzing the current test is (ie 123/256)

**Comment by mattsse** [comment]
cc @Evalir

**Comment by mds1** [comment]
Seems related to https://github.com/foundry-rs/foundry/issues/585, maybe worth tackling both at the same time?

**Comment by 0xMelkor** [comment]
Taking this up

**Comment by Evalir** [comment]
Gave this a bit of thought recently along with #585. 

- I think we could do this using [`indificatif`](https://github.com/console-rs/indicatif) which is what nextest uses.
- For having "test events" (mainly pointing out slow events), we could use an `unbounded_channel` that sends `TestEvent`s to the runner for when a test is slow.
- We can add a smol progress bar with a countup (X/Y) of the current run and total runs to be done, whenever a fuzz test comes up.
- This status bar could also show the name of the current test being run.
