### ISSUE TITLE
anvil: make block time configurable with foundry.toml

### ISSUE THREAD

**Issue by holic** [foundry-rs/foundry#4453]
### Component

Anvil

### Describe the feature you would like

`anvil` has a `--block-time` argument/option, but that doesn't appear to be configurable with `foundry.toml` (or, if it is, it's undocumented).

I'd love for this to be made available. In fact, it would be great if most/all anvil options were configurable via `foundry.toml`.

**Comment by zerosnacks** [comment]
Related: https://github.com/foundry-rs/foundry/issues/4226
