### ISSUE TITLE
feat(forge) --build-only to whitelist test files to be rebuilt

### ISSUE THREAD

**Issue by valle-xyz** [foundry-rs/foundry#4460]
### Component

Forge

### Describe the feature you would like

Problem: In a situation with a lot of test files, the dependency paths of test files cannot be entangled. This leads to a situation, where a change at one of the chore contracts (ChoreContract.sol) will lead to a very long compilation time of all test files.

Solution: Add a command like `--build-only "test/unit/this-one-file.t.sol"`. In this case, a change to ChoreContract.sol will a) rebuild all files in src/ that import this contract, but b) no file in the test folder, except `test/unit/this-one-file.t.sol`. This will reduce the build time of tests, and make sure that fast iterations loops can happen at a late project phase ("Tests need to run fast.", [Uncle Bob](https://blog.cleancoder.com/uncle-bob/2014/09/03/TestTime.html)).

Addition: As this will be run with the ´--watch´ option most of the time, maybe the same logic could be applied that checks which tests to re-run. The logic would then be extended to only re-compile this file.

**Comment by grandizzy** [comment]
@valle-xyz `forge build` supports now 
```
  [PATHS]...
          Build source files from specified paths
```

which can be multiple paths to single files or dirs, e.g. `forge build src/Dapp.sol` will build single file, `forge build src/Dapp.sol tests` will build one file and all tests, etc.

Going to close this one, please reopen if you hit issues with current impl. Thank you
