### ISSUE TITLE
bug(chisel): importing and deploying contract wrecks the REPL

### ISSUE THREAD

**Issue by exp-table** [foundry-rs/foundry#4467]
### Component

Chisel

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0

### Operating System

macOS (Apple Silicon)

### Describe the bug

Importing a contract, whether from `src` or `test`, does not work and wrecks chisel.

I have provided an example below.

```console
➜ import "src/L1/Fountain.sol";
➜ Fountain public ftn = new Fountain(address(0), address(0));
➜ ftn
Failed to find REPL contract!
➜ uint public a;
➜ a
Failed to find REPL contract!
```

**Comment by mlgarchery** [comment]
Just importing seems to be enough to break the REPL

**Comment by mattsse** [comment]
@clabby 
I'm lacking some context what 

> Failed to find REPL contract!

actually means in this context and what the assumptions here are

**Comment by mlgarchery** [comment]
Maybe I can provide more.
In my case, running chisel at the root of a forge project, then importing a library ends up like said above:
![chisel_import](https://user-images.githubusercontent.com/16239564/229517931-52f51422-088e-4df8-91eb-b9364583e885.png)

**Comment by mattsse** [comment]
I wasn't able to reproduce this in the forge default repro with the Counter contract.

could you please prepare a repro for this?

**Comment by mlgarchery** [comment]
@mattsse Here it is : https://github.com/mlgarchery/chisel-imports
I narrowed down the issue, I was able to reproduce when importing something that contains an import
