### ISSUE TITLE
bug(forge): invariant test fails with [FAIL. Reason: Arithmetic over/underflow], same sequence passes with unit test

### ISSUE THREAD

**Issue by prateek105** [foundry-rs/foundry#4470]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (f96e0ba 2023-03-03T01:47:26.815053Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

Running an invariant test using forge gives `[FAIL. Reason: Arithmetic over/underflow]` error when `fail_on_revert = true` in `foundry.toml`. 

When the same sequence is run in a unit test(regression test) it shows no such error. The traces for both the invariant test and the regression test are exactly similar, but invariant fails while regression test passes.

I am adding sample test contract, test handler and test invariant that replicates the bug. The test contract is a simple contract that increments and decrements a counter with a few conditions. Also increment is called before every decrement. This means that counter can never be less than zero, which is our invariant.

### TestContract
```
contract TestContract {
    uint256 public counter;
    uint256 internal previousUpdate;
    constructor(uint256 counter_) {
        counter = counter_;
        previousUpdate = block.timestamp;
    }

    function increment() external {
        counter += 1;

        if(block.timestamp - previousUpdate > 2 hours) {
            previousUpdate = block.timestamp;
        }
    }

    function decrement() external {
        counter -= 1;

        if(block.timestamp - previousUpdate > 2 hours) {
            previousUpdate = block.timestamp;
        }
    }
}
```

### TestHandler
```
import "forge-std/Test.sol";

contract TestHandler is Test {

    TestContract _test;
    
    constructor(address testContract_) {
        _test = TestContract(testContract_);
    }

    function increment() public {
        _test.increment();
        vm.warp(block.timestamp + 3 hours);
    }

    function decrement() public {
        increment();
        _test.decrement();
    }
}
```

### Invariants

```
import "forge-std/Test.sol";

contract TestInvariants is Test {

    TestContract internal _testContract;
    TestHandler internal _testHandler;

    function setUp() public virtual {
        _testContract = new TestContract(1);
        excludeContract(address(_testContract));
        _testHandler = new TestHandler(address(_testContract));

        targetSender(address(0x1234));
    }

    // an invariant that should always hold 
    function invariant_counter() public {
        require(_testContract.counter() > 0, "Incorrect counter");
    }
}
```
#### This is the unit test with exact same failing sequence, but passes here.
```
// tests failing invariant sequence
contract TestRegression is TestInvariants {

    // the failing invariant sequence passes this regression test without any Arithmetic over/underflow revert
    function test_overflow_error() external {
        invariant_counter();
        _testHandler.decrement();
        invariant_counter();
        _testHandler.decrement();
        invariant_counter();
    }
}
```

### foundry.toml
```
[invariant]
runs           = 1000  # The number of calls to make in the invariant tests
depth          = 2     # The number of times to run the invariant tests
call_override  = false # Override calls
fail_on_revert = true  # Fail the test if the contract reverts
```

Also I found that the invariant runs if I make either of these changes:
1. time is not skipped
2. `if(block.timestamp - previousUpdate > 2 hours)` changed to `(block.timestamp >= previousUpdate && block.timestamp - previousUpdate > 2 hours) `

**Comment by prateek105** [comment]
Found a workaround for this issue in [maple-core-v2](https://github.com/maple-labs/maple-core-v2) repository invariant testing.
Maple are using these two modifiers to get things working:
- [useCurrentTimestamp](https://github.com/maple-labs/maple-core-v2/blob/main/tests/invariants/BaseInvariants.t.sol#L34)
- [useTimestamps](https://github.com/maple-labs/maple-core-v2/blob/main/tests/invariants/actors/LpHandler.sol#L62)

**Comment by mds1** [comment]
IIUC the issue is that the state/timestamp changes are not committed between calls within an invariant run, in which case I'll close this as a duplicate of https://github.com/foundry-rs/foundry/issues/3005. Please feel free to reopen if I misunderstood
