### ISSUE TITLE
Can't compile after update forge-std to 1.5

### ISSUE THREAD

**Issue by 0xDmtri** [foundry-rs/foundry#4473]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (f96e0ba 2023-03-03T01:47:26.815053Z)

### What command(s) is the bug in?

forge build

### Operating System

macOS (Apple Silicon)

### Describe the bug

First of all, I wanted to bump my deps, and ran `forge update` as I usually do (was running 1.1.0), which resulted in an error of git submodules. So to cure it I simply `forge remove && forge install`. And then after that I started getting this error on build:

Compiler run failed
YulException: Variable _28 is 1 too deep in the stack [ JUNK JUNK _28 _3 _18 memPtr_2 srcEnd _22 src _2 _21 _23 _25 dst memPtr_3 srcEnd_1 src_1 dst_1 value_2 ]
memoryguard was present.

I even tried removing other deps and compiling pure solidity but I would still get this error. Any ideas? 

P.S. I do have Yul in my code and I do know that I have to use `--via-ir` :)

**Comment by mattsse** [comment]
this is thrown by solc.
could be that some recent changes affected your stack.
but hard to tell without additional context.

**Comment by 0xDmtri** [comment]
> this is thrown by solc. could be that some recent changes affected your stack. but hard to tell without additional context.

Yeah, makes sense, so weird tho, works with 1.1.1 but doesnt with 1.5.0, same compiler. Everything is the same lol. Possibly 1.5.0 has changed some args for Solc?

**Comment by 0xDmtri** [comment]
> this is thrown by solc. could be that some recent changes affected your stack. but hard to tell without additional context.

Massive LoL, idk why, but if I comment out anything within those two tests, it fucking works lol. I dont see massive stack usage there tbh...

<img width="1037" alt="Screenshot 2023-03-03 at 10 36 26 PM" src="https://user-images.githubusercontent.com/33504992/222845055-e081fe31-3d65-40c6-b813-8552515e65fd.png">
