### ISSUE TITLE
Enable using `forge fmt --root <PATH> '[PATH]...'`

### ISSUE THREAD

**Issue by h0tw4t3r** [foundry-rs/foundry#4478]
### Component

Forge

### Describe the feature you would like

I use `lint-staged` to lint only the staged files, but my smart contracts are stored in a monorepo.

Thus, in order to use the `contracts/foundry.toml` config, I have to pass the `--root` of the foundry project.

So now I have the following `lint-staged` rule:

```json
"lint-staged": {
    "contracts/**/*.sol": [
      "forge fmt --root contracts"
    ]
  }
```
But unfortunately, I receive the next error.
![Снимок экрана 2023-03-05 в 15 46 39](https://user-images.githubusercontent.com/35642018/222964249-c0607d1a-c0b9-419c-98ed-f880c593f346.png)

Thus I can't really have lint on staged files enabled along with the custom formatting rules, instead default rules are applied.

**Comment by h0tw4t3r** [comment]
@mds1 I actually consider this a bug now, as the error and the usage guide are quite controversial, check the screenshot precisely.

**Comment by h0tw4t3r** [comment]
@mds1 Can we change this to a bug?

**Comment by rkrasiuk** [comment]
from `lint-staged` docs:
```
This project contains a script that will run arbitrary shell tasks with a list of staged files as an argument, filtered by a specified glob pattern.
```

`forge fmt` command accepts either std input, file paths or the root of the project to run formatter on. these arguments are mutually exclusive as specified in the `conflicts_with` attribute below. 
https://github.com/foundry-rs/foundry/blob/50738dd48660f594106d41267776496b97509307/cli/src/cmd/forge/fmt.rs#L24-L39

when `lint-staged` command runs, it passes the file paths as arguments which leads to a conflict with the `--root` arg. correct usage would be
```json
"lint-staged": {
    "contracts/**/*.sol": [
      "forge fmt"
    ]
}
```
since the arguments provided are already filtered by the glob.

Closing this issue as a user error. Happy to answer any other questions about the usage of this command

**Comment by h0tw4t3r** [comment]
> when lint-staged command runs, it passes the file paths as arguments, leading to a conflict with the --root arg. correct usage would be 
    ```
    "lint-staged": {
        "contracts/**/*.sol": [
          "forge fmt"
        ]
    }
    ```
  since the arguments provided are already filtered by the glob.

I have to doubt that. Can they somehow not be mutually exclusive?

Such is basically disabling formatting by custom config in the monorepos...

I believe that mine user error could be an error not just for me as a user, since some of the DApps want to enable rapid development by having a monorepo and yet use the newest toolings such as Foundry.

However, my particular case is next:
```
.
├── README.md
├── apps
├── contracts
├── node_modules
├── package.json
├── packages
├── pnpm-lock.yaml
├── pnpm-workspace.yaml
├── remappings.txt
└── turbo.json
```

> I leave `remappings.txt` so Solidity LSP running in VSCode doesn't go crazy. 

`foundry.toml` is hidden in the `contracts` folder. I tried first as you propose, to simply have `forge fmt` in the `lint-staged` script to format staged files, but the formatting rules I state in the config are not being respected.

Only when I do `forge fmt --root contracts` or format the files from the `contracts` folder one by one fixes the issue.

I would love to see those arguments to work together.

------
Thanks for diving into `lint-staged` library which probably not comes from your area of development.

**Comment by rkrasiuk** [comment]
i see, the root also defines the path to config file. we should still leave this as a feature request tho

**Comment by h0tw4t3r** [comment]
> i see, the root also defines the path to config file. we should still leave this as a feature request tho

Yeah, it would be more convenient if there had been any info about mutual args exclusiveness in `--help`, as it is incomplete and led me to think such usage is permitted.

Thus I thought about moving this to a bug – related to the `--help`. But my bet would be that it's the cmd framework that probably does not handle it, and there has to be some better description if such cases exist not only here.

**Comment by h0tw4t3r** [comment]
@rkrasiuk, just in case so it is not lost, GH Automation moved that to _Done_, but should be in _To do_ in the Project Board.

😃

**Comment by h0tw4t3r** [comment]
@rkrasiuk can we confirm this is on track?
