### ISSUE TITLE
Minimum Supported Rust Version (MSRV) not enforced in CI

### ISSUE THREAD

**Issue by SamWilsn** [foundry-rs/foundry#448]
The [README](https://github.com/gakonst/foundry/blob/a49473af557b3ce72efdd0ca4aecc5052b66e7aa/README.md#minimum-supported-rust-version) says:

> The current minimum supported Rust version is `rustc 1.54.0 (a178d0322 2021-07-26)`.

As far as I could tell, only the `stable` toolchain is checked through GitHub actions.

**Comment by onbjerg** [comment]
It is now enforced via the `rust-toolchain` file
