### ISSUE TITLE
Support Encrypt/Decrypt function with specified private key.

### ISSUE THREAD

**Issue by jhweintraub** [foundry-rs/foundry#4480]
### Component

Forge

### Describe the feature you would like

I'm building some things and need to be able to encrypt and decrypt data before passing it as a function parameter. You already allow for signing using a private key with `vm.sign`, I would like two functions 

`decryptMessage(uint256 ownerPrivateKey, bytes message)` and returns the bytes returned from decrypting with ownerPrivateKey

`encryptMessage(uint256 recipientPublicKey, bytes message)` that encrypts `message` using `recipientPublicKey`

**Comment by mds1** [comment]
I think this is out of forge's scope and something that makes more sense as an external library, not a native forge feature. There are many ways to encrypt something, each with various tradeoffs, and devs should understand the encryption approach they are using.

**Comment by jhweintraub** [comment]
How would you suggest going about using this as an external library with foundry?  I think it would be a simple feature to implement to just utilize the ECC secp256k1 curve that Ethereum uses. If I write this functionality in myself would yall consider approving it?

**Comment by mds1** [comment]
I'd recommend using `vm.ffi` and calling out to a script to handle encryption/decryption. In theory adding this as a cheat code is reasonable, but I'm not convinced it's a good idea yet. Can you share more info about your use case? My main concerns are around:
- Adding a cheat code tailored to a use case, when encryption needs vary quite a bit, and now a niche use case needs to be maintained.
- What encryption algorithm are you going to use? You can use ECDH to generate a shared secret but still need to encrypt the data somehow.

**Comment by zerosnacks** [comment]
Marking as `not planned` for the reasons stated by @mds1 

It is recommended to use `vm.ffi` for this use case
