### ISSUE TITLE
chisel errors upon the code below

### ISSUE THREAD

**Issue by zhiqiangxu** [foundry-rs/foundry#4481]
### Component

Chisel

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e2fa2b5 2023-02-19T00:15:20.51416Z)

### What command(s) is the bug in?

chisel

### Operating System

macOS (Intel)

### Describe the bug

Here's the complete steps to reproduce the bug:

```
% RUST_BACKTRACE=1 chisel   
Welcome to Chisel! Type `!help` to show available commands.
library Search {
   function indexOf(uint[] storage self, uint value) public view returns (uint) {
      for (uint i = 0; i < self.length; i++) if (self[i] == value) return i;
      return self.length;
   }
}
contract Test {
   uint[] data;
   constructor() public {
      data.push(1);
      data.push(2);
      data.push(3);
      data.push(4);
      data.push(5);
   }
   function isValuePresent() external view returns(uint){
      uint value = 4;
      
      //search if value is present in the array using Library function
      uint index = Search.indexOf(data, value);
      return index;
   }
}
Test a = new Test()
```

The output:

```
thread 'main' panicked at 'No bytecode for contract.', /Users/runner/work/foundry/foundry/chisel/src/executor.rs:40:58
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
zsh: abort      RUST_BACKTRACE=1 chisel
```

**Comment by mattsse** [comment]
@clabby looks like this happens when `REPL` contract does not exist, see #4495

I'm not that familiar with the internals, what would be the fix here?

**Comment by zerosnacks** [comment]
Now throws error: "No bytecode found for `REPL` contract"

**Comment by grandizzy** [comment]
the error message ` No bytecode found for REPL contract` is due to external `library Search` hence bytecode not linked. In order to make the sample work change the visibility of `indexOf` function to internal so it will get inline in REPL contract
```Solidity
function indexOf(uint[] storage self, uint value) internal view returns (uint)
```
Going to close this issue as we don't have plans to extend this functionality to external libs, feel free to reopen if you disagree. Thank you!
