### ISSUE TITLE
Foundry does not parse [etherscan] section of foundry.toml

### ISSUE THREAD

**Issue by debych** [foundry-rs/foundry#4484]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (28b2ae6 2023-03-06T00:04:12.952149891Z)

### What command(s) is the bug in?

forge verify-contract

### Operating System

Linux

### Describe the bug

1) With these settings:
```
[etherscan]
polygon = { key = "${POLYGON_ETHERSCAN_API_KEY}", url = "https://api.polygonscan.com/api" }
```
Using `forge verify-contract --chain polygon <Address> <Name>` gives:

`ETHERSCAN_API_KEY must be set`

Though key is set in the foundry.toml

2) With these settings:
```
[etherscan]
boba = { key = "${BOBA_ETHERSCAN_API_KEY}", url = "https://api.bobascan.com/api" }
```

Using `forge verify-contract --chain boba<Address> <Name>` gives:

`[ETHERSCAN_API_KEY must be set](error: invalid value 'boba' for '--chain <CHAIN>': Expected known chain or integer, found: boba)`

Though the settings for **boba** are set

**Comment by DaniPopes** [comment]
We're not checking with config here:

https://github.com/foundry-rs/foundry/blob/1d9a34ecfe265d49b4237c9eb670d5aec389b646/cli/src/cmd/forge/verify/mod.rs#L190

CC @mattsse, but I think this applies to many other commands, see: #4474, #4057, #3824

**Comment by mattsse** [comment]
oh, nice find @DaniPopes 
do you want to take this on?

**Comment by debych** [comment]
It works only if I pass the `--etherscan-api-key` parameter

**Comment by debych** [comment]
@mattsse @DaniPopes 
Unfortunately, not fixed guys...
Using forge 0.2.0 (df8ab09 2023-03-14T10:00:26.197329Z)

**Comment by DaniPopes** [comment]
pls open another issue with all details possible, like command with all flags and all files necessary

**Comment by dimitar-nikovski** [comment]
Is there a solution for this? Still seeing this on version `forge 0.2.0 (008922d 2024-04-23T00:23:10.634984900Z)`

**Comment by DADADAVE80** [comment]
> @mattsse @DaniPopes I have updated to **forge 0.2.0 ([ed9298d](https://github.com/foundry-rs/foundry/commit/ed9298df05442040c126ee2a668e494a68cb1b6f) 2023-03-09T00:04:28.809303436Z)** but seems like the issue is not fixed
> 
> `forge verify-contract --chain bsc <address> <name> `
> 
> still gives me
> 
> `ETHERSCAN_API_KEY must be set`
> 
> The config is such:
> 
> ```
> [etherscan]
> bsc = { key = "${BSC_ETHERSCAN_API_KEY}", url = "https://api.bscscan.com/api" }
> ```

Worked for me, thanks
