### ISSUE TITLE
anvil exited without any error message

### ISSUE THREAD

**Issue by GopherJ** [foundry-rs/foundry#4488]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (1d9a34e 2023-03-06T13:49:53.917536365Z)

### What command(s) is the bug in?

anvil \         --fork-url https://eth-mainnet.alchemyapi.io/v2/xxxx --no-rate-limit \         --chain-id 522 \         --tracing \         --host 0.0.0.0 \         --state-interval 60 \         --dump-state state.json \          \         --disable-block-gas-limit \         --code-size-limit 100000 \

### Operating System

Linux

### Describe the bug

```
eth_getTransactionReceipt

    Transaction: 0xad7e780dc641dc6670f690943aa7e7b2c06d5b91cf046af652ed945edfaca85a
    Gas used: 236361

    Block Number: 16773314
    Block Hash: 0x7841ea17339f535db19aca0582921ab79c6595e98a846a341b3c51dfc83f7cfb
    Block Time: "Tue, 07 Mar 2023 02:52:59 +0000"

eth_chainId
eth_getTransactionCount
eth_chainId
eth_blockNumber
eth_chainId
eth_getTransactionReceipt
make: *** [Makefile:601: anvil] Killed
```

anvil exited but no error message was thrown

**Comment by mattsse** [comment]
could be out of memory, because --tracing requires a lot of memory.

**Comment by grandizzy** [comment]
I am not able to reproduce this with latest version, started anvil using
```bash
anvil --fork-url https://mainnet.infura.io/v3/key --no-rate-limit --chain-id 522 --tracing --host 0.0.0.0 --state-interval 60 --dump-state state.json --disable-block-gas-limit --code-size-limit 100000
```

and then run
```bash
while true; do curl -H "Content-Type: application/json" --data '{"method":"eth_getTransactionReceipt","params":["0x7114b4da1a6ed391d5d781447ed443733dcf2b508c515b81c17379dea8a3c9af"], "id":1,"jsonrpc":"2.0"}' http://localhost:8545; done
```

for more than 10 minutes, without anvil crashing and memory stable

@GopherJ can you please recheck and reopen if still an issue for you? thank you
