### ISSUE TITLE
Lost events after accident exit

### ISSUE THREAD

**Issue by GopherJ** [foundry-rs/foundry#4490]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (1d9a34e 2023-03-06T13:49:53.917536365Z)

### What command(s) is the bug in?

anvil \         --fork-url https://eth-mainnet.alchemyapi.io/v2/xxxx --no-rate-limit \         --chain-id 522 \         --tracing \         --host 0.0.0.0 \         --state-interval 60 \         --dump-state state.json \         --load-state state.json \         --disable-block-gas-limit \         --code-size-limit 100000 \

### Operating System

Linux

### Describe the bug

I set anvil to dump state periodically. However the state is still corrupted after an accident exit. The implementation contract address got reverted to previous one. The events that I can scan previously cannot be scanned again

**Comment by grandizzy** [comment]
@GopherJ anvil dump / load state was enhanced in latest versions, please retest and reopen if still an issue (would be great also to get more details as what the exit was done). thank you!
