### ISSUE TITLE
Use `--deny-warnings` on specific directory

### ISSUE THREAD

**Issue by pscott** [foundry-rs/foundry#4494]
### Component

Forge

### Describe the feature you would like

Currently, running `forge build --deny-warnings` or `forge test --deny-warnings` applies the `--deny-warnings` file to all the files compiled.

It can happen that a library you use emits a warning, which makes the whole build fail.

Ideally, the user could decide to enable / disable `--deny-warnings` to specific folders (for example, apply `--deny-warnings` to everything in `src/` but not in `lib/`).

**Comment by elanzalaco** [comment]
Bumping this post, it would be nice to be able to deny warnings on lib/ folder.
Chainlink contracts have lots of warnings cluttering my terminal.

**Comment by XORs33r** [comment]
Bumping this post same reason as above

**Comment by wottpal** [comment]
Dito

**Comment by 0xmonsoon** [comment]
bumping up

**Comment by mattsse** [comment]
@loocapro with the recent changes to warning filter we should be able to do this now, do you want to look into this?

**Comment by loocapro** [comment]
I can take a look, any guidance @mattsse ?

**Comment by zerosnacks** [comment]
Marking as duplicate / resolved by https://github.com/foundry-rs/foundry/issues/1200
