### ISSUE TITLE
feat(cast): Option to disassemble bytecode returned by `cast code`

### ISSUE THREAD

**Issue by ckoopmann** [foundry-rs/foundry#4500]
### Component

Cast

### Describe the feature you would like

To make the result of a `cast code` call a bit more readable it could be nice to give the user the option to disassemble the hex bytecode into individual opcodes.

So if the user adds the `--disassemble` flag instead of printing the hex bytecode `0x6060604052600436106100af576000357c...`
It would print the individual opcodes one per line.

This behaviour can already be achieved by piping the output of `cast code` into a 3rd party tool such as [pyevmasm](https://github.com/crytic/pyevmasm) (see screenshot), but it might be worth integrating it into forge directly.

Alternatively (or additionally) we could also add `disassemble` as a separate command to cast. 

<img width="800" alt="image" src="https://user-images.githubusercontent.com/15629702/223616586-c7d23ae5-9fac-473d-b9c6-6fbd740921a6.png">

**Comment by RyanRHall** [comment]
I believe the feature exists now! The issue can probably be closed :)
