### ISSUE TITLE
The position of chisel command line prompt on windows is displayed incorrectly

### ISSUE THREAD

**Issue by daog1** [foundry-rs/foundry#4503]
### Component

Chisel

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (1d9a34e 2023-03-07T00:06:14.4107988Z)

### Operating System

Windows

### Describe the bug

The position of the cursor is wrong

![1678268335956](https://user-images.githubusercontent.com/1438562/223677503-32d5eecb-817e-4b0a-b67f-e2dac63c8de5.png)

I analyzed the code, the problem lies in the dispatcher.get_prompt function

This can be modified chisel.rs main function
`
let prompt = if cfg!(windows) { format!(">") }else {dispatcher.get_prompt()};
`

**Comment by mattsse** [comment]
nice, catch, do you want to submit a PR with a fix?
unable to test this myself because I don't have access to a windows machine.

**Comment by daog1** [comment]
> nice, catch, do you want to submit a PR with a fix? unable to test this myself because I don't have access to a windows machine.

Ok. Please wait for a moment

**Comment by DaniPopes** [comment]
> unable to test this myself because I don't have access to a windows machine.

🫡
<https://www.virtualbox.org/>
