### ISSUE TITLE
Display error traces in setUp function

### ISSUE THREAD

**Issue by outdoteth** [foundry-rs/foundry#4506]
### Component

Forge

### Describe the feature you would like

During testing, if an error is thrown in `setUp()` then no error traces are shown.
It would be nice to show debug traces with the verbosity set as `-vvv` set just like regular tests.

<img width="486" alt="Screenshot 2023-03-08 at 15 12 35" src="https://user-images.githubusercontent.com/37438950/223751180-36067bb1-96ff-4382-b74b-f26808689755.png">

At the moment it just shows this single line (no matter what verbosity is set to)^

**Comment by mds1** [comment]
Use `-vvvv` to show setup traces for failing tests. You can read about all verbosity options here: https://book.getfoundry.sh/forge/tests#logs-and-traces
