### ISSUE TITLE
Error on "forge init"

### ISSUE THREAD

**Issue by marchev** [foundry-rs/foundry#4514]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ed9298d 2023-03-09T00:05:44.23018Z)

### What command(s) is the bug in?

forge init

### Operating System

macOS (Apple Silicon)

## Steps to reproduce
1. Run `forge init` in a new empty folder.

## Expected result
The command runs successfully without any issues.

## Actual result
The command throws the following error:
```
Initializing /Users/martinmarchev/projects/solidity/ethernaut/token...
Installing forge-std in "/Users/martinmarchev/projects/solidity/ethernaut/token/lib/forge-std" (url: Some("https://github.com/foundry-rs/forge-std"), tag: None)
Error:
usage: git submodule [--quiet] add [-b <branch>] [-f|--force] [--name <name>] [--reference <repository>] [--] <repository> [<path>]
   or: git submodule [--quiet] status [--cached] [--recursive] [--] [<path>...]
   or: git submodule [--quiet] init [--] [<path>...]
   or: git submodule [--quiet] deinit [-f|--force] (--all| [--] <path>...)
   or: git submodule [--quiet] update [--init] [--remote] [-N|--no-fetch] [-f|--force] [--checkout|--merge|--rebase] [--[no-]recommend-shallow] [--reference <repository>] [--recursive] [--] [<path>...]
   or: git submodule [--quiet] summary [--cached|--files] [--summary-limit <n>] [commit] [--] [<path>...]
   or: git submodule [--quiet] foreach [--recursive] <command>
   or: git submodule [--quiet] sync [--recursive] [--] [<path>...]
   or: git submodule [--quiet] absorbgitdirs [--] [<path>...]
```

**Comment by mattsse** [comment]
this looks a git error,
what's your git version?

**Comment by marchev** [comment]
Actually, I've just updated my `git` to `git version 2.39.2` and it all works just fine. My previous version was `git version 2.20.1`. It should probably be mentioned in the docs what is the required `git` version.

**Comment by gavinBP** [comment]
Hey Y'all I just stumbled on here wondering if you might also know what's going on with mine. I followed all of the foundry steps to install foundry and now im just trying to init in a new folder (forge init) and im getting this error:
forge init
──────────────
✖ 'init' is not a valid subcommand. See 'forge --help'
──────────────
ℹ Did you mean this?
  - forge join
  - forge asset
  - forge config
  - forge help
  - forge install
  - forge logs
  - forge ls
  - forge ps
  - forge start
  - forge stop
  - forge tx
  - forge use
  - forge web
(node:20829) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)



for some reason it says init is not valid. How can this be? Am I missing something obvious? I'd really appreciate any advice :,)
