### ISSUE TITLE
Chisel erroring out when importing an external sol file (interface in this case)

### ISSUE THREAD

**Issue by simpledefi** [foundry-rs/foundry#4516]
### Component

Chisel

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ed9298d 2023-03-09T00:04:28.809303436Z)

### Operating System

Linux

### Describe the bug

Start up chisel:
import "iSimpleDefiStaking.txt"
address a = 0x7f9Ef04582Fe662c19A0d016b9FF27E2ca2ADfc6;

Last line generates error:
Failed to find REPL contract!

Welcome to Chisel! Type `!help` to show available commands.
➜ import "iSimpleDefiStaking.txt"
➜ address a = 0x7f9Ef04582Fe662c19A0d016b9FF27E2ca2ADfc6;
Failed to find REPL contract!
➜ !so
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.17;

import {Cheats} from "forge-std/Vm.sol";
import "iSimpleDefiStaking.txt";

contract REPL {
    Cheats internal constant vm = Cheats(address(uint160(uint256(keccak256("hevm cheat code")))));

    /// @notice REPL contract entry point
    function run() public {}
}

iSimpleDefiStaking.txt is really iSimpleDefiStaking.sol (github extension limitation)

[iSimpleDefiStaking.txt](https://github.com/foundry-rs/foundry/files/10933094/iSimpleDefiStaking.txt)

**Comment by mattsse** [comment]
@clabby mind taking a look at this?

perhaps this is the same error as https://github.com/foundry-rs/foundry/issues/4481

**Comment by grandizzy** [comment]
not able to repro with provided file, though after removing the `function stakes(address _user) external returns (SimpleDefiStaking.returnStakes[] memory)` line as `SimpleDefiStaking` is not declared

```
Welcome to Chisel! Type `!help` to show available commands.
➜ import "iSimpleDefiStaking.txt"
➜ address a = 0x7f9Ef04582Fe662c19A0d016b9FF27E2ca2ADfc6;
➜ !so
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.26;

import {Vm} from "forge-std/Vm.sol";

import "iSimpleDefiStaking.txt";

contract REPL {
    Vm internal constant vm = Vm(address(uint160(uint256(keccak256("hevm cheat code")))));

    /// @notice REPL contract entry point
    function run() public {
        address a = 0x7f9Ef04582Fe662c19A0d016b9FF27E2ca2ADfc6;
    }
}
```

going to close for now, please reopen if still an issue. thank you!
