### ISSUE TITLE
Clearer Terminal Errors for Foundry.toml file issues 

### ISSUE THREAD

**Issue by McCoady** [foundry-rs/foundry#4520]
### Component

Forge

### Describe the feature you would like

Currently when running `forge test`, if your foundry.toml file includes invalid characters you get the following message:
```
Error:
unexpected character found: `;` at line 5 column 16
unexpected character found: `;` at line 5 column 16
unexpected character found: `;` at line 5 column 16
unexpected character found: `;` at line 5 column 16
```

It would be nice to give a clearer error message to direct the user to the file where the error originates from.

Similar errors occur if you don't include `solc="x.y.z"` in the toml file but don't make it clear what the issue is or how to fix it.

**Comment by mattsse** [comment]
what's the content of line 5 here for
> unexpected character found: `;` at line 5 column 16
?

> Similar errors occur if you don't include solc="x.y.z" in the toml file but don't make it clear what the issue is or how to fix it.

can you please explain this in more detail, I'm afraid I can't follow which error you are referring to

**Comment by McCoady** [comment]
Hi sorry, will try to explain what was going on.

I mistakenly added a semi-colon at the end of  `solc = "0.8.17"` when setting up my toml file. Then when later trying to run `forge test`, this was the error I received. It would be more helpful if the error could tell the user which file the unexpected character is coming from as it's unclear from reading the error message.
