### ISSUE TITLE
New version of  VSCode breaks the formatter

### ISSUE THREAD

**Issue by zgorizzo69** [foundry-rs/foundry#4529]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (93aa2d0 2023-03-11T00:09:06.544116259Z)

### Operating System

Linux

### Describe the bug

using VSCode 1.76.1 with JuanBlanco.solidity extension installed
in a mono repo with this .vscode/settings.json
```
{
    "editor.formatOnSave": true,
    "[solidity]": {
        "editor.defaultFormatter": "JuanBlanco.solidity" 
      },
    "solidity.compileUsingRemoteVersion": "v0.8.16",
    "solidity.formatter": "forge",
    "solidity.packageDefaultDependenciesContractsDirectory": "src",
    "solidity.packageDefaultDependenciesDirectory": "lib"
}
```
the format on save doesn't work anymore 
I tried opening only the packages/contracts folder in vsCode and also updating the vscode user's setting
It also doesn't work when I do a Format Document (forced)

**Comment by mattsse** [comment]
does `forge fmt` still work?
I guess this issue should be filed in the extension's repo instead?

**Comment by zgorizzo69** [comment]
Yep make sense
