### ISSUE TITLE
forge: more efficient JSON-RPC calls from within test

### ISSUE THREAD

**Issue by jonathanpwang** [foundry-rs/foundry#4534]
### Component

Forge

### Describe the feature you would like

For certain tests I need to get the block hashes of many different blocks. I can do this using `ffi` to call `cast` from terminal, but this ends up being very slow (I'm guessing because it needs to do a subroutine call each time?). It would be great if some cast commands like `eth_getBlock`, `eth_getProof` could be available from within forge test. Even better, if the forge fork caching worked on these requests.

**Comment by mattsse** [comment]
this is basically https://github.com/foundry-rs/foundry/issues/3362 + caching

sgtm, I'll try to finally squeeze this in
