### ISSUE TITLE
flatten broken

### ISSUE THREAD

**Issue by sakulstra** [foundry-rs/foundry#4545]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (d1c84e3 2023-03-13T00:07:48.790822528Z)

### What command(s) is the bug in?

forge flatten

### Operating System

Linux

### Describe the bug

`forge flatten` appears to be broken in certain circumstances.
Can not exactly pinpoint it as it's super inconsistent - with some contracts it works with some it doesn't :shrug: 

Added a reproduction repo here: https://github.com/sakulstra/forge-bug-repro/tree/issue/flatten

Running flatten will yield in the following error:
```
forge flatten lib/aave-v3-core/contracts/protocol/configuration/PoolAddressesProvider.sol                                                                                         
Error: 
Failed to flatten the file: cannot resolve file at ""/home/sakulstra/Documents/bgd/forge-bug-repro/lib/aave-v3-core/contracts/protocol/configuration/PoolAddressesProvider.sol""
```

The file is for sure there, so the error message seems to be wrong.

Running e.g. inspect with the same file will work just fine.
```
forge inspect lib/aave-v3-core/contracts/protocol/configuration/PoolAddressesProvider.sol:PoolAddressesProvider storage-layout --pretty
| Name       | Type                        | Slot | Offset | Bytes | Contract                                                                                          |
|------------|-----------------------------|------|--------|-------|---------------------------------------------------------------------------------------------------|
| _owner     | address                     | 0    | 0      | 20    | lib/aave-v3-core/contracts/protocol/configuration/PoolAddressesProvider.sol:PoolAddressesProvider |
| _marketId  | string                      | 1    | 0      | 32    | lib/aave-v3-core/contracts/protocol/configuration/PoolAddressesProvider.sol:PoolAddressesProvider |
| _addresses | mapping(bytes32 => address) | 2    | 0      | 32    | lib/aave-v3-core/contracts/protocol/configuration/PoolAddressesProvider.sol:PoolAddressesProvider |
```

One thing that's slightly suspicious is the double quoting, but as it works just fine with some contracts, i guess that's not he issue.

**Comment by mattsse** [comment]
this seems to be an error in the preprocess step, perhaps related to paths.

will check.
thanks for the repro

**Comment by mattsse** [comment]
okay found and fixed the issue, this was an edge case that happened when the target file is not part of the project graph (no project file imports it)
