### ISSUE TITLE
excessive mainnet gas estimation without --legacy

### ISSUE THREAD

**Issue by sakulstra** [foundry-rs/foundry#4547]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (d1c84e3 2023-03-13T00:07:48.790822528Z)

### What command(s) is the bug in?

forge 

### Operating System

Linux

### Describe the bug

When using `forge script --broadcast --slow -vvvv` without the `--legacy` flag on mainnet, the baseFee seems wrong(excessive).

On this repo for [example](https://github.com/bgd-labs/static-a-token-v3/blob/main/Makefile) the gas estimation yields:

**mainnet --legacy**: 36gwei
**mainnet**: 73gwei 
**etherscan reference**: 35-38 gwei

**polygon --legacy**: 140 gwei
**polygon**: 177 gwei 
**polygonscan reference**: 130-180 gwei

Probably there was some timing issue when producing the numbers.
That said for me eth non-legacy transactions are consistently priced with a 100% premium, where on other networks they seem to be on par.

Additional info:
I tried a few different rpcs for mainnet (alchemy & public ones) and seems like it's always the same behavior. 1559 on ethereum being excessively priced.

**Comment by mattsse** [comment]
estimate is here 

https://github.com/foundry-rs/foundry/blob/d1c84e3e756c00a5baeab2a7714786e4885d4b0c/common/src/provider.rs#L226-L236

which should trigger this section:

https://github.com/gakonst/ethers-rs/blob/2cead3e11160a48b403d1334eab329d38f10b4fa/ethers-providers/src/rpc/provider.rs#L428-L441

and 

https://github.com/gakonst/ethers-rs/blob/2cead3e11160a48b403d1334eab329d38f10b4fa/ethers-core/src/utils/mod.rs#L453-L453

looks like we need to tune this a bit @prestwich ?

**Comment by prestwich** [comment]
this appears to be a direct result of https://github.com/gakonst/ethers-rs/blob/2cead3e11160a48b403d1334eab329d38f10b4fa/ethers-core/src/utils/mod.rs#L615-L625

which simply doubles the base fee (leading to the 36->73 relationship)

An excessive base fee in a tx is only a problem if the sending account doesn't have funds to cover the max. The basefee here is the max, not the effective payment. As long as the max priority fee is low (seems like it's 1 gwei?) there shouldn't be an issue. This will not cause users to overpay, it will cause their transactions to confirm even if there's a price surge

**Comment by sakulstra** [comment]
@prestwich interesting, pardon my ignorance - would be good if the code was documented a bit :sweat_smile:
What the rationale behind this surge multiplier?
The lower the base fee, the higher the multiplier? 
To me this assumption seems to be incorrect/unfounded as
- on ethereum the price is "mostly stable" (yes it moves up and down, but usually not more than a few gwei per block)
- where on polygon which i assume has a higher base fee already, the volatility is quite high from block to block

While i see now, that eventually it doesn't matter (if you have enough funds on your wallet, i assume otherwise you cannot even execute?).
I think it would be good if estimation would be somewhat closer to reality. At least for me when trying non legacy, the estimated 2x was concerning so i used legacy - assume others might experience the same.

**Comment by prestwich** [comment]
this is @gakonst's code. so I don't know the full rationale

> I think it would be good if estimation would be somewhat closer to reality. At least for me when trying non legacy, the estimated 2x was concerning so i used legacy - assume others might experience the same

generally, we assume that users have a good grasp of EIP1559 transaction fee params. I'm not sure we should adjust the MBF in a way that makes transactions less likely to confirm, in order to quote the same as legacy

**Comment by sakulstra** [comment]
@prestwich fair point. Might make sense to log though, how the fee is composed (base + tip) is the current log doesn't show this afaik.

Also might make sense, to allow users to adjust this surplus (didn't try yet, perhaps i can use gas multiplier 70, to reduce the 100% surplus in case my wallet is short of funds).

**Comment by sakulstra** [comment]
yes, for sure :+1:
