### ISSUE TITLE
feat: forge create ... --interactive

### ISSUE THREAD

**Issue by dcposch** [foundry-rs/foundry#455]
## summary

the `cast` command allows a handful of authentication options, including `--private-key` (for an inline private key) and `--interactive` (to prompt for a private key interactively).

it looks like `forge create` supports the first option but not the second.

**version:**
```
$ forge  --version
foundry-cli 0.1.0
```

**Comment by onbjerg** [comment]
This should work now:. ``forge create --interactive src/Contract.sol:Contract --flashbots`` gives me a prompt to enter my private key
