### ISSUE TITLE
feat(forge): add command line flag to exit after first test failure

### ISSUE THREAD

**Issue by 0xalpharush** [foundry-rs/foundry#4551]
### Component

Forge

### Describe the feature you would like

Testing tools often give the ability to exit upon the first test failure. It would great if `forge test --fail-fast` could be added to accomplish this. This not only provides fast feedback loops for developers but also makes tools that programmatically call forge test like CIs more efficient.

### Additional context

https://docs.pytest.org/en/7.1.x/how-to/failures.html#stopping-after-the-first-or-n-failures

**Comment by mds1** [comment]
Closing as completed by https://github.com/foundry-rs/foundry/pull/4819
