### ISSUE TITLE
Celo native token not compatible with foundry

### ISSUE THREAD

**Issue by kyscott18** [foundry-rs/foundry#4559]
### Component

Forge, Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (df8ab09 2023-03-14T10:00:26.197329Z)

### Operating System

macOS (Apple Silicon)

### Describe the bug

This test fails I think because the celo token is a precompile. This issue is also present in Viem.

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

import { Test } from "forge-std/Test.sol";
import { console2 } from "forge-std/console2.sol";
import { ERC20 } from "solmate/tokens/ERC20.sol";

contract CeloTest is Test {
    ERC20 celo = ERC20(0x471EcE3750Da237f93B8E339c536989b8978a438);

    // deal doesn't work in this case so use an address that already has some celo
    address addr = 0x4117f8C086a0ECA19eA21dE0AE7C5087e3C359fb;

    address recipient = makeAddr("");

    function testCeloBalance() external {
        vm.createSelectFork("celo");
        uint256 balance = celo.balanceOf(addr);

        vm.prank(addr);
        celo.transfer(recipient, 1 ether);

        assertEq(balance - 1 ether, celo.balanceOf(addr));
        assertEq(1 ether, celo.balanceOf(recipient));
    }
}
```

**Comment by DaniPopes** [comment]
This is known. We currently only support mainnet precompiles which are implemented in [Revm](https://github.com/bluealloy/revm), and there's no way to configure this in Foundry. See also https://github.com/foundry-rs/foundry/issues/748.

**Comment by chen4903** [comment]
Are there any other ways to indirectly achieve the same effect? For example, by changing the content of the contract.
