### ISSUE TITLE
--silent should make no logs come through at all

### ISSUE THREAD

**Issue by joshstevens19** [foundry-rs/foundry#4561]
### Component

Anvil

### Describe the feature you would like

When using --silent, I know it says in docs it only silents the startup, but it would be nice to silence the JSON-RPC method names being called to avoid spamming the logs if you do not care for it.

The use case is if you are trying to run a local node in a `child_process`, you have to override the max buffer to infinity for it not to bail out after it's been running for x time over just being able to do --silent and make it run in the background without any noise.

**Comment by mattsse** [comment]
good point, I consider this a bug. fixing

**Comment by joshstevens19** [comment]
awesome thanks a lot
