### ISSUE TITLE
Forge verify does not parse etherscan section of foundry.toml

### ISSUE THREAD

**Issue by debych** [foundry-rs/foundry#4563]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (df8ab09 2023-03-14T10:00:26.197329Z)

### What command(s) is the bug in?

forge verify-contract

### Operating System

macOS (Apple Silicon)

### Describe the bug

Calling this command

`forge verify-contract --chain polygon <address> <name>`

Gives

```
Error: 
ETHERSCAN_API_KEY must be set
```

after probably this [commit](https://github.com/foundry-rs/foundry/commit/93aa2d071b635a838030aa29ad85b52d361f5728). It doesnt work even this way

`forge verify-contract --chain polygon --etherscan-api-key <key> <address> <name>`

getting the same error

**Comment by mattsse** [comment]
cc @DaniPopes 

@debych can you please post your config file.

**Comment by debych** [comment]
@mattsse 
```
[profile.default]
test = 'test/solidity'
solc_version = '0.8.17'
optimizer = true
optimizer_runs = 10000
sender = '<sender>'
tx_origin = '<tx_origin>'
out = 'out'
fs_permissions = [
  { access = "read", path = "./config/" },
  { access = "read-write", path = "./test/logs/" },
]
ffi = true
libs = ["node_modules", "lib"]

[rpc_endpoints]
polygon = "${ETH_NODE_URI_POLYGON}"

[etherscan]
polygon = { key = "${POLYGON_ETHERSCAN_API_KEY}", url = "https://api.polygonscan.com/api" }
```

**Comment by DaniPopes** [comment]
Is the `POLYGON_ETHERSCAN_API_KEY` environment variable set? I just ran this:

```sh
forge init test
cd test
forge build

printf '\n[etherscan]\npolygon = { key = "${POLYGON_ETHERSCAN_API_KEY}" }' >> foundry.toml

# error: ... not set
unset POLYGON_ETHERSCAN_API_KEY
forge v $(cast address-zero) Counter --chain polygon

# error (after making the request to etherscan): invalid api key
export POLYGON_ETHERSCAN_API_KEY="abcd"
forge v $(cast address-zero) Counter --chain polygon
```

**Comment by debych** [comment]
Yes it is set in the `.env` file like so

`POLYGON_ETHERSCAN_API_KEY=<key>`

**Comment by mattsse** [comment]
@debych could you please link the repo or prepare a repro for this?
