### ISSUE TITLE
forge bind overwrite causes a "No such file or directory (os error 2)" if not run before

### ISSUE THREAD

**Issue by ryanorendorff** [foundry-rs/foundry#4570]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (c15becc 2023-03-13T20:15:37.45287Z)

### What command(s) is the bug in?

forge bind --module --single-file  --select "^NAME$"

### Operating System

macOS (Apple Silicon)

### Describe the bug

When running a `forge bind` command for the first time with the `--overwrite` flag, an error is generated (on macOS: `No such file or directory (os error 2)`). This can be mitigated by rerunning the command without the `--overwrite` flag, and then subsequent commands with the `--overwrite` flag should work here.

What I assume is happening is that the `--overwrite` flag tries to do something like remove the files before continuing, but throws this error when a non-existent file cannot be removed.

I would have guessed that the `--overwrite` would work if the generated code did not exist.

**Comment by mattsse** [comment]
closed via #4569
