### ISSUE TITLE
Add way to manually shutdown anvil

### ISSUE THREAD

**Issue by joshstevens19** [foundry-rs/foundry#4585]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

0.2.0

### Operating System

macOS (Apple Silicon)

### Describe the bug

Classing this as a bug, but it could be a feature either way; we can reassign it.

If you are running the anvil node in a child process alongside other code when the main code is shutdown, SIGINT or other codes would throw, but due to the node running in another process, that part does not get closed (understandable). You can listen to these events being emitted to handle these cases, which is fine, but to now clean up and shut down the node, you have to use a bespoke operating system code to kill the port process, aka mac:

```
lsof -t -i tcp:8545 | xargs kill
```

It would be much better if we just had a:

```
anvil shutdown
```

This shuts down the node and can be run on cleanup tasks supporting any OS with the same command. Also, note you may wish to spin up a node and then close it once you have used it and still have the main process running. It seems a handy thing to have. 

It may exist, but I can not see it in the docs.

**Comment by joshstevens19** [comment]
Just straight up command `anvil --shutdown`, maybe? 

`anvil_shutdown` also works as a RPC call

**Comment by aathan** [comment]
If it does not already exist, a command line option to have anvil write a pid file would also be nice. This could then be used with scripts instead of a `pkill ...` or `lsof ...` to find the exact anvil process that must be killed.

**Comment by grandizzy** [comment]
a similar request is tracked in https://github.com/foundry-rs/foundry/issues/2806 as well, going to close this one and keep track of 2806. thank you
