### ISSUE TITLE
vm.rollFork in invariant testing causes panic

### ISSUE THREAD

**Issue by Teamo0** [foundry-rs/foundry#4586]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (97f070f 2023-03-17T09:32:25.079445775Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

Same error message as in https://github.com/foundry-rs/foundry/issues/4572. While #4572 reported error when vm.rollFork is called within invariant test and was fixed, the same error still exists when vm.rollFork is called from a helper contract.
When helperContract.rollFork is explicitly called, we get the panic.
If it is called by the fuzzer, no panic occurs but the fork block is not changed.

Please find basic setup and tests showing the bug in.
https://github.com/Teamo0/FoundryRollFork

**Comment by chalex-eth** [comment]
After running foundryup --nightly, the issue is still here,
When running forge test on this repo : https://github.com/Teamo0/FoundryRollFork
We still get 
```

[⠒] Compiling...
[⠢] Compiling 20 files with 0.8.19
[⠰] Solc 0.8.19 finished in 1.02s
Compiler run successful
The application panicked (crashed).
Message:  called `Option::unwrap()` on a `None` value
Location: /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/revm-2.3.1/src/journaled_state.rs:548

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
zsh: abort      forge t
```

**Comment by mattsse** [comment]
thanks for the repro, will debug this!

**Comment by Teamo0** [comment]
Hey @mattsse ,
thanks for the quick fix. The panic doesn't occur anymore, but unfortunately vm.rollFork() called in the handler contract still doesn't change the state of the fork. When calling forge test on the repro I provided, the invariant assertEq(block.number, initialBlock) passes still after vm.rollFork(block.number + 1) is called by the fuzzer.
Also the application still panics if instead of vm.rollFork(block) we call vm.createSelectFork(API_KEY, block), which should be equivalent cheat codes from my understanding.

![image](https://user-images.githubusercontent.com/77360332/229027822-d9ccae2c-ccdf-4999-b8c5-da55bee58003.png)

Thanks a lot!

**Comment by Teamo0** [comment]
Hey @mattsse,
any update on this? Being able to use rollFork() during invariant testing would be really a huge improvement to simulating real world environment.
