### ISSUE TITLE
Unable to verify contract that uses external library

### ISSUE THREAD

**Issue by j-vp** [foundry-rs/foundry#4587]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (df8ab09 2023-03-14T09:59:20.944687208Z)

### What command(s) is the bug in?

forge verify-contract 0xe1De7d003D27232245B4c6d9D6F29F744f46516b Counter --chain-id 10 --num-of-optimizations 200 --constructor-args $(cast abi-encode "constructor(address)" "0x000000000000000000000000000000000000007B") --watch --compiler-version v0.8.17+commit.8df45f5f -e $KEY

### Operating System

Linux

### Describe the bug

Provided contracts deployed at https://github.com/j-vp/foundry-issue-4587

Running the following command: 
```
forge verify-contract 0xe1De7d003D27232245B4c6d9D6F29F744f46516b Counter --chain-id 10 --num-of-optimizations 200 --constructor-args $(cast abi-encode "constructor(address)" "0x000000000000000000000000000000000000007B") --watch --compiler-version v0.8.17+commit.8df45f5f -e $OPTETHKEY
```

returns with 
```
Start verifying contract `0xe1de7d003d27232245b4c6d9d6f29f744f46516b` deployed on optimism

Submitting verification for [src/Counter.sol:Counter] "0xe1De7d003D27232245B4c6d9D6F29F744f46516b".
Submitted contract for verification:
        Response: `OK`
        GUID: `sp8tqhdsxc3kdxk8xfemggde3a9hvbcebmvz99gcdpqf2k83ud`
        URL:
        https://optimistic.etherscan.io/address/0xe1de7d003d27232245b4c6d9d6f29f744f46516b
Contract verification status:
Response: `NOTOK`
Details: `Pending in queue`
Contract verification status:
Response: `NOTOK`
Details: `Fail - Unable to verify. Error! Plese check for missing Library or invalid name (i.e names are case senstive). Library was required but suitable match not found`
Contract failed to verify.
```

Contract `0xe1de7d003d27232245b4c6d9d6f29f744f46516b` (to be verified) uses an external library deployed at `0xC9c0433D488672B7937929002ae014FE21bbb2FF`, named `ExtLib` (see code).

I cannot seem to get the command working with `--libraries`. For example:

```
forge verify-contract 0xe1De7d003D27232245B4c6d9D6F29F744f46516b Counter --chain-id 10 --num-of-optimizations 200 --constructor-args $(cast abi-encode "constructor(address)" "0x000000000000000000000000000000000000007B") --watch --compiler-version v0.8.17+commit.8df45f5f -e $OPTETHKEY --libraries ExtLib
```
```
forge verify-contract 0xe1De7d003D27232245B4c6d9D6F29F744f46516b Counter --chain-id 10 --num-of-optimizations 200 --constructor-args $(cast abi-encode "constructor(address)" "0x000000000000000000000000000000000000007B") --watch --compiler-version v0.8.17+commit.8df45f5f -e $OPTETHKEY --libraries 0xC9c0433D488672B7937929002ae014FE21bbb2FF
```
```
forge verify-contract 0xe1De7d003D27232245B4c6d9D6F29F744f46516b Counter --chain-id 10 --num-of-optimizations 200 --constructor-args $(cast abi-encode "constructor(address)" "0x000000000000000000000000000000000000007B") --watch --compiler-version v0.8.17+commit.8df45f5f -e $OPTETHKEY --libraries ExtLib:0xC9c0433D488672B7937929002ae014FE21bbb2FF
```
```
forge verify-contract 0xe1De7d003D27232245B4c6d9D6F29F744f46516b Counter --chain-id 10 --num-of-optimizations 200 --constructor-args $(cast abi-encode "constructor(address)" "0x000000000000000000000000000000000000007B") --watch --compiler-version v0.8.17+commit.8df45f5f -e $OPTETHKEY --libraries src/ExtLib.sol
```

all return with 
```Error: 
failed to parse library address: 0xC9c0433D488672B7937929002ae014FE21bbb2FF
``` 
or similar.

The library itself can be verified with `forge verify-contract`

Question: how to use the `--libraries` field?

**Comment by nicolas-geniteau** [comment]
I had the same issue. Valid format for `--libraries` is `file:name:addr` : https://github.com/gakonst/ethers-rs/blob/0b2bf4f6c3d4c5061f833672a23568a928912102/ethers-solc/src/artifacts/mod.rs#L546

`--libraries src/ExtLib.sol:ExtLib:0xC9c0433D488672B7937929002ae014FE21bbb2FF` works.

We should improve documentation for this.

**Comment by Evalir** [comment]
Closing—answer was provided.

**Comment by johnnyonline** [comment]
how do i pass several arguments (i.e. several libraries) to the `--libraries` flag though?

a space or a `,` seems to fail with `failed to parse, too many arguments passed`.

**Comment by johnnyonline** [comment]
> how do i pass several arguments (i.e. several libraries) to the `--libraries` flag though?
> 
> a space or a `,` seems to fail with `failed to parse, too many arguments passed`.

specifying `--libraries` several times did the trick.

**Comment by Karkunow** [comment]
Had the same problem today, it is very annoying that there is no info about how to pass multiple libraries via CLI in docs.
