### ISSUE TITLE
vm.serializeString might produce numbers

### ISSUE THREAD

**Issue by sakulstra** [foundry-rs/foundry#4601]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### Operating System

Linux

### Describe the bug

There's some unexpected behavior with `vm.serializeString`.

When using
```
string memory out = vm.serializeString(key, key, '10000000000000');
vm.writeJson(out, path);
```
It seems like foundry will automatically convert the string to a number if it looks like a number.
This is somewhat unexpected and it hard to work with consumer languages that don't natively support big numbers.

**Comment by mds1** [comment]
cc @odyslam just added this to #3801

**Comment by Thegaram** [comment]
We also ran into this issue -- we want to write a string value but it's instead written as a number, which the consumer (a geth fork) is unable to parse.

**Comment by yash-atreya** [comment]
@sakulstra I cannot reproduce this anymore. Feel free to reopen if you encounter this again.
