### ISSUE TITLE
Core dumped with looping recursion

### ISSUE THREAD

**Issue by QGarchery** [foundry-rs/foundry#4604]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (04e6c91 2023-03-19T00:12:01.130238347Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

When calling a contract that calls itself recursively an unbounded number of time, `forge` crashes with the following message:
![core_dumped](https://user-images.githubusercontent.com/22668539/226211013-184c8ac1-7634-4509-80a9-50d148b750a9.png)

This bug happens when running `forge test` in the following repository: https://github.com/QGarchery/infinite-loop-oracle. I understand that the code is buggy because of the infinite recursion, but I assume that a different error message should be shown instead, such as a revert from the EVM.

**Comment by mattsse** [comment]
this looks like a similar issue to this

https://github.com/foundry-rs/foundry/issues/2106

you have recursion in your test

on my system

you can try this by experimenting with the --gas-limit value. on my system `--gas-limit 1400000000` results in a SO but `--gas-limit 1400000000` reverts

**Comment by QGarchery** [comment]
Oh ok, thanks for the link I couldn't find the other issue. The conclusion is very similar and it's left open, so I'll close this one
