### ISSUE TITLE
feat(debugger): Add indicator for where in the code you currently are 

### ISSUE THREAD

**Issue by Philogy** [foundry-rs/foundry#4607]
### Component

Forge

### Describe the feature you would like

When stepping through code via the `forge debug` TUI I'd like to be able to see the line and source file I'm currently in. This is especially important for larger projects where the execution flow of a single function might be jumping between internal functions defined across dozens of source files.

### Additional context

Part of #4440

**Comment by grandizzy** [comment]
@Philogy would you mind detail the request a little bit? Per screenshot here https://book.getfoundry.sh/forge/debugger#debugger-layout we already highlight the line of code that is executed, thank you!

**Comment by Philogy** [comment]
I think this was related to past issues and sometimes still present issues related to the source map, where even though you have a solidity contract either the contract as a whole is highlighted or the functional as a whole and it doesn't show you where you are, but generally seems better now. I think it's fine to close for now
