### ISSUE TITLE
Forge debugger only highlights memory at word alignments

### ISSUE THREAD

**Issue by Philogy** [foundry-rs/foundry#4608]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (394f217 2023-03-20T00:05:20.377895339Z)

### What command(s) is the bug in?

forge debug

### Operating System

Linux

### Describe the bug

When an `MSTORE` op writes to a section of memory that is not word aligned (`mem_offset != x * 32`) the section of memory highlighted in the debugger's TUI window is still aligned to the word and does not reflect what section of memory is about to be changed by progressing to the next execution step.

Meta: #4440

**Comment by iFrostizz** [comment]
@mattsse could u close this please ?
