### ISSUE TITLE
Auto Impersonation

### ISSUE THREAD

**Issue by koenmtb1** [foundry-rs/foundry#4609]
### Component

Anvil

### Describe the feature you would like

A startup flag or cheatcode (though I've yet to figure out how to get them working using straight up just Anvil) to disable signing checks completely.
Or more easily said, automatically impersonate any person that sends a transaction. This is mainly for testing purposes and prevents me from having to call the impersonate for every address I want to make a transaction with, it saves quit a bit of compute and storage by not having to do this for every transaction.

I'd be happy to provide a PR for this, I already made this locally to test. Happy to start contributing.

**Comment by koenmtb1** [comment]
Implemented with merged PR #4673

**Comment by rickbeeloo** [comment]
Just switched to Anvil, and this is exactly what I thought was missing, cool to see it :) (thanks @koenmtb1) Still getting used to foundry and wondering how I should "enable" the sender cheat when using the RPC. Looking at the commit I suppose I should call `AutoImpersonateAccount` somehow?

**Comment by mattsse** [comment]
we don't have it as cli arg yet, feel free to open an issue for this.

you can call `cast rpc anvil_autoImpersonateAccount true` to toggle it

**Comment by hcheng826** [comment]
quick Q - how does the user specify which address to impersonate?
