### ISSUE TITLE
Cheatcodes directly to Anvil with RPC

### ISSUE THREAD

**Issue by koenmtb1** [foundry-rs/foundry#4610]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (394f217 2023-03-20T00:05:00.028277Z)

### What command(s) is the bug in?

anvil

### Operating System

macOS (Intel)

### Describe the bug

I think I'm doing something wrong when trying to call, but the documentation doesn't say anything about performing cheat codes directly to Anvil (only mentions cheat codes using `vm` in forge).

Currently I'm trying to do this by calling the respective function names (`deal`, `chainId`, etc.) as contract functions on the specified contract address (`0x7109709ECfa91a80626fF3989D68f67F5b1DD12D`). This doesn't seem to be doing anything.

Am I doing something wrong or is this a bug? It seems like the code is there (https://github.com/foundry-rs/foundry/blob/master/evm/src/executor/inspector/cheatcodes/mod.rs#L527) but I don't think it's getting hit.

Besides this I also see that in the documentation it says that the `deal` function has 3 available signatures but I can only find code for the 1st option for setting eth balance and nothing for the ERC20 implementation.

**Comment by mds1** [comment]
Cheat codes cannot be used with anvil, instead you have to use special RPC methods. See [here](https://github.com/foundry-rs/foundry/discussions/4475) (which links to the docs) for more info

**Comment by mds1** [comment]
> Besides this I also see that in the documentation it says that the `deal` function has 3 available signatures but I can only find code for the 1st option for setting eth balance and nothing for the ERC20 implementation.

The others are part of forge-std's `StdCheats`, and are not native cheat codes
