### ISSUE TITLE
Add `/broadcast` to `.gitignore` by default

### ISSUE THREAD

**Issue by PatrickAlphaC** [foundry-rs/foundry#4614]
### Component

Forge

### Describe the feature you would like

Many users use node-as-a-service providers like Alchemy, Infura, or Quicknode to run their transactions. If a user `broadcast`s a transaction, it will be stored in the `broadcast` folder, and includes the RPC URL.

These RPC URLs oftentimes contain sensitive information like API keys, and should not be pushed to git. So I'd love to see `/broadcast` be included in `.gitignore` by default. Right now it's:

```
!/broadcast
/broadcast/*/31337/
/broadcast/**/dry-run/
```

But I'd like to see:

```
!/broadcast
/broadcast/*/31337/
/broadcast/**/dry-run/
/broadcast
```

**Comment by mds1** [comment]
I think committing the broadcast files make sense to track deployments, and instead would suggest just removing the RPC URL field from the broadcast log, because I agree this is a footgun
