### ISSUE TITLE
unexpected exit code on `forge build --sizes` for scripts

### ISSUE THREAD

**Issue by sakulstra** [foundry-rs/foundry#4615]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (d1c84e3 2023-03-13T00:07:48.790822528Z)

### What command(s) is the bug in?

forge build --sizes

### Operating System

Linux

### Describe the bug

`forge build --sizes` will exit with exit code `1`  when one of the exceed succeeds the codesizelimit.

While this is a legitimate behavior for normal `contract`s, it's quite common to surpass codesizelimits in `Script/Tests`s as they will never be deployed, but instead perform multiple contract deployments.

Currently `forge build --sizes` doesn't consider this "special cases" but simply errors. I think the correct behavior would be to ignore codesizelimit on these two special cases.

- Discussed in https://github.com/foundry-rs/foundry/discussions/4285

**Comment by mds1** [comment]
Do you have a repo to reproduce on? Test and script contracts should be excluded from the size report, per

https://github.com/foundry-rs/foundry/blob/ffa038b73ad3035996bd71eebdff60473bb6fd33/common/src/compile.rs#L150-L160

**Comment by sakulstra** [comment]
@mds1 sadly it's all on private repos, so cannot share right now.

That said i looked into the code before and didn't see this so probably it's just some weird patterns we're having causing this. As we want to use the scripts within tests without broadcast we tend doing stuff like.


```solidity
contract CommonDeployer {
  function _deploy() internal {
    do a lot of stuff
  }
}

contract PolygonDeployer is Script,CommonDeployer {
  function run() public {
    vm.startBroadcast();
    _deploy();
    vm.stopBroadcast();
  }
}
```

So in this case the violating contract would be `CommonDeployer` which is not actually a script (but only used within scripts)... now that i know that in theory it works, i can work around it :sweat_smile: by inheriting script as well i guess.
Thx for the quick response, not sure if there's sth to fix then.

**Comment by mds1** [comment]
A workaround is to just add `bool public IS_SCRIPT = true;` to the `CommonDeployer` — this isn't used anywhere else afaik so it shouldn't cause any issues.

Another thing you could do is just merge `PolygonDeployer` and `CommonDeployer` into a single contract so it is a script, and then in your test you do `MyTest is Test, PolygonDeployer` and call `PolygonDeployer.run()` in setup, and the broadcasts basically just act like pranks
