### ISSUE TITLE
cast send --interactive asks for sender address

### ISSUE THREAD

**Issue by Thegaram** [foundry-rs/foundry#4616]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

cast 0.2.0 (394f217 2023-03-21T00:11:00.708322Z)

### What command(s) is the bug in?

cast send

### Operating System

macOS (Apple Silicon)

### Describe the bug

This command worked as expected up until yesterday:

```
cast send --rpc-url https://alpha-rpc.scroll.io/l2 0x5300000000000000000000000000000000000005 "withdraw()" --interactive --legacy
```

After upgrading `cast`, now I get this error:

```
Error: 
No wallet or sender address provided. Consider passing it via the --from flag or
setting the ETH_FROM env variable or setting in foundry.toml
```

It still doesn't work if I pass `--from` (`the method eth_sendTransaction does not exist/is not available`). It does work if I pass `--private-key`.

**Comment by zerosnacks** [comment]
Unable to reproduce, assuming this has been resolved

`cast send --rpc-url https://rpc.scroll.io/l2 0x5300000000000000000000000000000000000005 "withdraw()" --interactive --legacy`  now asks for the private key and not for a corresponding sender address

Feel free to re-open if you still experience an issue
