### ISSUE TITLE
OOM'd when fuzzing seaport with 100k runs

### ISSUE THREAD

**Issue by sambarnes** [foundry-rs/foundry#4618]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (394f217 2023-03-21T00:11:00.708322Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

Following up from our slack discussion @gakonst -- requested issue w/ repo 

---

When setting `fuzz_runs = 100_000` on the seaport repo, the growth of memory usage looks up-only and eventually OOM's our runner in k8s.

Specifically i've been using branch `sam/moat-runner` and running `FOUNDRY_PROFILE=moat forge test -vvv`

![image](https://user-images.githubusercontent.com/1211977/226708910-b4ad13a2-6f28-4cab-9dc8-24dc3d1fe7a9.png)

Can see one [example GH Action run here](https://github.com/ProjectOpenSea/seaport/actions/runs/4481829220/jobs/7879075989?pr=1035)

---

I'm looking to get a sense of what can be tuned (tried a few cache related config options, to no discernible impact) or if something in our code is fundamentally problematic in causing this memory growth over time.

Perhaps 32g simply isn't enough here and there's not much to tune in forge itself

**Comment by mattsse** [comment]
do you need `-vvv`?
this will record a lot of stuff.
does running without -vvv succeed?

**Comment by sambarnes** [comment]
mmm that is a great point 🤔 will try it out now

**Comment by sambarnes** [comment]
@mattsse it ultimately got killed again ([in this run](https://github.com/ProjectOpenSea/seaport/actions/runs/4482781518/jobs/7881257182?pr=1035)), however the growth curve was definitely stunted compared to the previous runs so it lasted longer. Definitely great information to know regardless, thanks 🙏 

<img width="920" alt="image" src="https://user-images.githubusercontent.com/1211977/226721510-678acc8c-c2c3-412f-97a4-cc3461f16cb0.png">

--- 

perhaps i'll try upping the limit and seeing if a usage plateau emerges? or if it can just generally succeed at a certain amount

the fact that it doesn't go down is what makes me hesitant to simply throw more resources at it

**Comment by mattsse** [comment]
I'll checkout the PR

https://github.com/ProjectOpenSea/seaport/pull/1035

**Comment by mattsse** [comment]
I was able to reduce this a bit, fuzzing still takes a bit too much ram imo. 
but additional improvements need more changes. with #4620 I was able to keep this at ~14GB, but haven't run it to completion, just because it takes forever 

not sure what's still eating all the memory, but I'm also not that familiar with the fuzz code.

@joshieDo it is weird that the memory footprint continuously grows, any ideas on what to check?

**Comment by gakonst** [comment]
> is there some shared state across all tests that gets filled by fuzz runs?

yeah the dictionary, so im assuming it's related to that

**Comment by PaulRBerg** [comment]
Can confirm that we've also been affected by this. Our CI fuzz tests (with 50k runs) have suddenly started taking a long time - from 1h 30m to over 6 hours.

The repo is private (for now); I just wanted to confirm that this is still an issue.

**Comment by mattsse** [comment]
the "fix" in #4627 introduced the regression @PaulRBerg mentioned which is due to poor eviction performance.

ref #4678

**Comment by grandizzy** [comment]
@sambarnes @PaulRBerg wonder if this is still reproducible and if you could share instructions on how to hit such if still an issue. thank you

**Comment by sambarnes** [comment]
@grandizzy tbh this was resolved (well enough) for us with the above patches :)


I left opensea a while back so haven't had to run a similar sized workload recently
