### ISSUE TITLE
forge fmt doesn't format contract instantiation arguments

### ISSUE THREAD

**Issue by Philogy** [foundry-rs/foundry#4619]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What command(s) is the bug in?

forge 0.2.0 (394f217 2023-03-21T00:03:24.86Z)

### Operating System

Linux

### Describe the bug

`forge fmt` does not seem to format contract instantiation statements such as:

```solidity
// SPDX-License-Identifier: MIT
pragma solidity 0.8.17;

contract B {
    constructor(uint256 a, uint256 b, uint256 c) {}
}

contract A {
    function f() public {
        new B (1, 3,


               4);
    }
}
```

Running `forge fmt` with the above in the repo will not correct the `new B` statement to the expected `new B(1, 3, 4);\n` but instead leaves it as is. Other statements in the same file are still formatted as expected.

**Comment by fubhy** [comment]
Same with e.g. `new address[]( ... )`

**Comment by beeb** [comment]
I can take this one if no-one started yet
