### ISSUE TITLE
Fuzzer calls functions other than given in targetSelector() after contract deployment

### ISSUE THREAD

**Issue by Teamo0** [foundry-rs/foundry#4623]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (da2392e 2023-03-22T00:04:12.437988019Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

Functions to fuzz are restricted via targetSelector. One of the fuzzed functions deploys a proxy contract for user. After the proxy is deployed, the fuzzer starts calling all functions on the newly deployed contract, although not specified in targetSelectors.

Code to specify functions to be called on handler:
![image](https://user-images.githubusercontent.com/77360332/226824852-c3c9860a-8cb3-4692-a971-6735d9802afa.png)

Error message when running forge test shows that fuzzer is calling function 'transferAsset' on UserProxy Contract, which was deployed during function call 'botProcessRequests'.

![image](https://user-images.githubusercontent.com/77360332/226825244-103c0227-c9ee-4a77-bfeb-45f07a097684.png)

**Comment by mds1** [comment]
This is the expected behavior—contracts deployed during your invariant test are automatically added to the list of potential targets. To exclude them, you can use [`excludeArtifact`](https://github.com/foundry-rs/forge-std/blob/46264e9788017fc74f9f58b7efa0bc6e1df6d410/src/StdInvariant.sol#L34-L36)
