### ISSUE TITLE
Support glob patterns in `--skip` option (e.g. to skip entire tests dir)

### ISSUE THREAD

**Issue by fubhy** [foundry-rs/foundry#4628]
### Component

Forge

### Describe the feature you would like

Currently, you can specify the `--skip` option when running `forge build` to ignore certain files specifically. There's also special handlings for `scripts` and `tests` which excludes `.t.sol` and `.s.sol` files respecitively. It would be great if we could also exclude glob patterns. 

My use-case specifically is to run `forge build` while ignoring the entire `tests` directory when generating code based on `forge build` artifacts. Specifically, I'm using the build artifacts to then run `cast interface` on them to produce interface representations for different solc versions so I can write my integration tests in Solidity >0.8.10). This creates a "chicken and egg" problem where I can't generate those interfaces if my test files currently don't compile but in order for them to compile I'd need to generate the interfaces first.

### Additional context

We've solved this for now with a little workaround:

```Makefile
...

$(ARTIFACTS_DIR): Makefile $(shell find $(CONTRACTS_DIR) -type f -name "*.sol")
> mkdir -p $(@D)
> # Remove this once the `forge build` command supports glob patterns in `--skip` option.
> export FOUNDRY_TEST=this-directory-does-not-exist
> forge build --extra-output-files abi
> touch $@ 

...
```

**Comment by mattsse** [comment]
just to summarize:

--skip should support globs?

> Unfortunately, running --skip test script often still includes other test/script files since they don't have the extension but import scripts/tests.

I don't fully understand what this means exactly.

should `--skip test script` behave as glob that match the file path and exclude those that match?

**Comment by mattsse** [comment]
okay this should actually be very simple:

just need to change how this filter behaves, because rn it operates on file name

sorry should have followed up on this issue earlier...

https://github.com/foundry-rs/foundry/blob/8ecdc2af69bb7e61c0cd6a3c994b58230295b406/common/src/compile.rs#L525-L537

**Comment by 0xalpharush** [comment]
What will happen if a skipped file is a dependency of a file in `src/`?  It may be too opinionated but I don't think `src/` should take a dependency on `tests` or `scripts`. Unless that's enforced, I'd almost rather get an error that the glob pattern cannot be honored due to the dependency as opposed to it getting pulled into the artifacts.

**Comment by 0xalpharush** [comment]
@mattsse If you could point me in the right direction, I could probably knock this out

**Comment by mattsse** [comment]
ah yikes, sorry I totally forgot about this again...

I think what we want here is a variant that supports globs?

https://github.com/foundry-rs/foundry/blob/8ecdc2af69bb7e61c0cd6a3c994b58230295b406/common/src/compile.rs#L485-L494

or rather interpret the `Custom` string variant as glob when checking if the file is a match:

https://github.com/foundry-rs/foundry/blob/8ecdc2af69bb7e61c0cd6a3c994b58230295b406/common/src/compile.rs#L525-L537

currently this just checks if the file name includes the value:

https://github.com/foundry-rs/foundry/blob/8ecdc2af69bb7e61c0cd6a3c994b58230295b406/common/src/compile.rs#L502

https://github.com/foundry-rs/foundry/blob/8ecdc2af69bb7e61c0cd6a3c994b58230295b406/common/src/compile.rs#L531C48-L532

we could check if this is a glob
