### ISSUE TITLE
Cheat Code for Assert Not Equal which logs the value on failure

### ISSUE THREAD

**Issue by another-dave** [foundry-rs/foundry#4634]
### Component

Forge

### Describe the feature you would like

At the moment to test for inequality I need to do:

```
assertFalse(a == b, "A should not equal B")
```

but if this false, the assertion doesn't contain any details about the failure. Compared with `assertEq` where we get a breakdown logged:

```
├─ emit log_named_string(key: Error, val: A should equal B)
    ├─ emit log(: Error: a == b not satisfied [uint])
    ├─ emit log_named_uint(key:   Expected, val: 2)
    ├─ emit log_named_uint(key:     Actual, val: 3)
```

It would be great to have an assertion e.g. `assertNe` that would log out similarly:

```
├─ emit log_named_string(key: Error, val: A should not equal B)
    ├─ emit log(: Error: a != b not satisfied [uint])
    ├─ emit log_named_uint(key:   Actual, val: 2)
 ```
 
 Sometimes if you know the expected value in advance you can do:
 
 ```
 assertFalse(x == 2, "X should not be 2");
 ```
 
But logging the value would be useful when the test set-up creates the values dynamically, e.g. asserting that items in a sequence are incrementing correctly, e.g. that two calls to `nextValue()` don't produce duplicates.

**Comment by mds1** [comment]
There are a few options here:
- Use a more descriptive error string: `assertFalse(a == b, string.concat(vm.toString(A), vm.toString(B));`
- Use the greater than/less than assertions to be more specific about what you're expecting
- DSTest now has [`assertNotEq`](https://github.com/dapphub/ds-test/blob/e282159d5170298eb2455a6c05280ab5a73a4ef0/src/test.sol#L200-L291), but are they are not yet in forge-std. Feel free to open a PR to forge-std that bums the ds-test version to add these assertions

**Comment by another-dave** [comment]
Hi @mds1, thanks for coming back so quickly. Yeah so far I've been using a version on 1) but like the fact with `assertEq` that I can use the message for context and have separate emits for the values themselves.

Didn't realise the split with DSTest, nor that `assertNotEq` is already in there. I will close this (as redundant) and will raise a PR for the latest ds-test version.

Thanks for your help!
