### ISSUE TITLE
`fail_on_revert` stateful fuzzing (invariant) tests should have an override

### ISSUE THREAD

**Issue by PatrickAlphaC** [foundry-rs/foundry#4636]
### Component

Forge

### Describe the feature you would like

When I'm writing invariant tests, in our `foundry.toml` you have the option to have `fail_on_revert` be true or false. 

I'd love to see like a decorator or something like such:

```
vm.fail_on_revert(false);
function invariant_testSomething() public {
// code
}
```

Or something.

**Comment by mds1** [comment]
I think this is a subset of https://github.com/foundry-rs/foundry/issues/3062, which tries to figure out a UX for changing all fuzz/invariant configs on e.g. a per-test basis. Would love to get your thoughts on that proposal! Just added a comment to the end (https://github.com/foundry-rs/foundry/issues/3062#issuecomment-1483130224) with some more recent thoughts on how to structure the UX

**Comment by grandizzy** [comment]
that's possible with inline `/// forge-config: default.invariant.fail-on-revert = true` @mds1 I think this one can be closed?

**Comment by mds1** [comment]
Agreed with that, thanks!
