### ISSUE TITLE
Run specific Tests

### ISSUE THREAD

**Issue by joedakwa** [foundry-rs/foundry#4637]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (cee162f 2023-03-17T00:07:48.109591974Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

Hi I am trying to run specific tests in my repo using Foundry.

How do i bypass running all tests with the ```forge test``` command?

I just want to run, say one test at a time?

Thanks

**Comment by DaniPopes** [comment]
Please keep issues for bug reports or feature requests. If you want to ask a question, please check the FAQ / book first, the answer is here: <https://book.getfoundry.sh/faq#how-do-i-run-specific-tests>
