### ISSUE TITLE
Arbitrum airdrop claim script didn't work

### ISSUE THREAD

**Issue by tonisives** [foundry-rs/foundry#4640]
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge 0.2.0

### Operating System

macOS (Intel)

### Describe the bug

I wrote a script to claim Arbitrum airdrop from their [TokenDistributor](https://arbiscan.io/address/0x67a24ce4321ab3af51c2d0a4801c3e111d88c9d9#code)

However, on the claiming hour, the `claim()` function call failed for my script with
`TokenDistributor: claim ended`

If you look at the TokenDistributor source code, then this error makes sense:
```solidity
require(block.number < claimPeriodEnd, "TokenDistributor: claim ended");
```
Their `claimPeriodEnd` is 18208000 uint256, but the latest block is [73375296](https://arbiscan.io/blocks). So this revert makes sense.

However, if I used the same contract to claim with js or with metamask, then claiming worked. You can clearly see from the contract that [claiming tx-s](https://arbiscan.io/tx/0x9e524f7491939f1f80475c168e1717564b282308569c4475a022e45cce1e6a66) work.

Why does metamask and ethers.js succeed, but forge script does not?

Here is my script:
```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import "forge-std/Script.sol";
import { console2 } from "forge-std/console2.sol";

contract Run is Script {
    function setUp() public {}

    function run() external {
        vm.startBroadcast();
      
        ArbAirDrop airDrop = ArbAirDrop(0x67a24CE4321aB3aF51c2D0a4801c3E111D88C9d9);

        // correct 625000000000000000000
        airDrop.claimableTokens(0xe5B1B7295B3A82d5eD9d16Cf3c79Ad0316Efa279);
        console2.log(block.number);
        console2.log(uint(airDrop.claimPeriodEnd()));
        
        // airDrop.claimPeriodEnd() = around 18000000
        // but block.timestamp is 73094372.

        // doesnt work with neither interface call, or address.call
        // airDrop.claim();
        0x67a24CE4321aB3aF51c2D0a4801c3E111D88C9d9.call(abi.encodeWithSignature("claim()"));

        vm.stopBroadcast();
    }
}

interface ArbAirDrop {
    function claim() external;
    function claimableTokens(address owner) external view returns (uint);
    function claimPeriodEnd() external returns (uint);
}
```

I called it with my alchemy rpc (tried it also with arbitrum's public rpc)
```
forge script script/claimArb/ClaimArb.s.sol:Run \
  --rpc-url https://arb-mainnet.g.alchemy.com/v2/my-access-token \
  --ledger \
  --sender 0xme \
  --broadcast \
  -vvvv
```

**Comment by mattsse** [comment]
thanks for this, will check
ref https://github.com/foundry-rs/foundry/issues/4566

**Comment by mattsse** [comment]
> Their claimPeriodEnd is 18_208_000 uint256, but the latest block is [73_375_296](https://arbiscan.io/blocks). So this revert makes sense.

ah... I know what's up here, `block.number` is the L1 one block,

so this failed during the simulation step and didn't actually send the tx? because on the real arbitrum chain block.number would be the L1 block.
