### ISSUE TITLE
vm.createSelectFork causes panic when informing a block number

### ISSUE THREAD

**Issue by 0xRusowsky** [foundry-rs/foundry#4649]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ac07071 2023-03-26T00:04:24.930648335Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

The bug occurs when trying to fork mainnet at a specific block. Nevertheless, it works correctly when the block number is not informed. I've run such tests in the past without any problems, so not sure why it crashes now.

Test setup:

```
function setUp() public {
        uint256 forkBlock = 16_900_000;
        vm.createSelectFork(vm.rpcUrl("mainnet"), forkBlock);
        //vm.createSelectFork(vm.rpcUrl("mainnet"));
}
```

backtrace:
```
The application panicked (crashed).
Message:  Integer overflow when casting to u32
Location: /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/primitive-types-0.12.1/src/lib.rs:38

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: start_thread<unknown>
      at <unknown source file>:<unknown line>
   2: clone<unknown>
      at <unknown source file>:<unknown line>
```

PS: I'm using WSL in case that helps identify the root cause.

**Comment by mattsse** [comment]
> it works correctly when the block number is not informed

what does this mean exactly?

**Comment by mattsse** [comment]
wasn't able to reproduce this 

```solidity
    function setUp() public {
        uint256 forkBlock = 16_900_000;
        vm.createSelectFork(vm.rpcUrl("mainnet"), forkBlock);
        console.log(block.number);
    }
    function testIncrement() public {
    }
```

```
forge t -vvv
[PASS] testIncrement() (gas: 142)
Logs:
  16900000
```

**Comment by 0xRusowsky** [comment]
> > it works correctly when the block number is not informed
> 
> what does this mean exactly?

for me it only works properly when I don't inform the `forkBlock`:
```
function setUp() public {
        vm.createSelectFork(vm.rpcUrl("mainnet"));
}
```

**Comment by 0xRusowsky** [comment]
> wasn't able to reproduce this
> 
> ```solidity
>     function setUp() public {
>         uint256 forkBlock = 16_900_000;
>         vm.createSelectFork(vm.rpcUrl("mainnet"), forkBlock);
>         console.log(block.number);
>     }
>     function testIncrement() public {
>     }
> ```
> 
> ```
> forge t -vvv
> [PASS] testIncrement() (gas: 142)
> Logs:
>   16900000
> ```

After this comment, I tried running a dummy test (like you did) and I just realized that the issue is not properly reported.

It crashes doesn't crash when I fork from the latest block because the test reverts early. Instead, when I fork from a specific block, something happens that makes it crash.

Since I wasn't able to print the traces I assumed it was crashing when forking... my bad. Closing the issue and will investigate further on my end.

**Comment by mattsse** [comment]
the only location where we use this unsafe cast is during console.log with formatting
