### ISSUE TITLE
Forge Test compiles multiple contracts with severe errors

### ISSUE THREAD

**Issue by PtahSeven** [foundry-rs/foundry#4653]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6c1eee9 2023-03-27T00:04:12.999873464Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

The system I use: mac,linux, windows
![image](https://user-images.githubusercontent.com/126786904/227882639-c14c3338-b0ab-4ac9-ac92-e37345d9828b.png)
![image](https://user-images.githubusercontent.com/126786904/227882870-1b9a8eb7-1d16-41b7-b233-8f666fcaa6bd.png)

![image](https://user-images.githubusercontent.com/126786904/227882524-3c17ff8b-9a33-4e38-8de4-77738387f4bd.png)

The TickMath.sol library file of uniswapV3 is used.
It uses a feature that exists in the lower version, and the higher version does not have  that feature.
All this created a problem, forge can not use more than one compiler at the same time, to compile the contract. Hardhat can use multiple editors to compile contracts at the same time. Please fix it so that it supports compiling multiple contracts by default!

**Comment by zerosnacks** [comment]
Specifically when working with Uniswap V2 / V3 make sure to check out the `0.8` branch: https://github.com/Uniswap/v3-core/tree/0.8

See: https://github.com/Uniswap/v3-core/blob/6562c52e8f75f0c10f9deaf44861847585fc8129/contracts/libraries/TickMath.sol#L29
