### ISSUE TITLE
RPC calls to non-localhosts are slow

### ISSUE THREAD

**Issue by moubctez** [foundry-rs/foundry#4658]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6c1eee9 2023-03-27T11:13:24.314347Z)

### What command(s) is the bug in?

forge create

### Operating System

macOS (Intel)

### Describe the bug

I have `anvil` running on 0.0.0.0.

I benchmark `forge create`

```
time forge create --offline --rpc-url=http://127.0.0.1:8545 --private-key=…
1.958u 0.247s 0:00.79 277.2% 1+0k 0+0io 0pf+0w

time forge create --offline --rpc-url=http://192.168.0.123:8545 --private-key=…
1.931u 0.246s 0:06.69 32.4% 1+0k 0+0io 0pf+0w
```

**Why** the second invocation takes about 7 seconds to execute, providing 192.168.0.123 points to the same `anvil` service?

Same story with `--rpc-url=http://anvil:8545` and `127.0.0.1	anvil` in /etc/hosts.

**Comment by mattsse** [comment]
ideally, we fix this in the `is_local_endpoint` function:

https://github.com/gakonst/ethers-rs/blob/9a5b31a0a2302480080ffe34c9e1f4c957d0fd3d/ethers-providers/src/rpc/provider.rs#L1449

**Comment by lucaprov1989** [comment]
Ok cool! Shall I open an issue on `ethers-rs` and link it back to here?

**Comment by Evalir** [comment]
Closing—the upstream fix is now in foundry and rpc calls should not be slow anymore (quickly tested and seemed fast enough).
