### ISSUE TITLE
forge test hangs on invariant testing

### ISSUE THREAD

**Issue by cdgmachado0** [foundry-rs/foundry#4662]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (97f070f 2023-03-17T09:30:30.350509Z)

### Operating System

None

### Describe the bug

Follow-up to #4656 since it's unresolved.

**Comment by mds1** [comment]
Reopened https://github.com/foundry-rs/foundry/issues/4656 since that has all the details, and closing this one 🙂
