### ISSUE TITLE
Block with id: 'latest' not found.

### ISSUE THREAD

**Issue by miohtama** [foundry-rs/foundry#4666]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (7398b65 2023-03-29T00:17:00.135482Z)

### What command(s) is the bug in?

Not yet repeatable test case

### Operating System

macOS (Apple Silicon)

### Describe the bug

I am running Python based test suite against Anvil BNB Chain fork, using automining mode.

Randomly tests fail at `eth_getBlock("latest")`

The JSON-RPC error message is

```
Block with id: 'latest' not found
```

- I do not think this happens on any real node or Python Ethereum Tester

- There is no clear pattern here when/why this happens so I suspect some sort of internal race condition inside Anvil. 

No repeatable test case yet.

**Comment by mattsse** [comment]
can please share more context when this happens?

what's the actual call?

**Comment by miohtama** [comment]
Ok I will attempt to figure this out.

It happens randomly in a long (non-Foundry) test run. The issue makes tests flaky, so I have been dealing with this by just marking the tests flaky. Seems like there is no pattern; it can happen at any time.

**Comment by Evalir** [comment]
Closing—stale and cannot reproduce.
