### ISSUE TITLE
Ledger --hd-paths returns "Ledger device not available"

### ISSUE THREAD

**Issue by bschreck** [foundry-rs/foundry#4692]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (f7a535d 2023-04-03T00:04:49.769079000Z)

### What command(s) is the bug in?

forge script <script.s.sol> --chain-id 137 --rpc-url $POLYGON_RPC_URL --ledger --broadcast --hd-paths "m44'60'/0'/1/0" --sender <address>

### Operating System

macOS (Apple Silicon)

### Describe the bug

I've tried many versions of the above command with different hd-path variants, removing the m and the last /0. I'm trying to deploy using the second address on my ledger, but even using the hd-path of the first address does not work. The command works fine if I leave out --hd-paths and deploy using the first address of my ledger as the --sender.

I get
```
Error: 
Ledger device not available.

Context:
- Received unexpected response from device. Expected data in response, found none.
```

**Comment by gpsanant** [comment]
+1 on this. Anything with the `--hd-paths` flag breaks for me. Using `--sender` with the first address derived from my ledger's mnemonic works perfect. Pretty inconvenient though, as I wanted to use a different address...

**Comment by brayansdt** [comment]
I was also having the same problem when using the `--hd-paths` option, however, it works if I use the `--mnemonic-indexes` option.

eg: 

```zsh
➜  ✗ forge script --rpc-url $SEPOLIA_URL  script/....s.sol --ledger --mnemonic-indexes 1 --sender 0x... --verify --broadcast
```

**Comment by zerosnacks** [comment]
@bschreck / @gpsanant / @brayansdt would be great to know if you are still facing issues around this

Foundry has recently moved to Alloy's Ledger implementation so it is likely your issue may have been resolved

**Comment by grandizzy** [comment]
I confirm this works with latest version but the derivation path in original comment is wrong (that is `m44'60'/0'/1/0` instead `m/44'60'/0'/1/0`) 

```bash
forge script script/Counter.s.sol --rpc-url RPC_URL --ledger --broadcast --hd-paths "m/44'/60'/1'/1/0" --sender SENDER
[⠒] Compiling...
No files changed, compilation skipped
Script ran successfully.

## Setting up 1 EVM.

==========================

Chain 137

Estimated gas price: 30.000000052 gwei

Estimated total gas used for script: 138729

Estimated amount required: 0.004161870007213908 ETH

==========================

Transactions saved to: /broadcast/Counter.s.sol/137/run-latest.json

Sensitive values saved to: /cache/Counter.s.sol/137/run-latest.json
```

going to close the issue, @bschreck @gpsanant @brayansdt please reopen if you still hit problems. thank you!
