### ISSUE TITLE
The help comments for `--gas-limit` and `--block-gas-limit` are the same.

### ISSUE THREAD

**Issue by minaminao** [foundry-rs/foundry#4693]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (0e7ff88 2023-04-04T00:11:28.439758000Z)

### What command(s) is the bug in?

forge test --help, forge script --help

### Operating System

macOS (Intel)

### Describe the bug

The help messages for `--gas-limit` and `--block-gas-limit` are confusing because they are the same.

```
$ forge test --help | grep gas-limit -A 1
      --gas-limit <GAS_LIMIT>
          The block gas limit
--
      --block-gas-limit <GAS_LIMIT>
          The block gas limit
```

The following code shows that the `--block-gas-limit` option is prioritized.

```rust
    pub fn gas_limit(&self) -> U256 {
        self.env.block_gas_limit.unwrap_or(self.env.gas_limit).into()
    }
```

When I actually specified both and got the value of `--block-gas-limit` for `block.gaslimit`. If only one was specified, that value was given.

If they are equivalent, it would be easier to understand if one or the other is deleted. If not, it would be better to change the help message.

**Comment by mattsse** [comment]
I'm not sure the `gas-limit` isn't actually intended for the transaction.

but this is redundant atm, but not sure what the ideal solution here is.

what do you think?

**Comment by minaminao** [comment]
@mattsse Thanks for your comment! Do you mean that `--gas-limit` may have been created as the gas limit for a transaction, but the option is redundant now because only one transaction is executed per block in the current test and script?

Cutting it short, I think it would be better to keep `gas_limit` and remove the `--gas-limit` option.

It's difficult for users to guess from the current help message if the `--gas-limit` was designed as a future role for the transaction gas limit, but now behaves as a block gas limit. In `cast`, `--gas-limit` is the transaction gas limit, and it's not trivial that specifying `--gas-limit` changes the `block.gaslimit`. I think the behavior of the `--gas-limit` option in `forge` and `cast` should be consistent.

Also, I don't currently need the transaction gas limit option in my tests and scripts. I think the block gas limit option is sufficient. I can think of cases where it's necessary to specify a block gas limit, but I can't think of any cases where it's necessary to specify a transaction gas limit using the option. This is because the function call option `{gas: <foo>}` can be used to specify the transaction gas limit. (related: #2627)

However, I think the implementation with `gas_limit` and `block_gas_limit` should be left as is if there is even a slight possibility that the the roles of two vars will have differences in the future. The performance will not change if `gas_limit` and `block_gas_limit` are present. I think it would be a waste to reimplement them in the future.
