### ISSUE TITLE
vm.etch in setUp() breaks invariant tests

### ISSUE THREAD

**Issue by MikeHathaway** [foundry-rs/foundry#4707]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (c49e5e1 2023-04-07T20:29:51.393814535Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

Invariant tests fail with: `ERROR forge::multi_runner: error=Failed to replay counter examples` fired here: https://github.com/foundry-rs/foundry/blob/master/forge/src/runner.rs#L529

I'm attempting to etch a newly deployed token onto an address that is hardcoded in the smart contracts I'm testing. In order to provide an ERC20 token at that address, I used the `vm.etch` approach recommended in the `getCode` section of the Foundry Book. The etching appears to be working, and the setup completes normally but the invariant tests fail to run.

**Comment by grandizzy** [comment]
I just retested similar scenario and was not able to reproduce it, going to close this one, please reopen if still an issue
