### ISSUE TITLE
global config not load in forge

### ISSUE THREAD

**Issue by wiasliaw** [foundry-rs/foundry#4711]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (0158159 2023-04-07T07:58:23.058250000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

Here's the global config in`$HOME/foundry.toml`

```toml
[rpc_endpoints]
mainnet  = "https://eth-mainnet.g.alchemy.com/v2"
```

And run `forge test` in a repo.

```solidity
contract TestFork is Test {
    function test_forking() external {
        string[2][] memory allUrls = vm.rpcUrls();
        for (uint256 i = 0; i < allUrls.length; ++i) {
            console.logString(allUrls[i][0]);
            console.logString(allUrls[i][1]);
        }
    }
}
```

Here's the log.
```txt
[FAIL. Reason: Failed to resolve env var `ALCHEMY_API_KEY` in `https://eth-kovan.alchemyapi.io/v2/${ALCHEMY_API_KEY}`: environment variable not found] test_forking() (gas: 2927)
```

If forge find `foundry.toml` in repo, it will ignore the global config. Here's the comment I found. BTW, it seems that global config should be placed at `~/.foundry/foundry.toml`, not `$HOME/foundry.toml` in documentation.

https://github.com/foundry-rs/foundry/blob/c49e5e1b1df95214059a9c92a211a8ae81bc21dd/config/src/lib.rs#L1293-L1298

**Comment by wiasliaw** [comment]
Sorry for bothering, I found that I placed the wrong `toml` file in my repo which had setup `[rpc_endpoints]`.

The only question here is where to place the global config.

**Comment by mattsse** [comment]
yeh you're right it expects it in `~/.foundry/foundry.toml` is this wrongly documented in the book?

**Comment by wiasliaw** [comment]
@mattsse 
FYI https://book.getfoundry.sh/reference/config/overview#global-configuration

**Comment by mattsse** [comment]
also just tested this and rpc-endpoints are picked up as expected.

I'll close this one, if the global path is document wrong please file an issue in book repo

**Comment by mattsse** [comment]
> @mattsse FYI https://book.getfoundry.sh/reference/config/overview#global-configuration

ah yes this is indeed misleading, do you want to submit a fix? or open an issue?

**Comment by wiasliaw** [comment]
I'll fix it.
