### ISSUE TITLE
Add an ability to set ethers version for generated with `forge bind` bindings

### ISSUE THREAD

**Issue by Velnbur** [foundry-rs/foundry#4714]
### Component

Forge

### Describe the feature you would like

Add an option to `forge bind` to set ethers version and features in generate `Cargo.toml` crate

#### Situation

Currently, I have a project with several divided repos:

+ `contracts` - the repository for Solidity contracts made from [foundry template](https://github.com/foundry-rs/forge-template);
+ `contracts-bindings-rs` - the repository-crate with generated with `forge bind` bindings;
+ `contracts-sdk-rs` - the repository that uses _bindings_ and adds logic related to the that contracts.

And I'm trying to implement a GitHub action that on each new tag at `contracts` will:

1. Clone old bindings;
1. Generate new bindings using `forge bind` and rewrite old ones if needed;
1. Push new bindings to the `contracts-bindings-rs` repo;
1. Create a new tag for the `contracts-bindings-rs` repo;

The problem is, that I'm not able to set a stable version of `ethers` because it constantly rewrites it to `default` branch when all the project uses the other one.

#### Consideration

It could be some sort of `Cargo.toml` template that `forge bind` will fill if needed. Or just a flag that will set it's version

**Comment by mattsse** [comment]
once we updated to new ethers release this will default to latest crates.io ethers release:

https://github.com/gakonst/ethers-rs/pull/2317
