### ISSUE TITLE
forge debug looking for run() if raw calldata given

### ISSUE THREAD

**Issue by Fabien-Morrow** [foundry-rs/foundry#4721]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (b44b045 2023-02-21T00:11:41.592203605Z)

### What command(s) is the bug in?

forge debug

### Operating System

Linux

### Describe the bug

- create a Mwe.sol file containing
```
// SPDX-License-Identifier: MIT
pragma solidity 0.8.18;

contract Mwe {
    uint256 value;

    function set(uint256 x_) external {
        value = x_;
    }
}
```
- `forge debug src/Mwe.sol --sig 60fe47b10000000000000000000000000000000000000000000000000000000000000007`

current behaviour : `error[9582]: TypeError: Member "run" not found or not visible after argument-dependent lookup in contract Mwe.`

expected behaviour : executes set(7)

Thx for your GREAT work guys !

**Comment by Fabien-Morrow** [comment]
of course if you add `function run() external {}` it works. But it will be appreciable to run debug without having this useless code in the contract.

**Comment by zerosnacks** [comment]
Unable to reproduce with given setup, appears to have been fixed

Command ran:

```
forge debug Mwe --sig 60fe47b10000000000000000000000000000000000000000000000000000000000000007
```
