### ISSUE TITLE
Pretty print `--json` results

### ISSUE THREAD

**Issue by jim4067** [foundry-rs/foundry#4725]
### Component

Forge

### Describe the feature you would like

1. I would love for it to be possible to pretty spring json results of the tests.
2. Maybe someone would love to be able to save the result to a file?

**Comment by amusingaxl** [comment]
Can you just use `jq` for that?

```bash
forge test --json | jq -Rr 'fromjson?'
```

If you want to save it to a file, then just use `stdout` redirection:

```bash
forge test --json | jq -Rr 'fromjson?' > /path/to/file.json
```

**Comment by jim4067** [comment]
you can. I just thought it would be cool to have it in the forge.
