### ISSUE TITLE
ParseOverflow on forge test """called `Result::unwrap()` on an `Err` value: ParseOverflow"""

### ISSUE THREAD

**Issue by DrakeEvans** [foundry-rs/foundry#4727]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (27c9779 2023-04-12T01:40:37.519154000Z)

### What command(s) is the bug in?

forge test -w --mc TestFrxEthEthCurveLpDualOracle --mt testGetPrices

### Operating System

macOS (Apple Silicon)

### Describe the bug

called `Result::unwrap()` on an `Err` value: ParseOverflow

Full backtrace
export RUST_BACKTRACE=full && export RUST_BACKTRACE=1 && forge test -w --mc TestFrxEthEthCurveLpDualOracle --mt testGetPrices
[⠒] Compiling...
No files changed, compilation skipped
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: ParseOverflow
Location: evm/src/decode.rs:50

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 10 frames hidden ⋮
  11: foundry_evm::decode::decode_console_log::h902bf3055543101e
      at <unknown source file>:<unknown line>
  12: foundry_evm::decode::decode_console_logs::h077965f7919daeb7
      at <unknown source file>:<unknown line>
  13: forge::runner::ContractRunner::run_test::h3d115315e9513ed0
      at <unknown source file>:<unknown line>
  14: rayon::iter::plumbing::Folder::consume_iter::h3370292f0e16aebf
      at <unknown source file>:<unknown line>
  15: rayon::iter::plumbing::bridge_producer_consumer::helper::h2ff75269cf1210f8
      at <unknown source file>:<unknown line>
  16: <rayon::iter::flat_map::FlatMap<I,F> as rayon::iter::ParallelIterator>::drive_unindexed::h1bf7cde34de0df8d
      at <unknown source file>:<unknown line>
  17: rayon::result::<impl rayon::iter::FromParallelIterator<core::result::Result<T,E>> for core::result::Result<C,E>>::from_par_iter::h80b79c2ef8e533b8
      at <unknown source file>:<unknown line>
  18: forge::runner::ContractRunner::run_tests::h1b01eac2c1b7c354
      at <unknown source file>:<unknown line>
  19: forge::multi_runner::MultiContractRunner::run_tests::h14ad735658507b5e
      at <unknown source file>:<unknown line>
  20: <rayon::iter::map::MapFolder<C,F> as rayon::iter::plumbing::Folder<T>>::consume::h1b612507b3512e82
      at <unknown source file>:<unknown line>
  21: rayon::iter::plumbing::Folder::consume_iter::h1a178856afe7c0e8
      at <unknown source file>:<unknown line>
  22: rayon::iter::plumbing::bridge_producer_consumer::helper::hcc0e344ae506eee4
      at <unknown source file>:<unknown line>
  23: rayon_core::job::StackJob<L,F,R>::run_inline::h9748c011ec04f46e
      at <unknown source file>:<unknown line>
  24: rayon_core::join::join_context::{{closure}}::hc347e4449aa2ea7c
      at <unknown source file>:<unknown line>
  25: rayon_core::join::join_context::h2fc889e7b6d64e05
      at <unknown source file>:<unknown line>
  26: rayon::iter::plumbing::bridge_producer_consumer::helper::hcc0e344ae506eee4
      at <unknown source file>:<unknown line>
  27: rayon_core::job::StackJob<L,F,R>::run_inline::h9748c011ec04f46e
      at <unknown source file>:<unknown line>
  28: rayon_core::join::join_context::{{closure}}::hc347e4449aa2ea7c
      at <unknown source file>:<unknown line>
  29: rayon_core::join::join_context::h2fc889e7b6d64e05
      at <unknown source file>:<unknown line>
  30: rayon::iter::plumbing::bridge_producer_consumer::helper::hcc0e344ae506eee4
      at <unknown source file>:<unknown line>
  31: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hc7acb853afde9581
      at <unknown source file>:<unknown line>
  32: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h75127be20db1c5c3
      at <unknown source file>:<unknown line>
  33: rayon_core::registry::WorkerThread::wait_until_cold::habf6705c74b5d6f2
      at <unknown source file>:<unknown line>
  34: rayon_core::join::join_context::{{closure}}::hc347e4449aa2ea7c
      at <unknown source file>:<unknown line>
  35: rayon_core::join::join_context::h2fc889e7b6d64e05
      at <unknown source file>:<unknown line>
  36: rayon::iter::plumbing::bridge_producer_consumer::helper::hcc0e344ae506eee4
      at <unknown source file>:<unknown line>
  37: rayon_core::job::StackJob<L,F,R>::run_inline::h9748c011ec04f46e
      at <unknown source file>:<unknown line>
  38: rayon_core::join::join_context::{{closure}}::hc347e4449aa2ea7c
      at <unknown source file>:<unknown line>
  39: rayon_core::join::join_context::h2fc889e7b6d64e05
      at <unknown source file>:<unknown line>
  40: rayon::iter::plumbing::bridge_producer_consumer::helper::hcc0e344ae506eee4
      at <unknown source file>:<unknown line>
  41: rayon_core::join::join_context::{{closure}}::hc347e4449aa2ea7c
      at <unknown source file>:<unknown line>
  42: rayon_core::join::join_context::h2fc889e7b6d64e05
      at <unknown source file>:<unknown line>
  43: rayon::iter::plumbing::bridge_producer_consumer::helper::hcc0e344ae506eee4
      at <unknown source file>:<unknown line>
  44: rayon_core::join::join_context::{{closure}}::hc347e4449aa2ea7c
      at <unknown source file>:<unknown line>
  45: std::panicking::try::h7b429c52ad331afc
      at <unknown source file>:<unknown line>
  46: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::hf322f37bdb1231e9
      at <unknown source file>:<unknown line>
  47: rayon_core::registry::WorkerThread::wait_until_cold::habf6705c74b5d6f2
      at <unknown source file>:<unknown line>
  48: rayon_core::registry::ThreadBuilder::run::h80b75fa5e2d242f6
      at <unknown source file>:<unknown line>
  49: std::sys_common::backtrace::__rust_begin_short_backtrace::hc64d7937b3735455
      at <unknown source file>:<unknown line>
  50: core::ops::function::FnOnce::call_once{{vtable.shim}}::h8471436cbf851dc8
      at <unknown source file>:<unknown line>
  51: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h834161c0bc079953
      at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/boxed.rs:1988
  52: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h551d17f69af224a8
      at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/boxed.rs:1988
  53: std::sys::unix::thread::Thread::new::thread_start::h7c145656763309f3
      at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys/unix/thread.rs:108
  54: __pthread_deallocate<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.

**Comment by mattsse** [comment]
any repro for this?

**Comment by DrakeEvans** [comment]
Working on it

**Comment by DrakeEvans** [comment]
Reproduction repo: https://github.com/DrakeEvans/foundry-bug/tree/master
Add `MAINNET_URL=` to a .env file then run
`export RUST_BACKTRACE=full && export RUST_BACKTRACE=1 && forge test -w --mc TestFrxEthEthCurveLpDualOracle --mt testGetPrices`

**Comment by DrakeEvans** [comment]
@mattsse Im going to make the above repo private again, I found the (embarrassing) issue:
Its an overflow of the decimals field of assertApproxEqRelDecimal from forge-std.  
BAD:         assertApproxEqRelDecimal( _priceLow, _priceHigh, 1, 1e2);
GOOD:         assertApproxEqRelDecimal( _priceLow, _priceHigh, 1, 18);

**Comment by Evalir** [comment]
Closing, user issue in the end.
