### ISSUE TITLE
Anvil fork history height failed

### ISSUE THREAD

**Issue by Pythonberg1997** [foundry-rs/foundry#4737]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (5a257ef 2023-04-13T00:15:44.043211000Z)

### What command(s) is the bug in?

anvil fork

### Operating System

macOS (Apple Silicon)

### Describe the bug

I want to trace a txn on a specific height. Because `cast run` will run the txn on the latest block, I try to fork the chain to local on a history height.

I run `anvil -f ${RPC_URL} --fork-block-number ${HEIGHT}` and it returned:
```
thread 'main' panicked at 'Failed to fetch network chain id: HTTPError(reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("https")), port: None, path: "//URL", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError("dns error", Custom { kind: Uncategorized, error: "failed to lookup address information: nodename nor servname provided, or not known" })) })', /Users/runner/work/foundry/foundry/anvil/src/config.rs:798:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    3557 abort      anvil -f URL --fork-block-number 48738
```

However, I can fork that rpc with forge test script(`vm.createSelectFork("RPC", 48738)`). So I think it's not the rpc's problem.

**Comment by mattsse** [comment]
> "dns error"

likely just a flake

**Comment by Evalir** [comment]
Closing as stale, and this is working as normal since the latest foundryup.
