### ISSUE TITLE
Inconsistent discrepancies between `gasleft()` and gas cost annotation in traces

### ISSUE THREAD

**Issue by jkrivine** [foundry-rs/foundry#4740]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (c92dabc 2023-04-14T00:06:11.253773000Z)

### Operating System

None

### Describe the bug

I am trying to reconcile gas cost obtained by wrapping function calls between `gasleft()` instructions and the gas cost given by forge using `-vvvv` option.

Here is the contract I am using:
```solidity
import "forge-std/Test.sol";

contract C {
  uint public x = 10;
  function setX(uint n) external {
    x = n;
  }
}

contract GasTest is Test {
  C c = new C();

  function test_gasWrite0() public {
    uint g = gasleft();
    c.setX(0);
    g -= gasleft();
    console.log(g);
  }

  function test_gasWrite12() public {
    uint g = gasleft();
    c.setX(12);
    g -= gasleft();
    console.log(g);
  }

  function test_gasWrite10() public {
    uint g = gasleft();
    c.setX(10);
    g -= gasleft();
    console.log(g);
  }
}
```
Logs gives 
```
[PASS] test_gasWrite0() (gas: 8483)
Logs:
  10203
[PASS] test_gasWrite10() (gas: 10505)
Logs:
  7403
[PASS] test_gasWrite12() (gas: 13228)
Logs:
  10192
```
whereas trace shows:
```
[PASS] test_gasWrite0() (gas: 8483)
...
    ├─ [4170] C::setX(0) 

[PASS] test_gasWrite10() (gas: 10505)
...
    ├─ [2412] C::setX(10) 

[PASS] test_gasWrite12() (gas: 13228)
...
    ├─ [5212] C::setX(12) 
``` 
Am I misinterpreting the trace (doc says "gas usage (marked in square brackets) is for the entirety of the function call")? Also the gas cost of `gasWrite0` is less than the log but I assume this is because of gas refund from the evm?

**Comment by mds1** [comment]
Seems you're interpreting it correctly. The full gas cost of the test in brackets includes function dispatch cost and gas refunds. The 21000 intrinsic gas cost and calldata costs are not included in that number. And yep when you write a value of zero to storage you get a storage refund which is why that one is cheaper. Going to close this, but feel free to keep asking any further questions you have!

**Comment by jkrivine** [comment]
Sorry I was not being clear, I am aware of the gas refund. My problem is not the gas refund. It is the difference between the logs and the square brackets values. 
For instance  for `test_gasWrite10` the `gasleft()` around the function call yield a gas cost of 7403 and the square brackets in the trace show 2412.

**Comment by mds1** [comment]
Ahh I see, sorry I misunderstood. I'm pretty sure the number in brackets of 2412 is strictly the cost of the execution within the new call's context, whereas the number you get in your logs of 7403 includes all the extra "hidden" code in your test contract's context, i.e. the code solidity generates to execute and verify the call. This includes things like ABI encoding the calldata, copying the return data to memory, verifying the size of the return data, etc.

**Comment by jkrivine** [comment]
Right so this means that using `gasleft()` parenthesis around a piece of code in a test contract is not a good measurement. Maybe this would be worth mentioning somewhere [here](https://book.getfoundry.sh/forge/traces?highlight=trace#understanding-traces).
