### ISSUE TITLE
Foundry is not able to install solc.

### ISSUE THREAD

**Issue by Hareem-Saad** [foundry-rs/foundry#4747]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0

### What command(s) is the bug in?

forge test, forge build

### Operating System

Linux

### Describe the bug

I recently installed ubuntu 22 and then installed foundry on it.

forge init works fine, creates me a baseline project, but when I run forge test or build it gets stuck on ```Installing solc version 0.8.19``` for hours on end.

**Comment by Evalir** [comment]
Closing as stale, and I believe this was a faulty solc version in SVM at the time.
