### ISSUE TITLE
`cast sig` - param of uint256 and uint return the same selector

### ISSUE THREAD

**Issue by 0xfarhaan** [foundry-rs/foundry#4751]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (04ce078 2023-04-17T00:04:57.209269000Z)

### What command(s) is the bug in?

cast sig

### Operating System

macOS (Apple Silicon)

### Describe the bug

When using cast sig with the `uint` param type it returns the same signature as the `uint256` type.

Example:
`cast sig "test(uint)"` returns `0x29e99f07`
`cast sig "test(uint256)"` returns `0x29e99f07`

but `bytes4(keccak256("test(uint)"))` returns `0x1acb6f77`

Not sure if this was done on purpose as `uint` is an alias for `uint256` but there is a difference when generating the function selectors.

**Comment by DaniPopes** [comment]
This is intended since it's just an alias for "uint256". (newer versions of?) Solidity does the same, treats "uint" and "uint256" in a function sig as the same and throws an error if both functions are present in the same contract.

**Comment by 0xfarhaan** [comment]
Whilst I agree if you're using the types directly it differs if you use strings or encodeWithSignature to generate the selector.

Say you do a low level call: 

`address.call(abi.encodeWithSignature("test(uint)", amount))`

The signature this generates for `uint` and `uint256` is different. So if the contract you're calling has the signature `test(uint256)` it won't match the signature we generated above.

**Comment by DaniPopes** [comment]
I don't see where the problem is if Solidity generates "uint256" in both cases. You shouldn't be using "uint" in the first place, and if you really have to, you can use the manual keccak256

**Comment by 0xfarhaan** [comment]
I don't follow this comment? "I don't see where the problem is if Solidity generates "uint256" in both cases."

The problem is with `cast` in the end the utility shouldn't return the same sig for both `uint` and `uint256` because if you create the selector yourself `bytes4(keccak256("test(uint)"))` vs bytes4(keccak256("test(uint256)")) the selectors are different.

**Comment by DaniPopes** [comment]
Solidity generates the same ABI for both uint and uint256, namely both are encoded as uint256. "cast sig" generates a selector from a solidity function signature by parsing it as such. It is intended that it has the same behaviour as Solidity.

What it *doesn't do* is run "keccak256(bytes4(<sig>))" as if it were a raw string. If you want that behaviour, you can use this command instead to hash the raw bytes:

```sh
cast sha3 "sig()" | cut -c-6
```

**Comment by 0xfarhaan** [comment]
Closing issue, above makes sense. Thanks @DaniPopes
