### ISSUE TITLE
Unable to run scripts on contracts with linked libraries

### ISSUE THREAD

**Issue by chlwys** [foundry-rs/foundry#4758]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (4a0c8dc 2023-04-15T00:09:32.582313000Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Intel)

### Describe the bug

Running scripts fails when including linked libraries. Removing the linked library or converting it to an internal library allows skips the bug. Fails on both solidity 0.8.13 and 0.8.17

Need to use linked libraries here because of contract space constraints.

Logs:

> stderr:
> 
> tderr: 31
> stderr: mThe application panicked (crashed).
> Message:  called `Option::unwrap()` on a `None` value
> Location: /Users/runner/work/foundry/foundry/cli/src/cmd/forge/script/executor.rs:48
> 
> This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry
> 
>   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
>    1: __mh_execute_header<unknown>
>       at <unknown source file>:<unknown line>
>    2: __mh_execute_header<unknown>
>       at <unknown source file>:<unknown line>
>    3: __mh_execute_header<unknown>
>       at <unknown source file>:<unknown line>
>    4: __mh_execute_header
> 
> tderr: 90m<unknown>
>       at <unknown source file>:<unknown line>
>    5: __mh_execute_header<unknown>
>       at <unknown source file>:<unknown line>
>    6: __mh_execute_header<unknown>
>       at <unknown source file>:<unknown line>
>    7: __mh_execute_header<unknown>
>       at <unknown source file>:<unknown line>
>    8: __mh_execute_header
> 
> tderr: 90m<unknown>
>       at <unknown source file>:<unknown line>
>    9: __mh_execute_header<unknown>
>       at <unknown source file>:<unknown line>
>   10: __mh_execute_header<unknown>
>       at <unknown source file>:<unknown line>
>   11: __mh_execute_header<unknown>
>       at <unknown source file>:<unknown line>
>   12: __mh_execute_header
> 
> tderr: m<unknown>
>       at <unknown source file>:<unknown line>
>   13: __mh_execute_header<unknown>
>       at <unknown source file>:<unknown line>
>   14: __mh_execute_header<unknown>
>       at <unknown source file>:<unknown line>
>   15: __mh_execute_header<unknown>
>       at <unknown source file>:<unknown line>
> stderr:
> 
> Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
> Run with RUST_BACKTRACE=full to include source snippets.

**Comment by chlwys** [comment]
update: we've fixed it by adding a test with incorrect import syntax (importing a contract that doesnt exist)

no clue why this works. its just a load bearing test now. the bug still exists

**Comment by Evalir** [comment]
Hey @chlwys — could you retry this and see if it's working now? We just fixed a major bug in linking would like to see if this tackled it.

**Comment by zerosnacks** [comment]
> update: we've fixed it by adding a test with incorrect import syntax (importing a contract that doesnt exist)

ping @chlwys could you check if this is still an issue?

**Comment by zerosnacks** [comment]
Marking as `resolved`

Was able to successfully deploy a contract with a linked library
