### ISSUE TITLE
Checksum not found

### ISSUE THREAD

**Issue by pauliax** [foundry-rs/foundry#4759]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a44159a 2023-01-02T09:03:57.3799337Z)

### What command(s) is the bug in?

DISABLE_LOGS=true TS_NODE_TRANSPILE_ONLY=1 TESTING=1 forge coverage --report summary

### Operating System

Windows

### Describe the bug

Not my project, but when running this command, it crashes.

` "coverage": "DISABLE_LOGS=true TS_NODE_TRANSPILE_ONLY=1 TESTING=1 forge coverage --report summary"`

![image](https://user-images.githubusercontent.com/22328890/232712846-f347f2c0-6344-43c1-81a7-4a77c4b7e765.png)

The same is with other commands, e.g. `forge test`.

**Comment by mds1** [comment]
Can you `foundryup` to upgrade your forge version and see if this still happens? Looks like you're on a version that's a few months

**Comment by pauliax** [comment]
> Can you `foundryup` to upgrade your forge version and see if this still happens? Looks like you're on a version that's a few months

Thank you, running this on Windows solved the problem:
`cargo install --git https://github.com/foundry-rs/foundry foundry-cli anvil chisel --bins --locked`

**Comment by mds1** [comment]
Awesome, glad to hear it :)
