### ISSUE TITLE
forge build do not remove old artifact

### ISSUE THREAD

**Issue by wighawag** [foundry-rs/foundry#4760]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (04ce078 2023-04-18T00:04:04.312336893Z)

### What command(s) is the bug in?

forge build

### Operating System

Linux

### Describe the bug

When removing/renaming solidity contract file or removing/renaming contract name in solidity files, `forge build` keep old artifact

This prevent using the `out` folder as a source for the current set of artifacts ready to be used

**Comment by mattsse** [comment]
do you have a repro for this?

**Comment by SaulDope** [comment]
Can confirm I see this behavior as well

**Comment by DaniPopes** [comment]
We don't prune "unused" artifacts, nor I don't think we want to. Run with --force or `forge clean` beforehand.
