### ISSUE TITLE
Invalid test gas reporting for reverting tests

### ISSUE THREAD

**Issue by iconofsin** [foundry-rs/foundry#4764]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8d0099b 2023-04-18T08:52:10.531191000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Intel)

### Describe the bug

Code edited to redact project details.

The function in question belongs a contract known as `machine` and it will attempt to pull an `amount` of LINK from `account` using an ERC20 transfer wrapper (see below):
  ```solidity
    function transferLINKFrom(uint256 id, address account, uint256 amount) external {
        _enforce();
        emit LINKReplenished(id, account, amount);
        linkBalances[id] += amount;
        if (!link.stave(account, address(this), amount))
            revert ERC20TransferFailed();
    }
 ```

`transferLINKFrom` is supposed to be called from another contract, which `_enforce()` checks for:

```solidity
    function _enforce() internal view {
        if (msg.sender != address(hook)) revert Unauthorized();
    }
```
 
The ERC20 transfer wrapper is as follows:
```solidity
import "@openzeppelin8/contracts/token/ERC20/utils/SafeERC20.sol";
import "@openzeppelin8/contracts/token/ERC20/IERC20.sol";

library TransferERC20 {
    using SafeERC20 for IERC20;

    function stave(
        IERC20 token,
        address from,
        address to,
        uint256 amount
    ) internal returns (bool) {
        uint256 initialBalance = token.balanceOf(to);
        if (from == address(this)) {
            token.safeTransfer(to, amount);
        } else {
            token.safeTransferFrom(from, to, amount);
        }
        uint256 finalBalance = token.balanceOf(to);
        return (initialBalance + amount == finalBalance);
    }
}
```

This is the entry point (the driver contract which is known as the hook in the previous code snippet):
```solidity
    function startGame(uint256 id, address linkSource_) external {
        Game storage game = _getGameIfOrganizer(id);
        GameRound storage round = game.rounds[game.activeRound];
        if (
            game.activeRound > 0 ||
            (game.transitionTimestamps[STATE_INDEX_IN_PROGRESS] > 0)
        ) revert GameRunning();

        _setRoundState(id, 0, round, RoundState.InProgress);
        address from = (linkSource_ == address(0)) ? msg.sender : linkSource_;
        emit GameStarted(
            id,
            address(game.token),
            game.organizer
        );
        machine.transferLINKFrom(id, from, minimums[Params.LINK]);
    }
```

And finally, the relevant tests (`transient` is a modifier that takes a snapshot and reverts after, perhaps extraneous, but it doesn't impact tests):

```solidity
    function test_transferLINKFrom_non_hook_reverts() public transient {
        vm.prank(deployer);
        vm.expectRevert(Machine.Unauthorized.selector);
        bm.transferLINKFrom(0, address(0), 1);

        NonHookLINKTransferer nclt = new NonHookLINKTransferer();

        vm.expectRevert(Machine.Unauthorized.selector);
        nclt.simulatePullDeposit(address(bm));
    }
```

This checks that `transferLINKFrom` reverts on the `_enforce` condition both when called by an EOA and a contract that has not been set as the hook (which is what NonHookLINKTransferer is, a mock that simply calls `transferLINKFrom`). Running the test results in the following:

`[PASS] test_transferLINKFrom_non_cryptoballz_reverts() (gas: 115800)` I imagine most of the gas here is due to deploying an instance of NonHookLINKTransferer, and the intrinsic cost of the reverted transactions is negligibly low.

The other test is:
```solidity
    // @dev Fail when the allowance is sufficient, but the balance is insufficient
    function test_transferLINKFrom_insufficient_LINK_reverts() public {
        uint256 insufficientLINKAmount = 25 ether - 1;
        uint256 sufficientLINKAmount = insufficientLINKAmount + 1;
        deal(link, deployer, insufficientLINKAmount);

        vm.startPrank(deployer);
        bm.setHook(address(hook));

        IERC20(link).approve(address(bm), sufficientLINKAmount);

        vm.expectRevert("SafeERC20: low-level call failed");
        hook.startGame(0, address(0));
        vm.stopPrank();
    }
```

Here, `link` is the mock LINK token (deployed according to instructions by Chainlink). The testing is done on a Mainnet Ethereum fork, starting with block `16990493`. 

But this test results in:

`[PASS] test_transferLINKFrom_insufficient_LINK_reverts() (gas: 8797746687696090261)`

Another test where the amount in the balance is sufficient, but the allowance is insufficient does the same. As far as I can tell, these are the only two tests (out of 27 so far) that exhibit this overreactive behaviour.

The only idea I have is it somehow is related to `deal` (I haven't checked it any LINK exists on my mock at all), but the SafeERC20 wrapper does revert with a correct error, so in theory this shouldn't be an influence?

**Comment by grandizzy** [comment]
@iconofsin this could happen when the spent gas is less than refunded so an overflow happens as in https://github.com/foundry-rs/foundry/issues/4370
Going to optimistically close this one (as don't have full code to try reproducing it), please reopen with full source code to debug if you still see this issue.
Thank you!
