### ISSUE TITLE
bug: `forge inspect <contract> ir` hangs as it compiles all contracts

### ISSUE THREAD

**Issue by clabby** [foundry-rs/foundry#4765]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

da2392e & head at time of writing (8d0099be497922b53cded74b77a3e0b3c1079336)

### What command(s) is the bug in?

forge inspect

### Operating System

Linux

### Describe the bug

When running `forge inspect L1CrossDomainMessenger ir` in [`contracts-bedrock`](https://github.com/ethereum-optimism/optimism/tree/develop/packages/contracts-bedrock/contracts), the process seems to perpetually hang. I've had it running for nearly an hour on my Desktop, and the process has not exited.

> **Note**
> This could be due to long compilation times via the IR pipeline, `contracts-bedrock` is a large project - it is possible this is not foundry's fault.

**Comment by clabby** [comment]
Update: After an hour and a half, the command exited:
![Screenshot from 2023-04-18 13-33-51](https://user-images.githubusercontent.com/8406232/232858307-f8b2bbfb-a36a-4726-8320-8d419d94f0e9.png)

**Comment by mattsse** [comment]
this looks like a solc issue because this is a solc error message

**Comment by maurelian** [comment]
> hmm, this looks like a solc issue because this is a solc error message

That is odd. I'm able to generate the IR (in the same [repo and dir ](https://github.com/ethereum-optimism/optimism/tree/develop/packages/contracts-bedrock)as @clabby's screenshot) by running `solc` directly with this command: 

```
solc --ir "@openzeppelin/=./node_modules/@openzeppelin/" "@rari-capital=./node_modules/@rari-capital" contracts/L1/L1CrossDomainMessenger.sol
```

Perhaps forge is invoking the compiler incorrectly?

**Comment by daltyboy11** [comment]
I have experienced the same issue, and you can reproduce it with a very simple contract.

`forge inspect Foo ir` will hang, yet `solc --ir Foo.sol` will work. Forge version is `forge 0.2.0 (59f026f 2023-05-23T17:21:42.593814000Z)`

```
// SPDX-License-Identifier: MIT

pragma solidity >=0.8.19;

contract Foo {
  function increment(uint x) external pure returns (uint) {
    return x + 1;
  }
}
```

**Comment by mattsse** [comment]
it could just be that the solc input args for inspect are causing this, perhaps this is set for the entire input, which leads to long compile times on large repos

**Comment by grandizzy** [comment]
I cannot reproduce this with latest version, `time forge inspect L1CrossDomainMessenger ir` output

```
real	0m0.832s
user	0m1.459s
sys	0m0.140s
```

@clabby @mds1 could you please recheck and see if it can be closed? thank you!

**Comment by mds1** [comment]
Confirmed, thank you!
