### ISSUE TITLE
installing openzeppelin dependencies

### ISSUE THREAD

**Issue by SurajPoddar02** [foundry-rs/foundry#4771]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

0.2.0

### What command(s) is the bug in?

forge install @openzeppelin/contracts@4.4.0

### Operating System

Linux

### Describe the bug

The target directory is a part of or on its own an already initialized git repository, and it requires clean working and staging areas, including no untracked files.  Check the current git repository's status with `git status`. Then, you can track files with `git add ...` and then commit them with `git commit`, ignore them in the `.gitignore` file, or run this command again with the `--no-commit` flag.  If none of the previous steps worked, please open an issue at: https://github.com/foundry-rs/foundry/issues/new/choose

**Comment by KholdStare** [comment]
What's the problem? "Describe the bug" doesn't really describe the bug

**Comment by Evalir** [comment]
Closing—not a lot of information here and we improved this with #5209
