### ISSUE TITLE
Contracts are not properly covered (code coverage) when they define the same event

### ISSUE THREAD

**Issue by gagiuntoli** [foundry-rs/foundry#4780]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8d0099b 2023-04-19T00:08:21.764755505Z)

### What command(s) is the bug in?

forge coverage

### Operating System

Linux

### Describe the bug

I have use [this small](https://github.com/onbjerg/forge-coverage-test) repository used to test `forge coverage`. [Here](https://github.com/onbjerg/forge-coverage-test/pull/1) are my modifications to replicate the bug.

I cornered case the example a bit (the updates are also in the PR):

Let's define 2 new contracts:

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity >=0.8.15;

contract ExtraFileContract1 {
    event ExtraFileEvent(uint256 n);

    function compute(bool increment) external {
        // Should be treated as a branch
        require(increment);

        emit ExtraFileEvent(2);
    }
}

contract ExtraFileContract2 {
    // BUG (?): If we would call this event `ExtraFileEvent(uint256 n)`
    // then the compute function below would not be covered.
    // event ExtraFileEvent(uint256 n);
    event ExtraFileEvent();

    function compute(bool increment) external {
        // Should be treated as a branch
        require(increment);

        //emit ExtraFileEvent(2);
        emit ExtraFileEvent();
    }
}
```

In this case, we have 100% coverage.

If we rename the event as `ExtraFileEvent(uint256)` (or uncomment the lines) now we get 50% coverage.

What role are these events playing in code coverage?

**Comment by grandizzy** [comment]
confirmed fixed with https://github.com/foundry-rs/foundry/pull/8214

![image](https://github.com/foundry-rs/foundry/assets/38490174/08daad16-8275-4c56-9fa4-f73659f7b239)
