### ISSUE TITLE
run all repro tests in different CI job

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#4782]
### Component

Forge

### Describe the feature you would like

A lot of repro tests make use of forking and can lead to stalled CI

## TODO
* add new nextest run job that only runs repros
* exclude them in the existing runner

cc @Evalir do you want to try this?

this is how filters are set: 

https://github.com/foundry-rs/foundry/blob/dd58c32c2c153d5d9cde55d03b8830a44321d4ba/.github/workflows/test.yml#L90-L90

**Comment by Evalir** [comment]
yup happy to take this on!
