### ISSUE TITLE
ERROR sharedbackend: Failed to send/recv `basic` err=GetAccount

### ISSUE THREAD

**Issue by binsta** [foundry-rs/foundry#4787]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (df8ab09 2023-03-14T09:59:20.944687208Z)

### What command(s) is the bug in?

forge test --contracts ./src/test/HundredFinance_2_exp.sol -vvv

### Operating System

Linux

### Describe the bug

2023-04-21T03:49:10.872474Z ERROR sharedbackend: Failed to send/recv `basic` err=GetAccount(0x0000000000000000000000000000000000000000, 
(code: -32000, message: missing trie node 7887fc47300c36f531168e38613b85a3a5d30ef0f9fa6f36cb6d67978630e8b9 (path ), data: None)) address=0x0000000000000000000000000000000000000000
The application panicked (crashed).
Message:  called `Option::unwrap()` on a `None` value
Location: /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/revm-2.3.1/src/evm_impl.rs:285

**Comment by mds1** [comment]
Pretty sure `missing trie node` usually means you are trying to access archive data on a non-archive node, or there's an issue on the RPC provider's side. I don't think there is a forge issue here though, so going to close this
