### ISSUE TITLE
feat(forge): Solidity cheat to find and replace text in bytes and string variables

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/foundry#4789]
### Component

Forge

### Describe the feature you would like

Suppose you have a differential test that compares the bytecodes of a contract deployed using two different methods, e.g. see [`deployPermit2`](https://github.com/Uniswap/permit2/blob/db96e06278b78123970183d28f502217bef156f4/test/utils/DeployPermit2.sol#L12).

Now, imagine the contract-under-test takes a storage record of its `address(this)` in the constructor. In this case, the two deployment methods would produce two slightly different bytecodes (only ~20 bytes would be different), so the differential test would fail.

There are various ways to fix this using `vm.ffi`, but it would be nice to have a native find-and-replace cheat so that users don't have to exit Solidity in this scenario.

### Additional context

**Late edit**: it looks like I could use Solady's [`LibString`](https://github.com/Vectorized/solady/blob/2c7fa305e443b0e69abff24810dc814a9202f966/src/utils/LibString.sol#L354) for this.

**Comment by Tudmotu** [comment]
I would also like this feature.

`LibString` is not sufficient for me since I need UTF support. `solidity-stringutils` is too low-level and too slow for my needs.

What I have in mind is this interface:
```solidity
function stringReplaceAll (string memory source, string memory pattern, string memory replacement);
```
Where `pattern` will be a regex (as in `Regex::new(pattern).unwrap()`) and the cheatcode would invoke `.replace_all(source, replacement)`.

@PaulRBerg @mattsse WDYT?

**Comment by zerosnacks** [comment]
Marking as resolved by https://github.com/foundry-rs/foundry/pull/6891, implementing native cheatcodes for working with strings, including `replace`

Feel free to re-open if there are still action items @Tudmotu / @PaulRBerg
