### ISSUE TITLE
foundry symlinks issues

### ISSUE THREAD

**Issue by wighawag** [foundry-rs/foundry#4800]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e0afc7c 2023-04-22T00:03:37.411928847Z)

### What command(s) is the bug in?

forge compile

### Operating System

Linux

### Describe the bug

Reproduction repo : https://github.com/bug-reproduction/foundry-symlinks

Basically I am creating a symlinkd folder  into the lib folder and interestingly forge follow that link and can even import files from there as long as there is no import in these files that import from that lib subfoler

More details in the repo 

To reproduce execute the following:

```bash
git clone git@github.com:bug-reproduction/foundry-symlinks.git;
cd foundry-symlinks;

# working case
cp -R project-to-link forge-project/lib;
cd forge-project;
forge test;

cd ..;
rm -Rf forge-project/lib/project-to-link;

# failing case
ln -s `pwd`/project-to-link ./forge-project/lib/
cd forge-project;
forge test;

cd ../..;
```

Note that as mentioned, if the imported project do not itself import files of its own there is no issue.

if you remove that line from [project-to-link/src/AnotherCounter.sol](https://github.com/bug-reproduction/foundry-symlinks/blob/main/project-to-link/src/AnotherCounter.sol) it works

```
import "./TheIssueManifestItselfWhenTheLinkedProjectImportItself.sol";
```

**Comment by sambacha** [comment]
you may have to define the relative path for that dependency for forge to use git submodules to access the symlink path to the actual dir. Otherwise your outside the git dir

**Comment by wighawag** [comment]
Not sure what you mean here. My setup is a mono repo and want to use symlink to link the project to other and I do not want to use git submodule for that

Note that the lib is reachable via the symlink and the failure only happen if the file imported is itself referencing other file in its own lib. seems like a bug to me

**Comment by ifelsedeveloper** [comment]
I have the same issue and would like to use monorepo on lerna 8.0.2. Please prior this, many solidity projects are using monorepo

**Comment by DaniPopes** [comment]
This was fixed: I ran all commands in the [repro README](https://github.com/bug-reproduction/foundry-symlinks) successfully.
