### ISSUE TITLE
Anvil: CREATE2 Deployer not present on this chain. [0x4e59b44847b379578588920ca78fbf26c0b4956c]

### ISSUE THREAD

**Issue by wighawag** [foundry-rs/foundry#4807]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e0afc7c 2023-04-22T00:03:37.411928847Z)

### What command(s) is the bug in?

anvil and forge script

### Operating System

Linux

### Describe the bug

get anvil running
```bash
anvil
```

Then  create a project exhibiting the issue:

```bash
# create project
mkdir test-project;
cd test-project;
forge init;

# add a create2 call in a deploy script

cat > script/Counter.s.sol <<EOF
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import "forge-std/Script.sol";
import "../src/Counter.sol";

contract CounterScript is Script {
    function setUp() public {}

    function run() public {
        vm.broadcast();
        new Counter{salt: bytes32(uint256(1))}();
    }
}
EOF
```

Finally see the issue when executing the script against anvil:

```bash
forge script script/Counter.s.sol -v --rpc-url http://localhost:8545 --broadcast;
```

```
CREATE2 Deployer not present on this chain. [0x4e59b44847b379578588920ca78fbf26c0b4956c]
```

**Comment by mds1** [comment]
Hmm, should we have the create2 deployer on anvil by default? Not all chains have it so it feels like maybe we shouldn't. OTOH forge is focused on Ethereum mainnet which does have it so maybe anvil should also

Note that workarounds here are:
- Start anvil from a fork of a network that has the deployer (many chains do)
- Use the `anvil_setCode` RPC method to place that create2 deployer at that address

**Comment by wighawag** [comment]
I assumed that the create2 mechanism used by forge was supposed to automatically deploy a create2 fatory.

if not, then yes I agree, let's not do anything special

The workaround you propose fall short in my opinion

I might want to target a chain where the factory is not deployed yet

`anvil_setCode` would be a special case that works only for anvil

While I posted the issue I was looking for ways to send raw signed tx to basically deploy it myself: https://github.com/foundry-rs/foundry/issues/4816

**Comment by mds1** [comment]
> I assumed that the create2 mechanism used by forge was supposed to automatically deploy a create2 fatory.

forge uses the create2 deployer located at [`0x4e59b44847b379578588920cA78FbF26c0B4956C`](https://etherscan.io/address/0x4e59b44847b379578588920ca78fbf26c0b4956c). Anyone can deploy it on other chains though, the deployment transaction / more info on this deployer is here: https://github.com/Arachnid/deterministic-deployment-proxy

**Comment by wighawag** [comment]
I know how it works, I am the one we funded the signer and deployed it on [ethereum mainnet](https://etherscan.io/tx/0x2814f03c51cad09458eccf1dd0a2c101732e47f8bf8bbcfe49ab4eddebea365b)   (I have nothing to do with the wolf of wallstreet though :D, I guess they were the first to register with etherscan or something )

That is why It would be great if https://github.com/foundry-rs/foundry/issues/4816 was possible this way we can do it from solidity itself

**Comment by mds1** [comment]
Got it, given that context I understand the use case for #4816, and I think the feature request here is for forge to auto deploy the create2 deployer if it's missing? (Someone of course would have to fund the deployer address before running the forge script)

**Comment by wighawag** [comment]
The cool thing about #4816  is that forge would not need to do it on its own, a tool like forge-deploy could it for the user and handle the funding part too. this way it works on all network where the create2 factory works. 

And then like hardhat-deploy do, the tool could also support network where a different factory is required, see : https://github.com/wighawag/hardhat-deploy/pull/190

**Comment by Craigson** [comment]
What is the mechanism involved for using create2 within tests? I can easily call the `anvil_setCode` RPC call when running a node using `anvil`, but I'm attempting to replicate the behaviour inside tests (I'd prefer to not use a fork as I have separate tests setup for that).  `vm.etch` appears to be able to set the deterministic-deployer-proxy code at the desired address, but `forge` doesn't seem to make use of the contract internally, as far as I can tell.

**Comment by mshakeg** [comment]
Hey @mds1 could you please clarify the work around for deploying to a chain that does not have a create2 deployer at `0x4e59b44847b379578588920ca78fbf26c0b4956c`?

**Comment by mds1** [comment]
Instructions for deploying that deployer are here: https://github.com/Arachnid/deterministic-deployment-proxy

If you're on anvil you can use `anvil_setCode ` to set the code at that address
