### ISSUE TITLE
feat (cheatcode) TOML support

### ISSUE THREAD

**Issue by wighawag** [foundry-rs/foundry#4808]
### Component

Forge

### Describe the feature you would like

The TOML format is used by foundry itself and is quite an elegant configuration format.

it would be great if we could have TOML parsing facility like we do for json via vm cheatcode

This would allow us to also read the foundry toml file and this way we could extend it with new parameters

**Comment by zobront** [comment]
+1, would love this as well. Especially useful for interacting with Noir circuits.
