### ISSUE TITLE
no ir file generated when set `extra_output_files = [ "ir" ]`

### ISSUE THREAD

**Issue by robinsdan** [foundry-rs/foundry#4809]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (dedc31e 2023-04-23T07:49:04.825009295Z)

### What command(s) is the bug in?

forge build

### Operating System

Linux

### Describe the bug

after invoke `forge build`, no `.ir` files generated in the out dir.
but when set `extra_output_files = ["irOptimized" ]`, the `.iropt` file is generated.

**Comment by mds1** [comment]
Sorry, what is the issue here? By default the IR is not generated, it must be specified like you did, then the file is generated

**Comment by robinsdan** [comment]
@mds1 I have set extra_output_files = [ "ir" ], no IR file generated.

**Comment by mds1** [comment]
Ah, yea according to [the docs](https://book.getfoundry.sh/reference/config/solidity-compiler#extra_output_files) this should be supported, but you're right, I was able to reproduce this. cc @mattsse

**Comment by omMora** [comment]
Quick work around: include both options

extra_output = ['ir']
extra_output_files = ['ir']
