### ISSUE TITLE
Plans to support more cheatcodes in chisel?

### ISSUE THREAD

**Issue by jat9292** [foundry-rs/foundry#4811]
### Component

Chisel

### Describe the feature you would like

Support all the cheatocdes in chisel

### Additional context

Today only a few cheatcodes are supported in chisel, like prank and deal. But many are still missing : assertLt , envUnit, envAddress, assertEq , etc. 
Furthermore it is not clear which ones are already supported and which are not.

**Comment by mattsse** [comment]
Supportive,
What do you think ahould be prioritized?

**Comment by jat9292** [comment]
For quick testing purposes I think most important ones are assertions related ones like, especially assertEq.

**Comment by mds1** [comment]
Not sure what you are doing, but you can probably just use `require` instead of `assertEq` for that use case.

But the distinction here seems to be that the vm interface/cheats are available, but the stdCheats/etc from forge-std are not present. Maybe we just need a way to pull in forge-std into chisel (if that's not currently present)? cc @clabby

**Comment by jat9292** [comment]
This feature is useful to be able to debug tests faster inside chisel for example.

**Comment by jat9292** [comment]
Another annoying inconsistency I noticed is that vm.deal cheatcode in Chisel is only available for native ETH, but not for ERC20 tokens. I.e only the 2 arguments version of deal cheatcode is available. It would be nice if we can re-use same cheatcodes in Test and in Chisel.

**Comment by clabby** [comment]
> Not sure what you are doing, but you can probably just use `require` instead of `assertEq` for that use case.
> 
> But the distinction here seems to be that the vm interface/cheats are available, but the stdCheats/etc from forge-std are not present. Maybe we just need a way to pull in forge-std into chisel (if that's not currently present)? cc @clabby

We can definitely pull in forge-std, but when I did that for the first iteration to get it working, it slowed down compilation time and made the repl feel a good bit less snappy. We'd also have to add forge-std as a submodule - will defer to @mattsse and you on whether or not this is worth it!

As for the inconsistency of some of the cheatcodes (i.e. the lack of the version of `vm.deal` that is for ERC20 tokens), it's looking like that cheatcode is not present in `testdata/cheats/Cheats.sol`. Should probably go through and make sure `Cheats.sol` has parity w/ forge-std's `Vm.sol` and write tests for the ones that aren't there at the moment.
