### ISSUE TITLE
The Trust Settings Record was corrupted

### ISSUE THREAD

**Issue by ysqi** [foundry-rs/foundry#4813]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

nightly-dedc31eed0683764ae542b9b575c21f6bd2a5c60

### What command(s) is the bug in?

forge script script/deploy.s.sol --fork-url $GOERLI_RPC_URL --broadcast  -s "deployToken()" -vvvv

### Operating System

macOS (Intel)

### Describe the bug

```text
The application panicked (crashed).
Message:  Client::new(): reqwest::Error { kind: Builder, source: Custom { kind: Other, error: Error { code: -25262, message: "The Trust Settings Record was corrupted." } } }
Location: /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.16/src/async_impl/client.rs:1546

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
[1]    60788 abort      forge script script/deploy.s.sol --fork-url $GOERLI_RPC_URL --broadcast 
```

**Comment by VoR0220** [comment]
I am also running into this issue on build and test commands right when it's trying to install solc.

**Comment by ysqi** [comment]
It worked after removing all invalid certificates on the Mac.
