### ISSUE TITLE
Unable to add new item using the vm.writeJson method.

### ISSUE THREAD

**Issue by ysqi** [foundry-rs/foundry#4814]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

nightly-e99cf83396c4320e8c7e7f6650916183ad3051b4

### Operating System

None

### Describe the bug

While attempting to use vm.writeJson, I cannot set the value for the `.Goerli.admin2` path:

```json
{
  "Goerli": { }
}
```

However, when I write an empty value, the operation is successful:

```json
{
  "Goerli": {"admin2":"" }
}
```

here is my function :
```solidity
function writeJSON(string memory key, address value) public {
        string memory path = string.concat(".", chainName, key);
        vm.writeJson(vm.toString(value), "./deployInfo.json", path);
}
```
print log:
```text
VM::writeJson(<stringified JSON>, ./deployInfo.json, .Goerli.admin2)

Script ran successfully.
```

**Comment by mds1** [comment]
It sounds like you need to use `serializeJson` cheat to format your JSON properly before writing it: https://book.getfoundry.sh/cheatcodes/serialize-json

Closing this issue optimistically, but can reopen if there is a bug

**Comment by mds1** [comment]
Sorry, I don't understand why you can't use `serializeJson`? The purpose of that cheatcode is to help format JSON for writing it to a file, as shown in the docs linked above
