### ISSUE TITLE
Sign bytes with `cast wallet sign`

### ISSUE THREAD

**Issue by adhusson** [foundry-rs/foundry#4817]
### Component

Cast

### Describe the feature you would like

Often the data to be signed is not a string, it's raw bytes.

Two possible ways to present the feature:
1. `--as-hex` interprets the message as a hex string
2. Guess the data type by checking if the argument is prefixed by `0x` or not.

**Comment by 0xdapper** [comment]
I think this is done?

**Comment by adhusson** [comment]
#4820 closes it!
