### ISSUE TITLE
foundry test crashing

### ISSUE THREAD

**Issue by sanchaymittal** [foundry-rs/foundry#4825]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (df8ab09 2023-03-14T10:00:26.197329Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

[⠒] Compiling...
[⠒] Compiling 1 files with 0.8.19
[⠘] Solc 0.8.19 finished in 11.86s
Compiler run successful
2023-04-26T03:15:18.636505Z ERROR sharedbackend: Failed to send/recv `storage` err=GetStorage(0x7fa9385be102ac3eac297483dd6233d62b3e1496, 36, 
Deserialization Error: invalid type: string "1", expected u64 at line 1 column 25. Response: {"jsonrpc":"2.0","id":"1","error":{"code":-32043,"message":"Requested data is not available"}}) address=0x7fa9385be102ac3eac297483dd6233d62b3e1496 index=36
2023-04-26T03:15:18.776114Z ERROR sharedbackend: Failed to send/recv `basic` err=GetAccount(0x0000000000000000000000000000000000000000, 
Deserialization Error: invalid type: string "1", expected u64 at line 1 column 25. Response: {"jsonrpc":"2.0","id":"1","error":{"code":-32043,"message":"Requested data is not available"}}) address=0x0000000000000000000000000000000000000000
The application panicked (crashed).
Message:  called `Option::unwrap()` on a `None` value
Location: /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/revm-2.3.1/src/evm_impl.rs:285

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

**Comment by mattsse** [comment]
what provider did you use?

this is an error because it sends invalid json-rpc

**Comment by Evalir** [comment]
Closing—provider/RPC related.
