### ISSUE TITLE
`changePrank` fails with `No prank in progress to stop`

### ISSUE THREAD

**Issue by grandizzy** [foundry-rs/foundry#4835]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (f05fdd8 2023-04-27T00:04:10.201981651Z)

### Operating System

Linux

### Describe the bug

`changePrank` with no prank started used to work and was properly changing prank before enforcing it in https://github.com/foundry-rs/foundry/pull/4827 (https://github.com/foundry-rs/foundry/commit/8973b2b3ef1873ea1f81fdeb4dbbaa35a5881163)
For backwards compatibility reasons, can we have the `changePrank` exempted from this new check? (test works OK if `foundryup -v nightly-dedc31eed0683764ae542b9b575c21f6bd2a5c60`)

```Solidity
pragma solidity 0.8.14;

import '@std/Test.sol';
import '@std/Vm.sol';

contract SampleTest is Test {

    address bob;
    address alice;

    function setUp() external {
        bob = makeAddr("bob");
        alice = makeAddr("alice");

        vm.prank(bob);
    }

    function test_sample() external {
        changePrank(alice);
    }

}
```

```
Running 1 test for tests/forge/SampleTest.t.sol:SampleTest
[FAIL. Reason: No prank in progress to stop] test_sample() (gas: 5191)
Test result: FAILED. 0 passed; 1 failed; finished in 613.35µs
```

**Comment by PaulRBerg** [comment]
> `changePrank` with no prank started used to work

This should never have been the case. See https://github.com/foundry-rs/foundry/issues/4779. Are you absolutely sure that you didn't have a `startPrank` somewhere in your code base?

Cc @mds1.

**Comment by grandizzy** [comment]
> > `changePrank` with no prank started used to work
> 
> This should never have been the case. See #4779. Are you absolutely sure that you didn't have a `startPrank` somewhere in your code base?
> 
> Cc @mds1.

Oh, could be a plain `vm.prank` actually, going to double check

**Comment by grandizzy** [comment]
> > > `changePrank` with no prank started used to work
> > 
> > 
> > This should never have been the case. See #4779. Are you absolutely sure that you didn't have a `startPrank` somewhere in your code base?
> > Cc @mds1.
> 
> Oh, could be a plain `vm.prank` actually, going to double check

@PaulRBerg yeah, you're right, I updated test contract sample in PR description, thanks for flagging

**Comment by mds1** [comment]
I think we should keep the behavior from #4827, as if you have a `stopPrank` without a `startPrank` semantically that doesn't make sense and maybe you have a bug. Then we'd implement https://github.com/foundry-rs/foundry/pull/4826#issuecomment-1523333261, which removes the need for `changePrank` and would fix the UX

**Comment by grandizzy** [comment]
> I think we should keep the behavior from #4827, as if you have a `stopPrank` without a `startPrank` semantically that doesn't make sense and maybe you have a bug. Then we'd implement [#4826 (comment)](https://github.com/foundry-rs/foundry/pull/4826#issuecomment-1523333261), which removes the need for `changePrank` and would fix the UX

Thank you, I think this makes sense. Do you have any timeline for #4826 , not sure if I should start fixing tests (pretty substantial :) ) at this point and then update them again when #4826 gets in. Or if I should just lock version that works here atm and update test only once when #4826 ready.

**Comment by mds1** [comment]
@4meta5 is working on that PR so deferring to them on timeline :)

**Comment by Evalir** [comment]
@mds1 is this closeable?

**Comment by mds1** [comment]
I think so, if anyone disagrees just let me know why and we can reopen
