### ISSUE TITLE
Feature request: vm.sleep() cheatcode

### ISSUE THREAD

**Issue by Tudmotu** [foundry-rs/foundry#4848]
I've been using Forge scripts as a full-on scripting environment, interacting with contracts, running simulations, etc.

One thing I'm still missing is polling: e.g. calling the Uniswap Quoter every 10s.

Would you consider adding a `vm.sleep(uint ms)` cheatcode?

I'd be happy to implement/assist, if this is a desirable feature.

**Comment by pistomat** [comment]
I can do this

**Comment by Evalir** [comment]
Should I assign it to you @pistomat ?

**Comment by pistomat** [comment]
Yes please

**Comment by Tudmotu** [comment]
Thank you @pistomat :pray:
