### ISSUE TITLE
I can't install foundry

### ISSUE THREAD

**Issue by 0xEvi** [foundry-rs/foundry#4852]
**when I try to do the command**  
```
curl -L https://foundry.paradigm.xyz | bash 
```
 **I get the following error:**
 ```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:05:00 --:--:--     0
  curl: (28) SSL connection timeout
  ```

I tried the command line with sudo, updated my curl & npm packages and still getting the same error :(

**Comment by mattsse** [comment]
hmm, is up for me, I just reinstalled it successfully as well.

```
ping foundry.paradigm.xyz
PING foundry.paradigm.xyz (104.24.173.3): 56 data bytes
64 bytes from 104.24.173.3: icmp_seq=0 ttl=59 time=39.678 ms
```

perhaps an issue with your firewall?

**Comment by 0xEvi** [comment]
sounds about right Mattse but I even turned off the firewall on windows and still same error, checked firewall on WSL and it was disabled too :/ I installed most packges and node js and other stuff but when it comes to foundry it doesn't respond back. One last thing to add I pinged the website and still nothing changed. 
```
PING foundry.paradigm.xyz (104.24.172.3) 56(84) bytes of data.
64 bytes from 104.24.172.3 (104.24.172.3): icmp_seq=1 ttl=47 time=71.1 ms
64 bytes from 104.24.172.3 (104.24.172.3): icmp_seq=2 ttl=47 time=69.2 ms
64 bytes from 104.24.172.3 (104.24.172.3): icmp_seq=3 ttl=47 time=71.6 ms
64 bytes from 104.24.172.3 (104.24.172.3): icmp_seq=4 ttl=47 time=75.6 ms
64 bytes from 104.24.172.3 (104.24.172.3): icmp_seq=5 ttl=47 time=69.2 ms
^C64 bytes from 104.24.172.3: icmp_seq=6 ttl=47 time=69.4 ms

--- foundry.paradigm.xyz ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5677ms
rtt min/avg/max/mdev = 69.183/71.020/75.631/2.278 ms
```

**Comment by 0xEvi** [comment]
So with some help i was able to solve it by taking the script out of the paradigm URL and paste in an executable file on my ubuntu and it worked like a charm. I hope if anyone got same issue find the solution here ^.^

**Comment by dopewilly10** [comment]
Hello, please can you clearly state how you fixed pleaseee

**Comment by dopewilly10** [comment]
> So with some help i was able to solve it by taking the script out of the paradigm URL and paste in an executable file on my ubuntu and it worked like a charm. I hope if anyone got same issue find the solution here ^.^

HELLO, PLS EXPLAIN CLEARLY
