### ISSUE TITLE
Coverage doesn't cover internal libs when passing implicit storage vars via the `using` syntax

### ISSUE THREAD

**Issue by Craigson** [foundry-rs/foundry#4854]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8f246e0 2023-04-28T00:14:27.758082000Z)

### What command(s) is the bug in?

forge coverage --report lcov && genhtml -o forge-coverage lcov.info

### Operating System

macOS (Apple Silicon)

### Describe the bug

When importing an internal lib and utilizing it with the `using` syntax, coverage does not detect any hits on the functions in the library.

Example is shown below (some code omitted for brevity):

```js
import "./lib/StakeManagerLibs.sol";

contract StakeManager is IStakeManager, Initializable {
    ...
    using LibStakesManager for Stakes;

    function stakeFor(uint256 id, uint256 amount) external {
        require(id != 0 && id <= _chains.counter, "INVALID_ID");
        MATIC.safeTransferFrom(msg.sender, address(this), amount);
        _stakes.addStake(msg.sender, id, amount); // <========= Coverage registers no hits here
        ISupernetManager manager = managerOf(id);
        manager.onStake(msg.sender, amount);
        emit StakeAdded(id, msg.sender, amount);
    }


```

Yields the following coverage report:

![Screen Shot 2023-04-29 at 7 33 30 PM](https://user-images.githubusercontent.com/4640172/235328259-c082d6a4-e51a-49df-a8aa-757b956f3c55.png)

However, if I change the syntax of how the library function is called, where the storage variable isn't implicitly passed as the first argument, the coverage is correct.

```js
    function stakeFor(uint256 id, uint256 amount) external {
        require(id != 0 && id <= _chains.counter, "INVALID_ID");
        MATIC.safeTransferFrom(msg.sender, address(this), amount);
        LibStakesManager.addStake(_stakes, msg.sender, id, amount); // <======= Use the library explicitly
        // _stakes.addStake(msg.sender, id, amount);
        ISupernetManager manager = managerOf(id);
        manager.onStake(msg.sender, amount);
        emit StakeAdded(id, msg.sender, amount);
    }
```

Then coverage report is accurate:

![Screen Shot 2023-04-29 at 7 36 41 PM](https://user-images.githubusercontent.com/4640172/235328329-d4ef4c6e-c63a-4cdb-952f-1bd8ac26f1db.png)

Another important piece of information to add is that calling the Library function explicitly just once, ie the remainder of the `_stakes.addStake(...)` and any additional library calls to any/all functions using the implicit syntax are now covered.

**Comment by Craigson** [comment]
@gretzke for visibility

**Comment by gretzke** [comment]
The workaround of calling the library directly once also only works once. If you have a second internal library in the same contract you can call it directly as often as you want, it won't show up in the coverage report as covered. This does not seem to be connected to the `using X for Y` syntax, calling all internal libraries directly shows the same behaviour.

**Comment by FredCoen** [comment]
having similar issue with using for directive on custom types

**Comment by aiwowo1** [comment]
I think I have the similar issue by using the `using` syntax to define a state struct define in an internal library. The code coverage report 0 coverage.

**Comment by aviggiano** [comment]
I am having the same issue, but interestingly I don't get 0 coverage, only partial coverage, even though all lines are being touched by my tests.
