### ISSUE TITLE
forge script CLI crashes

### ISSUE THREAD

**Issue by sourabhmarathe** [foundry-rs/foundry#4857]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (91f69dd 2023-05-01T00:13:59.372319000Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Intel)

### Describe the bug

Hey guys, I’m running into a CLI panic when I try to use `forge script`. In short, I run `forge script script/Script.s.sol --rpc-url $GOERLI_RPC_URL` and get the following error message: 
```
The application panicked (crashed).
Message:  called `Option::unwrap()` on a `None` value
Location: /Users/runner/work/foundry/foundry/cli/src/cmd/forge/script/executor.rs:49

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
[1]    95623 abort      forge script script/tenderly/Strategy.s.sol:S
```

Here is the backtrace of the crash:
```
  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   2: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   3: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   4: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   5: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   6: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   7: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   8: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   9: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  10: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  11: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  12: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  13: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  14: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  15: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
```

I also have confirmed that $GOERLI_RPC_URL is set. In addition, when I use the same RPC URL (albeit on its respective mainnet URL) to run `forge test`, it works fine.

**Comment by CJBangert** [comment]
Hello,
Not sure if this is _the_ solution, but a workaround I used that worked was simply specifying and renaming my deploy script, as I have several script files that all had the name DeployScript. For example, I was running
```
forge script script/anvil/DeployFactory.s.sol:DeployScript --fork-url http://localhost:8545 --broadcast --ffi
```
when I also had a `script/anvil/DeployXContract.sol:DeployScript` and a  `script/anvil/DeployYContract.sol:DeployScript` in the same folder. I changed the name of the script contract to `DeployFactoryScript` and it ran successfully: 
```
forge script script/anvil/DeployFactoryToAnvil.s.sol:DeployFactoryScript --fork-url http://localhost:8545 --broadcast --ffi
```

**Comment by sourabhmarathe** [comment]
@CJBangert That was definitely it for me! Thanks for leaving this comment. It looks like this is the result of scripts sharing the same name. 

I'm prepared to close this issue if that's alright, unless the Foundry team feels this is worth addressing. (cc @mds1)
