### ISSUE TITLE
Add `vm.assertContains` with overloads (String, etc..)

### ISSUE THREAD

**Issue by johnnyshankman** [foundry-rs/foundry#4859]
### Component

Forge

### Describe the feature you would like

In the [DS Test](https://book.getfoundry.sh/reference/ds-test) assertions there should be a `assertStringContains(string, string)` method for checking strings interpolation.

### Additional context

Since we are not deploying these contracts to the network, the gas costs of doing string contains is negligible. It's extremely useful in testing on-chain NFT data etc and straight forward enough to do with two for loops that convert to bytes.

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.17;

contract StringContains {

    function assertStringContains(string memory _base, string memory _value) public pure returns (bool) {
        bytes memory baseBytes = bytes(_base);
        bytes memory valueBytes = bytes(_value);

        if (valueBytes.length == 0) {
            return true;
        }

        if (baseBytes.length < valueBytes.length) {
            return false;
        }

        for (uint i = 0; i <= baseBytes.length - valueBytes.length; i++) {
            bool found = true;
            for (uint j = 0; j < valueBytes.length; j++) {
                if (baseBytes[i + j] != valueBytes[j]) {
                    found = false;
                    break;
                }
            }
            if (found) {
                return true;
            }
        }
        return false;
    }
}
```

I use this in my tests. It works for every situation I've thrown at it but I have not unit tested this method itself.

**Comment by johnnyshankman** [comment]
Btw let me know if anything here is unclear. Hopefully pretty straight forward request 🙏  thanks y'all!

Would make a PR myself but I don't have the time this week to dive into the Foundry repo. Hopefully soon.

**Comment by mattsse** [comment]
I think this would be a nice assert to have.

though we probably want this as native cheatcode impl and not implemented in solidity itself.

forge-std/Test.sol then could simply call `vm.assertStringContains`?

**Comment by leovct** [comment]
Hi @zerosnacks, happy to tackle this issue :)
