### ISSUE TITLE
Can we show the custom revert message?

### ISSUE THREAD

**Issue by rickbeeloo** [foundry-rs/foundry#4863]
**Component**
Anvil

**Have you ensured that all of these are up to date?**
Yes just redownloaded all

**What command(s) is the bug in?**
forge cast

**Operating System**
Linux

**Describe the bug**
Just new here so I might be misunderstanding something, but first thanks a lot for building this! The speed is amazing :). 
I have a contract that I deploy on a fork (using `anvil --fork-url ` to properly test it (as it interacts with existing contracts). Then I sent a thousand transactions through the contract using `cast send`. This often gives me messages like:
```
    Transaction: 0xa9f8642e6a769564611cea7ff787d3376e224121991ae3612f3564941cc18d52
    Gas used: 299468
    Error: reverted with custom error: 

    Block Number: 17169631
    Block Hash: 0x90b18ed8be59213823795b5c393a4efcc21902e8797f69089838a6555f4d2460
    Block Time: "Tue, 02 May 2023 06:25:53 +0000"
```
I don't understand why the `Error: reverted with custom error` is empty? 

(P.s. maybe I could do this with `forge` but couldn't see how that would work with a fork + own transaction sequences)

**Comment by mattsse** [comment]
do you have example of the revert code and the abi of the custom error?

**Comment by Evalir** [comment]
Closing, not enough info provided and OP didn't follow up.
