### ISSUE TITLE
feat: add config option to turn off shrinking

### ISSUE THREAD

**Issue by mds1** [foundry-rs/foundry#4867]
### Component

Forge

### Describe the feature you would like

> I am experiencing same issues when running large invariant test suite (bunch of invariants + runs + big depth), would be great to have the option to turn off shrinking. Thank you

_Originally posted by @grandizzy in https://github.com/foundry-rs/foundry/issues/3662#issuecomment-1530975485_

**Comment by grandizzy** [comment]
thanks for tracking this! I made a PR to address this here https://github.com/foundry-rs/foundry/pull/4868

**Comment by mds1** [comment]
Resolved by https://github.com/foundry-rs/foundry/pull/4868
