### ISSUE TITLE
bug(fmt): comment gets moved on next line with a bracket

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/foundry#4872]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ac19482 2023-05-03T00:04:41.398754000Z)

### What command(s) is the bug in?

forge fmt

### Operating System

macOS (Apple Silicon)

### Describe the bug

This:

```solidity
abstract contract PRBProxyPlugin is
    IPRBProxyPlugin, // 1 inherited component
    PRBProxyStorage // 1 inherited component
{ }
```

Gets turned into this:

```solidity
abstract contract PRBProxyPlugin is
    IPRBProxyPlugin, // 1 inherited component
    PRBProxyStorage
{ // 1 inherited component
}
```

**Comment by zerosnacks** [comment]
Unable to reproduce

Now formats as:

```
abstract contract A {}

abstract contract B {}

contract Counter is
    A, // A is a contract
    B // B is a contract
{
    uint256 public number;

    function setNumber(uint256 newNumber) public {
        number = newNumber;
    }

    function increment() public {
        number++;
    }
}
```

Feel free to re-open if you are still experiencing this issue

**Comment by PaulRBerg** [comment]
thank you for knocking out so many of my old issues, @zerosnacks!
