### ISSUE TITLE
OutOfGasError and other unknown tx failures

### ISSUE THREAD

**Issue by antazoey** [foundry-rs/foundry#4877]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e807429 2023-05-04T00:14:49.442476000Z)

### What command(s) is the bug in?

anvil

### Operating System

macOS (Intel)

### Describe the bug

Before a couple days ago, I use max gas in my `gas_limit` when making requests to an Anvil node.
As of lately, I have to subtract a little from it for it to work.

By max gas, this is what I mean: 

```python
block = self.web3.eth.get_block("latest")
return block["gasLimit"]
```

it is the gas limit of the latest block.
I do the same in geth, hardhat, and eth-tester, and anvil before a few day ago.

Now my workaround is this:

```python
block = self.web3.eth.get_block("latest")
return block["gasLimit"] * 1024
```

but I thought you should be aware of teh breakage

**Comment by Evalir** [comment]
cc @mattsse could be related to the anvil regression we saw and fixed with #4861, will investigate

**Comment by antazoey** [comment]
after forcing a gas it likes, i end up getting a different error:

```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Invalid input length', anvil/src/eth/backend/executor.rs:276:77
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by antazoey** [comment]
my full anvil command:

```shell
anvil --port 8545 --mnemonic "test test test test test test test test test test test junk" --accounts 10 --derivation-path "m/44'/60'/0'" --steps-tracing --block-base-fee-per-gas 0
```

then i send a raw transaction:

```python
{'chainId': 31337, 'from': '0x318b469BBa396AEc2C60342F9441be36A1945174', 'gas': 29296, 'nonce': 0, 'value': 0, 'data': b'`\x80`@R4\x80\x15a\x00 ....  <tons of deploy data i am omitting>', 'type': 2, 'maxFeePerGas': 0, 'maxPriorityFeePerGas': 0, 'accessList': []}
```

and then i get a receipt:

```python
{'block_number': 1, 'gas_used': 0, 'logs': [], 'status': 0, 'txn_hash': '0x773caccdb10edd3c230644490541ed51f79d69577a0e47a8ba817c77ad6e8272', 'gas_limit': 29296, 'gas_price': 0}
```

it has a failing status for some reason...

so i attempt to replay it and find a revert reason of some kind....

and i get this error:

```python
ValueError({'code': -32603, 'message': 'EVM error OutOfGas'})
```

i have tried messing with the gas values all sorts of way but i haven't been able to make it happy.
this was working last week. i am not exactly sure where the problem lies. i get other similar oddities in other situations, not sure if everything is the same bug or not

**Comment by Evalir** [comment]
Hey hey! Thanks for the examples, this is really helpful.

Working on the fix: https://github.com/foundry-rs/foundry/pull/4885

**Comment by antazoey** [comment]
I still have 1 slight weird issue that I can work around.
(note was working fine before)

but basically when I replay a failed published txn (using eth call) to derive the failure message, I always get `intrinsic gas too high` **if and only if** i include a `nonce` in the txn params.

**Comment by Evalir** [comment]
Yeah @antazoey this is pretty odd. Let's track this as a separate issue—it might be coming from a different place now (i'll open it as there are a few other people with this comment)
