### ISSUE TITLE
Forge test crashes on minimal repo

### ISSUE THREAD

**Issue by DrakeEvans** [foundry-rs/foundry#4880]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (5753e6a 2023-05-04T19:53:54.938695000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

Reproduction repo: https://github.com/FraxFinance/uni-v3-manipulation-simulator
Install with npm i, update .env file with MAINNET_URL= key
Run forge test

There is only 1 test contract in the repo.  

forge test
[⠒] Compiling...
[⠆] Compiling 18 files with 0.8.19
[⠔] Solc 0.8.19 finished in 2.11s
Compiler run successful with warnings:
Warning (2072): Unused local variable.
  --> test/TestUniswapV3Price.t.sol:31:9:
   |
31 |         uint256 _amountOut = swapRouter.exactInputSingle(params);
   |         ^^^^^^^^^^^^^^^^^^

The application panicked (crashed).
Message:  Unsupported EVM version
Location: cli/src/utils.rs:93

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 9 frames hidden ⋮                               
  10: foundry_cli::cmd::forge::test::TestArgs::execute_tests::ha5dd22ad286d2aa2
      at <unknown source file>:<unknown line>
  11: <foundry_cli::cmd::forge::test::TestArgs as foundry_cli::cmd::utils::Cmd>::run::hb17b3069aeb518ba
      at <unknown source file>:<unknown line>
  12: forge::main::h162db42525d5bd47
      at <unknown source file>:<unknown line>
  13: std::sys_common::backtrace::__rust_begin_short_backtrace::h769714918fe6cdf2
      at <unknown source file>:<unknown line>
  14: std::rt::lang_start::{{closure}}::h7529b0f3940c5e6b
      at <unknown source file>:<unknown line>
  15: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hf2f6b444963da11f
      at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/ops/function.rs:287
  16: std::panicking::try::do_call::h9152231fddd58858
      at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:487
  17: std::panicking::try::hcc27eab3b8ee3cb1
      at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:451
  18: std::panic::catch_unwind::hca546a4311ab9871
      at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panic.rs:140
  19: std::rt::lang_start_internal::{{closure}}::h4e65aa71fe685c85
      at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:148
  20: std::panicking::try::do_call::h61aea55fbdf97fc2
      at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:487
  21: std::panicking::try::hcfc3b62fb8f6215e
      at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:451
  22: std::panic::catch_unwind::h61a201e98b56a743
      at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panic.rs:140
  23: std::rt::lang_start_internal::h91996717d3eb1d2a
      at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/rt.rs:148
  24: _main<unknown>
      at <unknown source file>:<unknown line>
      
      Happy to hop on zoom to debug, find me on telegram @Drakeevans

**Comment by Evalir** [comment]
Hi @DrakeEvans ! Thanks for reporting. This is a very similar issue to #4873 — https://github.com/foundry-rs/foundry/pull/4856 will fix this. In the meanwhile, you can put `evm_version = 'london'` in your `foundry.toml`.

**Comment by Evalir** [comment]
This is fixed by #4856 — closing. Feel free to reopen if this happens again once the new nightly binary is released
