### ISSUE TITLE
Getting `gas required exceeds allowance` while using `forge create`

### ISSUE THREAD

**Issue by tkowalczyk** [foundry-rs/foundry#4882]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (200b3f4 2023-05-05T00:04:08.284562894Z)

### What command(s) is the bug in?

forge create

### Operating System

Linux

### Describe the bug

I am using below command:

```
forge create ./src/SimpleERC.sol:SimpleERC --rpc-url 'https://eth-goerli.g.alchemy.com/v2/'${ALCHEMY_ETH_GOERLI} --private-key ${PRIVATE_KEY} --force --constructor-args "SimpleERC" "SERC"
```

with the simplest possible contract for ERC20 token like below:

```
// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.18;

import "@openzeppelin/contracts/token/ERC20/ERC20.sol";

contract SimpleERC is ERC20 {
    constructor() ERC20("SimpleERC", "SERC") {
        _mint(msg.sender, 100 * 10 ** decimals());
    }
}
```

So I believe this is not related to small amount of ETH on wallet. What it could be?

**Comment by Evalir** [comment]
Hi! Thanks for reporting this.

I think our gas estimation might still be off @mattsse — investigating.
