### ISSUE TITLE
Wrong exit code when using forge test --fail-fast

### ISSUE THREAD

**Issue by MorenaBarboni** [foundry-rs/foundry#4883]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (326a889 2023-05-05T14:34:44.765124800Z)

### What command(s) is the bug in?

forge test --fail-fast

### Operating System

Windows

### Describe the bug

I am running the forge test command with the --fail-fast argument. The tests stop after the first failure as expected. However, the process still exits with code 0 although I'm not using the  --allow-failure argument.

**Comment by Evalir** [comment]
Closed with #5146
