### ISSUE TITLE
chisel 0.1.1 is broken: can't run any command

### ISSUE THREAD

**Issue by stavalfi** [foundry-rs/foundry#4888]
### Component

Chisel

### Have you ensured that all of these are up to date?

- [X] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (3092735 2023-05-06T00:10:49.805815000Z)

### What command(s) is the bug in?

chisel

### Operating System

macOS (Apple Silicon)

### Describe the bug

```
chisel
Welcome to Chisel! Type `!help` to show available commands.
➜ 1+1
Compiler errors:
Error: Invalid EVM version requested.
```

I didn't find any exmple on how to specify custom EVM version or what that is. tried `0.8.0` didn't work.

**Comment by Evalir** [comment]
Hey! Could you try installing a recent Solidity version, like 0.8.19, and trying again? When I try to reproduce it goes smoothly provided I've got a newish compiler version.

**Comment by stavalfi** [comment]
Hi @Evalir! how can i do that? what is the command for that?

**Comment by Evalir** [comment]
For this, you could use [svm-rs](https://github.com/roynalnaruto/svm-rs).

Also, try this out: `chisel --evm-version "shanghai"

**Comment by stavalfi** [comment]
```
chisel --version
chisel 0.1.1 (3092735 2023-05-06T00:11:33.551414000Z)


chisel --evm-version "london"
Welcome to Chisel! Type `!help` to show available commands.
➜ 1+1
Compiler errors:
Error: Invalid EVM version requested.
```

**Comment by 0xCalibur** [comment]
Having the same issue as well
<img width="471" alt="image" src="https://user-images.githubusercontent.com/92554750/236644074-e1ee2776-1352-4400-8c4b-e46af65d39cc.png">

Apple M1 Max
macos 13.3.1

**Comment by alexotsu** [comment]
Same for me.
Chisel version: chisel 0.1.1 (866f6ed 2023-05-07T00:06:37.860996000Z)

Apple M2
macOS 13.3.1

**Comment by Hicham010** [comment]
Same for me as well

MacBook Pro M1

<img width="420" alt="Screenshot 2023-05-07 at 18 44 31" src="https://user-images.githubusercontent.com/47334105/236690927-3f83c9bc-ce9d-416f-b421-f392a99a02eb.png">

**Comment by 77abe77** [comment]
I am still getting this error on `chisel 0.1.1 (f3c20d5 2023-05-12T00:07:55.652494000Z)`

**Comment by plotchy** [comment]
Had this error on a new pc, realized it was due to not having solc 0.8.19 installed

putting basic svm instructions here
```
cargo install svm-rs
svm install 0.8.19
```

**Comment by Hicham010** [comment]
> Had this error on a new pc, realized it was due to not having solc 0.8.19 installed
> 
> putting basic svm instructions here
> 
> ```
> cargo install svm-rs
> svm install 0.8.19
> ```

This fixed it for me. Thanks!
