### ISSUE TITLE
Anvil should gracefully deal with the upstream fork rate limits

### ISSUE THREAD

**Issue by miohtama** [foundry-rs/foundry#4894]
### Component

Anvil

### Describe the feature you would like

Currently, when using Anvil with quicknode.com hard fork Anvil may crash:

```
stderr: thread 'main' panicked at 'Failed to get fork block number: JsonRpcClientError(SerdeJson { err: Error("unknown field `code, expected one of id, jsonrpc, result, error, params, method`", line: 1, column: 7), text: "{\"code\":-32007,\"message\":\"100/second request limit reached - reduce calls per second or upgrade your account at quicknode.com\"}" })', /home/runner/work/foundry/foundry/anvil/src/config.rs:816:30
```

### Additional context

This could be dealt with

- Anvil allowing to set the rate limit to the upstream, e.g. by a command line option `--force-rate-limit 100/s` 
- Correctly throttle on Quicknode.com error if should throttling logic already exists in Anvil, instead of panic

**Comment by grandizzy** [comment]
@miohtama there was a PR merged with quicknode retry improvements, can you check if panic is still reproducible with latest anvil? thank you

**Comment by mattsse** [comment]
@grandizzy this issue is outdated and can be closed, added test for good measure
