### ISSUE TITLE
Direct import in contract fails (https:// import)

### ISSUE THREAD

**Issue by milaabl** [foundry-rs/foundry#4899]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

foundry 4.7.0 (forge 0.2.0)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

Currently when I try to import a specific .sol file from a remote address I get errors:

```
//SPDX-License-Identifier: Unlicense
pragma solidity >=0.8.13;

import "https://gist.githubusercontent.com/JofArnold/bf2c4a094fcdd4aee2f52983c7714de8/raw/f8ca925324b3bf53354c84d47d080e6a87439233/BoredApeYachtClub.sol";

// TODO: Implement all user stories and one of the feature request
contract Game {
    uint256 public x;

    constructor() {
        x = 4;
    }
}

```

```
Compiler run failed:
Error (6275): Source "https://gist.githubusercontent.com/JofArnold/bf2c4a094fcdd4aee2f52983c7714de8/raw/f8ca925324b3bf53354c84d47d080e6a87439233/BoredApeYachtClub.sol" not found: File not found. Searched the following locations: "/home/ubuntu/solidity-exercise".
```

It treats the remote address like a local import.

Same code works in Remix, as well as with Hardhat/Truffle.

I may be mistaken, please let me know if there's any workaround for this.

**Comment by Evalir** [comment]
This is not supported by Foundry, as we do dep management using git. No real plans to handle this until after 1.0, so closing unless somebody objects.
