### ISSUE TITLE
storage kept hot when should be cold

### ISSUE THREAD

**Issue by internetmoneydev** [foundry-rs/foundry#4900]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8adf428 2023-05-08T00:12:01.390438000Z)

### Operating System

macOS (Apple Silicon)

### Describe the bug

SLOAD/SSTOREs are hot after their first load in the test. I would think that hitting a contract would be a signal to invalidate the storage cache (make all storage slots cold) since that would indicate a separate transaction. However, what happens is SLOAD/SSTOREs are kept hot over the course of a test, presumably because it is a single function. Is there a way to work around this, or is this a bug?

**Comment by internetmoneydev** [comment]
i have tried moving the block timestamp forward to see if that helps, but it does not seem to

**Comment by radeksvarz** [comment]
Hope to have the vm cheatcode for warming/cooling for proper simulations.

**Comment by mds1** [comment]
Right, slots are warm the whole time since each test is a single transaction. There is an issue for a `vm.cool` cheatcode here https://github.com/foundry-rs/foundry/issues/1340

**Comment by zerosnacks** [comment]
`vm.cool` has been added here: https://github.com/foundry-rs/foundry/pull/5830

We also have the `--isolate` mode for improved gas accuracy to run a test in an isolated environment
