### ISSUE TITLE
Enable way to browse Foundry book locally

### ISSUE THREAD

**Issue by misirov** [foundry-rs/foundry#4902]
### Component

Foundryup

### Describe the feature you would like

```bash
fundryup docs --book
```
Allow users to open `https://book.getfoundry.sh/` locally.

### Additional context

You are programming and need to pull up the `book.getfoundry.sh` docs, but internet access is either limited or not available. What a bummer!
But no problemo! The same way you use `rustup doc --book` to browse rust docs locally, now you can run `foundryup doc --book` and browse the foundry documentation offline! 
This is the true definition of happiness

**Comment by zerosnacks** [comment]
Thanks for your suggestion!

For now the most practical workaround is to simply keep a version of https://github.com/foundry-rs/book locally and run with `mdbook serve`

Requires https://github.com/foundry-rs/foundry/issues/1158

**Comment by zerosnacks** [comment]
Marking as `not planned` for the time being, may be possible some day when `foundryup` is written in Rust
