### ISSUE TITLE
Deploy to Optimism via script fails after incorrect gas estimation

### ISSUE THREAD

**Issue by spengrah** [foundry-rs/foundry#4903]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8adf428 2023-05-08T00:04:45.691256000Z)

### What command(s) is the bug in?

forge script script/MyScript.s.sol -f optimism --broadcast --verify

### Operating System

macOS (Apple Silicon)

### Describe the bug

I have a script that deploys an implementation contract and a clone factory. I'm currently attempting to run the script to deploy to Optimism. Simulation run works just fine, but when broadcasting I end up with a `code -32000 [...] insufficient funds for gas * price + value` error.

I have confirmed that all my wallet and rpc configs are correct (I'm able to broadcast a simple eth transfer on optimism, for example).

As you can see in the screenshot below, the deployer balance exceeds the estimated amount required value, but the broadcast is still failing. It appears that the cost estimation is way too low, likely because **it excludes the L1 gas component that is part of an L2 transaction**.

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/13247381/236910952-4b13efe0-466a-42e9-8892-c2ed79c0908c.png">

**Comment by backseats** [comment]
I am experiencing something similar, deploying to mainnet. Wallet has triple the ETH in it relative to the estimate

`forge 0.2.0 (dedc31e 2023-04-24T00:12:05.706154000Z)`

Command: `forge script script/MultiMerkleMinterV1.s.sol:MultiMerkleMinterV1Script --rpc-url $MAINNET_RPC_URL --chain-id 1 --private-key $MAINNET_PRIVATE_KEY --broadcast --verify -vvvv`

macOS (Apple Silicon)

```
$ forge script script/MultiMerkleMinterV1.s.sol:MultiMerkleMinterV1Script --rpc-url $MAINNET_RPC_URL --chain-id 1 --private-key $MAINNET_PRIVATE_KEY --broadcast --verify -vvvv
[⠰] Compiling...
No files changed, compilation skipped
Traces:
  [2296694] MultiMerkleMinterV1Script::run() 
    ├─ [0] VM::envUint(PRIVATE_KEY) [staticcall]
    │   └─ ← <env var value>
    ├─ [0] VM::startBroadcast(<pk>) 
    │   └─ ← ()
    ├─ [2237130] → new MultiMerkleMinterV1@0x3B718a2272216343c4E63809276317E8295e453B
    │   ├─ [8087] GenArt721CoreV3_Engine::getPrimaryRevenueSplits(0, 0) 
    │   │   └─ ← 0, 0xE7bEB4Af9Da9b567778278F863Ed475212589526, 0, 0xFdc45dae01d1F9EF394b33c227BA9489795d148B, 0, 0x0000000000000000000000000000000000000000, 0, 0x0000000000000000000000000000000000000000
    │   ├─ [326] MinterFilterV1::genArt721CoreAddress() 
    │   │   └─ ← GenArt721CoreV3_Engine: [0x6DdefE5DB20D79EC718A8960177bEB388f7EbB8d]
    │   └─ ← 10987 bytes of code
    ├─ [0] VM::stopBroadcast() 
    │   └─ ← ()
    └─ ← ()


Script ran successfully.

## Setting up (1) EVMs.
==========================
Simulated On-chain Traces:

  [2471622] → new MultiMerkleMinterV1@0x3B718a2272216343c4E63809276317E8295e453B
    ├─ [8087] GenArt721CoreV3_Engine::getPrimaryRevenueSplits(0, 0) 
    │   └─ ← 0, 0xE7bEB4Af9Da9b567778278F863Ed475212589526, 0, 0xFdc45dae01d1F9EF394b33c227BA9489795d148B, 0, 0x0000000000000000000000000000000000000000, 0, 0x0000000000000000000000000000000000000000
    ├─ [326] MinterFilterV1::genArt721CoreAddress() 
    │   └─ ← GenArt721CoreV3_Engine: [0x6DdefE5DB20D79EC718A8960177bEB388f7EbB8d]
    └─ ← 10987 bytes of code


==========================

Chain 1

Estimated gas price: 139.159975345 gwei

Estimated total gas used for script: 3213108

Estimated amount required: 0.44713603006082226 ETH

==========================

###
Finding wallets for all the necessary addresses...
##
Sending transactions [0 - 0].

Transactions saved to: /Users/backseats/tender/broadcast/MultiMerkleMinterV1.s.sol/1/run-latest.json

Error: 
(code: -32000, message: insufficient funds for gas * price + value, data: None)
```

**Comment by simplyoptimistic** [comment]
> it excludes the L1 gas component that is part of an L2 transaction.

I also had this issue. Given that the majority of the gas consumed by a L2 transaction on Optimism (at this stage) is in the L1 gas component, the gas estimation functionality is fairly useless on Optimism. 

I have also noticed that it overestimates the gas price unless you use --legacy (perhaps related to this issue https://github.com/foundry-rs/foundry/issues/4547).

Optimism has described [here](https://community.optimism.io/docs/developers/build/transaction-fees/#the-l1-data-fee) how the L1 fee could be estimated, by reading from the gas oracle contract, so perhaps that could be a way foundry could address this issue.

**Comment by PaulRBerg** [comment]
Just bumped into this issue as well, but when trying to deploy to Arbitrum. My account is funded with 0.04 ETH, but the gas estimation reports (incorrectly) that I need ~0.0821 ETH instead:

```text
## Setting up (1) EVMs.

==========================

Chain 42161

Estimated gas price: 3.2 gwei

Estimated total gas used for script: 25681451

Estimated amount required: 0.0821806432 ETH
```

This estimation is incorrect. I deployed bigger contracts yesterday and they cost much less than that.

**Comment by PaulRBerg** [comment]
I ended up having to deploy via Remix + MetaMask because of this bug 😬

**Comment by ctate** [comment]
> Just bumped into this issue as well, but when trying to deploy to Arbitrum. My account is funded with 0.04 ETH, but the gas estimation reports (incorrectly) that I need ~0.0821 ETH instead:
> 
> ```
> ## Setting up (1) EVMs.
> 
> ==========================
> 
> Chain 42161
> 
> Estimated gas price: 3.2 gwei
> 
> Estimated total gas used for script: 25681451
> 
> Estimated amount required: 0.0821806432 ETH
> ```
> 
> This estimation is wrong. I deployed bigger contracts yesterday and they cost much less than that.

I’m having the same issue mentioned here via Arbitrum

**Comment by PaulRBerg** [comment]
@ctate see a neat workaround on Twitter: [Is it possible to send CREATE transactions via MetaMask (without using Remix)?](https://twitter.com/PaulRBerg/status/1676258597003460609).

**Comment by rachel-bousfield** [comment]
@PaulRBerg your issue is likely that the L1 basefee increased since your previous contract deployments.

On Arbitrum gas estimation fluctuates with the L1 basefee, since you pay for the cost of posting calldata to L1 with L2 gas. Contract deployments use a lot of calldata so estimates are especially sensitive to changes.

Your best bet is to estimate right before deployment.

**Comment by klkvr** [comment]
FIxed by https://github.com/foundry-rs/foundry/pull/7106
