### ISSUE TITLE
Bytecode not getting generated anymore

### ISSUE THREAD

**Issue by utx0** [foundry-rs/foundry#4906]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8adf428 2023-05-08T00:10:49.224701699Z)

### What command(s) is the bug in?

forge build --extra-output-files bin

### Operating System

Linux

### Describe the bug

Bytecode has stopped getting generated in the `./out` directory with this command: `forge build --extra-output-files bin` cant seam to find if this has changed to something else.

**Comment by mattsse** [comment]
I wasn't able to reproduce this

```
forge build --extra-output-files bin
```

```
ls out/Counter.sol                                                                                                                                    
Counter.bin     Counter.json
```

**Comment by Evalir** [comment]
Closing, not reproducible
