### ISSUE TITLE
Add function selector vanity miner

### ISSUE THREAD

**Issue by eugenioclrc** [foundry-rs/foundry#4907]
### Component

Cast

### Describe the feature you would like

I would love to have a vanity selector mining in cast, here is a sample;
https://github.com/kadenzipfel/function-selector-miner

### Additional context

https://github.com/kadenzipfel/function-selector-miner

**Comment by eugenioclrc** [comment]
@gakonst i would love to code this feature

**Comment by mds1** [comment]
I've assigned it to you, but let's spec it out a bit first before getting a PR open. What's your proposed UX/syntax?

**Comment by kadenzipfel** [comment]
@eugenioclrc it's already been added, sorry! https://github.com/foundry-rs/foundry/pull/4705

**Comment by mds1** [comment]
Closing as completed by https://github.com/foundry-rs/foundry/pull/4705
