### ISSUE TITLE
`cast` fails to decode calldata blob

### ISSUE THREAD

**Issue by jmcph4** [foundry-rs/foundry#4910]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (7bba788 2023-05-10T00:07:19.521959963Z)

### What command(s) is the bug in?

cast --abi-decode "(uint112,uint112,uint32)" 0x645aff8b000000000004e7bf82165aab10e90060379f76d5b5f22cdfa046a9a5

### Operating System

Linux

### Describe the bug

```
$ cast --abi-decode "(uint112,uint112,uint32)" 0x645aff8b000000000004e7bf82165aab10e90060379f76d5b5f22cdfa046a9a5
The application panicked (crashed).
Message:  could not convert (uint112,uint112,uint32) to function
Location: common/src/abi.rs:230

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Aborted
$ RUST_BACKTRACE=full cast --abi-decode "(uint112,uint112,uint32)" 0x645aff8b000000000004e7bf82165aab10e90060379f76d5b5f22cdfa046a9a5
The application panicked (crashed).
Message:  could not convert (uint112,uint112,uint32) to function
Location: common/src/abi.rs:230

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: __libc_start_main<unknown>
      at ./csu/../csu/libc-start.c:308

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Aborted
```

**Comment by CalabashSquash** [comment]
`cast --abi-decode` does not decode calldata by default. To decode calldata, you need to include the `--input` flag. Also, the signature provided should be a full function signature, which I think is the specific problem that causes the "Message:  could not convert (uint112,uint112,uint32) to function" message. I also don't believe that calldata blob is valid. It would need to include 3*32 = 96 bytes but only seems to include 28.

**Comment by jmcph4** [comment]
Sorry, forgot about this and only just re-encountered it!

> I also don't believe that calldata blob is valid.

Yeah, if I recall correctly I accidentally posted a memory region (a UniV2 0th slot I think), not actual calldata.

The new case I've stumbled upon is much the same:

```
$ cast --version
cast 0.2.0 (8f20631 2023-07-10T00:04:29.812703538Z)
$ cast ad --input "(bytes,address)" 0x1494ca1f11d487c2bbe4543e90080aeba4ba3c2b000bb8c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2
The application panicked (crashed).
Message:  could not convert (bytes,address) to function
Location: common/src/abi.rs:251

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Aborted
```

Which, as you point out, is the same condition more or less:

https://github.com/foundry-rs/foundry/blob/8f20631932be893c3c5e4835077f8a722e14c037/common/src/abi.rs#L251

It's pretty minor in the grand scheme of things; `cast` should just handle the error more gracefully than panicking (especially when there's a prompt for the user to file a bug report). I only kept this going in the spirit of the recent [bug drive](https://twitter.com/gakonst/status/1680145708676939778).

**Comment by keroro520** [comment]
According to the error message "could not convert (bytes,address) to function",
I think the input should include the function name, such as `cast ad --input 'xxx(bytes,address)' <calldata>`, `xxx` is the function name.

**Comment by jmcph4** [comment]
> According to the error message "could not convert (bytes,address) to function", I think the input should include the function name, such as `cast ad --input 'xxx(bytes,address)' <calldata>`, `xxx` is the function name. @jmcph4

@keroro520 Yeah definitely -- it's more the explicit panic, that's all. Pretty minor bug in the grand scheme of things.

**Comment by DaniPopes** [comment]
Current error:

```
$ cast ad --input "(bytes,address)" 0x1494ca1f11d487c2bbe4543e90080aeba4ba3c2b000bb8c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2
Error: 
could not parse function signature

Context:
- parser error:
(bytes,address)
^
```
