### ISSUE TITLE
Can cast sig support 'Struct Encoding' by default  or can we have a single sub-command for `Struct Encoding`

### ISSUE THREAD

**Issue by nzhl** [foundry-rs/foundry#4911]
### Component

Cast

### Describe the feature you would like

Saying I have a function that takes a ﻿struct type as an argument.

```solidity
  struct NestedStruct {
      string name;
      uint8 age;
   }
   struct ComplicatedStruct {
       NestedStructA a;
   }

    function f(
        ComplicatedStruct memory data,
        uint256 tokenId
    );
```

For now if i want  calculated the function selector of function f. What i need is to first `Struct Encoding` ComplicatedStruct first, according to the [doc](https://book.getfoundry.sh/reference/cast/cast-sig)

<img width="842" alt="image" src="https://github.com/foundry-rs/foundry/assets/16397293/0a1308b3-0608-4867-ae71-d2facac4d4c8">

would be appretiate if we can support  'Struct Encoding' by default, for example we can do the following direct to get selector back.
```
cast sig '
  struct NestedStruct {
      string name;
      uint8 age;
   }
   struct ComplicatedStruct {
       NestedStructA a;
   }

    function f(
        ComplicatedStruct memory data,
        uint256 tokenId
    );
'

```

**Comment by zerosnacks** [comment]
For local contracts we already support: `forge inspect CONTRACT_NAME methodIdentifiers` 

```
{
  "f(((string,uint8)),uint256)": "c7d90969",
}
```

With `forge clone`: https://github.com/foundry-rs/foundry/pull/7576 you can pull in sources

Marking as `not planned`
