### ISSUE TITLE
Compiling...The application panicked (crashed).

### ISSUE THREAD

**Issue by pavankv241** [foundry-rs/foundry#4913]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (b28119b 2022-11-23T00:08:30.903618812Z)

### What command(s) is the bug in?

forge test  --match-path test/Time.t.sol -vvvv 

### Operating System

Linux

### Describe the bug

While testing simple file Below error occurring :-
  ```
forge test  --match-path test/Time.t.sol -vvvv                                 1 ⚙
[⠃] Compiling...The application panicked (crashed).
Message:  checksum not found
Location: /home/runner/.cargo/git/checkouts/ethers-rs-c3a7c0a0ae0fe6be/c17c0c3/ethers-solc/src/compile/mod.rs:463

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
zsh: abort      forge test --match-path test/Time.t.sol -vvvv
```

**Comment by DevABDee** [comment]
facing the same issue

**Comment by pavankv241** [comment]
> facing the same issue

Resolve by changing directory

**Comment by mattsse** [comment]
> forge 0.2.0 (https://github.com/foundry-rs/foundry/commit/b28119b56d7dd18c268a471167a0c547c301c13e 2022-11-23T00:08:30.903618812Z)

this is likely related to new 0.8.20 release,
please try after upgrading forge

**Comment by DevABDee** [comment]
> > forge 0.2.0 ([b28119b](https://github.com/foundry-rs/foundry/commit/b28119b56d7dd18c268a471167a0c547c301c13e) 2022-11-23T00:08:30.903618812Z)
> 
> this is likely related to new 0.8.20 release, please try after upgrading forge

Hey, pls tell me the command to update foundry/forge. Thanks

**Comment by pavankv241** [comment]
I just deleted cloned repo and try to clone in different directory like /home/Desktop that's all issue solved for me and try to update forge also.

**Comment by twcctop** [comment]
in `foundry.toml` config file:  solc_version = "0.8.19"
This works for me

**Comment by Evalir** [comment]
Closing as this has been fixed.

**Comment by pavankv241** [comment]
> in `foundry.toml` config file: solc_version = "0.8.19" This works for me

Thanks it's working for me
