### ISSUE TITLE
Gas limit in unit tests

### ISSUE THREAD

**Issue by storojs72** [foundry-rs/foundry#4914]
### Component

Forge

### Describe the feature you would like

Is there any particular reasons of having upper limit for gas usage in unit tests (currently it seems to be 18446744073709551615)? In my understanding, this limit forces developer to think over proper design of the smart contract, because there is no sense to have a contract that can't be deployed to the network. But it looks to me that sometimes while initial contract development, it is useful to forget about deployment requirements and focus just on actual logic - let's consider development of some complex cryptographic algorithm for example.

What about having gas limit enabled by default and adding flag (like `allowUnlimitedGasUsage = true`) used specifically in unit tests for disabling this limitation?

**Comment by Evalir** [comment]
Hmmm this seems to be `U64_MAX`? cc @mattsse i think this smells like a conversion bug somewhere, wdyt?

**Comment by Evalir** [comment]
Closing as stale—big test users don't seem to report the same issue, and can't reproduce. Please feel free to reopen if this is still an issue!
