### ISSUE TITLE
Broken functionality for downloading source code cast etherscan-source for multiple networks

### ISSUE THREAD

**Issue by semyonnyzhnykprofitwork** [foundry-rs/foundry#4919]
### Component

Cast

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

7bba788 2023-05-10T00:07:19.521959963Z

### What command(s) is the bug in?

cast etherscan-source -c 100

### Operating System

Linux

### Describe the bug

Hello

some networks support for downloading source code is broken, but there is list of supported networks

i found that cast supports next networks
[possible values: mainnet, morden, ropsten, rinkeby, goerli, kovan, sepolia, optimism, optimism-kovan, optimism-goerli, arbitrum, arbitrum-testnet, arbitrum-goerli, arbitrum-nova, cronos, cronos-testnet, rsk, bsc, bsc-testnet, poa, sokol, scroll-alpha-testnet, metis, xdai, polygon, mumbai, polygon-zkevm, polygon-zkevm-testnet, fantom, fantom-testnet, moonbeam, moonbeam-dev, moonriver, moonbase, dev, anvil-hardhat, evmos, evmos-testnet, chiado, oasis, emerald, emerald-testnet, filecoin-mainnet, filecoin-hyperspace-testnet, avalanche, fuji, celo, celo-alfajores, celo-baklava, aurora, aurora-testnet, canto, canto-testnet, boba, base-goerli, zksync]

For example

for network gnosisscan with 100 ChainID 
when i type
cast etherscan-source -c 100 -e DEU5I6AYJGDK6ATQNZ6NKC2JDRKE2ETANJ -d 0xa6038721c3d2c060f97a413bda554f815d4c34e0 0xa6038721c3d2c060f97a413bda554f815d4c34e0

it returns 

Error:
Received error response: status=0,message=Something went wrong., result=None

for network celoscan with 42220 ChainID 
when i type
cast etherscan-source -c 42220 -e TZQQMNIMGMEFT1673FWE8RPF5U584Y5MZK -d 0x7162c4651b77a7b261674f2f5b30d6053c2b6223 0x7162c4651b77a7b261674f2f5b30d6053c2b6223

it returns 

2023-05-10T19:42:50.079459Z ERROR etherscan: Failed to deserialize response: data did not match any variant of untagged enum ResponseData res="{\"message\":\"OK\",\"result\":[{\"Address\":\"0x7162c4651b77a7b261674f2f5b30d6053c2b6223\"}],\"status\":\"1\"}"
Error:
data did not match any variant of untagged enum ResponseData

but in https://github.com/gakonst/ethers-rs
there is Celo Support

for network aurorascan with 1313161554 ChainID 
when i type

cast etherscan-source -c 1313161554 -e BKTEQA9CP5MUIXB3WHC9TXWKBUQEXDDNXS -d 0xd5f2210d0bcba06a8c757f160ff3b6ca6cf570f7 0xd5f2210d0bcba06a8c757f160ff3b6ca6cf570f7

it returns

2023-05-10T19:31:01.922062Z ERROR rustls::conn: TLS alert received: AlertMessagePayload {
    level: Fatal,
    description: InternalError,
}
Error:
error sending request for url (https://api.aurorascan.dev/api/?apikey=BKTEQA9CP5MUIXB3WHC9TXWKBUQEXDDNXS&module=contract&action=getsourcecode&address=0xd5f2210d0bcba06a8c757f160ff3b6ca6cf570f7): error trying to connect: received fatal alert: InternalError

Context:
- Error #0: error trying to connect: received fatal alert: InternalError
- Error #1: received fatal alert: InternalError

for network metis with 1088 ChainID 
when i type

cast etherscan-source -c 1088 -e BKTEQA9CP5MUIXB3WHC9TXWKBUQEXDDNXS -d 0xc73edcb49095a3a3ac53999f76d6712b2f59f316 0xc73edcb49095a3a3ac53999f76d6712b2f59f316

it returns

Error:
Received error response: status=0,message=Something went wrong., result=None

I found bug in gnosisscan, celoscan, aurorascan, metis, but there can be bugs in other networks

please, can you fix bug in this 4 networks to download source code?

thank you very much

**Comment by zerosnacks** [comment]
Hi @semyonnyzhnykprofitwork thanks for raising this. Would you be able to report these issues separately in https://github.com/alloy-rs/chains/issues?. This is unfortunately outside of the scope of Foundry.
