### ISSUE TITLE
refactor foundry-evm

### ISSUE THREAD

**Issue by DaniPopes** [foundry-rs/foundry#4928]
The `foundry-evm` crate is massive. Compiling it takes more than 4 seconds on simple incremental `cargo check` builds (which goes to 7 or 8 seconds including `rust-analyzer`), and over 30 seconds on optimized builds.

Roughly 2 to 3 seconds are spent on each new build on just the `abigen!` macro invocations, which is most of the time spent in debug checking (see [`-Zprofile-self`](https://blog.rust-lang.org/inside-rust/2020/02/25/intro-rustc-self-profile.html)). Separating these into their own crate would mean they would only need to get expanded once, and much earlier in the build since they only require basic ethers types.

Some other ideas:
- further split off from the crate `foundry-cheatcodes` or `foundry-inspector`. Also provides a clearer way to contribute to cheatcodes, and could help with tests.
  - Maybe derive the cheatcodes bindings by compiling the Solidity interface in a build script? Less maintenance burden.
- use `ethers-*` sub-crates instead of `ethers`
- merge `utils.rs`, `decode.rs`, `error.rs` into `foundry-utils`
- remove `hashbrown` dependency and just use `std::collections`, because they're the same, minus the hasher. This can be imported separately.
- remove `ethers-solc` dependency to allow compilation to start earlier from as many crates as possible. Compiling `ethers-solc` is a major bottleneck due to its huge size and its dependencies `lalrpop` -> `solang-parser`.
Its utils can be vendored separately, and everything else can go into `foundry-solc`. Maybe one day in the future we'll also be able to have a language-agnostic backend too, and this certainly helps towards it.

As we add more crates, we should also consider to flatten the project structure into a "crates/" directory.

**Comment by mattsse** [comment]
yes!!!

> further split off from the crate foundry-cheatcodes or foundry-inspector. Also provides a clearer way to contribute to cheatcodes, and could help with tests.

100%

> As we add more crates, we should also consider to flatten the project structure into a "crates/" directory.

supportive

**Comment by Evalir** [comment]
Closeable? @DaniPopes
