### ISSUE TITLE
Failed to install solc 0.8.20: Unknown version provided

### ISSUE THREAD

**Issue by enginer** [foundry-rs/foundry#4933]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (f3c20d5 2023-05-12T00:11:18.720897000Z)

### What command(s) is the bug in?

forge test -vvv --fork-url $MY_RPC_URL

### Operating System

macOS (Apple Silicon)

### Describe the bug

After command `forge test -vvv --fork-url $MY_RPC_URL`

```
[⠊] Compiling...
[⠘] Installing solc version 0.8.20
[⠃] Failed to install solc 0.8.20: Unknown version provided
Error: 
Unknown version provided
```

**Comment by mattsse** [comment]
ref https://github.com/roynalnaruto/svm-rs/issues/84

**Comment by enginer** [comment]
How to downgrade guys, I do not need this version of solidity?

**Comment by enginer** [comment]
fixed! I just missed this warning

`warning: libusb not found. You may need to install it manually on MacOS via Homebrew (brew install libusb).`

**Comment by PaulRBerg** [comment]
@enginer See `solc` in https://github.com/foundry-rs/foundry/tree/58a272997516046fd745f4b3c37f91d0eb113358/config#foundrytoml

**Comment by 0xCourtney** [comment]
I had the same issue with forge 0.2.0 (06f7c9c 2023-03-18T00:16:11.192812Z). Installing forge 0.2.0 (31fcf5a 2023-05-19T00:10:33.861185000Z) resolved it.

**Comment by Evalir** [comment]
@enginer this should've been fixed recently—could you `foundyup` and let me know if this is solved?

**Comment by lukaracki** [comment]
I had the same issue and can confirm it's solved after `foundyup` (for me).

**Comment by Evalir** [comment]
Fixed with https://github.com/foundry-rs/foundry/pull/4975

**Comment by ro61zzy** [comment]
`foundryup` works

**Comment by dhanesh24g** [comment]
> I had the same issue and can confirm it's solved after `foundyup` (for me).

Same for me as well !
