### ISSUE TITLE
In Chisel memory and stack dumps break for assembly block ending with `let`

### ISSUE THREAD

**Issue by Sabnock01** [foundry-rs/foundry#4938]
### Component

Chisel

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

chisel 0.1.1 (58a2729 2023-05-15T00:04:42.785499234Z)

### Operating System

Linux

### Describe the bug

When inputting the following subsection of [LibString.sol](https://github.com/Vectorized/solady/blob/2b33744067c2afa74a6ee364004e99035cae692e/src/utils/LibString.sol#L27) into Chisel, memory `!md` and stack `!sd` dumps are not functional. 

This appears to happen any time a variable is declared in the `run` function but not initialized where `!md` and `!sd` will report erroneously that the function is empty. 

![image](https://github.com/foundry-rs/foundry/assets/24715302/42674fc9-041c-4ddd-a772-d462f017aadb)

**Comment by Sabnock01** [comment]
This appears to happen any time an assembly block ends with a `let` statement. 

A workaround I've found is to declare all variables externally and simply remove the `let` keywords from the block.

**Comment by zerosnacks** [comment]
Able to reproduce with given setup

```
chisel
uint256 value = 12345;
string memory str;
assembly {
str := add(mload(0x40), 0x80)
mstore(0x40, add(str, 0x20))
mstore(str, 0)
let end := str
}
```
