### ISSUE TITLE
Release checksums

### ISSUE THREAD

**Issue by onbjerg** [foundry-rs/foundry#495]
:lock: We should really checksum our releases. Requires a change in the CI and (preferably also) `foundryup`

**Comment by brooklynbagel** [comment]
If this is a good first issue it's something I can taking a crack at.

**Comment by lucas-manuel** [comment]
Close-able? @mds1

**Comment by mds1** [comment]
I don't think we currently do this? cc @Evalir

**Comment by Evalir** [comment]
no i don't think we do—could probably be solved along with #494

**Comment by mds1** [comment]
good point, let's dedupe the two, I'll close this one
