### ISSUE TITLE
bug(forge): incompatible evm version & solc versions are accepted

### ISSUE THREAD

**Issue by Evalir** [foundry-rs/foundry#4954]
### Component

Forge

### Describe the bug

Right now, we have no validation regarding the combination of EVM version and solc version set. And if we auto detect the solidity version, it seems we don't take into account the EVM version as well. While this wasn't an issue for quite a while, this is bound to cause an incredible amount of headaches going forward with 2 different EVM versions being released in the span of a year (Paris and Shanghai).

If the solc version is specified, we should:
- If the EVM version is also set, validate that the combination is compatible.
- If the EVM version is not set, then use an appropiate evm version.

If the solc version is autodetected:
- We should ensure that the EVM version set is compatible with the autodetected version, and if not, use a compatible one (I'm open to erroring here @mattsse but i think the whole point of autodetection is for people to not have to care about this)

**Comment by mattsse** [comment]
> If the EVM version is not set, then use an appropiate evm version.
If the solc version is autodetected:

ideally we emit a warning here

**Comment by lucas-manuel** [comment]
Agreed that warning would be good here.
