### ISSUE TITLE
feat(forge): retries and timeouts for fork testing

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/foundry#4958]
### Component

Forge

### Describe the feature you would like

https://github.com/foundry-rs/foundry/pull/2918 added support for retries and timeouts in Anvil, but these features don't seem to be available in Forge when fork testing, e.g. when using the [`createSelectFork`](https://book.getfoundry.sh/cheatcodes/create-select-fork) cheat.

It should ideally be possible to specify the number of retries and the timeout via the CLI or `foundry.toml`.

### Additional context

Alchemy's docs on retries: https://docs.alchemy.com/reference/throughput#retries.

**Comment by zerosnacks** [comment]
Looks like we are supporting this as of https://github.com/foundry-rs/foundry/pull/6582/files + https://github.com/foundry-rs/foundry/issues/6532

The syntax for `foundry.toml` looks like this

```
[rpc_endpoints]
mainnet = { endpoint = "${_CONFIG_MAINNET}", retries = 3, retry_backoff = 1000, compute_units_per_second = 1000 }
```

cc @mattsse

**Comment by mattsse** [comment]
yeah this is also uses the regular retry provider now
