### ISSUE TITLE
Multi-Library verification issue

### ISSUE THREAD

**Issue by riordant** [foundry-rs/foundry#4971]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

`forge 0.2.0 (db96393 2023-05-11T00:05:59.668094030Z)`

### What command(s) is the bug in?

`forge verify-contract`, `forge script --verify ...`

### Operating System

Linux

### Describe the bug

Hi,
I am getting an issue with verifying libraries that also contain libraries.
Here is the failure output:

```
❯ forge verify-contract --chain-id 42161  --watch ${CONTRACT_ADDRESS} src/lib/FeeIntegral.sol:FeeIntegralLib --etherscan-api-key ${ETHERSCAN_API_KEY}

Start verifying contract `0x2d4d37de64a7877260469ec14bd13eb57729d028` deployed on arbitrum

Submitting verification for [src/lib/FeeIntegral.sol:FeeIntegralLib] "0x2d4d37De64a7877260469ec14bd13eB57729D028".
Submitted contract for verification:
        Response: `OK`
        GUID: `hmfm5dmj5uzkkv1jhvghbhxatpq6ekfqyajxpdkskx35p38r1g`
        URL:
        https://arbiscan.io/address/0x2d4d37de64a7877260469ec14bd13eb57729d028
Contract verification status:
Response: `NOTOK`
Details: `Pending in queue`
Contract verification status:
Response: `NOTOK`
Details: `Fail - Unable to verify. Please check for missing Library or invalid name (i.e names are case senstive). Library was required but suitable match not found`
Contract failed to verify.
```
This library (`0x2d4d37de64a7877260469ec14bd13eb57729d028`), internally links this library: `0x1c0dbe0986a831f36ee2058cb4a3d0b95f93074a`.

Initially, I attempted to verify through a deployment script, with `forge script Deploy --verify --etherscan-api-key arbitrum`. Following deployment, the first error message showed this:

```
We haven't found any matching bytecode for the following contracts: [0x2d4d37de64a7877260469ec14bd13eb57729d028].

This may occur when resuming a verification, but the underlying source code or compiler version has changed.
```

I was successfully able to verify the contract manually on the Arbiscan UI with a flattened version of the contract, by entering in the library as a dependency before verification. otherwise, it also fails there.

Here are the settings created by Forge:

```
{
  "remappings": [
    "@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "erc4626-tests/=lib/openzeppelin-contracts-upgradeable/lib/erc4626-tests/",
    "forge-std/=lib/forge-std/src/",
    "openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/"
  ],
  "optimizer": {
    "enabled": true,
    "runs": 80
  },
  "metadata": {
    "bytecodeHash": "ipfs"
  },
  "outputSelection": {
    "*": {
      "*": [
        "evm.bytecode",
        "evm.deployedBytecode",
        "devdoc",
        "userdoc",
        "metadata",
        "abi"
      ]
    }
  },
  "evmVersion": "london",
  "libraries": {
    "src/lib/FeeBuffer.sol": {
      "FeeBufferLib": "0xa8df1f75458d5b6594f8a79fb15eaf63c7870847"
    },
    "src/lib/FeeIntegral.sol": {
      "FeeIntegralLib": "0x2d4d37de64a7877260469ec14bd13eb57729d028"
    },
    "src/lib/FundingFee.sol": {
      "FundingFee": "0x1c0dbe0986a831f36ee2058cb4a3d0b95f93074a"
    },
    "src/lib/PositionMaths.sol": {
      "PositionMaths": "0x26292fbc81c8d840af1eb49e8199cb9ac7231584"
    },
    "src/lib/PositionStats.sol": {
      "PositionStatsLib": "0x05423d197a925d424ca055cfb79f9440203de962"
    }
  }
}
```

please also notice the spelling mistake in `Details`: `case senstive`

Thanks

**Comment by Evalir** [comment]
With the linker fix, this is now possible. When you're deploying a library `A` that depends on `B`, please append `--libraries` with `<path_to_library>:<library_name>:address>`. See: https://book.getfoundry.sh/reference/forge/forge-inspect?highlight=--libraries#options

**Comment by charlescrain** [comment]
> With the linker fix, this is now possible. When you're deploying a library `A` that depends on `B`, please append `--libraries` with `<path_to_library>:<library_name>:address>`. See: https://book.getfoundry.sh/reference/forge/forge-inspect?highlight=--libraries#options

Worked like a charm! Thanks!
