### ISSUE TITLE
`forge build` doesn't output build info for inherited contracts on partial build

### ISSUE THREAD

**Issue by sam-goldman** [foundry-rs/foundry#4981]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a5d506e 2023-05-18T00:15:53.051480000Z)

### What command(s) is the bug in?

forge build 

### Operating System

macOS (Apple Silicon)

### Describe the bug

**Steps to reproduce:**
1. Define two contracts:
```sol
// ./src/Counter.sol
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import "./ParentCounter.sol";

contract Counter is ParentCounter {
    uint256 public number = 1;
}
```

```sol
// ./src/ParentCounter.sol
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

contract ParentCounter {
    uint public parentNumber;
}
```

2. `forge build --build-info --extra-output 'storageLayout'`
3. Change the `Counter` contract slightly: `uint256 public number = 333;`
4. `forge build --build-info --extra-output 'storageLayout'`
5. In the build info file generated by step 4, the `outputSelection` field looks like:
```json
"outputSelection": {
    "src/Counter.sol": {
        "": [
            "ast"
        ],
        "*": [
            "abi",
            "evm.bytecode",
            "evm.deployedBytecode",
            "evm.methodIdentifiers",
            "metadata",
            "storageLayout"
        ]
    },
    "src/ParentCounter.sol": {
         "*": []
    }
},
```
Notice how the field for `"src/ParentCounter.sol"` is empty. As a result, the compiler output in this file for the `ParentCounter` contract is essentially empty too.

I'd expect the compiler output for the parent contract to be included in this build info file. This is how Hardhat handles this case. Without this info, tools like [`solidity-ast`](https://github.com/OpenZeppelin/solidity-ast) break because the parent contract's AST IDs aren't included in the file.

The `outputSelection` field should look like this:
```json
"outputSelection": {
    "*": {
        "": [
            "ast"
        ],
        "*": [
            "abi",
            "evm.bytecode",
            "evm.deployedBytecode",
            "evm.methodIdentifiers",
            "metadata",
            "storageLayout"
        ]
    }
}
```
Notice that `outputSelection["*"]["*"]` is defined here.

**Comment by sakulstra** [comment]
I think related: `forge build --build-info` does not generate buildInfo when previously being build without `--build-info`
It will skip via:
```
[⠔] Compiling...
No files changed, compilation skipped
```
