### ISSUE TITLE
vm.prank() stopped working after update

### ISSUE THREAD

**Issue by hananbeer** [foundry-rs/foundry#4982]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (31fcf5a 2023-05-19T00:04:19.980323193Z) (same Linux & Mac)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

update: sorry I'm in a rush to catch a flight and didn't manage to find the exact cause of the bug.
but this fact remains: my tests began to break on mac & linux but not on windows. something to do with vm.prank not registering properly.

I assume this is vm.prank because my error says:
[FAIL. Reason: No prank in progress to stop]

---

oddly this also started occurring on mac after updating foundry, but strangely enough not on windows.
I've updated all three of those several times, deleted foundry manually then tried again, cleared env vars... always same results. linux & mac fail, windows works normally.

my windows version is:
forge 0.2.0 (bb62e3c 2023-03-15T09:18:40.7502879Z)

(update: I downgraded manually and now it's working again)

**Comment by mds1** [comment]
There have recently been breaking changes to how pranks works, you can find more info on recent breaking changes here: https://github.com/foundry-rs/foundry/blob/master/CHANGELOG.md

Not totally sure if that is related to your issue, if you can share code to reproduce that would be really helpful. cc'ing @Evalir since this seems related to prank updates

**Comment by Evalir** [comment]
Hey! Indeed—some minimal repro would be truly helpful

**Comment by Evalir** [comment]
Haven't been able to reproduce and this error hasn't resurfaced in other issues—will close for now.
