### ISSUE TITLE
Forge test fails to retrieve uniswap source code

### ISSUE THREAD

**Issue by rickbeeloo** [foundry-rs/foundry#4983]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

Hey everyone :)

I actually have a quite complex test environment using Vyper for which foundry also doesn't seem able to load the source code but I guess that's not related to this.  This vyper contract interacts with Uniswap where it reverts. I have been trying to debug this but the traces just show:

```
    ..... etc.....
    ├─ [684] 0x104fBc016F4bb334D775a19E8A6510109AC63E00::allowance(0x104fBc016F4bb334D775a19E8A6510109AC63E00, UniswapV2Router02: [0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D]) [staticcall]
    │   └─ ← 1000000000000000000000000000
    ├─ [21712] 0x104fBc016F4bb334D775a19E8A6510109AC63E00::878b21f9() 
    │   ├─ [275] UniswapV2Router02::WETH() [staticcall]
    │   │   └─ ← WETH9: [0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2]
    │   ├─ [203] UniswapV2Router02::ab4e4c24(00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000000000000000000000000000104fbc016f4bb334d775a19e8a6510109ac63e00000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2000000000000000000000000104fbc016f4bb334d775a19e8a6510109ac63e000000000000000000000000000000000000000000000000000000000064671a07) 
    │   │   └─ ← ()
    │   └─ ← ()
    └─ ← "EvmError: Revert"
```
    
    
    
After I read about the forking I used my api key in the hope this from the docs would work:

> Traces that cannot be decoded by local contracts when running in a forked environment (e.g. calls to contracts that live on mainnet, like tokens) can optionally be decoded using Etherscan. To use Etherscan for trace decoding, set ETHERSCAN_API_KEY or pass --etherscan-api-key <KEY>.

`forge test --fork-url "https://eth-mainnet.g.alchemy.com/v2/......" --etherscan-api-key JSQJ2C33X..........  --debug`

But it seems the calls are not decoded, also in debug mode it just shows "Unknown contract at address 0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D" but this is just the router contract so I expect that to be just fetched?

**Comment by Evalir** [comment]
Hmm tried to reproduce but couldn't—traces seem to download correctly. That being said, this could be a vyper related issue.

We'll close for now as we haven't gotten any duplicates, but feel free to ping and reopen if it keeps happening! Please post a repro if it's still an issue.
