### ISSUE TITLE
Why is it slow to create a contract using `create opcode` when testing vs `vm.etch`

### ISSUE THREAD

**Issue by allan-wei-tx** [foundry-rs/foundry#4985]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a5d506e 2023-05-18T00:15:53.051480000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

This is the demo repo that I created for reproduction.
https://github.com/WEI-NERD/test-deploy-via-create-vs-etch

So, I was trying to use UniswapV2Factory and UniswapV2Router in my project using Foundry, and Foundry right now doesn't support multi solc version, so my solution was to copy the deployedCode of two contracts and use `vm.etch` to jam the code into my dummy `factory` and `router` contract. This is fast, which only took me ~1 second in the demo repo.

![image](https://github.com/foundry-rs/foundry/assets/131971450/db4ce56c-7c7c-4b38-912e-e8cb319df449)

But using the other approach, which is to use the creationCode of two contracts, and then create a contract using `create` opcode in assembly, is extremely slow, took me ~26 seconds to complete. 

![image](https://github.com/foundry-rs/foundry/assets/131971450/55bee600-7c14-49ac-b4fd-12fcba2da10c)

So, I'm confused now, why is it so slow to create a contract?

**Comment by twxia** [comment]
```
function getUniswapV2FactoryBytecode() public returns (bytes memory) {
        string memory json = vm.readFile("./node_modules/@uniswap/v2-core/build/UniswapV2Factory.json");
        bytes memory data = vm.parseJson(json);
        bytes memory bc = stdJson.parseRaw(json, ".bytecode");
        string memory bytecode = abi.decode(bc, (string));
        return vm.parseBytes(bytecode);
}
```

FYI, if I directly read the bytecode from the file and use `create` op code to create the contract, this again is faster than directly coded the bytecode in file. My guess is something related to memory caused that huge delay when there's a huge hex string in the file.

**Comment by grandizzy** [comment]
this is solc related, if you inline the bytecode in solidity file then it takes longer to compile (see 25 seconds vs 1.3 seconds in attached screenshot), not too much we can do about this (also mind that until recent versions solc segfaults with big contracts but should be solved now). Reading bytecode from file should be the preferred way if you looking to speed it up.

**Comment by twxia** [comment]
Thanks, left the related issue here to let everyone reference it. https://github.com/ethereum/solidity/issues/13496/.
