### ISSUE TITLE
--abi-decode --input should behave as the complement to abi-encode 

### ISSUE THREAD

**Issue by alxs** [foundry-rs/foundry#4987]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (31fcf5a 2023-05-19T00:10:33.861185000Z)

### What command(s) is the bug in?

cast --abi-decode 

### Operating System

None

### Describe the bug

Currently, `cast --abi-decode --input` behaves identically to `cast --calldata-decode`, in that both expect a function signature. However, I propose a change in this behavior for consistency and clearer distinction between the two. 

In the same way as `cast abi-encode` excludes the selector in its output, while `cast calldata` includes it, I suggest `cast --abi-decode --input` should also not expect the selector in its input. This contrasts with `cast --calldata-decode` that would continue to expect the selector. I believe this change would provide a more intuitive and consistent user experience across these commands. Thoughts?

**Comment by mattsse** [comment]
I think this is a valid point. --abi-encode and --abi-decode should ideally complement each other.

I'm supportive of that change.

**Comment by ptisserand** [comment]
Hi @mattsse any comment about `abi_decode` modification or adding a custom implementation?

**Comment by mattsse** [comment]
> Hi, can I work on this issue?

of course, 

> I'm wondering if foundry_common::abi::abi_decode(sig, calldata, input) should be modified or a custom implementation in SimpleCast::abi_decode added.

I think this would be the right approach here!

**Comment by andyrobert3** [comment]
do you know where the tests are written for `cast.rs`, especially `abi_decode`

**Comment by andyrobert3** [comment]
@mattsse  @gakonst  

I have created a draft PR to fix this issue 
https://github.com/foundry-rs/foundry/pull/5178

However, am unsure how is testing done for `cast` methods, since I am unable to find any tests related to `abi-decode` command

So please do share the "correct" place to write tests for this

**Comment by Evalir** [comment]
Hey @andyrobert3 ! you can add a new test at the end of the file, where `mod test` is found. Use a method that you know what it decodes to (it helps to corroborate with other tools) and see if the cast output equals that.

**Comment by andyrobert3** [comment]
thanks for the help @Evalir !

**Comment by andyrobert3** [comment]
Sounds good, adding it at the end of the file `cast/src/lib.rs`, within the `mod test` block
