### ISSUE TITLE
Anvil crash

### ISSUE THREAD

**Issue by wighawag** [foundry-rs/foundry#4990]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (35d516b 2023-05-13T12:06:08.359378058Z)

### What command(s) is the bug in?

anvil

### Operating System

Linux

### Describe the bug

I ll try to reproduce but for now the only info I got is this error:

```
thread 'tokio-runtime-worker' panicked at 'writing rfc2822 datetime to string should never fail: Error',
/home/wighawag/.cargo/registry/src/github.com-1ecc6299db9ec823/chrono-0.4.24/src/datetime/mod.rs:594:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace 
Aborted
```

I was calling setNextBlockTimestamp to 1 hour in the future

**Comment by mattsse** [comment]
What was the request?

**Comment by wighawag** [comment]
Not really sure, which one caused it
Could  be the `setNextBlockTimestamp` or `eth_getBlockByNumber`

**Comment by mattsse** [comment]
it is in setNextBlockTimestamp
but I was more interested in the value of that call because that caused the panic somehow.

this could also be an issue with the internal clock

**Comment by wighawag** [comment]
Ha yes, sorry, did not record that and I did not encounter the issue again yet.

It should have been values in the range of hours. But it could also be that there was computation bug on the client. if I encounter again, I hope to get more info

**Comment by Evalir** [comment]
Closing—stale
