### ISSUE TITLE
docs(fmt): document `disable-start` and `disable-end`

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/foundry#4998]
### Component

Forge

### Describe the feature you would like

I've just seen this feature in Forge Std:

https://github.com/foundry-rs/forge-std/blob/20872c5b1900526579159bdc6967f6b48c22e50e/src/StdCheats.sol#L212-L225

It is not documented in `forge fmt`'s README:

https://github.com/foundry-rs/foundry/tree/c331b5eeee1b4151ef7354a081667e2d770b37f5/fmt

**Comment by zerosnacks** [comment]
Resolved by https://github.com/foundry-rs/foundry/pull/6083
