### ISSUE TITLE
forge create --verify does not respect allow_paths

### ISSUE THREAD

**Issue by miohtama** [foundry-rs/foundry#5003]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (31fcf5a 2023-05-19T00:10:33.861185000Z)

### What command(s) is the bug in?

forge create

### Operating System

macOS (Apple Silicon)

### Describe the bug

I include the third-party protocol contracts in the contract source file. Because these files live in their own repository, with their own compiling toolchain and stuff, I cannot simply drop their files to `lib`.

I can still compile my contracts with some violence. In `foundry.toml` I have:

```toml
[profile.default]
# solc is a hard mistress and simply refuses to compile relative paths down in the parent tree
# allow the file system root and hope solc shuts up, as the error is not relevant
allow_paths = ["*", "/"]
```

`foundry build` works fine with these settings.

However the following command fails:

```shell
forge create --rpc-url $JSON_RPC_POLYGON \
    --constructor-args $USDC_TOKEN $VAULT_COMPTROLLER \
    --private-key $PRIVATE_KEY \
    --etherscan-api-key $POLYGONSCAN_API_KEY \
    --verify \
    src/VaultUSDCPaymentForwarder.sol:VaultUSDCPaymentForwarder
```

With the error:

```
Start verifying contract `0xe3eaaba28b03d873304958eb30f412b6ccd4016c` deployed on polygon

Submitting verification for [src/VaultUSDCPaymentForwarder.sol:VaultUSDCPaymentForwarder] "0xE3eAabA28B03d873304958EB30f412b6CCd4016c".

Submitting verification for [src/VaultUSDCPaymentForwarder.sol:VaultUSDCPaymentForwarder] "0xE3eAabA28B03d873304958EB30f412b6CCd4016c".

Submitting verification for [src/VaultUSDCPaymentForwarder.sol:VaultUSDCPaymentForwarder] "0xE3eAabA28B03d873304958EB30f412b6CCd4016c".
Submitted contract for verification:
        Response: `OK`
        GUID: `uudsxq2pdcmkgcdabweyrwtgjjbynf5i2dbqqcyitv3vmuk256`
        URL:
        https://polygonscan.com/address/0xe3eaaba28b03d873304958eb30f412b6ccd4016c
Contract verification status:
Response: `NOTOK`
Details: `Pending in queue`
Contract verification status:
Response: `NOTOK`
Details: `Fail - Unable to verify. Solidity Compilation Error: Source "../enzyme/node_modules/@openzeppelin/contracts/utils/Context.sol" not found: File outside of allowed directories.`
Contract failed to verify.

```

So it seems that `allow_paths` it only respected to `forge build`, but not for `forge create --verify`

I assume this is because files are uploaded to Etherscan for compilation and it cannot handle relative paths. In this case, a flattened verification might work?

**Comment by mattsse** [comment]
The allowed-paths setting is a CLI only setting and can not be expressed via the standard json interface alone

> I assume this is because files are uploaded to Etherscan for compilation and it cannot handle relative paths

which means we can't tell (or at least I don't think it's possible) to tell etherscan how to add the `--allow-paths` solc argument

https://docs.soliditylang.org/en/latest/using-the-compiler.html#compiler-api

**Comment by miohtama** [comment]
As a workaround, I am attempting to verify manually but hitting another snag

```shell
forge verify-contract \
    --etherscan-api-key $POLYGONSCAN_API_KEY   --flatten \
    --constructor-args $(cast abi-encode "constructor(address,address)" $USDC_TOKEN $VAULT_COMPTROLLER )\ 
     0xE3eAabA28B03d873304958EB30f412b6CCd4016c \
     src/VaultUSDCPaymentForwarder.sol:VaultUSDCPaymentForwarder
```

```
Start verifying contract `0xe3eaaba28b03d873304958eb30f412b6ccd4016c` deployed on mainnet
Compiler run failed:
Error: Invalid EVM version requested.
Failed to compile the flattened code locally.
This could be a bug, please inspect the output of `forge flatten /Users/moo/code/ts/trade-executor/deps/web3-ethereum-defi/contracts/in-house/src/VaultUSDCPaymentForwarder.sol` and report an issue.
To skip this solc dry, pass `--force`.
```

**Comment by miohtama** [comment]
With added `--force`, as `--flatten --force` another error message which I cannot make sense of:

```
VaultUSDCPaymentForwarder.sol:VaultUSDCPaymentForwarder
Start verifying contract `0xe3eaaba28b03d873304958eb30f412b6ccd4016c` deployed on mainnet
Error: 
expected value at line 1 column 1

```

**Comment by miohtama** [comment]
Finally `forge verify-contract --chain polygon --flatten --force` did the trick. Closing this issue, as it is likely unfixable, or too hard to fix. It would be nice to have `--flatten` as a parameter for `forge create`, but might be a bit too niche use case for inter-protocol connoseurs.
