### ISSUE TITLE
Failed to install with foundryup

### ISSUE THREAD

**Issue by zouguangxian** [foundry-rs/foundry#5007]
### Component

Foundryup

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What command(s) is the bug in?

foundryup

### Operating System

macOS (Apple Silicon)

### Describe the bug

foundryup can't download the binary archive file.
it looks like you didn't generate the nightly-31fcf5aa1ee7a480fa78cbf7fd266eea3f53dfd7.

**Comment by mattsse** [comment]
closed via #5010

new release available
