### ISSUE TITLE
Forge: `forge selectors` feature request meta issue

### ISSUE THREAD

**Issue by lmanini** [foundry-rs/foundry#5012]
### Component

Forge

### Describe the feature you would like

Main feature I'd like to add is a cmd to check for colliding method selectors between two given contracts.
@mds1 suggested to implement a `forge selectors` cmd and have the following initial subcommands:
- `forge selector collision` for what my original PR does
- `forge selector list <options>` to list function selectors and/or error selectors and/or event sigs for certain/all files in a project
- `forge selector upload` to replace `forge upload-selectors`

### Additional context

context: #4973

**Comment by mds1** [comment]
Thanks for opening this @lmanini. I'll defer to @mattsse and @Evalir but in the interest of keeping PRs easy to review/test, my suggestion would be as follows:

The first PR just structures things:
- Adds the `forge selectors` subcommand with a `forge selectors upload` command that duplicates the `forge upload-selectors` functionality
- Adds a warning to `forge upload-selectors` that it's deprecated and will be removed in v1 (cc @Evalir)

Then follow up PRs for:
- `forge selectors collision <ContractA> <ContractB>. Should be able to just specify contract names if there's no duplicate names, or use the `ContractA.sol:ContractA` when there are duplicates. Should exit with an error on collision and print the colliding signatures and their selectors
- `forge selectors list` prints all function selectors, error selectors, and event signatures for the src directory
    - Supports additive `--functions`, `--errors`, `--events` flags to specify a subset of the above, e.g. if you only want error selectors
    - Supports `--contracts <ContractA> <ContractB> ...` flag for limiting the contracts it's printed for
    - I'm open to other syntaxes/UX for the CLI args here

(Also I think `forge selectors`, plural, is better than `forge selector`, singular)

**Comment by lmanini** [comment]
> Should exit with an error on collision and print the colliding signatures and their selectors
Is there an example of how this should be handled? I was thinking of just doing a `shell::println(Paint::red(...))`. Do you have something else in mind?

**Comment by mds1** [comment]
`std::process::exit(1)` will exit the process with exit code 1 which indicates an error. So just call that after printing the relevant info

https://github.com/foundry-rs/foundry/blob/cae66aa8dd246b6707f682a1481ea494b8240526/common/src/compile.rs#L168

**Comment by lmanini** [comment]
oh ok haha - just started off with rust, still got a long way to go

**Comment by zerosnacks** [comment]
Marking as resolved by https://github.com/foundry-rs/foundry/pull/5116 + https://github.com/foundry-rs/foundry/pull/6205

Now yields:

```
$ forge selectors

Function selector utilities

Usage: forge selectors <COMMAND>

Commands:
  collision  Check for selector collisions between contracts [aliases: co]
  upload     Upload selectors to registry [aliases: up]
  list       List selectors from current workspace [aliases: ls]
  help       Print this message or the help of the given subcommand(s)

Options:
  -h, --help  Print help
```
