### ISSUE TITLE
Support making proposal to Openzeppelin Defender

### ISSUE THREAD

**Issue by KholdStare** [foundry-rs/foundry#5015]
### Component

Forge

### Describe the feature you would like

Not entirely sure the best way to approach such a feature, but it would be great to utilize Forge Scripts to generate proposals for Openzeppelin Defender: https://docs.openzeppelin.com/defender/admin.

The idea is that some changes to contracts need to be administered by a multi-sig (e.g. Gnosis Safe). I could see a workflow like this:

- Create an upgrade/update script for forge, and run it to produce a proposal on Openzeppelin Defender
- Check is on Defender, and approve with multisig

There is a hardhat defender plugin that can probably be mimicked. The idea is to simulate the script and gather the broadcasted transactions. Then convert those transactions into a format that Defender understands for proposals and send it over.

**Comment by zerosnacks** [comment]
Related: https://github.com/solidity-labs-io/forge-proposal-simulator

**Comment by zerosnacks** [comment]
> This is tracked in [OpenZeppelin/openzeppelin-foundry-upgrades#3](https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/issues/3)

Great thanks! I'll mark this as `out of scope` for here
