### ISSUE TITLE
Member "prevrandao" not found

### ISSUE THREAD

**Issue by alexbakers** [foundry-rs/foundry#5016]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (59f026f 2023-05-23T17:21:42.593814000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

```
$ forge init

// add vm.prevrandao(bytes32(uint256(42))); -> test/Counter.t.sol

$ forge test             
[⠢] Compiling...
[⠒] Compiling 1 files with 0.8.19
[⠑] Solc 0.8.19 finished in 250.58ms
Error: 
Compiler run failed:
Error (9582): Member "prevrandao" not found or not visible after argument-dependent lookup in contract Vm.
  --> test/Counter.t.sol:16:9:
   |
16 |         vm.prevrandao(bytes32(uint256(42)));
   |         ^^^^^^^^^^^^^


```

**Comment by mattsse** [comment]
@Evalir did we release this already:

https://github.com/foundry-rs/forge-std/pull/377

@alexbakers it should be there on forge-std main

**Comment by Evalir** [comment]
yep i believe we haven't cut a release with prevrandao in it cc @mds1

**Comment by mds1** [comment]
Ah sorry about that. @alexbakers I'm hoping to release forge-std v1.5.6 tomorrow, just want to see if we can get one of the open PRs in first. In the meantime you can either use the latest main commit on forge-std, or just wrap vm in your own interface that defines the prevrandao cheat

**Comment by mds1** [comment]
Just released forge-std v.1.5.6! Updating will give you this cheat, so closing this as completed

https://github.com/foundry-rs/forge-std/releases/tag/v1.5.6

**Comment by alexbakers** [comment]
@mds1 tell me please, does it anvil support prevrandao?

**Comment by mds1** [comment]
It should, my guess is that it defaults to 0 and there's an RPC method you need to call to change. I'm not certain though, so if you can't find your answer in the docs I'd suggest opening a separate issue
