### ISSUE TITLE
Latest version breaks invariant tests

### ISSUE THREAD

**Issue by alexroan** [foundry-rs/foundry#5020]
### Component

Foundryup

### Have you ensured that all of these are up to date?

- [x] Foundry
- [X] Foundryup

### What version of Foundry are you on?

foundryup: installing foundry (version nightly, tag nightly-59f026fc492ea09f2c640917f960e697d6e120b5) foundryup: downloading latest forge and cast ######################################################################################################################### 100.0% foundryup: downloading manpages ######################################################################################################################### 100.0% foundryup: installed - forge 0.2.0 (59f026f 2023-05-24T00:05:48.067515000Z) foundryup: installed - cast 0.2.0 (59f026f 2023-05-24T00:05:48.067515000Z) foundryup: done

### What command(s) is the bug in?

forge test -vvvvv --match-test invariant_

### Operating System

macOS (Apple Silicon)

### Describe the bug

The latest version of Foundry breaks invariant test suites that work with previous versions.

With `fail_on_revert=true`, ssertions fail despite there being no assertions in the handler actions:
```
[FAIL. Reason: Assertion failed.]
        [Sequence]
                sender=0xe3bc896cd3d9a8292ee9e7907fe3ada211349122 addr=[test/invariants/Handler2.t.sol:Handler2]0x2e234dae75c793f67a35089c9d99245e1c58470b calldata=pokeBlockchain(), args=[]
```

The stack trace appears to show no reverts either:

```
 invariant_printGhosts() (runs: 1, calls: 1, reverts: 1)
Traces:
  [5984066] Invariants::setUp() 
    ├─ [4997650] → new LimitOrderRegistry@0x5615dEB798BB3E4dFa0139dFa1b3D433Cc23b72f
    │   ├─ emit OwnershipTransferred(user: 0x0000000000000000000000000000000000000000, newOwner: Invariants: [0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496])
    │   └─ ← 24601 bytes of code
    ├─ [22743] LimitOrderRegistry::setMinimumAssets(1, 0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174) 
    │   └─ ← ()
    ├─ [22743] LimitOrderRegistry::setMinimumAssets(1, 0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619) 
    │   └─ ← ()
    ├─ [55463] LimitOrderRegistry::setupLimitOrder(0x45dDa9cb7c25131DF268515131f647d726f50608, 0) 
    │   ├─ [266] 0x45dDa9cb7c25131DF268515131f647d726f50608::token0() [staticcall]
    │   │   └─ ← 0x0000000000000000000000002791bca1f2de4661ed88a30c99a7a9449aa84174
    │   ├─ [308] 0x45dDa9cb7c25131DF268515131f647d726f50608::token1() [staticcall]
    │   │   └─ ← 0x0000000000000000000000007ceb23fd6bc0add59e62ac25578270cff1b9f619
    │   ├─ [251] 0x45dDa9cb7c25131DF268515131f647d726f50608::fee() [staticcall]
    │   │   └─ ← 0x00000000000000000000000000000000000000000000000000000000000001f4
    │   ├─ emit LimitOrderSetup(pool: 0x45dDa9cb7c25131DF268515131f647d726f50608)
    │   └─ ← ()
    ├─ [612290] → new Handler2@0x2e234DAe75C793f67A35089C9d99245E1C58470b
    │   └─ ← 2834 bytes of code
    ├─ [0] VM::startPrank(0x00000000000000000000000000000000000004d2) 
    │   └─ ← ()
    └─ ← ()

  [3567] Handler2::pokeBlockchain() 
    ├─ [0] VM::warp(1673207417 [1.673e9]) 
    │   └─ ← ()
    ├─ [0] VM::roll(37834660 [3.783e7]) 
    │   └─ ← ()
    └─ ← ()
```

With `fail_on_revert=false` reverts exist, but it's impossible to trace because when this flag is flipped, no indication of any reverts reveals itself.

I've resolved this locally by installing a previous commit of foundry: `e15e33a07c0920189fc336391f538c3dad53da73 `

**Comment by mattsse** [comment]
@Evalir looks like this is not fully fixed yet

**Comment by Evalir** [comment]
hey @alexroan any chance you could provide a repro for this?

**Comment by alexroan** [comment]
Today's `foundryup` seems to have resolved this issue!
