### ISSUE TITLE
forge build command customization 

### ISSUE THREAD

**Issue by huahuayu** [foundry-rs/foundry#5040]
### Component

Forge

### Describe the feature you would like

Since there are many options for `solc`, can I make `forge build` run my custom command e.g.

```bash
/usr/local/bin/solc --yul --bin --optimize --optimize-runs 200 --yul-dialect evm $(CONTRACT) | tail -1 > $(OUTPUT_DIR)/bytecode.bin
```

I have checked the `foundry.toml` configs, but it seems not supported.

**Comment by grandizzy** [comment]
there are constraints / specific options needed by foundry, we are handling new additions case by case but not planning for a general customization / pass through command. Please reopen if you disagree. thank you
