### ISSUE TITLE
feat(forge): compile only the test files matched via `--match-test`

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/foundry#5041]
### Component

Forge

### Describe the feature you would like

During development in large code bases, it it often useful to use the `--match-test` flag to zero in on specific tests. However, making one small change in `src` often leads to Forge recompiling all test files:

```text
[⠒] Compiling 139 files with 0.8.19
```

This operation takes time (minutes) even with the optimizer disabled (and via IR disabled, too).

It would be helpful if Forge could exclude all test files not matched via `--match-test` (or `--match-contract`, or `--match-path`) from the compilation step.

**Comment by PaulRBerg** [comment]
How difficult would it be to support this feature?

Debugging anything in a large code base like [Sablier V2](https://github.com/sablier-labs/v2-core/tree/main/test) takes up to a minute. Basically, every time I add a new `console.log2` in my `src` files, 100+ files get recompiled because most of our tests depend on some files in `src`.

**Comment by klkvr** [comment]
Solved by #7334
