### ISSUE TITLE
bug: incorrect `resetNonce` behavior for contracts

### ISSUE THREAD

**Issue by mds1** [foundry-rs/foundry#5043]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### Operating System

None

### Describe the bug

https://github.com/foundry-rs/foundry/pull/5033 introduced the `resetNonce` cheat which set the nonce of the given address to 0. However, per [EIP-161](https://eips.ethereum.org/EIPS/eip-161) contract nonces start at 1.

Either:
1. This cheat should be updated to conform to this behavior to. For the selfdestruct use case you'd have to etch the code to be empty first then reset nonce, or use `setNonceUnsafe` to make the order independent
2. This cheat should be left alone but we should document why it behaves this way and note that it can result in an invalid EVM state

While decrementing nonces can be an invalid state transition, lots of forge testing involves invalid state transitions, so this is ok. However I *think* actual invalid EVM states never (or least infrequently?) occur in forge, but the current behavior introduces that more concretely. As a result, I'd suggest option 1

cc @joaquinlpereyra

**Comment by joaquinlpereyra** [comment]
Good catch. `resetNonce` is a misnomer in light of this. I'm preparing a PR with option (1).

**Comment by joaquinlpereyra** [comment]
Fixed at: https://github.com/foundry-rs/foundry/pull/5044

**Comment by Evalir** [comment]
Closed due to #5044 being merged
