### ISSUE TITLE
Resuming a multi chain deployment leads to: The application panicked (crashed). Message:  to have been filled with a proper rpc

### ISSUE THREAD

**Issue by 0xTimepunk** [foundry-rs/foundry#5047]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a26edce 2023-05-25T00:12:21.044857000Z)

### What command(s) is the bug in?

forge script script/Test.Mainnet.Deploy.s.sol \     --resume \     --multi \     --slow \     -vvvv

### Operating System

macOS (Apple Silicon)

### Describe the bug

I am trying to do a multiChain deployment to three chains. I am trying to do this with the following command

```
forge script script/Test.Mainnet.Deploy.s.sol \
    --broadcast \
    --slow \
    -vvvv
```

Some transactions failed in Polygon, probably due to block re-rogs. I wanted to retry them, so I decided to run the following script:

```
forge script script/Test.Mainnet.Deploy.s.sol \
    --resume \
    --multi \
    -vvvv
```

And I get the following error
```
The application panicked (crashed).
Message:  to have been filled with a proper rpc
Location: cli/src/cmd/forge/script/sequence.rs:362

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   2: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   3: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   4: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   5: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   6: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   7: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   8: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   9: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  10: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  11: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  12: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  13: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  14: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  15: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  16: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  17: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  18: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  19: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  20: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  21: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
utils/run_script_mainnet.sh: line 12: 95185 Abort trap: 6           forge script script/Test.Mainnet.Deploy.s.sol --resume --multi
```

**Comment by Evalir** [comment]
cc @mattsse looks like a regresión from #4892, will investigate

**Comment by 0xTimepunk** [comment]
> cc @mattsse looks like a regression from #4892, will investigate

Thanks for commenting @Evalir. 

Also, we are not sure in the first place why so many transactions were not even processed in our script. On Polygon it was obvious what the problem was, but for BSC and AVAX it's as if the script stopped midway with no apparent reason.

Are multi-chain deployments fully working and if not what are their limitations?

**Comment by devanoneth** [comment]
Happy to also take a look. @0xTimepunk is the repo public anywhere? It can help with reproducing. Thanks.

**Comment by 0xTimepunk** [comment]
> Happy to also take a look. @0xTimepunk is the repo public anywhere? It can help with reproducing + I'd like to add a regression test once we get it fixed. Thanks.

@devanoneth @Evalir can we just privately share with you both? The code is not yet ready for a public release. Appreciate your work! Thanks

**Comment by Evalir** [comment]
Closing, stale and can't seem to repro regression.
