### ISSUE TITLE
auto increment operator bug inside chisel

### ISSUE THREAD

**Issue by GopherJ** [foundry-rs/foundry#5048]
### Component

Chisel

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (33f3fee 2023-05-26T00:03:48.457406188Z)

### What command(s) is the bug in?

chisel

### Operating System

Linux

### Describe the bug

chisel
![image](https://github.com/foundry-rs/foundry/assets/33961674/d0d1799a-06c4-49fd-a56f-0c438d0c5d9b)
solidity-shell
![image](https://github.com/foundry-rs/foundry/assets/33961674/6824e690-94aa-4f4a-a35d-35164f06b14d)

**Comment by DaniPopes** [comment]
Expressions that don't end in semicolon (`;`) won't get saved in the session. See https://github.com/foundry-rs/foundry/issues/7193

**Comment by zerosnacks** [comment]
Remarking as `duplicate` of https://github.com/foundry-rs/foundry/issues/7193
