### ISSUE TITLE
Anvil support block.prevrandao?

### ISSUE THREAD

**Issue by alexbakers** [foundry-rs/foundry#5056]
### Component

Anvil

### Describe the feature you would like

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

contract Counter {
    uint256 public number;

    function setPrevrandao() public {
        number = block.prevrandao;
    }
} 
```

### Additional context

`block.prevrandao` always `0`

**Comment by ualtinok** [comment]
Can we reopen this? Prevrandao is still always 0 for any block. @Evalir

**Comment by mattsse** [comment]
can just init this to random

**Comment by ualtinok** [comment]
Wouldn’t it be better if it gives a different random for each block?

**Comment by mattsse** [comment]
definitely
