### ISSUE TITLE
cast: create a keystore file for an existing private key

### ISSUE THREAD

**Issue by calldata** [foundry-rs/foundry#5057]
### Component

Cast

### Describe the feature you would like

There is no way to create a keystore file for an existing private key using the `cast wallet` subcommand. This subcommand can only create keystore file for a fresh new generated private key by ` cast wallet new -p <KEYSTORE-PATH>`. It would be convenient to have the abliity to wrap an existing private key to a keystore file.

**Comment by scottt** [comment]
This issue should be closed since `cast wallet import` exists now.
