### ISSUE TITLE
anvil --hardfork shanghai/paris give an unknown value error

### ISSUE THREAD

**Issue by d1onys1us** [foundry-rs/foundry#5058]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (33f3fee 2023-05-27T00:09:05.418420000Z)

### What command(s) is the bug in?

anvil --hardfork

### Operating System

macOS (Apple Silicon)

### Describe the bug

When I run the command `anvil --hardfork shanghai` or `anvil --hardfork paris` I get the error: `error: invalid value 'paris' for '--hardfork <HARDFORK>': Unknown hardfork shanghai`.

I believe this was supposed to be addressed in this PR: https://github.com/foundry-rs/foundry/pull/5001.

**Comment by mattsse** [comment]
nice catch,

fixed via #5061
