### ISSUE TITLE
inconsistent result between `chisel` and `forge test`

### ISSUE THREAD

**Issue by zhiqiangxu** [foundry-rs/foundry#5064]
### Component

 Chisel

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e2fa2b5 2023-02-19T00:15:20.51416Z)

### What command(s) is the bug in?

chisel

### Operating System

macOS (Intel)

### Describe the bug

```solidity
contract Test2 {
    function t() public returns (uint256) {
        return 1;
    }
}

➜ keccak256(type(Test2).creationCode)
Type: bytes32
└ Data: 0x6469cc681ffdab12993915bc6711b198aa897668cb2fbe8c4c9934a4e679acf9
➜ keccak256(abi.encodePacked(type(Test2).creationCode))
Type: bytes32
└ Data: 0x8cded7f9d62c29d349b543260ae86c44c162e11730270ff61e2162f4037c517d
```
`keccak256(type(Test2).creationCode)` and `keccak256(abi.encodePacked(type(Test2).creationCode))` returns different result on `chisel`, but it's the same on `forge test`.

**Comment by Evalir** [comment]
This is due to how chisel's session is setup vs forge's testrunner. Closing as stale.

**Comment by zhiqiangxu** [comment]
> This is due to how chisel's session is setup vs forge's testrunner. Closing as stale.

could you elaborate on this?
