### ISSUE TITLE
forge coverage counts branches for "require()" statements that will always revert

### ISSUE THREAD

**Issue by kshyun28** [foundry-rs/foundry#5068]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (31fcf5a 2023-05-19T00:10:33.861185000Z)

### What command(s) is the bug in?

forge coverage

### Operating System

macOS (Apple Silicon)

### Describe the bug

Hello team, 

I've encountered a potential bug on **calculating branch coverage** while working on my [project](https://github.com/kshyun28/foundry-nft).

Currently I cannot get 100% coverage on the branches when running `forge coverage`.
![coverage](https://github.com/foundry-rs/foundry/assets/56709653/0208fc06-c280-4969-a104-f9e27073bbd1)

Then when running `forge coverage --report debug`, I get
```bash
Compiler run successful!
Analysing contracts...
Running tests...
Uncovered for src/MyNFT.sol:
- Branch (branch: 0, path: 1) (location: source ID 29, line 44, chars 1313-1346, hits: 0)
```

The culprit is the code below, which is a "require" statement that will **always revert**, 
```solidity
require(false, "cannot renounce");
```
but the coverage report is still expecting a branch where "require" **will not revert**. 

I appreciate the team's inputs here if this is expected behavior or a valid bug, and will assist wherever I can.

Minimal code snippet to reproduce below, then run `forge coverage`.

**MyNFT.sol**
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.13;

import "@openzeppelin/utils/Strings.sol";
import "@openzeppelin/token/ERC721/ERC721.sol";
import "@openzeppelin/access/Ownable.sol";

contract MyNFT is ERC721, Ownable {
    constructor() ERC721("MyNFT", "MN") {}

    function renounceOwnership() public pure override {
        require(false, "cannot renounce");
    }
}
```

**MyNFT.t.sol**
```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import "forge-std/Test.sol";
import "../src/MyNFT.sol";

contract MyNFTTest is Test {
    MyNFT public myNFT;

    function setUp() public {
        myNFT = new MyNFT();
    }

    function testRenounceOwnership() public {
        vm.expectRevert();
        myNFT.renounceOwnership();
    }
}

```

**Comment by KholdStare** [comment]
I think in this case it's a misuse of `require`. I think you should be using `revert` in this case: https://docs.soliditylang.org/en/latest/control-structures.html#revert-statement

**Comment by kshyun28** [comment]
I guess you're right about this. Revert would indeed do better for my use case.

Feel free to close this issue thanks.
