### ISSUE TITLE
bug(`forge`): running an invariant test with inputs makes forge crash

### ISSUE THREAD

**Issue by Evalir** [foundry-rs/foundry#5084]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### Operating System

None

### Describe the bug

Seems that if we run an invariant test with function inputs it panics:

<img width="588" alt="Screenshot 2023-05-30 at 10 01 17" src="https://github.com/foundry-rs/foundry/assets/26014927/af5a3595-da4a-4e61-a094-5dbdacdb5f32">

This should just be an error.

**Comment by ruvaag** [comment]
@Evalir is this being worked on? If not, would love to take this on. 

I was able to reproduce the bug locally and have a fix in mind.

**Comment by Evalir** [comment]
Yep @ruvaag feel free to work on this! assigning you
