### ISSUE TITLE
Bug(`forge`): Treat init code size errors as test failures

### ISSUE THREAD

**Issue by Evalir** [foundry-rs/foundry#5090]
... sigh, this is bad -.-

however https://github.com/bluealloy/revm/pull/491 should fix that, but we don't have it in foundry yet

I believe https://github.com/foundry-rs/foundry/pull/5089 should do it, mind trying this?

separately @Evalir we should treat this as test failures

_Originally posted by @mattsse in https://github.com/foundry-rs/foundry/issues/5088#issuecomment-1570300932_

**Comment by mattsse** [comment]
I think we should just convert the `Err` into a SuiteResult and treat it the same as `setup.setup_failed`:

https://github.com/foundry-rs/foundry/blob/a5c27411c7e5d1dd574df758060da8ad501ecbde/forge/src/runner.rs#L251-L254
