### ISSUE TITLE
Speedup forge install with git shallow clone

### ISSUE THREAD

**Issue by Vectorized** [foundry-rs/foundry#5095]
### Component

Forge

### Describe the feature you would like

Right now, it appears that `forge install` clones the entire history of the git submodules.

But what we actually need is just the latest commit or a particular commit.

If possible, we can make it clone only the relevant commit. 

https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/

Of course, we will still need to clone all the dependencies recursively.

**Comment by thedavidmeister** [comment]
yes please, i'm finding forge install to be very slow, taking several minutes to install a single dep

**Comment by smyja** [comment]
Still having the same issue
