### ISSUE TITLE
feat(doc): Don't mess with spacing inside markdown block codes in natspec

### ISSUE THREAD

**Issue by amusingaxl** [foundry-rs/foundry#5096]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9751242 2023-05-31T18:40:53.843284217Z)

### What command(s) is the bug in?

forge doc

### Operating System

Linux

### Describe the bug

I have some nested markdown code blocks in NatSpec like the following:

```java
     * @inheritdoc DistributionCalc
     * @dev Here is a summary of the mathematical model behind the formula in the code.
     *
     * To make sure the total vested amount `tot` is distributed by the end of the period, we must ensure that:
     *
     * ```
     *       _                        _
     *      /  clf  -  bgn           /  fin - clf
     *      |              r dt  =   |            kt  +  s dt
     *     _/  0                    _/  0
     * ```
     * 
     */
```

However, the file generated by `forge doc` relative to this contract removes the leading white spaces from the block above:

```markdown
### getMaxAmount

Gets the amount to be distributed from a vesting stream.

*Here is a summary of the mathematical model behind the formula in the code.
To make sure the total vested amount `tot` is distributed by the end of the period, we must ensure that:
'''
_                        _
/  clf  -  bgn           /  fin - clf
|              r dt  =   |            kt  +  s dt
_/  0                    _/  0
'''
```

Which makes the expression unreadable.

It would be nice if the generator did not remove leading/trailing spaces inside markdown code blocks.

**Comment by grandizzy** [comment]
we're tracking same issue in https://github.com/foundry-rs/foundry/issues/4539, closing as dupe
