### ISSUE TITLE
forge debug panicks instead of returning an error message

### ISSUE THREAD

**Issue by QGarchery** [foundry-rs/foundry#5097]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9751242 2023-05-31T18:40:53.843284217Z)

### What command(s) is the bug in?

forge test --debug

### Operating System

Linux

### Describe the bug

The debugger panicks with:
```
Message:  called `Option::unwrap()` on a `None` value
Location: cli/src/cmd/forge/test/mod.rs:194
```
when run on a test that is mistakenly not prefixed by `test`. It would be more user-friendly to return the cause of the error.

To reproduce, run `forge test --debug doStuff` on the following test contract:
```solidity
contract TestContract {
    function testDummy() public pure {
        assert(true);
    }

    function doStuff() public pure {
        assert(true);
    }
}
```

**Comment by DaniPopes** [comment]
This has been fixed.
