### ISSUE TITLE
forge build hangs on mac silicon

### ISSUE THREAD

**Issue by thedavidmeister** [foundry-rs/foundry#5102]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (08a629a 2023-06-03T00:14:26.563741000Z)

### Operating System

macOS (Apple Silicon)

### Describe the bug

Running `forge build` on this repo https://github.com/rainprotocol/rain.orderbook hangs

It builds in a couple of seconds on linux/CI

Confirmed on 2 different mac devices

**Comment by mattsse** [comment]
hmm, interesting, I can reproduce this on M2, but this is all solc, not sure why though

<img width="384" alt="image" src="https://github.com/foundry-rs/foundry/assets/19890894/2f1d9d1e-58fb-458a-a03a-7f0cd47fc98c">

**Comment by Evalir** [comment]
Can also reproduce. Unsure what this is though...

**Comment by ASaidOguz** [comment]
I have same problem while building this project https://github.com/code-423n4/2023-06-llama
![image](https://github.com/foundry-rs/foundry/assets/98320812/530a4137-9742-46d2-bb07-5cae66267146)
it just hangs in compile phase after 15 minutes and gives Solc error with no exlplanation.
Using wsl ubuntu VERSION="20.04.4 LTS (Focal Fossa)"

**Comment by DaniPopes** [comment]
It did use about ~8GiB of RAM. 

```
$ forge b
[⠊] Compiling...
[⠒] Compiling 99 files with 0.8.19
[⠢] Solc 0.8.19 finished in 26.96s
Compiler run successful!
```
