### ISSUE TITLE
Getting InvalidFEOpcode

### ISSUE THREAD

**Issue by jewei1997** [foundry-rs/foundry#5104]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (08a629a 2023-06-03T00:14:26.563741000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

Getting "EvmError: InvalidFEOpcode" when running a simple mint and burn function when forking off of eth mainnet. Here's a repro:

```
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.0;

import {Test} from "../lib/forge-std/src/Test.sol";

interface IKNCV2 {
    function mintWithOldKnc(uint256 amount) external;
    function balanceOf(address account) external view returns (uint256);
}

contract KncTest is Test {

    address constant KNC_WHALE = 0xe4798421a171DC2a2992CF2E8991Ee6D59D2BA1d;
    address constant KNCV2 = 0xdeFA4e8a7bcBA345F687a2f1456F5Edd9CE97202;

    function testKncMint() public {
        vm.createSelectFork("https://eth.llamarpc.com");

        vm.startPrank(KNC_WHALE);
        IKNCV2(KNCV2).mintWithOldKnc(1e18);
        vm.stopPrank();
    }
}
```

The error stack trace looks like:
```
Running 1 test for test/Knc.t.sol:KncTest
[FAIL. Reason: EvmError: Revert] testKnc() (gas: 8797746687696155730)
Traces:
  [8797746687696155730] KncTest::testKnc()
    ├─ [0] VM::createSelectFork(https://eth.llamarpc.com)
    │   └─ ← 0
    ├─ [0] VM::startPrank(0xe4798421a171DC2a2992CF2E8991Ee6D59D2BA1d)
    │   └─ ← ()
    ├─ [8797746687696149491] 0xdeFA4e8a7bcBA345F687a2f1456F5Edd9CE97202::mintWithOldKnc(1000000000000000000 [1e18])
    │   ├─ [8797746687696142250] 0xe5E8E834086F1a964f9A089eB6Ae11796862e4CE::mintWithOldKnc(1000000000000000000 [1e18]) [delegatecall]
    │   │   ├─ [16033] 0xdd974D5C2e2928deA5F71b9825b8b646686BD200::burnFrom(0xe4798421a171DC2a2992CF2E8991Ee6D59D2BA1d, 1000000000000000000 [1e18])
    │   │   │   └─ ← "EvmError: InvalidFEOpcode"
    │   │   └─ ← "EvmError: Revert"
    │   └─ ← "EvmError: Revert"
    └─ ← "EvmError: Revert"

Test result: FAILED. 0 passed; 1 failed; finished in 1.10s

Failing tests:
Encountered 1 failing test in test/Knc.t.sol:KncTest
[FAIL. Reason: EvmError: Revert] testKnc() (gas: 8797746687696155730)

Encountered a total of 1 failing tests, 0 tests succeeded
```

**Comment by DaniPopes** [comment]
This happens when the EVM executes a [0xFE opcode](https://www.evm.codes/#fe?fork=shanghai), which happens in a few points if you look at the disassembly on Etherscan (`'fe'(Unknown Opcode)`). I believe this might be a bounds check or an assertion inserted by older Solc versions v0.4.X.

**Comment by PaulRBerg** [comment]
I was getting this error when fork testing against USDT; the issue was that the allowance amount was smaller than the transfer amount.

**Comment by jewei1997** [comment]
That was it, thank you @PaulRBerg @DaniPopes !

**Comment by rayeaster** [comment]
> I was getting this error when fork testing against USDT; the issue was that the allowance amount was smaller than the transfer amount.

Really helpful ser @PaulRBerg
