### ISSUE TITLE
anvil disk caching not working anymore?

### ISSUE THREAD

**Issue by michprev** [foundry-rs/foundry#5111]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

anvil 0.1.0 (08a629a 2023-06-03T00:05:11.227787246Z)

### What command(s) is the bug in?

anvil

### Operating System

Linux

### Describe the bug

It seems that anvil disk caching does not work now. If I launch anvil and send some transactions, the `~/.foundry/anvil/tmp` directory is not created anymore.

I am trying to take advantage of anvil caching when running fork tests, but the tests always take the same time (12s for a few transactions) no matter what parameters I set. I think this may be related to the fact that the `tmp` directory is not created.

```
anvil -f https://mainnet.infura.io/v3/API_KEY --fork-block-number 17386454 --fork-chain-id 1
```

**Comment by mattsse** [comment]
> It seems that anvil disk caching

what caching do you mean?

```
~/.foundry/cache/rpc/mainnet/17386454
```

should exist?

**Comment by michprev** [comment]
I remember there always was the `~/.foundry/anvil/tmp` directory causing my disk running out of space quickly. This directory is not created anymore even when launching anvil with default parameters (by just simply running `anvil`).

The directory `~/.foundry/cache/rpc/mainnet/17386454` exists but its presence does not speed up my fork tests. It runs 16s for the first time (with `~/.foundry/cache/rpc` removed) and 15.4s for the second time (with `~/.foundry/cache/rpc/mainnet/17386454/storage.json` present).

**Comment by mattsse** [comment]
this was for caching the entire state/history of the chain, this is now stored in a regular tmp dir because this is only valid for the time the chain exists.

this shouldn't have any impact on rpc though because all rpc state is cached in rpc folder, so idk what's causing this, can you try another key?
or have a look at the logs maybe you can identify the logs this way

**Comment by michprev** [comment]
I am experiencing the same behavior with Alchemy. Anvil sends many `eth_getCode`, `eth_getBalance`, `eth_getStorageAt` requests as if there was no cache. I can create a minimal example. Are there any anvil/foundry logs I can inspect?

**Comment by michprev** [comment]
Looking into the anvil code, it seems like it never supported full offline mode with forking. I got confused by this PR https://github.com/foundry-rs/foundry/pull/3877 from which I got the impression that forking can be run fully offline if all necessary data are cached.
