### ISSUE TITLE
`Deserialization Error` when trying to run tests that have used `selectFork`

### ISSUE THREAD

**Issue by SamAg19** [foundry-rs/foundry#5114]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

0.2.0

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

Running forking tests periodically reverts with the following deserialization error:

```
2023-06-06T06:21:06.134224Z ERROR sharedbackend: Failed to send/recv `basic` err=GetAccount(0x7e5f4552091a69125d5dfcb7b8c2659029395bdf, 
Deserialization Error: invalid type: string "11", expected u64 at line 1 column 26. Response: {"jsonrpc":"2.0","id":"11","result":"0x1ba"}) address=0x7e5f4552091a69125d5dfcb7b8c2659029395bdf
The application panicked (crashed).
Message:  called `Option::unwrap()` on a `None` value
Location: /home/runner/.cargo/git/checkouts/revm-bf744d8ffabcbad9/4e6750b/crates/revm/src/evm_impl.rs:281

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry
```

**Comment by mattsse** [comment]
> {"jsonrpc":"2.0","id":"11","result":"0x1ba"}

it looks like that your provider sends the response id incorrectly, we set id to an integer
and therefor expect the same integer
