### ISSUE TITLE
Anvil local rejecting 0 base tx fee when using --base-fee 0

### ISSUE THREAD

**Issue by chlwys** [foundry-rs/foundry#5125]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (08a629a 2023-06-03T00:14:26.563741000Z)

### What command(s) is the bug in?

anvil  --base-fee 0

### Operating System

macOS (Apple Silicon)

### Describe the bug

Anvil rejects transactions priced at `0 gwei` when `--base-fee 0`. It fails with
> Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":72,\"error\":{\"code\":-32003,\"message\":\"max fee per gas less than block base fee\"}}", error={"code":-32003}, requestBody="{\"method\":\"eth_sendRawTransaction\"

First noticed this with forge 0.2.0 (cc5637a 2023-06-02T00:22:41.615504000Z)

**Comment by mattsse** [comment]
there's indeed an edge case when base fee is pinned to 0:

https://github.com/bluealloy/revm/blob/69f417f15755d7fcf9fac8dd2df3dc4cb2cd6bad/crates/primitives/src/env.rs#L282

fixing
