### ISSUE TITLE
feat(`config`): Allow config values related to `invariant` to use new `statefulFuzz` keyword

### ISSUE THREAD

**Issue by Evalir** [foundry-rs/foundry#5136]
This is a 1.0 related change—with config, we're still using the invariant keyword. We should allow using `statefulFuzz`.

**Comment by grandizzy** [comment]
we discussed to keep `invariant` config as it is now better known by foundry users than `statefulFuzz`. the functions named `statefulFuzz` should continue to work like `invariant_`. thank you!
