### ISSUE TITLE
Forge install doesn't work on Windows 11

### ISSUE THREAD

**Issue by lingfei1999** [foundry-rs/foundry#5139]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (08a629a 2023-06-03T00:08:43.223181800Z)

### What command(s) is the bug in?

forge install transmissions11/solmate

### Operating System

Windows

### Describe the bug

When I run the command `forge install transmissions11/solmate` , I got this error: 

```
Error:
The target directory is a part of or on its own an already initialized git repository,
and it requires clean working and staging areas, including no untracked files.

Check the current git repository's status with `git status`.
Then, you can track files with `git add ...` and then commit them with `git commit`,
ignore them in the `.gitignore` file, or run this command again with the `--no-commit` flag.

If none of the previous steps worked, please open an issue at:
https://github.com/foundry-rs/foundry/issues/new/choose
NativeCommandExitException: Program "forge.exe" ended with non-zero exit code: 1.

```

**Comment by Evalir** [comment]
This is not an error. You'll get this if you're installing dependencies with a "dirty workspace" (uncommitted file).
