### ISSUE TITLE
foundryup --version "tar: Error opening archive: Unrecognized archive format"

### ISSUE THREAD

**Issue by jdg2896** [foundry-rs/foundry#5141]
### Component

Foundryup

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (08a629a 2023-06-03T00:14:26.563741000Z)

### What command(s) is the bug in?

foundryup --version

### Operating System

macOS (Apple Silicon)

### Describe the bug

Hello, after running `foundryup --version`, there's an error after:
- "downloading latest forge, cast, anvil, and chisel" and  
- "downloading manpages"

which is 
`tar: Error opening archive: Unrecognized archive format`.

terminal output is also shown at screenshot below.
![foundryup --version](https://github.com/foundry-rs/foundry/assets/56709653/86d2efbb-05fe-4280-83b6-df9dd8210e5e)

**Comment by kshyun28** [comment]
Hello Evalir,

Actually I just ran the command as is without specifying a specific version, so it defaults to downloading the "latest".

I see.

**Comment by DaniPopes** [comment]
`--version` expects a value, but this isn't checked so it ended up trying to download an empty version ""
