### ISSUE TITLE
`anvil`: no `withdrawalsRoot` returned in block data

### ISSUE THREAD

**Issue by Evalir** [foundry-rs/foundry#5142]
adding to this--how do I know if anvil is running --shanghai by default? when i do `cast block` against either `anvil` or `anvil --hardfork shanghai`, I am not seeing `withdrawalsRoot` returned in the block data.

_Originally posted by @d1onys1us in https://github.com/foundry-rs/foundry/issues/4916#issuecomment-1587153571_

**Comment by mattsse** [comment]
perhaps we're missing formatting for this?

**Comment by Evalir** [comment]
Yeah probably—I'm pretty sure the data is there, just might not be showing up
