### ISSUE TITLE
forge verify-contract command adds "/" suffix to verifier url

### ISSUE THREAD

**Issue by islishude** [foundry-rs/foundry#5160]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ce687fc 2023-06-15T00:16:21.518016000Z)

### What command(s) is the bug in?

forge verify-contract

### Operating System

macOS (Intel)

### Describe the bug

Command

Note that the verifier url doesn't have `/` suffix

```
forge verify-contract --verifier=blockscout --verifier-url=https://example.com/api 0x9c6554832dc990710a686be993558a52fb55d838 src/Counter.sol:Counter
```

the following log is from blockscout, you can see that the request has `/` suffix, and blockscout can't handle it.

```
2023-06-15T14:24:40.011 application=api request_id=F2jbNL1OUofKgP4AAJKm [info] /api/?module=contract&action=getabi&address=0x9c6554832dc990710a686be993558a52fb55d838
2023-06-15T14:24:40.011 application=api request_id=F2jbNL1OUofKgP4AAJKm [info] Sent 500 in 62µs
```

and I have tested with curl, blockscout returns `{"message":"Something went wrong.","result":null,"status":"0"}`

but if I use the request without `/` then blockscout returns `{"message":"Contract source code not verified","result":null,"status":"0"}`.

**Comment by Evalir** [comment]
This is expected behavior—try appending `\?` at the end, like so: `https://example.com/api\?`

We'll do a better job at documenting this.

**Comment by oveddan** [comment]
wow, glad to come across this issue, adding the \? to the url solved our problem too (for the zora chains with verification urls located at `https://testnet.explorer.zora.energy/api` and `https://explorer.zora.energy/api`). we were trying to figure out what was wrong for a while.

**Comment by MarcusWentz** [comment]
@Evalir 

I opened this pull request
https://github.com/foundry-rs/book/pull/967
to document the fix commented here
https://github.com/foundry-rs/foundry/issues/5160#issuecomment-1599602416

**Comment by Kongarto** [comment]
goods
