### ISSUE TITLE
feat: allow to broadcast every tx of the script at once

### ISSUE THREAD

**Issue by wei3erHase** [foundry-rs/foundry#5166]
### Component

Forge

### Describe the feature you would like

For long deployment scripts, waiting txs for receipts and then broadcasting the next one can take a lot of time, it'd be nice to allow the user to broadcast them all (at the user's safety expense since one of them could revert).
Since all txs are signed with a nonce, no reordering could happen that would make one prior to a previous one.

`--slow` method seems to be selected by default, plz add `--fast` one 🙏 

Related to #5035

**Comment by RickVM** [comment]
Would be great to have this! Our protocol has become quite large, and a testnet deploy currently takes 30 mins... :)

**Comment by samlaf** [comment]
Is this not currently possible? What is the forge script `--batch-size` parameter?
https://book.getfoundry.sh/reference/cli/forge/script?highlight=batch-size#forge-script says
<img width="708" alt="image" src="https://github.com/foundry-rs/foundry/assets/9342524/668f2dbd-b730-4f85-9980-4538d5fb9118">

**Comment by zerosnacks** [comment]
The `--batch-size` parameter was added here: https://github.com/foundry-rs/foundry/pull/7540/files to handle < 100 case and is automatically enabled if batching is available and `--slow` is not enabled.

Marking as `resolved`. Please re-open if this does not resolve your issue.

**Comment by samlaf** [comment]
Only works when txs are from the same sender though, unfortunately.
