### ISSUE TITLE
forge fails due to gasstation used to get fees for Polygon mainnet being down

### ISSUE THREAD

**Issue by dontrolle** [foundry-rs/foundry#5167]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (fca0a6c 2023-06-16T00:08:10.030703163Z)

### What command(s) is the bug in?

forge script

### Operating System

Linux

### Describe the bug

Note: We've encountered this bug in our CI pipeline run on a fairly standard GitHub Actions setup (cf. https://github.com/mangrovedao/mangrove-bots/actions/runs/5276245102/jobs/9571216174, if interested).

**Bug**

`forge script` fails when deploying to (a local fork of) Polygon mainnet - seemingly due to https://gasstation-mainnet.matic.network/v2 being used to get gas-fees (I assume due to the long-standing Polygon/ethers.js fee-issue, cf https://github.com/ethers-io/ethers.js/issues/2828). This gasstation has recently (this week) stopped being available. 

We are ourselves in the middle of switching over to https://gasstation.polygon.technology/v2 for gas-fee estimation for Polygon mainnet. 

Without having dug deeply in the underlying code for `forge`, I assume that `forge` may need to do something similar.

**Comment by dontrolle** [comment]
PS adding the `--legacy` option to the `forge script` command does seem to alleviate the problem, so for now, we're using that to unblock our CI pipelines.

**Comment by Evalir** [comment]
Closing as we recently merged #5180 — thanks @DaniPopes 👑
