### ISSUE TITLE
broken url used for mumbai gas estimates

### ISSUE THREAD

**Issue by thedavidmeister** [foundry-rs/foundry#5168]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What command(s) is the bug in?

forge script

### Operating System

Linux

### Describe the bug

The URL https://gasstation-mumbai.matic.today/v2 does not resolve so gas fails and forge scripts cannot deploy to mumbai

https://wiki.polygon.technology/docs/develop/tools/polygon-gas-station/ documents the gas estimation url as

https://gasstation-testnet.polygon.technology/v2

**Comment by mattsse** [comment]
ref https://github.com/gakonst/ethers-rs/pull/2479

**Comment by thedavidmeister** [comment]
note that somehow --legacy allowed me to deploy, even though mumbai supports 1559 i think

**Comment by PaulRBerg** [comment]
Just got the same error while trying to deploy to Polygon Mainnet:

> Failed to estimate EIP1559 fees. This chain might not support EIP1559, try adding --legacy to your command.

And the full logs:

```text
Context:
- Error #0: error sending request for url (https://gasstation-mainnet.matic.network/v2): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known
- Error #1: error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known
- Error #2: dns error: failed to lookup address information: nodename nor servname provided, or not known
- Error #3: failed to lookup address information: nodename nor servname provided, or not known
```

Can confirm that passing `--legacy` let me deploy, but the deployment should work even with EIP-1559 because Polygon supports it.

**Comment by KholdStare** [comment]
@mattsse Are there any commandline params or environment variables to bypass the fee estimation or give a different URL in general?

Having these URLs hardcoded in code is bad practice IMO, because it couples a code version and the environment it runs in. That means previously "stable" releases of forge would now stop working for polygon networks, just because of this hardcoded URL.

There should be a way to override these somehow.
