### ISSUE TITLE
The target directory is a part of or on its own an already initialized git repository, and it requires clean working and staging areas, including no untracked files.  Check the current git repository's status with `git status`. Then, you can track files with `git add ...` and then commit them with `git commit`, ignore them in the `.gitignore` file, or run this command again with the `--no-commit` flag.

### ISSUE THREAD

**Issue by AdMub** [foundry-rs/foundry#5173]
### Component

Forge, Cast, Anvil, Foundryup, Chisel

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (fca0a6c 2023-06-16T00:07:44.213322400Z)

### What command(s) is the bug in?

 forge install OpenZeppelin/openzeppelin-contracts

### Operating System

Windows

### Describe the bug

cc

**Comment by AdMub** [comment]
the same issue

**Comment by Evalir** [comment]
This happens when your directory is dirty (has uncommitted files). Run it with `--no-commit`.

Closing as this is expected behavior.

**Comment by Praveen2645** [comment]
forge init --no-commit, this worked for me

**Comment by mandatedisrael** [comment]
> This happens when your directory is dirty (has uncommitted files). Run it with `--no-commit`.
> 
> Closing as this is expected behavior.

Yeah, worked like magic, Gracias Eva
