### ISSUE TITLE
The target directory is a part of or on its own an already initialized git repository, and it requires clean working and staging areas, including no untracked files.  Check the current git repository's status with `git status`. Then, you can track files with `git add ...` and then commit them with `git commit`, ignore them in the `.gitignore` file, or run this command again with the `--no-commit` flag.

### ISSUE THREAD

**Issue by AdMub** [foundry-rs/foundry#5174]
### Component

Forge, Cast, Anvil, Foundryup, Chisel

### Describe the feature you would like

The target directory is a part of or on its own an already initialized git repository,
and it requires clean working and staging areas, including no untracked files.

Check the current git repository's status with `git status`.
Then, you can track files with `git add ...` and then commit them with `git commit`,
ignore them in the `.gitignore` file, or run this command again with the `--no-commit` flag.

**Comment by Evalir** [comment]
Closing. Duplicate.
