### ISSUE TITLE
Failed to create wallet from private key. Private key is invalid hex: Odd number of digits

### ISSUE THREAD

**Issue by deep0072** [foundry-rs/foundry#5176]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (cf104a5 2023-06-18T00:07:31.412385891Z)

### Operating System

Windows

### Describe the bug

when I raan this 

```cast send 0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9 'setFavNUmber(uint256)' 786 --rpc-url $RPC_URL --private-key $PRIVATE_KEY ```

though i can echo out the privatekey but its showing error in above given command

```Failed to create wallet from private key. Private key is invalid hex: Odd number of digits```

**Comment by Evalir** [comment]
Hey, this means that the private key might be incomplete—are you sure the `env` is correct? can you try putting it in a wallet and see what happens?

**Comment by deep0072** [comment]
Now its working fine. Don't know. I just restart the system.😀
