### ISSUE TITLE
The application panicked (crashed)

### ISSUE THREAD

**Issue by ololade97** [foundry-rs/foundry#5187]
This is the message I get from the terminal while running "forge test" in VSCode:

The application panicked (crashed).
Message:  byte index 56 is not a char boundary; it is inside '’' (bytes 55..58) of `61 |         require(_size > 0, "SortedTroves: Size can’t be zero");`
Location: /home/ololade/.cargo/git/checkouts/ethers-rs-c3a7c0a0ae0fe6be/79c1953/ethers-solc/src/artifacts/mod.rs:2095

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

**Comment by Evalir** [comment]
Could you provide more info on what went wrong? A minimal repro maybe?

**Comment by Evalir** [comment]
Closing, no followup.
