### ISSUE TITLE
`nonce` of contract deployer not updated correctly when deploying contracts with externally linked libraries when using `forge test`

### ISSUE THREAD

**Issue by WEI-NERD** [foundry-rs/foundry#5191]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (794f831 2023-06-21T00:11:25.200247000Z)

### What command(s) is the bug in?

`forge test`

### Operating System

macOS (Apple Silicon)

### Describe the bug

I've created a [demo](https://github.com/WEI-NERD/forge-test-bug-nonce) with this issue for reproduction.
When using `forge test`, the `nonce` of the contract deployer is not updated correctly when deploying contracts with externally linked libraries.
```Solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

library A {
    function a() public pure returns (uint256) {
        return 1;
    }
}

library B {
    function b() public pure returns (uint256) {
        return 2;
    }
}

contract Counter {
    function lib() public pure returns (uint256, uint256) {
        uint256 a = A.a();
        uint256 b = B.b();
        return (a, b);
    }
}
```
A `counter` contract that uses two externally linked libraries is deployed with a new account in `forge test`, the result shows that the `nonce` of the deployer before the deployment is 0 and 1 after the deployment, and the address of the counter is indeed calculated with the deployer's address and `nonce` of 0.

![image](https://github.com/foundry-rs/foundry/assets/131971450/4b625bda-03fd-441b-98fa-88c6754910a6)
![image](https://github.com/foundry-rs/foundry/assets/131971450/6cfb9eb3-0deb-42d2-95d0-9304f2dca1ab)

However, when deploying to test net, the script result shows that library A takes up the address when deployer's `nonce` is 0, and counter is deployed to the address calculated with `nonce` 2.

![image](https://github.com/foundry-rs/foundry/assets/131971450/71402d2d-65eb-422c-9349-e4681f361767)
![image](https://github.com/foundry-rs/foundry/assets/131971450/d5070df8-12fe-41b4-87bd-f168bf701ad6)

The account link is https://goerli.etherscan.io/address/0xaE0bDc4eEAC5E950B67C6819B118761CaAF61946.

**Comment by mds1** [comment]
@Evalir I haven't tried to repro this one but just calling it out since I think we made linked lib changes recently, so maybe this is related
