### ISSUE TITLE
anvil get nth account and private key 

### ISSUE THREAD

**Issue by huahuayu** [foundry-rs/foundry#5196]
### Component

Anvil

### Describe the feature you would like

When you use `anvil` cmd, it simply lists 10 account & private key for test use, which is straightforward.

But if I want to write a script, sometimes I need to get one of the accounts, either I have to use text grep search or manually copy it. It's not good for automation.

What if there's a cmd like 

```bash
$ anvil --account 0
```

and the output like
```
0x00000000account0 privatekey
```

**Comment by mattsse** [comment]
the node does not expose private keys, but you get a list of all accounts with `eth_accounts` 

I suppose this is for `sendTransaction`?
then you can set the from field to `eth_accounts[idx]`

**Comment by Evalir** [comment]
Closing—mattsse provided the answer!

**Comment by dpaiton** [comment]
@Evalir @mattsse this does not return the private key, correct? Only the [addresses](https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_accounts). Is it possible to get the private keys in a similar way?

**Comment by antazoey** [comment]
Second this. I am only using the Anvil subprocess, no forge.. I am able to re-generate the private keys myself from the accounts ~OR~ parse the subprocess output, but it'd be simpler for my use-case to allow getting the keys via RPC.
