### ISSUE TITLE
Running anvil as execution layer.

### ISSUE THREAD

**Issue by batphonghan** [foundry-rs/foundry#5198]
### Component

Anvil

### Describe the feature you would like

Hi, I'm trying running anvil as execution layer with eth2 client (lighthouse) and got following error:

```
ERRO Unable to get transition config         error: Api { error: ServerMessage { code: -32601, message: "Method not found" } }, service: exec
ERRO Not ready for merge                     hint: try updating Lighthouse and/or the execution layer, info: Could not confirm the transition configuration with the execution endpoint: "EngineError(Api { error: ServerMessage { code: -32601, message: \"Method not found\" } })", service: slot_notifier
```
I assume this kind of setup not support of anvil yet. Would be awesome if we can setup like that.

### Additional context

anvil 0.1.0 (a81d36f 2023-06-22T00:10:39.932374540Z)

**Comment by Evalir** [comment]
This is not possible—Anvil is just a small client that can simulate transactions, just like ganache. It's not the scope to make it a full node—This would fall into Paradigm's reth node.

Closing—out of scope.
