### ISSUE TITLE
Halted execution (code does not return any value)

### ISSUE THREAD

**Issue by adaki2004** [foundry-rs/foundry#5200]
I'd like to report something that we are not able to fully understand and explain within our testing environment (foundry used obv.).

We have a big repository and failing test cases which seems to be (at first glance for sure, but we also spent some hours debugging) a ghost issue - some wild memory violation thing.. (?).

**How to reproduce ?**

This is the repo (+ branch we are seeing this):
https://github.com/taikoxyz/taiko-mono/tree/integrate-new-l3-circuits

1. Clone/Pull branch
2. `cd packages/protocol`
3. `pnpm install`
4. `forge test --match-test 'testOracleProverCannotOverwriteIfSameProof' -vvv`

The 'ugly', monolith codebase should not mislead or distract you, we hunted down where the code halts and it seems it is not related to our codebase but rather a 'generic' WTF happens type. (Again, I might be completely blind on this and reserve the right to be dumb but we could not figure out the root cause.)

In this specific test there are 2 `proveBlock()` calls. 1 is at `line 187` and another at `217`.
The implementation of this can be found in `TaikoL1TestBase.t.sol`. Both should do the exact same, but the second should revert. The problem is not with revert vs. not revert, the problem is that:

1. `proveBlock()` calls` getInstance()`
2. `getInstance()` calls `resolver.resolve("signal_service", false)` on line 243 of `TaikoL1TestBase.t.sol`

At the first proveBlock() it works perfectly fine. The second one tho does not return any value, seems like it 'halts'. When we put debug prints right before the return of that function (`AddressResolver.sol line 55`) it prints the resolved address, but does not return.

Could you help us out investigating what could it be ? A memory violation issue, are we stupid ? :) Or some stack-dept issue.. ?

Thanks in advance !

**Comment by mattsse** [comment]
thanks for flagging,

what's the output you're getting?

**Comment by Evalir** [comment]
Is it possible for you guys to post a small reproduction of this issue, so we can look into this?

**Comment by Evalir** [comment]
Hey @adaki2004 — we'll be looking at this over the next few days!

**Comment by Evalir** [comment]
Closing, stale
