### ISSUE TITLE
forge install from local directory

### ISSUE THREAD

**Issue by wasifferoze** [foundry-rs/foundry#5218]
How can I install package from local repository. Like I have download openzipline contracts and zip file and extracted these now how can I use it with forge install

**Comment by Evalir** [comment]
Please see the `forge install` docs: https://book.getfoundry.sh/reference/forge/forge-install?highlight=install#forge-install

You need to install from a remote git repo, e.g `forge install openzeppelin/openzeppelin-contracts`.
