### ISSUE TITLE
Forge debugger does not load sourcemaps for Seaport deployments

### ISSUE THREAD

**Issue by emo-eth** [foundry-rs/foundry#5224]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (2e18681 2023-06-26T00:15:26.624789000Z)

### What command(s) is the bug in?

forge test --debug

### Operating System

macOS (Apple Silicon)

### Describe the bug

Run the following test with `forge test --debug testSourceMapSeaportX_Y` for each test to observe that there is no source map located for any of the Seaport deployments.

```solidity

contract SeaportSourceMapTest is Test {
    bytes encodedCall;

    function setUp() public {
        vm.createSelectFork(getChain("mainnet").rpcUrl);
        encodedCall = abi.encodeWithSignature("incrementCounter()");
    }

    function testSourceMapSeaport1_1() public {
        (bool success,) =
            0x00000000006c3852cbEf3e08E8dF289169EdE581.call(encodedCall);
        require(success, "Expected call to succeed");
    }

    function testSourceMapSeaport1_4() public {
        (bool success,) =
            0x00000000000001ad428e4906aE43D8F9852d0dD6.call(encodedCall);
        require(success, "Expected call to succeed");
    }

    function testSourceMapSeaport1_5() public {
        (bool success,) =
            0x00000000000000ADc04C56Bf30aC9d3c0aAF14dC.call(encodedCall);
        require(success, "Expected call to succeed");
    }
}
```

It may be worth noting that due to Seaport's complexity, Etherscan had to manually verify the contracts for us, versus relying on the API to do it. This leads to some discrepancies in the compiler information – for example, Seaport 1.4 and 1.5 both specified 2**32-1 optimizer runs, but Etherscan reports 0 and 9999999 respectively.

**Comment by zerosnacks** [comment]
Confirming this is still the case

Findings:

- running with `RUST_LOG=trace` shows that the verified source code from Etherscan is being requested
- `forge clone` is able to clone the verified source code from Etherscan without issue

I'll therefore close it in favor of this more general ticket: https://github.com/foundry-rs/foundry/issues/5435
