### ISSUE TITLE
Halted execution. I test a function and don returns any value and gets stuck during execution.

### ISSUE THREAD

**Issue by RafaTatay** [foundry-rs/foundry#5231]
### Component

Forge, Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

0.2

### What command(s) is the bug in?

forge test 

### Operating System

None

### Describe the bug

Im executing a test. First I deposit ETH into some protocol (The deposit test works) but when I try to execute the withdraw test the execution get stuck. The project use Anvil on Arbitrum, I also tried using a RPC (not Anvil) but I see the same error. So the execution gets stuck. 

I don't know if there are any operations limit. 

![image](https://github.com/foundry-rs/foundry/assets/102363810/db36ca16-017e-4e84-89f1-a4e40083f28e)

**Comment by Evalir** [comment]
You might be getting rate limited your RPC if you're using forking. Could you post a small repro of the issue if possible?

**Comment by GopherJ** [comment]
in the case of rate limit, I think an error should be thrown?

**Comment by GopherJ** [comment]
I disabled rate limit, but my transaction still hangs and only shows logs:


![image](https://github.com/foundry-rs/foundry/assets/33961674/d58ac02b-1a8d-4bd9-91c2-96952f79f2e2)

**Comment by RafaTatay** [comment]
Some help of how i solved it. 

I found a infinite loop in the code and Foundry does not revert. Is like there is no gas limit while testing and if you limit it, it does not work.

This could be interesting to solve. 

=D

**Comment by Evalir** [comment]
Yeah I concur with @RafaTatay — it could be some infinite loop happening that you might not be aware of @GopherJ.

Closing as OP's issue was fixed
