### ISSUE TITLE
intrinsic gas too high

### ISSUE THREAD

**Issue by GopherJ** [foundry-rs/foundry#5237]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (31d6498 2023-06-28T00:10:20.700537031Z)

### What command(s) is the bug in?

	anvil \ 		$(if $(FORK),--fork-url https://eth-$(FORK).alchemyapi.io/v2/$(ALCHEMY_KEY) --chain-id 522 --no-rate-limit,--chain-id 31337) \ 		$(if $(FORK_BLOCK_NUMBER),--fork-block-number $(FORK_BLOCK_NUMBER),) \ 		$(if $(DEPLOYER_MNEMONIC),--mnemonic "${DEPLOYER_MNEMONIC}",--mnemonic "test test test test test test test test test test test junk") \ 		--host 0.0.0.0 \ 		--state-interval 60 \ 		--dump-state state.json \ 		$(if $(wildcard state.json),--load-state state.json,) \ 		--disable-block-gas-limit \ 		--code-size-limit 100000 \ 		--timeout 9000000

### Operating System

Linux

### Describe the bug

I got this error while sending a giant transaction but it also happens randomly for smaller transactions

**Comment by lpinilla** [comment]
x2

**Comment by Evalir** [comment]
Could we get a small repro of this happening?

**Comment by PaulRBerg** [comment]
Just bumped into this error while attempting to deploy this [`ERC20GodMode`](https://github.com/PaulRBerg/prb-contracts/blob/878032e1925f5366e52ce7a93bb6a12c9a4098e4/src/token/erc20/ERC20GodMode.sol) contract with Ledger:

```sh
forge create src/token/erc20/ERC20GodMode.sol:ERC20GodMode \
--ledger \
--rpc-url "localhost" \
--constructor-args \
"Test token" \
"TKN" \
18
```

Running the command without the `--ledger` flag works.

Error:

> (code: -32000, message: intrinsic gas too high, data: None)

**Comment by Florian-S-A-W** [comment]
I also get this error when fetching large amounts of data. For me the steps were:
- Deploy a contract that fetches large amounts of data (around 5GB over 7M calls) on an anvil instance that forks from a node in my local network. 
- When fetching (forking) from the node in the local network with ~1ms latency everything is fine. 
- When connecting to an RPC provider via internet (or the same node over VPN) with significant latency, I get 'intrinsic gas too high' for every 10th-20th call.
- When I rerun the calls, it executes 10-100 times faster as anvil doesn't have to fetch the data again. Nevertheless the data from the anvil instance is broken permanently, meaning I get the same error for the same calls every time. 
- Creating a fresh instance of anvil and running again on the 1ms latency forked node "fixes" the problem.

Not a huge issue for me but maybe it helps in identifying the problem.

**Comment by DeVazzi** [comment]
I also got that error message when trying to simulate a transaction a local anvil fork of mainnet

**Comment by brech1** [comment]
I ran into this issue while using new accounts with low funds, sending more ETH to them seem to have fixed it.

**Comment by Evalir** [comment]
Closing as stale—we've had several fixes related to these, so similar errors now mean different things probably. We'd rather get new issues filed with up-to-date details

**Comment by jimjimvalkema** [comment]
ran into this issue and sending a couple txs with metamask fixed it. Maybe forge create is using a nonce that is too high?  
Sorry only just started using foundry 😅
