### ISSUE TITLE
NonceTooLow

### ISSUE THREAD

**Issue by GopherJ** [foundry-rs/foundry#5239]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (31d6498 2023-06-28T00:10:20.700537031Z)

### What command(s) is the bug in?

```
.PHONY: anvil
anvil:
	anvil \
		$(if $(FORK),--fork-url https://eth-$(FORK).alchemyapi.io/v2/$(ALCHEMY_KEY) --chain-id 522 --no-rate-limit,--chain-id 31337) \
		$(if $(FORK_BLOCK_NUMBER),--fork-block-number $(FORK_BLOCK_NUMBER),) \
		$(if $(DEPLOYER_MNEMONIC),--mnemonic "${DEPLOYER_MNEMONIC}",--mnemonic "test test test test test test test test test test test junk") \
		--host 0.0.0.0 \
		--state-interval 60 \
		--dump-state state.json \
		$(if $(wildcard state.json),--load-state state.json,) \
		--disable-block-gas-limit \
		--code-size-limit 100000 \
		--timeout 9000000
```
### Operating System

Linux

### Describe the bug

```javascript
    GLOBAL_OVERRIDES.nonce = (await user.getTransactionCount()) + 1;
    await waitForTx(
      await pool
        .connect(user)
        .method1(
          pick(params, ["cTokens", "cTypes", "cAmountsOrTokenIds", "dTokens"]),
          GLOBAL_OVERRIDES
        )
    );
```
previously I dont need to edit the nonce but today for some of my transactions I have to edit the nonce to be `transactionCount + 1`, otherwise it fails with:

```
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value:
backend: failed while inspecting: Transaction(NonceTooLow { tx: 2512, state: 2513 })
Location: /home/runner/work/foundry/foundry/cli/src/cmd/cast/run.rs:179


```

**Comment by GopherJ** [comment]
@mattsse it's just a normal transaction, nothing special, so I dont really know why most of the transactions are fine. Other transactions failed with this error

**Comment by GopherJ** [comment]
I can simulate transaction using `cast + hardhat` but not `cast + anvil`

**Comment by Evalir** [comment]
Closing as stale—we've had several fixes related to these, so similar errors now mean different things probably. We'd rather get new issues filed with up-to-date details

**Comment by GopherJ** [comment]
@Evalir I think this issue should be reopen as I can still reproduce it with latest foundry

**Comment by GopherJ** [comment]
```
Executing previous transactions from the block.
Error:
backend: failed while inspecting: Transaction(NonceTooLow { tx: 4, state: 5 })
```
