### ISSUE TITLE
forge selector upload doesn't support errors

### ISSUE THREAD

**Issue by thedavidmeister** [foundry-rs/foundry#5241]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e6574c9 2023-06-25T00:10:48.177241000Z)

### What command(s) is the bug in?

forge selectors upload --all

### Operating System

macOS (Apple Silicon)

### Describe the bug

This issue makes me think it is expected that error selectors are uploaded

https://github.com/foundry-rs/foundry/issues/5012

e.g.

> Supports additive --functions, --errors, --events flags to specify a subset of the above, e.g. if you only want error selectors

But from what I can see only functions and event selectors are uploaded.

Definitely makes sense to be able to upload and reference error selectors e.g. https://github.com/foundry-rs/foundry/issues/3656

I wasn't sure whether to file this as a bug or feature request, but it was unexpected enough for me to feel like it's more of a bug.

**Comment by thedavidmeister** [comment]
i think maybe it does support errors now, but not explicitly

at least, when i go to openchain.xyz i can see the error selectors listed as function selectors

**Comment by DaniPopes** [comment]
Yes, see https://github.com/foundry-rs/foundry/issues/5293#issuecomment-1954709411
