### ISSUE TITLE
EvmError: Revert when calling new Curve Tricrypto pools

### ISSUE THREAD

**Issue by pierremarsotlyon1** [foundry-rs/foundry#5242]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (31d6498 2023-06-28T00:19:43.942564000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

Contract code : 

`pragma solidity ^0.8.19;
contract LoanManagerTest is Test {
    address constant TRICRYPTO_USDT = address(0x7F86Bf177Dd4F3494b841a37e810A34dD56c829B);

    function setUp() public {
    }

    function testSetupLoan() public {
        uint256 dy = ITricrypto(TRICRYPTO_USDT).get_dy(0, 2, 39983312567);
        console.log(dy);
    }
}`

I got : 
`Traces:
  [120] LoanManagerTest::setUp() 
    └─ ← ()

  [4949] LoanManagerTest::testSetupLoan() 
    ├─ [1849] 0x7F86Bf177Dd4F3494b841a37e810A34dD56c829B::get_dy(0, 2, 39983312567 [3.998e10]) 
    │   └─ ← ()
    └─ ← "EvmError: Revert"`

But working on etherscan
<img width="348" alt="Capture d’écran 2023-06-28 à 15 59 38" src="https://github.com/foundry-rs/foundry/assets/24700690/c7a56730-1ac3-4923-a1e2-d019416892fa">

**Comment by Evalir** [comment]
Are you using forking or an external rpc? If so, you'll use a local instance and the contracts won't be deployed

**Comment by pierremarsotlyon1** [comment]
yes i'm using a fork url : 
forge test --fork-url https://eth-mainnet.g.alchemy.com/v2/....

Fork created today

**Comment by Evalir** [comment]
Closing—stale and not enough info
