### ISSUE TITLE
Allow cast to get function sig from local ABI

### ISSUE THREAD

**Issue by ryanio** [foundry-rs/foundry#5244]
### Component

Cast

### Describe the feature you would like

I have a contract where I hid some functions from the public interface for brevity, but I do have defined in a separate interface (that is not inherited by the contract).

I see that `cast` can get the fn sig from etherscan (which is very cool), but for my use case it'd be really powerful to also scan local ABI in `out/` or specify e.g. `--abi IHiddenInterface` to derive the fn sig locally. This would be really helpful for complex struct params that are not so easy to type out.

**Comment by Sabnock01** [comment]
Isn't this already possible under `forge inspect methodIdentifiers`?

**Comment by mds1** [comment]
> Isn't this already possible under `forge inspect methodIdentifiers` or am I missing something?

IIUC then yes. @ryanio Running `forge inspect IHiddenInterface methodIdentifiers` will do what you want, so going to close this, but let me know if I misunderstood

**Comment by ryanio** [comment]
ah thank you, yes methodIdentifiers works great didn't know about that one. is there a way to get the return values it expects too though, for formatting the response properly?

**Comment by mds1** [comment]
Can you expand on what you're trying to do? The return values are part of the ABI which can be found in the artifact or with `forge inspect IHiddenInterface abi`

**Comment by ryanio** [comment]
@mds1 yes for sure, primarily I am trying to call a getter that returns a complex struct:

```bash
➜  seadrop git:(v2) ✗ cast call 0x232e97b08266510de8f43f179fd0efbfe2910975 "getPublicDrop(uint256)(uint80,uint80,uint40,uint40,bool,address,uint24,uint24,uint16,uint16,uint16)" 0 --rpc-url $MAINNET_RPC_URL
115000000000000000
115000000000000000
1688065200
1688670000
true
0x0000000000000000000000000000000000000000
1
20
10000
10000
500
```

I haven't found an easy way to get the formatted return value for the `(uint80,uint80,uint40,uint40,bool,address,uint24,uint24,uint16,uint16,uint16)` part, or something cool like:

`cast call 0x232e97b08266510de8f43f179fd0efbfe2910975 $(forge inspect IERC1155SeaDrop methodIdentifiers getPublicDrop) 0 --rpc-url $MAINNET_RPC_URL`

where the methodIdentifier would also contain the return values. Maybe something like this exists you can point me to? Regardless not a huge priority, moreso a unique challenge since my public interface on etherscan isn't exhaustive of everything it supports.

**Comment by ryanio** [comment]
this was a narrow need of mine for a certain type of contracts i was developing, closing since it probably isn't needed for most others and not worth prioritizing. thanks for always listening!
