### ISSUE TITLE
Options for colorized output and/or do not use white

### ISSUE THREAD

**Issue by aathan** [foundry-rs/foundry#5254]
### Component

Forge

### Describe the feature you would like

I think it's forge build that colorizes errors generated by solc. It looks like white is sometimes used, and for those of us that use a white background in our terminal, that's invisible. Perhaps avoid white and black as colors and/or expose color options in foundry.toml?

**Comment by DaniPopes** [comment]
Do you have an example output or a repro for it? I'll take a look tomorrow

**Comment by aathan** [comment]
https://github.com/ethereum/solidity/issues/14358#issuecomment-1612350239

**Comment by DaniPopes** [comment]
"info" error severity in Solidity [is colored with white](https://github.com/ethereum/solidity/blob/a297a687261a1c634551b1dac0e36d4573c19afe/liblangutil/SourceReferenceFormatter.cpp#L79) ([code 37](https://github.com/ethereum/solidity/blob/2f451a186b23bd2ec22c2a594b7cafa8a92e7597/libsolutil/AnsiColorized.h#L44)) so I just copied that from them ([ethers-rs](https://github.com/gakonst/ethers-rs/blob/df165b84229cdc1c65e8522e0c1aeead3746d9a8/ethers-solc/src/artifacts/mod.rs#L2165)).

**Comment by aathan** [comment]
I'll spend some time re-familiarizing myself with terminal color theory (i.e., I am by no means an expert in this area). My original bug post made some potentially incorrect assumptions, one of which was that the invisible color was "white". At the alacritty site you posted, if the octal `037` examples visible when you scroll down correspond to the `code 37`, they label this not as white but "light grey." Perhaps this is alacritty's attempt to avoid having a forground color which is pure white? No idea here.

Anyway, thinking more clearly about this problem, what is to be avoided really is the use of a color which is equal to the background color of the current terminal. If there exists a way to query the latter, the former can be avoided. I'm having trouble remembering if there is a mechanism for the flow of terminal information in that direction, but there must be, since at least terminal window size can be obtained by editors.

I guess this is worth noting to the solidity team as well. I'll open a bug linking this bug for them.

**Comment by aathan** [comment]
Also, for anyone seeing this: see solc's `--no-color`
