### ISSUE TITLE
libraries的使用问题

### ISSUE THREAD

**Issue by xf8259980** [foundry-rs/foundry#5255]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8bbde62 2023-06-26T07:47:04.57225Z)

### What command(s) is the bug in?

forge create

### Operating System

macOS (Intel)

### Describe the bug

在forge create 的过程中，需要先把library部署。 于是我部署并验证了 library文件。并得到了地址0x970f2af442e7a6c7c6abb9367b11ac16a5daca1f  。 但是之后的部署主合约的过程中，我使用 
forge create --rpc-url https://eth-sepolia.g.alchemy.com/v2/xxx --private-key xxx  --etherscan-api-key xxx --libraries src/expand/MerkleVerifier.sol:MerkleVerifier:0x970f2af442e7a6c7c6abb9367b11ac16a5daca1f --use 0.8.17 --optimize --optimizer-runs 200 src/Test.sol:A 

会提示  Fail - Unable to verify. Please check for missing Library or invalid name (i.e names are case senstive). Library was required but suitable match not found    可我感觉 --libraries 的用法好像并没有错

**Comment by WEI-NERD** [comment]
If you are deploying contracts that need external libraries, specify in foundry.toml `libraries` field or use `--libraries` when `forge create`, reference in the `Foundry book` are listed below. Please RTFM, and please use English for better communication. Thanks.
https://book.getfoundry.sh/reference/forge/forge-create?highlight=linking#description
https://book.getfoundry.sh/reference/config/solidity-compiler#libraries

**Comment by xf8259980** [comment]
> 

thinks. I tried to build the library and it worked.but i used --libraries src/expand/xxx.sol:xxx:0x...  ，always prompts me Fail - Unable to verify. Please check for missing Library or invalid name (i.e names are case senstive). Library was required but suitable match not found.    path and library name all right，address also checked. I don't understand what's wrong

**Comment by WEI-NERD** [comment]
I had the same issue, this could be a potential bug. I used `forge script` as a workaround. Imo, it's always better to use `forge scrip` than `forge create`.

**Comment by Evalir** [comment]
Closed with recent linking fixes
