### ISSUE TITLE
Foundry fuzz test time doubled over the last 2-3 days

### ISSUE THREAD

**Issue by pcaversaccio** [foundry-rs/foundry#5262]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

`forge 0.2.0 (0396e22 2023-07-01T00:04:34.413676821Z)`

### What command(s) is the bug in?

`forge test`

### Operating System

Linux

### Describe the bug

For context: https://twitter.com/pcaversaccio/status/1675085794963337216

See my repo actions: https://github.com/pcaversaccio/snekmate/actions/workflows/test-contracts.yml

The same is true for [OpenZeppelin](https://github.com/OpenZeppelin/openzeppelin-contracts/actions?query=branch%3Amaster) or [Solady fuzz tests](https://github.com/Vectorized/solady/actions) (cc @Vectorized)

![image](https://github.com/foundry-rs/foundry/assets/25297591/dfde7b68-8873-460f-a799-e3c1b3ee23a3)
![image](https://github.com/foundry-rs/foundry/assets/25297591/c0b6c3fd-ef57-48ad-a9f4-75601f81e009)

Maybe that [PR](https://github.com/foundry-rs/foundry/pull/5246) triggered the issue?

**Comment by pcaversaccio** [comment]
@DaniPopes already did a preliminary analysis (posting this here for completeness):

```bash
here's what I have so far on snekmate
1. nightly-31d6498c79af595577f200fc2136b31f43885397: forge test  136,57s user 7,99s system 1036% cpu 13,944 total
2. nightly-f9fc9294d480c69a51837a586040ffb51d3e57dc: forge test  203,52s user 8,39s system 1365% cpu 15,515 total
```

https://github.com/foundry-rs/foundry/compare/31d6498c79af595577f200fc2136b31f43885397...f9fc9294d480c69a51837a586040ffb51d3e57dc

**Comment by plotchy** [comment]
Really sorry to see this. Based on recent prs it would make sense #5246 caused the time increase. 

Some thoughts on what may be the cause specifically:
- Each value has in `state` has comparisons to `U256::zero()` and `U256::max()`
    - match on value does effectively the same thing yeah?
- ~3x Vec pushes in `collect_push_bytes` -> leading to 1-2+ Vec reallocs in the fn
    - an iterator over the original `bytes` output would do a similar job without the reallocs
~3x HashSet insertions into `state`
    - Not sure how to get increase performance on this
- The fuzz corpus could be providing values that get deeper into the fns, executing more opcodes


OTOH, causing a doubling in time seems really unexpected based on these changes. There could be side effects I'm not aware of. Spitballing here - `proptest` generation time could be linear on `state` size?

In any case, @mds1 had good instinct with fearing fuzz merges without extensive benching on daedaluzz/etc. It makes sense to revert the pr and I can work on testing it more rigorously with metrics of time/findings/etc. 🫡

**Comment by DaniPopes** [comment]
It is not #5246, I compared the affected nightlies (https://github.com/foundry-rs/foundry/compare/31d6498c79af595577f200fc2136b31f43885397...f9fc9294d480c69a51837a586040ffb51d3e57dc) and also manually reverting the #5246 commit does not fix the regression.

**Comment by DaniPopes** [comment]
It's very likely #5205, which added an extra run to each fuzz tests but I believe that might be unnecessary. cc @Evalir we can probably just check the final fuzz result instead of running it twice

**Comment by Evalir** [comment]
Thanks @DaniPopes — actually pretty surprised fuzzing with only one run adds so much overhead—the intention was to cut fuzzing time by skipping the whole test altogether if it's marked as skipped. Let's patch the fuzzer ASAP then so this doesn't keep happening and CI comes back to normal again 🙏

**Comment by DaniPopes** [comment]
I guess building the state, dictionary etc is very expensive. Might be worth looking into

**Comment by Evalir** [comment]
Yeah agreed, I definitely wanna look into it. Even if just patching solves the issue I'd love to see what causes the overhead on the fuzz runner and improve it—looks to me like we can go even faster
