### ISSUE TITLE
--debug abort

### ISSUE THREAD

**Issue by degatchi** [foundry-rs/foundry#5272]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (d369d24 2023-07-02T00:05:10.773939000Z)

### What command(s) is the bug in?

forge test --match-test x -vvvv --fork-url https://rpc.flashbots.net --debug x

### Operating System

macOS (Apple Silicon)

### Describe the bug

```
[⠒] Compiling...
No files changed, compilation skipped
2023-07-02T12:51:32.303362Z ERROR forge::runner: setUp failed reason="EvmError: Revert" contract=0x7fa9385be102ac3eac297483dd6233d62b3e1496
The application panicked (crashed).
Message:  Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.
Location: /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/mod.rs:65

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

```

Whenever i run `--debug x` on my test it gives me this error message.

**Comment by degatchi** [comment]
Is there any way to go down a version? This wasn't happening before I did `foundryup`.

**Comment by mattsse** [comment]
check latest nightly, should include the fix https://github.com/foundry-rs/foundry/pull/5273

**Comment by owieth** [comment]
Hey @mattsse 
I get a similar error when running my test suite since today, using `forge 0.2.0 (9aefa43 2023-07-03T00:07:40.921128000Z)`. The exact error is 

`2023-07-03T14:19:08.920071Z ERROR forge::runner: setUp failed reason="82314932:" contract=0x7fa9385be102ac3eac297483dd6233d62b3e1496`

I found out that a code snipped in my contracts triggers this error:

```solidity
        if (!checkIfAddressIsWhitelisted(_from)) {
            revert TransferModule__AddressIsNotWhitelisted(_from);
        } else if (!checkIfAddressIsWhitelisted(_to)) {
            revert TransferModule__AddressIsNotWhitelisted(_to);
        }
```

When the ```!``` is removed the tests run successfully 🤔

```solidity
        if (checkIfAddressIsWhitelisted(_from)) {
            revert TransferModule__AddressIsNotWhitelisted(_from);
        } else if (checkIfAddressIsWhitelisted(_to)) {
            revert TransferModule__AddressIsNotWhitelisted(_to);
        }
```

Full Code:

```solidity
    function checkTransferability(address _from, address _to) public view {
        if (!checkIfAddressIsWhitelisted(_from)) {
            revert TransferModule__AddressIsNotWhitelisted(_from);
        } else if (!checkIfAddressIsWhitelisted(_to)) {
            revert TransferModule__AddressIsNotWhitelisted(_to);
        }
    }

    function checkIfAddressIsWhitelisted(address _address) public view returns (bool) {
        return s_whitelist[_address];
    }
```

**Comment by DaniPopes** [comment]
Are you experiencing the *panic* above, which says the application crashed? If not please open another issue @owieth

**Comment by owieth** [comment]
@DaniPopes Okey sorry was confused by this error and solved my test suite now (still don't know why this error appeared 🤔). 

BTW it wasn't panicking, only this error: ```2023-07-03T14:19:08.920071Z ERROR forge::runner: setUp failed reason="82314932:" contract=0x7fa9385be102ac3eac297483dd6233d62b3e149```

**Comment by Evalir** [comment]
Closing, stale
