### ISSUE TITLE
4byte uses outdated db, does not find sig that openchain.xyz can find

### ISSUE THREAD

**Issue by naps62** [foundry-rs/foundry#5274]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

cast 0.2.0 (288ab2e 2023-07-02T13:12:31.567912304Z)

### What command(s) is the bug in?

cast 4byte

### Operating System

Linux

### Describe the bug

The docs mention that `4byte` commands use https://sig.eth.samczsun.com; Clicking that link now redirects to https://openchain.xyz/signatures, so I initially assumed it was the same DB but migrated or rebranded.

however `cast` fails to find a sig that the website does find.
According to @gakonst , sam stopped maintained his db. I don't know what the exact action here is, but I'm available to help if there are some pointers

![image](https://github.com/foundry-rs/foundry/assets/283819/d0e13909-c455-491b-9930-2ddc7a63b992)

**Comment by Evalir** [comment]
thank you for filing! perhaps it's time to move over from db

@mattsse do you have some context here? i thought this db was still maintained

**Comment by gakonst** [comment]
@samczsun Is this as simple as just changing the URL? pls advise

@Evalir let's get this in before 1.0

**Comment by naps62** [comment]
was looking into this. appears to have been fixed in #4177
