### ISSUE TITLE
Compile error should include more information about origin

### ISSUE THREAD

**Issue by shazow** [foundry-rs/foundry#5276]
### Component

Forge

### Describe the feature you would like

When doing `forge build` on a contract repo that has some stack-too-deep scenarios, it's unclear which contracts are causing the error:

```
$ forge build --offline
[⠔] Compiling...
[⠑] Compiling 38 files with 0.8.19
[⠊] Solc 0.8.19 finished in 5.14s
Error:
Compiler run failed:
Error: Compiler error (/solidity/libyul/backends/evm/AsmCodeGen.cpp:63):Stack too deep. Try compiling with `--via-ir` (cli) or the equivalent `viaIR: true` (standard JSON) while enabling the optimizer. Otherwise, try removing local variables. When compiling inline assembly: Variable pos is 4 slot(s) too deep inside the stack. Stack too deep. Try compiling with `--via-ir` (cli) or the equivalent `viaIR: true` (standard JSON) while enabling the optimizer. Otherwise, try removing local variables.
```

I'm not sure if the compiler backend interface would allow surfacing this information, but would be useful if it does. Perhaps one solution is having a verbose mode for build that prints contracts it's processing as it goes.

**Comment by shazow** [comment]
Alternatively, would be nice if `forge build` could allow limiting which contracts get compiled, so help track down which one is causing problems. Either glob-style like `forge test` or taking an optional list of paths to compile.

**Comment by shazow** [comment]
This one looks related: https://github.com/foundry-rs/foundry/issues/559

**Comment by mds1** [comment]
Unfortunately solc does not provide more info about the location of the stack too deep, so there's not much we can do here. See https://github.com/ethereum/solidity/issues/13938 to learn more

> Alternatively, would be nice if `forge build` could allow limiting which contracts get compiled, so help track down which one is causing problems. Either glob-style like `forge test` or taking an optional list of paths to compile.

This is coming soon, see https://github.com/foundry-rs/foundry/pull/5267
