### ISSUE TITLE
feat(forge): make `--priority-gas-price` available in `forge script`

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/foundry#5281]
### Component

Forge

### Describe the feature you would like

The `--priority-gas-price` flag seems to be available only for the `forge create` command:

https://book.getfoundry.sh/reference/forge/forge-create?highlight=priority#options

Running `forge script --help` does not list this flag:

https://app.warp.dev/block/8XMHLZq19VYER8fe5XpURz

### Additional context

Output of `forge --version`:

```text
9aefa43 2023-07-03T00:07:40.921128000Z
```

**Comment by ultrasecreth** [comment]
+1, I think this is very important, I've been deploying some contracts to optimism, and the default 3 Gwei tip is many orders of magnitude higher than the gas price of about 60 Wei, so it costed me infinitely more.

**Comment by Sabnock01** [comment]
Do you mind if I take this one @Evalir ?

**Comment by Evalir** [comment]
oh actually was just finishing this one @Sabnock01 sorry about this! but there are quite a few other ones open that you could take a stab 🙏

**Comment by NavalRavikant** [comment]
I just wasted $200 deploying contracts because of same issue on BASE (optimism based).

This is really important. I'm forced to switch to Hardhat now until it's fixed.

**Comment by PaulRBerg** [comment]
> I just wasted $200 deploying contracts because of same issue on BASE

ditto

**Comment by mattsse** [comment]
ah yikes

@Evalir let's fix this

**Comment by ultrasecreth** [comment]
> ah yikes
> 
> @Evalir let's fix this

Also when you do so, pls pls make sure you look at the chain you're interacting with.
What I mean is that there's prob no reason to even set a tip on Optimism and Arbitrum, so the default should be zero for those chains (and any other fork/similar ones).

This should be a thing done across the board, to include `cast send` and others, surprisingly enough none of the big wallets seems to be handling this correctly, leading to what I believe is multi-million loses for the users of those L2s, let's not get foundry on the same bag pls :) 

More info here: https://twitter.com/ultrasecreth/status/1687785758755622912?s=20
