### ISSUE TITLE
feat(forge): `script` should not default to `run()` if contract has only one function with another signature

### ISSUE THREAD

**Issue by klkvr** [foundry-rs/foundry#5282]
### Component

Forge

### Describe the feature you would like

Let's take following script as an example:
```solidity
contract MintTokens is Script {
    function run(address token, uint256 amountToMint) {
        ...
    }
}
```
Right now, to run it I have to run following command: 
`forge script MintTokens <token_address> <amount_to_mint> --sig 'run(address,uint256)'`

If I run just `forge script MintTokens <token_address> <amount_to_mint>` it fails with error `Function run() is not implemented in your script.`

It would be handy if in case when script contract has only one function, forge defaulted to it and not to `run()`

**Comment by Evalir** [comment]
I don't think we'd wanna do this—it's good for consistency and determinism's sake to always default to a certain function and let the user _explicitly_ override this. This would be a very minimal UX gain that could introduce footguns.

Closing for lack of appetite for now.

**Comment by mds1** [comment]
+1 to @Evalir, this would introduce a footgun where the behavior of a `forge script` invocation is dependent on the code itself, so adding a second method called `run` at a later date changes behavior, which seems dangerous
