### ISSUE TITLE
incorrect docs for vm.expectRevert

### ISSUE THREAD

**Issue by thedavidmeister** [foundry-rs/foundry#5288]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (42fb694 2023-07-04T00:04:51.760418000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

The docs state that string literals are supported by `vm.expectRevert`

<img width="857" alt="Screenshot 2023-07-04 at 11 22 22" src="https://github.com/foundry-rs/foundry/assets/629710/7880ce46-2c5d-4aae-8a14-d93c5f8b6a9b">

https://book.getfoundry.sh/cheatcodes/expect-revert

But actually it seems only the form where you first cast the string to bytes like `vm.expectRevert(bytes("foo"))` is supported

```
Compiler run failed:
Error (6675): Member "expectRevert" not unique after argument-dependent lookup in contract Vm.
  --> test/concrete/Foo.t.sol:26:9:
   |
26 |         vm.expectRevert("foo");
```

**Comment by klkvr** [comment]
Actually, `vm.expectRevert` supports only `bytes4` and `bytes` inputs. But you are able to pass string literals to it because Solidity allows implicit casting of string literals into bytes.

The error you mentioned is happening because Solidity allso allows implicit casting of strings with length <= 4 into bytes4. 

In this case possible workaround would be to use `vm.expectRevert(bytes("foo"))`

**Comment by thedavidmeister** [comment]
hmm, ok, not sure if it's worth mentioning in docs

**Comment by xeno097** [comment]
It is mentioned in the docs nearly at the bottom of the page although maybe an improvement could be made to clarify that if a string that is less than or equal to 4 bytes long is used, an explicit conversion should be performed to help the compiler decide which override should be used (The docs say that you should do it in case you use a 4 char long string).

![image](https://github.com/foundry-rs/foundry/assets/42520800/40cb722d-bc30-4b6c-80de-57615812ba2c)

**Comment by thedavidmeister** [comment]
> It is mentioned in the docs nearly at the bottom of the page although maybe an improvement could be made to clarify that if a string long <= 4 bytes is used, an explicit conversion should be performed to help the compiler decide which override should be used (The docs say that you should do it in case you use a 4 char long string).
> 
> ![image](https://user-images.githubusercontent.com/42520800/251018672-40cb722d-bc30-4b6c-80de-57615812ba2c.png)

ok cool, i'm happy to close this out then, i must have missed that when i was reading it
