### ISSUE TITLE
Failed verification passes with "Response: `OK`"

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/foundry#5289]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (42fb694 2023-07-04T00:04:51.760418000Z)

### What command(s) is the bug in?

forge verify-contract

### Operating System

macOS (Apple Silicon)

### Describe the bug

Steps to reproduce:

1. Write a contract (any contract)
2. Enable the optimizer and set it to any number of runs, e.g. 500 runs
3. Run `verify-contract` with a different number of optimizer runs, e.g. 2,000 runs
4. The command will print a message like this:

```text
Submitting verification for [src/Contract.sol:Contract] <ADDR>.
Submitted contract for verification:
	Response: `OK`
	GUID: `vhszijnisxwyxaysfinpdewnec1gfta9jp4dvuc2kw1jtrfu4u`
	URL: <UDR>
```

**Comment by klkvr** [comment]
I think this 'OK' response indicates that request for verification submission was succesful. But the result of request processing may still be different. You can wait for verification processing and see real status via `--watch` flag

**Comment by PaulRBerg** [comment]
Oh, I didn't know about the `--watch` flag - thanks for the tip!

After adding it, I started seeing messages like this:

```text
Details: `Pending in queue`
```

So all good now.
