### ISSUE TITLE
Absolute project paths in submodules: `Invalid implicit conversion from Type to Type requested`

### ISSUE THREAD

**Issue by Rubilmax** [foundry-rs/foundry#5290]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (42fb694 2023-07-04T00:05:23.262068000Z)

### What command(s) is the bug in?

forge build

### Operating System

None

## Reproducing the bug

1. Clone repository https://github.com/Rubilmax/forge-import-bug
2. Clone submodules `forge install`
3. Run `forge build`

## What's expected

The contract compiles successfully, because the types used should be equal (`Type1` is indeed [imported](https://github.com/Rubilmax/forge-import-bug/blob/86510e45a2c4e5a90210080f4fd3ebd0b771c729/src/Contract.sol#L6) from the same file it is [defined and used in the submodule](https://github.com/Rubilmax/forge-import-bug-submodule/blob/420734f4ed3afd40a0fa120fe56997fd1fed3b9b/src/libraries/Types.sol), `Type2` as well)

## Leads

It seems forge is adding implicit remappings in submodules: `src/` & `test/` which are messing up with import resolutions...
If the remapping `src/=lib/forge-import-bug-submodule/src/` is added to [forge-import-bug/remappings.txt](https://github.com/Rubilmax/forge-import-bug/blob/main/remappings.txt) then the contract compiles, but it's not a desirable behavior as far as `src/` should map to `forge-import-bug/src/`, from the high-level project's perspective...

**Comment by DaniPopes** [comment]
No implicit remappings are added, but `--include-path` is passed which is probably why this happens.

Solc args: `"--base-path" "/tmp/forge-import-bug" "--allow-paths" "/tmp/forge-import-bug,/tmp/forge-import-bug/lib" "--include-path" "/tmp/forge-import-bug/lib/forge-import-bug-submodule" "--standard-json"`

Solc input:
```json
{
    "language": "Solidity",
    "sources": {
        "lib/forge-import-bug-submodule/src/interfaces/IContract.sol": {
            "content": "// SPDX-License-Identifier: MIT\npragma solidity ^0.8.0;\n\nimport {Type1, Type2} from \"src/libraries/Types.sol\";\n\ninterface IContract {\n    function test1(Type1 calldata type1) external;\n\n    function test2(Type2 type2) external;\n}\n"
        },
        "lib/forge-import-bug-submodule/src/libraries/Types.sol": {
            "content": "// SPDX-License-Identifier: MIT\npragma solidity ^0.8.0;\n\nstruct Type1 {\n    uint256 field;\n}\n\ntype Type2 is uint256;\n"
        },
        "src/Contract.sol": {
            "content": "// SPDX-License-Identifier: MIT\npragma solidity ^0.8.0;\n\nimport {IContract} from \"@forge-import-bug-submodule/interfaces/IContract.sol\";\n\nimport {Type1, Type2} from \"@forge-import-bug-submodule/libraries/Types.sol\";\n\ncontract Contract {\n    IContract target;\n\n    function test1(Type1 calldata type1) external {\n        target.test1(type1);\n    }\n\n    function test2(Type2 type2) external {\n        target.test2(type2);\n    }\n}\n"
        }
    },
    "settings": {
        "remappings": [
            "@forge-import-bug-submodule/=lib/forge-import-bug-submodule/src/",
            "forge-import-bug-submodule/=lib/forge-import-bug-submodule/src/"
        ],
        "optimizer": { "enabled": true, "runs": 200 },
        "metadata": { "useLiteralContent": false, "bytecodeHash": "ipfs", "appendCBOR": true },
        "outputSelection": {
            "*": {
                "": ["ast"],
                "*": [
                    "abi",
                    "evm.bytecode",
                    "evm.deployedBytecode",
                    "evm.methodIdentifiers",
                    "metadata"
                ]
            }
        },
        "evmVersion": "paris",
        "libraries": {}
    }
}
```

**Comment by grandizzy** [comment]
@Rubilmax I see https://github.com/Rubilmax/forge-import-bug was removed, is this still an issue and if it is could you please put repro back? thank you

**Comment by Rubilmax** [comment]
Sorry I deleted the repository and cannot undelete it so unfortunately I don't have a repro anymore.. feel free to close the issue

**Comment by DaniPopes** [comment]
The full source is included in the solc input I posted above if you want to reconstruct it, but I don't think we can do much here either way
