### ISSUE TITLE
feat(cheatcodes): get access to deployed libraries of current active instance

### ISSUE THREAD

**Issue by hexonaut** [foundry-rs/foundry#5291]
### Component

Forge

### Describe the feature you would like

It would be helpful to have access to the deployed libraries in the current active instance. I have two concrete use-cases for this:

1. Write out the library locations to a json file in a deploy script. I output named versions of all deployed contracts [like this](https://github.com/marsfoundation/sparklend/blob/b737f3d77d2d37cb67340f7b6e888304336af027/script/DeploySpark.s.sol#L213) and it would be nice to be able to do the same for the libraries.
2. Automated bytecode comparison in tests to match deployed code with repository. Knowing what the repository code library was deployed with in the fork test will allow find and replace without having to set the libraries in the cli args.

The obvious place for this seems like a cheatcode, but am open to alternative suggesions.

**Comment by zerosnacks** [comment]
Closing `1.` in favor of https://github.com/foundry-rs/foundry/issues/4515

For `2.` we've since added `forge verify-bytecode`

Thanks for your suggestion
