### ISSUE TITLE
`cast ups out/**/*.json` doesn't upload error signatures

### ISSUE THREAD

**Issue by wei3erHase** [foundry-rs/foundry#5293]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9aefa43 2023-07-03T00:07:40.921128000Z)

### What command(s) is the bug in?

cast ups out/**/*.json

### Operating System

macOS (Apple Silicon)

### Describe the bug

When trying to upload all the functions, events and errors from a project, `cast ups` successfully uploads functions and signatures, but there's no track of it uploading the errors (and they cannot be found on the database later).

Even tried `cast ups error out/**/*.json` and the command seems to be ignoring `error` and uploading again functions and events.

**Comment by DaniPopes** [comment]
errors are treated identically as functions, just tried by adding `error MyCustomError();` and running `forge b; cast ups out/**/*.json | grep MyCustomError`
