### ISSUE TITLE
`forge verify` has issues with `libs = ["../lib"]` remapping

### ISSUE THREAD

**Issue by jonathanpwang** [foundry-rs/foundry#5298]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### Operating System

macOS (Apple Silicon)

### Describe the bug

See https://github.com/axiom-crypto/axiom-apps/issues/6 

If the foundry root is `./foo` (so `foundry.toml` is at `./foo/foundry.toml`), while library files are installed to `./lib`, then the remapping `libs = ["../lib"]` causes source not found issues when running `forge verify-contract` on etherscan. 

If I just `cp -r ./lib ./foo/` and then change `foundry.toml` to use `libs = ["lib"]`, everything works.

**Comment by Evalir** [comment]
Known shortcoming for `forge verify`, see https://book.getfoundry.sh/forge/deploying?highlight=verify#verifying-contracts-with-ambiguous-import-paths
