### ISSUE TITLE
Add `vm.expectRevert` overloads that take an address arg, to distinguish between error selectors that are identical but in different contracts.

### ISSUE THREAD

**Issue by simplyoptimistic** [foundry-rs/foundry#5299]
### Component

Forge

### Describe the feature you would like

As described in this [issue](https://github.com/foundry-rs/book/issues/945) in the foundry book:

If you have two contracts with identical custom errors:

```
contract A {
  error NotValid();
  // contract A specific code here...
}
contract B {
  error NotValid();
  // contract A specific code here...
}
```

then: `A.NotValid.selector == B.NotValid.selector`.

If you have a test that checks for a revert from `A.NotValid.selector` and the error is thrown by `B` in the test, the test will still pass as the error selector comparisons will pass. 

By including the address of the contract in `expectRevert`, you can specify with greater granularity which error you wish to test for. 

As it stands, it is not practical to refactor common errors into a shared interface as there is no way of checking the source of a revert.

**Comment by xeno097** [comment]
If no one is working on this I'd like to 😄

**Comment by Evalir** [comment]
@xeno097 just assigned you!

@mds1 quickly looping u in to further nail UX on this

**Comment by xeno097** [comment]
Yep, I agree. I'll see how feasible it is to achieve the third bullet point and if not, then I'll stick to plan A.

**Comment by mds1** [comment]
> if not, then I'll stick to plan A.

sorry what is "plan A", is that referring to the below plan?

> So it might be better to just consider all 3 of those bullets a success, i.e. we're expecting that A throws that error anywhere in the call stack, and does not have to be the originator

**Comment by xeno097** [comment]
> > if not, then I'll stick to plan A.
> 
> sorry what is "plan A", is that referring to the below plan?
> 
> > So it might be better to just consider all 3 of those bullets a success, i.e. we're expecting that A throws that error anywhere in the call stack, and does not have to be the originator

Yep sorry for not being clear 😅
