### ISSUE TITLE
bug: keyboard shortcuts are missing from debugger UI

### ISSUE THREAD

**Issue by mds1** [foundry-rs/foundry#5310]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (bf56869 2023-07-05T00:05:02.811991000Z)

### What command(s) is the bug in?

forge test --debug <test>

### Operating System

macOS (Apple Silicon)

### Describe the bug

```solidity
pragma solidity ^0.8.20;

import "forge-std/Test.sol";

contract Test5 is Test {
    function test1() external {
        uint256 x = 1;
    }
}
```

Run `forge test --debug test1` and you'll see this:

<img width="1682" alt="image" src="https://github.com/foundry-rs/foundry/assets/17163988/74447b8e-3ae6-483e-9bc1-034ca61a42f4">

Another example of it missing, from @pcaversaccio:

![telegram-cloud-photo-size-4-5850561595883765630-y](https://github.com/foundry-rs/foundry/assets/17163988/060c6292-6d00-4ace-865b-49d7c2fce72f)

There used to be a bottom row showing keyboard shortcuts, which now seems to be missing. See the below image for an example:

![telegram-cloud-photo-size-4-5850561595883765631-y](https://github.com/foundry-rs/foundry/assets/17163988/f0307da0-a513-4d8e-ae7c-8c461dca7673)

I've tried zooming out a lot in the terminal and this does not resolve the issue

**Comment by Evalir** [comment]
Closed with #5313
