### ISSUE TITLE
`vm.assume(address(0) != address(console));` causes tests to not be found

### ISSUE THREAD

**Issue by thedavidmeister** [foundry-rs/foundry#5311]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (4b27780 2023-07-06T00:05:17.042719000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

I can't get this to happen consistently but sometimes when a test includes

```
vm.assume(address(0) != address(console));
```

Then forge can't find the test

```
thedavidmeister@davids-iMac rain.orderbook % forge test --mt testDepositMany 
[⠒] Compiling...
No files changed, compilation skipped

No tests match the provided pattern:
        match-test: `testDepositMany`

Did you mean `testWithdrawMany`?
```

actually, forge can't find _any_ tests in the same test contract, although it sees other tests in other contracts

removing the offending line allows the test to be found and run

```
thedavidmeister@davids-iMac rain.orderbook % forge test --mt testDepositMany 
[⠒] Compiling...
No files changed, compilation skipped

Running 1 test for test/concrete/OrderBook.deposit.t.sol:OrderBookDepositTest
```

**Comment by mds1** [comment]
First thing is that the assume condition seems weird. `vm.assume(address(0) != address(console))` means you want to ensure the zero address does not equal the console address (which presumably means the `console.log` address). This will always evaluate to true, so perhaps you have a typo there?

Do you have a link to a repo to reproduce this? I am not able to reproduce it with a simple test

**Comment by thedavidmeister** [comment]
@mds1 the real assume condition puts an address from the fuzzer instead of `address(0)` but i simplified for the purpose of putting an issue up

https://github.com/rainprotocol/rain.orderbook/actions/runs/5470695926/jobs/9961068378

you can see in "run forge tests" that it doesn't run any deposit related tests

https://github.com/rainprotocol/rain.orderbook/actions/runs/5470722041/jobs/9961122150?pr=8

here it does run deposit tests, the only change i made is commenting out the `vm.assume` line

**Comment by thedavidmeister** [comment]
looks like i can workaround this by providing the console address as a constant to assume

**Comment by DaniPopes** [comment]
1. Cannot reproduce
2. I don't see how this would even happen given finding tests happens before running them, obviously.
