### ISSUE TITLE
Unable to set gas limit and gas price when deploying large contracts

### ISSUE THREAD

**Issue by amit-supraoracles** [foundry-rs/foundry#5314]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (4b27780 2023-07-06T00:04:37.328364360Z)

### What command(s) is the bug in?

forge script

### Operating System

Linux

### Describe the bug

**URGENT :** We are from [SupraOracles](https://supraoracles.com/) and we have major launch in couple of days.

Description:
I'm trying to deploy a large contract using Foundry, but I'm having trouble setting the gas limit and gas price using the `--gas-limit` and `--gas-price` command line options. When I run the `forge script` command with these options, I get an error saying that the transaction has run out of gas.

Foundry version: **forge 0.2.0 (4b27780 2023-07-06T00:04:37.328364360Z)**
Solidity version: **0.8.19**
Node.js version: **v18.16.0**

**Sample Code** : https://github.com/amit-supraoracles/foundry_test 

**Command:**
`forge script script/Deployer.s.sol:Deployer --rpc-url 'https://api.zan.top/node/v1/polygon/mumbai/public' --private-key 41fbc282e78ccb368f4f5d01d6ccbc198e9572c59f18bf21c06ab419d17d0251 --gas-limit 20000000 --gas-price 12000000000 --legacy --broadcast
`

**TransactionHash :**  https://mumbai.polygonscan.com/tx/0xabb8ff7d51839ec2da238feb70bc1cf15e3efa407ad6862b23fcf34744955581

Hope team will look into this in high priority.

Amit Kumar 
SupraOracles

**Comment by zerosnacks** [comment]
Unable to reproduce the issue using the flags described on Polygon Amoy, Mumbai has since been deprecated
