### ISSUE TITLE
Detected: Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by bitdeep** [foundry-rs/foundry#5316]
### Component

Other (please describe)

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

Nightly (2023-07-06)

### Operating System

Windows

### Describe the bug

I'm trying to download latest foundry, but I'm being blocked by Windows Defender with this alert:

![image](https://github.com/foundry-rs/foundry/assets/19378023/63e023be-4ad0-44ec-a81b-c34e3fa3cc5d)

**Comment by Evalir** [comment]
This is possibly due to you using another third party tool that might've included this trojan. 😅 it will insert itself in multiples from what i can see, explaining this alert.

**Comment by Evalir** [comment]
Closing—I tested on a windows box and this doesn't happen. This might be on your computer 😅
