### ISSUE TITLE
feat: User-defined default template

### ISSUE THREAD

**Issue by 0xClandestine** [foundry-rs/foundry#5322]
### Component

Forge

### Describe the feature you would like

It would be incredibly convenient if I didn't have to repeatedly type out the same command every time I want to use a specific template. For example:

`forge init my-awesome-vulcan-project --template https://github.com/nomoixyz/vulcan-template`

To enhance the user experience, it would be fantastic if there was a way to set a default value for the template using a command such as:

`forge defaults --template https://github.com/nomoixyz/vulcan-template`

Once a default value is set, users could simplify the process by using a command like this:

`forge init --template`

**Comment by mds1** [comment]
This seems very easy to solve with a function in your `~/.zshrc` or equivalent, so it feels like bloat to add to forge

```sh
# Usage: `forgeInit <name>`, e.g. `forgeInit my-awesome-vulcan-project`
forgeInit () { 
  forge init $1 --template https://github.com/nomoixyz/vulcan-template
}

**Comment by Evalir** [comment]
Agreed, this feels like bloat and makes the forge init command stateful which is also usually problematic.

Closing for lack of appetite.

**Comment by 0xClandestine** [comment]
@mds1 @Evalir Thanks for your time, your responses make sense.
