### ISSUE TITLE
forge-std is not available in chisel

### ISSUE THREAD

**Issue by klkvr** [foundry-rs/foundry#5326]
### Component

Chisel

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### Operating System

None

### Describe the bug

Right now it is impossible to use forge-std remapping in chisel.
```
Welcome to Chisel! Type `!help` to show available commands.
➜ import "forge-std/Test.sol";
Compiler errors:
Error (6275): Source "forge-std/Test.sol" not found: File not found. Searched the following locations: "".
 --> ReplContract.sol:6:1:
  |
6 | import "forge-std/Test.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```
The same error occurs when trying to import project contracts which are using forge-std (tests, for example).

The error reason is following function:
https://github.com/foundry-rs/foundry/blob/c78a811a8af95fb1e029427583a07b2ca3a3fa51/chisel/src/session_source.rs#L312-L333

On line 331 it explicitly excludes forge-std remapping from list of remappings getting passed into solc

**Comment by startup-dreamer** [comment]
I would like to take this @gakonst any direction for this...

**Comment by mattsse** [comment]
hmm I can't remember why I added the note -.-

I believe I retroactively added support for running chisel inside a forge project

But the note hints at this already

> NOTE(mattsse): perhaps the better solution is to not add the Vm.sol 

we should not do this if forge is already in the project tree

@klkvr do you want to try this?

**Comment by klkvr** [comment]
Yep, I will take this then

**Comment by klkvr** [comment]
https://github.com/foundry-rs/foundry/blob/master/testdata/cheats/Cheats.sol

Is there a reason why interface here is named `Cheats` and not `Vm`? The same naming is used in all tests.
<img width="705" alt="image" src="https://github.com/foundry-rs/foundry/assets/62447812/9e4d2638-c7fe-4fce-85c7-02c8334ca31b">

**Comment by mattsse** [comment]
it used to be called cheats,

we just haven't renamed this universally in tests to `Vm`

would accept a PR for this
