### ISSUE TITLE
Anvil fork from local ipc/ws node

### ISSUE THREAD

**Issue by wzunknown** [foundry-rs/foundry#5329]
### Component

Anvil

### Describe the feature you would like

Allow anvil forking from local ipc/ws node. Currently, anvil and foundry only support http rpc forking. I am supposing ipc/ws would have better performance, or could anyone help provide some performance comparison? Any help is appreciated!

**Comment by mattsse** [comment]
https://github.com/0xvanbeethoven can probably help here

**Comment by DaniPopes** [comment]
This should already be supported
