### ISSUE TITLE
feat: `--unlocked` flag for Anvil which enables `autoImpersonate` on startup

### ISSUE THREAD

**Issue by Sabnock01** [foundry-rs/foundry#5334]
### Component

Anvil

### Describe the feature you would like

Currently, in order to enable auto-impersonation of accounts in Anvil, you need to call the `anvil_autoImpersonate` RPC method on your local Anvil instance:

This can be done through `curl` like so:
```bash
curl -X POST \
  http://localhost:8545 \
  -H "Content-Type: application/json" \
  -d '{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "anvil_autoImpersonateAccount",
  "params": [true]
}'
```

Or through `cast rpc`:
```bash
cast rpc anvil_autoImpersonateAccount true
```

It would be convenient to have an `--unlocked` flag when creating an Anvil instance to enable auto-impersonation on startup. Not dissimilar from the flag of the same name for `cast send`.

### Additional context

Am happy to work on this myself if it's a feature we decide to add. 

Indeed, I've already looked at the Anvil source yet have a few questions however.

**Comment by mattsse** [comment]
reasonable,
supportive

we need
1. a new config field + cli cmd field
2. if provided call the corresponding ethapi or backend function

**Comment by mattsse** [comment]
`cast rpc anvil_autoImpersonateAccount true`

this should work?

**Comment by Sabnock01** [comment]
> `cast rpc anvil_autoImpersonateAccount true`
> 
> this should work?

You're correct. It does. Modified the issue. (Was sending the request incorrectly)
