### ISSUE TITLE
anvil seems to characterize DB errors as gas errors

### ISSUE THREAD

**Issue by aathan** [foundry-rs/foundry#5336]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

built from bit repo

### What command(s) is the bug in?

anvil

### Operating System

Linux

### Describe the bug

I am currently attempting to run a project that works correctly under a hardhat node under anvil, and am not succeeding.

After augmenting InvalidTransactionError::GasTooHigh to be a struct that allows me to report details as to which GasTooHigh instance is being generated, the failing call seems to be from In `pub fn call_with_state<D>`. Therein it looks to me like every EvmError, irrespective of its actual type, is reported as a GastTooHigh error.

Is this intentional?

**Comment by mattsse** [comment]
This is thrown when

> The transaction gas exceeds the limit

> Therein it looks to me like every EvmError, irrespective of its actual type, is reported as a GastTooHigh error.

This looks like a regression after we switched to newer revm API

@Evalir ptal

**Comment by Evalir** [comment]
yep, the error is here:

https://github.com/foundry-rs/foundry/blob/master/anvil/src/eth/backend/mem/mod.rs#L1057-L1062

while we're treating the invalid tx correctly, we're always categorizing them as out of gas. We need to convert the errors appropiately
