### ISSUE TITLE
ecpairing precompile decoding is incorrect

### ISSUE THREAD

**Issue by recmo** [foundry-rs/foundry#5337]
### Component

Forge, Other (please describe)

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (c78a811 2023-07-08T00:13:27.174343000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

https://github.com/foundry-rs/foundry/blob/c78a811a8af95fb1e029427583a07b2ca3a3fa51/evm/src/trace/decoder.rs#L130

I'm not sure where `x1, y1, x3, x2, y3, y2` comes from, but it's there.

The ecpairing interface doesn't follow the ABI standard strictly and is `((x, y), ((x0, x1), (y0, y1)))*`. See [eip-197].

[eip-197]: https://eips.ethereum.org/EIPS/eip-197#encoding

**Comment by DaniPopes** [comment]
We were using the definitions from evm.codes and looks like it was incorrect there, see smlxl/evm.codes#236

This is a simple fix, just renaming the parameters correctly, if anybody wants to take this on 🙂

**Comment by recmo** [comment]
It's a bit more complicated than renaming. The number of variables itself is dynamic. Note that precompile contracts do not follow ABI encoding rules, and for this one and `modexp` there is no ABI equivalent. What maybe works is decoding the first couple point pairs and decode the rest as raw bytes? Or just do everything as raw bytes.

**Comment by CluEleSsUK** [comment]
Sorry to necro this, but I still get `EvmError: InvalidFEOpcode` running `PRECOMPILES::ecpairing` in tests.

i'm running `forge 0.2.0 (b174c3a 2024-02-09T00:19:10.198273000Z)` on mac m1 which ought to include the fix in the PR attached to this issue.

**Comment by DaniPopes** [comment]
Not related at all, that error is an `0xfe` opcode was encountered while executing bytecode. Usually a solidity 0.4 revert or something like arbitrum precompiles not being loaded. Please open another issue if you really think this is not right.

**Comment by CluEleSsUK** [comment]
Ah I see, thanks for your help and quick response!
