### ISSUE TITLE
solc error

### ISSUE THREAD

**Issue by malik672** [foundry-rs/foundry#5344]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8c48932 2023-07-09T00:04:12.656091700Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

clone thirdweb contracts and whenver i run forge test i get this:
![image](https://github.com/foundry-rs/foundry/assets/61387346/7d5e8261-38d5-4854-9e73-722fe994a8d8)

**Comment by malik672** [comment]
i should probably add that if i were to use solc version 0.8.13 instead of 0.8.12,  i won't get the error again

**Comment by mattsse** [comment]
can you please run with `RUST_LOG=ethers` and share the logs?

**Comment by mds1** [comment]
Try deleting your `~/.svm` folder and re-running `forge test`. (@mattsse you may recall this was a common issue a while ago and nuking the `~/.svm` folder was the fix, but I forget the details)

**Comment by malik672** [comment]
> can you please run with `RUST_LOG=ethers` and share the logs?

nothing comes up

**Comment by malik672** [comment]
> Try deleting your `~/.svm` folder and re-running `forge test`. (@mattsse you may recall this was a common issue a while ago and nuking the `~/.svm` folder was the fix, but I forget the details)

ive done this, still no changes

**Comment by malik672** [comment]
sometimes it compiles , other time solc error

**Comment by Evalir** [comment]
Closing—not enough info to properly debug this, and svm was recently upgraded which should help.

**Comment by robriks** [comment]
Relevant for people experiencing this issue:

https://github.com/foundry-rs/foundry/issues/2186#issuecomment-1777923634
