### ISSUE TITLE
Scripts do not properly use specified contract

### ISSUE THREAD

**Issue by efecarranza** [foundry-rs/foundry#5350]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (2e18681 2023-06-26T00:15:26.624789000Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

There seems to be an issue with contracts that have the same name when running `forge script`
We have the following repo: 

https://github.com/bgd-labs/aave-proposals

Where we have our contracts in this format:

`src/ProjectName/Contract.sol:Contract`

We also have a `Makefile` with the following script:

`deploy-ledger :; forge script ${contract} --rpc-url ${chain} $(if ${dry},--sender 0x25F2226B597E8F9514B3F68F00f494cF4f286491 -vvvv,--broadcast --ledger --mnemonics foo --mnemonic-indexes ${MNEMONIC_INDEX} --sender ${LEDGER_SENDER} --verify -vvvv)`

When running `make deploy-ledger` and specifying a certain `${contract}, forge instead seems to find the first iteration it can find of `Contract.sol:Contract` and because only `src/PROJECT_NAME_IS_UNIQUE/Contract.sol:Contract` the project name might change, it seems it's deploying the first contract as can be seen in the attached screenshot.

<img width="1052" alt="Screen Shot 2023-07-10 at 3 20 02 PM" src="https://github.com/foundry-rs/foundry/assets/10481745/189c33bf-4673-4cbf-85da-56c9ceced62b">

While we're running with path `src/AaveV3StrategicAssets_20230622/DeployProposal.sol:SinglePayloadProposal` and it looks as Make is getting that command to run correctly, the issue happens later on Foundry as can be seen on line `VM::ffi` where it's getting the information from `src/AaveV3OPEmode_20230622`

Tried to replicate with a new project was unable to get it to do the same thing.

Thank you.

**Comment by grandizzy** [comment]
bump @efecarranza @sakulstra Thank you!

**Comment by sakulstra** [comment]
I think it's indeed resolved

**Comment by grandizzy** [comment]
thank you, optimistically closing this one, please reopen if still an issue @efecarranza
