### ISSUE TITLE
Most links in v1.0.0 release notes broken

### ISSUE THREAD

**Issue by CodeSandwich** [foundry-rs/foundry#5357]
### Component

Other (please describe)

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### Operating System

None

### Describe the bug

Almost all links in https://github.com/foundry-rs/foundry/releases/tag/v1.0.0 are broken, they either lead to the root of the git project or to a 404 page in book. The only working ones are TG links and the installation guide book link. I'd love to read the announcement and see the v1 migration guide.

**Comment by Evalir** [comment]
Still working on it :).
