### ISSUE TITLE
solang-parser update in ethers-rs break foundry compilation

### ISSUE THREAD

**Issue by ArielTM** [foundry-rs/foundry#5358]
### Component

Other (please describe)

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

1.0.0

### What command(s) is the bug in?

compiling foundry

### Operating System

macOS (Apple Silicon)

### Describe the bug

Following https://github.com/gakonst/ethers-rs/commit/a126ca45a06ab86f1624a6158245a700b86804d2 ethers-rs requires `solang-parser=0.3.1` while in here https://github.com/foundry-rs/foundry/blob/afdbbc05cc479468b15a6f42b577b62e0fd4895e/Cargo.toml#L75 it explicitly requires `solang-parser=0.3.0`

**Comment by ArielTM** [comment]
Simply updating to "=0.3.1" breaks tests
```
error[E0027]: pattern does not mention field `annotation`
   --> fmt/src/solang_ext/ast_eq.rs:356:21
    |
356 |                 let $name { $($field),* } = self;
    |                     ^^^^^^^^^^^^^^^^^^^^^ missing field `annotation`
...
398 | derive_ast_eq! { struct Parameter { loc, ty, storage, name } }
    | -------------------------------------------------------------- in this macro invocation
    |
    = note: this error originates in the macro `derive_ast_eq` (in Nightly builds, run with -Z macro-backtrace for more info)
help: include the missing field in the pattern
    |
356 |                 let $name { $($field, annotation } = self;
    |                                     ~~~~~~~~~~~~~~
help: if you don't care about this missing field, you can explicitly ignore it
    |
356 |                 let $name { $($field, .. } = self;
    |                                     ~~~~~~

```

**Comment by mattsse** [comment]
looks like there's a new field annotation that we need to add to the macro

do you want to take this on?
