### ISSUE TITLE
Anvil does not revert or report certain revm failures

### ISSUE THREAD

**Issue by aathan** [foundry-rs/foundry#5365]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

nightly-c78a811a8af95fb1e029427583a07b2ca3a3fa51

### What command(s) is the bug in?

anvil

### Operating System

Linux

### Describe the bug

TL;DR

based on observed behaviors and only a cursory understanding of the code, my *conjecture* is that anvil may contain any or all of the following problems:

* seems to have a design that assumes it can identify all invalid transactions before passing them to revm (`TransactionValidator`)
* it's not clear if `TransactionValidator` is intended to catch ALL semantically invalid transaction or also ALL transactions that would fail if passed to `revm` *while also ignoring revm errors either intentionally or due to a bug*
* if either, this seems brittle, because what revm considers invalid may change silently/unexpectedly and anvil can't hope to have complete test coverage of all possible permutations of parameters
* revm may or may not be returning error codes for certain transaction failures (such as out of gas, or tx.gas>block.gas). If it is not, this may be a bug that should be reported to revm.
* either due to an unintentional bug or due to this foregoing design choice (i.e., a feature) anvil either ignores certain errors revm is returning or revm doesn't generate errors in certain cases

I'll also note that there is another possible explanation to the behaviors I've observed:

* instead of any of the above, anvil may be squelching certain transactions after the `TransactionValidator` runs, before passing them to `revm` *without reporting the failure anywhere*

See below for longer explanation.
=====

While debugging the implementation of `--disable-block-gas-limit` discussed in https://github.com/foundry-rs/foundry/issues/5341 it became apparent that anvil is probably not always catching and reporting failed `revm` transaction executions.

One way to see this is to configure/code anvil such that its TransactionValidator accepts a transaction who's tx gas > block gas. Then, I think revm fails to execute the transaction in some way, but anvil doesn't ever report that failure back to the submitter. The transaction I believe stays in some "still executing" state of some sort.

This may not be a "bug" per-se in that Anvil's design may be that the `TransactionValidator` should never let through a transaction that  for some `revm` mediated reason (such as the tx.gas>block.gas). Also, it may be that `revm` is specifically designed such that it silently fails if invalid transaction are let through.

However, I am not familiar with the internals of `revm`. On general principles, I find that to be an unlikely design choice on the part of `revm`. I think it's more likely/better that `revm` DOES/SHOULD report errors if you ask it to execute a transaction that fails for any reason.

If I'm right, then I've observed that Anvil will essentially "hang" the submitted transaction.

To test this, implement the change in https://github.com/foundry-rs/foundry/issues/5341#issuecomment-1627741061 without the change in https://github.com/foundry-rs/foundry/issues/5341#issuecomment-1631913430 and send through a transaction that exceeds the block gas limit while running anvil with `--disable-block-gas-limit` E.g., you could set the block gas limit to `1` and send any non-empty transaction through. ***

This will effectively allow a transaction through that exceeds the block gas limit. Whatever it is that `revm` does when this occurs is not trapped by anvil, and the result is a transaction that is never completed. For example, if hardhat is being used to send the transaction it will `await` that transaction receipt forever.

For example, below I describe the test I was using. It triggers the behavior if run against an anvil that has been built as described above. I.e., the TransactionValidator modification allows the overlimit transaction but anvil does not set the block gas limit to U256::max_value(). Per the description in https://github.com/foundry-rs/foundry/issues/5341, something in anvil or revm limits the block gas to less than the `19999999` passed in the tx (even if `--block-gas` specifies e.g. `20000000`). Thus, the described tx seems to get to revm, but doesn't actually run.

Ok, my test was to run `anvil --fork-url https://api.avax.network/ext/bc/C/rpc --base-fee 1 --inline-logs --disable-block-gas-limit` after making the changes described in the paragraph above that is marked with *** and built from a modified revm, such that:

```
pub fn sstore<SPEC: Spec>(interpreter: &mut Interpreter, host: &mut dyn Host) {
    println!("sstore");
```

Then, implement some toy contract

```
contract Toy {
    address[2] public impls;
    event Foo(address,address,address,address);

    function runStore() public {
        impls[0] = address(2);
    }

    constructor(...){
        impls[0]=address(1);
        emit Foo(address(0),address(0),address(0),address(0));
```

and in a hardhat.js I do:

```
async function init() {
    console.log('deploying')
    const signers = await ethers.getSigners()
    signer = signers[0]
    const depl = await getContractFactory(signer, 'Toy')
        .deploy(...,{
            gasLimit: 19999999,
            gasPrice: ethers.utils.parseUnits('10', 'gwei'),
        })
    console.log("1")
    let m = network.provider.send('evm_mine')
    await m
    let x = depl.runStore() // this hangs
    await x
    console.log("2")
```

As written above the output from Anvil is:

```
Listening on 127.0.0.1:8545
eth_accounts
eth_chainId
eth_blockNumber
eth_chainId
eth_sendTransaction

    Block Number: 32492941
    Block Hash: 0xe97f624d21d740c06ed4ef2edd43d7c6afa8794e133c8ac157cfe63f131254be
    Block Time: "Wed, 12 Jul 2023 05:24:30 +0000"

eth_chainId
eth_getTransactionByHash
evm_mine

    Block Number: 32492942
    Block Hash: 0x78e72148e6f53307456ef2c9abf5935f92642bafa022aed78e8b2c0c4d98bb41
    Block Time: "Wed, 12 Jul 2023 05:24:31 +0000"

eth_chainId
eth_getTransactionReceipt
eth_chainId
eth_getTransactionReceipt
eth_chainId
eth_getTransactionCount
eth_blockNumber
eth_chainId
eth_chainId
eth_getTransactionReceipt
eth_chainId
eth_getTransactionCount
eth_blockNumber
eth_chainId
eth_blockNumber
eth_chainId
...
```

Notice that there is no output that says "sstore"  The `eth_blockNumber,eth_chainId,...` calls repeat forever.

There is no syntactically valid ordering of the lines between `console.log("1")` and `consoloe.log("2")` that doesn't hang.
If the `await x` is above the `await m` then it waits forever and never outputs the second `Block Number...` block, so I know the "mining" is doing something ... but what?. If I give the `--no-mine` parameter, Anvil  doesn't output either `Block Number` block.

What seems to be the case is that the block is mined, but the tx is silently never executed and its status as a failed transaction is lost to anvil and to the submitter.

**Comment by Evalir** [comment]
Will close for now—we've fixed several of these and as a result of the alloy migration the Anvil code has been moving a lot. We'll be resolving these as they come case-by-case, but for now this should've been improved.
