### ISSUE TITLE
anvil eth_feehistory may return 0 values

### ISSUE THREAD

**Issue by aathan** [foundry-rs/foundry#5368]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

nightly-c78a811a8af95fb1e029427583a07b2ca3a3fa51

### Operating System

Linux

### Describe the bug

Not clear this is really a bug per se, however see https://github.com/NomicFoundation/hardhat/issues/4136 ... should anvil perhaps protect against sending 0 return values for any percentile? I am not sure if any spec (for either eth_feehistory or the EVM in general) either already does or SHOULD specify that 0 fees are nonsense. I suppose it takes a rather special invocation of anvil to cause this (`--base-fee 1`), and protecting 0 return values in certain fields is arguably more about protecting against naive calcs in the calling program (hardhat/cast/foundry scripts/etc)

**Comment by aathan** [comment]
I've realized that base_fee=0 could maybe be useful in testing scenarios where you want to be spending 0 fees so that your tests never fail due to insufficient funds. However, allowing calculated values of zero out in a testing scenario that is meant to emulate a "real" chain seems incorrect.

I don't want to be bikeshedding this issue, as the easiest way to configure a dapp into "test" mode may be to point it to a chain that was started with `--base-fee 0` ... but such settings seem very specifically geared to *testing* vs *deployment*.

To the extent that hardhat and/or the foundry toolset has any guard rails as to behaviors that should be allowed "for testing" vs "for deployment," this seems like one. And yes, I realize it's unlikely to actually cause any accidental loss of funds, as worst case we're just talking about a fake node emulating a production chain.

I guess "not a bug"?

**Comment by Evalir** [comment]
Not a bug but rather a feature—I understand this is a tad controversial and there's usually a good amount of discussion around this, but so far it hasn't been a footgun, so will close for lack of appetite to triage for now!
