### ISSUE TITLE
cast `lookup-address` and `resolve-name` fail on names with unicode characters

### ISSUE THREAD

**Issue by jameswenzel** [foundry-rs/foundry#5386]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e488e2b 2023-07-10T15:17:42.605282000Z)

### What command(s) is the bug in?

cast lookup-address, cast resolve-name

### Operating System

macOS (Apple Silicon)

### Describe the bug

ENS names without unicode characters resolve correctly in both directions

>❯ cast resolve-name emo.eth
0x28679A1a632125fbBf7A68d850E50623194A709E
 ❯ cast lookup-address 0x28679A1a632125fbBf7A68d850E50623194A709E
emo.eth

ENS names with unicode characters result in errors – although, interestingly, lookup-address fails by saying it couldn't look up _the correctly resolved name_.

> ❯ cast lookup-address 0x00000000000061aD8EE190710508A818aE5325C3
Error: 
ens name not found: ret↩️rn.eth
❯ cast resolve-name ret↩️rn.eth
Error: 
ens name not found: ret↩️rn.eth
❯ cast resolve-name 🤦<200d>♀️.eth
Error: 
ens name not found: 🤦‍♀️.eth

**Comment by mds1** [comment]
Ah thanks for the issue, noticed this earlier and was wondering if the contract was misconfigured or if it was an issue with the emoji

> interestingly, lookup-address fails by saying it couldn't look up the correctly resolved name.

This is because you can set the reverse record to resolve to any ENS name you want. So the proper way to do reverse lookups (address -> ENS) is to first do the reverse lookup (address -> ENS), then do a forward lookup (ENS -> address) and verify you get back the original address. So you see this error on the forward lookup step

**Comment by Sabnock01** [comment]
Can I take this one?

**Comment by mds1** [comment]
@Sabnock01 assigned!

**Comment by Sabnock01** [comment]
This appears to be an error in `ethers_providers`. Will need to fix there and then reference back here.

**Comment by Sabnock01** [comment]
@Evalir this has been merged. Do we just bump `ethers` here now?

**Comment by Evalir** [comment]
Yep we're bumping it on https://github.com/foundry-rs/foundry/pull/5397 already

**Comment by Sabnock01** [comment]
This is working for me on `cast 0.2.0 (d8d9aa1 2023-07-20T00:18:13.787200434Z)`. @jameswenzel @Evalir either of you guys want to confirm so we can close this issue as completed?

**Comment by Evalir** [comment]
Can confirm it's working! Thanks for the ping @Sabnock01 — closing
