### ISSUE TITLE
Forge crashes with message `No target contract named <path>:<name>`.

### ISSUE THREAD

**Issue by guidanoli** [foundry-rs/foundry#5396]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6c0fce3 2023-07-14T02:45:24.569798838Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

Hello, my name is Guilherme. I am one of the core contributors of [`cartesi/rollups`](https://github.com/cartesi/rollups). Our [test workflow](https://github.com/cartesi/rollups/actions/runs/5554303929) started failing since earlier today (10 a.m. BRT), because `forge test` is crashing. I managed to replicate the error locally, and this is the error message. The back trace is not very helpful, so I omitted it.

```
The application panicked (crashed).
Message:  No target contract named ../node_modules/@cartesi/util/contracts/CartesiMathV2.sol:CartesiMathV2
Location: utils/src/lib.rs:269
```

I easily managed to pinpoint the line that raised the error: [here](https://github.com/foundry-rs/foundry/blob/master/utils/src/lib.rs#L269).
Also, it seems that this section of code was last updated by this PR: [here](https://github.com/foundry-rs/foundry/pull/5364).

You can replicate the error yourself by following these steps:

1. Start the latest Ubuntu machine
2. Install `jq`, `yarn` and `docker`
3. Clone `https://github.com/cartesi/rollups.git`
4. Initialize the submodules (`git submodule update --init --recursive`)
5. Go to `onchain/rollups`
6. Run `yarn` (installs contract dependencies)
7. Run `./test/foundry/dapp/helper/update-proofs.sh --setup`
8. Run `forge test`

**Comment by mattsse** [comment]
yeah this is a linking regression @onbjerg 

https://github.com/foundry-rs/foundry/blob/e07606df4eb6fb8211486bc42495138e034c4c9e/utils/src/lib.rs#L267-L269

**Comment by onbjerg** [comment]
I am unable to install the dependencies for the repository, please advise:

```
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@chainsafe/ssz/-/ssz-0.9.4.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/media/vault/Projects/cartesi/rollups/onchain/rollups/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error https://registry.yarnpkg.com/@esbuild/darwin-x64/-/darwin-x64-0.16.17.tgz: Request failed "404 Not Found"
```

My system:

```
$ uname -a
Linux dagr 6.1.31-2-MANJARO #1 SMP PREEMPT_DYNAMIC Sun Jun  4 12:31:46 UTC 2023 x86_64 GNU/Linux

$ yarn --version
1.22.19
```

**Comment by guidanoli** [comment]
@onbjerg That's weird. Could you try it on an Ubuntu machine?

**Comment by guidanoli** [comment]
It's weird because when I run `forge clean`, and then `forge test`, it works.
But if I run `forge test` a second time, it crashes.
Maybe this has something to do with the cache.

**Comment by onbjerg** [comment]
Doesn't work on Ubuntu either.

**Comment by guidanoli** [comment]
Hey, @mattsse, could you try on your machine?

**Comment by mattsse** [comment]
@guidanoli 

I'm unable to install via yarn, tried several node version but:

> error hardhat@2.14.0: The engine "node" is incompatible with this module. Expected version ">=14.0.0". Got "8.16.2"

**Comment by guidanoli** [comment]
Thanks for the speedy effort, everyone! :clap:

**Comment by tommyrharper** [comment]
Hey, @Evalir and @mattsse, I am a core contributor at [kwenta](https://github.com/Kwenta/token) - a defi protocol.

This issue has been closed, but I am still facing the same issue:
```
The application panicked (crashed).
Message:  No artifact for contract contracts/libraries/SafeDecimalMath.sol:SafeDecimalMath
Location: /Users/runner/work/foundry/foundry/utils/src/lib.rs:288
```

Same thing - the tests used to run, until our CI broke a few weeks ago. Then today I started getting the same error locally as in the CI. It's not based on any code changes, I have tried checking out old versions of code before the issue cropped up, so this is definitely a foundry issue.

I have run `foundryup`.

You can replicate the issue by cloning the [kwenta-token-repo](https://github.com/Kwenta/token) locally and running `npm run f-test`.

Any ideas what the problem is?

**Comment by Evalir** [comment]
Could you try out the _latest_ foundryup version? @tommyrharper that commit is two weeks old, we've had a few related fixes since then

**Comment by tommyrharper** [comment]
@Evalir I get the error with the latest version of foundry - I was just trying to narrow down between which commits the issue appeared.

**Comment by tommyrharper** [comment]
@Evalir I found the responsible commit: `6fbf0177a06fd6b0a17e1aef91be5e86f6ecb511`
It's here: https://github.com/foundry-rs/foundry/commit/6fbf0177a06fd6b0a17e1aef91be5e86f6ecb511

This is exactly the commit which causes it to break.

Let me know if there is anything else I can do to help debug this, and thanks for responding so quickly 🙏

**Comment by tommyrharper** [comment]
Boom! 💥 Thanks - you are super responsive @Evalir, thanks for the great work, its fixed now! ❤️
