### ISSUE TITLE
Using forge on constantinople EVM

### ISSUE THREAD

**Issue by ersanyakit** [foundry-rs/foundry#5398]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### Operating System

macOS (Apple Silicon)

### Describe the bug

Hello, is it possible to use Forge on the Constantinople version of the Ethereum Virtual Machine (EVM)?

**Comment by Evalir** [comment]
Hey! Yes—just add the `--evm-version constantinople` flag when running a forge command..

**Comment by ersanyakit** [comment]
<img width="806" alt="Ekran Resmi 2023-07-15 03 33 51" src="https://github.com/foundry-rs/foundry/assets/10724463/f6104793-57e3-4d15-85a2-649decf71f68">

**Comment by onbjerg** [comment]
Should work on master now

**Comment by ersanyakit** [comment]
@onbjerg it will not work... because ethereum constatinople doesn't support "block.chainId" forge-std libs using block.chainId on ERC20 contracts
