### ISSUE TITLE
CREATE2 Deployer not present on this chain. [0x4e59b44847b379578588920ca78fbf26c0b4956c]

### ISSUE THREAD

**Issue by ersanyakit** [foundry-rs/foundry#5401]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### Operating System

macOS (Apple Silicon)

### Describe the bug

`forge script script/Test.s.sol -v --rpc-url https://rpc.bitci.com --broadcast;`
<img width="886" alt="Ekran Resmi 2023-07-15 04 51 18" src="https://github.com/foundry-rs/foundry/assets/10724463/de37ea7e-47fe-4a12-af53-506c592ed50c">

**Comment by Evalir** [comment]
Closing—this just means we need to deploy arachnid's deployment proxy on this chain.
