### ISSUE TITLE
Add state diff tracer to Anvil

### ISSUE THREAD

**Issue by alex-miller-0** [foundry-rs/foundry#5403]
### Component

Anvil

### Describe the feature you would like

Anvil is an extremely useful tool for simulating a sequence of unsigned transactions and determining if any will revert. The `eth_sendUnsignedTransaction` appears to be without analogy in any other client/tool and is awesome! However, being able to simulate *state diffs* is important to many workflows as well.

Geth has several [built in tracers](https://geth.ethereum.org/docs/developers/evm-tracing/built-in-tracers), including one that is exceedingly useful called the [`prestateTracer`](https://geth.ethereum.org/docs/developers/evm-tracing/built-in-tracers#prestate-tracer). 

It would be great if Anvil could incorporate a similar tracer to provide state diffs for simulated, unsigned transactions.

**Comment by Ifechukwudaniel** [comment]
This would be really awesome

**Comment by 0xad1onchain** [comment]
Having support for `prestateTracer` as a `tracer` argument would be really useful

**Comment by 409H** [comment]
+1, would really like to see this!

**Comment by grandizzy** [comment]
going to track prestateTracer (and other tracers built in Reth) support in https://github.com/foundry-rs/foundry/issues/5855 and close this one as dupe
