### ISSUE TITLE
Add `randomUint`/`randomInt` cheatcodes

### ISSUE THREAD

**Issue by LilaRest** [foundry-rs/foundry#5407]
### Component

Forge

### Describe the feature you would like

While property-based testing (fuzz) should fit for most case of general testing, there are some other cases where a test function would require generating random values dynamically.

As an example, here is a function that ensures rewards of a staking contract are properly applied no matter the number of time the APR has changed after an investment, as well as no matter the intervals between each pair of APRs changes.

```solidity
function test_rewardsOf_1(
    uint256 initialInvestment,
    uint256 numberOfAPRChanges
) public {
    // Initially invest random amount of tokens
    deal(investedToken, address(1234), initialInvestment);
    vm.prank(address(1234));
    testedContract.stake(initialInvestment);

    // Bound numberOfAPRChanges to [0,200]
    numberOfAPRChanges = bound(numberOfAPRChanges, 0, 200);

    // Create random number of APR change after investment
    for (uint256 i = 0; i < numberOfCheckpoints; i++) {
        testedContract.setAPR(randomNumber(0, type(uint16).max));

        // Move forward a random amount of time until next APR
        skip(randomNumber(0, type(uint40).max));
    }

    // ... Verify that rewards are properly calculated
}
```

In this example using `randomNumber()` would be better than using static values as it would potentially reveal more complex errors scenarios.

However, I think those random values wouldn't offer the same trust than random values received through functions parameters (as they are simple random values and don't use any shrinking/resolve mechanism).

Maybe a solution could be to implement shrinking/resolve on those too, but its seems complex.

So I'm a bit mixed on this idea, but I'd be happy to read your thoughts on it :)

**Comment by LilaRest** [comment]
Note that I've already tried [this library](https://github.com/joejordan/foundry-random) but it slows my tests run by ~200x.

I also tried to implement my own helper contract relying on ffi to retrieve `$RANDOM` environment variable, but it also slows so much my tests runs and may produce inaccurate results on numbers that don't fit in 64 bits.

**Comment by Evalir** [comment]
imho @mds1 this sounds like a good idea to build this in. wdyt?

**Comment by mds1** [comment]
> In this example using `randomNumber()` would be better than using static values as it would potentially reveal more complex errors scenarios.

You can also achieve this with a new fuzz parameter that you hash in each iteration of the loop:

```solidity
function test_rewardsOf_1(
    uint256 initialInvestment,
    uint256 numberOfAPRChanges,
    uint256 entropy // <-- new param
) public {
    // --- snip ---
    for (uint256 i = 0; i < numberOfCheckpoints; i++) {
        testedContract.setAPR(randomNumber(0, type(uint16).max));

        // Move forward a random amount of time until next APR
        uint256 randomNumber = uint256(keccak256(entropy, i));
        skip(bound(randomNumber, 0, type(uint40).max));
    }

    // ... Verify that rewards are properly calculated
}
```

Or if you don't want to introduce a fuzz param because you want determinism, you can deterministically generate a pseudo-random value:
```solidity
function test_rewardsOf_1(
    uint256 initialInvestment,
    uint256 numberOfAPRChanges
) public {
    // --- snip ---
    for (uint256 i = 0; i < numberOfCheckpoints; i++) {
        testedContract.setAPR(randomNumber(0, type(uint16).max));

        // Move forward a random amount of time until next APR
        uint256 randomNumber = uint256(keccak256("entropy", i));
        skip(bound(randomNumber, 0, type(uint40).max));
    }

    // ... Verify that rewards are properly calculated
}
```

> Note that I've already tried [this library](https://github.com/joejordan/foundry-random) but it slows my tests run by ~200x.
> 
> I also tried to implement my own helper contract relying on ffi to retrieve `$RANDOM` environment variable, but it also slows so much my tests runs and may produce inaccurate results on numbers that don't fit in 64 bits.

Yea ffi is very slow and I wouldn't recommend using it for this purpose. A much better/more performant approach to use `$RANDOM` would be to just use `vm.envUint("RANDOM")` 

> imho @mds1 this sounds like a good idea to build this in. wdyt?

This feature has been requested a few times, but I'm not sure of the use case. There's also some decisions to make before it's implemented, namely around how it should behave, e.g. should it be uniformly random, or deterministic, or act like a fuzz value (e.g. leverage strategies and the dictionary).

- If purely random, we need to introduce a seed for this cheat (it could just be an input), or we could leverage the existing seed param. This is required for when you need reproducibility. But if you're doing that, what benefit does the cheat add over a fuzz param or `$RANDOM`?
- If deterministic, you can do this already by hashing some block/context properties (like timestamp, etc), or by hashing an arbitrary string. You can continually generate deterministic but pseudo-random values this way with a loop index, or by storing the last result in storage then hashing that to get the next result, like [this](https://github.com/FrankieIsLost/forge-template/blob/cdea5d32c03a4c29030ed851830c55c82300b1ed/src/test/utils/Utilities.sol#L10-L17) (the example is for generating addresses, but same idea)

**Comment by mattsse** [comment]
I actually think we can easily add this
`randmon()`
`random(from, to)`

I believe thread_rng is perfectly fine here

adding this isn't much work or complex and having a simple cheatcode for this could be useful

**Comment by mds1** [comment]
@Tudmotu what is your use case for this that you can't do with a fuzz parameter or `vm.envUint("RANDOM")` + forge-std's `bound` method to get your randomness within a range? I hear this feature requested a lot but honestly haven't heard a compelling use case for a dedicated randomness feature

My main hesitation about adding it is (1) I'm not clear on the use case, and (2) it's another thing that needs a seed config option, so consequently needs some way to be reproduced when a fuzz run fails, so reproducing test failures gets a bit more complex

**Comment by Tudmotu** [comment]
Up till now I've been using `ffi` + python for random.
Testing `envUint('RANDOM')` now, I get an error trying to access `RANDOM`:
```
Failed to get environment variable `RANDOM` as type `uint256`: environment variable not found
```
I'm running Linux. So possibly `RANDOM` is not injected into the Foundry process?

Not sure my personal use case is applicable to many people:
In my scripts (not tests) I write temporary files and I need their names to be random so that I don't accidentally overwrite them.

**Comment by mds1** [comment]
Are you running a fuzz test? If so you can just add an extra fuzz parameter, or use `msg.data` as your entropy. Can also use `vm.unixTime` which might help

**Comment by Tudmotu** [comment]
Personally I need it in a script, not a test. But again, I have a very specific use-case. The idea of using `unixTime` might actually be good enough for me. Thanks, didn't think about that!

So unless someone else has a more common use case, I agree it might not be necessary :slightly_smiling_face:

**Comment by mathewmeconry** [comment]
> Up till now I've been using `ffi` + python for random. Testing `envUint('RANDOM')` now, I get an error trying to access `RANDOM`:
> 
> ```
> Failed to get environment variable `RANDOM` as type `uint256`: environment variable not found
> ```
> 
> I'm running Linux. So possibly `RANDOM` is not injected into the Foundry process?
> 
> Not sure my personal use case is applicable to many people: In my scripts (not tests) I write temporary files and I need their names to be random so that I don't accidentally overwrite them.

this is because `$RANDOM` is not an env variable in Linux but rather a script injected by shells like bash. This is why it isn't visible with the `env` command.

I would need this random feature too. I would like to simulate some market transactions.

**Comment by mds1** [comment]
Some questions that need to be answered before a `vm.random()` cheat is introduced, namely around how to guarantee users can always reproduce failed tests when the cheat is used:
- Should it be reliant on the calldata, like the [solady method](https://github.com/Vectorized/solady/blob/23cb3cb13ea32bc94d9d136666090b36d0485e1c/test/utils/TestPlus.sol#L65-L119), that way the approach to reproducing failed cases doesn't change? If not, what does the UX look like there to ensure you can always reproduce failures? (Consider that users will want to run both with and without specifying a seed for the rng).
- Should it leverage the same strategies as fuzzer inputs for generating values, or should it use some other distribution?

**Comment by Tudmotu** [comment]
I'll share my extended personal opinion:
I view Forge as something beyond a testing framework. Don't know about any of you, but I use Forge scripts extensively & practically have replaced all my JS scripts with Solidity scripts by now, including stuff like automatically updating our Notion docs whenever we deploy. Forge is to Solidity what Node was to Javascript — and I believe we will start seeing more and more libraries built specifically for Forge (e.g. Surl). Therefore I think it is reasonable to include a cheatcode even if it is not suitable for writing tests, as long as it caters to script & library authors.

I also think test authors should know what they are doing to some degree. Jest does not prevent me from using `Math.random()`, for example. And there are many other ways in which tests can become flaky.

That said, while I don't hold the same view, I do understand your position regarding reproducibility.

**Comment by startswithaj** [comment]
Hi everyone, sorry if this is not the appropriate place to ask, but wondering now that this is merged into master when will it be available as a release, or how I might install master on my local?

Im currently using `6822860 2024-07-29T00:23:34.055980000Z`


Cheers
