### ISSUE TITLE
master - build broken

### ISSUE THREAD

**Issue by MarcelCiernik** [foundry-rs/foundry#5409]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

cargo install --path ./cli --profile local --bins --force

### What command(s) is the bug in?

error[E0063]: missing field `context` in initializer of `Remapping`

### Operating System

Linux

### Describe the bug

build broken

**Comment by mattsse** [comment]
ref #5397

**Comment by Evalir** [comment]
Closing, #5397 merged
