### ISSUE TITLE
`anvil_mine` performs sleep when time interval set

### ISSUE THREAD

**Issue by michprev** [foundry-rs/foundry#5419]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (c835a3d 2023-07-17T00:21:00.033122754Z)

### Operating System

None

### Describe the bug

[This](https://github.com/foundry-rs/foundry/blame/1be8787cc3e12f813b068140675ee274d5bfae81/anvil/src/eth/api.rs#L1433-L1435) `sleep` should be replaced with the logic from [evm_set_next_block_timestamp](https://github.com/foundry-rs/foundry/blame/1be8787cc3e12f813b068140675ee274d5bfae81/anvil/src/eth/api.rs#L1663).

The logic should be something like:

- mine a block
- if `interval` is set:
    - get timestamp of the latest block
    - `self.backend.time().set_next_block_timestamp(last_timestamp + interval)`
- repeat until all blocks mined

**Comment by Evalir** [comment]
Hey! Sorry, I can't really understand what you mean here. What is the actual bug here?

**Comment by michprev** [comment]
Yeah sorry, I should have explained more. The issue is that `anvil_mine` with `interval` set performs busy waiting. It waits a given amount of seconds between subsequent block mines. Instead, it should set the next block timestamp using the same logic (or almost the same logic) as `evm_set_next_block_timestamp`.

In other words, if you call `evm_mine` with 10 blocks to mine and the interval set to 1_000 (seconds), you will wait 10 * 1_000 seconds for the request to finish.
