### ISSUE TITLE
current nightly build breaks parallel hardhat setup

### ISSUE THREAD

**Issue by elmariachi111** [foundry-rs/foundry#5433]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

0e72b7158

### Operating System

Linux

### Describe the bug

We're running hardhat tests in combination with foundry tests (@nomicfoundation/hardhat-foundry) to execute oz upgrade verifiers. We recently noticed that our hardhat tests break when executed against code generated by the latest nightly (nightly-0e72b71580da73d3d89c9b9aaa1bc832831e0da7) : 

```
Run yarn hardhat test --network hardhat
yarn run v1.22.19
$ /home/runner/work/IPNFT/IPNFT/node_modules/.bin/hardhat test --network hardhat
Downloading compiler 0.8.18
An unexpected error occurred:

Error: Content for lib/token-vesting-contract/lib/openzeppelin-contracts/contracts/access/Ownable.sol not available
    at getSource (/home/runner/work/IPNFT/IPNFT/node_modules/@openzeppelin/upgrades-core/src/src-decoder.ts:25:15)
    at /home/runner/work/IPNFT/IPNFT/node_modules/@openzeppelin/upgrades-core/src/src-decoder.ts:33:31
    at extractStorageLayout (/home/runner/work/IPNFT/IPNFT/node_modules/@openzeppelin/upgrades-core/src/storage/extract.ts:50:19)
    
...    
```

they work fine with the build from July 2(nightly-d369d2486f85576eec4ca41d277391dfdae21ba7). We're not exactly sure which of the intermediate builds introduced the breaking change but it must be one between July2 and July19 2023.

Here are 2 or our workflow runs for reference:

breaks: https://github.com/moleculeprotocol/IPNFT/actions/runs/5597735526/jobs/10236488893
works: https://github.com/moleculeprotocol/IPNFT/actions/runs/5598108479/jobs/10237312810

**Comment by Evalir** [comment]
Closing as fixed by #5532
