### ISSUE TITLE
--gas-limit throws bug when set on script with forge

### ISSUE THREAD

**Issue by nicolasguasca1** [foundry-rs/foundry#5440]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (0e72b71 2023-07-19T00:31:31.205426000Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Intel)

### Describe the bug

Im running a script that deploys various contracts into the sepolia testnet. The first set of contracts are libraries, the second set of contracts are templates that use the libraries deployed and will be used as the templates to deploy various proxies. However, out of the 12 transactions necessary, only 5 of them are successful. I run into the:

```(code: -32000, message: insufficient funds for gas * price + value```

This is my script so far:
```forge script scripts/01_InitialDep.s.sol:MyInitialScript --rpc-url $SEPOLIA_RPC_URL --private-key $PRIVATE_KEY --broadcast --sender <myAddress> -vvvvv --gas-limit 3000000 RUST_BACKTRACE=$RUST_BACKTRACEB```

As you can see, I tried to use --gas-limit 3000000 within my script and the CLI panicked(crashed) with this backtrace:

```
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   2: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   3: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   4: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   5: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   6: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   7: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   8: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   9: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  10: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  11: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  12: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  13: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  14: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  15: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  16: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
      ```
      
      The message after it crasher starts with this:
      
      ``` couldn't deploy library: Execution(ExecutionErr { reverted: true, reason: "EvmError: OutOfGas", gas_used: 3000000, gas_refunded: 0, stipend: 0, logs: [], traces: Some(CallTraceArena { arena: [CallTraceNode { parent: None, children: [], idx: 0, trace: CallTrace { depth: 0, success: false, contract: None, label: None, caller: 0x65aa9b131fa4d4ab112cd5e912b82c068574c9b5, address: 0x8ccf83ae2ffa68b94efe521d16d03d8d045b9995, kind: Create, value: 0, data:```
      
    Even if I set a higher gas limit than 3000000, then I don't get the creash, but I still get the -32000 code so I feel I get the same error doing two different things.  I would like to know how to properly set a gas limit for a transaction using forge. I know the only way to get the gas within solidity is using gasleft() function but I don't think its giving me realistic figures as it says at the end of the "run" function that remaining gas is 2974882756 which means its not taking too much gas to run. 
    
    The functions within the script run perfectly and then the transactions receipt shows a different reality. Does it have to do with the fact that the script is also a "test"?

**Comment by Evalir** [comment]
Hey! can you provide a minimal repro of this happening please? This way I can take a proper look at this.

**Comment by nicolasguasca1** [comment]
Hello Evalir! My problem was that I was using:

```function run() external {
        uint256 deployerPrivateKey = vm.envUint("ANVIL_PRIVATE_KEY");
        vm.startBroadcast(deployerPrivateKey);
        ```
And my script was using my actual $PRIVATE_KEY. That was causing the out of gas error.
