### ISSUE TITLE
Add ability to output post state after `forge script`

### ISSUE THREAD

**Issue by tynes** [foundry-rs/foundry#5443]
### Component

Forge

### Describe the feature you would like

It would be great if it was possible to have a CLI flag that enabled writing a file to disk after `forge script` execution that includes the altered state as a JSON file compatible with go-ethereum's genesis serialization.  This doesn't necessarily need to be a full state diff with the pre and post state, just the post state is useful. Then developers will have a way to see the exact side effects of their script as all of the modified state will be in this JSON file.

### Additional context

This is particularly useful to Optimism so that our foundry based deployment scripts can have test coverage in our in memory end to end test suite by running the deployment using `forge` and outputting a JSON file that is then consumed by the e2e tests to initialize the L1 genesis state.

**Comment by zerosnacks** [comment]
Hi @tynes, is this still something you would like to see? It sounds like something that should be achievable through Anvil `dumpState` / `loadState` and some cheatcodes

**Comment by tynes** [comment]
> Hi @tynes, is this still something you would like to see? It sounds like something that should be achievable through Anvil `dumpState` / `loadState` and some cheatcodes

We now accomplish this with the dumpState and loadAllocs cheat codes, thanks for checking in
