### ISSUE TITLE
forge build providing insufficient information on compile errors in v0.7 solidity

### ISSUE THREAD

**Issue by simplyoptimistic** [foundry-rs/foundry#5446]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (02e430c 2023-07-21T00:24:08.481175000Z)

### What command(s) is the bug in?

forge build

### Operating System

macOS (Apple Silicon)

### Describe the bug

`forge b` doesn't show the location of compilation errors in v0.7 of solidity. 

I expect the following:

```
[⠔] Solc 0.8.19 finished in 3.49ms
Error:
Compiler run failed:
Error (6933): Expected primary expression.
  --> test/Counter.t.sol:17:36:
   |
17 |         assertEq(counter.number(), );
   |                                    ^
```

In particular, I am expecting to see the file the error is in, as well as the line. 

On v0.7.6, I get this, which provides none of that information. 

```
[⠔] Solc 0.7.6 finished in 15.01ms
Error:
Compiler run failed:
Error (6933): Expected primary expression.
        assertEq(counter.number(), );
```

To reproduce: 
- Run `forge init example` to create the test repository. 
- Delete the script folder.
- Introduce a compilation error (remove a random number from the test file)
- Run `forge b`

**Comment by DaniPopes** [comment]
```
[⠰] Compiling 22 files with 0.7.6
[⠊] Solc 0.7.6 finished in 278.03ms
Error: 
Compiler run failed:
Error (6160): Wrong argument count for function call: 0 arguments given but expected 1.
        counter.setNumber();
        ^-----------------^
```
