### ISSUE TITLE
bug(forge): overlapping nested remappings are not resolved

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/foundry#5447]
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### What version of Foundry are you on?

`forge 0.2.0 (02e430c 2023-07-21T00:24:08.481175000Z)`

### What command(s) is the bug in?

`forge build`

### Operating System

macOS Silicon

## Problem

#5397 added support for remapping contexts (closing #1855), however, the implementation does not handle all edge cases yet.

Suppose you have a project structure like this:

```tree
project/
└── lib/
    ├── foo/
    │   └── lib/
    │       └── openzeppelin-contracts  
    └── bar/
        └── lib/
            └── openzeppelin-contracts
```

In both `foo` and `bar`, `openzeppelin-contracts` is remapped to the following:

```bash
@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/
```

The bug is that only one of the two remappings gets resolved, not both.

## Error Log

Sneak peek:

>  Unable to resolve imports: "@openzeppelin/contracts/token/ERC20/IERC20.sol"

See the full log [here](https://app.warp.dev/block/NzkoqBiRAVrpY7IW8d5M0r).

The issue is that only the `v2-core` remapping appears in the auto-detected remappings:

```bash
lib/v2-core:@openzeppelin/contracts/=/Users/prb/Sablier/examples/lib/v2-core/lib/openzeppelin-contracts/contracts/
```

## Reproduce

1. Clone [sablier-labs/examples](https://github.com/sablier-labs/examples) at commit [eae781](https://github.com/sablier-labs/examples/commit/eae781627e15d963a62c1545fe0944ad94d5519c)
2. Remove the `permit2` remapping in `remappings.txt`
3. Run `forge build`

**Comment by Evalir** [comment]
Yep I'm on this today actually @PaulRBerg — will rollback the remappings context PR first to unblock you & others, and we'll get a fixed PR later!

**Comment by Evalir** [comment]
Btw @PaulRBerg — any chance you can provide a more minimal repro with a recent foundry version? this way it'll be much easier

**Comment by PaulRBerg** [comment]
I'm afraid that I don't have any repro smaller than the Sablier examples repo. However, what should matter is the `IERC20` import. You should be able to focus on that.

It is also difficult to provide a small repro due to the nature of this bug - it gets activated when there are nested deps with shared deps between them.

Re Foundry version - I ran `foundryup` now and I observed the same behavior when running `forge build`.

**Comment by lorbke** [comment]
Still having issues with overlapping remappings. I have updated my foundry to the latest version.

This is the relevant part of my remappings.txt:
@openzeppelin/contracts/utils/math/SafeMath.sol/=src/SafeMath.sol
@openzeppelin/=lib/openzeppelin-contracts/

With the remappings arranged like above, all imports **including** the SafeMath one crash whereas when arranged the other way around, all imports work except for the SafeMath one.

**Comment by pikonha** [comment]
+1

"@ensdomains/=lib/evmgateway/"
"@ensdomains/ens-contracts/=lib/ens-contracts/"
"@ensdomains/buffer/=lib/buffer/"

the first one works but the following ones don't

**Comment by PaulRBerg** [comment]
Just switch to node modules guys - check out my [Foundry template](https://github.com/PaulRBerg/foundry-template).

https://twitter.com/PaulRBerg/status/1736694426578137247

**Comment by hungtran2492** [comment]
this apps full of bugs haha.

**Comment by lorbke** [comment]
any progress on this issue? Still having it a year later.

**Comment by BrennerSpear** [comment]
I might be doing something wrong, but I'm still gettin this issue. Been stuck on it for awhile
