### ISSUE TITLE
Not able to deploy on zk evm polygon testnet 1442 

### ISSUE THREAD

**Issue by supernovahs** [foundry-rs/foundry#5452]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (c92dabc 2023-04-14T00:06:11.253773000Z)

### What command(s) is the bug in?

forge create

### Operating System

macOS (Apple Silicon)

### Describe the bug

No discriminant in enum `Chain` matches the value `1442` 
When running forge create with zk evm polygon testnet rpc url

**Comment by xeno097** [comment]
I think that the version of foundry you are using is outdated. I managed to deploy a contract at address [0x83c0fa3e2b1ac388bd1aeb268f169882f31971e1](https://testnet-zkevm.polygonscan.com/address/0x83c0fa3e2b1ac388bd1aeb268f169882f31971e1) using the latest version:
```shell
forge 0.2.0 (6e09b4e 2023-07-22T00:17:34.012434229Z)
```
Can you run `foundryup` to update foundry and see if the issue persists?

Just in case you need it I'm leaving the command I used for the deployment

```shell
forge create src/Counter.sol:Counter --rpc-url=https://rpc.public.zkevm-test.net --private-key=$PRIV_KEY
```
