### ISSUE TITLE
Default Solidity Templates can be refactored.

### ISSUE THREAD

**Issue by allwin199** [foundry-rs/foundry#5455]
In default solidity templates

```
import "forge-std/Script.sol";
import "forge-std/Test.sol";
import "../src/Counter.sol";
```
This can be changed to `named` imports for better readability.

```
import {Script} from  "forge-std/Script.sol";
import {Test} from "forge-std/Test.sol";
import {Counter} from "../src/Counter.sol";
```

If this is necessary, I would like to work on this.

**Comment by Evalir** [comment]
Assigned!

**Comment by allwin199** [comment]
@Evalir can I bump the foundry version to `^0.8.18` in templates?

**Comment by Evalir** [comment]
I'd say let's keep it at `^0.8.13` just for having that wiggle room—no need to force users to a very recent solidity version

**Comment by allwin199** [comment]
Sure!
