### ISSUE TITLE
README template can be added to forge init

### ISSUE THREAD

**Issue by allwin199** [foundry-rs/foundry#5456]
### Component

Forge

### Describe the feature you would like

README.md file can be added to the `forge` template.

This file can contain

```
forge build 
forge test
# to run a single test
forge test --mt <filename> 
```
more info about `anvil` and `chisel` can be also mentioned here.

If this is necessary, I would like to work on this.

**Comment by Evalir** [comment]
Happy to assign this to you @allwin199

**Comment by allwin199** [comment]
@Evalir I have created a basic README.md template, let me know if there is anything to be added or deleted.
Also, I have added this file only to [assets directory](https://github.com/foundry-rs/foundry/tree/master/cli/assets).
Let me know if this has to be mapped anywhere to be downloaded with `forge init`
