### ISSUE TITLE
anvil cannot fork from https://ethereum-goerli.publicnode.com

### ISSUE THREAD

**Issue by aathan** [foundry-rs/foundry#5458]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

anvil 0.1.0 (6e09b4e 2023-07-24T00:19:12.456381803Z)

### What command(s) is the bug in?

anvil

### Operating System

Linux

### Describe the bug

This should "just work" right? Repeated calls show a different (higher) `result` in the jsonrpc portion of the JsonRpcClientError, so this data does seem to indicate a proper response from publicnode.com.  hardhat is able to fork from that url without a problem.

```
$ RUST_LOG="info" anvil --fork-url https://ethereum-goerli.publicnode.com
thread 'main' panicked at 'Failed to get fork block number: JsonRpcClientError(SerdeJson { err: Error("response must be either a success/error or notification object", line: 1, column: 71), text: "{\"jsonrpc\":\"2.0\",\"method\":\"eth_blockNumber\",\"result\":\"0x8f696c\",\"id\":1}" })', /home/runner/work/foundry/foundry/anvil/src/config.rs:841:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by mattsse** [comment]
for some reason this endpoint returns the method value itself in the response

> {\"jsonrpc\":\"2.0\",\"method\":\"eth_blockNumber\",\"result\":\"0x8f6a50\",\"id\":1}

which is invalid json rpc

**Comment by Evalir** [comment]
Yep as mattsse said, this endpoint is returning invalid json rpc. It's a bit of a minor issue but we prefer to keep it strict

closing as reason is found

**Comment by aathan** [comment]
Can we have a `--relaxed-rpc` option? It seems in other areas (I remember seeing a thread on this topic), foundry/anvil is looking to achieve parity with hardhat and it arguably should be possible to move a project between hardhat and foundry easily. This would allow devs to both test that two EVM emulators from different sources yield the same behaviors, as well as test the emulators themselves. Also, with problems stemming from upstream inaccuracies relative to standards, there's not much that users can do. Failing to process a response that returns a base 10 vs base 16, or without zero padding, for example, are problems I've reported in hardhat which were relaxed in cases deemed safe. Also relevant is that publicnode.com has a non-trivial user base.

Meanwhile I'll alert publicnode.com.

**Comment by aathan** [comment]
For anyone else stumbling on a similar issue, you can relax ether-rs's strict json rpc response handling by making this change in ethers-providers/src/rpc/transports/common.rs ~ line 211:

```
                 match (id, result, error, method, params) {
                   (Some(id), Some(result), None, None, None) => {
```

to

```
                 match (id, result, error, method, params) {
                    (Some(id), Some(result), None, _, _) => {
```

**Comment by aathan** [comment]
See https://github.com/foundry-rs/foundry/pull/5490
