### ISSUE TITLE
Anvil does not recover block number from state after restart.

### ISSUE THREAD

**Issue by kamenik** [foundry-rs/foundry#5460]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (35f2070 2023-07-24T15:04:54.605528057Z)

### Operating System

Linux

### Describe the bug

After restart, anvil loads state from previously stored one, but starts count blocks from 1 again. I am running it as:

`anvil --port 7545 --accounts 200 --mnemonic '........' --block-time 12 --state ./state.json --gas-limit 30000000`

**Comment by nambrot** [comment]
Also running into this

**Comment by mattsse** [comment]
I see this only dumps the state

https://github.com/foundry-rs/foundry/blob/0232ee56a20324af443e69b0c42db7c0b12031d8/crates/anvil/src/eth/backend/db.rs#L335-L335

maybe we should consider also including the block number etc?

**Comment by kkharji** [comment]
Yeah this would be awesome feature to have. For my use case I need to maintain transactions and block number between restarts. If someone can pointing me to right direction, I can open a PR/.

**Comment by mattsse** [comment]
totally, forgot about this sorry.
will try to squeeze in this week.

**Comment by NikitaBerezhnoy** [comment]
Had problem with this bug. I want to launch anvil on a separate server and connect subgraph to it, so we can use it as a private dev testnet, but I use state file to deploy contracts and setup state (20k tx)

**Comment by escottalexander** [comment]
I would really love to see this fixed. It would make it possible for me to run Anvil instead of Ganache or Hardhat for my application.

**Comment by mattsse** [comment]
fixing as we speak,

very sorry for the delay
