### ISSUE TITLE
feat req: `cast call --trace` or expand `cast run` to unpublished txs

### ISSUE THREAD

**Issue by nhtyy** [foundry-rs/foundry#5461]
### Component

Cast

### Describe the feature you would like

when debugging contracts i think it would be useful to have to access to potential traces on the fly, for instance nowadays when writing some rust/js code its pretty common for me to need to call a function because something is reverting (often to do some encoding scheme lol)

so basically `cast run` for unpublished txs, at the moment, i just use a empty forge test with a fork to see the trace

### Additional context

ALSO, i would love to be assigned this feature :) seems pretty straight forward, fork the current remote env, run it, print trace

**Comment by Evalir** [comment]
Done, assigned it to you—give it a shot! 😄

**Comment by nhtyy** [comment]
Going with `cast call --trace`
