### ISSUE TITLE
Foundry auto caches the last 3 solc versions, however these are specifically identified by their version numbers (0.8.18,.19,20)

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#5468]
Fix: Add 0.8.21 as Foundry auto caches the last 3 solc versions, these are specifically identified by their version numbers (0.8.18,.19,20) 

This version isnt added to that list (replacing .18)

_Originally posted by @sambacha in https://github.com/foundry-rs/foundry/pull/5459#issuecomment-1649727739_

**Comment by mattsse** [comment]
not exactly sure what this means, can you elaborate?

**Comment by sambacha** [comment]
> not exactly sure what this means, can you elaborate?

Foundry will download solc 0.8.18, 0.8.19, and 0.8.20 in anticipation that they will be used so it reduces the overhead when the user executes their first build as it does not have to download those SOLC versions, it already has when it was first setup.

**Comment by sambacha** [comment]
> not exactly sure what this means, can you elaborate?

I am actually not sure if this effects normal user usage, but this is what I was referring to https://github.com/foundry-rs/foundry/pull/5504

**Comment by Evalir** [comment]
closed with #5504
