### ISSUE TITLE
ChainID changes in tests if you fork in a constructor instead of setUp

### ISSUE THREAD

**Issue by vicnaum** [foundry-rs/foundry#5471]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (114e69d 2023-07-25T11:38:05.716355000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

1. I'm forking during tests using the cheatcodes instead of the command-line parameter.
2. I have a dedicated ForkManagement file that handles all the forking.
3. My TestSetup (main test file which all others inherit from) inherits from ForkManagement.
4. I'm using both `constructor` and `setUp` functions (maybe I shouldn't - cause that's where the bug comes from!)
5. The forking is happening in the ForkManagement constructor
6. It is still the same in the TestSetup constructor, but it suddenly becomes different in TestSetup.setUp (it becomes 31337 default one)
7. If I move the forking from ForkManagement constructor into ForkManagement.setUp - then all is fine

Here are example code snippets to reproduce:

**ForkManagement.sol**
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.13;

import 'forge-std/Script.sol';

contract ForkManagement is Script {
    constructor() {
        vm.createSelectFork("polygon", 45504400);
        console.log('Chain ID in ForkManagement: %s', block.chainid);
    }

    function setUp() public virtual {
    //     vm.createSelectFork("polygon", 45504400);
    //     console.log('Chain ID in ForkManagement.setUp: %s', block.chainid);
    }
}
```

**TestSetup.sol**
```
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import "forge-std/Test.sol";
import "./ForkManagement.sol";

contract TestSetup is Test, ForkManagement {
    constructor() {
        console.log("ChainId in TestSetup constructor: %s", block.chainid);
    }

    function setUp() public virtual override {
        super.setUp();
        console.log("ChainId in TestSetup.setUp: %s", block.chainid);
    }

    function testTest() public {
        console.log("ChainId in TestSetup.testTest: %s", block.chainid);
    }
}
```

You also need to have this in your **foundry.toml**:
```
[rpc_endpoints]
polygon = "${POLYGON_RPC_URL}"
```

And this in your **.env**:
```
export POLYGON_RPC_URL="https://........... your rpc url here"
```

Output of the `forge t`:
```
Logs:
  Chain ID in ForkManagement: 137
  ChainId in TestSetup constructor: 137
  ChainId in TestSetup.setUp: 31337
  ChainId in TestSetup.testTest: 31337
```

Expected output:
```
Logs:
  Chain ID in ForkManagement: 137
  ChainId in TestSetup constructor: 137
  ChainId in TestSetup.setUp: 137
  ChainId in TestSetup.testTest: 137
```

Output if I move the forking to ForkManagement setUp:
```
Logs:
  ChainId in TestSetup constructor: 31337
  Chain ID in ForkManagement.setUp: 137
  ChainId in TestSetup.setUp: 137
  ChainId in TestSetup.testTest: 137
```

**Comment by Evalir** [comment]
Yep you should only use either the constructor or the `setUp` function! thanks for flagging this, we should probably disallow this cc @mds1 @mattsse

**Comment by mds1** [comment]
> Yep you should only use either the constructor or the `setUp` function

What's the status of constructor support? Long term we've discussed deprecating `setUp` in favor of constructors, but I'm not clear on whether only using constructor is equally well supported

**Comment by Evalir** [comment]
Yeah I think constructors aren't really there yet in terms of full support like `setUp` as we do some special stuff with the setup function which i think it's not replicated properly yet on the constructor. That being said, i def think we should at least warn users that using both constructor and setUp is prob not a good idea

**Comment by pegahcarter** [comment]
Is constructor support in the works?
