### ISSUE TITLE
Building from source on Windows seems broken

### ISSUE THREAD

**Issue by pcaversaccio** [foundry-rs/foundry#5473]
### Component

Other (please describe)

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

`forge 0.2.0 (e6574c9 2023-06-25T10:11:04.115137400Z)`

### What command(s) is the bug in?

`cargo install --git https://github.com/foundry-rs/foundry --profile local --force foundry-cli anvil chisel`

### Operating System

Windows

### Describe the bug

I just wanted to do my monthly Windows upgrade of Foundry via:

```console
cargo install --git https://github.com/foundry-rs/foundry --profile local --force foundry-cli anvil chisel
```

and it seems the building it from source on Windows is borked ([full log](https://gist.github.com/pcaversaccio/6042919ed589ab91dd6a774a8d44267b)):

```console
warning: build failed, waiting for other jobs to finish...
error: failed to compile `foundry-cli v0.2.0 (https://github.com/foundry-rs/foundry#41a65936)`, intermediate artifacts can be found at `C:\Users\pasca\AppData\Local\Temp\cargo-installTzqkOQ`
error: failed to compile `anvil v0.1.0 (https://github.com/foundry-rs/foundry#41a65936)`, intermediate artifacts can be found at `C:\Users\pasca\AppData\Local\Temp\cargo-installDpXL4N`
error: failed to compile `chisel v0.1.0 (https://github.com/foundry-rs/foundry#41a65936)`, intermediate artifacts can be found at `C:\Users\pasca\AppData\Local\Temp\cargo-install8RAFRL`
     Summary Failed to install foundry-cli, anvil, chisel (see error(s) above).
error: some crates failed to install
```

Anyone has a clue what's going on?

**Comment by Evalir** [comment]
will take a look—haven't seen anything in ci that could've pointed to this, but might be a newish pr maybe

**Comment by pcaversaccio** [comment]
My configs:

```
- cargo 1.71.0 (cfd3bbd8f 2023-06-08)
- rustc 1.71.0 (8ede3aae2 2023-07-12)
```

**Comment by mattsse** [comment]
this looks like a libgit issue

> error: failed to run custom build command for `libgit2-sys v0.15.2+1.6.4` which requires libgit2

can you try via wsl?

**Comment by pcaversaccio** [comment]
> this looks like a libgit issue
> 
> > error: failed to run custom build command for `libgit2-sys v0.15.2+1.6.4` which requires libgit2
> 
> can you try via wsl?

WSL works, I tested it this morning. This is just when I use Windows directly.

**Comment by pcaversaccio** [comment]
I've been building Foundry from source on Windows for at least a year w/o an issue until now...

**Comment by mattsse** [comment]
hmm, we only test via wsl in CI

> fatal error C1083: Cannot open include file: 'zlib.h': No such file or directory

I think zlib is extra, maybe not installed?

**Comment by pcaversaccio** [comment]
> hmm, we only test via wsl in CI
> 
> > fatal error C1083: Cannot open include file: 'zlib.h': No such file or directory
> 
> I think zlib is extra, maybe not installed?

What's the effort to quickly make a CI test for Windows?

Since when is `zlib` needed? Was this added recently?

**Comment by pcaversaccio** [comment]
I really can't fix the bug with `zlib`; at this point it might be worth opening an issue here: https://github.com/rust-lang/git2-rs. I also found a recent issue with Windows `zlib` here: https://github.com/rust-lang/git2-rs/issues/797.

**Comment by pcaversaccio** [comment]
Let's see https://github.com/rust-lang/git2-rs/issues/972. I really don't know what's wrong, 3 weeks ago everything was still working...

**Comment by pcaversaccio** [comment]
I'm really lost, I tried everything to fix this issue (also via installing `zlib`, uninstall and reinstall rust and cargo etc.). I honestly think it's not a Foundry but a `libgit2` issue... Was anyone able to reproduce this behaviour in the meantime? What I can try later is to install an older foundry version from source (maybe a week ago or so) to see whether I still face the error.

**Comment by pcaversaccio** [comment]
> hmm, libgit2-sys hasn't been updated in over 2 months

yeah I also saw that, idk... (I mean it's not sooo important rn since I use WSL, but still sucks)

**Comment by pcaversaccio** [comment]
I've been trying to build foundry from source at commit [`c835a3df4fb066016d8201047ea58de84486e699`](https://github.com/foundry-rs/foundry/tree/c835a3df4fb066016d8201047ea58de84486e699):

![image](https://github.com/foundry-rs/foundry/assets/25297591/579933e4-2ddd-4b4b-84a9-344a2ee37b3d)

hmm, will go back now another 1 week

**Comment by pcaversaccio** [comment]
Same story for [`ed8b709c8fed1aaec4e7de4e3c95553ef09de034`](https://github.com/foundry-rs/foundry/commit/ed8b709c8fed1aaec4e7de4e3c95553ef09de034):

![image](https://github.com/foundry-rs/foundry/assets/25297591/73a713b1-95be-470d-b8d4-5bb91c075b79)

**Comment by pcaversaccio** [comment]
After trying a couple of other older commits and failing again, I can say the last one I was able to build without issue is version: `forge 0.2.0 (e6574c9 2023-06-25T10:11:04.115137400Z)`. I haven't tried all commits until now since Windows is really slow to compile rust code, but it's just weird...

**Comment by pcaversaccio** [comment]
Alright sers, I tested building Foundry via GH CI:

```yml
name: 🛠 Test Native Windows Foundry Build

on: [workflow_dispatch]

jobs:
  build:
    name: Foundry
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build Foundry from source
        run: cargo install --git https://github.com/foundry-rs/foundry --profile local --force foundry-cli anvil chisel
```

That one seems to work, but man that takes very long (it's the same as on my local machine...):

![image](https://github.com/foundry-rs/foundry/assets/25297591/3e74aa5b-b68a-42f0-9086-c9ec41d710f3)

I continue to document here my rabbit hole deep dive until I find the bug :-D

**Comment by pcaversaccio** [comment]
I can't believe it, I fucking fixed! That's what I did:

- Go to `%TEMP%` folder and delete everything
- Run `rustup update`
- Restart the computer

I honestly don't know what triggered this error (maybe the `%TEMP%` folder), but am just happy it works now...

**Comment by mattsse** [comment]
sorry you had to deal with that,

thank you for reporting this

**Comment by peritoflores** [comment]
Same issue in Ubuntu  .....

**Comment by InfectedIsm** [comment]
> I can't believe it, I fucking fixed! That's what I did:
> 
> * Go to `%TEMP%` folder and delete everything
> * Run `rustup update`
> * Restart the computer
> 
> I honestly don't know what triggered this error (maybe the `%TEMP%` folder), but am just happy it works now...

this worked for me, thanks!!
Had so much issue, i broke everything, then couldn't reinstall forge because of a different issue.
(you're a legend fr...)
