### ISSUE TITLE
match

### ISSUE THREAD

**Issue by veridelisi** [foundry-rs/foundry#5476]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### Operating System

None

### Describe the bug

forge test --match testAccessModifiers
forge test -mt testAccessModifiers is not working

error: unexpected argument '--match' found

<img width="175" alt="Ekran Resmi 2023-07-26 07 51 29" src="https://github.com/foundry-rs/foundry/assets/72710290/1f28ef39-bbfc-41c4-9bb1-54ab0eb2d37e">

<img width="558" alt="Ekran Resmi 2023-07-26 07 52 21" src="https://github.com/foundry-rs/foundry/assets/72710290/7db07a08-6100-42ee-bc4b-6e2756824fab">

I use only
forge test --match-contract AccessModifiersTest --match-test testAccessModifiers

**Comment by Evalir** [comment]
You need to `--`, not `-` (single dashes). Also, `--match` has also been deprecated
