### ISSUE TITLE
can't use forge because the variable is used by another app

### ISSUE THREAD

**Issue by ngmisl** [foundry-rs/foundry#5482]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### Operating System

Linux

### Describe the bug

using ubuntu, FORGE is already used by SNAP, getting  obvious errors:

```
[contracts] Error: 
[contracts] FORGE - training program for SNAP (version 2006-07-28)
```

how do I fix this? there is no way to disable or remove this dependency from SNAP

**Comment by Evalir** [comment]
Uh I think this is a first haha. @onbjerg ideas?

**Comment by mds1** [comment]
This is a different forge binary that you have installed for SnAP: https://manpages.ubuntu.com/manpages/jammy/man1/forge.1.html

You can either uninstall it if you don't use it, or move one of the forge binaries out of your path and create an alias for it. Going to close since this isn't a forge issue, but @ngmisl let us know if you have any more questions :)

**Comment by Frankcastleauditor** [comment]
> This is a different forge binary that you have installed for SNAP: https://manpages.ubuntu.com/manpages/jammy/man1/forge.1.html
> 
> So there's two binaries named `forge` and the SNAP one is the one being used. You can either uninstall it if you don't use it, or move one of the forge binaries out of your path and create an alias for it. Going to close since this isn't a forge issue, but @ngmisl let us know if you have any more questions :)

can you please say how to remove this package

**Comment by ngmisl** [comment]
> > This is a different forge binary that you have installed for SNAP: https://manpages.ubuntu.com/manpages/jammy/man1/forge.1.html
> > So there's two binaries named `forge` and the SNAP one is the one being used. You can either uninstall it if you don't use it, or move one of the forge binaries out of your path and create an alias for it. Going to close since this isn't a forge issue, but @ngmisl let us know if you have any more questions :)
> 
> can you please say how to remove this package

Ulitmately I didn't.

Just added an export line to my shell, for example zsh:

`export PATH="$PATH:/home/USER/.foundry/bin"`
