### ISSUE TITLE
remove redundant is_eip1559 argument

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#5485]
### Component

Anvil

### Describe the feature you would like

the boolean arg is not needed and can be derived from the transaction itself
https://github.com/foundry-rs/foundry/blob/0e33b3e4246482e21b7008a3e6fe115ed6dda85b/anvil/src/eth/backend/mem/mod.rs#L2247C17-L2247C21

**Comment by lazyfuhrer** [comment]
Assign me @mattsse

**Comment by Evalir** [comment]
assigned! go for it

**Comment by dhruvdabhi101** [comment]
If no one is working on this, then i can go for it.

**Comment by Evalir** [comment]
Are you gonna work on this @lazyfuhrer ?

**Comment by lazyfuhrer** [comment]
You can assign him

**Comment by Evalir** [comment]
@dhruvdabhi101 assigned!
