### ISSUE TITLE
forge(create): Issue with verifying with `forge create --verify`

### ISSUE THREAD

**Issue by lucas-manuel** [foundry-rs/foundry#5486]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (0e33b3e 2023-07-27T00:26:56.802725000Z)

### What command(s) is the bug in?

forge create --verify

### Operating System

macOS (Apple Silicon)

### Describe the bug

Ran into an issue with `forge create --verify` that seems like a regression, did a `foundryup` and couldn't get it to work and then went to a past commit `foundryup -C 08a629a5e3f33b6750222526c8f58e2beb83f794` (nothing special about this commit) and got it to work.

Steps to reproduce:

Code is here: https://github.com/marsfoundation/spark-spells/tree/sc-62-create-the-august-2-spell-see-description

`export ETH_RPC_URL=$GOERLI_RPC_URL`

Ran `forge create SparkGoerli_20230802 --verify`

And got this: 

```
Contract verification status:
Response: `NOTOK`
Details: `Fail - Unable to verify. Solidity Compilation Error: Source "lib/aave-helpers/lib/aave-address-book/lib/aave-v3-core/contracts/protocol/libraries/types/DataTypes.sol" not found: File not found.`
Contract failed to verify.
```

My current theory is that it is something to do with remappings.

**Comment by Evalir** [comment]
Fixed with #5532 ! ^^
