### ISSUE TITLE
feat(forge): Forge debugger should have calldata and returndata buffer views

### ISSUE THREAD

**Issue by emo-eth** [foundry-rs/foundry#5492]
### Component

Forge

### Describe the feature you would like

The Forge debugger should be able to view both the calldata and returndata buffers. Currently, only the stack and memory are viewable.
Visually, this could be achieved by adding the ability to toggle or cycle the standard panels to returndata/calldata views.

**Comment by iFrostizz** [comment]
supportive !

**Comment by iFrostizz** [comment]
Would be really cool to also highlight the memory that is being returned / reverted / keccaked / ... !!

**Comment by radeksvarz** [comment]
+1 also wanted to raise such issue while debugging my huff made create3 factory

It would be great to have some (tree/list?) view of the call sequence wrt related calldata and returndata.
