### ISSUE TITLE
forge test -vvvv reports less gasUsed than the actual tx in mainnet

### ISSUE THREAD

**Issue by y1cunhui** [foundry-rs/foundry#5494]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8e365be 2023-07-18T00:28:12.648082999Z)

### What command(s) is the bug in?

forge test -vvvv

### Operating System

Linux

### Describe the bug

I want to compare the gas usage of my own MEV bot and the real-world MEV bots.
When I simulate the real-world MEV bot transaction locally, it reports really different gasUsed compared with explorers.

The tx I want to simulate: 0x40aeb6ef9d4d74baa249cc41a1d24cdef08ab4e93b94a7929269822494eb929b

The code I run locally:
```solidity
function setUp() public {
        vm.createSelectFork("eth", 17789587);
        vm.label(address(this), "owner");
        //... omitted
    }
function test1C09() public {
// ...omitted
address bot = 0xD7f3FBe8C72a961A5515203eADA59750437Fa762;
        vm.startPrank(0x1C09A10047fcc944efDE9226e259edDfde2c1cF0);
        bytes memory a = hex"0000000600000000000000000000000000000000000000000000000633f4f445050f0ce0000000000000000000000000000000000000000000000000000000317dc0e0ff0000000000000000000000000000000000000000000000000000000064c357a4";
        bot.call(a);
        vm.stopPrank();
}
```

The gas result when I run `forge test -vvvv`:
![image](https://github.com/foundry-rs/foundry/assets/38470282/1181c932-c061-4ddc-9ab5-ca7bc00e3e30)

The actual gas usage:(images from https://explorer.phalcon.xyz/tx/eth/0x40aeb6ef9d4d74baa249cc41a1d24cdef08ab4e93b94a7929269822494eb929b)

![image](https://github.com/foundry-rs/foundry/assets/38470282/5434934d-ae91-4c9b-ae2b-e2b5ad7ac99e)
![image](https://github.com/foundry-rs/foundry/assets/38470282/f8039ad6-624f-44e1-9f04-ce76d79ba79d)

After comparison, we can see they have the same gasUsed in the staticcalls(like balanceOf), and the uniswapV3Callback call also have the same gasUsed. However, when considering the whole tx or even the single `USDC.transfer`, the gas gap is huge.

When simulate this tx using `trace_call` JSON-RPC interface, it gives me the right number(identical to the `executed gas` part of the Gas Profiler of Phalcon) 

I don't know where the gas gap comes from, so open this issue.

**Comment by y1cunhui** [comment]
When using script instead of test, it gives a mroe accurate result:
![image](https://github.com/foundry-rs/foundry/assets/38470282/b7f8ff6b-e601-49ee-8384-86f8678f484b)
Now the call to pool.swap is identical to real tx. Apart from the base fee and calldata gas, there is still 4200 gas difference. I think maybe this gap is from `read params from calldata` and `read params from memory`?

**Comment by Evalir** [comment]
This is due to different things, but mainly just how we set the EVM for testing. When it comes to simulation scripts can be more accurate in terms of gas metering.
