### ISSUE TITLE
`EvmError: NotActivated` when calls `balanceOf` method for curve LP token

### ISSUE THREAD

**Issue by 0xmikko** [foundry-rs/foundry#5500]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (0e33b3e 2023-07-28T00:16:41.244077009Z)

### What command(s) is the bug in?

forge test with anvil connect

### Operating System

Linux

### Describe the bug

It returns `EvmError: NotActivated` when calls `balanceOf` method for curve LP token: 

` 0xf5f5B97624542D72A9E06f04804Bf81baA15e2B4::balanceOf(PricePrinterTest: [0x34A1D3fff3958843C43aD80F30b94c510645C316])`

![Screenshot from 2023-07-29 00-55-35](https://github.com/foundry-rs/foundry/assets/26343374/a241eb1a-2e85-4857-99a1-9b7653285f68)

**Comment by Evalir** [comment]
Hey! This is because you need to run forge with `--evm-version shanghai`. If you're using cast run, use `cast run --evm-version shanghai`.
