### ISSUE TITLE
Could not instantiate forked environment

### ISSUE THREAD

**Issue by psych2go** [foundry-rs/foundry#5503]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (0e33b3e 2023-07-26T00:20:00.310757040Z)

### What command(s) is the bug in?

forge test $SEPOLIA_RPC_URL

### Operating System

Linux

### Describe the bug

command: forge test $SEPOLIA_RPC_URL
error:
```
The application panicked (crashed).
Message:  Could not instantiate forked environment: 
Could not instantiate forked environment with fork url: https://eth-sepolia.g.alchemy.com/v2

Context:
- Error #0: Failed to get latest block number
- Error #1: error sending request for url (https://eth-sepolia.g.alchemy.com/v2): error trying to connect: tcp connect error: Connection refused (os error 111)
- Error #2: error trying to connect: tcp connect error: Connection refused (os error 111)
- Error #3: tcp connect error: Connection refused (os error 111)
- Error #4: Connection refused (os error 111)
Location: /home/runner/work/foundry/foundry/evm/src/executor/opts.rs:64

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Aborted
```

I used WSL2. 
In .bashrc，I set the proxy in the following way:
```
export http_proxy="http://windows_ip:7890"
export https_proxy="http://windows_ip:7890"
```

**Comment by Evalir** [comment]
Right, there are two things here:
- forge being unable to connect is because you're probably not setting the `env` var correctly—try defining it on your `foundry.toml` or using `--fork-url`.
- We could probably make `evm_env` fail a bit more gracefully

Closing, this is an user issue (but we'll make the second change)

**Comment by SvenMeyer** [comment]
So, i.e. if I have this in my `bashrc` it's not suppose to work ? .. it has be be in a `.env` in the project directory ?
`export MAINNET_RPC="https://mainnet.infura.io/v3/"`

**Comment by c14sh** [comment]
> So, i.e. if I have this in my `bashrc` it's not suppose to work ? .. it has be be in a `.env` in the project directory ? `export MAINNET_RPC="https://mainnet.infura.io/v3/"`

It can be in bashrc or .env, it doesn't matter as long as you set the env var correctly. You can also specify the value directly after `--fork-url`

It appears that many sepolia RPCs are not working.

**Comment by akshwalia** [comment]
--rpc-url works, but why so? Is --fork-url deprecated?
