### ISSUE TITLE
Recover from failed foundryup

### ISSUE THREAD

**Issue by Inphi** [foundry-rs/foundry#5508]
### Component

Foundryup

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (fca0a6c 2023-06-16T00:05:16.412631000Z)

### What command(s) is the bug in?

foundryup -C 3b1129b5bc43ba22a9bcf4e4323c5a9df0023140

### Operating System

macOS (Apple Silicon)

### Describe the bug

Foundryup fails to checkout a specific foundry commit when a prior install failed.
Issue occurs like this:
1. User runs foundryup -C 3b1129b5bc43ba22a9bcf4e4323c5a9df0023140
2. Foundryup git checkout foundry repo at specified commit
3. Foundryup then tries to cargo install foundry
4. rustc linker fails because of a nightly bug
5. User reconfigures rust environment to use stable
6. Users runs foundryup -C 3b1129b5bc43ba22a9bcf4e4323c5a9df0023140
7. Foundryup git checkout fails because there are local changes in the foundryup repo directory

I am able to fix this by manually reverting the changes introduced by step 2; `cd $HOME/.foundry/foundry-rs/foundry && git reset --hard`. It'll be nicer if foundryup were to do this automatically when installing a specific commit.

**Comment by Evalir** [comment]
Hey! We understand but this can be a somewhat destructive feature and can't account for every environment we support, so we consider it a bit out of scope. What we _can_ do is include docs about this!
