### ISSUE TITLE
forge(debug) `goto breakpoint` does not work when the debugger is invoked with `forge debug`

### ISSUE THREAD

**Issue by jameswenzel** [foundry-rs/foundry#5510]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What command(s) is the bug in?

forge debug

### Operating System

macOS (Apple Silicon)

### Describe the bug

the `'<char>` shortcut seems to work when the debugger is invoked with `forge test --debug`, but not when invoked with `forge debug`.

For example, running `forge debug CounterScript` with the following code:
```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import {Script, console2} from "forge-std/Script.sol";
import {Counter} from "../src/Counter.sol";

contract CounterScript is Script {
    Counter counter;

    function setUp() public {}

    function run() public {
        counter = new Counter();
        vm.breakpoint("a");
        counter.increment();
        vm.breakpoint("b");
        require(counter.number() == 1, "number should be 1");
        vm.breakpoint("c");
    }
}
```

or when running `forge debug --sig "testIncrement()" test/Counter.t.sol` with the following code:

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import {Test, console2} from "forge-std/Test.sol";
import {Counter} from "../src/Counter.sol";

contract CounterTest is Test {
    Counter public counter;

    function setUp() public {
        counter = new Counter();
        counter.setNumber(0);
    }

    function testIncrement() public {
        vm.breakpoint("a");
        counter.increment();
        vm.breakpoint("b");
        assertEq(counter.number(), 1);
        vm.breakpoint("c");
    }

}
```

goto breakpoint seems to work normally when running `forge test --debug testIncrement` with the above code.

**Comment by iFrostizz** [comment]
Could I be assigned please ?

**Comment by mds1** [comment]
@iFrostizz just assigned you!

**Comment by iFrostizz** [comment]
Investigating - this may require an additional PR for cleaning up things. Having an explicit `breakpoints` argument that is passed is not very optimal.

**Comment by iFrostizz** [comment]
@jameswenzel what's up after a fresh `foundryup` ? Got merged today !

**Comment by Evalir** [comment]
Nightly will be auto-released in 2h, after this this should be fixed!

**Comment by iFrostizz** [comment]
Tested with latest foundryup, it's working @Evalir ! Can we close that ?

**Comment by Evalir** [comment]
Yep, closing!
