### ISSUE TITLE
`vm.createSelectFork` should set warm coinbase(EIP-3651)

### ISSUE THREAD

**Issue by y1cunhui** [foundry-rs/foundry#5513]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8e365be 2023-07-18T00:28:12.648082999Z)

### Operating System

Linux

### Describe the bug

As [EIP-3651](https://eips.ethereum.org/EIPS/eip-3651), which is applied in Shanghai upgrade, the block.coinbase address should be warm in this block. 
When using the cheatcode createSelectFork, user expect the behaviour to be identical to execute the tx at the top of the specific block. This will have a little effect on gas calculation.

**Comment by zerosnacks** [comment]
Good point! I don't think we currently handle this specific edge case
