### ISSUE TITLE
bug(forge): emitted events are not output in on-chain tracing when running a script without the `--private-key` option

### ISSUE THREAD

**Issue by minaminao** [foundry-rs/foundry#5514]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (25d3ce7 2023-08-01T00:20:16.462585000Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Intel)

### Describe the bug

This is a minor bug.

When the following script

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import {Script, console2} from "forge-std/Script.sol";

contract ContractScript is Script {
    function setUp() public {}

    function run() public {
        vm.startBroadcast();
        new Contract().f();
    }
}

contract Contract {
    event Log(uint256);

    function f() public {
        emit Log(0);
    }
}
```

is run with the `--private-key` option, the following result is displayed,

```
$ forge script ContractScript -vvvvv --private-key $PRIVATE_KEY 
(snip)
## Setting up (1) EVMs.
==========================
Simulated On-chain Traces:

  [88199] → new Contract@0xa0d6b72cf71EE0B8AA7ffb91651E8f86b40267E8
    └─ ← 161 bytes of code

  [25023] Contract::f() 
    ├─ emit Log(: 0)
    └─ ← ()
```

but if it is run without the `--private-key` option, `emit Log(: 0)` is not printed.

```
$ forge script ContractScript -vvvvv
(snip)
## Setting up (1) EVMs.
==========================
Simulated On-chain Traces:

  [88199] → new ContractScript@0x5b73C5498c1E3b4dbA84de0F1833c4a029d90519
    └─ ← 161 bytes of code

  [22380] Contract::f() 
    └─ ← ()
```

full source: https://github.com/minaminao/foundry-bug-reports/tree/main/2023-08-event-not-output

**Comment by Evalir** [comment]
Hey! right, what's the entire command you're using for this?

**Comment by minaminao** [comment]
Hi, the entire command is written in the issue. You couldn't reproduce it using the command?

**Comment by Evalir** [comment]
Hmm I wasn't able to—will try again soon

**Comment by minaminao** [comment]
oh, did you set the rpc?
https://github.com/minaminao/foundry-bug-reports/blob/main/2023-08-event-not-output/foundry.toml#L5

**Comment by zerosnacks** [comment]
Unable to reproduce with the given setup

```
$ forge script script/Counter.s.sol --tc ContractScript -vvvvv
[⠊] Compiling...
No files changed, compilation skipped
Traces:
  [98] ContractScript::setUp()
    └─ ← [Stop] 

  [68945] ContractScript::run()
    ├─ [0] VM::startBroadcast()
    │   └─ ← [Return] 
    ├─ [32287] → new Contract@0x90193C961A926261B756D1E5bb255e67ff9498A1
    │   └─ ← [Return] 161 bytes of code
    ├─ [1179] Contract::f()
    │   ├─ emit Log(: 0)
    │   └─ ← [Stop] 
    └─ ← [Stop] 


Script ran successfully.

[...]
```

Feel free to re-open if you are still experiencing this issue
