### ISSUE TITLE
Next block after `evm_revert` does not have increased timestamp

### ISSUE THREAD

**Issue by michprev** [foundry-rs/foundry#5518]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

anvil 0.1.0 (25d3ce7 2023-08-01T00:20:13.496244391Z)

### What command(s) is the bug in?

anvil --prune-history 100 --steps-tracing --silent --port 36655

### Operating System

Linux

### Describe the bug

It seems that the next block mined after an `evm_revert` JSON-RPC request does not have the timestamp increased. I believe this can be considered a bug since timestamps of blocks mined without `evm_snapshot` and `evm_revert` are always increased by 1.

I think this may be the relevant part of the code:
https://github.com/foundry-rs/foundry/blob/9a4bb7f54563d73b23b597098dcaf1e590905e85/anvil/src/eth/backend/mem/mod.rs#L625-L629

The current behavior is (described in [Woke](https://ackeeblockchain.com/woke/docs/latest/testing-framework/overview/) testing framework):
```python
from woke.testing import *

@default_chain.connect()
def test_reverting():
    t1 = default_chain.blocks["latest"].timestamp
    with default_chain.snapshot_and_revert():
        default_chain.mine()

    t2 = default_chain.blocks["latest"].timestamp
    assert t1 == t2

    default_chain.mine()
    t3 = default_chain.blocks["latest"].timestamp
    assert t3 == t2
```
while the expected behavior is
```python
    assert t3 == t2 + 1
```

**Comment by mattsse** [comment]
@Evalir I think the `self.time.reset(reset_time);` is the culprit here

**Comment by Evalir** [comment]
Hey @michprev — i cannot seem reproduce this either manually or with woke. i haven't used woke before, maybe you can provide a repo that i can clone and run the test to detect this?

**Comment by michprev** [comment]
Hey @Evalir, I have modified the script to call `eth_getBlockByNumber` directly to provide a proof the issue is not in the testing framework.

The steps to reproduce the issue are:
1. `pip3 install -U woke`
2. Create `test_xyz.py` containing the Python code below
3. Run `woke test test_xyz.py`

The script:
```python
import logging
from woke.testing import *
from woke.development.json_rpc.communicator import logger

@default_chain.connect()
def test_reverting():
    logger.setLevel(logging.INFO)

    t1 = int(default_chain.chain_interface.get_block("latest")['timestamp'], 16)
    with default_chain.snapshot_and_revert():
        default_chain.mine()

    t2 = int(default_chain.chain_interface.get_block("latest")['timestamp'], 16)
    assert t1 == t2

    default_chain.mine()
    t3 = int(default_chain.chain_interface.get_block("latest")['timestamp'], 16)
    assert t3 == t2 + 1
```

The script now performs full logging of JSON-RPC communication. I am attaching the log file. Please take a look at requests with id 14 and 16 (`eth_getBlockByNumber`). Both blocks have the same `timestamp` but a different block number.
[log.txt](https://github.com/foundry-rs/foundry/files/12258453/log.txt)

**Comment by klkvr** [comment]
Confirming that issue was the case on 25d3ce7 but is fixed now
