### ISSUE TITLE
Custom Error hashing

### ISSUE THREAD

**Issue by amatureApe** [foundry-rs/foundry#5524]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ca67d15 2023-08-02T00:22:03.700607000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

I am currently doing some testing creating ERC4626 adapters for Sommelier Finance vaults. When running into errors, instead of getting the error, I am instead receiving a hash of the error and I'm not sure if this is unintended behavior from foundry's side. 

The specific contract is here at Cellar.sol: https://etherscan.deth.net/address/0x0274a704a6d9129f90a62ddc6f6024b33ecdad36

I expect to receive errors as defined in the contract, but am instead receiving a hash of the error code as shown in the picture below. 

Wanted to check to see if this was an issue on Foundry's end. Thanks

![Screenshot 2023-08-02 at 8 37 54 AM](https://github.com/foundry-rs/foundry/assets/48165147/b1122dd3-03a6-416c-ba94-5957f90a99df)

**Comment by DaniPopes** [comment]
This is very likely fixed.
