### ISSUE TITLE
forge coverage is not producing coverage reports

### ISSUE THREAD

**Issue by aviggiano** [foundry-rs/foundry#5530]
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (f9fc929 2023-06-29T00:04:55.475093000Z)

### What command(s) is the bug in?

forge coverage

### Operating System

macOS (Apple Silicon)

### Describe the bug

Running `forge coverage` on my project is not producing any coverage reports.

https://github.com/aviggiano/fuzzer-evaluation

**Comment by 0xalpharush** [comment]
https://github.com/foundry-rs/foundry/issues/4007

**Comment by Evalir** [comment]
Just noting—we're aware of this, just closing to consolidate on #4007 — let's keep discussing there
