### ISSUE TITLE
Panic for non-English letter

### ISSUE THREAD

**Issue by 0xmikko** [foundry-rs/foundry#5531]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ca67d15 2023-08-02T00:22:03.700607000Z)

### What command(s) is the bug in?

forge t

### Operating System

macOS (Apple Silicon)

### Describe the bug

Occasionally I changed English `c` to Russian `c` and got panic

<img width="1190" alt="Screenshot 2023-08-03 at 00 20 50" src="https://github.com/foundry-rs/foundry/assets/26343374/7110cbd6-5ab0-4619-8407-4c7a8cad7c8b">

**Comment by mattsse** [comment]
can you please provide additional context about what command you're running?
