### ISSUE TITLE
forge can prioritize autogenerated remappigns over the user ones

### ISSUE THREAD

**Issue by alcuadrado** [foundry-rs/foundry#5540]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (2d87c0c 2023-08-04T00:24:28.478338727Z)

### What command(s) is the bug in?

forge build

### Operating System

Linux

### Describe the bug

If an import matches an autogenerated remapping and one provided by the user, the autogenerated one can take precedence, resulting in compilation errors.

I created [this repository](https://github.com/alcuadrado/foundry-custom-remappings-priority) to reproduce it.

**Comment by mattsse** [comment]
I think this is an issue with remapping autodetection because forge is mapping `node_modules/@prb/math/src` to `@prb/=node_modules/@prb/`, I think this is an edge case since there is only one subdir in `node_modules/@prb/` where contracts are: `node_modules/@prb/math/src` hence it maps it like that

you can opt-out via foundry.toml

```
[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]
auto_detect_remappings = false
```

```
forge re                                                                                                  
@prb/math/=node_modules/@prb/math/src/
```

**Comment by mattsse** [comment]
@Evalir 

the issue is how we sort

https://github.com/foundry-rs/foundry/blob/2a88930a4a2b0e96ecf7a03129a7db5740f5483a/config/src/providers/remappings.rs#L127-L130

```
[config/src/providers/remappings.rs:128] &new_remappings = [
    Remapping {
        context: None,
        name: "@prb/math",
        path: "node_modules/@prb/math/src/",
    },
    Remapping {
        context: None,
        name: "@prb/",
        path: "/Users/Matthias/git/foundry-repros/foundry-custom-remappings-priority/node_modules/@prb/",
    },
]
```

post:

```
[config/src/providers/remappings.rs:134] &new_remappings = [
    Remapping {
        context: None,
        name: "@prb/",
        path: "/Users/Matthias/git/foundry-repros/foundry-custom-remappings-priority/node_modules/@prb/",
    },
    Remapping {
        context: None,
        name: "@prb/math",
        path: "node_modules/@prb/math/src/",
    },
]
```
