### ISSUE TITLE
cast calldata-decode is too dumb

### ISSUE THREAD

**Issue by banteg** [foundry-rs/foundry#5543]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (31d6498 2023-06-28T00:19:43.942564000Z)

### What command(s) is the bug in?

cast

### Operating System

macOS (Apple Silicon)

### Describe the bug
i tried decoding a very simple calldata i grabbed straight from the wallet

```shell
# what i got
> cast abi-decode --input "approve(address,uint256)" 0x095ea7b300000000000000000000000090c1f9220d90d3966fbee24045edd73e1d588ad50000000000000000000000000000000000000000000000000000000000000000
0x0000000090C1F9220d90d3966FbEE24045EdD73E
13273513334079720284718673085964011655589830771079571127896056687522027143168 [1.327e76]

# what i expect
> cast abi-decode "approve(address,uint256)" 0x095ea7b300000000000000000000000090c1f9220d90d3966fbee24045edd73e1d588ad50000000000000000000000000000000000000000000000000000000000000000
0x90c1f9220d90d3966FbeE24045EDd73E1d588aD5
0
```

i see several problems with that:
- [ ] cast completely ignores the selector when it's present, while it should correctly process it and warn if it doesn't match the provided signature
- [ ] even if this was corrupted calldata, it wouldn't blink at non-zero upper bits for a type with a size less than a word like address
- [ ] it doesn't error out because of leftover undecoded input. if it did, at least the user could suspect their input is wrong.
- [ ] i don't see the need for `--input` option, if a user provides a method name, assume there is a selector, otherwise decode as a tuple

**Comment by banteg** [comment]
found `cast calldata-decode`, so maybe wrong usage on my side

**Comment by mattsse** [comment]
yeah, slightly different usecase, cast cdd is what you're looking for here, but I definitely agree on better warnings/errors

it should either strip the matching identifier or display an appropriate error that this is unexpected and refer to calldata-decode

> cast abi-decode --help
> Decode ABI-encoded input or output data.

> Defaults to decoding output data. To decode input data pass --input.

> When passing `--input`, function selector must NOT be prefixed in `calldata` string
