### ISSUE TITLE
**Feature Request: Forge-Snapshots-Analyzer for Comparing Gas Snapshots** 🕵️

### ISSUE THREAD

**Issue by CarlosAlegreUr** [foundry-rs/foundry#5552]
### Component

Forge

### **Description:**
Hi there! While auditing some projects using Foundry, I couldn't find a feature that could be incredibly beneficial to many users. Specifically, I noticed the absence of a way to compare gas snapshots for quickly assessing the overall effects of gas optimizations in test cases.

To fill this gap, I've created some bash scripts that perform this analysis. You can find the code and an overview of the functionality in my repository:
[Forge-Snapshots-Analyzer](https://github.com/CarlosAlegreUr/Forge-Snapshots-Analyzer)
https://github.com/CarlosAlegreUr/Forge-Snapshots-Analyzer

### **Proposed Enhancement:**
I propose rewriting my analyzer in Rust and integrating it directly into Forge. This would provide a native, efficient way to perform gas comparisons within the framework. Such a feature could help developers to quickly asses the impact of their changes.

### **Benefits:**
- Faster insight into gas consumption across different code versions or optimizations.
- A unified toolset within Forge for gas analysis, enhancing usability.
- Encouraging best practices in optimizing gas consumption.

### **Next Steps:**
I would enjoy contributing with this feature to Forge and would be happy to collaborate on the design and implementation if there's interest.

What are your thoughts?

Looking forward to hearing from you, and happy to provide more details if needed!

Best,
Carlos Alegre Urquizú

### Additional context

This is how my analyzer currently displays results
![net-zero-snapshot](https://github.com/foundry-rs/foundry/assets/88899281/1cea3916-0196-40df-a759-771d56df7c5b)
![not-optimized-snapshot](https://github.com/foundry-rs/foundry/assets/88899281/ec23580c-2361-4643-9114-b29e075edbbb)
![optmized-snapshot](https://github.com/foundry-rs/foundry/assets/88899281/654dd698-c219-40b0-888e-f8ce8f8baed0)

**Comment by zerosnacks** [comment]
Hi @CarlosAlegreUr thanks for your suggestion

Marking this as resolved as we currently have a `forge snapshot --diff <SNAPSHOT_NAME>` command to get the difference between different snapshots in percentage terms

```
forge snapshot --diff
[⠊] Compiling...
No files changed, compilation skipped

Ran 2 tests for test/Counter.t.sol:CounterTest
[PASS] testFuzz_SetNumber(uint256) (runs: 256, μ: 30977, ~: 31288)
[PASS] test_Increment() (gas: 31303)
Suite result: ok. 2 passed; 0 failed; 0 skipped; finished in 11.27ms (10.92ms CPU time)

Ran 1 test suite in 272.87ms (11.27ms CPU time): 2 tests passed, 0 failed, 0 skipped (2 total tests)
testFuzz_SetNumber(uint256) (gas: 0 (0.000%)) 
test_Increment() (gas: 0 (0.000%)) 
Overall gas change: 0 (0.000%)
```
