### ISSUE TITLE
Debugger feature requests

### ISSUE THREAD

**Issue by laudiacay** [foundry-rs/foundry#5553]
### Component

Forge

### Describe the feature you would like

The debugger experience is pretty slick, but could be even better.

- Making it smarter about where solidity structs are laid out and labelling them with variable names
- visual storage/memory explorer with struct/variable knowledge
- calling convention/ABI.encode awareness
- get better at not losing where it is with weird assembly/reentrancy

### Additional context

Was using the debugger last night, very exciting :) but I ended up falling back to "just logging a bunch" repeatedly in a way I wouldn't have with GDB.

Thanks for building this, excited to see where it goes!

**Comment by zerosnacks** [comment]
Marking as `duplicate`, added your suggestions to the debugger meta issue: https://github.com/foundry-rs/foundry/issues/927
