### ISSUE TITLE
 forge test --contracts ./src/test/mander.sol -vvv

### ISSUE THREAD

**Issue by ashtimar12** [foundry-rs/foundry#5554]
### Component

Forge, Foundryup, Other (please describe)

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

pragma solidity ^0.8.10;pragma solidity ^0.8.18

### What command(s) is the bug in?

 forge test --contracts ./src/test/mander.sol -vvv

### Operating System

None

### Describe the bug

[FAIL. Reason: Setup failed: Failed to get account for 0x1804c8ab1f12e6bbf3894d4083f33e07309d1f38: 0x1804c8ab1f12e6bbf3894d4083f33e07309d1f38] setUp() (gas: 0)
Test result: FAILED. 0 passed; 1 failed; 0 skipped; finished in 52.15s
Ran 1 test suites: 0 tests passed, 1 failed, 0 skipped (1 total tests)
2023-08-07T21:26:05.162094Z ERROR sharedbackend: Failed to send/recv `basic` err=GetAccount(0x4200000000000000000000000000000000000011, 
TimeoutError) address=0x4200000000000000000000000000000000000011
The application panicked (crashed).
Message:  called `Option::unwrap()` on a `None` value
Location: /home/runner/.cargo/git/checkouts/revm-bf744d8ffabcbad9/8833792/crates/revm/src/evm_impl.rs:363

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Aborted (core dumped)

**Comment by Evalir** [comment]
could we get a snippet of the contract you were trying to run? This looks like user error.
