### ISSUE TITLE
Red wave lines below import statement whenever a new project is initialized

### ISSUE THREAD

**Issue by linghuccc** [foundry-rs/foundry#5555]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What command(s) is the bug in?

forge 0.2.0 (ca67d15 2023-08-02T00:16:51.291393754Z)

### Operating System

Linux

### Describe the bug

Firstly, the operating system is Ubuntu-22.04 (Windows subsystem for linux).

Steps to reproduce error:
1. forge init test
2. cd test
3. forge install Openzeppelin/openzeppelin-contracts
4. add "import "openzeppelin-contracts/contracts/access/Ownable.sol";" in /src/Counter.sol

You will see red wave line below import statement as below:
![red](https://github.com/foundry-rs/foundry/assets/59200993/b52683e9-e485-4299-a6f0-f518359397d4)

Close the VS code window and re-open, the red wave line will be gone:
![wave](https://github.com/foundry-rs/foundry/assets/59200993/258649e2-9633-44b7-bc19-88adb465fcf2)

**Comment by Evalir** [comment]
Hi! This is a VScode issue—it has to re-process your project. You can also re-print the remappings to remappings.txt with `forge re > remappings.txt`.
