### ISSUE TITLE
Weird artifacts when having two contracts with different casing in the same file

### ISSUE THREAD

**Issue by iFrostizz** [foundry-rs/foundry#5560]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6672134 2023-08-07T00:22:23.426482201Z)

### What command(s) is the bug in?

forge build

### Operating System

Linux

### Describe the bug

When having a Solidity file with multiple contract whose name is the same but the casing is different, the artifacts generation is a bit weird.

For instance, if we have a file `Counter.sol` with the content:

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

contract Counter {
    uint256 public number;

    function setNumber(uint256 newNumber) public {
        number = newNumber;
    }

    function increment() public {
        number++;
    }
}

contract COUNTER {}
```

The generated artifacts under `out/` use a different layout for this file. It creates a `src/` in this `out/` folder, with the structure

```sh
out/src/
└── Counter.sol
    ├── Counter.json
    └── COUNTER.json
```

While if the name is even *slightly* different,

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

contract Counter {}

contract COUNTERs {}
```

the structure is as expected:

```sh
out/
├── Base.sol
│   ├── CommonBase.json
│   ├── ScriptBase.json
│   └── TestBase.json
├── console2.sol
│   └── console2.json
├── console.sol
│   └── console.json
├── Counter.sol
│   ├── Counter.json
│   └── COUNTERs.json
├── Counter.s.sol
│   └── CounterScript.json
├── IMulticall3.sol
│   └── IMulticall3.json
...
```

Sorry if this bug is originating from the `ethers-rs` repo, please consider transferring it as I have not investigated myself.

**Comment by zerosnacks** [comment]
Hi @iFrostizz thanks for your report

There have been quite a lot of changes to the way artifacts are generated

```
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

contract Counter {
    uint256 public number;

    function setNumber(uint256 newNumber) public {
        number = newNumber;
    }

    function increment() public {
        number++;
    }
}

contract COUNTER {}
```

Currently yields

```
── out
│   ├── Counter.sol
│   │   ├── Counter.json
│   │   └── COUNTER.json
```

As expected

If you are still running into this issue feel free to re-open
