### ISSUE TITLE
fix(`remappings`): proposing rollback changes that deduplicates insertion of `remappings` entry with `.contains()` method

### ISSUE THREAD

**Issue by cool-mestorf** [foundry-rs/foundry#5561]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6672134 2023-08-08T00:21:59.824374000Z)

### What command(s) is the bug in?

forge remappings

### Operating System

macOS (Apple Silicon)

### Describe the bug

This issue proposes to rollback https://github.com/foundry-rs/foundry/pull/5541 and to implement a different fix for the original issue https://github.com/foundry-rs/foundry/issues/5540.

considering a femplate repo with uniswap/v3-core installed, this remappings file

```txt
v3-core/=lib/v3-core/
@uniswap/v3-core/=lib/v3-core/
```

gives this result

```bash
$ forge remappings
@uniswap/v3-core/=lib/v3-core/
ds-test/=lib/forge-std/lib/ds-test/src/
forge-std/=lib/forge-std/src/
solmate/=lib/solmate/src/
v3-core/=lib/v3-core/
```

however this file, which is just two entries in switched order,

```txt
@uniswap/v3-core/=lib/v3-core/
v3-core/=lib/v3-core/
```

gives this result, `v3-core` removed.

```bash
$ forge remappings
@uniswap/v3-core/=lib/v3-core/
ds-test/=lib/forge-std/lib/ds-test/src/
forge-std/=lib/forge-std/src/
solmate/=lib/solmate/src/
```

The problem occurs because of recent fix on remappings entries processing, from merging given configuration and generated entries, sort, and deduplication ([diff](https://github.com/foundry-rs/foundry/pull/5541/files#diff-6620cb198ba2683cd67a6d30c5a96706268bd95e26d02134643f117ea57d0750R36)), to sequentially push entries to configuration object but deduplicate entries that has common suffix ([diff](https://github.com/foundry-rs/foundry/pull/5541/files#diff-5e2a1c419d9d0933e6c8c6f584b3f251326a3f18f96cd748e9bf032ab894255cL155-L156)). Because the entries in `remappings.txt` file are sequentially pushed, some entries may be excluded if they appear behind their supersets - `@uniswap/v3-core` contains `v3-core` but `v3-core` does not contain `@uniswap/v3-core`.

This issue was hard to identify and understand when I got foundryup updated and every imports starting with `v3-core` got broken. I was unable to find any official specification for `remappings.txt` file or remappings configuration formats, and if considering `remappings` consumption by solc occurs sequentially, I would suggest applying no sort or deduplication to merged configuration, but just keep their orders to user defined configs first, and auto-generated next. It may be problematic if there are multiple entries with same key pointing to different destinations, but it does not seem to be harmful in case multiple keys pointing to the same destination, just like the above example. And I think this implementation will be much easier for users to understand the behavior, as it does not override any user-defined configurations.

If specifications are fixed, I would be more than happy to submit a PR for this task.

**Comment by mattsse** [comment]
thanks for flagging

do you have a repro for this @cool-mestorf ?

@Evalir why are the remappings still sorted here?

**Comment by cool-mestorf** [comment]
The sort version I mentioned is from previous PR; Never mind it. I will bring a reproduction asap.

**Comment by mattsse** [comment]
I think we found the issue already:

it's this check

https://github.com/foundry-rs/foundry/blob/6672134672c8e442684d7d9c51fa8f8717b0f600/config/src/providers/remappings.rs#L36-L36
added for https://github.com/foundry-rs/foundry/issues/5540
which should not be contains, but starts_with
