### ISSUE TITLE
feat(cast): cast call --tx-hash `0x...`

### ISSUE THREAD

**Issue by llllvvuu** [foundry-rs/foundry#5568]
### Component

Cast

### Describe the feature you would like

Like `forge debug`, but instead of running as a script can run against a live contract with live state. Similar to the [Truffle debugger](https://trufflesuite.com/docs/truffle/how-to/debug-test/use-the-truffle-debugger/)

**Comment by Evalir** [comment]
hmmm, wondering—does the new `cast call --trace --debug` work here?

**Comment by llllvvuu** [comment]
It could work, yeah. Looks like `--trace` takes a block height, technically replaying a tx depends on not only the block height but also the tx's index within the block. Also syntactic sugar for replaying a txhash would be very dank although could be tricky to hook up the source map

**Comment by zerosnacks** [comment]
Would the expected command look like: `cast call --trace --debug --rpc-url <RPC_URL> <TX_HASH>`?

**Comment by zerosnacks** [comment]
Marking as resolved, supported as follows:

```
cast call 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2 "balanceOf(address)(uint256)" 0x761DF92194FAA59Ea31b828D1bD27ed95B257d20  --rpc-url <RPC_URL> --etherscan-api-key <ETHERSCAN_API_KEY> --trace --debug
```
