### ISSUE TITLE
feat(forge script): add `--verifier-selector-db-url` to use local verifier for selector database

### ISSUE THREAD

**Issue by bschreck** [foundry-rs/foundry#5573]
### Component

Forge

### Describe the feature you would like

When developing contracts, it's sometimes best practice to not release publicly until e.g. audits are finished. It's possible to verify contracts locally via sourcify, but not possible to use these verified contracts for forge script debugging (e.g. getting access to the hash->selector mapping in tracebacks).

Ideally an arg could be added to `forge script` like `--verifier-selector-db-url`

**Comment by grandizzy** [comment]
@bschreck could you please provide a concrete example of what you're trying to accomplish? wouldn't the abi be available locally if those contracts are in active development? (if not you could just add the interfaces in the project). Could be missing something, please add some details. thank you

**Comment by grandizzy** [comment]
we now have added `forge selectors cache` which will be uploading and using the project selectors when decoding traces, please use that and reopen if still an issue. Thank you!
