### ISSUE TITLE
Console logging a bytes32 with an additional string

### ISSUE THREAD

**Issue by jhweintraub** [foundry-rs/foundry#5578]
### Component

Forge

### Describe the feature you would like

When you are debugging a contract and want to console log a bytes32 string you need to use `console.logBytes32(bytes32 _someBytes)`. You cannot also include some kind of string to let the person reading the output what its for. You need to do a separate console log that looks like this

```
console.log("--- SOME EXPLANATION ---");
console.logBytes32(theThing);
```

Would be really great if you could just combine both of these into one call that looks like 
`console.log("some explanation: %s", someBytes32String);`

**Comment by Evalir** [comment]
I think this has been discussed a few times—this might be a better discussion for forge-std, but I believe the general view has been no appetite so far. Closing unless @mds1 wants to move the issue

**Comment by mds1** [comment]
Note this can already be accomplished with existing console.log methods by leveraging `string.concat`, `bytes.concat`, and `vm.toString`
