### ISSUE TITLE
cheatcode: getDeployedCode and etch, can not find the funtion

### ISSUE THREAD

**Issue by chen4903** [foundry-rs/foundry#5579]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0

### What command(s) is the bug in?

forge test

### Operating System

Windows

### Describe the bug

I use forge test to test the following code:

    contract attackTest is Test {

        string constant weth9_Artifact = 'out/helper_WETH9.sol/WETH9.json';

        IWETH9 weth9 = IWETH9(0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2);
    
        function setUp() public {        
           bytes memory runtimeBytecode = vm.getDeployedCode(weth9_Artifact);
           vm.etch(address(weth9), runtimeBytecode);
           console.log(weth9.decimals());
        }    

    contract WETH9 {
        string public name     = "Wrapped Ether";
        string public symbol   = "WETH";
        uint8  public decimals = 18;
        ....
    }
but the output is not 18 but zero. But I use ` console(address(weth9).code.length);`, the output is 1650, so it has runtimecode. I don't know why the `decimals ` is zero but not 18. Maybe something wrong in it?

**Comment by Evalir** [comment]
etch writes arbitrary runtime bytecode to an account—it does not modify its storage. As `decimals` is autogenerated and reads storage, it won't return what you want, as the storage is still empty.
