### ISSUE TITLE
forge test --match-test testLinkCharactersInBatchFail -vvv

### ISSUE THREAD

**Issue by iavl** [foundry-rs/foundry#5583]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (16208aa 2023-08-10T00:21:13.638772620Z)

### What command(s) is the bug in?

forge test --match-test testLinkCharactersInBatchFail -vvv

### Operating System

Linux

### Describe the bug

os: Ubuntu 22.04.2 LTS

logs:
```
forge test --match-test testLinkCharactersInBatchFail -vvv

[⠒] Compiling...
No files changed, compilation skipped
The application panicked (crashed).
Message:  called `Option::unwrap()` on a `None` value
Location: /home/runner/.cargo/git/checkouts/revm-bf744d8ffabcbad9/1478724/crates/revm/src/evm_impl.rs:267

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Aborted (core dumped)
```

Could someone kindly take a look, and my code is [here](https://github.com/iavl/Crossbell-Contracts)

**Comment by bstchow** [comment]
Seeing the same issue in our repo. 

Our tests were passing with
forge 0.2.0 (`16208aa` 2023-08-10T00:21:13.638772620Z)

Our tests are now failing with
forge 0.2.0 (`1044042` 2023-08-10T13:04:25.942019017Z)

**Comment by Evalir** [comment]
Yep, this was due to #5592, which has since been reverted.
