### ISSUE TITLE
Malicious Object Detected [Trojan] when trying to download Foundry

### ISSUE THREAD

**Issue by yenxuan1381** [foundry-rs/foundry#5586]
### Component

Other (please describe)

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

latest

### Operating System

None

### Describe the bug

Malicious object detected when trying to download foundry using the Rust method, on Windows operating system.

What my Kaspersky detected:
```
Event: Malicious object detected
Component: Application Control
Result description: Detected
Type: Trojan
Name: VHO:Trojan.Win32.Convagent.gen
Threat level: High
Object path: C:\[redacted]\cargo-install9Y6UXn\local\build\libm-766624a62d39c941
Object name: build-script-build.exe
Reason: Cloud Protection
MD5: 8707AA726C0D65B0200C03A6612DCF24
```

**Comment by mattsse** [comment]
> Malicious object detected when trying to download foundry using the Rust method, on Windows operating system.

how did you install it?

**Comment by yenxuan1381** [comment]
I'm using Rust, using this command `cargo install --git https://github.com/foundry-rs/foundry --profile local --force foundry-cli anvil chisel`

**Comment by Evalir** [comment]
Closing, cargo binary seems to be the culprit. Can't repro on windows boxes.
