### ISSUE TITLE
Add flag that disables interactive y/n prompting

### ISSUE THREAD

**Issue by storojs72** [foundry-rs/foundry#5587]
### Component

Forge

### Describe the feature you would like

`forge script` when using with large contracts / libraries that exceed EIP-170 size limit, asks following confirmation:

```
[⠰] Compiling...
No files changed, compilation skipped
Script ran successfully.
`Unknown8` is above the EIP-170 contract size limit (128607 > 24576).
`Unknown9` is above the EIP-170 contract size limit (128972 > 24576).
`Unknown21` is above the EIP-170 contract size limit (128972 > 24576).
`Unknown22` is above the EIP-170 contract size limit (31574 > 24576).
`NovaVerifierContract` is above the EIP-170 contract size limit (37490 > 24576).
Do you wish to continue? [y/n] 
```

which can be difficult to handle in tty-disabled environments like docker containers. It would be nice to have `-n`, `-y` flags that can be submitted to `forge script` which disable mentioned interactive prompt.

P.S.: [Solutions](https://askubuntu.com/questions/338857/automatically-enter-input-in-command-line) like `yes | forge script` also don't work in no-tty env.

**Comment by mattsse** [comment]
thanks for flagging,

@Evalir do we have an option to override this? like --force or perhaps better --no-interactive?

I think the reason we added this was to prevent accidental deployments of too large contracts

**Comment by Evalir** [comment]
yeah i think we don't @mattsse — this is a quick add though. agreed it should be a verbose flag

**Comment by storojs72** [comment]
Confirming that it works. Thanks!
