### ISSUE TITLE
Increase DUMMY_CALL_OUTPUT or make it dynamic (if possible)

### ISSUE THREAD

**Issue by apuigsech** [foundry-rs/foundry#5588]
### Component

Forge

### Describe the feature you would like

This feature request is directly related to an issue I raised a few days ago, referenced as #5536. The issue was successfully resolved under #5538 by increasing the DUMMY_CALL_OUTPUT size from 512 to 1024 bytes

In the context of my [openlotto](https://github.com/apuigsech/openlotto-contracts) project, I encounter challenges with certain tests due to the management of large data structures. These structures surpass the dimensions of the DUMMY_CALL_OUTPUT, causing tests utilizing vm.expectRevert() to fail. _The usage of such large data structures warrants a review, as it may indicate an underlying anti-pattern on my code._

In particular, I'd like to draw attention to this specific data structure which is the one causing the issues;

```
    struct LotteryItem {
        string Name;                                                // Human-readable identifier for the lottery.

        uint256 InitBlock;                                          // Block number at which the lottery rounds are initialized or started.
        uint32 Rounds;                                              // Number of rounds or iterations for the lottery (how many times the lottery will be played).
        uint16 RoundBlocks;                                         // Number of blocks between each round.

        uint256 BetPrice;                                           // Cost of a single bet for the lottery.

        uint256 JackpotMin;                                         // Minimum size of the lottery jackpot.

        address[_MAX_DISTRIBUTIONPOOL] DistributionPoolTo;          // Destination for the distribution pool entries. (address(0) sends money to the reserve, remaining value goes to jackpot).
        UD60x18[_MAX_DISTRIBUTIONPOOL] DistributionPoolShare;       // Share (%) for the distribution pool entries.

        UD60x18[_MAX_PRIZEPOOL] PrizePoolShare;                     // Share (%) for the prize pool entries.
        bytes8[_MAX_PRIZEPOOL] PrizePoolAttributes;                 // Attributes for the prize pool entries.

        LotteryOperatorInterface Operator;                          // Contract that 'operates' this lottery.
        bytes16 Attributes;                                         // Attributes for the operator.
    }
```

The most direct solution to my issue could be adjusting the DUMMY_CALL_OUTPUT size. However, maintaining a fixed size for this parameter inherently imposes limitations. Alternatively, a potential solution (albeit with uncertain feasibility) it's implementing dynamic sizing.

_NOTE: this does NOT block me because I am using my own version of `forge` that I patched, sizing DUMMY_CALL_OUTPUT with 4096. If you are happy with that solution, I can PR._

**Comment by mattsse** [comment]
@Evalir let's bump this and also convert this into a lazy so we don't need to clone this everytime
