### ISSUE TITLE
Surface more information about compiler errors

### ISSUE THREAD

**Issue by fubhy** [foundry-rs/foundry#559]
Currently, when there's a compiler error, `forge build` simply hoists the original compiler error message but does not add any information about the responsible sources, e.g.:

```
Error: 
   0: Compiler run failed
      CompilerError: Stack too deep when compiling inline assembly: Variable headStart is 3 slot(s) too deep inside the stack.
```

It would be great if it at least included the name / path of the responsible source file(s).

**Comment by fubhy** [comment]
Interestingly, this error only occurs with `forge build` but `dapp build` works fine. I have to do a bit of debugging...

**Comment by onbjerg** [comment]
This is unfortunately all that the Solidity compiler gives us for this specific error :(

I'll cc @mattsse in case he has some clever idea, but I don't see us being able to add more context unless we compile each file separately or we fix it upstream, so I'll close this for now

**Comment by fubhy** [comment]
@onbjerg Right... That makes sense. Would it help to add a cli option to instead group the sources by origin file and have the cli iterate on those one by one so we can at least pin point which of the source trees is responsible?

If I'm interpreting the `compiler.rs` code correctly, that should be fairly simple, no?

**Comment by gakonst** [comment]
we seem to be eating up some of the compiler output (the file source) here yeah, should def print the filename. @mattsse seems to be an ethers-solc issue

**Comment by onbjerg** [comment]
@gakonst If you look at the tests in the compiler repo this specific error gives no context at all:

- https://github.com/ethereum/solidity/blob/69411436139acf5dbcfc5828446f18b9fcfee32c/test/scripts/fixtures/stack_too_deep_json_output.json
- https://github.com/ethereum/solidity/blob/e6e30f82cac301b519182caba50300f9aec865ac/libyul/backends/evm/AsmCodeGen.cpp

**Comment by lucas-manuel** [comment]
Close-able? @mds1

**Comment by Valentin-Seehausen** [comment]
Maybe adding a hunt-compiler-error process that iterates through files? Will learn Rust, I promise.
