### ISSUE TITLE
Incorrect error report for missing --rpc-url in forge script

### ISSUE THREAD

**Issue by kadenzipfel** [foundry-rs/foundry#5594]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (1044042 2023-08-10T13:09:55.662307000Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

When running `forge script` with a missing `--rpc-url` value, the error output is: `error: a value is required for '--fork-url <URL>' but none was supplied`. Instead, the error output should be: `error: a value is required for '--rpc-url <URL>' but none was supplied`.

**Comment by Evalir** [comment]
Right, this is because `rpc-url` is an alias to `fork-url`—this message is constructed automatically by the CLI lib we use. While it's definitely not the exact value used, it's not necessarily a big deal (this could probably be filed on clap though)
