### ISSUE TITLE
solc repeated installation: makes the foundry too slow

### ISSUE THREAD

**Issue by chen4903** [foundry-rs/foundry#5601]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

0.2.0

### What command(s) is the bug in?

forge test --match-path test/04.broker/attackTest.sol -vvvv

### Operating System

Windows

### Describe the bug

When I run a test for example: forge test --match-path test/04.broker/attackTest.sol -vvvv, the foundry will install sloc again and again although it has install the same sloc version before.
   
    PS E:\BlockChainCTF\Paradigm 2021> forge test --match-path test/04.broker/attackTest.sol -vvvv
    [⠊] Compiling...
    [⠆] Installing solc version 0.5.12
    [⠰] Successfully installed solc 0.5.12
    [⠒] Installing solc version 0.4.26
    [⠒] Successfully installed solc 0.4.26
    [⠒] Compiling 5 files with 0.8.0
    [⠘] Solc 0.8.0 finished in 4.83s
    Compiler run successful!

    Running 1 test for test/04.broker/attackTest.sol:attackTest
    [PASS] test_isComplete() (gas: 189)
    Traces:
    [189] attackTest::test_isComplete()
        └─ ← ()

    Test result: ok. 1 passed; 0 failed; 0 skipped; finished in 3.51ms
    Ran 1 test suites: 1 tests passed, 0 failed, 0 skipped (1 total tests)
    PS E:\BlockChainCTF\Paradigm 2021> forge test --match-path test/04.broker/attackTest.sol -vvvv
    [⠊] Compiling...
    [⠘] Installing solc version 0.4.26
    [⠊] Successfully installed solc 0.4.26
    [⠒] Installing solc version 0.5.12
    [⠢] Successfully installed solc 0.5.12
    No files changed, compilation skipped

    Running 1 test for test/04.broker/attackTest.sol:attackTest
    [PASS] test_isComplete() (gas: 189)
    Traces:
    [189] attackTest::test_isComplete() 
        └─ ← ()

    Test result: ok. 1 passed; 0 failed; 0 skipped; finished in 2.19ms
    Ran 1 test suites: 1 tests passed, 0 failed, 0 skipped (1 total tests)
    PS E:\BlockChainCTF\Paradigm 2021> forge --version
    forge 0.2.0 (56adbe4 2023-07-16T07:03:29.896803000Z)

In this example, the sloc version 0.4.26 and 0.5.12 install again. Once I run a test, foundry will install the sloc though it has install it before, it makes my foundry too slow.

**Comment by mattsse** [comment]
hmm, can you please run with `RUST_LOG=ethers` and share the logs?

this could be a checksum issue, can you try nuking the `~/svm` folder

**Comment by chen4903** [comment]
I have tried: deleted ~/svm, but the problem is the same.
sorry, I don't know how to run with RUST_LOG=ethers, the command.

And I try many times, there is something wrong: I cannot download the solc, maybe the solc bans my IP because I send to many request?

    PS E:\BlockChainCTF\Paradigm 2021> forge test --match-path test/04.broker/attackTest.sol -vvvvv
    [⠊] Compiling...
    [⠘] Installing solc version 0.4.26
    [⠃] Failed to install solc 0.4.26: error sending request for url (https://binaries.soliditylang.org/windows-        amd64/list.json): error trying to connect: 远程主机强迫关闭了一个现有的连接。 (os error 10054)
    Error: 
    error sending request for url (https://binaries.soliditylang.org/windows-amd64/list.json): error trying to connect: 远程主机强迫关闭了一个现有的连接。 (os error 10054)

    Context:
    - Error #0: error trying to connect: 远程主机强迫关闭了一个现有的连接。 (os error 10054)
    - Error #1: 远程主机强迫关闭了一个现有的连接。 (os error 10054)

**Comment by mattsse** [comment]
like
> RUST_LOG=ethers forge test

or set the RUST_LOG env var

**Comment by chen4903** [comment]
my PC: windows 11. 
I try: `set RUST_LOG=ethers`, and then run `forge test --match-path test/04.broker/attackTest.sol -vvvv`, but it doesn't print the log. I google in the Internet but can not find the command.

**Comment by mattsse** [comment]
> 2023-08-12T05:33:53.821384Z TRACE compile: ethers_solc::resolver: verifying solc checksum for 
> C:\Users\ChenQin\.svm\0.4.26\solc-0.4.26
2023-08-12T05:33:53.842706Z TRACE compile: ethers_solc::resolver: corrupted solc version, redownloading  "0.4.26"

interesting, can you check what's the sha2 of these files?

**Comment by chen4903** [comment]
I use this site to hash: https://oktools.net/file-hash

C:\Users\ChenQin\.svm\0.4.26\solc-0.4.26

    solc-0.4.26	(n/a) - 3892736bytes
    MD5	        8de83ca7945828afc9e77f3083eeecfe
    SHA1  	b4d642b6a497f7ec5ed4c0404ab276e74d4b290e
    SHA256	c2218bfc4ad4dfde9b56cff0a2d53b4c5a540d131394a9c7535390b364afe933

C:\Users\ChenQin\.svm\0.5.12\solc-0.5.12

    solc-0.5.12	(n/a) - 5783040bytes
    MD5	  	1a7e64b2859a03079b840a1b6c9b61be
    SHA1		5ed4e6a29d927225046dba870fbc8529678a8ba7
    SHA256	c37b19013b3bac6e5ec5e201882332bde26d1b7916a3a784974de3e74013ad08

C:\Users\ChenQin\.svm\0.7.0\solc-0.7.0

    MD5		6447f140ba80b761a80a1a54c77f0f05
    SHA1		372e68a254aa607c5dd70e0d1f17f41a3af7067c
    SHA256	08bcfc125791ca7993fa4a9fff1a669792b4a014d59b04f61a154e97fda527cf

C:\Users\ChenQin\.svm\0.5.12\solc-0.8.0

    MD5		4d1e06259de9b47b6070ab6a0a86a542
    SHA1		f6a70b5ab094bd2ad95e4aa92aeffa8ac7276a33
    SHA256	ed74a625bd67dbb74f616aec64f771060df3376f38ef068bd17fd5a5fe19d98c

C:\Users\ChenQin\.svm\0.4.26\slotest.exe

    soltest.exe	(application/x-msdownload) - 13295616bytes
    MD5		3333322b1020a8583a4874304b2dae6d
    SHA1		304e4a370c851ada13db5af3b11637a8636a14c8
    SHA256	9e4b2bfde031cfe03fa408b93f6da91d95ebd77da28ff207e0ea7be0504ea278

the ~.svm: 

    C:\Users\ChenQin\.svm>tree /f
    C:.
    │  .global-version
    │
    ├─0.4.26
    │      msvcp140.dll
    │      msvcp140_1.dll
    │      msvcp140_2.dll
    │      solc-0.4.26
    │      soltest.exe
    │
    ├─0.5.12
    │      msvcp140.dll
    │      msvcp140_1.dll
    │      msvcp140_2.dll
    │      solc-0.5.12
    │      soltest.exe
    │
    ├─0.7.0
    │      msvcp140.dll
    │      msvcp140_1.dll
    │      msvcp140_2.dll
    │      solc-0.7.0
    │      soltest.exe
    │
    └─0.8.0
            solc-0.8.0

**Comment by mattsse** [comment]
ah yikes, on windows this track the hash of the zip file not the actual binary.

will get that fixed, in the meantime you can run with --offline to prevent redownloads

**Comment by chen4903** [comment]
I use `--offline` and it works.
_on windows this track the hash of the zip file not the actual binary_ : Do I need to provide u hash fo another files? Or it is a bug in windows(mine is 11)?

**Comment by DaniPopes** [comment]
All releases before 0.7.2 (excluded) hash the zip file instead of the executable file. You can see this in the [`binaries.soliditylang.org` binaries list](https://binaries.soliditylang.org/windows-amd64/list.json) for windows-amd64 (look for change between .zip and .exe in 0.7.1 and 0.7.2).
This should be fixed in the next nightly release, thanks for the report!
