### ISSUE TITLE
bug(Coverage): `forge coverage --report lcov` is failing after the latest release

### ISSUE THREAD

**Issue by jalextowle** [foundry-rs/foundry#5609]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

Run forge --version forge 0.2.0 (3fec8c1 2023-08-11T00:15:50.024503184Z)

### What command(s) is the bug in?

forge coverage

### Operating System

Linux

### Describe the bug

`forge coverage --report lcov` runs for 6 hours before our CI actions are timing out. I'm posting screenshots from before and after the new release dropped. Prior to the new release, we never had issues with our code coverage action, but since the release, every coverage job has run for 6 hours and failed due to a timeout. 

Here's a screenshot showing our recent job statuses:
<img width="1355" alt="Screen Shot 2023-08-11 at 10 29 46 AM" src="https://github.com/foundry-rs/foundry/assets/34827329/08eb6ebc-8123-405f-a165-d72ba2fe0b7e">

I looked at the release history, and the latest release coincides with this. 
<img width="1290" alt="Screen Shot 2023-08-11 at 10 18 39 AM" src="https://github.com/foundry-rs/foundry/assets/34827329/cd094f06-4a39-4e4c-b625-95163118eef2">

I downgraded to version `forge 0.2.0 (1044042 2023-08-10T13:04:25.942019017Z)`, and sure enough, the coverage job succeeds: 

<img width="1727" alt="Screen Shot 2023-08-11 at 10 38 38 AM" src="https://github.com/foundry-rs/foundry/assets/34827329/6203de2f-396f-4244-88c0-b858daaf527c">

Downgrading is an easy fix for us in the meantime, but let me know if there's any other information that would be helpful when investigating this. Unfortunately, our repo is private at the moment, so I don't have an example to point to.

**Comment by mathieu-bour** [comment]
I can confirm this bug on my [company's smart contract repository](https://github.com/pooky-labs/smart-contracts). See relevant [action run](https://github.com/pooky-labs/smart-contracts/actions/runs/5834027779?pr=67).

**Comment by arr00** [comment]
Actions broke on my repo as well. Reran past actions that succeeded and they fail now.

**Comment by Evalir** [comment]
Hey all! this is a result of revm upgrades we recently did—we're rolling out a fix soon: #5610

**Comment by mathieu-bour** [comment]
Issue seems to be solved in my CI

**Comment by 0xTimepunk** [comment]
@Evalir the issue has returned today on our CI, can you please verify?

**Comment by Evalir** [comment]
Closed with #5695 and #5698
