### ISSUE TITLE
targeted_contracts in invariant test is getting updated unexpectedly partway through an invariant test run

### ISSUE THREAD

**Issue by Melvillian** [foundry-rs/foundry#5625]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a0a31c3 2023-08-11T18:45:55.249069000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

Background:

I am running a invariant test contract using a forked version of the blockchain pointing at Mainnet, with a single Handler, and I only want the Handler and its functions to be called throughout the entire invariant test run. Any calls to non-handler functions is undesired and results in me needing to set `fail_on_revert = false` in order to prevent my invariant test run from failing every time.

Expected Behavior:

I use `targetContract` and `targetSelector` to select my Handler's address and various Handler functions, respectively, in the `setUp` function of my InvariantTest contract. This will mean that the only function I ever see being fuzzed should be the Handler. I should run `forge test -vvvv` and not see any calls to other contracts

Actual Behavior:

When I run `forge test -vvvv`, I see that there are many calls being made to a contract that was deployed during the `setUp` of my InvariantTest contract. Specifically, the only other contract besides the Handler being fuzzed is the one that was setup with the code below. The purpose of the code below is to take an already-deployed (i.e. already existing contract on the mainnet fork) and overwrite its bytecode with my own supplied code in order to mock it and make testing simpler:

```solidity
function _deployMockBridge() internal {
        vm.selectFork(_l1Fork);
        MockBridge mb1 = new MockBridge();
        bytes memory mb1Code = address(mb1).code;
        vm.etch(_bridge, mb1Code);

        vm.selectFork(_l2Fork);
        MockBridge mb2 = new MockBridge();
        bytes memory mb2Code = address(mb2).code;
        vm.etch(_bridge, mb2Code);
    }
```

Hypothesis:

I cloned `foundry` and added some debugging logs to a locally running version of `forge` in order to try to understand what is going on. From running that, I was able to that in [this executor.rs function](https://github.com/foundry-rs/foundry/blob/master/crates/evm/src/fuzz/strategies/state.rs#L251) the list of targeted_contracts is being updated with the MockBridge code's address. Whys is that happening, even though we never deployed the MockBridge in our InvariantTeest? My guess is that because of [this check in collect_data](https://github.com/foundry-rs/foundry/blob/master/crates/evm/src/fuzz/invariant/executor.rs#L556C13-L556C21), because of the call to `vm.etch`, there is a bug where Forge thinks that we actually did deploy the contract with a sender that didn't have any code (whatever addresses is used by `vm`) and so it ends up adding the MockBridge contract to the listed of `created_contracts`, which ultimately gets sampled from to decide on the next fuzz run, and thus will probabilistically end up choosing the MockBridge code and its selectors to be fuzzed.

Solution:
when calculated `created_contracts`, exclude any that were touched by Cheatcode addresses, as those are not really created, as we can see here with `etch`. Though to be clear, I'm not sure this is the problem because I'm not super familiar with Forge's codebase; that is just what I've been able to uncover by manually debugging.

**Comment by Evalir** [comment]
hey—could you try with the latest foundry version by using `foundryup`? this issue was caused by an unrelated update, and should be OK now

**Comment by Melvillian** [comment]
> hey—could you try with the latest foundry version by using `foundryup`? this issue was caused by an unrelated update, and should be OK now

Hey, just upgraded to:

`forge 0.2.0 (93ebcdd 2023-08-15T00:27:50.951269000Z)`

and I'm still seeing the `MockBridge` contract get added to the list of contracts that it uses to build the next fuzz run.

**Comment by PatrickAlphaC** [comment]
@Melvillian I'm seeing something similar. My `MockERC20` keeps getting added and it's breaking my runs.

**Comment by 77abe77** [comment]
this is still happing on `forge 0.2.0 (619f3c5 2023-10-20T00:22:09.970731000Z)`. Please help with this issue bc its super annoying to have to give up on invariant testing bc of features that should work as intended.

**Comment by gabriel-liraa** [comment]
Im having this exact issue with forge 0.2.0 (143abd6 2024-09-04T00:21:38.406856490Z).
Forge keeps running a functions that is not from the targetContract, but from a contract that was deployed in the setUp, even if i exclude this contract and explicitly mark the desired contract as target. (Using fail_on_revert = true)

This is my setUp function:
`function setUp() external {
        DeploySCT deployer = new DeploySCT();
        (stableCoinToken, engine, config) = deployer.run();
        (, , weth, wbtc, ) = config.activeNetworkConfig();
        handler = new Handler(engine, stableCoinToken);
        targetContract(address(handler));
    }`
    
   I want the tests to run the handler contract, but im facing this:
   `[FAIL. Reason: invariant_protocolMustHaveMoreCollateralThanTokensAvailable persisted failure revert]
	[Sequence]
		sender=0x00000000000000000000000000000000000002d0 addr=[script/DeploySCT.s.sol:DeploySCT]0x5615dEB798BB3E4dFa0139dFa1b3D433Cc23b72f calldata=run() args=[]
		sender=0x00000000000000000000000000000000000001f9 addr=[src/StableCoinToken.sol:StableCoinToken]0x5FbDB2315678afecb367f032d93F642f64180aa3 calldata=mint(address,uint256) args=[0x0000000000000000000000000000000000000000, 2779]`
		
It calls "mint" a function from StableCoinToken that is deployed in "deployer.run()"
