### ISSUE TITLE
Feature: maintain a CHANGELOG based from GitHub Issues labels

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#5630]
### Component

Other (please describe)

### Describe the feature you would like

# Useful CHANGELOG 

Maintain a CHANGELOG based from GitHub Issues labels

Additionally, do something like a `forge completions bash > forge_bash_$COMMIT` && `diff forge_bash_$COMMIT forge_bash_$COMMIT` showing changes to the CLI's easily. 

### Additional context

The nightly summaries are not sufficient. Labels bypass the contents of parsing the git commit because those commit messages may not be very helpful.

**Comment by Evalir** [comment]
Closing as stale for now, we'll have a more stable changelog with versioned releases
