### ISSUE TITLE
Fork Testing – EVM Compatibility

### ISSUE THREAD

**Issue by pcaversaccio** [foundry-rs/foundry#5632]
### Component

Forge

### Describe the feature you would like

Fork tests are local simulations with accounts, states, and storage slot information fetched from the RPC, but the EVM behaviour of the forked chain might not identically be replicated locally. I created a [repository](https://github.com/pcaversaccio/fork-testing-evm-compatibility) that implements a [simple fork test](https://github.com/pcaversaccio/fork-testing-evm-compatibility/blob/main/test/Store.t.sol) on Optimism that proves that the EVM behaviour of the forked chain is _not_ identically replicated locally. This can lead to problems due to new opcodes such as [`PUSH0`](https://www.evm.codes/#5f?fork=shanghai) which would lead to untested behaviour as the EVM behaviour is not correctly replicated as part of the test suite.

Foundry should implement a way to ensure the EVM behaviour of the selected fork is followed correctly. One way is to reconfigure the opcodes for these different networks. But this is a maintenance-heavy approach. I would love to see a solution where the RPCs should provide the used EVM and Foundry consumes this information accordingly.

**Comment by Evalir** [comment]
So, closing this to consolidate on the issue tracker, but this is definitely something that is on our minds every day. We need a better way to handle EVM discrepancies and we're still on the early stages of defining how this is going to look like. Ideas appreciated ^^
