### ISSUE TITLE
`forge fmt` formatting with `Modifier-style base constructor call without arguments` compiler error

### ISSUE THREAD

**Issue by vladikopl01** [foundry-rs/foundry#5633]
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (dffdfde 2023-08-14T00:22:15.788827000Z)

### What command(s) is the bug in?

forge fmt

### Operating System

macOS (Apple Silicon)

### Describe the bug

```solidity
import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";
import {ERC1155} from "solmate/tokens/ERC1155.sol";

import {IAchievements} from "./interfaces/IAchievements.sol";
import {SoulBound1155} from "./abstracts/SoulBound1155.sol";

contract Achievements is IAchievements, SoulBound1155, Ownable {
    constructor(address owner) Ownable() ERC1155() {}
}
```

While formatting this piece of code with `forge fmt`, it removes parentheses for `ERC1155` inline derived constructor call. Then, the compiler gives such an error on `forge build`:
```
vladikopl@Vladichek-Air core % forge build
[⠊] Compiling...
[⠢] Compiling 1 files with 0.8.20
[⠆] Solc 0.8.20 finished in 18.36ms
Error: 
Compiler run failed:
Error (1563): Modifier-style base constructor call without arguments.
  --> contracts/Achievements.sol:17:42:
   |
17 |     constructor(address owner) Ownable() ERC1155 {}
   |                                          ^^^^^^^
``` 

May it be caused by `SoulBound1155` contract as it is already derived from `ERC1155`? Anyways, I think formatter should recognise it, and not change `ERC1155()` to `ERC1155`

**Comment by mattsse** [comment]
likely somewhere around here @Evalir 

https://github.com/foundry-rs/foundry/blob/a0a31c393279e08548920a54c49036a11c180a62/crates/fmt/src/formatter.rs#L1433-L1449

**Comment by vladikopl01** [comment]
Are there any updates? Maybe this formatting feature could be set in the config somehow? 

Also, need to mention that there are some differences between `forge fmt` formatter and `prettier-plugin-solidity`
```solidity
for (uint256 i = 0; i < length;) { // forge
for (uint256 i = 0; i < length; ) { // prettier

// forge
function linkThirdPartyToProfile(address _profileAddress, uint256 _thirdPartyId, uint256 _thirdPartyUserID)
    external
    onlyOperator
{
// prettier
function linkThirdPartyToProfile(
    address _profileAddress,
    uint256 _thirdPartyId,
    uint256 _thirdPartyUserID
) external onlyOperator {

// forge
associatedWallets[_primaryWallet][_associatedWallet] =
    WalletAssociation(true, primaryWallets[_primaryWallet].length);
// prettier
associatedWallets[_primaryWallet][_associatedWallet] = WalletAssociation(
    true,
    primaryWallets[_primaryWallet].length
);
```

**Comment by JoscelynFarr** [comment]
Hey guys, is there any update for this issue? After I use the command `forge fmt` it also removes parentheses from the constructor

<img width="401" alt="img" src="https://github.com/foundry-rs/foundry/assets/130961775/2a41b64a-ee26-4f69-a77c-84dd05c68edf">
