### ISSUE TITLE
`vm.broadcast()` sets incorrect nonce for txs

### ISSUE THREAD

**Issue by klkvr** [foundry-rs/foundry#5635]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a0a31c3 2023-08-12T00:23:12.943797000Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

```solidity
contract NonceBug is Script {
    function run() public payable {
        vm.broadcast(1);
        IERC20(0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48).approve(
            address(1), 1000
        );

        vm.broadcast(1);
        IERC20(0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48).approve(
            address(1), 1000
        );
    }
}
```
Dry-running following script on mainnet will generate two transactions with the same nonce for the same sender:
```
{
  "transactions": [
    {
        ...
        "nonce": "0x661",
        "accessList": []
      },
      ...
    },
    {
        ...
        "nonce": "0x661",
        "accessList": []
      },
      ...
    }
  ],
...
}
```

When adding --broadcast flag, script will fail with error `EOA nonce changed unexpectedly while sending transactions`

I have tracked the issue down to this line of code: https://github.com/foundry-rs/foundry/blob/410c8173e76b9fa42864e2d63309cd7cc4b6cfd9/crates/evm/src/executor/inspector/cheatcodes/mod.rs#L727
And it seems to be actually increasing nonce to correct next value. But somehow on the next broadcast it becomes the old value again.

Another interesting thing here is that following script would generate correct nonces:
```solidity
contract NonceBug is Script {
    function run() public payable {
        vm.broadcast(1);
        address(0).call("");

        vm.broadcast(1);
        address(0).call("");
    }
}

```
```
{
  "transactions": [
    {
        ...
        "nonce": "0x661",
        "accessList": []
      },
      ...
    },
    {
        ...
        "nonce": "0x662",
        "accessList": []
      },
      ...
    }
  ],
...
}
```

Also, using `vm.startBroadcast()/vm.stopBroadcast()` instead of `vm.broadcast()` solves the issue too.

**Comment by nhtyy** [comment]
Ah so I have actually run into this in another form i think, and I couldnt tell you at the moment exactly whats going on will try to repro soon but

https://github.com/foundry-rs/foundry/blob/95a93cd397f25f3f8d49d2851eb52bc2d52dd983/crates/evm/src/executor/inspector/cheatcodes/mod.rs#L768-L776

this block would have been executed at the end of your first call.

It sets the broadcast field to None on the Cheatcodes Inspector, so your code block would never be hit after the first broadcast (?)

(This does not happen when you use `vm.startBroadcast` / `vm.stopBroadcast`)

Im guessing this is related. Although prank (single call) has the same logic here so not 100%

**Comment by klkvr** [comment]
I think that the reason for this is here:

https://github.com/foundry-rs/foundry/blob/95a93cd397f25f3f8d49d2851eb52bc2d52dd983/crates/evm/src/executor/inspector/cheatcodes/env.rs#L695-L705

It is the only place in the whole codebase which is actually decreases nonce, and somehow it is being called for the first scenario (with ERC20), and not being called for other scenario.

I will try to dive deeper into this logic

**Comment by klkvr** [comment]
This is due to delegatecall which happens when calling USDC. Replacing USDC address with DAI solves the issue

**Comment by klkvr** [comment]
So, the exact flow is as following:

1. `broadcast` call is getting processed, and tx.origin is set to the user address
2. User calls some contract after broadcast
3. Contract makes delegatecall
4. call_end function gets entered and due to depth mismatch caller stays the same, but the broadcast is getting removed:
https://github.com/foundry-rs/foundry/blob/95a93cd397f25f3f8d49d2851eb52bc2d52dd983/crates/evm/src/executor/inspector/cheatcodes/mod.rs#L768-L776
5. The caller is never updated until the next call/prank/whatever
6. On the next `.broadcast`, we still have the caller set to the user address, and correct_caller_nonce function decreases it's nonce
https://github.com/foundry-rs/foundry/blob/95a93cd397f25f3f8d49d2851eb52bc2d52dd983/crates/evm/src/executor/inspector/cheatcodes/env.rs#L695-L705
