### ISSUE TITLE
Newer foundry version takes more time in fuzz testing

### ISSUE THREAD

**Issue by Ahmed-Aghadi** [foundry-rs/foundry#5636]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (91f69dd 2023-05-01T19:02:48.262468700Z)

### Operating System

Windows

### Describe the bug

I'm using WSL1.

So when I use foundry latest version that is `forge 0.2.0 (91f69dd 2023-05-01T19:02:48.262468700Z)` then my tests takes a lot of time and if I use older version like `forge 0.2.0 (e15e33a 2023-08-15T15:28:37.376537200Z)` then it takes less time.

For later version `forge 0.2.0 (91f69dd 2023-05-01T19:02:48.262468700Z)`, it takes 101.72s:
```
Running 5 tests for solidity/test/e2e/CryptoAnts.t.sol:E2ECryptoAnts
[PASS] testBeAbleToCreate100AntsWithOnlyOneInitialEgg() (gas: 144)
[PASS] testBurnTheAntAfterTheUserSellsIt(uint256) (runs: 1000, μ: 2432930, ~: 2375428)
[PASS] testBuyAnEggAndCreateNewAnt() (gas: 134403)
[PASS] testOnlyAllowCryptoAntsToMintEggs(address,uint256) (runs: 1000, μ: 86772, ~: 86569)
[PASS] testSendFundsToTheUserWhoSellsAnts(uint256) (runs: 1000, μ: 1917240, ~: 2005421)
Test result: ok. 5 passed; 0 failed; 0 skipped; finished in 4.46s
Ran 1 test suites: 5 tests passed, 0 failed, 0 skipped (5 total tests)
Done in 101.72s.
```
 For older version `forge 0.2.0 (e15e33a 2023-08-15T15:28:37.376537200Z)`, it takes 11.24s:
```
Running 5 tests for solidity/test/e2e/CryptoAnts.t.sol:E2ECryptoAnts
[PASS] testBeAbleToCreate100AntsWithOnlyOneInitialEgg() (gas: 144)
[PASS] testBurnTheAntAfterTheUserSellsIt(uint256) (runs: 1000, μ: 1874984, ~: 1776765)
[PASS] testBuyAnEggAndCreateNewAnt() (gas: 134403)
[PASS] testOnlyAllowCryptoAntsToMintEggs(address,uint256) (runs: 1000, μ: 86800, ~: 86569)
[PASS] testSendFundsToTheUserWhoSellsAnts(uint256) (runs: 1000, μ: 1907862, ~: 1897328)
Test result: ok. 5 passed; 0 failed; finished in 4.45s
Done in 11.24s.
```

It looks like older version executes asynchronously all of the tests whereas newer version executes synchronously.

**Comment by mattsse** [comment]
without any repro this is impossible to triage this your referenced version is 3 months old

**Comment by Ahmed-Aghadi** [comment]
> without any repro this is impossible to triage this your referenced version is 3 months old

Understandable, will share repo. Please give me some time.

**Comment by mds1** [comment]
@mattsse guess this is a good time to resurface the idea of adding [benchmarks](https://github.com/foundry-rs/foundry/issues/3411#issuecomment-1656155235) somewhere in the CI flow (or at least on-demand when fuzz related stuff changes) so we can better diagnose these

I don't think there have been many fuzz related changes recently so this is probably due to https://github.com/foundry-rs/foundry/issues/5262

**Comment by Evalir** [comment]
Heavily improved with multiple optimization PRs over the past few days—we still need to introduce benchmarks, but will close.
