### ISSUE TITLE
Ledger --froms "Ledger device not available" #4692

### ISSUE THREAD

**Issue by EricForgy** [foundry-rs/foundry#5638]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (93ebcdd 2023-08-15T00:27:50.951269000Z)

### What command(s) is the bug in?

forge script --froms

### Operating System

macOS (Apple Silicon)

### Describe the bug

Probably related to https://github.com/foundry-rs/foundry/issues/4692

```
> forge script <MyScript> --ledger --froms <MyAddress> --via-ir --rpc-url <MyRPC> --slow --broadcast

Finding wallets for all the necessary addresses...

Transactions saved to: /Users/eric/Development/CavalRe/solidity/amm/broadcast/DeployEmptyPool.s.sol/43114/run-latest.json

Sensitive values saved to: /Users/eric/Development/CavalRe/solidity/amm/cache/DeployEmptyPool.s.sol/43114/run-latest.json

Error:
Ledger device not available.

Context:
- Received unexpected response from device. Expected data in response, found none.
```

**Comment by Evalir** [comment]
The flag is `--from`, not `--froms` 😅 

if it's still persisting, could we comment on #4692 and track there? Ideally to avoid duplicates.
