### ISSUE TITLE
Add ability to return calldata for a Gnosis Safe bundle from a script

### ISSUE THREAD

**Issue by nhtyy** [foundry-rs/foundry#5639]
### Component

Forge

### Describe the feature you would like

You can create a Gnosis Safe [bundle](https://github.com/safe-global/safe-contracts/blob/main/contracts/libraries/MultiSend.sol) from a script, there is also potential for api integrations with their front end 

### Additional context

Conveniently lol, Im willing to work on this issue if we want soon, and i wrote a crate already that encodes bundles using ethers rs and submits to thier api

Edit: 

### Example Use Cases
Multisig controls a proxy that has to a  multi stage migration.

### Edge Cases

Things may not be deterministic if subsequent calls depend on the output of previous ones, there is probably some hacks you can do at runtime to check the outputs, still an open thought. Not sure if worth the trouble or even viable

**Comment by nhtyy** [comment]
errr actually i think there could be issues if subsequent calls depends on previous in some cases?

**Comment by zerosnacks** [comment]
Hi @nhtyy, thanks for your suggestion!

For now marking this as `not planned` but would love have a `Safe` extension for Foundry once we've figured out how to approach extensions / plugins, see: https://github.com/foundry-rs/foundry/issues/8266

Related: https://github.com/ind-igo/forge-safe
