### ISSUE TITLE
"forge install foundry-rs/forge-std" error

### ISSUE THREAD

**Issue by armada2013** [foundry-rs/foundry#5641]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0

### Operating System

macOS (Intel)

### Describe the bug

When  I type the "forge install foundry-rs/forge-std" to install forge standard lib, it reports the following errors. How can I deal with this problem?
Error: The target directory is a part of or on its own an already initialized git repository, and it requires clean working and staging areas, including no untracked files.  Check the current git repository's status with `git status`. Then, you can track files with `git add ...` and then commit them with `git commit`, ignore them in the `.gitignore` file, or run this command again with the `--no-commit` flag.

**Comment by mattsse** [comment]
what is unclear about this message?
maybe we can make it concise

**Comment by Evalir** [comment]
Closing as stale, and this is better suited for the foundry telegram support chat.
