### ISSUE TITLE
Support for Library Linking in Solidity

### ISSUE THREAD

**Issue by mshakeg** [foundry-rs/foundry#5642]
### Component

Forge

### Describe the feature you would like

Allow for dynamic library linking within Solidity by adding a `libraries` field to the contract creation syntax. This would enable linking libraries to contracts during deployment, akin to how it's done in Hardhat. The proposed syntax would be:

```solidity
string[] memory myContractLibraries = ['src/libraries/MyLibrary.sol:MyLibrary: 0x1230000000000000000000000000000000000abc'];
MyContract myContract = new MyContract{libraries: myContractLibraries}();
```

### Additional context

I initially asked [a question on the ethereum stackexchange](https://ethereum.stackexchange.com/q/153411/86303)

The proposed syntax adheres to existing practices within Foundry, requiring a list of strings in the format `<libraryPath>:<libraryName>:<libraryAddress>`.

This solution aims to bring Foundry's capabilities in line with other popular development environments while maintaining its unique all-Solidity approach.

**Comment by mshakeg** [comment]
I initially created this issue due to experiencing a problem to similar to that described in #4049

However, I have since come up with a temporary workaround, regardless I've confirmed that the expected behaviour would be for foundry to deploy all libraries that a contract depends on and link those libraries automatically before deploying.

However, I still think the ask in this issue would be helpful in the case that the libraries have already been deployed at known addresses and so developers can avoid deploying duplicate libraries. I also like the idea of foundry using deterministic CREATE2 deploys of libraries as [explained here](https://github.com/foundry-rs/foundry/issues/4443#issuecomment-1602250083).

This issue seems related to #3664

**Comment by Evalir** [comment]
Yep ack—I think we want this on a cheatcode so we don't have to hijack solidity's syntax 😄 Will close to unify these requests on #3664
