### ISSUE TITLE
`eth_getCode` returns empty on fork when `--chain-id` is specified

### ISSUE THREAD

**Issue by penandlim** [foundry-rs/foundry#5646]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

anvil 0.2.0 (11b08e9 2023-08-16T00:24:19.012904000Z)

### What command(s) is the bug in?

anvil --fork-url $ARB_RPC_URL --port 8545 --chain-id 42161

### Operating System

macOS (Apple Silicon)

## Steps to reproduce
1. Run `anvil --fork-url $ARB_RPC_URL --port 8545 --chain-id 42161` with arbitrum RPC url that supports archive node
2. Try calling `eth_getCode` via curl
```
curl http://127.0.0.1:8545 \
  -X POST \
  -H "Content-Type: application/json" \
  -d '{"jsonrpc":"2.0","method":"eth_getCode","params": ["0x912CE59144191C1204E64559FE8253a0e49E6548", "latest"],"id":1}'
```
3. Result is `{"jsonrpc":"2.0","id":1,"result":"0x"}%  `

However simply removing `--chain-id` in CLI gets around this issue and returns the correct bytecode. Also anvil fetches correct chainID from the RPC so looks like there are no negative effects from not specifying. Not sure if this behavior is intended.

**Comment by klkvr** [comment]
hey @penandlim I can't reproduce this locally, could you check if the issue persists on your side?

**Comment by grandizzy** [comment]
I confirm this is not reproducible with latest version, @penandlim please reopen if you hit issue again. thank you!

![image](https://github.com/user-attachments/assets/66aafc00-89cf-4200-a9d4-fcf464fdadf5)
