### ISSUE TITLE
Invalid value "shanghai" for '--evm-version <VERSION>'

### ISSUE THREAD

**Issue by descartes100** [foundry-rs/foundry#5648]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

0.2.0

### What command(s) is the bug in?

forge test

### Operating System

Windows

### Describe the bug

hello, when I try to run "forge test --contracts ./test/testContract.sol --evm-version 'shanghai' ", I always get the error:
"error: Invalid value "shanghai" for '--evm-version <VERSION>': Unknown evm version: shanghai". 
I have updated my foundry to the latest version, but it does not work. 

how can I fix this problem? thanks!

**Comment by Evalir** [comment]
Hey, I can't seem to reproduce this on a windows box. `--evm-version "shanghai"` works well for me. Are you using WSL or normal?

**Comment by descartes100** [comment]
> Hey, I can't seem to reproduce this on a windows box. `--evm-version "shanghai"` works well for me. Are you using WSL or normal?

Thanks for your help! I use normal (btw all other forge commands work well ) and I am still struggling with this error

**Comment by Evalir** [comment]
what foundry version are you on? @descartes100

**Comment by descartes100** [comment]
> what foundry version are you on? @descartes100 could you double check you've updated?

Oh I just find the cause: I haven't renew the 'Path' so I am running on the old foundry version but not the latest one. And now the 'evm-version "shanghai"' works well! Thanks so much !!!

**Comment by InfectedIsm** [comment]
> what foundry version are you on? @descartes100 could you double check you've updated?

Hi, I' facing same issue, I'm strugling to find how to update foundry on normal windows.
Would be huge if someone could help on this.

**Comment by tanliwei** [comment]
I faced the same issue, with the below forge version
```
~ % forge -V  
forge 0.2.0 (edf15ab 2023-02-22T00:11:26.185311Z)
```

then, upgrade forge with below command:
```
~ % foundryup
~ % forge -V 
forge 0.2.0 (8343e7d 2024-01-07T00:19:11.564229000Z)
```
At last, forge install successfully:
```
 % forge install
...
Submodule 'lib/forge-std' (https://github.com/foundry-rs/forge-std) registered for path 'lib/forge-std’
```
