### ISSUE TITLE
forge build --deny-warnings fail when no warnings issued

### ISSUE THREAD

**Issue by hellwolf** [foundry-rs/foundry#5649]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ca67d15 2023-08-02T00:16:51.291393754Z)

### What command(s) is the bug in?

forge build --deny-warnings

### Operating System

Linux

### Describe the bug

No warnings issued from compliation, but `forge build --deny-warnings` still exit with failure.

I have tried to reproduce with a smaller example, but I could not. Here is a full reproduciable case:

```
$ forge --version
forge 0.2.0 (ca67d15 2023-08-02T00:16:51.291393754Z)
$ git clone https://github.com/superfluid-finance/protocol-monorepo.git
...
$ cd protocol-monorepo/
$ yarn install
...
$ cd packages/ethereum-contracts/
$ forge build --deny-warnings 
[⠊] Compiling...
[⠘] Compiling 167 files with 0.8.19
[⠰] Solc 0.8.19 finished in 42.73s
Error: 
Compiler run failed:
```

**Comment by ryanio** [comment]
this is happening for me with `ignored_error_codes=["same-varname"]`, the output is:

```bash
➜  forge build
[⠊] Compiling...
[⠒] Compiling 5 files with Solc 0.8.24- 
[⠑] Solc 0.8.24 finished in 1.54s
Compiler run successful with warnings:
```

```bash
➜  forge build --deny-warnings
[⠊] Compiling...
[⠒] Compiling 4 files with Solc 0.8.24
[⠢] Solc 0.8.24 finished in 1.06s
Error: 
Compiler run failed:
```

**Comment by klkvr** [comment]
I can see that clean build produces a warning
```
Compiler run successful with warnings:
Warning (5574): Contract code size is 24649 bytes and exceeds 24576 bytes (a limit introduced in Spurious Dragon). This contract may not be deployable on Mainnet. Consider enabling the optimizer (with a low "runs" value!), turning off revert strings, or using libraries.
   --> packages/ethereum-contracts/contracts/mocks/SuperfluidMock.sol:130:1:
    |
130 | contract SuperfluidMock is Superfluid {
    | ^ (Relevant source part starts here and spans across multiple lines).
```

Could you try updating foundry to latest nightly and see if something changes for you?

**Comment by klkvr** [comment]
ah sorry, I've tried it on repo from the initial issue description

could you try doing `forge clean` and then running `forge build` to see if there are any warning printed?

**Comment by hellwolf** [comment]
Found a easier to reproduce case, perhaps related, https://github.com/foundry-rs/foundry/issues/8342

**Comment by grandizzy** [comment]
@hellwolf is this still an issue? I tried to reproduce but wasn't able, though noticed the solc version was changed since issue reported
```bash
[⠢] Compiling...
[⠆] Compiling 209 files with Solc 0.8.26
[⠃] Solc 0.8.26 finished in 29.01s
Compiler run successful!
```

thank you!
