### ISSUE TITLE
open zeppelin aave v3 core contracts

### ISSUE THREAD

**Issue by shreya179-disk** [foundry-rs/foundry#5650]
### Component

Forge

### Describe the feature you would like

forge install @openzeppelin/contracts @aave/core-v3
Installing contracts in /Users/shreya/Flash_Loans/lib/contracts (url: Some("https://github.com/openzeppelin/contracts"), tag: None)
Error: 
The target directory is a part of or on its own an already initialized git repository,
and it requires clean working and staging areas, including no untracked files.

Check the current git repository's status with `git status`.
Then, you can track files with `git add ...` and then commit them with `git commit`,
ignore them in the `.gitignore` file, or run this command again with the `--no-commit` flag.

I tried all the steps but didn't work

**Comment by Evalir** [comment]
hi! this is more of a git issue—it seems like you're installing in the incorrect directory for some reason. Can you head to [the Foundry tg support channel](https://t.me/foundry_support) for help with this issue?
