### ISSUE TITLE
Failed to verify contract on gnosisscan with `forge script --verify` and `forge verify-contract`

### ISSUE THREAD

**Issue by QYuQianchen** [foundry-rs/foundry#5656]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (f64fe13 2023-08-18T00:25:19.524820000Z)

### What command(s) is the bug in?

forge verify-contract; forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

A set of contracts were deployed to Gnosis chain with forge script with option `--verify`. However, the contract verification failed.

Command used:
```
FOUNDRY_PROFILE=staging forge script --broadcast \
   --verify --verifier etherscan --verifier-url "https://api.gnosisscan.io/api" \
   --delay 30 --chain 100 --etherscan-api-key "${ETHERSCAN_API_KEY}" \
   --use 0.8.19 --watch \
   script/DeployAll.s.sol:DeployAllContractsScript
```

Then a subsequent attempt to verify deployed contract with `forge verify-contract` also failed.

Command used
```
forge verify-contract 0x6E078019EEE40B249fa3A876E7a6b089B77cFf9b \
   --verifier etherscan --verifier-url "https://api.gnosisscan.io/api" \
   --delay 30 --chain 100 --etherscan-api-key "${ETHERSCAN_API_KEY}" \
   --compiler-version 0.8.19 --watch \
   --optimizer-runs 200 \
   src/node-stake/NodeStakeFactory.sol:HoprNodeStakeFactory
   --constructor-args 
```

In both commands, the `ETHERSCAN_API_KEY` is the API key [obtained from gnosisscan](https://docs.gnosisscan.io/getting-started/viewing-api-usage-statistics#creating-an-api-key)

**Comment by Evalir** [comment]
Hey! we'll look into this and see if there's anything we can do to improve. Can you try putting a `?` in your url? like `https://api.gnosisscan.io/api\?`

Will close—there are several duplicates of these and we're consolidating verification failures to a few issues.
