### ISSUE TITLE
foundryup fails when building from specific commit or branch

### ISSUE THREAD

**Issue by geoff-vball** [foundry-rs/foundry#5658]
### Component

Foundryup

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (f64fe13 2023-08-18T00:16:15.507396567Z)

### What command(s) is the bug in?

foundryup -b and foundryup -C

### Operating System

Linux

### Describe the bug

Input: `foundryup -b master`

```
...
Compiling anvil v0.2.0 (/home/geoff/.foundry/foundry-rs/foundry/crates/anvil)
Compiling cast v0.2.0 (/home/geoff/.foundry/foundry-rs/foundry/crates/cast)
Finished release [optimized] target(s) in 9m 33s
mv: cannot stat 'target/release/forge.exe': No such file or directory
mv: cannot stat 'target/release/cast.exe': No such file or directory
mv: cannot stat 'target/release/anvil.exe': No such file or directory
mv: cannot stat 'target/release/chisel.exe': No such file or directory
foundryup: done
```

Through tests, this has the same issue on Apple Silicon Mac

**Comment by mattsse** [comment]
@DaniPopes we replaced cargo install with cargo build and move https://github.com/foundry-rs/foundry/pull/5653

which is incorrect for non windows:

https://github.com/foundry-rs/foundry/blob/1e6f441a0daeac0f0cfc06344491477e0aceab46/foundryup#L209-L209

**Comment by DaniPopes** [comment]
Ugh
