### ISSUE TITLE
can not install foundry-rs cli

### ISSUE THREAD

**Issue by conlotor** [foundry-rs/foundry#5659]
I'm going to install foundry-cli using below command.
```
cargo install --git https://github.com/foundry-rs/foundry --profile local --force foundry-cli
```

This command was working a few days ago.
But now, I'm getting below error.

![image](https://github.com/foundry-rs/foundry/assets/51798556/e527c5be-b9d9-4fd2-8db6-2d808383ddc9)

**Comment by mattsse** [comment]
fyi @DaniPopes 

the instructions are outdated now

https://book.getfoundry.sh/getting-started/installation

can we make this work with cargo install again?

**Comment by DaniPopes** [comment]
No

**Comment by mattsse** [comment]
thanks will update

**Comment by Evalir** [comment]
@mattsse https://github.com/foundry-rs/book/pull/987

**Comment by Evalir** [comment]
Closed with https://github.com/foundry-rs/book/pull/987 — you can use the new instructions to install! sorry about the outdated instructions 🙏

**Comment by Ata786** [comment]
> I'm going to install foundry-cli using below command.
> 
> ```
> cargo install --git https://github.com/foundry-rs/foundry --profile local --force foundry-cli
> ```
> 
> This command was working a few days ago. But now, I'm getting below error.
> 
> ![image](https://private-user-images.githubusercontent.com/51798556/261658590-e527c5be-b9d9-4fd2-8db6-2d808383ddc9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0ODk5MzMsIm5iZiI6MTcwMzQ4OTYzMywicGF0aCI6Ii81MTc5ODU1Ni8yNjE2NTg1OTAtZTUyN2M1YmUtYjlkOS00ZmQyLThkYjYtMmQ4MDgzODNkZGM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDA3MzM1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxZmMxZTE1M2Q3YjM2NWU5YzIxMGQwZWY3NjIwMmFhNzU3ZmRjODM5ZTNlMjJkOGE4YjRlZDI1ZWE3MTNlMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YgfgxDbCGOllnPxYWRP8Zy2cwfQiRsEp7NREZJmO42k)

bro i have save issue please tell me solution if you find

**Comment by Ata786** [comment]
> I'm going to install foundry-cli using below command.
> 
> ```
> cargo install --git https://github.com/foundry-rs/foundry --profile local --force foundry-cli
> ```
> 
> This command was working a few days ago. But now, I'm getting below error.
> 
> ![image](https://private-user-images.githubusercontent.com/51798556/261658590-e527c5be-b9d9-4fd2-8db6-2d808383ddc9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0OTAzMTksIm5iZiI6MTcwMzQ5MDAxOSwicGF0aCI6Ii81MTc5ODU1Ni8yNjE2NTg1OTAtZTUyN2M1YmUtYjlkOS00ZmQyLThkYjYtMmQ4MDgzODNkZGM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDA3NDAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxZDMxZjRiMDcxZjhlMjYzM2YzNjk5NmM3NDU1MTczZjJjYjA2OTM2ZDBiMWYxMTZkZmU2NjhjOGNiZTQzNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JfxGIyN3x7KKVWWqQ23OvsrHDrJJhdfGxlbtYDLk5cc)

i have same issue at the end it gives error that 
This may also occur with an optional dependency that is not enabled.
  Installed package `chisel v0.2.0 (https://github.com/foundry-rs/foundry#ba0cc1d4)` (executable `chisel.exe`)
   Summary Successfully installed anvil, chisel! Failed to install foundry-cli (see error(s) above).
error: some crates failed to install
