### ISSUE TITLE
`forge test -vw` starts an infinite loop of processes

### ISSUE THREAD

**Issue by mrchonky** [foundry-rs/foundry#5684]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (b536f51 2023-08-21T00:16:24.090951402Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

Running the command
`forge test -vw`
creates an infinite loop.

Expected result is either:
A) an error stating that the flag -vw does not exist
B) run tests with 1 V of verbosity & enter watch-mode

Here's a screenshot of infinite processes spawning after running `forge test -vw`
![image](https://github.com/foundry-rs/foundry/assets/104332780/a16c77e2-9915-4f6c-be18-bb34b981b8ec)

**Comment by wbelhomsi** [comment]
Were you able to resolve this in any way?
In my case, I'm running a simple test but noticed the spawning of processes and that most of them are 0:00.00 but only 1 or 2 are actually doing the work
![Screenshot 2023-09-21 at 1 54 26 PM](https://github.com/foundry-rs/foundry/assets/40052755/0b8240e7-9509-4ce0-9dad-b36f429664ac)

**Comment by mattsse** [comment]
this is a bug with the watch command, I think I found the issue

fixing
