### ISSUE TITLE
Impossible to "cast interface" of Vyper contract

### ISSUE THREAD

**Issue by L0GYKAL** [foundry-rs/foundry#5688]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (dea5405 2023-08-17T00:25:19.368594453Z)

### What command(s) is the bug in?

cast interface 0x5f3b5DfEb7B28CDbD7FAba78963EE202a494e2A2

### Operating System

Linux

### Describe the bug

I'm trying to cast the interface of the veCRV vyper contract and it gives me an error
([0x5f3b5DfEb7B28CDbD7FAba78963EE202a494e2A2](https://etherscan.io/token/0x5f3b5DfEb7B28CDbD7FAba78963EE202a494e2A2))
![image](https://github.com/foundry-rs/foundry/assets/32228897/a9ca4b91-8a6d-4e84-b197-e9e3e7199e85)

**Comment by Evalir** [comment]
Right, this is because we currently do not have vyper support for `cast interface`—sorry!

**Comment by mds1** [comment]
@Evalir how does cast interface work under the hood? I'd have thought cast could grab the API via etherscan and generate a solidity interface for it, without vyper support

**Comment by L0GYKAL** [comment]
That would have been my thought as well
ABI should be the same format from Vyper and from Solidity
