### ISSUE TITLE
Forge coverage never completes

### ISSUE THREAD

**Issue by 0xAlcibiades** [foundry-rs/foundry#5697]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6676e81 2023-08-22T00:28:15.086036000Z)

### What command(s) is the bug in?

forge coverage --report summary --report lcov

### Operating System

Linux

### Describe the bug

https://github.com/valorem-labs-inc/clear/pull/215

**Comment by 0xAlcibiades** [comment]
> ref [bluealloy/revm#628](https://github.com/bluealloy/revm/pull/628)
> 
> working on the fix! should be out soon

So fast

**Comment by 0xAlcibiades** [comment]
Seems like it relates to https://github.com/foundry-rs/foundry/pull/5695 possibly as well @Evalir

**Comment by 0xAlcibiades** [comment]
Relates to #5609

**Comment by samtvlabs** [comment]
We are experiencing this too : https://github.com/tvl-labs/khalani-core/actions/runs/5943318500/job/16118176128?pr=207

**Comment by Evalir** [comment]
Fix is being tracked on https://github.com/foundry-rs/foundry/pull/5698 , patience is appreciated 🙏

**Comment by Evalir** [comment]
We've put out an interim fix with #5695 — feel free to try!

**Comment by varunsrin** [comment]
thanks for the fast fix @Evalir
