### ISSUE TITLE
run "foundryup" in bash happen a about libsub-1.0.0.dylib error

### ISSUE THREAD

**Issue by gitStevenChen** [foundry-rs/foundry#5704]
### Component

Foundryup

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What command(s) is the bug in?

foundryup

### Operating System

macOS (Intel)

### Describe the bug

I install Foundry.

curl -L https://foundry.paradigm.xyz | bash

foundryup

happen error:
foundryup: installing foundry (version nightly, tag nightly-f95fb9b543cab101e89b9d29f9b330c1203d4e33)
foundryup: downloading latest forge, cast, anvil, and chisel

curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 
foundryup: command failed: download https://github.com/foundry-rs/foundry/releases/download/nightly-f95fb9b543cab101e89b9d29f9b330c1203d4e33/foundry_nightly_darwin_amd64.tar.gz
foundryup: downloading manpages

curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 
dyld: Library not loaded: /usr/local/opt/libusb/lib/libusb-1.0.0.dylib
  Referenced from: /Users/chenqiping/.foundry/bin/forge
  Reason: Incompatible library version: forge requires version 4.0.0 or later, but libusb-1.0.0.dylib provides version 3.0.0
foundryup: command failed: /Users/chenqiping/.foundry/bin/forge --version
foundryup: installed - 
dyld: Library not loaded: /usr/local/opt/libusb/lib/libusb-1.0.0.dylib
  Referenced from: /Users/chenqiping/.foundry/bin/cast
  Reason: Incompatible library version: cast requires version 4.0.0 or later, but libusb-1.0.0.dylib provides version 3.0.0
foundryup: command failed: /Users/chenqiping/.foundry/bin/cast --version
foundryup: installed - 
dyld: Library not loaded: /usr/local/opt/libusb/lib/libusb-1.0.0.dylib
  Referenced from: /Users/chenqiping/.foundry/bin/anvil
  Reason: Incompatible library version: anvil requires version 4.0.0 or later, but libusb-1.0.0.dylib provides version 3.0.0
foundryup: command failed: /Users/chenqiping/.foundry/bin/anvil --version
foundryup: installed - 
dyld: Library not loaded: /usr/local/opt/libusb/lib/libusb-1.0.0.dylib
  Referenced from: /Users/chenqiping/.foundry/bin/chisel
  Reason: Incompatible library version: chisel requires version 4.0.0 or later, but libusb-1.0.0.dylib provides version 3.0.0
foundryup: command failed: /Users/chenqiping/.foundry/bin/chisel --version
foundryup: installed - 
foundryup: done!

ps: i also installed libsub(1.0.23)
os version:  macos 10.13.6

**Comment by Evalir** [comment]
This looks more like an SSL issue here, but to fix this you can also manually update libusb.
