### ISSUE TITLE
In Chisel, return the specific type of the integer instead of `Type: uint`

### ISSUE THREAD

**Issue by DJViau** [foundry-rs/foundry#5705]
### Component

Chisel

### Describe the feature you would like

Please return the specific type of an integer in Chisel instead of defaulting to `Type: uint`.

For example, when you enter `type(uint8).max`, Chisel returns:

```
Type: uint
├ Hex: 0xff
└ Decimal: 255
```

But `type(uint8).max` has `Type: uint8`.

See the thread ending with https://warpcast.com/gakonst/0x45eb2f for more detail and some example confusion.

### Additional context

<img width="557" alt="Screenshot of confusing chisel behavior" src="https://github.com/foundry-rs/foundry/assets/14304708/67b1343e-d5f6-4f1d-aab8-058927f5fa5d">

**Comment by Evalir** [comment]
cc @clabby / @refcell chisel is fully alloy, should be fixable
