### ISSUE TITLE
Invariant Testing: failing assert in a handler function does not print execution traces (when using forge test -vvv)

### ISSUE THREAD

**Issue by omnifient** [foundry-rs/foundry#5712]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (1143e57 2023-08-24T00:20:21.116511461Z)

### What command(s) is the bug in?

forge test -vvv

### Operating System

Linux

### Describe the bug

**Context**:
- doing invariant tests
- test contract with invariant checks
- handler contract with multiple functions that do assertions
- explicitly force one of the handler functions to fail an assert
- `fail_on_revert` = true

**Action**: run `forge test -vvv`
**Expected**: execution breaking, but to see the execution trace for the failing assertion printed
**Observed**: execution breaks, but no execution trace printed

I know that the docs say `- 3: Print execution traces for failing tests` and technically this is a handler failing and not the test contract, but this does count as a revert by forge

Note: `assert(false)` in the test function works as expected, printing the execution trace

**Resources**: created a repo with the tests
https://github.com/omnifient/fuzzing-around/blob/main/test/invariant/TestHandlerWithFailingFunction.invariants.t.sol
https://github.com/omnifient/fuzzing-around/blob/main/test/invariant/HandlerWithFailingFunction.sol

**Comment by Evalir** [comment]
Right, this is because it's a handler failing. could you try `-vvvv` or `-vvvvv` for more verbose traces so it prints? We limit the amount of traces we print for performance.

**Comment by omnifient** [comment]
yeah, with -vvvv I'm able to see the traces, but it's going to print for all executions (successful and failing)

@Evalir on another note, what's the expectation for the number of times handler functions run vs the test functions?

in a previous forge version, execution was 1 handler function : 1 test function

but in the latest version, it's not
here's a print from that repo (`t1` and `t2` are test functions)

```
Logs:
  +++ t1
  +++ t1
  +++ t1
  +++ t1
  +++ t1
  +++ t1
  +++ t1
  +++ t1
  +++ t1
  --- handlerC 115792089237316195423570985008687907853269984665640564039457584007913129639932
  +++ t1
  +++ t1
  --- handlerA (fails) 115792089237316195423570985008687907853269984665640564039457584007913129639935
  +++ t1

[PASS] invariantTestHandlerWithFailingFunction2() (runs: 2, calls: 27, reverts: 1)
Logs:
  +++ t2
  --- handlerA (fails) 992
  +++ t2
```

according to the prints, 
1. the test function is being called multiple times without any handler function called before
2. then it calls a handler function
3. then it calls a test function two times in a row

is there no guarantee of execution between handler/test?

**Comment by 0xTimepunk** [comment]
@Evalir I think this issue should be re-opened
we have a very complex invariant test and the log traces with vvvvv do not show any errors, so now I am suspecting something is wrong in the handler itself but it doesn't show in the logs.

Having these traces present would help a lot in debugging
