### ISSUE TITLE
`forge coverage` does not recognise 2 contracts that have the same source file layout

### ISSUE THREAD

**Issue by Pradeep-selva** [foundry-rs/foundry#5729]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

0.2.0

### What command(s) is the bug in?

forge coverage

### Operating System

macOS (Apple Silicon)

### Describe the bug

In a setup similar to this-
<img width="409" alt="image" src="https://github.com/foundry-rs/foundry/assets/56924144/68923c6f-cbf5-4c03-b4c3-df61eff5669b">
where 2 contracts inherit the same interface and implement the same functions and have the same source layout, although they are both tested fully, `forge coverage` fails to recognise hits on one of the contracts. 
In this case it would fail to recognise hits on `SecondContract` as `FirstContract` comes first alphabetically.

I confirmed this by changing their names to ensure it picked up the alphabetically first contract and also confirmed that when the source layout of either contracts is changed, `forge coverage` manages to recognise all hits on both of them.

**Comment by 0xad1onchain** [comment]
Can confirm this behavior

**Comment by Neftyr** [comment]
Same here, It even buggs with mock's from other folder and with silghtly different code.

**Comment by rootminus0x1** [comment]
I'm seeing this too. The similar contracts can be in different files, can have different names but as long as the functions are similar one will mask the other.
Easy to replicate:
1) create the base foundry setup
2) copy the src/Counter.sol to src/Counter2.sol, renaming the contract in Counter2.sol to Counter2
3) likewise for test/Counter.t.sol, so you now have two unrelated contracts with independent test contracts.
4) forge coverage
5) note that there is zero coverage reported for Counter2.sol
6) now add a function, e.g. decrement(), to Counter (in Counter.sol)
7) forge coverage
8) note that a) Counter2.sol has 100% coverage and b) Counter.sol has 66% coverage. Both as expected.

**Comment by grandizzy** [comment]
confirmed fixed with https://github.com/foundry-rs/foundry/pull/8214

![image](https://github.com/foundry-rs/foundry/assets/38490174/5fea40ba-fdc3-4377-be22-da7c67678f94)
