### ISSUE TITLE
Forge test time increased by ~20mins over the last week

### ISSUE THREAD

**Issue by pcaversaccio** [foundry-rs/foundry#5730]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

`forge 0.2.0 (ae3ec74 2023-08-26T00:16:39.244732249Z)`

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

My `forge` test time increased over the last week almost by 20mins _without_ making changes in the contract or test code: 
![image](https://github.com/foundry-rs/foundry/assets/25297591/a3c70aaa-8117-42d7-bf4b-93edee38f3d7)

You can replicate the behaviour [here](https://github.com/pcaversaccio/snekmate/actions/workflows/test-contracts.yml).

**Comment by pcaversaccio** [comment]
@Evalir @DaniPopes any idea what could lead to this behaviour?

**Comment by DaniPopes** [comment]
Some probable causes:
- revm removing hash from the bytecode struct and is calculated on each call to `hash_slow`. It's called a lot by fuzz and invariant tests (`foundry_evm::executor::Executor::ensure_success` -> `revm::db::in_memory_db::CacheDB::insert_contract`). CC @Evalir @rakita
- Rust bump from 1.71 to 1.72, as I've seen some regressions on the Rust issue tracker

I've tested locally and overall performance is better for normal tests but ~30% slower for running with the `ci` profile like in your example.

**Comment by 0xTimepunk** [comment]
Our CI stopped running coverage at all and locally coverage takes a long time to complete

**Comment by kayabaNerve** [comment]
My tests failed after having 6h to execute.

https://github.com/serai-dex/serai/blob/develop/coins/ethereum/tests/contract.rs

**Comment by rakita** [comment]
@Evalir we can make modification here to use `account.code_hash` and not calculate it again: https://github.com/bluealloy/revm/blob/42725351f4691c99addb1658e5deef7fb66335d0/crates/revm/src/db/in_memory_db.rs#L66-L70

Or we can have a check that would see if `account.code_hash == KECCAK_EMPTY` (is the default) and only then calculate hash again.

**Comment by pcaversaccio** [comment]
@DaniPopes @Evalir @mattsse any update on this. It becomes a little bit painful for me to always wait ~50mins until a PR is ran successfully...

**Comment by lucadonnoh** [comment]
i can also attest that tests are now significantly slower

**Comment by malonehedges** [comment]
tests are hanging for me now

**Comment by malonehedges** [comment]
is there no way to downgrade or pin a version for github actions / local dev? certain functions are broken for me right now

**Comment by Evalir** [comment]
@malonehedges currently a new foundry version with a performance improvement is being released—could you test in ~30 mins?

**Comment by Evalir** [comment]
how's your ci @pcaversaccio ? took a look and it seems like it's somewhat back to normal—foundry's due to get a tad faster due to migrating to alloy as we speak, so we'll probably keep having perf improvements from here on!

**Comment by pcaversaccio** [comment]
Yeah it's back to normal or even slightly faster 🖖 - I will close this issue and would re-open if I face the same issue again. Thx guys, you rock!
