### ISSUE TITLE
Capture chain specific nuances for Solidity Tests

### ISSUE THREAD

**Issue by ankurdubey521** [foundry-rs/foundry#5733]
### Component

Forge

### Describe the feature you would like

Tests in Foundry are run against a standard EVM implementation which works well for most cases. However, some chains (notably rollups) modify the behaviour of the EVM in different ways.
For example, Optimism charges a separate L1 Fee once the transaction has been submitted as a batch to L1, outside of the standard execution fee charged by all chains. 

It would be great to capture chain-specific details while running tests. One way for this could be to run foundry tests on an external node (like op-geth), where the functionality for running foundry tests (support for cheats etc) is implemented by a middleware between foundry and the node.

### Additional context

https://community.optimism.io/docs/developers/build/transaction-fees/#the-l1-data-fee

**Comment by Evalir** [comment]
Hi! Yep understood—this is something we have in mind as it causes issues not only on tests but also deployments due to gas estimation issues. We're tracking this on several other places—so will close this as duplicate.

**Comment by ankurdubey521** [comment]
@Evalir do you mind linking to some of these issues? Thanks!
