### ISSUE TITLE
[Chisel] Incorrect return type for Fixed-size byte array

### ISSUE THREAD

**Issue by raxhvl** [foundry-rs/foundry#5737]
### Component

Chisel

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (bff4ed9 2023-08-28T00:24:09.226668296Z)

### What command(s) is the bug in?

chisel

### Operating System

Linux

### Describe the bug

Two instances where Fixed-size byte array return types in chisel are incorrect.

## 1. Fixed size byte array `.length` returns `bytesN` instead of `uint8`
**Current behavior:**
```java
➜ bytes3 a = 0xfefefe
➜ a.length
Type: bytes3
└ Data: 0x000000
```
**Expected behavior:**
```java
➜ bytes3 a = 0xfefefe
➜ a.length
Type: uint8
└ Data: 0x03
```
## 2. Index access on `bytesN` retuns `bytesN` instead of `bytes1`
**Current behavior:**
```java
➜ bytes3 a = 0xfefefe
➜ a[0]
Type: bytes3
└ Data: 0xfe0000
```
**Expected behavior:**
```java
➜ bytes3 a = 0xfefefe
➜ a[0]
Type: bytes1
└ Data: 0xfe
```

**Comment by mds1** [comment]
Possibly related to https://github.com/foundry-rs/foundry/issues/5705, cc @refcell @clabby
