### ISSUE TITLE
serializeJson cheatcode 

### ISSUE THREAD

**Issue by vdrg** [foundry-rs/foundry#5745]
### Component

Forge

### Describe the feature you would like

Add a new `serializeJson(string calldata objectKey, string calldata value)` cheatcode (naming might not be the best), which adds the provided json string to [`serialized_jsons`](https://github.com/foundry-rs/foundry/blob/master/crates/evm/src/executor/inspector/cheatcodes/mod.rs#L171) directly as a new object.

Currently it is possible to "create" a new serialized json in the state by specifying an `id` and a `key`, but it is not possible to start from an existing json string. `serializeJson` should just insert the value to the `serialized_jsons` or overwrite with value if the id already exists.

If this makes sense and there is interest I can try to implement it :)

**Comment by mds1** [comment]
Is my understanding correct that the use case is you have some JSON read in as a string and you want to add keys to it, but currently that's not possible since you can only build up a JSON object from scratch?

**Comment by vdrg** [comment]
Yes exactly

**Comment by mds1** [comment]
Makes sense, optimistically assigned you to the issue but want to confirm the feature with @Evalir or @mattsse
