### ISSUE TITLE
Rate Limit Exceeded Error Although I've switched by --rpc-url provider.

### ISSUE THREAD

**Issue by caiosabarros** [foundry-rs/foundry#5750]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (50756e5 2023-05-29T00:04:27.574210907Z)

### What command(s) is the bug in?

 cast storage MAINNET_ADDRESS  --rpc-url API_LINK

### Operating System

Linux

### Describe the bug

When I ran the command a couple times:

```cast storage MAINNET_ADDRESS --rpc-url API_LINK```

I got the expected layout for multiple different mainnet contract addresses.

The thing is that I came to a point where the following was logged on the terminal:
```
cast storage MAINNET_ADDRESS --rpc-url API_LINK
[⠆] Compiling...
No files changed, compilation skipped
No matching artifacts found, fetching source code from Etherscan...
Contract at MAINNET_ADDRESS is a proxy, trying to fetch source at IMPLEMENTATION_ADDRESS...
Error:
Rate limit exceeded
```

So I thought: Alright, I've reached the max calls for my `--rpc-url`. However, after switching the `--rpc-url` to another provider (from Alchemy to Infura), I ran the same command again and...the same errors was logged again. 

Just to clarify:

I looked at the first `--rpc-url` I'd gotten and my max API calls weren't reached. I switched to another `--rpc-url` - where I had no API calls - and the error continued. It seems like it's something related to the max API calls from an internal foundry API call that has been reached, I believe.

**Comment by caiosabarros** [comment]
I noticed the commands only gives the error when fetching proxy contracts, since it tries to fetch the implementation from the proxy requested - giving the error. However, if I fetch the implementation directly, there's no issue. Also, is there an `option` for fetching the proxy itself instead of the implementation one - or to fecth both...?

**Comment by bdmcbri** [comment]
```
cast storage --rpc-url https://ethereum.publicnode.com 0x4Dbd4fc535Ac27206064B68FfCf827b0A60BAB3f
No matching artifacts found, fetching source code from Etherscan...
Contract at 0x4dbd…ab3f is a proxy, trying to fetch source at 0x5aed5f8a1e3607476f1f81c3d8fe126deb0afe94...
Error:
Rate limit exceeded
```

**Comment by bdmcbri** [comment]
> ```
> cast storage --rpc-url https://ethereum.publicnode.com 0x4Dbd4fc535Ac27206064B68FfCf827b0A60BAB3f
> No matching artifacts found, fetching source code from Etherscan...
> Contract at 0x4dbd…ab3f is a proxy, trying to fetch source at 0x5aed5f8a1e3607476f1f81c3d8fe126deb0afe94...
> Error:
> Rate limit exceeded
> ```

Just figured out you can use the --etherscan-api-key option with cast storage.  Problem solved.

**Comment by caiosabarros** [comment]
That's Awesome, thanks guys!

**Comment by luanxu-dev** [comment]
If forge's concurrent RPC requests are triggering 429s, one mitigation while this is being addressed upstream: use a provider with higher concurrency limits so you're less likely to hit rate limits during fork tests.

[BlockReq](https://blockreq.com) handles high-concurrency workloads well — free tier includes 80M RU/month with archive + trace/debug access. No CU multiplier on complex methods, so fork tests with heavy trace calls don't get disproportionately expensive.

*(Disclosure: I work at BlockReq.)*
