### ISSUE TITLE
SSL Connection Timeout when Running Foundryup Script

### ISSUE THREAD

**Issue by hyh88384092** [foundry-rs/foundry#5774]
### Component

Foundryup

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### Operating System

Linux

### Issue Description

I attempted to install the `foundryup` tool on my virtual machine using the following command:

sudo curl -L https://foundry.paradigm.xyz/ | bash

However, during the execution, I encountered the following error message:

curl: (28) SSL connection timeout

**Comment by hyh88384092** [comment]
Sorry, could you please provide a detailed explanation of the solution? Thank you！

**Comment by Evalir** [comment]
Hey, this is a connection issue on you're end. Make sure your VPN is not blocking access here. The install script works well on our end.

**Comment by ChintadaAbhilash** [comment]
@hyh88384092 I'm facing the same while running "curl -L https://foundry.paradigm.xyz/ | bash" on WSL Ubuntu. did you figure out any solution ? I don't use any VPN nor have any restrictions on web sites. "wget" works fine for me
