### ISSUE TITLE
`extcodesize` reports value greater than zero after `selfdestruct`

### ISSUE THREAD

**Issue by Bobface** [foundry-rs/foundry#5781]
### Component

Forge, Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (dea5405 2023-08-17T00:25:19.368594453Z)

### What command(s) is the bug in?

script

### Operating System

Linux

### Describe the bug

Calling `extcodesize` on a `selfdestruct`ed contract after the transaction is confirmed returns a value greater than zero.

Example script:
```
pragma solidity ^0.8.20;

import {Script} from "forge-std/Script.sol";
import {console} from "forge-std/console.sol";

contract Example is Script {
    function run() external {
        // Create a contract that selfdestructs
        Destruct destruct = new Destruct();

        // Call the selfdestruct function
        destruct.destruct();

        // This is only here to absolutely make sure that the line
        // below it is executed after the selfdestruct tx is confirmed
        payable(address(0)).transfer(0);

        // This does not output 0, but 107
        console.log("codesize", address(destruct).code.length);
    }
}

contract Destruct {
    function destruct() external {
        selfdestruct(payable(0));
    }
}
```

Executing it with
```
forge script \
    --broadcast \
    --slow \
    --rpc-url http://localhost:3000 \
    --with-gas-price 0 \
    -vvvv \
    Example
```

against a local `anvil` node running on `localhost:3000` results in
```
Traces:
  [86293] Example::run() 
    ├─ [21475] → new Destruct@0xC7f2Cf4845C6db0e1a1e91ED41Bcd0FcC1b0E141
    │   └─ ← 107 bytes of code
    ├─ [7704] Destruct::destruct() 
    │   └─ ← ()
    ├─ [0] 0x0000000000000000000000000000000000000000::fallback() 
    │   └─ ← ()
    ├─ [0] console::9710a9d0(0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000006b0000000000000000000000000000000000000000000000000000000000000008636f646573697a65000000000000000000000000000000000000000000000000) [staticcall]
    │   └─ ← ()
    └─ ← ()


Script ran successfully.

== Logs ==
  codesize 107
```

**Comment by klkvr** [comment]
https://ethereum.stackexchange.com/questions/113861/q-extcodesize-is-non-zero-after-selfdestruct

This seems to be expected

**Comment by Bobface** [comment]
@klkvr The post you have linked to describes the case when calling `selfdestruct` and `extcodesize` in the same transaction. In that case it is indeed expected, as the contract is only destroyed at the end of the transaction.

What I ran into is the issue that even after the transaction is confirmed, the `extcodesize` is still greater than zero.:
- Transaction A: Calls `selfdestruct`
- Transaction B (after A is confirmed): Calls `extcodesize` which returns >0 although it should be zero.

**Comment by klkvr** [comment]
The script simulation is executed as a single call to script's `run()` method. After that, it collects all external calls, and broadcasts them as separate transactions. The logs you are seeing are from this atomic simulation. 

This seems to be a case when executing calls atomically and in separate transaction may cause different results. I am not even sure if there are any other EVM scenarios when such behavior may happen :)

It seems that fixing this is not possible without much changes to script execution logic, as the only way to collect external-calls is to firstly simulate transaction atomically

**Comment by Bobface** [comment]
@klkvr Ahh, I see. Thanks for the clarification of the internal workings of `forge script`. That explains why this happens.

I wonder if this should still be addressed somehow. The above example is of course made up, but `selfdestruct`ing a contract can be a real-world use case, and the different behaviour between simulation and on-chain execution could cause bugs here.

**Comment by Evalir** [comment]
Hey, so, thanks for the discussion here—I think this informs a feature for scripts for "simulating non-atomic execution"—we'll keep this in mind for when we improve on scripts. I'll close this as it's filed as a bug, but it isn't (pruning issue tracker)
