### ISSUE TITLE
Support cancun version flag

### ISSUE THREAD

**Issue by snreynolds** [foundry-rs/foundry#5782]
### Component

Forge

### Describe the feature you would like

Foundry is updated to use the latest revm (https://github.com/foundry-rs/foundry/issues/5565) which has tstore/tload support, however can't be run because there is no cancun flag. 

Requesting an early cancun flag to be able to run an 1153 enabled environment.

**Comment by mattsse** [comment]
on it

**Comment by mattsse** [comment]
hmm, the --evm-version arg mirrors solc's available versions

https://github.com/ethereum/solidity/blob/develop/liblangutil/EVMVersion.h#L74

I'm hesitant to add it as an additional variant of the `solc::EvmVersion` enum (which mirrors solc's versions) since this would end up as invalid version. 
However the evm_version setting clearly states that it's for the evm:

https://github.com/foundry-rs/foundry/blob/0f530f2ae63342b136ad65e1c7d3b3231b939a6b/crates/config/src/lib.rs#L170-L172

not sure what the correct behaviour for `--evm-version cancun` should be, compile with `shanghai` and configure evm as cancun?

**Comment by snreynolds** [comment]
A temporary cancun flag would work if that's easiest! Meanwhile I did speak with @hrkrshnn who said they can work on making sure evm_version = cancun applies... so if you'd prefer waiting on that I understand too. I am however working off the transient-store branch of solidity though so I'd imagine it would only work there at least until we're closer to cancun

**Comment by snreynolds** [comment]
Thanks! Compiling with custom solc binary just fine but running into `OpcodeNotFound` errors. Working off [this](https://github.com/Uniswap/v4-core/tree/transient-storage) branch and if you want to reproduce you can run `forge test --mt testSwapFailsWithTooLargeFee -vvv`.

**Comment by snreynolds** [comment]
@mattsse Dug into it and solidity and revm are using different hex values. [solidity](https://github.com/ethereum/solidity/commit/de26576f429c5ef9435daf28e3f3af9c1ea270fd#diff-b6252a0d63bb80bb7bba71df32370024b8c94b56984d93a26da70fadac354fadR180) vs [revm](https://github.com/bluealloy/revm/blob/main/crates/interpreter/src/instructions/opcode.rs#L52). The spec is 0x5c/0x5d so I will talk to solc team!

**Comment by mattsse** [comment]
EIP was updated here https://github.com/ethereum/EIPs/pull/7074

**Comment by snreynolds** [comment]
> EIP was updated here [ethereum/EIPs#7074](https://github.com/ethereum/EIPs/pull/7074)

yep! chatting w/solc team.

**Comment by laudiacay** [comment]
any updates here? Is there anything @xBalbinus and i could look at to help get this thru more quickly?

**Comment by mattsse** [comment]
I don't think it's natively supported by recent 0.8.23?
so still requires custom solidity branch

**Comment by hrkrshnn** [comment]
@laudiacay you can use https://github.com/hrkrshnn/tstore-template temporarily; the solc change will only make it to a proper release after the hardfork.

**Comment by NelsonGaldeman** [comment]
Friendly reminder. `cancun` is already added to solc @mattsse 
https://github.com/ethereum/solidity/blob/develop/liblangutil/EVMVersion.h#L90C1-L90C41

**Comment by sambacha** [comment]
This issue should be closed, 0.8.25 uses cancun by default 

cc @DaniPopes / @mds1
