### ISSUE TITLE
Foundry: can't build forge, cast, chisel. ethers-rs fails to compile.

### ISSUE THREAD

**Issue by PierrickGT** [foundry-rs/foundry#5783]
### Component

Forge, Cast, Chisel

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (b1c03fa 2023-09-03T21:03:46.548309000Z)

### What command(s) is the bug in?

cargo install --git https://github.com/foundry-rs/foundry --profile local forge cast chisel anvil

### Operating System

macOS (Apple Silicon)

### Describe the bug

Here is the stack trace of the compile error:
```
   Compiling ethers v2.0.9 (https://github.com/gakonst/ethers-rs#1052c935)
error[E0432]: unresolved imports `ethers_providers::ConnectionDetails`, `ethers_providers::Ipc`, `ethers_providers::Ws`
 --> crates/common/src/runtime_client.rs:6:20
  |
6 |     Authorization, ConnectionDetails, Http, HttpRateLimitRetryPolicy, Ipc, JsonRpcClient,
  |                    ^^^^^^^^^^^^^^^^^                                  ^^^
  |                    |                                                  |
  |                    |                                                  no `Ipc` in the root
  |                    |                                                  help: a similar name exists in the module: `rpc`
  |                    no `ConnectionDetails` in the root
7 |     JsonRpcError, JwtAuth, JwtKey, ProviderError, PubsubClient, RetryClient, RetryClientBuilder,
8 |     RpcError, Ws,
  |               ^^ no `Ws` in the root
  |
  = help: consider importing this variant instead:
          crate::runtime_client::InnerClient::Ipc
  = help: consider importing this variant instead:
          crate::runtime_client::InnerClient::Ws

   Compiling miniz_oxide v0.7.1
   Compiling foundry-utils v0.2.0 (/Users/pierrickturelier/.cargo/git/checkouts/foundry-f7cca724e93059b0/0f530f2/crates/utils)
   Compiling proptest v1.2.0
For more information about this error, try `rustc --explain E0432`.
error: could not compile `foundry-common` (lib) due to previous error; 1 warning emitted
warning: build failed, waiting for other jobs to finish...
error: failed to compile `forge v0.2.0 (https://github.com/foundry-rs/foundry#0f530f2a)`, intermediate artifacts can be found at `/var/folders/pz/dht7l1mj2dxcnqprz89w8fnr0000gn/T/cargo-installi7ge8q`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
error: failed to compile `cast v0.2.0 (https://github.com/foundry-rs/foundry#0f530f2a)`, intermediate artifacts can be found at `/var/folders/pz/dht7l1mj2dxcnqprz89w8fnr0000gn/T/cargo-installKGIWh9`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
error: failed to compile `chisel v0.2.0 (https://github.com/foundry-rs/foundry#0f530f2a)`, intermediate artifacts can be found at `/var/folders/pz/dht7l1mj2dxcnqprz89w8fnr0000gn/T/cargo-installJH421F`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
     Summary Successfully installed anvil! Failed to install forge, cast, chisel (see error(s) above).
error: some crates failed to install
```

**Comment by 0xDetermination** [comment]
I have this exact issue as well

**Comment by dannydoritoeth** [comment]
Im also getting this error. I'm trying to install for the first time.

**Comment by limo923** [comment]
I got this error too

**Comment by bernard-wagner** [comment]
I made the PR to introduce Ipc and Ws. I think `ether-rs` needs to be installed with the `ws` and `ipc` features.

**Comment by conlotor** [comment]
i'm also facing this issue.
@bernard-wagner , do you have any updates about this?

**Comment by PierrickGT** [comment]
Fixed by https://github.com/foundry-rs/foundry/pull/5791

**Comment by gakonst** [comment]
Just wondering, why are folks building from source vs using the released binaries?

**Comment by dannydoritoeth** [comment]
@gakonst - im on windows and the bash scripts weren't working after trying a few things (install wsl, bash etc.) so it was just about needing to try different things until it worked.

**Comment by gakonst** [comment]
Which bash scripts weren't working? Do you mind flagging where we need to improve the docs?

**Comment by dannydoritoeth** [comment]
I would suggest looking at the user journey for someone on windows to install for the first time. 

https://book.getfoundry.sh/getting-started/installation

Everything seems very much oriented towards being on unix including the scripts. I tried setting up wsl and installing bash & curl etc. but it wasn't working so I just moved down the page looking for an easier path.

**Comment by PierrickGT** [comment]
> Just wondering, why are folks building from source vs using the released binaries?

I'm on Mac and use a bash script to handle my dotfiles and automatically update the tools I use.
The cargo command seemed to be the easiest way to install/update Foundry.
