### ISSUE TITLE
anvil_reset cannot start forking, anvil must be already forking

### ISSUE THREAD

**Issue by devanoneth** [foundry-rs/foundry#5805]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (d5c51a5 2023-09-10T00:26:11.552502000Z)

### What command(s) is the bug in?

anvil

### Operating System

macOS (Apple Silicon)

### Describe the bug

It seems like `anvil_reset` is almost at feature parity with `hardhat_reset`, but it's missing one thing. With the hardhat node, you can actually enable forking even if the hardhat node had never been forking before, by passing the following params to `hardhat_reset`:
```json
{ "forking": {"jsonRpcUrl": "<fork_url>" }
```
This will start forking from the latest block on `fork_url` even if the hardhat node was started as purely a local dev node.

Trying the same procedure against anvil yields a `Forking not enabled` error. I've tracked it down to this line: https://github.com/foundry-rs/foundry/blob/d5c51a5007805486ee5a456d35865e0ee440c8a7/crates/anvil/src/eth/backend/mem/mod.rs#L415

I'd like to bring anvil to feature parity with the hardhat RPC here and allow forking to be set for the first time via RPC. If maintainers agree, happy to open a PR.

**Comment by mattsse** [comment]
supportive

on launch, this is how fork db is configured:

https://github.com/mattsse/foundry/blob/master/crates/anvil/src/config.rs#L807-L807

in order to swap out the db we'd need to create a forkdb and replace the mem db

we can reuse a lot of code so this requires some refactoring

**Comment by devanoneth** [comment]
I've started on this and seem to be in `tokio::sync::RwLock` hell. Feel like I'm going about it the wrong way at this point. 

I've moved most of the code from here:
https://github.com/foundry-rs/foundry/blob/5cfed63071ef1bb06f90190d2f678f546bfc971c/crates/anvil/src/config.rs#L807-L807

to a separate function and have added a `node_config` member to the `backend::mem::Backend` struct. This then allows the `backend` to "call up" to the `node_config` to get the `db` and `fork` structs back which it needs to setup forking for the first time. Since doing that, I've had to change `env` and `fork` inside of `backend::mem::Backend` to be wrapped in `tokio::sync::RwLock` and add a lot of subsequent awaits... Feels wrong and still not compiling because then I encounter a lot of `future is not Send` errors due to `env` and `fork` previously not needing async calls.

Maybe instead of "calling up" from the `backend` I should allow the `EthApi` to replace the `backend` entirely? 

Would appreciate some pointers as I feel like I'm going against the grain here. Thanks!

**Comment by mattsse** [comment]
hard to say without looking at a draft.

we definitely need a standalone function that returns:

https://github.com/foundry-rs/foundry/blob/5cfed63071ef1bb06f90190d2f678f546bfc971c/crates/anvil/src/config.rs#L983

basically like 807-983

then it should be possible to replace the rwlock guarded values

**Comment by devanoneth** [comment]
> hard to say without looking at a draft.
Very fair. I was just not happy even sharing the attempt I made yet, so started again with a fresh head and more understanding of the code and I think I've cracked it!

https://github.com/foundry-rs/foundry/pull/5834

**Comment by MOZGIII** [comment]
Just as an FYI, there is another issue in this domain area: https://github.com/foundry-rs/foundry/issues/6018
Might be useful to take that into account if devising the architectural improvements.

**Comment by mattsse** [comment]
@devanoneth can we close this now?

**Comment by devanoneth** [comment]
Sorry for the delay @mattsse, yes, closing now as completed in #6026.
