### ISSUE TITLE
vm.expectRevert not work as expected when calling internal library method

### ISSUE THREAD

**Issue by bogdoslavik** [foundry-rs/foundry#5806]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What command(s) is the bug in?

forge test

### Operating System

Windows

### Describe the bug

BigIntsEx - library with internal methods (not linkable).
Test case fails with message.
```[FAIL. Reason: Overflow()] test_toUint_overflow():(uint256) (gas: 6947)```
So vm.expectRevert not works correctly.
When I test same at contract or library with public method it works as expected.

Currently, to pass this tests I've renamed test function to ```testFail_toUint_overflow()``` 

```
    function test_toUint_overflow() public returns (uint) {
        CommonTypes.BigInt memory big = CommonTypes.BigInt('0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff', false);
        vm.expectRevert(BigIntsEx.Overflow.selector);
        return BigIntsEx.toUint(big);
    }
```

```
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.17;

import "@zondax/filecoin-solidity/contracts/v0.8/utils/BigInts.sol";

library BigIntsEx {
    error Overflow();

    function toUint(CommonTypes.BigInt memory bi) internal view returns (uint) {
        (uint result, bool overflow) = BigInts.toUint256(bi);
        if (overflow) revert Overflow();
        return result;
    }
. . .
```

**Comment by Evalir** [comment]
`expectRevert` works for the _next call_. However, here you're calling a library with an internal method, which means you're performing a `JUMP`, so `expectRevert` won't work as intended. See the book: https://book.getfoundry.sh/cheatcodes/expect-revert?highlight=revert#description
