### ISSUE TITLE
Bad fork_url provider: RelativeUrlWithoutBase

### ISSUE THREAD

**Issue by abhilashi** [foundry-rs/foundry#5807]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (3c49efe 2022-07-14T00:05:10.018576Z)

### What command(s) is the bug in?

yarn deploy (scaffold-eth2)

### Operating System

macOS (Intel)

### Describe the bug

[⠊] Compiling...
No files changed, compilation skipped
The application panicked (crashed).
Message:  Bad fork_url provider: RelativeUrlWithoutBase
Location: /Users/runner/work/foundry/foundry/utils/src/lib.rs:927

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   2: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   3: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   4: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   5: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   6: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   7: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   8: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   9: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  10: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  11: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  12: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  13: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  14: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  15: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.

**Comment by mattsse** [comment]
your version is outdated, the new error message should include the URL, is the URL valid?

**Comment by Evalir** [comment]
Hey @abhilashi—I tried reproducing with the latest foundry version but can't—I get the proper error message. Please check that:
- Your URL is valid
- It is *complete* (has `http://` or `https://`

Closing as it doesn't seem like an actual bug. Please feel free to reopen if this persists.
