### ISSUE TITLE
readInt automatic base detection is a footgun

### ISSUE THREAD

**Issue by dcposch** [foundry-rs/foundry#5808]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (75836a7 2023-09-09T00:31:54.458033000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

JSON reading functions `readInt`/`readUint`/`readIntArray` etc automatically detect the base of the string.

This leads to unpleasant surprises... in our case we had a P256 verifier working on all but four of ~300 Wycheproof test vectors, and the last four were due to `readUint` switching to decimal.

## Minimal reproducible example

```solidity
import {stdJson} from "forge-std/StdJson.sol";
import {Test, console2} from "forge-std/Test.sol";

using stdJson for string;

contract ReadIntTest is Test {
    function testReadInt() public {
        string memory json = '["ffffffff","00000010"]';
        int256[] memory ints = json.readIntArray("");
        console2.log(ints[0]);
        console2.log(ints[1]);
    }
}
```

<img width="610" alt="image" src="https://github.com/foundry-rs/foundry/assets/169280/93d3db1e-1865-4c2f-a8b9-c0f5af2bdf63">

## Proposed fix

- Parse decimal only
- (If there's demand for it, you could parse hex when there is an `0x` prefix)

Less is more. If people pass a bare hex string to readInt, better to error right away (then they can easily `uint256(json.readBytes32(...))`) than sneakily, later, once some input lacks letters.

**Comment by mattsse** [comment]
> This leads to unpleasant surprises... in our case we had a P256 verifier working on all but four of ~300 Wycheproof test vectors, and the last four were due to readUint switching to decimal.

sorry, can you elaborate on this, not exactly following here

what's the issue?

**Comment by dcposch** [comment]
Yes, exactly. In all modern standard libraries I know (Rust, Go, etc) `parseInt("10")` or similar returns 10, `parseInt("ff")` throws an error. Runtime heuristics are bad especially in this context (smart contract testing).

**Comment by dcposch** [comment]
@mds1 yes, sounds perfect. key is it's deterministic: string either starts with 0x (and is parsed as hex) or not (and is parsed as decimal), no guessing.

**Comment by mds1** [comment]
cc @Evalir, this should be an easy one to fix to remove the footgun

**Comment by ruvaag** [comment]
@mds1 @Evalir I can take this up, but might need some help.

Couple of things I came across:
* This behaviour appears to be bubble from the [parity-common/uint](https://github.com/paritytech/parity-common/blob/6ba56691d1b8efabd9bed115d146372c7843476c/uint/src/uint.rs#L1712) `U256` implementation
* Under the hood`parseJsonInt` and `parseJsonUint` cheats use the same parse function also used by `parseInt` and `parseUint` ([ext::parse_json](https://github.com/foundry-rs/foundry/blob/92900269bd38751d868afaf901f23c402e3e22b1/crates/evm/src/executor/inspector/cheatcodes/ext.rs#L315) calls [parse::parse](https://github.com/foundry-rs/foundry/blob/92900269bd38751d868afaf901f23c402e3e22b1/crates/evm/src/executor/inspector/cheatcodes/parse.rs#L10)) so directly modifying one would affect the other too.

Given this, one way way to proceed could be to explicitly check if a non-prefix string contains only numeric characters before parsing it as a uint / int across all kinds of cheats? Curious if there's a better way or if I'm missing something here.

**Comment by Evalir** [comment]
happy to assign it to you @ruvaag !

indeed, this is bubbling up from the parity types crate. What you propose is what I'd do—only accept decimal characters before parsing as `uint`/`int`. Eventually we'll switch to alloy types and this will be a tad easier to do.
