### ISSUE TITLE
false positive results when using `vm.expectRevert` - part of the test is ignored

### ISSUE THREAD

**Issue by DZariusz** [foundry-rs/foundry#5820]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (893fc9f 2023-09-12T00:28:57.627748000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

```
function test_should_fail_1() public {
    vm.expectRevert();
    revert("A");

    // execution stops here for some reason

    revert("never reverts and test passes");
}

function test_should_fail_2() public {
    vm.expectRevert();
    revert("A");

    assertTrue(false, "test pass despite failed condition");
}
```

this tests **pass**, but they should not. 

```
foundryup: installed - forge 0.2.0 (893fc9f 2023-09-12T00:28:57.627748000Z)
foundryup: installed - cast 0.2.0 (893fc9f 2023-09-12T00:28:57.752674000Z)
foundryup: installed - anvil 0.2.0 (893fc9f 2023-09-12T00:28:57.365492000Z)
foundryup: installed - chisel 0.2.0 (893fc9f 2023-09-12T00:28:57.495467000Z)
```

**Comment by Evalir** [comment]
Please see https://github.com/foundry-rs/foundry/issues/3723 — this is a known footgun, as reverts stop EVM execution. It will be fixed with #5728 but for now the recommendation is to split these tests.
