### ISSUE TITLE
jemalloc breaks foundry build process for systems with unsupported page sizes 

### ISSUE THREAD

**Issue by mtugan** [foundry-rs/foundry#5832]
### Component

`forge`, `chisel`, `cast`

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What command(s) is the bug in?

In the build process.

### Operating System

Linux (aarch64)

### Describe the bug

Due to the following:

https://github.com/jemalloc/jemalloc/issues/467

`jemalloc` will break portable foundry binaries or if building from source the build process on systems with page sizes different from the compiled-in one (not sure exactly what that page size is, 4k?). 

In any case an example output when build on the ALARM kernel:

```bash
foundryup: downloading manpages
###################################################################################################### 100.0%
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
memory allocation of 5 bytes failed
foundryup: command failed: /var/cache/pacman-aur/srcpkg/foundry-bin/src/usr/bin/forge --version
foundryup: installed - 
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
memory allocation of 5 bytes failed
foundryup: command failed: /var/cache/pacman-aur/srcpkg/foundry-bin/src/usr/bin/cast --version
foundryup: installed - 
foundryup: installed - anvil 0.2.0 (74c0318 2023-09-14T00:22:18.142452503Z)
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
memory allocation of 5 bytes failed
foundryup: command failed: /var/cache/pacman-aur/srcpkg/foundry-bin/src/usr/bin/chisel --version
foundryup: installed - 
foundryup: done!
==> Starting pkgver()...
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
memory allocation of 5 bytes failed
```

The following PR introduces `jemalloc` for `forge`, `chisel`, `cast`, `anvil`:

https://github.com/foundry-rs/foundry/pull/5690

The following PR removes `jemalloc` from `anvil` due to other issues:

https://github.com/foundry-rs/foundry/pull/5759

It would be nice to remove `jemalloc` entirely.

**Comment by rymnc** [comment]
This issue exists again, since `jemalloc` was re-introduced as a default feature.

I'm running on `aarch64-unknown-linux-gnu` (an old M1 mini w/ Asahi), and am facing this issue while using `foundryup`, but not when installing from source.

Here's an issue in another repo, and their patch:
issue: https://github.com/oxc-project/oxc/issues/3783
patch: https://github.com/oxc-project/oxc/commit/a94ef68c0f005e00398762f97806c23484c299e1
