### ISSUE TITLE
suggestion: rename `vm.skip` to `vm.skipTest`

### ISSUE THREAD

**Issue by mds1** [foundry-rs/foundry#5837]
### Component

Forge

### Describe the feature you would like

In https://github.com/foundry-rs/foundry/pull/5205 `vm.skip(bool)` cheat was added to skip tests. However for a long time forge-std has had [`skip`](https://github.com/foundry-rs/forge-std/blob/705263c95892a906d7af65f0f73ce8a4a0c80b80/src/StdCheats.sol#L646-L649) which skips forward in time.

The latter has been around longer, and `skipTest` is more explicit, so I'd suggest renaming the `vm.skip` cheat to `vm.skipTest`

If people agree with this change, let's introduce `vm.skipTest` now and remove `vm.skip` as part of the v1 release

**Comment by PraneshASP** [comment]
Agreed that it is confusing to use `skip` for both. In favor of using `skipTest()`. Can take this on if needed. lmk
