### ISSUE TITLE
Discrepancy in block.number during on-chain deployement in Forge script

### ISSUE THREAD

**Issue by Maroutis** [foundry-rs/foundry#5840]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (75836a7 2023-09-09T00:28:38.542568580Z)

### Operating System

None

## Component
**Forge**

## Related Issue
This issue is somewhat related to #1902 but discusses a distinct concern.

## Issue Description
I'm trying to automate the deployment process of the [Ethernaut #3](https://ethernaut.openzeppelin.com/level/0xA62fE5344FE62AdC1F356447B669E9E6D10abaaF) challenge on-chain using a Forge script. The challenge's resolution necessitates the execution of specific transactions depending on the block's hash. 
Right now, I've given up on using a loop to resolve the challenge as this won't work since the block.number is not changing which causes the transaction to revert. I've now adopted the strategy of manually executing the script provided below ten times:

```solidity
vm.startBroadcast(deployerKey);
uint256 blockValue;
uint256 coinFlip;
blockValue = uint256(blockhash(block.number - 1));
coinFlip = blockValue / 57896044618658097711785492504343953926634992332820282019728792003956564819968;
require(CoinFlip(instance).flip(coinFlip == 1), "guess failed");
console.log("Consecutive wins : ", CoinFlip(instance).consecutiveWins());
vm.stopBroadcast();
```

However, I've noticed that a discrepancy has emerged between the simulation logs and the actual on-chain results:
```plaintext
[29877] CoinFlip::flip(true) 
    │   └─ ← true
    ├─ [295] CoinFlip::consecutiveWins() [staticcall]
    │   └─ ← 1
    ├─ [0] console::f5b1bba9(0000000000000000000000000000000000000000000000000000000000000001) [staticcall]
    │   └─ ← ()
    ├─ [295] CoinFlip::consecutiveWins() [staticcall]
    │   └─ ← 1
    ├─ [0] VM::stopBroadcast() 
    │   └─ ← ()
    └─ ← ()
Script ran successfully.

== Logs ==
  Using same instance
  Consecutive wins : 1

SKIPPING ON CHAIN SIMULATION.

###
Finding wallets for all the necessary addresses...
##
Sending transactions [0 - 0].
```

The logs say that consecutive wins = 1 but on sepolia.etherscan it says 0 (which mean the guess was wrong):
![](https://github.com/foundry-rs/foundry/assets/118286466/2a82d41b-bf25-4019-b275-c44f80678fd0)

This doesn't always happen, but still do often.

Here's my guess, I believe that foundry fails to simulate block.number. Reasons :
1. When executing the exact same piece of code on remix, everything works as expected.
2. When executing the script in foundry in --slow slow mode, the result will be different from the actual chain results 100% of the time.

## Desired Feature
A tool or feature that accurately simulates the mining of a new block in Foundry, or ensuring that the --slow mode genuinely and consistently simulates increments in block.number.

**Comment by Evalir** [comment]
The thing is, there's a few things here:
- Even if we perform the simulation correctly (right now we only have atomic simulations), you still have network delays to get over, which could cause your tx to not be included in the block you intended it to be, therefore making your guess possibly fail.
- If you do this on a test (which I'd recommend rather than a script), you have cheatcodes to manipulate the block number. See the book: https://book.getfoundry.sh/cheatcodes/roll
- Are you forking as well?

In general, I'd say this is more of a user thing. I'd consider looking at how different ethernaut x foundry impls work: https://github.com/ciaranmcveigh5/ethernaut-x-foundry

**Comment by Maroutis** [comment]
@Evalir 

> The thing is, there's a few things here:
> 
> * Even if we perform the simulation correctly (right now we only have atomic simulations), you still have network delays to get over, which could cause your tx to not be included in the block you intended it to be, therefore making your guess possibly fail.
> * If you do this on a test (which I'd recommend rather than a script), you have cheatcodes to manipulate the block number. See the book: https://book.getfoundry.sh/cheatcodes/roll
> * Are you forking as well?
> 
> In general, I'd say this is more of a user thing. I'd consider looking at how different ethernaut x foundry impls work: https://github.com/ciaranmcveigh5/ethernaut-x-foundry

Thank you for the feedback. Actually, I've already done this on a local test (no forking) using the cheatcodes and it works as expected. I wanted to fully automate the scripting part to validate the solution on a testnet without having to go through the ethernaut platform or using another tool for deployement. But, I understand that this will not be possible due to the reasons that you mentioned. 
Also I have a last question, is it conceivable to add functions (or cheatcodes) in foundry to mine and wait for blocks using scripts ?
