### ISSUE TITLE
forge test hangs after finishing running tests

### ISSUE THREAD

**Issue by holic** [foundry-rs/foundry#5845]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ecf9a10 2023-09-17T00:27:35.909605000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

With latest foundry, I’ve been seeing `forge test` hang for several seconds after “Ran … test suites” (aka tests complete).

I asked about this in the Telegram channel and confirmed a few others are seeing this too. Any ideas on debugging?

I'm not sure if this is related, but also seeing anvil (started and stopped via anvil.js) take a while to shut down.

**Comment by Evalir** [comment]
hey—would like to investigate this. Any specific repo you're observing this on so i can reproduce?

**Comment by holic** [comment]
I'm not sure if it's specific to our repo or my OS, but here's the code I'm working in: https://github.com/latticexyz/mud

```
pnpm install
cd packages/store
forge test
```

I haven't seen any recent slow downs in our tests or gas reports in CI, so I am curious if this is a MacOS thing.

**Comment by trevorgjohnson** [comment]
I'm also seeing the same problem but it seems to only occur on test suites with more than 100 tests (Like [Solady](https://github.com/Vectorized/solady) for instance). I'm on a M1 Max Macbook if that helps as well 👍

**Comment by trevorgjohnson** [comment]
@Evalir, if it helps, I did some breakpoint logging to see where the halting is happening and it looks like it has something to do with this for loop in _crates/forge/bin/cmd/test/mod.rs_. I'll try narrowing down further.

![image](https://github.com/foundry-rs/foundry/assets/27569194/96e1926f-4175-4ce5-9f1d-1ea03a149758)

**Comment by Evalir** [comment]
Ohhhhh I see... @trevorgjohnson can you try running forge with `RUST_LOG=forge,forge::evm,etherscan`?

**Comment by holic** [comment]
I can see forge process spinning at 70-100% CPU after tests complete

with those env vars, I don't see any extra output between the last log line and the several seconds until I get returned to my command line:
```
[PASS] testIsEnabled() (gas: 5724)
Test result: ok. 4 passed; 0 failed; 0 skipped; finished in 841.38ms

Ran 26 test suites: 247 tests passed, 0 failed, 0 skipped (247 total tests)
2023-09-21T15:35:15.064808Z TRACE forge::test: received 26 results
mud/packages/store %

**Comment by holic** [comment]
confirmed fixed with the latest foundry, thanks! 🙏
