### ISSUE TITLE
feat: add real-time counter for fuzz/invariant runs

### ISSUE THREAD

**Issue by mds1** [foundry-rs/foundry#585]
dapptools has a counter like the one in the screenshot below so you can track progress in fuzz runs while those fuzz runs are executing. I recently ran a 10k fuzz run test that uses ffi, so it was quite slow and appears as if tests hang. A counter that updates live like the one below would be helpful for monitoring fuzz/invariant run progress and having confidence tests are still running as expected

![image](https://user-images.githubusercontent.com/17163988/151186647-d463d552-b2ca-45c6-91a6-93a8ca8f5843.png)

**Comment by pbshgthm** [comment]
I could see the run count, along with mean and median too - implemented in this line.

https://github.com/gakonst/foundry/blob/9de25d1928da362cd3b185ebaccc0e3d00aee2c8/forge/src/runner.rs#L101

Am I missing something here, or this feature is already implemented?

<img width="593" alt="Screenshot 2022-01-26 at 1 54 42 PM" src="https://user-images.githubusercontent.com/24489964/151128057-e74b09da-7805-443c-9a5d-763c3aaa50ca.png">

**Comment by onbjerg** [comment]
Oh, you are right.

Perhaps the request is probably moreso the real-time update of the counter (if supported by your terminal) than the count itself? Generally we should work on streaming in test results where possible #141

**Comment by mds1** [comment]
Ah yea it does show the number of fuzz runs after a run already. The main motivation for opening this issue was to show a counter during the fuzz runs. I recently ran 10k fuzz runs with ffi, so it was quite slow, and it looks like your tests are hanging since there's nothing printed to the terminal during execution. 

A real-time fuzz run counter seems to be a simpler scope than #141, and I don't see this functionality mentioned in there (though I only skimmed all the comments), so I feel like they could be tracked separately. But either way is fine with me 🙂

**Comment by onbjerg** [comment]
I agree it would be valuable to have some sort of real-time counter. Let's track it here then :sweat_smile: Can you update the original issue to reflect it?

**Comment by lucas-manuel** [comment]
I would love to see this for invariants

**Comment by PaulRBerg** [comment]
This would also be useful for long-winded end-to-end fork tests, since they can take a long time to run.

**Comment by brockelmore** [comment]
We should add coverage % for invariant runs. Basically, record locations of `JUMPDEST`s in a contract, and when we hit it record that and print out something like:
```
Runs: 6097
Coverage: 54% (27/54 Blocks)
```
