### ISSUE TITLE
Forge script should treat 0x0 returned from eth_getStorageAt as zero

### ISSUE THREAD

**Issue by nhynes** [foundry-rs/foundry#5856]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8c1a569 2023-09-18T22:08:02.792869850Z)

### What command(s) is the bug in?

forge script

### Operating System

Linux

### Describe the bug

Some networks return `hexutil.Big` from their implementation of `eth_getStorage`, which marshals zero as `0x0`. This causes forge to produce an error that looks like `fuzz: failed to inspect: Database(GetStorage(contract, slot), Odd number of digits)`. `hexutil.Big` is a reasonable thing to be returned by a web3 gateway, so `forge script` should treat `0x0` as zero.

It is very inconvenient to fall back to `cast` for deployments because scripting doesn't work due to this bug. MITM proxying the Web3 gateway and returning `0x` is my workaround for now.

**Comment by zerosnacks** [comment]
Hi @nhynes thanks for your report!

We've recently moved to Alloy and the behavior of `U256` has changed accordingly

```
use alloy::primitives::U256;
use std::str::FromStr;

fn main() {
    let a = U256::from(0);

    let zero = "0x0";
    let b = U256::from_str(zero).expect("Failed to parse 0x0");

    println!("a: {}, b: {}", a, b);

    assert_eq!(a, b);
}
```

Runs succesfully and prints

```
a: 0, b: 0
```

Would be great to know if you are still facing this issue with the lastest version of Foundry, if not we can mark this ticket as resolved.

**Comment by mattsse** [comment]
iirc the ethstoragekey situation has been improved across multiple clients since this issue.
optimistically closing, please open a new issue if this is still a problem
