### ISSUE TITLE
foundry crashing when debugging

### ISSUE THREAD

**Issue by thedavidmeister** [foundry-rs/foundry#5883]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ec3f9bd 2023-09-19T13:46:42.143604000Z)

### What command(s) is the bug in?

forge test --debug

### Operating System

macOS (Apple Silicon)

### Describe the bug

This command:

```
thedavidmeister@davids-iMac rain.interpreter % forge test --debug testOpCallNPRunOrdering                    
[⠢] Compiling...
No files changed, compilation skipped
The application panicked (crashed).
Message:  We should have collected debug information
Location: crates/debugger/src/debugger.rs:28

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
zsh: abort      forge test --debug testOpCallNPRunOrdering
```

on this commit/test:

https://github.com/rainprotocol/rain.interpreter/pull/58/commits/b4e7baed64e04f99dcacbd7dabfa54aba78b33eb#diff-bea0843aa18e85c9b745792c10293799f94956cb299f847b0ba81e7276eed1ccR12

**Comment by ShuaJJ** [comment]
Same issue

**Comment by 0xbbbaron** [comment]
Facing same issue. Reproduces on Ubuntu Linux 20.

**Comment by mattsse** [comment]
sorry for the wait.

I debugged this and fixed a bug that was the root cause of the reported crash.
