### ISSUE TITLE
Unknown evm version: paris for setting `evm_version`

### ISSUE THREAD

**Issue by mauricedesaxe** [foundry-rs/foundry#5884]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (d09be02 2023-02-24T00:15:39.16429Z)

### What command(s) is the bug in?

forge install, forge build

### Operating System

macOS (Apple Silicon)

### Describe the bug

I was attempting to participate in [this Code4rena contest](https://code4rena.com/contests/2023-09-maia-dao-ulysses#top). I cloned their [repo which can be found here](https://github.com/code-423n4/2023-09-maia).

First things first, I used `forge install` which returned the following logs (I'm replacing my name with <user>):

```
Updating dependencies in "/Users/<user>/Developer/2023-09-maia/lib"
(base)
```

I assumed all is well and went on to use `forge build` which provided the following output:

```
❯ forge build
The application panicked (crashed).
Message:  failed to extract foundry config:
foundry config error: Unknown evm version: paris for setting `evm_version`

Location: config/src/lib.rs:449

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
[1]    98536 abort      forge build
(base)
```

The same error now also happens for `forge install`.

I looked at the root `foundry.toml` file and there is no mention of using the paris version, but I still modified it to explicitly try london as such:

```
[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.19"
evm_version = "london"
via_ir = true
gas_price = 10000
```

The error still happens just the same. So I CMD+SHIFT+F ed my way to look for any "paris" mention throughout the whole code base.

It appears Solady which is a dependancy of this project uses paris for their `evm_version`.

Please not that I'm not a Foundry/forge expert nor a solc versioning expert. I simply figured it might be useful to you to report this because the error message told me so.

Also, I haven't really tried diving to deep yet. I figured I should report early and update this issue later if I figure out the fix for this. 

Thanks.

**Comment by mattsse** [comment]
> forge 0.2.0 (https://github.com/foundry-rs/foundry/commit/d09be021460fe2b28fc9a6e338f3db42894d7e21 2023-02-24T00:15:39.16429Z)

try new foundry version

**Comment by mauricedesaxe** [comment]
Fixed it by updating foundry. Thanks.
