### ISSUE TITLE
forge coverage output files need a flag to specify the name and location of where lcov.info should be placed

### ISSUE THREAD

**Issue by rswanson** [foundry-rs/foundry#5886]
### Component

Forge

### Describe the feature you would like

In the `forge coverage --report lcov` command it will automatically generate `lcov.info` within the root of the project. It would be great if we could specify the name and location of this file via a flag. 

Suggested syntax: `--report-file /path/to/lcov.info` 

Just as another design thought, it might be a nice if this file flag could also work on the other report types as well, in the case of a summary report it could output the summary to a file instead of stdout. 

### Additional context

This is documented as a [TODO in the codebase already](https://github.com/foundry-rs/foundry/blob/master/crates/forge/bin/cmd/coverage.rs#L345), didn't find a corresponding issue.

**Comment by Perelyn-sama** [comment]
handling this one
