### ISSUE TITLE
Fail to reproduce invariant error

### ISSUE THREAD

**Issue by PavelCore** [foundry-rs/foundry#5891]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ec3f9bd 2023-09-19T13:48:52.205431000Z)

### What command(s) is the bug in?

FOUNDRY_INVARIANT_RUNS=1 FOUNDRY_INVARIANT_DEPTH=15 forge test -v --mc="CallStorageTest"

### Operating System

macOS (Intel)

### Describe the bug

While making an invariant testing, Forge successfully identifies failing scenario but cannot reproduce it when the targeted contract does not implement targeted interface, despite having a fallback function and artifacts provided.

Example handler without the actual implementation of the functions in the code:
```
contract CallStorageHandler {

    bytes private _storedCall;
    uint256 public storedCalls = 0; 

    modifier storeCall() {
        console2.log("storing call");
        console2.logBytes(msg.data[:4]);
        storedCalls += 1;
        _storedCall = msg.data;
        _;
    }

    function getStoredCall() external view returns(bytes memory) {
        return _storedCall;
    }

    fallback() external storeCall {}
    receive() external payable storeCall {}

    // These functions are present in IReentrant interface
    // function deposit() external payable storeCall {
    // }

    // function withdraw() external storeCall {
    // }
}
```

The contract has a callback, hence it should not fail with any called function.

The contract with the invariants. It calls the `CallStorageHandler` contract with the fuzzed functions from `IReentrant` interface.
```
contract CallStorageTest is Test {
    Reentrant public reentrant;
    CallStorageHandler public callStorage;

    function setUp() public {
        reentrant = new Reentrant();
        excludeContract(address(reentrant));

        callStorage = new CallStorageHandler();
        string[] memory artifacts = new string[](1);
        artifacts[0] = "src/interfaces/IReentrant.sol:IReentrant";
        targetInterface(FuzzInterface(
            payable(address(callStorage)), artifacts
        ));
    }

    function invariant_storedCallsCounter() public {
        assertLe(callStorage.storedCalls(), 10);
    }
}
```

Here is the output of the forge:
```
$ FOUNDRY_INVARIANT_RUNS=1 FOUNDRY_INVARIANT_DEPTH=15 forge test -v --mc="CallStorageTest"
[⠰] Compiling...
No files changed, compilation skipped
2023-09-25T13:11:21.423554Z ERROR forge::runner: Failed to replay invariant error err=
Failed to create counter example

Context:
- Couldn't find function

Running 1 test for test/TestProxy.t.sol:CallStorageTest
[FAIL. Reason: Assertion failed.] invariant_storedCallsCounter() (runs: 1, calls: 11, reverts: 0)
Test result: FAILED. 0 passed; 1 failed; 0 skipped; finished in 31.69ms
 
Ran 1 test suites: 0 tests passed, 1 failed, 0 skipped (1 total tests)

Failing tests:
Encountered 1 failing test in test/TestProxy.t.sol:CallStorageTest
[FAIL. Reason: Assertion failed.] invariant_storedCallsCounter() (runs: 1, calls: 11, reverts: 0)

Encountered a total of 1 failing tests, 0 tests succeeded
```

The basic idea is that I want to fuzz the calls to the Reentrant contract without actually calling it and without implementing the whole interface of it in another contract.

**Comment by bernard-wagner** [comment]
Think it might due to `CallStorageHandler` not having any mutable functions (Doesn't consider fallback) and being excluded from the test cases. Try again with a dummy mutable function. `function dummyFunc() external {}`.

**Comment by bernard-wagner** [comment]
Did some initial investigation and it seems that the issue is due to `load_contracts` not extending the abis with those specified in `targetInterface`. https://github.com/foundry-rs/foundry/blob/a1f5842c62a5fdd6f6b52cc2a852d2cca7e73f47/crates/evm/src/fuzz/invariant/mod.rs#L135

So it fails to find the function. Clearly an oversight when I initially developed `targetInterface` helper. I will investigate how to pass the extended abi down the stack.

**Comment by bernard-wagner** [comment]
@PavelCore I have a WIP fix. It not a perfect fix, as it will not decode the functions in the CounterExample printout. However, in general I don't think forge should bail if it can't pretty decode the call trace.

**Comment by PavelCore** [comment]
In case anyone needs to decode a trace, here is a trick:
You can deploy the contract with a desired interface and after that, change the bytecode at that address to any desired one. The forge will use an old contract interface for the trace decoding.

```
function _deployCallStorageHandler() internal returns(address payable) {
        Reentrant reentrantToReplace = new Reentrant();
        deployCodeTo("./CallStorageHandler.sol", address(reentrantToReplace));
        return payable(address(reentrantToReplace));
    }
```

I do not recommend using this approach though.
