### ISSUE TITLE
Remappings with the same prefix but different contexts are broken

### ISSUE THREAD

**Issue by mateuszradomski** [foundry-rs/foundry#5902]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ec3f9bd 2023-09-19T13:46:42.143604000Z)

### What command(s) is the bug in?

every forge subcommand

### Operating System

None

### Describe the bug

Hello,

We're trying to use forge for testing in L2Beat but we've encountered a problem that makes it hard to integrate it into our workflow. The problem in question is that since we download all of the source code from Etherscan we end up with a big directory with many different subdirectories where each one of them corresponds to source code for a given contract in a given project.

Something like this:

```
.code
├── Colosseum
│   ├── implementation
│   └── proxy
└── KromaPortal
    ├── implementation
    └── proxy
```

We would want to create a single foundry project to test all of the different contracts. Each contract provides its own dependencies like `@openzeppelin` in the `implementation` folder. The idea we came up with is to use remappings and create a following structure for the test folder

```
test
├── Colosseum
└── KromaPortal
```

Where for each test subdirectory we would specify a different remapping using the context feature of solc. As its [documentation](https://docs.soliditylang.org/en/latest/path-resolution.html#import-remapping) specifies, it is possible to create a remapping per module using the context field with the same prefix but a different value.

>As a more complex example, suppose you rely on a module that uses an old version of dapp-bin that you checked out to /project/dapp-bin_old, then you can run:
> ```
>solc module1:github.com/ethereum/dapp-bin/=dapp-bin/ \
>      module2:github.com/ethereum/dapp-bin/=dapp-bin_old/ \
>      --base-path /project \
>      source.sol
>```

But creating a following remapping (it does not matter there the remapping is specified, both `remappings.txt` and `foundry.toml` do not work) fails to be parsed by `forge remappings` subcommand:

```
test/Colosseum/:@code/=code/Colosseum/implementation/
test/KromaPortal/:@code/=code/KromaPortal/implementation/
code/Colosseum/:@openzeppelin/=code/Colosseum/implementation/node_modules/@openzeppelin/
code/Colosseum/:@rari-capital/=code/Colosseum/implementation/node_modules/@rari-capital/
code/KromaPortal/:@openzeppelin/=code/KromaPortal/implementation/node_modules/@openzeppelin/
code/KromaPortal/:@rari-capital/=code/KromaPortal/implementation/node_modules/@rari-capital/
```

---

Expected `forge remappings` output:
```
test/Colosseum/:@code/=code/Colosseum/implementation/
test/KromaPortal/:@code/=code/KromaPortal/implementation/
code/Colosseum/:@openzeppelin/=code/Colosseum/implementation/node_modules/@openzeppelin/
code/Colosseum/:@rari-capital/=code/Colosseum/implementation/node_modules/@rari-capital/
code/KromaPortal/:@openzeppelin/=code/KromaPortal/implementation/node_modules/@openzeppelin/
code/KromaPortal/:@rari-capital/=code/KromaPortal/implementation/node_modules/@rari-capital/
```

Actual `forge remappings` output:
```
test/Colosseum/:@code/=code/Colosseum/implementation/
code/Colosseum/:@openzeppelin/=code/Colosseum/implementation/node_modules/@openzeppelin/
code/Colosseum/:@rari-capital/=code/Colosseum/implementation/node_modules/@rari-capital/
```

---

This is not only observed in the `forge remappings` subcommand but `forge test` also fails as if it did not know the second set of remappings. I've created a repository that will allow you to repro that case [here](https://github.com/mateuszradomski/forge-repo). 
I've also been able to **fix the issue** myself, the code is in #5901, I've marked it as a draft since I don't expect that the lack of tests is going to be passable, but I wanted to provide a jumping of point anyway.

I'm open to answering any questions to get this issue solved as soon as possible, thanks in advance!

**Comment by Evalir** [comment]
Right, so, remapping contexts, at this point in time, are not supported. We tried to introduce them back in July but ran into the issue that introducing them can break existing repo setups for a _lot_ of users, therefore, we're a bit wary of introducing them again. Will look at the PR draft!

**Comment by mateuszradomski** [comment]
Closing as #5901 has been merged.
