### ISSUE TITLE
Application panicked (crashed). Mismatch between definition and access of `fuzz_seed`

### ISSUE THREAD

**Issue by adaki2004** [foundry-rs/foundry#5913]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What command(s) is the bug in?

forge test -vvv --gas-report --fuzz-seed ...

### Operating System

None

### Describe the bug

From day one to another, we experience the following issue (in our github CI/CD):
![kép](https://github.com/foundry-rs/foundry/assets/51912515/049d97e0-bd82-42fc-8cf7-e4762d214760)

Please see our CI/CD job here:
https://github.com/taikoxyz/taiko-mono/actions/runs/6310828389/job/17133554856?pr=14823

Also the strange thing is, that we do not see it locally just in CI/CD.

Here is the pull request i'm experimenting with, to solve the issue:
https://github.com/taikoxyz/taiko-mono/pull/14823

**Comment by mattsse** [comment]
try fuzz seed as hex

**Comment by adaki2004** [comment]
> try fuzz seed as hex

Hmm..
<img width="1224" alt="kép" src="https://github.com/foundry-rs/foundry/assets/51912515/69ac7648-6184-42ad-a245-5ca80429d888">

**Comment by mattsse** [comment]
thanks, found the bug, will be fixed shortly

fyi @Evalir  #5916
