### ISSUE TITLE
`--deny-warnings` causes compilation to succeed on error

### ISSUE THREAD

**Issue by Lumyo** [foundry-rs/foundry#5927]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (80df71f 2023-09-26T17:57:41.214971363Z)

### What command(s) is the bug in?

forge b --deny-warnings

### Operating System

Linux

### Describe the bug

1. Fork https://github.com/PaulRBerg/foundry-template
2. Introduce an error in `Foo.sol` (Ex : Change `function id(uint256 value)` to `function id(uint111 value)`)
3. Run `forge build` work as expected and result in `Compiler run failed` :
```sh
forge b
[⠒] Compiling...
[⠆] Compiling 3 files with 0.8.19
[⠰] Solc 0.8.19 finished in 98.31ms
Error:
Compiler run failed:
Error (7920): Identifier not found or not unique.
 --> src/Foo.sol:5:17:
  |
5 |     function id(uint111 value) external pure returns (uint256) {
  |                 ^^^^^^^
```
4. Run `forge build --deny-warnings` result in `Compiler run successful`
```sh
forge b --deny-warnings
[⠒] Compiling...
[⠆] Compiling 3 files with 0.8.19
[⠰] Solc 0.8.19 finished in 83.02ms
Compiler run successful!
Error (7920): Identifier not found or not unique.
 --> src/Foo.sol:5:17:
  |
5 |     function id(uint111 value) external pure returns (uint256) {
  |                 ^^^^^^^
```

This leads to CI not failing as expected when the flag is used and there is a compilation error.

**Comment by CodeSandwich** [comment]
It silences compilation errors not only from `forge build` but also `forge test`. It's a **severe** issue and I got caught by it too. It's not a common flag to use in the local environment, it's pretty much only for the CIs which makes it especially tricky to find, if somebody pushes code that doesn't compile, you need to read the logs to catch the fault.
