### ISSUE TITLE
Vyper Support

### ISSUE THREAD

**Issue by ControlCplusControlV** [foundry-rs/foundry#5934]
### Component

Forge

### Describe the feature you would like

# Goal

Foundry should ideally support compiling Vyper contracts and running tests against them. With the development of [vypers-rs](https://github.com/crypdoughdoteth/vyper-rs) vyper now has rust compiler bindings (and additional ones can be added as needed but it's current stage should support it. [vypers-rs] can both auto-detect and install a new version of vyper if needed, and keeps it all contained within venvs.

Plan would be to a feature flag supporting Vyper initially, then as it stabilizes gradually add it to the default

**Comment by crypdoughdoteth** [comment]
Can I grab this? @gakonst

**Comment by zerosnacks** [comment]
Marking as resolved by https://github.com/foundry-rs/foundry/pull/8011

For the limitation on `forge coverage` tracking here: https://github.com/foundry-rs/foundry/issues/5411
