### ISSUE TITLE
Feature request: vm.time() cheatcode to return current system time in milliseconds since epoch

### ISSUE THREAD

**Issue by Tudmotu** [foundry-rs/foundry#5937]
### Component

Forge

### Describe the feature you would like

It would be nice to have a cheatcode for getting the current system time in milliseconds since epoch.

Personally my main use case is for measuring performance of scripts. Some scripts can become quite complex and I encounter performance issues and I find it useful to measure the time it takes certain parts of the script to run.

Currently my solution is to use `vm.ffi(['python', '-c', 'import time; print(int(time.time() * 1000))'])` :sweat_smile: 

The interface I have in mind is:
```solidity
function time () view returns (uint millisecondsSinceEpoch);
```

I'll also happily open a PR if needed :slightly_smiling_face:

**Comment by mattsse** [comment]
with epoch you mean the unix epoch, right?

supportive, I think this is useful.

**Comment by Tudmotu** [comment]
Yes, I mean the unix epoch :slightly_smiling_face: 

Would you like me to open a PR or rather leave this to the core team?

**Comment by mattsse** [comment]
happy to accept a pr for this

**Comment by mds1** [comment]
I'd suggest a more clear name like `vm.systemTime` or `vm.unixTime` to make it clear what time this is referring to, to disambiguate against block timestamp

**Comment by Tudmotu** [comment]
@mattsse @mds1 I've opened a draft PR with some open questions, maybe we can move the discussion there?
https://github.com/foundry-rs/foundry/pull/5952
