### ISSUE TITLE
feat(cheatcodes): add `vm.setHelperContract(myToken, helper)` to modify storage in `myToken`;

### ISSUE THREAD

**Issue by drortirosh** [foundry-rs/foundry#5951]
### Component

Other (please describe)

### Describe the feature you would like

There is a lot of confusion on how to modify storage (e.g. using StdStorage) for testing purposes.
Here is a suggestion to a new way to modify storage.
- add a VM cheat to run transaction with *alternate code* (this is kind of "reverse delegateCall")
- developer should override the original contract, and add "god-mode" methods to modify storage, and deploy it.
- This after calling:
  `vm.setGodMode(originalContract, godModeContract)`
  he can use `godModeContract.doSometing()` which will modify the storage of `originalContract`

- this "GodModeContract" can either be a sub-class of original contract, or just contain a copy of all its storage (e.g. [safe's storage](https://github.com/safe-global/safe-contracts/blob/main/contracts/libraries/SafeStorage.sol)) 
- can even add a helper to generate such "storage layout" contract, either by parsing solidity code, or using --storage-layout

**Comment by zerosnacks** [comment]
Hi @drortirosh 

I think this is largely achievable by using https://book.getfoundry.sh/cheatcodes/etch and https://book.getfoundry.sh/cheatcodes/store

Feel free to re-open if this is not the case

**Comment by drortirosh** [comment]
`vm.store()` works, but it is very difficult to use, and requires deep understanding of the VM structure.

Example of my suggestion:
assume you have a `MyToken` contract I want to test, and I want to initialize a large amount.
I _don't_ want to change the implementation of the contract for the test, and using "vm.store()" is difficult.

So I create a helper:

```solidity
contract HelperToken is MyToken {
   function setAmount(address addr, uint val) {
    //assume the token implementation has a low-level internal "mint" function
     _mint(addr, val);
   }
}
```

It is possible to use the helper with `etch` - but it requires calling it twice: once to set the helper, and once to restore it:

```solidity
helper = new HelperToken();
bytes memory savedCode = myToken.code;
vm.etch(myToken, helper.code);
helper.setAmount(...);
vm.etch(myToken, savedCode);
```

What I suggested instead is to have a new cheatcode:
`vm.setHelperContract(myToken, helper);`

and now any call to `helper.setAmount()` will be executed - but on the storage of "myToken"

**Comment by zerosnacks** [comment]
The most common pattern to achieve this is to just wrap the implementation in a mock contract and then operate on the mocked token, never using the underlying implementation. 

```solidity
contact MockToken is MyToken {
    // ...
}
```

and then just use `token = new MockToken();` as if it were the actual token throughout your tests. It is also a safe way of exposing internal functionality to your tests.

>What I suggested instead is to have a new cheatcode: `vm.setHelperContract(myToken, helper)`;

cc @mds1 do you see a use case for something like this?

**Comment by mds1** [comment]
It feels like there are a few ways to accomplish what this proposed cheatcode aims to solve
1. `vm.store`, which you can use with the StdStorage library to remove the need for knowledge on storage layout. It even works with packed slots
2. `vm.etch`, which you can wrap in a helper method to minimize the verbosity of having to restore the original code
3. The mock contract approach suggested by @zerosnacks 

The above approaches also all feel more clear and intuitive to me than the proposed cheat. What exactly is the use case for this proposal that that isn’t solved by the above methods?

> There is a lot of confusion on how to modify storage (e.g. using StdStorage) for testing purposes

What is this confusion specifically? Perhaps resolving that is the correct solution here

**Comment by grandizzy** [comment]
@drortirosh in recent forge version there's `vm.mockFunction` cheatcode, would this help in your scenario?
https://book.getfoundry.sh/cheatcodes/mock-function#description

Thank you!

**Comment by drortirosh** [comment]
yes, it can work.
nice idea.

We can use mockFunction to "add" the "sudo" function to the existing contract.

So the flow above becomes:
```solidity
helper = new HelperToken();
vm.mockFunction(address(myToken), address(helper), abi.encodePacked(HelperToken.setAmount.selector));
// now myToken contract has a "helper" function to force amount
HelperToken(address(myToken)).setAmount(...);
```

**Comment by grandizzy** [comment]
awesome, please close the ticket if you can use that one and no longer need a new cheatcode. Thank you!
