### ISSUE TITLE
Add an example genesis.json file that shows all options

### ISSUE THREAD

**Issue by mshakeg** [foundry-rs/foundry#5953]
### Component

Anvil

### Describe the feature you would like

The foundry book documentation doesn't have an example `genesis.json` file that lists all options that developers can configure. Instead of having to go through the code to figure out these options the documentation should have an example file.

**Comment by mattsse** [comment]
supportive,
do you want to add one?

ref genesis files https://github.com/paradigmxyz/reth/tree/8f3e4a15738d8174d41f4aede5570ecead141a77/crates/primitives/res/genesis

**Comment by mshakeg** [comment]
@mattsse sure, I don't mind, if I have time this weekend

**Comment by AbhinavMir** [comment]
HI @mattsse, seems like the issue was inactive for a while so just made a quick push (I know I am backlogged on other issues but personally needed this haha).
