### ISSUE TITLE
Try catch blocks count as reverts in invariant testing

### ISSUE THREAD

**Issue by 0xTimepunk** [foundry-rs/foundry#5956]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (80df71f 2023-09-27T00:24:52.309432000Z)

### What command(s) is the bug in?

forge test -vvvvv --match-contract InvariantTest

### Operating System

macOS (Apple Silicon)

### Describe the bug

Essentially if a `try` block is ran into during the call made to a function and fails (into the `catch` block) that is being counted as a revert and the invariant test halts (when `fail_on_revert = true`), even though the stack of calls continues.

If this behaviour is expected during the source code (correctly try catching) and the invariant is correctly asserted at the end, is this the expected behaviour of foundry invariant testing (to count as a revert and fail)? 

It seems like it is a bug.

**Comment by vovikhangcdv** [comment]
Hi, I have the same issue. Has it been resolved, or did you find a workaround, @0xTimepunk ?
