### ISSUE TITLE
Test with contracts deployed at fixed addressed.

### ISSUE THREAD

**Issue by DreamerWiz** [foundry-rs/foundry#5958]
### Component

Forge

### Describe the feature you would like

Hi team,

Are there any features that allow me to run the tests with contracts deployed at fixed addresses. So that my test files won't have those dependencies of the contract files. I do not want my test files re-compiled.

Thanks much.

**Comment by mattsse** [comment]
I think you're looking for 

https://book.getfoundry.sh/cheatcodes/etch

**Comment by DreamerWiz** [comment]
> I think you're looking for
> 
> https://book.getfoundry.sh/cheatcodes/etch

Thanks but this is not my want. This is to read the contract's bytecode? For example, I want to deploy contract Foo at address(0x01), so that i can write IFoo interface in the test file. And I can write IFoo targetContract = IFoo(addres(0x01)); So the test contract might not need compiled again.

**Comment by mattsse** [comment]
> I want to deploy contract Foo at address(0x01)

maybe https://book.getfoundry.sh/reference/forge-std/deployCodeTo

**Comment by DreamerWiz** [comment]
/

> > I want to deploy contract Foo at address(0x01)
> 
> maybe https://book.getfoundry.sh/reference/forge-std/deployCodeTo

Yes, it's something like `deployCodeTo`. But the key is that the code of the contract is frequently changed, and i don't want the test file frequently compiled since as per the documentation, the test file has the dependencies of those codes.

**Comment by Evalir** [comment]
Closing, ask unclear / seems compilation related in which we're limited on we can do, and issue is stale.
