### ISSUE TITLE
Support all ether units in to-unit

### ISSUE THREAD

**Issue by bosswissam** [foundry-rs/foundry#5962]
### Component

Cast

### Describe the feature you would like

Hi Foundry Team

First I love all the foundry tools.

Would be great to be able to use `cast to-unit` with the rest of the ether units `kwei`, `mwei`, `microether` and `milliether`. The reason being for easy command-line decimal conversion of certain smart contract calls, e.g. USDC's `balanceOf`, which has a decimals of `6` rather than the standard `18`

**Comment by bosswissam** [comment]
Similarly `from-unit` would be equally useful

**Comment by Evalir** [comment]
marking as `good first issue`, should be relatively easy to add. Albeit, this will also change a bit as we move to alloy in the coming 2 weeks.

**Comment by ruvaag** [comment]
i can take this up - can add some common ones for now (kilo, mega, tera) and then refactor once alloy migration is done?

**Comment by wiggnash** [comment]
heyy , my pull request failed , It would be great if someone could guide me by giving more steps and i will be able to rectify the issue!

**Comment by Evalir** [comment]
Closed with #5978 — sorry I didn't see your answer earlier @ruvaag !

**Comment by bosswissam** [comment]
I noticed this issue was closed and functionality added but would certainly help to fix the `--help` to include the new units
