### ISSUE TITLE
When comparing address with `assertEq` and address is displayed in error, checksum is not included

### ISSUE THREAD

**Issue by winor30** [foundry-rs/foundry#5965]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ddca274 2023-09-30T00:19:15.633264000Z)

### What command(s) is the bug in?

forge test

### Operating System

None

## Description

When comparing two Ethereum addresses using the `assertEq` function in tests, if there is a mismatch and the test fails, the error message displays the addresses without their checksums. However, when the addresses are logged using `console.log`, the checksums are present as expected.

## Code to Reproduce

```sol
    function testEqAddress() public {
        address a = address(0xa37F3eF79651b67FC3b642016C6347745A7545aa);
        address b = address(0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266);
        console.log("a: %s", a);
        console.log("b: %s", b);
        assertEq(a, b);
    }
```

## Test Results
```sh
$ forge test -vv --match-test "testEqAddress"
[⠢] Compiling...
[⠒] Compiling 1 files with 0.8.19
[⠑] Solc 0.8.19 finished in 1.29s
Compiler run successful!

Running 1 test for test/Test.t.sol:Test
[FAIL. Reason: Assertion failed.] testEqAddress() (gas: 18758)
Logs:
  a: 0xa37F3eF79651b67FC3b642016C6347745A7545aa
  b: 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
  Error: a == b not satisfied [address]
    Expected: 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266  
      Actual: 0xa37f3ef79651b67fc3b642016c6347745a7545aa

Test result: FAILED. 0 passed; 1 failed; 0 skipped; finished in 6.31ms

Ran 1 test suites: 0 tests passed, 1 failed, 0 skipped (1 total tests)

Failing tests:
Encountered 1 failing test in test/Test.t.sol:Test
[FAIL. Reason: Assertion failed.] testEqAddress() (gas: 18758)

Encountered a total of 1 failing tests, 0 tests succeeded
```

This behavior can cause confusion as the checksum provides an additional layer of assurance regarding the correctness of an Ethereum address. It would be helpful if the error message retained the checksum to maintain consistency with the console.log output.

**Comment by Evalir** [comment]
Fixed during the alloy ABI migration. Closing.
![Screenshot 2023-12-18 at 13 43 47](https://github.com/foundry-rs/foundry/assets/26014927/fa2e5c25-36cc-43d6-b3dd-31222f8622e6)
