### ISSUE TITLE
What's the operation after all tests are done?

### ISSUE THREAD

**Issue by DreamerWiz** [foundry-rs/foundry#5967]
### Component

Forge

### Describe the feature you would like

<img width="728" alt="image" src="https://github.com/foundry-rs/foundry/assets/139531402/e187ca50-ff84-4fdd-b05d-f9aa417ac6c1">

As shown in the pic, it takes 1.06ms to perform the tests but up to 5 secs to exit the command.

After the tests are all done, the process still needs some seconds to exit. I wonder what's the operation during that time, is there a method to skip this? I expect the tests run as fast as possible.

Thank you.

**Comment by Evalir** [comment]
Closing—this was an issue related to the etherscan identifier hanging up which should've been fixed. Please reopen if not the case
