### ISSUE TITLE
"cast sig" command with specific sequence of characters with_$ returns different results. Why?

### ISSUE THREAD

**Issue by armbull** [foundry-rs/foundry#5970]
**Issue Description:**

When I attempted to decode the value `0x23b872dd` using [this link](https://openchain.xyz/signatures?query=0x23b872dd), I discovered that the function signature `__$_$__$$$$$__$$_$$$_$$__$$___$$(address,address,uint256)` also corresponds to `0x23b872dd`. 

<img width="692" alt="image" src="https://github.com/foundry-rs/book/assets/9640387/0ff0f3de-0a34-4226-a3ef-b21436cfe1d8">

However, when I tried to encode it using the `cast sig` command, I consistently received different results. Here are some examples:

- `cast sig "__$_$__$$$$$__$$_$$$_$$__$$___$$(address,address,uint256)"` resulted in `0xba3f71a9`.
- `cast sig "__$_$__$$$$$__$$_$$$_$$__$$___$$(address,address,uint256)"` resulted in `0x0bd6065e`.
- `cast sig "__$_$__$$$$$__$$_$$$_$$__$$___$$(address,address,uint256)"` resulted in `0x61b8db71`.
- ... and so on.

<img width="514" alt="image" src="https://github.com/foundry-rs/book/assets/9640387/87943cf1-6eb6-46bc-93a0-c3bdee174469">

**Question:**
Why is this happening? I believed that the `cast sig` command should consistently return a static value. Is this a bug in foundry?

**Comment by mattsse** [comment]
you're not escaping the $ variable correctly

try: 

```
cast sig '__$_$__$$$$$__$$_$$$_$$__$$___$$(address,address,uint256)'
0x23b872dd
```

instead which tells your shell that this is a raw string

**Comment by armbull** [comment]
Wow! Can you provide me a link about correctly escaping variable. Now it is very interesting for me)
