### ISSUE TITLE
intrinsic gas too low error after too many transactions

### ISSUE THREAD

**Issue by mshakeg** [foundry-rs/foundry#5984]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (5be158b 2023-10-02T00:23:45.731792000Z)

### What command(s) is the bug in?

eth_sendTransaction

### Operating System

macOS (Apple Silicon)

### Describe the bug

In a hardhat project I'm replaying all transactions on a `UniswapV3Pool` block by block against a local anvil node and after about 73k transactions (constructed from the pool's event logs) are replayed the transaction fails with the following error:
```
ProviderError: intrinsic gas too low
```

Below is the command I'm using to start the anvil node:
```
anvil --prune-history --timestamp 1619820000 --order fifo --code-size-limit 4294967296 -m "test test test test test test test test test test test junk" --gas-limit 100000000000 --gas-price 0 --base-fee 0
```

I've had the `gas-price` and `base-fee` at 1 or omitted from the above command but it made no difference.

The FeeData I'm getting back doesn't seem to be changing and is fixed as follows:
```
{
  gasPrice: 1000000000n,
  maxFeePerGas: 1000000000n,
  maxPriorityFeePerGas: 1000000000n
}
```

It fails when trying to replay the `Swap` event(i.e. the 73780 core event) on [this pool](https://etherscan.io/address/0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640#events) at block 12622017

**Comment by mshakeg** [comment]
bug was in my code

**Comment by DADADAVE80** [comment]
@mshakeg please can you remember the bug?

**Comment by mshakeg** [comment]
@DADADAVE80 don't recall exactly, but I was likely specifying a `gasLimit` for a tx below the intrinsic gas cost(i.e. 21k gas).
