### ISSUE TITLE
Better errors on `transact` cheatcodes

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#5985]
### Component

Forge

### Describe the feature you would like

current example of the transact cheatcode is no longer working and fails with:

`Reason: backend: failed committing transaction: Transaction(NonceTooLow { tx: 1, state: 2 })]`

this is because the example forks off at the block the transaction was mined in.

ref https://github.com/foundry-rs/book/blob/82b99014a448e3bb1d2d2cc5a6e95da5fd401051/src/cheatcodes/transact.md?plain=1#L1

## TODO
map common errors like NonceTooLow and GasPriceLessThanBasefee with additional context and hints for example hint to setNonce or basefee to modify the currently enforced basefee on the fork

tx is executed here:

https://github.com/foundry-rs/foundry/blob/2fc85cb4a2d296b916a413f9f13caadebcf4cf47/crates/evm/src/executor/backend/mod.rs#L1192-L1192

### Additional context

Related: https://github.com/foundry-rs/book/issues/1023

**Comment by azurwastaken** [comment]
I can try this one if possible

**Comment by gr4yha7** [comment]
@mattsse is this still open? maybe i can take it.

**Comment by germankuber** [comment]
I encounter a consistent error when attempting to execute a transaction on my local fork.

**Comment by mattsse** [comment]
@germankuber do you have an example, would love to debug

**Comment by grandizzy** [comment]
addressed in https://github.com/foundry-rs/foundry/pull/9141 now showing

![image](https://github.com/user-attachments/assets/9afe53ee-4c0a-4928-aaa6-1976034a4e8a)
