### ISSUE TITLE
running tx on base result with `Transaction(GasPriceLessThanBaseFee)` error

### ISSUE THREAD

**Issue by wooong210** [foundry-rs/foundry#5987]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (2fc85cb 2023-10-05T00:18:04.223871000Z)

### What command(s) is the bug in?

cast run

### Operating System

macOS (Apple Silicon)

### Describe the bug

```
cast run 0x21563663043751acd37ae493a3346cba400e23e5e85f617b70898bb2aef8dd8c --rpc-url "https://mainnet.base.org"

Executing previous transactions from the block.
Error:
Failed to execute transaction: 0x14124145d321a660c7bc360fb00fe8513c61eb0fb53be6203d77ec310ebf48d2

Context:
- backend: failed while inspecting: Transaction(GasPriceLessThanBasefee)
```

Related Issue & PR: [#5122](https://github.com/foundry-rs/foundry/issues/5122), [#5226](https://github.com/foundry-rs/foundry/pull/5226)

Like arbitrum, base chain has a fixed first transaction that is made from/to specific special addresses. It has gas price 0 which violates the base fee checks in revm.

**Comment by mattsse** [comment]
thanks for flagging,

we're currently not able to trace OP system transaction but we should be able to add support for it now, I'll open an issue for this.
