### ISSUE TITLE
Support replaying Optimism system transactions

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#5992]
### Component

Cast

### Describe the feature you would like

ref https://github.com/foundry-rs/foundry/pull/5991
ref https://github.com/foundry-rs/foundry/issues/5987

revm now supports this via (kinda at least):

https://github.com/bluealloy/revm/blob/main/crates/primitives/src/env.rs#L86C11-L86C11

also would require ethers optimism feature

## TODO
* enable revm optimism feature
* support configuring tx env accordingly:

https://github.com/foundry-rs/foundry/blob/master/crates/evm/src/executor/inspector/cheatcodes/util.rs#L45-L45

**Comment by Evalir** [comment]
this is closeable @mattsse right?

**Comment by zerosnacks** [comment]
> this is closeable @mattsse right?

Bump, are there still parts of this ticket that need to be implemented?

**Comment by mattsse** [comment]
can close
