### ISSUE TITLE
Unexpected error during genering binding for OZ 4.9.3.

### ISSUE THREAD

**Issue by 0xmikko** [foundry-rs/foundry#6010]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (fcae63a 2023-10-08T00:28:16.248807500Z)

### What command(s) is the bug in?

forge bind

### Operating System

Linux

### Describe the bug

Steps to reproduce:
- get OZ via NPM   "@openzeppelin/contracts": "^4.9.3"
- make a contact importing IERC20Permit
- launch ```forge bind```

![image](https://github.com/foundry-rs/foundry/assets/26343374/fcfb250b-2a44-4fc3-8c48-1f86e3200073)

However, if you skip draft-* (draft-ERC20.sol & draft-IERC20.so;) ```forge clean && forge b --skip draft-```
And then run ```forge bind```- it works correct

**Comment by mattsse** [comment]
This looks like a parser bug that appears to be fixed.

wasn't able to reproduce this

**Comment by 0xmikko** [comment]
1. Please, clone `git clone [https://github.com/Gearbox-protocol/core-v3`](https://github.com/Gearbox-protocol/core-v3.git)`
2. `yarn`
3. Run `forge bind`

**Comment by 0xmikko** [comment]
Hi, now it generates new type of error:

Error: 
failed to parse Abigen from file: "/home/mikael/Coding/tt/core-v3/forge-out/draft-IERC20Permit.sol/draft-IERC20Permit.json"
