### ISSUE TITLE
Gas report unexpectedly omits some tests

### ISSUE THREAD

**Issue by QGarchery** [foundry-rs/foundry#6019]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e0722a1 2023-10-10T00:25:42.578508482Z)

### What command(s) is the bug in?

forge test --gas-report

### Operating System

Linux

### Describe the bug

The issue happens when running `forge test --gas-report` on the following file:
https://gist.github.com/QGarchery/b4399a96db810e95453713fca2d816e2

This produces the following ouput:
![Screenshot from 2023-10-10 15-22-25](https://github.com/foundry-rs/foundry/assets/22668539/43171fbd-d125-4a3a-a3ad-db596ae0504e)

Notice the number of calls: only 1 call.

The gas report does not seem to take into account the test `testAggregateTwice`, which can be shown by running the same command again after having deleted this test (which produces the same output).

**Comment by mds1** [comment]
Potentially related to https://github.com/foundry-rs/foundry/issues/2287
