### ISSUE TITLE
Forge Flatten creates duplicate declarations (unable to compile)

### ISSUE THREAD

**Issue by daweth** [foundry-rs/foundry#6022]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (95a93cd 2023-08-25T00:32:44.694202000Z)

### What command(s) is the bug in?

forge flatten

### Operating System

macOS (Apple Silicon)

### Describe the bug

To repro:

https://github.com/balancer/balancer-v2-monorepo/blob/master/pkg/vault/contracts/Vault.sol
Clone the repo and call `forge flatten Vault.sol  > VaultFlattened.sol`

Try to compile `VaultFlattened.sol` in a blank forge repo

<img width="426" alt="Screen Shot 2023-10-10 at 5 22 40 PM" src="https://github.com/foundry-rs/foundry/assets/46637826/26b1ff6f-6f20-4162-bdd3-481330c4b982">

**Comment by mds1** [comment]
There's a lot of `forge flatten` issues that have accrued so aggregating them here, cc @Evalir @mattsse:
- https://github.com/foundry-rs/foundry/issues/3265
- https://github.com/foundry-rs/foundry/issues/4034 (same as this issue)
- https://github.com/foundry-rs/foundry/issues/3678 (same as https://github.com/foundry-rs/foundry/issues/2344)
- https://github.com/foundry-rs/foundry/issues/2545
- https://github.com/foundry-rs/foundry/issues/2378

**Comment by SidestreamColdMelon** [comment]
Hey @mds1, thanks for collecting those issues in one place!

As investigated in https://github.com/foundry-rs/foundry/issues/4034#issuecomment-1709929206, the flattening is actually implemented in the dependency from the same author called [`ethers-rs`](https://github.com/gakonst/ethers-rs/). The issue in that repo which contains description of the problem: https://github.com/gakonst/ethers-rs/issues/2588.

For anyone wanting to contribute, you can start by extending "Reproducible example" [provided in that issue](https://github.com/gakonst/ethers-rs/issues/2588#issue-1885639175) with other use-cases and making it into a PR with a failing test.
