### ISSUE TITLE
The application panicked (crashed).

### ISSUE THREAD

**Issue by MohiniVasisth** [foundry-rs/foundry#6028]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8c1a569 2023-09-19T00:38:40.696654600Z)

### What command(s) is the bug in?

forge script

### Operating System

Windows

### Describe the bug

![image](https://github.com/foundry-rs/foundry/assets/98387326/725e71d5-c5d4-4fd1-96be-41e0105912a5)

**Comment by mattsse** [comment]
hmm, this is thrown when no bytecode was found for the contract

could you please try the full path to the script file like `forge script script/NFT.s.sol`

https://book.getfoundry.sh/reference/forge/forge-script#examples
