### ISSUE TITLE
InvalidFEOpcode when simulating Arbitrum transactions

### ISSUE THREAD

**Issue by impactdni2** [foundry-rs/foundry#6035]
### Component

Cast, Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (5068b7a 2023-10-12T00:22:06.981802088Z)

### What command(s) is the bug in?

cast run --rpc-url https://rpc.ankr.com/arbitrum 0x9aa8ffa054d6e73536dfa34a8e018382bcf597877665c1281e3adb4ec8db6037

### Operating System

Linux

### Describe the bug

Transaction succeeds on Arbitrum mainnet: https://arbiscan.io/tx/0x9aa8ffa054d6e73536dfa34a8e018382bcf597877665c1281e3adb4ec8db6037

But when simulating in anvil/cast, it fails with "InvalidFEOpcode", looks specific to the 0x6c::getCurrentTxL1GasFees() precompile.

Looking at https://book.getfoundry.sh/misc/precompile-registry, it suggests there is a precompile at that address, but not sure why its failing?

**Comment by mattsse** [comment]
this precompile is not supported by the evm foundry uses,

in forge you can mock this like this:

https://github.com/saucepoint/foundry-arbitrum

if you want you can open an issue for arbitrum precompile support on https://github.com/bluealloy/revm
