### ISSUE TITLE
`forge selectors list`

### ISSUE THREAD

**Issue by holic** [foundry-rs/foundry#6038]
### Component

Forge

### Describe the feature you would like

Sometimes I am debugging a local issue where I have an error with function selector and want to locate the function signature via selector, but without uploading these to the registry.

**Comment by mattsse** [comment]
that's a good suggestion, supportive,

do you want to take this on?

**Comment by holic** [comment]
I would but I haven't touched Rust yet and the existing code is scary 🙈

**Comment by holic** [comment]
What I am looking for is just a list of selectors in the contracts built by forge/in the context of the current foundry project. Foundry already has the source and can generate selectors from it. Basically `forge selectors upload` but no upload step, just print them.

**Comment by schroyar** [comment]
@mattsse i think i can take this, if @holic doesnt mind...

any rec resources to read for first issue?

**Comment by schroyar** [comment]
@mattsse @holic does this format looks like what you guys had in mind? if so, ill make final touches and make the pr soon
![image](https://github.com/foundry-rs/foundry/assets/100044502/087dd29d-606c-483e-811d-e413d563012d)

**Comment by mds1** [comment]
This looks great! A few comments:
- I’d remove the colon in the function signatures between the inputs and outputs. That way it matches the format used by cast to compute selectors 
- Do you have an example screenshots using bytes, struct, array, and array of structs inputs, to make sure those all render properly? 
- What about error selectors and event sigs? It would be nice to be able to list those as well

**Comment by schroyar** [comment]
> This looks great! A few comments:
> 
> * I’d remove the colon in the function signatures between the inputs and outputs. That way it matches the format used by cast to compute selectors
> * Do you have an example screenshots using bytes, struct, array, and array of structs inputs, to make sure those all render properly?
> * What about error selectors and event sigs? It would be nice to be able to list those as well

done!

this ss should show how the structs/array of structs is being rendered and how events/errors are now being rendered as well. 

1. is the function rendering ok?
2. should i add identifier in the left? (function/event/error)

![image](https://github.com/foundry-rs/foundry/assets/100044502/f9a01e50-200f-4513-96fe-ba5ad729a866)

**Comment by mds1** [comment]
LGTM! I do think an identifier column that says one of "Function" / "Error" / "Event" would be useful. And using the same table style as `forge inspect` seems reasonable to me

**Comment by schroyar** [comment]
> LGTM! I do think an identifier column that says one of "Function" / "Error" / "Event" would be useful. And using the same table style as `forge inspect` seems reasonable to me

perfect, theres an updated screenshot in the open pr https://github.com/foundry-rs/foundry/pull/6075
