### ISSUE TITLE
Tagged releases change hashes

### ISSUE THREAD

**Issue by RensR** [foundry-rs/foundry#6039]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### Operating System

None

### Describe the bug

Is it by design that the unofficial long term supported released (the ones on the 2nd of each month that stay up) change hashes randomly? Not sure how or why, but we relied on the Oct 2nd release, which is still up, with hash `e0722a10b45859892ec3b998df958a9edc77c202`. Now when I go to that release it's the same, but targets hash `5be158ba6dc7c798a6f032026fe60fc01686b33b`.

Is there any way, before the proper versioning starts, to use Foundry with static versions?

ref #3895 cc @gakonst @3ldarin

**Comment by shazow** [comment]
Ah these changing hashes have also been sporadically breaking the foundry nix flake I maintain: https://github.com/shazow/foundry.nix/issues/25

**Comment by Evalir** [comment]
Sadly right now we don't have versioned releases yet, but we do have monthly pinned binaries. We had some issues with CI back in october which caused these issues—sorry about that!
