### ISSUE TITLE
cast etherscan-source behind the https_proxy raise tunneling error 

### ISSUE THREAD

**Issue by jkryanchou** [foundry-rs/foundry#6044]
### Component

Cast

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

cast 0.2.0 (ec3f9bd 2023-09-19T13:46:42.260032000Z)

### What command(s) is the bug in?

cast etherscan-source 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2

### Operating System

macOS (Apple Silicon)

### Describe the bug

When I ran with the command line `cast etherscan-source <contract_address>` through the `https_proxy` While it raise the error as below

```
Error: 
error sending request for url (https://api.etherscan.io/api/?apikey=<API-KEY>&module=contract&action=getsourcecode&address=0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2): error trying to connect: unexpected eof while tunneling

Context:
- Error #0: error trying to connect: unexpected eof while tunneling
- Error #1: unexpected eof while tunneling
```
 
I wonder whether the `cast` command processing the request through https_proxy still exists some issues on tunneling.
I have met same issue on `forge build` behind the same https_proxy

**Comment by Blaeaea** [comment]
Did you used your API KEY etherscan ?

**Comment by jkryanchou** [comment]
Yeah. I have configured it in foundry.yml. and try many times.

**Comment by jkryanchou** [comment]
While I recently try `cast storage --block <block_number> <contract_address>` with `etherscan` to fetch contract code through http_proxy. it didn't work again.

**Comment by Evalir** [comment]
closing as duplicate—we've received several of these issues, but proxy tunneling can mess with http requests in foundry.

**Comment by jkryanchou** [comment]
@Evalir Is there any solution I could work this out? I have met the issue again and again...
