### ISSUE TITLE
How to mock mapping value in foundry test code?

### ISSUE THREAD

**Issue by linghuccc** [foundry-rs/foundry#6045]
I am writing an NFT project test codes. And in the test, I want to mock owner of a specific NFT (given NFT ID). In the contract code, ownership information is stored in a private mapping - _packedOwnerships. 
![packed](https://github.com/foundry-rs/foundry/assets/59200993/fec1e988-ce04-49df-826c-14d3b9a0d0be)
I already found storage slot of _packedOwnerships.
![memory](https://github.com/foundry-rs/foundry/assets/59200993/996bccd4-fc91-4c12-8242-415a44689a10)
But since it is a mapping, I cannot write value to the storage slot directly, right?

For example, if I want to mock NFT number 1145's owner to be address(0x123), how can I achieve it?

**Comment by Evalir** [comment]
Hey! Have you looked at the [foundry telegram room](https://github.com/foundry-rs/foundry#getting-help) for these questions? There's a lot of people that can help you with this there!

We generally try to keep the issue tracker as clean as we can with actual application errors—so will close this preemptively. Sorry!
