### ISSUE TITLE
feat(anvil) Ability to programatically set chainId

### ISSUE THREAD

**Issue by ape-dev-cs** [foundry-rs/foundry#6046]
### Component

Anvil

### Describe the feature you would like

Given that resetting in anvil can now start a fork (https://github.com/foundry-rs/foundry/pull/5834), it would be useful if anvil provided an RPC method that can change the chain ID, effectively allowing the same anvil instance to fork one chain after another programatically, without a restart. 

I'm currently working on some fork testing functionality in [CoW services](https://github.com/cowprotocol/services/) for which this feature would be useful, as we'll be able to test against multiple forked chains with different IDs without restarting anvil.

Pull request to enable this is here: https://github.com/foundry-rs/foundry/pull/6047

**Comment by Evalir** [comment]
Closed with #6047
