### ISSUE TITLE
Trezor One support

### ISSUE THREAD

**Issue by kargakis** [foundry-rs/foundry#606]
### Component

Forge

### Describe the feature you would like

Currently it seems that Forge only supports Trezor T. 
```
Error: 
   0: Trezor ethereum app requires at least version: ">=2.4.2"
```
Trezor One firmware finally supports both EIP-1559 and EIP-712 which brings it on par with model T in terms of Ethereum ops so it would be nice to get support for it in Forge. 

Not sure if the underlying trezor library already supports One, it seems it's only tested with T.
https://github.com/joshieDo/rust-trezor-api

**Comment by joshieDo** [comment]
> Not sure if the underlying trezor library already supports One, it seems it's only tested with T.

To be honest, I think it should work, but I don't have a trezor one to test it with. 

the necessary changes to test it out would be: 

patch ethers-rs and disable this check:
https://github.com/gakonst/ethers-rs/blob/c6b51e3ae0826f5c5cd1605bfd020a3e5054581a/ethers-signers/src/trezor/app.rs#L75

and run it again with a trezor one.

If it works, I'd just implement an improved version check for the different models

**Comment by kargakis** [comment]
@joshieDo I am trying to build forge with a local version of ethers-rs to test but fail. Any clues on how to get it working?

1. Checkout [ethers-rs#24c39bd32af37f7906bf0d5288a4daa7c83ac095](https://github.com/gakonst/foundry/blob/1be3bab9ff4bfb0c46302718d92b9f901b3c6ce6/Cargo.lock#L1240) locally, side by side with foundry
2. Remove [version check](https://github.com/gakonst/ethers-rs/blob/c6b51e3ae0826f5c5cd1605bfd020a3e5054581a/ethers-signers/src/trezor/app.rs#L80-L82)
3. Uncomment this [build config](https://github.com/gakonst/foundry/blob/1be3bab9ff4bfb0c46302718d92b9f901b3c6ce6/Cargo.toml#L21-L27) in Foundry
4. `cargo build`
```
 Compiling forge v0.1.0 (/home/michalis/code/foundry/forge)
error[E0599]: the method `into_compact_contract` exists for struct `ContractBytecodeSome`, but its trait bounds were not satisfied
   --> cli/src/cmd/run.rs:288:42
    |
288 |         let contract = contract_bytecode.into_compact_contract().unwrap();
    |                                          ^^^^^^^^^^^^^^^^^^^^^ method cannot be called on `ContractBytecodeSome` due to unsatisfied trait bounds
    |
   ::: /home/michalis/code/ethers-rs/ethers-solc/src/artifacts.rs:925:1
    |
925 | pub struct ContractBytecodeSome {
    | -------------------------------
    | |
    | doesn't satisfy `ContractBytecodeSome: Artifact`
    | doesn't satisfy `_: Into<CompactContractBytecode>`
    |
    = note: the following trait bounds were not satisfied:
            `ContractBytecodeSome: Into<CompactContractBytecode>`
            which is required by `ContractBytecodeSome: Artifact`
            `&ContractBytecodeSome: Into<CompactContractBytecode>`
            which is required by `&ContractBytecodeSome: Artifact`
            `&ContractBytecodeSome: Into<CompactContract>`
            which is required by `&ContractBytecodeSome: Artifact`
            `&mut ContractBytecodeSome: Into<CompactContractBytecode>`
            which is required by `&mut ContractBytecodeSome: Artifact`
            `&mut ContractBytecodeSome: Into<CompactContract>`
            which is required by `&mut ContractBytecodeSome: Artifact`

error[E0609]: no field `bin` on type `CompactContractBytecode`
   --> cli/src/cmd/mod.rs:178:22
    |
178 |             artifact.bin.ok_or_else(|| {
    |                      ^^^ unknown field
    |
    = note: available fields are: `abi`, `bytecode`, `deployed_bytecode`

error[E0609]: no field `bin_runtime` on type `CompactContractBytecode`
   --> cli/src/cmd/mod.rs:181:22
    |
181 |             artifact.bin_runtime.ok_or_else(|| {
    |                      ^^^^^^^^^^^ unknown field
    |
    = note: available fields are: `abi`, `bytecode`, `deployed_bytecode`

error[E0609]: no field `bin` on type `CompactContractBytecode`
   --> cli/src/cmd/mod.rs:222:18
    |
222 |         artifact.bin.ok_or_else(|| eyre::Error::msg(format!("bytecode not found for {}", name)))?,
    |                  ^^^ unknown field
    |
    = note: available fields are: `abi`, `bytecode`, `deployed_bytecode`

error[E0609]: no field `bin_runtime` on type `CompactContractBytecode`
   --> cli/src/cmd/mod.rs:224:14
    |
224 |             .bin_runtime
    |              ^^^^^^^^^^^ unknown field
    |
    = note: available fields are: `abi`, `bytecode`, `deployed_bytecode`

warning: unused import: `Artifact`
  --> cli/src/cmd/run.rs:14:44
   |
14 |     prelude::{artifacts::ContractBytecode, Artifact},
   |                                            ^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

Some errors have detailed explanations: E0599, E0609.
For more information about an error, try `rustc --explain E0599`.
warning: `foundry-cli` (bin "forge") generated 1 warning
error: could not compile `foundry-cli` due to 5 previous errors; 1 warning emitted
warning: build failed, waiting for other jobs to finish...
warning: `foundry-cli` (bin "cast") generated 1 warning (1 duplicate)
error: build failed
```

**Comment by joshieDo** [comment]
Can you pull the latest master changes from foundry and try again? I think there was an issue with the master branch recently

**Comment by onbjerg** [comment]
Hey @kargakis! Do you still encounter this error?

**Comment by onbjerg** [comment]
Closing this since I haven't heard back - please let me know if this is still an issue!

**Comment by kargakis** [comment]
Hi @onbjerg, yes, the original error is still an issue:
```
Error: 
Trezor ethereum app requires at least version: ">=2.4.2"
```

**Comment by joshieDo** [comment]
To be honest, I'd close the PR here, since it's a question of compatibility with the underlying trezor lib. 

I do not have a Trezor One to test it out. Maybe they have an emulator for it as well that I can use? In any case, I created an issue, but I don't when I can get to it... https://github.com/joshieDo/rust-trezor-api/issues/4

**Comment by prusnak** [comment]
This is an issue with ethers-rs - opened a PR there: https://github.com/gakonst/ethers-rs/pull/2350

**Comment by prusnak** [comment]
> This is an issue with ethers-rs - opened a PR there: [gakonst/ethers-rs#2350](https://github.com/gakonst/ethers-rs/pull/2350)

This PR has been merged
