### ISSUE TITLE
Remove existing CREATE2 deployments from script

### ISSUE THREAD

**Issue by kopy-kat** [foundry-rs/foundry#6061]
### Component

Forge

### Describe the feature you would like

This feature would allow developers to use solidity-native create2 deployments (by calling `new Contract{salt: salt}()` without needing to build workaround solutions for whether the contract already exists. 

One solution would be that you manually calculate the CREATE2 address, such as through the code below:

```
keccak256(abi.encodePacked(bytes1(0xff), address(this), salt, keccak256(abi.encodePacked(
    type(MyContract).creationCode,
    abi.encode(<constructor params>)
))));
```

Then check if code exists at this address and finally, if no code exists, deploy the contract.

Currently, when trying to create a contract the above way without the workaround, it will fail if the deployment fails. There is an existing issue on the solidity repo (https://github.com/ethereum/solidity/issues/13521) which kind of attempts to achieve the same goal. However, in the context of Solidity it seems like this feature will not be implemented anytime soon (for understandable concerns mentioned on the issue. In the context of a Foundry script, it could make sense to replace these failing creations with the address at which the contract has already been created.

**Comment by zerosnacks** [comment]
Marking as `out of scope`

It is expected that the user handles this in their script if they rely on this functionality

https://book.getfoundry.sh/tutorials/create2-tutorial#create2-factory
