### ISSUE TITLE
`forge coverage` discrepancies

### ISSUE THREAD

**Issue by adaki2004** [foundry-rs/foundry#6064]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (577dae3 2023-09-01T00:41:50.439385000Z)

### What command(s) is the bug in?

forge coverage

### Operating System

None

### Describe the bug

So currently we see discrepancies between 2 of our branches when we are about to export the `forge coverage` reports. On one branch (`main`) it shows somewhat correct numbers, but on the feature branch (`contestable-zkrollup`) it says 0% for most of the contracts.

The forge versions are the same, the dependencies (in `package.json`) looks different but locally i tried to have the same (as `main` - which is the working one) and gave no resolution of the problem.

Let me just get you up to speed how you could re-create the issue quick.

Here is our repo:
`git@github.com:taikoxyz/taiko-mono.git`

In order to replicate it, please create 2 local repositories (so that you can beyond-compare 3 files which are suspicious). One with branch `main` and one with branch `contestable-zkrollup`

1. Clone main: `git clone git@github.com:taikoxyz/taiko-mono.git`
2. Clone feature: `git clone --branch contestable-zkrollup git@github.com:taikoxyz/taiko-mono.git`
3. Enter into the repos' packages/protocol library: `cd taiko-mono/packages/protocol` (on both)
4. Install deps. `pnpm install`
5. `forge coverage --report summary`

You will see different results.

Now, what seemed to be suspicious (beside the versions and dependencies which we ruled out not be the case) to see the test files itself.

So i picked 3 files (`TestBase.sol`, `TaikoL1TestBase.sol`, `TaikoL1.t.sol`) in beyond compare and tried to figure out, why `TaikoL1` tests are on main branch are covered, and on feature branch not.

Obviously there are changes in these 3 files, but not on interface level. We import some additional contracts, or remove other imports, changed the logic inside a function but the function signatures and APIs / inheritance is the same.

Could you please help us figure out what could be the issue, since it is a prio thing for use to see (and prove) coverage ?

**Comment by Evalir** [comment]
We'll be improving forge coverage in 2024—for now we'll close to prune the issue tracker but it's something we plan addressing next year.

**Comment by Evalir** [comment]
We'll be improving forge coverage in 2024—for now we'll close to prune the issue tracker but it's something we plan addressing next year.
