### ISSUE TITLE
Error: Unimplemented feature 

### ISSUE THREAD

**Issue by Raulioui** [foundry-rs/foundry#6065]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0

### What command(s) is the bug in?

forge build

### Operating System

Linux

### Describe the bug

I'm trying to compile my smart contracts and I'm getting this error: Error: Unimplemented feature (/solidity/libsolidity/codegen/CompilerUtils.cpp:419):Encoding type "struct StdInvariant.FuzzInterface memory[] memory" not yet implemented.

**Comment by Zokunei** [comment]
I encountered this issue when compiling a file inheriting from forge-std/Test using solc 0.6.11, but adding `pragma experimental ABIEncoderV2;` to the contract seemed to fix it for me.

**Comment by mattsse** [comment]
yeah this looks like a solc issue with struct encoding

**Comment by mds1** [comment]
Closing since the solution was shared by @Zokunei, but @Raulioui please let us know if you’re still having issues

**Comment by Raulioui** [comment]
@Zokunei Yeah, it works, thanks you :)
