### ISSUE TITLE
Bug(`forge build`): ambiguity in source unit IDs with incremental builds affects source maps

### ISSUE THREAD

**Issue by RaoulSchaffranek** [foundry-rs/foundry#6067]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (490b588 2023-10-19T00:17:56.537546457Z)

### What command(s) is the bug in?

forge build

### Operating System

Linux

### Describe the bug

I observed that source maps exhibit some ambiguity in relation to their source unit IDs during incremental builds. Specifically, upon building a project and adding a new contract within a new file, followed by another build, the new file incorrectly receives a source unit ID of `0` already utilized. Consequently, multiple source units now share an identical ID, creating confusion about which file certain source unit entries within the source maps correspond.

## Steps to Reproduce

1. Initialize a new contract file under `src/First.sol` with the ensuing content:
    ```solidity
    // SPDX-License-Identifier: UNLICENSED
    pragma solidity ^0.8.21;

    contract First {
    }
    ```

2. Execute the command `forge build`.

3. Subsequently, create an additional contract within `src/Second.sol` including the following:
    ```solidity
    // SPDX-License-Identifier: UNLICENSED
    pragma solidity ^0.8.21;

    contract Second {
    }
    ```

4. Run the command `forge build` once again.

5. Proceed by examining the generated output artifacts, specifically `out/First.sol/First.json` and `out/Second.sol/Second.json`, noting that the content is abbreviated for brevity. The contents are as follows:

    ```json
    // First.json
    {
      "bytecode": {
        "sourceMap": "65:18:0:-:0;;;;;;;;;;;;;;;;;;;"
      },
      "deployedBytecode": {
        "sourceMap": "65:18:0:-:0;;;;;"
      },
      "id": 0
    }

    // Second.json
    {
      "bytecode": {
        "sourceMap": "65:19:0:-:0;;;;;;;;;;;;;;;;;;;",
      },
      "deployedBytecode": {
        "sourceMap": "65:19:0:-:0;;;;;",
      },
      "id": 0
    }
    ```

## Current Behavior

The artifacts generated post-build, namely `First.json` and `Second.json`, both possess an `id` attribute at the top level with a value of `0`. This `id` ostensibly represents the source unit ID. However, the source maps within each artifact refer to this identical ID, leading to an ambiguity as to the actual source unit to which the source maps are referring.

## Expected Behavior

Each unique source unit or file should be assigned a distinct source unit ID to prevent overlaps, thereby eliminating any ambiguity in the source maps. This clear distinction is vital for ensuring the source maps accurately reflect their corresponding source units, especially in incremental build environments.

**Comment by zerosnacks** [comment]
cc @klkvr

**Comment by klkvr** [comment]
after https://github.com/foundry-rs/compilers/pull/140 we keep a mapping from build_id to source ids allowing to determine which source given id in source map corresponds to.

It is already used in debugger: https://github.com/foundry-rs/foundry/blob/63fe89cd7af23b4c03980f74a5f1c82783f287a3/crates/common/src/compile.rs#L280

There's not much we can do to ensure unique ids for incremental builds as IDs are getting assigned by solc
