### ISSUE TITLE
Handling of aliases with --verify flag

### ISSUE THREAD

**Issue by rdubois-crypto** [foundry-rs/foundry#6069]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0

### What command(s) is the bug in?

 forge script script/DeployElliptic.s.sol:MyScript --rpc-url https://ethereum-sepolia.blockpi.network/v1/rpc/public --private-key <> --etherscan-api-key <> --verify 

### Operating System

Linux

### Describe the bug

When aliases are used with remappings, the --verify flag fails, with a path error. While the compilation of sources is fine, the verify script is not able to interpret correctly the path to src/ if it is not in the main directory.

In this case remappings is external to the directory where 'forge init' was made, to keep sources separated from the workplace.
toml line:
remappings = ["@solidity/=../../../solidity/src","@external/=../../../solidity/external/"]

![image](https://github.com/foundry-rs/foundry/assets/103030189/2e090931-219f-4e91-a6a2-088ad418aef0)

**Comment by Evalir** [comment]
Closing as duplicate
