### ISSUE TITLE
parse $PRIVATE_KEY as type `uint256`: digit 10 is out of range for base 10

### ISSUE THREAD

**Issue by billchen-818** [foundry-rs/foundry#6070]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (619f3c5 2023-10-20T00:17:29.281153000Z)

### What command(s) is the bug in?

forge script script/Counter.s.sol:CounterScript

### Operating System

macOS (Apple Silicon)

### Describe the bug

I use a script to deploy the contract and write the deployer's private key (a hexadecimal string, 64 bits in length) in the .env environment variable.When executing the script, reade the  PRIVATE_KEY and converte it  to uint256,
`
uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");
`

An error will be reported,
`
Failed to parse $PRIVATE_KEY as type `uint256`: digit 10 is out of range for base 10
`

**Comment by billchen-818** [comment]
I understand, the private key needs to be prefixed with '0x'.

**Comment by billchen-818** [comment]
This is not a bug, the private key needs to be prefixed with '0x'

**Comment by mattsse** [comment]
we'll add a fallback for 0x again shortly and improve error message, #6041

but it's recommended to use 0x prefix if it's hex

**Comment by Chinwuba22** [comment]
> This is not a bug, the private key needs to be prefixed with '0x'

thanks this helped.
