### ISSUE TITLE
Foundry to generate contract ABI and latest deployment address, without other data

### ISSUE THREAD

**Issue by AuroraLantean** [foundry-rs/foundry#6071]
### Component

Forge

### Describe the feature you would like

I know `forge build` can generate ABI files inside the `out` folder, 

but they are quite large for Frontend to use them. Because those files have lots of other data within them.

And they do not contain the latest deployment addresses.

Is there a way for Foundry to generate such ABI and deployment address in json formats for each of selected contracts?

**Comment by AuroraLantean** [comment]
I did that with Bun / NodeJs and the result looks like:
```
[
 {
    contractName: "ERC721",
    contractAddress: "0xabc123...",
    abi: [ ... ],
}, 
{ ... }, { ... }, 
]
```

**Comment by zerosnacks** [comment]
You can use `forge inspect <CONTRACT> abi` to get the ABI of any contract

To parse the `broadcast` JSON files I recommend `jq` to extract what you need

For now marking as `not planned`

**Comment by maikelordaz** [comment]
> I did that with Bun / NodeJs and the result looks like:
> 
> ```
> [
>  {
>     contractName: "ERC721",
>     contractAddress: "0xabc123...",
>     abi: [ ... ],
> }, 
> { ... }, { ... }, 
> ]
> ```

Can you provide an example?

**Comment by pstephenwille** [comment]
> You can use `forge inspect <CONTRACT> abi` to get the ABI of any contract
> 
> To parse the `broadcast` JSON files I recommend `jq` to extract what you need
> 
> For now marking as `not planned`

newbie here but this sounds a bit hacky and clumsy.  Having to take on another dependency (JQ) for what I understand is a very common use case, seems like a feature miss to me.
