### ISSUE TITLE
Anvil allows execution of invalid signed transactions

### ISSUE THREAD

**Issue by k-xo** [foundry-rs/foundry#6072]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

0.2.0

### Operating System

macOS (Apple Silicon)

### Describe the bug

Anvil seemingly allows for the execution of invalid transactions. I'm able to create an invalid transaction, by having a signature on a transaction where the `s` value is greater than `n/2` these transaction should be invalid https://github.com/ethereum/EIPs/blob/master/EIPS/eip-2.md#specification, so even though the signature recovers to the correct / address and public key it shouldn't be able to execute. Here's the decoded version of the signed transaction -- https://rawtxdecode.in/?rawTx=0x02f873827a6980849184e72a849184e72a82753094b89ff4e9ad6b33f69153fa710f9849f51712eec4872386f26fc1000080c080a02b3416d8559c481663227484c8f7dea8705b6e1109d67bb3d0d760ef3b271503a0ec9ca501276589e81c0381db75e978cba19497bc0c15670df49c3a9ef411d70c.

and also a gist of how I was executing the transaction -- https://gist.github.com/k-xo/670520238fbb1c1b950b3bf10211f6be

and some of the anvil and script logs
<img width="746" alt="Screenshot 2023-10-20 at 17 57 49" src="https://github.com/foundry-rs/foundry/assets/32230412/0118d5cf-9cf2-4986-b5ea-9c6f6e9b0d3a">
<img width="529" alt="Screenshot 2023-10-20 at 17 56 59" src="https://github.com/foundry-rs/foundry/assets/32230412/6cd650ad-fb12-421b-9757-3d1e0c62e165">

**Comment by mattsse** [comment]
paging @prestwich 

we're using this:

https://github.com/gakonst/ethers-rs/blob/d25351436378967e4cf3cc4e1abdb6c4f7ca073d/ethers-core/src/types/signature.rs#L87-L94

from here:

https://github.com/foundry-rs/foundry/blob/619f3c56302b5a665164002cb98263cd9812e4d5/crates/anvil/core/src/eth/transaction/mod.rs#L1066-L1074

**Comment by prestwich** [comment]
That recover function will accurately recover signers, but will not ensure that the signature is canonical and consensus acceptable.

You need to invoke [`signature.normalize_s()`](https://docs.rs/ecdsa/0.16.6/ecdsa/struct.Signature.html#method.normalize_s) and check the result of the operation is `None`

Adding this should remediate:
```
if  s.normalize_s().is_some() {
    return Err(Signature::RecoveryError);
}
```

**Comment by Evalir** [comment]
Closing, this was fixed in ethers and bumped here
