### ISSUE TITLE
GLIB_2.27 not found

### ISSUE THREAD

**Issue by 0xfourzerofour** [foundry-rs/foundry#6088]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

NA - cannot run

### What command(s) is the bug in?

foundryup

### Operating System

Linux

### Describe the bug

I have seen this issue a few times in the past on this repo however most of the fixes that I have seen are to use `ubuntu-latest` instead of a specific version. I have tried both and am getting the same issue however I am not calling this directly within a github action.

I am using cross-rs to have both x86 and arm64 builds on linux to be deployed to dockerhhub.

Here are the relevant files that are causing the issues.

https://github.com/alchemyplatform/rundler/blob/josh/release-pipeline/.github/workflows/docker-release.yaml
https://github.com/alchemyplatform/rundler/blob/josh/release-pipeline/Cross.toml
https://github.com/alchemyplatform/rundler/blob/josh/release-pipeline/Makefile

We use forge in a build.rs file in the rundler project for autogenerated bindings to solidity which is why it needs to be in the image and not just in the actions runtime 

```
#5 11.59 /root/.foundry/bin/forge: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /root/.foundry/bin/forge)
#5 11.59 /root/.foundry/bin/forge: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /root/.foundry/bin/forge)
#5 11.59 /root/.foundry/bin/forge: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.29' not found (required by /root/.foundry/bin/forge)
#5 11.59 /root/.foundry/bin/forge: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /root/.foundry/bin/forge)
#5 11.59 /root/.foundry/bin/forge: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /root/.foundry/bin/forge)
#5 11.59 /root/.foundry/bin/forge: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /root/.foundry/bin/forge)
#5 11.59 foundryup: command failed: /root/.foundry/bin/forge --version
#5 11.59 foundryup: installed - 

```

**Comment by mattsse** [comment]
yeah something weird happens on ubuntu-latest hence we're still pinning to ubuntu-20 in CI

I was never able to figure out what exactly... or how to fix, everytime we tried to migrate to ubuntu-latest we got this report

maybe this https://github.com/alchemyplatform/rundler/blob/d9365bcc39ca52629bb82417e3e09b2669766e6c/Dockerfile.cross#L5

**Comment by mattsse** [comment]
maybe this is useful as reference

https://github.com/foundry-rs/foundry/blob/master/Dockerfile

**Comment by 0xfourzerofour** [comment]
@mattsse yeh I tried that but then it gave me the same error but for cross-rs where GLIBC_2.33 is not found. 

Such a strange bug, I will try to dig into it deep tomorrow and see if I can find anything, it much help out the foundry project if I can sort it out. I might have to do a PR for 4337 opcode tracing in foundry soon so could loop it in the PR

**Comment by 0xfourzerofour** [comment]
I believe this is related to the default images that the cross-rs library is using. I overrode the default image and used debian bookworm and the glib issues did not happen. However it did lead to some other issues that I have not dug too deep into yet

**Comment by Evalir** [comment]
Closing, this is a highly specific user error
