### ISSUE TITLE
feat(`forge fmt`): Option for changing `if`/`else` clause format

### ISSUE THREAD

**Issue by Tudmotu** [foundry-rs/foundry#6090]
### Component

Forge

### Describe the feature you would like

Today `forge fmt` automatically "cuddles" elses:
```solidity
if (true) {
  // ...
} else {
  // ...
}
```

I could not find a way to change this.

While this is a common format there are two other common formats:
```solidity
if (true) {
  // ...
}
else {
  // ...
}
```
```solidity
if (true)
{
  // ...
}
else
{
  // ...
}
```

Could we maybe add a new `fmt` option, e.g. `if_braces_style` ?

**Comment by Evalir** [comment]
Closing as won't fix for now. While it would be nice to have these we currently don't have the bandwith atm.
