### ISSUE TITLE
Anvil: First block mined after a snapshot revert does not increase its block time

### ISSUE THREAD

**Issue by simon-saliba** [foundry-rs/foundry#6096]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

0.2.0

### Operating System

None

### Describe the bug

Reproduction steps from scratch: 
- Fork at any block height n
- Take snapshot
- Mine next block and get its timestamp
- Revert to snapshot
- Mine again and get latest block timestamp
- Check that timestamps don't match

You can also reproduce by removing this line and running the corresponding test: https://github.com/foundry-rs/foundry/blob/e82f5bd0380a5990065cf1ea43a4ce4fb6648271/crates/anvil/tests/it/fork.rs#L691

**Comment by mattsse** [comment]
just to summarize:

the bug is, we're setting the next block time stamp to the initial block but it should be the next?

**Comment by simon-saliba** [comment]
I suspect that the bug is coming from this line: https://github.com/foundry-rs/foundry/blob/e82f5bd0380a5990065cf1ea43a4ce4fb6648271/crates/anvil/src/eth/backend/mem/mod.rs#L664C73-L664C73

If my analysis is correct, the `reset_time` should be equal `block.timestamp`.

**Comment by mattsse** [comment]
ah I see,

yeah since we're reverting to the targeted block, the timestamp of the next block after (revert + 1) is wrong here?

**Comment by simon-saliba** [comment]
Yes, the block (revert+1) ends up having the same block timestamp as the block we reverted to (revert), while it should have been incremented by one. 

Not sure why `reset_time` is `block.timestamp - 1` (one less that the snapshot block timestamp) in the line I linked previously. For me it should only be equal to the snapshot block timestamp
