### ISSUE TITLE
Feature Request: Storage Layout

### ISSUE THREAD

**Issue by transmissions11** [foundry-rs/foundry#610]
### Component

Forge

### Describe the feature you would like

The ability to print out a contract's storage layout, accounting for packed slots, etc.

**Comment by transmissions11** [comment]
similar to slither's `variable-order` printer:

https://github.com/crytic/slither/wiki/Printer-documentation#variable-order

**Comment by onbjerg** [comment]
cc @abigger87 is this something that `forge inspect` can/could do, given it is in the solc output? https://docs.soliditylang.org/en/v0.8.12/using-the-compiler.html#output-description

**Comment by mds1** [comment]
`forge inspect` will print the storage layout as outputted by the compiler, but I think the scope of this issue might be for a more user friendly display similar to slither's printer? Maybe we add a `--table` or `--pretty` option to `forge inspect` and for `mode`s that support it we display a more human-friendly format. Potential storage layout pretty print:

```
$ forge inspect <contract> storage-layout --pretty
+----------+---------+-------+--------+
|     Name |   Type  | Slot  | Offset |
+----------+---------+-------+--------+
| varA     | uint256 | 0     | 0      |
| varB     | uint256 | 1     | 0      |
+----------+---------+-------+--------+
```

**Comment by transmissions11** [comment]
+1 on the above

inspect already provides all the data we need, just need a lil pretty printed chart :D
