### ISSUE TITLE
`vm.expectRevert` sets a test passed with revert inside

### ISSUE THREAD

**Issue by madlabman** [foundry-rs/foundry#6109]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (950d863 2023-10-25T11:49:15.075206396Z)

### Operating System

Linux

### Describe the bug

```solidity
function test_minimal() public {
    assertTrue(false);
    vm.expectRevert();
}

// [FAIL. Reason: Call did not revert as expected]
```

Given the toy example above, one may expect something like `Assertion failed` because of  `assertTrue(false);` but instead `Call did not revert as expected` emitted.

```solidity
function test_minimal() public {
    vm.expectRevert();
    _itReverts();
    this._call();
}

function _itReverts() internal {
    // Arithmetic over/underflow
    type(uint256).max + 1;
}

function _call() external {
    // nop
}

// [PASS] test_minimal() (gas: 3178)
```

Given another example, one may expect something like `[FAIL. Reason: Arithmetic over/underflow]` but instead it looks like the `vm.expectRevert` inspects the test function call itself (just my guess) and silently passes the test. With no `this._call();` it works in the same way.

**Comment by skhomuti** [comment]
It seems in #5728 had been given some clarifications especially for the 2nd example

I've checked on this branch and noticed that the following example is not fixed yet
not sure if it's a known but or not, but I'd expect `[FAIL. Reason: Assertion failed.] ` in this case
```
function test_minimal() public {
    reverter = new Reverter();
    assertTrue(false);

    vm.expectRevert();
    reverter.doNotRevert();
}
[FAIL. Reason: Call did not revert as expected]
```

**Comment by Evalir** [comment]
The logic around `expect*` can be tricky and the community seems to have a divided opinion on how this should work, along with test assertion quirks that are foundry specific that cause this specific issue. We'll be putting up a spec on how these cheatcodes should work in V1 for everyone to discuss. Will close this for now—we acknowledge this is an issue, but we can't work this out without a formal spec.
