### ISSUE TITLE
Fuzz testing with `bytes4`, `bytes8`, `bytes12` params reverting instantly

### ISSUE THREAD

**Issue by hexcowboy** [foundry-rs/foundry#6115]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9fd44a7 2023-10-26T00:23:32.602895000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

Running any test with `bytes4`, `bytes8`, or `bytes12` params instantly reverts the test.

To reproduce, just do a `forge init` and add any of these types to the sample `test/Counter.t.sol` like so:

```sol
    function testFuzz_SetNumber(uint256 x, bytes12 test) public {
        counter.setNumber(x);
        assertEq(counter.number(), x);
    }
```

Running the test, you will see the issue:

```bash
➜ forge test -vvvv --match-test testFuzz_SetNumber
[⠢] Compiling...
No files changed, compilation skipped

Running 1 test for test/Counter.t.sol:CounterTest
[FAIL. Reason: EvmError: Revert Counterexample: calldata=0x0xdd274b79000000000000000000000000000000000000000000000000000000000000004b0000000000000000000000000002a06c7c48e3a5000000000000000000000000, args=[75, 0x0000000000000000000000000002a06c7c48e3a5000000000000000000000000]] testFuzz_SetNumber(uint256,bytes12) (runs: 18, μ: 27340, ~: 28446)
Traces:
  [106719] CounterTest::setUp() 
    ├─ [49499] → new Counter@0x5615dEB798BB3E4dFa0139dFa1b3D433Cc23b72f
    │   └─ ← 247 bytes of code
    ├─ [2390] Counter::setNumber(0) 
    │   └─ ← ()
    └─ ← ()

  [297] CounterTest::testFuzz_SetNumber(75, 0x0000000000000000000000000002a06c7c48e3a5000000000000000000000000) 
    └─ ← "EvmError: Revert"

Test result: FAILED. 0 passed; 1 failed; 0 skipped; finished in 7.20ms

**Comment by hexcowboy** [comment]
https://t.me/foundry_support/45713

**Comment by thedavidmeister** [comment]
i think i'm seeing the same issue with `bytes1`

current workaround is to set the fuzzer to produce a `uint8` then cast it to bytes in the test
