### ISSUE TITLE
perf(anvil): execution time per transaction increases with number of transactions

### ISSUE THREAD

**Issue by 09tangriro** [foundry-rs/foundry#6124]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (dbfd8d9 2023-09-06T13:18:18.344860000Z)

### Operating System

macOS (Apple Silicon)

### Describe the bug

Hi everyone 👋

We're building a smart contract simulation platform on top of `anvil` and we noticed that the time to process a transaction increases linearly with the number of transactions processed (seems to be roughly O(n)). This only happens with strict transactions that change the state of the blockchain, so is not an issue for read-only contract calls. I am running the following command to create a local development network (no forking):
```
anvil --accounts 1 --balance 10000000000000000000 --chain-id 31337 --port {port} --base-fee 0 --disable-block-gas-limit --ipc /tmp/anvil_{port}.ipc --prune-history --order fifo --transaction-block-keeper 64
```
Please see the graphs below for proof and issue #6017 for more discussion on a parallel issue.
![timing_contract_transact_exactInputSingle](https://github.com/foundry-rs/foundry/assets/47002898/95f6692d-dac8-4772-90c1-3a7ae275468c)
![timing_contract_transact_increaseLiquidity](https://github.com/foundry-rs/foundry/assets/47002898/a3c73057-8bd3-4b9f-8baf-52f14a90532f)
![timing_contract_transact_burn](https://github.com/foundry-rs/foundry/assets/47002898/cfea9842-d0e6-43e8-aca7-344e91305757)

Ideally, I think it would be better if this was O(1) constant transaction time. Let me know what you think, I suspect there must be an O(n) lookup datastructure somewhere in the transact code 🤔

**Comment by mattsse** [comment]
> (seems to be roughly O(n))

this makes sense, ref #6017

because the historic state is solved by simply cloning the entire state which is likely responsible for this, because we only have in memory state and no DB

I need to check how --prune-history is implemented and if we can add an option to prevent the expensive clones entirely

**Comment by grandizzy** [comment]
@09tangriro I suspect this is related to same testing as in https://github.com/foundry-rs/foundry/issues/6017  is ok to close it too?
Thank you!

**Comment by 09tangriro** [comment]
Sure let's close it :)
