### ISSUE TITLE
Broken forge create

### ISSUE THREAD

**Issue by bosswissam** [foundry-rs/foundry#6132]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

above 5be158b

### What command(s) is the bug in?

forge create

### Operating System

None

### Describe the bug

Hi

I have been using forge create with no problems the last few days. Today, after running `foundryup`, it started created bad contracts with empty bytecode.

I went to the nightly builds and kept trying different builds until it worked again. It finally worked at build `5be158b`. I feel like it has been broken in the nightly builds since, but it takes a long time to install each so I could not verify each of them (some of them even failed to install)

**Comment by Evalir** [comment]
Closed with #6134
