### ISSUE TITLE
Cast fails to parse signature after update

### ISSUE THREAD

**Issue by karlb** [foundry-rs/foundry#6135]
After going from `cast 0.2.0 (ba6c851 2023-10-23T00:25:30.528411000Z)` to `cast 0.2.0 (93f64c7 2023-10-27T00:23:01.290541000Z)`, I can't use some previously working signatures with `cast send` anymore.

Errors:
```
$ cast send --private-key 0x2771aff413cac48d9f8c114fabddd9195a2129f3c2c436caa07e27bb7f58ead5 0xefb84935239dacdecf7c5ba76d8de40b077b7b33 'function addOracle(address token, address oracleAddress) external' 0x000000000000000000000000000000000000ce16 0x42cf1bbc38BaAA3c4898ce8790e21eD2738c6A4a
parser error:
function addOracle(address token, address oracleAddress) external
          ^
expected `(`
```
```
$ cast send --private-key 0x2771aff413cac48d9f8c114fabddd9195a2129f3c2c436caa07e27bb7f58ead5 0x471ece3750da237f93b8e339c536989b8978a438 'function transfer(address to, uint256 value) external returns (bool)' 0x000000000000000000000000000000000000dEaD 100
parser error:
function transfer(address to, uint256 value) external returns (bool)
          ^
expected `(`
```
Since these worked before and I don't see anything wrong with the signatures, I assume this is a regression in cast.

OS: macOS 14.0 23A344

**Comment by Evalir** [comment]
Try without `function `

**Comment by karlb** [comment]
Removing both `function` and `external` avoids the problem, thanks! Could I have known this change from some changelog? I looked for signature handling changes in https://github.com/foundry-rs/foundry/releases and did not find anything.

While the new behaviour is acceptable, I still prefer the old one where I could blindly paste the signature from the solidity code.

**Comment by mattsse** [comment]
since this was a breaking change @Evalir 
can we support the previous again?
