### ISSUE TITLE
Anvil reverts with invalid FE opcode even though the opcode is not run.

### ISSUE THREAD

**Issue by thekevinbrown** [foundry-rs/foundry#6138]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

anvil 0.2.0 (5be158b 2023-10-02T00:23:45.472182000Z)

### What command(s) is the bug in?

Running specific smart contract code

### Operating System

macOS (Apple Silicon)

### Describe the bug

I'm using cannon to develop some contracts. Cannon uses Anvil to run them.

When I run the code on the Hardhat network, everything succeeds. When I run it on Anvil, I get an `InvalidFEOpcode` error even though the FE Opcode is not being run. Full error:
```
 Error: transaction reverted in contract unknown: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":53,\"error\":{\"code\":-32603,\"message\":\"EVM error InvalidFEOpcode\"}}", error={"code":-32603}, requestBody="{\"method\":\"eth_estimateGas\",\"params\":[{\"type\":\"0x2\",\"maxFeePerGas\":\"0xd09dc300\",\"maxPriorityFeePerGas\":\"0x59682f00\",\"from\":\"0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266\",\"to\":\"0xe661b3f15d0310af885f4d5c6482c0b5a8c0523d\",\"data\":\"0xd7513467000000000000000000000000000000000000000000000000000000000000002000000000000000000000000070997970c51812dc3a010c7d01b50e0d17dc79c8000000000000000000000000f275321e2e6a907f9113f037ef9ecc22b4dd4ff4000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000f42405f63408b72155b13a706288900cf7bc9ad629958e4992a0087324937e2affbfa00000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000001200000000000000000000000000000000000000000000000000000000000000004cfae3217000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000041da67e60a74f3985567c34a9a75a40f78bdc0c2924f024a7289639a776b84a7ec7e24181439b2166af1274da4127e41ce452f2add4a77692aa1c35727ed8a77c51b00000000000000000000000000000000000000000000000000000000000000\"}],\"id\":53,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="http://127.0.0.1:8545", code=SERVER_ERROR, version=web/5.7.1)
```

## Reproduction Repo

Including a more in-depth explanation is here: https://github.com/CoinageCrypto/anvil-revert-issue

**Comment by mattsse** [comment]
thanks for flagging 

https://github.com/foundry-rs/foundry/pull/6140 should fix it

I was unable to run the example, unclear how I can run this against a local anvil instance, only got errors with `pnpm t -- --network hardhat`

```
pnpm t -- --network hardhat                                                                                    

> synthetix-sandbox-trading-example@0.0.1 test /Users/Matthias/git/rust/forge-repros/anvil-revert-issue
> hardhat test "--network" "hardhat"

Downloading compiler 0.8.21
Error HH502: Couldn't download compiler version list. Please check your internet connection and try again.

For more info go to https://hardhat.org/HH502 or run Hardhat with --show-stack-traces
 ELIFECYCLE  Test failed. See above for more details.
```

could you perhaps check the PR directly?

**Comment by noisekit** [comment]
> Downloading compiler 0.8.21
> Error HH502: Couldn't download compiler version list. Please check your internet connection and try again.

We've noticed today that compiler cannot be downloaded, that looks like something on hardhat end perhaps?

**Comment by Evalir** [comment]
Yep @noisekit this looks hardhat related—please let us know once you get to test!

**Comment by noisekit** [comment]
> Yep @noisekit this looks hardhat related—please let us know once you get to test!

I personally did not have this issue today because all these compilers are already cached on my dev machine (and in CI).
