### ISSUE TITLE
`internal error: entered unreachable code: We should never have decoded calldata for contract creations`

### ISSUE THREAD

**Issue by pcaversaccio** [foundry-rs/foundry#6139]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

`forge 0.2.0 (93f64c7 2023-10-27T00:24:49.496418315Z)`

### What command(s) is the bug in?

`forge test`

### Operating System

Linux

### Describe the bug

Multiple times during CI runs I face the following error ([example](https://github.com/pcaversaccio/createx/actions/runs/6664854666/job/18113729646?pr=18#step:12:5118))

```bash
Running 1 test for test/invariants/CreateX_Invariants.t.sol:CreateX_Invariants
[PASS] statefulFuzz_EtherBalance() (runs: 5000, calls: 75000, reverts: 74998)
The application panicked (crashed).
Message:  internal error: entered unreachable code: We should never have decoded calldata for contract creations
Location: crates/evm/traces/src/lib.rs:262
```

I'm doing an invariant test on my create factory [here](https://github.com/pcaversaccio/createx/blob/create3-tests/test/invariants/CreateX_Invariants.t.sol). The issue as it seems is that for certain `initCode` inputs (i.e. decoded calldata) it panics. It's getting pretty annoying lately tbh. Any way to disable this in my test environment?

**Comment by mattsse** [comment]
@Evalir what changed with trace decoding?

https://github.com/foundry-rs/foundry/blob/cc760aac6e971ecc89b0f90efbb38f9bb49a672d/crates/evm/traces/src/lib.rs#L262-L262

this unreachable doesn't look sound to me

**Comment by Evalir** [comment]
@mattsse we'll have to triage—this unreachable was already there from the previous implementation. Possible that the issue might come from another place

**Comment by mattsse** [comment]
looks like we're decoding init code now, so I'm removing the unreachable

https://github.com/foundry-rs/foundry/pull/6141

this shouldn't be there anyway

**Comment by mattsse** [comment]
any other issues we need to fix asap @pcaversaccio ? :)

sorry for the inconveniences lately, lots of moving parts atm -.-

**Comment by mattsse** [comment]
triggering new release once merged

**Comment by pcaversaccio** [comment]
> any other issues we need to fix asap @pcaversaccio ? :)
> 
> sorry for the inconveniences lately, lots of moving parts atm -.-

Well you might look at a similar issue I reported some months ago: https://github.com/foundry-rs/foundry/issues/5629. Very weird behaviour.

**Comment by pcaversaccio** [comment]
> > any other issues we need to fix asap @pcaversaccio ? :)
> > sorry for the inconveniences lately, lots of moving parts atm -.-
> 
> Well you might look at a similar issue I reported some months ago: #5629. Very weird behaviour.

See the debugging info I added there.

**Comment by mattsse** [comment]
okay that's the same bug, yeah.

so the bug here is actually pretty simple that we just didn't handle the case where we were able to decode the constructor calldata

this panic is now removed with #5629, so no more crashes here

**Comment by pcaversaccio** [comment]
> okay that's the same bug, yeah.
> 
> so the bug here is actually pretty simple that we just didn't handle the case where we were able to decode the constructor calldata
> 
> this panic is now removed with #5629, so no more crashes here

you mean https://github.com/foundry-rs/foundry/pull/6141

**Comment by Evalir** [comment]
Amazing! Is this closeable @pcaversaccio ?

**Comment by pcaversaccio** [comment]
> Amazing! Is this closeable @pcaversaccio ?

one sec -currently running my CI with the latest release

**Comment by pcaversaccio** [comment]
LGTM - thx for fixing.
