### ISSUE TITLE
forge test can't find the contract which is not in the same folder as foundry.toml and test/test.sol

### ISSUE THREAD

**Issue by jiajieey** [foundry-rs/foundry#6142]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (58a2729 2023-05-15T00:04:23.550925000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

My contract file is in `/Users/j/Library/CloudStorage/OneDrive/n/nd/blockchain_assets/contracts/p/contract.sol`.
My test file is in `/Users/j/Library/CloudStorage/OneDrive/n/nd/contract_unit_tests/p/test/contract_t.sol`
In the test file, I import contract file using:
`import "../../../blockchain_assets/contracts/p/contract.sol";`
When i run `forge test`,
I get error:
`Source "blockchain_assets/contracts/p/t.sol" not found: File not found. Searched the following locations: "/Users/j/Library/CloudStorage/OneDrive/n/nd/contract_unit_tests/p".
 --> test/plonk_vk_jellyfish_t.sol:6:1:
  |
6 | import "../../../blockchain_assets/contracts/p/contract.sol";`
But if i use the full path of contract.sol, i won't get this error.

I also checked fs-permission in `/Users/j/Library/CloudStorage/OneDrive/n/nd/contract_unit_tests/p/foundry.toml`, 
I have
```
 fs_permissions = [{ access = "read", path = "./"},
{ access = "read", path = "../../blockchain_assets/contracts/p/"}]
```
, if I understand it correctly, this should give forge permission to read all files in blockchain_assets/contracts/p.

The problem is that 
when contract sits in  ./nd/blockchain_assets/contracts/p/contract.sol, 
test is in ./nd/contract_unit_tests/p/test/contract_t.sol
foundry.toml is in ./nd/contract_unit_tests/p/foundry.toml, 
how can I import contract in the test.sol with relative path?
Thank you!

**Comment by Evalir** [comment]
This is more of a question than a bug—you have a custom setup for contract locations and need to set up your remappings accordingly. We'd recommend not deviating much from the default layout as it can make your submodules ugly.

For more info on this, let's please take the convo to the foundry TG chat, thank you! 🙏
