### ISSUE TITLE
builder error: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by 0xPetra** [foundry-rs/foundry#6145]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

0.2.0 (62e3a84 2023-10-27T09:58:50.337034000Z)

### What command(s) is the bug in?

cast send

### Operating System

macOS (Apple Silicon)

### Describe the bug

When I run `cast send ...` I get this error: 

```
builder error: No such file or directory (os error 2)
```

Other commands, such as `cast wallet` and `cast to-wei` work well. 

I'm on a Macbook M1 Silicon running on Ventura 13.1. I tried installing `z3` as suggested to solve the `.solc` error, with no luck. 

What are the recommendations to debug further?

**Comment by mattsse** [comment]
can you post the full command?
or ideally a repro

**Comment by 0xPetra** [comment]
Sure, I didn't post the full command since none would work:

```cast send --private-key [PRIVATE-KEY] vitalik.eth --value 0.1ether```

Also, using `cast send` won't show help info with commands (as it does with other incomplete commands). It will still throw the error.

<img width="436" alt="Screenshot 2023-10-27 at 18 26 55" src="https://github.com/foundry-rs/foundry/assets/20055787/97ec83cc-090a-499a-9d76-94c1d471750d">

**Comment by mattsse** [comment]
hmm, cannot reproduce on 
```
cast --version                                                                                                
cast 0.2.0 (70d0022 2023-10-27T16:41:44.139091000Z)`
```

```
cast send --private-key ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 0x70997970C51812dc3A010C7d01b50e0d17dc79C8 --value 0.1ether

blockHash               0x87baf8ff5d78c11284de4267a37ab22937fdb4b00301313cdb5efe99b69ba384
blockNumber             3
...
transactionHash         0x86cfc278e133f3b800ebe05571b984db4af07c796ee88256f5da694a881f723e
```

**Comment by 0x0OZ** [comment]
@mattsse I am getting a bit similar error when I try to create a wallet using cast to a keystore file
![image](https://github.com/foundry-rs/foundry/assets/52073989/9c8f042c-e2a2-41c0-a6a2-0157c0aaeb1a)
according the help it is supposed to store keys into a keystore file named test but it doesn't

I am using archlinux
