### ISSUE TITLE
Forge create parse tuple error

### ISSUE THREAD

**Issue by minghinmatthewlam** [foundry-rs/foundry#6151]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

nightly-70d00222c2ef74fc484b8d98c5705d131ab31871

### What command(s) is the bug in?

forge create --private-key $key --constructor_args "array of tuples" --rpc-url $url $contract

### Operating System

Linux

### Describe the bug

Trying to use `forge create` to deploy a contract onto a local network through rpc-url. Was working previously, and now without changes to the contract or other parts of the PR, getting following error in CI. The contract being deployed takes in an array of structs, and our script passes in array of tuple like so "[(struct element1, fields separated by commas)]".

```
local_network_test    | The application panicked (crashed).
local_network_test    | Message:  Could not parse types: TypeParser(Error("invalid type string: tuple"))
local_network_test    | Location: crates/forge/bin/cmd/create.rs:332
local_network_test    | 
local_network_test    | This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry
local_network_test    | 
local_network_test    | Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
local_network_test    | Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by mattsse** [comment]
thanks for flagging, looking into it
