### ISSUE TITLE
Foundryup: Error opening archive: Unrecognized archive format

### ISSUE THREAD

**Issue by gnkz** [foundry-rs/foundry#6152]
### Component

Foundryup

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9fd44a7 2023-10-26T00:23:32.602895000Z)

### What command(s) is the bug in?

foundryup

### Operating System

macOS (Apple Silicon)

### Describe the bug

When running `foundryup` I'm getting this error

```
foundryup: installing foundry (version nightly, tag nightly-4422d671b39d11788731f51e67896e305503ea6c)
foundryup: downloading latest forge, cast and anvil
############################################################################################################################################## 100.0%
tar: Error opening archive: Unrecognized archive format
foundryup: downloading manpages
############################################################################################################################################## 100.0%
tar: Error opening archive: Unrecognized archive format
foundryup: installed - forge 0.2.0 (9fd44a7 2023-10-26T00:23:32.602895000Z)
foundryup: installed - cast 0.2.0 (9fd44a7 2023-10-26T00:23:32.882582000Z)
foundryup: installed - anvil 0.2.0 (9fd44a7 2023-10-26T00:23:33.029728000Z)
foundryup: done
```

**Comment by mattsse** [comment]
could you try after reinstalling foundryup `curl -L https://foundry.paradigm.xyz | bash`

**Comment by SonOfMosiah** [comment]
Receiving the same error here even after reinstalling foundryup.

- Also using macOS (Apple Silicon)

- Default shell is zsh


Is there a documented method to uninstall before reinstalling?

**Comment by clabby** [comment]
+1, also receiving this error.

The reason is because `foundryup` is currently looking for the nightly build [in the format of `nightly-<SHA>`](https://github.com/foundry-rs/foundry/blob/master/foundryup/foundryup#L86-L92), where the tag is just `nightly`.

See: https://api.github.com/repos/foundry-rs/foundry/git/refs/tags/nightly
and: https://github.com/foundry-rs/foundry/releases/tag/nightly (notice the assets were updated a few minutes ago, and the commit SHA isn't in the URI path).

**Comment by SonOfMosiah** [comment]
Was able to fix on my machine with the following commands:

Update Rust
`brew upgrade rust`

`foundryup --branch master`

**Comment by gosuto-inzasheru** [comment]
ran into this same issue, was solved by reinstalling (`curl -L https://foundry.paradigm.xyz | bash`)
