### ISSUE TITLE
Allow to pass http headers for --fork-url

### ISSUE THREAD

**Issue by vbrvk** [foundry-rs/foundry#6173]
### Component

Anvil

### Describe the feature you would like

I trying to setup e2e testing with anvil, my private node protected by http header with token, but anvil does not support passing http headers to fork url.

It would be nice to have such option, for example under `--fork-header` key with support of multiple headers at once

**Comment by vbrvk** [comment]
I would like to implement this feature by myself, if we are agree on param name and if it is useful at all

**Comment by mattsse** [comment]
cool, I think this is reasonable.

the argument should be called `--fork-headers: Vec<String>` I think,

and should be grouped with the existing fork attributes:

https://github.com/foundry-rs/foundry/blob/30ae702a31e175ca9c2c23bba71ee9d8520c8e45/crates/common/src/evm.rs#L49-L49

then we need support for this here:

https://github.com/foundry-rs/foundry/blob/30ae702a31e175ca9c2c23bba71ee9d8520c8e45/crates/common/src/provider.rs#L49-L49

and

https://github.com/foundry-rs/foundry/blob/30ae702a31e175ca9c2c23bba71ee9d8520c8e45/crates/common/src/runtime_client.rs#L131-L131
