### ISSUE TITLE
Regarding script result file name 

### ISSUE THREAD

**Issue by PraneshASP** [foundry-rs/foundry#6177]
## Description:
The latest script run result file is named `run-latest.json` but other runs has a timestamp attached which makes it easier to identify when the script was run. But to find the timestamp of the latest run we have to manually find it via one of the transaction hashes from the broadcast file. 

## Possible workaround:
It would be nice to add the timestamp to the latest run as well. 
The resulting file name would be something like `run-latest-<TIMESTAMP>.json`. 

I'm happy to take this on if you think this would be a reasonable change.

**Comment by mds1** [comment]
The latest script run always generates two files: One is called `run-latest.json` but the other is `run-<timestamp>.json`, and they are identical. When the same script is run again, the timestamp named file remains and `run-latest.json` is overwritten.

**Comment by PraneshASP** [comment]
Ahh that's news to me. Thanks for letting me know!
