### ISSUE TITLE
forge script nonce issue related to selectFork

### ISSUE THREAD

**Issue by sakulstra** [foundry-rs/foundry#6184]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (deae4f1 2023-10-11T00:27:48.322843000Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

Hello, at aave governance v3 we have a script that:

1. iterates trough multiple chains to check for some configuration correctness
2. submits a single txn on mainnet

While when testing everything works/worked fine, when actually submitting via ledger we're getting nonce issues like:
> nonce changed unexpectedly while sending transactions. Expected 2007 got 2006 from provider.

The issue seems to happen whenever we do selectFork within a script.

Here i created a minimal reproduction:
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;
import {Script} from 'forge-std/Script.sol';

contract Reproduction is Script {
  function run() public {
    uint256 previousFork = vm.activeFork();
    vm.selectFork(previousFork);
    vm.startBroadcast();
    address(0x25F2226B597E8F9514B3F68F00f494cF4f286491).call{value: 1}(new bytes(0));
  }
}
```

The script is started with a mainnet rpc, calls selectFork witht he activeForkId which is 0 and i think should essentially just be a noop in that case?.

The trace looks as follows:
```
Traces:
  [41465] Reproduction::run() 
    ├─ [0] VM::activeFork() [staticcall]
    │   └─ ← 0
    ├─ [0] VM::selectFork(0) 
    │   └─ ← ()
    ├─ [0] VM::startBroadcast() 
    │   └─ ← ()
    ├─ [7180] 0x25F2226B597E8F9514B3F68F00f494cF4f286491::fallback{value: 1}() 
    │   ├─ [55] 0x10c74b37Ad4541E394c607d78062e6d22D9ad632::fallback() [delegatecall]
    │   │   └─ ← ()
    │   └─ ← ()
    └─ ← ()
    
Script ran successfully.
```

Instead of being able to submit the txn though, i'm getting:
```
###
Finding wallets for all the necessary addresses...
##
Sending transactions [0 - 0].

Error: 
EOA nonce changed unexpectedly while sending transactions. Expected 46 got 45 from provider.
```

Seems related:
- https://github.com/foundry-rs/foundry/issues/4701

**Comment by sakulstra** [comment]
edit: updated the example to be even more minimal (initially though was related to multichain, but just calling `selectFork(activeForkId)` will reproduce the same issue.

In practice what we do is:
- store the current forkId
- switch to another fork
- test some stuff
- switch back to the previous fork
The example is simplified, as it seems like most of this is unrelated to the actual error.

---

Also, for anyone facing this, one workaround which seems to work for us is to simply not switch back to the fork but always create a new one:

```diff
- uint256 previousFork = vm.activeFork();
- vm.selectFork(previousFork);
+ vm.createSelectFork(vm.rpcUrl('mainnet'));
````

**Comment by ArshanKhanifar** [comment]
I've proposed a fix here. #6271

**Comment by RedaOps** [comment]
@sakulstra @Evalir can close this as completed since https://github.com/foundry-rs/foundry/pull/6271 is merged?

**Comment by sakulstra** [comment]
@RedaOps i think it's working fine now thx.
