### ISSUE TITLE
Improved Monorepo Profile Management for Enhanced CI/CD

### ISSUE THREAD

**Issue by rmcmk** [foundry-rs/foundry#6186]
### Component

Forge, Cast, Anvil, Chisel

### Introduction

Our project is a monorepo where packages are organized into Foundry profiles, each with its own set of scripts and tests. In many cases, running tests across all profiles or recompiling the entire codebase is essential, especially within a CI/CD pipeline. However, achieving this currently poses challenges, which can only be overcome by duplicating profile definitions or manually parsing the Foundry configuration.

### Proposed Features

1. **Inclusive All Profiles Option**

   - **Option 1:** Introduce a `foundry.toml` setting that allows including all profiles when executing commands if no `FOUNDRY_PROFILE` environment variable is set.
   
   - **Option 2:** Implement a `--all-profiles` command-line flag for executing operations across all profiles.

2. **Enhanced Profile Tooling for CI/CD**

   - Develop additional profile management tools to streamline CI/CD processes, including:

      - **Profile Listing:** Implement a command to list all available profiles within the monorepo.
   
      - **Multi-Profile Support:** Enable the use of multiple profiles through a new environment variable, such as `FOUNDRY_PROFILES="a,b,c"`.

### Conclusion
I believe that these proposed features would be beneficial for our monorepo, but I recognize that they may not represent the ultimate solutions to the challenges we face. This issue is intended to initiate a constructive discussion around improving Foundry profiles and profile management, so if I'm out of line or am totally missing something, please put me in my place, haha! Your feedback, insights, and alternative ideas are highly encouraged as we collectively work towards enhancing our development process.

**Comment by rmcmk** [comment]
**Semi-related bug:**

I'm encountering an issue when trying to use the Forge formatter in Visual Studio Code. It appears that the formatter doesn't work correctly unless the `FOUNDRY_PROFILE` environment variable is set. This requires running a manual command in the terminal: `FOUNDRY_PROFILE="abcdef" forge fmt`.

**Expected Behavior:**

The Forge formatter should be able to detect and use the `FOUNDRY_PROFILE` environment variable without the need for manual setup. Users should be able to format files in VSC seamlessly.

**Comment by zerosnacks** [comment]
Hi @rmcmk, thanks for your report

I've added your requests here https://github.com/foundry-rs/foundry/issues/5479#issuecomment-2209265718

Closing this ticket in favor of that one

>I'm encountering an issue when trying to use the Forge formatter in Visual Studio Code. It appears that the formatter doesn't work correctly unless the FOUNDRY_PROFILE environment variable is set. This requires running a manual command in the terminal: FOUNDRY_PROFILE="abcdef" forge fmt.

Please open a new issue for this if you are still encountering this behavior, it may have been fixed already
