### ISSUE TITLE
Ability to manually disable PUSH0 Support for Compiler Versions >=0.8.20

### ISSUE THREAD

**Issue by jhweintraub** [foundry-rs/foundry#6187]
### Component

Forge

### Describe the feature you would like

Starting in Solidity Version `0.8.20`, the `PUSH0` opcode was implemented in compiled bytecode. As it currently stands only Ethereum mainnet supports this opcode. Anyone wishing to deploy their solidity to an EVM-Chain that is not mainnet is forced to use Solidity Version `0.8.19`. Given as OpenZeppelin has released newer versions with 0.8.20, this can be a real headache for developers's compatibility problems when building contracts intended to be multi-chain or exclusively to L2.

Feature Request: A new `foundry.toml` configuration option `USE_PUSH0` which can be toggled manually and will not compile with the opcode if set to false. This would allow users to take advantage of newer features of the language and associated common libraries without harming their ability to directly deploy such code to the network of their choice.

**Comment by mds1** [comment]
You can use the `evm_version` flag to control which EVM version solc generates bytecode for. Although solc defaults to shanghai, forge defaults to paris and therefore even with solc 0.8.20 and later PUSH0 is not used by default:
- https://book.getfoundry.sh/reference/config/solidity-compiler#evm_version
- https://docs.soliditylang.org/en/latest/using-the-compiler.html#setting-the-evm-version-to-target

**Comment by dezzeus** [comment]
That's what I was looking and hoping for, but was not sure as your doc states _"The EVM version to use during tests"_ which seems to say that it's not the one generally used (e.g. for deployment).

**Comment by jhweintraub** [comment]
> That's what I was looking and hoping for, but was not sure as your doc states _"The EVM version to use during tests"_ which seems to say that it's not the one generally used (e.g. for deployment).

I have also encountered this and had issue with attempting to deploy to L2 networks despite specifying the EVM version in the config file.
