### ISSUE TITLE
Weird behavior when using `ffi` in Linux vs Mac

### ISSUE THREAD

**Issue by gnkz** [foundry-rs/foundry#6188]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (94ae897 2023-10-31T00:17:29.299689000Z)

### Operating System

Linux

### Describe the bug

After the last nightly release I realized that there is a difference between running commands in Linux vs Mac

For example trying to run a non-existen binary using `tryFfi`

Error message in linux:
```
failed to execute command cd "/home/foo/bar" && "foo": No such file or directory (os error 2)
```

Error message in mac:
```
Failed to execute command "foo": No such file or directory (os error 2)
```

In Linux `tryFfi` always uses a `cd /current/dir` and then it tries to execute the actual command while on Mac it just tries to executes the command right away.

Not sure if this is intended or a bug

**Comment by mattsse** [comment]
though the error is expected, right?

**Comment by gnkz** [comment]
> though the error is expected, right?

I think so. What's weird to me is the `cd /current/dir` stuff in Linux vs just executing the command in Mac

**Comment by DaniPopes** [comment]
it's how rust displays the command, cd here indicates setting the current directory of the command programmatically to the workspace root

**Comment by gnkz** [comment]
> it's how rust displays the command, cd here indicates setting the current directory of the command programmatically to the workspace root

Oh, didn't thought about being a rust thing because in previous versions of foundry the errors were consistent between the two OS

**Comment by DaniPopes** [comment]
Right, that's because before the command wasn't even logged.

**Comment by gnkz** [comment]
> Right, that's because before the command wasn't even logged.

ok, so just to understand, it's expected for the error messages to be different between Linux and MacOS, right?

**Comment by DaniPopes** [comment]
Yes, is this a problem?

**Comment by gnkz** [comment]
> Yes, is this a problem?

no, just wanted to confirm, thanks!
