### ISSUE TITLE
Cast no longer correctly returns signature if name with `uint` (no bit size annotation) used

### ISSUE THREAD

**Issue by Philogy** [foundry-rs/foundry#6195]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

cast 0.2.0 (34f684d 2023-11-01T22:17:43.258061708Z)

### What command(s) is the bug in?

cast sig

### Operating System

Linux

### Describe the bug

Previously cast would correctly give the same result if you requested the selector for with an input like `transfer(address, uint256)` and `transfer(address, uint)` however `cast` has begun interpreting `uint` literally, returning different (incorrect) selectors for the two:

```
$ cast sig "transfer(address, uint)"
> 0x6cb927d8 // keccak256("transfer(address,uint)")[0:4]

$ cast sig "transfer(address, uint256)"
> 0xa9059cbb // keccak256("transfer(address,uint256)")[0:4], actually correct
```

**Comment by mattsse** [comment]
wdyt @DaniPopes ?
