### ISSUE TITLE
Anvil: Migrate reth's tracers once the providers & RPC types migration is complete.

### ISSUE THREAD

**Issue by Evalir** [foundry-rs/foundry#6197]
This would allow us to receive any upstream fixes to the tracers directly on Anvil, without having to duplicate work on fixing bugs on each side.

**Comment by ankurdubey521** [comment]
I would like to take this up as soon as the providers / RPC Types migration is done, and can also look into taking up tasks related to the providers / types migration if available

**Comment by gakonst** [comment]
Hi @ankurdubey521 we're gonna drive this feature as it's p critical and we'd like to iterate quick on it! Thank you for offering nonetheless!
