### ISSUE TITLE
Verify "notok"  

### ISSUE THREAD

**Issue by deed3e** [foundry-rs/foundry#6203]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 34f684d

### What command(s) is the bug in?

forge script script/Test.s.sol:Test --fork-url https://data-seed-prebsc-2-s2.binance.org:8545 --broadcast --etherscan-api-key 3......P -vv --via-ir --verify --watch

### Operating System

macOS (Intel)

### Describe the bug

![Screen Shot 2023-11-03 at 17 12 56](https://github.com/foundry-rs/foundry/assets/50208354/3656f0ec-f6c9-40cd-9d60-8bbac14245df)
Help me!!!

**Comment by Evalir** [comment]
Note that you have your API key exposed, so someone can take it. I'd recommend generating a new one.

Without a repro it's hard to see what's happening, and this is bsc testnet which can be notoriously finicky with verification. What's your repo structure like?

**Comment by deed3e** [comment]
this is repo
https://github.com/deed3e/fd-trading-contract

**Comment by deed3e** [comment]
![Screen Shot 2023-11-03 at 22 04 02](https://github.com/foundry-rs/foundry/assets/50208354/970c7cdb-0d05-4bb3-9f18-5f218aaf4fb6)
So i deploy in linea test , not verify

**Comment by Evalir** [comment]
Closing as duplicate—this is another instance of verification issues
