### ISSUE TITLE
cast is slow on OSX

### ISSUE THREAD

**Issue by drortirosh** [foundry-rs/foundry#6204]
### Component

Cast

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

cast 0.2.0 (34f684d 2023-11-01T22:19:24.957042000Z)

### What command(s) is the bug in?

time cast bn

### Operating System

macOS (Apple Silicon)

### Describe the bug

For some reason, network commands of `cast` are slow.
(all measures are against a local `geth` or `anvil`)

- `time cast to-hex` takes ~25ms, but
- `time cast bn` takes **~200** ms.
In comparison, the equivalent curl takes ~15 ms
`time curl -H 'content-type: application/json' -d '{"id":1,"jsonrpc":"2.0","method":"eth_blockNumber"}' http://localhost:8545`

I verified that it works better on a linux (google cloud) - 10ms for "to-hex" and 15 ms for "bn"

(note: I verified I use native "arm64" executables.

**Comment by mattsse** [comment]
I see, the issue here is that we're trying to resolve foundry config because the bn command also supports chain aliases.

we can make this a bit smarter though

**Comment by drortirosh** [comment]
I still don't understand why this hurts OSx build, and don't the Linux version.
I also tried to add an alias
```
[rpc_endpoints]
local = "http://localhost:8545"
```

And all variants: 
- time cast bn -r http://localhost:8545
- time cast bn -r local
- time cast bn

Take roughly the same.

**Comment by DaniPopes** [comment]
Can reproduce as well. Profiling shows that 80% of the time is spent in `rustls_native_certs::load_native_certs`: <https://share.firefox.dev/463tYIx>
