### ISSUE TITLE
Unable to encode empty bytes ("0x")

### ISSUE THREAD

**Issue by Thegaram** [foundry-rs/foundry#6211]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (1c7bf46 2023-11-03T13:18:06.065760000Z)

### What command(s) is the bug in?

cast calldata, cast abi-encode, cast send

### Operating System

macOS (Apple Silicon)

### Describe the bug

Possible regression, worked well before I updated yesterday using `foundryup`.

```
$ cast calldata "foo(bytes memory)" "0x"
Error: 
parser error:
0x
   ^


Context:
- parser error:
0x
   ^
```

**Comment by Thegaram** [comment]
Thanks, when is this change expected to make its way into foundry?

**Comment by mattsse** [comment]
ref #6214
