### ISSUE TITLE
Rename `4byte-event` command

### ISSUE THREAD

**Issue by guidanoli** [foundry-rs/foundry#6217]
### Component

Cast

### Describe the feature you would like

I find it weird that this command is called `4byte-event` because it actually only accepts 32-byte hashes, which are the `topic0` of logs. Wouldn't it be more technically correct to call it something like `32byte-event` or `topic0-event`? I'm not suggesting any specific alternative, but I do think we need to rename this command to avoid confusion.

**Comment by Evalir** [comment]
At this point we wanna avoid backward-incompatible changes, but we can give it an alias for `topic0-event`

**Comment by mattsse** [comment]
we can add an alias though
