### ISSUE TITLE
After running the test, a large core file will be generated in the /tmp directory.

### ISSUE THREAD

**Issue by guange2015** [foundry-rs/foundry#6220]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6ac22df 2023-10-25T00:27:18.529420296Z)

### What command(s) is the bug in?

forge test --match-path test/file.t.sol -vv

### Operating System

Linux

### Describe the bug

After running the test, my /tmp directory:

du  -sh /tmp/forge.1699254022.43842*
1.4G    /tmp/forge.1699254022.438428.6.core
1.4G    /tmp/forge.1699254022.438429.6.core

**Comment by DaniPopes** [comment]
Those are core dump files <https://en.wikipedia.org/wiki/Core_dump>

Do you have any other info like logs or a reproducer? Otherwise can't do much
