### ISSUE TITLE
Offer `anvil_metadata` RPC

### ISSUE THREAD

**Issue by antazoey** [foundry-rs/foundry#6221]
### Component

Anvil

### Describe the feature you would like

I would like the same feature from Hardhat as this: https://hardhat.org/hardhat-network/docs/reference#hardhat_metadata
This way, I can easily perform verifications on the forked network without relying on genesis block hashes or anything weird.

It is useful metadata at the node level in general.

**Comment by mattsse** [comment]
sgtm!

we can easily add this, will do if no one picks it up

**Comment by iankressin** [comment]
I also need this one and I can give it a try @mattsse. Prob will need some guidance on the PR since it'll be the first time contributing to the repo

**Comment by iankressin** [comment]
Doesn't `anvil_nodeInfo` already returns the info that you need?

https://github.com/foundry-rs/foundry/blob/86f3d181d09ec2ffb9f8bac8bdf6d5e08e20f0d2/crates/anvil/src/eth/api.rs#L1662

**Comment by mattsse** [comment]
metadata includes more info and NodeInfo is standard format

we can just add a new type + call

**Comment by antazoey** [comment]
All I am really doing is checking to see if the connected _is_ a fork; I supposed to existence of `forkConfig` in `anvil_nodeInfo` may accomplish that.

One nice thing about the `metadata` response is the chain ID being present instead of me having to make another request to get it.

**Comment by mattsse** [comment]
fyi @Evalir this would be super simple to add

**Comment by Evalir** [comment]
yep there's utility to this, so let's go and add it
