### ISSUE TITLE
Unimplemented precompiles on L2s are treated as implemented

### ISSUE THREAD

**Issue by zobront** [foundry-rs/foundry#6230]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (fd90b1d 2023-11-06T20:43:26.902623000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

Since precompiles are implemented in revm, they're intercepted from `forge test` calls before reaching the network.

For L2s that don't implement certain precompiles (for example, [Polygon zkEVM](https://wiki.polygon.technology/docs/zkevm/faq/zkevm-eth-faq/#what-precompiled-smart-contract-functions-does-polygon-zkevm-support) only implements ecRecover and identity - most other ZK rollups are similarly limited), this can lead to inaccurate behavior, where fork tests that call to precompiles will succeed when they should fail.

To reproduce:
```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import {Test, console2} from "forge-std/Test.sol";

contract PrecompileTest is Test {
    function testPrecompiles() public {
        vm.createSelectFork("https://zkevm-rpc.com");
        bytes memory input = "hello";
        (bool s, bytes memory d) = address(2).call(input);
        console2.log(s);
        console2.logBytes(d);
    }
}
```
```
Logs:
  true
  0x2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824
```

Compare this to the `cast call`, which presumable pings the actual RPC node for a response:
```
zachobront@Zachs-MacBook-Pro prec % cast call 0x0000000000000000000000000000000000000002 --rpc-url "https://zkevm-rpc.com" 0x12345678
Error: 
(code: 3, message: execution reverted, data: Some(String("0x")))
```

**Comment by DaniPopes** [comment]
This is known. We currently only support mainnet precompiles which are implemented in [Revm](https://github.com/bluealloy/revm), and there's no way to configure this in Foundry. See https://github.com/foundry-rs/foundry/issues/748.
