### ISSUE TITLE
bug(forge): `blockhash` returns the block number

### ISSUE THREAD

**Issue by minaminao** [foundry-rs/foundry#6235]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (fd90b1d 2023-11-06T20:45:35.983698000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Intel)

### Describe the bug

Hi, I noticed that `blockhash` returns the block number, not a random value now.
In my project, a test that assumes `blockhash` is somewhat random was not passed, so I found this.
Maybe the spec was changed to that, I think `blockhash` should be random.

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import {Test, console2} from "forge-std/Test.sol";

contract CounterTest is Test {

    function testBlockNumber() public {
        vm.roll(10);
        console2.log(uint256(blockhash(block.number - 1)));
    }
}
```

```sh
$ forge test -vvvvv
[⠰] Compiling...
[⠢] Compiling 1 files with 0.8.22
[⠆] Solc 0.8.22 finished in 1.71s
Compiler run successful!

Running 1 test for test/Counter.t.sol:CounterTest
[PASS] testBlockNumber() (gas: 6036)
Logs:
  9

Traces:
  [6036] CounterTest::testBlockNumber() 
    ├─ [0] VM::roll(10) 
    │   └─ ← ()
    ├─ [0] console::log(9) [staticcall]
    │   └─ ← ()
    └─ ← ()

Test result: ok. 1 passed; 0 failed; 0 skipped; finished in 1.08ms
 
Ran 1 test suites: 1 tests passed, 0 failed, 0 skipped (1 total tests)
```

**Comment by DaniPopes** [comment]
The "random value" was just `keccak256(block.number)`, which I removed in https://github.com/bluealloy/revm/pull/691
What is your usecase for using blockhash in tests?

**Comment by minaminao** [comment]
@DaniPopes 

Oh it was a feature of revm. Thanks for letting me know.

In my case, if `uint256(blockhash(x - 1)) % 2 == uint256(blockhash(x - 2)) % 2`, a process is executed, but now it's completely failed.
Of course, I know that `blockhash` is a weak source of randomness, and such codes are rare in real, but imo we should make it as close to real behavior.

It's not too much of a problem for the even-odd case, but I think it's bad that the blockhash, even though it's a 256-bit value, can be represented by a much smaller number of bits from a security point of view.
For example, if a contract has a bug that the upper bits of the blockhash value are missing in inline-assembly or something, the bug would not be detected in tests.

So i think `keccak256(block.number)` is enough.

**Comment by mds1** [comment]
Agreed, I think we should keep the blockhash as `keccak256(block.number)` for the reasons mentioned. It's more realistic than being identical to block number and having the majority of the bytes being zero bytes

**Comment by minaminao** [comment]
This is fixed in revm

**Comment by mds1** [comment]
Reopened since this has not been upstreamed to foundry yet

**Comment by zerosnacks** [comment]
This has since been upstreamed to Foundry

With given setup:

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import {Test, console2} from "forge-std/Test.sol";

contract CounterTest is Test {

    function testBlockNumber() public {
        vm.roll(10);
        console2.log(uint256(blockhash(block.number - 1)));
    }
}
```

Now yields:

```
[PASS] testBlockNumber() (gas: 6014)
Logs:
  95425574589610153198208762008858956030090942575336134545694646396662888954619

Traces:
  [6014] CounterTest::testBlockNumber()
    ├─ [0] VM::roll(10)
    │   └─ ← [Return] 
    ├─ [0] console::log(95425574589610153198208762008858956030090942575336134545694646396662888954619 [9.542e76]) [staticcall]
    │   └─ ← [Stop] 
    └─ ← [Stop] 

Suite result: ok. 1 passed; 0 failed; 0 skipped; finished in 404.78µs (117.44µs CPU time)

Ran 1 test suite in 3.86ms (404.78µs CPU time): 1 tests passed, 0 failed, 0 skipped (1 total tests)
```
