### ISSUE TITLE
ERC20: transfer amount exceeds allowance

### ISSUE THREAD

**Issue by nstylo** [foundry-rs/foundry#6237]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (059aa45 2023-11-07T08:13:53.055005635Z)

### What command(s) is the bug in?

cast send

### Operating System

Linux

### Describe the bug

I am trying to `transferFrom` an address to some contract on anvil, which I forked like so:

`anvil --fork-url https://arb-mainnet.g.alchemy.com/v2/<API-KEY>`

![image](https://github.com/foundry-rs/foundry/assets/45883614/80032c85-0390-4aa3-9e93-0be2df86929d)

It keeps saying that the transfer amount exceeds the allowance. What am I doing wrong?

![image](https://github.com/foundry-rs/foundry/assets/45883614/d5d93376-e510-4dbe-bc44-e41a7f607e75)

**Comment by DaniPopes** [comment]
Repro script OCR'd from image
```bash
#!/usr/bin/env bash

USDC=0xaf88d065e77c8cC2239327C5EDb3A432268e5831
USER=0x7CCbb89862f5cA9A83562Aa6cB8Af686c89A3701
TARGET=0x7c68c7866a64fa2160f78eeae12217ffbf871fa8

function echoed() {
    echo
    echo ">" "$@"
    "$@"
}

echoed cast rpc anvil_impersonateAccount $USER
echoed cast send $USDC --unlocked --from $USER "approve(address,uint256)" $TARGET 100000
echoed cast call $USDC "balanceOf(address)(uint256)" $USER
echoed cast call $USDC "allowance(address,address)(uint256)" $USER $TARGET
echoed cast send $USDC --unlocked --from $USER "transferFrom(address,address,uint256)" $USER $TARGET 100000
```

**Comment by nstylo** [comment]
User error, I used transferFrom incorrectly. TARGET should indeed be SPENDER and another target address is needed to transfer the funds to, so really the last send should be:

```bash
echoed cast send $USDC --unlocked --from $SPENDER "transferFrom(address,address,uint256)" $USER $TARGET 100000
```
