### ISSUE TITLE
Parser error when passing string as parameter to script

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/foundry#6265]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (57180fc 2023-11-09T01:50:25.972958000Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

I was trying to run this [script](https://github.com/sablier-labs/v2-periphery/blob/0004fd2e61e032df3d895045ec414ecb212ddcc8/script/DeployDeterministicBatch.t.sol), when I got the following error:

> Error:
> parser error:
> ChainID 42161, Version 1.0.0

The full command I tried to run is:

```sh
FOUNDRY_PROFILE=optimized \
forge script script/DeployDeterministicBatch.t.sol \
--broadcast \
--rpc-url arbitrum_one \
--sig "run(string)" \
--verify \
"ChainID 42161, Version 1.0.0" \
-vvvv
```

The error seems to be that Foundry cannot parse the string correctly.

This wasn't happening before.

**Comment by PaulRBerg** [comment]
Replacing the comma (`,`) with a colon (`:`) worked.

**Comment by PaulRBerg** [comment]
This issue has to be re-opened. I am getting the exact same error as before:

```
Deserialization Error: EOF while parsing a value at line 1 column 0. Response:
```

When trying to use a string that contains a comma as a constructor param, e.g.

```
"ChainID 56, Version 1.1.1"
```

We used commas in our V2.0 deployment, and we would like to use them in our V2.1 deployment, too.

**Comment by PaulRBerg** [comment]
This issue has to be re-opened. I am getting the exact same error as before:

```
Deserialization Error: EOF while parsing a value at line 1 column 0. Response:
```

When trying to use a string that contains a comma as a constructor param, e.g.

```
"ChainID 56, Version 1.1.1"
```

We used commas in our V2.0 deployment, and we would like to use them in our V2.1 deployment, too.

Cc @DaniPopes @Evalir

**Comment by PaulRBerg** [comment]
Actually - this might be something else. Commented in https://github.com/foundry-rs/foundry/issues/6050.

**Comment by smol-ninja** [comment]
This issue still exists. See https://github.com/sablier-labs/v2-core/issues/750#issuecomment-1860622788

Foundry throws error when trying to use comma in the constructor param.
