### ISSUE TITLE
[Cheatcode] RecordCalls

### ISSUE THREAD

**Issue by marktoda** [foundry-rs/foundry#6267]
### Component

Forge

### Describe the feature you would like

Would like a cheatcode similar to `record` and `recordLogs` called `recordCalls` which records all external calls during the recorded period. My particular use case is to more accurately assess L2 gas costs in my forge-gas-snapshot library, but can see this being useful for testing to ensure certain interactions occurred as expected.

**Comment by mds1** [comment]
Once https://github.com/foundry-rs/foundry/pull/6310 is merged it should solve this use case (you'll just have to filter the accesses to only keep calls), feel free to take a look at that and leave comments with your thoughts

**Comment by marktoda** [comment]
Sick, #6310 is merged, closing this
