### ISSUE TITLE
feature(cheatcode): `vm.predictContractAddr()`; pre-determine next deployed addresses

### ISSUE THREAD

**Issue by Anish-Agnihotri** [foundry-rs/foundry#6270]
### Component

Forge

### Describe the feature you would like

Would be useful to have a cheatcode that can pre-compute future contract deployment addresses based on deployer address and nonce:

```solidity
function predictContractAddr(address deployer, uint256 nonce) external returns (address);
```

Frequently run into use-cases where the contract ordering is dependent and I need to serialize some address/call for a future-deployed contract.

### Additional context

Today, I just copy-paste @k06a's handy [`addressFrom` function](https://ethereum.stackexchange.com/questions/24248/how-to-calculate-an-ethereum-contracts-address-during-its-creation-using-the-so) into a test-suite library.

```solidity
function addressFrom(address _origin, uint _nonce) public pure returns (address) {
    bytes memory data;
    if (_nonce == 0x00)          data = abi.encodePacked(bytes1(0xd6), bytes1(0x94), _origin, bytes1(0x80));
    else if (_nonce <= 0x7f)     data = abi.encodePacked(bytes1(0xd6), bytes1(0x94), _origin, uint8(_nonce));
    else if (_nonce <= 0xff)     data = abi.encodePacked(bytes1(0xd7), bytes1(0x94), _origin, bytes1(0x81), uint8(_nonce));
    else if (_nonce <= 0xffff)   data = abi.encodePacked(bytes1(0xd8), bytes1(0x94), _origin, bytes1(0x82), uint16(_nonce));
    else if (_nonce <= 0xffffff) data = abi.encodePacked(bytes1(0xd9), bytes1(0x94), _origin, bytes1(0x83), uint24(_nonce));
    else                         data = abi.encodePacked(bytes1(0xda), bytes1(0x94), _origin, bytes1(0x84), uint32(_nonce));
    return address(uint160(uint256(keccak256(data))));
}
```

**Comment by mattsse** [comment]
sgtm, we can do the same for create2 with salt.
this is just a single call in rust

**Comment by qiweiii** [comment]
Hi, I would like to try implement this! Any hint on which category I should put this cheatcode under?

**Comment by mds1** [comment]
Thanks @qiweiii, I’ll assign you

We should match the function names and signatures of the forge-std methods that do this: https://github.com/foundry-rs/forge-std/blob/37a37ab73364d6644bfe11edf88a07880f99bd56/src/StdUtils.sol#L97-L134

Additionally, we should PR in a warning event emission to the existing forge-std methods that they’re deprecated in favor of the native cheats

**Comment by qiweiii** [comment]
There is one more task to do😅

> Additionally, we should PR in a warning event emission to the existing forge-std methods that they’re deprecated in favor of the native cheats

Does this mean do something like this? https://github.com/foundry-rs/forge-std/blob/37a37ab73364d6644bfe11edf88a07880f99bd56/src/StdCheats.sol#L700

**Comment by mds1** [comment]
Yes, just like that! So the forge-std PR will need that change + an update to `Vm.sol` to add the new cheats. I think `Vm.sol` should be organized roughly the same as the foundry cheat definitions, so choose whatever location within `VmSafe` you think makes the most sense and I can always move it if needed
