### ISSUE TITLE
Bug: `The application panicked (crashed). Message:  index out of bounds: the len is 2 but the index is 2`

### ISSUE THREAD

**Issue by pcaversaccio** [foundry-rs/foundry#6276]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

`forge 0.2.0 (834d959 2023-11-10T00:19:17.918296482Z)`

### What command(s) is the bug in?

`forge test`

### Operating System

Linux

### Describe the bug

Another day, another bug :-D

My CI throws now with the following bug (see [here](https://github.com/pcaversaccio/snekmate/actions/runs/6822323083/job/18554176162#step:15:1580)):

![image](https://github.com/foundry-rs/foundry/assets/25297591/bfbb649e-482b-45b8-81bf-14451942185d)

The PR is this one: https://github.com/pcaversaccio/snekmate/pull/182. It doesn't change any test code.

**Comment by pcaversaccio** [comment]
For context, it's the same PR that threw yesterday with another bug (https://github.com/foundry-rs/foundry/issues/6262) and got fixed via https://github.com/foundry-rs/foundry/pull/6263.

**Comment by cuckflong** [comment]
Another case here but only happens when running test with `--gas-report`
