### ISSUE TITLE
`forge build SomeContract.sol` (target a single file or glob of files)

### ISSUE THREAD

**Issue by holic** [foundry-rs/foundry#6278]
### Component

Forge

### Describe the feature you would like

I think there's an issue with forge cache not taking into account inheritance when generating new ABIs: https://github.com/foundry-rs/foundry/issues/6241#issuecomment-1802142594

As a workaround, I was hoping to just rebuild (with `--force`) a single file, but looks like forge doesn't have a way to do this? I'm not sure if the above is easier to fix than to add this feature, but this feature seems useful anyhow, so thought I'd ask.

**Comment by Rubilmax** [comment]
Would love this

**Comment by zerosnacks** [comment]
Resolved by https://github.com/foundry-rs/foundry/pull/8158 + https://github.com/foundry-rs/foundry/pull/8149

Now allows for syntax:

`forge build <DIR1> <DIR2>` e.g. `forge build scripts test` 

and

`forge build src/Counter.sol` to build an individual file
