### ISSUE TITLE
Feature Request: more verbose build output

### ISSUE THREAD

**Issue by pmdaly** [foundry-rs/foundry#628]
### Component

Forge

### Describe the feature you would like

It would be helpful to have the option to see more output information when compiling contracts such as
1. The number of contracts compiled - maybe grouped by core contracts and test
2.  Solidity version - not sure how this would be displayed with different versions but some output would be nice
3. Compile time - not crucial just interesting

Verbosity could be added as a flag to build to control how much output to display.  

### Additional context

Hardhat example
![Screen Shot 2022-01-29 at 2 42 22 PM](https://user-images.githubusercontent.com/8229664/151680156-1ada05f5-2ab8-4891-b3a3-bfc359dcf9e9.png)

Brownie example
![Screen Shot 2022-01-29 at 2 47 23 PM](https://user-images.githubusercontent.com/8229664/151680158-c3295fcd-e005-4f6d-906e-a9bf803e144b.png)

**Comment by gakonst** [comment]
loosely related to @gtklocker ideas around extending `forge build` similar to `go build`

```
$ go build
The build flags are shared by the build, clean, get, install, list, run,
and test commands:
    -n
        print the commands but do not run them.
    -v
        print the names of packages as they are compiled.
    -x
        print the commands.
```

**Comment by onbjerg** [comment]
Can this be closed now that we have `forge build --names` (contract names + solc version), `forge build --sizes` (contract names + sizes) and `forge build` now displays the time it took to compile?

**Comment by gakonst** [comment]
yep
