### ISSUE TITLE
forge(doc): Include `@param` tags provided for events, errors and structs

### ISSUE THREAD

**Issue by webthethird** [foundry-rs/foundry#6282]
### Component

Forge

### Describe the feature you would like

When generating user docs with `forge doc`, I would like to have a table for each event, custom error and struct that has parameters, in the same manner as functions, provided that the developer has included `@param` tags for the event/error parameters. For example:

```solidity
    /// @notice Emitted when a new reward token is added
    /// @param rewardToken Reward token address
    /// @param initialTimestamp Timestamp when reward token was added
    /// @param initialInflationRate Initial inflation rate for the reward token
    /// @param initialReductionFactor Initial reduction factor for the reward token
    event RewardTokenAdded(
        address indexed rewardToken,
        uint256 initialTimestamp,
        uint256 initialInflationRate,
        uint256 initialReductionFactor
    );
```

should generate:

### RewardTokenAdded

Emitted when a new reward token is added

```solidity
event RewardTokenAdded(
    address indexed rewardToken, uint256 initialTimestamp, uint256 initialInflationRate, uint256 initialReductionFactor
);
```

**Parameters**

| Name                     | Type      | Description                                |
| ------------------------ | --------- | ------------------------------------------ |
| `rewardToken`            | `address` | Reward token address                |
| `initialTimestamp`       | `uint256` | Timestamp when reward token was added      |
| `initialInflationRate`   | `uint256` | Initial inflation rate for the reward token   |
| `initialReductionFactor` | `uint256` | Initial reduction factor for the reward token |

Similarly,

```solidity
    /// @notice Data structure containing essential info for each reward token
    /// @param token Address of the reward token
    /// @param paused Whether the reward token accrual is paused
    /// @param initialTimestamp Time when the reward token was added
    /// @param initialInflationRate Initial rate of reward token emission per year
    /// @param reductionFactor Factor by which the inflation rate is reduced each year
    /// @param marketAddresses List of markets for which the reward token is distributed
    /// @param marketWeights Market reward weights as basis points, i.e., 100 = 1%, 10000 = 100%
    struct RewardInfo {
        IERC20Metadata token;
        bool paused;
        uint256 initialTimestamp;
        uint256 initialInflationRate;
        uint256 reductionFactor;
        address[] marketAddresses;
        uint16[] marketWeights;
    }
```

should generate

### RewardInfo
Data structure containing essential info for each reward token

```solidity
struct RewardInfo {
    IERC20Metadata token;
    bool paused;
    uint256 initialTimestamp;
    uint256 initialInflationRate;
    uint256 reductionFactor;
    address[] marketAddresses;
    uint16[] marketWeights;
}
```

**Properties**
| Name                     | Type      | Description                                |
| ------------------------ | --------- | ------------------------------------------ |
| `token`            | `IERC20Metadata` | Address of the reward token                |
|`paused`|`bool`| Whether the reward token accrual is paused |
| `initialTimestamp`       | `uint256` | Time when the reward token was added     |
| `initialInflationRate`   | `uint256` | Initial rate of reward token emission per year  |
| `reductionFactor` | `uint256` | Factor by which the inflation rate is reduced each year |
| `marketAddresses`|`address[]`| List of markets for which the reward token is distributed |
| `marketWeights`|`uint16[]`| Market reward weights as basis points, i.e., 100 = 1%, 10000 = 100% |

**Comment by klkvr** [comment]
Hey @webthethird are you planning to work on this? I would be happy to take this otherwise

**Comment by webthethird** [comment]
No, I'm not comfortable enough with Rust yet 😅

**Comment by mattsse** [comment]
Adding this was super simple:


<img width="579" alt="image" src="https://github.com/foundry-rs/foundry/assets/19890894/1722e059-8b32-4e0a-b945-35555efe46f3">


<img width="570" alt="image" src="https://github.com/foundry-rs/foundry/assets/19890894/db82c27e-0f62-46a7-8763-546392562343">


<img width="577" alt="image" src="https://github.com/foundry-rs/foundry/assets/19890894/564dcba2-11ce-49f9-9b60-8d92bd1f7814">

ref #6287

**Comment by webthethird** [comment]
Great! 

For the custom errors, it might make more sense for the table header to say parameters rather than properties, but otherwise this is exactly what I was looking for. 

Thanks!

**Comment by mattsse** [comment]
sg!
updated
