### ISSUE TITLE
forge script failed

### ISSUE THREAD

**Issue by lucas7788** [foundry-rs/foundry#6306]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (d70aea4 2023-02-16T00:15:56.365073Z)

### What command(s) is the bug in?

RUST_BACKTRACE=full forge script script/MyLockProxy.s.sol:DeployMyLockProxyScript --legacy --broadcast --rpc-url $POLARIS_TESTNET_URL

### Operating System

macOS (Intel)

### Describe the bug

 RUST_BACKTRACE=full forge script script/MyLockProxy.s.sol:DeployMyLockProxyScript --legacy --broadcast --rpc-url $POLARIS_TESTNET_URL
[⠢] Compiling...The application panicked (crashed).
Message:  checksum not found
Location: /Users/runner/.cargo/git/checkouts/ethers-rs-c3a7c0a0ae0fe6be/a69036f/ethers-solc/src/compile/mod.rs:463

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   2: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   3: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   4: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   5: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   6: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   7: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   8: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
   9: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  10: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  11: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  12: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  13: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  14: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  15: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  16: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  17: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  18: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  19: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  20: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  21: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>
  22: __mh_execute_header<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
zsh: abort      RUST_BACKTRACE=full forge script  --legacy --broadcast --rpc-url

**Comment by DaniPopes** [comment]
Can you try clearing `$HOME/.svm`?

**Comment by Evalir** [comment]
Closing as stale.
