### ISSUE TITLE
[Regression] `cast sig-event` unexpected behavior on v0.2.0 (6b72a8c)

### ISSUE THREAD

**Issue by 0xarthurxyz** [foundry-rs/foundry#6309]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

cast 0.2.0 (6b72a8c 2023-11-06T00:23:40.259531000Z)

### What command(s) is the bug in?

cast sig-event

### Operating System

macOS Sonoma Version 14.1 (Apple Silicon M1 Pro)

### Describe the bug

When I run: 

```sh
$ cast sig-event "Transfer(address indexed from, address indexed to, uint256 amount)"
```

I'd expect to see a hash, which represents the event signature that will be in `topic[0]` of an event log.
Instead, I'm getting a string which is simply the event signature stripped of parameter names.

### Expected

```sh
cast sig-event "Transfer(address indexed from, address indexed to, uint256 amount)"
0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef
```

### Actual

```sh
$ cast sig-event "Transfer(address indexed from, address indexed to, uint256 amount)"
"Transfer(address,address,uint256)"
```

### Fix

Reverting to a previous version for Foundry solved this bug: 

```sh
foundryup -C 2885b0d
```

**Comment by Evalir** [comment]
I think this is already fixed in a newer version—could you try updating foundry first?

**Comment by 0xarthurxyz** [comment]
Ah great, I can confirm this is fixed:

```sh
$ cast --version
cast 0.2.0 (1a2e2e0 2023-11-14T00:27:18.117898000Z)
```

```sh
$ cast sig-event "Transfer(address indexed from, address indexed to, uint256 amount)"
0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef
```
