### ISSUE TITLE
Anvil work very slow, freezing

### ISSUE THREAD

**Issue by debych** [foundry-rs/foundry#6316]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (106889c 2023-11-15T00:21:25.192158570Z)

### What command(s) is the bug in?

anvil --port 8585 -f https://eth.llamarpc.com --block-base-fee-per-gas 0 --auto-impersonate

### Operating System

Linux

### Describe the bug

Anvil is up on a linux server. We try to use it as test blockchain for the testing of our application. 

Even several eth_call's of balanceOf can cause anvil to freeze and answer to this command for more than 1 minute.

When sending several transactions and calls, for example:
1) call to check allowance
2) approve
3) execute

execution or estimate_gas can also freeze for longer than 1 minute.

There is no errors in logs. It just works slow as you can see on timings

![image](https://github.com/foundry-rs/foundry/assets/48215060/b900d724-5fbe-4be2-8b66-9b07ddb9447b)

The server has 50% of memory free and CPU (2 core) is loaded slighty

**Comment by debych** [comment]
@mattsse 
Thanks for the answer! 
I have tried --no-rate-limit. It didn't affect. 

Does forked RPC impact the performance of anvil? Not only the initializing stage

**Comment by mattsse** [comment]
yeah significantly because everyhting is fetched from remote

**Comment by Evalir** [comment]
Closing as stale—we know the cause and this is configurable and easily fixable if there's access to a personal node. We're improving other aspects of anvil to make this faster.
