### ISSUE TITLE
Bug: `cast storage` displays wrong values for packed slots

### ISSUE THREAD

**Issue by pcaversaccio** [foundry-rs/foundry#6319]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

`forge 0.2.0 (64b0e8f 2023-11-15T14:06:05.905353479Z)`

### What command(s) is the bug in?

`cast storage`

### Operating System

Linux

### Describe the bug

Repro example (replace it with your Etherscan API key of Optimism).

Run:

```console
cast storage --rpc-url https://mainnet.optimism.io --etherscan-api-key <YOUR_API_KEY> 0x13b0D85CcB8bf860b6b79AF3029fCA081AE9beF2
```

which returns:

```console
| Name    | Type    | Slot | Offset | Bytes | Value                                            | Contract
                       |
|---------|---------|------|--------|-------|--------------------------------------------------|-----------------------------------------------|
| _owner  | address | 0    | 0      | 20    | 486747459873938072359747357390379788195179410093 | contracts/Create2Deployer.sol:Create2Deployer |
| _paused | bool    | 0    | 20     | 1     | 486747459873938072359747357390379788195179410093 | contracts/Create2Deployer.sol:Create2Deployer |
```

The value of `_paused` is set to the `_owner` value, which however should be simply 0 in this case.

**Comment by mattsse** [comment]
I see we don't actually handle the offset of the Storage entry

https://github.com/foundry-rs/foundry/blob/7769cf01ca951d96167d70bb0ba1d81277b66a19/crates/cast/bin/cmd/storage.rs#L215-L216

**Comment by mattsse** [comment]
maybe we should also include the raw slot value as hex in the output?

**Comment by mattsse** [comment]
@DoTheBestToGetTheBest this should be straight forward, basically only including the relevant range of the `get_storage_at` response determined by the offset

do you want to take this?

**Comment by pcaversaccio** [comment]
> maybe we should also include the raw slot value as hex in the output?

Fully support this.

**Comment by DoTheBestToGetTheBest** [comment]
> his should be straight forward, basically only including the relevant range of the `get_storage_at` response value determined by the offset

Happy to take this

**Comment by pcaversaccio** [comment]
Any update on this? I think this should be fixed sooner rather than later as storage inspection is important during incident analysis and `cast storage` should be reliable...

**Comment by DoTheBestToGetTheBest** [comment]
> Any update on this? I think this should be fixed sooner rather than later as storage inspection is important during incident analysis and `cast storage` should be reliable...

still working on it, i'm having bit difficulty to understand how to fix this

**Comment by DoTheBestToGetTheBest** [comment]
what i'm doing is probably not the right way to fix this error, so i'm trying to understand how i can do it in different way

```rust
 let results = futures::future::join_all(futures).await;


    let mut values = Vec::new();
    for (storage_entry, result) in layout.storage.iter().zip(results.into_iter()) {
        let raw_slot_data = result?.to_alloy(); 

        
        let storage_type = layout.types.get(&storage_entry.storage_type)
            .ok_or_else(|| eyre::Error::msg("Storage type not found"))?;
        let num_bytes = storage_type.number_of_bytes.parse::<usize>()
            .map_err(|_| eyre::Error::msg("Invalid number of bytes"))?;

     
        let offset = storage_entry.offset as usize;
        if offset + num_bytes > 32 {
            return Err(eyre::Error::msg("Offset out of bounds"));
        }

        
        let value = match storage_type.label.as_str() {
            "bool" => {
                
                let byte_index = offset / 8;
                let bit_index = offset % 8;
                let relevant_bit = (raw_slot_data.0[byte_index] >> bit_index) & 1;
              
                B256::from(relevant_bit)
            },
            _ => {
                
                let mut bytes = [0u8; 32];
                bytes[32 - num_bytes..].copy_from_slice(&raw_slot_data.0[offset..offset + num_bytes]);
                B256(bytes)
            },
        };

        values.push(value);
```

**Comment by DoTheBestToGetTheBest** [comment]
sorry for the late guys

**Comment by mattsse** [comment]
please open a PR so we can review

**Comment by pcaversaccio** [comment]
> > Guys, I don't wanna be a pain in the ass, but can we please get this fixed?
> 
> it is already fixed :)

Your PR is still open and I just tried it with the latest `cast` version `cast 0.2.0 (d4e6b43 2023-12-04T00:22:30.496154195Z)` which gives me the following:

```console
| Name    | Type    | Slot | Offset | Bytes | Value                                            | Hex Value
                                            | Contract                                      |
|---------|---------|------|--------|-------|--------------------------------------------------|--------------------------------------------------------------------|-----------------------------------------------|
| _owner  | address | 0    | 0      | 20    | 486747459873938072359747357390379788195179410093 | 0x000000000000000000000000554282cf65b42fc8fddc6041eb24ce5e8a0632ad | contracts/Create2Deployer.sol:Create2Deployer |
| _paused | bool    | 0    | 20     | 1     | 486747459873938072359747357390379788195179410093 | 0x000000000000000000000000554282cf65b42fc8fddc6041eb24ce5e8a0632ad | contracts/Create2Deployer.sol:Create2Deployer |
```

The value for `_paused` is _not_ `0x000000000000000000000000554282cf65b42fc8fddc6041eb24ce5e8a0632ad` but should be simply `0x00`.

**Comment by pcaversaccio** [comment]
@mattsse what's the expected timeline for merging the fix PR?

**Comment by plotchy** [comment]
The https://github.com/foundry-rs/foundry/pull/6370 PR mentions further downstream improvements in a PR. Adding an example for bool offset calculating values as not 0 or 1

reproduce:
```
cast storage --rpc-url https://mainnet.optimism.io --etherscan-api-key T2KRFNUMEN4U8XZQ87YCN82I3AF6XE21NF 0xB67c152E69217b5aCB85A2e19dF13423351b0E27
```

what:
- isUserCancelEnabled is a bool and is 256
- allowUserCloseOnly is a bool and is 16777216
```
| Name                          | Type                                                            | Slot | Offset | Bytes | Value                                             | Hex Value                                                          | Contract                                           |
|-------------------------------|-----------------------------------------------------------------|------|--------|-------|---------------------------------------------------|--------------------------------------------------------------------|----------------------------------------------------|
| gov                           | address                                                         | 0    | 0      | 20    | 1352965747418285184211909460723571462248744342032 | 0x000000000000000000000000ecfd15165d994c2766fbe0d6bacdc2e8dedfd210 | contracts/perp/PositionManager.sol:PositionManager |
| _status                       | uint256                                                         | 1    | 0      | 32    | 1                                                 | 0x0000000000000000000000000000000000000000000000000000000000000001 | contracts/perp/PositionManager.sol:PositionManager |
| admin                         | address                                                         | 2    | 0      | 20    | 1352965747418285184211909460723571462248744342032 | 0x000000000000000000000000ecfd15165d994c2766fbe0d6bacdc2e8dedfd210 | contracts/perp/PositionManager.sol:PositionManager |
| feeCalculator                 | address                                                         | 3    | 0      | 20    | 1297482016264593221714872710065075000476194625473 | 0x000000000000000000000000e3451b170806aab3e24b5cd03a331c1ccdb4d7c1 | contracts/perp/PositionManager.sol:PositionManager |
| oracle                        | address                                                         | 4    | 0      | 20    | 241116142622541106669066767052022920958068430970  | 0x0000000000000000000000002a3c0592dcb58accd346ccee2bb46e3fb744987a | contracts/perp/PositionManager.sol:PositionManager |
| referralStorage               | address                                                         | 5    | 0      | 20    | 1224602325975115131568536406232630666650384091454 | 0x000000000000000000000000d6811146780d50d24bd3475acb23c2118034493e | contracts/perp/PositionManager.sol:PositionManager |
| minExecutionFee               | uint256                                                         | 6    | 0      | 32    | 20000                                             | 0x0000000000000000000000000000000000000000000000000000000000004e20 | contracts/perp/PositionManager.sol:PositionManager |
| minBlockDelayKeeper           | uint256                                                         | 7    | 0      | 32    | 0                                                 | 0x0000000000000000000000000000000000000000000000000000000000000000 | contracts/perp/PositionManager.sol:PositionManager |
| minTimeExecuteDelayPublic     | uint256                                                         | 8    | 0      | 32    | 180                                               | 0x00000000000000000000000000000000000000000000000000000000000000b4 | contracts/perp/PositionManager.sol:PositionManager |
| minTimeCancelDelayPublic      | uint256                                                         | 9    | 0      | 32    | 180                                               | 0x00000000000000000000000000000000000000000000000000000000000000b4 | contracts/perp/PositionManager.sol:PositionManager |
| maxTimeDelay                  | uint256                                                         | 10   | 0      | 32    | 1800                                              | 0x0000000000000000000000000000000000000000000000000000000000000708 | contracts/perp/PositionManager.sol:PositionManager |
| isUserExecuteEnabled          | bool                                                            | 11   | 0      | 1     | 1                                                 | 0x0000000000000000000000000000000000000000000000000000000000000001 | contracts/perp/PositionManager.sol:PositionManager |
| isUserCancelEnabled           | bool                                                            | 11   | 1      | 1     | 256                                               | 0x0000000000000000000000000000000000000000000000000000000000000100 | contracts/perp/PositionManager.sol:PositionManager |
| allowPublicKeeper             | bool                                                            | 11   | 2      | 1     | 0                                                 | 0x0000000000000000000000000000000000000000000000000000000000000000 | contracts/perp/PositionManager.sol:PositionManager |
| allowUserCloseOnly            | bool                                                            | 11   | 3      | 1     | 16777216                                          | 0x0000000000000000000000000000000000000000000000000000000001000000 | contracts/perp/PositionManager.sol:PositionManager |
| openPositionRequestKeys       | bytes32[]                                                       | 12   | 0      | 32    | 27359                                             | 0x0000000000000000000000000000000000000000000000000000000000006adf | contracts/perp/PositionManager.sol:PositionManager |
| closePositionRequestKeys      | bytes32[]                                                       | 13   | 0      | 32    | 16981                                             | 0x0000000000000000000000000000000000000000000000000000000000004255 | contracts/perp/PositionManager.sol:PositionManager |
| openPositionRequestKeysStart  | uint256                                                         | 14   | 0      | 32    | 27359                                             | 0x0000000000000000000000000000000000000000000000000000000000006adf | contracts/perp/PositionManager.sol:PositionManager |
| closePositionRequestKeysStart | uint256                                                         | 15   | 0      | 32    | 16981                                             | 0x0000000000000000000000000000000000000000000000000000000000004255 | contracts/perp/PositionManager.sol:PositionManager |
| isPositionKeeper              | mapping(address => bool)                                        | 16   | 0      | 32    | 0                                                 | 0x0000000000000000000000000000000000000000000000000000000000000000 | contracts/perp/PositionManager.sol:PositionManager |
| openPositionsIndex            | mapping(address => uint256)                                     | 17   | 0      | 32    | 0                                                 | 0x0000000000000000000000000000000000000000000000000000000000000000 | contracts/perp/PositionManager.sol:PositionManager |
| openPositionRequests          | mapping(bytes32 => struct PositionManager.OpenPositionRequest)  | 18   | 0      | 32    | 0                                                 | 0x0000000000000000000000000000000000000000000000000000000000000000 | contracts/perp/PositionManager.sol:PositionManager |
| closePositionsIndex           | mapping(address => uint256)                                     | 19   | 0      | 32    | 0                                                 | 0x0000000000000000000000000000000000000000000000000000000000000000 | contracts/perp/PositionManager.sol:PositionManager |
| closePositionRequests         | mapping(bytes32 => struct PositionManager.ClosePositionRequest) | 20   | 0      | 32    | 0                                                 | 0x0000000000000000000000000000000000000000000000000000000000000000 | contracts/perp/PositionManager.sol:PositionManager |
| managers                      | mapping(address => bool)                                        | 21   | 0      | 32    | 0                                                 | 0x0000000000000000000000000000000000000000000000000000000000000000 | contracts/perp/PositionManager.sol:PositionManager |
| approvedManagers              | mapping(address => mapping(address => bool))                    | 22   | 0      | 32    | 0                                                 | 0x0000000000000000000000000000000000000000000000000000000000000000 | contracts/perp/PositionManager.sol:PositionManager |
```

**Comment by grandizzy** [comment]
> The #6370 PR mentions further downstream improvements in a PR. Adding an example for bool offset calculating values as not 0 or 1
> 
> reproduce:
> 
> ```
> cast storage --rpc-url https://mainnet.optimism.io --etherscan-api-key T2KRFNUMEN4U8XZQ87YCN82I3AF6XE21NF 0xB67c152E69217b5aCB85A2e19dF13423351b0E27
> ```
> 
> what:
> 
>     * isUserCancelEnabled is a bool and is 256
> 
>     * allowUserCloseOnly is a bool and is 16777216
> 
> 
> ```
> | Name                          | Type                                                            | Slot | Offset | Bytes | Value                                             | Hex Value                                                          | Contract                                           |
> |-------------------------------|-----------------------------------------------------------------|------|--------|-------|---------------------------------------------------|--------------------------------------------------------------------|----------------------------------------------------|
> | gov                           | address                                                         | 0    | 0      | 20    | 1352965747418285184211909460723571462248744342032 | 0x000000000000000000000000ecfd15165d994c2766fbe0d6bacdc2e8dedfd210 | contracts/perp/PositionManager.sol:PositionManager |
> | _status                       | uint256                                                         | 1    | 0      | 32    | 1                                                 | 0x0000000000000000000000000000000000000000000000000000000000000001 | contracts/perp/PositionManager.sol:PositionManager |
> | admin                         | address                                                         | 2    | 0      | 20    | 1352965747418285184211909460723571462248744342032 | 0x000000000000000000000000ecfd15165d994c2766fbe0d6bacdc2e8dedfd210 | contracts/perp/PositionManager.sol:PositionManager |
> | feeCalculator                 | address                                                         | 3    | 0      | 20    | 1297482016264593221714872710065075000476194625473 | 0x000000000000000000000000e3451b170806aab3e24b5cd03a331c1ccdb4d7c1 | contracts/perp/PositionManager.sol:PositionManager |
> | oracle                        | address                                                         | 4    | 0      | 20    | 241116142622541106669066767052022920958068430970  | 0x0000000000000000000000002a3c0592dcb58accd346ccee2bb46e3fb744987a | contracts/perp/PositionManager.sol:PositionManager |
> | referralStorage               | address                                                         | 5    | 0      | 20    | 1224602325975115131568536406232630666650384091454 | 0x000000000000000000000000d6811146780d50d24bd3475acb23c2118034493e | contracts/perp/PositionManager.sol:PositionManager |
> | minExecutionFee               | uint256                                                         | 6    | 0      | 32    | 20000                                             | 0x0000000000000000000000000000000000000000000000000000000000004e20 | contracts/perp/PositionManager.sol:PositionManager |
> | minBlockDelayKeeper           | uint256                                                         | 7    | 0      | 32    | 0                                                 | 0x0000000000000000000000000000000000000000000000000000000000000000 | contracts/perp/PositionManager.sol:PositionManager |
> | minTimeExecuteDelayPublic     | uint256                                                         | 8    | 0      | 32    | 180                                               | 0x00000000000000000000000000000000000000000000000000000000000000b4 | contracts/perp/PositionManager.sol:PositionManager |
> | minTimeCancelDelayPublic      | uint256                                                         | 9    | 0      | 32    | 180                                               | 0x00000000000000000000000000000000000000000000000000000000000000b4 | contracts/perp/PositionManager.sol:PositionManager |
> | maxTimeDelay                  | uint256                                                         | 10   | 0      | 32    | 1800                                              | 0x0000000000000000000000000000000000000000000000000000000000000708 | contracts/perp/PositionManager.sol:PositionManager |
> | isUserExecuteEnabled          | bool                                                            | 11   | 0      | 1     | 1                                                 | 0x0000000000000000000000000000000000000000000000000000000000000001 | contracts/perp/PositionManager.sol:PositionManager |
> | isUserCancelEnabled           | bool                                                            | 11   | 1      | 1     | 256                                               | 0x0000000000000000000000000000000000000000000000000000000000000100 | contracts/perp/PositionManager.sol:PositionManager |
> | allowPublicKeeper             | bool                                                            | 11   | 2      | 1     | 0                                                 | 0x0000000000000000000000000000000000000000000000000000000000000000 | contracts/perp/PositionManager.sol:PositionManager |
> | allowUserCloseOnly            | bool                                                            | 11   | 3      | 1     | 16777216                                          | 0x0000000000000000000000000000000000000000000000000000000001000000 | contracts/perp/PositionManager.sol:PositionManager |
> | openPositionRequestKeys       | bytes32[]                                                       | 12   | 0      | 32    | 27359                                             | 0x0000000000000000000000000000000000000000000000000000000000006adf | contracts/perp/PositionManager.sol:PositionManager |
> | closePositionRequestKeys      | bytes32[]                                                       | 13   | 0      | 32    | 16981                                             | 0x0000000000000000000000000000000000000000000000000000000000004255 | contracts/perp/PositionManager.sol:PositionManager |
> | openPositionRequestKeysStart  | uint256                                                         | 14   | 0      | 32    | 27359                                             | 0x0000000000000000000000000000000000000000000000000000000000006adf | contracts/perp/PositionManager.sol:PositionManager |
> | closePositionRequestKeysStart | uint256                                                         | 15   | 0      | 32    | 16981                                             | 0x0000000000000000000000000000000000000000000000000000000000004255 | contracts/perp/PositionManager.sol:PositionManager |
> | isPositionKeeper              | mapping(address => bool)                                        | 16   | 0      | 32    | 0                                                 | 0x0000000000000000000000000000000000000000000000000000000000000000 | contracts/perp/PositionManager.sol:PositionManager |
> | openPositionsIndex            | mapping(address => uint256)                                     | 17   | 0      | 32    | 0                                                 | 0x0000000000000000000000000000000000000000000000000000000000000000 | contracts/perp/PositionManager.sol:PositionManager |
> | openPositionRequests          | mapping(bytes32 => struct PositionManager.OpenPositionRequest)  | 18   | 0      | 32    | 0                                                 | 0x0000000000000000000000000000000000000000000000000000000000000000 | contracts/perp/PositionManager.sol:PositionManager |
> | closePositionsIndex           | mapping(address => uint256)                                     | 19   | 0      | 32    | 0                                                 | 0x0000000000000000000000000000000000000000000000000000000000000000 | contracts/perp/PositionManager.sol:PositionManager |
> | closePositionRequests         | mapping(bytes32 => struct PositionManager.ClosePositionRequest) | 20   | 0      | 32    | 0                                                 | 0x0000000000000000000000000000000000000000000000000000000000000000 | contracts/perp/PositionManager.sol:PositionManager |
> | managers                      | mapping(address => bool)                                        | 21   | 0      | 32    | 0                                                 | 0x0000000000000000000000000000000000000000000000000000000000000000 | contracts/perp/PositionManager.sol:PositionManager |
> | approvedManagers              | mapping(address => mapping(address => bool))                    | 22   | 0      | 32    | 0                                                 | 0x0000000000000000000000000000000000000000000000000000000000000000 | contracts/perp/PositionManager.sol:PositionManager |
> ```

there's a fix available for this in latest nightly, mind to recheck and report if you see any other discrepancies? thank you

**Comment by grandizzy** [comment]
@mattsse this one can be closed
