### ISSUE TITLE
cast tx --raw should format typed txs as enveloped encoded txs

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#6326]
### Component

Cast

### Describe the feature you would like

currently

https://github.com/foundry-rs/foundry/blob/5692c5cdc01cf75b92f59504de891cdec012b4d1/crates/cast/bin/opts.rs#L397-L399
 
which adheres to the help message:

https://github.com/foundry-rs/foundry/blob/5692c5cdc01cf75b92f59504de891cdec012b4d1/crates/cast/src/lib.rs#L662-L663

however this does not include the type identifier for typed txs.
usually "raw", like in `eth_sendRawTransaction` refers to the EIP-2718 typed transaction envelope format

ref https://eips.ethereum.org/EIPS/eip-2718

## TODO
* change help message
* format typed txs in developed format (prefix with with type byte)

cc @DaniPopes

**Comment by DaniPopes** [comment]
The `.rlp()` is already prefixed with the TX type, should it also be prefixed with the RLP header? cc @Rjected

**Comment by bernard-wagner** [comment]
I wrote the `cast tx --raw` code and have been using it with `eth_sendRawTransaction` and comparing the results with https://etherscan.io/getRawTx?tx=0x. 

Is this still an issue or can we close it? If some work is still needed, happy to look at it again.

**Comment by DaniPopes** [comment]
I think there was a misunderstanding when this issue was opened
