### ISSUE TITLE
forge script `estimated amount required` 100x greater than actual

### ISSUE THREAD

**Issue by tonisives** [foundry-rs/foundry#6336]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (3e12d88 2023-11-17T00:28:12.734710000Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Intel)

### Describe the bug

Script estimates 5$, actual cost is 5cents. For 5$, I started researching what might be the problem (high gas price or wrong contract?)

In the end, the forge script predicted a price that is 100x higher than actual

```
forge script script/mainnet/Script.s.sol:AddProUsers \
  --rpc-url $ARB_MAINNET \
  --ledger \
  --sender 0xme \
  --broadcast -vvvv --verify
```

```
==========================

Chain 42161

Estimated gas price: 3.2 gwei

Estimated total gas used for script: 907546

Estimated amount required: 0.0029041472 ETH

==========================

###
Finding wallets for all the necessary addresses...
##
Sending transactions [0 - 0].
⠁ [00:00:47] [###############################################################################################################################] 1/1 txes (0.0s)
⠉ [00:00:06] [###########################################################################################################################] 1/1 receipts (0.0s)
##### arbitrum
✅  [Success]Hash: 0x3bd...
Block: 151...
Paid: 0.0000586377 ETH (586377 gas * 0.1 gwei)
```

**Comment by onbjerg** [comment]
Can you please share if the gas price was off, or if the estimated gas usage was off?

**Comment by tonisives** [comment]
The network is Arbitrum According to logs, the estimated gas price seems off? 3.2 gwei vs 0.1 gwei in result

**Comment by StillFantastic** [comment]
It happens on Base as well. The estimated gas was 3 gwei but something like 0.000000511 gwei would be sufficient.

**Comment by Evalir** [comment]
Closing as one of many duplicates of gas estimation issues—we're aware, just consolidating the issue tracker at the moment.

**Comment by wminshew** [comment]
@Evalir would you please link what you consider to be the canonical open issue that this one was consolidated into?
