### ISSUE TITLE
eth_subscribe newHeads doesn't appear to work?

### ISSUE THREAD

**Issue by kristian1108** [foundry-rs/foundry#6345]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (3e12d88 2023-11-17T00:33:21.440760000Z)

### What command(s) is the bug in?

anvil -b 1

### Operating System

macOS (Apple Silicon)

### Describe the bug

It appears the latest version of anvil is not correctly handling new block subscriptions.

On the latest version of Anvil `anvil -b 1`, this request comes back with nothing.

```json
{
    "jsonrpc": "2.0",
    "id": 0,
    "method": "eth_subscribe",
    "params": ["newHeads"]
}
```

I discovered this after updating from my old version a few months ago; all of our CI started failing.

I verified this is an issue by installing the previous commit we were using:

```shell
foundryup --commit 7b291d43778be31620a9b45b19a68339f7286f08
```

Then running 

```shell
anvil -b 1
```

New block subscription works as expected.

**Comment by mattsse** [comment]
@DaniPopes this is a regression after bumping axum https://github.com/foundry-rs/foundry/pull/6321

**Comment by mattsse** [comment]
hmm, it looks like it just takes forever to send items for some reason

**Comment by mattsse** [comment]
I think I've figured it out, I encoutered the same thing recently: https://github.com/mattsse/chromiumoxide/pull/179

the underlying poll logic changed
