### ISSUE TITLE
vm.env[type] doesn't work for envs that starts from digit

### ISSUE THREAD

**Issue by smak0v** [foundry-rs/foundry#6359]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (675a824 2023-09-07T00:27:00.029673000Z)

### What command(s) is the bug in?

forge script --rpc-url ${RPC_ETH_GOERLI} --broadcast --verify --optimizer-runs 8000 -vvvv

### Operating System

macOS (Apple Silicon)

### Describe the bug

<img width="930" alt="image" src="https://github.com/foundry-rs/foundry/assets/26391964/3a863014-27ed-4a22-9a75-48c194108017">

**Comment by RedaOps** [comment]
I'm pretty sure this is not a problem with foundry, but it's rust that doesn't really support environment variables that start with a digit. After all, it's not standard:

https://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap08.html#:~:text=Applications%20can%20define%20any%20environment,names%20is%20not%20recommended%20anywhere.
> Other applications may have difficulty dealing with environment variable names that start with a digit. For this reason, use of such names is not recommended anywhere.
> Environment variable names used by the utilities in the Shell and Utilities volume of IEEE Std 1003.1-2001 consist solely of uppercase letters, digits, and the '_' (underscore) from the characters defined in [Portable Character Set](https://pubs.opengroup.org/onlinepubs/009695399/basedefs/xbd_chap06.html#tagtcjh_3) and do not begin with a digit.

Maybe try to change the environment variables names to match the standard. You could change `01_PROXY_ADMIN_INITIAL_OWNER` to `PROXY_ADMIN_INITIAL_OWNER_01`.

**Comment by smak0v** [comment]
Got it
Thank you @RedaOps
