### ISSUE TITLE
`forge verify-contract` panics with invalid ETHERSCAN_API_KEY set

### ISSUE THREAD

**Issue by RedaOps** [foundry-rs/foundry#6376]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (3e962e2 2023-11-20T00:24:11.858869000Z)

### What command(s) is the bug in?

forge verify-contract

### Operating System

macOS (Apple Silicon)

### Describe the bug

In order to test a command, i set the `ETHERSCAN_API_KEY` to 1, and when I ran the `verify-script` command, the thread panicked:

```
The application panicked (crashed).
Message:  failed to extract foundry config:
foundry config error: invalid type: found unsigned int `1`, expected a string for key "ETHERSCAN_API_KEY" in environment variable(s) for setting `etherscan_api_key`

Location: crates/config/src/lib.rs:465

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
```

Expected behaviour: throw error with invalid `ETHERSCAN_API_KEY` set, but not panic.

 ~~PS: Will fix it myself in a new PR.~~ - it seems like everything is handled through the same function, so adding an exact test case that would not fail for just this error is not really a good fix.

**Comment by zerosnacks** [comment]
Now throws a fatal error instead of a panic

```
Error: 
failed to extract foundry config:
foundry config error: invalid type: found signed int `1`, expected a string for setting `etherscan_api_key`
```

And 

```
Encountered an error verifying this contract:
Response: `NOTOK`
Details: `Invalid API Key`
```

When set as an invalid environment variable

Marking as resolved
