### ISSUE TITLE
forge test vm.env `got val: ` logs suppression/silence

### ISSUE THREAD

**Issue by Metaxona** [foundry-rs/foundry#6381]
### Component

Forge

### Describe the feature you would like

Component: forge test
Version: forge 0.2.0 (87283bc 2023-10-06T00:27:02.062949965Z)

So I've been testing my contracts and can't find a way to store a signature generated by a wallet to bytes memory.
During this time I also found a way to bypass this on the `.t.sol` by using `vm.setEnv`  and retrieve the value using `vm.envBytes`

Now my problem is I am using a fuzzer on my test and this `got val:` log is taking all the space on the terminal exceeding it's default limit that using the search feature of the terminal won't even register them since they've been truncated.

Now, I've tried `--silence` which did nothing.

This is making it hard for me to view other test's result / console2.log since they've already been truncated.

so is there a way for us to have a flag or config of some sort that would silence `vm.env` output logs? 

### Additional context

This is an example of the `got val:` logs I am talking about
![image](https://github.com/foundry-rs/foundry/assets/110418886/9f05a327-ba5b-49ff-9167-9e37b0b83954)

**Comment by mattsse** [comment]
what's your `forge --version`?

**Comment by Metaxona** [comment]
> what's your `forge --version`?

ohhh sorry forgot to add that part

```
forge 0.2.0 (87283bc 2023-10-06T00:27:02.062949965Z)
```

**Comment by mattsse** [comment]
I believe I remember this, we forgot to remove a debug println.

please try after foundryup, this has since been fixed

**Comment by Metaxona** [comment]
> I believe I remember this, we forgot to remove a debug println.
> 
> please try after foundryup, this has since been fixed

okay it was not showing now in 
`Version: ` forge 0.2.0 (7b45265 2023-11-21T00:22:00.899582254Z)

still it would be better to have a toggle switch for it, since it is also how i found there was an incorrect in my `vm.setEnv` 

 something like `--log-vm`
