### ISSUE TITLE
failed parsing JSON: key must be a string

### ISSUE THREAD

**Issue by cuhavp** [foundry-rs/foundry#6385]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (1a2e2e0 2023-11-14T00:27:18.137399000Z)

### What command(s) is the bug in?

forge test --match-path test/Fuzz.t.sol -vvv    

### Operating System

None

### Describe the bug

My json file is
```json
{
    "raw": [
        {
            "a": 1,
            "b": 2,
            "expected": 2
        },
        {
            "a": 1,
            "b": 0,
            "expected": 1
        }
    ]
}
```
```
function onlyOneOperandZero_Sets() internal returns (Case[] memory) {
        delete sets;
        string memory testData = vm.readFile("./test/TestData.json");
        string[] memory raw = testData.readStringArray(".raw");
        console.log("sets lenght", raw.length);
        for (uint256 i = 0; i < raw.length; ++i) {
            console.log("set===>", raw[i]);
            bytes memory a = vm.parseJson(raw[i], ".a");
        }
        sets.push(set(0, 1, 1));
        sets.push(set(1, 2, 3));
        return sets;
    }
```
and got error
```sh
Traces:
  [14509] FuzzTest::testTableSums()
    ├─ [0] VM::readFile("./test/TestData.json") [staticcall]
    │   └─ ← <file>
    ├─ [0] VM::parseJsonStringArray("<stringified JSON>", ".raw")
    │   └─ ← ["{a:1,b:2,expected:2}", "{a:1,b:0,expected:1}"]
    ├─ [0] console::9710a9d0(00000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000b73657473206c656e676874000000000000000000000000000000000000000000) [staticcall]
    │   └─ ← ()
    ├─ [0] console::log("set===>", "{a:1,b:2,expected:2}") [staticcall]
    │   └─ ← ()
    ├─ [0] VM::parseJson("<JSON file>") [staticcall]
    │   └─ ← failed parsing JSON: key must be a string at line 1 column 2
    └─ ← failed parsing JSON: key must be a string at line 1 column 2
```

**Comment by mds1** [comment]
`readStringArray` is intended to read a key that contains an array of strings, but your `.raw` key is an array of objects. So you'll notice the JSON it read in (`console::log("set===>", "{a:1,b:2,expected:2}") [staticcall]`) doesn't actually have quotes around the key names and therefore is not valid JSON. See https://book.getfoundry.sh/cheatcodes/parse-json#decoding-json-objects-into-solidity-structs on how you can read that in as an array of solidity structs.

Going to close this but feel free to keep asking any questions here :)

**Comment by klepto** [comment]
Structs are good until you encounter JSON with reserved keywords for keys such as `address` (which is pretty common when it comes to web3 related data). For cases those cases the only work-around I found so far is re-parsing entire JSON file for each array entry with different selector which is very hacky and slow. Ability to traverse JSON tree without abi-encoding would add a lot of flexibility.

**Comment by mds1** [comment]
The names in your struct do not have match the JSON key names. I admit it is confusing, but if you have suggestions or issues please open a new issue :) https://book.getfoundry.sh/cheatcodes/parse-json#decoding-json-objects-into-solidity-structs
