### ISSUE TITLE
Member "mockCall" not found or not visible after argument-dependent lookup in contract Vm. solidity(9582)

### ISSUE THREAD

**Issue by czar0** [foundry-rs/foundry#6387]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (7b45265 2023-11-21T00:18:30.267248000Z)

### What command(s) is the bug in?

forge test -vvvv

### Operating System

macOS (Apple Silicon)

### Describe the bug

I am trying to use the `mockCall` function in a test file as described in the [book](https://book.getfoundry.sh/cheatcodes/mock-call), but the compiler doesn't seem to recognise the exported (external) `mockCall` from the imported `forge-std/Test.sol` contract (`Vm`).
All the other `vm`'s functions in the snippet below work with no issues.

Code snippet:

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.17;

import "forge-std/Test.sol";

contract SafePayoutsModuleTest is Test {
   ...

    function test_executePayouts_OperatorIsAllowed() public {
        vm.deal(address(safeAccount), 10 ether);
        assertEq(address(safeAccount).balance, 10 ether);

        vm.startPrank(address(this));
        payoutsModule.addPayout(alice, 1 ether); 
        payoutsModule.addPayout(bob, 2 ether); 
        payoutsModule.addPayout(charlie, 3 ether);
        vm.stopPrank();

        vm.mockCall(
            safeAccount,
            0,
            abi.encodeWithSelector(safeAccount.execTransactionFromModule.selector, address(alice), 1 ether, "", 0),
            abi.encode(true)
        );
 
        ...

   }
}
```

Error log:

```bash
➜ forge test -vvvv                             
[⠰] Compiling...
[⠆] Compiling 12 files with 0.8.23
[⠰] Solc 0.8.23 finished in 886.64ms
Error: 
Compiler run failed:
Error (9582): Member "mockCall" not found or not visible after argument-dependent lookup in contract Vm.
   --> test/SafePayoutsModule.t.sol:126:9:
    |
126 |         vm.mockCall(
    |         ^^^^^^^^^^^
```

**Comment by DaniPopes** [comment]
What type is `safeAccount`? I see you used `address(safeAccount)` above so can you try that?
