### ISSUE TITLE
Automatically label known contract addresses in traces

### ISSUE THREAD

**Issue by fubhy** [foundry-rs/foundry#639]
### Component

Forge

### Describe the feature you would like

With the new `vm.label` cheat code, it's now possible to manually assign labels to addresses.

In addition to manually assigning labels, as discussed in the original issue (https://github.com/gakonst/foundry/issues/553), it would be great to automatically derive labels for known contracts, instead of having to do

```solidity
...
address myContract = new MyContract();
vm.label(myContract, "MyContract");
...
```

**Comment by onbjerg** [comment]
Is this not already the case?

**Comment by fubhy** [comment]
> Is this not already the case?

I'm currently caught up in other tasks so haven't had a chance to check out the latest versions of foundry in ~3-4 weeks. Not sure if this was added in the meantime.

This issue was about automatically labeling the addresses of known contract instances in log output & stack traces e.g. when those addresses appear in event payloads or similar.

**Comment by onbjerg** [comment]
This should be fixed, so I'm closing - let me know if this is not the case and I can investigate :smile:
