### ISSUE TITLE
Foundry does not auto format on save anymore using latest forge in Vscode

### ISSUE THREAD

**Issue by 0xTimepunk** [foundry-rs/foundry#6397]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (7b45265 2023-11-21T00:18:30.267248000Z)

### What command(s) is the bug in?

forge fmt

### Operating System

macOS (Apple Silicon)

### Describe the bug

When saving a file in vscode with auto save enabled, forge does not auto format the file anymore, even though nothing was changed in fmt settings in foundry.toml

This only started to happen in the most recent foundry version.

Using vscode Version: 1.84.2 (latest version)

**Comment by mattsse** [comment]
just to summarize, invoking `forge fmt` directly works as expected but auto formatting does not?

**Comment by 0xTimepunk** [comment]
Connected with https://github.com/microsoft/vscode/issues/198791 but potentially unrelated to foundry itself

**Comment by DaniPopes** [comment]
We don't maintain VSCode extensions, this is out of scope for this repo

**Comment by 0xTimepunk** [comment]
> We don't maintain VSCode extensions, this is out of scope for this repo

This is not about VSCode extensions, but agree in out of scope
