### ISSUE TITLE
 Memory Bug in Test

### ISSUE THREAD

**Issue by goheesheng** [foundry-rs/foundry#6407]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (0e33b3e 2023-07-26T07:07:06.336177323Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

## Bug Description:
I encountered a memory bug while writing a test case using the Foundry framework. The error message indicates an invalid type for an argument in a function call, specifically an invalid implicit conversion from enum CoinType to enum CoinType requested. The relevant code snippet is as follows:
```solidity
// SPDX-License-Identifier: MIT
pragma solidity 0.8.7;

import {Test, console2} from "forge-std/Test.sol";
import { ZRC20 } from "../../contracts/zevm/ZRC20.sol";
import { SystemContractMock } from "../../contracts/zevm/testing/SystemContractMock.sol";
import "./Interfaces.sol";

contract zrc20_interface is Test {
    ZRC20 public zrc20;
    SystemContractMock public systemContract;
    CoinType cointype;

    function setUp() public {
        cointype = CoinType.Zeta;
        systemContract = new SystemContractMock(address(0), address(0), address(0));
        zrc20 = new ZRC20("TOKEN","TKN",18,1,cointype,0,address(systemContract));
    }
}
```
## Explanation:
If contract A imports B, and when you write a contract that imports the same context in B but in a different file C. There issue will occur.

The enum CoinType is defined in Interfaces.sol, and it seems there might be an issue with how it is imported in the test case.
```diff

import {Test, console2} from "forge-std/Test.sol";
-- import { ZRC20 } from "../../contracts/zevm/ZRC20.sol";
++ import { ZRC20, CoinType } from "../../contracts/zevm/ZRC20.sol";
import { SystemContractMock } from "../../contracts/zevm/testing/SystemContractMock.sol";
-- import "./Interfaces.sol";
```
The error:
```
Error (9553): Invalid type for argument in function call. Invalid implicit conversion from enum CoinType to enum CoinType requested.
  --> test/foundry/zrc20_interface.t.sol:16:46:
   |
16 |         zrc20 = new ZRC20("TOKEN","TKN",18,1,cointype,0,address(systemContract));
   |       
```

## Expected Behavior:
The contract should compile successfully without any memory-related errors.

## Actual Behavior:
The compiler throws an error related to an invalid type for an argument in a function call.

## Recommendation:
Create a new error log that specify the issue correctly to increase efficiency in debugging.

**Comment by kamikazebr** [comment]
Got similiar error but using structs in storage when i try use that as memory it give me that error.

`Error (9553): Invalid type for argument in function call. Invalid implicit conversion from struct Metadata storage ref to struct Metadata memory requested.`

**Comment by goheesheng** [comment]
> Got similiar error but using structs in storage when i try use that as memory it give me that error.
> 
> `Error (9553): Invalid type for argument in function call. Invalid implicit conversion from struct Metadata storage ref to struct Metadata memory requested.`

Do show the codes for clarity thanks

**Comment by zerosnacks** [comment]
Marking as resolved, most errors are related to the Solidity compiler throwing errors

Remappings can be spotty and sometimes require manual mapping
