### ISSUE TITLE
Make `CommentWithMetadata` public in the `forge-fmt` crate

### ISSUE THREAD

**Issue by alexfertel** [foundry-rs/foundry#6409]
### Component

Forge

### Background

I'm currently working on https://github.com/alexfertel/bulloak/issues/30, for which I needed a way to emit a `solang_parser::pt`. I settled on using `forge-fmt`, since it emits a formatted string.

### Problem

I'm building the parse tree myself, and not by parsing but by translating a custom tree structure into a parse tree. This means that I don't have a source string (`src`) to pass to `Comments::new(comments, src)`.

### Request

Make `CommentWithMetadata` part of the public API  (and probably the whole `comments` module as well). This solves the issue because I can call `CommentWithMetadata::new()`, which doesn't have the source string requirement.

I'm expecting this to be a trivial change, so I'm happy to do it myself.

**Comment by mattsse** [comment]
reasonable

**Comment by alexfertel** [comment]
> reasonable

Nice! Should I give it a go?

**Comment by mattsse** [comment]
please go for it, 
supportive of making all internals pub that you need

**Comment by alexfertel** [comment]
After going forward with the above, I realized that I still can't use `forge-fmt` only as an emitter. This stems from the requirement `Formatter::new()` has on a `source: &'a str`. I need a thing that given a `solang_parser::pt` prints its solidity string.

I think we can close this issue since I'll have to write my own anyway.
