### ISSUE TITLE
forge create fails with address[] constructor arguments

### ISSUE THREAD

**Issue by izcoser** [foundry-rs/foundry#6415]
### Component

Forge, Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (89f74f2 2023-11-23T00:16:20.422885370Z)

### What command(s) is the bug in?

forge create

### Operating System

Linux

### Describe the bug

I am trying to deploy a contract using forge create and cast.
The command:

`forge create --rpc-url https://ethereum-sepolia.publicnode.com --private-key pk src/A.sol:A --constructor-args $(cast abi-encode "constructor(address[],address)" [0x4838b106fce9647bdf1e7877bf73ce8b0bad5f97,0x4838b106fce9647bdf1e7877bf73ce8b0bad5f97] 0x4838b106fce9647bdf1e7877bf73ce8b0bad5f97)`

I get this error:

```
Error: 
parser error:
0x00000000000000000000000000000000000000000000000000000000000000400000000000000000000000004838b106fce9647bdf1e7877bf73ce8b0bad5f9700000000000000000000000000000000000000000000000000000000000000020000000000000000000000004838b106fce9647bdf1e7877bf73ce8b0bad5f970000000000000000000000004838b106fce9647bdf1e7877bf73ce8b0bad5f97
 ^
expected `[`

Context:
- parser error:
0x00000000000000000000000000000000000000000000000000000000000000400000000000000000000000004838b106fce9647bdf1e7877bf73ce8b0bad5f9700000000000000000000000000000000000000000000000000000000000000020000000000000000000000004838b106fce9647bdf1e7877bf73ce8b0bad5f970000000000000000000000004838b106fce9647bdf1e7877bf73ce8b0bad5f97
 ^
expected `[`

```

The contract in question:
```
pragma solidity ^0.8.13;

contract A {
    constructor(address[] memory a, address b) {}
}

```

**Comment by mattsse** [comment]
paging @DaniPopes

**Comment by DaniPopes** [comment]
You have to put quotes around parentheses and brackets because of shell expansions:
```bash
$ cast abi-encode "constructor(address[],address)" "[0x4838b106fce9647bdf1e7877bf73ce8b0bad5f97,0x4838b106fce9647bdf1e7877bf73ce8b0bad5f97]" 0x4838b106fce9647bdf1e7877bf73ce8b0bad5f97
0x00000000000000000000000000000000000000000000000000000000000000400000000000000000000000004838b106fce9647bdf1e7877bf73ce8b0bad5f9700000000000000000000000000000000000000000000000000000000000000020000000000000000000000004838b106fce9647bdf1e7877bf73ce8b0bad5f970000000000000000000000004838b106fce9647bdf1e7877bf73ce8b0bad5f97
```

**Comment by DaniPopes** [comment]
And in this case, `--constructor-args` expects a list of arguments to encode, not the already-encoded arguments with `$(cast abi-encode)`:
```bash
forge create --rpc-url https://ethereum-sepolia.publicnode.com --private-key pk src/A.sol:A --constructor-args "[0x4838b106fce9647bdf1e7877bf73ce8b0bad5f97,0x4838b106fce9647bdf1e7877bf73ce8b0bad5f97]" 0x4838b106fce9647bdf1e7877bf73ce8b0bad5f97
```

**Comment by izcoser** [comment]
> And in this case, `--constructor-args` expects a list of arguments to encode, not the already-encoded arguments with `$(cast abi-encode)`:
> 
> ```shell
> forge create --rpc-url https://ethereum-sepolia.publicnode.com --private-key pk src/A.sol:A --constructor-args "[0x4838b106fce9647bdf1e7877bf73ce8b0bad5f97,0x4838b106fce9647bdf1e7877bf73ce8b0bad5f97]" 0x4838b106fce9647bdf1e7877bf73ce8b0bad5f97
> ```

verify-contract requires the encoded abi so I thought create worked the same way. Thank you.
