### ISSUE TITLE
`forge bind` generates a Rust binding with clashing "events" functions

### ISSUE THREAD

**Issue by serejke** [foundry-rs/foundry#6421]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0

### What command(s) is the bug in?

forge bind

### Operating System

macOS (Apple Silicon)

### Description
If a contract has a public field `events`
`mapping(bytes32 eventHash => bool) public events;`

`forge bind` fails to generate a compilable Rust binding:
 
```
error[E0592]: duplicate definitions with name `events`
   --> src/gmp_event_verifier.rs:807:9
    |
639 | /         pub fn events(
640 | |             &self,
641 | |             event_hash: [u8; 32],
642 | |         ) -> ::ethers::contract::builders::ContractCall<M, bool> {
    | |________________________________________________________________- other definition for `events`
...
807 | /         pub fn events(
808 | |             &self,
809 | |         ) -> ::ethers::contract::builders::Event<
810 | |             ::std::sync::Arc<M>,
811 | |             M,
812 | |             GMPEventVerifierEvents,
813 | |         > {
    | |_________^ duplicate definitions for `events`

error[E0592]: duplicate definitions with name `events`
    --> src/gmp_intent_event_verifier.rs:996:9
     |
801  | /         pub fn events(
802  | |             &self,
803  | |             event_hash: [u8; 32],
804  | |         ) -> ::ethers::contract::builders::ContractCall<M, bool> {
     | |________________________________________________________________- other definition for `events`
```

**Comment by mattsse** [comment]
ah yeah that's an edge case

hmm since `pub fn events(&self)` is not part of a trait, I think we should check if that name is conflicting with any field getters and rename that, like `contract_events` or something

**Comment by zerosnacks** [comment]
Unable to reproduce with `forge bind` (ethers) or `forge bind --alloy`, bindings are generated correctly.

Assuming this has been resolved

If you are able to reproduce the error, particularly with `--alloy` feel free to re-open.
