### ISSUE TITLE
feat(forge verify-contract): support fully verifying a partially-verified contract

### ISSUE THREAD

**Issue by tsite** [foundry-rs/foundry#6424]
### Component

Forge

### Describe the feature you would like

`forge verify-contract` does not attempt to re-verify an already-verified contract as this is an expensive operation. However there are some cases in which this behavior is desired e.g. to re-verify a partially-verified contract with source code that matches the metadata hash. I suggest adding a flag `--ignore-already-verified` to the verifier command-line arguments to skip the contract already verified check.

**Comment by mattsse** [comment]
closed by #6461
