### ISSUE TITLE
bug: `forge doc` does not parse unordered lists correctly

### ISSUE THREAD

**Issue by guidanoli** [foundry-rs/foundry#6425]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (55dd5de 2023-11-24T00:16:54.792480251Z)

### What command(s) is the bug in?

forge doc

### Operating System

Linux

### Describe the bug

I document several contracts with NatSpec.
In some of these comments, more specifically in `@notice` tags, I like to add unordered lists. The problem is that in the HTML pages compiled by `forge doc`, everything that comes after these unordered lists is also part of the unordered list, even after empty lines.

Here is an example Solidity contract:

```solidity
// SPDX-License-Identifier: Apache-2.0 (see LICENSE)

pragma solidity ^0.8.8;

/// @notice Here is a list of fruits:
///
/// * bananas
/// * apples
/// * pears
///
/// And here is a list of shapes:
///
/// * circle
/// * square
/// * triangle
///
contract Foo {}
```

Here is the relevant part of the HTML output:

```html
<p>Here is a list of fruits:</p>
<ul>
<li>bananas</li>
<li>apples</li>
<li>pears
And here is a list of shapes:</li>
<li>circle</li>
<li>square</li>
<li>triangle</li>
</ul>
```

What I expected was something like this instead:

Here is the relevant part of the HTML output:

```html
<p>Here is a list of fruits:</p>
<ul>
<li>bananas</li>
<li>apples</li>
<li>pears</li>
</ul>
<p>And here is a list of shapes:</p>
<ul>
<li>circle</li>
<li>square</li>
<li>triangle</li>
</ul>
```

**Comment by guidanoli** [comment]
One workaround is to start the new paragraph with `@notice` but I think this current behavior is unexpected and could be handled by `forge doc`.

**Comment by zerosnacks** [comment]
Able to reproduce, indeed generates as:

```html
<p>Here is a list of fruits:</p>
<ul>
<li>bananas</li>
<li>apples</li>
<li>pears
And here is a list of shapes:</li>
<li>circle</li>
<li>square</li>
<li>triangle</li>
</ul>
```
