### ISSUE TITLE
The 'forge --via-ir' compilation option leads to a contract running state that is inconsistent with expectations

### ISSUE THREAD

**Issue by fpChan** [foundry-rs/foundry#6430]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

 0.2.0 (3e12d88 2023-11-17T00:33:21.440760000Z)

### What command(s) is the bug in?

--via-ir

### Operating System

macOS (Apple Silicon)

## source code
```sol
        uint256 startAt = block.timestamp;
        console2.log("startAt %d now %d", startAt, block.timestamp);
        vm.warp(startAt + 1 days);
        console2.log("startAt %d now %d", startAt, block.timestamp);
```

## run without --via-ir
`forge test --match-contract CounterTest  -vv`
The result meets expectations.
```
Logs:
  startAt 1 now 1
  startAt 1 now 86401
```

## run with --via-ir
`forge test --match-contract CounterTest  -vv  --via-ir`
The result does not meet expectations.
```
Logs:
  startAt 1 now 1
  startAt 86401 now 86401
```

<img width="792" alt="image" src="https://github.com/foundry-rs/foundry/assets/29588923/efa34624-585f-423a-828f-5b7894a365e9">

**Comment by Evalir** [comment]
`--via-ir` introduces quite a few optimizations which can make a lot of things, including sourcemaps, innacurate. What you're seeing is your code being optimized in the logs. You can disable certain optimizations for IR compilation, but in general we recommend running tests without ir. See https://github.com/ethereum/solidity/issues/12533

**Comment by mds1** [comment]
For workarounds, see the convo + linked items at https://github.com/foundry-rs/foundry/issues/4934#issuecomment-1546667682
