### ISSUE TITLE
BUG: Undeflow when running unit tests

### ISSUE THREAD

**Issue by Brianspha** [foundry-rs/foundry#6436]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (dbd935b 2023-10-17T06:28:15.598998000Z)

### Operating System

macOS (Apple Silicon)

### Describe the bug

There seems to be a bug that very random whenever I try to run unit tests the error seems to occur here

``rust
  JournalEntry::NonceChange { address } => {
                    state.get_mut(&address).unwrap().info.nonce -= 1;
                }
``
I would suggest we check if the nonce is greater than 0 like 

``rust
  if let Some(entry) = state.get_mut(&address) {
                        if entry.info.nonce > 0 {
                            entry.info.nonce -= 1;
                        }
                    }
``

**Comment by mattsse** [comment]
> to occur here

where is that?

**Comment by Brianspha** [comment]
```
The application panicked (crashed).
Message:  attempt to subtract with overflow
Location: /Users/siphamandlamjoli/.cargo/registry/src/index.crates.io-6f17d22bba15001f/revm-3.5.0/src/journaled_state.rs:387
```

**Comment by Brianspha** [comment]
I just ran ``forge test -vvvv``

**Comment by Evalir** [comment]
@Brianspha could you try doing `foundryup` and then running the test again? If it happens, could you post a way to reproduce this bug so we can look into it more easily?

**Comment by Brianspha** [comment]
```
forge test  --match-path ./test/foundry/intergration/FeeStructure.t.sol
[⠰] Compiling...
No files changed, compilation skipped
The application panicked (crashed).
Message:  attempt to subtract with overflow
Location: /Users/xxx/.cargo/git/checkouts/revm-bf744d8ffabcbad9/b00ebab/crates/revm/src/journaled_state.rs:332

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
zsh: abort      forge test --match-path ./test/foundry/intergration/FeeStructure.t.sol
```

**Comment by Brianspha** [comment]
```
forge test -vvvv --match-path ./test/foundry/intergration/FeeStructure.t.sol
[⠆] Compiling...
No files changed, compilation skipped
The application panicked (crashed).
Message:  attempt to subtract with overflow
Location: /Users/xxx/.cargo/git/checkouts/revm-bf744d8ffabcbad9/b00ebab/crates/revm/src/journaled_state.rs:332

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
zsh: abort      forge test -vvvv --match-path ./test/foundry/intergration/FeeStructure.t.sol
```

**Comment by mattsse** [comment]
do you have a repro for this?

**Comment by Brianspha** [comment]
Unfortunately, it's a private repo, but what I can say is my unit tests are forking 3 networks this happens a lot when I do this and run unit tests switching between the forks maybe I'm mistaking but regular tests without any forking are fine

**Comment by mattsse** [comment]
yeah this sounds like a forking issue.
likely when a revert happens.
it would be super helpful if you could provide a minimal reproducible example.

I think this happens when forks are switched and then there's a revert

**Comment by DaniPopes** [comment]
It has been a while since this issue was created, and I believe we have had some fixes to forking since then.
