### ISSUE TITLE
`vm.parseJsonAddressArray` throwing error with no data.

### ISSUE THREAD

**Issue by morelazers** [foundry-rs/foundry#6437]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6432031 2023-11-27T00:19:19.837119000Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

An error started popping up in CI runs and I'm trying to get to the bottom of why these lines of code don't work. Hopefully someone can point me in the right direction:

```
string memory json = "[\"0x0000000000000000000000000000000000000000\"]";
console.log(json); // prints correctly
address[] memory arr = vm.parseJsonAddressArray(json, "$");
console.log("here"); // does not print at all
```

The only error that I receive is:

```
"script failed: <no data>"
```

Cheers!

**Comment by mattsse** [comment]
ptal @DaniPopes
