### ISSUE TITLE
`--skip` doesn't filter out scripts correctly

### ISSUE THREAD

**Issue by ZeroEkkusu** [foundry-rs/foundry#6482]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (f5c9199 2023-12-01T00:23:15.670999000Z)

### What command(s) is the bug in?

forge build

### Operating System

macOS (Apple Silicon)

### Describe the bug

**`--skip` doesn't filter out scripts correctly**

<br>

❌ Neither `script` nor `.s.sol` filters scripts out:

```
forge build --skip script .s.sol
```

✅ Only `s.sol` works correctly:

```
forge build --skip s.sol
```

**Comment by zerosnacks** [comment]
Marking as resolved

Now filters both: `.s.sol` and `s.sol`
