### ISSUE TITLE
`forge test` can't locate files on Windows system.

### ISSUE THREAD

**Issue by kongtaoxing** [foundry-rs/foundry#6496]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (5b7e4cb 2023-12-02T08:29:53.916542100Z)

### What command(s) is the bug in?

forge test

### Operating System

Windows

### Describe the bug

I run the following code to create a new project
```sh
forge init hello_foundry
```
And enter the project folder, run `forge test`, got errors belows
```
$ forge test
[⠊] Compiling...
[⠒] Unable to resolve imports:
      "ds-test/test.sol" in "D:/Users/Hasee/Desktop/hello_foundry/lib/forge-std/src/StdAssertions.sol"
      "ds-test/test.sol" in "D:/Users/Hasee/Desktop/hello_foundry/lib/forge-std/src\Test.sol"
with remappings:
[⠢] Unable to resolve imports:e/Desktop/hello_foundry/lib/forge-std/src/
      "ds-test/test.sol" in "D:/Users/Hasee/Desktop/hello_foundry/lib/forge-std/src/StdAssertions.sol"
      "ds-test/test.sol" in "D:/Users/Hasee/Desktop/hello_foundry/lib/forge-std/src\Test.sol"
with remappings:
      forge-std/=D:/Users/Hasee/Desktop/hello_foundry/lib/forge-std/src/
[⠔] Compiling 23 files with 0.8.23
[⠒] Solc 0.8.23 finished in 230.42ms
Error:
Compiler run failed:
Error (6275): Source "ds-test/test.sol" not found: File not found. Searched the following locations: "/Users/Hasee/Desktop/hello_foundry".
 --> lib/forge-std/src/StdAssertions.sol:4:1:
  |
4 | import {DSTest} from "ds-test/test.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error (6275): Source "ds-test/test.sol" not found: File not found. Searched the following locations: "/Users/Hasee/Desktop/hello_foundry".
  --> lib/forge-std/src/Test.sol:27:1:
   |
27 | import {DSTest} from "ds-test/test.sol";
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Linux is ok, but run the project on Windows got errors.

**Comment by rspadinger** [comment]
Specifying the forge template works: forge init --template https://github.com/foundry-rs/forge-template test

**Comment by kongtaoxing** [comment]
> Specifying the forge template works: forge init --template https://github.com/foundry-rs/forge-template test

I've already fix it, but thank you anyway.

**Comment by tvirgg** [comment]
> > Specifying the forge template works: forge init --template https://github.com/foundry-rs/forge-template test
> 
> I've already fix it, but thank you anyway.

how ?

**Comment by rok4f** [comment]
Run
```
git submodule update --progress --init
```
in directory  `lib/forge-std` will pull the source code of DSTest for you
