### ISSUE TITLE
Cannot set variables with 'setter' functions  

### ISSUE THREAD

**Issue by stefante** [foundry-rs/foundry#6497]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (5b7e4cb 2023-12-02T00:23:06.838679000Z)

### Operating System

macOS (Apple Silicon)

### Describe the bug

when trying to write a 'setter function' like, 

_function setNumber(int _newNumber) public {
        number = _newNumber;
    }_

with 'number' being a contract variable (private or public does not matter, also variable type does not matter).

Forge test, forg build etc. work. 

However wenn running it against a blockchain (tried Sepolia, Goerli, Anvil) with the following command

_cast send $ConAddress "setNumber(5)" --private-key $PrivKey --rpc-url $RPC_URL_ 

I get the following error message 

_invalid AbiItem keyword: "setNumber", expected one of "constructor", "function", "error", or "event"_

Thanks

**Comment by DaniPopes** [comment]
"setNumber(5)" is not a valid function signature; it's probably "setNumber(uint256)", with an argument of 5, so `cast send address "setNumber(uint256)" 5 ...`

**Comment by stefante** [comment]
Thanks a lot @DaniPopes
