### ISSUE TITLE
console.log() does not work with uint

### ISSUE THREAD

**Issue by ckksec** [foundry-rs/foundry#6501]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (1529edd 2023-12-01T15:45:10.088350100Z) but also tested on a version 2023-06-XX something

### What command(s) is the bug in?

forge test (-vvvvv)

### Operating System

Windows

### Describe the bug

`console.log(...)` is not recognized in the stack trace when working with numbers, for example uint, int, etc. The same goes for `console.logUint(...)` or `console.logInt(...)`. The function is output with its signature in the stack trace instead of a "human readable" `[0] console::log("")`. In my examples I used it as an additional parameter, but also just using `console.log(num)` where `num` is any number (type) does not work properly. However, `console2.log(...)` works fine. But that on the other hand does not support parameter replacing, so e.g. `console2.log("A string %s in a string!", "< I am a string >");` does not work, the `%s` is not replaced (not sure if it's a bug or just working as should for `console2.log(...)`).
<img width="494" alt="num1" src="https://github.com/foundry-rs/foundry/assets/85028981/60575309-b168-4fe7-87e2-5e098509dd11">
<img width="280" alt="num2" src="https://github.com/foundry-rs/foundry/assets/85028981/1675041f-ba01-428a-a6fb-f8b1edd303b4">

**Comment by mattsse** [comment]
@DaniPopes hmm maybe we're missing these log signatures during decoding?

**Comment by DaniPopes** [comment]
I don't think we ever decoded hardhat `console` (*not* `console2`) due to their non-conformance with ABI.

**Comment by DaniPopes** [comment]
@ckksec

> but also tested on a version 2023-06-XX something

Were the screenshots taken with the older version?

Anyway, this should be fixed in #6504; you can try with `foundryup --pr 6504` (builds from source).
