### ISSUE TITLE
Mapping Deletion Retains Previous Value - Chisel Bug Detected

### ISSUE THREAD

**Issue by bala-Blockchian** [foundry-rs/foundry#6507]
### Component

Chisel

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (d369d24 2023-07-02T00:05:10.773939000Z)

### What command(s) is the bug in?

chisel

### Operating System

macOS (Apple Silicon)

### Describe the bug

---
**Title:** Mapping Element Deletion Issue in Chisel
---

**Description:**
### Bug Summary
When attempting to delete a mapping element in the `token2token` mapping, the expected behavior is to have the deleted element return `0x0000000000000000000000000000000000000000`. However, the current behavior after deletion is returning `0x0000000000000000000000000000000000000002`, which doesn’t reflect the expected outcome.

### Steps to Reproduce
1. Assign a value to `token2token[address(1)]` (e.g., `token2token[address(1)] = address(2)`)
2. Verify the value of `token2token[address(1)]` to confirm it's `address(2)`
3. Attempt to delete the element using `delete token2token[address(1)]`
4. Check the value of `token2token[address(1)]` post-deletion

### Code Snippet
```solidity
mapping (address => address) public token2token;

// Assigning a value to token2token[address(1)]
token2token[address(1)] = address(2);

// Verifying the value before deletion
// Expected: address(2)
// Actual: address(2)
address valueBeforeDeletion = token2token[address(1)];

// Attempting to delete the element
delete token2token[address(1)];

// Checking the value after deletion
// Expected: 0x0000000000000000000000000000000000000000
// Actual: 0x0000000000000000000000000000000000000002
address valueAfterDeletion = token2token[address(1)];
```

### Expected Outcome
After deletion (`delete token2token[address(1)]`), the value of `token2token[address(1)]` should return `0x0000000000000000000000000000000000000000`.

### Actual Outcome
Instead of returning `0x0000000000000000000000000000000000000000` after deletion, the value of `token2token[address(1)]` is `0x0000000000000000000000000000000000000002`.

**Comment by clabby** [comment]
hm, unable to reproduce this. Can you attach the underlying source via `!so`?

![Screenshot 2023-12-04 at 9 32 08 AM](https://github.com/foundry-rs/foundry/assets/8406232/49f972f7-cfe8-449c-92fa-1ff65decee20)
