### ISSUE TITLE
Help Installing Foundry, Error curl: (60) SSL certificate problem: certificate has expired

### ISSUE THREAD

**Issue by cozymfer** [foundry-rs/foundry#6512]
### Discussed in https://github.com/foundry-rs/foundry/discussions/6510

<div type='discussions-op-text'>

<sup>Originally posted by **cozymfer** December  3, 2023</sup>
Trying to install Foundry for the first time using the first command instructed

```
curl -L https://foundry.paradigm.xyz | bash
```

but it doesnt install

```
 % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html
curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
HTTPS-proxy has similar options --proxy-cacert and --proxy-insecure.
```
very new to coding in general any help would be much appreciated. Not sure how to approach this or any other ways to download or just use one of the proxy commands and trust it? 
</div>

**Comment by onbjerg** [comment]
Please ensure your time is accurate on your computer. The certificate has certainly not expired :)

**Comment by cozymfer** [comment]
I dont know exactly how to change my comp to start getting correct certificates many things i try to curl and i still receive same (60) code. but my resolution was to get the code from the site and manually execute it as a script. I foundryup and it installed thanks for the help current issue resolved

**Comment by saurabhf89** [comment]
@cozymfer Getting same SSL certification issue. Can you please explain how did you get code from site?
