### ISSUE TITLE
Running "forge install" in a project with no submodule dependencies does not work

### ISSUE THREAD

**Issue by PaulRBerg** [foundry-rs/foundry#6519]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (d4e6b43 2023-12-04T00:30:25.537736000Z)

### What command(s) is the bug in?

forge install

### Operating System

macOS (Apple Silicon)

### Describe the bug

Running `forge install` in a project with no submodule dependencies does not work. Forge will produce the following error:

```text
Updating dependencies in /Users/prb/Projects/prb-proxy/lib
error: pathspec '/Users/prb/Projects/prb-proxy/lib' did not match any file(s) known to git
Error:
git submodule exited with code 1
```

It looks like Foundry assumes that there is a `lib` directory and that there are some submodules in there.

You can quickly reproduce the bug using [PRBProxy](https://github.com/PaulRBerg/prb-proxy) and the instructions provided here:

https://github.com/crytic/slither-action/issues/44#issuecomment-1838832654

This is a blocker so a fix would be appreciated 🙏 

Cc @DaniPopes @mattsse

**Comment by sambacha** [comment]
congrats, we can finally close this issue now #2649
