### ISSUE TITLE
Bug: forge bind fails to convert file name if out/bindings directory is present

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#6524]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

87bf7e4 2023-12-03T00:19:35.001371000Z

### What command(s) is the bug in?

forge bind

### Operating System

macOS (Apple Silicon)

### Describe the bug

# forge bind fails if bindings alrdy exist

Running `forge bind` twice generates this error

```bash
$ forge  bind
[⠒] Compiling...
No files changed, compilation skipped
Bindings found. Checking for consistency.
Error:
failed to parse Abigen from file: "/Users/**/meveth3/out/bindings/target/.rustc_info.json"

Context:
- Error #0: failed convert file name to contract identifier /Users/**/meveth3/out/bindings/target/.rustc_info.json
- Error #1: unexpected end of input, expected identifier
```

## Fixing

```bash
rm -rf out/bindings
forge bind
[⠒] Compiling...
No files changed, compilation skipped
Generating bindings for 99 contracts
Bindings have been output to /Users/**/meveth3/out/bindings
```

**Comment by zerosnacks** [comment]
Whilst this is indeed still an issue for `ethers-rs` we have since upgraded to use `alloy`

Re-running `forge bind --alloy` multiple times yields:

```
forge bind --alloy
[⠊] Compiling...
No files changed, compilation skipped
Generating bindings for 9 contracts
Bindings have been generated to /home/zerosnacks/Projects/counter/out/bindings

forge bind --alloy
[⠒] Compiling...
No files changed, compilation skipped
Bindings found. Checking for consistency.
Checking bindings for 9 contracts
OK.
```

Marking as `resolved` as `ethers-rs` is not recommended anymore and no longer maintained
