### ISSUE TITLE
Chisel Mapping issues after delete

### ISSUE THREAD

**Issue by touqeerShah** [foundry-rs/foundry#6528]
### Component

Chisel

### Have you ensured that all of these are up to date?

- [x] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (5b7e4cb 2023-12-02T00:18:06.256766369Z)

### Operating System

macOS (Apple Silicon)

### Describe the bug

When I create mapping and assign value to it , even i delete it still return the values but when I try with `Remix` it work fine please check this one 

```
  mapping(address => address) public s_tokenToAssetToken;

➜ s_tokenToAssetToken[address(1)] = address(2)
Type: address
└ Data: 0x0000000000000000000000000000000000000002
➜ delete s_tokenToAssetToken[address(1)]
➜ s_tokenToAssetToken[address(1)] 
Type: address
└ Data: 0x0000000000000000000000000000000000000002
```

**Comment by DaniPopes** [comment]
You need to add a semicolon `;` to the end of the `delete ..`, otherwise it gets interpreted as an expression and not added to the context

**Comment by touqeerShah** [comment]
yes that works
