### ISSUE TITLE
Extend RpcEndpoints with more fork settings

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#6532]
### Component

Forge

### Describe the feature you would like

currently 

the rpc endpoints table only supports the URL

```
[rpc_endpoints]
optimism = "https://example.com/"
mainnet = "${_CONFIG_MAINNET}"
```

we should also make it possible to configure:
* retry_backoff
* retries
* compute_units_per_second

See also:

https://github.com/foundry-rs/foundry/blob/fdad9fb0dde45d3476fc5d1fe6f40e8dc7c17caa/crates/evm/core/src/opts.rs#L26-L38

## TODO 
add a new type that has all these fields (`RpcEndpointConfig`) with custom serialize, deserialize so it is backwards compatible with (Deserialize from String gets interpreted as `RpcEndpoint`, object as `RpcEndpointConfig`):

https://github.com/foundry-rs/foundry/blob/fdad9fb0dde45d3476fc5d1fe6f40e8dc7c17caa/crates/config/src/endpoints.rs#L15-L15
ref 
https://github.com/foundry-rs/foundry/issues/4958

**Comment by sakulstra** [comment]
Hey just stumbled over this as i'm frequently facing issues with quicknode due credits per second rate limit.

Therefore i'm wondering how good a generalized foundry.toml settings could work, given that all providers measure differently, throw errors differently etc pp. Would it perhaps make more sense to automatically detect the provider & correctly handle the errors as suggested in https://github.com/foundry-rs/foundry/issues/4894 (if hitting rate limits, automatically configuring cups etc)

**Comment by zerosnacks** [comment]
Resolved by: https://github.com/foundry-rs/foundry/pull/6582
