### ISSUE TITLE
bug(cheatcodes): attempting to serialize a number as JSON string will still serialize to a number

### ISSUE THREAD

**Issue by jeffywu** [foundry-rs/foundry#6533]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (fdad9fb 2023-12-06T00:17:31.361933000Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

Attempting to serialize a number as a string will still serialize it to a number:
vm.serializeString(t, "value", "0");

will still serialize it to:
"value": 0

Full gist here:
https://gist.github.com/jeffywu/882111d670faaacc7a0541989bb46fb2

Use case: gnosis txn builder requires all numbers to be serialized as strings.

**Comment by DaniPopes** [comment]
We first try to parse it as a JSON value, so `"0"` parses as the number 0: https://github.com/foundry-rs/foundry/blob/f0166ccf0c8dc3ff626eed3c0a060804d8b94cb1/crates/cheatcodes/src/json.rs#L457-L459

You can get around this for now by wrapping the number in another pair of quotes like `'"0"'`.

cc @mattsse @Evalir @klkvr @odyslam

**Comment by grandizzy** [comment]
@jeffywu this is no longer reproducible in latest versions, using your gist and hardcoding to smth like `vm.serializeString(t, "value", "11111");` produce following json with proper `"value": "1111"`

```json
{
  "chainId": 31337,
  "createdAt": 1000,
  "meta": {
    "name": "Transactions Batch",
    "txBuilderVersion": "1.16.1"
  },
  "transactions": [
    {
      "contractMethod": {
        "inputs": [],
        "name": "fallback",
        "payable": true
      },
      "data": "0x",
      "to": "0x328809Bc894f92807417D2dAD6b7C998c1aFdac6",
      "value": "1111"
    }
  ],
  "version": "1.0"
}
```

Please reopen if you still hit the issue. thank you!
