### ISSUE TITLE
Custom errors are not decoded (hex shown)

### ISSUE THREAD

**Issue by ferencdg** [foundry-rs/foundry#6579]
### Component

Forge

### Describe the feature you would like

Whenever a custom error is thrown in the contract, I only see the 4 bytes of keccak256 has of the custom error.

For example, if I defined an error
error PoolNotInitialized()

and the error is thrown, then I would only see 0x486aa307 in the stack trace. This makes debugging much harder then it should be.

**Comment by mattsse** [comment]
wasn't able to repro this here #6587

it's possible that this has just been fixed via #6531

**Comment by DaniPopes** [comment]
Can you please try after updating to the latest version?

**Comment by ladislavdubravsky** [comment]
I notice the error is not decoded if it occurs in a `setUp` function, i.e.:

```
error PoolNotInitialized();

contract CustomTypesTestSetupFun is Test {
    function setUp() public {
        revert PoolNotInitialized();
    }

    function testErr() public pure {}
}
```

**Comment by ferencdg** [comment]
@mattsse I used this version of forge:
forge 0.2.0 (9fd44a7 2023-10-26T00:16:42.293111408Z)

**Comment by DaniPopes** [comment]
Please try again on the latest version

**Comment by grandizzy** [comment]
@mattsse this can be closed, tried with sample above and properly shown as `[FAIL. Reason: setup failed: PoolNotInitialized()] setUp() (gas: 0)`
