### ISSUE TITLE
Fork debugging panic with swap_remove

### ISSUE THREAD

**Issue by Silur** [foundry-rs/foundry#6584]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (cdbaf9d 2023-12-12T00:22:07.069991375Z)

### What command(s) is the bug in?

forge test --rpc-url http://localhost:8545 --debug 'test_myTest'

### Operating System

Linux

### Describe the bug

```bash
anvil --fork-url=https://mainnet.base.org &
forge test --rpc-url http://localhost:8545 --debug 'test_myTest'
```

`test_myTest` calls a very long chain of internal transactions, including many swaps and ERC4626 deposits/withdrawals.

This first fires up the debugger as usual but it quickly crashes with the following:

```
The application panicked (crashed).
Message:  swap_remove index (is 6171) should be < len (is 2806)
Location: library/alloc/src/vec/mod.rs:1452
```

**Comment by mattsse** [comment]
could you provide the code for `test_myTest`

fyi @DaniPopes

**Comment by Silur** [comment]
after more experiments it seems that if you try to navigate with the debugger with j/k, but especially c/C with a super long trace from the RPC, it's very likely that the RPC haven't finished actually supplying the whole trace. This means a JMPDEST that points further than the current "cursor" from the RPC will reach this overflow. After waiting a little and the RPC finishing sending the whoel trace (confirmed with wireshark) navigation doesn't cause the panic anymore.

My proposal is to disable navigation, or make it async and await the full trace is retreived from the RPC

**Comment by Silur** [comment]
After some experiments it seems that if you provide an invalid `ETHERSCAN_API_KEY` into the debugger and start receiving 403 errors from the API, JUMPDEST calls will deserialize the HTML response and starts to seek to nonexistent addresses when using j/k, c/C.

My proposal is to filter for 403 prior deserialization. 

Removing the faulty API key from `.env` solved the issue

**Comment by DaniPopes** [comment]
Not sure I follow, invalid Etherscan responses fail before entering the debugger.
In any case, closing since there have been a lot of fixes since this issue was created, and an issue was found by OP.

**Comment by DaniPopes** [comment]
@Mouradif can you please open another issue with more details?
