### ISSUE TITLE
feat(cheatcodes):  add `vm.meterTxGas` cheatcode

### ISSUE THREAD

**Issue by emo-eth** [foundry-rs/foundry#6590]
### Component

Forge

### Describe the feature you would like

As [suggested](https://github.com/foundry-rs/foundry/issues/6578#issuecomment-1851437216) by @Vectorized, Forge should have a cheatcode with signatures `meterTxGas()` and `meterTxGas(AccessList[] memory)` for accurately measuring how much real-world gas a transaction would use. Currently, gas reporting is misleading for a [number](https://github.com/foundry-rs/foundry/pull/5852) of [reasons](https://github.com/foundry-rs/foundry/issues/6578).

### Additional context

Real-world gas metering is hard in Forge because tests are executed in the context of a single transaction. Execution of test setup marks accounts and storage slots as "warm," in addition to affecting gas refund logic by changing "starting" storage slot values.

### Background 
The `pause/resumeGasMetering` cheatcodes affect reported gas by [caching a copy of the interpreter's `Gas` struct when paused](https://github.com/foundry-rs/foundry/blob/e972bf70412e51b1e15041341f7c29725bb6ac17/crates/cheatcodes/src/inspector.rs#L321) and [writing it back to the interpreter with each step.](https://github.com/foundry-rs/foundry/blob/e972bf70412e51b1e15041341f7c29725bb6ac17/crates/cheatcodes/src/inspector.rs#L367). On resume, the cached copy is deleted and the interpreter's `gas` member is left to proceed as normal.

After execution, [`gas_refunded` is subtracted from `gas`,](https://github.com/foundry-rs/foundry/blob/388e181c50c9313ca8cfe2c4f413397100dd1ce7/crates/evm/core/src/utils.rs#L282) and even farther down the line, an extra ["stipend"](https://github.com/foundry-rs/foundry/blob/8a31bf1ec2fb386e5441ee2a629b0c12b4433aed/crates/evm/evm/src/executors/mod.rs#L754) (the 21000 + calldata costs of invoking the forge test) is subtracted from the reported number.

### Approaches

After invoking the cheatcode, the interpreter's `Gas` struct can be reset. The overall "stipend" can be calculated by adding 21000 + the calldata cost of the next external call seen by the EVM.

After that, I see two obvious ways to account for differences in gas costs and refunds:

- Add functionality to `revm` (which Forge can then use) to mark [accounts](https://github.com/bluealloy/revm/blob/e802930cf3be9e773d008203665af9005f14dc2d/crates/revm/src/journaled_state.rs#L542) and [storage](https://github.com/bluealloy/revm/blob/e802930cf3be9e773d008203665af9005f14dc2d/crates/revm/src/journaled_state.rs#L606) [slots](https://github.com/bluealloy/revm/blob/e802930cf3be9e773d008203665af9005f14dc2d/crates/revm/src/journaled_state.rs#L648) in `JournaledState` as cold, and to [override slots' "original" values](https://github.com/bluealloy/revm/blob/aa5667764890bc554ea6392ea1e84e3e1991be6d/crates/primitives/src/state.rs#L142)
	- this may have unintended consequences on the overall state transition
	- as a separate project, changes that benefit Foundry might not be in revm's best interest
- Track which accounts and storage slots have been accessed + changed since invoking the cheatcode, and do manual gas+refund accounting on the interpreter's `Gas` struct during execution. Similar to #5852's approach, but more comprehensive. See also [`forge-gas-metering`](https://github.com/emo-eth/forge-gas-metering/blob/temp-accounting/src/AccessAccounting.sol#L159) for a similar WIP in Solidity.
	- adds a lot of overhead both in complexity and execution

After execution, the test runner should at least report calldata portion of the stipend in addition to execution costs.

### Note

Supporting many different EVM execution environments or hard forks may require a lot of extra configuration, which should be considered.

**Comment by sam-goldman** [comment]
This would be very useful!

**Comment by sambacha** [comment]
why not something like this:

```solidity
pragma solidity ^0.8.4;

Contract GasTracerFactory {

	/// @dev  returns the exact value of the gas provided in any call to it.

    function build() public returns (address out) {
      assembly {
        mstore(mload(0x40), 0x6b5a60020160005260206000f360005260206014f3)
        out := create(0, add(11, mload(0x40)), 21)
      }
    }
}
```

```solidity
contract Test is DSTest {
//...
address gasTracer;

    function setUp() public {
//...
      GasTracerFactory gasTracerFactory = new GasTracerFactory();
      gasTracer = gasTracerFactory.build();
}
```


Any pure solidity implementation will always return an incorrect result.

**Comment by zerosnacks** [comment]
Marking as resolved by the `--isolation` mode and recent fixes to the `pause/resumeGasMetering` cheatcodes.
