### ISSUE TITLE
Forge significantly underestimates gas on Arbitrum Sepolia

### ISSUE THREAD

**Issue by sam-goldman** [foundry-rs/foundry#6591]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

cdbaf9dda688cab08b9f6945af287534d68b1e1f

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

The gas estimates in the broadcast files for Arbitrum Sepolia are significantly lower than the actual gas used. This doesn't break broadcasts using `forge script`, but it breaks off-chain tooling that uses forge script to estimate the gas without broadcasting the transactions.

A minimal reproducible example is here: [https://github.com/sam-goldman/ArbSepoliaGasEstimation](https://github.com/sam-goldman/ArbSepoliaGasEstimation)

**Comment by Evalir** [comment]
Hey thanks! ack this is a problem, but we have several issues describing the same issue. For pruning the issue tracker, we'll close this
