### ISSUE TITLE
`forge coverage` doesn't use via-ir/optimizer setting

### ISSUE THREAD

**Issue by calbera** [foundry-rs/foundry#6592]
When running `forge coverage`, it builds differently than running `forge build` (seems like does not use any of the configuration provided in foundry.toml that is used by `forge build`). 

forge coverage fails (due to no `via-ir` flag set):
```
>>> forge coverage --report lcov --root ./contracts
[⠒] Compiling...
[⠑] Compiling 112 files with 0.8.21
[⠃] Solc 0.8.21 finished in 2.68s
Error:
Compiler run failed:
Error: Compiler error (/solidity/libsolidity/codegen/LValue.cpp:56):Stack too deep. Try compiling with `--via-ir` (cli) or the equivalent `viaIR: true` (standard JSON) while enabling the optimizer. Otherwise, try removing local variables.
```

forge build success using `via-ir = true` from foundry.toml:
```
>>> forge build --root ./contracts
[⠢] Compiling...
[⠰] Compiling 3 files with 0.8.21
[⠔] Solc 0.8.21 finished in 32.61s
Compiler run successful with warnings:
```

**Comment by mds1** [comment]
In order of best results:

1. Refactor your contracts so they don't give stack too deep when compiled with no optimizer and no via-ir
2. Run forge coverage with the `--ir-minimum` flag

**Comment by calbera** [comment]
Thanks @mds1! Yeah 1) is the main priority here. However 2) worked as well; should the flag be on the [docs page](https://book.getfoundry.sh/reference/forge/forge-coverage)? I didn't see an option on the docs and then never tried `forge coverage --help` to find the `--ir-minimum` flag.

**Comment by mds1** [comment]
Yes it definitely should be in the docs page, if you could open a PR for it that would be awesome! You can learn more about that flag here: https://github.com/foundry-rs/foundry/pull/5349
