### ISSUE TITLE
rpc url ending in slash causes issues

### ISSUE THREAD

**Issue by sakulstra** [foundry-rs/foundry#6593]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (0ae39ea 2023-12-11T00:27:32.487222000Z)

### What command(s) is the bug in?

forge

### Operating System

macOS (Apple Silicon)

### Describe the bug

> script failed: Could not instantiate forked environment with fork url: `https://redacted//`

It seems like when using a rpc ending in `/` the scripts etc break as foundry adds another /.

**Comment by jmcph4** [comment]
How is this being invoked?

**Comment by sakulstra** [comment]
@jmcph4 e.g. `forge test` (the rpc in env is set to `https://test/`)

As a workaround you can ofc remove the trailing /, but foundry should just work with both i guess.
The rpc used was quicknode if that matters.

**Comment by jmcph4** [comment]
> @jmcph4 e.g. `forge test` (the rpc in env is set to `https://test/`)

Yeah just managed to reproduce this locally.

> As a workaround you can ofc remove the trailing /, but foundry should just work with both i guess.

Definitely agree.

> The rpc used was quicknode if that matters.

No, I've done it with llama (I wouldn't expect it to matter anyway).

```rust
/// Tests that we can launch in forking mode when our RPC URL has trailing slashes
#[tokio::test(flavor = "multi_thread")]
async fn test_launch_fork_trailing_slash() {
    let mut rpc_url = foundry_common::rpc::next_http_archive_rpc_endpoint();
    rpc_url.push('/');
    rpc_url.push('/');
    let runner = forked_runner(&rpc_url).await;
    let filter = Filter::new(".*", ".*", &format!(".*fork{RE_PATH_SEPARATOR}Launch"));
    TestConfig::with_filter(runner, filter).run().await;
}
```

Interestingly this passes, so I assume the URL is being mutated much earlier in the pipeline.

**Comment by mattsse** [comment]
do you have an example for how you're using this?

we currently have a bug that this hack tried to address when the same fork URL is used twice for creating the same fork.
if you're creating the same fork, could you instead try to reuse the existing uint256 id?
apparently, there are some edge cases or we should just fix this properly...

**Comment by sakulstra** [comment]
@mattsse i think we don't select a fork multiple times.

Faced the issue here:
https://github.com/bgd-labs/aave-proposals-v3/blob/main/src/20231212_AaveV3Ethereum_ContinuousSecurityProposalAaveCertora/AaveV3Ethereum_ContinuousSecurityProposalAaveCertoraPart2_20231212.t.sol#L17

Which essentially only does `vm.createSelectFork(vm.rpcUrl('mainnet'), 18771153);` here.
https://github.com/bgd-labs/aave-proposals-v3/blob/main/src/20231212_AaveV3Ethereum_ContinuousSecurityProposalAaveCertora/BaseCertoraTest.t.sol#L17

As i said it's not a big deal as it's easy to work around, just a bit weird as obviously there's some wrong url mutation somewhere.

**Comment by zerosnacks** [comment]
Unable to reproduce:

```
forge script script/Counter.s.sol --rpc-url https://eth-holesky.g.alchemy.com/v2/<API_KEY>/ --broadcast --keystore <KEYSTORE>
```

and additional slashes

```
forge script script/Counter.s.sol --rpc-url https://eth-holesky.g.alchemy.com/v2/<API_KEY>// --broadcast --keystore <KEYSTORE>
```

Looks like trailing slashes are now ignored

Feel free to re-open if this is still an issue
