### ISSUE TITLE
cast wallet sign --data (where did it go?)

### ISSUE THREAD

**Issue by sandybradley** [foundry-rs/foundry#6602]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e15e33a 2023-05-02T00:04:33.253887158Z)

### What command(s) is the bug in?

cast wallet sign

### Operating System

Linux

### Describe the bug

data argument has disappeared. Not sure why?

```bash
$ cast wallet sign --data
error: unexpected argument '--data' found
```

Here it is in the cli docs:
https://book.getfoundry.sh/reference/cli/cast/wallet/sign

Here it is in the unit tests:
https://github.com/foundry-rs/foundry/blob/53b15e6cee787a7765988bb7228f26f62eb78129/crates/cast/tests/cli/main.rs#L100-L112

**Comment by mattsse** [comment]
can you try after updating the version.

couldn't reproduce:
```
cast wallet sign --private-key 0x0000000000000000000000000000000000000000000000000000000000000001 --data "{\"types\": {\"EIP712Domain\": [{\"name\": \"name\",\"type\": \"string\"},{\"name\": \"version\",\"type\": \"string\"},{\"name\": \"chainId\",\"type\": \"uint256\"},{\"name\": \"verifyingContract\",\"type\": \"address\"}],\"Message\": [{\"name\": \"data\",\"type\": \"string\"}]},\"primaryType\": \"Message\",\"domain\": {\"name\": \"example.metamask.io\",\"version\": \"1\",\"chainId\": \"1\",\"verifyingContract\": \"0x0000000000000000000000000000000000000000\"},\"message\": {\"data\": \"Hello\!\"}}"
0x06c18bdc8163219fddc9afaf5a0550e381326474bb757c86dc32317040cf384e07a2c72ce66c1a0626b6750ca9b6c035bf6f03e7ed67ae2d1134171e9085c0b51b
```

**Comment by sandybradley** [comment]
Apologies. I updated my version and it worked.
