### ISSUE TITLE
feat(cheatcodes): implement EIP-2098 in `vm.sign`

### ISSUE THREAD

**Issue by waynehoover** [foundry-rs/foundry#6606]
### Component

Forge

### Describe the feature you would like

[EIP-2098](https://eips.ethereum.org/EIPS/eip-2098) describes a compact signature, needing only two words to create a signature (instead of 3). In order to test signatures using EIP-2098 `vm.sign` should return the `vs` key (for when v != 27).

### Additional context

You can see how a EIP-2098 compact signature is created in ethers here: https://github.com/ethers-io/ethers.js/blob/master/packages/bytes/src.ts/index.ts#L380-L381

On the flip side you can see how Solady recovers an EIP-2098 signature here: https://github.com/Vectorized/solady/blob/main/src/utils/ECDSA.sol#L93-L97

I was able to implement this manually in my test by doing this:
```solidity
(uint8 v, bytes32 r, bytes32 s) = vm.sign(privateKey, digest);
if (v != 27) {
  // then left-most bit of s has to be flipped to 1.
  s = s | bytes32(uint256(1) << 255);
}
```

But ideally the `vs` would be returned by `vm.sign`.

Thanks!

**Comment by zerosnacks** [comment]
Hi @waynehoover, would you be interested in implementing this?

**Comment by leovct** [comment]
Hi @zerosnacks, I'd like to tackle this one :)

**Comment by zerosnacks** [comment]
> Hi @zerosnacks, I'd like to tackle this one :)

Thanks! Assigning to you

**Comment by mds1** [comment]
What is the proposed interface here? We probably should implement as a new cheat to avoid breaking changes to the interface right?

**Comment by leovct** [comment]
> What is the proposed interface here? We probably should implement as a new cheat to avoid breaking changes to the interface right? 

What do you think of:

- `vm.signEIP2098()`?
- or `vm.signCompact()`?

**Comment by mds1** [comment]
It looks like viem uses "[compact signature](https://viem.sh/docs/utilities/signatureToCompactSignature#signaturetocompactsignature)" so I would say `vm.signCompact`
