### ISSUE TITLE
Branch coverage not returning correct value for branch coverage

### ISSUE THREAD

**Issue by jatZama** [foundry-rs/foundry#6609]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (3d6bfdd 2023-12-16T00:20:53.761034000Z)

### What command(s) is the bug in?

forge coverage

### Operating System

macOS (Apple Silicon)

### Describe the bug

I tested this contract : 
```solidity
// SPDX-License-Identifier: BSD-3-Clause-Clear

pragma solidity 0.8.22;

contract Branch {

    function branch(bool lhs, bool rhs) external returns (bool){
        bool result;
        if (lhs || rhs){
            result = true;
        }
        return result;
    }
}
```
With this simple test:
```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.22;

import {Test, console2} from "forge-std/Test.sol";
import {Branch} from "../src/Branch.sol";

contract BranchTest is Test {
    Branch public branch;

    function setUp() public {
        branch = new Branch();
    }

    function test_branch() public {
        branch.branch(true,false);
    }
}
```
`forge coverage` (latest forge version, with default params) returns 100% coverage for % Branches, which is obviously incorrect. On the other hand, the saùe test returns 50% coverage with hardhat coverage which seems more correct.

**Comment by zerosnacks** [comment]
Related: https://github.com/foundry-rs/foundry/issues/4314

I think there is a logical error in your test setup as you run the test once 

```
if (lhs || rhs){
    result = true;
}
 ```
 
 Rewriting the test as
 
 ```
 contract Branch {
    function branch(bool foo) external returns (bool){
        bool result;
        if (foo) {
            result = true;
        } else {
            result = false;
        }
        return result;
    }
}
```
 
 ```
 contract BranchTest is Test {
    Branch public branch;

    function setUp() public {
        branch = new Branch();
    }

    function test_branch() public {
        branch.branch(true);
    }
}
```

Correctly yields:

| File           | % Lines      | % Statements | % Branches   | % Funcs       |
|----------------|--------------|--------------|--------------|---------------|
| src/Branch.sol | 80.00% (4/5) | 75.00% (3/4) | 50.00% (1/2) | 100.00% (1/1) |
| Total          | 80.00% (4/5) | 75.00% (3/4) | 50.00% (1/2) | 100.00% (1/1) |

![Screenshot from 2024-07-05 15-38-24](https://github.com/foundry-rs/foundry/assets/95942363/22e69b80-9cd2-4fa2-a246-584b5168c5e8)

Marking as resolved, https://github.com/foundry-rs/foundry/issues/4314 is still an issue.
