### ISSUE TITLE
Chisel does not output anything for some valid calculations

### ISSUE THREAD

**Issue by Proxy1967** [foundry-rs/foundry#6610]
### Component

Chisel

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (3d6bfdd 2023-12-16T00:17:23.049683682Z)

### What command(s) is the bug in?

chisel

### Operating System

Linux

### Describe the bug

When trying to calculate `10e18*1e18/110e18` chisel does not give any output. But for instance for `10e18*1e18/100e18` or `10e18*1e18/90e18` or even `10e18*1e18/200e18` it does. When dividing with anything from `101e18` to `199e18` it does not output anything. Same thing happens when dividing with `201e18` etc.

**Comment by Evalir** [comment]
cc @clabby / @refcell

**Comment by mattsse** [comment]
closing this because `10e18*1e18/110e18` is invalid solidity:

```
Error (6090): Fractional numbers cannot yet be encoded.
  --> ReplContract.sol:14:46:
   |
14 |         bytes memory inspectoor = abi.encode(10e18*1e18/110e18);
   |                                              ^^^^^^^^^^^^^^^^^
```

with #6647 the error is now logged if run with -vvv, perhaps we should always log them, but could be noisy
