### ISSUE TITLE
Doc generator strips all white spaces from comments

### ISSUE THREAD

**Issue by matevz** [foundry-rs/foundry#6619]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (477b345 2023-12-18T00:22:09.434601489Z)

### What command(s) is the bug in?

forge doc

### Operating System

Linux

### Describe the bug

`forge doc` strips out whitespaces from the comments which it shouldn't.

For example, from the following solidity code:

```solidity
/**
 * @notice
 *   Use this library to do fancy stuff:
 *   - determine the local weather
 *     - by using the weather API
 *     - or decoding the image content of your area
 *   - determine the local time
 *
 *   #### Example
 *
 *   ```solidity
 *   pragma solidity ^0.8.13;
 *
 *   import MyLib from "libraries/mylib.sol";
 *
 *   contract MyContracts {
 *     function test() public view returns (bytes32) {
 *       return MyLib.hello();
 *     }
 *   }
 *   ```
 */
library MyLib {
}
```

The forge doc will output a markdown file:
```markdown
# MyLib
[Git Source](...)

Use this library to do fancy stuff:
- determine the local weather
- by using the weather API
- or decoding the image content of your area
- determine the local time
#### Example
```solidity
pragma solidity ^0.8.13;
import MyLib from "libraries/mylib.sol";
contract MyContracts {
function test() public view returns (bytes32) {
return MyLib.hello();
}
}
```

As a consequence, the bullets will be flattened and any code snippets inside the natspec documentation will be un-indented and blank lines removed.

**Comment by grandizzy** [comment]
we're going to track this issue with https://github.com/foundry-rs/foundry/issues/4539 marking this as dupe, please reopen if you think should be a different ticket. Thank you!
