### ISSUE TITLE
when I exec 'docker run  ghcr.io/foundry-rs/foundry:nightly-5068b7a06df7d25afe22ecd8b433b9ecfec2810a "forge script scripts/Deploy.s.sol:Deploy --sig sync'()' --private-key xx --rpc-url xx"'

### ISSUE THREAD

**Issue by tori-sallery** [foundry-rs/foundry#6622]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### Operating System

None

### Describe the bug

  [44353] Deploy::sync()
    ├─ [0] VM::readFile(/packages/contracts-bedrock/deployments/torinetL113333/.deploy) [staticcall]
    │   └─ ← <file>
    ├─ [0] VM::ffi([bash, -c, jq 'keys' <<< '{
│   └─ ← "Failed to execute command: No such file or directory (os error 2)"
    └─ ← "Failed to execute command: No such file or directory (os error 2)"

**Comment by Evalir** [comment]
Is it possible for you to provide a repro? It's hard to understand what's the issue here.

**Comment by tori-sallery** [comment]
> Is it possible for you to provide a repro? It's hard to understand what's the issue here.

https://docs.optimism.io/builders/chain-operators/tutorials/create-l2-rollup#generate-some-keys
when I deploy op
Generate contract artifacts
use docker run forge script scripts/Deploy.s.sol:Deploy --sig 'sync()' --rpc-url $L1_RPC_URL

error occour
