### ISSUE TITLE
align --hd-path(s) cli argument

### ISSUE THREAD

**Issue by radeksvarz** [foundry-rs/foundry#6625]
### Component

Forge

### Describe the feature you would like

relevant for create and script:

forge script ... --hd-path ... raises
```
error: unexpected argument '--hd-path' found

  tip: a similar argument exists: '--hd-paths'
```

forge create ... --hd-paths ... raises
```
error: unexpected argument '--hd-paths' found

  tip: a similar argument exists: '--hd-path'
```

Can this be aligned?

**Comment by zerosnacks** [comment]
`--hd-path` is of type `Option<String>` (singular) whereas `--hd-paths` is of type `Option<Vec<String>>` (multiple); they are functionally different.

Could you expand on the feature you would like to see?

**Comment by zerosnacks** [comment]
Marking as `not planned`

`forge create` supports `--hd-path` singular whereas `forge script` support `--hd-path` plural, functionally different

also throws error that sufficiently explains it

```
error: unexpected argument '--hd-path' found

  tip: a similar argument exists: '--hd-paths'
```
