### ISSUE TITLE
`vm.prank()` failed on specific block number

### ISSUE THREAD

**Issue by gunboatsss** [foundry-rs/foundry#6627]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (eb2141c 2023-12-20T00:19:37.580705466Z)

### Operating System

Linux

### Describe the bug

I was testing with Gelato, I unable to `prank` the address `0xd55caA93dAeb8D4F846C4936E3D7E402EE952b70`. while using OP Mainnet fork with specfic block `18634930`

```solidity
function test_prankfailed() public {
        vm.createSelectFork(vm.envString("OP_MAINNET_RPC"), 18634930);
        (address dedicatedMsgSender, bool deployed) = ops.getProxyOf(target);
        if (!deployed) {
            ops.deployFor(target);
        }
        vm.prank(target);
    }
```
The repo with minimal reproduction for this issue.
https://github.com/gunboatsss/minimal-reproduction

**Comment by zerosnacks** [comment]
Hi @gunboatsss,

I was able to reproduce the error but I think it is not actually a bug.

In your minimal reproduction test the requested blockheight for forking of `18634930` on OP mainnet was [524 days ago](https://optimistic.etherscan.io/block/18634930) at time of writing whereas the `OpsProxyFactory` was deployed only [344 days ago](https://optimistic.etherscan.io/tx/0x1d2dbb34f92564b18a48bebdb6666bbbe43b22d876e4ddf9074b94565581123e). Therefore the `OpsProxyFactory` contract is not yet deployed at the blockheight and throws.

I think you were attempting to use the Ethereum blockheight to query OP Mainnet, which produces its own [blocks](https://optimistic.etherscan.io/blocks).

Hope this helps.

@gakonst feels free to double check - I think this ticket can be closed.

**Comment by mattsse** [comment]
@zerosnacks tysm for looking into this

this indeed reverts on the proxy factory call:

`(address dedicatedMsgSender, bool deployed) = ops.getProxyOf(target);`

**Comment by gunboatsss** [comment]
@zerosnacks hey, thank for checking in. I tried again with block `114556536` which is ~8 days ago from the time I writing this. This is on my own [repo](https://github.com/gunboatsss/max-mint-with-gelato/blob/main/test/LiquidationSaverV2.t.sol/). Sorry for wrong block number on reproduction repo.

```
Traces:
  [42162] LiquidationSaverV2Test::test_happy_path()
    ├─ [26995] 0x44bde1bccdD06119262f1fE441FBe7341EaaC185::getProxyOf(0xd7BBeEA70aa555476D4e9bEF553fC137Cc20EcF6) [staticcall]
    │   ├─ [22037] 0xFd5851BdE5066Ac84AbA9137F00Ef89BC8777f00::getProxyOf(0xd7BBeEA70aa555476D4e9bEF553fC137Cc20EcF6) [delegatecall]
    │   │   └─ ← 0xdb13a478d1038AAE2c2d58FBD14782BcF6c869eF, false
    │   └─ ← 0xdb13a478d1038AAE2c2d58FBD14782BcF6c869eF, false
    ├─ [0] VM::prank(0xd7BBeEA70aa555476D4e9bEF553fC137Cc20EcF6)
    │   └─ ← ()
    └─ ← EvmError: Revert
```
