### ISSUE TITLE
Add EIP-4844 fields to EthTransactionRequest and introduce EIP4844TransactionRequest

### ISSUE THREAD

**Issue by Rjected** [foundry-rs/foundry#6633]
### Component

Anvil

### Describe the feature you would like

Right now anvil cannot accept blob transactions in `eth_sendTransaction`. To be compatible, `EthTransactionRequest` needs three extra fields:
* `max_fee_per_blob_gas`
* `blob_versioned_hashes`
* `sidecar`

ref reth: https://github.com/paradigmxyz/reth/blob/6b99292f8fd8ad7d7849a93de0627f64804337c3/crates/rpc/rpc-types/src/eth/transaction/request.rs#L40-L45

`EIP4844TransactionRequest` would also need to be introduced

**Comment by Evalir** [comment]
ideally done after #6219

**Comment by Rjected** [comment]
> ideally done after #6219

yep, then I guess this is more of an alloy feature request rather than foundry - will add an issue there

**Comment by Rjected** [comment]
Assuming this will be integrated in #6219: https://github.com/alloy-rs/alloy/pull/89

this issue will then be solved

**Comment by zerosnacks** [comment]
Marking as resolved by https://github.com/foundry-rs/foundry/pull/7242
