### ISSUE TITLE
baseFeePerGas of the first mined block after anvil_reset equals block before anvil_reset

### ISSUE THREAD

**Issue by vlad-blana** [foundry-rs/foundry#6640]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (eb2141c 2023-12-20T00:44:21.180725100Z)

### Operating System

Windows

### Describe the bug

After any "anvil_reset" rpc call, the first block that gets mined doesn't use the EIP1559 formula for the baseFeePerGas, but instead uses the last block baseFeePerGas value before anvil_reset.

The next blocks use the EIP1559 formula.
This causes not enough balance issues when mining transactions expecting the EIP1559 formula to be used for the first block after every anvil_reset

Here is an example on ethereum mainnet

![image](https://github.com/foundry-rs/foundry/assets/42930668/4589b081-c947-4d5e-8033-3a886ed25498)

anvil started with command: .\anvil.exe --fork-url "https://rpc.flashbots.net" --no-mining
eth mainnet

**Comment by mattsse** [comment]
thanks for flagging,

this was indeed an oversight in the reset impl that used the base fee of the targeted block and not the _next_ basefee
