### ISSUE TITLE
Contract verification fails with dependency "File not found" in pnpm monorepo

### ISSUE THREAD

**Issue by rocketman-21** [foundry-rs/foundry#6653]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (1978a03 2023-12-21T09:54:24.034180000Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

The error details suggest that a source file from OpenZeppelin's contracts is not found.

### Steps to Reproduce
Run the following command in this branch:
https://github.com/collectivexyz/revolution-protocol/pull/39

```
cd packages/protocol-rewards && forge script script/DeployProtocolRewards.s.sol:DeployContracts --rpc-url https://rpc.sepolia.org/ --broadcast --verify -vvvvv --etherscan-api-key [API_KEY] --private-key [PRIVATE_KEY] --chain-id 11155111 --verifier etherscan --verifier-url https://api-sepolia.etherscan.io/api? --force
```

Observe the error output.

### Expected Behavior
Successful verification of the contract.

### Actual Behavior
Error during contract verification with the following message:

```
Fail - Unable to verify. Solidity Compilation Error: Source "node_modules/@openzeppelin/contracts/utils/cryptography/MessageHashUtils.sol" not found: File not found. Searched the following locations: "".
```

### Tried solutions

`allow_paths = ["../../node_modules", "node_modules"]` in `packages/protocol-rewards/foundry.toml` doesn't resolve the issue. It is just not finding the file.

**Comment by mattsse** [comment]
is this still the case on a newer version?
we recently added a few fixes for smylinks:

https://github.com/foundry-rs/compilers/pull/35
https://github.com/foundry-rs/compilers/pull/36

**Comment by rocketman-21** [comment]
> is this still the case on a newer version? we recently added a few fixes for smylinks:
> 
> [foundry-rs/compilers#35](https://github.com/foundry-rs/compilers/pull/35) [foundry-rs/compilers#36](https://github.com/foundry-rs/compilers/pull/36)

amazing it seems to be working now with

`forge 0.2.0 (71d8ea5 2024-01-09T15:10:35.372218000Z)`
