### ISSUE TITLE
package installing error with forge.

### ISSUE THREAD

**Issue by RutvikGujarati** [foundry-rs/foundry#6657]
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (834d959 2023-11-10T00:19:17.918296482Z)

### What command(s) is the bug in?

 forge install @openzeppelin-contracts/contracts

### Operating System

Windows

### Describe the bug

forge install @openzeppelin-contracts/contracts
Installing contracts in /mnt/d/solidity/Faucet/lib/contracts (url: Some("https://github.com/openzeppelin-contracts/contracts"), tag: None)
Error: 
The target directory is a part of or on its own an already initialized git repository,
and it requires clean working and staging areas, including no untracked files.

```I have done everything that tells by chatgpt or by google but it doesn't worked for me```

**Comment by Evalir** [comment]
The error is clear—you have a dirty git directory with unstaged files. Please try `--no-commit`. If this persists please ask for help in the foundry tg chat, you can find it in the README.md

thanks!

**Comment by RutvikGujarati** [comment]
I did it bro .
i did --force , -- --no--commit, --no-commit.
all major things but it still give me an error.
