### ISSUE TITLE
echo command in not working while calling a function from a .env file.

### ISSUE THREAD

**Issue by Rhythm23-tech** [foundry-rs/foundry#6661]
echo $"RPC-URL"  this command does not showing any value which is already been specified in the .env file. 
![GitHUb query 1](https://github.com/foundry-rs/foundry/assets/153013690/ee748245-83a2-4b3b-b70b-7caade33718b)

**Comment by DaniPopes** [comment]
you have a space between the equals and the URL, and also the URL should be quoted in "". Anyway I don't see how this is Foundry related.
