### ISSUE TITLE
UTF-8 with BOM file case a crash

### ISSUE THREAD

**Issue by CorrM** [foundry-rs/foundry#6664]
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a5171a4 2023-12-24T00:17:25.574824499Z)

### What command(s) is the bug in?

forge build

### Operating System

Windows

### Describe the bug

When try to compile file that have the encode `UTF-8 with BOM' will crash (btw i use WSL2)
```
forge build
[⠒] Compiling...
[⠢] Compiling 1 files with 0.8.23
[⠆] Solc 0.8.23 finished in 5.89ms
The application panicked (crashed).
Message:  byte index 5 is not a char boundary; it is inside '\u{feff}' (bytes 4..7) of `1 | // SPDX-License-Identifier: GPL-3.0`
Location: /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/foundry-compilers-0.1.1/src/artifacts/mod.rs:2085
```

The example file that case the problem: (json ext so i can upload it here)
[Test.json](https://github.com/foundry-rs/foundry/files/13763065/Test.json)

**Comment by mattsse** [comment]
why do you want to use the BOM for your solidity files?

**Comment by CorrM** [comment]
> why do you want to use the BOM for your solidity files?

For some reason vs code was forcing me to use BOM. i want use BOM for sure, but its a bug!
maybe you guys can add a WARN or supporting BOM.

**Comment by DaniPopes** [comment]
This should be fixed in the latest few releases @CorrM can you please confirm

**Comment by CorrM** [comment]
> This should be fixed in the latest few releases @CorrM can you please confirm

Version: forge 0.2.0 (05d6062 2024-01-10T00:16:31.110671064Z)

```
forge build
[⠢] Compiling...
[⠰] Compiling 25 files with 0.8.23
[⠔] Solc 0.8.23 finished in 56.67ms
Error:
Compiler run failed:
Error (7858): Expected pragma, import directive or contract/interface/library/struct/enum/constant/function/error definition.
 --> src/Test.sol:1:1:
  |
1 | // SPDX-License-Identifier: GPL-3.0
  | ^
```

its not panic, but throw error. Showing error that describe the problem are about the file encoding is better.

**Comment by DaniPopes** [comment]
We pass files as is to solc, so we can't do much about it. You might want to open an issue in the solc repository.
