### ISSUE TITLE
Solc installation error while running forge build

### ISSUE THREAD

**Issue by Prasoon1308** [foundry-rs/foundry#6665]
```
[⠊] Compiling...
[⠒] Installing Solc version 0.8.18
[⠢] Failed to install Solc 0.8.18: error sending request for url (https://raw.githubusercontent.com/alloy-rs/solc-builds/260964c1fcae2502c0139070bdc5c83eb7036a68/macosx/aarch64/list.json): error trying to connect: tcp connect error: Operation timed out (os error 60)
Error: 
error sending request for url (https://raw.githubusercontent.com/alloy-rs/solc-builds/260964c1fcae2502c0139070bdc5c83eb7036a68/macosx/aarch64/list.json): error trying to connect: tcp connect error: Operation timed out (os error 60)

Context:
- Error #0: error trying to connect: tcp connect error: Operation timed out (os error 60)
- Error #1: tcp connect error: Operation timed out (os error 60)
- Error #2: Operation timed out (os error 60)
```

Operating system : macOS
foundry is up to date, but while running `forge build` it is erroring out

**Comment by Prasoon1308** [comment]
on changing the solc version fro 0.8.18 to 0.8.21, it works fine!

**Comment by krajarajan** [comment]
i have tried ,  Solc version 0.8.23  , issue persists .

**Comment by Prasoon1308** [comment]
there maybe some solidity compatibility issues; try different versions

**Comment by krajarajan** [comment]
following url working ?   https://raw.githubusercontent.com/alloy-rs/solc-builds/260964c1fcae2502c0139070bdc5c83eb7036a68/macosx/aarch64/list.json

**Comment by SayHalou** [comment]
you can change solc version,modify foundry.toml file 
[profile.default]
solc-version = "0.8.17" 
src = "src"
out = "out"
libs = ["lib"]
https://raw.githubusercontent.com/alloy-rs/solc-builds/260964c1fcae2502c0139070bdc5c83eb7036a68/macosx/aarch64/list.json this list display support solc version
