### ISSUE TITLE
Download Issue and foundry not working

### ISSUE THREAD

**Issue by Killpit** [foundry-rs/foundry#6668]
Right now I'm working to make the foundry command working long after it's been installed, what steps should I take to make the command and the rest of the framework functions properly on my computer 
<img width="1512" alt="Ekran Resmi 2023-12-26 12 05 04" src="https://github.com/foundry-rs/foundry/assets/57031187/1bfbd49b-ca98-4da2-96cd-6d038ecda8d7">
![Ekran Resmi 2023-12-26 11 48 02](https://github.com/foundry-rs/foundry/assets/57031187/c9968f42-b6e8-4ad9-9e36-6c390e050bd0)
![Ekran Resmi 2023-12-26 11 44 47](https://github.com/foundry-rs/foundry/assets/57031187/32981939-0aad-4cfa-9bbb-9613f6f44404)
![Ekran Resmi 2023-12-26 11 36 10](https://github.com/foundry-rs/foundry/assets/57031187/21b0834b-bc50-408d-85a5-63d89d7c9161)
<img width="1512" alt="Ekran Resmi 2023-12-26 10 50 55" src="https://github.com/foundry-rs/foundry/assets/57031187/a436cc1e-0ca8-4d50-904b-462a5beb90d8">

**Comment by mattsse** [comment]
ptal here https://book.getfoundry.sh/getting-started/installation

**Comment by Killpit** [comment]
Even though I followed the docs multiple times, when I say foundry, it says command not found, but the main components are installed.

**Comment by Evalir** [comment]
@Killpit foundry has been installed correctly (forge/chisel/cast/anvil). It seems your issue lies on how `foundryup` is getting added to your system, which might be due to your terminal config, zsh related. You also seem to have multiple `forge`/`anvil`/cast`/`chisel` PATHs exported, see the warning messages you have.

I'm closing this because this is actually user config error—let's take this to the telegram chat so we can help you further. We just wanna keep actual bugs and features on the issue tracker, thanks 🙏

**Comment by Killpit** [comment]
> @Killpit foundry has been installed correctly (forge/chisel/cast/anvil). It seems your issue lies on how `foundryup` is getting added to your system, which might be due to your terminal config, zsh related. You also seem to have multiple `forge`/`anvil`/cast`/`chisel` PATHs exported, see the warning messages you have.
> 
> I'm closing this because this is actually user config error—let's take this to the telegram chat so we can help you further. We just wanna keep actual bugs and features on the issue tracker, thanks 🙏

I actually opened the new issue, but I didn't get any answer at the chat

**Comment by Killpit** [comment]
> @Killpit foundry has been installed correctly (forge/chisel/cast/anvil). It seems your issue lies on how `foundryup` is getting added to your system, which might be due to your terminal config, zsh related. You also seem to have multiple `forge`/`anvil`/cast`/`chisel` PATHs exported, see the warning messages you have.
> 
> I'm closing this because this is actually user config error—let's take this to the telegram chat so we can help you further. We just wanna keep actual bugs and features on the issue tracker, thanks 🙏

Shared on telegram too, hope I get something

**Comment by Killpit** [comment]
Should I remove the duplicates to make `foundryup` and other commands working @Evalir

**Comment by Booker-CU** [comment]
> Should I remove the duplicates to make `foundryup` and other commands working @Evalir

Did you get this working, I'm having a similar problem on Ventura... I install it but it says command not found when I run foundryup
