### ISSUE TITLE
Add optional feature to enable faster keccak implementation

### ISSUE THREAD

**Issue by DaniPopes** [foundry-rs/foundry#6678]
### Component

Other (please describe)

### Describe the feature you would like

See https://github.com/alloy-rs/core/pull/466 (released in v0.5.4), and https://github.com/paradigmxyz/reth/issues/5874.

It should also enable this feature by default when creating distribution binaries in CI, since that's where the biggest speed up is.

**Comment by MuhtasimTanmoy** [comment]
Details, high-level design, and testing procedures are needed.

**Comment by 1010adigupta** [comment]
understood, I can take this up
