### ISSUE TITLE
I forked a bsc using anvil, and then the code for the same contract I was able to execute in a tenderly forked environment, but the fork using anvil had a weird reentry problem.

### ISSUE THREAD

**Issue by wg200202** [foundry-rs/foundry#6681]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### Operating System

macOS (Apple Silicon)

### Describe the bug

I forked a bsc using anvil, and then the code for the same contract I was able to execute in a tenderly forked environment, but the fork using anvil had a weird reentry problem.
<img width="1418" alt="image" src="https://github.com/foundry-rs/foundry/assets/10970322/830c7163-7c7c-44f5-b7e4-ab96d15f0045">

The case study is https://github.com/SunWeb3Sec/DeFiHackLabs/blob/main/src/test/Paraluni_exp.sol. Of course I deployed it with the cheat code removed.

I've been testing other ethereum related cases and I'm not experiencing any problems. Only bsc has problems.

<img width="579" alt="image" src="https://github.com/foundry-rs/foundry/assets/10970322/2f8476c8-4b25-49f4-932f-fa9b5e9b55c7">

**Comment by Evalir** [comment]
let's take this to the foundry help telegram chat (see README.md)—i'm not sure if bsc evm has any different assumptions, but wouldn't surprise me it's something bsc specific. If we confirm this is a bug we can reopen

**Comment by wg200202** [comment]
Thanks, but how do I find the answers in telegram?

**Comment by Evalir** [comment]
@wg200202 feel free to just ask!
