### ISSUE TITLE
Unable to import foundry crates into external project

### ISSUE THREAD

**Issue by spencer-xyz** [foundry-rs/foundry#6690]
### Component

Forge, Cast, Anvil, Chisel

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### Operating System

macOS (Apple Silicon)

### Describe the bug

I am trying to import some of the foundry crates into an external Rust project, but I am not able to compile the project after importing.

Steps to reproduce:
1. Create new cargo project: `cargo new foundry-test`
2. Add the following dependency to the Cargo.toml file: `anvil = { git = "https://github.com/foundry-rs/foundry.git", branch = "master" }`
3. Compile project: `cargo build`

I have attached the error messages that I encounter when doing this

[logs.txt](https://github.com/foundry-rs/foundry/files/13804312/logs.txt)

**Comment by Evalir** [comment]
Hi! You need to use the same patches we use for this to work. please check out the root `Cargo.toml`.
