### ISSUE TITLE
`cast index string` does not work 

### ISSUE THREAD

**Issue by eunseong-theori** [foundry-rs/foundry#6692]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (da2392e 2023-08-02T09:00:14.068523319Z)

### What command(s) is the bug in?

cast index 

### Operating System

Linux

### Describe the bug

cast index error if the `key_type` is a string. (https://book.getfoundry.sh/reference/cast/cast-index)

The cast index uses `abi.encode` to calculate slots for the mapping type (https://github.com/foundry-rs/foundry/blob/master/crates/cast/src/lib.rs#L1664C75-L1664C75), but it doesn't work for string . 

`abi.encodePakced` works instead of `abi.encode` for string.

The contract code: https://arbiscan.io/address/0xA32E7eA512525B89171F3b48C7F01bD933d17c59#readContract

```
root@user:/home/user# cast index string "hello" 1
0x3556fc8e3c702d4479a1ab7928dd05d87508462a12f53307b5407c969223d1f8
root@user:/home/user# cast storage 0xA32E7eA512525B89171F3b48C7F01bD933d17c59 0x3556fc8e3c702d4479a1ab7928dd05d87508462a12f53307b5407c969223d1f8 -r https://arbitrum-one.publicnode.com
0x0000000000000000000000000000000000000000000000000000000000000000
root@user:/home/user# chisel
Welcome to Chisel! Type `!help` to show available commands.
➜ keccak256(abi.encodePacked("hello",uint256(1)))
Type: bytes32
└ Data: 0x8404bb4d805e9ca2bd5dd5c43a107e935c8ec393caa7851b353b3192cd5379ae
➜ 
(To exit, press Ctrl+C again)
➜ 
root@user:/home/user# cast storage 0xA32E7eA512525B89171F3b48C7F01bD933d17c59 0x8404bb4d805e9ca2bd5dd5c43a107e935c8ec393caa7851b353b3192cd5379ae -r https://arbitrum-one.publi
cnode.com
0x776f726c6400000000000000000000000000000000000000000000000000000a
```

This issue applies to `bytes` types as well as `strings`.

**Comment by mattsse** [comment]
thoughts @DaniPopes ?

**Comment by rbtree-theori** [comment]
When is this gonna fixed? I'm even surprised that another person from my company already reported this like two months ago.
Also `bytes` is not handled in a proper way.

**Comment by mattsse** [comment]
@DaniPopes mind taking a look at this?

I think strings/bytes <32 are packed? https://docs.soliditylang.org/en/latest/internals/layout_in_storage.html#bytes-and-string
