### ISSUE TITLE
```cast``` returning 'illegal abi' error when sending transactions to functions with tuples

### ISSUE THREAD

**Issue by sadministrator** [foundry-rs/foundry#670]
### Component

Cast, Other (please describe)

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (0b6b202 2022-02-04T16:36:20.877746906+00:00)

### What command(s) is the bug in?

```forge send``` and possibly others

### Operating System

Linux

### Describe the bug

```cast send``` used in format ```seth call [<options>] <to> <sig> [<args>...]``` does not correctly parse function signatures if they contain tuples. It seems this problem stems from the ```ethers-rs``` repo, specifically [here](https://github.com/gakonst/ethers-rs/blob/77dcccb7bae83a896a319e116bd34a6844b896ba/ethers-core/src/abi/human_readable.rs).

It looks like line 261 in particular would  be causing the issue since is splits the calldata arguments with '(' as the delimiter in order to separate input and output args, but that would break if there are any tuples present as args.

This issue is also present in ```seth```, although the error message is a little clearer here as it outputs ```seth-abi: error: unexpected character "(" at position 0 in "(bytes1,bytes32,uint64)"```.

**Comment by onbjerg** [comment]
@mattsse Assigning you to this since it's the same underlying issue as #2025 and you assigned yourself to that one
