### ISSUE TITLE
feat(`cheatcodes`): add `vm.getStateDiffOpcodes` to access opcodes inside of tests

### ISSUE THREAD

**Issue by drortirosh** [foundry-rs/foundry#6704]
### Component

Forge

### Describe the feature you would like

Currently, Foundry test can access most traces of call execution, via `startStateDiffRecording()`, 
which eventually returns an array `AccountAccess[]`, with account references and storage access.
However, the one thing that is not returned is the actual executed bytecodes.

This is something that we do need for [erc4337](https://ercs.ethereum.org/ERCS/erc-4337) implementation
(in short: smart wallet contracts must perform validation while avoiding some code patterns. We have enough information for validation storage access, but we also need to verify opcode usage.

### Suggestion.
Instead of overloading the returned struct of `stopAndReturnStateDiff()`, we can add a new method 
```
function getStateDiffOpcodes(uint index) returns (OpcodeAccess[] memory)
```
The "index" parameter is the same index into the array returned by: `stopAndReturnStateDiff()`
That is, for each `AccountAccess` entry, we return a array of opcodes

```
struct OpcodeAccess {
  uint8 opcode;
  uint pc;
  uint gasCost;
  uint gas;
  uint depth;
}
```

**Comment by mds1** [comment]
I've heard this come up as a limitation of foundry testing in the context of ERC-4337 a few times now, so I'm supportive of this feature

**Comment by kopy-kat** [comment]
Is there already a status on this feature? I’m happy to contribute and built a prototype of this would be useful

**Comment by DaniPopes** [comment]
This should now be possible by conditionally enabling opcode tracing during execution thanks to https://github.com/foundry-rs/foundry/pull/8181

cc @klkvr

**Comment by zerosnacks** [comment]
So I understand correctly, the next step would be to add the cheatcode?

**Comment by DaniPopes** [comment]
Yeah that's right

**Comment by grandizzy** [comment]
@drortirosh we have a pending PR in this area https://github.com/foundry-rs/foundry/pull/8571 could you please have a look and see if the cheatcodes we're going to add are also resolving your use case? thank you!

**Comment by boolafish** [comment]
FYI, I have the ERC4337 checker tool implemented here: https://github.com/boolafish/erc4337-checker/blob/main/src/ERC4337Checker.sol that leverages the cheatcodes from #8571 . The tool should be exactly what this issue is looking for.
