### ISSUE TITLE
multibyte string crashes chisel

### ISSUE THREAD

**Issue by thedavidmeister** [foundry-rs/foundry#6716]
### Component

Chisel

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

chisel 0.2.0 (0f20cc6 2024-01-03T00:17:38.828033000Z)

### What command(s) is the bug in?

chisel

### Operating System

macOS (Apple Silicon)

### Describe the bug

```
davids-iMac:rain.interpreter thedavidmeister$ chisel
Welcome to Chisel! Type `!help` to show available commands.
➜ "ஒ"
The application panicked (crashed).
Message:  byte index 52 is not a char boundary; it is inside 'ஒ' (bytes 51..54) of `14 |         bytes memory inspectoor = abi.encode("ஒ");`
Location: /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/foundry-compilers-0.1.2/src/artifacts/mod.rs:2084

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Abort trap: 6
```

**Comment by mattsse** [comment]
possibly fixed by https://github.com/foundry-rs/compilers/pull/40

cc @DaniPopes

**Comment by DaniPopes** [comment]
yes that's the same error

**Comment by DaniPopes** [comment]
With #6717 (note that it needs a semicolon to display the error, otherwise it just silently doesn't display anything)

![image](https://github.com/foundry-rs/foundry/assets/57450786/3022ec1c-0356-48f8-8cec-59a759ab5ab5)
