### ISSUE TITLE
multibyte string crashes foundry-compilers

### ISSUE THREAD

**Issue by radeksvarz** [foundry-rs/foundry#6718]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6fc7463 2024-01-05T00:21:51.712802723Z)

### What command(s) is the bug in?

forge script

### Operating System

Linux

### Describe the bug

script had this string in the code: `\u250c\u2500\u2015\u2015┄┈\n"`

```
 forge script script/Example.s.sol --broadcast --private-key $PK --slow --rpc-url $RPC
[⠢] Compiling...
[⠆] Compiling 3 files with 0.8.20The application panicked (crashed).
Message:  byte index 47 is not a char boundary; it is inside '┄' (bytes 46..49) of `57 |                 "\u250c\u2500\u2015\u2015┄┈\n"`
Location: /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/foundry-compilers-0.1.2/src/artifacts/mod.rs:2084

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry
```

Edge case - mitigated by properly escaping all unicode chars.

**Comment by onbjerg** [comment]
Interesting, cc @matthias.seitz any ideas here?

**Comment by mattsse** [comment]
this has been mitigated by https://github.com/foundry-rs/compilers/pull/40

and now correctly displays the solc error:

```
Error: 
Compiler run failed:
Error (8936): Invalid character in string. If you are trying to use Unicode characters, use a unicode"..." string literal.
  --> src/Counter.sol:12:28:
   |
12 |         string memory  s = "\u250c\u2500\u2015\u2015┄┈\n";
```
