### ISSUE TITLE
[Trojan:Script/Wacatac.B!ml] Defender on Windows 10 pinned forge.exe 

### ISSUE THREAD

**Issue by TheHustler0** [foundry-rs/foundry#6723]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### Operating System

Windows

### Describe the bug

Hi,

Just downloaded Foundry from this nightly release:
https://github.com/foundry-rs/foundry/releases/tag/nightly-c7b1c18472059c938de697d4fd72de9938527b48

After download, tried copying the executable to another folder, this made Windows Defender (Defender is triggered each time a file gets in clipboard) raised an alert at Trojan detection in forge.exe file. 

![forge_virus](https://github.com/foundry-rs/foundry/assets/123905476/685f94b6-9d6a-4f6d-b7cd-4f791f72209d)

Also Chrome previously stopped download because of suspicious file.

**Comment by onbjerg** [comment]
I'm not really sure what we can do here as I am not on Windows, so it's hard to reproduce. Do you have any pointers? For example, does Windows also complain if you compile from source?

**Comment by TheHustler0** [comment]
Didn't try to compile from source, only used binaries of nighly build. To reproduce, simply download that specific build on a Windows 10 VM or a sandbox, after that just moving file should be enough to trigger Defender scanner & detection.

**Comment by DaniPopes** [comment]
There is basically nothing we can do on our side, Windows Defender likes to flag Rust binaries as malicious. You can only whitelist it.
