### ISSUE TITLE
`fmt`: defaults produce different results between two versions

### ISSUE THREAD

**Issue by riordant** [foundry-rs/foundry#6726]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (02292f2 2024-01-08T00:22:29.377806466Z)

### What command(s) is the bug in?

forge fmt

### Operating System

Linux

### Describe the bug

Hi guys,

we have a strange issue with formatting, that was only introduced from the `nightly-5b7e4cb3c882b28f3c32ba580de27ce7381f415a` release (2023-12-02) onwards. it appears that the default formatting rules have changed.

here is how to repro:
clone https://github.com/spoolfi/spool-v2-core/, forge install

`foundryup -v nightly-60ec00296f00754bc21ed68fd05ab6b54b50e024` (version 2023-11-01)
`forge fmt` - produces no formatting changes.

`foundryup -v nightly-5b7e4cb3c882b28f3c32ba580de27ce7381f415a` (version 2023-12-02)
`forge fmt` - produces a host of changes.

Our toml file has no `[fmt]` entries indicating that it should be using the defaults.

This means that we can no longer update foundry from this version without the source being modified.

i have tried to figure out exactly where the issue was introduced, but the only formatting changes are to introduce `hex_underscore` rules which should not affect it.

**Comment by riordant** [comment]
Ok, thanks for pointing it out. I was just trying to figure out if this was a breaking change or a bug, looks like the former.
No particular thing we disagree with, it's just that it modifies audited code in our `src/`, which we do not want to change anymore. 
Is there anyway to preserve the old rules with new versions? I guess not then?

**Comment by DaniPopes** [comment]
> Is there anyway to preserve the previous new rules with new versions? I guess not as there is not a format option for new expressions?

No, this was a bug fix because new expressions were getting skipped altogheter.

> it's just that it modifies audited code in our src/, which we do not want to change anymore.

You should ignore the directory instead of relying on us not to ever change the formatter
