### ISSUE TITLE
bug in foundry 

### ISSUE THREAD

**Issue by heheboii11** [foundry-rs/foundry#6727]
The application panicked (crashed).
Message:  byte index 11 is not a char boundary; it is inside 'ß' (bytes 10..12) of `17 |     }ß`
Location: /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/foundry-compilers-0.1.1/src/artifacts/mod.rs:208
getting this error

**Comment by DaniPopes** [comment]
@heheboii11 This bug was fixed recently, can you please try again after `foundryup`?

**Comment by heheboii11** [comment]
yes it worked thank you
