### ISSUE TITLE
ETH_RPC_URL doesn't work

### ISSUE THREAD

**Issue by thedavidmeister** [foundry-rs/foundry#6731]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### Operating System

None

### Describe the bug

I see `ETH_RPC_URL` in the `RpcOpts`

```rust
#[derive(Clone, Debug, Default, Parser)]
pub struct RpcOpts {
    /// The RPC endpoint.
    #[clap(short = 'r', long = "rpc-url", env = "ETH_RPC_URL")]
    pub url: Option<String>,
```

But it does not work for me, afaics the only way to get forge to actually use it is like `forge script --rpc-url "$ETH_RPC_URL"` which doesn't seem right to me.

I expect that when i use the environment variable defined in the config that i don't also have to pass it to the flag for the same option.

**Comment by thedavidmeister** [comment]
seems relevant

https://github.com/foundry-rs/foundry/pull/1231

https://github.com/foundry-rs/foundry/pull/1238/files

personally i'd like to be able to use environment variables when i can, there wasn't a good explanation that i see for why it was (partially) removed

**Comment by onbjerg** [comment]
What version are you on?

**Comment by thedavidmeister** [comment]
```
davids-iMac:rainix thedavidmeister$ forge --version
forge 0.2.0 (02292f2 2024-01-08T00:26:30.856271000Z)
```

@onbjerg

**Comment by onbjerg** [comment]
Two more questions:

* What operating system are you on?
* Can you clarify what you mean by "I expect that when i use the environment variable defined in the config"?

In the future please fill out the issue form with the relevant info (OS and version) so we don't have to ask 😄

**Comment by thedavidmeister** [comment]
@onbjerg 

you can see the issue on ubuntu

https://github.com/rainlanguage/rain.subgraph.docker/actions/runs/7449003666/job/20264616372#step:11:30

here's a build where `ETH_RPC_URL` is set in the CI environment but we get

```
If you wish to simulate on-chain transactions pass a RPC URL.
```

adding `--rpc-url "$ETH_RPC_URL"` makes this go away but clap macro makes me expect `--rpc-url` to be equal to `ETH_RPC_URL` already, so I see this as a bug

```
#[clap(short = 'r', long = "rpc-url", env = "ETH_RPC_URL")]
```

**Comment by grandizzy** [comment]
@thedavidmeister you can now add the key in config and env vars are picked up  (see sample here https://github.com/foundry-rs/foundry/issues/8795#issuecomment-2393133819)
e.g.
```
eth_rpc_url = "mainnet"

[profile.default.rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
```

then you can `forge script --rpc-url mainnet`

Please reopen if still an issue, thank you.
