### ISSUE TITLE
foundry binaries that the nix overlay relies on are getting rugged

### ISSUE THREAD

**Issue by thedavidmeister** [foundry-rs/foundry#6732]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### Operating System

macOS (Apple Silicon)

### Describe the bug

There is discussion on the nix overlay

https://github.com/shazow/foundry.nix/issues/31#issuecomment-1879751727

**Comment by onbjerg** [comment]
I don't know how the linked repository works and there is really not enough context for me to resolve this issue. What is the issue exactly? Are you trying to download old nightlies? Nightlies are purged after a while, we only keep a few around.

**Comment by jaypaik** [comment]
We're running into the same thing too after recently updating our pinned nightly version in CI. And these are very recent versions.

Examples of ones that poofed:
- https://github.com/foundry-rs/foundry/releases/tag/nightly-6fc74638b797b8e109452d3df8e26758f86f31fe
- https://github.com/foundry-rs/foundry/releases/tag/nightly-02292f2d2caa547968bd039c06dc53d98b72bf39

Do you have recommendations on the latest stable version we can use that won't be purged?

**Comment by thedavidmeister** [comment]
<img width="696" alt="Screenshot 2024-01-10 at 10 22 28" src="https://github.com/foundry-rs/foundry/assets/629710/fd66806d-3ad6-407d-8a1d-f0b57789f536">

@onbjerg context from TG, yes we need versions of binaries that we pin to remain existant

**Comment by shazow** [comment]
Looks like the "permanent" monthly releases are getting wiped (the first nightly release of each month is supposed to be retained). Reference PR: https://github.com/foundry-rs/foundry/pull/3888

Need to investigate what changed.

**Comment by shazow** [comment]
cc @hellwolf, since you did the work last time (thank you again!), in case you wanted to take a peek.

**Comment by shazow** [comment]
I think this is the issue:

https://github.com/foundry-rs/foundry/blob/b0e70ba7401d120701de10dee2b09d4e55c7354e/.github/scripts/prune-prereleases.js#L16-L17

If the first of the month release gets nuked or missed, then a new release is never retained.

**Comment by onbjerg** [comment]
Yes, that script is responsible for pruning nightly releases so they don't stick around. Otherwise we'd have over 700 releases at this point 😄 The releases will continue to get purged until we release a stable, but I do see the reasoning in keeping around some "monthly nightlies". The script above should be adjusted accordingly

**Comment by hellwolf** [comment]
Hey folks, I can have a look asap.

P.S. I did notice this week that the https://github.com/shazow/foundry.nix monthly was broken this week.

**Comment by shazow** [comment]
@hellwolf Much appreciated!

I'm semi-AFK the next several days but happy to review PRs too. @thedavidmeister also said he'll be able to contribute some time this weekend if it's not resolved already. :)

**Comment by thedavidmeister** [comment]
@onbjerg what would be the problem with over 700 releases?

**Comment by thedavidmeister** [comment]
@shazow @hellwolf https://github.com/shazow/foundry.nix/pull/32

Here's a PR that sets the github node id for the "version" rather than a hardcoded `0.0.0` so maybe that helps with the hash corruption issue (which is not the 404 issue, but it certainly exacerbates the situation)

**Comment by thedavidmeister** [comment]
<img width="1294" alt="Screenshot 2024-01-14 at 11 17 03" src="https://github.com/foundry-rs/foundry/assets/629710/26fc72a1-b673-4a16-91cb-f61c1f29ab6c">

@shazow @onbjerg @hellwolf 

So looks like the tags that are `nightly-<hash>` are mutable and non-deterministic?

This release was 20 hours ago, i ran the overlay update script 19 hours ago to pick up all the assets, then all the assets changed 6 hours ago and the derivation is now corrupted because the sha of the assets doesn't match.

Why are the assets being replaced on hash-tagged releases?

**Comment by thedavidmeister** [comment]
https://github.com/foundry-rs/foundry/pull/6789 here's a PR that includes the timestamp in the nightly release tag

rust builds are not deterministic so if two release jobs ever run for the same github sha then currently the releases will collide and the assets will be rebuilt, and anyone downstream that is checking the hash of the releases will see it as a corrupt release

**Comment by hellwolf** [comment]
Fwiw, how I test locally: https://github.com/foundry-rs/foundry/blob/master/.github/scripts/prune-prereleases.js

```
import { Octokit, App } from "octokit";

// Create a personal access token at https://github.com/settings/tokens/new?scopes=repo
const octokit = new Octokit({ });

async function prune({ github, context }) {
    console.log("Pruning old prereleases");

    // doc: https://docs.github.com/en/rest/releases/releases
    const { data: releases } = await github.rest.repos.listReleases({
        owner: context.repo.owner,
        repo: context.repo.repo,
    });

    let nightlies = releases.filter(
        release =>
            // Only consider releases tagged `nightly-${SHA}` for deletion
            release.tag_name.includes("nightly") &&
            release.tag_name !== "nightly" &&
            // ref: https://github.com/foundry-rs/foundry/issues/3881
            // Skipping pruning the build on 1st day of each month
            !release.created_at.includes("-01T")
    );

    // Keep newest 3 nightlies
    //nightlies = nightlies.slice(3);

    return nightlies;
};

(async() => {
    console.log((await prune({
        github : octokit,
        context : {
            repo : { owner: "foundry-rs", repo: "foundry" }
        },
    })).map(i => i.name));
})();
```

```
$ cat package.json 
{
  "dependencies": {
    "octokit": "^3.1.2"
  }
}
```

```
$ node index.mjs 
Pruning old prereleases
[
  'Nightly (2024-01-15)',
  'Nightly (2024-01-14)',
  'Nightly (2024-01-12)'
]
```

**Comment by hellwolf** [comment]
@shazow  I noticed that the monthly action starts to run every month:

https://github.com/shazow/foundry.nix/actions/workflows/update-foundry-bin-monthly.yml

**Comment by hellwolf** [comment]
https://github.com/foundry-rs/foundry/pull/6806

**Comment by shazow** [comment]
> @shazow I also noticed that the monthly action starts to run every month:
> 
> https://github.com/shazow/foundry.nix/actions/workflows/update-foundry-bin-monthly.yml

The monthly action runs daily now, since it was made to be idempotent.

**Comment by hellwolf** [comment]
> > @shazow I also noticed that the monthly action starts to run every month:
> > https://github.com/shazow/foundry.nix/actions/workflows/update-foundry-bin-monthly.yml
> 
> The monthly action runs daily now, since it was made to be idempotent.

Okay, that makes sense. It added stronger requirement to the pruning script for sure, I think the PR #6806 should have fixed it.

**Comment by hellwolf** [comment]
Fwiw, this is the kept jan release: https://github.com/foundry-rs/foundry/releases/tag/nightly-293fad73670b7b59ca901c7f2105bf7a29165a90
