### ISSUE TITLE
v1.0 is ready, make it so 🫡

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#6747]
1.0 coming in the next few weeks! Thanks for the patience.

_Originally posted by @gakonst in https://github.com/foundry-rs/foundry/issues/872#issuecomment-1535691090_
         
         
Now that Alloy Providers is here lets give the lads a win and release v1.0

**Comment by mattsse** [comment]
it's happening, but there are still a few things left to do, the biggest blocker is resolved now.

**Comment by shazow** [comment]
I wouldn't be mad if there were some v0.x releases first, to really ease yourself in before all of the things left to do are done. :)

**Comment by sambacha** [comment]
> it's happening, but there are still a few things left to do, the biggest blocker is resolved now.

Ok ok v1.0-RC1 it is then

Release Candidate 1 ✨⭐️

Lets get some HYPE

**Comment by shazow** [comment]
### _**‼️**_

**Comment by onbjerg** [comment]
Duplicate of #3895
