### ISSUE TITLE
bug(`forge test`): `no artifact for contract` when using library with external functions

### ISSUE THREAD

**Issue by mejango** [foundry-rs/foundry#6756]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (88ae503 2023-12-17T00:19:58.880993000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

![image](https://uploads.linear.app/f2544f8c-2bdf-42c2-a891-97db14e1d6ff/ba02208c-5140-4921-adfa-be5815e0d40a/d494fc42-bd32-4bd9-b9f9-48dbfbe25e41?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2YyNTQ0ZjhjLTJiZGYtNDJjMi1hODkxLTk3ZGIxNGUxZDZmZi9iYTAyMjA4Yy01MTQwLTQ5MjEtYWRmYS1iZTU4MTVlMGQ0MGEvZDQ5NGZjNDItYmQzMi00YmQ5LWI5ZjktNDhkYmZiZTI1ZTQxIiwiaWF0IjoxNzEyNjYxMjQ0LCJleHAiOjMzMjgzMjIxMjQ0fQ.QwTKqEjLtdvA_Nelpz86cZorR-HV5JdYfsh8UIfqjO0 "=1345x")

Tests run once, and only run again once `forge clean` is run.

src/libraries/JBMetadataResolver.sol:JBMetadataResolver is a library with public functions that are accessed in the contract being tested.

![image](https://uploads.linear.app/f2544f8c-2bdf-42c2-a891-97db14e1d6ff/5f32bc40-bdb7-42ba-a325-ee23bf9389d4/cf827c7e-bea7-438f-aa00-7d717daa2e0e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2YyNTQ0ZjhjLTJiZGYtNDJjMi1hODkxLTk3ZGIxNGUxZDZmZi81ZjMyYmM0MC1iZGI3LTQyYmEtYTMyNS1lZTIzYmY5Mzg5ZDQvY2Y4MjdjN2UtYmVhNy00MzhmLWFhMDAtN2Q3MTdkYWEyZTBlIiwiaWF0IjoxNzEyNjYxMjQ0LCJleHAiOjMzMjgzMjIxMjQ0fQ.zHcTKlRHps7ULdwoNr1ichOvpvM3IV5A_ejtGZssr5k "=782x")

![image](https://uploads.linear.app/f2544f8c-2bdf-42c2-a891-97db14e1d6ff/1f7742ee-b9b9-461a-aa67-748ee5730f7d/49943b60-51eb-4732-be0b-d095dd6bde7a?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2YyNTQ0ZjhjLTJiZGYtNDJjMi1hODkxLTk3ZGIxNGUxZDZmZi8xZjc3NDJlZS1iOWI5LTQ2MWEtYWE2Ny03NDhlZTU3MzBmN2QvNDk5NDNiNjAtNTFlYi00NzMyLWJlMGItZDA5NWRkNmJkZTdhIiwiaWF0IjoxNzEyNjYxMjQ0LCJleHAiOjMzMjgzMjIxMjQ0fQ.iquLHOSoJcrbt3_C8BNjAUSfhp-yEQ2biYXkcjHH_no "=934x")

**Comment by mattsse** [comment]
could you please provide a repro, can't debug otherwise

**Comment by zerosnacks** [comment]
ping @mejango, a minimal reproduction would still be appreciated to narrow this down

**Comment by grandizzy** [comment]
the code pointed out in ticket was rewritten, please reopen with a sample to reproduce if still an issue. thank you!
