### ISSUE TITLE
createFork for same block number multiple times adds an extra `/` for every call

### ISSUE THREAD

**Issue by maa105** [foundry-rs/foundry#6759]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (71d8ea5 2024-01-09T14:41:14.837767655Z)

### What command(s) is the bug in?

createFork/createSelectFork

### Operating System

Linux

### Describe the bug

each time you use a createFork for a specific block number it adds a `/` to the rpcUrl. try:
```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.21;

import {console, Test} from "forge-std/Test.sol";

import {Vm} from "forge-std/Vm.sol";

contract MyTest is Test {
    function testStart() public {
        vm.createFork('ws://valid-rpc-url:1000', 18983785);
        vm.createFork('ws://valid-rpc-url:1000', 18983785);
        vm.createFork('ws://valid-rpc-url:1000', 18983785); // <-- it will fail here
    }
}
```

Error:
```
    ├─ [0] VM::createFork("ws://valid-rpc-url:1000", 18983785 [18.98e6])
    │   └─ ← Could not instantiate forked environment with fork url: ws://valid-rpc-url:1000//
    └─ ← Could not instantiate forked environment with fork url: ws://valid-rpc-url:1000//
```

notice the error the fork url adds 2 `/`

we tried

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.21;

import {console, Test} from "forge-std/Test.sol";

import {Vm} from "forge-std/Vm.sol";

contract MyTest is Test {
    function testStart() public {
        vm.createFork('ws://valid-rpc-url:1000/', 18983785);
        vm.createFork('ws://valid-rpc-url:1000/', 18983785); // <-- it will fail here
        vm.createFork('ws://valid-rpc-url:1000/', 18983785);
    }
}
```

Notice here we added a `/` here explicitly. it failed one statement before with the same error with two `/`

even if we add different block# for createFork it will break only on the third of the same block number.

**Comment by maa105** [comment]
notice valid-rpc-url:1000 is dummy replacement for our real node

**Comment by mattsse** [comment]
the added slash was a previous hotfix

properly fixed with #6765

**Comment by maa105** [comment]
Thx for the fix. We noted also that forking using transaction hash has the same issue i.e. `creacteFork(rpcUrl, txHash);` 3 times on the same rpcUrl and txHash will cause the same issue. Not sure if this helps

**Comment by maa105** [comment]
you are awesome guys! tested it with block number and transaction hash both work as expected thanks!
