### ISSUE TITLE
Attempt to subtract with overflow while using bound in invariant test

### ISSUE THREAD

**Issue by FaisalAli19** [foundry-rs/foundry#6779]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (b9d9a5c 2023-12-19T12:25:23.960984000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Intel)

### Describe the bug

Hello,

I encountered an issue while using the bound function in an invariant test. The test fails with the error "attempt to subtract with overflow" when the minimum value passed to bound is set to 1. However, if I set the minimum value to 0, the test runs correctly but fails when the value is 1 or more.

<img width="734" alt="Screenshot 2024-01-13 at 12 47 38 AM" src="https://github.com/foundry-rs/foundry/assets/20942500/3e3633db-9f60-4c0c-8a14-bba9e8072605">

Here's the code snippet:

This works

```solidity
function depositToken(uint256 _amount) public {
    uint256 amount = bound(_amount, 0, INITIAL_BALANCE);
    vm.startPrank(user);
    tokenA.approve(address(pool), amount);
    tokenB.approve(address(pool), amount);
    tokenC.approve(address(pool), amount);
    pool.deposit(amount, uint64(block.timestamp + 10 days));
    vm.stopPrank();
}
```

This doesn't

```solidity
function depositToken(uint256 _amount) public {
    uint256 amount = bound(_amount, 1, INITIAL_BALANCE);
    vm.startPrank(user);
    tokenA.approve(address(pool), amount);
    tokenB.approve(address(pool), amount);
    tokenC.approve(address(pool), amount);
    pool.deposit(amount, uint64(block.timestamp + 10 days));
    vm.stopPrank();
}
```

I would appreciate any guidance or suggestions on how to handle this issue effectively.

Thank you!

**Comment by mattsse** [comment]
this should be closed by https://github.com/foundry-rs/foundry/pull/6819
