### ISSUE TITLE
perf(fuzz): Fuzzing `uint256[][]` is very slow (30s+ for noop)

### ISSUE THREAD

**Issue by thedavidmeister** [foundry-rs/foundry#6784]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (78b22db 2024-01-13T00:17:38.098713000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

Running any test with `uint256[][]` in the fuzzer is very slow, much slower than `uint256[]`.

I made a noop test with a single `uint256[][]` argument and it took 36s.

The same test with a `uint256[]` argument took 390ms, so about 100x faster.

I've generally found the same if the `uint256[][]` appears somewhere in a struct etc. so I think it's probably just related to how the fuzzer builds nested structures.

**Comment by thedavidmeister** [comment]
actually doing something in the test gets extra slow

<img width="611" alt="Screenshot 2024-01-14 at 00 29 14" src="https://github.com/foundry-rs/foundry/assets/629710/8a4595e6-6c09-44e4-bd35-7f7c108943c4">
<img width="624" alt="Screenshot 2024-01-14 at 00 29 23" src="https://github.com/foundry-rs/foundry/assets/629710/5baca17f-db40-4bdb-81ac-cdf88c54775f">

**Comment by DaniPopes** [comment]
Well I think that's fair for 25.7M gas per run, for 2056 runs. I'm sure we can lower the time, but I don't believe by much.

**Comment by DaniPopes** [comment]
Using

```solidity
contract CounterTest is Test {
    function testFuzz_SetNumber(bool[][] memory x) public {}
}
```

Profiles:
- 12.95s debug mode: https://share.firefox.dev/47PFR5T
-  2.35s release mode: https://share.firefox.dev/3HD30Oh

14% of the time is spent generating values, 26% in our own `Inspector::{step, step_end}` functions, 60% running the transactions.

This is probably where the next Revm update might help us with custom opcodes, but in general we're still just executing a ton of bytecode.

**Comment by thedavidmeister** [comment]
@DaniPopes is there real value in generating gigantic matrices? i'd expect that there are diminishing returns at some point and data only needs to be so big to flush out most issues

**Comment by grandizzy** [comment]
we don't plan to make any change of this behavior as it is something more related to the way tests are written / organized
