### ISSUE TITLE
`forge init` requires setting `user.name` and `user.email` in git global config

### ISSUE THREAD

**Issue by 0kenx** [foundry-rs/foundry#6798]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (c5fd67b 2024-01-15T00:23:11.184513736Z)

### What command(s) is the bug in?

forge init abc

### Operating System

Linux

### Describe the bug

`forge init` fails when git global configs `user.name` and `user.email` are unset. Those settings are not necessary when initiating a git repo, and I do not want to set those global settings (with multiple accounts I want to minimize the chance of mixing things up, so I set those for each repo individually).

**Comment by onbjerg** [comment]
Pass `--no-git` or `--no-commit`
