### ISSUE TITLE
forking using a transaction hash speed heavily depends on the tx position inside the block

### ISSUE THREAD

**Issue by maa105** [foundry-rs/foundry#6811]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (293fad7 2024-01-14T00:19:14.283768427Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

It seems the speed of createSelectFork when using it like `createSelectFork(rpcUrl, transactionHash)` heavily depends on the the order of set transaction within the block. In the below test the [0xe55 transaction](https://etherscan.io/tx/0xe55a899b252090c71988e0c069e75b7df468d7110993e89937cec29a2d503a9d) is the first transaction in eth mainnet block [19017590](https://etherscan.io/block/19017590) and [0x8e4 transaction](https://etherscan.io/tx/0x8e456439e743e9d85b4444e6221d395f4e6079acc4a392c0b1ca03e11a4f0e2b) is the last (137th) transaction in that same block. the code below attempts to create a fork at each of these transactions. the output of the code will be something like:

![image](https://github.com/foundry-rs/foundry/assets/5106107/f493687f-30da-414b-b0b5-61703f5565ba)

~340ms for last transaction, ~10ms for first transaction a significant degradation for later transactions.

P.S. replace `valid-rpc-url` by your rpc url

P.S. depending on your eth node's history retention and the time you run the below test the test might fail if the node does not keep the whole blockchain history. so to test just go to [ethscan blocks](https://etherscan.io/blocks) select latest block and then select first transaction hash and last transaction hash and replace below.

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.21;

import {console,Test} from "forge-std/Test.sol";

contract EntryTest is Test {

    function testStart() public {
        uint s1 = vm.unixTime();
        vm.createSelectFork('ws://valid-rpc-url', vm.parseBytes32('0x8e456439e743e9d85b4444e6221d395f4e6079acc4a392c0b1ca03e11a4f0e2b')); // last tx
        uint s2 = vm.unixTime();
        vm.createSelectFork('ws://valid-rpc-url', vm.parseBytes32('0xe55a899b252090c71988e0c069e75b7df468d7110993e89937cec29a2d503a9d')); // first tx
        uint s3 = vm.unixTime();
        console.log("T1", s2 - s1); // ~340ms
        console.log("T2", s3 - s2); // ~10ms
    }
}
```

**Comment by mattsse** [comment]
> t seems the speed of createSelectFork when using it like createSelectFork(rpcUrl, transactionHash) heavily depends on the the order of set transaction within the block.

this is expected because it needs to replay the state up until the targeted transaction.
The way this works is, the fork is created based on the transaction's parent block and then all the previous transactions in the block are replayed so you get the exact state of the transaction.

**Comment by maa105** [comment]
@mattsse Thanks for the answer I expected as such. but is this sever degradation expected? Cause I believe the application of a transaction should be very fast and the bottleneck would be fetching the transactions from the network. I suspect that the transactions are not fetched in batch but rather one by one and applied which might explain the above results.

**Comment by mattsse** [comment]
when a tx is executed we need to fetch every unknown slot, so basically every SLOAD and account access is translated into rpc requests, which can easily lead to ratelimiting by the provider

**Comment by maa105** [comment]
We are using a local node. Rate limiting is not the issue I'm affraid

**Comment by mattsse** [comment]
could you try with --no-rate-limit
