### ISSUE TITLE
need run `forge fmt` twice to make `forge fmt --check` happy.

### ISSUE THREAD

**Issue by robinsdan** [foundry-rs/foundry#6812]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (24abca6 2024-01-16T07:35:41.234348345Z)

### What command(s) is the bug in?

forge fmt

### Operating System

Linux

### Describe the bug

the following code shows the difference after run `forge fmt`, then run `forge fmt --check` will report error for the line 93.
![image](https://github.com/foundry-rs/foundry/assets/115981357/0aa212d9-39b6-47f8-bc80-579bf3786220)
rerun `forge fmt` again, the space at line 93 will be removed.
![image](https://github.com/foundry-rs/foundry/assets/115981357/61e9445e-964e-4b63-9e40-036185845cf3)

**Comment by mattsse** [comment]
could you please provide this snippet as text?

**Comment by robinsdan** [comment]
```solidity
    /**
     *  TODO: this fuzz use too much time to execute
    function testGetFuzz(bytes[2][] memory kvs) public {
        for (uint256 i = 0; i < kvs.length; i++) {
            bytes32 root = trie.update(kvs[i][0], kvs[i][1]);
            console.logBytes32(root);
        }

        for (uint256 i = 0; i < kvs.length; i++) {
            (bool exist, bytes memory value) = trie.get(kvs[i][0]);
            console.logBool(exist);
            console.logBytes(value);
            require(exist);
            require(BytesSlice.equal(value, trie.getRaw(kvs[i][0])));
        }
    }
    */
```
