### ISSUE TITLE
feature request: add `--token` option to cast balance 

### ISSUE THREAD

**Issue by fenghaojiang** [foundry-rs/foundry#6813]
### Component

Cast

### Describe the feature you would like

Currently I use following ways to get erc20 / erc721 balance. 

```shell
cast call [token_address] "balanceOf(address) returns uint256" --rpc-url=https://rpc.ankr.com/eth 
```
Every time I spend some time to write the method sig params. 
IMHO, as erc20 / erc721 become standard and become some common sense rules, I want to make a short cut to get erc20 / erc721 balance.  

Like: 

```
cast balance 0x162c6270266667ccf5a9ed752b5d6a2bdc0f90de --token=0x5a98fcbea516cf06857215779fd812ca3bef1b32  --rpc-url=https://rpc.ankr.com/eth
```

And I would like to implement it.

**Comment by Evalir** [comment]
@fenghaojiang feel free to go for it!

**Comment by mds1** [comment]
The proposed UX of `cast balance --token <address>` lgtm!

**Comment by gakonst** [comment]
supportive
