### ISSUE TITLE
Forge test hangs while using -vvv

### ISSUE THREAD

**Issue by Krishnakumarskr** [foundry-rs/foundry#6814]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (24abca6 2024-01-16T00:26:29.551032000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

When I run the forge test command with -vvv or -vvvv or -vvvvv, it simply hangs right after [PASS] or [FAIL] it's not printing any other traces after this.

No issues on using -v or -vv

<img width="618" alt="Screenshot 2024-01-16 at 4 57 48 PM" src="https://github.com/foundry-rs/foundry/assets/29063514/a8005835-bf75-4b32-b22b-3eb2235ab646">

**Comment by mattsse** [comment]
is this public? need a repro to debug

**Comment by Evalir** [comment]
@Krishnakumarskr thanks! this is impossible to look at without knowing what you're doing or a repro. It doesn't hang for me through any codebases I can test on.

**Comment by Krishnakumarskr** [comment]
Thanks for looking into this! 
It resolved automatically. Haven't made any change. I was trying everything for 6hrs, still I got the same issue. But, somehow it's working now. I haven't even restarted the system. But, just started working. Not sure of the root cause.
Closing this issue for now.
