### ISSUE TITLE
native String utils cheatcodes

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#6818]
### Component

Forge

### Describe the feature you would like

such as

replace
lowercase
uppercase
trim
split
...

**Comment by 1010adigupta** [comment]
can take this

**Comment by 1010adigupta** [comment]
@mattsse can you provide some more context of these features here?

**Comment by mattsse** [comment]
here are some docs/instructions

https://github.com/foundry-rs/foundry/blob/master/docs/dev/cheatcodes.md#cheatcodes-implementation

what we want is something like:

`function toLowercase(string) returns string`

the rust cheatcode then simply returns `.to_lowercase()`

see EnvBool cheatcode for example:

https://github.com/foundry-rs/foundry/blob/6b2633c6fe7d894c4ae46899f9cd928e4d49d227/crates/cheatcodes/spec/src/vm.rs#L844-L847

https://github.com/foundry-rs/foundry/blob/6b2633c6fe7d894c4ae46899f9cd928e4d49d227/crates/cheatcodes/src/env.rs#L27-L32

**Comment by bolajahmad** [comment]
Are you currently working on this @1010adigupta? I find it interesting and would like to work on it especially after the great guide from @mattsse

**Comment by bolajahmad** [comment]
@mattsse a few questions, for the native string utils are you suggesting adding the following and any other suggestions?
_replace, lowercase, uppercase, trim, split_

Implementing the string to the respective cheat code and returning the response, will that suffice to close this issue?

**Comment by 1010adigupta** [comment]
yes currently working on it :)

**Comment by mattsse** [comment]
> Implementing the string to the respective cheat code and returning the response, will that suffice to close this issue?

yes, I guess we also want these:

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Strings.sol

**Comment by 1010adigupta** [comment]
In what group should these Utils go?
string or env?

**Comment by 1010adigupta** [comment]
Hey @mattsse I have created a pr for string utils of lowercase, uppercase, trim, replace, split if that's lgtm you can merge it

**Comment by 1010adigupta** [comment]
> > Implementing the string to the respective cheat code and returning the response, will that suffice to close this issue?
> 
> yes, I guess we also want these:
> 
> https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/Strings.sol
