### ISSUE TITLE
processing of WASM opcodes 

### ISSUE THREAD

**Issue by 1010adigupta** [foundry-rs/foundry#6820]
### Component

Forge

### Describe the feature you would like

I think Foundry is not able to recognise WASM opcodes now, due to which I am not able to get gas reports of Stylus contracts using foundry, even though they are fully interoperable with solidity contracts.
can anyone tell me if this feature is in the pipeline? if not then I would like to work on this.

**Comment by DaniPopes** [comment]
WASM and Stylus are completely out of scope of this project.
