### ISSUE TITLE
The application panicked (crashed).

### ISSUE THREAD

**Issue by rasyidred** [foundry-rs/foundry#6829]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (477b345 2023-12-18T00:22:09.434601489Z)

### What command(s) is the bug in?

forge test, forge clean, forge update, and maybe more

### Operating System

Windows

### Describe the bug

**Problem** 
When attempting to execute `forge test` on my project, an unexpected error occurred, resulting in the following messages:
```
The application panicked (crashed).
Message:  failed to extract foundry config:
foundry.toml error: Input/output error (os error 5)
 in foundry.toml TOML file

Location: crates/config/src/lib.rs:465

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
Aborted
```

Additionally, when including RUST_BACKTRACE=FULL, the extended result is:
```
The application panicked (crashed).
Message:  failed to extract foundry config:
foundry.toml error: Input/output error (os error 5)
 in foundry.toml TOML file

Location: crates/config/src/lib.rs:465

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: __libc_start_main<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
Aborted
```

Even after executing forge clean and forge update, the issue persists. Furthermore, when navigating to other projects, the same error messages continue to appear. I am currently using Windows 11 and running Foundry with WSL.

**Comment by mattsse** [comment]
hmm, could you share your foundry.toml file?

**Comment by rasyidred** [comment]
Here is my foundry.toml
```
[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read", path = "./out"}]

ignored_error_codes = ["license", "unused-param", "unused-var"]

[invariant]
runs = 64
depth = 64
fail_on_revert = true

[fmt]
line_length = 80

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
```

Additionally, I needed to install Foundry from scratch since I couldn't really do anything. Now it works well, though.

**Comment by Evalir** [comment]
Interesting, so, confirming a reinstall fixed the issue? @rasyidred

**Comment by rasyidred** [comment]
@Evalir Yes, a reinstall fixed the issue. Unfortunately, however, I couldn't replicate the error.

**Comment by Evalir** [comment]
Let's close for now—this could've been some installation error that might not be worth tracking down. If this appears again we'll reopen
