### ISSUE TITLE
called `Result::unwrap()` on an `Err` value: TryFromSliceError(())

### ISSUE THREAD

**Issue by PengDeng-Cyber** [foundry-rs/foundry#6839]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (b51c057 2024-01-18T00:23:54.396010000Z)

### What command(s) is the bug in?

forge script script/DeployAll.s.sol:DeployAll --rpc-url $RPC_URL --private-key $PRIVATE_KEY --broadcast --slow -vvv

### Operating System

macOS (Apple Silicon)

### Describe the bug

```
Script ran successfully.

## Setting up 1 EVM.
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: TryFromSliceError(())
Location: /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/alloy-primitives-0.6.0/src/bits/address.rs:45

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
/bin/sh: line 1: 32126 Abort trap: 6           FOUNDRY_PROFILE=stg forge script script/DeployAll.s.sol:DeployAll --rpc-url $RPC_URL --private-key $PRIVATE_KEY --broadcast --slow -vvv
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Evalir** [comment]
Could you provide a repro for this? it's hard to look into otherwise

**Comment by DaniPopes** [comment]
I cannot find any panics in the logged files, so without a backtrace or repro this issue is not actionable. Feel free to reopen if you can provide anything.
