### ISSUE TITLE
Grep package version/tag instead of exact match during forge install

### ISSUE THREAD

**Issue by pmdaly** [foundry-rs/foundry#685]
### Component

Forge

### Describe the feature you would like

`forge install openzeppelin/openzeppelin-contracts@3.1.0` falls back to latest version despite the presence of v3.1.0 in the list of tags, which can additionally be confusing if you thought you were installing 3.1.0.  The above command will work if the exact full tag is added.  There are no other tags with 3.1.0 in their strings so exact match fails but a grep would return the correct result.

Suggested change: search all tags for version requested. If no tag is found, error and display what versions are available. If one tag is found, install it.  If multiple tags contain the version (ie, 3.1 and 3.1.1 when searching with 3.1) then prompt for a selection.

### Additional context
Here's an example of when a package version is not found using pip
![Screen Shot 2022-02-06 at 10 40 48 AM](https://user-images.githubusercontent.com/8229664/152696252-b32181bc-7688-4ffd-b2b4-fbdfa590a262.png)

**Comment by 0xYYY** [comment]
I can work on this if this feature is still being considered.

My current thought is as following:
1. do a regex match `r"v?\d+(\.\d+)*"` on `tag`
2. if there's a match, then before `git checkout` ([here](https://github.com/foundry-rs/foundry/blob/37452a3644e6a7e356204096232345f8aede53b6/cli/src/cmd/forge/install.rs#L143) and [here](https://github.com/foundry-rs/foundry/blob/37452a3644e6a7e356204096232345f8aede53b6/cli/src/cmd/forge/install.rs#L199)), we get the list of tags in the repo with `git tag`
4. show the list and let user select which tag to use.

This should improve the UX when specifying a version tag, while the functionality of selecting a branches/commits to install still stays the same.

**Comment by 0xYYY** [comment]
Something like this:
![2022-04-29_01:13:59](https://user-images.githubusercontent.com/86655648/165808754-e3b2c5f7-0b1b-46cd-8fb9-00fe16c01aec.png)

**Comment by zk-tarts** [comment]
#1248 patched a similar request. Now when you `forge install` with a nonexistent tag the install should panic.  Just an FYI

**Comment by 0xYYY** [comment]
Thanks for bringing this up. Then I think the the above process I mentioned should happen befoer this check. To give users a chance to select the correct tag.

**Comment by 0xYYY** [comment]
Also, I'm suspecting that the `check_tag` function will always fail if the tag is a commit hash since `git ls-remote URL COMMIT_HASH` won't return anything.
https://github.com/foundry-rs/foundry/blob/dda018950cf9a27db3904b6a0c695783325d09b1/cli/src/cmd/forge/install.rs#L106-L118

**Comment by 0xYYY** [comment]
Given the above observation, I would like to suggest that we revamp the install process as follow:
1. Always clone/add the repo as submodule **without checking the tag**. Because I think the intention is clear that the user want to install the repo, even if they supply an invalid tag.
2. Give the user a chance to disambiguate the tag if it "looks like" a version tag. (We may do similar UX improvement for other kinds of tags in the future if wanted.)
>     1. do a regex match `r"^v?\d+(\.\d+)*$"` on `dep.tag`.
>     2. if there's a match, we get the list of tags in the repo with `git tag`.
>     3. show the list of candidate tags and let user select which one to use.
3. After that, if the tag is still invalid, i.e. `git checkout tag` fail, then we show a clear warning and suggest actions to take.

**Comment by sambacha** [comment]
> Given the above observation, I would like to suggest that we revamp the install process as follow:
> 
> 1. Always clone/add the repo as submodule **without checking the tag**. Because I think the intention is clear that the user want to install the repo, even if they supply an invalid tag.
> 2. Give the user a chance to disambiguate the tag if it "looks like" a version tag. (We may do similar UX improvement for other kinds of tags in the future if wanted.)
> 
> > ```
> > 1. do a regex match `r"^v?\d+(\.\d+)*$"` on `dep.tag`.
> > 2. if there's a match, we get the list of tags in the repo with `git tag`.
> > 3. show the list of candidate tags and let user select which one to use.
> > ```
> 
> 3. After that, if the tag is still invalid, i.e. `git checkout tag` fail, then we show a clear warning and suggest actions to take.

you should see this proposal: https://github.com/foundry-rs/foundry/issues/786
