### ISSUE TITLE
Regression in forge script, fuzz: could not fetch slot {idx} from {address}

### ISSUE THREAD

**Issue by Thegaram** [foundry-rs/foundry#6855]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

d46bcb3ddc768b35da8d1d29f85886476f974128

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

Regression in d46bcb3ddc768b35da8d1d29f85886476f974128 (#6219). When I install the previous commit (02292f2d2caa547968bd039c06dc53d98b72bf39) using `foundryup --commit` the issue goes away.

```
> forge script --legacy scripts/foundry/InitializeL2BridgeContracts.s.sol:InitializeL2BridgeContracts --rpc-url "$SCROLL_L2_DEPLOYMENT_RPC" 2>&1
[⠊] Compiling...
[⠘] Compiling 261 files with 0.8.16
[⠢] Solc 0.8.16 finished in 17.54s
2024-01-19T14:27:30.019085Z ERROR sharedbackend: Failed to send/recv `storage` err=failed to get storage for 0x5300000000000000000000000000000000000000 at 82: could not fetch slot {idx} from {address} address=0x5300000000000000000000000000000000000000 index=82
Error: 
fuzz: failed to inspect: Database error: failed to get storage for 0x5300000000000000000000000000000000000000 at 82: could not fetch slot {idx} from {address}
```

A similar command works with `ethereum/client-go:v1.11.6` but not with `scrolltech/l2geth:scroll-v5.1.7` (which is a fork of geth). It is possible that alloy providers rely on some RPC features not widely supported.

**Comment by Evalir** [comment]
Right, is it possible for you to provide a small repro where we can isolate this case? This way we can take a look at it

**Comment by DaniPopes** [comment]
May be fixed with https://github.com/foundry-rs/foundry/pull/6857, can you try again with `foundryup -b master` or in the next nightly?

**Comment by Thegaram** [comment]
Yes, tested with `master` (5ea2c5e), it works now, thanks!
