### ISSUE TITLE
`forge build` does not create build-info file if cache is enabled

### ISSUE THREAD

**Issue by RaoulSchaffranek** [foundry-rs/foundry#6859]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (2335dea 2024-01-19T00:18:45.919964404Z)

### What command(s) is the bug in?

forge build

### Operating System

Linux

### Describe the bug

`forge build` does not create the build-info files when caching is enabled.

Steps to reproduce:

~~~bash
forge init
echo "cache = true" >> foundry.toml
forge build --build-info
~~~

After that, I'd expect a new folder `out/build-info` that contains a JSON file with the solc standard JSON contents. However, no such folder and file is created.

**Comment by klkvr** [comment]
I can't really reproduce this right now, could you check if the issue still persists on latest nightly?

**Comment by RaoulSchaffranek** [comment]
Hey! Thanks for looking into it. Actually, I messed up the reproduction steps. To reproduce you have to **disable** the cache - not enable it. Thus the correct sequence to reproduce is the following:

~~~
forge init
echo "cache = false" >> foundry.toml
forge build --build-info
~~~

I can confirm that the bug is still present as of version `forge 0.2.0 (5c3b075 2024-03-08T00:17:08.055896400Z)`
