### ISSUE TITLE
debt(`anvil`): migrate to use `op-alloy` optimism types

### ISSUE THREAD

**Issue by Evalir** [foundry-rs/foundry#6860]
~~TBD yet if this should go on alloy—but we should refactor out the Optimism types as the network abstraction comes together. https://github.com/foundry-rs/foundry/pull/6808#discussion_r1459593115~~

Edit: Optimism types have since moved to https://github.com/alloy-rs/op-alloy

Updated the ticket to reflect that we should use those types in Foundry instead of the local implementation

**Comment by leovct** [comment]
Hi, I'd like to tackle this issue if it is still relevant!

**Comment by zerosnacks** [comment]
> Hi, I'd like to tackle this issue if it is still relevant!

Awesome thanks, yes this is still relevant: 

See:
- https://github.com/foundry-rs/foundry/blob/da77402c298066b084547c6027f1c9e3104fe871/crates/anvil/core/src/eth/transaction/optimism.rs#L4
- https://github.com/foundry-rs/foundry/blob/da77402c298066b084547c6027f1c9e3104fe871/crates/anvil/tests/it/optimism.rs

**Comment by leovct** [comment]
I've noticed that there are also references to `revm::primitives::OptimismFields`, is it in the scope of this PR also?

https://github.com/foundry-rs/foundry/blob/master/crates/anvil/src/eth/backend/mem/mod.rs#L92

**Comment by zerosnacks** [comment]
> I've noticed that there are also references to `revm::primitives::OptimismFields`, is it in the scope of this PR also?
> 
> https://github.com/foundry-rs/foundry/blob/master/crates/anvil/src/eth/backend/mem/mod.rs#L92

Possibly not but worth looking into, I think Reth still uses its own Optimism types

**Comment by zerosnacks** [comment]
Related: https://github.com/foundry-rs/foundry/issues/8943

Folding that ticket into here

**Comment by zerosnacks** [comment]
Related PR: https://github.com/foundry-rs/foundry/pull/8595

**Comment by leovct** [comment]
I think this issue can be closed, #9047 just got merged :)
