### ISSUE TITLE
Forge Coverage Exclude Scripts, Tests and Optional Library Exclusion

### ISSUE THREAD

**Issue by Metaxona** [foundry-rs/foundry#6874]
### Component

Forge

### Describe the feature you would like

forge 0.2.0 (7b45265 2023-11-21T00:22:00.899582254Z)

currently forge coverage includes `.s.sol` and at times even `.t.sol` in the coverage report which should not be happening since it is not a part of the contract that's being tested which is usually in `src/` or in `contracts/` or `src/contracts/` when using a hardhat-foundry hybrid project. This is causing a problem including and not limited to when looking at the debug summary generating more information than necessary.

an optional exclusion for libraries should also be included since some functions in a library wont be used and some branches, statements and lines won't ever be hit since the code is written to prevent hitting those conditions.

this would make it easier  to debug contracts and add more tests that should be added without any unnecessary data being added

**Comment by zerosnacks** [comment]
Marking as `resolved` by https://github.com/foundry-rs/foundry/pull/8321
