### ISSUE TITLE
Donating Funds to Foundry

### ISSUE THREAD

**Issue by Lfada** [foundry-rs/foundry#6879]
### Component

Other (please describe)

### Describe the feature you would like

Hi Foundry maintainers. I'm Lucas, a core contributor to the Drips project (https://www.drips.network/). I help recipients of donations through their learning and onboarding process.

[OpenZeppelin](https://www.openzeppelin.com/) has been using https://github.com/foundry-rs/foundry. It's one of their most critical dependencies! You are already getting funded by two projects (OpenZ and us, Drips).

OpenZeppelin core contributors appreciate your work and want to ensure you are all well-funded to keep doing it. For that reason, they have decided to donate some funds to your project through [Drips](https://www.drips.network/).

Who can I talk to about it?

cc: @gakonst 

### Additional context

N/a

**Comment by gakonst** [comment]
Thanks for the reminders mate. Just [set up](https://github.com/foundry-rs/foundry/commit/bf3b4b0e41299bbf6bb35e42c69c0587d745c2cd) and claimed the project https://www.drips.network/app/projects/github/foundry-rs/foundry?collectHint=true. Looking forward!!!
