### ISSUE TITLE
Implement Calltracer in anvil

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#6882]
### Component

Anvil

### Describe the feature you would like

currently the tracer type `callTracer` is ignored as highlighted by https://github.com/foundry-rs/foundry/issues/6873

this isn't handled properly:

https://github.com/foundry-rs/foundry/blob/c6790a02bb80b163469e2e3bb0b16ae95ad7334f/crates/anvil/src/eth/backend/mem/storage.rs#L419-L426

see for ref:

https://github.com/paradigmxyz/reth/blob/021d236f8c7a067cfbcc4ecd7ff77b6a72adc1cb/crates/rpc/rpc/src/debug.rs#L473-L473

**Comment by qiweiii** [comment]
hi @mattsse I put up a draft pr, a question is do we only need to add CallTracer or match all types of GethDebugTracerType like in https://github.com/paradigmxyz/reth/blob/021d236f8c7a067cfbcc4ecd7ff77b6a72adc1cb/crates/rpc/rpc/src/debug.rs#L473-L473

**Comment by prasincs** [comment]
@qiweiii sweet, I can help test this and any subsequent DebugTracer types, but I'm most interested in calltracer right now
