### ISSUE TITLE
Foundry and forge issue

### ISSUE THREAD

**Issue by Yinkathenoob** [foundry-rs/foundry#6889]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (f0199f0 2024-01-23T00:28:54.274732000Z)

### What command(s) is the bug in?

forge initialize

### Operating System

None

### Describe the bug

Yinkathenoob@Olayinkas-MacBook-Air ~ % forge init hello_foundry && cd hello_foundry
Error: 
The target directory is a part of or on its own an already initialized git repository,
and it requires clean working and staging areas, including no untracked files.

Check the current git repository's status with `git status`.
Then, you can track files with `git add ...` and then commit them with `git commit`,
ignore them in the `.gitignore` file, or run this command again with the `--no-commit` flag.

If none of the previous steps worked, please open an issue at:
https://github.com/foundry-rs/foundry/issues/new/choose

**Comment by Evalir** [comment]
You need to run `forge init` in a new, non-git directory. If you want to run it on a directory with git, you must use the `--no-commit` flag as specified.
