### ISSUE TITLE
Add config support to cast

### ISSUE THREAD

**Issue by ncitron** [foundry-rs/foundry#689]
### Component

Cast

### Describe the feature you would like

Right now the config items only are only consumed by forge. Many of the options in cast could benefit from the config feature such as ETH_RPC_URL and ETHERSCAN_API_KEY.

I was looking into how the implementation of this would work but have gotten a bit stuck. Forge relies on having a common `BuildArgs` struct that can be deserialized from the config file. Unfortunately, this is not the case for cast. One thought I had was creating a `CastCommon` struct that served the same purpose as `BuildArgs`, but this might make the help sections generated by clap confusing, since some of the fields of `CastCommon` may not make sense in the context of certain commands.

**Comment by SusheendharVijay** [comment]
Anyone working on this? really want this added to cast, so can give a shot 😄

**Comment by onbjerg** [comment]
Feel free, I don't think anyone is working on it @SusheendharVijay :smile:

**Comment by SusheendharVijay** [comment]
Hey @mattsse, some questions while working on this, 
- So if I understand correctly, we need structs like BuildArgs, BindArgs, CreateArgs etc, but for cast commands that consume config items? 
- For a new cast command that uses config values, 
    - we create an Args struct, impl Provider trait, impl From(Arg) for Config (merge here), and impl Cmd. 


Is this what you were talking about? I'm still wrapping my head around it. Thanks!

Sample `CallArgs` for `cast call` that uses config data (it won't compile, just sharing for basic structure). 

```rust
pub struct CallArgs {
    #[clap(help = "the address you want to query", parse(try_from_str = parse_name_or_address))]
    address: NameOrAddress,
    sig: String,
    args: Vec<String>,
    #[clap(long, short, help = "the block you want to query, can also be earliest/latest/pending", parse(try_from_str = parse_block_id))]
    block: Option<BlockId>,
    #[clap(flatten)]
    eth: EthereumOpts,
}

impl<'a> From<&'a CallArgs> for Config {
    fn from(args: &'a CallArgs) -> Self {
        let config = Config::figment_with_root(find_project_root_path().unwrap())
            .merge(args)
            .extract::<Config>()
            .unwrap();
        config
    }
}

impl Provider for CallArgs {
    fn metadata(&self) -> Metadata {
        Metadata::named("Call args provider")
    }

    fn data(&self) -> Result<Map<Profile, Dict>, figment::Error> {
        let value = Value::serialize(self)?;
        let error = InvalidType(self.to_actual(), "map".into());
        let mut dict = value.into_dict().ok_or(error)?;

        let rpc = self.eth.rpc_url().map_err(|err| err.to_string())?;
        dict.insert("eth_rpc_url".to_string(), Value::from(rpc.to_string()));

        dict.insert("chain".to_string(), Value::from(self.eth.chain.to_string()));
        Ok(Map::from([(Config::selected_profile(), dict)]))
    }
}

**Comment by SusheendharVijay** [comment]
Hey @mattsse, some questions while working on this, 
- So if I understand correctly, we need structs like BuildArgs, BindArgs, CreateArgs etc, but for cast commands that consume config items? 
- For a new cast command that uses config values, 
    - we create an Args struct, impl Provider trait, impl From(Arg) for Config (merge here), and impl Cmd. 


Is this what you were talking about? I'm still wrapping my head around it. Thanks!

Sample `CallArgs` for `cast call` that uses config data (it won't compile, just sharing for basic structure). 

```rust
pub struct CallArgs {
    #[clap(help = "the address you want to query", parse(try_from_str = parse_name_or_address))]
    address: NameOrAddress,
    sig: String,
    args: Vec<String>,
    #[clap(long, short, help = "the block you want to query, can also be earliest/latest/pending", parse(try_from_str = parse_block_id))]
    block: Option<BlockId>,
    #[clap(flatten)]
    eth: EthereumOpts,
}

impl<'a> From<&'a CallArgs> for Config {
    fn from(args: &'a CallArgs) -> Self {
        let config = Config::figment_with_root(find_project_root_path().unwrap())
            .merge(args)
            .extract::<Config>()
            .unwrap();
        config
    }
}

impl Provider for CallArgs {
    fn metadata(&self) -> Metadata {
        Metadata::named("Call args provider")
    }

    fn data(&self) -> Result<Map<Profile, Dict>, figment::Error> {
        let value = Value::serialize(self)?;
        let error = InvalidType(self.to_actual(), "map".into());
        let mut dict = value.into_dict().ok_or(error)?;

        let rpc = self.eth.rpc_url().map_err(|err| err.to_string())?;
        dict.insert("eth_rpc_url".to_string(), Value::from(rpc.to_string()));

        dict.insert("chain".to_string(), Value::from(self.eth.chain.to_string()));
        Ok(Map::from([(Config::selected_profile(), dict)]))
    }
}

**Comment by mattsse** [comment]
sorry, missed this one -.-

> So if I understand correctly, we need structs like BuildArgs, BindArgs, CreateArgs etc, but for cast commands that consume config items?

we can go the struct route where it makes sense, so extracting the named fields of some `Subcommands` to their own struct. 

> For a new cast command that uses config values,
we create an Args struct, impl Provider trait, impl From(Arg) for Config (merge here), and impl Cmd.

Yes this is how it's currently used in `forge`, given that cast's inputs are simpler, I think we don't necessarily need the `Cmd` impl

Your example looks correct.
Merging entries into the Data/Figment can either be done via `serde` or manually, or even both.

For example to serialize all fields into a `Data` you can use 

```rust
 let mut data = Serialized::defaults(self).data()?;
 // insert manually, see also config/src/lib.rs:805
```

So I think in this case you could derive Serialize and use `serde(skip)` to ignore fields that should not be included in the figment and then use the approach above when implementing Provider.

I think we could perhaps also extend the existing `impl_figment_convert` macros to accept varargs of `(key: field_name)`?
this would be the most elegant solution as it would remove lots of boilerplate code (impl Provider...) but more challenging, lmk if you need more pointers, have questions etc.

**Comment by SusheendharVijay** [comment]
Great, was worried I was working in the wrong direction, I'll get a bit more familiar with serde and make the changes. Totally agree about extending `impl_figment_convert` . Seems worth it. Once I get this working, I'll work on that 😄

**Comment by SusheendharVijay** [comment]
Okay since the setup is done in #1222, now will add support for all cast commands that need it. 

Tracking here: 

- [x] `cast call`
- [ ]  `cast send`
- [ ] `cast access-list`
- [ ] `cast block`
- [ ] `cast block-number`
- [ ] `cast chain`
- [ ] `cast chain-id`
- [ ] `cast client`
- [ ] `cast compute-address`
- [ ] `cast code`
- [ ] `cast tx`
- [ ] `cast publish`
- [ ] `cast estimate`
- [ ] `cast age`
- [ ] `cast balance`
- [ ] `cast basefee`
- [ ] `cast gas-price`
- [ ] `cast interface`
- [ ] `cast resolve-name`
- [ ] `cast storage`
- [ ] `cast proof`
- [ ] `cast receipt`
- [ ] `cast nonce`
- [ ] `cast etherscan-source`
- [ ] `cast find-block`
- [ ] `cast lookup-address`

lmk if I missed something

**Comment by SusheendharVijay** [comment]
@mattsse, most commands just use the rpc_url, so I'm thinking just a helper function should do. Like this: 

```rust
fn consume_config_rpc_url(rpc_url: Option<String>) -> Result<String, eyre::Error> {
    let final_rpc_url: String;
    if let Some(cli_rpc_url) = rpc_url {
        final_rpc_url = cli_rpc_url;
    } else {
        final_rpc_url = Config::load().eth_rpc_url.unwrap();
    }

    Ok(final_rpc_url)
}
```
cast block: 
```rust
 Subcommands::Block { rpc_url, block, full, field, to_json } => {
            let rpc_url = consume_config_rpc_url(rpc_url)?;
            let provider = Provider::try_from(rpc_url)?;
            println!("{}", Cast::new(provider).block(block, full, field, to_json).await?);
        }
```
Sound good to you?

**Comment by mattsse** [comment]
that seems reasonable!

**Comment by SusheendharVijay** [comment]
@onbjerg, we can close this issue now? 😄

**Comment by onbjerg** [comment]
Yep!
