### ISSUE TITLE
Unknown error when verify contract on Sepolia etherscan

### ISSUE THREAD

**Issue by Boyuan-Chen** [foundry-rs/foundry#6892]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (0f20cc6 2024-01-03T21:03:37.351917000Z)

### What command(s) is the bug in?

forge verify-contract

### Operating System

macOS (Apple Silicon)

### Describe the bug

Hi, I got `expected value at line 1 column 1` when I verified the smart contract on Sepolia etherscan. This is the command.
```
forge verify-contract [ADDRESS][CONTRACE_NAME] --watch --chain sepolia --constructor-args [ARG]
Error: 
expected value at line 1 column 1
```

**Comment by 0xpApaSmURf** [comment]
Also having this problem. This seems to be a recent problem as I was able to verify a few days ago. Possible the etherscan API has changed?

**Comment by jdubpark** [comment]
Pretty sure the internal Etherscan API for Sepolia has changed or is faulty — it had some maintenance yesterday and through this morning. I've tested on Etherscan Goerli, which works fine.

**Comment by 0xpApaSmURf** [comment]
Seems to work now, maybe the etherscan API is fixed?

**Comment by Evalir** [comment]
Could everybody else confirm if it works now? This does seem like an etherscan specific issue.

**Comment by jdubpark** [comment]
I can verify it's working, seems like Etherscan's Sepolia explorer had an internal issue.

**Comment by Evalir** [comment]
Awesome! Will close this issue—if someone is still running into issues, we'll reopen.

**Comment by softdev629** [comment]
Please open the issue! I am facing the same issue.

The smart contract is complied well in Remix but the etherscan says it can't find the matching bytecode results.

**Comment by Divinejicks** [comment]
> Please open the issue! I am facing the same issue.
> 
> The smart contract is complied well in Remix but the etherscan says it can't find the matching bytecode results.

I am facing this same issue.
