### ISSUE TITLE
forge test and compile takes a long time (1.2hrs) and still did not compile.

### ISSUE THREAD

**Issue by pavankv241** [foundry-rs/foundry#6895]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (96ab913 2023-09-28T13:12:39.623109640Z)

### What command(s) is the bug in?

forge test  

### Operating System

Linux

### Describe the bug

https://github.com/catalystdao/catalyst/tree/main/evm... 

The above code base i'm working but it takes 1.2 hrs to compile and still did not compile and suspended it . By enabling and disabling the `via-ir` in toml file also not working. Any alternate way for it ... 

**Commands**
`fore test` and `forge compile`

System configuration 

8gb ram 
AMD ryzen 3 processor.

**Comment by mattsse** [comment]
can you please try after upgrading?

**Comment by pavankv241** [comment]
> can you please try after upgrading?

I did that.. foundryup

**Comment by mattsse** [comment]
yeah this is waiting for solc to finish for while, unfortunately...
unclear what exactly the bottleneck in solc is here

```
[⠰] Compiling...
[⠆] Compiling 193 files with 0.8.22
```

**Comment by pavankv241** [comment]
> yeah this is waiting for solc to finish for while, unfortunately... unclear what exactly the bottleneck in solc is here
> 
> ```
> [⠰] Compiling...
> [⠆] Compiling 193 files with 0.8.22
> ```

I didn't understand please expand it

**Comment by pavankv241** [comment]
> yeah this is waiting for solc to finish for while, unfortunately... unclear what exactly the bottleneck in solc is here
> 
> ```
> [⠰] Compiling...
> [⠆] Compiling 193 files with 0.8.22
> ```
Is compilation succes on your side ..?

**Comment by mattsse** [comment]
it did

```
forge b 346.48s user 10.65s system 99% cpu 5:57.38 total
```

**Comment by pavankv241** [comment]
> it did
> 
> ```
> forge b 346.48s user 10.65s system 99% cpu 5:57.38 total
> ```

How I waited 1.2 hrs still not completely

**Comment by mattsse** [comment]
```
forge --version                                                                                                 
forge 0.2.0 (4a64380 2024-01-25T00:29:43.620621000Z)
```

**Comment by pavankv241** [comment]
I just updated to 

> ```
> forge --version                                                                                                 
> forge 0.2.0 (4a64380 2024-01-25T00:29:43.620621000Z)
> ```

I just updated to above version only . No use..

**Comment by pavankv241** [comment]
Can you please share screenshot here..

**Comment by pavankv241** [comment]
![17061837303895571914096030723255](https://github.com/foundry-rs/foundry/assets/69415766/e06c1e67-203d-4754-9c54-64fef169ecfb)
I have above version

**Comment by pavankv241** [comment]
> yeah this is waiting for solc to finish for while, unfortunately... unclear what exactly the bottleneck in solc is here
> 
> ```
> [⠰] Compiling...
> [⠆] Compiling 193 files with 0.8.22
> ```

I have extension name solc and solium in vs code is that causing time ...?

**Comment by mattsse** [comment]
<img width="288" alt="image" src="https://github.com/foundry-rs/foundry/assets/19890894/c6f10c5a-5ec5-4fe9-a08b-b69863237aa1">

I'm on mac apple silicon

**Comment by pavankv241** [comment]
> <img alt="image" width="288" src="https://private-user-images.githubusercontent.com/19890894/299651569-c6f10c5a-5ec5-4fe9-a08b-b69863237aa1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxODQ1NzEsIm5iZiI6MTcwNjE4NDI3MSwicGF0aCI6Ii8xOTg5MDg5NC8yOTk2NTE1NjktYzZmMTBjNWEtNWVjNS00ZmU5LWEwOGItYjY5ODYzMjM3YWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDEyMDQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyNThlYTc2N2UzZGMzMGYxZDhiODUzNmZlZjlmODM0ZmI2YmUxNGU1YWViMmRmNjU4N2NiYWQ0Mzg2NTA0YmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rAje0Dv7wtnvzvz-6pBBsr4cvSZAMCMgrZD0ZfeagNY">
> I'm on mac apple silicon
Yeah your luck .. is there alternative way for man please...? I did all the possible way

**Comment by mattsse** [comment]
hmm since this looks like a solc issue, perhaps try reinstalling the solc binary

**Comment by Evalir** [comment]
@pavankv241 please use `svm` to install solc and then could you report back if the issue persists? https://github.com/alloy-rs/svm-rs

**Comment by pavankv241** [comment]
I just installed svm . But .. could you please drop command to install sloc through svm

**Comment by Evalir** [comment]
please read the docs: https://github.com/alloy-rs/svm-rs

**Comment by pavankv241** [comment]
Install

> please read the docs: https://github.com/alloy-rs/svm-rs

Installed stilled no use ..

**Comment by pavankv241** [comment]
Hi there
I'm using mac air m1 intel chip i5 still same on mac also . 
 https://github.com/catalystdao/catalyst/tree/main/evm

**Comment by DaniPopes** [comment]
Hey @pavankv241

It might be that you're running out of RAM, and possibly going into swap which is significantly slower.

I could also build in ~6 minutes (x86_64 Ryzen 7950X) and it took about ~7-8GiB of RAM:
```
time forge b
[⠒] Compiling...
[⠘] Compiling 193 files with 0.8.22
Solc 0.8.22 finished in 353.98s
...
forge b --via-ir  351,02s user 1,93s system 99% cpu 5:54,68 total
```

**Comment by pavankv241** [comment]
> Hey @pavankv241
> 
> It might be that you're running out of RAM, and possibly going into swap which is significantly slower.
> 
> I could also build in ~6 minutes (x86_64 Ryzen 9 7950X) and it took about ~8GB of RAM at the end:
> 
> ```
> time forge b
> [⠒] Compiling...
> [⠘] Compiling 193 files with 0.8.22
> Solc 0.8.22 finished in 353.98s
> ...
> forge b --via-ir  351,02s user 1,93s system 99% cpu 5:54,68 total
> ```
> 
> Unfortunately there is not much we can do on our side. Disabling either via-ir or optimizer in the config results in "stack too deep" errors.

I thought same it's working on mac and took 1600 sec == 16 minutes  after installation of `svm`  . But kali linux with 8 gb ram and amd ryzen 3 took hrs and crashed finally.   Thanks for @mattsse  @Evalir @DaniPopes for your replies.
