### ISSUE TITLE
sampath

### ISSUE THREAD

**Issue by sampathkml** [foundry-rs/foundry#6899]
### Component

Foundryup

### Describe the feature you would like

forge init hello_foundry && cd hello_foundry

### Additional context

forge create src/Counter.sol:Counter \
  --rpc-url https://rpc.katla.taiko.xyz \
  --private-key YOUR_PRIVATE_KEY

**Comment by onbjerg** [comment]
Closing as this has no context, please open up a new issue that describes a feature or a bug 😄
