### ISSUE TITLE
Invariant Testing

### ISSUE THREAD

**Issue by gakonst** [foundry-rs/foundry#69]
@transmissions11 leaked some alpha by @MrChico from the dapphub chat

![telegram-cloud-photo-size-1-5096339203830163703-x](https://user-images.githubusercontent.com/17802178/135541195-c8db7564-9fef-47c9-8a96-3baa48f3b99b.jpg)
![telegram-cloud-photo-size-1-5096339203830163702-x](https://user-images.githubusercontent.com/17802178/135541201-d9364a68-501f-4b84-af54-1bd153e70a8d.jpg)

This algorithm should be easy to do inside our fuzzer logic.

>  you should run the invariant func once before you do any txs
> Because sometimes it doesn’t hold off the bat but then that changes after txs or if all the txs revert then the invariant will show as passed when it may have totally failed if ever called
> https://github.com/dapphub/dapptools/pull/745

**Comment by transmissions11** [comment]
personal wishlist:

1. would like a way to specify that a test can revert, just not fail an assert
2. would like to fuzz a set of invariants for time instead of fixed fuzz runs, or as long as i want
    a) ui showing failures as they occur and the progress of the campaign
    b) don't stop the campaign after a failure is found, keep fuzzing parts of it if possible
3. would like a way to control the list of accounts that the fuzzer calls things from
4. would like a way to control the contracts the fuzzer targets

**Comment by lucas-manuel** [comment]
Working on invariants right now so will come back with a wish list as well, is this currently being worked on btw?

**Comment by gakonst** [comment]
I think @brockelmore had hacked something?

**Comment by lucas-manuel** [comment]
One thing that would be really nice is a summary of how many times each function was called and the mean values like in the current fuzz run output. Also logging numbers of reversions for each function call if any.

**Comment by mattsse** [comment]
vote close @joshieDo

**Comment by gakonst** [comment]
> would like a way to control the list of accounts that the fuzzer calls things from

I think we don't have this yet? Probably for separate issue.

**Comment by joshieDo** [comment]
We do with `targetSenders` and `excludeSenders`
