### ISSUE TITLE
Allow us to pass any argument to the Solidity compiler

### ISSUE THREAD

**Issue by Vectorized** [foundry-rs/foundry#6917]
### Component

Forge

### Describe the feature you would like

So that we don't need to wait 2 days for nightly to activate latest solc features in future. 
Waiting 2 days is bad. Not blazing fast.

Some of us might want to bypass footgun protection.

**Comment by mattsse** [comment]
triggering release with 0.8.24 rn

this feature is out of scope

**Comment by Vectorized** [comment]
Thanks for blazing fast response!
