### ISSUE TITLE
forge build doesn't work for PCs with ram < 16 gb 

### ISSUE THREAD

**Issue by JADcooler** [foundry-rs/foundry#6924]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (deb3116 2024-01-27T00:16:24.795550479Z)

### What command(s) is the bug in?

forge test, forge build, forge script

### Operating System

Linux

### Describe the bug

SIGKILL for any PC that has lesser than 16gb ram

**Comment by onbjerg** [comment]
Just tested this on a virtual machine with less than 16 gigabytes of ram and had no issues. Please provide some code for which this does not work.

**Comment by JADcooler** [comment]
Have to apologise, the bug refers to projects that are moderately big in size
https://github.com/code-423n4/2024-01-salty

**Comment by JADcooler** [comment]
Whereas it builds normally for 16gb ram pcs,
My issue is that it shouldn't be executed in a way for SIgKill to happen 

There must be a way to compile it despite the amount of code or restricted Ram available.

Ty, might be more of a feature request but I think it's essential for people with shit PCs

**Comment by onbjerg** [comment]
I ran `/usr/bin/time -v forge build` in that project specifically and it never used more than 3 gigabytes of RAM:

```
[⠊] Compiling...
[⠢] Compiling 172 files with 0.8.22
[⠃] Solc 0.8.22 finished in 52.11s
Compiler run successful!
	Command being timed: "../../foundry-rs/foundry/target/release/forge build"
	User time (seconds): 51.45
	System time (seconds): 1.96
	Percent of CPU this job got: 100%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 0:53.26
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 3269624
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 922490
	Voluntary context switches: 7497
	Involuntary context switches: 326
	Swaps: 0
	File system inputs: 0
	File system outputs: 204952
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
```

This is on Arch Linux

**Comment by DaniPopes** [comment]
If you're using via-ir, see also https://github.com/foundry-rs/foundry/issues/6895#issuecomment-1911570027

In any case, I am getting similar results to @onbjerg's comment above.
I'm going to close this since I assume most of the memory consumption is in `solc`.
