### ISSUE TITLE
docs: Solidity compilers are not downloaded to `~/.svm` on macOS

### ISSUE THREAD

**Issue by macaujack** [foundry-rs/foundry#6925]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6fc7463 2024-01-05T00:17:41.668342000Z)

### Operating System

macOS (Apple Silicon)

### Describe the bug

The `README` says:
> Automatic Solidity compiler version detection & installation (under `~/.svm`)

However, on my machine (macOS Apple silicon, system version 14.1), the compilers are downloaded to `/Users/yourUsername/Library/Application Support/svm`. Seems like a mistake in `README`.

**Comment by DaniPopes** [comment]
The directory is resolved here: https://github.com/alloy-rs/svm-rs/blob/8423030a242915ec8629e6f1be1cd2f5a876ec70/crates/svm-rs/src/lib.rs#L51

which was updated in https://github.com/alloy-rs/svm-rs/pull/87

I think we just have to update the docs

cc @mattsse

**Comment by piavgh** [comment]
@DaniPopes : so if I don't have `.svm` folder in my $HOME, where does it install?

In my case, if I don't manually create the `.svm` folder, when I run `forge test`, it will try to install Solc again (which takes time)
After creating the `.svm` folder manually, it works properly again

**Comment by CadeMichael** [comment]
if everything is installed to '/Users/username/Library/Application Support/svm' if you want to uninstall a certain compiler version do you just have to remove it from that dir?
