### ISSUE TITLE
cast logs doesn't fail when the RPC URL is not set

### ISSUE THREAD

**Issue by CodeSandwich** [foundry-rs/foundry#6928]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (c5fd67b 2024-01-15T00:23:11.184513736Z)

### What command(s) is the bug in?

cast logs

### Operating System

Linux

### Describe the bug

`cast logs` only works when communicating with a client. When the user forgets to set `-r`, `--rpc-url` or `ETH_RPC_URL`, `cast logs` can't fetch the logs, but instead of printing an error, it prints an empty output, as if there were no logs.

The RPC URL should be a mandatory argument, and lack of it should cause an error message to be printed.

**Comment by bernard-wagner** [comment]
As with almost all `cast` commands it defaults to `http://localhost:8545` and if the host is an unavailable returns an error:

```
cast logs 
Error: 
error sending request for url (http://localhost:8545/): error trying to connect: tcp connect error: Connection refused (os error 61)

Context:
- Error #0: error trying to connect: tcp connect error: Connection refused (os error 61)
- Error #1: tcp connect error: Connection refused (os error 61)
- Error #2: Connection refused (os error 61)
```

If you are running an `anvil` instance in the background, the behavior as you described but is expected. The `anvil` node as none of the logs you are looking for.

**Comment by CodeSandwich** [comment]
Indeed, I was running anvil in the background, that's a great catch! I agree, it's a non-issue.
