### ISSUE TITLE
Error when running branch tests

### ISSUE THREAD

**Issue by Liguangyyu** [foundry-rs/foundry#6947]
### Component

Forge

### Have you ensured that all of these are up to date?

- [x] Foundry
- [ ] Foundryup

### What command(s) is the bug in?

--fork-url

### Operating System

Windows

### Describe the bug

When I use mubai's rpc, this problem occurs
![Uploading BUGLOG.png…]()

**Comment by Liguangyyu** [comment]
It ran... But it lasted nearly an afternoon before it was all done
![true](https://github.com/foundry-rs/foundry/assets/126438727/52d3af32-add9-4295-b7a3-9e5a042f724a)

**Comment by Evalir** [comment]
hey! can't really see the first image you posted. This seems like an RPC issue though no? If it took that long to run under a fork test it's probably because you're getting rate limited. I'd try another RPC and see if that solves the issue.

**Comment by Liguangyyu** [comment]
It recovered a little bit when I switched to another ETH node, I'm not sure if it's because of too many fuzzy scenarios being run or if it's a problem with RPCs

**Comment by DaniPopes** [comment]
Closing as RPC issue.
