### ISSUE TITLE
Delete doesn't work great with chisel mappings.

### ISSUE THREAD

**Issue by aravindb26** [foundry-rs/foundry#6948]
### Component

Chisel

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (5b7e4cb 2023-12-02T00:21:00.501921838Z)

### What command(s) is the bug in?

chisel

### Operating System

Windows

### Describe the bug

Hello team `Delete doesn't work great with chisel mappings.`

Here is the proof:
```
chisel
Welcome to Chisel! Type `!help` to show available commands.
➜ mapping(address => address) public token2token;
➜ token2token[address(1)] = address(2)
Type: address
└ Data: 0x0000000000000000000000000000000000000002
➜ token2token[address(1)]
Type: address
└ Data: 0x0000000000000000000000000000000000000002
➜ delete token2token[address(1)]
➜ token2token[address(1)]
Type: address
└ Data: 0x0000000000000000000000000000000000000002
```
<img width="493" alt="chisel_delete" src="https://github.com/foundry-rs/foundry/assets/89305482/6d201d77-334f-4dc2-ac32-9ce4fa87684b">

**Comment by DaniPopes** [comment]
Currently expressions without a semicolon (`;`) at the end don't get saved in the session. If you add `;` in the `delete` line it should work.

**Comment by aravindb26** [comment]
> Currently expressions without a semicolon (`;`) at the end don't get saved in the session. If you add `;` in the `delete` line it should work.

Yeah it works if we do `delete token2token[address(1)];`
