### ISSUE TITLE
Foundry Linux binaries not updated on `nightly` release tag.

### ISSUE THREAD

**Issue by jxom** [foundry-rs/foundry#6964]
### Component

Foundryup

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### Operating System

None

### Describe the bug

Looks like the Linux binaries aren't being updated – does it usually take this long to propagate?

https://github.com/foundry-rs/foundry/releases/tag/nightly

**Comment by jxom** [comment]
Looks like the workflow is failing: https://github.com/foundry-rs/foundry/actions/runs/7717279638/job/21036030883

**Comment by DaniPopes** [comment]
Linux runners were OOM-ing due to a recent change
Fixed by https://github.com/foundry-rs/foundry/pull/6963
