### ISSUE TITLE
$ETHERSCAN_API_KEY present in .env seems to take priority over any --etherscan-api-key flags

### ISSUE THREAD

**Issue by g-01234** [foundry-rs/foundry#6965]
### Component

Cast

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (56e9583 2024-01-30T12:30:23.386976000Z)

### What command(s) is the bug in?

cast storage <addr> --etherscan-api-key <non-mainnet-key>

### Operating System

macOS (Apple Silicon)

### Describe the bug

Just ran `foundryup` and started getting `Invalid API key` when running cast queries for non-mainnet chains (mainnet works fine). 

I was running the commands from a directory with a `.env` file that contains various explorer API keys, named e.g. `ETHERSCAN_API_KEY`, `BSCSCAN_API_KEY`, etc. 

The non-mainnet commands work when run from a different directory (without a `.env`), so it seems the `.env:ETHERSCAN_API_KEY` is getting picked up and used over anything else, even when I run e.g. `cast storage 0xf7de7e8a6bd59ed41a4b5fe50278b3b7f31384df --etherscan-api-key $BSCSCAN_API_KEY --rpc-url $BSC_RPC_URL`.

I believe it may be a result of this commit:
https://github.com/foundry-rs/foundry/commit/2249e077b39dd27fe09f5192223383d4146a6852

**Comment by DaniPopes** [comment]
cc @mattsse https://github.com/foundry-rs/foundry/pull/6918

**Comment by PaulRBerg** [comment]
Just bumped into this issue while trying to verify a contract on Arbiscan.

I have an `ETHERSCAN_API_KEY` environment variable set globally on my machine, which seems to take priority over the flag passed to `verify-contract`.

It would make more sense to prioritize command-line options over environment variables.

**Comment by g-01234** [comment]
fixed, thanks king
