### ISSUE TITLE
No coverage report inside `do...while` loops

### ISSUE THREAD

**Issue by beeb** [foundry-rs/foundry#6968]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (caef136 2024-01-29T00:20:25.410303708Z)

### What command(s) is the bug in?

forge coverage --report lcov

### Operating System

Linux

### Describe the bug

The coverage report generated by foundry does not include any coverage information inside `do...while` loops.

Repro: https://github.com/beeb/repro_foundry_coverage

Report below was generated with lcov's `genhtml` using the report generated by forge.

![image](https://github.com/foundry-rs/foundry/assets/703631/39421321-1a70-4191-a34f-4746f8eff08a)

**Comment by kayagokalp** [comment]
I did a little bit of digging for this one, my first guess was an error with the visitor implementation but it was not the case, it looks like `statement`s are omitted while generating `lcov` reports. I am not sure about the reason but there is comment that says statement's are not compatible with `lcov`. I am not very familiar with lcov so not sure about the next statement but, I feel like adding `DA` to lcov report for statements should work. https://github.com/foundry-rs/foundry/blob/e897bd6874312d2c2d9acc7d24081ef721845b29/crates/forge/src/coverage.rs#L119-L120

By changing it to emit `DA` values I obtained following coverage report for the project reported:


<img width="1723" alt="image" src="https://github.com/foundry-rs/foundry/assets/20915464/9d7d2a3c-684e-4997-baba-af6c2073b56c">


I have the change, produced this coverage report here on my fork:
https://github.com/kayagokalp/foundry/tree/kayagokalp/add-statements-to-coverage

I can open a PR but if we have some context on why the comment said statements are not compatible, that would be great. I don't want to introduce a regression.

**Comment by beeb** [comment]
Thanks a lot for looking into this! The fixed example you showed looks great, hopefully someone can confirm it wouldn't cause problems elsewhere.

**Comment by beeb** [comment]
@onbjerg since git blame points at you maybe you can pitch in? Thanks ^^

**Comment by onbjerg** [comment]
we can add DA to lcov but note that expressions and statements are two different constructs

please open a PR - coverage does not cover everything because we had to reconstruct the AST data structure ourselves since it is undocumented in solidity, and even worse, changes over different versions.

**Comment by beeb** [comment]
The bug was re-introduced by https://github.com/foundry-rs/foundry/commit/5b8416363c7c1aab6d3cda0da6e7c65594ad8a12 (regression). @onbjerg or @grandizzy can you re-open the issue?

**Comment by beeb** [comment]
Additional comment: now that foundry puts `BRDA` branch coverage info (even inside do..while), the final LCOV file is not compliant and `genhtml` cannot parse it:

```
$ genhtml -o .coverage lcov.info --rc branch_coverage=1
[...]
genhtml: ERROR: line 158 of src/File.sol has branchcov but no linecov data
```

**Comment by grandizzy** [comment]
I opened #10422 to fix this, will make sure unit test is included to avoid future regressions
