### ISSUE TITLE
feat: `stateOverride` usage with `eth_estimateGas`

### ISSUE THREAD

**Issue by TateB** [foundry-rs/foundry#6980]
### Component

Anvil

### Describe the feature you would like

geth recently added the optional `stateOverride` parameter to `eth_estimateGas`, with the same functionality as `eth_call` (see https://github.com/ethereum/go-ethereum/issues/27800, https://github.com/ethereum/go-ethereum/pull/27845). would be super useful to have this added to anvil!

example usage: estimating the total gas of an `approve` and `transfer` transaction, before the `approve` transaction has been done

**Comment by mattsse** [comment]
## TODO

add StateOverrides to estimate endpoint, then apply to state:

https://github.com/foundry-rs/foundry/blob/00cec1d2445ad9b8917a377cb6f9b755728eb9da/crates/anvil/src/eth/backend/mem/mod.rs#L1035-L1035

here 

https://github.com/foundry-rs/foundry/blob/00cec1d2445ad9b8917a377cb6f9b755728eb9da/crates/anvil/src/eth/api.rs#L2162-L2163

**Comment by loocapro** [comment]
Can I take this?
