### ISSUE TITLE
`fs_permissions` does not work with symlinked paths

### ISSUE THREAD

**Issue by oveddan** [foundry-rs/foundry#6981]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (2b2a499 2024-01-31T17:46:44.163875000Z)

### What command(s) is the bug in?

any forge scripting or test commands

### Operating System

macOS (Apple Silicon)

### Describe the bug

A fully reproduceable example of this issue [can be seen in this github repo](https://github.com/oveddan/foundry-symlink-issue-example)

I have a monorepo setup, where I want to be able to import a package within the same monorepo, and read some files from it in forge scripts.   For a basic example of this kind of setup:

My folder structure is:

```
packages/imported/files/config.json
packages/contracts/test/ImportTest.t.sol
```

 The imported project is installed via npm packages, and as a result is symlinked within the `node_modules` folder of the `contracts` project:

```
packages/contracts/node_modules/@repo/imported/files/config.json -> packages/imported/files/config.json
```

To see if this file can be loaded I created a simple test in:
`packages/contracts/test/ImportTest.t.sol`:

```
import "forge-std/Test.sol";

contract ImportTest is Test {
    function test_can_import_file_from_node_modules() public {
        string memory jsonString = vm.readFile(
            "node_modules/@repo/imported/files/config.json"
        );
    }
}
```

my `packages/contracts/foundry.toml` is configured to allow these paths:
```toml
fs_permissions = [
  { access = "read", path = "./node_modules/@repo/imported/files/config.json" },
  { access = "read", path = "./node_modules/@repo/imported/files" },
  { access = "read", path = "../imported/files" },
  { access = "read", path = "../imported/files/config.json" },
]
```

Yet when I run this test I get an error "[FAIL. Reason: the path node_modules/@repo/imported/files/config.json is not allowed to be accessed for read operations]"

If I manually copy the folder into the same exact location, with the commands:
`cd packages/contracts && rm -r node_modules/@repo/imported && cp -r ../imported node_modules/@repo/imported`

Then I can run the tests successfully.

I believe the cause is that the path is symlinked and forge may be treating the path as one outside the project folder.

This **is not** an issue with code imported from those symlinked folders

**Comment by DaniPopes** [comment]
https://github.com/foundry-rs/foundry/pull/7022
