### ISSUE TITLE
Improve `forge verify-contract` return message with the correct network and block explorer display

### ISSUE THREAD

**Issue by 0xlxy** [foundry-rs/foundry#6988]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (f460583 2023-12-08T11:40:00.032248000Z)

### What command(s) is the bug in?

forge verify-contract

### Operating System

macOS (Apple Silicon)

### Describe the bug

Following the instructions on the [Blast Doc](https://testnet.blastscan.io/documentation/recipes/foundry-verification), I used the command:
```
forge verify-contract [contract-address] [src/path/ContractPath.sol:ContractName] 
--verifier-url 'https://api.routescan.io/v2/network/testnet/evm/168587773/etherscan' 
--etherscan-api-key "verifyContract" 
--compiler-version [solc compiler version]
```
to verify the smart contract I deployed on Blast Sepolia. 
The verification succeeded, but in the return message I got:
```
Start verifying contract `[contract-address]` deployed on mainnet

Submitting verification for [src/path/ContractPath.sol:ContractName] [contract-address].
Submitted contract for verification:
        Response: `OK`
        GUID: `da00bebb-6b0b-5004-9470-e08d6bac45ef`
        URL:
        https://etherscan.io/address/[contract-address]
```

The chain id I used for verification here is `168587773` (Blast Sepolia), and would suggest improving the message:
- instead of "mainnet", it should be "Blast Sepolia".
- instead of "https://etherscan.io/address/[contract-address]" in URL, it should be "https://testnet.blastscan.io/address/[contract-address]".

**Comment by mattsse** [comment]
can you try this again with `--chain blast-sepolia` as argument?

**Comment by 0xlxy** [comment]
It works after updating to the lastest forge (`forge 0.2.0 (ceb739a 2024-02-01T00:36:17.123881000Z)`) 👍
The smart contract got verified with `forge create` and no further `forge verify-contract` needed.
