### ISSUE TITLE
add a cheat code for test blobhash

### ISSUE THREAD

**Issue by flyq** [foundry-rs/foundry#6996]
### Component

Forge

### Describe the feature you would like

Now, the `blobhash` is supported by the solidity 0.8.24, and the forge also support it when set `evm_version="cancun"` in foundry.toml. but missing way to be able to test `blobhash`.

**Comment by mattsse** [comment]
we can add cheatcodes to set and get the blobhash?

**Comment by flyq** [comment]
great work

**Comment by finlayedwards34-del** [comment]
How do you do it

**Comment by deatonl159-prog** [comment]
How to hack

**Comment by LANDOn45-glitch** [comment]
How do I get these

**Comment by hr2qw2hmx6-dotcom** [comment]
How to hack

**Comment by obaydatareq-rgb** [comment]
how to hack

**Comment by 455773-gif** [comment]
how to get all the blooks in blooket and I don't know I  try YouTube but it's not working

**Comment by 1008450-cmyk** [comment]
how to get all blooks on blooket

**Comment by nikkiesixxx6-source** [comment]
it worked jk

**Comment by minedcam-gif** [comment]
what am i suppossed to do?

**Comment by dariyaleap889-cyber** [comment]
git@gitlab.com:zacharylee2/blooket-cheats.git
