### ISSUE TITLE
parser error when using `cast` and struct of arrays containing bytes params

### ISSUE THREAD

**Issue by fedealconada** [foundry-rs/foundry#6998]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (84d9842 2024-02-02T00:19:34.098872000Z)

### What command(s) is the bug in?

`cast send`

### Operating System

macOS (Apple Silicon)

### Describe the bug

hi!

i'm trying to execute this function, which receives an array of a struct which contains several params including some `bytes` ones.
 
`cast send --private-key $PRIVATE_KEY $CONTRACT "handleOps((address,uint256,bytes,bytes,uint256,uint256,uint256,uint256,uint256,bytes,bytes)[],address)" "[(0x0000000000000000000000000000000000000000,0,'0x1','0x1',0,0,0,0,0,'0x1','0x1')]" $PUBLIC_KEY --rpc-url $RPC_URL`

this is what i'm receiving:

<img width="604" alt="image" src="https://github.com/foundry-rs/foundry/assets/4473536/1e25f09c-ad5b-4344-8ef9-4a709efdc7f7">

i noticed that if i try removing all the `bytes` params and sending it like this:
"handleOps((address,uint256,uint256,uint256,uint256,uint256,uint256)[],address)" "[(0x0000000000000000000000000000000000000000,0,0,0,0,0,0)]" 

it also fails but with a different error which makes me think that the issue is on the `bytes` params.

<img width="448" alt="image" src="https://github.com/foundry-rs/foundry/assets/4473536/dd898866-94ea-4c9a-9933-baebbb7015f5">

either i'm not passing them correctly or there's something wrong.

if i try removing all of the params which are not `bytes`, sending it like this: 

"handleOps((bytes,bytes,bytes,bytes)[],address)" "[('0x1','0x1','0x1','0x1')]"

i'm again receiving the 1st error:

<img width="298" alt="image" src="https://github.com/foundry-rs/foundry/assets/4473536/fd22526a-0f6d-41d7-968a-aa206fede991">

thanks!

**Comment by klkvr** [comment]
bytes can't have an odd length. 

please check if `"[(0x0000000000000000000000000000000000000000,0,0x10,0x10,0,0,0,0,0,0x10,0x10)]"` will work

**Comment by DaniPopes** [comment]
The error message is rough, but the message is "Odd number of digits" so 0x1 should be 0x01

As for the RPC error that's just a contract revert on your end.
