### ISSUE TITLE
Add cheatcode to read forge config as json object 

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#7003]
### Component

Forge

### Describe the feature you would like

we want to allow arbitrary sections in foundry.toml, so it might be beneficial to get access to foundry.toml via a cheatcode without having to invoke ffi to first convert toml to json

## TODO
* add new cheatcode `vm.foundryConfig()` that reads loads the config, we might also want to capture any additional entries in a new field of the Config struct `BTreeMap<String, serde_json::Value`

**Comment by tynes** [comment]
This is an interesting way to configure application specific things in scripts. If there was a particular section that was a catch all for extra key value pairs that could have subsections based on foundry profile, i could see this being very useful

**Comment by mds1** [comment]
Related to https://github.com/foundry-rs/foundry/issues/5866 which proposes a format for arbitrary sections

**Comment by mattsse** [comment]
ah right, this is basically a dup of #5866
