### ISSUE TITLE
JUnit XML Test Reports

### ISSUE THREAD

**Issue by clabby** [foundry-rs/foundry#7004]
### Component

Forge

### Describe the feature you would like

JUnit XML test reports are widely used in CI tools to provide more advanced test reporting, such as [CircleCI's Test Insights](https://circleci.com/docs/insights-tests) feature. Having `forge test` support this standard test result format would enable projects to track individual test failure rates, average individual test speed, etc., with existing services that support the standard.

**Comment by zerosnacks** [comment]
Related: https://github.com/foundry-rs/foundry/issues/7813

**Comment by smartcontracts** [comment]
Bump here, this would be highly valuable for being able to generate test timings so we can properly split tests up in CI 🙏

**Comment by grandizzy** [comment]
> Bump here, this would be highly valuable for being able to generate test timings so we can properly split tests up in CI 🙏

`forge test --junit` is now available for such, pls give it a try

**Comment by clabby** [comment]
@grandizzy Thank you!!
