### ISSUE TITLE
bug: function selector collisions cause calldata to get swallowed in the trace output

### ISSUE THREAD

**Issue by thedavidmeister** [foundry-rs/foundry#7011]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (293fad7 2024-01-14T00:19:24.272194000Z)

### What command(s) is the bug in?

forge test -vvvvv

### Operating System

macOS (Apple Silicon)

### Describe the bug

If there is some selector in the registry that collides with the selector of some function being called, the traces seem to use the upstream selector to decide how much of the calldata to use, which can be 0 bytes of it

for example, the selector `0x00000003` matches `rz_16jun22_88961909()` in the openchain.xyz database

as `rz_16jun22_88961909()` has no arguments, if you try to trace any calldata sent to selector `0x00000003` it simply doesn't appear in the foundry logs even with `-vvvvv`

here's an example in ci https://github.com/h20liquidity/xblock/actions/runs/7773311580/job/21196831982

<img width="1132" alt="Screenshot 2024-02-04 at 17 42 17" src="https://github.com/foundry-rs/foundry/assets/629710/a9dfd804-46e3-4008-b7cf-1b07de68d423">

here is a screenshot, you can see that selector `0x00000000` traces calldata, `0x00000002` traces calldata, but `0x00000003` collides with the selector without arguments, and so does NOT trace the calldata

admittedly i am doing something a bit "weird" by using sequential selectors rather than hash based selectors, but this bug probably generalises to any time there's a collision and the upstream signature is used instead of the local one

**Comment by thedavidmeister** [comment]
as a workaround i found that `--offline` suppresses the upstream selectors, but also is a big hammer as it causes _everything_ to work offline

a flag to suppress found selectors without forcing forge offline could be a simple mvp solution to this situation

**Comment by zerosnacks** [comment]
Hi @thedavidmeister, would it be possible for you to create a minimal reproduction case of this? The original CI logs are not available anymore

**Comment by grandizzy** [comment]
@thedavidmeister please reopen with a minimal repro if this still occur. thank you!

**Comment by thedavidmeister** [comment]
@grandizzy the selector `0x00000003` still collides yes

**Comment by thedavidmeister** [comment]
@grandizzy but i don't have the ability to reopen the issue

**Comment by grandizzy** [comment]
@thedavidmeister can you pls provide a repro for this issue? Thanks

**Comment by thedavidmeister** [comment]
@grandizzy in what format? the repro is that you run traces on the cli that use the selector i posted

**Comment by grandizzy** [comment]
Would need the commands / sequence you use to reproduce the issue (also this is expired https://github.com/h20liquidity/xblock/actions/runs/7773311580/job/21196831982 so not much to be used from)

**Comment by grandizzy** [comment]
what if you `forge selectors cache` from your project, is the same?

**Comment by grandizzy** [comment]
All looking good here

```bash
Ran 1 test for test/Issue5521.t.sol:DuplicateSelectorTest
[PASS] test_duped_selectors() (gas: 71768)
Traces:
  [71768] DuplicateSelectorTest::test_duped_selectors()
    ├─ [38691] → new ContractWithSelector@0x5615dEB798BB3E4dFa0139dFa1b3D433Cc23b72f
    │   └─ ← [Return] 193 bytes of code
    ├─ [300] ContractWithSelector::rz_16jun22_88961909(100, 200) [staticcall]
    │   └─ ← [Stop] 
    └─ ← [Stop] 
```
