### ISSUE TITLE
Cant run scripts after foundryup

### ISSUE THREAD

**Issue by chasebrownn** [foundry-rs/foundry#7015]
I run scripts quite often. Was trying to run a script that was previously working just fine. And got this error:
```
solc exited with signal: 6 (SIGABRT) (core dumped)
corrupted size vs. prev_size
```

My solution to this was using `foundryup` to make sure my tools were of the latest version and if anything was corrupted it would be replaced upon a new install of the tools. This did fix that error, but now no mater what script I run I get this error:
```
Failed to deploy script:
Execution reverted: EvmError: Revert (gas: 497176)
```

Everything seems right, env variables are the same. Is there a chance the new forge version has an issue running scripts?

**Comment by Evalir** [comment]
Can you share a repro so we can debug this? hard to look into it otherwise

**Comment by chasebrownn** [comment]
Unfortunately the repo is private. I ended up downgrading to a foundry commit from 6 months ago and that did the trick.

**Comment by onbjerg** [comment]
In that case we'll have to close the issue. We run scripts as part of our testing suite, but without some way to reproduce the issue we won't be able to make much progress here. If you do end up finding a reproducible example, please do open up an issue again (or re-open this one), we'd love to fix any bugs present 😊  Sorry!

**Comment by fedealconada** [comment]
I'm experiencing the same error but coulnd't fix it by downgrading (I'm actually getting an error when downgrading).
You can try running [this](https://github.com/KintoXYZ/kinto-core/blob/main/script/migrations/28-deploy_faucet_v4.sol) script to reproduce @onbjerg

**Comment by luckybool1020** [comment]
> Can you share a repro so we can debug this? hard to look into it otherwise

I get the same error when I run scripts,but its work well on cast. what is the problem,so confused.
![image](https://github.com/foundry-rs/foundry/assets/16422202/94f30593-71e4-43e0-9bec-6a8c8d9ed004)
