### ISSUE TITLE
Debugger panics due to out-of-bounds access during debugging session

### ISSUE THREAD

**Issue by jmcph4** [foundry-rs/foundry#7029]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (2cf84d9 2024-02-07T00:16:06.769732275Z)

### What command(s) is the bug in?

forge test -vvv --debug test_createWithdrawRequest_HappyPath

### Operating System

Linux

### Describe the bug

# Actual Behaviour

Whilst trying to debug a failing test case, the debugger panics (seemingly arbitrarily) throughout scrolling in the TUI pane (i.e., with the Vim-style `j` and `k`, respectively).

```
$ forge test -vvv --debug test_createWithdrawRequest_HappyPath
[⠑] Compiling...
No files changed, compilation skipped
The application panicked (crashed).
Message:  range start index 101 out of range for slice of length 100
Location: crates/debugger/src/tui/draw.rs:281

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 8 frames hidden ⋮                               
   9: core::slice::index::slice_start_index_len_fail::h89a39d0ac724bb0b
      at <unknown source file>:<unknown line>
  10: foundry_debugger::tui::draw::<impl foundry_debugger::tui::context::DebuggerContext>::draw_src::h321ce7e5a8acef34
      at <unknown source file>:<unknown line>
  11: foundry_debugger::tui::draw::<impl foundry_debugger::tui::context::DebuggerContext>::draw::h8f9a8fa7d8b381ff
      at <unknown source file>:<unknown line>
  12: foundry_debugger::tui::TerminalGuard<B>::with::hf9dcfe40c68341b4
      at <unknown source file>:<unknown line>
  13: foundry_debugger::tui::Debugger::try_run::h7bd7166c58965fcc
      at <unknown source file>:<unknown line>
  14: forge::cmd::test::TestArgs::execute_tests::{{closure}}::hb8f005d4a1299f14
      at <unknown source file>:<unknown line>
  15: forge::cmd::test::TestArgs::run::{{closure}}::h2d35bdc882e608c0
      at <unknown source file>:<unknown line>
  16: foundry_cli::utils::block_on::had29e279981a55fe
      at <unknown source file>:<unknown line>
  17: forge::main::hbf519a0f7d8dc99f
      at <unknown source file>:<unknown line>
  18: std::sys_common::backtrace::__rust_begin_short_backtrace::h9f8502f1caad2d6b
      at <unknown source file>:<unknown line>
  19: std::rt::lang_start::hf133f0be0057f709
      at <unknown source file>:<unknown line>
  20: __libc_start_main<unknown>
      at <unknown source file>:<unknown line>
  21: _start<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Aborted (core dumped)
```

The panic arises directly from:

https://github.com/foundry-rs/foundry/blob/2cf84d9f3ba7b6f4a9296299e7036ecc24cfa1da/crates/debugger/src/tui/draw.rs#L281

Scrolling speed nor key combination seem to impact the occurrence of the bug.

# Expected Behaviour

For the debugger to not panic.

**Comment by onbjerg** [comment]
any chance you could share the repo this happens in?

**Comment by jmcph4** [comment]
> any chance you could share the repo this happens in?

Unfortunately not, although I could attempt a local reproduction separately. I've had this happen before though so I sense it shouldn't be too hard to trigger again.

**Comment by Evalir** [comment]
Please, we'd love a repro even if it's a local one different from your repo, that way we could look into it 🙏

**Comment by jmcph4** [comment]
> Please, we'd love a repro even if it's a local one different from your repo, that way we could look into it 🙏

Yeah obviously a reproduction is important, I'll cook something up once I have a bit more time to commit.

**Comment by emo-eth** [comment]
I believe I found the issue here. Reproducing is *very* tricky because the out-of-bounds access depends on the _size of the debugger window_ (lol)

There's at least one bug in how the debugger calculates which part of the source code to highlight. [Here's the problematic line I found.](https://github.com/foundry-rs/foundry/blob/e5edb0840b1595b4b13392f172b50ce932b7e4f3/crates/debugger/src/tui/draw.rs#L260)

Sometimes, `above` can be zero; thus `start_line == before.len()`, which causes [the out-of-range error on line 281](https://github.com/foundry-rs/foundry/blob/e5edb0840b1595b4b13392f172b50ce932b7e4f3/crates/debugger/src/tui/draw.rs#L281), like the error message says.

**Comment by jmcph4** [comment]
> I believe I found the issue here. Reproducing is _very_ tricky because the out-of-bounds access depends on the _size of the debugger window_ (lol)

I had a sneaking suspicion this might be involved! Pretty wild you've already nailed it though.

For context, I'm running Kitty with:

```
Resize this window

Press one of the following keys:
  Wider
  Narrower
  Taller
  Shorter
  Reset

Press Esc to quit resize mode
Hold down Ctrl to double step size

Sizes
Original: 43 rows 147 cols
Current:  43 rows 147 cols
```
