### ISSUE TITLE
Invalid Bytecode generated

### ISSUE THREAD

**Issue by mustermeiszer** [foundry-rs/foundry#7032]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (2cf84d9 2024-02-07T00:15:49.638525000Z)

### What command(s) is the bug in?

forge build

### Operating System

macOS (Apple Silicon)

### Describe the bug

The contracts bytecode contains an invalid hex sequence `__$a334d32fe50f4079904586988e51d312a5$__`, making it impossible to decode the bytecode back into bytes. Compilation works fine. 

* Contract: https://github.com/centrifuge/liquidity-pools/blob/main/src/gateway/Gateway.sol
* Foundry.toml: https://github.com/centrifuge/liquidity-pools/blob/main/foundry.toml
* Json output: [Gateway.json](https://github.com/foundry-rs/foundry/files/14194058/Gateway.json)

Would appreciate help a lot, whether I can simply remove that sequence, need to change the compiler settings, or just decode the bytecode differently.

**Comment by mattsse** [comment]
this is just a placeholder for the MessagesLib library


```json
      "linkReferences": {
            "src/libraries/MessagesLib.sol": {
                "MessagesLib": [{
                        "start": 3375,
                        "length": 20
                    },
                    {
                        "start": 4863,
                        "length": 20
                    }
                ]
            }
        }
```

**Comment by mustermeiszer** [comment]
Thanks for the fast reply!! 

How would I decode that bytecode then?

**Comment by mattsse** [comment]
`MessagesLib.formatDomain` is not internal so it doesn't get inlined

**Comment by mustermeiszer** [comment]
* Can I inline it somehow? 
* How would I decode that bytecode without inlining it? 

I am trying to deploy the contract via the https://github.com/rust-ethereum/ethabi/blob/b1710adc18f5b771d2d2519c87248b1ba9430778/ethabi/src/contract.rs#L31-L44 crate. But I need to generate the init-code correctly for that, and hence need the full bytecode.

**Comment by zerosnacks** [comment]
> * Can I inline it somehow?

If you control the source code, the easiest would be to change the visibility of these functions from `public` to `internal`.

https://github.com/centrifuge/liquidity-pools/blob/e2c3ac92d1cea991e7e0d5f57be8658a46cbf1fe/src/libraries/MessagesLib.sol#L957-L963

See: https://docs.soliditylang.org/en/latest/contracts.html#libraries

**Comment by mustermeiszer** [comment]
Thanks, will give it a try and see whether we can do that!

**Comment by mustermeiszer** [comment]
Thanks! That is fine for the solidity team and fixes my issue!
