### ISSUE TITLE
Forge test debugger does not show sourcemaps for inherited contracts

### ISSUE THREAD

**Issue by emo-eth** [foundry-rs/foundry#7043]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (2cf84d9 2024-02-07T00:15:49.638525000Z)

### What command(s) is the bug in?

forge test --debug

### Operating System

None

### Describe the bug

Sourcemaps for inherited contracts are not found/shown by the Forge test debugger.

In this case, the call to the inheriting contract is displayed correctly with sourcemap:
<img width="600" alt="Screenshot 2024-02-07 at 4 54 49 PM" src="https://github.com/foundry-rs/foundry/assets/6371847/36c5c3de-ce68-4b48-9c57-b27c53239c31">

But once the function is dispatched to the inherited contract (`JUMPI` -> `JUMPDEST`), the debugger reports no sourcemap:
<img width="626" alt="Screenshot 2024-02-07 at 4 55 27 PM" src="https://github.com/foundry-rs/foundry/assets/6371847/4fccf812-1110-47cf-99b9-a862701f8617">

Code for minimal repro; run with `forge clean; forge test --debug test_Increment.` Tested with solc `0.8.13` and `0.8.23`.

### Counter.sol
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.13;

contract Counter {
    uint256 internal _number;

    event SetNumber(uint256 newNumber);
    event Increment();

    function setNumber(uint256 newNumber) public {
        emit SetNumber(newNumber);
        _number = newNumber;
    }

    function increment() public {
        emit Increment();
        ++_number;
    }

    function number() public view returns (uint256) {
        return _number;
    }

    function name() public view virtual returns (string memory) {
        return "Counter";
    }
}
```

### AltCounter.sol (inheriting contract)
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.13;

import {Counter} from "src/Counter.sol";

contract AltCounter is Counter {
    function name() public view virtual override returns (string memory) {
        return "AltCounter";
    }
}
```

### Counter.t.sol
```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.13;

import {Test} from "forge-std/Test.sol";
import {Counter} from "src/Counter.sol";
import {AltCounter} from "src/AltCounter.sol";

contract CounterTest is Test {
    Counter public counter;

    function setUp() public {
        counter = new AltCounter();
        counter.setNumber(0);
    }

    function test_Increment() public {
        counter.increment();
        assertEq(counter.number(), 1);
    }

    function testFuzz_SetNumber(uint256 x) public {
        counter.setNumber(x);
        assertEq(counter.number(), x);
    }
}
```

**Comment by emo-eth** [comment]
@DaniPopes any idea if this is related to #6522? I'm pretty sure it's been broken for longer, but something about looking up sourcemaps from inherited contracts is broken at some point. Trying my best to figure out if that's loading the sources when building the debugger or when looking up the pc in the map.

**Comment by emo-eth** [comment]
I've located the issue. 

[`ContractSources`](https://github.com/foundry-rs/foundry/blob/725c9a95b1331c67b55facd4da1598cbc8e03112/crates/common/src/compile.rs#L276) is a mapping of `name -> id -> (source code, bytecode)`

In `src_map`, the source for the contract is [looked up by name](https://github.com/foundry-rs/foundry/blob/3344e2ceeb68fd77d6be001ce7990742debc2e9a/crates/debugger/src/tui/draw.rs#L331). Since this may return multiple contracts with the same name, the entries are iterated over and the SourceElement's `index` is compared to the `file_id` of the current contract source. [If they match, the source code is returned](https://github.com/foundry-rs/foundry/blob/3344e2ceeb68fd77d6be001ce7990742debc2e9a/crates/debugger/src/tui/draw.rs#L353).

The problem is that this will never return source code for inherited contracts, because it is only loading source code for the contract being invoked; if the `SourceElement` points to a different `index` (aka `file_id`), it will never match any of the contract sources loaded from `ContractSources`. 

`ContractSources` should maintain an index both of `name -> id -> (source, bytecode)` _and_ `id -> (source, bytecode)` for looking up cross-source sourcemaps.

**Comment by emo-eth** [comment]
This is broken again @DaniPopes

**Comment by mmsaki** [comment]
@emo-eth I having this same issue where the contract source is not loaded. I am reading your comments here but it doesn't mention anything about how to resolve it. Can you share how to get the contract to be loaded on the debug panel?
