### ISSUE TITLE
`getDeployedCode` failed to find the code

### ISSUE THREAD

**Issue by zhiqiangxu** [foundry-rs/foundry#7045]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a5efe4f 2024-02-08T00:15:08.598684835Z)

### What command(s) is the bug in?

forge script

### Operating System

Linux

### Describe the bug

When executing `VM::getDeployedCode("DeployConfig.s.sol:DeployConfig")`, foundry is looking for `forge-artifacts/DeployConfig.s.sol/DeployConfig.json`, but there's no such file:

```bash
ll forge-artifacts/DeployConfig.s.sol/
total 680
drwxr-xr-x   2 root root   4096 Jan 26 04:23 ./
drwxr-xr-x 343 root root  20480 Feb  8 02:34 ../
-rw-r--r--   1 root root 359118 Feb  8 02:34 DeployConfig.0.8.15.json
-rw-r--r--   1 root root 308925 Jan 26 04:23 DeployConfig.0.8.19.json
```

Here's the complete tree for forge-artifacts:

```bash
# tree forge-artifacts/
forge-artifacts/
...
├── DeployConfig.s.sol
│   ├── DeployConfig.0.8.15.json
│   └── DeployConfig.0.8.19.json
...

343 directories, 712 files
```

It seems the naming convension is not consistent, some are like `xxx.json`, some are like `xxx.version.json`?

**Comment by klkvr** [comment]
You can fetch specific artifact via `VM::getDeployedCode("DeployConfig.s.sol:DeployConfig.0.8.15")`

What would you like as a default behavior in this case? It seems that you compile sources with different solc versions and some of artifacts are getting compiled with more than one. I don't think it would be safe for cheatcode backend to decide which contract bytecode to return in that case without explicitly specified version

**Comment by zhiqiangxu** [comment]
Why are there two naming conventions, some are like `xxx.json`, some are like `xxx.version.json`?

**Comment by klkvr** [comment]
`xxx.version.json` is used only when the same `xxx` contract is getting compiled with different solc versions

**Comment by zhiqiangxu** [comment]
Where're the solc versions specified in `foundry.toml`? I glimpsed over https://github.com/ethereum-optimism/optimism/blob/develop/packages/contracts-bedrock/foundry.toml but didn't see such options specified.

**Comment by klkvr** [comment]
By default, solc versions are determined automatically if [auto_detect_solc](https://book.getfoundry.sh/reference/config/solidity-compiler#auto_detect_solc) is set to true, otherwise, you may specify [solc_version](https://book.getfoundry.sh/reference/config/solidity-compiler#solc_version) to lock specific version

**Comment by zhiqiangxu** [comment]
But it seems neither `auto_detect_solc` nor `solc_version` is specified in the above `foundry.toml`.

**Comment by tynes** [comment]
Try `forge clean` to remove all artifacts and then rebuild. It will build with only 1 version for the particular contract now instead of 2

fwiw the following syntax has never worked for me: `VM::getDeployedCode("DeployConfig.s.sol:DeployConfig.0.8.15")`, maybe i was doing something wrong
