### ISSUE TITLE
`forge flatten` : Failed to flatten: missing field `block`

### ISSUE THREAD

**Issue by Metaxona** [foundry-rs/foundry#7069]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (b174c3a 2024-02-09T00:16:22.953958126Z)

### What command(s) is the bug in?

forge flatten

### Operating System

Linux

### Describe the bug

UUPS Contract Implementations are not getting flattened, only the proxy contracts and other specified contracts are getting flattened

errors are showing: 
Failed to flatten: missing field `block` at line 1 column 194281
Failed to flatten: missing field `block` at line 1 column 492135

when it's the implementation's turn to be flattened

![image](https://github.com/foundry-rs/foundry/assets/110418886/3775dbad-a5ac-4fae-96ce-43d4b7e0206b)

tried it on WSL
![image](https://github.com/foundry-rs/foundry/assets/110418886/b47715c7-4cb2-42ac-a36a-8489212fd4b3)

and on Ubuntu server
![image](https://github.com/foundry-rs/foundry/assets/110418886/a454131f-bbe2-4204-9ccb-0b2b906385c9)

forge 0.2.0 (b174c3a 2024-02-09T00:16:22.953958126Z)

ending up with the same result

**Comment by klkvr** [comment]
hey @Metaxona thank you for the report! any chance you could share a repro for this?

If the code being flattened contains do-while blocks than I probably know what might be causing this, but otherwise a repro would be very useful here

**Comment by Metaxona** [comment]
> hey @Metaxona thank you for the report! any chance you could share a repro for this?
> 
> If the code being flattened contains do-while blocks than I probably know what might be causing this, but otherwise a repro would be very useful here

yeah it does indeed contain a do while loop, several of them. though I am currently not able to share the repo since it's a private and not a personal repo

but i did use do while loops in-place of all or most for loop applications
