### ISSUE TITLE
`eth_gasPrice` value lower than `eth_maxPriorityFeePerGas`

### ISSUE THREAD

**Issue by antonis19** [foundry-rs/foundry#7070]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a5efe4f 2024-02-08T00:16:00.244105000Z)

### Operating System

macOS (Apple Silicon)

### Describe the bug

I am running a local fork of Ethereum mainnet using anvil:
```bash
anvil --fork-url <INFURA_URL>
```

The issue is that the `eth_gasPrice` estimate I get from the anvil node is less than the `eth_maxPriorityFeePerGas` estimate, leading to the transaction using these values getting rejected.

Here is an example:

```bash
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_gasPrice","params":[],"id":1}' http://localhost:8545
{"jsonrpc":"2.0","id":1,"result":"0x2cddfb229"}
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_maxPriorityFeePerGas","params":[],"id":1}' localhost:8545
{"jsonrpc":"2.0","id":1,"result":"0x560249a52"}
```

As you can see the gas price estimate is significantly lower than the priority fee estimate. 

Note that this wasn't the case when sending these RPC calls directly to the Infura URL.

**Comment by mattsse** [comment]
is this on the first block after launch?

**Comment by antonis19** [comment]
@mattsse  Yes.
