### ISSUE TITLE
delegate `debug_traceTransaction` in forking mode

### ISSUE THREAD

**Issue by Silur** [foundry-rs/foundry#7072]
### Component

Anvil

### Describe the feature you would like

Anvil currently returns "Requested data unavailable" when trying to call `debug_traceTransaction' on an forked anvil instance. It should however be delegated to the fork, same as in https://github.com/foundry-rs/foundry/pull/2832

**Comment by mattsse** [comment]
the `debug_traceTransaction ` is already delegated to the fork if we're unable to find it

doe your provider support this call?

**Comment by Silur** [comment]
my provider is alchemy, so yes

**Comment by Silur** [comment]
testing `debugTraceTransaction` using web3py against the same RPC worked, but when done with an anvil fork it's __data unavailable__

**Comment by mattsse** [comment]
> Fork it's data unavailable

this should be fixed via https://github.com/foundry-rs/foundry/pull/7229
