### ISSUE TITLE
Copying `memory` array of structs to `storage` leads to an ICE in `solc`

### ISSUE THREAD

**Issue by lum7na** [foundry-rs/foundry#7085]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (93f094bf 2024-02-12T12:10:59.691138419Z)

### What command(s) is the bug in?

forge test  -vvvv --gas-limit 30000000 --use 0.8.24  -j

### Operating System

Linux

### Describe the bug

Hi! I'm testing the following Solidity program using Forge. I created an array of structs in `memory` and copied it to `storage`. I tested it with the `solc` compiler versions 0.8.21 to 0.8.24, and they all produced an ICE:

```plaintext
Compiler run failed:
Error: Unimplemented feature (/solidity/libsolidity/codegen/ArrayUtils.cpp:227): Copying of type struct C.S memory[] memory to storage not yet supported.
```

Notably, if I add `--via-ir` to the Forge parameters, this issue does not occur.

If I compile the file directly with `solc` (using `solc test.sol`), there is no problem.

```solidity
pragma abicoder v2;

contract C {

    struct S {
        uint136 p;
        uint128[3] b;
        uint128[] c;
    }

    S[] s;

    function f() external {
        S[] memory m = new S[](3);
        s = m;
    }

}
```

```solidity
import {Test, console2} from "forge-std/Test.sol";

import {C} from "src/test.sol";

contract SolcTest is Test {C public c_t;

    function setUp() public {
        c_t = new C();
    }

    function testf() public {
        c_t.f();
    }

}
```

**Comment by mattsse** [comment]
idk what the progress on that solidity feature is but it looks like this is only supported --via-ir

**Comment by DaniPopes** [comment]
This ICE happens during code generation, so you have to pass `solc path.sol --bin` to trigger it.

```sh
$ cat src/Test.sol
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.24;
pragma abicoder v2;

contract C {
    struct S {
        uint136 p;
        uint128[3] b;
        uint128[] c;
    }

    S[] s;

    function f() external {
        S[] memory m = new S[](3);
        s = m;
    }
}

$ solc src/Test.sol --bin
Unimplemented feature:
/solidity/libsolidity/codegen/ArrayUtils.cpp(227): Throw in function solidity::frontend::ArrayUtils::copyArrayToStorage(const solidity::frontend::ArrayType&, const solidity::frontend::ArrayType&) const::<lambda(solidity::frontend::CompilerContext&)>
Dynamic exception type: boost::wrapexcept<solidity::langutil::UnimplementedFeatureError>
std::exception::what: Copying of type struct C.S memory[] memory to storage not yet supported.
[solidity::util::tag_comment*] = Copying of type struct C.S memory[] memory to storage not yet supported.
```

See also: https://github.com/ethereum/solidity/issues/14837, 

Closing as this is not related to Foundry.
