### ISSUE TITLE
Forge not printing error/warning messages

### ISSUE THREAD

**Issue by derekchiang** [foundry-rs/foundry#7100]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (b174c3a 2024-02-09T00:19:10.198273000Z)

### What command(s) is the bug in?

forge build

### Operating System

macOS (Apple Silicon)

### Describe the bug

The compiler is simply not printing any warning/error messages as can be seen in the screenshot.  Reinstalling foundry doesn't fix it.

<img width="719" alt="Screenshot 2024-02-12 at 10 00 56 PM" src="https://github.com/foundry-rs/foundry/assets/1535686/e910e448-de8d-4db6-ba1d-1f05c55c4511">

**Comment by DaniPopes** [comment]
Do you have a reproducer? What solc version are you using?
