### ISSUE TITLE
support EIP-4844 blob transactions in cast send

### ISSUE THREAD

**Issue by colinlyguo** [foundry-rs/foundry#7102]
### Component

Cast

### Describe the feature you would like

It would be very useful for devs to try out and test blob transactions locally if `cast` supports EIP-4844 blob transactions.
Raising this issue because the parameters of blob transactions cannot be found in this doc: https://book.getfoundry.sh/reference/cast/cast-send.

**Comment by zerosnacks** [comment]
Resolved by https://github.com/foundry-rs/foundry/pull/7823

See: `cast send --help`

```
      --blob
          Send a EIP-4844 blob transaction

      --blob-gas-price <BLOB_PRICE>
          Gas price for EIP-4844 blob transaction
          
          [env: ETH_BLOB_GAS_PRICE=]
```
