### ISSUE TITLE
Parsing fails with bytes32 and address

### ISSUE THREAD

**Issue by QGarchery** [foundry-rs/foundry#7139]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (3cdee82 2024-02-15T00:16:41.175930486Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

Parsing a json file as the following struct fails unexpectedly with `Reason: EvmError: Revert`:
```solidity
struct S {
        bytes32 id;
        address addr;
    }
```
Parsing is done on `example.json`:
```
{ "id" : "0x1111111111111111111111111111111111111111111111111111111111111111", "addr": "0x0000000000000000000000000000000000000000"}
```
using the following snippet:
```solidity
        string memory projectRoot = vm.projectRoot();
        string memory path = string.concat(projectRoot, "/example.json");
        string memory json = vm.readFile(path);

        abi.decode(json.parseRaw(""), (S));
```

For convenience, this is [reproduced here](https://github.com/QGarchery/forge-parse-bytes/actions/runs/7915201317/job/21606536166). Notice that if you switch the order of the fields in the struct, then [it goes through](https://github.com/QGarchery/forge-parse-bytes/pull/1/files).

**Comment by grandizzy** [comment]
can take this one, using `serde_json::Map` (which is backed by a BTreeMap) here https://github.com/foundry-rs/foundry/blob/master/crates/cheatcodes/src/json.rs#L371 should solve it

**Comment by grandizzy** [comment]
> can take this one, using `serde_json::Map` (which is backed by a BTreeMap) here https://github.com/foundry-rs/foundry/blob/master/crates/cheatcodes/src/json.rs#L371 should solve it

hm, actually this will probably break backward compatibility so don't think it's a good idea
