### ISSUE TITLE
 "Failed to decode constructor arguments" when running script

### ISSUE THREAD

**Issue by chlwys** [foundry-rs/foundry#7144]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (3cdee82 2024-02-15T00:19:38.655803000Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

Similar issue to https://github.com/foundry-rs/foundry/issues/6571. This only broke with `3cdee82` – the nightly release from the day before `fd87629` works fine

Havent been able to isolate it specifically, and the current optimism build doesn't trigger the bug. 

For context: the script running is used to deploy around 200 contracts with about 1.5k transactions. Will update if I manage to get it into a sample repo

Error message:
> 2024-02-15T21:48:11.162433Z ERROR forge::cmd::script::transaction: Failed to decode constructor arguments contract=Some("AddressComponent") signature=constructor(address,uint256) is_create2=false constructor_args=90b9317c2b3be33c164621cf9cae64736f6c63430008110033000000000000000000000000610178da211fef7d417bc0e6fed39f05609ad788

**Comment by DaniPopes** [comment]
fd87629...3cdee82

Either https://github.com/foundry-rs/foundry/pull/7108 or https://github.com/foundry-rs/foundry/pull/7109

Are you able to reproduce on every run?

If you can't get a minimal repro, could you share the full logs with `RUST_LOG=debug,evm::traces=trace`?

**Comment by chlwys** [comment]
@DaniPopes managed to reproduce it here. Note that it only doesn't work when broadcasting to a node

https://github.com/chlwys/foundry_decode_constructor_reproduction
