### ISSUE TITLE
Install via CURL - "SSL certificate problem: certificate has expired"

### ISSUE THREAD

**Issue by ewebgh33** [foundry-rs/foundry#7147]
### Component

Foundryup

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

Cannot install, issue is installing

### What command(s) is the bug in?

curl -L https://foundry.paradigm.xyz | bash

### Operating System

macOS (Intel)

### Describe the bug

Thought you would want to know
Tried to install Foundry just now
And got this:

```
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
HTTPS-proxy has similar options --proxy-cacert and --proxy-insecure.
```

Yes I could tell it to ignore but as I said, I thought the team would like to know this is happening.

Aside: _SSLs are the worst part of the internet. If we all need them, why aren't they included with all hosts by default? Oh right, profiteering. I feel you. :(_

**Comment by EmmaWebGH** [comment]
Uh do I need to worry about this too?
Related or not?

```
dyld: cannot load 'forge' (load command 0x80000034 is unknown)
foundryup: command failed: /Users/COMPUTERFACE/.foundry/bin/forge --version
foundryup: installed - 
dyld: cannot load 'cast' (load command 0x80000034 is unknown)
foundryup: command failed: /Users/COMPUTERFACE/.foundry/bin/cast --version
foundryup: installed - 
dyld: cannot load 'anvil' (load command 0x80000034 is unknown)
foundryup: command failed: /Users/COMPUTERFACE/.foundry/bin/anvil --version
foundryup: installed - 
dyld: cannot load 'chisel' (load command 0x80000034 is unknown)
foundryup: command failed: /Users/COMPUTERFACE/.foundry/bin/chisel --version
foundryup: installed - 
```

**Comment by EmmaWebGH** [comment]
Where can I find the minimum MacOS version needed to run please?

**Comment by DaniPopes** [comment]
Should be MacOS 10.12 Sierra, but we build in CI with macos-large-latest which is MacOS 13.

I don't really have much context cc @onbjerg @mattsse

**Comment by onbjerg** [comment]
this is because that specific load command was introduced in later versions of macos, i'm not sure which one specifically. can prob be fixed in CI. i assume you're on an intel chip?

**Comment by EmmaWebGH** [comment]
Certainly

10.13.6 High Sierra / 3ghz Intel Core Xeon X5 / 64GB RAM

It's a Mac Pro trashcan but that shouldn't be any different to any other Mac running High Sierra.
I would love to be able to get Foundry working here - previously tried Truffle/Brownie and Hardhat, about 18months back, and then stopped (but no troubles running those at the time). Trying to pick up again with current tools.

Googling did indeed tell me it was some command native to later versions of Mac, but sadly not how to get around it.
Appreciate this is a niche case but if anyone knows of a simple workaround I would really like to get this working.

:) Thanks
E

**Comment by DaniPopes** [comment]
You can try compiling from source with the latest stable rust version (https://rustup.rs) using 'foundryup -b master'

**Comment by onbjerg** [comment]
Yeah, building from source would be your best bet

**Comment by Evalir** [comment]
Closing as stale—please let us know if it isn't fixed and we'll reopen
