### ISSUE TITLE
Multiple Compiler issue

### ISSUE THREAD

**Issue by hammad-ali18** [foundry-rs/foundry#7157]
Hello folks, I just want to know that how can I run the multiple compiler versions contract , like some are libraries and some are the contracts ,and when I ran >> forge build  it lays down me this error
Like should I need to edit the foundry.toml file with multiple versions , guide me to the process.
![compilerissue](https://github.com/foundry-rs/foundry/assets/91586903/9e0d6465-aca4-4b7d-aec9-ab119dd031bb)

**Comment by DaniPopes** [comment]
Your project's Solidity pragmas are not compatible. You cannot use both chainlink 0.6 and 0.8.

**Comment by hammad-ali18** [comment]
> Your project's Solidity pragmas are not compatible. You cannot use both chainlink 0.6 and 0.8.

yes , I know I can use but how should I configure inside my foundry.toml file?
