### ISSUE TITLE
feat: cheatcode to set address name for trace

### ISSUE THREAD

**Issue by algtm** [foundry-rs/foundry#7160]
### Component

Forge

### Describe the feature you would like

Allow using cheatcode to set aliases for addresses and contracts deployed by deploycode, making it convenient to display in the trace.

**Comment by grandizzy** [comment]
I think you're looking for `label` cheatcode? https://book.getfoundry.sh/cheatcodes/label

**Comment by onbjerg** [comment]
Closing per above comment, `vm.label` is what you are looking for :)

**Comment by algtm** [comment]
> I think you're looking for `label` cheatcode? https://book.getfoundry.sh/cheatcodes/label

yes! thank you
