### ISSUE TITLE
Contents of Cargo.toml do not match ethers::Abigen from Template

### ISSUE THREAD

**Issue by nbstrong** [foundry-rs/foundry#7163]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (1bb2d67 2024-02-19T00:17:15.443050638Z)

### What command(s) is the bug in?

forge bind --bindings-path ./crates/bindings --root ./contracts --crate-name bindings

### Operating System

Linux

### Describe the bug

Created a new project with
`forge init --template https://github.com/foundry-rs/foundry-rust-template foundry_prj`

Ran through the commands in the Readme until I got to
`forge bind --bindings-path ./crates/bindings --root ./contracts --crate-name bindings`

And receive this error:
$`forge bind --bindings-path ./crates/bindings --root ./contracts --crate-name bindings`
[⠢] Compiling...
No files changed, compilation skipped
Bindings found. Checking for consistency.
Checking bindings for 1 contracts.
Error:
To skip Cargo.toml consistency check, pass --skip-cargo-toml

Context:
- The contents of `./crates/bindings/Cargo.toml` do not match the expected output of the newest `ethers::Abigen` version.This indicates that the existing bindings are outdated and need to be generated again.

If I run forge bind again I get:
$`forge bind`
[⠊] Compiling...
[⠒] Unable to resolve imports:
      "ds-test/test.sol" in "/foundry_prj/contracts/lib/forge-std/src/Test.sol"
      "ds-test/test.sol" in "/foundry_prj/contracts/lib/forge-std/src/StdAssertions.sol"
      "forge-std/Script.sol" in "/foundry_prj/contracts/script/Counter.s.sol"
      "forge-std/Test.sol" in "/foundry_prj/contracts/test/Counter.t.sol"
with remappings:
[⠢] Unable to resolve imports:
      "ds-test/test.sol" in "/foundry_prj/contracts/lib/forge-std/src/Test.sol"
      "ds-test/test.sol" in "/foundry_prj/contracts/lib/forge-std/src/StdAssertions.sol"
      "forge-std/Script.sol" in "/foundry_prj/contracts/script/Counter.s.sol"
      "forge-std/Test.sol" in "/foundry_prj/contracts/test/Counter.t.sol"
with remappings:

[⠆] Compiling 34 files with 0.8.24
[⠰] Solc 0.8.24 finished in 51.05ms
Error:
Compiler run failed:
Error (6275): Source "ds-test/test.sol" not found: File not found. Searched the following locations: "/foundry_prj".
 --> contracts/lib/forge-std/src/StdAssertions.sol:4:1:
  |
4 | import "ds-test/test.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^

Error (6275): Source "ds-test/test.sol" not found: File not found. Searched the following locations: "/foundry_prj".
 --> contracts/lib/forge-std/src/Test.sol:5:1:
  |
5 | import "ds-test/test.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^

Error (6275): Source "forge-std/Script.sol" not found: File not found. Searched the following locations: "/foundry_prj".
 --> contracts/script/Counter.s.sol:4:1:
  |
4 | import "forge-std/Script.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error (6275): Source "forge-std/Test.sol" not found: File not found. Searched the following locations: "/foundry_prj".
 --> contracts/test/Counter.t.sol:4:1:
  |
4 | import "forge-std/Test.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by DaniPopes** [comment]
In that section:

> Any follow-on calls to forge bind will check that the generated bindings match the ones under the build files. If you want to re-generate your bindings, pass the --overwrite flag to your forge bind command.

Pass `--overwrite`.

**Comment by nbstrong** [comment]
Ok, I tried that and the template still throws errors

$forge bind --overwrite
[⠊] Compiling...
[⠒] Unable to resolve imports:
      "forge-std/Script.sol" in "/foundry_prj/contracts/script/Counter.s.sol"
      "ds-test/test.sol" in "/foundry_prj/contracts/lib/forge-std/src/StdAssertions.sol"
      "forge-std/Test.sol" in "/foundry_prj/contracts/test/Counter.t.sol"
      "ds-test/test.sol" in "/foundry_prj/contracts/lib/forge-std/src/Test.sol"
with remappings:
[⠢] Unable to resolve imports:
      "forge-std/Script.sol" in "/foundry_prj/contracts/script/Counter.s.sol"
      "ds-test/test.sol" in "/foundry_prj/contracts/lib/forge-std/src/StdAssertions.sol"
      "forge-std/Test.sol" in "/foundry_prj/contracts/test/Counter.t.sol"
      "ds-test/test.sol" in "/foundry_prj/contracts/lib/forge-std/src/Test.sol"
with remappings:
[⠆] Unable to resolve imports:
      "forge-std/Script.sol" in "/foundry_prj/contracts/script/Counter.s.sol"
      "ds-test/test.sol" in "/foundry_prj/contracts/lib/forge-std/src/StdAssertions.sol"
      "forge-std/Test.sol" in "/foundry_prj/contracts/test/Counter.t.sol"
      "ds-test/test.sol" in "/foundry_prj/contracts/lib/forge-std/src/Test.sol"
with remappings:

[⠰] Compiling 34 files with 0.8.24
[⠔] Solc 0.8.24 finished in 52.86ms
Error:
Compiler run failed:
Error (6275): Source "ds-test/test.sol" not found: File not found. Searched the following locations: "/foundry_prj".
 --> contracts/lib/forge-std/src/StdAssertions.sol:4:1:
  |
4 | import "ds-test/test.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^

Error (6275): Source "ds-test/test.sol" not found: File not found. Searched the following locations: "/foundry_prj".
 --> contracts/lib/forge-std/src/Test.sol:5:1:
  |
5 | import "ds-test/test.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^

Error (6275): Source "forge-std/Script.sol" not found: File not found. Searched the following locations: "/foundry_prj".
 --> contracts/script/Counter.s.sol:4:1:
  |
4 | import "forge-std/Script.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error (6275): Source "forge-std/Test.sol" not found: File not found. Searched the following locations: "/foundry_prj".
 --> contracts/test/Counter.t.sol:4:1:
  |
4 | import "forge-std/Test.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by DaniPopes** [comment]
you need all the other arguments as well, please read the readme and documentation first

**Comment by nbstrong** [comment]
A templated project should not have errors from running commands found in the readme with no changes.
