### ISSUE TITLE
cannot verify the contract on mumbai scan

### ISSUE THREAD

**Issue by mymiracle0118** [foundry-rs/foundry#7164]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge script script/MRPTDeploy.s.sol:MRPTDeploy --broadcast --rpc-url mumbai --etherscan-api-key mumbai --verify -vv

### Operating System

Windows

### Describe the bug

I tried to deploy the contract to mumbai scan.
![image](https://github.com/foundry-rs/foundry/assets/146400751/22cda381-94b7-4b86-a83a-e240775d66cf)
this is my foundry.toml

![image](https://github.com/foundry-rs/foundry/assets/146400751/e73ab181-999e-4068-84f6-73393e3dc9cd)

![image](https://github.com/foundry-rs/foundry/assets/146400751/85f65d0c-a540-43f5-866d-6b69ee29c548)
Can anyone help me to fix it?

**Comment by DaniPopes** [comment]
MUMBAISCAN_API_KEY is not set or not a valid API key on Mumbaiscan.

**Comment by mymiracle0118** [comment]
![image](https://github.com/foundry-rs/foundry/assets/146400751/b6dc830f-8a83-4c56-97d7-bcb74808f42b)
This is env
