### ISSUE TITLE
verification response ok, but in fact not successful

### ISSUE THREAD

**Issue by zhiqiangxu** [foundry-rs/foundry#7171]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (7922fd5 2024-02-05T00:19:20.258041000Z)

### What command(s) is the bug in?

forge verify-contract

### Operating System

macOS (Intel)

### Describe the bug

I found that no matter whether the verification is successful, `verify-contract` always returns "Response: `OK`". It should only return "Response: `OK`" when verification is successful.

**Comment by DaniPopes** [comment]
`Submitted contract for verification: OK` does not mean it's successfully verified. This only means that the submission was successful, you have to use `--watch` or check later to see if it's been verified.
