### ISSUE TITLE
Formatter integration with emacs

### ISSUE THREAD

**Issue by clearloop** [foundry-rs/foundry#7175]
### Component

Forge

### Describe the feature you would like

Ethereum has provided an emacs mode https://github.com/ethereum/emacs-solidity which uses solium as the default formatter and it has conflicts with the foundry code structure

the problem leads emacs users to a hard situation ...

- abandon flycheck/company mode for solidity code
- develop a plugin themselves
- use hardhat with well-built code editing environment
- forget about writing solidity code
- switch to vscode (don't ask)

foundry seems now only has chapter about the integration with https://book.getfoundry.sh/config/vscode only,

- PR `solidity-mode` or fork it to `foundry-mode.el`
- add documentation about how to use it in emacs
- (advanced) add the mode to the popular emacs frameworks, for example https://docs.doomemacs.org/v21.12/modules/lang/solidity/

**Comment by onbjerg** [comment]
This should be a 3rd party tool, we do not maintain the VS Code plugin either. Feel free to open a PR to the book with a guide on how to set it up 😊

**Comment by clearloop** [comment]
in case anybody else need a workaround, for `src/.solumrc.json`:

```json,diff
{
  - extends: "solium:recommend",
  "rules": {                                                                                                                                                                                                
    "max-len": ["error", 120],
    "__others": "..."
   }
}
```

> This should be a 3rd party tool, we do not maintain the VS Code plugin either. Feel free to open a PR to the book with a guide on how to set it up 😊

and since solium is a dead project now, see no reasons making it an option in `forge fmt` or developing a foundry plugin for it atm ))
