### ISSUE TITLE
No output for files having no contract/library definition

### ISSUE THREAD

**Issue by ShahriarJavidi** [foundry-rs/foundry#7200]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (2f4b5db 2024-02-21T00:17:48.983570637Z)

### What command(s) is the bug in?

forge build

### Operating System

Linux

### Describe the bug

If there is a file in the project with neither a contract nor a library definition (a use-case of that could be a file holding all constants definition for a project), `forge build` creates no `.json` file for it, despite having `SourceUnit` definitions. As an example [Spool-V2-core](https://github.com/SpoolFi/spool-v2-core/tree/main) has under `src/interfaces/` a `.sol` file named `Constants.sol`, which consists of only constant definitions. However, no `.json` output gets generated for it.

**Comment by 0xalpharush** [comment]
I would recommend using the artifacts produced by `forge build --build-info` as they are much easier to work with and you won't run into issues like https://github.com/foundry-rs/foundry/issues/7199

**Comment by ShahriarJavidi** [comment]
Thanks a lot, @0xalpharush!
The artifacts under `out/build-info`  contain not only constant definitions but also resolves what I mention in [Colliding contract names](https://github.com/foundry-rs/foundry/issues/7199#issue-2146162279).
Using them, I could resolve both issues.

Thanks again for your awesome hint!
