### ISSUE TITLE
feat(cheatcodes): allow `forge script` to access wallet addresses with `vm.getScriptWallets()`

### ISSUE THREAD

**Issue by superical** [foundry-rs/foundry#7213]
### Component

Forge

### Describe the feature you would like

To have a feature where we can access in our foundry scripts the private keys input from `--interactives` mode or the resolved public addresses of those private keys. This way, we don't have to repeat the sender address in the `--sender` because we can decide which private keys to use as the sender and pass the intended address as the `sender` in `vm.startBroadcast(sender)`.

For example:
```solidity
uint256[] privateKeys = vm.interactives();
// Or, an optional index parameter to get from the list of input private keys
// uint256 privateKey = vm.interactives(0);   // gets the first private key entered from interactive mode

address sender = vm.addr(privateKeys[0]);

vm.startBroadcast(sender);
// ...
vm.stopBroadcast();
```

### Additional context

Currently, when forge is run with `--interactives`, it doesn't seem like there is a way to access the private keys or the public addresses of those private keys provided through the interactive input in the foundry scripts. The only way (as far as I have tried) to run the foundry scripts with `--interactives` is:

- Provide the address of the private key through `--sender` on top of `--interactives`
- AND only use `vm.startBroadcast()`. I cannot use `vm.startBroadcast(sender)` since I cannot access the private key supplied through the interactive input and so I won't know the `sender` address.

Supplying the public address through `--sender` feels repeated because the address should already be resolvable from the private key.

Moreover, the `--interactives` parameter can accept more than one private keys which seems to suggest a script should be able to select one of the keys supplied to be the actual sender. 

If there is a feature where we can access the input private keys or their translated public addresses in our foundry scripts, we wouldn't have to repeat the address in the `--sender` because our foundry script can decide which private key to use as sender and pass the correct address as the sender in `vm.startBroadcast(sender)`.

**Comment by mds1** [comment]
Can `vm.getScriptWallets()` could return an array of [`Wallet`](https://github.com/foundry-rs/forge-std/blob/1d0766bc5d814f117c7b1e643828f7d85024fb51/src/Vm.sol#L126-L136) structs in scripts and tests? This way you can write tests for your scripts and do something like `forge test script/MyScript.s.sol --private-key $DUMMY_PRIVATE_KEY` to test your scripts

**Comment by klkvr** [comment]
We can't always get a private/public key for script wallets as such info is not available for hw wallets

**Comment by klkvr** [comment]
This should be solvable with pattern similar to the one discussed in https://github.com/foundry-rs/foundry/pull/7012#issuecomment-1927218283

That way, the script will look like
```solidity
contract Script {
    function run() public {
        address[] memory wallets = vm.getScriptWallets();
        // logic to determine which wallets to use for broadcasting
        run(wallet1, wallet2);
    }

    function run(address broadcaster1, address broadcaster2) public {
        // actual logic
    }
}
```

> do something like forge test script/MyScript.s.sol --private-key $DUMMY_PRIVATE_KEY to test your

this is similar to dry-running a script I believe

Probably more often it's useful do determine broadcaster at runtime when testing script, by calling `.owner()` on some contract for example

**Comment by grandizzy** [comment]
going to close in favor of https://github.com/foundry-rs/foundry/issues/8225 and track impl there
