### ISSUE TITLE
Add an "airdrop" feature at start of Anvil network

### ISSUE THREAD

**Issue by AbhinavMir** [foundry-rs/foundry#7217]
### Component

Anvil

### Describe the feature you would like

```
anvil --accounts 10 --balance 10 --mnemonic-random --airdrop=[0x...., 0x....]
```

This would allow me to use my test wallet instead of creating new wallets every time. A genesis file similar to the one available in Cosmos will be great too. Wondering if there is something similar available.

### Additional context

Since Anvil "knows" the private key at start of network, it can use one of the private keys to send the tokens to a mentioned address via Alloy or Ethers.

**Comment by Evalir** [comment]
You can initialize anvil with a `genesis.json` file, see the general options: https://book.getfoundry.sh/reference/anvil/?highlight=genesis#general-options

for an example of a `genesis.json` file, see https://github.com/foundry-rs/foundry/blob/5f8579b3fefc5b3e3b76cecf827c7361866fbd36/crates/anvil/tests/it/genesis.rs#L12-L37 , you probably want to see the `alloc` section. This is geth's genesis.json format (see https://geth.ethereum.org/docs/fundamentals/private-network#ethash-example)

**Comment by AbhinavMir** [comment]
My bad, thank you!
