### ISSUE TITLE
Evaluate environment variables in foundry.toml

### ISSUE THREAD

**Issue by tkali** [foundry-rs/foundry#7220]
### Component

Anvil

### Describe the feature you would like

Currently `anvil` is able to read url aliases set in `[rpc_endpoints]` defined in `foundry.toml` config file (thanks to #4384), but fails short if an URL contains interpolated environment variable, say `$INFURA_KEY`, which is supported by `forge`.

**Comment by mattsse** [comment]
hmm, I cannot reproduce this

```
[rpc_endpoints]
mainnet = "${_CONFIG_MAINNET}"
```

anvil -f mainnet

**Comment by kamuik16** [comment]
> hmm, I cannot reproduce this
> 
> ```
> [rpc_endpoints]
> mainnet = "${_CONFIG_MAINNET}"
> ```
> 
> anvil -f mainnet

I did this

```
[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
```

`anvil -f mainnet` gives me this 

```
thread 'main' panicked at /home/runner/work/foundry/foundry/crates/anvil/src/config.rs:959:57:
Failed to get fork block number: Transport(Custom(TransportError(Transport(Custom(Os { code: 2, kind: NotFound, message: "No such file or directory" })))))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted
```

**Comment by kamuik16** [comment]
> > hmm, I cannot reproduce this
> > ```
> > [rpc_endpoints]
> > mainnet = "${_CONFIG_MAINNET}"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > anvil -f mainnet
> 
> I did this
> 
> ```
> [rpc_endpoints]
> mainnet = "${MAINNET_RPC_URL}"
> ```
> 
> `anvil -f mainnet` gives me this
> 
> ```
> thread 'main' panicked at /home/runner/work/foundry/foundry/crates/anvil/src/config.rs:959:57:
> Failed to get fork block number: Transport(Custom(TransportError(Transport(Custom(Os { code: 2, kind: NotFound, message: "No such file or directory" })))))
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> Aborted
> ```

Okay so I got it working after exporting my `MAINNET_RPC_URL` variable like `export MAINNET_RPC_URL="key"`.

**Comment by tkali** [comment]
Thanks for the quick response.

I can confirm, prepending variables with `export` in the `.env` file and then sourcing it works, but I don't need to do these steps with `forge`.

So it looks like reading shell environment vars works, but reading and evaluating from `.env` doesn't.

**Comment by zerosnacks** [comment]
Was able to replicate, fix implemented in https://github.com/foundry-rs/foundry/pull/7344
