### ISSUE TITLE
Add a `rawBroadcast` style cheatcode

### ISSUE THREAD

**Issue by valerioleo** [foundry-rs/foundry#7221]
### Component

Forge

### Describe the feature you would like

> This is a followup from Telegram conversation: https://t.me/foundry_support/50555

Complex Scripts can sometimes require broadcasting a pre-signed transaction, just as we would do with `cast publish`.

For example, if I want to test Seaport using @0age's keyless deployment of IMMUTABLE_CREATE2_FACTORY (as outlined in [Seaport deployment guide](https://github.com/ProjectOpenSea/seaport/blob/main/docs/Deployment.md#setting-up-factory-on-a-new-chain)). 

A the moment, the only alternative I could find is to use `vm.ffi` in this way:
```solidity
    string[] memory args = new string[](5);
    args[0] = 'cast';
    args[1] = 'publish';
    args[2] = '--rpc-url';
    args[3] = 'http://127.0.0.1:8545';
    args[4] = '0xf87e8085174876e800830186a08080ad601f80600e600039806000f350fe60003681823780368234f58015156014578182fd5b80825250506014600cf31ba02222222222222222222222222222222222222222222222222222222222222222a02222222222222222222222222222222222222222222222222222222222222222';

    vm.ffi(args);
```

However, having a `vm.publish(signetTX)` cheat code can make this process much simpler. 

Note: to avoid race conditions, the cheat code **should return only after the inclusion of that signed tx into a block** (or a revert if it is failed).

**Comment by tynes** [comment]
See https://github.com/foundry-rs/foundry/pull/4931 for an initial implementation of this. I would definitely find this useful

**Comment by zerosnacks** [comment]
Marking as a `duplicate` of https://github.com/foundry-rs/foundry/issues/4816

https://github.com/foundry-rs/foundry/pull/4931 is currently an active PR addressing this issue we are looking to get merged
