### ISSUE TITLE
Allow specifying RPC Url via cheatcode when Scripting

### ISSUE THREAD

**Issue by jhweintraub** [foundry-rs/foundry#7224]
### Component

Forge

### Describe the feature you would like

When running a script you are forced to specify the RPC url you want to use to broadcast your transactions with `forge script --rpc-url`. If you want to do a multi-chain deployment this can mean having to run a script multiple times with different RPC-urls or with a bash script that chains it together. It would be very useful if you could use a cheatcode similar to how tests allow you to use `vm.createSelectFork("mainnet")` to fork from mainnet.

I'm thinking something like `Script.setChain()` that takes an alias to a chain and sets the RPC url and the etherscan verification key accordingly from the `foundry.toml` file. This would make multi-chain deployments easier as you could simply just have one script that deployed to all chains sequentially with the same address. It would also make it easier to test multi-chain transactions that you may have to do with a multisig. 

I know this is a requested feature so if an issue already exists for it please feel free to delete this.

**Comment by klkvr** [comment]
You can use `vm.createSelectFork("mainnet")` in scripts as well. As long as you have correct rpc url and etherscan api key configured in foundry.toml for the forking chainm, everything will work correct and contracts will be verified

**Comment by jhweintraub** [comment]
> You can use `vm.createSelectFork("mainnet")` in scripts as well. As long as you have correct rpc url and etherscan api key configured in foundry.toml for the chain being forked, everything will work correctly and contracts will be verified

And this works for broadcasting as well? Sick. Thanks
