### ISSUE TITLE
[Forge] Build info are not produced when `--no-cache` is used

### ISSUE THREAD

**Issue by 0xMemoryGrinder** [foundry-rs/foundry#7230]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ac80261 2024-02-24T00:17:06.154246094Z)

### What command(s) is the bug in?

forge build --build-info --no-cache

### Operating System

Linux

### Describe the bug

Hello,

I tried to extract AST of a project using forge build info but I get an issue when I try to recompile a project. I need to pass `--no-cache` argument to the `forge build` command to make sure I recompile every file and get coherent types IDs in the AST. 

The problem is, when the cache is forcefully disabled, the build info are never generated (even if there is no previous compilation).

This is likely due to this line (https://github.com/foundry-rs/foundry/blob/master/crates/config/src/lib.rs#L673).

I am sure there is a good reason for this but can an analysis be made to evaluate the refactor needed to remove the cache condition? I would be happy to implement the changes needed.
In the meantime, I removed the cache condition for the build info and it seems to work fine (at least on the `forge init` project)

**Comment by stevennevins** [comment]
Also ran into this issue

**Comment by 0xMemoryGrinder** [comment]
Hello, is thee any update or information needed to perform the analysis ?

**Comment by klkvr** [comment]
Closed by #7347
