### ISSUE TITLE
Allow for cleaner output messages when forking origin ID is not valid

### ISSUE THREAD

**Issue by AbhinavMir** [foundry-rs/foundry#7243]
### Component

Anvil

### Describe the feature you would like

Currently, a bad command like `anvil --fork-url https://mainnet.infura.io/v3/INVALID_CODE` will result in 

```
thread 'main' panicked at /home/runner/work/foundry/foundry/crates/anvil/src/config.rs:951:57:
Failed to get fork block number: DeserError { err: Error("expected value", line: 1, column: 1), text: "invalid project id\n" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    74091 IOT instruction (core dumped)  anvil --fork-url https://mainnet.infura.io/v3/INVALID_CODE
Time taken: 1 seconds         
```
A panic is rather hard for a non-Rust user to parse in a glance. A better message would probably be `Fork error: Bad source URL` or something of that kind. 

Another side request, which I'm not sure of, is checking via regex is a URL during fork is valid (i.e of the form http://xyz.abc/)

Happy to take this up.

**Comment by zerosnacks** [comment]
I think a panic in this case is appropriate and the resulting error is highly dependent on the context

Marking as `not planned`
