### ISSUE TITLE
Add a method to remove all pending txns from the txpool

### ISSUE THREAD

**Issue by AbhinavMir** [foundry-rs/foundry#7249]
### Component

Anvil

### Describe the feature you would like

`anvil_dropTranasction` already can drop transactions, iterating over with the response from `txpool_content` would be a quick endpoint.

**Comment by AbhinavMir** [comment]
I'll be in denver till 4th, but I'd love to solve this for myself if I get the time in between. Can I be assigned this?

**Comment by mattsse** [comment]
great!
assigned

**Comment by mahmudsudo** [comment]
Still assigned , can i take on this ?
