### ISSUE TITLE
Add a `anvil_remove_pool_transaction(_by_sender)`

### ISSUE THREAD

**Issue by AbhinavMir** [foundry-rs/foundry#7250]
### Component

Anvil

### Describe the feature you would like

Allow all transactions from the txpool to be removed by sender origin.

**Comment by gerceboss** [comment]
Hi , I am new to this repository . Can  you guide me to the discussion forum for this repository? 
And can you please guide a little at what exact location do you need this function? @AbhinavMir

**Comment by mattsse** [comment]
adding support for a new endpoint is done by:

1. adding a new variant to 

https://github.com/foundry-rs/foundry/blob/b671576e738e1dc938ddee50f1fcbd730e381d67/crates/anvil/core/src/eth/mod.rs#L44-L44

2. add a new handler function
https://github.com/foundry-rs/foundry/blob/9fff5c20c08b235fd6587362c9ff639c093f68c3/crates/anvil/src/eth/api.rs#L154-L154

**Comment by gerceboss** [comment]
Thanks ! I will work upon it . Do I have to get this issue assigned for that?

**Comment by gerceboss** [comment]
Other than the files you mentioned, I observed that we have a function to remove transactions from the pool in `anvil/src/eth/pool/transaction.rs` named `remove(&self, hashes) -> Vec<Arc<PoolTransaction>>`  , I can use the same logic given here but how do I check if these are being removed by the address we received in our function. @AbhinavMir

**Comment by PanGan21** [comment]
Hi! Since this ticket seemed stale, I gave it a try in #7480  and looking for reviews 🙂
Please let me know for any suggestions!

**Comment by AbhinavMir** [comment]
ty @PanGan21 , closing this issue
