### ISSUE TITLE
Forge build failed with "solc exited with signa"

### ISSUE THREAD

**Issue by DinhKhai0201** [foundry-rs/foundry#7253]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (85b4872 2024-02-28T00:15:52.013068000Z)

### What command(s) is the bug in?

forbuild

### Operating System

macOS (Intel)

### Describe the bug

When i run 'forge build',  I get the following error
`Error: 
solc exited with signal: 6 (SIGABRT)
dyld: Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /Users/mjlt2/Library/Application Support/svm/0.8.24/solc-0.8.24 (which was built for Mac OS X 13.5)
  Expected in: /usr/lib/libc++.1.dylib`
  
  Thank team.

**Comment by DinhKhai0201** [comment]
> what's your macos version?
> 
> I assume your OS is outdated, at least that's what I read from googling the error

I am using Macos v11.6.
So Is there anyway I can use forge cli in this macos version @mattsse ?
Thanks.
<img width="298" alt="image" src="https://github.com/foundry-rs/foundry/assets/36871514/4d11fcbd-120f-4c7e-b525-975ab5a95ef2">

**Comment by Hrithik200** [comment]
Getting the same problem I am also on MACOS 11
Is there any solution for using forge?

**Comment by zerosnacks** [comment]
Tentatively closing this ticket as it relates to `solc`, not Foundry.

Instead I've added a new ticket outlining the goal of better documenting the minimal OS requirements: https://github.com/foundry-rs/foundry/issues/8417 

If you are running into issues with `solc` and you cannot upgrade to a newer version of MacOS I would recommend attempting to build from source.

**Comment by yupquc** [comment]
Do you have any solution for this problem?

When i run 'forge build', I get the following error

> Error:  solc exited with signal: 6 (SIGABRT) dyld: Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv Referenced from: /Users/mjlt2/Library/Application Support/svm/0.8.24/solc-0.8.24 (which was built for Mac OS X 13.5) Expected in: /usr/lib/libc++.1.dylib
