### ISSUE TITLE
Cast encodes incorrect calldata when given empty bytes arrays

### ISSUE THREAD

**Issue by jurassic-technology** [foundry-rs/foundry#7280]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (d58ab7f 2024-02-27T00:16:43.649244000Z)

### What command(s) is the bug in?

cast abi-encode, cast calldata

### Operating System

macOS (Apple Silicon)

### Describe the bug

Running `cast calldata "register(bytes,address,bytes[])" 0x09736b79736b79736b79026f7300  0xB7b54cd129e6D8B24e6AE652a473449B273eE3E4 "[]"` yields the following bytes: 

`
0xd123f99a0000000000000000000000000000000000000000000000000000000000000060000000000000000000000000b7b54cd129e6d8b24e6ae652a473449b273ee3e400000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000000e09736b79736b79736b79026f7300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000
`

These are incorrect and I presume this is why `cast estimate-gas` fails with these arguments. I determined this by created a forge script which invoked the method and inspected the broadcast record, which shows different calldata that succeeds when sent to the chain. That correct calldata is (address argument is different but format is same): 

`
0xd123f99a0000000000000000000000000000000000000000000000000000000000000060000000000000000000000000de12193c037f768fdc0db0b77b7e70de723b95e700000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000000e09736b79736b79736b79026f73000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
`

To verify successful calldata generation run the following forge script:

```
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import {Script, console} from "forge-std/Script.sol";
import {VmSafe} from "forge-std/Vm.sol";

contract TestBytesArrayEncoding {
    function register (bytes calldata, address, bytes[] calldata) external { }
}

contract SeeEncodingScript is Script {

    bytes constant first_arg = hex"09736b79736b79736b79026f73";

    TestBytesArrayEncoding test = new TestBytesArrayEncoding();

    function run () public {

        vm.startBroadcast();

        test = new TestBytesArrayEncoding();

        test.register(first_arg, msg.sender, new bytes[](0));

    }

}
```

**Comment by DaniPopes** [comment]
I'm running the command you posted and it returns your correct version:
```sh
$ cast calldata "register(bytes,address,bytes[])" 0x09736b79736b79736b79026f7300  0xB7b54cd129e6D8B24e6AE652a473449B273eE3E4 "[]"
0xd123f99a0000000000000000000000000000000000000000000000000000000000000060000000000000000000000000b7b54cd129e6d8b24e6ae652a473449b273ee3e400000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000000e09736b79736b79736b79026f73000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```
