### ISSUE TITLE
Add devcontainer-feature.json to root

### ISSUE THREAD

**Issue by mmsaki** [foundry-rs/foundry#7290]
### Describe the feature you would like

Devcontainer feature allows you to set up foundry packages when you create your codespaces for any foundry project that has a `.devcontainer.json`

In your user's git project directory `.devcontainer/devcontainer.json`
```json
{
"image": "mcr.microsoft.com/devcontainers/rust:1-1-bullseye",
  "features": {
    "ghcr.io/foundry-rs/foundry:latest": {}
  }
}
```

- Without this feature, your users will have to manually run installations in bash for foundry packages 🥲 

  > "I manually install foundry packages everytime i use codespaces" - Dev

- Alternatively, users can install foundry packages using `"onpostCreateCommand"`, but this is not the right pattern to get around installing foundry packages, and here's why:

**Reasons why using `"onpostCreateCommand"` | `"postAttachCommand"` | `"postStartCommand"` is not a good pattern for container package installations**
1. Each command you provide to `"onpostCreateCommand"` will be run in parallel, so you need to split into three commands, [see this setup](https://github.com/ExtropyIO/GasOptimisationFoundry/blob/main/.devcontainer/devcontainer.json)
2. In our case, if you choose to run `curl -L https://foundry.paradigm.xyz | bash && foundryup`,`foundryup` will often fail since codespaces will alway run these commands in parallel, and not sequentially as you would expect

## Adding devcontainer-feature.json

Only 3 fields are required, id, version, and name. Here's an example:

In this root directory `./devcontainer-feature.json`
```json
{
"id": "ghcr.io/foundry-rs/foundry",
"version": "1.1.0", // Each bump updated with dependabot integration see: https://containers.dev/guide/dependabot
"name": "Foundry Codespaces Feature (FCF)"
}
```

More information about the complete list of configurations possible for `devcontainer-feature.json` can be found [here](https://containers.dev/implementors/features/)

**Comment by zerosnacks** [comment]
Hi @mmsaki thanks for your suggestion,

So I understand correctly, does this rely on Foundry having versioned releases? See: https://github.com/foundry-rs/foundry/issues/3895

**Comment by mmsaki** [comment]
@zerosnacks yes foundry would need versioned releases

**Comment by grandizzy** [comment]
hey @mmsaki this is not actionable atm as we don't have versions in place (yet). Furthermore, we discussed to add this as a config doc update (similar with https://book.getfoundry.sh/config/vscode) rather than have the file committed in git, going to close this for now. thank you!
