### ISSUE TITLE
bug(`cast`): cast rpc `eth_gasPrice` --raw returns code: `-32600, message: Invalid request`

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#7297]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

cast 0.2.0 (de33b6a 2024-03-02T00:15:56.318147000Z)

### What command(s) is the bug in?

cast rpc eth_gasPrice

### Operating System

macOS (Apple Silicon)

### Describe the bug

using `cast rpc eth_gasPrice` returns a correct value:

~~~console
$ cast rpc eth_gasPrice
"0x53ca419d"
~~~

However defining the --raw RPC parameters gives us an invalid request. 

> [!NOTE]    
> Could this be because eth_gasPrice takes no parameters in the JSON-RPC Request?

```console
$ cast rpc eth_gasPrice --raw {"method":"eth_gasPrice","params":[]}
Error:
(code: -32600, message: Invalid request, data: None)
```

> [!WARNING]
> Even the full JSON-RPC array of params fails, `{"method":"eth_gasPrice","params":[],"id":1,"jsonrpc":"2.0"}`   
~~~console
$ cast rpc eth_gasPrice --raw {"method": "eth_gasPrice", "params": []}
2024-03-02 16:24:20.514 cast[10603:202241] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon or value in dictionary on line 1. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolonOrValue to debug.
2024-03-02 16:24:20.514 cast[10603:202241] CFPropertyListCreateFromXMLData(): Old-style plist parser: missing semicolon or value in dictionary on line 1. Parsing will be abandoned. Break on _CFPropertyListMissingSemicolonOrValue to debug.
Error:
(code: -32600, message: Invalid request, data: None)
~~~

What I expect:

> [!TIP]
> Running Anvil $ETH_RPC_URL=http://127.0.0.1:8545
```console
$ curl $ETH_RPC_URL   -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_gasPrice","params":[],"id":1,"jsonrpc":"2.0"}'
{"jsonrpc":"2.0","id":1,"result":"0x53ca419d"
```

**Comment by fenghaojiang** [comment]
This isn't how it should use cast rpc. It should be: 

```shell
cast rpc eth_gasPrice --raw '[]' --rpc-url=https://rpc.ankr.com/eth
```

**Comment by grandizzy** [comment]
works properly if passed as in comment above, https://github.com/foundry-rs/foundry/issues/7297#issuecomment-1976393546 , please reopen if you still have issues with the raw flag. thank you!
