### ISSUE TITLE
dapp build parity

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#73]
Currently `dapp build` dumps `Name -> CompiledContract` to `dapp.sol.json`, essentially the core output of `ethers::Solc::build`

whereas the OG's output is `{ contracts: { "path": {"name: {"abi": [..], "evm": {..}, "metadata" }} }}`

To get the same out, probably some changes are needed for ethers as well

**Comment by gakonst** [comment]
Yeah that's flagged [here](https://github.com/gakonst/dapptools-rs/blob/434b49d982670037bc0bb725006c693c44f8900b/solc/src/lib.rs#L51) as well..Need to make Solc emit the full file path, whereas [now it just emits the contract name](https://github.com/gakonst/ethers-rs/blob/master/ethers-core/src/utils/solc.rs#L161-L210)
