### ISSUE TITLE
Cast gives ambiguous error on invalid RPC connection

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#7300]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

cast 0.2.0 (de33b6a 2024-03-02T00:15:56.318147000Z)

### What command(s) is the bug in?

cast run, cast tx

### Operating System

macOS (Apple Silicon)

### Describe the bug

When using an invalid Infura API Key, Cast gives this ambiguous error message:

```console
$ cast run -d 0xc46124238fce86f4cbe6db34723672752d1eda1a5d8491f48ba94998b0fa3573
Error:
tx not found: 0xc46124238fce86f4cbe6db34723672752d1eda1a5d8491f48ba94998b0fa3573

Context:
- Error #0: Deserialization error: expected value at line 1 column 1
- Error #1: expected value at line 1 column 1
```

However, when running `cast tx` We get the much more helpful error message:

```console
$ cast tx 0xc46124238fce86f4cbe6db34723672752d1eda1a5d8491f48ba94998b0fa3573
Error:
Deserialization Error: expected value at line 1 column 1. Response: invalid project id
```

Having the second error message would be more helpful and consistent.

**Comment by yash-atreya** [comment]
This maybe due to `cast run` using alloy vs `cast tx` using ethers. cc @DaniPopes @mattsse?

**Comment by zerosnacks** [comment]
After migrating from Ethers to Alloy this now yields:

```
cast tx 0xc46124238fce86f4cbe6db34723672752d1eda1a5d8491f48ba94998b0fa3573 --rpc-url <INVALID_KEY>

Error: 
HTTP error 401 with body: invalid project id


Context:
- HTTP error 401 with body: invalid project id
```

```
cast run -d 0xc46124238fce86f4cbe6db34723672752d1eda1a5d8491f48ba94998b0fa3573 --rpc-url <INVALID_KEY>

Error: 
tx not found: 0xc46124238fce86f4cbe6db34723672752d1eda1a5d8491f48ba94998b0fa3573

Context:
- Error #0: HTTP error 401 with body: invalid project id

- Error #1: HTTP error 401 with body: invalid project id
```

Marking as resolved
