### ISSUE TITLE
Invariant BSC fork test fails: "fuzz: failed to inspect: Database error: failed to get account for 0x0000000000000000000000000000000000001d2F: Deserialization error: EOF while parsing a value at line 1 column 0"

### ISSUE THREAD

**Issue by arynyestos** [foundry-rs/foundry#7308]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (3df3e0c 2024-03-04T00:16:13.254227572Z)

### What command(s) is the bug in?

forge test --mt invariant --fork-url $BSC_RPC_URL

### Operating System

Windows

### Describe the bug

When trying to run an invariant fork test on BSC I get "fuzz: failed to inspect: Database error: failed to get account for 0x00000000000000000000000000000000000004cB: Deserialization error: EOF while parsing a value at line 1 column 0":
![image](https://github.com/foundry-rs/foundry/assets/33223441/f679a6f6-3565-4ce6-b9cb-ada934e9c426)
![image](https://github.com/foundry-rs/foundry/assets/33223441/9e634348-1b7f-41f1-89aa-76c24669a6f5)

However, unit tests do work alright. It says "This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry" so here I am :-) I didn't find any responses to this on the forum.

Thanks for any help provided.

**Comment by DaniPopes** [comment]
Relevant line https://github.com/foundry-rs/foundry/blob/c9ae920ae3e215a02e77384d1fc0b2eb4a5d0d96/crates/evm/evm/src/executors/invariant/mod.rs#L219

We should get rid of unwrap and expect calls when calling the evm because it can still fail when forking. cc @grandizzy
