### ISSUE TITLE
In-line test configuration not respected

### ISSUE THREAD

**Issue by shuhuiluo** [foundry-rs/foundry#7310]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (3df3e0c 2024-03-04T00:19:46.775990000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

`forge test` no longer respects [In-line test configuration](https://book.getfoundry.sh/reference/config/inline-test-config).

To replicate, simply `forge init` a new `Counter` project. Add an in-line fuzz runs config to `testFuzz_SetNumber`:
```Solidity
    /// forge-config: default.fuzz.runs = 100
    function testFuzz_SetNumber(uint256 x) public {
        counter.setNumber(x);
        assertEq(counter.number(), x);
    }
```
Run `forge test`. Output:
```
Ran 2 tests for test/Counter.t.sol:CounterTest
[PASS] testFuzz_SetNumber(uint256) (runs: 256, μ: 27787, ~: 28409)
[PASS] test_Increment() (gas: 28379)
Suite result: ok. 2 passed; 0 failed; 0 skipped; finished in 8.41ms (8.13ms CPU time)
```

**Comment by grandizzy** [comment]
the Solc JSON ASTs are not included anymore for test (see https://github.com/foundry-rs/foundry/pull/7197) so inline config cannot be applied, works OK if you run `forge test --ast` but I think this should be on by default for tests too @mattsse @DaniPopes ?
