### ISSUE TITLE
Delete does'nt work great with chisel mappings

### ISSUE THREAD

**Issue by YourGuyD3v** [foundry-rs/foundry#7318]
### Component

Chisel

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (2097194 2023-06-23T00:10:47.525915714Z)

### Operating System

Linux

### Describe the bug

chisel output:

```javascript
➜ mapping(address => address) public token2token;
➜ token2token[address(1)] = address(2);
➜ address(2)
Type: address
└ Data: 0x0000000000000000000000000000000000000002
➜ delete token2token[address(1)];
➜ address(2)
Type: address
└ Data: 0x0000000000000000000000000000000000000002
➜ 
```
Run this on Remix and the mapping will be deleted:
```javascript
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.23;

contract MappingTest {

    mapping(address => address) public token2token;

    function setToken(address token, address token2) public {
        token2token[token] = token2;
    }

     function remove(address token) public {
        delete token2token[token];
    }

    function get(address token) public view returns (address) {
        return token2token[token];
    }
}
```

**Comment by IzuMan0x** [comment]
I am having the same issue: 
### Foundry Version
`forge 0.2.0 (3dfa43b 2024-03-05T00:16:33.810560000Z)`

`chisel` does not correctly delete mappings.

**Comment by JayeshShukla** [comment]
@YourGuyD3v the code provided by you behaves exactly how it should !

why would `delete token2token[address(1)];` this line have any impact on `address(2)` ?
`address(2)` is always going to print the below output :

```javascript
address(2)
Type: address
└ Data: 0x0000000000000000000000000000000000000002
```

**Comment by dhanesh24g** [comment]
Hi @JayeshShukla,
Thanks for advising the Chisel statement (By adding ; to it).
The recommendation is working fine.

**Comment by zerosnacks** [comment]
Marking as `duplicate` of https://github.com/foundry-rs/foundry/issues/7193
