### ISSUE TITLE
`forge script` should use sender address of the provided keystore

### ISSUE THREAD

**Issue by Sabnock01** [foundry-rs/foundry#7320]
### Component

Forge

### Describe the feature you would like

When running `forge script`, one should not have to use the `--sender` flag if the `--account` flag is provided as it is redundant. 

### Additional context

Of note is the Foundry keystores do not contain the address as part of their JSON object. This is contrary to keystores generated from tools such as `geth account` and `keythereum`. 

Is there a particular reason for this and would this be the fix necessary to make?

**Comment by klkvr** [comment]
You should be able to run scripts without providing `--sender` flag if `--account` is present, this was addressed in #7141.

**Comment by Sabnock01** [comment]
> You should be able to run scripts without providing `--sender` flag if `--account` is present, this was addressed in #7141.

Excellent! Didn't know this was solved already! Will close issue.

Still curious about the reason why Foundry keystores don't contain the address field though.

**Comment by klkvr** [comment]
@Sabnock01 keystore support is enabled through ethers-rs (and partially through alloy now) which uses [eth_keystore](https://github.com/roynalnaruto/eth-keystore-rs/tree/master) which has address field under geth-compat feature flag (https://github.com/roynalnaruto/eth-keystore-rs/blob/master/src/keystore.rs#L13)

So it shouldn't be hard to enable now, but would require some work for correct processing of existing keystores users might have created. Probably, we should simply populate "address" field on a first read of such file.
