### ISSUE TITLE
bug: `forge script` periodically forgets remappings

### ISSUE THREAD

**Issue by 0xhank** [foundry-rs/foundry#7330]
I'm seeing an issue where I run a script that typically works but every so often it forgets the remappings during compilation and fails. Case in point:

<img width="563" alt="image" src="https://github.com/foundry-rs/forge-std/assets/71292860/02507688-d682-4cb5-b18b-b70c8350fb3a">

To resolve, I change the rpcUrl flag to something invalid, get an invalid RPC error message, and after unmodifying the RPC, compilation is successful.

**Comment by zerosnacks** [comment]
When you running the script are you (re)generating the code `MapStoredColonies.sol` (considering it is in a `codegen` directory) or is it a static file?

**Comment by 0xhank** [comment]
It's static, the only file getting compiled is the script

**Comment by zerosnacks** [comment]
Hi @0xhank, I don't see how the compilation step and changing the RPC could be related.

For now I'm marking this ticket as `can't repro`, feel free to re-open with additional details and preferably a minimal reproduction example as it is likely dependent on your specific context.
