### ISSUE TITLE
Pin alloy deps to a specific hash

### ISSUE THREAD

**Issue by mattyg** [foundry-rs/foundry#7337]
### Component

Other (please describe)

### Describe the feature you would like

In the workspace Cargo.toml file you're depending on a bunch of alloy crates via its git repo, but not pinning any specific commit hash. 

My crate depends on foundry, so it grabs the latest alloy commit hash from that git repo, which causes foundry to fail to build, since it *actually* depends on older commit hashes (the ones in its Cargo.lock).

Can you please update the foundry Cargo.toml to pin the alloy deps to the actual commit hash?

**Comment by zerosnacks** [comment]
Thanks for raising this, this will be resolved soon when https://github.com/foundry-rs/foundry/pull/7125 is merged.
