### ISSUE TITLE
bug: `invalid sender` error when using Trezor with `forge script` with `--broadcast` flag

### ISSUE THREAD

**Issue by klkvr** [foundry-rs/foundry#7342]
#7141 probably introduced some regeression for trezor signers: https://t.me/foundry_support/51031

"Invalid sender" error when using Trezor with forge script and the --broadcast flag.

Command: `forge script script/myscript --rpc-url $MAINNET_RPC_URL --mnemonic-derivation-paths "myderivation" --trezor --broadcast -vvvv  --sender myaddr --sig "something"`

- Works without the --broadcast flag.
- Issue arises with Trezor and the --broadcast flag.

**Comment by zerosnacks** [comment]
Possibly related fix: https://github.com/trezor/trezor-firmware/pull/3952#issuecomment-2225060273 just got released, highlighted in https://github.com/foundry-rs/foundry/issues/7660#issuecomment-2169205625

Requires updating Alloy to `0.1.4`: https://github.com/alloy-rs/alloy/blob/bec60984fc3097e91bbfbe59892a9e3ab75d03ff/crates/signer-trezor/Cargo.toml

**Comment by zerosnacks** [comment]
Related PR: https://github.com/alloy-rs/alloy/pull/1045 including possible fix: https://github.com/trezor/trezor-firmware/pull/3952#issuecomment-2225060273

**Comment by zerosnacks** [comment]
Marking as resolved by https://github.com/alloy-rs/alloy/releases/tag/v0.2.0 and Foundry having been bumped to 0.2.0 in https://github.com/foundry-rs/foundry/pull/8305/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542
