### ISSUE TITLE
`forge test` doesn't support absolute path

### ISSUE THREAD

**Issue by zhiqiangxu** [foundry-rs/foundry#7350]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (7922fd5 2024-02-05T00:19:20.258041000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Intel)

### Describe the bug

`forge test --match-path  absolute_path` will report `No tests match the provided pattern`, only relative path works.

` --match-path` should work for both absolute path and relative path.

**Comment by matthewliu10** [comment]
I'll give this issue a try
