### ISSUE TITLE
Unrecognized chain ID '0x1e76'

### ISSUE THREAD

**Issue by adeamos** [foundry-rs/foundry#7354]
While using metamask, I couldn't participate in Openex testnet because of unrecognized chain ID '0x1e76'error

**Comment by zerosnacks** [comment]
@adeamos this is related indirectly to Foundry as we rely on `alloy-chains`

I would recommend reporting this in https://github.com/alloy-rs/chains as it does seem to be missing in https://github.com/alloy-rs/chains/blob/main/assets/chains.json (0x1e76 = 7798).
