### ISSUE TITLE
cast fails when used with a lib using `evm_version = "paris"`

### ISSUE THREAD

**Issue by kyhyco** [foundry-rs/foundry#7357]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9f6bb3b 2024-03-10T00:17:56.235891000Z)

### What command(s) is the bug in?

cast chain-id

### Operating System

macOS (Apple Silicon)

### Describe the bug

Hello team!

How to reproduce
```
anvil

// on a separate terminal pane
forge init hello_foundry

cd hello_foundry

forge install vectorized/solady

cast chain-id
```

I expect to see `31337` but instead get:
```sh
The application panicked (crashed).
Message:  failed to extract foundry config:
foundry config error: Unknown evm version: paris for setting `evm_version`

Location: config/src/lib.rs:448
```

solady sets `evm_version = paris` in its [foundry.toml](https://github.com/Vectorized/solady/blob/main/foundry.toml#L8)

Unclear to me if this is an issue with cast or solady. Would appreciate any insight! Thank you!

Reference - https://github.com/Vectorized/solady/issues/430

**Comment by zerosnacks** [comment]
Unable to reproduce the issue on my end with the given instructions.

```
forge 0.2.0 (9f6bb3b 2024-03-11T00:16:41.198026000Z)
cast 0.2.0 (9f6bb3b 2024-03-11T00:16:41.190155000Z)
anvil 0.2.0 (9f6bb3b 2024-03-11T00:16:41.186304000Z)
```

Not sure if I understand the reproduction steps correctly as `cast chain-id` simply runs against `http://localhost:8545/` (Anvil instance), this is unrelated to the `hello_foundry` repo or adding Solady.

I've also tried running the Anvil instance from the `hello_foundry` repo but this made no change and works correctly.

**Comment by DaniPopes** [comment]
What is your `cast --version`? It might not be the same as `forge`

**Comment by kyhyco** [comment]
```
forge 0.2.0 (9f6bb3b 2024-03-10T00:17:56.235891000Z)
cast 0.2.0 (ed9298d 2023-03-09T05:36:14.53538Z)
anvil 0.2.0 (9f6bb3b 2024-03-10T00:17:56.195647000Z)
```

Oh good call out. Looks like my cast is behind.

**Comment by kyhyco** [comment]
Using same version of `forge` and `cast` resolves the issue. Thank you so much!
