### ISSUE TITLE
bug(`anvil`): `anvil --init` from `genesis.json` generates unexpected genesis block hash 

### ISSUE THREAD

**Issue by joshklop** [foundry-rs/foundry#7366]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

0.2.0

### What command(s) is the bug in?

anvil --init genesis.json

### Operating System

Linux

### Describe the bug

(this may not be a bug, it's more of a question)

I'm trying to set up a devnet with anvil and Optimism's op-node. However, anvil generates a genesis block hash that the `op-node` does not expect.

I have tried variations of `anvil --init`, but they all generate the same genesis block hash:

- `anvil --init genesis.json`
- `anvil --init genesis.json -a 1 --no-create2`
- `anvil --init genesis.json -a 0 --no-create2` 

When I use geth's `core.Genesis` type, I can generate the expected block hash:
```go
package main

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/ethereum/go-ethereum/core"
)

func main() {
	genesisBytes, err := os.ReadFile("genesis.json")
	if err != nil {
		panic(err)
	}
	g := new(core.Genesis)
	if err := json.Unmarshal(genesisBytes, &g); err != nil {
		panic(err)
	}
	fmt.Println(g.ToBlock().Hash())
}
```

I assume anvil is modifying the genesis state somewhere. If so, is it possible to override that behavior?

**Comment by joshklop** [comment]
Here is an example genesis file. The expected block hash is `0x37183ca790ba04084b79600e546732fcdd8553db8775ed9fb14f8f380e8f348d`

[genesis-l1.json](https://github.com/foundry-rs/foundry/files/14561717/genesis-l1.json)

**Comment by EdwardJES** [comment]
I'm happy to take this one.

**Comment by grandizzy** [comment]
@joshklop could you please check if that's still valid, there were some changes in the area that might be fixed the problem. thank you!

**Comment by grandizzy** [comment]
@joshklop we're optimistically closing this one, please reopen if still an issue for you. thanks!
