### ISSUE TITLE
deploy contract on zetachain failed

### ISSUE THREAD

**Issue by Zeb-blockchain** [foundry-rs/foundry#7372]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (7545c7a 2024-03-12T00:17:55.654014000Z)

### What command(s) is the bug in?

forge script src/scripts/ZetaOfficialBridgeAdapter.s.sol:ZetaOfficialBridgeAdapter -vvvv --broadcast -g 500

### Operating System

macOS (Apple Silicon)

### Describe the bug

Here is part of script:

```
    function run() public {
        deploy();
    }
    function deploy() public{
        // deploy on zeta
        vm.createSelectFork(vm.envString("ZETACHAIN_RPC_URL"));
        vm.startBroadcast(deployer);

        console2.log("block.chainID", block.chainid);
        require(block.chainid == 7000 , "must be ZETA chain");

        ZetaChainAdaptorForZeta adapter = new ZetaChainAdaptorForZeta(address(xBridge), _routerList, feeto, _zetaOfficalBridge, ETH_ETH, BNB_BSC);
        console2.log("ZetaOfficialBridgeAdapter deployed on ZETA chain", address(adapter));

        vm.stopBroadcast();
    }
```
    
   It can pass the simulation, but the final error is as follows：
```
==========================

Chain 7000

Estimated gas price: 20 gwei

Estimated total gas used for script: 5727215

Estimated amount required: 0.1145443 ETH

==========================
##
Sending transactions [0 - 0].
⠁ [00:00:02] [######################################################################################################] 1/1 txes (0.0s)##
Waiting for receipts.

Transactions saved to: .../broadcast/ZetaOfficialBridgeAdapter.s.sol/7000/run-latest.json

Sensitive values saved to: .../cache/ZetaOfficialBridgeAdapter.s.sol/7000/run-latest.json

Error: 
Transaction Failure:0x.....(I omitted the actual tx)
```

I raised the gaslimit 50 times, but it's still the same mistake。This contract can be deployed normally using the hardhat framework.

**Comment by klkvr** [comment]
if transaction landed on-chain and reverted, the tx hash would be helpful here

**Comment by Zeb-blockchain** [comment]
> if transaction landed on-chain and reverted, the tx hash would be helpful here

Here is one of transactions.
https://zetachain.blockscout.com/tx/0x012a898d6b21bea261a65f426f90af90591e40e4b5eef60d130d8f0fcbf5f02f

**Comment by yash-atreya** [comment]
> > if transaction landed on-chain and reverted, the tx hash would be helpful here
> 
> 
> 
> Here is one of transactions.
> 
> https://zetachain.blockscout.com/tx/0x012a898d6b21bea261a65f426f90af90591e40e4b5eef60d130d8f0fcbf5f02f

Zetachain doesn't support the PUSH0 opcode. View the [call trace](https://zetachain.blockscout.com/tx/0x012a898d6b21bea261a65f426f90af90591e40e4b5eef60d130d8f0fcbf5f02f?tab=raw_trace) of the tx.

You need to compile with the EVM version that is supported by the chain you're deploying to.
