### ISSUE TITLE
Bug: `memory allocation of 9223372036854775807 bytes failed`

### ISSUE THREAD

**Issue by pcaversaccio** [foundry-rs/foundry#7378]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

`forge 0.2.0 (7545c7a 2024-03-12T00:16:54.294788023Z)`

### What command(s) is the bug in?

`forge test`

### Operating System

Linux

### Describe the bug

See CI run [here](https://github.com/pcaversaccio/createx/actions/runs/8251324345/job/22568096906?pr=90#step:16:5066):

```sh
memory allocation of 9223372036854775807 bytes failed
Aborted (core dumped)
 ELIFECYCLE  Test failed. See above for more details.
Error: Process completed with exit code 1.
```

I haven't changed the tests for 3 months, except for that PR https://github.com/pcaversaccio/createx/pull/90 which raises now with that error.

**Comment by pcaversaccio** [comment]
> hmm, I'm unable to reproduce this locally.
> 
> couldn't locate where this overflow before allocating might have happened.
> 
> could you perhaps rerun with `RUST_LOG=trace`

I can't reproduce this error locally neither. I only face it in the CI, unfortunately. 3 hrs ago I pushed a commit that passed the tests (cf. https://github.com/pcaversaccio/createx/commit/5811b5a3774aa052f6b9ae9bbe05d205cb8b8f7c). So there happened something in between...

**Comment by pcaversaccio** [comment]
Let me try locally using `RUST_LOG=trace` and with the same CI run params for the fuzz and invariant tests. Maybe I can reproduce like that...

**Comment by onbjerg** [comment]
Can you try rerunning the CI? I'm wondering if this is maybe a fuzz or invariant test allocating a crazy big type?

**Comment by onbjerg** [comment]
Looks to have completed successfully (no core dump), albeit with failing tests. Am I reading correctly?

**Comment by pcaversaccio** [comment]
> Looks to have completed successfully (no core dump), albeit with failing tests. Am I reading correctly?

It looks like this indeed but maybe it just didn't get there due to an early revert due to the failing test (which has never failed until now; maybe time for an additional `assume` lol). But let me rerun it, because it might be simply bad luck (again)...

**Comment by onbjerg** [comment]
What would you identify as the largest fuzz/invariant tests in the code base? Might be worth trying to narrow down if it's one of the generators

We should probably log the fuzz seed so this is more easily reproducible

**Comment by pcaversaccio** [comment]
> What would you identify as the largest fuzz/invariant tests in the code base? Might be worth trying to narrow down if it's one of the generators
> 
> We should probably log the fuzz seed so this is more easily reproducible

https://github.com/pcaversaccio/createx/blob/main/foundry.toml#L21

`10_000` for fuzz and `5_000` for invariant tests

**Comment by pcaversaccio** [comment]
> > What would you identify as the largest fuzz/invariant tests in the code base? Might be worth trying to narrow down if it's one of the generators
> > We should probably log the fuzz seed so this is more easily reproducible
> 
> https://github.com/pcaversaccio/createx/blob/main/foundry.toml#L21
> 
> `10_000` for fuzz and `5_000` for invariant tests

I tried reproduce the bug locally using these params but no luck. Maybe it's just a crazy weird edge case tbh, idk. If you think it's too hard to figure out the issue with the limited data we have, I can close it and reopen again later if I face it again? Thoughts?

**Comment by mattsse** [comment]
sg!
thanks

**Comment by grandizzy** [comment]
> 
> We should probably log the fuzz seed so this is more easily reproducible

No need since we have https://github.com/foundry-rs/foundry/pull/7336 :) just make sure you save the failure file somewhere in CI and download locally to replay

**Comment by onbjerg** [comment]
@grandizzy does this work even if forge ooms?

**Comment by grandizzy** [comment]
> @grandizzy does this work even if forge ooms?

obviously it doesn't :D nm

**Comment by pcaversaccio** [comment]
Just faced another overflow bug here: https://github.com/foundry-rs/foundry/issues/7394
