### ISSUE TITLE
Support SocketAddress as --rpc-url input

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#7381]
### Component

Forge, Anvil

### Describe the feature you would like

currently we're failing "anvil --port 6969 --fork-url [IP]:8545" with a bad error

```
thread 'main' panicked at /home/runner/work/foundry/foundry/crates/anvil/src/config.rs:979:57:
Failed to get fork block number: Transport(Custom(TransportError(Transport(Custom(Os { code: 2, kind: NotFound, message: "No such file or directory" })))))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This is because this will be interpreted as file:

https://github.com/foundry-rs/foundry/blob/eef87de35375311f134fb4261c18455ced8022a5/crates/common/src/provider/alloy.rs#L93-L93

## TODO

try parsing as SocketAddress, if the URL is a socketaddr, prefix it with http://

similar to the localhost check

https://github.com/foundry-rs/foundry/blob/eef87de35375311f134fb4261c18455ced8022a5/crates/common/src/provider/alloy.rs#L88-L89

**Comment by MuhtasimTanmoy** [comment]
Working on it

**Comment by kamuik16** [comment]
> ### Component
> Forge, Anvil
> 
> ### Describe the feature you would like
> currently we're failing "anvil --port 6969 --fork-url [IP]:8545" with a bad error
> 
> ```
> thread 'main' panicked at /home/runner/work/foundry/foundry/crates/anvil/src/config.rs:979:57:
> Failed to get fork block number: Transport(Custom(TransportError(Transport(Custom(Os { code: 2, kind: NotFound, message: "No such file or directory" })))))
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```
> 
> This is because this will be interpreted as file:
> 
> https://github.com/foundry-rs/foundry/blob/eef87de35375311f134fb4261c18455ced8022a5/crates/common/src/provider/alloy.rs#L93-L93
> 
> ## TODO
> try parsing as SocketAddress, if the URL is a socketaddr, prefix it with http://
> 
> similar to the localhost check
> 
> https://github.com/foundry-rs/foundry/blob/eef87de35375311f134fb4261c18455ced8022a5/crates/common/src/provider/alloy.rs#L88-L89
> 
> ### Additional context
> _No response_

Can I take this one?
