### ISSUE TITLE
Optimize DebugNode flatten_to

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#7386]
### Component

Forge

### Describe the feature you would like

ref #7382

This currently does a bunch of expensive clones:
https://github.com/foundry-rs/foundry/blob/b2f9346ef75810a48f776a36ad1bfb3b873c3514/crates/debugger/src/tui/builder.rs#L40-L45

https://github.com/foundry-rs/foundry/blob/b2f9346ef75810a48f776a36ad1bfb3b873c3514/crates/evm/core/src/debug.rs#L74-L87

since we're consuming the type, we can get rid of the clones by rewriting this with a stack approach

### Additional context

<img width="787" alt="image" src="https://github.com/foundry-rs/foundry/assets/19890894/5aa87a8c-8b23-4d98-a69f-cd766ac55528">

**Comment by qiweiii** [comment]
May I know how do you generate the image under Additional context

**Comment by qiweiii** [comment]
May I know how do you generate the image under Additional context

**Comment by PanGan21** [comment]
Hi @mattsse .
I am interested to pick this up. Would a `VecDeque` be a good option for our use case?

**Comment by mattsse** [comment]
> Hi @mattsse . I am interested to pick this up. Would a `VecDeque` be a good option for our use case?

yeah, I think it should be similar to 

https://github.com/paradigmxyz/evm-inspectors/blob/d7317c7fbf38d5e5df2393beee0414c987ea440a/src/tracing/builder/geth.rs#L46

**Comment by mattsse** [comment]
> Hi @mattsse . I am interested to pick this up. Would a `VecDeque` be a good option for our use case?

this is https://github.com/mstange/samply

**Comment by PanGan21** [comment]
> > Hi @mattsse . I am interested to pick this up. Would a `VecDeque` be a good option for our use case?
> 
> 
> 
> this is https://github.com/mstange/samply

I will give it a try then!

**Comment by MuhtasimTanmoy** [comment]
Would like to give it a try as well.

Does this change looks ok?

```rust
pub fn flatten_to(&self, entry: usize, out: &mut Vec<DebugNodeFlat>) {

      let mut stack = VecDeque::new();
      stack.push_back(entry);

      while let Some(entry) = stack.pop_back() {
          let node = &self.arena[entry];

          if node.steps.len() {
              out.push(node.flat());
          }

          for child in &node.children.into_iter().rev() {
              stack.push(*child);
          }
      }
 }
```

Also, what needs to be done to test it?

**Comment by PanGan21** [comment]
No problem. Let me know if I can still help with something

**Comment by MuhtasimTanmoy** [comment]
@mattsse What command should generate the profiler image from additional context? `samply record .....` ?
How to measure improvement?

As suggested by @DaniPopes how should we work on this function and try to get rid this `clone`?
```
/// Flattens this node into a [`DebugNodeFlat`].
pub fn flat(&self) -> DebugNodeFlat {
    DebugNodeFlat { address: self.address, kind: self.kind, steps: self.steps.clone() }
}
```

**Comment by lakshya-sky** [comment]
IMO we can't get rid of clones since we are passing DebugArena by ref, but somebody can correct me on this.

**Comment by DaniPopes** [comment]
You're right, we have to pass by reference due to the nested data structure. I don't think this is worth it.
