### ISSUE TITLE
bug(`forge script`): `code: -32000, message: invalid chain id, data: None` when deploying contracts on Polygon ZkEVM / Scroll using Windows

### ISSUE THREAD

**Issue by yohanelly95** [foundry-rs/foundry#7407]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (3dfa43b 2024-03-05T00:16:09.056435300Z)

### What command(s) is the bug in?

forge script 

### Operating System

Windows, MacOS

### Describe the bug

```
forge script script/Deployer.s.sol:Deployer --rpc-url $RPC_URL --optimize -vvvv --ledger --sender $DEPLOYER_ADDRESS  --hd-paths "m/44'/60'/$INDEX'/0/0" --slow --broadcast
```
Getting this error on MacOS and Windows
```
Error:
(code: -32000, message: invalid chain id, data: None)
```
Note: This issue is currently faced on Polygon zkevm and scroll mainnet chains

**Comment by yohanelly95** [comment]
cc @mattsse  on scroll mainnet we get the error 
```
Error:
(code: -32000, message: invalid sender, data: None)
```

**Comment by yohanelly95** [comment]
> simulation

this is during the broadcast step only, and after confirming the txn on a ledger

**Comment by zerosnacks** [comment]
Hi @yohanelly95 are you still experiencing this issue? There have been some significant updates to the Ledger implementation (we've since moved from `ethers-rs` to `alloy`).

**Comment by mattsse** [comment]
I think we can close this, this was pre alloy so the entire provider impl is different
