### ISSUE TITLE
`forge verify-contract` fails to verify contract, if it is in the `lib` folder

### ISSUE THREAD

**Issue by apoorvlathey** [foundry-rs/foundry#7411]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (3fa0270 2024-03-15T00:16:56.190232509Z)

### What command(s) is the bug in?

forge verify-contract

### Operating System

None

### Describe the bug

If I try to verify a contract from the `lib` folder, it reverts as follows:
```
> forge verify-contract --chain-id 5 --num-of-optimizations 800 --watch --etherscan-api-key $ETHERSCAN_API_KEY --compiler-version v0.8.15+commit.e14f2714 0xffE5d77309efd6e9391Ac14D95f2035A1e138659 lib/nftx-protocol-v3/src/custom/proxy/Create2BeaconProxy.sol:Create2BeaconProxy

Start verifying contract `0xffE5d77309efd6e9391Ac14D95f2035A1e138659` deployed on goerli
Error: 
Failed to get standard json input

Context:
- cannot resolve file at "/home/forge-verify-issue/lib/nftx-protocol-v3/src/custom/proxy/Create2BeaconProxy.sol"
```

But if I clone the `lib/nftx-protocol-v3` repo separately in this case, and then run the following, the verification succeeds as expected:
```
> forge verify-contract --chain-id 5 --num-of-optimizations 800 --watch --etherscan-api-key $ETHERSCAN_API_KEY --compiler-version v0.8.15+commit.e14f2714 0xffE5d77309efd6e9391Ac14D95f2035A1e138659 src/custom/proxy/Create2BeaconProxy.sol:Create2BeaconProxy

Start verifying contract `0xffE5d77309efd6e9391Ac14D95f2035A1e138659` deployed on goerli

Contract [src/custom/proxy/Create2BeaconProxy.sol:Create2BeaconProxy] "0xffE5d77309efd6e9391Ac14D95f2035A1e138659" is already verified. Skipping verification.
```

**Comment by TilakMaddy** [comment]
Same issue for me !

**Comment by grandizzy** [comment]
> hey
> 
> is it possible to make `forge-verify` smarter by automatically doing this?
> 
> https://gist.github.com/aviggiano/099f52fb6b243d0689e635a88128ee66

👍 will look into adding such
