### ISSUE TITLE
gas used returned by cast run doesn't match on-chain gas used amount

### ISSUE THREAD

**Issue by eshaben** [foundry-rs/foundry#7412]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (3fa0270 2024-03-15T00:16:21.040039000Z)

### What command(s) is the bug in?

cast run

### Operating System

macOS (Intel)

### Describe the bug

When running the following command, the gas used value printed at the end of the output does not match the gas used on-chain:

```
cast run 0x4e42d4c4cc45a560b45cc9d299117498678b49bb5d5997e4d355d302acfaec55 --rpc-url https://rpc.api.moonbeam.network
```

Running the above command outputs: `Gas used: 4883401`. But on the [transaction details on Moonscan](https://moonscan.io/tx/0x4e42d4c4cc45a560b45cc9d299117498678b49bb5d5997e4d355d302acfaec55), you'll see that the actual gas used was `6962784`.

I believe this may be related to [MBIP-5 on Moonbeam](https://docs.moonbeam.network/builders/get-started/eth-compare/tx-fees/#overview-of-mbip-5), where the gas required increases with the increase in chain state.

Ultimately, when using Cast, this issue makes it seem that the transaction was successful, but it actually failed.

**Comment by Lohann** [comment]
Moonbean doesn't use [REVM](https://github.com/bluealloy/revm), instead is uses [sputnik-evm](https://github.com/rust-ethereum/evm/issues), which is not ethereum compliant, so the only way to get the exact same gas cost as moonbean, is using the same evm.
- https://github.com/rust-ethereum/evm/issues/222
- https://github.com/rust-ethereum/evm/issues/225
- https://github.com/rust-ethereum/evm/issues/248
- https://github.com/rust-ethereum/evm/issues/249
