### ISSUE TITLE
Slow connection (to localhost)

### ISSUE THREAD

**Issue by drortirosh** [foundry-rs/foundry#7430]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

cast 0.2.0 (42a9d34 2024-03-18T00:21:12.549807000Z)

### What command(s) is the bug in?

cast ci

### Operating System

macOS (Apple Silicon)

### Describe the bug

I see no reason for `cast` to take ~3 times `curl` to contact localhost. This makes scripts that use `cast` for various rpc calls very sluggish. - 48ms to a TCP round-trip to local "get", compared to 15ms for "curl"

```sh
 $ time cast chain-id -r http://localhost:8545
1337

real	0m0.048s
user	0m0.020s
sys	0m0.020s
✔ /tmp
19:45 $ time curl -s -d '{"method":"eth_chainId","params":[],"id":1234,"jsonrpc":"2.0"}' -H content-type:application/json http://localhost:8545
{"jsonrpc":"2.0","id":1234,"result":"0x539"}

real	0m0.015s
user	0m0.003s
sys	0m0.008s
✔ /tmp
19:45 $ cast --version
cast 0.2.0 (42a9d34 2024-03-18T00:21:12.549807000Z)
```

**Comment by mattsse** [comment]
are you executing this in a foundry project by any chance?

this is likely because we're trying to load foundry.toml

I believe we added this so that aliases work as input args, although I think we should skip that entirely if the URL arg is actually an URL

**Comment by DaniPopes** [comment]
cc https://github.com/foundry-rs/foundry/issues/6204 https://github.com/foundry-rs/foundry/pull/6350, will do the same on the new reqwest clients
