### ISSUE TITLE
Bug: Must upgrade Forge (re: foundry) in order to use latest solc

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#7439]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### Operating System

macOS (Apple Silicon)

### Describe the bug

Forge requires to be updated in order to use latest SOLC versions, e.g. 0.8.25 must use a release after the release of 0.8.25.

Ideally, Forge would be able to use solc latest versions regardless of when a release of forge was made.

**Comment by DaniPopes** [comment]
I believe this is only true on macos when solc didn't ship binaries so we had our own solutions. cc @mattsse

**Comment by onbjerg** [comment]
this is because there are some binaries that solc did not (still don't?) provide, e.g. m1/m2/m3 builds, so we had to build our own

**Comment by sambacha** [comment]
> this is because there are some binaries that solc did not (still don't?) provide, e.g. m1/m2/m3 builds, so we had to build our own

solc now by default ships universal macOS builds (as of 0.8.24), so they should work on both intel and arm chipsets using one binary going forward 

see also
https://github.com/alloy-rs/solc-builds/issues/13

ref
https://github.com/ethereum/solidity/issues/14813

**Comment by sambacha** [comment]
I think this is also possibly a related issue: https://github.com/foundry-rs/foundry/issues/6925#issuecomment-2006567811 as I have observed the same behaviour

**Comment by mattsse** [comment]
sorry I have no idea what the issue here is?

you should be able to use whatever solc you downloaded manually if you don't want it managed through forge

**Comment by zerosnacks** [comment]
Marking as `resolved`, this is only the case for non-universal macOS builds pre-`0.8.24`

This is handled correctly in https://github.com/alloy-rs/svm-rs/blob/de5bd77c5af7b5188dfe0d00675cef72dbdbd145/crates/svm-rs/src/releases.rs#L43
