### ISSUE TITLE
Bug: Forge relies on outdated alloy-rs solc `list.json` for solc binary information 

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#7441]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (0026488 2024-03-19T00:20:40.934617000Z)

### What command(s) is the bug in?

forge build

### Operating System

macOS (Apple Silicon)

### Describe the bug

Forge is fetching the following solc binary information from alloy-rs, however these list files do not contain the latest solc binary, 0.8.25

```
https://raw.githubusercontent.com/alloy-rs/solc-builds/e4b80d33bc4d015b2fc3583e217fbf248b2014e1/macosx/aarch64/list.json
https://github.com/alloy-rs/solc-builds/raw/e4b80d33bc4d015b2fc3583e217fbf248b2014e1/macosx/aarch64/list.json
```

This sort of overlaps with https://github.com/foundry-rs/foundry/issues/7440

**Comment by mattsse** [comment]
could you please be more specific,
is the issue redundant call or is 0.8.25 not working?

> however these list files do not contain the latest solc binary, 0.8.25

yes this is correct because 0.8.25 is now a universal binary.
I think we can get rid of the extra call by checking if universal binaries are available, starting with 0.8.24 I believe

**Comment by zerosnacks** [comment]
Resolved by https://github.com/alloy-rs/svm-rs/blob/de5bd77c5af7b5188dfe0d00675cef72dbdbd145/crates/svm-rs/src/releases.rs#L137-L170 added in https://github.com/alloy-rs/svm-rs/pull/118

**Comment by sambacha** [comment]
> Resolved by https://github.com/alloy-rs/svm-rs/blob/de5bd77c5af7b5188dfe0d00675cef72dbdbd145/crates/svm-rs/src/releases.rs#L137-L170 added in [alloy-rs/svm-rs#118](https://github.com/alloy-rs/svm-rs/pull/118)

Thanks, you da real MVP mr snacks
