### ISSUE TITLE
anvil test migration to alloy

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#7449]
### Component

Anvil

### Describe the feature you would like

anvil e2e tests are using ethers-providers, which can be fully migrated to foundry now:

https://github.com/foundry-rs/foundry/blob/0026488754512acf0fd902a0d2c90cf8a09367b0/crates/anvil/tests/it/main.rs#L1-L1

these can be done iteratively, one file at a time so that we could work in tandem on this

the setup should be very similar to alloy-examples

cc @zerosnacks @yash-atreya 

~~likely blocked until @klkvr cast migration pr lands that updates alloy~~

Unblocked

**Comment by zerosnacks** [comment]
Likely unblocked now that https://github.com/foundry-rs/foundry/pull/7425/files has been merged

**Comment by klkvr** [comment]
@zerosnacks #7425 was merged in #7106 branch, this PR is blocked on it currently

**Comment by zerosnacks** [comment]
Unblocked by merged https://github.com/foundry-rs/foundry/pull/7106

Now ready to pick up

cc @yash-atreya
