### ISSUE TITLE
INVALID DATA

### ISSUE THREAD

**Issue by DMG-01** [foundry-rs/foundry#7455]
when trying to write test for my project none of the test works, and it throws an error that says invalid data, i thought the issue was with my code or something but after creating a new folder and i ran `forge init` the default foundry code throws the same error when i try to  run test

**Comment by onbjerg** [comment]
Please provide the exact error message and some information about your system

**Comment by DMG-01** [comment]
![Screenshot (132)](https://github.com/foundry-rs/foundry/assets/110745735/f43de364-a966-42aa-9c9a-21b0bc9700ca)

**Comment by DMG-01** [comment]
Running 2 tests for test/test.t.sol:MainTest
[FAIL. Reason: Invalid data] testDeployerIsFirstOwner() (gas: 13621)
[FAIL. Reason: Invalid data] testNumberIncrease() (gas: 16649)
Test result: FAILED. 0 passed; 2 failed; finished in 43.20ms

Failing tests:
Encountered 2 failing tests in test/test.t.sol:MainTest
[FAIL. Reason: Invalid data] testDeployerIsFirstOwner() (gas: 13621)
[FAIL. Reason: Invalid data] testNumberIncrease() (gas: 16649)

Encountered a total of 2 failing tests, 0 tests succeeded
root@DVYNE-ETH-01:~/chancellor-Cup# 
this is the error it throws

**Comment by SFzxc** [comment]
I got same error too, when using `assertEq` with version `forge 0.2.0 (08d09b6 2023-06-03T14:23:57.564996000Z)`

**Comment by onbjerg** [comment]
Please provide something we can run to reproduce, a screenshot doesn't provide enough info. For example, a repository and a command to run, or steps to arrive at this state ourselves

**Comment by DMG-01** [comment]
i didnt use a repo, just running forge init and forge test throws that error

**Comment by liamcf44** [comment]
Might have just been my machine but running `foundryup` and updating the packages worked for me when I was hitting this issue

**Comment by DMG-01** [comment]
i'd try that, thank you

**Comment by grkmyvz** [comment]
I was use to foundry. I didnt have this error before. Me too take this error now. I created new folder and I run `forge test` at default folder. I am taking this error. I tried `foundryup` and other updates command. But i didnt solve.

![Screenshot at Apr 07 01-03-06](https://github.com/foundry-rs/foundry/assets/85451018/bb0cc22c-2a29-4f98-8407-da7dac98faf1)

**Comment by Evalir** [comment]
we really can't take any action on this issue unless we get a repro—please try `forge clean` and test again @grkmyvz ?

**Comment by grkmyvz** [comment]
I tried many combinations. It doesnt work at all. @Evalir 

![Screenshot at Apr 08 14-04-41](https://github.com/foundry-rs/foundry/assets/85451018/7f6dc554-a2b4-43de-8fbc-57794eab4d73)

**Comment by Evalir** [comment]
ok— @grkmyvz could you give us more info about your environment? just like when opening a new issue please

**Comment by grkmyvz** [comment]
I solved this problem. I removed Foundry and Rust, and after that, I installed them again. It's running now.

**Comment by Evalir** [comment]
oh @grkmyvz glad to hear. if you run into this again please feel free to ping on this issue again.

@DMG-01 could you provide more info about your env & a repro? else we'll close as fixed.

**Comment by DMG-01** [comment]
yeah all i did was run foundryup and it worked but then about 50 of the test that previously passed  failed
