### ISSUE TITLE
code: -32003, message: Insufficient funds for gas * price + value, data: None

### ISSUE THREAD

**Issue by whiskyfrenzy** [foundry-rs/foundry#7456]
### Component

Forge, Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (1a4960d 2024-03-20T00:19:54.542150000Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

Running the below `forge script` command:
`forge script V2Test.s.sol --sig 'run(bytes memory)' $input --sender $SENDER --skip-simulation --rpc-url http://127.0.0.1:1234 --broadcast --unlocked --legacy --with-gas-price 35243602672 --json --priority-gas-price 1099305329 -vvv`

Where:
`$input` is a EIP1559Request's data field
`$SENDER` is 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 (One of the accounts provided from running anvil fork)
The RPC URL comes from my anvil fork command, basically forking the mainnet and listens on port 1234.

Will give me the following:
```
{"logs":[],"gas_used":36453,"returns":{}}

SKIPPING ON CHAIN SIMULATION.
Sending transactions [0 - 0].

Transactions saved to: [TRUNCATED]/run-latest.json

Sensitive values saved to: [TRUNCATED]/run-latest.json

Error: 
Failed to send transaction

Context:
Error #0: Failed to estimate gas for tx: 0xa6588218af3b69925349825ca9eaa3fb6bf07cabf8c3d5bb1d7c21112e9ea5c2
Error #1: (code: -32003, message: Insufficient funds for gas * price + value, data: None)
```

What I am not understanding is, the error complains about having insufficient funds and the JSON log output states gas_used as 36453, but anvil forked accounts have 10000 ETH on creation, and I can verify it having balance still when running:

$ cast balance 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 --rpc-url http://127.0.0.1:1234
9999949831288618906569

Running that forge script command without the `--broadcast` flag works with no errors; however, I want to broadcast my transaction on my forked chain, and then rerun the `cast balance` command above and see whether my balance goes up or down, as essentially what that transaction does is swapping a variety of tokens.

I'm sure I'm just missing something really obvious, but I have tried asking on Telegram and stackoverflow. Any help from devs would be very much appreciated. :D

**Comment by mattsse** [comment]
hmm, that's odd

could you please share the logs you get if you start anvil with `RUST_LOG=node,api,rpc,backend=trace anvil ...`

**Comment by whiskyfrenzy** [comment]
Sure thing @klkvr 
This is cache - [run-latest.json](https://github.com/foundry-rs/foundry/files/14667001/run-latest.json)
This is broadcast- [run-latest.json](https://github.com/foundry-rs/foundry/files/14667004/run-latest.json)

**Comment by klkvr** [comment]
> This is cache - [run-latest.json](https://github.com/foundry-rs/foundry/files/14667001/run-latest.json)
> This is broadcast- [run-latest.json](https://github.com/foundry-rs/foundry/files/14667004/run-latest.json)

Links are not working for me for some reason :/

**Comment by whiskyfrenzy** [comment]
> this looks odd, but it's definitely coming from rpc, this looks more like a number than an address
> 
> could you also share the forge logs
> 
> `RUST_LOG=forge,foundry=trace`
> 
> @klkvr I wonder if this has something to do with script?

This actually doesn't give me any output, but if I use `RUST_LOG=forge,node,api,rpc,foundry=trace,backend=trace` instead, i do get output, but its the same as the previous logs.

**Comment by mattsse** [comment]
@klkvr looks like 3078616330393734626563333961313765333662 is the prefix of the "privateKey" cheatcode identifier:

https://github.com/foundry-rs/foundry/blob/0026488754512acf0fd902a0d2c90cf8a09367b0/testdata/out/Derive.t.sol/DeriveTest.json#L1-L1

@whiskyfrenzy are you using that cheatcode?

**Comment by whiskyfrenzy** [comment]
> @klkvr looks like 3078616330393734626563333961313765333662 is the prefix of the "privateKey" cheatcode identifier:
> 
> https://github.com/foundry-rs/foundry/blob/0026488754512acf0fd902a0d2c90cf8a09367b0/testdata/out/Derive.t.sol/DeriveTest.json#L1-L1
> 
> @whiskyfrenzy are you using that cheatcode?

I'm gonna go with a no, because I have no idea, but is there a way to be sure? Also, this link is giving me a 404.

**Comment by whiskyfrenzy** [comment]
Just read some of the docs for cheatcodes and traces, @mattsse  I think the the answer might be yes as my run function in my script is:
```
function run(bytes memory data) public {
        address deployerPrivateKey = address(bytes20(bytes("0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80")));
        vm.startBroadcast(deployerPrivateKey);

        uint256 gasBefore = gasleft();

        emit Gas(gasBefore - gasleft());

        address(bytes20(bytes("0x24EcC5E6EaA700368B8FAC259d3fBD045f695A08"))).call(data);
        // address(bot).call(data);

        vm.stopBroadcast();
    }
```
The private key comes from the list given after running anvil fork.

@klkvr removing `--skip-simulation` and using `-vvvv` gives me the following:

```
[⠒] Compiling...
No files changed, compilation skipped
{"logs":[],"gas_used":36501,"returns":{}}

## Setting up 1 EVM.
==========================
Simulated On-chain Traces:

  [0] 0x3078323445634335453645614137303033363842::executeSwap(650000000 [6.5e8], 0, 0xBA12222222228d8Ba445958a75a0704d566BF2C8, 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48, 0x0000000000000000000000000000000000000000000000000000000026be36800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000ba12222222228d8ba445958a75a0704d566bf2c80000000000000000000000001b02da8cb0d097eb8d57a175b88c7d8b47997506000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb480000000000000000000000008642a849d0dcb7a15a974794668adcfbe4794b560000000000000000000000001b02da8cb0d097eb8d57a175b88c7d8b479975060000000000000000000000008642a849d0dcb7a15a974794668adcfbe4794b560000000000000000000000001c9922314ed1415c95b9fd453c3818fd41867d0b0000000000000000000000001b02da8cb0d097eb8d57a175b88c7d8b479975060000000000000000000000001c9922314ed1415c95b9fd453c3818fd41867d0b000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb48)
    └─ ← ()


==========================

Chain 1

Estimated gas price: 35.243602672 gwei

Estimated total gas used for script: 36436

Estimated amount required: 0.001284135906956992 ETH

==========================
##
Sending transactions [0 - 0].

Transactions saved to: [TRUNCATED]/run-latest.json

Sensitive values saved to: [TRUNCATED]/run-latest.json

Error: 
Failed to send transaction

Context:
- (code: -32602, message: No Signer available, data: None)
```
And the truncated run-latest.json files are:
broadcast - [run-latest.json](https://github.com/foundry-rs/foundry/files/14667369/run-latest.json)
cache - [run-latest.json](https://github.com/foundry-rs/foundry/files/14667377/run-latest.json)

**Comment by klkvr** [comment]
ah, your code seems incorrect
`address(bytes20(bytes("0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80")))` will evaluate to `0x3078616330393734626563333961313765333662` which will be treated as a broadcasting address (tx.from)

If you want to proadcast via provided private key, you should do the following:
```
function run(bytes memory data) public {
        uint256 deployerPrivateKey = uint256(0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80);
        vm.startBroadcast(deployerPrivateKey);

        uint256 gasBefore = gasleft();

        emit Gas(gasBefore - gasleft());

        address(bytes20(bytes("0x24EcC5E6EaA700368B8FAC259d3fBD045f695A08"))).call(data);
        // address(bot).call(data);

        vm.stopBroadcast();
    }
```

`address(bytes20(bytes("0x24EcC5E6EaA700368B8FAC259d3fBD045f695A08")))` doesn't make much sense as well as it would evaluate to 0x3078323445634335453645614137303033363842

**Comment by whiskyfrenzy** [comment]
It works! Thanks to both of you. Nice catch @klkvr 
I'll close this off now :D
