### ISSUE TITLE
bug: `vm.expectEmit` doesn't work with `anonymous` events

### ISSUE THREAD

**Issue by duncancmt** [foundry-rs/foundry#7457]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (1a4960d 2024-03-20T00:17:21.177444508Z)

### What command(s) is the bug in?

forge test`

### Operating System

Linux

### Describe the bug

`anonymous` events (i.e. `LOG0`) cannot be matched with `vm.expectEmit(...)`

```Solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.25;

import {Test} from "forge-std/Test.sol";

event Foo(address emitter) anonymous;

contract Dummy {
    function doEmit() external {
        emit Foo(address(this));
    }
}

contract AnonEventTest is Test {
    Dummy dummy;

    function setUp() external {
        dummy = new Dummy();
    }

    function testEmit0() external {
        vm.expectEmit(address(dummy));
        emit Foo(address(dummy));
        dummy.doEmit();
    }

    function testEmit1() external {
        vm.expectEmit(true, true, true, true, address(dummy));
        emit Foo(address(dummy));
        dummy.doEmit();
    }

    function testEmit2() external {
        vm.expectEmit(true, true, true, true);
        emit Foo(address(dummy));
        dummy.doEmit();
    }

    function testEmit3() external {
        vm.expectEmit(false, false, false, true);
        emit Foo(address(dummy));
        dummy.doEmit();
    }
}
```

**Comment by zerosnacks** [comment]
Hi @duncancmt thanks for flagging this

Anonymous events are handled, except for the edge case where no `indexed` fields exist (i.e. contains no topics) in the event.

Created a draft here to implement a fix: https://github.com/foundry-rs/foundry/pull/7461

**Comment by zerosnacks** [comment]
Due to specific limitations of `vm.expectEmit` and not wanting to introduce any footguns we'll have to implement a new cheatcode to deal with anonymous events: https://github.com/foundry-rs/foundry/issues/7545
