### ISSUE TITLE
forge verify-contract error when using --chain parameter

### ISSUE THREAD

**Issue by coffeexcoin** [foundry-rs/foundry#7466]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e5318c3 2024-03-21T00:17:26.798143000Z)

### What command(s) is the bug in?

forge verify-contract

### Operating System

macOS (Apple Silicon)

### Describe the bug

Using `forge verify-contract` or `forge create --verify` with an alternate chain ID always fails with "ETHERSCAN_API_KEY must be set"

The `ETHERSCAN_API_KEY` environment variable is already set in my environment. There are no customizations to foundry.toml.

```
forge verify-contract --etherscan-api-key $ETHERSCAN_API_KEY --rpc-url $RPC_URL --verifier-url $VERIFIER_URL --chain 2 $CONTRACT x.sol:X
Start verifying contract `0x85E8697e8Be8B807A423af0aa812cfA4a1682a84 ` deployed on morden
Error:
ETHERSCAN_API_KEY must be set
```

**Comment by zeninsucks** [comment]
same issue - always emits `ETHERSCAN_API_KEY must be set` error, literally impossible to verify contract with `forge`.

tested with commits https://github.com/foundry-rs/foundry/commit/2249e077b39dd27fe09f5192223383d4146a6852 and https://github.com/foundry-rs/foundry/commit/57180fc6ddc71c26c71ad336cf1a0f0961dae28f - same result.

OS: macOS (Apple Silicon)

**Comment by highskore** [comment]
Have the same issue, my error is `Missing etherscan key for chain 123456789`

using 

```
forge script script/Deploy_Create.s.sol:Deploy --rpc-url $RPC_URL \
-vv \
--broadcast \
--chain 123456789 \
--slow \
--verify \
--verifier-url ${VERIFIERY_URL} \
--etherscan-api-key ${KEY}
```

forge 0.2.0 (72bc4f4 2024-04-08T00:17:17.438514000Z)

**Comment by mattsse** [comment]
cc @zerosnacks

**Comment by silvercondor** [comment]
getting the same error. setting env var or passing `-e` `--etherscan-api-key` doesn't work either

**Comment by cryptochou** [comment]
same error.

**Comment by rori4** [comment]
I can also confirm that this is an issue with latest forge 
```
forge 0.2.0 (ba9fa20 2024-06-24T00:23:20.410766000Z)
```

**Comment by consentsam** [comment]
Same issue

**Comment by gzliudan** [comment]
I encountered this bug also.

**Comment by CodeSandwich** [comment]
I got hit by that too, but from a different angle. It seems that having `ETH_RPC_URL` set makes Foundry fetch the chain ID, probably from the RPC server, and that's enough to trigger this bug.

**Comment by borre-haechi** [comment]
Although not an ideal solution, you can make slight modifications to the Forge source code to allow the verify command to work on arbitrary chains. In my case, I modified it to support verification for the SEI chain's seitrace. You can view the changes in my pull request here:

https://github.com/borre-haechi/foundry/pull/1/files#diff-16e4f33545b1873752adc0c3470e2130266a1ef984a287800f0031fbd771ae90R270

**Comment by amusingaxl** [comment]
I managed to get it fixed by adding this to my `foundry.toml`:
```toml
[etherscan]
unknown_chain = { key = "${TENDERLY_ACCESS_KEY}", chain = ${CHAIN_ID}, url = "${ETH_RPC_URL}/verify/etherscan" }
```

This solves the issue when verifying contracts using Tenderly Virtual Testnets. Should do the trick for other situations as well, as long as the parameters are correct.

**Comment by DenisGorbachev** [comment]
For people coming from Google: use `--verifier custom`

**Comment by rouzwelt** [comment]
> For people coming from Google: use `--verifier custom`

what does it mean? --verfier only takes 3 specific args, custom is none of them, right?
