### ISSUE TITLE
Failed to deserialize response

### ISSUE THREAD

**Issue by Abhishek-2416** [foundry-rs/foundry#7470]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (0026488 2024-03-19T00:17:15.606490924Z)

### What command(s) is the bug in?

forge script script/Interactions.s.sol:MintBasicNft --fork-url $SEPOLIA_RPC_URL --private-key $PRIVATE_KEY --broadcast --etherscan-api-key $ETHERSCAN_API_KEY -vvvv

### Operating System

Linux

### Describe the bug

So basically i had created a simple NFT and wanted to put it out on the testnet when i was able to deploy the nft using the command `forge script script/DeployBasicNft.s.sol --fork-url $SEPOLIA_RPC_URL --private-key $PRIVATE_KEY --broadcast --verify --etherscan-api-key $ETHERSCAN_API_KEY -vvvv`
but when i wanted to mint the NFT programmatically using the command `forge script script/Interactions.s.sol:MintBasicNft --fork-url $SEPOLIA_RPC_URL --private-key $PRIVATE_KEY --broadcast --etherscan-api-key $ETHERSCAN_API_KEY -vvvv`
it gives and error and says it runs successfully but my NFT doesnt show up in my metamask

**Comment by zerosnacks** [comment]
Marking as `duplicate` of https://github.com/foundry-rs/foundry/issues/6651
