### ISSUE TITLE
Challenges in Directly Accessing Nested Mappings within Structs in Solidity for Testing

### ISSUE THREAD

**Issue by CypherBee** [foundry-rs/foundry#7471]
### Component

Forge

### Describe the feature you would like

I'm trying to run the tests on my contract, which stores a project merkle root, and its participants in an array of structs. 

My test is simple: I want to call registerInterest by an address (0x123) for a projectId, then check the state variable if `projects[projectId].isParticipating[0x123`] evaluates to true, which it should.

Inside my contract, I have an isRegistered function which takes an address and a projectId and returns true if the address registered its interest for that projectId, and it returns false otherwise. 

When I run my tests, I call function `registerInterest(uint256 projectId)` - _the address registered will be msg.sender_ , and  `assertTrue(isRegistered(address _address, uint projectId)`). **The test passes.**

Now here's the problem:
I want to run the same test, but instead of calling the isRegistered function to check whether the caller is registered, I tried to access the isParticipating mapping directly to check if `projects(projectId).isParticipating[address]==true`.
projects(projectId) gives back a string instead of a struct and I cannot access the .isParticipant mapping, here's the error:

`bool isParticipatant= rootStorage.projects(0).isParticipating[address(0x123)];
//Member "isParticipating" not found or not visible after argument-dependent lookup in string memory.
`
Basically it only finds the string, not the mapping data.

I know that it's a limitation with Solidity Getter, but this feature would allow for more in-depth testing.

Finally, There's a workaround which is to make the test contract inherit the Main contracts - RootStorage, and call these parameters With the main contract identifier: _(Capital letter R)_ `RootStorage.projects(0).isParticipating[address(0x123)];MainContract.project` and now the expression is accepted. But you need to call all the functions on RootStorage, instead of the instanciated rootStorage.

### Additional context

Here's my contract: 

```
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/access/Ownable.sol";

contract RootStorage is Ownable(msg.sender) {
    
    struct Project  {
        string merkleRoot;
        mapping(address=>bool) isParticipating;
        address[] participantsList;
        
    }

    Project[] public projects;
    uint256 public projectCount;

    event ProjectAdded(uint256 indexed projectId, string merkleRoot);
    event MerkleRootUpdated(uint256 indexed projectId, string newMerkleRoot);
    event InterestRegistered(uint indexed projectId, address addr);

    function isRegistered(address _address, uint projectId) public view returns (bool) {
        return (projects[projectId].isParticipating[_address]);
    }

    // Function to add a new project's Merkle root, only callable by the contract owner
    function addProject(string memory merkleRoot) public onlyOwner {

        Project storage project=projects.push();
        project.merkleRoot=merkleRoot;
        emit ProjectAdded(projectCount, merkleRoot);
        projectCount++;
    }

    function registerInterest(uint256 projectId) public{
        require(projectId < projects.length, "Project ID does not exist");
        Project storage project=projects[projectId];

        require(!isRegistered(msg.sender,projectId));
        project.isParticipating[msg.sender]=true;
        project.participantsList.push(msg.sender);
        
        emit InterestRegistered(projectId,msg.sender);

    }
    }
```
    
Foundry Tests:
```
pragma solidity ^0.8.20;

import "../src/RootStorage.sol";
import "forge-std/Test.sol";
import "forge-std/console.sol";




contract RootStorageTest is Test,RootStorage{
    RootStorage public rootStorage;
    
    
    function setUp() public {
    rootStorage= new RootStorage();
    rootStorage.addProject("0x1f5ef9ffe259f05968e28dcdba2ceb2bc56d4af13dc54b198db979914891e632");
    
    }

// passing
function test_RegisterInterest() public {
        vm.prank(address(0x123));
        rootStorage.registerInterest(0);
        console.log(rootStorage.projects(0)); 
        assertTrue(rootStorage.isRegistered(address(0x123),0),"address should be marked as participating");

    }

//failing
    function test_RegisterInterestWithStorage() public {
        vm.prank(address(0x123));
        rootStorage.registerInterest(0);
        bool isParticipatant= rootStorage.projects(0).isParticipating[address(0x123)];
        //rootStorage.projects(0) is a string
        assertTrue(isParticipatant,"address should be marked as participating");

    }
    }
```

**Comment by zerosnacks** [comment]
Marking as `not planned`, this is a limitation of Solidity itself

I recommend reading https://solidity-fr.readthedocs.io/fr/latest/internals/layout_in_storage.html for a good explanation on storage layout
