### ISSUE TITLE
add the ability to select a given chain in the scripts

### ISSUE THREAD

**Issue by omnifient** [foundry-rs/foundry#7475]
### Component

Forge

### Describe the feature you would like

**what I'm requesting**
in the tests, we're able to `selectFork`
it would be great if we could do something similar in the scripts, but for selecting different chains

**context/why**?
developing for multiple chains is exploding in popularity, so it's common to have the need to do something in chain A, then in chain B, etc

**Comment by klkvr** [comment]
You can use forking cheatcodes in scripts as well

**Comment by omnifient** [comment]
i just realized i was actually already using that in an old script

got confused with the names when I revisited this 🤦‍♂️
