### ISSUE TITLE
anvil: configure memory limit

### ISSUE THREAD

**Issue by ryanio** [foundry-rs/foundry#7478]
### Component

Anvil

### Describe the feature you would like

i'm running into `EVM error MemoryLimitOOG` in anvil. it seems like `forge` and `chisel` have `--memory-limit` flags to configure a larger limit, would it be possible to have this in `anvil` as well? thank you!

**Comment by b68h4** [comment]
This a not feature, this is a critical bug!. I think need a fastly fix. I cant run transfer function below memory limit.It always print MemoryLimitOOG.

If you reduce the parse_units unit value below 18, MemoryLimitOOG is bypassed. Its so critical bug because i cant transfer tokens truly amount.

Screenshots:
![CleanShot 2024-03-24 at 17 32 48](https://github.com/foundry-rs/foundry/assets/35398147/cdc02990-6d3c-4a1f-97a3-e4919d973900)
![CleanShot 2024-03-24 at 17 33 53](https://github.com/foundry-rs/foundry/assets/35398147/9ee7d4bd-71b9-4863-81de-0cdc594a5fb0)

**Comment by mattsse** [comment]
> have --memory-limit flags to configure a larger limit, would it be possible to have this in anvil as well

this can be added easily

**Comment by mattsse** [comment]
> This a not feature, this is a critical bug! I think need a fastly fix. I cant run transfer function below memory limit.It always print MemoryLimitOOG.
> 
> If you reduce the parse_units unit value below 18, MemoryLimitOOG is bypassed. Its so critical bug because i cant transfer tokens truly amount.
> 
> Screenshots: ![CleanShot 2024-03-24 at 17 32 48](https://private-user-images.githubusercontent.com/35398147/316316213-cdc02990-6d3c-4a1f-97a3-e4919d973900.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMDAxNDAsIm5iZiI6MTcxMTI5OTg0MCwicGF0aCI6Ii8zNTM5ODE0Ny8zMTYzMTYyMTMtY2RjMDI5OTAtNmQzYy00YTFmLTk3YTMtZTQ5MTlkOTczOTAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDE3MDQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlMTU3YTljMWJlZDMxNTU5NGQ2YjJhYWVmMzVkYzNmMDNiNDFmY2UyMDg3Y2E5MGMzNGVkZTQzYzRhYTU1OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mm9nX08HaTGOvULkrc96pUzyhuU9ujNaChNlHH8hFpY) ![CleanShot 2024-03-24 at 17 33 53](https://private-user-images.githubusercontent.com/35398147/316316225-9ee7d4bd-71b9-4863-81de-0cdc594a5fb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMDAxNDAsIm5iZiI6MTcxMTI5OTg0MCwicGF0aCI6Ii8zNTM5ODE0Ny8zMTYzMTYyMjUtOWVlN2Q0YmQtNzFiOS00ODYzLTgxZGUtMGNkYzU5NGE1ZmIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDE3MDQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3ZGY4M2FkNGZjZmY1YjA2MDhmMTc4NmRlZmY5MTRiM2QyZjAwYWJkMDFiODU2ZmFmMzIxNDNjYmJhY2NmOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RWRuOhjtiVtZamfAwWzWaRl2VNdFWgN9RPR3tLYltYk)

this error is thrown when the evm tries to expand past the limit.
it looks like this is due to the transfer implementation.
