### ISSUE TITLE
Deserialization Error: EOF while parsing a value at line 1 column 0

### ISSUE THREAD

**Issue by Osub** [foundry-rs/foundry#7484]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (88e09f6 2024-03-25T00:21:20.957439000Z)

### What command(s) is the bug in?

forge script PostDeploy --sig "run(address)" "0x0c4363b384fba51abcaaebb9b0c26fe44eceee43" --broadcast --rpc-url "http://127.0.0.1:8545" -vvv

### Operating System

macOS (Apple Silicon)

### Describe the bug

```
 forge script PostDeploy --sig "run(address)" "0x0c4363b384fba51abcaaebb9b0c26fe44eceee43" --broadcast --rpc-url "http://127.0.0.1:8545" -vvv
Error: 
Deserialization Error: EOF while parsing a value at line 1 column 0. Response: 
```

**Comment by DaniPopes** [comment]
Can you please provide more information? What is `PostDeploy` script? What is the localhost RPC you're running?

**Comment by Osub** [comment]
fter I closed the clashX client, the error disappeared.

**Comment by Osub** [comment]
> Can you please provide more information? What is `PostDeploy` script? What is the localhost RPC you're running?

```
contract PostDeploy is Script {
  function run(address worldAddress) external {
    // Specify a store so that you can use tables directly in PostDeploy
    StoreSwitch.setStoreAddress(worldAddress);

    // Load the private key from the `PRIVATE_KEY` environment variable (in .env)
    uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");

    // Start broadcasting transactions from the deployer account
    vm.startBroadcast(deployerPrivateKey);

    // ------------------ EXAMPLES ------------------

       IWorld(worldAddress).setAdmin(vm.addr(deployerPrivateKey));
       IWorld(worldAddress).setPayToken(vm.envAddress("DAI"));

      IWorld(worldAddress).setBindRoot(vm.envAddress("BIND_ROOT"));
      IWorld(worldAddress).bind(vm.envAddress("BIND_ROOT"));
       IERC20(PayToken.get()).approve(worldAddress,  ~uint256(0));
      IWorld(worldAddress).pleged(10e18);

    vm.stopBroadcast();
  }
```

**Comment by magj2006** [comment]
> After I closed the clashX client, the error disappeared.
> 
> May be related to proxy vpn

Yes, As per I tested, if you run clashX client, same error will appear, even you run a empty script (that is empty in run function).
