### ISSUE TITLE
Feature request: `input.index(key)`

### ISSUE THREAD

**Issue by smol-ninja** [foundry-rs/foundry#7487]
`Vm.sol` [offers](https://github.com/foundry-rs/forge-std/blob/bb4ceea94d6f10eeb5b41dc2391c6c8bf8e734ef/src/Vm.sol#L745C1-L755C94) string manipulation functions that come in very handy when dealing with strings. In the latest versions of `forge-std`, the introduction of new functions such as `replace`  has [lowered our dependency](https://github.com/sablier-labs/v2-core/issues/843) on other external libraries.

However, `forge-std` still lacks one useful function for which foundry users may have to rely on external dependencies - a function that can return the index of the first occurrence of a key in an input string.

```solidity
function index(string memory input, string memory key) external pure returns (uint256);
```

It would, therefore, be very useful if we could add support to it.

**Comment by kamuik16** [comment]
Hey @DaniPopes! Opened a PR featuring this, review it whenever free. Thanks!

**Comment by kamuik16** [comment]
> Great work @kamuik16.

Thanks 🙂
