### ISSUE TITLE
Feature request: `--disable-metadata` as CLI option to `forge build`

### ISSUE THREAD

**Issue by PetarMax** [foundry-rs/foundry#7488]
### Component

Forge

### Describe the feature you would like

An equivalent of passing `--no-cbor-metadata  --metadata-hash none` to `solc`, or adding 
```
bytecode_hash = "none"
cbor_metadata = false
```
to `foundry.toml`, this CLI feature would help stabilise the generated EVM bytecode.

### Additional context

I am working on the development of [Kontrol](https://docs.runtimeverification.com/kontrol), a tool for formal verification of Ethereum smart contracts. As part of our verification pipeline, we would like to be able to switch this metadata manually using CLI. This would allow our analyses to scale better, while not requiring client-side changes.

**Comment by ehildenb** [comment]
@zerosnacks is there any progress on this? This would seriously improve the ease with which formal verification tools can re-use proof executions between runs.

**Comment by zerosnacks** [comment]
Hi @ehildenb, thanks for the ping - will be picking this up soon, aiming for a draft before EOW.

**Comment by zerosnacks** [comment]
@ehildenb & @PetarMax  

Added as `--no-metadata` in https://github.com/foundry-rs/foundry/pull/7684
