### ISSUE TITLE
feat(`forge script`): provide more verbose transaction information when running

### ISSUE THREAD

**Issue by robinsdan** [foundry-rs/foundry#7494]
### Component

Forge

### Describe the feature you would like

The `forge script` currently only provide a summary about the gas cost, it will be better to provide more info like: the total transctions constructed, priority gas price and max gas price.

**Comment by grandizzy** [comment]
@danrobinson could you please provide more details re how output should look vs how it is now? thank you

**Comment by grandizzy** [comment]
let's track this in https://github.com/foundry-rs/foundry/issues/6253 going to close it as dupe. thank you
