### ISSUE TITLE
from docs, "docker pull ghcr.io/foundry-rs/foundry:latest" fails 

### ISSUE THREAD

**Issue by stskeeps** [foundry-rs/foundry#7495]
### Component

Installer

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

n/a

### What command(s) is the bug in?

docker packages

### Operating System

Linux

### Describe the bug

docker pull ghcr.io/foundry-rs/foundry:latest

fails with:

Error response from daemon: Head "https://ghcr.io/v2/foundry-rs/foundry/manifests/latest": denied: denied

**Comment by grandizzy** [comment]
going to track arm64 support in https://github.com/foundry-rs/foundry/issues/8039
