### ISSUE TITLE
Fuzz Default Runs `257` Instead of `256`

### ISSUE THREAD

**Issue by pcaversaccio** [foundry-rs/foundry#7497]
Not sure if this is a small bug or intended, but I realised that the latest default fuzz runs used for `forge snapshot` got changed to `257` instead `256`. My `forge` version I used: `forge 0.2.0 (88e09f6f 2024-03-24T18:44:00.248018000Z)`

![image](https://github.com/foundry-rs/foundry/assets/25297591/21072862-7179-47aa-a3e7-6b3d1f08635c)

https://github.com/pcaversaccio/snekmate/pull/219/files#diff-11538116afca6cc6a316ec7e5532f95ee5b404085a676b3d186ac5776ef99712

**Comment by grandizzy** [comment]
it depends if you had a previous failed run it is now saved in `cache/fuzz/failed` dir and regression replayed on subsequent runs

**Comment by grandizzy** [comment]
hey @pcaversaccio could you pls check comment above and lmk if that's the case? Thank you!

**Comment by pcaversaccio** [comment]
> hey @pcaversaccio could you pls check comment above and lmk if that's the case? Thank you!

Well, now I have e.g. `264` runs: https://github.com/pcaversaccio/snekmate/blob/modules/.gas-snapshot#L3. This happened when I integrated Echidna into snekmate contracts: https://github.com/pcaversaccio/snekmate/pull/239. I'm not sure if this makes any sense now.

**Comment by grandizzy** [comment]
> > hey @pcaversaccio could you pls check comment above and lmk if that's the case? Thank you!
> 
> Well, now I have e.g. `264` runs: https://github.com/pcaversaccio/snekmate/blob/modules/.gas-snapshot#L3. This happened when I integrated Echidna into snekmate contracts: [pcaversaccio/snekmate#239](https://github.com/pcaversaccio/snekmate/pull/239). I'm not sure if this makes any sense now.

It makes sense if you have the `cache/fuzz/failed` not empty on the machine you collected gas snapshot

**Comment by pcaversaccio** [comment]
> It makes sense if you have the `cache/fuzz/failed` not empty on the machine you collected gas snapshot from (as failures / regressions accumulate and are replayed before the new campaign starts)

I usually run `forge clean` before I generate a new `.gas-snapshot` file, that's why I'm confused. But your overall explanation makes sense, sure.

**Comment by grandizzy** [comment]
Oh, yeah, just tried it and `forge clean` doesn't remove the `failures` file, will address this issue in a fix

**Comment by pcaversaccio** [comment]
> Oh, yeah, just tried it and `forge clean` doesn't remove the `failures` file, will address this issue in a fix

Great, that will fix this issue :)
