### ISSUE TITLE
Support injecting custom precompiles to anvil

### ISSUE THREAD

**Issue by alexfertel** [foundry-rs/foundry#7498]
### Component

Anvil

### Describe the feature you would like

Currently, we have a use case where we want to spin up an isolated `anvil` instance per test with custom precompiles.

Given that the team is [willing to support](https://github.com/foundry-rs/foundry/issues/7262) custom precompiles as functions in Foundry, it would be nice to add a way to inject custom precompiles to `anvil` (as a library), like for example, being able to pass the result of [`revm::Evm::builder()`](https://bluealloy.github.io/revm/crates/revm/builder.html#examples).

If I'm reading `anvil`'s source code correctly, this would imply updating [`NodeConfig`](https://github.com/foundry-rs/foundry/blob/563e0624ba5a4a317202b4c9bc1d0120ed7c49f0/crates/anvil/src/config.rs#L90) to support some form of precompile injection.

This would outsource maintaining custom precompiles from the team to consumers.

**Comment by mattsse** [comment]
This should be doable,

what we need is a way to tell the `Backend` how to configure an `Evm`, so the `Evm::builder()` step can be customized.

In reth this is kinda doable already, like:

https://github.com/paradigmxyz/reth/blob/be16072728abae152fd04a83f0f22e8b08ecbe04/examples/custom-evm/src/main.rs#L83-L99

so what we need here is something similar.

I think for anvil this should also be abstracted over a trait that can be boxed so we don't end up with a bunch of generics everywhere, which is the most difficult part here because the Evm interface is a bit hard to work with in that regard.

so this likely needs some trial and error first

**Comment by alexfertel** [comment]
Hey, so I started working on this, and I have the following thoughts/questions. I know you know all of this, but I like to have all the context in one place.

I see that Evm environment is separate from Evm execution, in the sense that all that `anvil::spawn()` does is setup all the environment surrounding execution, which makes sense. However, this also means that instantiation of `revm::Evm` occurs only in https://github.com/foundry-rs/foundry/blob/bd56eef59fff9d9597ab0aff4bf4fd6f0a9e399e/crates/evm/core/src/utils.rs#L102-L118

and this is passed the `Env` constructed by `anvil::spawn`. The difference between `anvil` and `reth` in this regard is that while `anvil` uses `revm`'s config types for its execution, as you can see in the signature of `new_evm_with_inspector()` above, `reth` uses its own config types, and stores the `Evm` instance itself in the processor https://github.com/paradigmxyz/reth/blob/be16072728abae152fd04a83f0f22e8b08ecbe04/crates/revm/src/processor.rs#L58 and uses it here https://github.com/paradigmxyz/reth/blob/be16072728abae152fd04a83f0f22e8b08ecbe04/crates/revm/src/processor.rs#L279.

So, one path I see is creating a wrapper `Env` for [`anvil::eth::backend::mem::Backend`](https://github.com/foundry-rs/foundry/blob/bd56eef59fff9d9597ab0aff4bf4fd6f0a9e399e/crates/anvil/src/eth/backend/mem/mod.rs#L150), so that the `TransactionExecutor` can tap into the injected precompiles. This will also mean modifying `new_evm_with_inspector()`, which btw, has the following notice:

```rust
    // NOTE: We could use `revm::Evm::builder()` here, but on the current patch it has some
    // performance issues.
```

Does this make sense to you? Am I missing something?

**Comment by onbjerg** [comment]
Somewhat related https://github.com/foundry-rs/foundry/issues/6509 (i.e. the idea is WASM modules to insert as precompiles for foundry)
