### ISSUE TITLE
feat(cheatcodes): add cheatcode to assert that a specific modifiers decorates a function

### ISSUE THREAD

**Issue by pegahcarter** [foundry-rs/foundry#7519]
### Component

Forge

### Describe the feature you would like

I would like a cheatcode to assert that a specific modifier decorates a function.  This would improve test coverage as I can make one test which checks, for example, all functions which should use an expected `onlyOwner` modifier.

**Comment by zerosnacks** [comment]
Thanks for your suggestion!

I can see this being useful, especially as modifiers like `nonReentrant` / `nonReadReentrant` are commonly used.

I've previously used a workaround with `forge build --build-info` and something along these lines to perform assertions against the AST.

```solidity
contract Counter {
    uint256 public number;

    modifier onlyOwner() {
        require(
            msg.sender == 0x220866B1A2219f40e72f5c628B65D54268cA3A9D,
            "You are not the owner"
        );
        _;
    }

    function setNumber(uint256 newNumber) public onlyOwner {
        number = newNumber;
    }

    function increment() public {
        number++;
    }
}
```

```sh
  cat out/Counter.sol/Counter.json | jq '
    .ast.nodes |
    map(.nodes) |
    flatten |
    .[] |
    select(.kind=="function") |
    { name: .name, modifiers: .modifiers }'
```

```
{
  "name": "setNumber",
  "modifiers": [
    {
      "id": 38888,
      "kind": "modifierInvocation",
      "modifierName": {
        "id": 38887,
        "name": "onlyOwner",
        "nameLocations": [
          "340:9:25"
        ],
        "nodeType": "IdentifierPath",
        "referencedDeclaration": 38883,
        "src": "340:9:25"
      },
      "nodeType": "ModifierInvocation",
      "src": "340:9:25"
    }
  ]
}
{
  "name": "increment",
  "modifiers": []
}
```

**Comment by grandizzy** [comment]
@pegahcarter we discussed internally and got to the conclusion this is better suitable for static analyzer tools (like slither). Going to close this for now as not planned, please reopen if you strongly think should be part of foundry. thank you!
