### ISSUE TITLE
Doubt regarding foundry test implementation flow 

### ISSUE THREAD

**Issue by Redidacove** [foundry-rs/foundry#7523]
I am recently working on a project using foundry and having issue with assertEq when I am running forge test it shows unknown selector fn when I went in test.sol there was a definition for assertEq fn in there but the body of fn was just vm.assertEq(params); I thought it is not defined here what is does internally maybe it is done in vm.sol but it comes out that there also its just a interface so my question is where is the functionality of assertEq is defined like the logical code of comparing two things where is that defined .

I know its a beginner doubt but I am not  able to figure it out. Please help

**Comment by DaniPopes** [comment]
Update your forge version, see https://github.com/foundry-rs/foundry/issues/7402
