### ISSUE TITLE
Failed script broadcasts after successful simulation on Arbitrum

### ISSUE THREAD

**Issue by ruvaag** [foundry-rs/foundry#7524]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (d1ab09d 2024-03-30T00:16:04.045075000Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Description

I'm working on a script to deploy and setup a protocol, around 30 transactions in all. The target network is Arb Sepolia, and eventually Arb mainnet. These transactions involve a mix of operations --- contract deployments, proxy deployments + configuration , ancillary contract deployments, setting initial params, transferring ownership etc.

While the script successfully passes simulation, it fails when actually run with `--broadcast` at multiple points. It also fails when I use `--slow`. Failures usually happens with transactions that depend on the previous one executing sequentially. An example is when deploying an implementation contract, followed by a transparent proxy pointing to it.

Note that I'm unable to `--resume` and continue off from where I left because the nonce is updated on a failed transaction which changes the deployment addresses for contracts to be deployed later in the script. The way I run the script right now is to manually edit addresses at every failure and before re-running the rest.

It seems like an unusual error, because it's as if the network confirms a transaction before the world state is actually updated. Or as if they're not being executed in the order that they're confirmed.

To rule out the possibility of it being a script issue I tried to deploy the same script on Eth Sepolia - it went through smoothly. So I suspect this happens due to some idiosyncratic behaviour on Arb.

### Suggested Fix

I think `forge script` should implement the ability to broadcast transactions after a time delay, as done for contract verification. Or perhaps allow configuring the number of confirmations to wait for when using `--slow`.

**Comment by klkvr** [comment]
@ruvaag could you please share the error messages which occur for failing scripts?

**Comment by ruvaag** [comment]
@klkvr closing this issue since i'm not able to replicate it anymore. The only change I made was updating rust and foundry a couple hours ago. I'll stay on top of this and reopen if I see something similar. Thanks a lot for taking the time to respond.
