### ISSUE TITLE
Automatically label known contract addresses in traces 

### ISSUE THREAD

**Issue by zhiqiangxu** [foundry-rs/foundry#7530]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (7922fd5 2024-02-05T00:19:20.258041000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Intel)

### Describe the bug

This issue is a follow-up issue of [this one](https://github.com/foundry-rs/foundry/issues/639), but since that one is old, I'd like to issue a new one.

It seems `0x0000000000000000000000000000000000000001` is a contract automatically created by foundry, but not labeled in traces:

```
[0] 0x0000000000000000000000000000000000000001::fallback{value: 1000000000000000000}()
```

It can be reproduced [here](https://github.com/zhiqiangxu/es-op-batchinbox/tree/foundry_label) by running `forge test --mp test/BatchInbox.t.sol -vvv`

**Comment by grandizzy** [comment]
here's the list of precompiles, probably can be labeled with `Name` value https://book.getfoundry.sh/misc/precompile-registry ?
