### ISSUE TITLE
Solmate Installation

### ISSUE THREAD

**Issue by CrsithianC** [foundry-rs/foundry#7542]
### Component

Other (please describe)

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (f625d0f 2024-04-02T00:22:27.735370800Z)

### What command(s) is the bug in?

forge install transmissions11/solmate

### Operating System

Windows

### Describe the bug

I can't install solmate with foundry in my working space, im using VS Code.
thats what i get when i run the command.

Installing solmate in C:/Users/lokos/Desktop/Alvearium/lib\solmate (url: Some("https://github.com/transmissions11/solmate"), tag: None)
Error: 
The target directory is a part of or on its own an already initialized git repository,
and it requires clean working and staging areas, including no untracked files.

Check the current git repository's status with `git status`.
Then, you can track files with `git add ...` and then commit them with `git commit`,
ignore them in the `.gitignore` file, or run this command again with the `--no-commit` flag.

If none of the previous steps worked, please open an issue at:
https://github.com/foundry-rs/foundry/issues/new/choose

**Comment by grandizzy** [comment]
make sure you don't have any untracked files as mentioned in message
```
The target directory is a part of or on its own an already initialized git repository,
and it requires clean working and staging areas, including no untracked files.

Check the current git repository's status with git status.
Then, you can track files with git add ... and then commit them with git commit,
ignore them in the .gitignore file, or run this command again with the --no-commit flag.
```
