### ISSUE TITLE
bug: forge fmt bad indentation

### ISSUE THREAD

**Issue by cruzdanilo** [foundry-rs/foundry#7549]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (f625d0f 2024-04-02T00:16:42.810315000Z)

### What command(s) is the bug in?

forge fmt

### Operating System

macOS (Apple Silicon)

### Describe the bug

forge fmt fails to properly indent closing parenthesis enclosed in `{ }`. example of formatted output:

```solidity
// SPDX-License-Identifier: AGPL-3.0
pragma solidity ^0.8.25;

contract Example {
    function one() external {
        this.other({
            data: abi.encodeCall(
                this.other, ("bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla")
                )
        });
    }

    function other(bytes memory data) external {}
}
```

**Comment by mattsse** [comment]
hmm, what would be the expected format here?

**Comment by cruzdanilo** [comment]
the closing parenthesis of `abi.encodeCall` should be one indent level below:
```solidity
        this.other({
            data: abi.encodeCall(
                this.other, ("bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla bla")
            )
        });
```

**Comment by mattsse** [comment]
ah gotcha
