### ISSUE TITLE
bug: `forge flatten` fails with `missing field body at line 1 column 30987`

### ISSUE THREAD

**Issue by duncancmt** [foundry-rs/foundry#7554]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (dbc48ea 2024-04-03T00:17:03.697365187Z)

### What command(s) is the bug in?

forge flatten

### Operating System

Linux

### Describe the bug

```
$ forge flatten src/ContractName.sol 
[⠊] Compiling...
[⠢] Compiling 23 files with 0.8.25
[⠰] Solc 0.8.25 finished in 4.26s
Compiler run successful!
Error: 
Failed to flatten: missing field `body` at line 1 column 28436
```
Seems related to #7069, but I have no further insights. I'm trying to flatten this contract because `forge create --verify` also fails with this contract and I'm about to pull my hair out.

**Comment by Evalir** [comment]
Hey @duncancmt thanks for the report! Would it be possible for you to provide a repro for this? Else it's really really hard to investigate.

cc @klkvr seems like another flattener edge case

**Comment by zerosnacks** [comment]
Thanks @duncancmt for reporting, would be great to have a minimal reproduction or additional details on your contract

For now I'll mark it as `can't repro` due to limited details on how to reproduce the bug

Feel free to re-open with additional details / minimal reproduction

**Comment by duncancmt** [comment]
Hi @zerosnacks . I couldn't give a repro because the contracts weren't released yet, but we just released, so I can show you. In the repo https://github.com/0xProject/0x-settler if you try `forge flatten src/chains/Mainnet.sol`, you'll observe the above error

**Comment by zerosnacks** [comment]
Was able to narrow it down to the `override` tag in this code block

```solidity
    function _uniV3ForkInfo(uint8 forkId)
        internal
        pure
        override
        returns (address factory, bytes32 initHash, uint32 callbackSelector)
    {
    // [...]
    }
```

https://github.com/0xProject/0x-settler/blob/fcd55335a6224f944d9d749166a441c4e257d059/src/chains/Mainnet.sol#L66

**Comment by klkvr** [comment]
> This is fixed by either removing the override tag or converting the method to an empty implementation rather than an interface definition:

hmm, it's strange that removing `overrides` allows to fix this, as without `override` this is no longer valid solidity and causes `forge build` to fail

**Comment by zerosnacks** [comment]
> > This is fixed by either removing the override tag or converting the method to an empty implementation rather than an interface definition:
> 
> hmm, it's strange that removing `override` allows to fix this, as without `override` this is no longer valid solidity and causes `forge build` to fail

Ah good point, `override` is indeed required in this situation and the compiler does throw an error

**Comment by klkvr** [comment]
> Ah good point, override is indeed required in this situation and the compiler does throw an error when attempting to build

ah it's succeeding because we are falling back to older flattener impl which does not require AST parsing
