### ISSUE TITLE
`ETHERSCAN_API_KEY` in `.env` activates trace resolving in non-forked tests

### ISSUE THREAD

**Issue by zerosnacks** [foundry-rs/foundry#7555]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [x] Foundryup

### What command(s) is the bug in?

forge test

### Operating System

macOS (Intel)

### Describe the bug

Currently if you define an `ETHERSCAN_API_KEY` in your `.env` file and run tests with tracing enabled (`-vvv`+) it will use it even in non-forking tests. Because of Etherscan rate limiting there is a huge performance impact, especially in fuzz tests.

After preliminary research it appears that we can disable this behaviour without issue as one is only interacting with contracts for which one should have artifacts, unless one does bytecode etch/deploys.

Identified as cause of https://github.com/foundry-rs/foundry/issues/7312

**Comment by zerosnacks** [comment]
Initially I figured it would be as simple as checking if we are in a forked test by checking `runner.fork.is_some()` in `run_tests`, simply skipping the enabling of etherscan traces otherwise.

Unfortunately there is some complexity to this as the creation and selecting of forks can be done during test execution using cheatcodes, transforming what was originally tagged as local test (as in, `runner.fork` being none) into a forked test.

Do you see an elegant way to implement this taking this dynamic switching into account? @mattsse @DaniPopes

**Comment by mattsse** [comment]
I think we want to include that info in the test result.

https://github.com/foundry-rs/foundry/blob/1281421e04144a8de0341f9cad9b623a012a74bf/crates/forge/src/runner.rs#L276-L295

this information could be obtained via the `backend`/ `executor` type  by adding `Backend/Executor::has_forks`

similar to:

https://github.com/foundry-rs/foundry/blob/1281421e04144a8de0341f9cad9b623a012a74bf/crates/evm/evm/src/executors/mod.rs#L430-L430

and include that info in the testresult:

https://github.com/foundry-rs/foundry/blob/1281421e04144a8de0341f9cad9b623a012a74bf/crates/forge/src/runner.rs#L425-L425

**Comment by zerosnacks** [comment]
Closing as `wontfix`. Performance issue has been resolved to a very large extend by the cache busting fix in https://github.com/foundry-rs/block-explorers/pull/40 - not worth spending more time on in my opinion.
