### ISSUE TITLE
(anvil): `forge script` breaks when run with Blast mainnet RPC against anvil forks

### ISSUE THREAD

**Issue by Sabnock01** [foundry-rs/foundry#7560]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (dbc48ea 2024-04-03T00:17:03.697365187Z)

### What command(s) is the bug in?

anvil --fork-url

### Operating System

Linux

### Describe the bug

Whenever running a `forge script` against a forked Blast mainnet anvil instance (created with `anvil --fork-url $BLAST_RPC`) the output of the scripts will give the following error: 
```
Error:
builder error

Context:
- relative URL without a base
```
This behavior is consistent across all Blast mainnet RPC's.
It is *not* the case for Blast Sepolia RPC's which work without issue.

It is also not the case when running a `forge script` against the RPC itself, as opposed to the anvil instance with `--rpc-url http://localhost:8545`

**Comment by mattsse** [comment]
do you have a repro for this we can use for debugging

cc @zerosnacks @yash-atreya

**Comment by Sabnock01** [comment]
This was a consistent issue on Wednesday for all Blast mainnet RPC's but since then I've not encountered it and have not been able to repo. I assume it was something on their end and not Foundry. In any case, the error message seems misleading.

**Comment by zerosnacks** [comment]
I think it makes sense to turn this ticket into a error improvement feature request but considering the originating error is from https://github.com/servo/rust-url/blob/54346fa288e16b25b71c45149d7067c752b450e0/url/src/parser.rs#L84 (as used by `reqwest`) I don't see an actionable item here. Considering the original issue has been resolved I'll mark it as so.

Feel free to re-open if you disagree
