### ISSUE TITLE
Add support for the frame.sh desktop wallet

### ISSUE THREAD

**Issue by topocount** [foundry-rs/foundry#7561]
### Component

Forge, Cast

### Describe the feature you would like

I have miscellaneous wallets stored in [frame](https://frame.sh/) that I'd like to be able to utilize in foundry workflows without handling the private keys and mnemonics directly. I try to utilize frame as a unified hub for wallet management, since it's fairly powerful and diverse for both injected web and CLI scripting. It also provides a nice electron-based UI for visually confirming low-level TX data before signing, which is an extra step I find useful on public networks.

N.B. I'd like to implement this myself

### Additional context

Frame has a dedicated rpc endpoint `http://127.0.0.1:1248` that accepts commands that allow for specifying a chainId and making other wallet management rpc commands. For now I'd just like to implement an interface for the [`wallet_switchEthereumChain`](https://eips.ethereum.org/EIPS/eip-3326) via a CLI flag like --chain-id, which would allow for invoking a specific network on the fly.

**Comment by topocount** [comment]
It looks like this is now supported extensionally via 
```sh
--from <addr> --rpc-url http://127.0.0.1:1248 --chain <chain id> --unlocked
```

I was getting a gas price error on this for a while but this is no longer the case.

**Comment by amusingaxl** [comment]
I'm getting a `No associated wallet for addresses: [<address>]` error. Any ideas how to circumvent this?

**Comment by yohanelly95** [comment]
> I'm getting a `No associated wallet for addresses: [<address>]` error. Any ideas how to circumvent this?

did you figure this out ?
