### ISSUE TITLE
Forge script deployment producing wrong contract address on `Rootstock` network

### ISSUE THREAD

**Issue by ahsan-javaiid** [foundry-rs/foundry#7565]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

#### 1\. Create a project

```
forge init rootstock
```

#### 2\. Create following contracts

* a) file: src/FirstContract.sol

```
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

contract FirstContract {
    constructor () {}
}
```

* b) file: src/SecondContract.sol

```
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import "./FirstContract.sol";

contract SecondContract {
    address public immutable firstContract;
    constructor () {
        firstContract = address(new FirstContract());
    }
}
```

#### 3\. Add deploy script

file: script/Script.s.sol

```

// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import {Script, console} from "forge-std/Script.sol";
import "../src/SecondContract.sol";

contract ReproductionScript is Script {
    function setUp() public {}

    function run() public {
        vm.startBroadcast(vm.envUint("PRIVATE_KEY"));
        SecondContract secondContract = new SecondContract();
        console.log("First contract address: ", secondContract.firstContract());
        vm.stopBroadcast();
    }
}

```

#### 4\. Build the project

```
forge build
```

#### 5\. Deploy contracts

You will also need to export a private key to your environment. The key should hold funds on RSK testnet.

faucet: [https://faucet.rootstock.io](https://faucet.rootstock.io)

```
export PRIVATE_KEY=0x...
```

Run:

```
forge script script/Script.s.sol --rpc-url https://public-node.testnet.rsk.co --broadcast --legacy
```

## Expected Behaviour

The contract should print the same address for `firstContract` when called from the script, and when called from the command line after deployment.

You should see output like this

```
== Logs ==
  First contract address:  0x4dA6e6cF4776a10968dD6b3BBB98C4788F02599d

...

##### 31
✅  [Success]Hash: 0x7c191fe7f74307d9945aed5ebb5ab2c4bee9e01bfd807ab6978c26db39f3e174
Contract Address: 0x2e73866C682ffc623A868Af8a94FBC85cff1999b
Block: 4978159
Gas Used: 136141
```

Then:

```
cast c --rpc-url https://public-node.testnet.rsk.co 0x2e73866C682ffc623A868Af8a94FBC85cff1999b "firstContract()"
```

This will print a different address than the one printed by the == Logs == above. The address is expected to be left padded with zeroes, but the rest of the characters are different.

After running the script if you see the file: rsk-bug/broadcast/Script.s.sol/31/run-latest.json

You will see a transaction with two contracts deployed. In that json you can see the
contract addresses.

1. The contractAddress field in the tx array is for second contract
2. additionalContracts field contains address for the first contract

The contract address in the additionalContracts field is not correct and in fact does not exist onchain.

This issue is happening in case of Rootstock network (EVM compatible).
Works fine in case of ETH, polygon, Arbitrum, BSC.

#### Investigations

When you run forge script to deploy the contracts it runs the some simulations to calculate the contract addresses
before the deployment.

#### I am aware of these:

* The address for an Ethereum contract is deterministically computed from the address of its creator (sender) and how many transactions the creator has sent (nonce). The sender and nonce are RLP encoded and then hashed with Keccak-256.

References : [https://ethereum.stackexchange.com/questions/760/how-is-the-address-of-an-ethereum-contract-computed](https://ethereum.stackexchange.com/questions/760/how-is-the-address-of-an-ethereum-contract-computed)
[https://ethereum.stackexchange.com/questions/24248/how-to-calculate-an-ethereum-contracts-address-during-its-creation-using-the-so](https://ethereum.stackexchange.com/questions/24248/how-to-calculate-an-ethereum-contracts-address-during-its-creation-using-the-so)

Forge also offers deterministic deployment using create2:
[https://book.getfoundry.sh/tutorials/create2-tutorial](https://book.getfoundry.sh/tutorials/create2-tutorial)
[https://solidity-by-example.org/app/create2/](https://solidity-by-example.org/app/create2/)

#### The forge script vm simulation for contract address calculation should work for Rootstock as its working for other networks

So run-latest.json file should contain valid rootstock contract address as similiar to other networks.

#### Further investigations

I tried to compare the deployed tx on Rootstock vs BSC network:

Rootstock tx: [https://rootstock-testnet.blockscout.com/tx/0x0e83e8bb55e2ae4c31e6d236d56130d5755a6a061ec708bd1d8f3ea7c88eb361](https://rootstock-testnet.blockscout.com/tx/0x0e83e8bb55e2ae4c31e6d236d56130d5755a6a061ec708bd1d8f3ea7c88eb361)

BSC tx: [https://testnet.bscscan.com/tx/0xd3386823d686cba90512a1d10f3bfff3863cd5dfafdbb30a9fa05a81d2143c5d](https://testnet.bscscan.com/tx/0xd3386823d686cba90512a1d10f3bfff3863cd5dfafdbb30a9fa05a81d2143c5d)

See the internal transaction tab. Notice two internal txn on Rootstock vs one on bsc

Not sure if this is causing any incompatibility in forge script address simulation or calculations of contract addresses.

Even turning off simulation or i also tried passing almost all the relavent flags from foundry docs does not help to fix the issue.

### Looking for a way if forge script simulation could be fixed to produce correct contract addresses on Rootstock chain or atleast produce correct address in run-latest.json

**Comment by ahsan-javaiid** [comment]
Any thoughts foundry team: @grandizzy, @DaniPopes. Would be great hear your thoughts.

**Comment by grandizzy** [comment]
I see deployer exists on testnet https://rootstock-testnet.blockscout.com/address/0x4e59b44847B379578588920CA78fBF26C0b4956C so maybe try creating contract with same salt? See https://book.getfoundry.sh/tutorials/create2-tutorial ```In forge scripts, using new MyContract{salt: salt}() will use the deterministic deployer at [0x4e59b44847b379578588920ca78fbf26c0b4956c](https://github.com/Arachnid/deterministic-deployment-proxy).``` part
