### ISSUE TITLE
feat(cheatcodes): allow replacing `immutable` in `vm.getDeployedCode`

### ISSUE THREAD

**Issue by hcheng826** [foundry-rs/foundry#7582]
### Component

Forge

### Describe the feature you would like

 is there a way to replace a constant or immutable variable? vm.store doesn't work as they are not in storage slot. Or is there a way to mockCall to override the constructor?

My use case is that I deploy a new contract in the constructor and save the contract address as immutable variable. While in my unit test, I want to override the implementation of that contract

```Solidity
pragma solidity ^0.8.0;

contract DataExtractor {
    function extractData(bytes32 dataId) public pure returns (uint256) {
        return uint256(dataId);
    }
}

contract DataFetcher {
    address public immutable dataExtractor;

    constructor() {
        dataExtractor = address(new DataExtractor());
    }

  // other functions that use dataExtractor
}
```

**Comment by shafu0x** [comment]
how would you implement this? constants/immutables are replaced in the bytecode itself before deployment

**Comment by mds1** [comment]
Related to https://github.com/foundry-rs/foundry/pull/5718

**Comment by kbrav** [comment]
Maybe use a proxy contract for testing?  Then you can modify the immutables in the implementation contract

**Comment by grandizzy** [comment]
@hcheng826 wonder if the newly introduced `vm.mockFunction` could help here, see https://book.getfoundry.sh/cheatcodes/mock-function#mockfunction

So you basically could have the original data fetcher
```Solidity
contract DataFetcher {
    function doSomething() public returns (bool) {
        return true;
    }
}
```
a mocked one
```Solidity
contract MockDataFetcher {
    function doSomething() public returns (bool) {
        return false;
    }
}
```

and in test use mock bytecode when calling data fetcher, e.g.
```Solidity
contract DataFetcherTest is Test {
    function testMockedDataFetcher() public {
        DataFetcher fetcher = new DataFetcher();
        MockDataFetcher mock = new MockDataFetcher();
        vm.mockFunction(
            address(fetcher),
            address(mock),
            abi.encodeWithSelector(DataFetcher.doSomething.selector)
        );
        assertEq(fetcher.doSomething(), false);
    }
}
```

**Comment by Nlferu** [comment]
@grandizzy 

My response here is not really related to this topic, but I have problem implementing `mockFunction` my compiler yells that `Member "mockFunction" not found or not visible after argument-dependent lookup in contract Vm.solidity(9582)`, usually this kind of error occurs when arguments for cheatcode are not correct, any idea why I cannot use `vm.mockFunction`?

![image](https://github.com/user-attachments/assets/fc1e4085-75c0-4846-9ebb-55df8612a1e6)

**Comment by Nlferu** [comment]
@grandizzy 

Yes I did foundryup and tried multiple variants of this function but nothing works, rest of vm cheatcodes works perfectly fine, same with tests etc. it is very strange indeed...

**Comment by grandizzy** [comment]
> @grandizzy
> 
> Yes I did foundryup and tried multiple variants of this function but nothing works, rest of vm cheatcodes works perfectly fine, same with tests etc. it is very strange indeed...

hm, weird, whats' the output of `forge --version`?

**Comment by Nlferu** [comment]
@

> > @grandizzy
> > Yes I did foundryup and tried multiple variants of this function but nothing works, rest of vm cheatcodes works perfectly fine, same with tests etc. it is very strange indeed...
> 
> hm, weird, whats' the output of `forge --version`?

forge 0.2.0 (3ff3d05 2024-10-01T00:25:45.808130533Z)

**Comment by grandizzy** [comment]
> forge 0.2.0 ([3ff3d05](https://github.com/foundry-rs/foundry/commit/3ff3d0562215bca620e07c5c4c154eec8da0f04b) 2024-10-01T00:25:45.808130533Z)

do you happen to have installed `zksync-foundry` or other tools like it? could affect if so

**Comment by Nlferu** [comment]
> > forge 0.2.0 ([3ff3d05](https://github.com/foundry-rs/foundry/commit/3ff3d0562215bca620e07c5c4c154eec8da0f04b) 2024-10-01T00:25:45.808130533Z)
> 
> do you happen to have installed `zksync-foundry` or other tools like it? could affect if so

Nah didnt use `zksync` or any other related to foundry. I just wanted to test below error:
```solidity
    /// @dev Override Vote Function
    /// @notice Changes block.number into block.timestamp for snapshot
    function clock() public view override returns (uint48) {
        return Time.timestamp();
    }

    /// @dev Override Vote Function
    /// @notice Changes block.number into block.timestamp for snapshot
    function CLOCK_MODE() public view override returns (string memory) {
        // Check that the clock was not modified
        if (clock() != Time.timestamp()) revert ERC6372InconsistentClock();

        return "mode=timestamp&from=default";
    }
```

by mocking function from corruptedClock contract, which returns wrong value for clock()

**Comment by grandizzy** [comment]
I see reinstalling forge worked from others, maybe you could give it a try too https://github.com/foundry-rs/forge-std/issues/428

**Comment by hcheng826** [comment]
@grandizzy thanks for the reply here! Yes I think `vm.mockFunction` would fulfill my need. This is super helpful. Appreciate it!

**Comment by Nlferu** [comment]
> I see reinstalling forge worked from others, maybe you could give it a try too [foundry-rs/forge-std#428](https://github.com/foundry-rs/forge-std/issues/428)

@grandizzy 

Thanks a lot!! That worked!

**Comment by grandizzy** [comment]
> @grandizzy thanks for the reply here! Yes I think `vm.mockFunction` would fulfill my need. This is super helpful. Appreciate it!

going to optimistically close this per comment above and sample posted that use `vm.mockFunction` to change contract impl, please reopen if you hit scenarios where the existing cheatcode does not work. thank you!
