### ISSUE TITLE
Where's the default priority gas price=3gwei set in cat send?  Could you document all default values and alert people in the `cast send --help`? blindly calling caused much more spent in gas, 1000x times more than in Metamask

### ISSUE THREAD

**Issue by tx0c** [foundry-rs/foundry#7584]
wonder where's the default priority-gas-price set? I was calling cast send blindly without a gas price cap, then found it costs 1000x times gas cost than the regular Metamask transaction gas cost, then I read again from etherscan to compare where was the gas cost spent, found the `cast send` was using `Max Priority: 3 Gwei`, while most other regular Metamask transactions were using `0.0009409gwei`, then I tried again with

```console
    $ cast send --priority-gas-price=0.0009409gwei ...
```

which can indeed makes comparable gas cost transactions to Metamask,

_Originally posted by @tx0c in https://github.com/foundry-rs/foundry/issues/2134#issuecomment-2041248606_

Could you document all default values and alert people in the `cast send --help`?

**Comment by onbjerg** [comment]
It is estimated using the provided RPC URL

**Comment by tx0c** [comment]
no, it's not right @onbjerg ; the estimation RPC call only gives the base gas price, it does not give priority gas price,

- https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_gasprice
- https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_estimategas

**Comment by tx0c** [comment]
as a workaround, I always call cast send with `--priority-gas-price=1wei` just put the minimum 1wei in priority instead of 3gwei,

    $ cast send --priority-gas-price=1wei --gas-price=0.1gwei

it works saving gas; but I believe the cast tool need a fix
