### ISSUE TITLE
docs(`forge script`): improve `Mac Mismatch` error referring to failure to decrypt key of keystore

### ISSUE THREAD

**Issue by PatrickAlphaC** [foundry-rs/foundry#7592]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (0c961f7 2024-04-07T00:19:01.787620000Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Intel)

### Describe the bug

Deploying contracts with `--account xxx --sender xxx` doesn't work with multi-contract deployments. 

Running this:

```
forge script script/DeployTokenBridges.s.sol --account defaultKey --sender MY_ADDRESS --broadcast --verify
```

On a script with `vm.createSelectFork(vm.rpcUrl("xxxx"));` to deploy to 2 chains failed with:

```
Error: 
Mac Mismatch
```

However, doing a "regular" deploy with `--private-key` worked fine:

```
forge script script/DeployTokenBridges.s.sol --private-key xxxx --broadcast --verify
```

I'm assuming there is an issue with getting the accounts when working on multiple chains?

**Comment by klkvr** [comment]
`Mac Mismatch` error usually means that you've entered a wrong password for a keystore

**Comment by PatrickAlphaC** [comment]
ah.... is there a way we can have that as the error? Perhaps "failed to decrypt key"?

**Comment by fabriziogianni7** [comment]
Having the same issue, and I'm actually putting the correct password

**Comment by leovct** [comment]
Hi @zerosnacks, I'd like to tackle this issue.
