### ISSUE TITLE
Function `vm.keyExistsJson` not found in openzepplin contracts

### ISSUE THREAD

**Issue by L0GYKAL** [foundry-rs/foundry#7602]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (14daacf 2024-04-09T00:16:23.595685880Z)

### What command(s) is the bug in?

forge compile

### Operating System

Linux

### Describe the bug

I installed the [Openzeppelin Foundry upgrades librairy](https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades). And I'm using the function `Upgrades.deployBeacon(...)` from `lib/openzeppelin-foundry-upgrades/src/Upgrades.sol` to deploy an upgradable contract but the function `vm.keyExistsJson` cannot be found in `lib/openzeppelin-foundry-upgrades/src/internal/Utils.sol:83:14`.

![image](https://uploads.linear.app/f2544f8c-2bdf-42c2-a891-97db14e1d6ff/806888ec-b750-4835-8fc0-d13358d5b797/451b9441-1e3d-4135-a2c2-d7d21ab6b921?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2YyNTQ0ZjhjLTJiZGYtNDJjMi1hODkxLTk3ZGIxNGUxZDZmZi84MDY4ODhlYy1iNzUwLTQ4MzUtOGZjMC1kMTMzNThkNWI3OTcvNDUxYjk0NDEtMWUzZC00MTM1LWEyYzItZDdkMjFhYjZiOTIxIiwiaWF0IjoxNzEyNjYwMzE1LCJleHAiOjMzMjgzMjIwMzE1fQ.UNXzjKhSVpVwvxQYgX5kZ1fbPxx8PahuLhTmkRnm7C0)

**Comment by zerosnacks** [comment]
You will need to update `forge-std` to v1.8.0 or later as this is a new feature introduced in that version.

For instructions see: https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/issues/33#issuecomment-2027431016

**Comment by L0GYKAL** [comment]
Thank you, it solved my problem!
