### ISSUE TITLE
Fix multi-chain gas estimation

### ISSUE THREAD

**Issue by Evalir** [foundry-rs/foundry#7608]
There's been constant reports of people heavily overpaying on L2s to deploy their contracts. This is caused mainly due to the hardcoded tip in the ethers estimator, and the difference in how opcodes are priced between L2s. We should approach a more general solution to this, ideally by not including the tip on any L2s.

**Comment by zerosnacks** [comment]
Marking as resolved given comments in https://github.com/foundry-rs/foundry/issues/5709 + https://github.com/foundry-rs/foundry/pull/7106
