### ISSUE TITLE
feat: invariant benchmarks

### ISSUE THREAD

**Issue by Evalir** [foundry-rs/foundry#7610]
We should add benchmarks for invariants, so we have clear data on how to improve them. See [https://github.com/foundry-rs/foundry/issues/4433](https://github.com/foundry-rs/foundry/issues/4433) for more details.

**Comment by grandizzy** [comment]
Proposed action plan:
- run https://github.com/foundry-rs/foundry/issues/4590
- set up daily runner of https://github.com/grandizzy/fuzz-benchmarks/ + add more tests
- report as suggested in https://github.com/fuzz-evaluator/guidelines

**Comment by grandizzy** [comment]
going to merge with https://github.com/foundry-rs/foundry/issues/3411
