### ISSUE TITLE
[FAIL. Reason: Invalid data] assertEq()

### ISSUE THREAD

**Issue by Shantaramm** [foundry-rs/foundry#7615]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (94ae897 2023-10-31T00:16:51.730405056Z)

### What command(s) is the bug in?

forge test -vvv --via-ir

### Operating System

Linux

### Describe the bug

Hello everyone, I’m testing the contract. To the moment I used the function assertEq()
All tests passed stably, after that, I specifically began to come in this test "Invalid data".
Code and logs I add below
![image](https://github.com/foundry-rs/foundry/assets/56877750/0aee8df2-d8c7-4bfd-8c6f-5244c3202fe1)
![image](https://github.com/foundry-rs/foundry/assets/56877750/2272e669-6b1f-41d8-83ec-6284cff99757)

**Comment by LI-YONG-QI** [comment]
Are you solved this ? I also met a same problem

**Comment by Evalir** [comment]
@Shantaramm please upgrade your foundry version—it's behind by a couple of months. This should hopefully fix the issue.

**Comment by reednaa** [comment]
In case anyone had the same problem as me, you may need to reinstalled foundryup. The version I had wouldn't install the latest foundry version.

**Comment by emnul** [comment]
Upgrading my foundry version solved this issue
