### ISSUE TITLE
`forge script` seems to exceed Tenderly's etherscan API rate limit when verifying a contract

### ISSUE THREAD

**Issue by xqft** [foundry-rs/foundry#7617]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

0.2.0 (14daacf 2024-04-09T00:17:09.802796000Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

Hello. I have a big set of contracts that I want to deploy to a Tenderly devnet [following this guide](https://docs.tenderly.co/contract-verification/foundry) using `forge script`, and also verify the contracts so I can use their debugger.

The problem is that when I run my `forge script` command, the verification fails because of reaching the rate limit to their etherscan-compliant API, spamming this error message:

```bash
ERROR etherscan: Failed to deserialize response: data did not match any variant of untagged enum ResponseData res="{\"error\":{\"id\":\"e6245af1-eff4-4ae2-98e9-45745859f665\",\"slug\":\"rate_limit_exceeded\",\"message\":\"Too many requests\"}}"
```

and also sometimes:

```bash
ERROR etherscan: Failed to deserialize response: EOF while parsing a value at line 1 column 0 res=""
```

The full `forge script` command I'm using is:

```bash
forge script script/Verify.s.sol:Verify \
-vvv \
--rpc-url=$RPC_URL \
--etherscan-api-key $TENDERLY_API_KEY \
--non-interactive \
--via-ir --optimize --broadcast \
--sender $SENDER_ADDRESS \
--verify \
--verifier-url $TENDERLY_VERIFIER_URL
```

I'm not sure if this can be solved by you guys, maybe by implementing a configurable delay between the requests. Thank you in advance.

**Comment by xqft** [comment]
Hey @Joshua-Jack, really sorry for the late reply, at the time I didn't found anything but now I noticed that `forge script` has a `--delay` option, which seems exactly what I needed. I moved on from this so can't test if it works with it.

**Comment by zerosnacks** [comment]
Marking as resolved by existing `--delay` parameter

```
      --delay <DELAY>
          Optional delay to apply inbetween verification attempts, in seconds
          
          [default: 5]
```
