### ISSUE TITLE
Script panicked

### ISSUE THREAD

**Issue by obatirou** [foundry-rs/foundry#7622]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (2cb8757 2024-02-03T00:16:30.204945000Z)

### What command(s) is the bug in?

forge script script/<DEPLOY>.s.sol:<DEPLOY> --slow --ledger --sender <SENDER> --rpc-url <RPC_URL> --broadcast --legacy --resume

### Operating System

macOS (Apple Silicon)

### Describe the bug

```bash
2024-04-10T09:47:18.914329Z ERROR foundry_evm_core::fork::init: It looks like you're trying to fork from an older block with a non-archive node which is not supported. Please try to change your RPC url to an archive node if the issue persists.
The application panicked (crashed).
Message:  Unable to create fork: 
Could not instantiate forked environment with fork url: <RPC_URL>
Location: crates/evm/core/src/backend/mod.rs:434

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 9 frames hidden ⋮                               
  10: foundry_evm_core::backend::Backend::new::ha073c46d9d2741b2
      at <unknown source file>:<unknown line>
  11: foundry_evm_core::backend::Backend::spawn::{{closure}}::h1dc5538084d1da53
      at <unknown source file>:<unknown line>
  12: forge::cmd::script::executor::<impl forge::cmd::script::ScriptArgs>::prepare_runner::{{closure}}::h1885bb8eff6a21db
      at <unknown source file>:<unknown line>
  13: forge::cmd::script::executor::<impl forge::cmd::script::ScriptArgs>::execute::{{closure}}::h149a1a0c2e32216a
      at <unknown source file>:<unknown line>
  14: forge::cmd::script::cmd::<impl forge::cmd::script::ScriptArgs>::run_script::{{closure}}::h0719e5c5a60e9fce
      at <unknown source file>:<unknown line>
  15: foundry_cli::utils::block_on::h160d4257ff5ab550
      at <unknown source file>:<unknown line>
  16: forge::main::hb5e2250f229bf86d
      at <unknown source file>:<unknown line>
  17: std::sys_common::backtrace::__rust_begin_short_backtrace::h6dbcb292c72ec9d4
      at <unknown source file>:<unknown line>
  18: std::rt::lang_start::hb4419e1bbe826a02
      at <unknown source file>:<unknown line>
  19: _main<unknown>
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
```

The version of foundry is not up to date due to: https://t.me/foundry_support/52065

**Comment by klkvr** [comment]
@obatirou recently foundry release includes some fixes for signers, could you please try if upgrading to latest nightly solves this and hw wallets issues?

**Comment by obatirou** [comment]
> @obatirou recently foundry release includes some fixes for signers, could you please try if upgrading to latest nightly solves this and hw wallets issues?

@klkvr After a retry the issue disappeared. With new version of foundry (`forge 0.2.0 (72bc4f4 2024-04-08T00:17:17.438514000Z)`) , I had other problems shared in the tg https://t.me/foundry_support/52063
Since this one, I do not see improvements on this side  by looking at commits (might miss something)
As I am trying to have reproductible steps for important deployments, I will stay for now with forge 0.2.0 (2cb8757 2024-02-03T00:16:30.204945000Z)

**Comment by zerosnacks** [comment]
Marking this issue as resolved

@obatirou please open additional issues of things you run into or tag me in existing issues that are currently preventing you from upgrading your Foundry version (if this is still the case)
