### ISSUE TITLE
bug: `vm.expectRevert(customError.selector)` not matching the error selector emitted by the contract

### ISSUE THREAD

**Issue by alfheimrShiven** [foundry-rs/foundry#7629]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (72bc4f4 2024-04-08T00:17:17.438514000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

I have a custom error defined in my contract:
`error Issuance__ProtocolInvariantBroken(uint256, uint256);`

When getting the error selector by running `forge inspect contractName errors`
`"Issuance__ProtocolInvariantBroken(uint256,uint256)": "eb4a71b0"`

Now I have a test which `expectRevert(Issuance__ProtocolInvariantBroken.selector)` but on running the test, the error selectors don't seem to match, even though the log shows the same selector as above `eb4a71b0`

Logs:
```
[Revert] Issuance__ProtocolInvariantBroken(5120, 5020)
    └─ ← [Revert] Error != expected error:  != 0xeb4a71b0
```

Ideally, since the error selectors are same `eb4a71b0`, the test should pass.

**Comment by kamuik16** [comment]
To use expectRevert with a custom [error type](https://docs.soliditylang.org/en/v0.8.11/contracts.html#errors) with parameters, ABI encode the error type.

**Comment by alfheimrShiven** [comment]
Hey @kamuik16 I want to just check the error type and not the parameter values, hence was using `vm.expectRevert(customError.selector);` as suggested in the docs [here.](https://book.getfoundry.sh/cheatcodes/expect-revert#expectrevert)

**Comment by DanL0** [comment]
Same problem here.

In forge-std/Vm.sol documentation says:
```
    /// Expects an error on next call that starts with the revert data.
    function expectRevert(bytes4 revertData) external;
```

which would indicate that selectors only need to match, but instead I error that there's no full match (wrong):
```
[FAIL. Reason: Error != expected error: 0x1deca43800000000000000000000000000000000000000000000000098a7d9b8314c0000 != 0x1deca438]
```

It should pass.

**Comment by mattsse** [comment]
@DanL0 do you have a repro for this?

fyi @klkvr

**Comment by DanL0** [comment]
https://github.com/foundry-rs/forge-std/blob/master/src/Vm.sol#L1735 - here it says if you use bytes4 it will match selector only, but actually in test cases of ExpectRevert in this repository I haven't found a test case that would document such behavior.

Also this feature request: https://github.com/foundry-rs/foundry/issues/3725 isn't closed - therefore it seems it's not implemented?

It seems documentation of Vm.sol is misleading.

**Comment by DanL0** [comment]
Reproducing is super easy. Please confront this repository:

https://github.com/DanL0/forge-expect-revert-error

With this documentation:
https://github.com/foundry-rs/forge-std/blob/master/src/Vm.sol#L1734

cc @mattsse @alfheimrShiven
