### ISSUE TITLE
feat(`cheatcodes`): add a `vm.getArtifactPath` cheatcode that gets the artifact path for a given contract address

### ISSUE THREAD

**Issue by sam-goldman** [foundry-rs/foundry#7634]
### Component

Forge

## Problem

At Sphinx, it's necessary for us to programmatically find the artifact that corresponds to each contract deployment in the user's Forge script. This is currently a complicated process that involves iterating over build info files and checking for a bytecode match. This has a couple significant drawbacks:

* Build info files are inherently large, so reading them from the file system is very slow.
* We've essentially re-implemented a version of Foundry's [`diff_score` function](https://github.com/foundry-rs/foundry/blob/0c961f742a0a567edf4618b9e6f12d286bc3a51c/crates/common/src/contracts.rs#L89) to match the bytecode in an artifact to the bytecode deployed in the user's script.

We could remove all of this logic if Foundry provides a cheatcode that returns an artifact path given a contract's address or bytecode.

## Solution

We propose a new cheatcode, `getArtifactPath`, with the following interface:
```sol
/// Gets the artifact path for the given contract address.
function getArtifactPath(
    address contract
) external view returns (string memory artifactPath);
```

Under the hood, this cheatcode would get the deployed bytecode for the given address, then use Foundry's [`diff_score` function](https://github.com/foundry-rs/foundry/blob/0c961f742a0a567edf4618b9e6f12d286bc3a51c/crates/common/src/contracts.rs#L89) to find the artifact that matches the deployed bytecode. (I'm not very familiar with Foundry's codebase, but I imagine the implementation would resemble that description).

We'd be happy to implement this cheatcode ourselves as long as we have the green light from the Foundry devs. cc @mattsse @klkvr

**Comment by mattsse** [comment]
I think this makes sense, this should basically be a part of `getCode("contract name")`, right @klkvr ?

I can see this being useful
