### ISSUE TITLE
`blobhash()` returns 0 on a `eth_estimageGas` call with blobs on anvil

### ISSUE THREAD

**Issue by nand2** [foundry-rs/foundry#7636]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (440ec52 2024-04-11T00:18:58.806922049Z)

### What command(s) is the bug in?

anvil

### Operating System

Linux

### Describe the bug

Hi!

On anvil, making an `eth_estimageGas` call with blobs AND his versioned hashes, `blobhash()` returns 0 instead of the expected hash.

```json
{"method":"eth_estimateGas","params":[{"blobVersionedHashes":["0x011e33a0244ea223b4b95c941d0d0dcd203108afe481134ec1ff03bfbc9d755e"],"blobs":["0x001f8b0......"],"data":"0xf7365f37....","from":"0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266","maxFeePerBlobGas":"0x2","maxFeePerGas":"0x439b15ef","maxPriorityFeePerGas":"0x3b9aca00","nonce":"0x2f","to":"0x67d269191c92caf3cd7723f116c85e6e9bf55933","value":"0xffcb9e57d4000"}]}
```

Calling a method with `require(blobhash(0) != 0, "failed to get blob hash");` will revert.

Thanks!

**Comment by klkvr** [comment]
hey @nand2 can you still reproduce this? For me locally mentioned example works

since you opened issue Anvil received much better Cancun support, so this is likely already fixed
