### ISSUE TITLE
`Error: Multiple matching artifacts found` upon testing w/ latest nightly version

### ISSUE THREAD

**Issue by Brean0** [foundry-rs/foundry#7641]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (440ec52 2024-04-11T00:22:09.585245000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

With foundry [nightly-440ec525deb00b4dca138794865c27d1e8ea4d01](https://github.com/foundry-rs/foundry/releases/tag/nightly-440ec525deb00b4dca138794865c27d1e8ea4d01) and above, whenever I run my tests, I get an `Multiple matching artifacts found` error. Upon reverting my foundry to [nightly-f625d0fa7c51e65b4bf1e8f7931cd1c6e2e285e9](https://github.com/foundry-rs/foundry/releases/tag/nightly-f625d0fa7c51e65b4bf1e8f7931cd1c6e2e285e9) and before, the tests pass. 

Specifically, the setup breaks when I call `deployCode()` on an contract that has multiple artifacts (that are not matching). 

The line in it's full context can be seen [here.](https://github.com/BeanstalkFarms/Beanstalk/blob/ad9df31178740e775a07622eecf37abed631a5e1/protocol/test/foundry/utils/BeanstalkDeployer.sol#L68)

Error code: 
<img width="1491" alt="image" src="https://github.com/foundry-rs/foundry/assets/90539204/17996d50-db09-438f-a871-3cd9c8753cbb">

Artifacts:
<img width="558" alt="image" src="https://github.com/foundry-rs/foundry/assets/90539204/336cc55d-f254-4d01-8ea2-ea70eaca8139">

after running `foundryup -v nightly-f625d0fa7c51e65b4bf1e8f7931cd1c6e2e285e9 && forge test`, the tests pass.

**Comment by klkvr** [comment]
We've recently added validation and more checks for `getCode` cheatcodes so it is now more sensitive to ambiguous inputs. It seems that your `GaugePointFacet.sol` file contains 2 contracts (interface and actual contract), thus this error occurs.

You can change this line to `deployCode("GaugePointFacet")` or `deployCode("GaugePointFacet.sol:GaugePointFacet")` and it should fix the issue
