### ISSUE TITLE
Anvil API test - can_remove_pool_transactions fails on master

### ISSUE THREAD

**Issue by mw2000** [foundry-rs/foundry#7645]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What command(s) is the bug in?

cargo test anvil

### Operating System

macOS (Apple Silicon)

### Describe the bug

The anvil API test `can_remove_pool_transactions` is failing on the master branch. This is testing whether there is an initial pending transaction present.

**Comment by mattsse** [comment]
cc @yash-atreya

**Comment by yash-atreya** [comment]
@mw2000 I'm unable to reproduce this, it's working for me on the latest commit bdc04c278f8. Anyways, we're migrating this code to Alloy currently.

**Comment by mw2000** [comment]
@yash-atreya just double checked commits and it seems to still be failing on the `bdc04c2` commit for me. No worries if not able to reproduce and have future plans to migrate to alloy.

**Comment by zerosnacks** [comment]
Marking as resolved as these tests have been passing since the migration to Alloy

Feel free to re-open if you are still experiencing issues with this @mw2000
