### ISSUE TITLE
feat(forge): add command to check solc autodetected version

### ISSUE THREAD

**Issue by izcoser** [foundry-rs/foundry#7656]
### Component

Forge

### Describe the feature you would like

Foundry has a config which is auto detect solc version. It defaults to true and when you type forge build, it detects the appropriate newest allowed version and uses that.

I propose you add a "forge detect-sol" command which spits out the detected version.

**Comment by kamuik16** [comment]
hey @mattsse! I would like to try this, but I need help with how to get the compile version if I have the root of the project?

**Comment by izcoser** [comment]
@kamuik16 Just to clarify, this feature is already built in, just not exposed as a command. So ideally you'd just find where this happens in the code.

I have no Rust experience and would take a while to learn this project's structure, which is why I didn't come up with a PR straight away.

**Comment by kamuik16** [comment]
> @kamuik16 Just to clarify, this feature is already built in, just not exposed as a command. So ideally you'd just find where this happens in the code.
> 
> I have no Rust experience and would take a while to learn this project's structure, which is why I didn't come up with a PR straight away.

I was asking for that function only, the project is pretty large.

**Comment by mattsse** [comment]
it's likely we need some helpers for this type

https://github.com/foundry-rs/compilers/blob/ce808f4a81d953b571b5dd823a74fdc3260c1441/src/resolver/mod.rs#L462-L468

the way this is used during the compilation step is:

https://github.com/foundry-rs/compilers/blob/ce808f4a81d953b571b5dd823a74fdc3260c1441/src/compile/project.rs#L138-L147

but for this command we'd need to do this ourselves: resolve the project's graph, then the versions and print them

**Comment by Piyushsahu99** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/foundry).

### My background and how it can be leveraged
I have experience with JavaScript and Python, along with a solid understanding of Solidity. My background in open-source projects equips me to effectively implement features and contribute to documentation. I can leverage my skills to enhance the Foundry toolset, ensuring clear communication and functionality for developers.

### How I plan on tackling this issue
I would start by reviewing the existing Foundry codebase to understand how the solc version detection is implemented. Then, I would create a new command, forge detect-sol, that retrieves and displays the detected solc version. After implementing the feature, I would write tests to ensure its functionality and verify that it works seamlessly with the existing command structure.
