### ISSUE TITLE
Curve Tricrypto Pool reverts when external functions are called

### ISSUE THREAD

**Issue by th3outcast** [foundry-rs/foundry#7658]
On calling the Curve Tricrypto Pool - `0x7f86bf177dd4f3494b841a37e810a34dd56c829b`, foundry reverts with an `EvmError`

### Foundry version
```bash
$ forge --version
forge 0.2.0 (89f0fb9 2024-04-14T00:20:50.727844499Z)
```

### Test
```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import "forge-std/Test.sol";

interface CurveTricrypto {
   function gamma() view external returns (uint256);
}

contract CurveTest is Test {
    function testExternalCall() public {
        uint256 ret = CurveTricrypto(address(uint160(728046774191597329306953719776344910502317294235))).gamma();
        console.logUint(ret);
    }
}
```

`Note`: I converted the address to decimal, because an error kept on popping up. As you can see from the following output, it doesn't pose an issue when resolving the address by calling this way:

```bash
$ forge test --match-test testExternalCall -vvvv --rpc-url https://eth-mainnet.g.alchemy.com/<personal_endpoint>
[FAIL. Reason: EvmError: Revert] testExternalCall() (gas: 9079256848778899283)
Traces:
  [9079256848778899283] CurveTest::testExternalCall()
    ├─ [9079256848778896414] 0x7F86Bf177Dd4F3494b841a37e810A34dD56c829B::gamma()
    │   └─ ← [NotActivated] EvmError: NotActivated
    └─ ← [Revert] EvmError: Revert

Suite result: FAILED. 0 passed; 1 failed; 0 skipped; finished in 4.03s (749.27ms CPU time)

Ran 1 test suite in 6.95s (4.03s CPU time): 0 tests passed, 1 failed, 0 skipped (1 total tests)
```

The address being called is correct, opening this address up on [etherscan](https://etherscan.io/address/0x7f86bf177dd4f3494b841a37e810a34dd56c829b#code) also shows the correct tricrypto pool, here is the function I'm calling - taken directly from etherscan:

```vyper
@view
@external
def gamma() -> uint256:
    """
    @notice Returns the current pool gamma parameter.
    @return uint256 gamma param.
    """
    return self._A_gamma()[1]
```

So I know I'm calling the right function, but I have no idea why it keeps failing. And this is not because of my rpc endpoint as calling a Uniswap V3 pool works in my testing.

**Comment by santipu03** [comment]
I just had a similar issue trying to test with an Optimism fork and I solved it with the following command:

```
--evm-version cancun
```

**Comment by th3outcast** [comment]
@santipu03 Thanks mate, this worked for me too!

**Comment by NateBrune** [comment]
This worked for me too!
