### ISSUE TITLE
Vscode extension JuanBlanco.solidity cannot be installed in the image built from alpine-glibc

### ISSUE THREAD

**Issue by louislung** [foundry-rs/foundry#7659]
### Component

Other (please describe)

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (4a91072 2024-03-01T01:07:50.445228968Z)

### Operating System

Linux

### Describe the bug

Foundry image are built `FROM docker.io/frolvlad/alpine-glibc:alpine-3.16_glibc-2.34`
However, vscode extension `JuanBlanco.solidity` cannot be installed in this image

**Comment by zerosnacks** [comment]
@louislung could expand a bit more on your specific use case?

**Comment by louislung** [comment]
My mistake, the extension can be installed on foundry image without any problem

**Comment by louislung** [comment]
For whoever bump into this issue, it is because the foundry-rs image support only amd64, and if you're using a Macbook with M1 chip, this issue happens.
