### ISSUE TITLE
I got an error when I make cast send command

### ISSUE THREAD

**Issue by ABDOGH98** [foundry-rs/foundry#7665]
When I try to make this command cast send --rpc-url "http://94.237.62.195:44737/rpc" --private-key 0x*****b5f312b946890bc3256199b2570dded16e18a8336eeef3cfae0f8a***** 0x50A236495200fF4C70ebfd77EE01dC606c159857 "attack(uint256)" 1000 I got the next error
![image](https://github.com/foundry-rs/foundry/assets/63199884/c2a9a2df-8f2e-4016-9dd8-92bd98be0f7c)

**Comment by mattsse** [comment]
hmm, looks like the server uses an outdated format and expects `data` instead of `input`, do you know what client this is? `web3_clientVersion`

maybe should set both input and data fields

**Comment by ABDOGH98** [comment]
@mattsse no I don't know
you have a proposition how to set them??

**Comment by DaniPopes** [comment]
That was referring to foundry setting both input and data. Can you please run
```bash
cast rpc web3_clientVersion --rpc-url ...
```
with the RPC URL and post the result?

**Comment by ABDOGH98** [comment]
@DaniPopes It return `"anvil/v0.1.0"`

**Comment by DaniPopes** [comment]
That is a very outdated version of anvil, please update it or use another rpc

**Comment by ABDOGH98** [comment]
Thank you @DaniPopes
