### ISSUE TITLE
`forge verify-bytecode` panics

### ISSUE THREAD

**Issue by QGarchery** [foundry-rs/foundry#7667]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (1ca9b85 2024-04-15T02:34:32.892525726Z)

### What command(s) is the bug in?

forge verify-bytecode

### Operating System

Linux

### Describe the bug

When trying to run `forge verify-bytecode` on Morpho Blue it panics with:
![Screenshot from 2024-04-15 10-46-13](https://github.com/foundry-rs/foundry/assets/22668539/7606e908-eed8-43e0-ae1c-545c5b2fd0d9)

Reproduce on [morpho-blue](https://github.com/morpho-org/morpho-blue) at last commit on main `470a6871b3eaa56e94efdc2ee15b873c5f03e086`, and run the following command:
`forge verify-bytecode --rpc-url $ETHEREUM_RPC --constructor-args 0xcBa28b38103307Ec8dA98377ffF9816C164f9AFa 0xBBBBBbbBBb9cC5e90e3b3Af64bdAF62C37EEFFCb src/Morpho.sol:Morpho --verification-type partial` (with your own `ETHEREUM_RPC`)

**Comment by zerosnacks** [comment]
cc @yash-atreya

**Comment by yash-atreya** [comment]
@QGarchery Try setting the etherscan config in foundry.toml like so https://book.getfoundry.sh/reference/config/etherscan?highlight=ETHERSCAN#etherscan

**Comment by mds1** [comment]
To be fair we can make this not rely on block explorers if:
1. All required inputs are provided by the user, and
2. We're ok with only verifying runtime code

We can also verify creation code but finding creation code is harder and RPC intensive (binary search over blocks to find deployment block, iterate through each tx, trace tx find where it was deployed(
