### ISSUE TITLE
bug(`forge test`): Arbitrum fork test gets stuck after compilation even when tried with multiple rpc's

### ISSUE THREAD

**Issue by viraj124** [foundry-rs/foundry#7671]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (1ca9b85 2024-04-15T02:39:24.309564000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Intel)

### Describe the bug

Hi

I am trying to run fork tests and forking arb mainnet, I tried using public, infura, alchemy rpc's  but my test get's stuck after compilation and I see no logs

I even set the etherscan key before running the test with `ETHERSCAN_API_KEY=my_key` but that didn't work too

so was wondering if there is a fix for this since my github actions also run the same tests but I don't see a problem there

thanks

**Comment by DaniPopes** [comment]
Is it possible that you have a very big / infinite loop, or that it will just take a while?
Can you see any activity when running with env `RUST_LOG=debug` and with `-vvv`?

**Comment by viraj124** [comment]
> RUST_LOG=debug

no loop as soon as I remove `vm.createSelectFork("my rpc");` the test executes and I see the logs

**Comment by viraj124** [comment]
I face this issue sometimes not all times for some reason

**Comment by zerosnacks** [comment]
With what level of verbosity are you running your test? Does lowering the level (from `-vvv` to `-vv`) have an impact on the speed of the test run?

If so, a fix has been merged earlier today related to Etherscan traces not being cached correctly that largely resolves this issue.

**Comment by viraj124** [comment]
> With what level of verbosity are you running your test? Does lowering the level (from `-vvv` to `-vv`) have an impact on the speed of the test run?
> 
> If so, a fix has been merged earlier today related to Etherscan traces not being cached correctly that largely resolves this issue.

I am debugging a failing test so the test which passes works with `-vv` but the failing one is stuck again

**Comment by zerosnacks** [comment]
Hi @viraj124 are you still experiencing issues around this?

**Comment by viraj124** [comment]
No
