### ISSUE TITLE
docker image: no matching manifest for linux/arm64/v8 in the manifest list entries

### ISSUE THREAD

**Issue by davidtaikocha** [foundry-rs/foundry#7680]
### Component

-

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What command(s) is the bug in?

docker image

### Operating System

macOS (Apple Silicon)

### Describe the bug

When I trying to fetch the foundry:nightly image on my M1 mac laptop, there will be this error: `no matching manifest for linux/arm64/v8 in the manifest list entries`

**Comment by migueldingli1997** [comment]
Same here and for my colleague, both on M1 mac laptops

**Comment by migueldingli1997** [comment]
Ping 🥲

**Comment by elmariachi111** [comment]
+1, MB Air M2

**Comment by migueldingli1997** [comment]
> +1, MB Air M2; this did the trick here: #7278

This was very helpful. In my case I needed to build my Docker image with `--platform linux/amd64` and this solved my issue.

**Comment by grandizzy** [comment]
going to track arm64 support in https://github.com/foundry-rs/foundry/issues/8039
