### ISSUE TITLE
Anvil: Make LogCollector configurable via CLI

### ISSUE THREAD

**Issue by adraffy** [foundry-rs/foundry#7681]
### Component

Anvil

### Describe the feature you would like

I'd like to separate Hardhat `console.log()` messages from stdout.

Possible ideas:
- custom prefix for console.log (cli, foundry.toml)
- custom prefix for all logs
- json output option `{type, line}`
- subscribe to console address pseudo-event
 
Possibly, this feature already exists and I'm blind?

**Comment by adraffy** [comment]
If https://github.com/foundry-rs/foundry/issues/7773 is likely, possibly this feature could accompany it?

**Comment by mattsse** [comment]
I think we can make this optional

https://github.com/foundry-rs/foundry/blob/29e51120ac6e77a62242364a22108edea7274a2a/crates/anvil/src/eth/backend/mem/inspector.rs#L22-L23

with an additional CLI argument

## TODO

* Make logcollector optional
* Add a similar flag to configure this via CLI:
https://github.com/foundry-rs/foundry/blob/29e51120ac6e77a62242364a22108edea7274a2a/crates/anvil/src/eth/backend/executor.rs#L301-L301

**Comment by clowestab** [comment]
+1 for this - this would be incredibly useful functionality.

**Comment by adraffy** [comment]
If I understand this change correctly, the CLI option is only to disable the printing?

What if I want to **separate** the console.logs from the rest of the anvil output?
