### ISSUE TITLE
`logs --subscribe` broken after migration to alloy

### ISSUE THREAD

**Issue by bernard-wagner** [foundry-rs/foundry#7682]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

`cast 0.2.0 (ee47bb0 2024-04-16T00:22:03.808948000Z)`

### What command(s) is the bug in?

cast logs

### Operating System

macOS (Apple Silicon)

### Describe the bug

Something I also overlooked for https://github.com/foundry-rs/foundry/commit/f840dbd930f8d7765652ba671a997a414a4bae78

When using `cast logs --subscribe` with a valid WebSocket endpoint a `subscriptions are not available on this provider` error is always returned.

Alloy uses downcasting to determine whether a Transport implements `PubSubFrontend`, however, this doesn't work for  `RetryBackoffService<RuntimeTransport>` and other towers. 

https://github.com/alloy-rs/alloy/blob/3ac4df34d18dc3c523e552a2590de55361cff0d2/crates/provider/src/provider.rs#L174

**Comment by mattsse** [comment]
@DaniPopes what ca we do here?
