### ISSUE TITLE
Add `personal_sign` as alias of `eth_sign` in `anvil`

### ISSUE THREAD

**Issue by efstajas** [foundry-rs/foundry#7683]
### Component

Anvil

### Describe the feature you would like

We use `anvil` as a local testnet for our app's E2E tests. It works great for this, but unfortunately we ran into a bit of a roadblack when we added a new feature that makes use of signed messages for authentication with a backend. We call `personal_sign` on the user's wallet to create these signatures, and when doing so while connected to anvil's RPC, it throws: ```Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":46,\"error\":{\"code\":-32601,\"message\":\"Method not found\"}}"```

I assume this is simply a case of the `personal_sign` method not being implemented. Is there any way it could be, or is there some workaround available today already? Thanks!

**Comment by zerosnacks** [comment]
Hi @efstajas

I think `personal_sign` is available as `eth_sign` in Anvil.

From: https://docs.metamask.io/wallet/how-to/sign-data/#use-personal_sign

```
Some other signers implement personal_sign as eth_sign, because the Go Ethereum client changed the behavior of their eth_sign method. Because MetaMask supports existing applications, MetaMask implements both personal_sign and eth_sign. You might need to check what method your supported signers use for a given implementation.
```

**Comment by efstajas** [comment]
I see, thanks a lot. We should be able to work around the issue by just manually calling `eth_sign` instead, then.

However, Ethers defaults to `personal_sign` when calling `signMessage` on a standard JsonRpcProvider: https://github.com/ethers-io/ethers.js/blob/29beb93ea76d560a129e4bc3fde6ee9c8cc887c4/src.ts/providers/provider-jsonrpc.ts#L437 That's at least one popular library expecting `personal_sign` to be implemented.

Might make sense to support it in addition to `eth_sign`?

**Comment by mattsse** [comment]
functionally this is the same endpoint, right?

then we could simply add an alias for this

**Comment by efstajas** [comment]
thanks a lot all ✌️

**Comment by efstajas** [comment]
Hey @mattsse, just pulled the latest nightly and gave it a go. Unfortunately, the `personal_sign` RPC our app sends still fails: ```processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":46,\"error\":{\"code\":-32602,\"message\":\"Invalid string length\"}}", error={"code":-32602}, requestBody="{\"method\":\"personal_sign\",\"params\":[\"0x4372656174652061206e657720636f6c6c61626f7261746976652044726970204c697374206f776e6564206279203078343333323230613836313236654665326238433938613732334537336542416432443043626144632c206f6e20636861696e2049442031313135353131312e205468652063757272656e742074696d6520697320323032342d30342d31385430383a30303a33302e3437315a2e2054686520766f7465727320666f722074686973206c697374206172653a205b22307834346635396438433437454636466138666346343737426665616435363232363844633643384145225d\",\"0x433220a86126efe2b8c98a723e73ebad2d0cbadc\"],\"id\":46,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="http://127.0.0.1:8545", code=SERVER_ERROR, version=web/5.7.1)```

Here's how we trigger the request using Ether's `signMessage` method: https://github.com/radicle-dev/drips-app-v2/blob/f9d956384127cfc92d061b09a66dcb875de74c51/src/lib/utils/multiplayer/multiplayer.ts#L93

The same exact request works fine with MetaMask, Rainbow etc. (we tested with a bunch of different real wallets).

Looks like there may actually be some differences between `eth_sign` and `personal_sign` after all. Just FYI for now, happy to look deeper into this or provide further info that might help you, just lmk.
