### ISSUE TITLE
Optimizer details are ignored if optimizer is disabled

### ISSUE THREAD

**Issue by frangio** [foundry-rs/foundry#7689]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ee47bb0 2024-04-16T00:17:39.642110112Z)

### Operating System

None

### Describe the bug

PR #4427 ignores `optimizer_details` if optimizer is disabled. However, `optimizer = false` [doesn't completely disable optimizations](https://github.com/ethereum/solidity/blob/bbb7f58be026fdc51b0b4694a6f25c22a1425586/docs/using-the-compiler.rst?plain=1#L282-L284), and in order to so [additional optimizer details have to be provided](https://github.com/ethereum/solidity/blob/bbb7f58be026fdc51b0b4694a6f25c22a1425586/docs/using-the-compiler.rst?plain=1#L293-L294).

I believe #4427 should be reverted.

**Comment by mattsse** [comment]
tbh I find these comments very confusing

```
          // WARNING: Before version 0.8.6 omitting the 'enabled' key was not equivalent to setting
          // it to false and would actually disable all the optimizations.
```


```
          // The "enabled" switch above provides two defaults which can be
          // tweaked here. If "details" is given, "enabled" can be omitted.
```

so enabled false basically just a specific details configuration that can be tweaked?
however if details are set, enabled can be omitted?

**Comment by frangio** [comment]
> so enabled false basically just a specific details configuration that can be tweaked?
> however if details are set, enabled can be omitted?

That's what I understand as well. Since "enabled" is just a shortcut, if the full details are specified it becomes redundant.
