### ISSUE TITLE
Filtering CompilerInputs to only required files / Graph pruning

### ISSUE THREAD

**Issue by gakonst** [foundry-rs/foundry#769]
### Component

Forge

### Describe the feature you would like

# PRoblem

Currently, when compiling a project, all files are fed in 1 `CompilerInput`. This is unnecessary and increases our compilation times

# Solution

Generally speaking, we only need to compile the test files (any file with `IS_TEST`, ends in .`t.sol`, or has a `function test_`), and not all their deps. Doing that, will speed up our compilation times drastically, as we only will end up compiling the "rightmost edges" of the dependency dag, instead of the entire dep dag.

Taken a step further, we can trim more aggressively when the `--matches*` flags are used, (c.f. #662).

This would need some filtering at the Solidity file level, i.e. before it's fed in the compiler. We could do this either with Solang, or with a manual filter / regex command on the text.

This should only be done during `forge test`, as the other files are not really useful. During `forge build`, everything should be compiled as users may want to use subsets of the ABIs.

**Comment by mattsse** [comment]
closing as setting the solc output selection based on changed files is no being done in ethers
