### ISSUE TITLE
Type parameter of `Vm.prevrandao` as `uint256`

### ISSUE THREAD

**Issue by guidanoli** [foundry-rs/foundry#7693]
In Solidity, `block.prevrandao` is typed as `uint256`, so there is no need to type it as `bytes32`.
Even its predecessor, `block.difficulty` was typed as `uint256`, so I don't understand the shift.

**Comment by mds1** [comment]
Confirmed this is the case in the [Solidity docs](https://docs.soliditylang.org/en/latest/units-and-global-variables.html#block-and-transaction-properties), maybe this was oversight? cc @mattsse 

<img width="712" alt="image" src="https://github.com/foundry-rs/foundry/assets/17163988/283fdf73-aca0-45f3-bd7f-46d9793ad89c">

Maybe we add a uint256 overload to avoid breaking changes

**Comment by mattsse** [comment]
just an oversight I believe, let's overload it

internally uint256 or bytes32 doesn't matter

**Comment by guidanoli** [comment]
Thanks, guys :-)
