### ISSUE TITLE
Update to yansi 1.0

### ISSUE THREAD

**Issue by DaniPopes** [foundry-rs/foundry#7709]
### Component

Other (please describe)

### Describe the feature you would like

[`yansi 1.0`](https://crates.io/crates/yansi) was recently released with a much better API, by turning the `Paint` struct into a trait implemented on all types. This will also require updating it in [`foundry-compilers`](https://github.com/foundry-rs/compilers).

**Comment by dcb9** [comment]
Hi @DaniPopes, I'd like to take this as a good start to be familiar with foundry

**Comment by mattsse** [comment]
cool,
we also need the same thing in the compilers repo

https://github.com/foundry-rs/compilers/blob/f58ff011f234bac39dd0a9c79420c7b894988597/Cargo.toml#L44

**Comment by dcb9** [comment]
thanks, yeah I'll start with [foundry-compilers](https://github.com/foundry-rs/compilers) first

**Comment by dcb9** [comment]
according to the update https://github.com/ctron/colored_json/pull/10, we do not need to check the platform, so I'll just remove the code and update the doc 
https://github.com/foundry-rs/foundry/blob/21b3346bc441505d06e15a758d57fe556fc51756/crates/cli/src/utils/mod.rs#L211-L221

**Comment by mattsse** [comment]
fyi release a new foundry-compilers patch
