### ISSUE TITLE
cast performance degradation

### ISSUE THREAD

**Issue by drortirosh** [foundry-rs/foundry#7712]
### Component

Cast

### Have you ensured that all of these are up to date?

- [x] Foundry
- [X] Foundryup

### What version of Foundry are you on?

cast 0.2.0 (63072be 2024-04-18T00:17:28.731499000Z)

### What command(s) is the bug in?

cast cs

### Operating System

macOS (Apple Silicon)

### Describe the bug

`cast cs` becomes painfully slow - taking **1.5 SECONDS** to connect to "localhost"

For some reason, it scans the files in the current folder, which happened to have some ~200k files (heavy node_modules)
The workaround was to run it in a **another folder**.

**Comment by DaniPopes** [comment]
We recursively search every file in the current directory to auto detect remappings if none are provided
1. [`ProjectPathsConfigBuilder::build_with_root`](https://github.com/foundry-rs/compilers/blob/938e4174dfb68692264619e97c8ce6fa23c9ff07/src/config.rs#L735)
2. [`Remapping::find_many`](https://github.com/foundry-rs/compilers/blob/00040e2aa5b1c98e5b407c1b54407351ab9ff67e/src/remappings.rs#L204)

cc @mattsse @klkvr

**Comment by mattsse** [comment]
closing this in favor of #7715
