### ISSUE TITLE
cast command rpc perf improvements 

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#7715]
### Component

Cast

### Describe the feature you would like

currently a bunch of cast commands resolve the config entirely because Config comes with a bunch of helpers to get the provider

https://github.com/foundry-rs/foundry/blob/358107683da49f4f57b8ff7123c5e119af7d9544/crates/cast/bin/main.rs#L279-L279

which also resolves remappings and nested toml files

https://github.com/foundry-rs/foundry/blob/358107683da49f4f57b8ff7123c5e119af7d9544/crates/config/src/lib.rs#L1658-L1664

we don't need any of this and only need to check if the rpc args has an alias as --rpc-url

https://github.com/foundry-rs/foundry/blob/358107683da49f4f57b8ff7123c5e119af7d9544/crates/cast/bin/main.rs#L279-L279

this can be improved by adding a rpcOpts -> Config mode that only loads the local foundry.toml file and nothing else

## TODO
* add a helper function for rpcOpts  -> Provider by checking if there's a HTTP or ws URL provided, if not we go through the config but don't resolve remappings or nested tomls

**Comment by drortirosh** [comment]
1. You could lazily resolve remappings, (cast command don't use remappings at all) 
2. Rethink if remappings if all indirectly referenced projects is required.. I have a project with 4-5 levels deep node_modules. I don't know any except the top level, so I wouldn't want those implicitly included modules be considered
