### ISSUE TITLE
bug: `forge script --verify --resume` fails without cache?

### ISSUE THREAD

**Issue by KholdStare** [foundry-rs/foundry#7719]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (63072be 2024-04-18T00:17:31.886906635Z)

### What command(s) is the bug in?

forge script --verify --resume

### Operating System

Linux

### Describe the bug

Recently polygon testnet switched from polygon mumbai to amoy, and in the meantime polygonscan was not available.

We deployed our contracts with `forge script --broadcast ...` thinking that once polygonscan rolls out support for amoy, we can just verify after the fact. Well, a week later polygonscan has support for amoy and I'm trying to verify with `forge script --verify --resume ...` and I get

```
Deployment's sensitive details not found for chain `80002`.

Context:
- "PROJECT_DIR/cache/DeployV1.s.sol/80002/dry-run/run-latest.json": No such file or directory (os error 2)
```

Welp! Is there any way to verify after the fact if I still have the broadcast logs but not the cache?

**Comment by jiwoongim** [comment]
Someone please take a look at this issue!
The logs aren't being parsed properly on polygonscan amoy because the contracts haven't been verified.

**Comment by zerosnacks** [comment]
The `--resume` flag here relates to the resuming of the transaction broadcasting, not the resuming of the verification.
One way to resolve this would be run `forge script --verify` **without** the `broadcast` flag.

If this does not work, please re-open or leave a comment.

For now marking as `not planned`.
