### ISSUE TITLE
bug(`forge fmt`): formatter does not handle `params_first` correctly when only one param

### ISSUE THREAD

**Issue by funderbrker** [foundry-rs/foundry#7721]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### Operating System

None

### Describe the bug

When there is only one parameter and the formatter needs to wrap a header line it does not follow the definition of 'params_first'. Instead it wraps the modifiers first. This creates discontinuity throughout the code where some headers wrap arguments and some wrap modifiers.

**Comment by mattsse** [comment]
could you please provide a code example?
