### ISSUE TITLE
feat(`forge script`): associate `--chain` parameter with RPC URL in `foundry.toml`

### ISSUE THREAD

**Issue by gas1cent** [foundry-rs/foundry#7726]
### Component

Forge

### Describe the feature you would like

Heyo! I'd like to be able to configure RPC urls and Etherscan API keys in the `foundry.toml` file and then execute forge scripts without having to pass these values as arguments. For example, given the following configuration:

```
[rpc_endpoints]
mainnet = '${MAINNET_RPC}'

[etherscan]
mainnet = { key = "${ETHERSCAN_MAINNET_KEY}" }
```

I'd like to run just:
```
forge script Deploy --broadcast --verify --chain mainnet
```

Note that no `--rpc-url` or `--etherscan-key` arguments are provided, and they're unnecessary because we already have the configuration in the `foundry.toml` file. Only `chain` is required in this case.

Would something like that be possible? Thanks!

**Comment by grandizzy** [comment]
@gas1cent this should now be possible with latest forge version, please reopen if still issues. thank you!

**Comment by grandizzy** [comment]
@gas1cent ah, the flag is `--rpc-url` try `forge script CounterScript --broadcast --rpc-url mainnet`
