### ISSUE TITLE
Re-enable Windows releases

### ISSUE THREAD

**Issue by onbjerg** [foundry-rs/foundry#773]
We should investigate re-enabling Windows releases. The issue we ran into was that the runner ran out of memory when compiling - the story might be different now, but we should try and investigate why it ran out of memory in the first place so we can mitigate it in the future.

I've marked this as a chore since re-enabling is pretty simple, but figuring out why we ran out of memory/mitigating it might be time consuming

**Comment by daodao2007** [comment]
You're right, + 1
