### ISSUE TITLE
forge clone compiling issues (src mapping seems to break imports)

### ISSUE THREAD

**Issue by wighawag** [foundry-rs/foundry#7736]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (844caa8 2024-04-20T00:17:56.919599675Z)

### What command(s) is the bug in?

forge clone

### Operating System

Linux

### Describe the bug

I execute: 
```
forge clone  0x9d27527Ada2CF29fBDAB2973cfa243845a08Bd3F
```

I get

```
Compiler run failed:
Error (6275): Source "src/src/@openzeppelin/contracts/utils/introspection/IERC165.sol" not found: File not found.
 --> src/@openzeppelin/contracts/interfaces/IERC165.sol:5:1:
  |
5 | import "../utils/introspection/IERC165.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Error (6275): Source "src/src/@openzeppelin/contracts/utils/introspection/IERC165.sol" not found: File not found.
 --> src/@openzeppelin/contracts/token/ERC721/IERC721.sol:5:1:
  |
5 | import "../../utils/introspection/IERC165.sol";
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
...
```

even though the import path is fine

**Comment by mattsse** [comment]
@Troublor
@ZhangZhuoSJTU

there's an issue with nested src folders I believe

```
@openzeppelin/=src/@openzeppelin/
src/=src/src/
```
not sure how the etherscan metadata looks for this contract https://etherscan.io/address/0x9d27527Ada2CF29fBDAB2973cfa243845a08Bd3F#code

but it looks like we could write the files into the root folder and not into src to avoid the nested src, or simply strip the src

**Comment by ZhangZhuoSJTU** [comment]
Sure, we will take a look!

Thanks for reporting! 🫡🫡🫡

**Comment by ZhangZhuoSJTU** [comment]
@mattsse could you please assign this issue to either me or @Troublor? It would help us keep better track of it.
