### ISSUE TITLE
`Vm.getCode` can't find the artifact file: `No matching artifact found` 

### ISSUE THREAD

**Issue by arshan-ritual** [foundry-rs/foundry#7745]
Ever since upgrading foundry today, all of my scripts that depended on `vm.getCode` are now failing.

### `foundryup` Output
```

.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx

 ╔═╗ ╔═╗ ╦ ╦ ╔╗╔ ╔╦╗ ╦═╗ ╦ ╦         Portable and modular toolkit
 ╠╣  ║ ║ ║ ║ ║║║  ║║ ╠╦╝ ╚╦╝    for Ethereum Application Development
 ╚   ╚═╝ ╚═╝ ╝╚╝ ═╩╝ ╩╚═  ╩                 written in Rust.

.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx

Repo       : https://github.com/foundry-rs/
Book       : https://book.getfoundry.sh/
Chat       : https://t.me/foundry_rs/
Support    : https://t.me/foundry_support/
Contribute : https://github.com/orgs/foundry-rs/projects/2/

.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx.xOx

foundryup: installing foundry (version nightly, tag nightly)
foundryup: downloading latest forge, cast, anvil, and chisel
############################################################################################################ 100.0%
foundryup: downloading manpages
############################################################################################################ 100.0%
foundryup: installed - forge 0.2.0 (844caa8 2024-04-20T00:16:40.844544000Z)
foundryup: installed - cast 0.2.0 (844caa8 2024-04-20T00:16:40.855337000Z)
foundryup: installed - anvil 0.2.0 (844caa8 2024-04-20T00:16:40.869255000Z)
foundryup: installed - chisel 0.2.0 (844caa8 2024-04-20T00:16:40.915894000Z)
foundryup: done!
```

### Old foundry version
I can't tell what my older version was unfortunately.

**Comment by arshan-ritual** [comment]
relative path to artifact works, but inputs of format `SolidityFile.sol:ContractName` don't work.

**Comment by DaniPopes** [comment]
cc @klkvr

**Comment by klkvr** [comment]
Likely resolved by #7738, @arshan-ritual could you please try running foundryup tomorrow and check if issue persists? or `foundryup -b master` now

**Comment by arshan-ritual** [comment]
Yes, will do.

**Comment by klkvr** [comment]
@arshan-ritual does it work for you on latest nightly?

**Comment by DaniPopes** [comment]
Assuming this works now. Please feel free to re-open if that's not the case.

**Comment by 0xMySt1c** [comment]
still having issues with this

**Comment by klkvr** [comment]
@0xMySt1c are you using getCode for contracts under src/?

**Comment by 0xMySt1c** [comment]
@klkvr using a custom dir set in foundry.toml

**Comment by klkvr** [comment]
what are the differences between profiles?

`No matching artifact` means that it is not found in the artifacts which were recompiled. when running script, foundry only compiles everything under src/ and the script itself, so if your contract is not in this set, you might get this error

**Comment by klkvr** [comment]
> using a custom dir set in foundry.toml

you mean something like `src = "contracts"` in foundry.toml and `vm.getCode("contracts/...")` is failing?

**Comment by 0xMySt1c** [comment]
i could read the profile and change the path. let me check to see if that works

**Comment by 0xMySt1c** [comment]
> > using a custom dir set in foundry.toml
> 
> you mean something like `src = "contracts"` in foundry.toml and `vm.getCode("contracts/...")` is failing?

no using the format "Contract.sol:Contract"

**Comment by 0xMySt1c** [comment]
confirming that a path works. my current workaround will be to determine the path using the profile

**Comment by klkvr** [comment]
sorry what do you mean by "path" here? are two profiles operating on different `src` dirs?

**Comment by 0xMySt1c** [comment]
getCode("out/artifacts/Contract.sol/Contract.json") works
getCode("Contract.sol:Contract") fails

**Comment by klkvr** [comment]
can you confirm that `getCode("Contract.sol:Contract")` works on one profile, but fails on another? If so, could you please share what are the differenceses between profiles?
