### ISSUE TITLE
Smart app control has blocked part of this app.. no foundry for windows any more

### ISSUE THREAD

**Issue by C0D3O** [foundry-rs/foundry#7752]
### Component

Other (please describe)

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

/c/Users/1111e/.foundry/bin/forge: Permission denied

### What command(s) is the bug in?

/c/Users/1111e/.foundry/bin/forge: Permission denied

### Operating System

Windows

### Describe the bug

anvil runs,  forge doesn't, chisel doesn't, a deploy script doesn't, 
admin rights doesn't matter ( it's the smart app control blocking everything )

foundryup: installing foundry (version nightly, tag nightly)
foundryup: downloading latest forge, cast, anvil, and chisel
################################################################### 100.0%
Archive:  /tmp/tmp.5eK6lFTJ8g/foundry.zip
replace /c/Users/1111e/.foundry/bin/anvil.exe? [y]es, [n]o, [A]ll, [N]one, [r]ename: A
  inflating: /c/Users/1111e/.foundry/bin/anvil.exe
  inflating: /c/Users/1111e/.foundry/bin/cast.exe
  inflating: /c/Users/1111e/.foundry/bin/chisel.exe
  inflating: /c/Users/1111e/.foundry/bin/forge.exe
foundryup: downloading manpages
################################################################### 100.0%
/c/Users/1111e/.foundry/bin/foundryup: line 273: /c/Users/1111e/.foundry/bin/forge: Permission denied
foundryup: command failed: /c/Users/1111e/.foundry/bin/forge --version
foundryup: installed -
foundryup: installed - cast 0.2.0 (63fff35 2024-04-22T00:23:54.016513400Z)
foundryup: installed - anvil 0.2.0 (63fff35 2024-04-22T00:23:53.188133100Z)
/c/Users/1111e/.foundry/bin/foundryup: line 273: /c/Users/1111e/.foundry/bin/chisel: Permission denied
foundryup: command failed: /c/Users/1111e/.foundry/bin/chisel --version
foundryup: installed -
foundryup: done!

**Comment by DaniPopes** [comment]
I don't even know what this means. Closing as non-actionable windows error.
