### ISSUE TITLE
add `--background` and `stop` to allow anvil to run in the background

### ISSUE THREAD

**Issue by letmejustputthishere** [foundry-rs/foundry#7762]
### Component

Anvil

### Describe the feature you would like

I'd like to be able to run anvil in the background to make it easier to write bash scripts that include starting an anvil instance.

**Comment by DaniPopes** [comment]
The concept of background/foreground exists at the shell level.
In bash you can append `&` to send a process to the background, save the process ID with `$!`, and kill it at the end of your script with `kill`.
See https://stackoverflow.com/questions/360201/how-do-i-kill-background-processes-jobs-when-my-shell-script-exits/53714583#53714583 for more actions

**Comment by letmejustputthishere** [comment]
i'm aware of that but i want anvil to continue running after my setup bash script completed. at this point keeping track of the pid and manually using it to kill the process becomes a bit cumbersome, especially if other developers are consuming a repository (i'm building a starter repo that uses foundry).
