### ISSUE TITLE
Regression: cast call results in execution reverted on local test network

### ISSUE THREAD

**Issue by Thegaram** [foundry-rs/foundry#7764]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

N/A (see description)

### What command(s) is the bug in?

cast call, cast send

### Operating System

macOS (Apple Silicon)

### Describe the bug

There's a regression in the commit range https://github.com/foundry-rs/foundry/compare/14daacfe40565b19bdfc3b78c6cf1775f54529da...460319558e455611be1de64be8364c65c6896d15, possibly related to the alloy migration. This call to a contract (on a local test network) worked before and now it results in `execution reverted` (returned by the node).

Setup:
- Custom geth fork (https://github.com/scroll-tech/go-ethereum)
- 0x5300000000000000000000000000000000000003 is a genesis predeploy.

```shell
> docker run --rm --platform linux/amd64 ghcr.io/foundry-rs/foundry:nightly-14daacfe40565b19bdfc3b78c6cf1775f54529da "cast call --rpc-url http://host.docker.internal:8545 0x5300000000000000000000000000000000000003 owner\(\)\(address\)"

0x6f4c950442e1Af093BcfF730381E63Ae9171b87a
```

```shell
> docker run --rm --platform linux/amd64 ghcr.io/foundry-rs/foundry:nightly-460319558e455611be1de64be8364c65c6896d15 "cast call --rpc-url http://host.docker.internal:8545 0x5300000000000000000000000000000000000003 owner\(\)\(address\)"

Error: 
server returned an error response: error code -32000: execution reverted
```

My only guess is that `cast call` might encode the call incorrectly. But that's probably not right, since the same call works on another network (same deployed bytecode, same node version).

```shell
> docker run --rm --platform linux/amd64 ghcr.io/foundry-rs/foundry:nightly-460319558e455611be1de64be8364c65c6896d15 "cast call --rpc-url https://sepolia-rpc.scroll.io 0x5300000000000000000000000000000000000003 owner\(\)\(address\)"

0x6E7C2D5bFd6FCe6C71c063C947397e9033C70b4C
```

**Comment by Thegaram** [comment]
Local network chain id is `222222`.

```shell
> docker run --rm --platform linux/amd64 ghcr.io/foundry-rs/foundry:nightly-460319558e455611be1de64be8364c65c6896d15 "cast chain-id --rpc-url http://host.docker.internal:8545"                         
222222
```

Tracing works but `cast call` fails.

```shell
> docker run --rm --platform linux/amd64 ghcr.io/foundry-rs/foundry:nightly-460319558e455611be1de64be8364c65c6896d15 "cast call --rpc-url http://host.docker.internal:8545 0x5300000000000000000000000000000000000003 owner\(\)\(address\) --trace"
Traces:
  [2348] 0x5300000000000000000000000000000000000003::owner()
    └─ ← [Return] 0x0000000000000000000000006f4c950442e1af093bcff730381e63ae9171b87a


Transaction successfully executed.
Gas used: 23412
```

**Comment by Thegaram** [comment]
Possibly related other issue: `contractAddress` is missing from the response.

```shell
> forge --version
forge 0.2.0 (e01038f3 2024-04-25T00:29:53.251953000Z)

> cast send --rpc-url "$SCROLL_L1_DEPLOYMENT_RPC" --chain "$CHAIN_ID_L1" --private-key "$L1_DEPLOYER_PRIVATE_KEY" --create "$PLONK_VERIFIER_BYTECODE"

blockHash               0xa62133809b388d5201dd0f347a29b25b081727a9949296843fb1684d2ed41785
blockNumber             84
contractAddress         
cumulativeGasUsed       291152
effectiveGasPrice       13452
from                    0x2B5AD5c4795c026514f8317c7a215E218DcCD6cF
gasUsed                 291152
logs                    []
logsBloom               0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
root                    
status                  1 (success)
transactionHash         0x1a74150e3cdce1e81249acc8c35efe8094c7e49eedfe0d84eff576baf7e83f6b
transactionIndex        0
type                    2
blobGasPrice            
blobGasUsed             
to                      0x0000000000000000000000000000000000000000
```

```shell
> forge --version
forge 0.2.0 (14daacfe 2024-04-25T09:15:50.111493000Z)

> cast send --rpc-url "$SCROLL_L1_DEPLOYMENT_RPC" --chain "$CHAIN_ID_L1" --private-key "$L1_DEPLOYER_PRIVATE_KEY" --create "$PLONK_VERIFIER_BYTECODE"

blockHash               0x26a09515593ec427e2238e9a617d2dbd19adcd71b11b8c7e37777e0a3f32269e
blockNumber             571
contractAddress         0x475652655309FA7CB1397537BEe9a7fbafdC11cA
cumulativeGasUsed       3740728
effectiveGasPrice       3000000007
from                    0x2B5AD5c4795c026514f8317c7a215E218DcCD6cF
gasUsed                 3740728
logs                    []
logsBloom               0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
root                    
status                  1
transactionHash         0xe0a0c976f6b8ae736b0d4afb1d68858a22b17343984d5a142c2913a04fdb48c8
transactionIndex        0
type                    2
```

**Comment by Thegaram** [comment]
I now had the same issue (on the same query) with Anvil, so it's probably not related to my local geth fork node.
```
server returned an error response: error code -32000: execution reverted
Execution failed
```

**Comment by mattsse** [comment]
@yash-atreya please look into this, might we be related to the new `to` field behaviour

@Thegaram could you confirm that this is still an issue with the newest nightly?

**Comment by Thegaram** [comment]
Same issue on latest nightly:

```shell
> docker run --rm --platform linux/amd64 ghcr.io/foundry-rs/foundry:nightly-aa333c6bebf43cb59de34cdf40b2e2bd70d98442 "cast call --rpc-url http://host.docker.internal:8545 0x5300000000000000000000000000000000000003 owner\(\)\(address\)"
Error: 
server returned an error response: error code -32000: execution reverted
```

**Comment by hochi-ho-partior** [comment]
I had the same issue, and I can confirm that it was cast call which has a bug.
I had a diamond proxy contract which parses the msg.sig in the calldata and delegatecall a facet. I checked every input is correct and my diamond contract gives an error message `execution reverted: Diamond: Function does not exist: 0x00000000`

this can only happen when the actual calldata has a leading first 4 bytes to be 0x00000000, which clearly shows it's a bug within the cast call.

```cast call --rpc-url="http://localhost:8545/" 0xsomeaddress "lookup(string)(address,string,string[])" "input here does not matter"```

**Comment by hochi-ho-partior** [comment]
P.S. the error only happen after the 2nd May build.

**Comment by randomlogin** [comment]
I have the same problem.
```
 cast call 0xb61e0E39b6d4030C36A176f576aaBE44BF59Dc78 "0x8da5cb5b"  --rpc-url localhost:8545
```
returns 
```
Error: 
server returned an error response: error code -32603: Error: Transaction reverted without a reason string
```

While direct `evm_call` succeeds: 
```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0xb61e0E39b6d4030C36A176f576aaBE44BF59Dc78","data":"0x8da5cb5b"}, "latest"],"id":1}' -H "Content-Type: application/json" localhost:8545                                     
{"jsonrpc":"2.0","id":1,"result":"0x00000000000000000000000049bd9989e31ad35b0a62c20be86335196a3135b1"}
```


Version: cast 0.2.0 (5494c33 2024-05-31T00:17:44.737298072Z)

**Comment by mattsse** [comment]
how to reproduce this?

could you please run with `RUST_LOG=trace cast ...` and share the logs?

**Comment by randomlogin** [comment]
> how to reproduce this?
> 
> could you please run with `RUST_LOG=trace cast ...` and share the logs?

I fork mainnet using hardhat node. Cast is unable to correctly retrieve data, but plain `eth_call` can.

Reproducing:
`npx hardhat node --fork <your archive node> --fork-block-number 20018451`

Then:
```
cast call 0x79918A4389A437906538E0bbf39918BfA4F7690e  "0x8da5cb5b" --rpc-url localhost:8545
```

and rpc call:

```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0x79918A4389A437906538E0bbf39918BfA4F7690e","data":"0x8da5cb5b"}, "latest"],"id":1}' -H "Content-Type: application/json" localhost:8545
```

(Same behaviour both with alchemy and infura nodes.)

TRACE_LOG: https://gist.github.com/randomlogin/d805a5cfb2ebdf1c07ea8bf24e552060

**Comment by steinitz** [comment]
Hi,

I'm one of the students of Patrick Collins' excellent Foundry course on youtube and Cyfrin.  Some of us have been having a problem with `cast send` and `cast call` which may be related to this issue.  Patrick has asked us to "add some context" to this issue in case it might help you resolve it thoroughly.

We don't see an error, as described in this issue, but we see an incorrect result from `cast call`: always `"0x"`

One of my fellow students tells us he was getting correct results until around the beginning of May which would seem to match the dates mentioned here.

If you would like further details I'll be happy to provide them.

**Comment by Thegaram** [comment]
Hi @mattsse, the issue remains on the latest version (`cast 0.2.0 (56dbd20 2024-07-05T00:18:08.608876000Z)`). Here's one way to reproduce:

```
> cast call --rpc-url https://rpc.scroll.io "0x5300000000000000000000000000000000000002" "l1BaseFee()(uint256)"
Error: 
server returned an error response: error code -32000: execution reverted

> cast calldata "l1BaseFee()(uint256)"                                                                         
0x519b4bd3

> curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_call", "params": [{"to": "0x5300000000000000000000000000000000000002", "data": "0x519b4bd3"}, "latest"] ,"id": 1}' https://rpc.scroll.io
{"jsonrpc":"2.0","id":1,"result":"0x00000000000000000000000000000000000000000000000000000002bc48c6b3"}
```

Using `RUST_LOG=trace` I identified that the issue is that `cast` is using `input` instead of `data` in the query:
```
> curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_call", "params": [{"to": "0x5300000000000000000000000000000000000002", "input": "0x519b4bd3"}, "latest"] ,"id": 1}' https://rpc.scroll.io
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"execution reverted"}}
```

While ethereum.org [indeed lists](https://ethereum.org/en/developers/docs/apis/json-rpc/#eth_call) `input` as the correct field name, [most](https://docs.infura.io/api/networks/ethereum/json-rpc-methods/eth_call) [other](https://docs.alchemy.com/reference/eth-call) [provider](https://www.quicknode.com/docs/ethereum/eth_call) [docs](https://docs.chainstack.com/reference/ethereum-ethcall) use `data`. And based on the comments in this issue, is seems like many networks haven't adopted the new standard (`input`).

Feel free to close this issue since this is technically not an issue with Foundry.

**Comment by mattsse** [comment]
thanks for looking into this
