### ISSUE TITLE
Can't deploy contracts

### ISSUE THREAD

**Issue by mits87** [foundry-rs/foundry#7770]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e0ea59c 2024-04-24T00:17:16.344194000Z)

### What command(s) is the bug in?

forge script 

### Operating System

macOS (Intel)

### Describe the bug

Hi!

I have a small problem with contract deployments. 
Basically I have extremely basic contract:

**script/Deploy-Test.s.sol**
```
// SPDX-License-Identifier: MIT
pragma solidity 0.8.19;

import {Script} from "forge-std/Script.sol";
import {Test} from "../src/protocol/Test.sol";

contract DeployTest is Script {
    function run() external {
        uint256 privateKey = 0x....;
        vm.startBroadcast(privateKey);
        Test test = new Test();
        vm.stopBroadcast();
    }
}
```

**src/protocol/Test.sol**
```
// SPDX-License-Identifier: MIT OR Apache-2.0
pragma solidity 0.8.19;

contract Test {
    string public greet = "Hello World!";
}
```

Whenever I execute command:
```
forge script script/Deploy-Test.s.sol:DeployTest \
	--rpc-url https://white-solitary-night.arbitrum-mainnet.quiknode.pro/API_KEY \
	--broadcast \
	--legacy \
	--with-gas-price 10000000 \
	-vvvv 
```

then my deployment stuck on `Waiting for receipts` step (check screen). 
I waited few hours but nothing changed. 

Any ideas how can I deploy my contracts?

<img width="1792" alt="image" src="https://github.com/foundry-rs/foundry/assets/605186/f8979872-8451-4335-a5e0-65b860357538">

**Comment by klkvr** [comment]
Fixed by https://github.com/foundry-rs/foundry/pull/7772
