### ISSUE TITLE
Anvil panic crash on eth_estimategas

### ISSUE THREAD

**Issue by franco-gondi** [foundry-rs/foundry#7771]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e0ea59c 2024-04-24T00:19:01.227145385Z)

### What command(s) is the bug in?

anvil

### Operating System

Linux

### Describe the bug

I'm running the following command, and I'm getting a panic crash in anvil:

`cast send  --priority-gas-price 0 ...`

Anvil logs:
```
eth_estimateGas
thread 'tokio-runtime-worker' panicked at crates/anvil/src/eth/api.rs:2227:37:
Uint conversion error: Overflow(256, 282838246896581192922586059702604946914, 340282366920938463463374607431768211455)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Without the priority-gas-price parameter I'm getting the same error than [#7769](https://github.com/foundry-rs/foundry/issues/7769)

**Comment by klkvr** [comment]
is this happening in forking mode? also are you performing any balance manipulations? from the error it seems that somehow balance of a sender is `2.8e20` ether which is pretty high
