### ISSUE TITLE
vm.expectRevert results in: panic: array out-of-bounds access (0x32)

### ISSUE THREAD

**Issue by ssadler** [foundry-rs/foundry#7785]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e01038f 2024-04-25T00:19:46.228617080Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

My test looks like this:

```solidity
IBoard board = new FakeBoard();              
vm.expectRevert("invalid board");            
createBeastie(board, 100, 100, 100, 1 ether);
```

However, running that produces the unexpected result:

![image](https://github.com/foundry-rs/foundry/assets/125019/9c7f6898-515e-40ab-b78f-eff9cde378f9)

If I comment the `expectRevert` line it fails as expected:

![image](https://github.com/foundry-rs/foundry/assets/125019/6e6aef95-5dbc-4e8e-a1f9-382ada7cc082)

The `createBeastie` function is dispatching 3 calls via a sort of multicall contract: https://github.com/beastieboard/utility-contracts/blob/main/src/AuthProxy.sol

```solidity
calls[0] = AuthProxy.Call(                                                
  address(_grid),                                                         
  abi.encodeCall(IMint.mintBeastie, ""),                                  
  0, 0                                                                    
);                                                                        
                                                                          
calls[1] = AuthProxy.Call(                                                
  address(_bouncer),                                                      
  abi.encodeCall(TokenBouncer.transfer, (_token, address(0), balance)),   
  1, 0                                                                    
);                                                                        
                                                                          
calls[2] = AuthProxy.Call(                                                
  address(0),                                                             
  abi.encodeCall(Beastie.place, (board, x, y, r, "probe")),               
  0, 0                                                                    
);                                                                        
                                                                          
bytes[] memory outputs = _authProxy.proxy(calls);           // expected to fail              
```
If I make each of the calls individually in the test, then expectRevert works as expected:

```solidity
IBeastie beastie = _grid.mintBeastie("");            
_bouncer.transfer(_token, address(beastie), 10**18); 
vm.expectRevert("invalid board");                    
beastie.place(board, 100, 100, 100, "probe");        
```

![image](https://github.com/foundry-rs/foundry/assets/125019/321e2ddd-7813-4d80-80a0-13431e71b75a)

The final revert made by the proxy (only produces the OOB error in combination with the `expectRevert`):

https://github.com/beastieboard/utility-contracts/blob/main/src/AuthProxy.sol#L73

**Comment by grandizzy** [comment]
@ssadler can you provide a simple test to reproduce locally and debug the issue? thank you

**Comment by ssadler** [comment]
@grandizzy, it turns out that the bug is due to the call not being in the same function, so the expectRevert succeeds with the call being in a different function, but the subsequent code fails. Basically a gotcha, I may even have run into this one before and forgotten about it! Going to close, anyhow.
