### ISSUE TITLE
Feat: installing forge using specific commit should install to different bin dir

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#7794]
### Component

Forge, Cast, Anvil, Foundryup, Chisel

### Describe the feature you would like

```console
foundryup: warning: overwriting existing forge in /Users/janitor/.foundry/bin
foundryup: warning: overwriting existing cast in /Users/janitor/.foundry/bin
foundryup: warning: overwriting existing anvil in /Users/janitor/.foundry/bin
foundryup: warning: overwriting existing chisel in /Users/janitor/.foundry/bin
```

Installing by commit should not overwrite the default install path, in fact foundry should support versioned install paths with a latest path being symlink updated on foundryup updates.

This would allow easier orchestration for regression matrix testing in CI env for example.

**Comment by grandizzy** [comment]
in latest foundryup multiple versions can be installed and managed:
```
    -l, --list      List versions installed from built binaries
    -u, --use       Use a specific installed version from built binaries
```

please give it a try and reopen if not what you're looking for. Thank you.

**Comment by sambacha** [comment]
> in latest foundryup multiple versions can be installed and managed:
> 
> ```
>     -l, --list      List versions installed from built binaries
>     -u, --use       Use a specific installed version from built binaries
> ```
> 
> please give it a try and reopen if not what you're looking for. Thank you.

my man, thank you
