### ISSUE TITLE
Access wallet from keystore in scripts | `vm.getActiveWallet()`

### ISSUE THREAD

**Issue by PatrickAlphaC** [foundry-rs/foundry#7803]
### Component

Forge

### Describe the feature you would like

Let's say I want to use the `vm.sign` feature in foundry.

```javascript
vm.sign(private_key, digest);
```

Right now, if I've imported my wallet and am using it as a keystore, I cannot use the private key directly to sign things in my script. 

It would be great to enable this, even if it had to prompt us every time to re-sign. Perhaps something like a `vm.getWallet` API.

Full `Sign.sol`:

```javascript
// SPDX-License-Identifier: MIT
pragma solidity 0.8.24;

import {Script, console2} from "forge-std/Script.sol";

contract Sign is Script {
  function run() public {
    bytes32 message = "hi";
    Wallet memory activeWallet = vm.getWallet();
    (uint8 v, bytes32 r, bytes32 s) = vm.sign(activeWallet.privateKey, message);
    console2.log(uint256(v));
    console2.logBytes32(r);
    console2.logBytes32(s);
  }
}
```

Then, from the command line:

```
forge script script/Sign.sol --sender xxxx --account yyyy
```

**Comment by klkvr** [comment]
You can already sign payloads with wallets passed into the script by using just `vm.sign(bytes32 digest)`: https://github.com/foundry-rs/forge-std/blob/5475f852e3f530d7e25dfb4596aa1f9baa8ffdfc/src/Vm.sol#L485

the signer to use is determined in a similar way to `vm.broadcast`/`vm.startBroadcast`

**Comment by PatrickAlphaC** [comment]
Ah this is helpful! Didn't realize this. Thanks.
