### ISSUE TITLE
Forge compiles too slow

### ISSUE THREAD

**Issue by trojanMcAfee** [foundry-rs/foundry#7805]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (d431f74 2024-04-27T00:16:50.327740000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Intel)

### Describe the bug

`forge` takes a considerable amount to compile files. It's worth noticing that I'm using solidity 0.8.21 only. 

If you see the screenshot, you can see that it's taking 91 seconds to compile 20 files: 

<img width="252" alt="image" src="https://github.com/foundry-rs/foundry/assets/59457858/380dadce-617b-4b23-94a3-ecf93e52d82a">

And this is the repo that's compiling: https://github.com/trojanMcAfee/ozel-vn1

I'm on a MackBook Air retina 2019, Sonoma 14.4.1, 1,6 GHz Dual-Core Intel Core i5, 8 GB 2133 MHz.

**Comment by mattsse** [comment]
this is solc time

**Comment by trojanMcAfee** [comment]
What does that mean? That it's normal that it takes a minute and a half to compile? @mattsse

**Comment by mattsse** [comment]
that's the time the solc binary takes to compile the input with the configured settings, forge only invokes the solc binary

**Comment by trojanMcAfee** [comment]
What configured settings should I use so `forge` compiles in the milliseconds range, which is the normality, instead of minutes? @mattsse 

This is my `foundry.toml` file, if it helps: 
```js
[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path = 'forge-cache'
offline = true

[rpc_endpoints]
arbitrum = "${ARBITRUM}"
ethereum = "${ETHEREUM}"
ethereum-mocks = "${ETHEREUM}"
```

**Comment by Evalir** [comment]
@trojanMcAfee `forge` will not compile faster as it does not add any overhead. All the time you're seeing is exclusively the `solc` binary compiling all contracts.
