### ISSUE TITLE
Implement missing formatter nodes

### ISSUE THREAD

**Issue by shekhirin** [foundry-rs/foundry#781]
### Component

Forge

### Describe the feature you would like

Recently, we've merged https://github.com/gakonst/foundry/pull/201 with basic formatter functionality which includes:
- Parsing source code (respecting project structure) with [solang](https://github.com/hyperledger-labs/solang/)
- Traversing the Parse Tree and reconstructing the code on-the-go (more about architecture here: https://github.com/gakonst/foundry/blob/master/fmt/README.md)
- Reconstructing some basic nodes such as pragma directives, import directives and enum definitions

Now we need to implement code reconstruction for other nodes listed here: https://github.com/foundry-rs/foundry/blob/4367ce1c3d2c10b71350b40258766d53a94c717f/fmt/README.md?plain=1#L6-L111

I think it may be worth creating separate PR every time someone's gonna work on implementing particular node type, and I'll update permalink above with features list.

**Comment by jpopesculian** [comment]
Hi :wave: I'm looking to finish the implementation of the Visitor, but before I get started, I had a couple of questions and concerns.

## The problem

It seems that solang only supports solidity version 0.7.x and thereby doesn't respect some of the breaking changes in 0.8.x. To give a concrete example. Given the two solidity examples

`example1.sol`

```solidity
pragma solidity ^0.8.10;

contract AstExample {
    constructor() {
        (1 ** 2) ** 3;
    }
}
```

`example2.sol`

```solidity
pragma solidity ^0.8.10;

contract AstExample {
    constructor() {
        1 ** 2 ** 3;
    }
}
```

solang will provide the same Parse Tree representing `(1 ** 2) ** 3` whereas the second example without parentheses should parse to `1 ** (2 ** 3)` as shown by the example below

```rust
use solang_parser::pt::{ContractPart, Expression, SourceUnitPart, Statement};

fn get_expression(file: &str) -> Expression {
    match &solang_parser::parse(&std::fs::read_to_string(file).unwrap(), 0)
        .unwrap()
        .0
         .0[1]
    {
        SourceUnitPart::ContractDefinition(cd) => match &cd.parts[0] {
            ContractPart::FunctionDefinition(fd) => match fd.body.as_ref().unwrap() {
                Statement::Block { statements, .. } => match &statements[0] {
                    Statement::Expression(_, exp) => exp.clone(),
                    _ => panic!(),
                },
                _ => panic!(),
            },
            _ => panic!(),
        },
        _ => panic!(),
    }
}

fn main() {
    let example1 = get_expression("./example1.sol");
    match example1 {
        Expression::Power(_, left, right) => {
            // parse tree compiled (a ** b) ** c
            assert!(matches!(*left, Expression::Power(..)));
            assert!(matches!(*right, Expression::NumberLiteral(..)));
        }
        _ => panic!(),
    }
    let example2 = get_expression("./example2.sol");
    match example2 {
        Expression::Power(_, left, right) => {
            // parse tree compiled (a ** b) ** c
            assert!(matches!(*left, Expression::Power(..)));
            assert!(matches!(*right, Expression::NumberLiteral(..)));
        }
        _ => panic!(),
    }
}
```

In contrast, the output of the solc as given by

```bash
solc --combined-json ast $FILE | jq ".sources[\"$FILE\"].AST.nodes[1].nodes[0].body.statements"
```

and reduced for clarity reveals the following parsed ASTs

`example1.ast.json`

```json
[
  {
    "expression": {
      "nodeType": "BinaryOperation",
      "operator": "**",
      "leftExpression": {
        "components": [
          {
            "nodeType": "BinaryOperation",
            "operator": "**",
            "leftExpression": {
              "value": "1"
            },
            "rightExpression": {
              "value": "2"
            }
          }
        ]
      },
      "rightExpression": {
        "value": "3"
      }
    }
  }
]
```

`example2.ast.json`

```json
[
  {
    "expression": {
      "nodeType": "BinaryOperation",
      "operator": "**",
      "leftExpression": {
        "value": "1"
      },
      "rightExpression": {
        "nodeType": "BinaryOperation",
        "operator": "**",
        "leftExpression": {
          "value": "2"
        },
        "rightExpression": {
          "value": "3"
        }
      }
    }
  }
]
```

if we generate the source code from the Parse Tree we would have no generate an improper ordering of operations

## Possible solutions

I see there being two possible solutions here. We either change solang to support 0.8.x, or we use the AST from solc to implement Visitable. In the second case we would probably make an abstract AST to support multiple versions of solc, which solang could also translate too. Also in the latter case we would have to parse the comments ourselves, but that should be fairly simple.

**Comment by gakonst** [comment]
I think we should get Solang to support later solidity versions - cc @seanyoung

**Comment by seanyoung** [comment]
This is broken, let me have a look.

**Comment by onbjerg** [comment]
@rkrasiuk & @jpopesculian what is the status on this issue in particular? There are a few fmt related issues that are very broad, I'm not sure if they have been solved or if we should close and split into more actionable issues?

**Comment by rkrasiuk** [comment]
i'd say it has been completed by now. @jpopesculian anything I'm missing?

**Comment by jpopesculian** [comment]
yeah, as far as i'm aware its been implemented completely and we're just working on bugs / configuration

**Comment by gakonst** [comment]
:+1: closing
