### ISSUE TITLE
Blob fields missing from anvil genesis

### ISSUE THREAD

**Issue by Thegaram** [foundry-rs/foundry#7841]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (d495216 2024-05-03T00:21:54.426103000Z)

### What command(s) is the bug in?

anvil

### Operating System

macOS (Apple Silicon)

### Describe the bug

```shell
> anvil --hardfork cancun

> cast rpc eth_getBlockByNumber 0 false | jq .blobGasUsed
null

> cast rpc eth_getBlockByNumber 1 false | jq .blobGasUsed
"0x0"
```

**Comment by mattsse** [comment]
@yash-atreya this should be a simple fix, basically we need to set blob fields accordingly here:

https://github.com/foundry-rs/foundry/blob/233b0f245dd7c1ec030a8af73dd7460020d1a2a1/crates/anvil/src/eth/backend/mem/storage.rs#L338-L351

we also need to track this for forked chains, similar to basefee:

https://github.com/foundry-rs/foundry/blob/233b0f245dd7c1ec030a8af73dd7460020d1a2a1/crates/anvil/src/eth/backend/fork.rs#L583-L584
