### ISSUE TITLE
Foundryup should be configured using bash_profile/zprofile for macOS/Darwin

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#785]
### Component

Foundryup

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### Describe the bug

macOS/darwin treats every shell as its a login shell. i.e. any time terminal is invoked it is as an interactive login shell, or as a non-interactive shell with the --login option, it first reads and executes commands from the file /etc/profile, if that file exists. After reading that file, it looks for ~/.bash_profile or ~/.zprofile

**Comment by onbjerg** [comment]
Not entirely sure what this issue is about, but is this relevant when we rewrite in Rust? If not, we should close this

**Comment by sambacha** [comment]
> Not entirely sure what this issue is about, but is this relevant when we rewrite in Rust? If not, we should close this

macOS uses `~/.bash_profile` for shell directives/etc. It does not use `~/.bashrc` which is the correct way and the way that foundryup does it. 


```bash

# Only add foundryup if it isn't already in PATH.
if [[ ":$PATH:" != *":${FOUNDRY_BIN_DIR}:"* ]]; then
  # if macOS use bash_profile
	if [[ $PLATFORM == 'darwin'* ]]; then
		echo >>"$HOME"/.bash_profile && echo "export PATH=\"\$PATH:$FOUNDRY_BIN_DIR\"" >>"$HOME"/.bash_profile
	fi
# use bashrc everywhere else 
	# Add the foundryup directory to the path and ensure the old PATH variables remain.
	echo >>"$PROFILE" && echo "export PATH=\"\$PATH:$FOUNDRY_BIN_DIR\"" >>"$PROFILE"
fi
```

**Comment by lucas-manuel** [comment]
Close-able? @mds1

**Comment by mds1** [comment]
macOS defaults to zsh now so I think this is outdated. Closing, but @sambacha lmk if I'm wrong here and this needs to be reopened

**Comment by diyahir** [comment]
Foundry does not persist on zsh
