### ISSUE TITLE
docker pull error

### ISSUE THREAD

**Issue by edwardyu** [foundry-rs/foundry#7851]
### Component

Other (please describe)

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### Operating System

None

### Describe the bug

```
edwardyu@MacBook-Pro-4  % docker pull ghcr.io/foundry-rs/foundry:latest                                                                        
latest: Pulling from foundry-rs/foundry
no matching manifest for linux/arm64/v8 in the manifest list entries
```

Able to reproduce among multiple devs

**Comment by grandizzy** [comment]
try `docker pull --platform linux/amd64 ghcr.io/foundry-rs/foundry:latest`

**Comment by edwardyu** [comment]
Indeed this solves it, thanks!
