### ISSUE TITLE
cast wallet sign --ledger gives an "Error: \noperation `sign_hash` is not supported by the signer\n"

### ISSUE THREAD

**Issue by 0xTimepunk** [foundry-rs/foundry#7852]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (f0d9eec 2024-04-30T00:16:44.393198000Z)

### What command(s) is the bug in?

cast wallet sign --ledger 

### Operating System

macOS (Apple Silicon)

### Describe the bug

When running `cast wallet sign --ledger ....` the following is returned in the console

"Error: \noperation `sign_hash` is not supported by the signer\n"

Nothing is displayed on the ledger hardware key visor to sign.

We have ensured ledger live software is up to date and this command/script file used to work in the past so it sounds like something has changed.

Any thoughts?

**Comment by 0xTimepunk** [comment]
@mattsse @Evalir I didn't include the rest of the flags of the cast command because they are too long to add here

also I did `foundryup -C 2cb8757` to try this on an older foundry version and the exact same command works

**Comment by DaniPopes** [comment]
They are very important, please include all the flags except for the actual data if you can't put it here.
