### ISSUE TITLE
🧰 Feature: replace remappings.txt with foundry.source

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#786]
### Component

Forge, Cast, Other (please describe)

### Describe the feature you would like

# foundry.source.json - replacement for remappings.txt

TLDR: remappings.txt is encumbered by its own inadequacies. Such great rust-based tooling must be worthy of superior configuration format than the currently used one.

> 🧰 This is a working draft, your questions and critiques are most welcomed. 

[TOC]
  * [Motivation](#motivation)
    + [current format: remappings.txt](#current-format--remappingstxt)
      - [proposed format: foundry.source.json](#proposed-format--foundrysourcejson)
  * [Import Maps](#import-maps)
    + [Import Maps](#import-maps-1)
  * [Generate the import mappings](#generate-the-import-mappings)
      - [Inline Imports for contract testing](#inline-imports-for-contract-testing)

##  💡 Motivation

Replace `remappings.txt` with a new file, `foundry.source.json`

- Remappings can be auto-generated and declared
- Support for inline imports via remapping
- Support for parallelizable test running via `@Scoping`
- Support for `Resolutions` for changing a contract dependency with a user replacement
- Support for nested directory structures for monorepos
- Enable deployment a more declarative deployment process (potentially)

Here are some issues that this change can potentially solve / eliminate 

https://github.com/gakonst/foundry/issues/768 - resolutions 
https://github.com/gakonst/foundry/issues/744 - inline imports 
https://github.com/gakonst/foundry/issues/768 - scopes 

## 🚨 current format: remappings.txt

```sh
ds-test/=lib/ds-test/src/
@openzeppelin/=node_modules/@openzeppelin/
@rari-capital/=node_modules/@rari-capital/
@manifoldxyz/=node_modules/@manifoldxyz/
```

## 🛠 proposed format: foundry.source.json

Foundry Source file format would be `.json`

Note the leading :,  in the first entry which is necessary when the remapping context is empty. Otherwise the https: part would be interpreted by the compiler as the context.

> {@link https://docs.soliditylang.org/en/develop/path-resolution.html#using-urls-in-imports}

```jsonc
{
 
	"#imports": {
         ":https://github.com/sambacha/forge-scripts/": "$(pwd)/src/injected Inject.sol",
		"@openzeppelin/contracts/": "/node_modules/@openzeppelin/contracts/", // validate against: ^[a-z][-a-z0-9]{0,255}$
		 "@uniswap/v2-core/": "/node_modules/@uniswap/v2-core/",
		 "@uniswap/v3-periphery/": "/node_modules/@uniswap/v3-periphery/"
		 "@boringcrypto/boring-solidity": "git+https://github.com/boringcrypto/BoringSolidity#ccb743d4" // example using git repo
	},
	"#inline": {
            "@yearn/sdk/contracts/BaseStrategyV1.sol/": ["@scope1", "BaseStrategy"], // see Inline Imports section for more
	},
	"#resolutions": {
        "@uniswap/v2-core/contracts/interfaces/IUniswapV2Pair.sol": "src/updates/IUniswapV2Pair02.sol",
    "forge-stdlib": {  // replacing hardhat's console with a forge-stdlib version
      "stdlib/console.sol": "hardhat/console.sol"
    },
	},
  "#scopes":  {
  "tbd": "l8r"
}
```

## Import Maps

> ex. [import_map rust crate used by Deno](https://crates.io/crates/import_map)

> Note to use with esm / URL based imports

```shell=
 ?pin=BUILD_VERSON
```

### Import Maps 

Read the specification here: https://github.com/WICG/import-maps

```jsonc 
{
 "dependencies": {
      "@openzeppelin/contracts": "^4.5.0",
      "@uniswap/v2-core": "^1.0.1",
      "@uniswap/v3-periphery": "^1.4.0"
    }
}
```
## Generate the import mappings 

Generating a useful import map for existing nodejs projects is obtained by running the following command

```sh 
$ npx importly < package.json > forge-importmap.json
$ cat forge-importmap.json
```

Which gives us:

```jsonc 
{

"imports": {
	"@openzeppelin/contracts/": "/node_modules/@openzeppelin/contracts/",
	"@uniswap/v2-core/": "/node_modules/@uniswap/v2-core/",
	"@uniswap/v3-periphery/": "/node_modules/@uniswap/v3-periphery/"
	},
"scopes": {}
}
```

#### Inline Imports for contract testing

Create a template solidity file and have forge compile however many times you define an import for that file

```solidity
pragma solidity *;

// We are actually importing 
// @yearn/sdk/contracts/BaseStrategyV1.sol, as defined in the forge-source file
import '<%= scope1 %>';

contract <%= scope1 %>Factory {

    function newInstance() public returns(address) {
     //  contractName = BaseStrategy, taken from @title in natspec
        return new <%= contractName %>Data();
    }
}

```

## Summary

![](https://en.meming.world/images/en/4/4a/Modern_Problems_Require_Modern_Solutions.jpg)

**Comment by sambacha** [comment]
Actually, running

```sh
forge config --basic > foundry.toml
```

creates a remappings for you as well, so this part at least should be aliased possibly

**Comment by sambacha** [comment]
Updated spec to include example of using a URL in which a colon `:`, is prefixed to the URL. This is  necessary when the remapping context is empty. Otherwise the https: part would be interpreted by the compiler as the context.

{@link https://docs.soliditylang.org/en/develop/path-resolution.html#using-urls-in-imports }

**Comment by sambacha** [comment]
the newest forge update includes a command `forge tree` which is similar to the example I provided above 

```
$ forge tree
src/TxManager.sol 0.6.7
├── lib/ds-auth/src/auth.sol >=0.6.7
├── lib/ds-token/lib/ds-math/src/math.sol >0.4.13
├── lib/ds-token/lib/ds-stop/lib/ds-note/src/note.sol >=0.4.23
└── lib/ds-token/lib/erc20/src/erc20.sol >0.4.20
src/TxManager.t.sol 0.6.7
├── lib/ds-test/src/test.sol >=0.4.23
├── lib/ds-token/src/base.sol >=0.4.23
│   ├── lib/ds-token/lib/erc20/src/erc20.sol >0.4.20
│   └── lib/ds-token/lib/ds-math/src/math.sol >0.4.13
└── src/TxManager.sol 0.6.7 (*)
```

**Comment by sambacha** [comment]
This is partially implemented here: https://github.com/sambacha/forge-nix

**Comment by onbjerg** [comment]
Closing this as out of scope for a couple of reasons:

- I don't think this will see much usage, mostly because it isn't very explicit in the source code itself, which makes reasoning about imports harder, which makes auditing harder
- This augments Solidity, which means we need to add some sort of preprocessing step which is itself out of scope for now. Augmenting Solidity also breaks compatibility with every other tool people might use (slither, echidna etc.)
