### ISSUE TITLE
Getting error "EIP-3855 is not supported in one or more of the RPCs used"

### ISSUE THREAD

**Issue by wuzhong-papermoon** [foundry-rs/foundry#7867]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ba399ae5 2024-04-30T13:37:57.271979000Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

The issue arises when using the Foundry toolchain and running the forge script command on Moonbeam. The system returns an "EIP-3855 is not supported in one or more of the RPCs used" error.

This issue is related to fee estimation for EIP-1559. Foundry uses the [eth_feeHistory](https://github.com/gakonst/ethers-rs/blob/51fe937f6515689b17a3a83b74a05984ad3a7f11/ethers-providers/src/rpc/provider.rs#L463) method to calculate the gas fee, and it sends the following request:
`{"method":"eth_feeHistory","params":[10,"latest",[20.0]],"id":1,"jsonrpc":"2.0"}`

While this works fine with Ethereum nodes, on a Moonbeam node, it returns the following error:
```
"code": -32602,
"message": "Invalid params",
"data": "invalid type: integer `10`, expected a (both 0x-prefixed or not) hex string or byte array containing between (0; 32] bytes at line 2 column 10"
```

Essentially, Foundry expects the node to accept an integer as an argument, but Moonbeam (and some other chains) does not. The issue is not specific to Moonbeam alone.
To reproduce the issue, you can try the following curl commands:

```
curl https://rpc.api.moonbase.moonbeam.network/ \
-X POST \
-H "Content-Type: application/json" \
--data '{"method":"eth_feeHistory","params":[10,"latest",[20.0]],"id":1,"jsonrpc":"2.0"}'
bash

curl https://ethereum-sepolia-rpc.publicnode.com/ \
-X POST \
-H "Content-Type: application/json" \
--data '{"method":"eth_feeHistory","params":[10,"latest",[20.0]],"id":1,"jsonrpc":"2.0"}'
```

A quick fix for this issue is to add the --legacy flag when running the forge script command with Foundry. This will disable the use of eth_feeHistory and instead use the legacy fee estimation method, which should work with both Ethereum and Moonbeam nodes.
But according to [Ethereum's API doc](https://ethereum.github.io/execution-apis/api-documentation/), the first parameter should be a hex string instead of a integer. 

Would you consider fixing it please?

**Comment by mattsse** [comment]
thanks for flagging, this is a client bug
