### ISSUE TITLE
vm.createFork() return always 0

### ISSUE THREAD

**Issue by fabriziogianni7** [foundry-rs/foundry#7872]
### Component

Other (please describe)

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (c486fca 2024-05-06T00:20:07.911403000Z)

### What command(s) is the bug in?

cheatcode vm.createFork()

### Operating System

macOS (Apple Silicon)

### Describe the bug

# Description
Foundry vm.createFork() returns zero instead of the chainID of sepolia.

```
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.25; // up to

import {Test, console} from "forge-std/Test.sol";


contract Demo is Test {
   
    function setUp() public {
        
    }

    function testCcipDummy() public {
        string memory ETHEREUM_SEPOLIA_RPC_URL = vm.envString("ETHEREUM_SEPOLIA_RPC_URL");
        uint256 forkId = vm.createFork(ETHEREUM_SEPOLIA_RPC_URL); // my url from alchemy

        console.log("sepoliaFork %", forkId); // return always 0
    }
}


```

**Comment by fabriziogianni7** [comment]
Ok so the identifiers start from 0 but the fork is created correctly then? Correct?

**Comment by yash-atreya** [comment]
> Ok so the identifiers start from 0 but the fork is created correctly then? Correct?

Yes
