### ISSUE TITLE
Can not deploy new SHIBUYA Contract 

### ISSUE THREAD

**Issue by kenvin1508** [foundry-rs/foundry#7879]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (c486fca 2024-05-06T00:20:07.911403000Z)

### What command(s) is the bug in?

 forge create 

### Operating System

macOS (Apple Silicon)

### Describe the bug

I create new project by -> "forge init hello_foundry"
setup _> .env 
and Run this -> forge create --rpc-url $SHIBUYA_RPC --private-key $ETH_PRIVATE_KEY src/Counter.sol:Couter --chain 81

Error: **server returned an error response: error code -32602: unknown field `chainId` at line 1 column 661**

Please help me detail this error

![image](https://github.com/foundry-rs/foundry/assets/32491345/e54f20d7-39a3-4f36-abd3-710322c0dd0f)

**Comment by klkvr** [comment]
Which chain are you using?
