### ISSUE TITLE
feat(`forge build`): add flag to show names of files that are not cached and being compiled

### ISSUE THREAD

**Issue by oveddan** [foundry-rs/foundry#7888]
### Component

Forge

### Describe the feature you would like

We have a ci workflow that downloads cached foundry build output before running `forge build`, in order to speed up compilation time.  Sometimes foundry recompiles some of the files, even though it seems that the source code hasn't changed between builds.  It would be great to add a flag that shows the names of the files being compiled.

For example, running `forge build`, when there are 221 files, and only some of the files have changed since the last build, produces the output while it compiles:
`Compiling 20 files with 0.8.17`

It would be great to be able to know the names of those 20 files.

If you add the `--names` flag, it will show all 221 files, regardless of if they were compiled or laoded from cache.

**Comment by grandizzy** [comment]
@oveddan could you check if rebuilding is still an issue with latest forge, there were couple of improvements in caching / rebuilding which could might help. `--names` command purpose is to show all compiled artifacts but we are going to look into accommodating your scenario

**Comment by mgiagante** [comment]
@grandizzy @oveddan  I'd like to take this in case it's still needed.

**Comment by zerosnacks** [comment]
Hi @mgiagante assigned to you! 

In https://github.com/foundry-rs/foundry/pull/9273 I introduce a global verbosity flag, I think running `forge build` with `-v` would be a great way to show additional details like what files are being compiled.
