### ISSUE TITLE
Build occurs without `--via-ir` but forge coverage retruns stack to deep error

### ISSUE THREAD

**Issue by HareemSaad** [foundry-rs/foundry#7891]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (008922d 2024-04-23T00:22:15.514185000Z)

### What command(s) is the bug in?

forge coverage

### Operating System

macOS (Apple Silicon)

### Describe the bug

my foundry.toml has the default settings

```[profile.default]
src = "src"
out = "out"
libs = ["lib"]
```

when I run `forge build` or `forge test -vvv` it compiles without any issue, but with `forge coverage` it produces a stack to deep error 
```
CompilerError: Stack too deep. Try compiling with `--via-ir` (cli) or the equivalent `viaIR: true` (standard JSON) while enabling the optimizer. Otherwise, try removing local variables. When compiling inline assembly: Variable headStart is 1 slot(s) too deep inside the stack. Stack too deep. Try compiling with `--via-ir` (cli) or the equivalent `viaIR: true` (standard JSON) while enabling the optimizer. Otherwise, try removing local variables.

```

if I run `forge coverage -ir-minimuum` it gives a differnet error

`Error: Unknown key "simpleCounterForLoopUncheckedIncrement"` 

How can i run forge coverage?

**Comment by DaniPopes** [comment]
Unfortunately forge coverage disables via-ir by default because it's fundamentally not supported, and ir-minimum is not guaranteed to work either. See https://github.com/foundry-rs/foundry/issues/3527

**Comment by HareemSaad** [comment]
@DaniPopes Thats not an issue the issue is my build, tests, scripts can run without IR so why does coverage demand it?
