### ISSUE TITLE
Have auto and interval mining at the same time

### ISSUE THREAD

**Issue by DefiCake** [foundry-rs/foundry#7901]
### Component

Anvil

### Describe the feature you would like

Use case: Have fast transactions (= fast CI pipelines and tests) with automated software that reacts on events, like bots, indexers, etc

At the moment anvil allows either one mining mode or the other - auto, or interval. This is specifically signaled by the interval mining mode, that warns that auto is disabled.

**Comment by mattsse** [comment]
this should be possible to support by adding a new mode that combines both of these:

https://github.com/foundry-rs/foundry/blob/d7eac74cfd786447cec9650048e2d2fac63fba0c/crates/anvil/src/eth/miner.rs#L102-L108

**Comment by caiquejjx** [comment]
@mattsse is this high priority? I would like to work on it but it's my first time interacting with foundry so it will take some time to get this done

**Comment by mattsse** [comment]
not high priority, the task here would be to add a new variant that is 

```rust
Mixed {
  auto: ReadyTransactionMiner,
  fixed: FixedBlockTimeMiner
}
```

and then polls both

**Comment by caiquejjx** [comment]
oh looks simple enough, thanks!

**Comment by caiquejjx** [comment]
@mattsse hey, I created a draft [pr](https://github.com/foundry-rs/foundry/pull/8280/files) with the new variant + it's pooling but I'm wondering if I should also add RPC handler for setting the mixed mining mode, when you have some time can you take a look? Thank you

**Comment by zerosnacks** [comment]
Hi @caiquejjx thanks for picking this up, draft is looking good!

I think it makes sense to add RPC methods for this (`anvil_setMixedmine(bool)`, `anvil_getMixedmine(bool)` matching `anvil_setAutomine(bool)` / `anvil_getAutomine(bool)`).

cc @mattsse

**Comment by caiquejjx** [comment]
thanks @zerosnacks, I'll follow up with the RPC methods implementation then
