### ISSUE TITLE
feat(cheatcodes): `P256` public key generator

### ISSUE THREAD

**Issue by pcaversaccio** [foundry-rs/foundry#7908]
### Component

Forge

### Describe the feature you would like

It would be very useful for testing of P256 signatures to have a `forge` function that can generate / derive the public key coordinates based on the `secp256r1` curve from a random `uint256` private key:

```solidity
function generatePublicKeyP256(uint256 privateKey) external pure returns (uint256 publicKeyX, uint256 publicKeyY)
```

Maybe, we can think this further, and add an `Enum` for the elliptic curve used (e.g. `secp256k1`, `secp256r1` etc.) to have the possibility to add further curves without breaking the API.

**Comment by protocolwhisper** [comment]
I'd love to work on this :)

**Comment by yash-atreya** [comment]
> I'd love to work on this :)

Assigned

**Comment by protocolwhisper** [comment]
Quick questions does this need to be here https://github.com/foundry-rs/foundry/blob/0b03a58b4a42b149a27e0b6cc1ff9559306f3603/crates/cheatcodes/src/utils.rs#L19 or in the forge crate if so where?

**Comment by mattsse** [comment]
in the cheatcodes

see https://github.com/foundry-rs/foundry/blob/29e51120ac6e77a62242364a22108edea7274a2a/crates/cheatcodes/spec/src/vm.rs#L305-L307

and 

https://github.com/foundry-rs/foundry/blob/29e51120ac6e77a62242364a22108edea7274a2a/crates/cheatcodes/src/evm.rs#L164-L169

for reference

**Comment by zerosnacks** [comment]
Hi @protocolwhisper how is it going? Do you need any pointers or have any questions?

**Comment by protocolwhisper** [comment]
Hi @zerosnacks, it's going well I've just submitted the pull requests + tests :)

**Comment by pcaversaccio** [comment]
Can you please add the function to the `vm` interface in `forge-std`, otherwise hard to use 🙃
