### ISSUE TITLE
Name latest solc and evm version supported by anvil in readme

### ISSUE THREAD

**Issue by jaketimothy** [foundry-rs/foundry#7921]
### Component

Anvil

### Describe the feature you would like

I would love to have a clear place to check anvil for the latest supported solc and evm versions. 

Solc and forge support runs ahead of anvil. This recently created issues for our team and Cancun when we were building and testing with forge, but failing to pass integration tests using anvil. Currently, we have to read through the PRs and commits on this repo to try to understand if/when new versions are supported - which involves time and human interpretation error. Please make a clear place for devs to communicate support.

A simple change, but adds a doc for devs to maintain.

**Comment by MukulKolpe** [comment]
Hey @mattsse, @jaketimothy can I work on this one?

**Comment by LukePereyra** [comment]
Hello Team ! I wish to take this issue and work on it
