### ISSUE TITLE
"vm.setBlockhash" cheatcode

### ISSUE THREAD

**Issue by zomglings** [foundry-rs/foundry#7929]
### Component

`cheatcodes`

### Describe the feature you would like

A `vm.setBlockhash` cheat code would be very convenient for testing code that uses the Solidity `blockhash` function.

This is how it would be used:

```
vm.roll(block.number + 1);
vm.setBlockhash(block.number - 1, "1234");
assertEq(blockhash(block.number - 1), "1234");
```

Currently, the easiest way to test code that calls `blockhash` is to wrap the `blockhash` call in a virtual, internal method and then create a test class that overrides that method to mock `blockhash` calls.

I'd rather just have the mocking performed at the level of the `vm`.

If this is considered sufficiently useful, I would be happy to try my hand at adding this cheat code. Just don't want to learn rust, etc. to add this only to have a PR rejected if the feature isn't seen as useful.

**Comment by zomglings** [comment]
Developer documentation for cheat codes: https://github.com/foundry-rs/foundry/blob/master/docs/dev/cheatcodes.md#cheatcodes-implementation

**Comment by onbjerg** [comment]
Unsure if this makes sense to add if https://eips.ethereum.org/EIPS/eip-2935 is included in Prague, as this could be emulated with just setting the appropriate slot on the contract

**Comment by zomglings** [comment]
> Unsure if this makes sense to add if https://eips.ethereum.org/EIPS/eip-2935 is included in Prague, as this could be emulated with just setting the appropriate slot on the contract

In that case, wouldn't `vm.setBlockhash` still be a useful shorthand to set that slot?

**Comment by mattsse** [comment]
yeah for setting a slot this will still be useful imo

**Comment by jrmncos** [comment]
Hello, is it still available? I would like to work on this one

**Comment by mattsse** [comment]
this is available and should be similar to

https://github.com/foundry-rs/foundry/blob/29e51120ac6e77a62242364a22108edea7274a2a/crates/cheatcodes/spec/src/vm.rs#L415-L420

https://github.com/foundry-rs/foundry/blob/29e51120ac6e77a62242364a22108edea7274a2a/crates/cheatcodes/src/evm.rs#L362-L367

the impl would need to update the hash of the block.number in the database

if you need more pointers, please open a draft pr and we take it from there

**Comment by TropicalDog17** [comment]
Hi @mattsse, it appears the previous assignee hasn't started on this task yet so I'd like to work on it. I've created a draft PR but I'm having trouble accessing the database in `apply_full` to update the blockhash. Could you provide some guidance on this? Thank you!

**Comment by jrmncos** [comment]
hey @mattsse you can re-assign the issue to @TropicalDog17 . Sorry for delay
