### ISSUE TITLE
feat(`forge test`): output filenames & line numbers in test output (when using the `-vvv` test flag)

### ISSUE THREAD

**Issue by kryptoklob** [foundry-rs/foundry#7930]
#### Context

When I debug tests, I often get confused as to which file (and line number) the function I'm looking at in the test output (especially when using the `-vvv` flag) corresponds to.

#### Request

Add a debug level that outputs the filename and line numbers inline with the test output, *or* add it into the existing `-vvv` debug level.

Upon failed asserts the filename and line numbers should also be outputted

#### Misc

I haven't done a deep dive into foundry internals, so I'm not sure how hard this would be to implement. Would be willing to contribute towards this feature, likely when I have more time in a few weeks (perhaps ~8 total hours to get this implemented, if it is not already implemented)

**Comment by zerosnacks** [comment]
Hey @kryptoklob! Thanks for your suggestion

I do not know if we can have access to line numbers given current limitations (cc @klkvr), I think it requires the AST which would incur additional build time prior to running tests

The rendering of the traces has been moved to https://github.com/paradigmxyz/revm-inspectors

Related: https://github.com/foundry-rs/foundry/issues/7605

**Comment by zerosnacks** [comment]
Closing in favor of https://github.com/foundry-rs/foundry/issues/2328, updated the description and title to reflect the requested change here
