### ISSUE TITLE
Segmentation fault or Unimplemented feature

### ISSUE THREAD

**Issue by jac0x** [foundry-rs/foundry#7936]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### Operating System

macOS (Intel)

### Describe the bug

Just `segmentation fault`, nothing else
nightly-a470d635cfcdce68609e9dc5762a3584351bacc1

Tried different version
nightly-09fe3e041369a816365a020f715ad6f94dbce9f2
```
Error: 
Compiler run failed:
Error: Unimplemented feature (/Users/distiller/project/libsolidity/codegen/CompilerUtils.cpp:420):Encoding type "struct StdInvariant.FuzzInterface memory[] memory" not yet implemented.
```

**Comment by jac0x** [comment]
But the latest nightly version fails with `segmentation fault` when running `forge`. All `forge` commands fail.

Is there specific device requirement for the latest version?

**Comment by jac0x** [comment]
I am on Catalian, intel iMac. Still this doesn't work.

**Comment by mmsaki** [comment]
I had this issue, here is a fix:

```js
// add this to your foundry test
pragma experimental ABIEncoderV2;
```
