### ISSUE TITLE
Memory leak in Anvil for high transaction volume

### ISSUE THREAD

**Issue by AnieeG** [foundry-rs/foundry#7940]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (503792a 2024-05-10T11:26:11.682258969Z)

### What command(s) is the bug in?

 anvil --chain-id 1337 --block-time 2 --gas-limit 400000000000000 --code-size-limit 30000 --base-fee 100000 --host 0.0.0.0 --port 8545 --accounts 20 --balance 2000000000000000000 --state /state/dump.json --state-interval 60 --transaction-block-keeper 500

### Operating System

Linux

### Describe the bug

While running Anvil as part of a load scenario, the memory usage of Anvil nodes increases very quickly. The load scenario generates one transaction every 5 seconds, and the blocktime of Anvil is set to 1 second. Within 30 minutes, the memory usage surges to 6 GiB. Using the --prune-history option effectively manages the memory usage, but it results in a BlockOutOfRangeError (BlockOutOfRangeError: block height is 501 but requested was 500) when querying deployed contracts.

Is there a workaround for this issue? Can Anvil be used for high load testing scenarios?

**Comment by grandizzy** [comment]
@AnieeG I don't see any mem leak using `anvil 0.2.0 (260ad350c0 2024-05-27T10:56:35.953226014Z)`, the test I did was to run anvil
```
anvil --chain-id 1337 --block-time 1 --gas-limit 400000000000000 --code-size-limit 30000 --base-fee 100000 --host 0.0.0.0 --port 8545 --accounts 20 --balance 2000000000000000000 --state dump.json --state-interval 60 --transaction-block-keeper 500
```
and deploy Counter contract in a loop
```
while true; do forge create --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 src/Counter.sol:Counter; done
```

After 30 mins the resident memory reached 705M

![image](https://github.com/foundry-rs/foundry/assets/38490174/e6ba6375-3605-4948-8910-914a01526492)

then OS started to release it as expected, going down to 693M

![image](https://github.com/foundry-rs/foundry/assets/38490174/3e4b0d3e-4a8a-4f30-811d-f2c694d8bcf0)

Please retest with latest anvil and provide more details on how to reproduce if mem not released.

**Comment by AnieeG** [comment]
I have rerun this on `latest` tagged  foundry version -` forge 0.2.0 (0a5b22f 2024-05-21T10:30:02.156279959Z)`
command used -

`anvil --chain-id 90000034 --block-time 1 --gas-limit 400000000000000 --code-size-limit 30000 --base-fee 100000 --host 0.0.0.0 --port 8545 --accounts 20 --balance 2000000000000000000 --state /state/dump.json --state-interval 60 --transaction-block-keeper 500`

Within 17m I see the usage is around 1.4GB
<img width="1266" alt="image" src="https://github.com/foundry-rs/foundry/assets/88458927/e851a60e-751a-4df8-aaa2-b7ba8722ad5a">

After 22m it shoots up to 2.0GB
<img width="1285" alt="image" src="https://github.com/foundry-rs/foundry/assets/88458927/742de9d5-575c-4d5f-a7f1-54dd9534e6b2">

But after 44m or so I see the usage has again gone down 808M
<img width="1201" alt="image" src="https://github.com/foundry-rs/foundry/assets/88458927/ac6f7774-9e9e-4cf9-9cac-568b2a558b14">

Thanks for fixing this!!

**Comment by grandizzy** [comment]
thanks, going to close per comment above
