### ISSUE TITLE
Cleanup build_tx and cast_send

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#7959]
### Component

Cast

### Describe the feature you would like

these functions is incredibly ugly and the result of additional features

https://github.com/foundry-rs/foundry/blob/003d0889ddb2aba5af8ff3606ae692e660156ae8/crates/cast/bin/tx.rs#L41-L41

https://github.com/foundry-rs/foundry/blob/003d0889ddb2aba5af8ff3606ae692e660156ae8/crates/cast/bin/cmd/send.rs#L215-L215

they should be converted into helper types, builder style

**Comment by yash-atreya** [comment]
Follow up #7823
