### ISSUE TITLE
bug(forge): flatten extra spacing

### ISSUE THREAD

**Issue by DeGatchi** [foundry-rs/foundry#796]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (67f9ed1 2022-02-23T00:44:43.196862+00:00)

### What command(s) is the bug in?

forge flatten 

### Operating System

macOS (amd)

### Describe the bug

When flattening a contract the license is formatted in a weird way, on the same line as the previous contract closing braces.
![image](https://user-images.githubusercontent.com/72078332/155275262-1bc1ba0b-c8dd-4ec3-a3fc-6d7f083fa606.png)

Spacing format bug
![image](https://user-images.githubusercontent.com/72078332/155276057-12b91e54-d7ec-4c8a-ab5b-1532801f47dd.png)

**Comment by mattsse** [comment]
cc @rkrasiuk I think we need to trim_end?

**Comment by rkrasiuk** [comment]
@mattsse thought about it yesterday as well, when changing tests to compare against the full string. what do you think about not trimming at all?

**Comment by mattsse** [comment]
not trimming at all is reasonable as flattening is supposed to work as concat(file1, file2,...)
so we just need to be careful when removing the license? to also remove the newline?

**Comment by rkrasiuk** [comment]
actually, it's also about the duplicate nested imports. we are removing the import statement, but leaving the blank line. should we just create a regex that replaces any `\n{3,}` with `\n\n`?

**Comment by onbjerg** [comment]
Is this still the case?

**Comment by rkrasiuk** [comment]
@onbjerg i think so, i was mia since my last comment. would be glad to take care of it now
