### ISSUE TITLE
docker images for Mac m1-m3, arm

### ISSUE THREAD

**Issue by NikZak** [foundry-rs/foundry#7964]
### Component

Anvil

### Describe the feature you would like

Any chance you could publish docker images for arm architecture, seems like currently it is not there
```
ERROR: failed to solve: failed to resolve source metadata for ghcr.io/foundry-rs/foundry:latest: no match for platform in manifest: not found
```

**Comment by stleon** [comment]
You can specify --platform=linux/amd64 
see https://github.com/foundry-rs/foundry/issues/7680

**Comment by trajan0x** [comment]
We're seeing some pretty poor performance with linux/amd64 (as expected from virtualization). Would be great to get an official manifest going

**Comment by grandizzy** [comment]
going to track arm64 support in https://github.com/foundry-rs/foundry/issues/8039
