### ISSUE TITLE
Failed to read artifacts from forge test

### ISSUE THREAD

**Issue by loocapro** [foundry-rs/foundry#7973]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a4d79ac 2024-05-09T00:18:10.247407000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

1. Clone https://github.com/aurelien-cuvelier/local-uniswapv2-foundry
2. Add `fs_permissions = [{ access = "read-write", path = "./"}]` to `foundry.roml`
3. Run: `forge test --initial-balance 10000000000000000000`

You ll get the following error:

`[FAIL. Reason: setup failed: failed to read from "local-uniswapv2-foundry/UniswapV2Factory.sol/UniswapV2Factory.json": No such file or directory (os error 2)] setUp() (gas: 0)`

Shouldnt the artifacts being searched in /out?

Note: This works in `forge 0.2.0 (ee47bb0 2024-04-16T00:15:57.186444587Z)` without setting the fs_permissions in toml.

**Comment by loocapro** [comment]
Seems like it fixes by changing the path of the artifacts from `"UniswapV2Router02.sol:UniswapV2Router02"` to `"out/UniswapV2Router02.sol:UniswapV2Router02"`, is it expected?

**Comment by nbaztec** [comment]
@loocapro Yes the artifacts are in `out/` and `zkout/` directories by default. We're currently in the process of merging https://github.com/matter-labs/foundry-zksync/pull/368 that will synchronize the paths in `zkout/` to mirror `out/` as currently they're a bit different.
