### ISSUE TITLE
0 ^ 0 returns 0

### ISSUE THREAD

**Issue by 0xnonso** [foundry-rs/foundry#7980]
**component**
forge, chisel

**have you ensured that all of these are up to date?**
- [x] foundry
- [x] foundryup

**what version of Foundry are you on?**
forge 0.2.0 (467aff3 2024-05-19T00:18:50.827112000Z)

**describe the bug**
0 ^ 0 returns 0 rather than 1 when running forge tests and also when using chisel. this also happens on remix so i'm not sure its a foundry specific bug.

**Comment by klkvr** [comment]
This behavior is determined by Solidity and it is correct behavior of XOR operator

**Comment by 0xnonso** [comment]
so sorry, yes you are right i mixed it up. i was using yul `exp` and mistakenly assumed the equivalent to be `^` not `**`
