### ISSUE TITLE
Uncommitted changes

### ISSUE THREAD

**Issue by ZhouZiJin981014** [foundry-rs/foundry#7987]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What command(s) is the bug in?

forge install OpenZeppelin/openzeppelin-contracts@v4.9.6

### Operating System

Windows

### Describe the bug

*

**Comment by ZhouZiJin981014** [comment]
Microsoft Windows [版本 10.0.22631.3593]
(c) Microsoft Corporation。保留所有权利。

E:\foundry project\eightDemo>forge init
Initializing E:\foundry project\eightDemo...
Installing forge-std in E:/foundry project/eightDemo\lib\forge-std (url: Some("https://github.com/foundry-rs/forge-std"), tag: None)
Cloning into 'E:/foundry project/eightDemo/lib/forge-std'...
remote: Enumerating objects: 2310, done.
remote: Counting objects: 100% (2305/2305), done.
remote: Compressing objects: 100% (799/799), done.
remote: Total 2310 (delta 1529), reused 2156 (delta 1434), pack-reused 5
Receiving objects: 100% (2310/2310), 664.74 KiB | 71.00 KiB/s, done.
Resolving deltas: 100% (1529/1529), done.
warning: in the working copy of '.gitmodules', LF will be replaced by CRLF the next time Git touches it
    Installed forge-std v1.8.2
    Initialized forge project

E:\foundry project\eightDemo>forge install LayerZero-Labs/LayerZero-v2
Installing LayerZero-v2 in E:/foundry project/eightDemo/lib\LayerZero-v2 (url: Some("https://github.com/LayerZero-Labs/LayerZero-v2"), tag: None)
Cloning into 'E:/foundry project/eightDemo/lib/LayerZero-v2'...
remote: Enumerating objects: 705, done.
remote: Counting objects: 100% (128/128), done.
remote: Compressing objects: 100% (84/84), done.
remote: Total 705 (delta 59), reused 53 (delta 43), pack-reused 577
Receiving objects: 100% (705/705), 6.65 MiB | 88.00 KiB/s, done.
Resolving deltas: 100% (348/348), done.
warning: in the working copy of '.gitmodules', LF will be replaced by CRLF the next time Git touches it
Submodule 'lib/forge-std' (https://github.com/foundry-rs/forge-std) registered for path 'lib/forge-std'
Cloning into 'E:/foundry project/eightDemo/lib/LayerZero-v2/lib/forge-std'...
remote: Enumerating objects: 2310, done.
remote: Counting objects: 100% (2305/2305), done.
remote: Compressing objects: 100% (799/799), done.
remote: Total 2310 (delta 1529), reused 2156 (delta 1434), pack-reused 5
Receiving objects: 100% (2310/2310), 664.74 KiB | 95.00 KiB/s, done.
Resolving deltas: 100% (1529/1529), done.
Submodule 'lib/ds-test' (https://github.com/dapphub/ds-test) registered for path 'lib/forge-std/lib/ds-test'
Cloning into 'E:/foundry project/eightDemo/lib/LayerZero-v2/lib/forge-std/lib/ds-test'...
remote: Enumerating objects: 313, done.
remote: Counting objects: 100% (171/171), done.
remote: Compressing objects: 100% (79/79), done.
remote: Total 313 (delta 91), reused 132 (delta 83), pack-reused 142
Receiving objects: 100% (313/313), 71.35 KiB | 106.00 KiB/s, done.
Resolving deltas: 100% (130/130), done.
    Installed LayerZero-v2

E:\foundry project\eightDemo>forge install LayerZero-Labs/LayerZero
Installing LayerZero in E:/foundry project/eightDemo/lib\LayerZero (url: Some("https://github.com/LayerZero-Labs/LayerZero"), tag: None)
Cloning into 'E:/foundry project/eightDemo/lib/LayerZero'...
remote: Enumerating objects: 253, done.
remote: Counting objects: 100% (49/49), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 253 (delta 28), reused 19 (delta 19), pack-reused 204
Receiving objects: 100% (253/253), 3.41 MiB | 2.53 MiB/s, done.
Resolving deltas: 100% (93/93), done.
warning: in the working copy of '.gitmodules', LF will be replaced by CRLF the next time Git touches it
    Installed LayerZero

E:\foundry project\eightDemo>forge install GNSPS/solidity-bytes-utils
Installing solidity-bytes-utils in E:/foundry project/eightDemo/lib\solidity-bytes-utils (url: Some("https://github.com/GNSPS/solidity-bytes-utils"), tag: None)
Cloning into 'E:/foundry project/eightDemo/lib/solidity-bytes-utils'...
remote: Enumerating objects: 597, done.
remote: Counting objects: 100% (193/193), done.
remote: Compressing objects: 100% (106/106), done.
remote: Total 597 (delta 112), reused 150 (delta 86), pack-reused 404
Receiving objects: 100% (597/597), 692.01 KiB | 855.00 KiB/s, done.
Resolving deltas: 100% (334/334), done.
warning: in the working copy of '.gitmodules', LF will be replaced by CRLF the next time Git touches it
    Installed solidity-bytes-utils v0.8.2

E:\foundry project\eightDemo>echo. > remapping.txt

E:\foundry project\eightDemo>notepad remapping.txt

E:\foundry project\eightDemo>notepad remapping.txt

E:\foundry project\eightDemo>forge install OpenZeppelin/openzeppelin-contracts@v4.9.6
Installing openzeppelin-contracts in E:/foundry project/eightDemo/lib\openzeppelin-contracts (url: Some("https://github.com/OpenZeppelin/openzeppelin-contracts"), tag: Some("v4.9.6"))
Error:
The target directory is a part of or on its own an already initialized git repository,
and it requires clean working and staging areas, including no untracked files.

Check the current git repository's status with `git status`.
Then, you can track files with `git add ...` and then commit them with `git commit`,
ignore them in the `.gitignore` file, or run this command again with the `--no-commit` flag.

If none of the previous steps worked, please open an issue at:
https://github.com/foundry-rs/foundry/issues/new/choose

**Comment by DaniPopes** [comment]
You have uncommitted changes, please read the error message.
