### ISSUE TITLE
Request for a stable release

### ISSUE THREAD

**Issue by wangeguo** [foundry-rs/foundry#8000]
Hi, I'm maintaining a [foundry buildpacks](https://github.com/amp-buildpacks/foundry) which requires a download address and sha256, and the current version of Nightly I'm using is frequently updated, and what's even more strange is that sometimes this nightly version disappears, resulting in a CI error over here. For example:

```
  [[metadata.dependencies]]
    id = "foundry"
    name = "Foundry"
    purl = "pkg:generic/foundry@0.2.0"
    sha256 = "6d493a985e0c8c666a9d6ded4c662d2db530d91ea2679dd941fd4b2820fab023"
    uri = "https://raw.githubusercontent.com/foundry-rs/foundry/nightly-23700c9233314e06ba65be4522daf3aa89130dc0/foundryup/install"
    stacks = ["*"]
    version = "0.2.0"
```

![截屏2024-05-27 11 54 34](https://github.com/foundry-rs/foundry/assets/146697/e0714be7-36ea-48a7-8d63-4092e52601b2)
https://github.com/amp-buildpacks/foundry/actions/runs/9248668764/job/25439315306

So, I'm requesting if the Foundry team can release a stable version that might help us, and the various package managers.

**Comment by jjbailey-io** [comment]
+1. This has been a large issue for our team. We've resulted to utilizing the `foundryup --commit` option and building our own containers so we could maintain a stable development environment.

**Comment by samlaf** [comment]
Big +1. Seems like releases are pruned by github for some reason (unless this is one of your configs to save money?). Docker images are not pruned however and are all available: https://github.com/foundry-rs/foundry/pkgs/container/foundry/versions?filters%5Bversion_type%5D=tagged

But for some reason `forge script` from inside docker image takes forever to deploy our large stuff, so is unusable for us. Then for any recent release that we need, we need to wait until the next monthly release before being able to update, which is annoying.

Is there a way to change your release config to keep all releases between the monthly releases? You can prune them after a month.

**Comment by wangeguo** [comment]
I found a temporary solution: foundry will keep one release per month on the 2nd, and the others will be removed, so I'm now specifying this in my dependencies.

**Comment by samlaf** [comment]
> I found a temporary solution: foundry will keep one release per month on the 2nd, and the others will be removed, so I'm now specifying this in my dependencies.

Yes but my point is they should keep all of the nightly releases until around until the next monthly release. Otherwise I need to wait 1 month before the next monthly release to get the bug fixes in.
