### ISSUE TITLE
"immutableReferences["Contracts"]" = false How is it defined?

### ISSUE THREAD

**Issue by xxeonge** [foundry-rs/foundry#8001]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

a170021b

### What command(s) is the bug in?

forge build

### Operating System

macOS (Apple Silicon)

### Describe the bug

When I create a bindings file using contracts, it says immutableReferences[Contracts] = false. However, this contract has a constructor and has Immutable items. Why does this result occur?

- binding file : [Link](https://github.com/tokamak-network/tokamak-thanos/blob/main/op-bindings/bindings/masterminter_more.go)
- The file that binds the contract is [Link](https://github.com/tokamak-network/tokamak-thanos/blob/main/packages/tokamak/contracts-bedrock/src/tokamak-contracts/USDC/L2/tokamak-USDC/minting/MasterMinter.sol).

MasterMinter contracts has constructor "_minterManager" 
However, when I bind MasterMinter, i**mmutableReferences["MasterMinter"] = false**, why do I get this result?
![스크린샷 2024-05-27 오후 4 59 09](https://github.com/foundry-rs/foundry/assets/123148171/d666343d-917f-4665-a705-7a1d0f17b620)
![스크린샷 2024-05-27 오후 4 59 36](https://github.com/foundry-rs/foundry/assets/123148171/221c83b5-86ba-44e7-9143-aeefc5cc2dce)
![스크린샷 2024-05-27 오후 5 00 21](https://github.com/foundry-rs/foundry/assets/123148171/8e97235d-291c-4d0e-a794-ef6e12763d3e)

**Comment by LukePereyra** [comment]
Hello ! I wish to work on this!

**Comment by xxeonge** [comment]
> Hello ! I wish to work on this!

sorry for late reply. Do you know the problem with this? @LukePereyra

**Comment by zerosnacks** [comment]
Marking as `unrelated`, `forge bind` does not build bindings for `go`
