### ISSUE TITLE
The block number of the forked master does not match `block.number`.

### ISSUE THREAD

**Issue by luciferzxj** [foundry-rs/foundry#8002]
### Component

Forge, Foundryup

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ec3f9bd 2023-09-19T14:02:40.053513700Z)

### What command(s) is the bug in?

forge test --match-path ./foundry/blockTest.t.sol -vvvvv

### Operating System

Windows

### Describe the bug

The test contract I use is as follows:
```solidity
function setUp()public{
        uint256 forkedBlockNumber = 215594273;
        vm.createSelectFork(ArbRpc, forkedBlockNumber);
        console.log("fored blockNumber",forkedBlockNumber);
        console.log("current blockNumber", block.number);
        assertEq(forkedBlockNumber, block.number, "incorrect block");
    }
    function testBlock()public{

    }
```
And when I execute it with the following command, it happens that the forked block number does not match the actual `block.number` block number:
```
forge test --match-path ./foundry/blockTest.t.sol -vvvvv
```
![image](https://github.com/foundry-rs/foundry/assets/106872309/f355a22f-f61a-46fd-a251-a11cd9e64ecf)
![image](https://github.com/foundry-rs/foundry/assets/106872309/af574c1b-c44e-4a9a-ba03-6ef374547276)

**Comment by mattsse** [comment]
ah I think this is arbitrum specific logic, because block.number returns the L1 block number iirc
