### ISSUE TITLE
forge verify-bytecode incorrectly returning a partial match

### ISSUE THREAD

**Issue by blmalone** [foundry-rs/foundry#8012]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ea2eff9 2024-05-29T00:18:15.036792000Z)

### What command(s) is the bug in?

forge verify-bytecode 0x5fb30336a8d0841cf15d452afa297cb6d10877d7 OptimismPortal --rpc-url $MAINNET_RPC_URL --json

### Operating System

macOS (Apple Silicon)

## Steps to reproduce

```bash
git clone https://github.com/ethereum-optimism/optimism.git
cd optimism
git checkout op-contracts/v1.3.0
pnpm clean && pnpm install && pnpm build
cd packages/contracts-bedrock
forge install
forge verify-bytecode 0x5fb30336a8d0841cf15d452afa297cb6d10877d7 OptimismPortal --rpc-url $MAINNET_RPC_URL --json
```

### Output:
```json
[
  {
    "bytecode_type": "creation",
    "matched": false,
    "verification_type": "full",
    "message": "Creation code did not match - this may be due to varying compiler settings"
  },
  {
    "bytecode_type": "runtime",
    "matched": true,
    "verification_type": "partial"
  }
]
```

As you can see the `op-contract/v1.3.0 tag` has completely difference runtime code for the `OptimismPortal` smart contract: [here](https://github.com/ethereum-optimism/optimism/blob/op-contracts/v1.3.0/packages/contracts-bedrock/src/L1/OptimismPortal.sol#L98). Compared to the source code onchain: [here](https://etherscan.io/address/0x5fb30336a8d0841cf15d452afa297cb6d10877d7#code#F1#L1).

**Comment by yash-atreya** [comment]
Looking into it

**Comment by mds1** [comment]
Hey @yash-atreya, any updates here?

**Comment by yash-atreya** [comment]
> Hey @yash-atreya, any updates here?

Hey @blmalone @mds1 

Sorry for the delay. Got caught up in alloy stuff. Will prio this now
