### ISSUE TITLE
perf(`forge test`): memory leak in latest foundry

### ISSUE THREAD

**Issue by 0xTimepunk** [foundry-rs/foundry#8014]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (5494c33 2024-05-30T00:18:10.251370000Z)

### What command(s) is the bug in?

forge test (make test)

### Operating System

macOS (Apple Silicon)

### Describe the bug

With the following PR as an example https://github.com/superform-xyz/superform-core/pull/541

To reproduce

Part 1
- Do `foundryup` (latest foundry)
- forge install
- Override RPCs in make file and run `make ftest`
- Open Mac activity monitor and check memory usage. This results in a oom:
![telegram-cloud-document-4-5960961092661285381](https://github.com/foundry-rs/foundry/assets/45543880/82a03765-cee3-4c1b-b3a5-dccc7575f9de)

code 137 in https://github.com/superform-xyz/superform-core/actions/runs/9289996043/job/25566018918

Please note that this is a powerful dedicated Github actions runner, so the memory limits shouldn't actually be reached

Part 2
- Do ` foundryup -v  nightly-cafc2606a2187a42b236df4aa65f4e8cdfcea970`
- forge install
- Override RPCs in make file and run `make ftest`
- Open Mac activity monitor and check memory usage
![telegram-cloud-photo-size-4-5963231644758425826-y](https://github.com/foundry-rs/foundry/assets/45543880/ea46deb2-1343-4e5e-95ff-5ca0883513d5)

A whopping difference of 36gb.

**Comment by mattsse** [comment]
@grandizzy I wonder if this is fuzzing related

@0xTimepunk were you able to narrow this down to a specific test?

**Comment by grandizzy** [comment]
> @grandizzy I wonder if this is fuzzing related
> 
> @0xTimepunk were you able to narrow this down to a specific test?

Invariants are excluded from project tests, so they're not the culprit. Going to check for regular fuzz tests

**Comment by 0xTimepunk** [comment]
I'm not sure if the nightly I posted is the last operating nightly as I haven't tested. Memory usage increase seems independent of test type, however we do have fuzzying in some scenario files which are part of make ftest or make coverage

**Comment by grandizzy** [comment]
> I'm not sure if the nightly I posted is the last well operating nightly as I haven't tested. Memory usage increase seems independent of test type, however we do have fuzzying in some scenario files which are part of make ftest or make coverage

@0xTimepunk I was under the impression you're excluding invariant tests where you hit such, but looking at `make ftest` target it is running all of them, is there same issue when running `make test-ci` ? I am yet able to try it locally as the project requires several chain rpc urls which I don't have handy

**Comment by 0xTimepunk** [comment]
<img width="1367" alt="image" src="https://github.com/foundry-rs/foundry/assets/45543880/37972ce1-f0b6-453c-9f72-ac010dfeea2d">
I notice 1gb is added on each fuzz test we run, when it should be stable. This is on `make test-ci` which has no invariant calls

**Comment by 0xTimepunk** [comment]
@mattsse @grandizzy (also please read conclusions at the bottom)

# Scenario 1 - the worst (with all latest versions)

### Settings

**On forge-std @52715a2 (latest)**

**latest foundry (foundryup)**

***Note: this checks out to a commit with latest forge-std and removed import of ds-test***

### `git checkout 0769ff1 && make test-ci`

![image](https://github.com/foundry-rs/foundry/assets/45543880/b9a18b0d-edb3-47b0-aa44-3d6e4f1cf0f0)


Results: Forge hits around  11gb. More has been observed

### `git checkout 0769ff1 && make coverage`

![image](https://github.com/foundry-rs/foundry/assets/45543880/6db2ead5-033e-4aea-ab22-34b6c204cd9a)

Results: Forge hits around +32gb. More has been observed Computer starts to freeze, 137 code sometimes both on local / ci

# Scenario 2 - very bad

### Settings

**On forge-std @52715a2 (latest)**

nightly-cafc2606a2187a42b236df4aa65f4e8cdfcea970

***Note: this checks out to a commit with latest forge-std and removed import of ds-test***

### `git checkout 0769ff1 && forge install && make test-ci`

![image](https://github.com/foundry-rs/foundry/assets/45543880/d723c226-9a39-45f3-8c63-7a401010bd23)


Results: Forge hits around 8gb usage. More has been observed in other runs which were not snapshoted.

### `git checkout 0769ff1 && forge install && make coverage`

![image](https://github.com/foundry-rs/foundry/assets/45543880/4d6fdd02-9dc6-4ed4-aa2c-6a8beb7fc5a4)

Results: Forge hits around 21gb of usage. More has been observed in other runs which were not snapshoted.

# Scenario 3 - not possible

### Settings

**On forge-std @52715a2 (latest)**

nightly-f625d0fa7c51e65b4bf1e8f7931cd1c6e2e285e9

***Note: this checks out to a commit with latest forge-std and removed import of ds-test***

### `git checkout 0769ff1 && forge install && make test-ci`

Crashes (likely too old foundry version for most recent forge-std), so skipping analysis here.

![image](https://github.com/foundry-rs/foundry/assets/45543880/4ec2f4aa-d11a-4c7a-87a8-dbabac62a9fd)


# Scenario 4 - not possible

### Settings

**On forge-std@2f11269** (6 months old, the one we had previously)

**AND Using ds-test@e282159**

**latest foundry (foundryup)**

***Note: this checks out to a commit which has our previous forge-std version, the one from 6 months ago, together with ds-test, both still operational***

### `git checkout e9826a51 && forge install && make test-ci`

Crashes. Likely new forge version did something that made it stop working with forge-std (unsure why should this happen). Skipping test.

![image](https://github.com/foundry-rs/foundry/assets/45543880/3de046f0-e122-42bc-a799-ab8e2f3fcb6a)


# Scenario 5 - somewhat healthy ram usage

**On forge-std@2f11269** (6 months old, the one we had previously)

**AND Using ds-test@e282159**

nightly-cafc2606a2187a42b236df4aa65f4e8cdfcea970

***Note: this checks out to a commit which has our previous forge-std version, the one from 6 months ago, together with ds-test, both still operational***

### `git checkout e9826a51 && forge install && make test-ci`

![image](https://github.com/foundry-rs/foundry/assets/45543880/075b7c92-0554-4d9b-97d3-d37819728ec2)


Results: 2gb. looks healthy

### `git checkout e9826a51 && forge install && make test-coverage`

![image](https://github.com/foundry-rs/foundry/assets/45543880/98cde7a3-cbda-434b-b3ca-908fd923fd00)

Results: 15gb. Worse than scenario 6, 3 times more gb usage, definitely something started to happen with forge between version nightly-f625d0fa7c51e65b4bf1e8f7931cd1c6e2e285e9 (check below) and nightly-cafc2606a2187a42b236df4aa65f4e8cdfcea970(this one). Still better than with new forge-std in scenario 2.

# Scenario 6 - the healthiest RAM usage

### Settings

**On forge-std@2f11269** (6 months old, the one we had previously)

**AND Using ds-test@e282159**

nightly-f625d0fa7c51e65b4bf1e8f7931cd1c6e2e285e9

***Note: this checks out to a commit which has our previous forge-std version, the one from 6 months ago, together with ds-test, both still operational***

### `git checkout e9826a51 && forge install && make test-ci`

![image](https://github.com/foundry-rs/foundry/assets/45543880/41594941-a79d-4e89-ae8d-e991cb35c127)


Results: Forge hits around 1.79gb usage

### `git checkout e9826a51 && forge install && make coverage`

![image](https://github.com/foundry-rs/foundry/assets/45543880/5acbd429-a52e-408c-949e-a797c02d2e14)

Results: Forge hits around 5gb usage

---

# Conclusions

- Pinning forge-std to an old commit together with using ds-test, plus reverting to an older foundry version is the best setup to stop the memory leak and continue operating with foundry for us for now as a temporary measure. **The best scenario is 6.**
- Old forge-std versions work well up until nightly cafc260 forge. In newest forge it crashes
- New forge-std version without ds-test import works well back to cafc260. In older forge like f625d0f it crashes
- **We believe new forge version should keep on supporting projects that wish to use older forge-std together with ds-test and not introduce crashes.**
    - We only decided to update forge-std to the latest version because forge started crashing (basically scenario 4). Then we were forced to start taking the memory leak which is impeding our operations.

**Comment by 0xTimepunk** [comment]
This issue is extra tricky to solve in a temporary fix because using latest forge allowed to overcome the problem in https://github.com/foundry-rs/foundry/issues/7852 (which was fixed this month)

**Comment by 0xTimepunk** [comment]
Update:

While this works on our main/develop branches (scenario 6, forge-std 1.7.3 and forge f625d0f), this breaks something in an upstream branch where tests on mainnet are pinned to a more recent block compared to main/develop. In this block a USDC upgrade was already made, which only works with forge-std 1.8.0+ (see release notes of https://github.com/foundry-rs/forge-std/releases/tag/v1.8.0)

### Some testing

Testing forge-std 1.8.0 with f625d0f does not work due to the crash in scenario 3 above.

Then I upgraded again foundry to cafc2606a2187a42b236df4aa65f4e8cdfcea970.

Testing once again (1.8.0 + cafc260) to see if the memory leak is there by running 

`git checkout xxx && forge install && make coverage`
<img width="1355" alt="image" src="https://github.com/foundry-rs/foundry/assets/45543880/4283969d-9966-48f2-9c5e-1200ab389375">


Results: 13gb, the memory leak is back


Conclusion: the memory leak seems to be definitely have been brought up by forge-std in versions >=1.8.0 crossover with forge.

for awareness @mattsse @grandizzy and tagging @mds1 

There is an urgency in solving this situation as this is almost completely halting our development. We need more advice how we can short term fix this to put down the memory leak and have the USDC fix brought up by 1.8.0 in place (is there a commit we can cherry pick for this)

**Comment by grandizzy** [comment]
@0xTimepunk running with trace enabled I can see mem grows when test forks chains (there are many tests with many chains forked running at the same time so eventually OS kicks in and kills the task). What worked for me locally (and I think you can apply it for now as an workaround too to get you going) is to split the `scenarios` test in several steps, as in

```
test-scenarios :; forge test --match-path "test/fuzz/scenarios/scenarios-deposit-multiDst*/*.sol" --no-match-path "test/invariant/**/*.sol" \
&& forge test --match-path "test/fuzz/scenarios/scenarios-deposit-singleDirect*/*.sol" --no-match-path "test/invariant/**/*.sol" ...
```
so mem doesn't ever grow up to the point where process needs to be killed

Looking more into this issue but I think you can use such for now?

**Comment by 0xTimepunk** [comment]
> @0xTimepunk running with trace enabled I can see mem grows when test forks chains (there are many tests with many chains forked running at the same time so eventually OS kicks in and kills the task). What worked for me locally (and I think you can apply it for now as an workaround too to get you going) is to split the `scenarios` test in several steps, as in
> 
> 
> 
> ```
> 
> test-scenarios :; forge test --match-path "test/fuzz/scenarios/scenarios-deposit-multiDst*/*.sol" --no-match-path "test/invariant/**/*.sol" \
> 
> && forge test --match-path "test/fuzz/scenarios/scenarios-deposit-singleDirect*/*.sol" --no-match-path "test/invariant/**/*.sol" ...
> 
> ```
> 
> so mem doesn't ever grow up to the point where process needs to be killed (this also helped me not to get rate limited by infura)
> 
> 
> 
> Looking more into this issue but I think you can use such for now?

Hey @grandizzy  it's super cumbersome to run a large test suite like ours like that suggested way unfortunately.
Thinking on using pre 1.8.0 forge-std plus a temporary fix to avoid dealing USDC

is there any further help we can give on this problem?

Thanks

**Comment by grandizzy** [comment]
yeah, I'm actively looking into this, just provided some thoughts while debugging

**Comment by 0xTimepunk** [comment]
@mattsse @grandizzy requesting to re-open the issue as something got merged around 2 days ago or more into foundry that made the issue appear once again

Ci exits once again with error 137 (out of memory)

Running `make coverage` on https://github.com/superform-xyz/superform-core/pull/516 yield 40gb of ram

![telegram-cloud-photo-size-4-6030658894684078297-y](https://github.com/foundry-rs/foundry/assets/45543880/61e442da-eb85-48a2-8da3-0d2b2a288de4)

**Comment by 0xTimepunk** [comment]
forge 0.2.0 (fb86e5d 2024-06-05T00:17:33.761343000Z) was one of the first versions which contained the initial fix to the memory issue which was working. However, given that the nightlies are removed after 3 days we can no longer access this nightly in the CI

**Comment by grandizzy** [comment]
> @klkvr @grandizzy does this ring a bell?

nothing I could think at but will do some tests shortly and try figure out if something changed to affect this. @0xTimepunk to rule out the possibility of your PR 516 exposing a new issue (as it adds new code and tests), could you please check if you see same coverage problem running latest forge against your master branch?

**Comment by grandizzy** [comment]
I am not able to locally spot any difference between June 5 forge build mentioned as working OK (https://github.com/foundry-rs/foundry/commit/fb86e5d3bf41f9cef3ccc7fbd04e1a422f20c29e) and latest (https://github.com/foundry-rs/foundry/commit/fb86e5d3bf41f9cef3ccc7fbd04e1a422f20c29e)  - when running `make coverage` on https://github.com/superform-xyz/superform-core/commit/68320ffd7190db2abb9b32d5fdf4912bf04275be commit both runs cap around 25G of res mem and completes succcessfully

same when testing v1 branch with both forge versions so I am pretty sure there's no regression. @0xTimepunk maybe there's an issue with the RPC URLs used by your CI that could somehow slow down tests / make mem accumulate?

**Comment by Inphi** [comment]
I'm seeing a variant of this when running `forge test --debug`. Though happy to create a separate issue if this is something else. Here's a small reproducer:

## Foundry Version

forge 0.2.0 (c4a984fbf 2024-06-28T00:53:16.491646468Z)

## Reproducer

```
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import {Test, console} from "forge-std/Test.sol";
import {Counter} from "../src/Counter.sol";

contract CounterTest is Test {
    Counter public counter;
    address addr = address(uint160(uint256(keccak256("ekans"))));

    function setUp() public {
        bytes memory buffer = new bytes(2000000);
        vm.etch(address(addr), buffer);

        counter = new Counter();
        counter.setNumber(0);
    }

    function test_Increment() public {
        counter.increment();
        assertEq(counter.number(), 1);
    }

    function testFuzz_SetNumber(uint256 x) public {
        counter.setNumber(x);
        assertEq(counter.number(), x);
    }
}
```

Running `forge test --debug test_Increment --mc CounterTest` consumes over 32 GB on my machine before the kernel kills it.
I think the critical part is this line here:
```
vm.etch(address(addr), buffer)
```

Etching a really large runtime code seems to trigger the issue. I use an empty buffer for illustrative purposes, but the run still consumes alot of memory even when a valid runtime bytecode is used. Reducing the size of the runtime code seems to work, with minimal memory usage. I'm sure there's some buffer size threshold where memory usage spikes, but I haven't narrowed it down.

**Comment by grandizzy** [comment]
@Inphi yes, please open a new issue for etch, going to use this one to optimize coverage report creation. Thank you.

**Comment by Inphi** [comment]
> @Inphi yes, please open a new issue for etch, going to use this one to optimize coverage report creation. Thank you.

Created an issue [here](https://github.com/foundry-rs/foundry/issues/8283).

Seems related to this issue based on this [comment](https://github.com/foundry-rs/foundry/issues/8283#issuecomment-2197207666). I imagine that the `Debugger` inspector is also used to track coverage which would explain the memory blowup.

**Comment by grandizzy** [comment]
@0xTimepunk can we now close this issue as if I correctly remember it's not the same as original report but a forge coverage high mem usage?
Pls open a new issue for coverage if problem still exists. Thank you!

**Comment by grandizzy** [comment]
@0xTimepunk going to close this for now per above comment, please open a new one if still issues. Thank you!

**Comment by 56789KD** [comment]
View a chang comment.
