### ISSUE TITLE
expectCall started counting calls differently (and probably wrongly)

### ISSUE THREAD

**Issue by vicnaum** [foundry-rs/foundry#8015]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (5494c33 2024-05-30T00:18:25.357590022Z)

### Operating System

macOS (Apple Silicon)

### Describe the bug

On this commit: 299902e34d32c4ea77bf2c8b9b13c68f45113f13 expectCall changed behaviour and started showing more calls than before in some cases (and less calls than before in other cases).

Here are a couple of cases:

1. Expecting a call to MockContract::initialize - the call is done (see screenshot for trace), but expectCall shows 0 and fails the test:
```
        bytes memory data = abi.encodeCall(MockContract.initialize, (address(0xdeadbeef)));

        vm.expectCall(address(hubAsProxy), abi.encodeCall(hubAsProxy.upgradeToAndCall, (hubImplV2, data)));
        vm.expectCall(address(hubImplV2), data);
        vm.prank(controllerContract);
        proxyAdminContract.proxy_upgradeAndCall(hubImplV2, data);
```
<img width="1164" alt="image" src="https://github.com/foundry-rs/foundry/assets/5636644/27e6fa72-29dd-40e3-b2e4-bef9b392fc3c">

2. Expecting a single call to LensHub::getContentURI - but it goes through the Proxy and then to the PublicationLib library - and counts all these as 3 calls for some reason
```
    function testTokenURI() public {
        vm.expectCall(address(hub), abi.encodeCall(hub.getContentURI, (defaultAccount.profileId, defaultPubId)), 1);
        collectNFT.tokenURI(firstCollectTokenId);
    }
```
<img width="1168" alt="image" src="https://github.com/foundry-rs/foundry/assets/5636644/f95f7340-0e22-4421-aa6f-cb4e9350abc8">

While (2) is unpleasant, but manageable by removing the count, (1) is a PITA and breaks the test in a way I cannot fix unless I remove the expectCall.

**Comment by vicnaum** [comment]
Found the exact commit when this happens and updated the issue with it:
299902e34d32c4ea77bf2c8b9b13c68f45113f13

**Comment by mattsse** [comment]
@yash-atreya this could be similar to the access issue, ptal

@vicnaum could you perhaps provide a repro for this?

**Comment by klkvr** [comment]
This is likely because earlier we'd treat a delegatecall as call with `expectCall`.

Repro for this would look like this:
```solidity
contract Simple {
    function initialize() public {}
}

contract SimpleProxy {
    function initialize(Simple impl) public {
        address(impl).delegatecall(abi.encodeWithSignature("initialize()"));
    }
}

contract BugTest is Script {
    function test() public {
        SimpleProxy proxy = new SimpleProxy();
        Simple impl = new Simple();

        vm.expectCall(address(proxy), abi.encodeWithSignature("initialize(address)", address(impl)));
        vm.expectCall(address(impl), abi.encodeWithSignature("initialize()"));

        proxy.initialize(impl);
    }
}
```

works fine before the mentioned commit and fails after

**Comment by yash-atreya** [comment]
> This is likely because earlier we'd treat a delegatecall as call with `expectCall`.
> 
> Repro for this would look like this:
> 
> ```solidity
> contract Simple {
>     function initialize() public {}
> }
> 
> contract SimpleProxy {
>     function initialize(Simple impl) public {
>         address(impl).delegatecall(abi.encodeWithSignature("initialize()"));
>     }
> }
> 
> contract BugTest is Script {
>     function test() public {
>         SimpleProxy proxy = new SimpleProxy();
>         Simple impl = new Simple();
> 
>         vm.expectCall(address(impl), abi.encodeWithSignature("initialize()"));
>         proxy.initialize(impl);
>     }
> }
> ```
> 
> works fine before the mentioned commit and fails after

Thanks for this.
Looking into it.

**Comment by vicnaum** [comment]
Here's my repro of the Proxy with a call, followed by the delegate call:

```
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import {Test, console} from "forge-std/Test.sol";

contract MockContract {
    function initialize(address initializationAddress) public pure {}
}

contract Proxy {
    function upgradeToAndCall(
        address newImplementation,
        bytes memory data
    ) external {
        address(newImplementation).delegatecall(data);
    }
}

contract ProxyController {
    Proxy immutable PROXY;

    constructor(address proxy) {
        PROXY = Proxy(proxy);
    }

    function proxy_upgradeAndCall(
        address newImplementation,
        bytes calldata data
    ) external {
        PROXY.upgradeToAndCall(newImplementation, data);
    }
}

contract ExpectCallTest is Test {
    function testProxyCallDelegateCall() public {
        address implementation = address(new MockContract());
        Proxy proxy = new Proxy();
        ProxyController proxyController = new ProxyController(
            address(new Proxy())
        );

        bytes memory data = abi.encodeCall(
            MockContract.initialize,
            (address(0xdeadbeef))
        );

        vm.expectCall(
            address(proxy),
            abi.encodeCall(proxy.upgradeToAndCall, (implementation, data))
        );
        vm.expectCall(address(implementation), data);

        proxyController.proxy_upgradeAndCall(implementation, data);
    }
}
```

Maybe it's the same thing, but just in case adding it here to reflect my exact case

**Comment by vicnaum** [comment]
I would like to add here another repro case, that uses a library and a proxy:

```
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import {Test, console} from "forge-std/Test.sol";

library LibraryContract {
    function getContentURI(
        uint256 profileId,
        uint256 pubId
    ) external view returns (string memory) {
        return "";
    }
}

contract MainContract {
    function getContentURI(
        uint256 profileId,
        uint256 pubId
    ) external view returns (string memory) {
        return LibraryContract.getContentURI(1, 2);
    }
}

contract Proxy {
    MainContract immutable IMPLEMENTATION;

    constructor(address implementation) {
        IMPLEMENTATION = MainContract(implementation);
    }

    function getContentURI(uint256 profileId, uint256 pubId) external {
        address(IMPLEMENTATION).delegatecall(
            abi.encodeWithSignature(
                "getContentURI(uint256,uint256)",
                profileId,
                pubId
            )
        );
    }
}

contract CollectNFTTest is Test {
    function testTokenURI() public {
        MainContract mainContractImpl = new MainContract();
        Proxy proxy = new Proxy(address(mainContractImpl));

        vm.expectCall(
            address(proxy),
            abi.encodeCall(MainContract.getContentURI, (1, 2)),
            1
        );
        proxy.getContentURI(1, 2);
    }
}
```

It says the call was called 3 times. And I'm not sure if this is correct (it was counted as 1 time before that commit)
