### ISSUE TITLE
feat(`cheatcodes`): improve error handling of unimplemented cheatcodes

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#8016]
When creating custom cheatcodes for a project it would be nice to be able to signal that the test execution ran into an unimplemented cheat code. 

Skipping the test or failing would be the behaviour cases.

**Comment by sambacha** [comment]
Here is another use case:

https://x.com/pcaversaccio/status/1802289404746092880

cc @pcaversaccio

**Comment by zerosnacks** [comment]
Hi @sambacha thanks for your request, is your suggestion limited to improving the reported error handling around unimplemented cheatcodes by returning the cheatcode name or is there more to it?

**Comment by grandizzy** [comment]
there were some changes in this area, an unimplemented cheatcode would now raise an error message like
```
[FAIL: setup failed: unknown cheatcode with selector 0x1d5abda4; you may have a mismatch between the `Vm` interface (likely in `forge-std`) and the `forge` version]
```

Please reopen if you think that this can be improved. Thank you!
