### ISSUE TITLE
Feature request: add an option to specify block "pending" "latest" "finalized" for cast block-number 

### ISSUE THREAD

**Issue by peyha** [foundry-rs/foundry#8028]
### Component

Cast

### Describe the feature you would like

Today, I wanted to check the difference between the block-number from the latest and the last finalized block but couldn't because the option is not implemented on cast

**Comment by mattsse** [comment]
this should be easy but requires a different call

**Comment by kamuik16** [comment]
> this should be easy but requires a different call

can you give some helper refs to get started on this?

**Comment by Degen-Player** [comment]
This exist no ? https://github.com/foundry-rs/foundry/blob/1c6bd3274430b96ea5c0c1f6bf81bb68912e9813/crates/cast/bin/cmd/call.rs#L60

**Comment by mattsse** [comment]
> > this should be easy but requires a different call
> 
> can you give some helper refs to get started on this?

we we'd need additional arguments for the bn command:

https://github.com/foundry-rs/foundry/blob/1c6bd3274430b96ea5c0c1f6bf81bb68912e9813/crates/cast/bin/opts.rs#L330-L335

we could do 

```rust
#[clap(long)]
pending: bool,
#[clap(long)]
finalized: bool,
#[clap(long)]
safe: bool
```

or perhaps even use

```rust
block: Option<BlockId>
```

which would also capture hashes

and then fetch the block number accordingly 

https://github.com/foundry-rs/foundry/blob/1c6bd3274430b96ea5c0c1f6bf81bb68912e9813/crates/cast/bin/main.rs#L257-L259

for safe/finalized, we'd need to fetch the block though and then print its number
