### ISSUE TITLE
feat(`cheatcodes`): add `vm.getFoundryVersion()`

### ISSUE THREAD

**Issue by PatrickAlphaC** [foundry-rs/foundry#8036]
### Component

Forge

### Describe the feature you would like

It would be great if there was a way to get the foundry version in our scripts. I can make sure a script with `ffi`, but it would be cool if there was an API like:

```javascript
vm.getFoundryVersion();
```

To let people know that some tests will only work on certain editions of foundry.

**Comment by PatrickAlphaC** [comment]
(IMO this is super low priority, and probably a good first issue?)

**Comment by LukePereyra** [comment]
Hello! I want to take this Issue !

**Comment by mattsse** [comment]
assigned,
lmk if you need need pointers

**Comment by LukePereyra** [comment]
> assigned, lmk if you need need pointers

oh perfect! I was taking a look into the code, and there is a file (crates/cheatcodes/spec/src/vm.rs) that is the interface with the EVM.
can I add the method getFoundryVersion there? (and then implement it with a Cheatcode)
btw, the foundryVersion is the one that its in Cargo.toml in the section [workspace.package] or that one it's outdate?

**Comment by mattsse** [comment]
> can I add the method getFoundryVersion there? (and then implement it with a Cheatcode)

exactly,

you can get the version by duplicating this in the cheatcodes crate

https://github.com/foundry-rs/foundry/blob/master/crates/forge/bin/opts.rs#L12-L19

**Comment by zerosnacks** [comment]
Hi @LukePereyra, any updates on this ticket? Would be great to get this in

Let me know if you are running into anything or need any pointers

**Comment by leovct** [comment]
Hi @zerosnacks, I'd like to take over if possible.

**Comment by zerosnacks** [comment]
Re-assigning to @leovct

**Comment by zerosnacks** [comment]
Hi @PatrickAlphaC 

There will be a breaking change introduced in https://github.com/foundry-rs/foundry/pull/9683 that changes the format of `vm.getFoundryVersion()` to use a UNIX timestamp and the parsing of the version format is slightly different.

`forge --version` will output a UNIX timestamp alongside a human readable version
