### ISSUE TITLE
Failed to get EIP-1559 fees

### ISSUE THREAD

**Issue by shafu0x** [foundry-rs/foundry#8047]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (0a5b22f 2024-05-21T10:32:10.544355000Z)

### What command(s) is the bug in?

forge script

### Operating System

Linux

### Describe the bug

When I try to deploy on Ethereum Mainnet like this:

```
	forge script script/deploy/Deploy.V2.s.sol \
		--rpc-url $(MAINNET_RPC) \
		--sender $(MAINNET_OWNER) \
		--broadcast \
		--verify \
		-i 1 \
		-vvvv \
		--via-ir \
		--optimize
```

I get the following error `Failed to get EIP-1559 fees` and I have to use `--legacy` to fix this.

But `--legacy` gas estimation is not precise enough to ensure that all txs are going to be included.

**Comment by DaniPopes** [comment]
can you please post the full message, is it an RPC error?

**Comment by mattsse** [comment]
ah this could be a forge version with buggy eth_feeHistory decoding

could you try newest forge, because this has been fixed

**Comment by shafu0x** [comment]
@mattsse yeah this fixed it, didn't realize I was running an old version. thanks

**Comment by vikiival** [comment]
This issue has magically appeared again in Sept 2024 on Base 🥺
Seems the `--legacy` was the fix

- https://github.com/Cyfrin/foundry-full-course-cu/discussions/1743

**Comment by shafu0x** [comment]
you can do `--legacy` but then you might be running into some weird gas miscalulations.
