### ISSUE TITLE
mockCall no longer working with delegatecall

### ISSUE THREAD

**Issue by codenutt** [foundry-rs/foundry#8066]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (fb86e5d 2024-06-05T00:17:41.128117927Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

We had a test start to fail after we upgraded forge. The test was performing a mockCall on an actual contract which is delegatecall'd by another. In the upgraded version, the mockCall is now being ignored. Here is a test to reproduce:
```
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import {Test} from "forge-std/Test.sol";

contract ParentTest is Test {
    Child public child;
    Parent public parent;

    function setUp() public {
        child = new Child();
        parent = new Parent(child);
    }

    function test_GetNum() public {
        assertEq(parent.getNum(5), 5, "beforeMock");

        vm.mockCall(
            address(child),
            abi.encodeWithSelector(IChild.returnNum.selector),
            abi.encode(6)
        );

        assertEq(parent.getNum(5), 6, "afterMock");
    }
}

contract Parent {
    Child internal _child;

    constructor(Child child) {
        _child = child;
    }

    function getNum(uint256 someNum) public returns (uint256) {
        (,bytes memory data) = address(_child).delegatecall(abi.encodeWithSelector(IChild.returnNum.selector, someNum));
        return abi.decode(data, (uint256));
    }
}

interface IChild {
    function returnNum(uint256 someNum) external returns (uint256);
}

contract Child is IChild {
    function returnNum(uint256 someNum) external returns (uint256) {
        return someNum;
    }
}
```
This is the last release where the `test_GetNum` passed: `forge 0.2.0 (cafc260 2024-05-02T00:18:55.934780579Z)`
And appears broken in the next release listed `forge 0.2.0 (5ac78a9 2024-06-02T00:19:17.377492500Z)` and in the latest `forge 0.2.0 (fb86e5d 2024-06-05T00:17:41.128117927Z)`

**Comment by mattsse** [comment]
@yash-atreya could be related to the other delegate call issues we had, ptal
