### ISSUE TITLE
ENS resolution for function parameters has quirky behaviour

### ISSUE THREAD

**Issue by joshieDo** [foundry-rs/foundry#807]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### Describe the bug

ref https://github.com/gakonst/foundry/pull/717

Seems to have some unfortunate effects just from having a `.` in a string parameter unrelated to ENS:
* I effectively cannot write `vitalik.eth` as a string parameter, without it replacing it
* If the RPC is not set to ETH mainnet, a panic happens (ethers-rs fix: https://github.com/gakonst/ethers-rs/pull/963)
* I wonder if there won't be a scenario where i pass a non-ens string (but with a `.`), but somehow gets decoded into an address. Unlikely, but...

I feel like we should revert it, or at least, adding an option to escape `.`

**Comment by gakonst** [comment]
I like that, wonder what @ncitron thinks?

**Comment by ncitron** [comment]
Yeah if someone passes in a valid ENS name as an argument, it ends up getting resolved which could cause some weird issues. However it should work fine if someone passes a string with a period in it that is not a valid name (pending the ethers-rs bug fix).

I think the solution @joshieDo describes works, but ideally we could just handle all ENS parameter resolution in the the `get_func_etherscan` and `encode_args` functions of `foundry_utils`. I had originally tried to go down this route, but ended up battling the compiler and had to add a bunch of crazy trait bounds to functions all the way up the call stack. I'm sure there's some way to get around the problems I ran into, but I'm still getting the hang of rust.

**Comment by 0xYYY** [comment]
How about adding an option like `--no-resolve` (default: false) to skip resolving args?

Required code change would only be adding an option for `cast` and an argument to `TxBuilder.set_args` I think.

**Comment by gakonst** [comment]
@robertabbott check this out
