### ISSUE TITLE
Compile a subdirectory

### ISSUE THREAD

**Issue by aviggiano** [foundry-rs/foundry#8071]
### Component

Forge

### Describe the feature you would like

While working invariant testing projects with Echidna/Medusa, I often encounter a compilation issue related to Foundry's default project structure.

By default, Echidna/Medusa uses [crytic-compile](https://github.com/crytic/crytic-compile) to compile a project using Foundry if `.` is passed as the target. This results in a [`forge build --build-info --skip */test/** */script/** --force`](https://github.com/crytic/crytic-compile/blob/master/crytic_compile/platform/foundry.py#L57-L73) command.

The problem is that this makes it impossible to host invariant tests under `test/invariants` and compile them using Foundry. The only alternative is to pass `--foundry-compile-all` to crytic-compile, which will then fall back to a `forge build --build-info` command. However, this will compile ALL Solidity files, which is also undesired, since in most cases the majority of files are unit and fuzz test files.

This results in a significant slowdown of the invariant testing process, and forces security researchers to either move invariant tests to `src/`, which is semantically incorrect, or to compile everything and waste time.

This feature request suggests introducing a configuration parameter in Foundry that allows specifying a subdirectory for compilation. This can be achieved by extending the forge build command with an option to compile only the specified subdirectory, such as `forge build --dir test/invariants`. This way, we could either update crytic-compile or simply pass `--ignore-compile` to these tools, relying on Foundry's subdirectory compilation.

**Comment by 0xalpharush** [comment]
Happy to coordinate on how best to update this as the binary of `--foundry-compile-all` probably isn't the best solution for fuzzers despite working well for Slither. For background, the reason we force a clean and recompile by default in crytic-compile is the caching logic in Foundry is not robust yet, resulting in strange failures that are really hard to troubleshoot

It seems caching was disabled recently if build info is requested anyway (see https://github.com/foundry-rs/foundry/issues/7379)
