### ISSUE TITLE
Publish docker containers with optional features enables

### ISSUE THREAD

**Issue by rswanson** [foundry-rs/foundry#8072]
### Component

Cast

### Describe the feature you would like

# Overview 

Now that the `--aws` flag is  behind a feature toggle it is not included in the nightly built binary. This means that the foundry github action (`foundry-rs/foundry-toolchain`) won't work if you use any of the cloud signers (`aws-kms`, `gcp`). 

My proposed fix is to update this repo's docker release CD so that it publishes additional docker images where the aws (and probably do one for gcp for good measure) are enabled for people to use in CI; then i'll make a PR to foundry-rs/foundry-toolchain (the GH action that currently won't work anymore)  to add an optional param to the github action to allow for people to request that it use the container with the feature enabled.

Happy to implement this as long as it feels like a good solution to folks. 

# Details

For the `foundry` docker release CD:
- Add a parameter to the dockerfile to 
- Add a matrix of optional features that people would want built and then parameterize the `build` command to spawn multiple parallel docker release paths for each feature we want an image for
- Publish all to github packages using a docker tag structure: maybe `foundry:nightly-aws` and `foundry:nightly-gcp` for example

For the `foundry-toolchain` github action
- Update the `README` to reflect the new potential values for the `version` input that already can be specified

**Comment by rswanson** [comment]
alternative suggestion as well after looking into the release workflow, could we update the release workflow specifically so it builds `forge` and `cast` binaries for the release with the `aws-kms` feature enabled so that i could continue to use the `foundry-rs/foundry-toolchain` github action as normal? Now that these features aren't included all of my ci is broken so i either need to start building foundry from scratch each time or maintain my own set of releases in the meantime with the feature enabled

**Comment by mattsse** [comment]
I'd be okay with enabling it by default or at least ship the binary with this feature enabled

**Comment by rswanson** [comment]
i'll make a pr with this
