### ISSUE TITLE
Add a Command to Calculate ERC7201 Slots in Cast

### ISSUE THREAD

**Issue by 0xHaku** [foundry-rs/foundry#8078]
### Component

Cast

### Describe the feature you would like

To add the `cast erc7201calc example.main` command in cast, which calculates the storage slot based on the EIP-7201 specification

```
keccak256(abi.encode(uint256(keccak256("example.main")) - 1)) & ~bytes32(uint256(0xff));
```

### Additional context

If you have any good ideas for the command name, please share them.

**Comment by DaniPopes** [comment]
There's `cast index` which computes the slot, I think this should be a separate command since the inputs are quite different
