### ISSUE TITLE
Failing to properly parse JSON

### ISSUE THREAD

**Issue by trojanMcAfee** [foundry-rs/foundry#8093]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (7469d79 2024-05-15T00:18:27.094471000Z)

### What command(s) is the bug in?

forge script script/Counter.s.sol:CounterScript --fork-url http://localhost:8545 --broadcast

### Operating System

macOS (Intel)

### Describe the bug

I'm trying to decode the following ZK proof, that lives in a JSON file, into a Solidity struct, but I'm getting continuous either errors or the wrong values:
```js
proof.json (output from circom)

{
  "pi_a": [
   "2720399574835611047319432267519597443800510951793924100709604643916046668864",
   "21169447659913775869641616993668271312873067516271118167674241904778219813622",
   "1"
  ],
  "pi_b": [
   [
    "788356656035051841708358638450195352382615813361747425582051608449447866349",
    "21509538277609533773031757573429186661467719646375006140164215546123692163566"
   ],
   [
    "9028525878891699111734184918251721195102867864970556377714819801325638399258",
    "18633996315291794828222944575811265884401355999740084735365734766162700392691"
   ],
   [
    "1",
    "0"
   ]
  ],
  "pi_c": [
   "5581999086238776195409293931034667783461156042606193706354659978644098138906",
   "11656141149254556914721437054215616892710984578952823965610611542248660952601",
   "1"
  ],
  "protocol": "groth16",
  "curve": "bn128"
 }
 ```
1.- If I use this struct:
```js
struct RootStruct {
    string curve;
    uint[2] pi_a;
    uint[2][2] pi_b;
    uint[2] pi_c;
    string protocol;
}
```
...it runs, but by logging `pi_a[0]` I get `224` instead of `2720399574835611047319432267519597443800510951793924100709604643916046668864`, which I find weird that it runs since `pi_a` is of length 3 and not 2.

It's worth mentioning that when logging `curve`, it successfully logs `bn128`. But when trying to log `protocol`, it throws an empty string.

2.- If I use this struct:
```js
struct RootStruct {
    string curve;
    uint[3] pi_a;
    uint[3][2] pi_b;
    uint[3] pi_c;
    string protocol;
}
```
...it reverts when decoding:
```js
bytes memory data = vm.parseJson(json);
RootStruct memory rootStruct = abi.decode(data, (RootStruct));
Same result also for 1 and 2 if using `bytes32` instead of `uint`.
```

3.- If I try:
```js
uint[] memory x = vm.parseJsonUintArray(json, "pi_a");
```
..., it reverts with the error `script failed: failed selecting from JSON: "path error: \n$pi_a\n^^^^^\n"`, but I'm logging the output of `string memory json = vm.readFile(path)` and it's the proper proof from `proof.json`, so that's working fine.

```js
Full function:

function run() external { 
        uint deployerKey = vm.envUint("PRIVATE_KEY");

        string memory root = vm.projectRoot();
        string memory path = string.concat(root, "/zk/proof.json");
        string memory json = vm.readFile(path);
        bytes memory data = vm.parseJson(json);
        console.logBytes(data);

        RootStruct memory rootStruct = abi.decode(data, (RootStruct));

        path = string.concat(root, "/zk/public.json");
        json = vm.readFile(path);
        data = vm.parseJson(json);
        uint[1] memory signal = abi.decode(data, (uint[1]));

        vm.startBroadcast(deployerKey);

        Verifier2 verifier2 = new Verifier2();
        bool isProof = verifier2.verifyProof(rootStruct.pi_a, rootStruct.pi_b, rootStruct.pi_c, signal);

        console.log('is - true: ', isProof); //<--- false
        console.log('rootStruct.pi_a[0]: ', rootStruct.pi_a[0]); //<---- 224

        vm.stopBroadcast();
    }
 ```

As last notes: 
- It does verify the proof to `true` when passing the raw inputs from `snarkjs generatecall`:
`
["0x0603b10c5a63402f3bf5d882fc448e07b48ce3fc5b0d7cb8f66dec453a041440", "0x2ecd7b96ab070a3423a4cc8118e5c8023def931ddef743ed58e71788f4eafaf6"],[["0x2f8df79cc70e0b9f4cfd9c2c4ff52efc32c2d783a94eaedef0d7d908d0f241ee", "0x01be31ad933394dd91c3e757e6496139538c43115425ff0596287ea4d8b7afed"],["0x293277d9721779eec31e0cfcff09f2c22f8f46d44e0001910b3c2b43a3afd8f3", "0x13f5f6ed375c958f15119371c201cb37531eaa801d4f4b92120a8aa2c39a351a"]],["0x0c574cad70264bb214423cf00cc112e0d2de6c5e7f9119dc672b765bff58431a", "0x19c5246070e29769bb6883a142ce225b8b2e37d4ebad4e8029c85d8844fc6619"],["0x0000000000000000000000000000000000000000000000000000000000000021"]
`

- Issue might be in the `bytes` data output, from `vm.parseJson(json)`, that gets passed to `abi.decode()`,  that does the decoding of a string as though it were an encoded `bytes`.

**Comment by trojanMcAfee** [comment]
bytes data where the encoding issue might be:
`
0x000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000002a000000000000000000000000000000000000000000000000000000000000006c000000000000000000000000000000000000000000000000000000000000008800000000000000000000000000000000000000000000000000000000000000005626e3132380000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000160000000000000000000000000000000000000000000000000000000000000004c323732303339393537343833353631313034373331393433323236373531393539373434333830303531303935313739333932343130303730393630343634333931363034363636383836340000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004d323131363934343736353939313337373538363936343136313639393336363832373133313238373330363735313632373131313831363736373432343139303437373832313938313336323200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000131000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000001c000000000000000000000000000000000000000000000000000000000000003200000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000004b373838333536363536303335303531383431373038333538363338343530313935333532333832363135383133333631373437343235353832303531363038343439343437383636333439000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004d3231353039353338323737363039353333373733303331373537353733343239313836363631343637373139363436333735303036313430313634323135353436313233363932313633353636000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000004c393032383532353837383839313639393131313733343138343931383235313732313139353130323836373836343937303535363337373731343831393830313332353633383339393235380000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004d31383633333939363331353239313739343832383232323934343537353831313236353838343430313335353939393734303038343733353336353733343736363136323730303339323639310000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000013100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000130000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000160000000000000000000000000000000000000000000000000000000000000004c353538313939393038363233383737363139353430393239333933313033343636373738333436313135363034323630363139333730363335343635393937383634343039383133383930360000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004d31313635363134313134393235343535363931343732313433373035343231353631363839323731303938343537383935323832333936353631303631313534323234383636303935323630310000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000013100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000767726f7468313600000000000000000000000000000000000000000000000000
`

**Comment by klkvr** [comment]
Please ensure that alphabetical order of struct arguments matches the order of keys in the JSON object you're trying to decode into given struct: https://book.getfoundry.sh/cheatcodes/parse-json?highlight=alphabetical%20order#decoding-json-objects-into-solidity-structs

**Comment by trojanMcAfee** [comment]
It matches already @klkvr 

I think the issue is on this call `vm.parseJson(json)` and how foundry encodes the JSON into bytes.

**Comment by trojanMcAfee** [comment]
Thanks! That solved it. @klkvr 

Closing this issue.
