### ISSUE TITLE
`forge flatten` includes duplicates when contract imported in multiple files

### ISSUE THREAD

**Issue by niftyorca** [foundry-rs/foundry#811]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (98f0771 2022-02-25T00:34:31.840096006+00:00)

### What command(s) is the bug in?

forge flatten

### Operating System

Linux

### Describe the bug

When using `forge flatten` when the same file is imported in multiple files, the source code of that file is included multiple times in the output.

**Comment by gakonst** [comment]
@rkrasiuk FYI

**Comment by mattsse** [comment]
There's the `NodesIter` struct that returns all unique imports of a specific node @rkrasiuk

**Comment by gakonst** [comment]
How would one go about for solving this?

The imports are fetched [here](https://github.com/gakonst/ethers-rs/blob/master/ethers-solc/src/config.rs#L257). 

Would one need to do something like below to get all the deps minus the current node? (doesn't compile I think)
```
let imports = NodesIter::new(*target_index, &graph).iter().skip(1).collect::<Vec<_>>();
```

**Comment by onbjerg** [comment]
This was solved in https://github.com/gakonst/ethers-rs/pull/995. Let us know if it still does not work for you!
