### ISSUE TITLE
`expectRevert` does not work with duplicate `CREATE2`

### ISSUE THREAD

**Issue by amusingaxl** [foundry-rs/foundry#8110]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (08b2d3e 2024-06-07T00:17:47.048257430Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

I have a contract that deploys another one using `CREATE2`:

```solidity
    function deploy(address _usr, bytes32 _tag) public returns (address _res) {
        _res = address(
            new Handler{salt: keccak256(abi.encode(_usr, _tag))}(
                address(this), _usr, _tag
            )
        );
        emit Deploy(_spell);
    }
```

Then I have a test case to ensure `deploy()` cannot be called twice for the same parameters:

```solidity
    function testRevertDeployTwice() public {
        protego.deploy(address(0x01), "tag1");

        vm.expectRevert();
        protego.deploy(address(0x01), "tag1");
    }
```

I expect the test case above to pass, however I'm facing the following error:

```
> [FAIL. Reason: call did not revert as expected]
```

If I remove `vm.expectRevert()`, I get the following error:

```
    ├─ [8937393460515711181] MyContract::deploy(Handler: [0x0000000000000000000000000000000000000001], 0x7461673100000000000000000000000000000000000000000000000000000000)
    │   ├─ [8937393460515676063] → new Handlder@0x4124E7560D42b3bEB2779DCB8A7929895C7Ff596
    │   │   └─ ← [CreateCollision] 0 bytes of code
    │   └─ ← [Revert] EvmError: Revert
    └─ ← [Revert] EvmError: Revert
```

**Comment by klkvr** [comment]
Could you perhaps provide a repro for this?

I've tried constructing one from the context you've provided, but it runs successfully for me:
```solidity
contract Simple {}

contract SimpleDeployer {
    function deploy(address _usr, bytes32 _tag) public {
        new Simple{salt: keccak256(abi.encode(_usr, _tag))}();
    }
}

contract SimpleTest is Test {
    function test() public {
        SimpleDeployer deployer = new SimpleDeployer();

        deployer.deploy(address(0x01), "tag1");

        vm.expectRevert();
        deployer.deploy(address(0x01), "tag1");
    }
}

```

**Comment by amusingaxl** [comment]
I just had a smol brain&trade; moment ser.
I trimmed down the example for conciseness, however I'm actually calling it like this:

```solidity
        vm.expectRevert();
        factory.deploy(mgr.usr(), mgr.tag());
```

Ofc `vm.expectRevert()` is being applied to `msg.usr()`, because it is called before `factory.deploy()`.
