### ISSUE TITLE
Graceful fail when executing transactions using cheatcode `vm.transact("txn_hash")`

### ISSUE THREAD

**Issue by dsalv** [foundry-rs/foundry#8121]
### Component

Forge

### Describe the feature you would like

I have a list of transaction hashes in a Solidity test. I want to execute them using `vm.transact()` cheatcode. It is possible that some of the transaction fail. When transactions fail, I want to use `try and catch` block in the solidity test to continue execution. Unfortunately, there are transactions that make the execution fail even inside of the `try and catch` block, the execution of `forge test` fails and does not proceed further.

To overcome this issue I have added a `Graceful fail` on transaction execution, where failed transaction execution is logges in the console, but the execution of the test continues. https://github.com/dsalv/foundry/pull/1

I have to run `cargo run --bin forge --manifest-path "path of the file"` to execute the test using my fork. I am not familiar with the whole Foundry code base. I have two questions:

1. Is there any serious violation of the test execution workflow with this change?
2. If this change makes sense, it would be useful to have a flag that lets you execute tests with a `graceful fail` option

This is not a clear feature request, but more of a discussion before the feature request. Let me know what you think.

**Comment by mattsse** [comment]
could you perhaps provide a repro for this case 

> there are transactions that make the execution fail even inside of the try and catch block, the execution of forge test fails and does not proceed further.

**Comment by dsalv** [comment]
[Fork_Simulate.sol.json](https://github.com/user-attachments/files/15779575/Fork_Simulate.sol.json)
Here is the solidity test I was running. 
Please, replace the `ETH_RPC` with your RPC for local runs.

**Comment by dsalv** [comment]
> [Fork_Simulate.sol.json](https://github.com/user-attachments/files/15779575/Fork_Simulate.sol.json) Here is the solidity test I was running. Please, replace the `ETH_RPC` with your RPC for local runs.



> could you perhaps provide a repro for this case
> 
> > there are transactions that make the execution fail even inside of the try and catch block, the execution of forge test fails and does not proceed further.

[Fork_Simulate.sol.json](https://github.com/user-attachments/files/15779586/Fork_Simulate.sol.json)

Here is the solidity test I was running.
Please, replace the ETH_RPC with your RPC for local runs.
