### ISSUE TITLE
cast send returns `server returned an error response: error code -32602: too many arguments, want at most 1` 

### ISSUE THREAD

**Issue by fredo** [foundry-rs/foundry#8122]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6179312 2024-06-10T00:18:46.177980000Z)

### What command(s) is the bug in?

cast send

### Operating System

macOS (Apple Silicon)

### Describe the bug

I'm trying to send a simple transfer with the following command

`cast s --private-key <<PRIV_KEY>> --rpc-url https://rpc.chiado.gnosis.gateway.fm --value 0.1ether <<ADDRESS>> "0x" `

I also tried 

`cast s --private-key <<PRIV_KEY>> --rpc-url https://rpc.chiado.gnosis.gateway.fm --value 0.1ether <<ADDRESS>> `

The server returns 

```
Error:
server returned an error response: error code -32602: too many arguments, want at most 1
```

It most likely fails on `eth_estimateGas`, since when I specify `--gas-limit` it works fine. I also tried connecting to a local RPC where I have access to the logs to and I saw that `estimateGas` is called multiple times. 

I downgraded `foundry` to find the first release where the error pops up. It's https://github.com/foundry-rs/foundry/releases/tag/nightly-cafc2606a2187a42b236df4aa65f4e8cdfcea970

**Comment by fredo** [comment]
This seems to be related to Chiado testnet. On gnosis chain mainnet it works fine. Will test more networks

**Comment by mattsse** [comment]
could you share the logs `RUST_LOG=trace cast...`

too many arguments is weird, perhaps it's the state override arg

checking

**Comment by fredo** [comment]
[log_foundry.txt](https://github.com/user-attachments/files/15776204/log_foundry.txt)

**Comment by mattsse** [comment]
we're def sending a valid request:

> {"method":"eth_estimateGas","params":[{"from":"0xc34b4858cf5f89916559fab2f864384d74b2f996","to":"0xc34b4858cf5f89916559fab2f864384d74b2f996","maxFeePerGas":"0xb368f487","maxPriorityFeePerGas":"0xb368f479","value":"0x38d7ea4c68000","input":"0x","chainId":"0x27d8"},"latest"],"id":2,"jsonrpc":"2.0"}

so it looks like the eth_estimateGas endpoint doesn't fully support the spec?

<img width="1228" alt="image" src="https://github.com/foundry-rs/foundry/assets/19890894/60a6b6a6-caf7-4e4a-90e1-ecd98737accd">

cast rpc web3_clientVersion --rpc-url "https://rpc.chiado.gnosis.gateway.fm/"
"erigon/2.60.1/linux-amd64/go1.21.5"

**Comment by fredo** [comment]
Thanks for digging into it. I will get in touch with the Erigon team. 
So far I can confirm that it only occurred on Erigon clients. However, what bothers me, is that older foundry versions are compatible (as I mentioned April 24 and older)

**Comment by yperbasis** [comment]
Erigon [v2.60.1](https://github.com/ledgerwatch/erigon/releases/tag/v2.60.1) has a breaking change that removes the 2nd argument from `eth_estimateGas`. See https://github.com/ledgerwatch/erigon/pull/10495

**Comment by yperbasis** [comment]
The breaking change was reverted in Erigon [v2.60.2](https://github.com/ledgerwatch/erigon/releases/tag/v2.60.2).

**Comment by mattsse** [comment]
we also fixed this on the client side and exclude the argument if missing
