### ISSUE TITLE
Forge test requires explicitly allowing cheatcodes for new contracts

### ISSUE THREAD

**Issue by Van0k** [foundry-rs/foundry#8150]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8801156 2024-06-13T00:22:06.739865000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Intel)

### Describe the bug

`forge test` fails with "cheatcodes are not enabled for ...; see `vm.allowCheatcodes(address)`" for contracts that are newly deployed during a test on a forked chain. This is also triggered in the constructor of the contract trying to invoke cheatcodes, essentially preventing the test from running without rewriting the respective contract. It doesn't seem that invoking cheatcodes in the constructor specifically is the cause, as this happens in other functions even after the contract is deployed.

![telegram-cloud-photo-size-2-5424855174922492481-y](https://github.com/foundry-rs/foundry/assets/19663524/b73ba1eb-2ba3-4596-b8df-9fc22b2927c9)

The tests in question ran successfully up until yesterday.

The contract in question is [here](https://github.com/Gearbox-protocol/core-v3/blob/69b1a25bb56944d19a6bc60b0da421d39d538d46/contracts/test/mocks/core/AddressProviderV3ACLMock.sol).

**Comment by zerosnacks** [comment]
Hi @Van0k, thanks for your report. Looks like this has been part of Foundry for >2 years, see comments detailing the reasoning for introducing this limitation: https://github.com/foundry-rs/foundry/issues/3042

**Comment by mattsse** [comment]
@Van0k could you try explicitly allowing cheatcodes for this in the constructor call before you deploy new contracts?

**Comment by Van0k** [comment]
> Hi @Van0k, thanks for your report. Looks like this has been part of Foundry for >2 years, see comments detailing the reasoning for introducing this limitation: #3042
 
I understand that, the issue is that (according to the thread) newly deployed contracts should be exempt from this, but it doesn't work like that for me.

**Comment by Van0k** [comment]
> @Van0k could you try explicitly allowing cheatcodes for this in the constructor call before you deploy new contracts?



> @Van0k could you try explicitly allowing cheatcodes for this in the constructor call before you deploy new contracts?

The issue is that the contract that uses cheatcodes is only being deployed - I do not know its address in advance so cannot allow cheatcodes for it from the upper-level contract. Allowing cheatcodes from the constructor of the contract that the runtime complains about does not work.

**Comment by zerosnacks** [comment]
I would generally recommend against using the `Test` abstract inside of deployable mocks. It is not intended to be used like that.

Instead of doing this inside of `PriceOracleMock` it is recommended to move this inside of the test where the `PriceOracleMock` is instantiated

```
    constructor() {
        vm.label(address(this), "PRICE_ORACLE");
    }
```

Marking as `not planned`
