### ISSUE TITLE
Add getRawTransaction endpoint

### ISSUE THREAD

**Issue by guidanoli** [foundry-rs/foundry#8152]
### Component

Anvil

### Describe the feature you would like

Context (from the Telegram group):

> Guilherme Dantas, [13/06/2024 09:39]
> Hey, does anyone know if it is possible to retrieve blob content (blobs, KZG commitments and proofs) after sending blob-carrying txs to anvil?
> 
> Matthias Seitz, [13/06/2024 10:11]
> hmm, we're actually missing the various getRawTransaction endpoints
> could you please open an issue for this, these can be added easily
> 
> Matthias Seitz, [13/06/2024 10:13]
> that's the only way to retrieve them and no guarantee that the blobs still exist, but anvil also keeps them around after they've been mined so the getRawTransaction format should include them

**Comment by mattsse** [comment]
ref 

https://github.com/paradigmxyz/reth/blob/46c8255fa887dcc9d9b65aa9c1c47eeeabc4764d/crates/rpc/rpc/src/eth/api/transactions.rs#L729-L741

this includes endpoints:
* `debug_getRawTransaction`
* `eth_getRawTransactionByHash`
* `eth_getRawTransactionByBlockHashAndIndex`
* `eth_getRawTransactionByBlockNumberAndIndex`


## TODO
* add support for these calls in `EthRequest`, similar: https://github.com/foundry-rs/foundry/blob/f8160598b76ac6fabb0133fe62fab4c432ccb5c9/crates/anvil/core/src/eth/mod.rs#L268-L273
* implement handler in `EthApi`, see reth for reference

**Comment by dorlneylon** [comment]
I think I will take this one
