### ISSUE TITLE
Error in Location: crates/evm/evm/src/executors/invariant/mod.rs:230

### ISSUE THREAD

**Issue by HugoDowsers** [foundry-rs/foundry#8170]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

0.2.0

### What command(s) is the bug in?

forge test --fork-url https://binance.llamarpc.com  --fork-block-number 19078510

### Operating System

Linux

### Describe the bug

When lauching the command, i've got the following message : 

No files changed, compilation skipped
2024-06-14T19:28:20.195771Z ERROR sharedbackend: Failed to send/recv `basic` err=failed to get account for 0x699029b38ca5Ef1d9559ece21B98f5981C305eb8: Max retries exceeded address=0x699029b38ca5Ef1d9559ece21B98f5981C305eb8
The application panicked (crashed).
Message:  could not make raw evm call:
backend: failed while inspecting

Context:
- Error #0: database error: failed to get account for 0x699029b38ca5Ef1d9559ece21B98f5981C305eb8: Max retries exceeded
- Error #1: failed to get account for 0x699029b38ca5Ef1d9559ece21B98f5981C305eb8: Max retries exceeded
Location: crates/evm/evm/src/executors/invariant/mod.rs:230

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                                ⋮ 8 frames hidden ⋮
   9: proptest::test_runner::runner::call_test::h94a7f50e94762e41
      at <unknown source file>:<unknown line>
  10: proptest::test_runner::runner::TestRunner::gen_and_run_case::h817469c4dd8d0e55
      at <unknown source file>:<unknown line>
  11: proptest::test_runner::runner::TestRunner::run_in_process::hcd0b46311676dc9f
      at <unknown source file>:<unknown line>
  12: forge::runner::ContractRunner::run_invariant_test::h55120638ca6b891a
      at <unknown source file>:<unknown line>
  13: rayon::iter::plumbing::bridge_producer_consumer::helper::h4ba7699c373ca576
      at <unknown source file>:<unknown line>
  14: rayon_core::join::join_context::{{closure}}::h801bcfe825e31612
      at <unknown source file>:<unknown line>
  15: rayon::iter::plumbing::bridge_producer_consumer::helper::h4ba7699c373ca576
      at <unknown source file>:<unknown line>
  16: rayon_core::join::join_context::{{closure}}::h801bcfe825e31612
      at <unknown source file>:<unknown line>
  17: <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::ha72919220ed182e7
      at <unknown source file>:<unknown line>
  18: rayon_core::registry::WorkerThread::wait_until_cold::h1b8d643da4e07a77
      at <unknown source file>:<unknown line>
  19: std::sys_common::backtrace::__rust_begin_short_backtrace::hc940be88c9f95cda
      at <unknown source file>:<unknown line>
  20: core::ops::function::FnOnce::call_once{{vtable.shim}}::h488a74cb13bf57a7
      at <unknown source file>:<unknown line>
  21: std::sys::pal::unix::thread::Thread::new::thread_start::h3631815ad38387d6
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Aborted

**Comment by grandizzy** [comment]
please specify the entire forge version (forge --version).  It looks like you're using an older version that doesn't handle error properly, if so please update to latest and retry (most probably test will fail but forge shouldn't panic)

**Comment by grandizzy** [comment]
I run same test and confirm forge does not panic but test just fails with message, I am going to close this one, please update to latest and retry 
![image](https://github.com/foundry-rs/foundry/assets/38490174/57ceaf0a-e754-45c9-899b-f0f3aca6defa)
