### ISSUE TITLE
feature request for cast(UX upgrade): cast block returning block time in human-readable string.  

### ISSUE THREAD

**Issue by JamieShip** [foundry-rs/foundry#8183]
### Component

Cast

### Describe the feature you would like

Every time I query cast block 
```shell
cast block 15944892 --rpc-url=https://rpc.ankr.com/base
```

The response would be like: 
```shell
baseFeePerGas        12951667
difficulty           0
extraData            0x
...
timestamp            1718679131
...
```

I have to copy the timestamp in unix and parse somewhere convert to human-readable GMT string. 
like following:
```shell
baseFeePerGas        12951667
difficulty           0
extraData            0x
gasLimit             90000000
...
timestamp            1718679131	GMT 2024-06-18 02:52:11
```

Or: 

```shell 
baseFeePerGas        12951667
difficulty           0
extraData            0x
gasLimit             90000000
...
timestamp            1718679131
time                 GMT 2024-06-18 02:52:11
```

I want to make a PR for it. But no sure if this would be accepted.

**Comment by mattsse** [comment]
supportive, what you need is

1. include the formatted timestamp here: https://github.com/foundry-rs/foundry/blob/91074f1e9dec3b636db219d42f4441dbfb26b30f/crates/common/src/fmt/ui.rs#L491-L491
2. add chrono dep `chrono.workspace = true` to crates/common/Cargo.toml
3. `chrono::DateTime::from_timestamp(block.header.timestamp as i64, 0).expect("block timestamp in range")` and then format accordingly, for example anvil uses `.to_rfc2822()`
