### ISSUE TITLE
bug(forge): tx.origin is incorrect with prank

### ISSUE THREAD

**Issue by seanmc9** [foundry-rs/foundry#8191]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (35356b0 2024-06-18T00:18:44.897407000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Intel)

### Describe the bug

When you run `forge test`, [this test](https://github.com/jk-labs-inc/refund-contract/blob/f397231486ecc2927d3d22835d1d0f061fc08386/test/RefundContract.t.sol#L17) fails because it is reading `tx_origin` as `0x1804c8AB1F12E6bbf3894d4083f33e07309d1f38`.

I have also tried setting `tx_origin` in `foundry.toml` as well as using the `--tx-origin` flag, both to no avail.

**Comment by klkvr** [comment]
`prank(address sender)` only overrides `msg.sender`. You should use another overload `prank(address sender, address origin)` to override `tx-origin` as well.

https://book.getfoundry.sh/cheatcodes/prank

**Comment by seanmc9** [comment]
oh cool, alright thank you!
