### ISSUE TITLE
Extract forked backend and db to a standalone repo

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#8193]
### Component

Forge

### Describe the feature you would like

This type doesn't really depend on any foundry-specific types

https://github.com/foundry-rs/foundry/blob/91074f1e9dec3b636db219d42f4441dbfb26b30f/crates/evm/core/src/fork/backend.rs#L82-L87

only:

https://github.com/foundry-rs/foundry/blob/91074f1e9dec3b636db219d42f4441dbfb26b30f/crates/evm/core/src/fork/backend.rs#L2-L5

which can also be moved or removed.

## TODO

* extract this mod to a standalone repo: https://github.com/foundry-rs/fork-db together with all the caching types

**Comment by teodorstupnicki** [comment]
hey @mattsse, I would like to give this one a try. Just want to clarify some stuff - this new repo is going to be a submodule of this one?

**Comment by mattsse** [comment]
we will do this in a few steps

2. copy current implementation to crate https://github.com/foundry-rs/alloy-fork-db
3. some touchups maybe
4. replace in foundry by pulling it in

**Comment by teodorstupnicki** [comment]
thanks, understood
