### ISSUE TITLE
feat(anvil): support forking at transaction level

### ISSUE THREAD

**Issue by HrikB** [foundry-rs/foundry#8227]
### Component

Anvil

### Describe the feature you would like

[Recently](https://x.com/rappie_eth/status/1803863049893495278) found out you can fork off a tx in a fork test. A similar feature for anvil would be great. 

I have personally have had times where having the ability to fork in between a flashbots bundle would have been useful.

**Comment by mattsse** [comment]
should the first anvil block contain all txs in the target tx's block up to that target tx or should we start a new block but based on the target tx's state?

**Comment by HrikB** [comment]
IMO the former is likely better in case you wanted to do smth with tx hashes. But I think either would work for most cases (since the state is probably most pertinent part of forking).

**Comment by sergerad** [comment]
@HrikB so the feature request is to add
```
anvil --fork-transaction-hash
```
to the same/similar effect of the `--fork-block-number` feature?

Happy to have a crack at this

**Comment by HrikB** [comment]
Yes that is correct

**Comment by HrikB** [comment]
And yes, you're welcome to take care of the implementation

**Comment by 13550501** [comment]
👍👍👍👍👍
