### ISSUE TITLE
Undeclared identifier for "deal" cheatcode

### ISSUE THREAD

**Issue by Blngogo** [foundry-rs/foundry#8248]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ba9fa20 2024-06-24T00:20:52.822818467Z)

### What command(s) is the bug in?

forge test

### Operating System

Windows

### Describe the bug

Had a EVM revert errors when testing with "deal" cheat code, decided to debug, now im trying with simple test case and it says: "Undeclared identifier"

![tester](https://github.com/foundry-rs/foundry/assets/145844752/2bf969b1-666d-4cf7-a88a-b00ca6a41149)
![tester 2](https://github.com/foundry-rs/foundry/assets/145844752/39e0a416-249d-46c2-bacb-a6162b2af3d3)

**Comment by DaniPopes** [comment]
You're either looking for `vm.deal`, or the `deal` utility in forge-std. In either case, you need to inherit Test: `contract VaultConfig is Test`.

**Comment by Blngogo** [comment]
YEP! Done this million times, but still miss it! I guess it's time for a rest. Thank you very much sir!
