### ISSUE TITLE
bug(`anvil`): unable to use `debug_traceTransaction` structLogs tracer on forked network 

### ISSUE THREAD

**Issue by antazoey** [foundry-rs/foundry#8262]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (7bef9ca 2024-06-26T00:21:14.969821000Z)

### What command(s) is the bug in?

anvil

### Operating System

macOS (Intel)

### Describe the bug

I am able to use debug_traceTransaction w/o specifying the tracer-value for any local transaction, and it works great.
However, when I use a forked network (such as Ethereum mainnet, forked with Anvil), and I use an old transaction hash, such as '0x0537316f37627655b7fe5e50e23f71cd835b377d1cde4226443c94723d036e32`, I get errors that I don't get when the transaction originated during local / testing (not a historical tx picked up from the fork).

the first error I get is like:

```
Fork Error: Transport(HttpError(HttpError { status: 400, body: "{\"jsonrpc\":\"2.0\",\"id\":41,\"error\":{\"code\":-32602,\"message\":\"invalid 2nd argument: options object was missing 'tracer' element\"}}" }))
```

Because my parameters are `{"stepsTracing": true, "enableMemory": true}` which work great for local anvil nodes when tracing, but I guess forked-mode expects something else?

So I tried messing around with parameters. I tried passing `"tracer": "structLogs"` which is valid in Geth but that does not seem to be valid tracer in `revm` or something. I tried excluding all of it together but i get the first error again.

I know before this used to work, so I am not sure what has happened.

Interestingly, Hardhat seems to also suddenly issues similar to this: https://github.com/NomicFoundation/edr/issues/533
And I think they are also using revm now.
Perhaps the real issues lie there?

**Comment by grandizzy** [comment]
@antazoey I think this depends on the capabilities your provider offers, I tried your sample by forking mainnet using alchemy provider and indeed it reproduce the error you posted
```bash
curl -H "Content-Type: application/json" --data '{"method":"debug_traceTransaction","params":["0x0537316f37627655b7fe5e50e23f71cd835b377d1cde4226443c94723d036e32", {"stepsTracing": true, "enableMemory": true}], "id":1,"jsonrpc":"2.0"}' http://localhost:8545
{"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"Fork Error: Transport(HttpError(HttpError { status: 400, body: \"{\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":35,\\\"error\\\":{\\\"code\\\":-32602,\\\"message\\\":\\\"invalid 2nd argument: options object was missing 'tracer' element\\\"}}\" }))"}}
```

However doing the same query against provider directly shows the same issue
```bash
curl https://eth-mainnet.g.alchemy.com/v2/KEY -X POST -H "Content-Type: application/json" -d '{"method":"debug_traceTransaction","params":["0x0537316f37627655b7fe5e50e23f71cd835b377d1cde4226443c94723d036e32", {"stepsTracing": true, "enableMemory": true}],"id":1,"jsonrpc":"2.0"}'
{"jsonrpc":"2.0","id":1,"error":{"code":-32602,"message":"invalid 2nd argument: options object was missing 'tracer' element"}}
```

But if starting anvil with linea fork, querying a tx works without issue:
```bash
curl -H "Content-Type: application/json" --data '{"method":"debug_traceTransaction","params":["0x5d3faa9b9605a8fb04d989a79bfe6d3b708bdcfc66048d2fe18ed2dda4a8297c", {"stepsTracing": true, "enableMemory": true}], "id":1,"jsonrpc":"2.0"}' http://localhost:8545
{"jsonrpc":"2.0","id":1,"result":{"failed":false,"gas":21000,"returnValue":"","structLogs":[]}}
```

Querying directly the provider works too
```bash
curl https://linea-mainnet.g.alchemy.com/v2/KEY -X POST -H "Content-Type: application/json" -d '{"method":"debug_traceTransaction","params":["0x5d3faa9b9605a8fb04d989a79bfe6d3b708bdcfc66048d2fe18ed2dda4a8297c", {"stepsTracing": true, "enableMemory": true}],"id":1,"jsonrpc":"2.0"}'
{"jsonrpc":"2.0","id":1,"result":{"gas":21000,"failed":false,"returnValue":"","structLogs":[]}}
```

Lmk if this makes sense and if good to close this. thank you

**Comment by grandizzy** [comment]
@antazoey going to close this for now, please check comment above and reopen if still an issue. thank you!
