### ISSUE TITLE
feat(config): add support for authentication in `[rpc_endpoints]`

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#8276]
### Component

Forge

### Describe the feature you would like

https://github.com/foundry-rs/foundry/blob/f9674c3ea80ec9cd92e5f96a75542b3a26fa4752/crates/config/src/endpoints.rs#L215-L215

we already support settings like cups and retries:

https://github.com/foundry-rs/foundry/blob/f9674c3ea80ec9cd92e5f96a75542b3a26fa4752/crates/config/src/endpoints.rs#L219-L228

we can easily integrate authentication as well,

this should probably be something like

```rust
auth = "bearer|basic:${BEARER}"
```

## TODO
* support parsing auth field
* integrate in provider setup

**Comment by caiquejjx** [comment]
hey! I'd like to work in this one if available

**Comment by mattsse** [comment]
awesome, lmk if you need some pointers by opening a draft pr

**Comment by caiquejjx** [comment]
@mattsse I was taking a look at it and I wasn't able to completely understand the Provider part as I didn't found the config being used, I appreciate if you can give some pointers

**Comment by mattsse** [comment]
oh interesting, I believe you're right.

let's first add support for auth parsing to the config and then we actually integrate this

**Comment by caiquejjx** [comment]
@mattsse I opened a [PR](https://github.com/foundry-rs/foundry/pull/8570) with the basic stuff of adding the auth field, since I'm not sure how it's going to be used can you check if it's enough for now?
Thanks!
