### ISSUE TITLE
`parseJSON` errors on non-hex strings starting with `0x`

### ISSUE THREAD

**Issue by dyedm1** [foundry-rs/foundry#8277]
### Component

Forge, Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (c8db1e4 2024-06-27T00:18:32.026850000Z)

### Operating System

Linux

### Describe the bug

As specified [here](https://github.com/foundry-rs/foundry/blob/f9674c3ea80ec9cd92e5f96a75542b3a26fa4752/crates/cheatcodes/src/json.rs#L445), the parser will attempt to cast any JSON strings beginning with `0x` to a bytearray (or an address/bytes32 if the size matches). While this interpretation likely works well enough most of the time, there is also the possibility that a string that begins with `0x` is either not intended to be interpreted as a hex value or prefixes only a portion of a string interpretable as hex (where the entire string is not).

As an example, suppose you wanted to represent the `0xBitcoin` [token](https://etherscan.io/token/0xb6ed7644c69416d67b522e20bc294a9a9b405b31#readContract) in JSON. The following JSON:
```
{
"name": "0xBitcoin Token",
"symbol": "0xBTC",
"decimals": 18
}
```

would fail with an error message like `Invalid character 'i' at position 1` if passed into `vm.parseJson`. Similarly, a string beginning with a valid hex substring (such as an address) like `"0x834629f473876e5f0d3d9d269af3dabcb0d7d520-identifier-0"` would also fail once the hyphen was hit: `Invalid character '-' at position 41`.

This is not ideal and can cause unexpected failures if the content of the strings in JSON is unsanitized. Ideally, the parser would fallback to a string upon failure to coerce a value into a bytearray/address/bytes32 instead of returning an error.

**Comment by mattsse** [comment]
do you have a solidity repro for this?
