### ISSUE TITLE
Forge coverage doesn't recognize require with custom error branches

### ISSUE THREAD

**Issue by anajuliabit** [foundry-rs/foundry#8279]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6179312 2024-06-10T00:18:46.177980000Z)

### What command(s) is the bug in?

forge coverage  --ir-minimum

### Operating System

macOS (Apple Silicon)

### Describe the bug

Solidity [0.8.26](https://github.com/ethereum/solidity/releases/tag/v0.8.26) introduce a new overload require(bool, Error) that allows usage of require functions with custom errors. This feature is available in the via-ir pipeline only.

Forge coverage doesn't recognize the `require` branches when using with custom error.

**Comment by gnapoli23** [comment]
I have the same problem while running `forge doc`.

**Comment by gnapoli23** [comment]
FYI: by looking at this commit, the legacy pipeline is allowed in the current setup -> https://github.com/ethereum/solidity/commit/06c27a5e06683a23e31413215e6561d33acf32ea

**Comment by grandizzy** [comment]
this was fixed with https://github.com/foundry-rs/foundry/issues/4294 and will be followed up as branch coverage in https://github.com/foundry-rs/foundry/issues/8423
