### ISSUE TITLE
lcov version 2.1 breaks coverage report

### ISSUE THREAD

**Issue by 0xernesto** [foundry-rs/foundry#8281]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (c8db1e4 2024-06-27T00:18:32.026850000Z)

### What command(s) is the bug in?

forge coverage --report lcov && genhtml lcov.info -o report --branch-coverage

### Operating System

macOS (Apple Silicon)

### Describe the bug

When trying to generate an HTML coverage report based on the `lcov.info` that `forge coverage --report lcov` outputs, the following error occurs:

```shell
Wrote LCOV report.
lcov: ERROR: (inconsistent) "src/MyContract.sol":49:  function MyContract. found on line but no corresponding 'line' coverage data point.  Cannot derive function end line.  See lcovrc man entry for 'derive_function_end_line'.
 (use "lcov --ignore-errors inconsistent ..." to bypass this error)
```

This problem happens if you install `lcov` using Homebrew on MacOS, which currently installs `lcov` version [2.1](https://github.com/linux-test-project/lcov/releases/tag/v2.1).

When downgrading to `lcov` version [1.16](https://github.com/linux-test-project/lcov/releases/tag/v1.16), this problem goes away.

To reproduce error:
```shell
brew install lcov
forge coverage --report lcov && genhtml lcov.info -o report --branch-coverage
```

To get around the error:
Downgrade `lcov` to version [1.16](https://github.com/linux-test-project/lcov/releases/tag/v1.16).

**Comment by grandizzy** [comment]
I think you can just `forge coverage --report lcov && genhtml lcov.info -o report --rc lcov_branch_coverage=1 derive_function_end_line=0` as `derive_function_end_line` is enabled by default in lcov 2.1

**Comment by PierrickGT** [comment]
I've fixed the issue with the following command:
`forge coverage --no-match-path 'test/invariant/**/*.sol' --report lcov && lcov --extract lcov.info --rc lcov_branch_coverage=1 --rc derive_function_end_line=0 -o lcov.info 'src/*' && genhtml lcov.info --rc branch_coverage=1 --rc derive_function_end_line=0 -o coverage`

Locally I'm running:
- `lcov: LCOV version 2.1-1`
- `genhtml: LCOV version 2.1-1`

**Comment by grandizzy** [comment]
awesome, thanks for confirming, not sure if there's any code change we should do here or only document options to run coverage using LCOV versions > 1.16 (as lcov did for their tests backward compatibility https://github.com/linux-test-project/lcov/commit/2bfaf3da897bd8c97acbaa94bb5038fa4692c3f5#diff-bc9ca225569a229568d59f0551dc13b2fb4aa27b6815d0903adac1c17ba0899eR6-R8) @mattsse @DaniPopes @klkvr wdyt? thanks

**Comment by mattsse** [comment]
makes sense to me!

**Comment by grandizzy** [comment]
Docs updated with https://github.com/foundry-rs/book/pull/1237

**Comment by DaniPopes** [comment]
This is fixed with https://github.com/foundry-rs/foundry/pull/9438.
