### ISSUE TITLE
Foundry incorrectly asseses gas costs when using proxy

### ISSUE THREAD

**Issue by novaknole** [foundry-rs/foundry#8289]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (f479e94 2024-06-01T00:19:17.421178000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

Assume the following contract:

```js
pragma solidity ^0.8.8;
import "forge-std/console.sol";

import {UUPSUpgradeable} from "@openzeppelin/contracts-upgradeable/proxy/utils/UUPSUpgradeable.sol";

contract Nice is UUPSUpgradeable {
    function test(uint256 _allowFailureMap, bytes calldata _metadata) public {
        console.log(gasleft());
    }

    function _authorizeUpgrade(address) internal override {}
}
```

There're 2 scenarios and the problem/bug happens only when `Nice` is deployed with proxy.

```js
Nice nice = new Nice();
Nice proxy = Nice(createProxyAndCall(address(nice), bytes("")));

```

Then, inside the tests, I do:

```js
(bool success, ) = address(proxy).call{gas: 380000}(
    abi.encodeWithSelector(Nice.test.selector, 0, "dummy")
);
(bool success, ) = address(proxy).call{gas: 420000}(
    abi.encodeWithSelector(Nice.test.selector, 0, "dummy")
);
```

After checking each case, It's clear that in both cases,  the total amount of gas is forwarded to the proxy. In first case, 380000 is forwarded to proxy and in 2nd case, 420000 is forwarded. The way I check this is inside stack trace, I look at `call` opcode which in the stack shows the total amount. 

Then, in first case, proxy forwards `377728` to the logic and in 2nd case, proxy forwards `417728`. It's clear that proxy contract code used the exact amount of gas.  The way I check this is in the strack trace, when delegatecall opcode is shown, I look at the stack and take the first top value which is `g`(i.e how much gas it will forward).

The strange thing is that `gasleft()` inside the `Nice` prints the following:
* in 1st case, 368807
* in 2nd case, 408182

in 1st case, forwarded gas to logic was 377728 and at the time of printing `gasLeft`, it was 368807, so we can do: 377728 - 368807 = 8921.

In 2nd case, forwarded gas to logic was 417728 and at the time of printing `gasleft`, it was 408182, so we can do 417728 - 408182 = 9546

How did we get different results(i.e 8921 and 9546) ? They must be the same. What's going on ?

**Comment by klkvr** [comment]
If I understood your issue right, then couldn't this be just a proxy overhead?

when calling a `Nice` created directly, you are just executing its bytecode, and when it's called through proxy there's additional cost of reading implementation from storage, copying calldata into memory for delegatecall, and doing `DELEGATECALL` itself.

**Comment by novaknole** [comment]
@klkvr

ofc, I know that. The problem is different.

```js
// This prints 373000
(bool success, ) = address(proxy).call{gas: 380000}(
    abi.encodeWithSelector(Nice.test.selector, new IDAO.Action[](0), 0, "dummy")
);
// This prints 412375
(bool success, ) = address(proxy).call{gas: 420000}(
    abi.encodeWithSelector(Nice.test.selector, new IDAO.Action[](0), 0, "dummy")
);
```

Passing different `gasLimit` is what causes it to print different values. Please,read the original question again.

**Comment by klkvr** [comment]
I see, then that's likely EIP-150

> If a call asks for more gas than the maximum allowed amount (i.e. the total amount of gas remaining in the parent after subtracting the gas cost of the call and memory expansion), do not return an OOG error; instead, if a call asks for more gas than all but one 64th of the maximum allowed amount, call with all but one 64th of the maximum allowed amount of gas

625 is exactly 1/64th of a diferrence between your gas limit amounts (`40000/64`). And this reduction only takes place for a proxy because the condition "call asks for more gas than the maximum allowed amount" does not hold for a root call, but does hold for internal delegatecall

**Comment by novaknole** [comment]
@klkvr I truly don't get what you mean.

Remember, that I specify so big gas limits(380000 and 420000) where the function maximum needs 50000 to succeed). So your logic doesn't seem to work here. When I call `Nice`, sure that proxy gets called and all the gas is forwarded, but note that 64th rule only works if I don't specify the gas limit manually.  Try this in remix and you will see. Also, I don't understand why the proxy makes any difference because my manual gas is forwarder to proxy which forwards all the gas to the Nice's logic contract.

**Comment by novaknole** [comment]
@klkvr thanks for so many follow-ups.

Would you know why on the debugger, the top most element at the time of `delegatecall` opcode shows the total gas amount instead of 63/64 of it ?

**Comment by klkvr** [comment]
This is because the gas reduction is performed after the opcode is being invoked. So if gas limit of 100.000 is passed to the opcode, the delegatecall frame will start with 98437 remaining

**Comment by novaknole** [comment]
@klkvr Thanks so much.

Would you happen to know how to test the following ? In one of my contracts(function `execute`), it expects multiple calldatas and uses `call` opcode to call each one of them. Due to my requirements, I need to track when the call fails out of gas error. See below(since solidity doesn't have OOG exception implemented).

Something like:

```
function execute(address[] tos, bytes[] memory datas) {
  for(uint i = 0; i <datas.length; i++) {
     uint256 gasBefore = gasleft();
     (bool success, ) = tos[i].call{value:0}(datas[i]);
     uint256 gasAfter = gasleft();
     if (gasAfter < gasBefore / 64) {
          revert insufficientGas();
      }
  }
}
```

The test I was thinking to write would consist of these steps.

1. call `execute` normally and get `vm.lastCallGas().gasTotalUsed`
2. Then, revert the state(go back to old snapshot before calling `execute`, so cold access would be in place) and now, pass the amount of gas manually to `execute` as the amount: `vm.lastCallGas().gasTotalUsed - 1000` (I took 1000 just to ensure that it would fail with `insufficientFunds` custom error).

I wonder isn't there any more straightforward way to test such thing ?
