### ISSUE TITLE
Error:  Etherscan could not detect the deployment.

### ISSUE THREAD

**Issue by AbolfazlR5** [foundry-rs/foundry#8304]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 

### What command(s) is the bug in?

forge script ./script/Chatter.s.sol:ChatterScript --rpc-url http://localhost:1248 --broadcast --sender 0xe723db61481390dFe97558fF454f9B0F40181830 --unlocked --chain-id 11155111 --verify

### Operating System

macOS (Intel)

### Describe the bug

Hello everyone,
I am facing an issue while trying to upload my smart contract on the Sepolia testnet network. Although the deployment is successful and I can view the transaction on Sepolia Etherscan, the input data for the contract is empty. Also when I am trying to verify the contract I receive this error "Error: Etherscan could not detect the deployment." 

I would highly appreciate it if you could help me with this.

here is my script contract code

```solidity
//SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Script} from "forge-std/Script.sol";
import {Chatter} from "../src/Chatter.sol";

contract ChatterScript is Script {

    function run() public{
        vm.broadcast();
        new Chatter();
    }

}
```

**Comment by klkvr** [comment]
Such error usually means that you have to wait a bit while Etherscan is indexing your contract. If that happens, running script with `--resume` flag after some time should help

**Comment by AbolfazlR5** [comment]
> Such error usually means that you have to wait a bit while Etherscan is indexing your contract. If that happens, running script with `--resume` flag after some time should help

I did, but unfortunately I am getting the same error again. Also the contract itself has no input data on Etherscan for Sepolia network again.

**Comment by klkvr** [comment]
does the deployed contract has any code? can you share the deployment transaction?

**Comment by AbolfazlR5** [comment]
> does the deployed contract has any code? can you share the deployment transaction?

No there is no code within the contract. This is the transaction hash "0x12f248de3fd27fcb7b0f03a845d8c1819860583d54271bbdbfcc68399ea5ff1a"

**Comment by klkvr** [comment]
right, so this is basically a CREATE transaction with empty data, this contract can't be verified.

Can you reproduce this reliably? Does script artifacts look correct?

**Comment by AbolfazlR5** [comment]
> right, so this is basically a CREATE transaction with empty data, this contract can't be verified.
> 
> Can you reproduce this reliably? Does script artifacts look correct?

Yeah everything looks fine I just double checked it.

**Comment by zerosnacks** [comment]
Marking as `invalid` as the deployed contract is empty (`0x`)

Your contract will need to be more substantial in order to be verified

Feel free to re-open with an additional minimal reproduction

**Comment by notchuks** [comment]
@zerosnacks the contract has some code. I am having the exact same issue. Here is the smart contract;

```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.13;

contract Chat {
    event Message(address indexed sender, string message);

    function sendMessage(string calldata message) public {
        emit Message(msg.sender, message);
    }
}
```

After deploying on sepolia, the verification times out.

**Comment by klkvr** [comment]
@notchuks are you on latest nightly? thinking this might have been fixed by https://github.com/foundry-rs/foundry/pull/8532

**Comment by notchuks** [comment]
@klkvr I will run foundryup right now and retry this. Thanks for the speedy response.

**Comment by notchuks** [comment]
It times out with the same response: `Etherscan could not detect the deployment.` Here is the contract address: 0x470bCcb64Abce80b0618E6c8F59E610738F9AaAa 
![Screenshot from 2024-08-21 18-12-03](https://github.com/user-attachments/assets/3aad4dd8-fc90-4e72-b883-d8bed5d02742)

**Comment by klkvr** [comment]
you mind sharing script artifacts from `broadcast/` folder?
