### ISSUE TITLE
Bug: Forge Flatten includes compiling errata messages at top of file

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#8312]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### Operating System

macOS (Apple Silicon)

### Describe the bug

When using `forge flatten` we get for example:

```console
Compiling 2 files with Solc 0.8.22
Solc 0.8.22 finished in 12.39ms
```

at the top of the flatten file.

**Comment by mattsse** [comment]
thanks, fixed via #8313
