### ISSUE TITLE
personal_sign "Invalid string length"

### ISSUE THREAD

**Issue by ssadler** [foundry-rs/foundry#8322]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [x] Foundry
- [x] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9058812 2024-07-01T00:22:58.417438907Z)

### What command(s) is the bug in?

anvil

### Operating System

Linux

### Describe the bug

personal_sign returns an error "Invalid string length"; I have played around with different string lengths (multiple of 4 bytes, 32 bytes hex encoded etc) and I couldn't get it to work.

The same request does work with Metamask, as well as Geth (though with Geth you have to provide a wallet unlock password as a 3rd parameter).

```bash
$ curl --location 'localhost:8545/' --header 'Content-Type: application/json' --data "{ \"id\": 36, \"jsonrpc\": \"2.0\", \"method\": \"personal_sign\", \"params\": [ \"0x7b22626c6f636b48617368223a22307833643062613065303032636463343564343836383966346437613739366661333135666561343437666533613765333239646136323836323233366266373962222c227075626c69634b6579223a22307830346231623661643361636434363366383338366363653362313233333736316164353837383935376565663365306530373838353536336231353130386130643436356635303437616637383365343630376333386661646333316631303237353037373335353830333164653332306231393666656333616363343261353066222c227365636f6e6473223a313230393630307d\", \"0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266\" ] }"
{"jsonrpc":"2.0","id":36,"error":{"code":-32602,"message":"Invalid string length"}}
```

**Comment by DaniPopes** [comment]
You got the parameters in the wrong order, it's address then bytes, see <https://ethereum.github.io/execution-apis/api-documentation/>

https://github.com/foundry-rs/foundry/blob/dee33a00b2572784d63755b937db61de6954f2e8/crates/anvil/core/src/eth/mod.rs#L143-L145

**Comment by mattsse** [comment]
looks like anvil has the wrong order

https://docs.metamask.io/wallet/reference/personal_sign/
