### ISSUE TITLE
Allow forking from different RPCs/block numbers when testing

### ISSUE THREAD

**Issue by 0xTomoyo** [foundry-rs/foundry#834]
### Component

Forge

### Describe the feature you would like

Currently if you want to test against mainnet state, you can pass in an RPC url and block number to fork from. However it isn't possible to run tests on multiple networks or fork from different block numbers.

For example, you might want 1 test to run against the state at block number 10000, and another at block number 20000.

Hardhat has a method called `hardhat_reset` which allows you to change the RPC url/block number mainnet state is forked from: https://hardhat.org/hardhat-network/guides/mainnet-forking.html#resetting-the-fork

A cheatcode similar to that would be useful. It could look like this:

```solidity
hevm.reset("https://infura.io/....", 12345);
```

**Comment by tynes** [comment]
Another thought - perhaps it would be better to have named urls in the config file and then use the name as the first arg to `hevm.reset`, then you wouldn't need to commit secrets into tests

**Comment by gakonst** [comment]
> Another thought - perhaps it would be better to have named urls in the config file and then use the name as the first arg to hevm.reset, then you wouldn't need to commit secrets into tests

Maybe we can add a `vm.env(string)(string)` cheatcode which loads an environment variable?

**Comment by tynes** [comment]
`vm.env(string)(string)` could be generally useful in different ways, could the env vars be automatically injected from `.dapprc` or something like that at runtime? Also just wondering about the case where the largest possible env var is pulled in, I feel like its an unlikely edge case and should be fine. I also think similar functionality could be achieved with `hevm.ffi` if you read an env var, use `cast` to abi encode the data and then pass it to `echo -n`

**Comment by cantbeevil** [comment]
any status update for this?

**Comment by onbjerg** [comment]
I don't think this is being worked on actively - @mattsse might be working on something similar for #1037 that can be ported to Forge as well, but I'm not sure

**Comment by mattsse** [comment]
yes there'll be an option to reset/ and change this on the fly, but since this concerns forge, lets keep this open

**Comment by hexonaut** [comment]
+1ing this from MakerDAO as we are very focused on cross-chain support for MCD.

**Comment by mattsse** [comment]
Support for this has landed in Anvil PR, but has not yet been incorporated into testing,

we'd need some cheatcodes first for that @onbjerg ?

**Comment by onbjerg** [comment]
> Support for this has landed in Anvil PR, but has not yet been incorporated into testing,
> 
> we'd need some cheatcodes first for that @onbjerg ?

Yes! We'd need two things:

1. A cheatcode to read config *or* environment variables so people don't paste RPC URLs directly into tests
2. A channel between the cheatcodes handler and the backend handler where we can pass messages like `connect`/`disconnect`/`swap` etc.

For 1. we can either add `vm.env(string) returns (string)` as @gakonst suggested or we can do something like `vm.chain(uint256)` that then reads the relevant config from `foundry.toml` and checks that the chain ID matches what we expect.

**Comment by onbjerg** [comment]
Not really. My only concern about only `vm.env` for this is that it's easy to set the wrong RPC URL in an environment variable, so to be safe you'd have to check that the chain ID matches what you expect, which some people may want yet another cheatcode for instead of using `block.chainid`. So, either we use `vm.env` for this + some helper in Forge Std, or we use `vm.chain` (or something better) for this feature and add `vm.env` in a separate task.

**Comment by gakonst** [comment]
One idea in the middle:
1. Adding a chainId -> RPC url mapping to Foundry toml
2. Vm.setFork (h/t @brockelmore) which would reset the url in the backend handler

Main thing to keep in mind imo is how do you maintain the in memory cache as you switch forks

**Comment by mds1** [comment]
FWIW this is also relevant to https://github.com/foundry-rs/foundry/issues/939. We'll need a block number anyway, so perhaps we can use `vm.setFork(string rpcUrl, uint256 blockNumber)` to solve both of these

**Comment by mds1** [comment]
> `vm.setFork(string rpcUrl, uint256 blockNumber)` would either set or, change the fork for the remainder for the test or until the next `vm.setFork` is called, right?

This sounds right to me, but worth considering `fork` / `startFork` / `stopFork` semantics to be consistent with other cheatcodes + enable switching to no fork if needed.

> so a possible solution would be to switch out the `read` halve when switching fork

Hmm, do we also need to switch out the `write` half? I'm imagining a case where a contract exists at the same address on two chains, but with different state. If I update that contract's state while forking from chain 1, we should ensure that we don't read that new state when I later switch to chain 2

**Comment by mattsse** [comment]
so each fork has its own state, which you can load into the current context (`setFork`)

How would we handle the state of the test contract that we're currently in? clone when changing fork?
