### ISSUE TITLE
forge coverage report does not show modifiers that revert

### ISSUE THREAD

**Issue by joaobrunoah** [foundry-rs/foundry#8347]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (7226aa06b 2024-07-02T23:13:43.699201000Z)

### What command(s) is the bug in?

forge coverage

### Operating System

macOS (Apple Silicon)

### Describe the bug

I have the following contract and test:

Contract A:
```
pragma solidity ^0.8.24;

contract ContractA {
    error CustomError();

    modifier withValidNumber(uint256 number) {
        if (number > 1e18) {
             revert CustomError(); // this line is never hit by `forge coverage`
        }
        _;
    }

    function mockWithValidNumber(uint256 number) external view withValidNumber(number) {
        // Do Nothing
    }
}
```

Test of Contract A
```
pragma solidity ^0.8.24;

import {ContractA} from "ContractA.sol";

contract ContractATest is Test{
    function testInvalidNumber() public {
        ContractA contract = new ContractA();
        vm.expectRevert(ContractA.CustomError.selector);
        contract.mockWithValidNumber(1.5e18);
    }
}
```

The test `testInvalidNumber` passes, but in the forge coverage the line with `revert CustomError();` is never hit.

**Comment by grandizzy** [comment]
hm, I cannot reproduce the issue, see below

![image](https://github.com/foundry-rs/foundry/assets/38490174/60095a70-3901-4682-912b-37f5f0ea9c20)

I used
```
forge coverage --mt testInvalidNumber --report lcov
genhtml lcov.info -o report --branch-coverage && firefox report/index.html
```

with a slightly changed test (imported ds-test and renamed `contract` var)

```Solidity
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";

import {ContractA} from "src/ContractA.sol";

contract ContractATest is Test {
    function testInvalidNumber() public {
        ContractA a = new ContractA();
        vm.expectRevert(ContractA.CustomError.selector);
        a.mockWithValidNumber(1.5e18);
    }
}
```

Are you sure `forge coverage --mt testInvalidNumber --report lcov` does not yield any test failure?

**Comment by grandizzy** [comment]
ping @joaobrunoah can you pls check comment above? thanks!

**Comment by joaobrunoah** [comment]
@grandizzy, you're correct. I tested it here, and it works with ContractA. I have a scenario in which it does not work, but I couldn't isolate the reason. It may be related to my code somehow.

For now, I think the best alternative is to close this issue. If I find the reason and it's a forge bug, I can reopen this or open another ticket.
