### ISSUE TITLE
`cast interface` downcasts `enum` types to `uint8`

### ISSUE THREAD

**Issue by gosuto-inzasheru** [foundry-rs/foundry#8379]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (1bac1b3 2024-07-06T00:21:09.672306000Z)

### What command(s) is the bug in?

cast interface

### Operating System

None

### Describe the bug

as originally reported by @Elyx0 here: https://github.com/foundry-rs/foundry/issues/2722#issuecomment-1236439906

for example the aave pool implementation contract `0x5FAab9E1adbddaD0a08734BE8a52185Fd6558E14` has the following enum (via imported `Datatypes`):
```
enum InterestRateMode {
  NONE,
  STABLE,
  VARIABLE
}
```
and if we then
```
cast interface 0x5FAab9E1adbddaD0a08734BE8a52185Fd6558E14
```
we get
```
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.4;

interface Pool {
    type InterestRateMode is uint8;
[...]
```

but if we now use this interface, we cannot pass it `DataTypes.InterestRateMode.STABLE`; the interface expects a `uint8` instead

**Comment by DaniPopes** [comment]
This information is not present in the JSON ABI, it's possible to go fetch it in the source code but would require a lot of extra complexity in the code.

**Comment by gosuto-inzasheru** [comment]
thanks @DaniPopes. makes sense to close this then i guess :)
