### ISSUE TITLE
Feature: add option or argument to `forge build` to compile specific .sol file

### ISSUE THREAD

**Issue by programskillforverification** [foundry-rs/foundry#8382]
### Component

Forge

### Describe the feature you would like

Every time I run `forge build`, it compiles all solidity files in current project. Sometimes, I only want to compile single specific .sol file or two, three files and make other files have syntax error.

**Comment by grandizzy** [comment]
that's already supported, use `forge build PATH_TO_FILE_OR_DIR` https://book.getfoundry.sh/reference/forge/forge-build#build-options

**Comment by programskillforverification** [comment]
@grandizzy thx, it's my fault to ignore this when referencing doc.

**Comment by grandizzy** [comment]
no worries, is something that was just added. Going to close this one for now
