### ISSUE TITLE
Anvil is consuming high disk space ( more than ~ 25Gi in 1 hour)

### ISSUE THREAD

**Issue by AnieeG** [foundry-rs/foundry#8392]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

anvil 0.2.0 (ed79650 2024-06-29T05:54:37.892564901Z)

### What command(s) is the bug in?

 anvil --chain-id 90000038 --block-time 1 --gas-limit 100000000 --code-size-limit 30000 --base-fee 1000000 --host 0.0.0.0 --port 8545 --accounts 20 --balance 2000000000000000000 --state /state/dump.json --state-interval 60 --transaction-block-keeper 500

### Operating System

Linux

### Describe the bug

With the recent anvil version the disk usage in anvil working dir is getting extremely high.
Here are some usage data when I ran `du` on the container's working dir.

```
4.0M    ./lib
31.9M   ./state
207.0M  ./usr
24.8G   ./home/foundry/.foundry/anvil/tmp/anvil-state-08-07-2024-22-10fvxvIm   
```

![image](https://github.com/foundry-rs/foundry/assets/88458927/44cd698a-b18e-455c-8835-09dd6a1d0074)

I am performing a load test which used to work with ` forge 0.2.0 (0a5b22f 2024-05-21T10:30:02.156279959Z)`
but with the recent version upgrade the high disk usage is causing the pod to get evicted. 
The load test sends a high volume of tx into the anvil node ( ~ 10-100 tx per 5 second ).

Is there any recent update which can be the cause of this high disk consumption? Is there any work around for this issue?

**Comment by grandizzy** [comment]
since https://github.com/foundry-rs/foundry/pull/8160 all blocks are dumped in json file

**Comment by AnieeG** [comment]
Is there a plan to optimize the consumption? I am not able to find the previous working version in the list of foundry images. Is there any suggested version I can use to avoid this issue?

**Comment by grandizzy** [comment]
do you need to keep the state dump during test load or could you just prune it periodically?

**Comment by AnieeG** [comment]
I need to keep the state, I tried to use` --prune-history` but getting the following error -
`BlockOutOfRangeError: block height is 3491 but requested was 3492`

**Comment by grandizzy** [comment]
you could probably try with this version https://github.com/foundry-rs/foundry/releases/tag/nightly-5ac78a9cd4b94dc53d1fe5e0f42372b28b5a7559

**Comment by grandizzy** [comment]
also wonder if setting up something like a logrotate job to compress file if certain size exceeded would work

**Comment by kalverra** [comment]
> also wonder if setting up something like a logrotate job to compress file if certain size exceeded would work

Would this compression disallow reading that block data?

**Comment by AnieeG** [comment]
I have used` anvil 0.2.0 (5ac78a9 2024-06-02T00:20:14.684725967Z) `and still see this 
![image](https://github.com/foundry-rs/foundry/assets/88458927/bb381bea-298d-4630-bf24-e5fcdfc50c29)

Is there a way to find the image related to this version -`  forge 0.2.0 (0a5b22f 2024-05-21T10:30:02.156279959Z)`

**Comment by grandizzy** [comment]
> > also wonder if setting up something like a logrotate job to compress file if certain size exceeded would work
> 
> Would this compression disallow reading that block data?

yes, they would need to be uncompressed in order to read it. I am going to propose a patch to add option for dumping blocks in json so will be having the same format as it used to be if disabled

**Comment by grandizzy** [comment]
> I have used`anvil 0.2.0 (5ac78a9 2024-06-02T00:20:14.684725967Z)`and still see this ![image](https://private-user-images.githubusercontent.com/88458927/347075844-bb381bea-298d-4630-bf24-e5fcdfc50c29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1ODk2OTYsIm5iZiI6MTcyMDU4OTM5NiwicGF0aCI6Ii84ODQ1ODkyNy8zNDcwNzU4NDQtYmIzODFiZWEtMjk4ZC00NjMwLWJmMjQtZTVmY2RmYzUwYzI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDA1Mjk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYWJiYTA4NWVlNDc4NjZiMDdiMzc1MDRlNDE3ZjMwNmQzOWVjYWFkN2NmMWFiMjhmYTQxOWE2OWI5NDcwMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rG2LFl0oMGmJZacut2880aDZJ7PsW3LN4VuqxLFj4Ic)
> 
> Is there a way to find the image related to this version -` forge 0.2.0 (0a5b22f 2024-05-21T10:30:02.156279959Z)`

hm, I thought is because the `/state/dump.json` size, but looks it is rather the anvil state cache. Can you pls confirm the size of `/state/dump.json` ?

**Comment by grandizzy** [comment]
the `max_on_disk_limit` https://github.com/foundry-rs/foundry/blob/82ff8ee338818e6a6dc356e4c72ab72d31965375/crates/anvil/src/eth/backend/mem/storage.rs#L58-L61
is set to 3600
https://github.com/foundry-rs/foundry/blob/82ff8ee338818e6a6dc356e4c72ab72d31965375/crates/anvil/src/eth/backend/mem/storage.rs#L45-L46

I think would make sense to have it configurable for handling scenarios like in this ticket, @mattsse wdyt?

**Comment by mattsse** [comment]
definitely, opening an issue for this: https://github.com/foundry-rs/foundry/issues/8399

**Comment by AnieeG** [comment]
> > I have used`anvil 0.2.0 (5ac78a9 2024-06-02T00:20:14.684725967Z)`and still see this ![image](https://private-user-images.githubusercontent.com/88458927/347075844-bb381bea-298d-4630-bf24-e5fcdfc50c29.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1ODk2OTYsIm5iZiI6MTcyMDU4OTM5NiwicGF0aCI6Ii84ODQ1ODkyNy8zNDcwNzU4NDQtYmIzODFiZWEtMjk4ZC00NjMwLWJmMjQtZTVmY2RmYzUwYzI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDA1Mjk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYWJiYTA4NWVlNDc4NjZiMDdiMzc1MDRlNDE3ZjMwNmQzOWVjYWFkN2NmMWFiMjhmYTQxOWE2OWI5NDcwMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rG2LFl0oMGmJZacut2880aDZJ7PsW3LN4VuqxLFj4Ic)
> > Is there a way to find the image related to this version -` forge 0.2.0 (0a5b22f 2024-05-21T10:30:02.156279959Z)`
> 
> hm, I thought is because the `/state/dump.json` size, but looks it is rather the anvil state cache. Can you pls confirm the size of `/state/dump.json` ?

The` /state/dump.json` is quite alright. In the screenshot I posted in description of this issue you will find `31.9M   ./state` whereas the /home cache has grown huge - `24.8G   ./home/foundry/.foundry/anvil/tmp/anvil-state-08-07-2024-22-10fvxvIm  `

**Comment by AnieeG** [comment]
> the `max_on_disk_limit`
> 
> https://github.com/foundry-rs/foundry/blob/82ff8ee338818e6a6dc356e4c72ab72d31965375/crates/anvil/src/eth/backend/mem/storage.rs#L58-L61
> 
> 
> is set to 3600
> https://github.com/foundry-rs/foundry/blob/82ff8ee338818e6a6dc356e4c72ab72d31965375/crates/anvil/src/eth/backend/mem/storage.rs#L45-L46
> 
> I think would make sense to have it configurable for handling scenarios like in this ticket, @mattsse wdyt?

Could you please also add a documentation for this? If the MAX_ON_DISK_HISTORY_LIMIT is over will I encounter similar error (`BlockOutOfRangeError: block height is 3491 but requested was 3492`) as I was getting for `--prune-history` option?

**Comment by grandizzy** [comment]
> MAX_ON_DISK_HISTORY_LIMIT

the `MAX_ON_DISK_HISTORY_LIMIT` already purge the oldest state cached on disk, which should also fix the issue you see with`--prune-history`

**Comment by AnieeG** [comment]
@grandizzy we increased the available disc space, but we keep on getting error like this even without `--prune-history ` enabled - `BlockOutOfRangeError: block height is 11112 but requested was 11113` 

This is blocking us significantly. Would really appreciate any suggestion to resolve this -

command used - 

`anvil --chain-id 90000050 --block-time 1 --gas-limit 100000000 --code-size-limit 30000 --base-fee 1000000 --host 0.0.0.0 --port 8545 --accounts 20 --balance 2000000000000000000 --state /state/dump.json --state-interval 60 --transaction-block-keeper 500`

**Comment by grandizzy** [comment]
@AnieeG there's a PR in works to address this https://github.com/foundry-rs/foundry/pull/8412 will be avail soon
