### ISSUE TITLE
bug(`forge coverage`): bug while generating lcov report 

### ISSUE THREAD

**Issue by IWildSniperI** [foundry-rs/foundry#8395]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

0.2.0

### What command(s) is the bug in?

forge coverage --report lcov

### Operating System

Linux

### Describe the bug

![image](https://github.com/foundry-rs/foundry/assets/154032821/7c34f27e-76d0-4502-8dee-db5349116ac6)
after i run `forge coverage --report lcov`

with consideration that forge works normally

**Comment by grandizzy** [comment]
please provide complete output of `forge --version`, would be great if you could also point to source code to replicate such. thank you

**Comment by DaniPopes** [comment]
could also be stale artifacts, can you try `forge clean` and trying again?

**Comment by IWildSniperI** [comment]
@grandizzy so sorry for late responses
![image](https://github.com/foundry-rs/foundry/assets/154032821/6a953ca0-399a-4add-a881-e92fac23e3ac)
code with error
https://github.com/Cyfrin/2024-07-biconomy.git

i got same error on another Codes too that i don't remember

**Comment by IWildSniperI** [comment]
@DaniPopes will try and update here

**Comment by grandizzy** [comment]
works OK here, @IWildSniperI as @DaniPopes says looks to be UTF-8 handling / no locale installed on your OS, what OS you use?
(btw you have to `yarn coverage:forge` for that repo instead `forge coverage --report lcov`)

**Comment by IWildSniperI** [comment]
@grandizzy i have done what you said
Sorry for the confusion for not having that note in the issue body

Not doing --ir-minimum would already have brought stack too deep error

So i preferred to put the main command that had that issue (cause some repos didn't require --ir-minimum) and the problem kept arriving 


Iam using wsl on Windows

**Comment by IWildSniperI** [comment]
Only showed in the new version tho

1 or 2 months earlier i never got such a problem

Right now iam getting it often

**Comment by grandizzy** [comment]
what's the output for `cat /etc/default/locale` ?

**Comment by IWildSniperI** [comment]
![image](https://github.com/foundry-rs/foundry/assets/154032821/941d1f98-0065-42ab-b18f-9eeaec36c9a1)
@grandizzy

**Comment by grandizzy** [comment]
I think I have a theory but to confirm you would need to remove all these headers from sol files and retry :smile: 

```
// ──────────────────────────────────────────────────────────────────────────────
//     _   __    _  __
//    / | / /__ | |/ /_  _______
//   /  |/ / _ \|   / / / / ___/
//  / /|  /  __/   / /_/ (__  )
// /_/ |_/\___/_/|_\__,_/____/
//
// ──────────────────────────────────────────────────────────────────────────────
```

**Comment by IWildSniperI** [comment]
@grandizzy 😕really?

Just want to confirm that same problem came for one without headers

See codehawks (cyfrin account - temple gold rep)

**Comment by grandizzy** [comment]
hey @IWildSniperI were you able to test it without those headers? thanks

**Comment by IWildSniperI** [comment]
![image](https://github.com/user-attachments/assets/26759551-0c46-423c-afa6-b5556e3858d1)
@grandizzy

**Comment by grandizzy** [comment]
@IWildSniperI it still looks like there's the header, see the message above. Maybe try `forge clean`. What I want to see if WSL introduce bad chars like in https://github.com/microsoft/terminal/issues/386

**Comment by IWildSniperI** [comment]
did forge clean same problem

**Comment by grandizzy** [comment]
can you paste the output, is the header still printed / same error? either way I don't think there's much we can do here as it looks like wsl related issue...

**Comment by grandizzy** [comment]
also try updating foundryup there are some new things included and error line doesn't match anymore

**Comment by grandizzy** [comment]
@IWildSniperI going to close this for now, please apply suggested actions and report back if still an issue. thank you!
