### ISSUE TITLE
anvil: make max on disk history limit configurable

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#8399]
### Component

Anvil

### Describe the feature you would like

https://github.com/foundry-rs/foundry/blob/82ff8ee338818e6a6dc356e4c72ab72d31965375/crates/anvil/src/eth/backend/mem/storage.rs#L45-L46

we already have this for the memory limit

https://github.com/foundry-rs/foundry/blob/82ff8ee338818e6a6dc356e4c72ab72d31965375/crates/anvil/src/eth/backend/mem/storage.rs#L77-L78

https://github.com/foundry-rs/foundry/blob/82ff8ee338818e6a6dc356e4c72ab72d31965375/crates/anvil/src/cmd.rs#L160-L163

maybe those can even be combined, because I think the 
--prune_history is slightly confusing

So I think this should be fixed by setting 

https://github.com/foundry-rs/foundry/blob/82ff8ee338818e6a6dc356e4c72ab72d31965375/crates/anvil/src/eth/backend/mem/storage.rs#L78-L78

to `limit`

**Comment by qiweiii** [comment]
I would like to try take this

**Comment by mattsse** [comment]
assigned,

I fixed a link above that provided relevant context:

`max_on_disk_limit: MAX_ON_DISK_HISTORY_LIMIT`

**Comment by qiweiii** [comment]
after set it to `limit`, I am a bit confused by `--prune_history`, if user don't enable it, it uses default limit of 500, so both in memory and max disk cache length will be 500

but if user enabled it, the state will be memory only:

https://github.com/foundry-rs/foundry/blob/642f13f5b0cdac4c0b83b1fecade8393febe1c33/crates/anvil/src/eth/backend/mem/storage.rs#L84-L87

it overwrites the `max_on_disk_limit` set in `InMemoryBlockStates::new`, so setting

https://github.com/foundry-rs/foundry/blob/82ff8ee338818e6a6dc356e4c72ab72d31965375/crates/anvil/src/eth/backend/mem/storage.rs#L78-L78

to `limit` has no effect, then `max_on_disk_limit` is still not configurable, it's default 500 or 0, maybe need a separate config for this?

**Comment by mattsse** [comment]
ah you're right so restricting this with --prune-history doesn't have any effect actually

**Comment by grandizzy** [comment]
I think we should expose `--max-persisted-states` arg (or a better name) to control value of `InMemoryBlockStates.max_on_disk_limit` that would basically make `--prune-history` same as `--max-persisted-states=0` wdyt? @mattsse @qiweiii

**Comment by qiweiii** [comment]
I agree, it needs a new arg to set its value

**Comment by mattsse** [comment]
> I agree, it needs a new arg to set its value

this makes sense to me as well

**Comment by qiweiii** [comment]
@mattsse @grandizzy please check #8412 if this is what we want, it still feels a bit weired to have two config for in memory limit and on disk limit

**Comment by qiweiii** [comment]
@mattsse @grandizzy please check #8412 if this is what we want, it still feels a bit weired to have two config for in memory limit and on disk limit

**Comment by grandizzy** [comment]
> @mattsse @grandizzy please check #8412 if this is what we want, it still feels a bit weired to have two config for in memory limit and on disk limit

thanks, I think that's OK, if I correctly understand there is only one config exposed for disk limit, that is the newly added `--max-persisted-states`, the memory limit is not configurable but set to `const DEFAULT_HISTORY_LIMIT: usize = 500;` 
Maybe we can also drop the `--prune-history` and just add description that this can be accomplished by setting `--max-persisted-states=0`
@mattsse wdyt?
