### ISSUE TITLE
"forge init" command not working

### ISSUE THREAD

**Issue by arujjval** [foundry-rs/foundry#8405]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

7.1.0

### What command(s) is the bug in?

forge init 

### Operating System

Linux

### Describe the bug

I tried to set up a project using forge, but am getting it whenever I am running `forge init`. 

"Error: ’init’ is not a Forge command."

**Comment by zerosnacks** [comment]
Are you sure you installed Foundry? There is no version `7.1.0`

See the installation guide: https://book.getfoundry.sh/getting-started/installation#installation

You may need to re-run `curl -L https://foundry.paradigm.xyz | bash` to update the installer

**Comment by arujjval** [comment]
I have already installed the latest version of Foundry. The issue is not with Foundry as I am getting the same issue whenever I am using the 'init' command.

**Comment by zerosnacks** [comment]
Can you post the output of `forge --version` and `forge --help`?

**Comment by DaniPopes** [comment]
You have installed `forge` through apt or something like that, please remove it and install it following the guide in the book: <https://book.getfoundry.sh/getting-started/installation>
