### ISSUE TITLE
feat: add global Rayon thread pool (`--jobs`) to `GlobalOpts`

### ISSUE THREAD

**Issue by DaniPopes** [foundry-rs/foundry#8408]
### Component

Other (please describe)

### Describe the feature you would like

Add a struct to all CLI parsers that contains global clap options. Initially this can contain `--jobs` and has a helper method to spawn the global rayon pool with the configured amount of threads

### Additional context

See `ShellOpts` from https://github.com/foundry-rs/foundry/pull/6569/files#diff-93947eff97e7f1937ebcb82f40d17f32e45c67ff18c286e675ed9fa9d0b89994

**Comment by DaniPopes** [comment]
Should be possible to implement by generalizing `ShellOpts` after common-shell PRs are merged @zerosnacks

**Comment by zerosnacks** [comment]
Related: https://github.com/foundry-rs/foundry/issues/5479
