### ISSUE TITLE
Error: both gasPrice and (maxFeePerGas or maxPriorityFeePerGas) specified

### ISSUE THREAD

**Issue by Thegaram** [foundry-rs/foundry#8418]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

cast 0.2.0 (72e44fb 2024-07-11T00:19:12.649283000Z)

### What command(s) is the bug in?

cast send

### Operating System

macOS (Apple Silicon)

### Describe the bug

```
> RUST_LOG=trace cast send --rpc-url "https://rpc.scroll.io" "0x1b6Fb2c650B8F9719762a8AE5041cBB3629B1647" --gas-price 0.2gwei --ledger
...
2024-07-11T13:10:48.687021Z TRACE alloy_rpc_client::call: serialized request request={"method":"eth_estimateGas","params":[{"from":"0x1b6Fb2c650B8F9719762a8AE5041cBB3629B1647","to":"0x1b6Fb2c650B8F9719762a8AE5041cBB3629B1647","gasPrice":"0x5fccfe2","maxFeePerGas":"0xbebc200","input":"0x","data":"0x","chainId":"0x82750"}],"id":2,"jsonrpc":"2.0"}
...
Error: 
server returned an error response: error code -32000: both gasPrice and (maxFeePerGas or maxPriorityFeePerGas) specified
```

We [just marked](https://github.com/alloy-rs/chains/pull/73) Scroll as an EIP-1559 chain, is this error because Foundry has not adopted the latest `alloy-rs/chains` version yet?

**Comment by klkvr** [comment]
we've indeed not yet updated alloy-rs/chains, but this error shouldn't happen anyway

#8420 will resolve it, for now you can manually pass `--legacy` flag as a workaround
