### ISSUE TITLE
bug(cheatcodes): `vm.dumpState` address entries are not checksummed

### ISSUE THREAD

**Issue by JuanCoRo** [foundry-rs/foundry#8427]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ef62fdb 2024-07-12T00:19:17.932227488Z)

### What command(s) is the bug in?

forge script

### Operating System

Linux

### Describe the bug

The entry addresses in the JSON produced by `vm.dumpState` are not checksummed. This behavior seems inconsistent with the way `vm.stopAndReturnStateDiff` records addresses, since they are checksummed.

I don't know if this is intended, but I've added the bug label due to the inconsistent behavior.

**Comment by jenpaff** [comment]
resolved by https://github.com/foundry-rs/foundry/issues/8715
