### ISSUE TITLE
Yarn Deploy - The application panicked (crashed)

### ISSUE THREAD

**Issue by iafhurtado** [foundry-rs/foundry#8435]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 

### What command(s) is the bug in?

forge build, test

### Operating System

Windows

### Describe the bug

![image](https://github.com/user-attachments/assets/0c5b9d60-e4b4-4447-a974-be5a8a7e846b)
When trying to run yarn deploy or forge build or test I get this bug, so I'm reporting it here. Hope I can get any pointers, thanks!

**Comment by grandizzy** [comment]
please add entire forge version and make sure it is updated (foundryup) - it looks like you're using an older one

**Comment by zerosnacks** [comment]
Optimistically marking as resolved, all indicates an outdated version of Foundry

Feel free to re-open / leave a comment if this is not the case
