### ISSUE TITLE
Feat(anvil): Implement `GethDebugBuiltInTracerType::PreStateTracer` in `mined_geth_trace_transaction`  

### ISSUE THREAD

**Issue by 0xOsiris** [foundry-rs/foundry#8443]
### Component

Anvil

### Describe the feature you would like

I am trying to use `PreStateTracer` on a mined block of transactions from the anvil eth api backend's `debug_trace_transaction`, and I kept receiving an empty `NoopFrame` finally realizing it's unimplemented. It would be useful to have an implementation here for my use case.

I guess an additional question - Is there a simple way to get the pre/post state of a mined transaction from anvil currently? And if so how beyond re-executing the transactions through revm & passing the `ResultAndState`/db into `geth_prestate_traces`

### Additional context

Ref: https://github.com/foundry-rs/foundry/blob/6de15b0136ccb7dcac412d6b97bb3269ac2361c3/crates/anvil/src/eth/backend/mem/storage.rs#L481

Ref: https://github.com/foundry-rs/foundry/blob/6de15b0136ccb7dcac412d6b97bb3269ac2361c3/crates/anvil/src/eth/backend/mem/mod.rs#L1957

**Comment by grandizzy** [comment]
going to track callTracer / prestateTracer with https://github.com/foundry-rs/foundry/issues/5855 and close this one as dupe
