### ISSUE TITLE
bug: `forge bind --alloy` fails in specific contract

### ISSUE THREAD

**Issue by bluele** [foundry-rs/foundry#8444]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (5902a6f 2024-07-14T00:21:20.051403320Z)

### What command(s) is the bug in?

forge bind --alloy

### Operating System

Linux

### Describe the bug

Thank you for providing such an amazing tool.

The following error occurred when the command `forge bind --alloy` was executed in my project:
```
[⠊] Compiling...
[⠢] Compiling 1 files with Solc 0.8.24
[⠆] Solc 0.8.24 finished in 74.15ms
Compiler run successful!
Generating bindings for 2 contracts
The application panicked (crashed).
Message:  proc-macro-error API cannot be used outside of `entry_point` invocation, perhaps you forgot to annotate your #[proc_macro] function with `#[proc_macro_error]
Location: /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro-error-1.0.4/src/lib.rs:483

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: __libc_start_call_main<unknown>
      at ./csu/../sysdeps/nptl/libc_start_call_main.h:58
   2: __libc_start_main_impl<unknown>
      at ./csu/../csu/libc-start.c:392

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
[1]    558893 IOT instruction  forge bind --alloy
```

The relevant contract is here:
```solidity
// src/Sample.sol
pragma solidity ^0.8.12;

library Height {
    struct Data {
        uint64 revision_number;
        uint64 revision_height;
    }
}

contract Sample {
    struct Data {
        Height.Data height;
    }

    function f(Data calldata m) public {}
}
```

**Comment by zerosnacks** [comment]
cc @yash-atreya  + @DaniPopes

**Comment by yash-atreya** [comment]
This is due to the structs having the same name in the library and contract i.e `Data`, changing any one of those fixes this. 

```solidity
pragma solidity ^0.8.12;

library Height {
    struct Info { // Changed name from `Data` to `Info`
        uint64 revision_number;
        uint64 revision_height;
    }
}

contract Sample {
    struct Data {
        Height.Info height;
    }

    function f(Data calldata m) public {}
}
```

**Comment by programskillforverification** [comment]
```
--ethers
          Generate bindings for the `ethers` library, instead of `alloy` (default, deprecated)
```
This part in document make me confused. It means alloy is deprecated?

**Comment by zerosnacks** [comment]
> ```
> --ethers
>           Generate bindings for the `ethers` library, instead of `alloy` (default, deprecated)
> ```
> 
> [This part](https://book.getfoundry.sh/reference/cli/forge/bind) in document make me confused. It means alloy is deprecated?

`--ethers` is deprecated (but still default for the time), `--alloy` will become the default soon, replacing `ethers`

**Comment by bluele** [comment]
> This is due to the structs having the same name in the library and contract i.e Data, changing any one of those fixes this.

@yash-atreya  Thanks for the workaround suggestion. However, it isn't easy to apply it to my use-case.

**Comment by yash-atreya** [comment]
This is no longer an issue with https://github.com/alloy-rs/core/pull/694 included
