### ISSUE TITLE
`forge flatten` fails with cryptic error message

### ISSUE THREAD

**Issue by duncancmt** [foundry-rs/foundry#8450]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ea7817c 2024-07-16T00:20:45.570266422Z)

### What command(s) is the bug in?

forge flatten

### Operating System

Linux

### Describe the bug

I had previously opened #7554, but couldn't provide a repro because the contracts weren't released and I couldn't figure out something minimal. But https://github.com/0xProject/0x-settler is now public. If you try `forge flatten src/chains/Mainnet.sol`, you'll observe the error:

```
$ forge flatten src/chains/Mainnet.sol 
Error: 
Failed to flatten: missing field `body` at line 1 column 30987
```

Seems possibly related to #7069

**Comment by zerosnacks** [comment]
Hi @duncancmt thanks for the repro

Marking as duplicate in favor of now re-opened https://github.com/foundry-rs/foundry/issues/7554
