### ISSUE TITLE
bug(`forge script`): `--slow` flag is being skipped

### ISSUE THREAD

**Issue by vbhattaccmu** [foundry-rs/foundry#8452]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6de15b0 2024-07-15T00:24:50.814665100Z)

### What command(s) is the bug in?

forge script 

### Operating System

Windows

### Describe the bug

When I execute a smart contract using the following command
```
 forge script Deploy.s.sol   --rpc-url <RPC_URL> --private-key <PRIVATE_KEY> --broadcast  --slow
```
The smart contract is sending internal transactions in random order of nonce. This scenario is reproducible with a lot of OpenZeppelin contracts. Seems like the command is skipping the --slow command. Would appreciate if I could get help/information on this.

**Comment by zerosnacks** [comment]
Marking this ticket as `can't repro`, please re-open or leave a comment  with a minimal production or additional information to help narrow down this issue.
