### ISSUE TITLE
bug: context not switched with `vm.selectFork` in invariance test

### ISSUE THREAD

**Issue by wcgcyx** [foundry-rs/foundry#8457]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (ea7817c 2024-07-16T00:18:48.894654000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

Hi, we are having issues with our current invariance testing that tests our [bridge](https://github.com/immutable/zkevm-bridge-contracts) between two chains.

To capture some invariants between two chains, we created two forks to simulate two chains and we used a mock messenger that uses `vm.selectFork` to switch between two forks and send messages between them.

This setup has been working till `5ac78a9cd4b94dc53d1fe5e0f42372b28b5a7559` but has been broken ever since.

I've created a small example to recreate this issue [here](https://github.com/immutable/zkevm-bridge-contracts/tree/NOJIRA_FIX_TEST2/test/invariant).

To recreate this issue with the example:
```
# Clone repo
git clone https://github.com/immutable/zkevm-bridge-contracts.git
cd zkevm-bridge-contracts
git checkout NOJIRA_FIX_TEST2
# Install Dependencies
yarn install
forge install
# Spin up the local test chain
yarn local:testchain
# Run successful test with foundry version 5ac78a9cd4b94dc53d1fe5e0f42372b28b5a7559
foundryup --version nightly-5ac78a9cd4b94dc53d1fe5e0f42372b28b5a7559
forge test --match-path "test/invariant/**" -vvvvv
# Run the same test with later release. This will fail
foundryup --version nightly-7bef9caccfe62761225be66e84bea2810e656c96
forge test --match-path "test/invariant/**" -vvvvv
```

The [MockMessenger](https://github.com/immutable/zkevm-bridge-contracts/blob/NOJIRA_FIX_TEST2/test/invariant/MockMessenger.sol) contract is deployed on both root chain and child chain at the same address.
The chain switch happens [here](https://github.com/immutable/zkevm-bridge-contracts/blob/4189f5e21ae6f5d553b329f46573be12f5f96b2d/test/invariant/MockMessenger.sol#L29), which was triggering the context and contract state to switch to the MockMessenger on the other chain in `nightly-5ac78a9cd4b94dc53d1fe5e0f42372b28b5a7559` but is performing differently now.

I'm not sure if there is any issue with this setup but added the bug label as the behavior has changed.

**Comment by grandizzy** [comment]
hey @wcgcyx indeed, the behavior was changed in https://github.com/foundry-rs/foundry/pull/8041 The reason for is that the contract managing forks (in your case `MockMessenger` as well) should have their state persisted across forks, otherwise tests could crash or become inconsistent. In order to accommodate your code to new behavior you should have forks managed from outside, please see below

<details><summary>MockMessenger.sol</summary>

```Solidity
// SPDX-License-Identifier: Apache 2.0
pragma solidity 0.8.19;

contract MockMessenger {
    uint256 public chainId;

    constructor(uint256 _chainId) {
        chainId = _chainId;
    }

    function onMessageReceive(bytes calldata data) public {}
}
```
</details>

<details><summary>InvariantBridge.t.sol</summary>

```Solidity
// SPDX-License-Identifier: Apache 2.0
pragma solidity 0.8.19;

import {Test} from "forge-std/Test.sol";
import {MockMessenger} from "./MockMessenger.sol";
import {MockHandler} from "./MockHandler.sol";
import "forge-std/console.sol";

contract InvariantBridge is Test {
    string public constant CHAIN_URL = "http://127.0.0.1:8500";
    address public constant ADMIN = address(0x111);

    uint256 childId;
    uint256 rootId;
    MockMessenger childMessenger;
    MockMessenger rootMessenger;
    MockHandler rootHandler;

    function setUp() public {
        // Create two forks, child chain and root chain
        childId = vm.createFork(CHAIN_URL);
        rootId = vm.createFork(CHAIN_URL);

        // Deploy messenger on child chain.
        vm.selectFork(childId);
        vm.startPrank(ADMIN);
        childMessenger = new MockMessenger(rootId);
        vm.stopPrank();

        // Deploy messenger on root chain.
        vm.selectFork(rootId);
        vm.startPrank(ADMIN);
        rootMessenger = new MockMessenger(childId);
        vm.stopPrank();

        // Send a message from root chain to child chain
        this.sendMessage(rootMessenger, "0x1234");

        // Set target contract
        rootHandler = new MockHandler();
        bytes4[] memory rootSelectors = new bytes4[](1);
        rootSelectors[0] = rootHandler.handler.selector;
        targetSelector(FuzzSelector({addr: address(rootHandler), selectors: rootSelectors}));
        targetContract(address(rootHandler));
    }

    /// forge-config: default.invariant.runs = 1
    /// forge-config: default.invariant.depth = 5
    /// forge-config: default.invariant.fail-on-revert = true
    function invariant_test() external {}

    function sendMessage(MockMessenger messenger, bytes calldata payload) external {
        // Get current chain.
        uint256 currentChainId = vm.activeFork();
        console.log("The current chain is", currentChainId, "messenger chain id is", messenger.chainId());
        if (currentChainId == messenger.chainId()) {
            revert("This should never happen");
        }

        // Switch to the other chain.
        vm.selectFork(messenger.chainId());

        currentChainId = vm.activeFork();
        console.log("The current chain is", currentChainId, "messenger chain id is", messenger.chainId());
        if (currentChainId == messenger.chainId()) {
            revert("This should never happen");
        }

        messenger.onMessageReceive(payload);

        // Switch back to the original chain.
        vm.selectFork(currentChainId);
    }
}
```
</details>

```bash
forge test --match-path "test/invariant/**"

Ran 1 test for test/invariant/InvariantBridge.t.sol:InvariantBridge
[PASS] invariant_test() (runs: 1, calls: 5, reverts: 0)
Suite result: ok. 1 passed; 0 failed; 0 skipped; finished in 17.19ms (5.59ms CPU time)
```

Please lmk if this makes sense, thank you

**Comment by wcgcyx** [comment]
Thank you for your confirmation @grandizzy.

>  ...otherwise tests could crash or become inconsistent...

Yes, we faced some issues with this setup previously but managed to mitigate by having the exact same messenger contract deployed to the same address on two forks like a symmetric contract, so switching within this contract is fine since there is a same contract on the other chain with only different state. 

 > In order to accommodate your code to new behavior you should have forks managed from outside (ideally from handler)

Yea, I can see what you mean now. I will try to see if it is possible to refactor our [actual existing tests](https://github.com/immutable/zkevm-bridge-contracts/tree/main/test/invariant) with this approach. I think there might be just one issue: we also test the balances of the messenger contract ([MockAdaptor](https://github.com/immutable/zkevm-bridge-contracts/blob/main/test/invariant/MockAdaptor.sol)) on both forks throughout the tests so having only one state available may cause some issues 🤔 

Thank you 🙏 , I will try to do some refactoring to see if I can accommodate this change.

**Comment by grandizzy** [comment]
>  I think there might be just one issue: we also test the balances of the messenger contract ([MockAdaptor](https://github.com/immutable/zkevm-bridge-contracts/blob/main/test/invariant/MockAdaptor.sol)) on both forks throughout the tests so having only one state available may cause some issues 🤔
> 
I don't think this should be an issue, if you move the fork management out of `MockAdaptor` then each adaptor will have their own state / own balance. But yeah, pls give it a try and get back if you hit any problem. thank you!

**Comment by wcgcyx** [comment]
Thanks @grandizzy , we managed to accommodate the change by moving fork switching out of the contract.
