### ISSUE TITLE
add a flag to dump the request and response involved

### ISSUE THREAD

**Issue by zhiqiangxu** [foundry-rs/foundry#8464]
### Component

Cast

### Describe the feature you would like

Yesterday I met a problem like this:

```bash
% cast send 0x79552BFA8Ed6d10Dc2DE7A48A9aaf2848848131E "attack()"   --private-key=$PRIVATE_KEY -r $RPC_URL
Error: 
server returned an error response: error code 1: decoding params: strconv.ParseUint: parsing "": invalid syntax
```

It's totally a mystery what's the actual problem, it may help if there's a flag to dump the request and response.

(The problem is gone after I run `foundryup`)

**Comment by zerosnacks** [comment]
Thanks for your suggestion, to get better introspection into what Foundry is doing (including request / response)  you can prefix your command by `RUST_LOG=trace`

Marking as `not planned`
