### ISSUE TITLE
feat(`forge script`): set both tx input fields (`input` and `data`)

### ISSUE THREAD

**Issue by ChiTimesChi** [foundry-rs/foundry#8469]
### Component

Forge

### Describe the feature you would like

See #8373 for more context. As of now using forge script with tools like Truffle Dashboard (or its forks) is not possible, as it expects `data` field to be populated rather than `input`:

https://github.com/trufflesuite/truffle/blob/5b5312dbd5ffe2d5ec575e078ff09d98eb1b45c2/packages/dashboard/src/utils/dash.ts#L95

I would also appreciate any recommendations for alternative tools to connect wallets unsupported by forge.

**Comment by zerosnacks** [comment]
Marked as `good first issue`

Related: https://github.com/foundry-rs/foundry/blob/2544793db0896f8f34e661195f8ad90a76dfc279/crates/cast/bin/tx.rs#L237-L239

**Comment by programskillforverification** [comment]
Could you assign it to me? I want to try.
