### ISSUE TITLE
Failed verification of external libs deployed using create2

### ISSUE THREAD

**Issue by skhomuti** [foundry-rs/foundry#8473]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (af97b2c 2024-07-18T00:22:15.301937000Z)

### What command(s) is the bug in?

ETHERSCAN_API_KEY={} forge script script/Counter.s.sol:CounterScript --rpc-url={} --private-key={} --broadcast --verify

### Operating System

macOS (Apple Silicon)

### Describe the bug

https://github.com/skhomuti/foundry-create2-verify repo with slightly modified Counter.sol to reproduce the issue, and also broadcast log on holesky

Foundry cannot verify external library `Incrementor` on Holesky Etherscan
The error is the following:
```
Details: `Fail - Unable to verify. Compiled contract deployment bytecode does NOT match the transaction deployment bytecode.`
Error during verification: Checking verification result failed: Contract failed to verify.
```

Seems to be caused by #7711. On prev foundry versions (e.g. 844caa8 ref) such contracts are verified successfully

**Comment by klkvr** [comment]
Likely similar to https://github.com/foundry-rs/foundry/issues/6023, can reproduce on Holesky, can't on Sepolia. Seems like etherescan has some issues with verifying contracts created through opcodes on holesky

**Comment by skhomuti** [comment]
@klkvr thanks for linking this, manual submitting works well for me
