### ISSUE TITLE
https://github.com/ethereum/go-ethereum/issues/22041

### ISSUE THREAD

**Issue by itsdevbear** [foundry-rs/foundry#848]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (2ddc47e 2022-03-02T00:34:52.877001+00:00)

### What command(s) is the bug in?

forge build

### Operating System

darwin/arm64

### Describe the bug

Ah ser Georgio, I have come again with more geth abi.ABI issues.
```
panic: json: cannot unmarshal array into Go struct field jsonCompiledContract.ABI of type string

goroutine 1 [running]:
github.com/berachain/core/solidity.init.0()
	/Users/dev/bc/core/solidity/contracts.go:52 +0xb4
panic: json: cannot unmarshal array into Go struct field jsonCompiledContract.ABI of type string
```

Maybe related to: https://github.com/ethereum/go-ethereum/issues/22041, it looks as if geth expects a string, could be out to lunch but thought I would take a look.

Also the new "bytecode" struct, and removal of "bin" from the output definitely botches things, if trying to make the abi output of forge compatible with geth data structures.

**Comment by onbjerg** [comment]
@itsdevbear Hey! The artifacts have changed somewhat, but maybe you can use `--extra-output` and `--extra-output-files` to get your desired result? See here https://book.getfoundry.sh/reference/forge/forge-build.html

**Comment by onbjerg** [comment]
Closed due to inactivity - feel free to ping if you need a reopen :)
