### ISSUE TITLE
feat(`forge doc`): add `--watch` flag

### ISSUE THREAD

**Issue by Metaxona** [foundry-rs/foundry#8484]
### Component

Forge

### Describe the feature you would like

allow --watch flag on forge doc to allow live updates on documentation changes

it would be good to have a live updates on doc changes when I update my contract instead of doing a build and serve every time

**Comment by francesco-gaglione** [comment]
Working on this, I will publish a draft pull request to propose a solution idea to be taken as a basis for implementing this functionality.
