### ISSUE TITLE
feat(`forge doc`): include @custom NatSpec

### ISSUE THREAD

**Issue by Metaxona** [foundry-rs/foundry#8488]
### Component

Forge

### Describe the feature you would like

it's weird to have author and all other natspec @ without including the `@custom` one

i think it would be good to have it on the same level as `@author` or 1 level below 

this should be included in the generated docs

**Comment by leovct** [comment]
Hi @zerosnacks, I'd like to work on this issue :)

**Comment by zerosnacks** [comment]
Thanks @leovct!
