### ISSUE TITLE
bug(`cast send`): failed to get resolver from the ENS registry: buffer overrun while deserializing

### ISSUE THREAD

**Issue by krishhh16** [foundry-rs/foundry#8491]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

0.2.0

### What command(s) is the bug in?

cast send

### Operating System

Linux

### Describe the bug

I was testing a smart contract in forgery, I tried running this command as cast send $PRIVATE_KEY "sendNumber(uint256)" 1

And I'm continuously getting this error

**Comment by zerosnacks** [comment]
Hi @krishhh16, would you mind running `foundryup` and re-running your example?

**Comment by krishhh16** [comment]
> Hi @krishhh16, would you mind running `foundryup` and re-running your example?

Pretty sure I did that. But still no luck, I've been on the latest version the entire time

**Comment by block0xhash** [comment]
> ### Component
> Cast
> 
> ### Have you ensured that all of these are up to date?
> * [x]  Foundry
> * [x]  Foundryup
> 
> ### What version of Foundry are you on?
> 0.2.0
> 
> ### What command(s) is the bug in?
> cast send
> 
> ### Operating System
> Linux
> 
> ### Describe the bug
> I was testing a smart contract in forgery, I tried running this command as cast send $PRIVATE_KEY "sendNumber(uint256)" 1
> 
> And I'm continuously getting this error

**Comment by block0xhash** [comment]
You get this  error when your command is wrong

if this is your full cast command then thats the problem

` cast send $PRIVATE_KEY "sendNumber(uint256)" 1` 

you need to pass the `contract  `address and and the `--rpc-url`

**Comment by zerosnacks** [comment]
Tentatively marking as resolved, feel free to re-open with additional details if you are still experiencing issues with this.

What @block0xhash wrote, it could be that you are not passing all required arguments and it attempts to resolve an argument as an invalid ENS name. Order of arguments does matter.
