### ISSUE TITLE
EvmError: InvalidOperandOOG - ERROR on console.logBytes32

### ISSUE THREAD

**Issue by JayeshShukla** [foundry-rs/foundry#8492]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (fe2acca 2024-07-22T00:24:23.688640000Z)

### What command(s) is the bug in?

forge test --mt "testName"

### Operating System

macOS (Intel)

### Describe the bug

```solidity
function consoleAfterAssignment() public view 
    {
        bytes32 test;
        assembly {
            mstore(0x40, 0x12345678) // <- error visible if 4 bytes or +4 bytes only & memory space has to be 0x40
        }
        console.logBytes32(test);
    }
```
    
In the above code, when assigned any value **greater than or equal to** `4bytes` i.e (0x12345678 or greater in bytes as compared to it)  to **0x40 free memory pointer space &** then console.logBytes32 always gives the below revert message.
    
  I checked it in remix as well where it says out of gas !
  
  
![image](https://github.com/user-attachments/assets/acd23b43-5893-4928-a4a6-acb5184d721a)

**Comment by zerosnacks** [comment]
This is simply an invalid operation as you are overwriting the free memory pointer expected to cause problems with later operations, unrelated to the Foundry cheatcode

`OOG` = out of gas
