### ISSUE TITLE
bug(`anvil`): `--fork-url` and `--load-state` are incompatible 

### ISSUE THREAD

**Issue by ericbrown99** [foundry-rs/foundry#8493]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (fe2acca 2024-07-22T00:23:01.187259000Z)

### What command(s) is the bug in?

anvil  --fork-url https://mainnet.infura.io/v3/$WEB3_INFURA_PROJECT_ID  --chain-id 31337 --dump-state state.json --load-state state.json

### Operating System

None

### Describe the bug

When forking from mainnet and attempting to load previous state, the previous state isn't loaded successfully. From the command above you can see that `anvil` is instructed to dump the state which it does successfully and the previous state is available when the new instance of `anvil` begins. But seemingly due to the use of `--fork-url` the previous state isn't properly loaded

**Comment by jenpaff** [comment]
`--fork-url` and `--load-state` are not supposed to work together, will add a CLI flag to make sure conflicting flags are communicated to user

**Comment by ericbrown99** [comment]
okay, thanks for the update. To confirm, this means its not possible to use a fork's data (e.g. DEX contracts with liquidity) while also loading in data from recent user sessions to simulate the over time use of our smart contracts locally?
