### ISSUE TITLE
bug(anvil): `anvil_loadState` fails to decode state dump after upgrading to new foundry version

### ISSUE THREAD

**Issue by dbeal-eth** [foundry-rs/foundry#8501]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (62cdea8 2024-07-23T00:19:34.618350138Z)

### What command(s) is the bug in?

anvil

### Operating System

Linux

### Describe the bug

when a foundry version state dump (with `anvil_dumpState`) older than the merging of [this PR](https://github.com/foundry-rs/foundry/pull/8445) is loaded into a anvil node newer than that PR (using `anvil_loadState`), anvil fails with error `{ code: -32602, message: 'Failed to decode state dump' }`

most likely the encoded JSON object of the `BTreeMap` differs from that of the previous `HashMap`.

Since the intention of `dumpState` is for the state to be stored so that it could be loaded later, it does not seem right that a newer version of foundry would no longer be able to load this slightly older state dump.

**Comment by 0xMithrandir** [comment]
This issue still persists, I tried using the latest foundry build today and still have issues where the anvil_loadState is failing.

**Comment by 0xMithrandir** [comment]
I'm using foundry from this version for now since there is no state issues there
 `foundryup -C 6de15b0136ccb7dcac412d6b97bb3269ac2361c`

**Comment by noahlitvin** [comment]
@DaniPopes Hi! Is there any update on the plan here? This is becoming a growing problem for us on [Cannon](https://github.com/usecannon/cannon) as we're not locked to a particular version of Foundry, so there's random incompatibility across packages.

At minimum, it would be good to know if you intent to revert the change that caused the regression, or if we should plan otherwise. Thank you!

**Comment by dbeal-eth** [comment]
since we haven't heard any updates over the last month regarding this issue, I am wondering if I produced a PR which resolves this issue by reverting to the old storage structure, and also sorts the contents of the state dump keys, would that PR be good to merge?

(fyi i am the person who first added `anvil_dumpState` and `anvil_loadState` commands 2 years ago so I am pretty familiar with this part of the codebase https://github.com/foundry-rs/foundry/pull/2256 )
