### ISSUE TITLE
abstract contract's already initialized immutable variable can be re initialized by inheriting it.

### ISSUE THREAD

**Issue by JayeshShukla** [foundry-rs/foundry#8504]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (fe2acca 2024-07-22T00:24:23.688640000Z)

### What command(s) is the bug in?

forge test --mt "testName"

### Operating System

macOS (Apple Silicon)

### Describe the bug

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

abstract contract Module {
    uint256 public immutable a;

    constructor() {
        a = 100;
    }
}

contract Counter is Module {
    constructor() {
        a = 200;
    }

    function getData() public returns (uint256) {
        return a; // reurns a = 200
    }
}
```

where as in Remix this issue gives a warning during compile time, same is missing in case of foundry also it re-initialized

**Comment by zerosnacks** [comment]
Solidity thought it was a good idea to relax restrictions on immutables in the constructor now allowing re-initialization by inherited contracts.

See: https://github.com/ethereum/solidity/blob/develop/Changelog.md#0821-2023-07-19

Unrelated to Foundry
