### ISSUE TITLE
bug(`forge build`): `Solc` download timeout window is too small for slow internet speeds

### ISSUE THREAD

**Issue by pi0neerpat** [foundry-rs/foundry#8507]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (62cdea8 2024-07-23T00:18:49.756549000Z)

### What command(s) is the bug in?

forge build

### Operating System

macOS (Apple Silicon)

### Describe the bug

Related to #6665

Downloading the solc compiler is timing out too quickly. This makes it impossible to use forge with slow internet speeds.

```
$ forge build -- --vvvv
Error: 
error decoding response body

Context:
- Error #0: request or response body error
- Error #1: operation timed out
```

### Cause

- The solc binary size for mac has increased from 37MB to 79MB since v0.8.23.
- The timeout for forge to download the binary is less than 3 minutes.
- On a slow internet connection, there is not enough time for the download to complete before timing out.

### Solution

- Increase the timeout limit for downloads to 10 minutes

### Temporary Fix

To resolve this on mac, you must manually add the solc binary:

1. Download the binary from the release page https://github.com/ethereum/solidity/releases
2. Rename the binary and place in your `svm` folder eg. `/Users/<username>/Library/Application Support/svm/0.8.26/solc-0.8.26`
4. Enable access with `chmod +x "/Users/<username>/Library/Application Support/svm/0.8.26/solc-0.8.26"`

**Comment by zerosnacks** [comment]
Related: https://github.com/alloy-rs/svm-rs/blob/de5bd77c5af7b5188dfe0d00675cef72dbdbd145/crates/svm-rs/src/install.rs#L18-L19

Looks like the timeout window is currently set to 2 minutes. Increasing this to 10 minutes seems reasonable to me. Only downside is that flaky tests could blow up more easily.
