### ISSUE TITLE
bug(`anvil`): `eth_getCode` fails with  `BlockOutOfRangeError` when Anvil started with `--load-state`

### ISSUE THREAD

**Issue by fmoura** [foundry-rs/foundry#8518]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

nightly-e90348416c3a831ab75bb43f6fa5f0a0be4106c4

### Operating System

Linux

### Describe the bug

1- Start Anvil with `--dump-state`
2- Deploy a contract
3- Stop Anvil
4- Restart Anvil with `--load-state`
5- Query the contract with `eth_getCode` , contract address and 'latest' as the block. It returns ok
6- Query the contract with `eth_getCode`, contract address and a block number mined before `load state`
get an error like the one bellow :
```
{"jsonrpc":"2.0","id":1,"error":{"code":-32602,"message":"BlockOutOfRangeError: block height is 253 but requested was 16"}}
```
But If i try `cast block 16` it returns a valid block.

**Comment by yash-atreya** [comment]
This error occurs because`load_state` populates the db but not the in-memory historical state (backend.states) in the backend. `backend.states` is only populated with the most recent block or `best_block`.

**Comment by yash-atreya** [comment]
@fmoura fix has been merged and should be released in the next nightly. 

You can now preserve the historical states by using the `--preserve-historical-states` flag along with `--dump-state`
