### ISSUE TITLE
bug(`forge flatten`): flattening smart contract fails for `@dev` string: `expected struct StructuredDocumentation`

### ISSUE THREAD

**Issue by crystalin** [foundry-rs/foundry#8520]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (0ad127a 2024-07-25T00:17:47.070402649Z)

### What command(s) is the bug in?

forge flatten -o out.sol 0x76BE3b62873462d2142405439777e971754E8E77eth-RaribleUserToken.sol

### Operating System

None

### Describe the bug

Trying to flatten the contract at 0x76BE3b62873462d2142405439777e971754E8E77, it raises the error:
Failed to flatten: invalid type: string "@dev Multiplies two numbers, throws on overflow.", expected struct StructuredDocumentation at line 1 column 19512

**Comment by zerosnacks** [comment]
Related code at https://etherscan.io/address/0x76BE3b62873462d2142405439777e971754E8E77#code:

```solidity
/**
 * @title SafeMath
 * @dev Math operations with safety checks that throw on error
 */
library SafeMath {

    /**
    * @dev Multiplies two numbers, throws on overflow.
    */
    function mul(uint256 a, uint256 b) internal pure returns (uint256 c) {
      // ...
    }
}
```

cc @klkvr

**Comment by klkvr** [comment]
seems to be caused by differences in AST for solc < 0.6.

for mentioned contract documentation is kept as string instead of an object:
```json
"documentation": "@title SafeMath\n@dev Math operations with safety checks that throw on error",
```

```json
"documentation": {
    "id": 3,
    "nodeType": "StructuredDocumentation",
    "src": "60:89:0",
    "text": " @title SafeMath\n @dev Math operations with safety checks that throw on error"
},
```

fixing this would require change in our AST bindings, though not sure if we want to work on this compatibility as supporting all AST formats for all versions would end up pretty messy

**Comment by grandizzy** [comment]
just for the records of issue reported in tg, another sample is 

https://github.com/Synthetixio/synthetix/blob/develop/contracts/StakingRewards.sol

```
forge flatten contracts/StakingRewards.sol
Error: 
Failed to flatten: invalid type: string "@notice Change the paused state of the contract\n@dev Only the contract owner may call this.", expected struct StructuredDocumentation at line 1 column 13262
```

**Comment by mattsse** [comment]
perhaps we can do an enum for this with string as the fallback?

**Comment by crystalin** [comment]
Awesome, thank you :)
