### ISSUE TITLE
feat: CLIs should accept `_` in digits passed to it

### ISSUE THREAD

**Issue by sambacha** [foundry-rs/foundry#8521]
### Component

Forge, Cast, Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (0ad127a 2024-07-25T00:18:26.746279000Z)

### What command(s) is the bug in?

 forge test -f http://127.0.0.1:8545 --isolate --fuzz-runs 4_294_967_290

### Operating System

macOS (Apple Silicon)

### Describe the bug

```bash
 forge test -f http://127.0.0.1:8545 --isolate --fuzz-runs 4_294_967_290
```
```console
error: invalid value '4_294_967_290' for '--fuzz-runs <RUNS>': invalid digit found in string
```

```bash
$ forge test -f http://127.0.0.1:8545 --isolate --fuzz-runs 4294967290
```
This works. 

Underscore is allowed in `foundry.toml`, so it would make sense I would think that it would similarly be accepted as command line argument.

**Comment by DaniPopes** [comment]
We would have to go out of our way to annotate every single integer command line option with a custom parser since the default one does not support this. I don't think this is worth the effort.
