### ISSUE TITLE
Jemalloc breaks linux aarch64 binary nightly release

### ISSUE THREAD

**Issue by protolambda** [foundry-rs/foundry#8526]
### Component

Foundryup

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

broken binary releases (nightly Jun 25)

### What command(s) is the bug in?

foundryup

### Operating System

Linux

### Describe the bug

The nightly CLI tools, when pulled as binaries, are all broken when installed via foundryup on aarch64 linux (Fedora asahi linux on Air m2 in my case). This used to work a few months ago.

```
$ foundryup
...
foundryup: installing foundry (version nightly, tag nightly)
foundryup: downloading latest forge, cast, anvil, and chisel
############################################################################################################################### 100.0%
foundryup: downloading manpages
############################################################################################################################### 100.0%
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
memory allocation of 56 bytes failed
foundryup: command failed: /home/proto/.foundry/bin/forge --version
foundryup: installed -
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
memory allocation of 56 bytes failed
foundryup: command failed: /home/proto/.foundry/bin/cast --version
foundryup: installed -
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
memory allocation of 56 bytes failed
foundryup: command failed: /home/proto/.foundry/bin/anvil --version
foundryup: installed -
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
memory allocation of 56 bytes failed
foundryup: command failed: /home/proto/.foundry/bin/chisel --version
foundryup: installed -
foundryup: done!
```

Resulting in a bad install:
```
proto@air projects $ forge -h
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
memory allocation of 56 bytes failed
Aborted (core dumped)
```

Linux on aarch64 uses a 16K aligned page size; this applies to Asahi linux, but also Raspberry Pi. 

I also tried running foundryup, with a specific commit, to force building from source:
```
foundryup -C 9444c6217
```
And it worked! The locally compiled binaries run fine. (rust 1.80.0)

I am not sure when jemalloc broke binary-release things, it's been quite a while since I last updated.

I searched around, and Jemalloc has broken foundry on aarch64 linux before:

https://github.com/foundry-rs/foundry/issues/5832

Someone [commented](https://github.com/foundry-rs/foundry/issues/5832#issuecomment-2198581179) in this a few weeks ago, after it was already closed, that they have the issue also, and linked a build-process fix of another rust project. It sets some env-var, and jemalloc then adjusts the page-size. But apparently foundry-up builds from source work, at least via foundryup, so I am not sure if the env-var fix is really necessary.

The CI build process does appear to explicitly not enable the "jemalloc" feature, saying it's "not compatible". See: https://github.com/foundry-rs/foundry/blob/9444c6217a258cb4fd6ac38597ea282d6642ec7c/.github/workflows/release.yml#L140

This must have broken, as jemalloc is definitely being used in the binaries pulled by foundryup that I am running.
I'm not sure what is happening with the feature-flag there.
But adding the env-var for page-size, as suggested in the comment to the `Linux ARM setup` step in CI might help.

**Comment by Tritlo** [comment]
I'm running into this again, both with `forge` and `anvil`.
