### ISSUE TITLE
bug(`cast`): fails in encoding of bytes if non-hexadecimal values passed

### ISSUE THREAD

**Issue by Amit0617** [foundry-rs/foundry#8536]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (62cdea8 2024-07-23T00:19:34.618350138Z)

### What command(s) is the bug in?

cast calldata

### Operating System

Linux

### Describe the bug

Try following command
```bash
cast calldata "sam(bytes)" dave
```
It fails parsing argument value because of `v`.
Technically, for non-hexadecimal values, it should be UTF8-encoding (ASCII values) padded right to 32 bytes. Look at third example https://docs.soliditylang.org/en/latest/abi-spec.html#examples

**Comment by zerosnacks** [comment]
Hi @Amit0617 thanks for flagging this

Cast supports: `cast calldata "sam(string)" dave`, `dave` is not a valid bytes32

Marking as `resolved`

**Comment by Amit0617** [comment]
I was unsure about that, but probably that example in documentation is wrong.
