### ISSUE TITLE
Unable to set a specific solc compiler version

### ISSUE THREAD

**Issue by zeroaddresss** [foundry-rs/foundry#8541]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (551bcb5 2024-02-28T07:40:42.782478000Z)

### What command(s) is the bug in?

forge build / forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

Despite declaring a specific solc version in my `foundry.toml`, when I run `forge build` or `forge test` it will return an error saying that there is no solc version matching the version I have declared (0.8.26).
My `foundry.toml` looks like this:
```toml
[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
auto_detect_solc = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
```
And the error I receive after `forge build` is the following:
```
[⠃] Compiling...2024-07-27T11:30:28.131852Z ERROR foundry_compilers::resolver: failed to resolve versions                                                                                       │
│[⠊] Compiling...                                                                                                                                                                                │
│Error:                                                                                                                                                                                          │
│Encountered invalid solc version in src/Example.sol: No solc version exists that matches the version requirement: =0.8.26                                                                    │
```

**Comment by zeroaddresss** [comment]
In addition to the above, I've also tried to run the command passing the `--use` flag to enforce solc version, but it won't solve the issue.
`forge build --use solc:0.8.26`
-> `Error: Unknown version provided`

**Comment by mattsse** [comment]
> forge 0.2.0 (551bcb5 2024-02-28T07:40:42.782478000Z)

could you please update your forge version? 0.8.26 didn't exist then

**Comment by zeroaddresss** [comment]
> > forge 0.2.0 (551bcb5 2024-02-28T07:40:42.782478000Z)
> 
> could you please update your forge version? 0.8.26 didn't exist then

my bad, I was doing `forge update` instead of `foundryup`
by the way, another compile error pops up now, which is related to the latest Solidity version (0.8.26):
```
[⠊] Compiling...                                                                                                                                                                                │
  33     │[⠰] Compiling 26 files with Solc 0.8.26                                                                                                                                                         │
 34 cont│[⠔] Solc 0.8.26 finished in 1.36s                                                                                                                                                               │ but no r
  35     │Error:                                                                                                                                                                                          │
  36     │Compiler run failed:                                                                                                                                                                            │
  37     │Error: Unimplemented feature (/solidity/libsolidity/codegen/ExpressionCompiler.cpp:1266):Require with a cu                                                                                      │
  38     │stom error is only available using the via-ir pipeline.                                                                                                                                         │
  39     │UnimplementedFeatureError: Require with a custom error is only available using the via-ir pipeline.
  ```
  This has to do with the newly implemented syntax for require statements, namely:
  ```sol
  require(sent, TransferError())
  ```

**Comment by grandizzy** [comment]
pls check if you're using `via-ir` pipeline, require with custom err is available only for such https://soliditylang.org/blog/2024/05/21/solidity-0.8.26-release-announcement/

**Comment by zeroaddresss** [comment]
Solved by updating foundry to latest version and adding the `--via-ir` flag to the `forge test` command:
```
forge test --mt testBlaBlaBla -vvv --via-ir
