### ISSUE TITLE
forge(build): `Compiler run successful with warnings:` but no warnings log

### ISSUE THREAD

**Issue by mds1** [foundry-rs/foundry#8548]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (bdd1137 2024-07-28T00:21:06.817030000Z)

### What command(s) is the bug in?

forge build

### Operating System

None

### Describe the bug

I haven't been able to create a minimal reproduction of the issue yet, but to reproduce:
1. Clone https://github.com/ethereum-optimism/optimism
2. Checkout the `ci/solc-check` branch (https://github.com/ethereum-optimism/optimism/pull/11231)
3. `cd packages/contracts-bedrock && forge install`
4. Run `forge build --force`

The output says `Compiler run successful with warnings:` but not warnings are logged. 
```
$ forge build --force
[⠒] Compiling...
[⠢] Compiling 394 files with Solc 0.8.15
[⠆] Compiling 138 files with Solc 0.8.25
[⠊] Compiling 16 files with Solc 0.8.19
[⠒] Solc 0.8.19 finished in 1.66s
[⠃] Solc 0.8.25 finished in 11.13s
[⠒] Solc 0.8.15 finished in 221.01s
Compiler run successful with warnings:
```

We thought this may be `ignored_error_codes` usage, but in my simpler repro case, adding an entry to `ignored_error_codes` was working as expected and resulted in `Compiler run successful!`

We are trying to use `--deny-warnings` in CI, but can't because this bug causes failure even though no warnings are logged:

```
$ forge build --force --deny-warnings
[⠒] Compiling...
[⠢] Compiling 138 files with Solc 0.8.25
[⠆] Compiling 394 files with Solc 0.8.15
[⠊] Compiling 16 files with Solc 0.8.19
[⠒] Solc 0.8.19 finished in 1.75s
[⠒] Solc 0.8.25 finished in 11.09s
[⠰] Solc 0.8.15 finished in 223.81s
Error: 
Compiler run failed:
```

I also took a quick look at the logs from running with `RUST_LOG=trace forge build --force` but couldn't find anything there

**Comment by mds1** [comment]
@mattsse @klkvr can we get a foundry-rs/compilers bump in this repo also? That way we can update our foundry version to get this fix. Reopening the issue until then :)

**Comment by mattsse** [comment]
on it
