### ISSUE TITLE
RPC for getting dev accounts including private key

### ISSUE THREAD

**Issue by antazoey** [foundry-rs/foundry#8558]
### Component

Anvil

### Describe the feature you would like

I would like to be able to programmatically obtain dev account private keys from other processes connected to anvil nodes (no access to forge)

Perhaps:

`anvil_accounts` (mirroring `eth_accounts` RPC) only have it include private keys, indices, and whatever else

### Additional context

If there is another way to do this besides grepping subprocess output or re-calculating the private keys via hd path and mnemonic (what am currently) doing, let me know!

**Comment by antazoey** [comment]
Similar to this: https://github.com/foundry-rs/foundry/issues/8558

**Comment by zerosnacks** [comment]
I don't think this makes sense from a security perspective to expose this for anything but the default dev account keys. Anvil is being used in many scenarios and exposing keys like this violates basic security assumptions. Maintaining a list of hardcoded private keys (or deriving) is not difficult.

**Comment by antazoey** [comment]
I mean, it is telling me the default keys already on process startup, not a huge leap to just give me that info on request, but ok no problem.

**Comment by zerosnacks** [comment]
My apologies, that came out rude. It was not my intention.
