### ISSUE TITLE
perf(`forge test`): forge tests freezing on high verbosity levels (> `-vvv`)

### ISSUE THREAD

**Issue by meitedaf** [foundry-rs/foundry#8559]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (6822860 2024-07-29T00:23:34.055980000Z)

### What command(s) is the bug in?

forge test -vvvvv

### Operating System

macOS (Apple Silicon)

## Every run with forge test -vvvv has become significantly slower, taking between 3-5 minutes to complete

Please look at it for me. This problem has been bothering me for a long time：
[Issue with Forge Tests Freezing on High Verbose Levels #2130](https://github.com/Cyfrin/foundry-full-course-cu/discussions/2130).

**Comment by meitedaf** [comment]
I even deleted VS Code and its configuration folder ~/Library/Application Support/Code, but that didn’t help either.

**Comment by zerosnacks** [comment]
Hi @meitedaf we will need more information for this ticket to be actionable.

Can you link to the test you are running or provide a minimal example?

Presumably it is this repo: https://github.com/Cyfrin/foundry-nft-cu

Running with `forge test -vvvvv` is not unexpectedly slow. Could it be due to your internet connection? If so, try passing the `--offline` flag.

**Comment by meitedaf** [comment]
> Hi @meitedaf we will need more information for this ticket to be actionable.嗨，我们需要更多的信息，这张票是可操作的。
> 
> Can you link to the test you are running or provide a minimal example?您能链接到您正在运行的测试或提供一个最小的示例吗?
> 
> Presumably it is this repo: https://github.com/Cyfrin/foundry-nft-cu大概是这个回购:https://github.com/Cyfrin/foundry-nft-cu
> 
> Running with `forge test -vvvvv` is not unexpectedly slow for me. Could it be due to your internet connection? If so, try passing the `--offline` flag.跑步对我来说并不是出乎意料的慢。会不会是你的网络问题?如果是，试着传递旗帜。

Yes, you are absolutely correct. I tried adding the `--offline` flag, and `forge test -vvvvv` completed very quickly. I’m curious, though, what does adding `--offline` change? Does it only stop checking dependencies from the network?

Even though I don’t understand why running the project directly from GitHub works fine when I have network issues, but running my own project (with the same version of the libraries imported) has problems, this issue that has troubled me for a long time is now resolved. Thank you!

**Comment by zerosnacks** [comment]
`--offline` prevents you from resolving information from Etherscan (this is useful for decoding traces of fork tests, this kicks in at `> -vvv`) and skips checking for missing `solc`

After the initial run the selectors are cached until you run `forge clean`
