### ISSUE TITLE
When getting gasUsed via vm.lastCallGas() function, it excludes intrinsic gas when there is no -gas-report flag in the forge command

### ISSUE THREAD

**Issue by usgeeus** [foundry-rs/foundry#8573]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (26a7559 2024-07-31T00:19:23.655582000Z)

### What command(s) is the bug in?

forge test --mp test/unit/FoundryGasUsedIssue.t.sol -vv

### Operating System

macOS (Apple Silicon)

### Describe the bug

**Describe the bug**
Running the test code below with the command `forge test --mp test/unit/FoundryGasUsedIssue.t.sol -vv` shows `Logs: GasUsed` as 10,275 in the console.
The test code is getting gasUsed via vm.lastCallGas() function.
However, the total gas used should be 10,275 + 96,288 = 106,563 (where 96,288 is the intrinsic gas).

When the `--gas-report` flag is added, running the test with `forge test --mp test/unit/FoundryGasUsedIssue.t.sol -vv --gas-report` correctly updates `GasUsed` to 106,563 in the console.

The reason this is a problem is that we can't use the `--gas-report` flag except for `forge test`.
Also, it's hard to notice that intrinsic gas is not included because we didn't give it the `--gas-report` flag.

**Test Code**
https://github.com/tokamak-network/VDF-RNG-verifier/blob/9ff0ded497f99015559d8b77ab148ced11dd0426/test/unit/FoundryGasUsedIssue.t.sol#L1-L49

**Comment by zerosnacks** [comment]
To get accurate gas measurements you should use the `--isolate` flag, `--gas-report` enables this by default

**Comment by usgeeus** [comment]
> To get accurate gas measurements you should use the `--isolate` flag, `--gas-report` enables this by default which is why you are seeing the difference in behavior 

Ah I see thank you I'll close this issue
