### ISSUE TITLE
replace anvil OP types with op-alloy

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#8575]
### Component

Anvil

### Describe the feature you would like

this anvil type https://github.com/foundry-rs/foundry/blob/c99854277c346fa6de7a8f9837230b36fd85850e/crates/anvil/core/src/eth/transaction/optimism.rs#L13-L13

should be equivalent to

https://github.com/alloy-rs/op-alloy/blob/2ecb2e50ec705df6615596b6c5bde879c6f7dee1/crates/consensus/src/transaction/deposit.rs#L12

and could be replaced

**Comment by programskillforverification** [comment]
I would like to solve this. Please assign it to me.

**Comment by programskillforverification** [comment]
@mattsse is necessary to rename the file?

**Comment by mattsse** [comment]
not necessary

**Comment by yash-atreya** [comment]
Closed by #9047
