### ISSUE TITLE
Add an option to skip calculating root hashes in Anvil

### ISSUE THREAD

**Issue by benwjhack** [foundry-rs/foundry#8579]
### Component

Anvil

### Describe the feature you would like

When doing simulations against anvil, a lot of time gets spent calculating root hashes. As far as I understand this is a proof of correctness, and is useful when multiple nodes are talking to each other; however in a simulation environment these hashes aren't useful. The simulation tooling I've been testing with ([Compass Labs](https://www.compasslabs.ai/docs)) shows that commenting out the lines which calculate these root hashes speeds things up the entire simulation by roughly 25%. 

I would like it if there was some way to configure anvil to not calculate these root hashes. This configuration option could be something like "skip_root_hashes", or something like "single_node_simulation_environment", in case there are further options that make sense only for a simulation environment.

 I would be happy to make an attempt to write this feature if people think it's a good idea, and I get advise on how best to do the configuration option.

**Comment by benwjhack** [comment]
See the fork in which I removed the hashes here - [CompassLabs/foundry-test at do-not-hash](https://github.com/CompassLabs/foundry-test/tree/do-not-hash)
https://github.com/CompassLabs/foundry-test/tree/do-not-hash

**Comment by grandizzy** [comment]
hey @benwjhack from what I can tell that's similar with https://github.com/foundry-rs/foundry/issues/5499#issuecomment-1663487217 so will keep that one to track implementation. Please add context there and feel free to reopen this one if I am wrong, thank you!

**Comment by benwjhack** [comment]
hey, thanks for the reply @grandizzy!
Skipping blocks when mining a large number might help our use case a bit. But my request here would be hopefully significantly technically simpler.
The key point here is that when we run simulations against a single node we do not care about consensus or proof mechanisms at all. So any time, e.g. calculating the state root, is wasted time. I don't think it should ever be the default not to calculate these root hashes; my suggestion is to add some pretty unambiguous configuration flag (with as long a name as appropriate, something like `DangerouslyDisableProofMechanisms`) that would enable the behaviour that I've implemented in the linked fork.
