### ISSUE TITLE
feat(cast): let cast interface look for abi file in the artifacts

### ISSUE THREAD

**Issue by zerosnacks** [foundry-rs/foundry#8580]
### Component

Cast

### Describe the feature you would like

From @DrakeEvans originally stated in: https://github.com/foundry-rs/foundry/pull/7528 

`cast interface` command needs a full file path to the abi which is annoying to look up.  Other commands just need the contract name.

If a name is passed instead of an `address/abi_path` we should look for it in the out folder (which is loaded from the config file)

### Additional context

There have been significant improvements in regards to the way the internals interact with artifacts which should be used.

**Comment by leovct** [comment]
Hi @zerosnacks, happy to tackle this one also :)
