### ISSUE TITLE
feat(`forge script`): ability to verify contracts on multiple explorers at once

### ISSUE THREAD

**Issue by norswap** [foundry-rs/foundry#8599]
### Component

Forge

### Describe the feature you would like

I'd like to verify my contracts on multiple explorers (e.g. Blockscout and Etherscan).

However `forge script` only lets you set a single verifier, and `forge verify-contract` requires you to manually input the constructor arguments, which is some case is quite difficult, and always leads to duplication of logic in any case.

I think the ideal solution would be to add options to `forge verify-contract` so that it can read from a broadcast output file and get the information it needs from there.

**Comment by klkvr** [comment]
This should already be possible with `forge script --resume`. e.g. after you've broadcasted+verified on etherscan, you can run the same command with additional `--resume --verifier-url <other url>` args

**Comment by norswap** [comment]
@klkvr Great point, I only starting understanding how --resume works after posting this, but that would work indeed!
