### ISSUE TITLE
feat(`cheatcodes`): add ability to set seed for `vm.randomUint()` and other cheatcodes that use randomness

### ISSUE THREAD

**Issue by StackOverflowExcept1on** [foundry-rs/foundry#8601]
### Component

Forge

### Describe the feature you would like

I would like to be able to set the seed via cheatcode instead of using `rand::thread_rng()` generator.
https://github.com/foundry-rs/foundry/blob/0b73b426d3aeb1563eeab4d5f2f8134d1c3902e3/crates/cheatcodes/src/utils.rs#L57-L65

**Comment by leovct** [comment]
Happy to tackle this issue!

**Comment by mds1** [comment]
Thanks @leovct! Just to align on the scope, I think we want to take the existing seed argument that used by the fuzzer and use the same seed here. So when the seed it set, it applies to both fuzzer and `vm.random*` cheats. This keeps the UX simpler, as I don't see a reason to separate out the two seeds.

What do you think @grandizzy? Also is there anything we'll need to account for here with the fuzz persistence to make sure seeds are factored in? I think it saves off the concrete values, so I don't think we need to account for anything, but just want to confirm

**Comment by mds1** [comment]
Also cc'ing @zerosnacks to confirm we want this feature / ensure there isn't a reason we left it out

**Comment by grandizzy** [comment]
> Thanks @leovct! Just to align on the scope, I think we want to take the existing seed argument that used by the fuzzer and use the same seed here. So when the seed it set, it applies to both fuzzer and `vm.random*` cheats. This keeps the UX simpler, as I don't see a reason to separate out the two seeds.

Yep, agree, would be nicer to be consistent with the global seed set (if any).

> 
> What do you think @grandizzy? Also is there anything we'll need to account for here with the fuzz persistence to make sure seeds are factored in? I think it saves off the concrete values, so I don't think we need to account for anything, but just want to confirm

Correct, the persisted failure contains calldata for failing test, so replay doesn't depend on the seed used.

**Comment by zerosnacks** [comment]
> Also cc'ing @zerosnacks to confirm we want this feature / ensure there isn't a reason we left it out

Agreed, make sense for this to be consistent with the global seed

It is probably best that these functions that use randomness take a seed are new cheatcodes (additive), not replacing the existing cheatcodes

**Comment by zerosnacks** [comment]
@leovct scratch that, per comment of @mds1, we should modify the existing cheatcodes to simply use the global seed if set, not a new cheatcode.

**Comment by StackOverflowExcept1on** [comment]
I've considered this feature in tests. For example, there is a cryptographic library in Rust and I want to port it to Solidity. In this case, it is quite convenient to set the seed via cheat code and you will have the same randomness on different platforms.

**Comment by leovct** [comment]
I think we could introduce a new forge [inline](https://book.getfoundry.sh/reference/config/inline-test-config) config like `default.fuzz.seed`?

```solidity
contract MyTest is Test {

    /// forge-config: default.fuzz.seed = 0xa1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2
    function test_SimpleTest() public {
        x = vm.randomUint()
    }
```

**Comment by StackOverflowExcept1on** [comment]
Nice, I didn't know about that
