### ISSUE TITLE
`forge test --rerun` should rerun failing fuzz test input

### ISSUE THREAD

**Issue by tynes** [foundry-rs/foundry#8629]
### Component

Forge

### Describe the feature you would like

I am currently experiencing a situation in which `forge test --rerun` does indeed rerun a failed test but the failed test is a fuzz test and it is not always capturing the failure in the fuzz test. Ideally the cached output for the failure should include the fuzz inputs that triggered the failure and those are specifically used as inputs during the call with `--rerun` so that the failure trace can be inspected with `-vvv`

**Comment by tynes** [comment]
Here is an example of this happening in CI: https://app.circleci.com/pipelines/github/ethereum-optimism/optimism/60845/workflows/9d3cf6ec-3be1-4da1-98f8-30b786def971/jobs/2551903

**Comment by grandizzy** [comment]
@tynes does your CI use same cache dir for subsequent runs? The saved fuzz failure counterexample needs to be available in cache dir when rerun, pls see

https://book.getfoundry.sh/forge/replay-testing#fuzz-tests-failures

**Comment by mds1** [comment]
@tynes Going to close this issue since I believe `--rerun` was working properly and what we really saw is https://github.com/foundry-rs/foundry/issues/8639

**Comment by tynes** [comment]
Thank you @grandizzy for the help!
