### ISSUE TITLE
The application panicked (crashed). Message:  failed to extract foundry config

### ISSUE THREAD

**Issue by 0xphantomotr** [foundry-rs/foundry#8630]
### Component

Foundryup

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (7f0f5b4 2024-08-08T00:19:27.650028841Z)

### Operating System

None

### Describe the bug

Hi, just after I used foundryup to update it I got this error on forge build:
`The application panicked (crashed).
Message:  failed to extract foundry config:
foundry config error: data did not match any variant of untagged enum SoldeerDependencyValue for setting `dependencies.@chainlink`

Location: crates/config/src/lib.rs:559

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: __libc_start_call_main<unknown>
      at ./csu/../sysdeps/nptl/libc_start_call_main.h:58
   2: __libc_start_main_impl<unknown>
      at ./csu/../csu/libc-start.c:392

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
Run with RUST_BACKTRACE=full to include source snippets.
Aborted (core dumped)
`

foundry.toml:
`[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
optimizer = true
optimizer_runs = 200

[profile.networks.arbitrum-sepolia]
url = "${ARB_RPC_URL}"
chainId = 421614
etherscan_api_key = "${ETHERSCAN_API_KEY}"
`

**Comment by mattsse** [comment]
> failed to extract foundry config: foundry config error: data did not match any variant of untagged enum SoldeerDependencyValue for setting dependencies.@chainlink`

hmm do you have a [dependencies] table in your foundry.toml?

**Comment by 0xphantomotr** [comment]
It appeared in lib/foundry.toml after foundryup apparently.. Removed it and Its working. Sorry, was too tired yd to figure It out. Closing it!
