### ISSUE TITLE
Unable to verify contract in arbiscan sepolia

### ISSUE THREAD

**Issue by maikelordaz** [foundry-rs/foundry#8631]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (1197fbe 2024-08-09T00:25:14.186740300Z)

### Operating System

Windows

### Describe the bug

Have not been able to verify contracts since last foundryup, neither new one nor existent ones. Tried in git bash and in wsl

**Comment by 0xphantomotr** [comment]
I have the same issue:
`
forge verify-contract --chain-id 421614 --constructor-args $(cast abi-encode "constructor(address,bytes32,uint256,address)" $VRF_COORDINATOR $KEYHASH $SUBSCRIPTION_ID $HOUSE_ACCOUNT) --etherscan-api-key  $ETHERSCAN_API_KEY 0xmyadress src/mycontract.sol:my contract --compiler-version v0.8.19+commit.7dd6d404 --watch
Start verifying contract `0xmyadress` deployed on arbitrum-sepolia

Submitting verification for [src/mycontract.sol:my contract ] 0xmyadress.
Submitted contract for verification:
        Response: `OK`
        GUID: `guid`
        URL: https://sepolia.arbiscan.io/address/0xmyadress
Contract verification status:
Response: `NOTOK`
Details: `Pending in queue`
Contract verification status:
Response: `NOTOK`
Details: `Pending in queue`
Contract verification status:
Response: `NOTOK`
Details: `Pending in queue`
Contract verification status:
Response: `NOTOK`
Details: `Pending in queue`
Contract verification status:
Response: `NOTOK`
Details: `Pending in queue`
Contract verification status:
Response: `NOTOK`
Details: `Pending in queue`
Contract verification status:
Response: `NOTOK`
Details: `Pending in queue`
Contract verification status:
Response: `NOTOK`
Details: `Pending in queue`
Contract verification status:
Response: `NOTOK`
Details: `Pending in queue`
Error: 
Checking verification result failed

Context:
- Verification is still pending...
`

**Comment by maikelordaz** [comment]
@0xphantomotr  I have exactly the same output, had some time without made `foundryup`, this morning I was diid some things in zksync so I did `foundryup-zksync` made some quick changes, change project made again `foundryup` and the problem started. I tried doing `foundryup --commit xxxx` with a commit from two days ago but the problem persists, I dont know to which commit return to be able to verify

**Comment by 0xphantomotr** [comment]
I had the same issue before and after foundryup, hope there is a solution to it :pray:

**Comment by 0xphantomotr** [comment]
Update: After 9 or so hours It got verified, maybe it needed time

**Comment by maikelordaz** [comment]
> Update: After 9 or so hours It got verified, maybe it needed time

Really? Will try again

**Comment by maikelordaz** [comment]
It works now. So I'm closing this
