### ISSUE TITLE
Impersonating account in foundry script using --unlocked flag not working on local forked anvil node

### ISSUE THREAD

**Issue by m-waqas88** [foundry-rs/foundry#8643]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (77158cc 2024-08-10T00:19:09.814973000Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

## What I want to achieve?
I have run a local anvil node that is a fork of mainnet. I want to interact with the local forked blockchain using an impersonated account.

## My research:
While trying to figure out the way to do it I came accross this [PR](https://github.com/foundry-rs/foundry/pull/3614#issuecomment-2278854754), so I followed the same path. But, it is not working.

## Facts

I am trying to impersonate below random account having some ethers
`0xAf2358e98683265cBd3a48509123d390dDf54534`

I run the anvil node using below command

`anvil --fork-url <mainnet-rpc-url>`

Then I run my script using below command

`forge script script/WyScript.s.sol:TestScript --rpc-url http://127.0.0.1:8545 --via-ir --broadcast --unlocked 0xAf2358e98683265cBd3a48509123d390dDf54534`

Terminal shows below error

```bash
[⠊] Compiling...
No files changed, compilation skipped
Script ran successfully.

== Logs ==
  Deployed Address 0x4DbD227Ec1C44DB9A5358d822F0cF7b5477e0CC9

## Setting up 1 EVM.

==========================

Chain 1

Estimated gas price: 2.31269169 gwei

Estimated total gas used for script: 112071

Estimated amount required: 0.00025918567038999 ETH

==========================

Transactions saved to: /Users/.../broadcast/WyScript.s.sol/1/run-latest.json

Sensitive values saved to: /Users/.../broadcast/WyScript.s.sol/1/run-latest.json

Error: 
Failed to send transaction

Context:
- server returned an error response: error code -32602: No Signer available
```

## Code

```solidity
contract TestContract {

    uint256 public immutable totalSupply;

    constructor() {
        totalSupply = 1_000_000e18;
    }

}

contract TestScript is Script {

    TestContract public myContract;


    function run() external {

        vm.startBroadcast(0xAf2358e98683265cBd3a48509123d390dDf54534);

        myContract = new TestContract();

        console.log("Deployed Address", address(myContract));

        vm.stopBroadcast();

    }

}
```

**Comment by m-waqas88** [comment]
@mds1 please consider

**Comment by klkvr** [comment]
You should firstly impersonate the given account:
```cast rpc anvil_impersonateAccount 0xAf2358e98683265cBd3a48509123d390dDf54534```

and then script should succeed

**Comment by m-waqas88** [comment]
> You should firstly impersonate the given account: `cast rpc anvil_impersonateAccount 0xAf2358e98683265cBd3a48509123d390dDf54534`
> 
> and then script should succeed

Yes it worked. Thanks bro. @klkvr 

For someone facing the same issue, here is the flow:

Step# 1: Run the local forked anvil node
Step# 2: Run 'cast rpc anvil_impersonateAccount'
Step# 3: Run the script with `--unlocked` flag

You will be able to broadcast a transaction on local forked blockchain using any real impersonated account.


M closing this issue.
