### ISSUE TITLE
forge fmt: single_line_statement_blocks = "multi" stopped working

### ISSUE THREAD

**Issue by NikitaZ** [foundry-rs/foundry#8650]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

 forge 0.2.0 (a0a0020 2024-08-12T00:20:02.260090000Z)

### What command(s) is the bug in?

forge fmt --check

### Operating System

macOS (Apple Silicon)

### Describe the bug

single_line_statement_blocks = "multi" stopped working, it happened some times during last week, it now requires the following change `else { call() }` to just `else call()` while we have single_line_statement_blocks set to "multi"
```
                          if (data.length == 0) {
108 108  |             _mintAndSettleCallback();
109 109  |         } else if (data.length == 160) {
110 110  |             // _claimVictoryCallback(data);
111      |-        } else {
112      |-            _makeBidCallback(data);
113 111  |         }
    112  |+        else _makeBidCallback(data);
114 113  |         return Constants.ZERO_BYTES;
115 114  |     }
```

It may be caused by https://github.com/foundry-rs/foundry/commit/5ee33c85bb76a08e94622f6922802376d30032bc
but we are not 100% sure. But it must be something about this time.

**Comment by grandizzy** [comment]
@NikitaZ I cannot reproduce it with a sample like

```Solidity
    function setNumber(uint256 newNumber) public {
        number = newNumber;
        if (newNumber = 1) number = 1;
        else if (newNumber = 2) number = 2;
        else newNumber = 3;
    }
```

formatted to 
```Solidity
    function setNumber(uint256 newNumber) public {
        number = newNumber;
        if (newNumber = 1) {
            number = 1;
        } else if (newNumber = 2) {
            number = 2;
        } else {
            newNumber = 3;
        }
    }
```

if 
```
[fmt]
single_line_statement_blocks = "multi"
```

otherwise stays as it is.

Mind to share a way to reproduce the issue? thank you!

**Comment by NikitaZ** [comment]
Yes, I confirm that this has been fixed, thank you so much, that was quick!
