### ISSUE TITLE
feat(forge `verify-contract`): make `verify` crate available as standalone lib; publish to crates.io

### ISSUE THREAD

**Issue by MicaiahReid** [foundry-rs/foundry#8659]
### Component

Forge

### Describe the feature you would like

I'd love to be able to pull foundry's `verify` crate from crates.io. As far as I can tell, we'd just need to re-export some of the crates that it is already importing and it should be ready to publish. I'd be happy to contribute to this if you are open to publishing!

### Additional context

I am working on [txtx](https://github.com/txtx/txtx). We are making a tool that aims to add additional security, reliability, and documentability to on-chain interactions, including contract deployments. [Quick demo](https://www.youtube.com/watch?v=CzARpNQEUzE) in case you're interested in more context.

**Comment by zerosnacks** [comment]
Hi @MicaiahReid thanks for your suggestion

I've added your suggestion in the comments here: https://github.com/foundry-rs/foundry/issues/3895#issuecomment-2287069797 so we can make sure to include it when releasing. If necessary please add additional context or suggestions in the comments on that ticket.

Marking this issue as `duplicate` in favor of https://github.com/foundry-rs/foundry/issues/3895
