### ISSUE TITLE
Simulation fails when revert is handled in low-level call

### ISSUE THREAD

**Issue by ericglau** [foundry-rs/foundry#8662]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (515a4cc 2024-08-13T00:20:15.426447000Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

Some contracts may have a getter which we want to call, and depending on whether that getter is present, we want our script to behave differently.

Specifically, upgradeable contracts from recent releases of OpenZeppelin Contracts [provides a getter to specify the version of the upgrade interface](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/v5.0.2/contracts/proxy/utils/UUPSUpgradeable.sol#L23-L31) that it supports.  The absense of this getter is a valid scenario for older versions.

If we call this getter with a low-level call and handle the case where the call fails, `forge script` detects this revert and fails the simulation prior to broadcasting, even though this revert is expected.  Should the simulation avoid failing in this case?

A workaround is to use a try/catch statement instead, which does not lead to the revert being detected, and does not cause the simulation to fail.

Originally reported in https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/issues/64 and https://github.com/OpenZeppelin/openzeppelin-foundry-upgrades/pull/65

---

Steps to reproduce:
1. In a new project directory, run `forge init`
2. Start an `anvil` node.
3. Change `scripts/Counter.s.sol` to the following:
```
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import {Script, console} from "forge-std/Script.sol";
import {Counter} from "../src/Counter.sol";

contract CounterScript is Script {
    Counter public counter;

    function setUp() public {}

    function run() public {
        vm.startBroadcast(0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80);

        counter = new Counter();

        (bool success, bytes memory returndata) = address(counter).call(abi.encodeWithSignature("myGetter()"));
        if (success) {
            console.log(abi.decode(returndata, (string)));
        } else {
            console.log('function does not exist');
        }

        vm.stopBroadcast();
    }
}
```
4. Run the following command:
```
forge script ./script/Counter.s.sol --rpc-url http://localhost:8545 --broadcast --sender 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
```

This causes the following error:
```
## Setting up 1 EVM.
  [148] Counter::7c0094be()
    └─ ← [Revert] EvmError: Revert

Error: 
Simulated execution failed.
```

**Comment by klkvr** [comment]
in scope of `startBroadcast`, forge script would try to broadcast all `CALL`s and would expect all of them to succeed.

I think in this case you can either disable broadcasting for the duration of this call (just call `stopBroadcast`), or convert it into a `staticcall` which forge wouldn't try to broadcast

**Comment by ericglau** [comment]
Thank you for providing that context.  Using `staticcall` works for this scenario.
