### ISSUE TITLE
docs(`cheatcodes`): `vm.parseJsonKeys` behaviour is documented incorrectly 

### ISSUE THREAD

**Issue by protolambda** [foundry-rs/foundry#8672]
### Component

Forge, Chisel

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9444c6217 2024-07-26T05:14:21.431897181Z)

### What command(s) is the bug in?

forge script, chisel

### Operating System

None

### Describe the bug

The foundry-book docs contain an example where a JSON object, nested in an array, is retrieved to fetch the keys of:
https://book.getfoundry.sh/cheatcodes/parse-json-keys
```
string memory json = '{"root_key": [{"a": 1, "b": 2}]}';
string[] memory keys = vm.parseJsonKeys(json, ".root_key.0"); // ["a", "b"]
```

However, this example doesn't actually seem to work.

To reproduce, in `chisel`:
```
Welcome to Chisel! Type `!help` to show available commands.
➜ string memory json = '{"root_key": [{"a": 1, "b": 2}]}';
string[] memory keys = vm.parseJsonKeys(json, ".root_key.0");
Traces:
  [3617] 0xBd770416a3345F91E4B34576cb804a576fa48EB1::run()
    ├─ [0] VM::parseJsonKeys("{\"root_key\": [{\"a\": 1, \"b\": 2}]}", ".root_key.0") [staticcall]
    │   └─ ← [Revert] key ".root_key.0" must return exactly one JSON object
    └─ ← [Revert] key ".root_key.0" must return exactly one JSON object
```

When not nested in the array it works fine:
```
Welcome to Chisel! Type `!help` to show available commands.
➜ string memory json = '{"root_key": {"a": 1, "b": 2}}';
string[] memory keys = vm.parseJsonKeys(json, ".root_key");
➜ keys
array(2) = [
...
```

**Comment by protolambda** [comment]
`.root_key[0]` works, it may be a docs issue, not a bug

**Comment by DevJSter** [comment]
gm , can i take this issue?

**Comment by DevJSter** [comment]
Hey @protolambda , is this behaviour correct ?

**Comment by jsanchez556** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/foundry).

### My background and how it can be leveraged
Hello, I’m Jose Mario from Costa Rica. With over 15 years of experience in development, I am passionate about contributing to open-source projects and currently expanding my skill set with Rust, Cairo, and Solidity as part of my involvement with Dojo Coding. I am eager to apply my extensive experience and newly acquired skills to new challenges and innovative projects.

### How I plan on tackling this issue
Update the **parseJsonKeys** documentation (https://github.com/foundry-rs/book/blob/master/src/cheatcodes/parse-json-keys.md) by correcting third example , replacing:

string memory json = '{"root_key": [{"a": 1, "b": 2}]}';
string[] memory keys = vm.parseJsonKeys(json, ".root_key[0]"); // ["a", "b"]

with

string memory json = '{"root_key": [{"a": 1, "b": 2}]}';
string[] memory keys = vm.parseJsonKeys(json, ".root_key.0"); // ["a", "b"]

**Comment by DevJSter** [comment]
Hey @jsanchez556 please refer to this PR https://github.com/foundry-rs/book/pull/1260 As I have already completed this issue in this PR

**Comment by protolambda** [comment]
Since the docs have been unified with the actual behavior this can be closed now
