### ISSUE TITLE
bug(`forge inspect`): different `deployedBytecode` returned for same artifact (?)

### ISSUE THREAD

**Issue by RonTuretzky** [foundry-rs/foundry#8673]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (f625d0f 2024-04-02T00:16:42.810315000Z)

### What command(s) is the bug in?

forge inspect

### Operating System

macOS (Intel)

### Describe the bug

Given a repository, one person on our team has run 

```
git checkout mainnet-v0.1.0
forge inspect /path/to/contract/contract.sol:contract deployedBytecode > inspectcode
sha256sum inspectcode
```

which has produced 
fa59be8a26904a24c76db7a5dcd95db95ae37a6aaf3679068fda1b6008919688

However , a different team member has checked out to the same commit, with the same foundry version , the same OS , and the same sha256sum version and has produced a different hash 

68a0d0563c6caf1f4e64c7d873b5c242cfc812da73987a995625aa9414f936fa

Both were on a clean git tree , of the same commit , same origin , etc. 
All foundry configuration files are tracked. 
All submodules were clean. 

Output files attached, they were also verified to be different using `diff` 

[inspectcode1.txt](https://github.com/user-attachments/files/16622830/inspectcode1.txt)
[inspectcode2.txt](https://github.com/user-attachments/files/16622841/inspectcode2.txt)

**Comment by zerosnacks** [comment]
I think there is a high likelihood this is unrelated to Forge given the `forge inspect` simply accesses the generated artifact

**Comment by mds1** [comment]
This is most likely due to a different solidity metadata hash, which can differ between machines. @RonTuretzky if you set the bytecode hash to none in the foundry config and test again, I suspect the code hashes will then match

**Comment by RonTuretzky** [comment]
> This is most likely due to a different solidity metadata hash, which can differ between machines. @RonTuretzky if you set the bytecode hash to none in the foundry config and test again, I suspect the code hashes will then match

Correct! thank you!
