### ISSUE TITLE
Panic when parsing a struct via `clap` containing `NodeArgs and `ScriptArgs`.

### ISSUE THREAD

**Issue by 0xKitsune** [foundry-rs/foundry#8703]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (1710187 2024-08-20T00:18:21.691256534Z)

### Operating System

Linux

### Describe the bug

Currently when trying to parse a struct with `clap` that contians both `NodeArgs` and `ScriptArgs`, this will result in a panic.

    ```
    The application panicked (crashed).
    Message:  Command script: Short option names must be unique for each argument, but '-s' is in use by both 'sig' and 'state_interval'
    ```
    
Would it be possible to remove the short name from the `sig` arg? Having the ability to specify both `NodeArgs` and `ScriptArgs` would be helpful [within op-test-vectors](https://github.com/ethereum-optimism/op-test-vectors/blob/0xkitsune/server/bin/opt8n/src/cmd/script.rs#L8-L16) to make it easier to generate execution test fixtures for OP Stack execution clients. If you would like, I can open a PR for this.
 
If you prefer to not remove the short name, no problem and we can figure out a way to make it work on our end.

**Comment by klkvr** [comment]
I think even if we resolve the `-s` issue there'll still be issue at least with `--fork-url` and some evm-related args.

Those structs belong to completely different components of foundry, thus ensuring and maintaining compatibility between them would be untrivial
