### ISSUE TITLE
bug(`tracing`): custom errors are sometimes not decoded

### ISSUE THREAD

**Issue by logan272** [foundry-rs/foundry#8705]
### Component

Forge

### Describe the feature you would like

Currently, Solidity custom errors are not decoded, making test error messages unreadable. It would greatly improve readability if Forge could decode custom errors in the tests output.

For example, I defined an error AlreadyPaid(address recipient), but it's displaying hex bytecode in the Forge output.

<img width="1545" alt="Screenshot 2024-08-21 at 11 27 10" src="https://github.com/user-attachments/assets/26e49a92-e55f-4c72-8522-8a2de7c51889">

### Additional context

```sh
$ forge --version
forge 0.2.0 (1710187 2024-08-20T00:19:23.968647000Z)
```

**Comment by zerosnacks** [comment]
Hi @logan272 would you have a minimal reproduction example of this error? I'm having trouble replicating it.

**Comment by logan272** [comment]
Hi @zerosnacks, thanks for the reply and here is a minimal reproduction example of the error. 

https://github.com/logan272/custom-error/blob/main/test/Counter.t.sol
