### ISSUE TITLE
bug(`forge verify-bytecode`): incorrectly returning `'No bytecode found at address'`

### ISSUE THREAD

**Issue by blmalone** [foundry-rs/foundry#8710]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (fa0e0c2ca 2024-08-22T00:18:15.471698000Z)

### What command(s) is the bug in?

forge verify-bytecode

### Operating System

macOS (Apple Silicon)

### Describe the bug

The recent PR: https://github.com/foundry-rs/foundry/pull/8510 introduced new functionality around being able to ignore creation code and using different block explorers. 

I'm trying to use a different L2 block explorer to verify a predeploy contract and I'm not able to get the command working. All three of the following commands fail (see screenshot below for failure message).

```
forge verify-bytecode 0xC0d3c0d3c0D3c0D3C0d3C0D3C0D3c0d3c0d30007 L2CrossDomainMessenger --verifier-url https://explorer.zora.energy/api --ignore creation

forge verify-bytecode 0xC0d3c0d3c0D3c0D3C0d3C0D3C0D3c0d3c0d30007 L2CrossDomainMessenger --verifier-url https://explorer.mode.network/api --ignore creation

forge verify-bytecode 0xC0d3c0d3c0D3c0D3C0d3C0D3C0D3c0d3c0d30007 L2CrossDomainMessenger --verifier-url https://explorer.metall2.com/api --ignore creation
```
These commands contain Blockscout explorers for Metal, Mode & Zora op stack rollups.

@yash-atreya @zerosnacks have you got an example of the test you used for testing a blockscout API like this? 

I was able to get this command to work, however it's using Ethereum mainnet so I'm guessing this was on the happy path:
```
forge verify-bytecode 0xE01efbeb1089D1d1dB9c6c8b135C934C0734c846 OptimismMintableERC20Factory --verifier-url https://eth.blockscout.com/api --ignore creation
```

### Steps to reproduce
```
foundryup
git clone https://github.com/ethereum-optimism/optimism.git
cd optimism/packages/contracts-bedrock
git checkout op-contracts/v1.3.0
forge build --skip test scripts
forge verify-bytecode 0xC0d3c0d3c0D3c0D3C0d3C0D3C0D3c0d3c0d30007 L2CrossDomainMessenger --verifier-url https://explorer.metall2.com/api --ignore creation
```

### Error Screenshot
<img width="1494" alt="Screenshot 2024-08-21 at 21 31 21" src="https://github.com/user-attachments/assets/d9a9efe9-9769-4bb4-b86f-e278dade7f26">

Maybe I'm misunderstanding and passing in the incorrect Blockscout URL for these L2s.

cc: @mds1

**Comment by yash-atreya** [comment]
@blmalone I cannot reproduce this. What is the RPC_URL you are using? 
Also, you don't need to specify `--ignore creation`. We detect predeploys automatically

**Comment by blmalone** [comment]
Okay, going to close this PR. I got it to work for:

**Commit**: op-contracts/v1.3.0
```
forge verify-bytecode 0xc0d3c0d3c0d3c0d3c0d3c0d3c0d3c0d3c0d30007 L2CrossDomainMessenger --rpc-url $METAL_RPC_URL --verifier-url $METAL_VERIFIER_URL --ignore creation --json
```

**Comment by blmalone** [comment]
@yash-atreya I've closed in favor of this more specific error: https://github.com/foundry-rs/foundry/issues/8722
