### ISSUE TITLE
Keep nightly builds binaries

### ISSUE THREAD

**Issue by CodeSandwich** [foundry-rs/foundry#872]
### Component

Other (CI)

### Describe the feature you would like

It'd be great if the nightly releases weren't automatically purged every 3 days along with their binaries.

### Additional context

Foundry is already great for local development but it's problematic to set up a CI to use it. There's the excellent `foundry-toolchain` GH action, which makes it a breeze. Unfortunately because it depends on the binaries from releases in this repo, it needs to be reconfigured every 3 days to migrate to the new nightly before the previous one is purged. Alternatively it can always fetch the newest nightly, but that's not acceptable for the CI, it MUST work consistently and it MUST NEVER break because of a 3rd party release. `foundry-toolchain` already supports setting specific nightly releases.

An alternative would be to host a pinned binary myself, but that requires forking `foundry-toolchain` and ideally also `foundryup` to use it, which less than ideal.

**Comment by CodeSandwich** [comment]
> we keep the feedback loop tight

That makes perfect sense. OTOH it hurts adoption, e.g. I'd love to start battering Foundry daily in our project but I can't because that would require destabilizing the CI. Maybe it's not visible from the inside but Foundry is in a really good shape, it's no longer an experiment, it has become a truly viable toolchain good enough to depend on in everyday work. Maybe it's time to acknowledge its readiness and let people start fully utilizing it?

**Comment by cruzdanilo** [comment]
what about cutting a `0.1.1` release?

**Comment by gakonst** [comment]
> Maybe it's not visible from the inside but Foundry is in a really good shape, it's no longer an experiment, it has become a truly viable toolchain good enough to depend on in everyday work. Maybe it's time to acknowledge its readiness and let people start fully utilizing it?

This is great to hear. In that case, let me poll a few others how they'd feel about a versioned release, and we can work on that.

**Comment by maurelian** [comment]
Would love to see versioned releases!

**Comment by desi** [comment]
Hi! I would also love to see versioned releases. If this exists now, I am unable to find them.

**Comment by gakonst** [comment]
1.0 coming in the next few weeks! Thanks for the patience.

**Comment by zerosnacks** [comment]
Closed by https://github.com/foundry-rs/foundry/commit/b0e562faf3f7096743605793e3e2d8c8fd4b7c04
