### ISSUE TITLE
use forge script deploy tron shasta network not work

### ISSUE THREAD

**Issue by zy8890** [foundry-rs/foundry#8725]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9444c62 2024-07-26T00:20:35.095786516Z)

### What command(s) is the bug in?

forge script myScript  --rpc-url https://api.shasta.trongrid.io  -vv

### Operating System

Linux

### Describe the bug

Error: 
HTTP error 405 with body: <html>
<head><title>405 Not Allowed</title></head>
<body>
<center><h1>405 Not Allowed</h1></center>
<hr><center>openresty</center>
</body>
</html>

**Comment by zerosnacks** [comment]
This is unrelated to Foundry. It appears that the RPC endpoint does not support the required RPC methods or does not expose the expected API (specifically POST).

**Comment by u59149403** [comment]
@zy8890

I'm having difficulties with Tron+alloy+foundry compatibility, too. It seems that alloy/foundry doesn't care about Tron compatibility.

I personally think the proper way to solve incompatibility problems is to fix them on Tron's side, not on alloy/foundry's side. Here are relevant threads in TRON about alloy/foundry compatibility: https://github.com/tronprotocol/java-tron/issues/6126 , https://github.com/tronprotocol/java-tron/issues/6289 . It seems that https://github.com/tronprotocol/java-tron/issues/6289 is currently main thread for discussing such compatibility problems. Unfortunately, TRON plans to create so-called archive node to be more compatible with Ethereum ecosystem. This definitely will help compatibility, but this is very big task, which will require a lot of time. I think TRON project should instead focus on small incompatibilities, which can be fixed quickly (such as `input`/`data` problem).

So, please go to mentioned TRON threads, describe your use case, and hopefully TRON will fix incompatibilities on its side!

As a quick workaround you can write your own JSON-RPC proxy, it is, in fact, very easy thing to do.

I wrote my own JSON-RPC proxy (limited to features I need), which makes TRON more Ethereum-compatible. I can share code, if you want.

Note: I'm not representative of alloy, foundry or TRON
