### ISSUE TITLE
feat(`forge selectors`): add option to `find` a selector in the given codebase

### ISSUE THREAD

**Issue by PraneshASP** [foundry-rs/foundry#8726]
### Component

Forge

### Describe the feature you would like

When building on top of other protocols, devs sometimes encounter reverts due to unknown selectors. If a selector isn’t listed in a registry like [4bytes.directory](4bytes.directory), we need to manually search for it by cloning the project, running `forge selectors list`, and finding the error. For large projects, `forge selectors list` output can be too long and get cut off in the terminal. 

To make this easier, I suggest adding a `find` option to the `forge selectors` command. 

**Example:**

```
forge selectors find 0x154c51b8
```

`0x154c51b8` is a selector not present in the registry. The `find` option would help us quickly locate the function/error.

I'm happy to implement this! lmk wdyt.

**Comment by zerosnacks** [comment]
Hi @PraneshASP I think this is a valuable addition, assigning this to you. We'll need to make sure find works for all cases: `function`, `error` and `event`. Perhaps it makes sense for `find` to accept a regex for increased flexibility.

**Comment by mds1** [comment]
Note that you can also use `forge selectors upload` to add all of your project's selectors to the 4byte database, then re-run the 4byte lookup command
