### ISSUE TITLE
bug(`anvil`): `eth_getBlockReceipts` should have support for block hash (`BlockId`)

### ISSUE THREAD

**Issue by Aliceonly** [foundry-rs/foundry#8727]
### Component

Anvil

### Describe the feature you would like

the `eth_getBlockReceipts` method now only support block_number as param

In graph-node v0.35.1, they use `eth_getBlockReceipts` with block_hash to index

Using block_hash param in `eth_getBlockReceipts` should be supported by anvil

I think the method should be flexible of those 2 params

### Additional context

`curl -X POST anvil_rpc \
-H "Content-Type: application/json" \
-d '{
  "jsonrpc": "2.0",
  "method": "eth_getBlockReceipts",
  "params": ["0xa186a130f6a45401fd8bee39bd4858f259eaee4bb0cec901e52cdf3aed172462"],
  "id": 1
}'
{"jsonrpc":"2.0","id":1,"error":{"code":-32602,"message":"number too large to fit in target type"}}%
`

**Comment by zerosnacks** [comment]
Related: https://github.com/alloy-rs/alloy/pull/1135/files

Alloy has been updated to use `BlockId` (the superset of `BlockNumberOrTag`) where applicable

This ticket should update the implementation in Anvil to match the interface now defined in Alloy

**Comment by nnlgsakib** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/foundry).

### My background and how it can be leveraged
I am a seasoned blockchain developer with extensive experience in Ethereum development, including smart contract creation, testing, and optimization. My proficiency in both Solidity and Rust, combined with my in-depth understanding of Ethereum’s underlying architecture, allows me to efficiently identify and address issues within blockchain frameworks. I have previously contributed to open-source projects similar to Foundry and have a strong understanding of RPC methods and their application within the Ethereum ecosystem.

### How I plan on tackling this issue
I would start by analyzing the current implementation of the eth_getBlockReceipts method in Anvil to understand why it currently only supports block_number. I would then propose a solution that allows the method to accept both block_number and block_hash as parameters. This involves modifying the method to detect the type of input provided and handle it accordingly. After implementing the changes, I would thoroughly test the updated method using both parameters to ensure compatibility and performance. Finally, I would update the documentation to reflect the new functionality.

**Comment by PrincesoDan** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/foundry).

### My background and how it can be leveraged
i'm developer

**Comment by mattsse** [comment]
this is actually fixed already:

https://github.com/foundry-rs/foundry/pull/8623
