### ISSUE TITLE
bug(`forge script`): Anvil is accused of not supporting EIP-3855 (PUSH0) when it in fact does

### ISSUE THREAD

**Issue by guidanoli** [foundry-rs/foundry#8730]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (70ef94a 2024-08-23T00:19:52.221312103Z)

### What command(s) is the bug in?

forge script

### Operating System

Linux

## Message

```
EIP-3855 is not supported in one or more of the RPCs used.
Unsupported Chain IDs: 31337.
Contracts deployed with a Solidity version equal or higher than 0.8.20 might not work properly.
For more information, please see https://eips.ethereum.org/EIPS/eip-3855
```

## Steps to reproduce

1. Start `anvil`
2. Create a new Forge project with `forge init`
3. Patch the dummy script, passing one of the private keys from Anvil's default mnemonic

```diff
diff --git a/script/Counter.s.sol b/script/Counter.s.sol
index cdc1fe9..ec1c54f 100644
--- a/script/Counter.s.sol
+++ b/script/Counter.s.sol
@@ -10,7 +10,7 @@ contract CounterScript is Script {
     function setUp() public {}
 
     function run() public {
-        vm.startBroadcast();
+        vm.startBroadcast(0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80);
 
         counter = new Counter();
 
```

4. Run `forge script CounterScript --fork-url http://localhost:8545 --broadcast`

**Comment by zerosnacks** [comment]
Related code: https://github.com/foundry-rs/foundry/blob/44cceb4a3d0a64faf818f16ce7c6ab7dc3a27400/crates/script/src/execute.rs#L234-L259

Will be resolved in https://github.com/alloy-rs/chains/pull/83 by marking Anvil as `shanghai` compatible
