### ISSUE TITLE
Variable's value being updated without reassigning after running skip.

### ISSUE THREAD

**Issue by 0xSpraggins** [foundry-rs/foundry#8756]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (d28a337 2024-08-27T00:19:36.462740000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

Within a foundry test script I am assigning a `uint256` variable the value of `block.timestamp`. Later on after running `skip()` the original variable automatically updats to reflect the new `block.timestamp` without the variable being manually reassigned in the code. 

Current Code:
```solidity
uint256 startingTime = block.timestamp;
console2.log("startingTime: ", startingTime) // Returns 604801

skip(180 days);

console2.log("startingTime: ", startingTime) // Returns 16156801
```

**Comment by DaniPopes** [comment]
This happens with via-ir

See
- https://github.com/foundry-rs/foundry/issues/3806
- https://github.com/foundry-rs/foundry/issues/4934
- https://github.com/foundry-rs/foundry/issues/6180

You can use `vm.getBlockTimestamp()` and other getter methods in vm to avoid compiler optimizations.
