### ISSUE TITLE
bug(`forge fmt`): files sometimes get formatted to entirely empty or partially

### ISSUE THREAD

**Issue by zerosnacks** [foundry-rs/foundry#8769]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (2442e7a 2024-08-28T00:20:11.390296375Z)

### What command(s) is the bug in?

forge fmt

### Operating System

Linux

### Describe the bug

Sometimes running `forge fmt` on a large codebase entirely empties the file content of a file, often unrelated to the file a user has performed changes to. It also sometimes removes a leading `/` in front of `// SPDX-License-Identifier: `.

It is not consistent. Sometimes one file is emptied, sometimes it is many files, sometimes it doesn't happen. Appears to be some kind of race condition.

~~This appears to be behavior introduced relatively recently.~~ see https://github.com/foundry-rs/foundry/issues/8769#issuecomment-2317340461

### To reproduce

Optional: comment out `solc = "0.8.18"` in `foundry.toml` in `foundry/testdata`

Run `forge fmt` inside of the `foundry/testdata` directory multiple times in relatively rapid succession.

### Examples

When running `forge fmt` multiple times (no user edits were made):

```
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   default/cheats/GetFoundryVersion.t.sol
	modified:   default/cheats/MockCall.t.sol
	modified:   default/cheats/SignP256.t.sol
```

Example of it removing a single `/`:

```diff
diff --git a/testdata/default/cheats/MockCall.t.sol b/testdata/default/cheats/MockCall.t.sol
index df7ee89c73..8a6c050089 100644
--- a/testdata/default/cheats/MockCall.t.sol
+++ b/testdata/default/cheats/MockCall.t.sol
@@ -1,4 +1,5 @@
-// SPDX-License-Identifier: MIT OR Apache-2.0
+
+/ SPDX-License-Identifier: MIT OR Apache-2.0
 pragma solidity 0.8.18;
 
 import "ds-test/test.sol";
 ```

Example of it emptying a file:

```diff
diff --git a/testdata/default/cheats/SignP256.t.sol b/testdata/default/cheats/SignP256.t.sol
index f1b62fe78d..8b13789179 100644
--- a/testdata/default/cheats/SignP256.t.sol
+++ b/testdata/default/cheats/SignP256.t.sol
@@ -1,18 +1 @@
-// SPDX-License-Identifier: MIT OR Apache-2.0
-pragma solidity 0.8.18;
 
-import "ds-test/test.sol";
-import "cheats/Vm.sol";
-
-contract SignTest is DSTest {
-    Vm constant vm = Vm(HEVM_ADDRESS);
-
-    function testSignP256() public {
-        bytes32 pk = hex"A8568B74282DCC66FF70F10B4CE5CC7B391282F5381BBB4F4D8DD96974B16E6B";
-        bytes32 digest = hex"54705ba3baafdbdfba8c5f9a70f7a89bee98d906b53e31074da7baecdc0da9ad";
-
-        (bytes32 r, bytes32 s) = vm.signP256(uint256(pk), digest);
-        assertEq(r, hex"7C11C3641B19E7822DB644CBF76ED0420A013928C2FD3E36D8EF983B103BDFE1");
-        assertEq(s, hex"317D89879868D484810D4E508A96109F8C87617B7BE9337411348D7B786F945F");
-    }
-}
```

**Comment by zerosnacks** [comment]
cc @klkvr / @grandizzy

**Comment by grandizzy** [comment]
I don't think it's something new (managed to reproduce with 5902a6fa87600cf0cbe44e689c97479c16fd474e before latest fmt changes) but more related to https://github.com/foundry-rs/foundry/issues/6033 which should not attempt to rewrite files if not changed (or at least lock it to avoid race conditions)
