### ISSUE TITLE
forge create sometimes takes two invocations to work properly

### ISSUE THREAD

**Issue by daweth** [foundry-rs/foundry#877]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (d08a59e 2022-03-01T00:35:40.445140+00:00)

### What command(s) is the bug in?

forge create

### Operating System

macOS (M1)

### Describe the bug

Sometimes, when running the command, it will fail the first time with 

```
Error:
   0: Contract was not deployed
```

then on the second invocation of the exact same command, it will work properly

**Comment by mattsse** [comment]
> forge 0.1.0 (https://github.com/gakonst/foundry/commit/d08a59ec16e07329c70f9a5ccf5dbb92baf367f3 2022-03-01T00:35:40.445140+00:00)

is a bit outdated, does this still happen on the latest version? 
is there a way to reproduce this?

**Comment by onbjerg** [comment]
Pinging @daweth, please update to the latest version and let us know if this is still happening :smile:

**Comment by daweth** [comment]
@onbjerg fixed with later versions of forge
