### ISSUE TITLE
feature --gas-report-diff

### ISSUE THREAD

**Issue by fico23** [foundry-rs/foundry#8774]
forge snapshot --diff offers valuable insights into overall gas consumption changes, yet it can sometimes lack granularity due to multiple function calls within tests. Introducing a forge test --gas-report-diff command could provide a more detailed comparison of gas usage at the function(and deployment) level. This feature would complement the existing forge test --gas-report, enabling developers to pinpoint specific changes in gas consumption with greater precision. Such an enhancement would be incredibly useful for optimizing contract efficiency.

**Comment by zerosnacks** [comment]
Hi @fico23 thanks for your suggestion

I think what you are looking for will be addressed in https://github.com/foundry-rs/foundry/pull/8755

Feel free to join the conversation in https://github.com/foundry-rs/foundry/issues/2065

If this is not the case feel free to re-open the ticket
