### ISSUE TITLE
bug(`forge script`): script hangs after compiling when having more than ~10 transactions

### ISSUE THREAD

**Issue by y77cao** [foundry-rs/foundry#8798]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (d90e997 2024-09-03T00:19:42.467055000Z)

### What command(s) is the bug in?

forge script PostDeploy --broadcast --sig "run()" --priority-gas-price 1 --rpc-url "https://rpc.garnetchain.com" --batch-size=3 --skip-simulation

### Operating System

macOS (Apple Silicon)

### Describe the bug

We have a script doing application configurations and sending out ~300 transactions. We started to see the script hanging for a very long time since last month before the transactions start being processed. It would stuck at this stage for more than 10 min:
```
forge script PostDeploy --broadcast --sig "run()" --priority-gas-price 1 --rpc-url "https://rpc.garnetchain.com" --batch-size=3 --skip-simulation --gas-price 1 --debug
[⠊] Compiling...
No files changed, compilation skipped
```
We only started seeing this around a month ago and didn't have issues before. Can we get some help looking into this?

**Comment by grandizzy** [comment]
@y77cao would you be able to share a way to reproduce it at will, like the source code and exact commands to run? thank you!

**Comment by grandizzy** [comment]
@y77cao optimistically closing this, pls try with latest version, waiting for receipt was changed to better handle errors and avoid infinite loop (https://github.com/foundry-rs/foundry/pull/9253). Please reopen woth sample to reproduce if still an issue. Thank you!
