### ISSUE TITLE
feat(`anvil`): add OP Superchain support to Anvil (`deposit`)

### ISSUE THREAD

**Issue by fainashalts** [foundry-rs/foundry#8801]
### Component

Anvil

### Describe the feature you would like

Hi folks! I lead DevX at OP Labs and I heard through the grapevine that people had questions about Anvil's deposit support in `eth_sendRawTransaction`. We're building a tool that uses this feature, but we don't want to put the onus on Foundry devs to maintain it indefinitely if you don't have other uses for it! I'm hoping we can maintain it or contribute to doing so but would love more context and guidance on the best path forward. ❤️ I posted this in telegram and it was suggested I make an issue here. Thanks!

**Comment by zerosnacks** [comment]
Hi @fainashalts thanks for reaching out

Considering we already support a lot of OP-stack specific functionality I think it is reasonable to add support here. Please add additional details to the ticket in regards to missing functionality, happy to accept a PR from your end to add support for it.

cc @mattsse

**Comment by mattsse** [comment]
anvil supports optimism with --optimism and also handles deposit txs as input, although we only a have a handful of tests for this

**Comment by fainashalts** [comment]
Hi @zerosnacks sorry for missing these comments! I think maybe I wasn't clear - we are super happy about the 
`--optimism` flag and support for the OP Stack. I was simply asking whether we at OP Labs can help with maintenance of the feature at all, specifically making sure Anvil's deposit support in `eth_sendRawTransaction` is maintained. I asked in the telegram channel and was told the best place to discuss this would be in an issue. Is there a better way to open up this convo?
