### ISSUE TITLE
feat(`cheatcodes`): add `vm.random{Bytes, Bytes4, Bytes8}()`

### ISSUE THREAD

**Issue by StackOverflowExcept1on** [foundry-rs/foundry#8805]
### Component

Forge

### Describe the feature you would like

I'm trying to rewrite the FROST cryptographic protocol from Rust to Solidity, and `vm.randomBytes` would be very useful for that. I could set `fuzz.seed = '0xdeadbeef'` in Solidity, and use `StdRng::from_seed(...)` in Rust. This way I can get the same random number generator, which is very convenient for debugging and copying the implementation from Rust code.

I think it makes sense to add [`RngCore`](https://docs.rs/rand/latest/rand/trait.RngCore.html) methods as new cheat codes:
- `vm.randomBytes4` (`next_u32`)
- `vm.randomBytes8` (`next_u64`)
- `vm.randomBytes` (`fill_bytes`)

**Comment by LazarusAA** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/foundry).

### My background and how it can be leveraged
I've worked with both Solidity and Rust before, I am confident I can leverage that experience to tackle this issue



### How I plan on tackling this issue
I will thoroughly review the RngCore documentation to ensure a solid understanding of how to implement the methods as cheat codes and integrate them effectively into the project.

**Comment by Abhishekkochar** [comment]
@StackOverflowExcept1on Please assign me this issue. Thanks.

**Comment by StackOverflowExcept1on** [comment]
@Abhishekkochar Thanks for your contribution, but I don't have rights in this organization.
