### ISSUE TITLE
bug(forge coverage): missing coverage when return variables are named

### ISSUE THREAD

**Issue by peitalin** [foundry-rs/foundry#8809]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (818eeb9 2024-08-31T00:23:20.447780000Z)

### What command(s) is the bug in?

forge coverage --report lcov

### Operating System

macOS (Apple Silicon)

### Describe the bug

When return variables are named in the function definition, the generated lcov file fails to cover the return line:
![Screenshot 2024-09-05 at 1 41 23](https://github.com/user-attachments/assets/9b581ccc-a844-4f98-b8ff-94fcffd34cf0)

Removing named variables resolves the issue:
![Screenshot 2024-09-05 at 1 30 06](https://github.com/user-attachments/assets/60121321-d0ac-4c3c-ac09-b974ef14f96f)

This only appears in some of the functions.

**Comment by grandizzy** [comment]
@peitalin I don't think that's something we can fix as there's no hit for such, rather you could just remove the return statement in functions with named vars as it is a noop anyways and will keep your code cleaner

**Comment by peitalin** [comment]
Ah yep makes sense, that approach works!
