### ISSUE TITLE
feat(`cheatcodes`): add `vm.parseTomlType`

### ISSUE THREAD

**Issue by mds1** [foundry-rs/foundry#8810]
### Component

Forge

### Describe the feature you would like

In https://github.com/foundry-rs/foundry/pull/8345, `parseJsonType` was added. We should also add a corresponding `parseTomlType` cheat

I also wonder if we can support the string being the name of the struct directly, perhaps of the form `ContractName:StructName` or similar so it can be read from artifacts

**Comment by leovct** [comment]
Hi, I'd like to work on this issue

**Comment by mds1** [comment]
Assigned you @leovct! cc @zerosnacks for visibility

> I also wonder if we can support the string being the name of the struct directly, perhaps of the form `ContractName:StructName` or similar so it can be read from artifacts

I would suggest we keep this out of the PR scope since this hasn't been discussed or agreed upon yet, and we can track that idea in a separate issue

**Comment by zerosnacks** [comment]
Thanks @mds1 & @leovct!

@leovct if you have any questions or run into blockers let me know
