### ISSUE TITLE
bug(`remappings`): the specified path cannot be found

### ISSUE THREAD

**Issue by oo90909** [foundry-rs/foundry#8812]
I'm using windows and I get an error when I use forge build
“The specified path cannot be found.”
Here, the path of the joining together with errors, path \, can you tell me the solution?

"D: / software/secure3 / code_Zircuit_zrc_token - main/code/lib/openzeppelin - contracts/contract s\token/ERC20/ERC20.sol”

```
PS D:\software\secure3\code_Zircuit_zrc_token-main\code> forge build
[⠊] Compiling...2024-09-05T02:03:49.467811Z ERROR foundry_compilers_artifacts_solc::sources: error="D:/software/secure3/code_Zircuit_zrc_token-main/code/lib/openzeppelin-contracts/contracts\token/ERC20/ERC20.sol": 系统找不到指定的路径。 (os error 3)
[⠒] Compiling...
Error: 
failed to resolve file: "D:/software/secure3/code_Zircuit_zrc_token-main/code/lib/openzeppelin-contracts/contracts\token/ERC20/ERC20.sol": 系统找不到指定的路径。 (os error 3); check configured remappings
        --> D:/software/secure3/code_Zircuit_zrc_token-main/code/src\ZRC.sol
        @openzeppelin/contracts/token/ERC20/ERC20.sol
```

**Comment by zerosnacks** [comment]
Hi @oo90909 it is likely related to your remappings and not a bug

Note the forward slashes in `D:/software/secure3/code_Zircuit_zrc_token-main/code/..` compared to the backward slashes in `D:\software\secure3\code_Zircuit_zrc_token-main\code` of your directory. Make sure your defined path is Windows compatible.

**Comment by sakulstra** [comment]
@zerosnacks, we started to face this issue randomly also on mac, linux & now also linux-ci.
For us it seems to be related to caches as we can resolve it by pruning the `/cache` folder.

```
2024-10-04T06:05:49.515788Z ERROR foundry_compilers_artifacts_solc::sources: error="/home/runner/work/***-gov-v3/***-gov-v3/lib/aave-helpers/lib/solidity-utils/src/contracts/utils/ChainHelpers.sol": No such file or directory (os error 2)
Error: 
failed to resolve file: "/home/runner/work/***-gov-v3/***-gov-v3/lib/aave-helpers/lib/solidity-utils/src/contracts/utils/ChainHelpers.sol": No such file or directory (os error 2); check configured remappings
	--> /home/runner/work/***-gov-v3/***-gov-v3/script/E2EPayload.s.sol
	solidity-utils/contracts/utils/ChainHelpers.sol
```

I don't know much about foundry internals, but the curious case here is that the file not found - is correctly not found, as it no longer exists at this path. The issue is though that it also is no longer referenced in the core (this is why pruning the cache folder helps).
