### ISSUE TITLE
feat(`anvil`): add `anvil_getIntervalMining` method or make `anvil_setAutomine` resume interval mining

### ISSUE THREAD

**Issue by holic** [foundry-rs/foundry#8813]
### Component

Anvil

### Describe the feature you would like

We start an anvil chain with interval mining:
```
anvil --block-time 2
```

In our deploy script, we want to enable automine for anvil chains so that we can speed up deploys. However, when we disable automine after this script completes, anvil doesn't resume interval mining:

```
cast rpc anvil_setAutomine true
cast rpc anvil_setAutomine false
```

For us to resume to the original interval mining behavior, we'd either need anvil to handle this automatically or expose an `anvil_getIntervalMining` method (to match the existing `anvil_setIntervalMining`) that we can call before we toggle automining and resume the interval mining after our script completes.

(Not sure what the process is like for renaming RPC methods and maintaining backwards compatibility, but with these two methods, it might be clearer to name them `anvil_getMiningInterval` and `anvil_setMiningInterval`).

**Comment by Suhas-30** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/foundry).

### My background and how it can be leveraged
Hi 
I'm Web3 developer and I have grip in NODE.js express.js 
In blockchain domain I have knowledge about foundry and hardhat. I'm proficient in Solidity i know how to openzeppelin  and  ERC20 token

### How I plan on tackling this issue
First i analyze the problem statement then start to think what tool required.
Then i try to break problem statement as possible as which make faster way to reach solution

**Comment by sashhh31** [comment]
i would love to handle this issue, can you assign me with this ?

**Comment by feynman-x** [comment]
I think providing anvil_getIntervalMining could be more useful than just resuming interval mining. 

Some developers may need a different interval than what was set before. With anvil_getIntervalMining, they can adjust it more flexibly to fit their needs.

I’m working on a PR to add this feature and would appreciate any feedback!

**Comment by PedroRosalba** [comment]
I'd love to give this a go.

**Comment by holic** [comment]
Thanks @feynman-x!
