### ISSUE TITLE
Anvil checks the nonce during estimateGas

### ISSUE THREAD

**Issue by blastrock** [foundry-rs/foundry#8814]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (3f15f9a8 2024-09-05T13:19:55.504790587Z)

### What command(s) is the bug in?

anvil --block-time 0.5

### Operating System

Linux

### Describe the bug

I am using interval mining to simulate the real behavior of the blockchain, but it looks like transactions with a nonce too high are rejected by estimateGas, even though they are valid.

## Steps to reproduce

1. Start `anvil --block-time 0.5`
2. Run `cast send 0x70997970C51812dc3A010C7d01b50e0d17dc79C8 --value 1ether --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --nonce 1`

This gives:

```
Error: 
server returned an error response: error code -32003: Nonce too high
```

## Expected behavior

Now, if you avoid the call to estimateGas by giving a gas limit:

1. Start `anvil --block-time 0.5`
2. Run `cast send 0x70997970C51812dc3A010C7d01b50e0d17dc79C8 --value 1ether --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --nonce 1 --gas-limit 50000`
3. Run `cast send 0x70997970C51812dc3A010C7d01b50e0d17dc79C8 --value 1ether --private-key 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80 --nonce 0 --gas-limit 50000`

After the step 3, everything unblocks and both transactions are mined at once.

On the real ethereum blockchain, I understand that estimateGas ignores the nonce and simulate the content of the transaction anyway. Anvil should have the same behavior.

**Comment by mattsse** [comment]
yeah, although I'd argue if you provide the nonce it shouldn't be ignored, but I encountered this on reth as well and we should just ignore the nonce

**Comment by blastrock** [comment]
That was fast! Thank you!
