### ISSUE TITLE
feat(cast): add `cast codehash` and `cast storage-root`

### ISSUE THREAD

**Issue by Sabnock01** [foundry-rs/foundry#8823]
### Component

Cast

### Describe the feature you would like

We currently have commands `cast balance` and `cast nonce` to examine these fields of an account's state. Yet we still lack a `cast codehash` or `cast storage-root`. I propose that these be added to round this out.

Regarding #5467 these would under `account` as subcommands although I'm not sure if they should be added before or after we start breaking the commands out into the different categories. What does everyone think?

**Comment by TC1211** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/foundry).

### My background and how it can be leveraged
I would like to work on this issue.

**Comment by mattsse** [comment]
@TC1211 assigned
