### ISSUE TITLE
bug(`anvil`): Anvil returns transaction log format lacking expected fields for `ots_searchTransactionsBefore`, possibly others

### ISSUE THREAD

**Issue by sealer3** [foundry-rs/foundry#8830]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (8a51b89 2024-09-07T10:53:35.909768350Z)

### Operating System

None

### Describe the bug

For `ots_searchTransactionsBefore` and possibly other Otterscan RPC methods which return receipts, Anvil is returning a `logs` object that does not contain all the required fields per the execution API spec:

Example logs returned by Anvil (`ots_searchTransactionsBefore` response -> `receipts`[0] -> `logs`):
```json
[
	{
		"address": "0x242c735479f3b5cd6a907a90d640edcc1eb1c815",
		"data": "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000254c6f7420230000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
		"topics": [
			"0xd9d4de58fddbbf888ad9e901d6b06fbc30f8267115058fb6860dda919f01bc79"
		]
	}
]
```

Expected format (example):
```json
[
	{
		"address": "0x248e21b0aa161efe3045e3d067d972cd6a01d1b5",
		"topics": [
			"0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
			"0x000000000000000000000000f39fd6e51aad88f6f4ce6ab8827279cfffb92266",
			"0x000000000000000000000000d7f387d4b0eece0a099d35895152de42bc987c5b",
			"0x00000000000000000000000000000000000000000000000000000000000019a7"
		],
		"data": "0x",
		"blockNumber": "0x13a6cb6",
		"transactionHash": "0xea6829000055ded8be1e45e390f0c8edab33aea6362da834e099644bef8dab75",
		"transactionIndex": "0x38",
		"blockHash": "0xca1480043b81baa375c8dfbfb4219f427a03ed126407006ee7f753389042360d",
		"logIndex": "0xc1",
		"removed": false
	}
]
```

**Comment by yash-atreya** [comment]
This is probably because we're using `alloy_primitives::Log` in `OtsReceipt` here
https://github.com/alloy-rs/alloy/blob/72b5b9e7a6a82aba63c35cd85a17347239d47483/crates/rpc-types-trace/src/otterscan.rs#L207

We can introduce a `OtsLog` type in alloy.

**Comment by sealer3** [comment]
Thank you. Note that these entries are also required in `eth_getTransactionReceipt`: https://ethereum.github.io/execution-apis/api-documentation/

**Comment by DaniPopes** [comment]
Is this fixed now? @yash-atreya

**Comment by yash-atreya** [comment]
Yeah bumping alloy to fix

> Is this fixed now? @yash-atreya

Yeah

https://github.com/foundry-rs/foundry/pull/8838
