### ISSUE TITLE
bug(`config`): additional profiles not view in `forge config` and not work with `forge build`

### ISSUE THREAD

**Issue by markgenuine** [foundry-rs/foundry#8846]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (be451fb 2024-09-11T00:20:08.082212000Z)

### What command(s) is the bug in?

forge build and forge config

### Operating System

macOS (Apple Silicon)

### Describe the bug

I have problem with:
1. `forge config`. In toml file i have 2 profile.default and profile.0820 but if call command i don't see it profile.
2. if i do `FOUNDRY_PROFILE=0820 forge install <package>` it's work. But if i do `FOUNDRY_PROFILE=0820 forge build` i get error because i make repos with several version sol. And FOUNDRY_PROFILE=0820 on execute command forge build not picks up.

**Comment by zerosnacks** [comment]
Hi @markgenuine thanks for your flag

Running `forge install` with custom profiles is not supported

Make sure `auto_detect_solc` is set to `true` to enable multi-compilation

https://book.getfoundry.sh/reference/config/solidity-compiler#auto_detect_solc
