### ISSUE TITLE
bug: `revert: ` is inserted when using `vm.expectRevert()` with require

### ISSUE THREAD

**Issue by linghuccc** [foundry-rs/foundry#8862]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (2cdbfac 2024-09-13T00:19:28.765326706Z)

### What command(s) is the bug in?

vm.expectRevert()

### Operating System

Linux

### Describe the bug

Contract source code: `https://github.com/linghuccc/tintinland_ethereum/blob/main/task2/src/NftSwap.sol`

Function having issue: `function purchase(address nftContract, uint256 tokenId)`

Check code having issue: `require(msg.value >= order.price, "Insufficient payment");`

==========================================================================

Test codes: `https://github.com/linghuccc/tintinland_ethereum/blob/main/task2/test/NftSwap.t.sol`

Testing function having issue: `function testFailPurchaseWithInsufficientPayment()`

Testing code having issue: `vm.expectRevert("Insufficient payment");`

==========================================================================

As can be seen from the contract source code, when doing testing, "`vm.expectRevert("Insufficient payment");`" should work, but it did not. Only "`vm.expectRevert("revert: Insufficient payment");`" works.

Please help to look into this. Thank you.

**Comment by grandizzy** [comment]
@linghuccc you're using a test named `testFailPurchaseWithInsufficientPayment` where `Fail` is a reserved keyword, see
```
testFail: The inverse of the test prefix - if the function does not revert, the test fails.
```
in https://book.getfoundry.sh/forge/writing-tests. Change name of test to `testPurchaseWithInsufficientPayment` to make it pass

**Comment by linghuccc** [comment]
> @linghuccc you're using a test named `testFailPurchaseWithInsufficientPayment` where `Fail` is a forge keyword / test prefix, see
> 
> ```
> testFail: The inverse of the test prefix - if the function does not revert, the test fails.
> ```
> 
> in https://book.getfoundry.sh/forge/writing-tests. Change name of test to `testPurchaseWithInsufficientPayment` to make it pass

Thank you so much. Could not believe I made such a low-level mistake.   -_-"
