### ISSUE TITLE
bug(`anvil`): `Error: contract not deployed`, contract disappears after a while

### ISSUE THREAD

**Issue by vseae** [foundry-rs/foundry#8866]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### Operating System

None

### Describe the bug

I deployed my contract, and it was callable at the time. Why did my contract disappear after a while, showing that it doesn't exist?

**Comment by vseae** [comment]
anvil -f https://arbitrum-mainnet.infura.io/v3/infura_key --chain-id 421614 --gas-limit 10000000000 --disable-block-gas-limit --disable-code-size-limit --auto-impersonate

**Comment by yash-atreya** [comment]
Can you provide clearer instructions to reproduce? What were the exact steps you took until this occurred? 
We cannot debug without reproducing.

**Comment by grandizzy** [comment]
@vseae please provide more details as suggested above, going to close ticket for now, please reopen with a way to reproduce if still an issue. Thank you
