### ISSUE TITLE
Error: `forge init`

### ISSUE THREAD

**Issue by iprotoni** [foundry-rs/foundry#8869]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0

### Operating System

None

### Describe the bug

`forge init`

Error: 
The target directory is a part of or on its own an already initialized git repository,
and it requires clean working and staging areas, including no untracked files.

Check the current git repository's status with `git status`.
Then, you can track files with `git add ...` and then commit them with `git commit`,
ignore them in the `.gitignore` file, or run this command again with the `--no-commit` flag.

If none of the previous steps worked, please open an issue at:
https://github.com/foundry-rs/foundry/issues/new/choose

**Comment by zerosnacks** [comment]
Rerun with `forge init --no-commit`
