### ISSUE TITLE
Put gas consumption of fuzz tests behind flag when using snapshot mode

### ISSUE THREAD

**Issue by gakonst** [foundry-rs/foundry#888]
### Component

Forge

### Describe the feature you would like

# Problem

When using snapshot testing, due to different fuzz values, the gas output from a test may differ across runs. This ends up creating gigantic snapshot diffs. 

# Potential Solution

We should by default not print the fuzz test values to the snapshot file (what we do now) and maybe add a flag which lets you get today's behavior

(This was requested by @transmissions1, pls weigh in if any other ideas for solving this)

**Comment by shuklaayush** [comment]
An alternative might be to do snapshot testing with a hardcoded seed for the fuzzer rng. proptest has a [`TestRng::deterministic_rng`](https://docs.rs/proptest/1.0.0/proptest/test_runner/struct.TestRng.html#method.deterministic_rng) function that can probably be used with [`TestRunner::new_with_rng`](https://altsysrq.github.io/rustdoc/proptest/latest/proptest/test_runner/struct.TestRunner.html#method.new_with_rng) for this

**Comment by onbjerg** [comment]
Solved in https://github.com/foundry-rs/foundry/pull/1141
