### ISSUE TITLE
bug(`cheatcodes`): memory not deallocating after snapshot `revertTo`

### ISSUE THREAD

**Issue by Akbar30Bill** [foundry-rs/foundry#8890]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a117fbf 2024-05-13T00:22:16.352837000Z)

### What command(s) is the bug in?

forge script script/testSnapshot.sol

### Operating System

macOS (Apple Silicon)

### Describe the bug

**Description:**
As suggested in the [Foundry book](https://book.getfoundry.sh/cheatcodes/snapshots), the snapshots that are reverted should be deleted from memory. However, my script demonstrates that this is not the case, as the memory usage keeps growing.

I wrote a simple Forge script to illustrate this behavior. You can run the script and observe the increasing memory usage during execution:

```solidity
pragma solidity ^0.8.25;

import {Script, console2} from "forge-std/Script.sol";

contract testSnapshot is Script {
    function run() public {
        for (uint256 i = 0; i < 1000000; i++) {
            console2.log("Snapshot number: ", i);
            uint256 snapshot = vm.snapshot();
            vm.revertTo(snapshot);
        }
    }

    function setUp() public {}
}
```

**Expected Behavior:**
After reverting to a snapshot, the memory allocated for that snapshot should be cleaned up or deallocated to prevent memory bloat.

**Actual Behavior:**
The memory usage continues to grow with each snapshot taken, even after it has been reverted.

**Environment:**
- Solidity version: 0.8.25
- Forge version: 0.2.0 (a117fbf 2024-05-13T00:22:16.352837000Z)
  
**Steps to Reproduce:**
1. Run the provided script.
2. Monitor the memory usage throughout the execution.

Please investigate this issue to confirm whether the snapshots are not being properly deallocated from memory.

**Comment by grandizzy** [comment]
@Akbar30Bill indeed `revertTo` doesn't delete snapshot, you need to use `revertToAndDelete` (deprecated in favor of `revertToStateAndDelete` in latest versions), will keep this issue to update book (there are other snapshot cheatcodes missing (`deleteSnapshot(s)`)
