### ISSUE TITLE
docs(`forge script`): incorrect `msg.sender` leading to unpredictable and potentially dangerous results

### ISSUE THREAD

**Issue by haydenyoung** [foundry-rs/foundry#8892]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (41d4e54 2024-09-17T00:18:07.762487140Z)

### What command(s) is the bug in?

forge script

### Operating System

Linux

### Describe the bug

When using forge script to deploy a smart contract, I am passing the msg.sender as a constructor parameter. However, the msg.sender value is unpredictable, which has resulted in an incorrect msg.sender being passed to the constructor when deploying to a testnet.

Example:  a local deployment to Anvil using an EOA's private key will result in the msg.sender being the EOA's wallet address:

```
forge script ./script/MyDeployment.s.sol --broadcast --private-key <some-pk> --rpc-url 127.0.0.1:8545
```

However, deploying to a remote chain using an account stored in the keystore results in (what appears to be) Foundry's default address being msg.sender:

```
forge script ./script/MyDeployment.s.sol --broadcast --rpc-url $(SEPOLIA_RPC_URL) --account SomeWallet --verify
``` 

If the msg.sender is passed to the smart contract in the constructor, this can lead to a smart contract being incorrectly instantiated. This can have a catastrophic effect on a contract which may be passing msg.sender as some kind of access control admin leading to the contract being inaccessible or vulnerable to attack.

[Another issue](https://github.com/foundry-rs/foundry/issues/7255) hints at an error message being printed during deployment but this only occurs when one of the vm methods is called, not when msg.sender is passed as a param during the instantiation of a smart contract.

I'm not sure why the msg.sender can potentially be some kind of default Foundry account and not always the address of the calling account (whether an EOA or another smart contract).

**Comment by zerosnacks** [comment]
Thanks @haydenyoung for flagging this

In `forge script` we have a parameter available to explicitly define the `sender` and we emit a warning whenever the default deployer is used

```
      --sender <ADDRESS>
          The address which will be executing tests/scripts
```

Because of `msg.sender` unpredictability I would generally recommend passing an address in the constructor but perhpas there is some further improvement we can do. Definitely interest in improving the user experience in this area further, open for suggestions.

**Comment by haydenyoung** [comment]
Thanks @zerosnacks. For now I am using the --sender flag you suggest and the deployment is successful.

Perhaps using msg.sender as a param to a constructor is not the best dev pattern as it can lead to unpredictability. As you say, maybe this should be passed in directly, I guess ideally via `vm.envAddress` so that it is configurable.

**Comment by rpedroni** [comment]
Not sure why this isn't a bug?

The following script is being passed both a `--private-key` and `--sender` (did try separately) and in both cases is using the default account, with no warnings

```solidity
console.log(">>> Sender: %s", msg.sender);
address calculatedAddress = vm.computeCreateAddress(msg.sender, vm.getNonce(msg.sender) + 1);
console.log(">>> Expected address: %s", calculatedAddress);

vm.startBroadcast();
...
```

**Comment by saeta-eth** [comment]
This should be reopened I guess; I would expect `--account` to be the default sender.
