### ISSUE TITLE
ci: avoid running the CI outside of explicit paths or explicit file extensions

### ISSUE THREAD

**Issue by zerosnacks** [foundry-rs/foundry#8894]
### Component

Other (please describe)

### Describe the feature you would like

With Github workflows we can define specific paths or file extensions which should trigger the CI

For example, a change to `README.md` shouldn't need to trigger the test workflow

See: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-including-paths

**Comment by DaniPopes** [comment]
tbh I never found specifying these worthwhile, we're not even paying anything for PR CI runners anyway

**Comment by zerosnacks** [comment]
> tbh I never found specifying these worthwhile, we're not even paying anything for PR CI runners anyway

Fair, especially if we are not paying for the CI

Going to mark this as `not planned`
