### ISSUE TITLE
feat: allow `forge coverage` to reuse build/test artifacts

### ISSUE THREAD

**Issue by vbidin** [foundry-rs/foundry#8904]
### Component

Forge

### Describe the feature you would like

Checking for code coverage is done by running `forge coverage` which always compiles contracts and runs tests. This means that even if the contracts were already compiled and/or tested (for example as part of a previous step in a CI pipeline) they will be processed again. Enabling `forge coverage` to use _existing_ build artifacts and to run _during_ `forge test` could prevent duplicate work from being carried out and make code coverage checks run faster.

**Comment by zerosnacks** [comment]
Hi @vbidin thanks for your suggestion

Unfortunately `forge coverage` always must run with optimizations disabled whereas tests by default run with optimization enabled (related: https://github.com/foundry-rs/foundry/issues/2486). We are looking at disabling optimizations by default which should make this possible but has other trade-offs (like stack to deep).

Going to mark this as a duplicate of https://github.com/foundry-rs/foundry/issues/8889, feel free to participate in that conversation as it aims to resolve the same issue
