### ISSUE TITLE
bug: logs emitted on RPC failures when forking are not descriptive enough

### ISSUE THREAD

**Issue by anajuliabit** [foundry-rs/foundry#8908]
### Component

Forge

### Describe the feature you would like

It's quite common in our codebase to experience CI failures related to RPC errors. For example:

```Could not instantiate forked environment with fork url: ***```

 or
```
[FAIL. Reason: backend: failed while inspecting] 
````

Here are some logs for more context
https://github.com/moonwell-fi/moonwell-contracts-v2/actions/runs/10927647686/job/30334305230?pr=350
https://github.com/moonwell-fi/moonwell-contracts-v2/actions/runs/10944099346/job/30385149157

It would be really great if the error messages from Forge could give us more details. We are not Rust engineers, so it's tough for us to figure out what's causing the issue.

Thank you!

**Comment by grandizzy** [comment]
@anajuliabit would it be possible to provide more informations on the failure (which RPC, fork block heights, etc), we're looking into a constant reproducing the issue to understand where the issue lies and provide a better err message. thank you!

**Comment by lyoungblood** [comment]
> @anajuliabit would it be possible to provide more informations on the failure (which RPC, fork block heights, etc), we're looking into a constant reproducing the issue to understand where the issue lies and provide a better err message. thank you!

The providers we are using are BlastAPI and Alchemy for Base and OP mainnet. The errors seem to occur on both.

On some networks like Moonbeam we are only using BlastAPI because that's the only provider we have.

The 520s seem to be intermittent and not correlated with any single network or RPC provider. Perhaps you could implement an exponential backoff/retry for these instead of crashing?

**Comment by grandizzy** [comment]
> The 520s seem to be intermittent and not correlated with any single network or RPC provider. Perhaps you could implement an exponential backoff/retry for these instead of crashing?

Hey @lyoungblood you could try setting `--fork-retries` and --fork-retry-backoff` to avoid such see https://book.getfoundry.sh/reference/cli/forge/script#forge-script
