### ISSUE TITLE
bug(`cheatcodes`): `deal` does not work with Overnight.fi USD+

### ISSUE THREAD

**Issue by thepluck** [foundry-rs/foundry#8916]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (2442e7a 2024-08-28T00:20:11.390296375Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

When using 'deal' with Overnight.fi USD+, it will fail with the following error:
```
    ├─ [0] VM::store(0xB79DD08EA68A908A97220C76d19A6aA9cBDE4376, 0x86352f061a975ea9f306ab8879222ebda71d83ef729b31963c8ea1eee97b258d, 0x0000000000000000000000000000000000000000000000000000000000000000)
    │   └─ ← [Return] 
    └─ ← [Revert] revert: stdStorage find(StdStorage): Failed to write value.
```
Token tracker page: https://basescan.org/token/0xB79DD08EA68A908A97220C76d19A6aA9cBDE4376

**Comment by yash-atreya** [comment]
@thepluck I cannot reproduce this. Can you share more details? Perhaps, some demo code and exact command

**Comment by thepluck** [comment]
@yash-atreya Sorry for the late response, here is a simplified code snippet that led to the error.
```solidity
// SPDX-License-Identifier: MIT
pragma solidity 0.8.9;

import 'forge-std/Test.sol';
import 'contracts/interfaces/aerodromev1/IAerodromeV1Pair.sol';

contract Base is Test {
  string BASE_RPC_URL = vm.envString('BASE_NODE_URL');
  uint256 FORK_BLOCK = 19713107;
  uint256 baseFork;
  address deployer = makeAddr('deployer');

  function setUp() public {
    baseFork = vm.createFork(BASE_RPC_URL);
    vm.selectFork(baseFork);
    vm.rollFork(FORK_BLOCK);
  }

  function testTest(uint256 seed) public {
    deal(0xB79DD08EA68A908A97220C76d19A6aA9cBDE4376, deployer, seed);
  }
}
```

**Comment by klkvr** [comment]
rebasing tokens are not straightforward to support for `deal` which assumes that balance is kept in a single storage slot

you should be able to calculate and override `_creditBalances` slot for needed user by using `vm.store` directly
