### ISSUE TITLE
Building from source for `cast` is broken

### ISSUE THREAD

**Issue by pcaversaccio** [foundry-rs/foundry#8932]
Repro:

```bash
cargo install --git https://github.com/foundry-rs/foundry --profile release --locked forge cast chisel anvil
```

Output:

![image](https://github.com/user-attachments/assets/fa48bc81-35a5-43ea-bb50-e1b28aa2747f)

and

```bash
Replacing C:\Users\yolo\.cargo\bin\anvil.exe
Replaced package `anvil v0.2.0 (https://github.com/foundry-rs/foundry#d90e997d)` with `anvil v0.2.0 (https://github.com/foundry-rs/foundry#cd1c77aa)` (executable `anvil.exe`)
Summary Successfully installed forge, chisel, anvil! Failed to install cast (see error(s) above).
```

OS: Windows

**Comment by mattsse** [comment]
@DaniPopes I believe this due to how cargo install works, and since we renamed the crate to foundry-cast, we'd need to run as `forge foundry-cast chisel anvil`

**Comment by pcaversaccio** [comment]
> @DaniPopes I believe this due to how cargo install works, and since we renamed the crate to foundry-cast, we'd need to run as `forge foundry-cast chisel anvil`, even though the binary is still called cast

This seems right - just tested. Is there a way of aliasing it somehow? Also, the docs should be updated to reflect this change: https://book.getfoundry.sh/getting-started/installation#building-from-source
