### ISSUE TITLE
Error using Anvil "--fork-transaction-hash" argument with Base chain

### ISSUE THREAD

**Issue by ctrl-danny** [foundry-rs/foundry#8940]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a592f7a 2024-09-23T00:23:27.691802000Z)

### What command(s) is the bug in?

anvil

### Operating System

macOS (Apple Silicon)

### Describe the bug

Using anvil along with the "--fork-transaction-hash" argument for transactions on Base chain is failing. This is in contrast to "--fork-block-number" which works fine. 

Here is an example of the command with a sample Base transaction, assuming FORK_URL is a valid Base node:
```
TRANSACTION_HASH=0x969d8e40260a84ecbc65658772bc80bcea2a84e7c386fe636a9f171c1bd04c90
anvil --fork-url $FORK_URL --fork-transaction-hash $TRANSACTION_HASH
```

The output received is:
```
thread 'main' panicked at /Users/runner/work/foundry/foundry/crates/anvil/src/config.rs:1091:77:
Failed to derive fork block number and force transactions from fork choice: Unexpected type flag. Got 126.

Caused by:
    Unexpected type flag. Got 126.

Location:
    crates/anvil/src/eth/pool/transactions.rs:122:33
```

The transaction forked from is a type 2 transaction, not type 126, however the first transaction in every Base block is a system transaction of type 126. For example, for the sample transaction used above from block 20142328, the system transaction from this block is https://basescan.org/tx/0x054a5a5c33d73422605ea96da29f9e23dfbdfacbd707a1a88cdd8753d471f30b. It seems that there is an issue during forking with the replay of the system transactions.

Note that the transaction used here is just an example, and that the fork fails for any chosen Base transaction as well.

**Comment by yash-atreya** [comment]
Identified the issue, It has to do with how we convert transactions to `TypedTransactions`, currently we're not handling OP `Deposit` txs during the conversion. 

https://github.com/foundry-rs/foundry/blob/07a1f67114565968b188d1abf42fe2c5c57bfca5/crates/anvil/core/src/eth/transaction/mod.rs#L1011

Fix should be up soon.

**Comment by grandizzy** [comment]
> Identified the issue, It has to do with how we convert transactions to `TypedTransactions`, currently we're not handling OP `Deposit` txs during the conversion.
> 
> https://github.com/foundry-rs/foundry/blob/07a1f67114565968b188d1abf42fe2c5c57bfca5/crates/anvil/core/src/eth/transaction/mod.rs#L1011
> 
> Fix should be up soon.

awesome! was wondering if we could just ignore that type of tx when we fork from tx, like

```rust
             let force_transactions = filtered_transactions
                 .iter()
+                .filter(|&transaction| transaction.transaction_type.unwrap_or_default() != DEPOSIT_TX_TYPE_ID)
                 .map(|&transaction| PoolTransaction::try_from(transaction.clone().inner))

```

https://github.com/foundry-rs/foundry/blob/07a1f67114565968b188d1abf42fe2c5c57bfca5/crates/anvil/src/config.rs#L1303

but not sure if other side effects, wdyt?

**Comment by yash-atreya** [comment]
Don't this we should ignore as this would remove them from the fork config and we already have the incoming txs from the RPC as `WithOtherFields<T>`, just need to change the `TryFrom` implementations.

**Comment by yash-atreya** [comment]
> > Identified the issue, It has to do with how we convert transactions to `TypedTransactions`, currently we're not handling OP `Deposit` txs during the conversion.
> > https://github.com/foundry-rs/foundry/blob/07a1f67114565968b188d1abf42fe2c5c57bfca5/crates/anvil/core/src/eth/transaction/mod.rs#L1011
> > 
> > Fix should be up soon.
> 
> awesome! was wondering if we could just ignore that type of tx when we fork from tx, like
> 
> ```rust
>              let force_transactions = filtered_transactions
>                  .iter()
> +                .filter(|&transaction| transaction.transaction_type.unwrap_or_default() != DEPOSIT_TX_TYPE_ID)
>                  .map(|&transaction| PoolTransaction::try_from(transaction.clone().inner))
> ```
> 
> https://github.com/foundry-rs/foundry/blob/07a1f67114565968b188d1abf42fe2c5c57bfca5/crates/anvil/src/config.rs#L1303
> 
> but not sure if other side effects, wdyt?

Don't this we should ignore as this would remove them from the fork config and we already have the incoming txs from the RPC as WithOtherFields<T>, just need to change the TryFrom implementations.

**Comment by grandizzy** [comment]
> Don't this we should ignore as this would remove them from the fork config and we already have the incoming txs from the RPC as WithOtherFields, just need to change the TryFrom implementations.

makes sense! I have a test that I think we could add for this scenario in anvil's fork suite, up to you

```rust
#[tokio::test(flavor = "multi_thread")]
async fn test_fork_optimism_with_transaction_hash() {
    use std::str::FromStr;
    // enable the Optimism flag
    // Fork to a block with a specific transaction
    let fork_tx_hash =
        TxHash::from_str("fcb864b5a50f0f0b111dbbf9e9167b2cb6179dfd6270e1ad53aac6049c0ec038")
            .unwrap();
    let (api, _handle) = spawn(
        NodeConfig::test()
            .with_eth_rpc_url(Some(rpc::next_rpc_endpoint(NamedChain::Optimism)))
            .with_fork_transaction_hash(Some(fork_tx_hash)),
    )
    .await;

    // Make sure the fork starts from previous block
    let block_number = api.block_number().unwrap().to::<u64>();
    assert_eq!(block_number, 125777954 - 1);
}
```

**Comment by yash-atreya** [comment]
> > Don't this we should ignore as this would remove them from the fork config and we already have the incoming txs from the RPC as WithOtherFields, just need to change the TryFrom implementations.
> 
> makes sense! I have a test that I think we could add for this scenario in anvil's fork suite, up to you
> 
> ```rust
> #[tokio::test(flavor = "multi_thread")]
> async fn test_fork_optimism_with_transaction_hash() {
>     use std::str::FromStr;
> 
>     // Fork to a block with a specific transaction
>     let fork_tx_hash =
>         TxHash::from_str("fcb864b5a50f0f0b111dbbf9e9167b2cb6179dfd6270e1ad53aac6049c0ec038")
>             .unwrap();
>     let (api, _handle) = spawn(
>         NodeConfig::test()
>             .with_eth_rpc_url(Some(rpc::next_rpc_endpoint(NamedChain::Optimism)))
>             .with_fork_transaction_hash(Some(fork_tx_hash)),
>     )
>     .await;
> 
>     // Make sure the fork starts from previous block
>     let block_number = api.block_number().unwrap().to::<u64>();
>     assert_eq!(block_number, 125777954 - 1);
> }
> ```

Thanks! Added it.
