### ISSUE TITLE
debt(`anvil`): use `TxDeposit` from `op-alloy-consensus` 

### ISSUE THREAD

**Issue by yash-atreya** [foundry-rs/foundry#8943]
### Component

Anvil

### Describe the feature you would like

Replace the existing `DepositTransaction` https://github.com/foundry-rs/foundry/blob/07a1f67114565968b188d1abf42fe2c5c57bfca5/crates/anvil/core/src/eth/transaction/optimism.rs#L277 with `TxDeposit` from op-alloy: https://github.com/alloy-rs/op-alloy/blob/f6d9d723fff605c8b87a95548d4eb56338dc2c1e/crates/consensus/src/transaction/deposit.rs#L15

**Comment by pratikramteke** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/foundry).

### My background and how it can be leveraged
i recently start learning about solidity.

### How I plan on tackling this issue
as you say in problem statement so just replacing DepositTransaction method to TxDeposit will be fine.

**Comment by toastx** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/foundry).

### My background and how it can be leveraged
I have used alloy-rs to build a smart contracts and their respective backend, and I am familiar with the module.

### How I plan on tackling this issue
Straight implementation of the TxDeposit Struct from alloy-rs

**Comment by c0np4nn4** [comment]
Can I take this issue?

### My background and how it can be leveraged
I previously contributed to Reth (https://github.com/paradigmxyz/reth/pull/9811) and have a solid understanding of Rust code.

### How I plan on tackling this issue
As you mentioned in the issue, I will review both structs and try to replace the old one (`DepositTransaction`) with the one from op-alloy.

**Comment by zerosnacks** [comment]
I think this is already included in scope of https://github.com/foundry-rs/foundry/issues/6860 that @leovct is working on
