### ISSUE TITLE
`forge coverage` yielding a backtrace error

### ISSUE THREAD

**Issue by chasebrownn** [foundry-rs/foundry#8957]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (07a1f67 2024-09-24T00:21:46.334787592Z)

### What command(s) is the bug in?

forge coverage

### Operating System

Windows

### Describe the bug

Trying to run `forge coverage` and it is outputting this:

![image](https://github.com/user-attachments/assets/3fcca061-3877-4340-80e5-05d598062354)

Repo: https://github.com/re-al-Foundation/rwa-contracts/tree/dev

**Comment by grandizzy** [comment]
looks similar with https://github.com/foundry-rs/foundry/issues/8395#issuecomment-2238509944 which I suspect is due to wsl introducing bad characters occasionally

**Comment by grandizzy** [comment]
@chasebrownn since I am not able to test this locally, could you please check tomorrow's nightly (should include https://github.com/foundry-rs/foundry/pull/8958) and report if it solves the issue? thank you!

**Comment by grandizzy** [comment]
you'll need to `foundryup` (which installs nightly builds) but fix is not yet released. it will be tomorrow, you can see what's included in a build here https://github.com/foundry-rs/foundry/releases

**Comment by chasebrownn** [comment]
Issue persists

**Comment by grandizzy** [comment]
fix is now published, pls foundryup and retest

**Comment by chasebrownn** [comment]
solved. thank you
