### ISSUE TITLE
feat(`cast`): add --timeout option

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#8959]
### Component

Cast

### Describe the feature you would like

there are certain (experimental) rpc endpoints that take a while, e.g. witness endpoints.

it'd be useful to bump the default timeout:

https://github.com/foundry-rs/foundry/blob/cd1c77aa5db15b643b9e994e4f71c71f9b9a862f/crates/common/src/constants.rs#L20-L20

## TODO
* add timeout option to
https://github.com/foundry-rs/foundry/blob/cd1c77aa5db15b643b9e994e4f71c71f9b9a862f/crates/cast/bin/cmd/rpc.rs#L10-L10

and configure rpc builder accordingly:

https://github.com/foundry-rs/foundry/blob/cd1c77aa5db15b643b9e994e4f71c71f9b9a862f/crates/cast/bin/cmd/rpc.rs#L41-L41

**Comment by msmilan69** [comment]
I can take this up

**Comment by farman13** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/foundry).

### My background and how it can be leveraged
I have experience in working with blockchain technologies, smart contract development, and optimizing decentralized systems. My understanding of Rust, RPC calls, and handling timeouts in distributed systems allows me to implement features like configurable timeouts efficiently. I can contribute by enhancing the current RPC functionality with minimal disruption, ensuring that long-running requests are handled effectively through configurable timeout options.

### How I plan on tackling this issue
We expanded the `RpcArgs` struct to include a timeout option, then configured the RPC provider to apply this timeout using `.with_timeout`. This allows RPC calls to handle longer requests, with a default of 45 seconds but customizable as needed. Finally, we tested to ensure both default and custom timeouts work smoothly.

**Comment by Deepak2623** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/foundry).

### My background and how it can be leveraged
I have over 3 years of experience working as a backend developer, with a focus on blockchain development, including smart contract deployment, debugging, and optimization. My experience spans various blockchain tools and frameworks, including Hardhat, Dojo, and recently Foundry. I am well-versed in interacting with RPC endpoints, particularly in optimizing request-response times and handling timeouts for decentralized applications. This background equips me with the necessary skills to identify performance bottlenecks in RPC calls and implement scalable solutions

### How I plan on tackling this issue
Review the Existing Timeout Configuration in Foundry: The first step would involve analyzing how the current timeout is set up in the Foundry framework. Specifically, I would look into the constants.rs file to understand the default timeout behavior for RPC calls. Understanding this baseline will help identify how it affects slower or experimental endpoints like witness endpoints.

Introduce a Timeout Option: I would extend the cast tool to allow users to specify a custom timeout for RPC requests via a command-line option. This would give developers the flexibility to adjust the timeout based on the nature of the endpoints they are working with. For slower endpoints like witness, this option would prevent premature timeouts by allowing users to configure a longer waiting period.

This option would be added to the appropriate location in rpc.rs to allow it to be passed during RPC calls.
Modify the RPC Builder: I would modify the existing RPC builder logic in rpc.rs to use the new timeout option. By integrating this option directly into the RPC construction process, it ensures that every request made to an endpoint considers the user-defined timeout, improving the robustness of the interactions.

Testing the Solution: After implementing the timeout option, I would conduct extensive testing to ensure its efficacy. This would include:

Testing with endpoints that require longer response times, such as witness endpoints.
Checking edge cases, such as invalid or extremely long/short timeout values.
Ensuring that the default behavior remains intact if no custom timeout is specified.

**Comment by alejandro-ll** [comment]
I plan to implement the `--timeout` option for the cast rpc command, allowing users to specify a custom timeout for RPC requests. Here's how I'll approach it:

> - I will add the --timeout option to the RpcArgs struct in rpc.rs, so users can pass a custom timeout value from the command line.
> - I'll modify the run function to use this timeout value when creating the RPC provider. If no timeout is provided, the default of 45 seconds will be used.
> - In utils.rs, I'll either modify or create a new version of the get_provider function to handle the custom timeout.
> - I'll run local tests to ensure the timeout works as expected. This includes testing with both the default timeout and custom values to ensure proper functionality.
> - Finally, I'll update the documentation with examples demonstrating how to use the --timeout option, ensuring it's easy for users to understand.

**Comment by PanGan21** [comment]
Hi! Opened a pr for this in #9044 ! Let me know please if it resolves the issue 🙂

**Comment by alejandro-ll** [comment]
Hello! I was waiting for confirmation to start knowing if there are other guys working on it 😁, let me know

**Comment by grandizzy** [comment]
completed in https://github.com/foundry-rs/foundry/pull/9044
