### ISSUE TITLE
bug(`forge test`) invariant test is failing with revert, but trace and logs show a successful execution

### ISSUE THREAD

**Issue by dglowinski** [foundry-rs/foundry#8971]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9dbfb2f 2024-09-27T00:21:07.231678000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

The bug manifests itself in one of the invariant tests of the [Euler Vault Kit](https://github.com/euler-xyz/euler-vault-kit)

The test is failing with `Reentrancy` error, but the traces and logs don't match the error, they are showing a successful run in fact. The code has been heavily audited and to the best of our knowledge the invariant should never hit the reentrancy error, so this behaviour is concerning. 

We suspect the issue is related to `--gas-report` flag. The error doesn't always show up, it depends on the fuzzer seed, but after many tries we have not been able to reproduce it without the gas report flag.

Platforms confirmed: Apple M3, Linux, Github CI

Steps to reproduce:
```bash
git clone https://github.com/euler-xyz/euler-vault-kit && cd euler-vault-kit
git checkout debug-fuzzer
forge install
forge test --mt invariant_totalAssetsShouldBeEqualToBalanceAfterSMEAR --gas-report -vvv
```

The test fails with re-entrancy error, but the logs and trace show a successful run, which is obviously a bug.

The test [here](https://github.com/euler-xyz/euler-vault-kit/blob/dbb31bbbbea01a6fa5cf6fcb7840fca11bf2bfe8/test/unit/esr/ESR.Fuzz.t.sol#L16)

The error reported is a reentrancy on `EulerSavigsRate` contract [here](https://github.com/euler-xyz/euler-vault-kit/blob/dbb31bbbbea01a6fa5cf6fcb7840fca11bf2bfe8/src/Synths/EulerSavingsRate.sol#L54) (note `console.log`s in preceding lines)

We have determined the call is coming from the invariant test itself: [here](https://github.com/euler-xyz/euler-vault-kit/blob/dbb31bbbbea01a6fa5cf6fcb7840fca11bf2bfe8/test/unit/esr/ESR.Fuzz.t.sol#L23)

In the trace the execution is successfull:
```
    ├─ [114647] EulerSavingsRate::deposit(10000000 [1e7], user: [0x6CA6d1e2D5347Bfab1d91e883F1915560e09129D])
    │   ├─ [0] console::log("nonReentrant START, msg.data:") [staticcall]
    │   │   └─ ← [Stop]
    │   ├─ [0] console::log(0x6e553f6500000000000000000000000000000000000000000000000000000000009896800000000000000000000000006ca6d1e2d5347bfab1d91e883f1915560e09129d) [staticcall]
    │   │   └─ ← [Stop]
    │   ├─ [0] console::log("  re-entrancy locked flag", 1) [staticcall]
    │   │   └─ ← [Stop]
    │   ├─ [18361] MockToken::transferFrom(user: [0x6CA6d1e2D5347Bfab1d91e883F1915560e09129D], EulerSavingsRate: [0xF62849F9A0B5Bf2913b396098F7c7019b51A820a], 10000000 [1e7])
    │   │   ├─ emit Transfer(from: user: [0x6CA6d1e2D5347Bfab1d91e883F1915560e09129D], to: EulerSavingsRate: [0xF62849F9A0B5Bf2913b396098F7c7019b51A820a], value: 10000000 [1e7])
    │   │   └─ ← [Return] true
    │   ├─ emit Transfer(from: 0x0000000000000000000000000000000000000000, to: user: [0x6CA6d1e2D5347Bfab1d91e883F1915560e09129D], value: 10000000 [1e7])
    │   ├─ emit Deposit(sender: user: [0x6CA6d1e2D5347Bfab1d91e883F1915560e09129D], owner: user: [0x6CA6d1e2D5347Bfab1d91e883F1915560e09129D], assets: 10000000 [1e7], shares: 10000000 [1e7])
    │   └─ ← [Return] 10000000 [1e7]
```

None of the calls in the sequence preceding the invariant check touch the reentrancy modifier.

To reiterate: we have not been able to reproduce the issue when `--gas-report` is removed, and we don't think this particular solidity error could be triggered by this particular invariant test.

**Comment by grandizzy** [comment]
indeed, when running tests with `--gas-report` flag tests are performed in isolation mode, in order to have better gas accounting (which means that all top-level calls are executed as a separate transaction). This could affect behavior of `invariant_totalAssetsShouldBeEqualToBalanceAfterSMEAR` call comparing to non gas report run (because it is basically sending multiple txes there - deposit/min/gulp). In general changing state in `invariant_` functions should be avoided and only current fuzzed state should be asserted.

**Comment by grandizzy** [comment]
confirmed this is a `--gas-report` / `--isolate` related bug (state wrongly committed)

**Comment by hoytech** [comment]
@grandizzy - Thanks for the info, we appreciate you looking into it!
