### ISSUE TITLE
Extra output `evm.legacyAssembly` is ignored

### ISSUE THREAD

**Issue by RaoulSchaffranek** [foundry-rs/foundry#8977]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9dbfb2f 2024-09-27T00:20:26.127318148Z)

### What command(s) is the bug in?

forge build

### Operating System

Linux

### Describe the bug

Compiling with the extra output option `evm.legacyAssembly` has no effect. Unfortunately, this breaks the only reliable way to get the metadata hash of the contracts - which are needed for source code verification and source mapping (see: https://docs.sourcify.dev/blog/finding-auxdatas-in-bytecode/#workarounds for more details).

Reproduction steps:

```
forge init
FOUNDRY_EXTRA_OUTPUT = '["evm.legacyAssembly", "storageLayout"]' forge build --build-info
```

The `storageLayout` is not required and is only added as a sanity check here.

Open the build info file. Notice, that `evm.legacyAssembly` is missing in the output selection and the `legacyAssembly`-field is missing from `output[source][contract].evm`:

<pre>
{
    "input": {
        "settings": {
            "ouptputSelection": {
                "lib/forge-std/src/Base.sol": {
                    "*": [
                        "abi",
                        "evm.bytecode",
                        "evm.deployedBytecode",
                        "evm.methodIdentifiers",
                        "metadata",
                        "storageLayout"
                        <b>// "evm.legacyAssembly" is missing here</b>
                    ]
                }
            }
        }
    },
    "output": {
        "contracts":
            "lib/forge-std/src/Base.sol": {
                "Script": {
                    "evm": {
                         <b>// "legacyAssembly": { ... } is missing here</b>
                    }
                }
            }
        }
    }       
}
</pre>

**Comment by grandizzy** [comment]
Hey @RaoulSchaffranek I dont think that can be set with env var (see https://book.getfoundry.sh/reference/config/solidity-compiler#extra_output where env is N/A) could you try adding it in foundry.toml?

**Comment by RaoulSchaffranek** [comment]
The environment variable `FOUNDRY_EXTRA_OUTPUT` generally works; otherwise, the `storageLayout` would also be missing from the `outputSelection`. I just double-checked and tried setting `extra_output = ["storageLayout", "evm.legacyAssembly"]` in `foundry.toml` - the behavior is the same as with the env var: `storageLayout` yay, `evm.legacyAssembly` nay.
