### ISSUE TITLE
Execute chisel command got a not supported solc

### ISSUE THREAD

**Issue by clarkwtc** [foundry-rs/foundry#8978]
### Component

Chisel

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (25f24e67 2024-09-28T12:38:07.736963000Z)

### Operating System

Windows

### Describe the bug

$ chisel
Error:
The set evm version, paris, is not supported by solc 0.8.17. Upgrade to a newer solc version.

I ran chisel command, but I got a not supported error.
I have already tried different setups and got the same result.

**Comment by zerosnacks** [comment]
Possibly related: https://github.com/foundry-rs/foundry/issues/8614
