### ISSUE TITLE
chore(`forge init`): upgrade Solidity version to `^0.8.26`

### ISSUE THREAD

**Issue by xyizko** [foundry-rs/foundry#8984]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (25f24e6 2024-09-29T00:23:48.950996240Z)

### Operating System

Linux

### Describe the bug

# Description 

1. When running [`slither`](https://github.com/crytic/slither) it reports the following 

```ml 
forge clean' running (wd: /workspace/xo-e-slither/REPORT/r1/c1)
'forge config --json' running
'forge build --build-info --skip */test/** */script/** --force' running (wd: /workspace/xo-e-slither/REPORT/r1/c1)
INFO:Detectors:
Version constraint ^0.8.13 contains known severe issues (https://solidity.readthedocs.io/en/latest/bugs.html)
        - VerbatimInvalidDeduplication
        - FullInlinerNonExpressionSplitArgumentEvaluationOrder
        - MissingSideEffectsOnSelectorAccess
        - StorageWriteRemovalBeforeConditionalTermination
        - AbiReencodingHeadOverflowWithStaticArrayCleanup
        - DirtyBytesArrayToStorage
        - InlineAssemblyMemorySideEffects
        - DataLocationChangeInInternalOverride
        - NestedCalldataArrayAbiReencodingSizeValidation.
It is used by:
        - ^0.8.13 (src/Counter.sol#2)
Reference: https://github.com/crytic/slither/wiki/Detector-Documentation#incorrect-versions-of-solidity
INFO:Slither:. analyzed (1 contracts with 93 detectors), 1 result(s) found

```

Slither version - `0.10.4`

# Impact 

1. The detectors state conflicting information 

# FIx 

1. Could just update the default contracts [`HERE`](https://github.com/foundry-rs/foundry/tree/master/crates/forge/assets)
2. Havent made a PR with the changes, since uncertain if the older versions of Solidity are on purpose chosen to avoid some issu e I am unaware of

## Process Screen Shot 

![Screenshot from 2024-09-29 09-56-46](https://github.com/user-attachments/assets/a3e52c80-7843-4007-aee2-b8b6944d9cbe)

**Comment by zerosnacks** [comment]
Hi @xyizko thanks for the report. I agree that the default template should point users towards a recent version without known bugs.

Do you know what version Slither recommends?

Related: https://github.com/foundry-rs/foundry/issues/8614

**Comment by zerosnacks** [comment]
Thinking about it again, we use `^0.8.13` as it is the lowest compatible version that doesn't run into stack-to-deep issues easily. 

We want to maintain as much backwards compatibility and I would therefore be in favor of sticking to `^0.8.13` for the time being.

It is generally recommended by auditors that users either pin their version in `foundry.toml` (and keep the pragma floating for compatibility) or pin the pragma in the files.

Marking as `not planned`

**Comment by xyizko** [comment]
SGTM

Seems to be a ongoing [issue](https://github.com/ethereum/solidity/issues?q=is%3Aissue+is%3Aopen+stack+to+deep).
