### ISSUE TITLE
bug: `--decode-internal` (and related flags `--flamechart` / `--flamegraph`) only work when optimizer is explicitly turned off

### ISSUE THREAD

**Issue by akshatmittal** [foundry-rs/foundry#8986]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9a0f66e 2024-09-26T00:22:17.831423400Z)

### Operating System

None

### Describe the bug

Any commands that utilizes `--decode-internal` (including `--flamechart` and `--flamegraph`) fail with `failed to parse source map: no previous offset` if optimizer isn't explicitly turned off.

The command should either throw a more descriptive error asking to disable optimizer or disable it automatically when running the command.

**Comment by zerosnacks** [comment]
Hi @akshatmittal thanks for your report

Would you be able to provide a minimal reproduction that throws `failed to parse source map: no previous offset` or point to a code snippet that does?

It will help us greatly narrow down the issue

**Comment by akshatmittal** [comment]
@zerosnacks Sure, here you go: https://github.com/uniswapfoundation/v4-template (I am working on a different codebase, but this starter repo has the same error)

`forge test --decode-internal -vvvvv` will throw the error I mentioned. (Narrowing to a single test doesn't change the outcome, but here you go anyway `forge test --decode-internal --match-test testCounterHooks -vvvvv`) Adding `optimizer = false` to config does work correctly.

**Comment by DaniPopes** [comment]
cc @klkvr
