### ISSUE TITLE
bug(`cheatcodes`): `vm.broadcastRawTransaction` failing for deployments, missing `to` field

### ISSUE THREAD

**Issue by ScreamingHawk** [foundry-rs/foundry#8993]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (3ff3d05 2024-10-01T00:25:45.808130533Z)

### What command(s) is the bug in?

forge script

### Operating System

Linux

### Describe the bug

When trying to deploy a pre-signed transaction via a script I'm getting an error: `No ``to`` field found`

```
...
├─ [0] VM::broadcastRawTransaction(0xf8a58085174876e800830186a08080b853604580600e600039806000f350fe7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe03601600081602082378035828234f58015156039578182fd5b8082525050506014600cf31ba02222222222222222222222222222222222222222222222222222222222222222a02222222222222222222222222222222222222222222222222222222222222222)
    │   └─ ← [Revert] vm.broadcastRawTransaction: transact_from_tx: No `to` field found
```

The above example is using the same value as specified in foundry tests here. https://github.com/foundry-rs/foundry/blob/master/testdata/default/cheats/BroadcastRawTransaction.t.sol#L342.

**Comment by grandizzy** [comment]
hey @ScreamingHawk could you please share the code or a minimal repro for this issue, would help for figuring out where the problem is. thank you!

**Comment by ScreamingHawk** [comment]
Thanks @grandizzy
Here's a minimum reproducible example:

https://github.com/ScreamingHawk/mre-forge-broadcastrawtransaction

**Comment by grandizzy** [comment]
thank you! yes, indeed that tx is missing the `to` field
```bash
cast dt 0xf8a58085174876e800830186a08080b853604580600e600039806000f350fe7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe03601600081602082378035828234f58015156039578182fd5b8082525050506014600cf31ba02222222222222222222222222222222222222222222222222222222222222222a02222222222222222222222222222222222222222222222222222222222222222
{
  "type": "0x0",
  "nonce": "0x0",
  "gasPrice": "0x174876e800",
  "gasLimit": "0x186a0",
  "value": "0x0",
  "input": "0x604580600e600039806000f350fe7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe03601600081602082378035828234f58015156039578182fd5b8082525050506014600cf3",
  "r": "0x2222222222222222222222222222222222222222222222222222222222222222",
  "s": "0x2222222222222222222222222222222222222222222222222222222222222222",
  "v": "0x1b",
  "hash": "0xeddf9e61fb9d8f5111840daef55e5fde0041f5702856532cdbb5a02998033d26"
}
```
as per https://github.com/foundry-rs/foundry/pull/4931#issuecomment-1546652889 seems this is a create tx, try encoding with to as 0x address

There are other samples that should work (or you could create your own raw tx), e.g.
```bash
cast dt 0xf869808502540be40083030d4094f39fd6e51aad88f6f4ce6ab8827279cfffb922668204d28082f4f6a061ce3c0f4280cb79c1eb0060a9a491cca1ba48ed32f141e3421ccb60c9dbe444a07fcd35cbec5f81427ac20f60484f4da9d00f59652f5053cd13ee90b992e94ab3
{
  "type": "0x0",
  "chainId": "0x7a69",
  "nonce": "0x0",
  "gasPrice": "0x2540be400",
  "gasLimit": "0x30d40",
  "to": "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266",
  "value": "0x4d2",
  "input": "0x",
  "r": "0x61ce3c0f4280cb79c1eb0060a9a491cca1ba48ed32f141e3421ccb60c9dbe444",
  "s": "0x7fcd35cbec5f81427ac20f60484f4da9d00f59652f5053cd13ee90b992e94ab3",
  "v": "0xf4f6",
  "hash": "0xd25911fa4ea892d775652a4417b11530d33cea00537fb0607756c6afab872c2c"
}
```

**Comment by ScreamingHawk** [comment]
Thanks @grandizzy 

Unfortunately since I'm hoping to use this for presigned transactions I am unable to re-encode as it will change the deployment address. See https://eips.ethereum.org/EIPS/eip-2470#deployment-transaction

As the transaction is valid and can be submitted on chain I believe this is a bug in forge scripts.
