### ISSUE TITLE
bug(`docs`): keystore path as a folder

### ISSUE THREAD

**Issue by henry-hz** [foundry-rs/foundry#9001]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (3ff3d05 2024-10-01T00:25:45.808130533Z)

### What command(s) is the bug in?

cast send

### Operating System

Linux

### Describe the bug

When using `cast send` with the `--keystore` path, cast command complains that we need to specify the file, while in the docs, we can specify the folder. In fact, the folder is much more better, as in dapp tools.

```
❯ cast send 0x... 'transfer(address,uint256)' 0x... 0x... --keystore ~/user/secrets
Error: 
Keystore path `"/home/user/secrets"` is a directory. Please specify the keystore file directly.
```

but the docs permits using a folder as a path:
```
--keystore path
    Use the keystore in the given folder or file.
    Environment: ETH_KEYSTORE
```

**Comment by zerosnacks** [comment]
Thanks @henry-hz for your report, I've updated the documentation to reflect that you are required to specify the filename.

**Comment by henry-hz** [comment]
Thanks @zerosnacks , in fact it would be great if `cast` could support also a file path as in dapp.tools seth supports
