### ISSUE TITLE
Functions "tstore" and "tload" not found (Solc 0.8.24)

### ISSUE THREAD

**Issue by trashpirate** [foundry-rs/foundry#9009]
I tried to use the latest Openzeppelin contracts library (v5.1) which uses now solidity version 0.8.24 instead of 0.8.20 (v5.0). When trying to compile I got multiple errors like the following:

```
Error (4619): Function "tstore" not found.
   --> lib/openzeppelin-contracts/contracts/utils/StorageSlot.sol:254:13:
    |
254 |             tstore(slot, value)
    |             ^^^^^^
   
```

```
Error (4619): Function "tload" not found.
   --> lib/openzeppelin-contracts/contracts/utils/StorageSlot.sol:263:22:
    |
263 |             value := tload(slot)
    |                      ^^^^^
```

These errors were all related to one single file `lib/openzeppelin-contracts/contracts/utils/StorageSlot.sol`

Using the earlier Openzeppelin version (release v5.0) did resolve the issue immediately without any code changes.

While I can live with v5.0, I just wanted to make aware of the issue as I have not found any solutions for v5.1 yet.

Foundry version: forge 0.2.0 (3ff3d05 2024-10-02T00:21:17.360903483Z)

**Comment by DaniPopes** [comment]
You need to use `evm_version = "cancun"`

**Comment by yellowBirdy** [comment]
Does not work
```
[profile.default]
solc = '0.8.24'
emv_version = 'cancun'
optimizer = true
optimizer_runs = 200
```

**Comment by trashpirate** [comment]
Also, Remix is able to compile with EVM version "paris" using Solidity 0.8.24 and the newest Openzeppelin contracts.
