### ISSUE TITLE
Load state returns incorrect latest block height

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#9017]
Looks like this goes a bit deeper. If you save a state and it ends on like block 8 for example, when you restart the node, it'll say the block number is 0, causing issues with making RPC calls.

```bash
anvil --dump-state state.json -b 10

# wait 20 seconds for 2 blocks to go, then kill it
```

Then, restart:

```
anvil --load-state state.json
```

And then call the latest block:

```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest", false],"id":1}' http://localhost:8545
```

And you'll see the starting number is `0x0`, which is incorrect.

_Originally posted by @PatrickAlphaC in https://github.com/foundry-rs/foundry/issues/8962#issuecomment-2391648849_

**Comment by grandizzy** [comment]
afaik the block to restore from dump is `best_block_number` which I see is properly persisted

**Comment by PatrickAlphaC** [comment]
More context:

`eth_blockNumber` looks like it works correctly, returning the latest block:

```
curl http://127.0.0.1:8545 -X POST -H "Content-Type: application/json"  --data '{"method":"eth_blockNumber","params":[],"id":1,"jsonrpc":"2.0"}'
```

`eth_getBlockByNumber` with parameters `"params":["latest", false],` fails:

```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest", false],"id":1}' http://localhost:8545
```

It returns 0, and then after the next block is mined, it starts returning the correct block.

**Comment by PatrickAlphaC** [comment]
Reproduce steps:

1. Start an anvil node, and wait 20 seconds for 2 blocks to mine

```bash
anvil --dump-state state.json -b 10
# let 2 blocks mine, and then kill it
```

2. Restart the node

```
anvil --load-state state.json
```

3. Compare the calls:


`eth_blockNumber` looks like it works correctly, returning the latest block:

```
curl http://127.0.0.1:8545 -X POST -H "Content-Type: application/json"  --data '{"method":"eth_blockNumber","params":[],"id":1,"jsonrpc":"2.0"}'
```

`eth_getBlockByNumber` with parameters `"params":["latest", false],` fails:

```
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["latest", false],"id":1}' http://localhost:8545
```

It returns 0, and then after the next block is mined, it starts returning the correct block.

**Comment by mattsse** [comment]
interesting this could indeed be related to #8926

**Comment by yash-atreya** [comment]
@PatrickAlphaC @mattsse 

Fix is up #9021

**Comment by PatrickAlphaC** [comment]
so fast!

**Comment by PatrickAlphaC** [comment]
It works great! Ty!
