### ISSUE TITLE
feat(`debug`): add watch variable to `forge debug`

### ISSUE THREAD

**Issue by 1m1-github** [foundry-rs/foundry#9025]
### Component

Forge

### Describe the feature you would like

watch the value of chosen variables, for example in another subwindow

**Comment by zerosnacks** [comment]
Hi @1m1-github could you expand on this more? Do you mean a `--watch` flag to reload the source upon change or do you mean the showing of variables in scope during debugging: https://github.com/foundry-rs/foundry/issues/410?

**Comment by zerosnacks** [comment]
Assuming it is the latter, marking as duplicate in favor of https://github.com/foundry-rs/foundry/issues/410

Please re-open or leave a comment if I'm incorrect
