### ISSUE TITLE
fuzz test with single bool input is 50x slower vs two non fuzz with functions

### ISSUE THREAD

**Issue by 1m1-github** [foundry-rs/foundry#9026]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (471e4ac 2024-10-03T00:27:20.819613000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

`function testWithBoolInput(bool x) public {...}`
takes 50x testing time vs running the following two combined:
`function testWithTrueInput() public {bool x=true;...}`
`function testWithFalseInput() public {bool x=false;...}`

maybe because the fuzzer runs over `uints` and converts to `bool`.

the fuzzer should specialize for `bool` input and deliver only 2 values.

**Comment by grandizzy** [comment]
@1m1-github thanks for reporting! The fuzzing test is done according to `fuzz.runs` config (which defaults to 256), therefore `function testWithBoolInput(bool x) public {...}` is actually called 256 times compared to only 2 calls when calling `testWithTrueInput()` + `testWithFalseInput` combined, see https://book.getfoundry.sh/reference/config/testing?fuzz#runs

Please reopen the issue if you see other perf improvements that could be done in the area. Thank you!

**Comment by 1m1-github** [comment]
my point is that a `bool` input variable should run at most twice no matter what `fuzz.runs` says

**Comment by grandizzy** [comment]
> @grandizzy my point is that a `bool` input variable should run at most twice no matter what `fuzz.runs` says

yeah, but that's better suitable for a unit test.
For fuzz tests IMO this is still valuable as the test itself could generate random values by using cheatcodes, e.g.
```Solidity
    function test_fuzzWithBoolInput(bool callAFirst) public {
        uint256 x = vm.randomUint();
        if (callAFirst) {
            target.a(x);
            target.b(x);
        } else {
            target.b(x);
            target.a(x);
        }
    }
```
