### ISSUE TITLE
feat(cast): add flag equivalents of `parseUnits`, `formatUnits`

### ISSUE THREAD

**Issue by 0xdapper** [foundry-rs/foundry#9030]
### Component

Cast

### Describe the feature you would like

`cast --from-wei <wei>` is equivalent to `parseEther`
`cast --to-wei <ether>` is equivalent to `formatEther`

However, `cast --to-unit` is not equivalents of the more generic `parseUnits`. It only supports parsing to `wei, gwei, ether`, not to arbitrary decimals. 

I couldn't find a `cast --from-unit` altogether.

This feature request is to add functionality to parse and format numbers to arbitrary decimals.

**Comment by kien6034** [comment]
hello, i would like to work on this

**Comment by zerosnacks** [comment]
@kien6034 thanks! assigned

**Comment by kien6034** [comment]
thank you
