### ISSUE TITLE
bug: `evm_setNextBlockTimestamp` with too large timestamp makes anvil crash

### ISSUE THREAD

**Issue by Rubilmax** [foundry-rs/foundry#9031]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e10ab3d 2024-10-04T00:21:35.392700542Z)

### What command(s) is the bug in?

anvil

### Operating System

Linux

### Describe the bug

`evm_setNextBlockTimestamp` with a timestamp like `317071597274n` makes anvil crash with:

```
thread 'tokio-runtime-worker' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/chrono-0.4.38/src/datetime/mod.rs:626:14:
writing rfc2822 datetime to string should never fail: Error
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

as soon as a new block is mined

I would expect anvil to throw an error to the `evm_setNextBlockTimestamp` request

**Comment by mattsse** [comment]
317071597274n isn't a valid number

what's the value?
