### ISSUE TITLE
bug(`anvil`): `eth_gasPrice` returns `1000000000` on an `anvil` instance with `--gas-price 0 --block-base-fee-per-gas 0`

### ISSUE THREAD

**Issue by Rubilmax** [foundry-rs/foundry#9033]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e10ab3d 2024-10-04T00:21:35.392700542Z)

### What command(s) is the bug in?

anvil

### Operating System

None

### Describe the bug

Calling `cast gas-price` on an `anvil --gas-price 0 --block-base-fee-per-gas 0` returns `1000000000` instead of `0`

**Comment by mattsse** [comment]
@zerosnacks 

I think it could be setup related, because this should eventually land here

https://github.com/foundry-rs/foundry/blob/d3ce9f08294bf3e78d0d3167f9b4a4669e262600/crates/anvil/src/eth/fees.rs#L102-L102

and I guess we don't respect the gasprice/basefee fields properly

also I think those two arguments should perhaps be mutually exclusive?

**Comment by zerosnacks** [comment]
Able to reproduce with given setup, looking into this

**Comment by zerosnacks** [comment]
This is related to this PR https://github.com/foundry-rs/foundry/pull/8081 enforcing a `MIN_SUGGESTED_PRIORITY_FEE` that introduced a minimum fee of `1e9`

https://github.com/foundry-rs/foundry/blob/eb046653de4047a27b181394338732e597965257/crates/anvil/src/eth/api.rs#L595 

Should we add a special case here to disable this when the block base fee is explicitly set to 0? @mattsse

**Comment by Rubilmax** [comment]
For context: it is interesting to have gas price / block base fee per gas 0 in tests to avoid having to fund impersonated addresses with ETH

**Comment by zerosnacks** [comment]
Added `--disable-min-priority-fee` as an Anvil flag to disable the enforcement of the minimum suggested priority fee here: https://github.com/foundry-rs/foundry/pull/9049
