### ISSUE TITLE
Add ability to fork partial block for Anvil + Forge

### ISSUE THREAD

**Issue by nakedkoalacapital** [foundry-rs/foundry#9059]
### Component

Anvil

### Describe the feature you would like

A common usecase in my workflow is that I need to fork partial block. (ie: fork block T and then replay the first N transaction at block T + 1.  This is to setup the environment for subsequent testing and simulation in test cases or script)

Now the replay solution I implemented is very rudimentary. I basically just copy the data of top N transaction and write code to apply them on top of block T

**Comment by grandizzy** [comment]
@nakedkoalacapital that's already possible in forge by using `createSelectFork` cheatcode and providing tx hash, see https://book.getfoundry.sh/cheatcodes/create-select-fork#description and in anvil by starting it with `--fork-transaction-hash <TRANSACTION>` flag, see https://book.getfoundry.sh/reference/anvil/#evm-options

Please use these option and open issues if you hit any problem with. Thank you!
