### ISSUE TITLE
forge throws core dump when encountering long string literal

### ISSUE THREAD

**Issue by nakedkoalacapital** [foundry-rs/foundry#9060]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (d7eac74 2024-06-21T00:16:53.812858792Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

I have to simulate a historic transaction.

I hardcode its calldata in string literal  `hex"long calldata......."`

forge build throws

```
Error: 
solc exited with signal: 11 (SIGSEGV) (core dumped)
<empty output>
```

LLM suggested this tweak in `foundry.toml`

```
[profile.default]
solc_args = ['--memory-limit', '16384']
```
but it didn't work.

I am not sure if this is intended or a bug and I am not sure if this originates from forge or underlying solc.

**Comment by grandizzy** [comment]
Most likely solc related https://github.com/ethereum/solidity/issues/13496 so not much we can do about.

The hex string is too long, try maybe loading it through a binary file rather than hard coding it.
