### ISSUE TITLE
bug: `vm.expectRevert` does not see low level call reverts as it should

### ISSUE THREAD

**Issue by meetmangukiya** [foundry-rs/foundry#9061]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e215f3f 2024-10-08T00:25:05.208317000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

```solidity

contract ExpectRevertTest is Test {
    error A();
    error B();

    function revertA() external {
        revert A();
    }

    function revertB() external {
        revert B();
    }

    function doesNotRevert() external {

    }

    function test_should_fail_1() external {
        vm.expectRevert(A.selector);
        // this call doesnt revert, should fail because we were expecting a revert with A.selector data
        address(this).call(abi.encodeCall(this.doesNotRevert, ()));
    }

    function test_should_fail_2() external {
        vm.expectRevert(A.selector);
        // this call reverts, but should still fail because revert data is B.selector instead of A.selector
        address(this).call(abi.encodeCall(this.revertB, ()));
    }

    function test_should_fail_3() external {
        vm.expectRevert(abi.encodePacked(A.selector));
        // this call reverts, but should still fail because revert data is B.selector instead of A.selector
        address(this).call(abi.encodeCall(this.revertB, ()));
    }
}
```

All of these should fail, but none of them do. `test_should_fail_1()` is a particularly surprising one, `test_should_fail_2()` and `test_should_fail_3()` seems like a bug where it is not matching the revert data as it should? Maybe related to #7238.

Behaviour as expected from the docs:
```solidity
    /// Expects an error on next call with any revert data.
    function expectRevert() external;

    /// Expects an error on next call that starts with the revert data.
    function expectRevert(bytes4 revertData) external;

    /// Expects an error on next call that exactly matches the revert data.
    function expectRevert(bytes calldata revertData) external;
```

vs the actual behaviour below 

```
[PASS] test_should_fail_1() (gas: 3803)
Traces:
  [3803] ExpectRevertTest::test_should_fail_1()
    ├─ [0] VM::expectRevert(custom error 0xc31eb0e0: f446c1d000000000000000000000000000000000000000000000000000000000)
    │   └─ ← [Return] 
    ├─ [209] ExpectRevertTest::doesNotRevert()
    │   └─ ← [Stop] 
    └─ ← [Stop] 

[PASS] test_should_fail_2() (gas: 3846)
Traces:
  [3846] ExpectRevertTest::test_should_fail_2()
    ├─ [0] VM::expectRevert(custom error 0xc31eb0e0: f446c1d000000000000000000000000000000000000000000000000000000000)
    │   └─ ← [Return] 
    ├─ [230] ExpectRevertTest::revertB()
    │   └─ ← [Revert] B()
    └─ ← [Stop] 

[PASS] test_should_fail_3() (gas: 4232)
Traces:
  [4232] ExpectRevertTest::test_should_fail_3()
    ├─ [0] VM::expectRevert(custom error 0xf28dceb3: 00000000000000000000000000000000…00000000000000000000000000000000 (96 bytes))
    │   └─ ← [Return] 
    ├─ [230] ExpectRevertTest::revertB()
    │   └─ ← [Revert] B()
    └─ ← [Stop] 

Suite result: ok. 3 passed; 0 failed; 0 skipped; finished in 7.98ms (5.99ms CPU time)
```

**Comment by grandizzy** [comment]
@meetmangukiya the problem with this scenario is that is using `call` which doesn't bubble up reverts. How `expectRevert` cheatcode works is that on the call expected to revert it sets the revert result and reason of failing

https://github.com/foundry-rs/foundry/blob/e215f3fdeada259a8886a7611151794d280ca298/crates/cheatcodes/src/inspector.rs#L1281-L1284

so in this case that's set on `call`. Since it doesn't bubble up reverts they won't be shown, still they're properly identified, for example, for the first test that doesn't seem to revert, if you write it as

```Solidity
    function test_should_fail_1() external {
        vm.expectRevert(A.selector);
        (bool success, bytes memory data) = address(this).call(
            abi.encodeCall(this.doesNotRevert, ())
        );
        console.log(success);
        console.log(vm.toString(data));
    }
```
will show the failure and reason of revert
```
Logs:
  false
  0xeeaa9e6f000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000246e6578742063616c6c20646964206e6f742072657665727420617320657870656374656400000000000000000000000000000000000000000000000000000000
```
if you remove the `vm.expectRevert(A.selector);` it will pass
```
Logs:
  true
  0x
```
I am not sure we should try any change here since `call` is not recommend to call existing functions (but for sending Ether via calling the fallback function) so better to call functions directly. CC @klkvr @DaniPopes @mds1 for thoughts

**Comment by meetmangukiya** [comment]
I personally think it should treat any `CALL` the same, whether it be called via an interface or via `address(..).call` or via assembly. 

I don't understand why the console.logs are necessary for this to be caught? 
```
    function test_should_fail_1() external {
        vm.expectRevert(A.selector);
        (bool success, bytes memory data) = address(this).call(
            abi.encodeCall(this.doesNotRevert, ())
        );
        console.log(success);
        console.log(vm.toString(data));
    }
```

**Comment by grandizzy** [comment]
> I don't understand why the console.logs are necessary for this to be caught?
> 
They're not necessary but just wanted to point out that the call actually reverts with message and not showing up in test because `call` doesn't bubble up reverts to test level. I am not sure if #7238 is for the same but definitely worth discussing it.

**Comment by meetmangukiya** [comment]
Ah you were demonstrating how foundry patches the results mid-test execution. I was confused by the output from console.log vs what I get in trace. But I understand it now. It's an implementation detail.

Nonetheless yeah I agree we should discuss this.

**Comment by meetmangukiya** [comment]
Using this workaround for now:
```solidity
    function _expectRevert(bytes4 selector, address target, bytes memory cd) internal {
        vm.expectRevert(selector);
        (bool success, bytes memory ret) = address(target).call(cd);
        if (!success) {
            assembly ("memory-safe") {
                revert(add(ret, 0x20), returndatasize())
            }
        }
    }
```

**Comment by grandizzy** [comment]
> Using this workaround for now:
> 
 neat! at min I think we should have such utilities (e.g. like `expectCallRevert`) in forge-std and well documented in book

**Comment by mds1** [comment]
The usage of `expectRevert` with low level calls is already documented in the book in the "Gotcha: Usage with low-level calls" box: https://book.getfoundry.sh/cheatcodes/expect-revert

**Comment by grandizzy** [comment]
> The usage of `expectRevert` with low level calls is already documented in the book in the "Gotcha: Usage with low-level calls" box: https://book.getfoundry.sh/cheatcodes/expect-revert

Thanks, missed that! Wdyt about having helpers for such cases in forge-std, would it make sense or should we just add some examples in book on how this can be achieved?

**Comment by grandizzy** [comment]
@meetmangukiya I am going to close this one since behavior is documented in book and we have trackers to improve it, please reopen if disagree. Thank you!
