### ISSUE TITLE
Provide `decoded_logs`  in `forge test --json`

### ISSUE THREAD

**Issue by kyrers** [foundry-rs/foundry#9064]
### Component

Forge

### Describe the feature you would like

It seems `forge test --json` no longer includes the `decoded_logs` as it used to. Only `logs`, such as:

```
"logs":[{
  "address": "0x000000000000000000636F6e736F6c652e6c6f67",
  "topics": [
    "0x41304facd9323d75b11bcdd609cb38effffdb05710f7caf0e9b16c6d9d709f50"
  ],
  "data": "0x00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000012436f6e74726163742073697a653a203133380000000000000000000000000000"
}]
```

### Additional context

According to the discussion in an old issue (#3002), this was feasible and simple. Did anything change? Is this no longer possible because of some technical reason I am not aware of?

**Comment by grandizzy** [comment]
that's likely a regression introduced withhttps://github.com/foundry-rs/foundry/pull/8396 will check and add tests for both json and junit output

**Comment by grandizzy** [comment]
@kyrers that should be fixed in next nightly, mind though that now consistently follows verbosity, so you will need to -v to see logs and decoded logs in json output
