### ISSUE TITLE
feat(`anvil`): allow zero-fee gas transactions

### ISSUE THREAD

**Issue by Rubilmax** [foundry-rs/foundry#9065]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e215f3f 2024-10-08T00:20:05.417359441Z

### What command(s) is the bug in?

anvil

### Operating System

None

### Describe the bug

So this seems to work in most cases, but for some txs the `effectiveGasPrice` is still `1e9`

For example, if I mine this transaction at block 19750000:

```
{
  hash: '0xc46039fbaf6011a62558d917fa188ef936d77efcbb65f64e6736cd120ce64073',
  nonce: 645,
  blockHash: null,
  blockNumber: null,
  transactionIndex: null,
  from: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266',
  to: '0xfd32fA2ca22c76dD6E550706Ad913FC6CE91c75D',
  value: 5000000000000000n,
  gasPrice: 1000000000n,
  gas: 283656n,
  maxFeePerGas: 1000000000n,
  maxPriorityFeePerGas: 1000000000n,
  input: '0x833947fd000000000000000000000000beef01735c132ada46aa9aa4c54623caa92a64cb00000000000000000000000000000000000000000000000000000000000000e0000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb4800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000a0b86991c6218b36c1d19d4a2e9eb0ce3606eb480000000000000000000000007f39c581f595b53c5cb19bd0b3f8da6c935e2ca000000000000000000000000048f7e36eb6b826b2df4b2e630b62cd25e89e40e2000000000000000000000000870ac11d48b15db9a138cf899d20f13f79ba00bc0000000000000000000000000000000000000000000000000bef55718ad60000000000000000000000000000000000000000000000000000000000003b9aca00',
  r: '0xea04f210b997f4731d878c6e462a0895cb3205a9d9d3cd290a861da2e0e98ef0',
  s: '0x5e1f5f2d8bcfaf84f5e6d1e2081aa00d91fd8b763b5a84a2ff59aacd3d88ca02',
  v: 0n,
  yParity: 0,
  chainId: 1,
  accessList: [],
  type: 'eip1559',
  typeHex: '0x2'
}
```

I get the following receipt:

```
{
  transactionHash: '0xc46039fbaf6011a62558d917fa188ef936d77efcbb65f64e6736cd120ce64073',
  transactionIndex: 0,
  blockHash: '0x2e7d591f0c01e60f9a7b49f477ddea1435cc670e3fcccc34883ea1416197320c',
  blockNumber: 19750003n,
  gasUsed: 260807n,
  effectiveGasPrice: 1000000000n,
  blobGasPrice: 1n,
  from: '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266',
  to: '0xfd32fA2ca22c76dD6E550706Ad913FC6CE91c75D',
  contractAddress: null,
  root: '0x0000000000000000000000000000000000000000000000000000000000000000'
}
```

For context: the tx I try to mine is to a payable function `reallocateTo`, with a `value`

**Comment by Rubilmax** [comment]
Followup of https://github.com/foundry-rs/foundry/issues/9033#issuecomment-2399987403

**Comment by zerosnacks** [comment]
Hi @Rubilmax thanks for flagging

Just so I have a better understanding of what you are trying to achieve, am I correct that you are attempting to send a transaction from any private key regardless of it having sufficient funds? If so, wouldn't that mean you would expect the gas related fields to all be 0?

From my initial investigation there seems to be a lot of assumptions on the lowest accepted gas of a valid `EIP-1559` / `EIP-4844` transaction to be 1, not 0.

Would you mind creating a minimum reproduction / documenting the steps?

**Comment by Rubilmax** [comment]
Hi!

> am I correct that you are attempting to send a transaction from any private key regardless of it having sufficient funds?
Indeed!
In a more general manner, I would like to mine txs with a gas price of zero so I don't spend ETH from any address inside my test. This is easier for example when comparing ETH balances before and after the tests: you don't want to have to worry about the gas price failing the test because the ETH balance was decreased a little more (or less) than expected

> If so, wouldn't that mean you would expect the gas related fields to all be 0?
Yes for all gas price related fields, but the gas spent should not be zero

> From my initial investigation there seems to be a lot of assumptions on the lowest accepted gas of a valid EIP-1559 / EIP-4844 transaction to be 1, not 0.
Right. Hardhat allows it in their fork: it seems they disable the checks related to these EIPs

> Would you mind creating a minimum reproduction / documenting the steps?

I think you can spin up a fork: `anvil --gas-price 0 --block-base-fee-per-gas 0 --disable-min-priority-fee --fork-block-number 19750000` from mainnet

Then send the transaction I pasted in this issue and you'll have the receipt I pasted, in which `effectiveGasPrice` is not zero and `blobGasPrice` neither (but this is less of a problem atm)

**Comment by zerosnacks** [comment]
Hey @Rubilmax thanks for your response

I think this is best captured as a feature request / design goal for `reth-anvil` that should be designed holistically rather than a patchy implementation relying on a combination of feature flags and odd behaviors

**Comment by zerosnacks** [comment]
Hi @Rubilmax,

For the time being we've decided to not plan this feature as part of `reth-anvil` due to the complexity involved around the assumptions on the lowest accepted gas of a valid EIP-1559 / EIP-4844 transaction being 1, not 0.

Depending on the use-case it may be possible to use `vm.deal` and ERC20's for accounting purposes or https://book.getfoundry.sh/reference/forge-std/assertApproxEqRel accounting for fixed costs.
