### ISSUE TITLE
security: `createFork` is logging RPC url in traces

### ISSUE THREAD

**Issue by anajuliabit** [foundry-rs/foundry#9069]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (25f24e6 2024-09-30T00:22:05.952969000Z)

### Operating System

macOS (Apple Silicon)

### Describe the bug

`vm.createFork` is logging the RPC URLs. The RPCs should be hidden as they were before because it will expose private RPCs on CI. I believe this should be fixed ASAP, and orgs with public repos should be notified.

**Comment by zerosnacks** [comment]
The recommended way of using RPC urls in your tests is by setting up an alias in `foundry.toml`:

```toml
[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
```

where `MAINNET_RPC_URL` is an environment variable

you then reference this by:

```
vm.createSelectFork("mainnet");
```

and in turn it will display "mainnet" in the traces, not render the RPC URL.

If however you do pass an RPC URL directly it does indeed get rendered inside of the traces, drafting a fix for that here: https://github.com/foundry-rs/foundry/pull/9077 - where if you pass in an RPC URL directly the field gets redacted to `<rpc url>`, similar to how we redact private keys.

**Comment by zerosnacks** [comment]
> > hey @anajuliabit is this re the fact it appears in traces when running tests with `-vvvv` verbosity (or there other places you noticed)? thank you
> 
> I have noticed in forge script with -vv as well

#9077 will do this in all places where you can have log traces e.g. `forge script`, `forge test`, etc..

Example:

```
Traces:
  [98] CounterScript::setUp()
    └─ ← [Stop] 

  [91862] CounterScript::run()
    ├─ [0] VM::envString("MAINNET_RPC_URL") [staticcall]
    │   └─ ← [Return] <env var value>
    ├─ [0] VM::createFork("<rpc url>")
    │   └─ ← [Return] 0
    ├─ [0] VM::startBroadcast()
    │   └─ ← [Return] 
    ├─ [49499] → new Counter@0xA8452Ec99ce0C64f20701dB7dD3abDb607c00496
    │   └─ ← [Return] 247 bytes of code
    ├─ [0] VM::stopBroadcast()
    │   └─ ← [Return] 
    └─ ← [Stop] 


Script ran successfully.
Gas used: 112926
```
