### ISSUE TITLE
bug(`forge script`): `ResponseData` error when verifying smart contract on Mode, but verification succeeds.

### ISSUE THREAD

**Issue by JacobHomanics** [foundry-rs/foundry#9072]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (de596a4 2024-09-06T00:25:03.025680000Z)

### What command(s) is the bug in?

forge script

### Operating System

macOS (Apple Silicon)

### Describe the bug

I try to run this command: `forge script script/VerifyAll.s.sol --ffi --rpc-url https://sepolia.mode.network --verifier-url https://sepolia.explorer.mode.network/api`.

In response, I get the following output: 

```shell
forge script script/VerifyAll.s.sol --ffi --rpc-url https://sepolia.mode.network --verifier-url https://sepolia.explorer.mode.network/api
[⠒] Compiling...
No files changed, compilation skipped
2024-10-09T02:54:08.871697Z ERROR etherscan: Failed to deserialize response: data did not match any variant of untagged enum ResponseData res="{\"message\":\"OK\",\"result\":[{\"Address\":\"0x5b73c5498c1e3b4dba84de0f1833c4a029d90519\"}],\"status\":\"1\"}"
Script ran successfully.
```
<img width="1287" alt="Screenshot 2024-10-08 at 9 57 13 PM" src="https://github.com/user-attachments/assets/9ff76bfa-c986-4514-b307-aff8b6f32054">

The `VerifyAll.s.sol` file is a utility script which can be found here: [VerifyAll.s.sol](https://github.com/scaffold-eth/scaffold-eth-2/blob/foundry/packages/foundry/script/VerifyAll.s.sol). However, I have gutted it in my project to be exactly like so:

```// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

contract VerifyAll {
    function run() external {}
}
```

and I still receive the error.

Not sure if there is a way to fix the error on my end or if its an issue with Foundry itself.

Glad to help any way I can.

Thanks!

**Comment by zerosnacks** [comment]
Hi @JacobHomanics 

Mode uses the Blockscout explorer and it looks like we are receiving back some unhandled response data. You can ignore this error, you deployment and verification should still work without issue.

Make sure you pass in the `--verify` flag and set the `ETHERSCAN_API_KEY` 

I was able to deploy and verify with the command below just now:

```
ETHERSCAN_API_KEY="x" forge script script/<file>.sol --rpc-url https://sepolia.mode.network --verifier-url https://sepolia.explorer.mode.network/api --verify --broadcast --keystore <keystore>
```

For future reference:

```
ERROR etherscan: Failed to deserialize response: data did not match any variant of untagged enum ResponseData res="{\"message\":\"OK\",\"result\":[{\"Address\":\"0x7109709ecfa91a80626ff3989d68f67f5b1dd12d\"}],\"status\":\"1\"}"

WARN traces::etherscan: could not get etherscan info: Serde { error: Error("data did not match any variant of untagged enum ResponseData", line: 0, column: 0), content: "{\"message\":\"OK\",\"result\":[{\"Address\":\"0x7109709ecfa91a80626ff3989d68f67f5b1dd12d\"}],\"status\":\"1\"}" }
```

**Comment by kevtechi** [comment]
Trying to verify with Etherscan and this fails as well. 

Not sure why this is `P-low` if the default verifier does not work anymore.

**Comment by zerosnacks** [comment]
Marking as `resolved` by https://github.com/foundry-rs/foundry/issues/9072#issuecomment-2402097496
