### ISSUE TITLE
solc exited with signal: 9 (SIGKILL)

### ISSUE THREAD

**Issue by cxp-13** [foundry-rs/foundry#9073]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (a17869a 2024-10-09T00:21:58.527050792Z)

### What command(s) is the bug in?

forge build

### Operating System

Linux

### Describe the bug

```
cxp@CXPfromR9000P:~/solana_learn/v2-core$ forge build
[⠆] Compiling...
[⠔] Compiling 197 files with Solc 0.8.26
Error: 
solc exited with signal: 9 (SIGKILL)
<empty output>
```
Oh, I don't know why. Cannot compile anymore.

How did this founder roll back the version and update the latest one, but the compilation keeps reporting insufficient memory. ```cxp@CXPfromR9000P:~/solana_learn/v2-core$ forge -V
forge 0.2.0 (a17869a 2024-10-09T00:21:58.527050792Z)```

When compiling, my memory was almost full. There was no such problem yesterday.
![image](https://github.com/user-attachments/assets/2f5fe868-c7af-41b3-82ec-8293a4216736)

**Comment by zerosnacks** [comment]
Unfortunately this is not something we have control over in Foundry, related: https://github.com/foundry-rs/foundry/issues/8525 + https://github.com/ethereum-optimism/optimism/issues/8646#issuecomment-1863282669

Marking as `non-actionable`
