### ISSUE TITLE
Unexpected OutOfFunds Error during Testing, but Works with Forge Script

### ISSUE THREAD

**Issue by mhxw** [foundry-rs/foundry#9091]
### Component

Forge, Foundryup

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (0ed43ce 2024-10-11T00:20:43.510778000Z)

### What command(s) is the bug in?

`forge fmt && forge clean && forge build && forge test -vvv`

### Operating System

macOS (Apple Silicon)

### Describe the bug

I encountered an unexpected **OutOfFunds** error when running tests for the following contract (only core parts are shown below). However, when deploying and executing the contract using forge script, everything works perfectly, and the assets flow as expected.

Here is a simplified version of the code that led to the issue:

```solidity
// Example core contract code

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.23;

import {IWETH} from "./interfaces/IWETH.sol";
import {Address} from "openzeppelin/utils/Address.sol";
import {console2} from "forge-std/console2.sol";

interface IB{
    event TransferredReserveAsset(
        address indexed sender, address indexed recipient, uint256 amount
    );

    function transferNativeAsset(address to, uint256 amount)
    external;
}

contract B is IB  {
    function transferNativeAsset(address to, uint256 amount)
    external
    onlyAContract
    {
//        function sendValue(address payable recipient, uint256 amount) internal {
//            if (address(this).balance < amount) {
//            revert AddressInsufficientBalance(address(this));
//            }
//
//            (bool success, ) = recipient.call{value: amount}("");
//            if (!success) {
//            revert FailedInnerCall();
//            }
//        }
        Address.sendValue(payable(to), amount);

        emit TransferredReserveAsset(address(this), to, amount);
    }
}

contract A {

    IB public bContract;
    IWETH public WETH;

    function add(uint256 ethLiquidity) public {
        console2.log(
            "bContractInfo1:", address(bContract), address(bContract).balance
        );
        bContract.transferNativeAsset(address(this), ethLiquidity);
        console2.log(
            "bContractInfo2:", address(bContract), address(bContract).balance
        );
        WETH.deposit{value: ethLiquidity}();
    }
}
```

### Traces

```log
Traces:
  [5621773] XXXTest::testAddXXX()
    │   │   ├─ [0] console::log("bContractInfo1:", 0xB7293b069fFaA41EAb356d0B85b62aa319AAFa22, 12583485206564041 [1.258e16]) [staticcall]
    │   │   │   └─ ← [Stop] 
    │   │   ├─ [175] 0xB7293b069fFaA41EAb356d0B85b62aa319AAFa22::transferReserveAsset(factory: [0xD2597C1A4f0610A32e5f46AbE5B1014E29cb083a], 10631528916991609 [1.063e16])
    │   │   │   ├─ [0] 0x0000000000000000000000000000000000000000::transferReserveAsset(factory: [0xD2597C1A4f0610A32e5f46AbE5B1014E29cb083a], 10631528916991609 [1.063e16]) [delegatecall]
    │   │   │   │   └─ ← [Stop] 
    │   │   │   └─ ← [Return] 
    │   │   ├─ [0] console::log("bContractInfo2:", 0xB7293b069fFaA41EAb356d0B85b62aa319AAFa22, 12583485206564041 [1.258e16]) [staticcall]
    │   │   │   └─ ← [Stop] 
    │   │   ├─ [0] weth::deposit{value: 10631528916991609}()
    │   │   │   └─ ← [OutOfFunds] EvmError: OutOfFunds
    │   │   └─ ← [Revert] EvmError: Revert
    │   └─ ← [Revert] EvmError: Revert
    └─ ← [Revert] EvmError: Revert


```

### Steps to Reproduce:
1. Write a test for the contract.
2. Run the test.
3. Observe the OutOfFunds error during the execution of the test.
4. However, when using forge script to deploy and execute the same contract, everything runs smoothly, and no errors are encountered.

### Expected Behavior:
The contract should function properly during testing, just like it does when using forge script.
### Actual Behavior:
Tests fail with an OutOfFunds error, but no such error occurs when using forge script.

**Comment by grandizzy** [comment]
@mhxw could you please add the test too,is that a fuzz test or regular? Thank you

**Comment by mhxw** [comment]
> regular

regular

**Comment by mhxw** [comment]
This is my foundry.toml

```
# The Default Profile
[profile.default]
solc = '0.8.23'
evm_version = "shanghai" # Cancun will be tested in the CI.
auto_detect_solc = true
optimizer = true
optimizer_runs = 200
gas_limit = 1_000_000_000 # ETH is 30M, but we use a higher value.
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
fs_permissions = [
    { access = "read", path = "./chain-configs" },
    { access = "read", path="./out" }
]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

[etherscan]
base_sepolia = { key = "${BASE_SEPOLIA_KEY}" }

[fmt]
line_length = 100 # While we allow up to 120, we lint at 100 for readability.

[profile.default.fuzz]
runs = 256

[invariant]
runs = 10
depth = 15
fail_on_revert = true
dictionary_weight = 80
```

**Comment by grandizzy** [comment]
I see, let me try, I suspect contract is not made persistent so it is replaced with the one from fork, here's book ref https://book.getfoundry.sh/cheatcodes/make-persistent

**Comment by mhxw** [comment]
> I see, let me try, I suspect contract is not made persistent so it is replaced with the one from fork, here's book ref https://book.getfoundry.sh/cheatcodes/make-persistent

Thank you for your response, and I appreciate the suggestion. I'll give it a try and look into making the contract persistent as you mentioned.

**Comment by grandizzy** [comment]
I am not able to recreate the test but looking at traces
```
    │   │   ├─ [0] weth::deposit{value: 10631528916991609}()
    │   │   │   └─ ← [OutOfFunds] EvmError: OutOfFunds
```
make sure `msg.sender` has enough funds for this operation, see
- vm.prank to set msg.sender for next call https://book.getfoundry.sh/cheatcodes/prank
- vm.deal to set balance for address: https://book.getfoundry.sh/cheatcodes/deal

**Comment by mhxw** [comment]
> I am not able to recreate the test but looking at traces
> 
> ```
>     │   │   ├─ [0] weth::deposit{value: 10631528916991609}()
>     │   │   │   └─ ← [OutOfFunds] EvmError: OutOfFunds
> ```
> 
> make sure `msg.sender` has enough funds for this operation, see
> 
> * vm.prank to set msg.sender for next call https://book.getfoundry.sh/cheatcodes/prank
> * vm.deal to set balance for address: https://book.getfoundry.sh/cheatcodes/deal

Yes, that's exactly what I did!

vm.startPrank(platformAdmin);
vm.deal(platformAdmin, 100 ether);

**Comment by mhxw** [comment]
I appreciate your help! If it’s more convenient, I can invite you to my private repository. Additionally, if you could share your Telegram username, we can also discuss further via Telegram.

**Comment by grandizzy** [comment]
was this done before or after createSelectFork call?

**Comment by mhxw** [comment]
First, I call createSelectFork to fork the chain. After that, I deploy the contract, and finally, I execute the necessary functions.

**Comment by mhxw** [comment]
![image](https://github.com/user-attachments/assets/f2443db0-63dc-4a60-94ed-9d9516162090)

Hello, I’ve invited you to my private repository. The specific error occurs during the execution at this point.
https://github.com/mhxw/launchpad/blob/dev/test/TokenFactoryTest.t.sol#L138

**Comment by grandizzy** [comment]
cool, had a look, it does seem like a legit failure, if you modify line https://github.com/mhxw/launchpad/blob/a71891b86a69ff55f0abb1bb079a2639254be77c/src/TokenFactory.sol#L438 and instead
`Address.sendValue(payable(config.tokenVaultAddress), reverseAmountInActual + projectFee);`
you put something like `Address.sendValue(payable(config.tokenVaultAddress), 1);` then deposit goes through (but test eventually fails after with different message, probably expected)
```
    │   │   ├─ [23846] weth::deposit{value: 10631528916991609}()
    │   │   │   ├─ emit Deposit(param0: factory: [0xD2597C1A4f0610A32e5f46AbE5B1014E29cb083a], param1: 10631528916991609 [1.063e16])
    │   │   │   └─ ← [Stop] 
```

I think you should revisit contract logic, please reopen ticket if you think still it's a foundry bug. thank you!

**Comment by mhxw** [comment]
My asset flow is correct, and I have already tested this.

**Comment by mhxw** [comment]
console2.log(
            "bContractInfo1:", address(bContract), address(bContract).balance
        );
        bContract.transferNativeAsset(address(this), ethLiquidity);
        console2.log(
            "bContractInfo2:", address(bContract), address(bContract).balance
        );
        WETH.deposit{value: ethLiquidity}();
        
        
<img width="942" alt="image" src="https://github.com/user-attachments/assets/ba3bb8d4-7286-4677-b2bb-2a5573af50b4">

Before and after calling transferNativeAsset, you can see from the logs that the balance in the contract should have decreased. However, in reality, the balance does not decrease, and the execution continues.

**Comment by grandizzy** [comment]
I see, yes, indeed this looks like something off, reopening for further investigations. thank you

**Comment by grandizzy** [comment]
yeah, still seems like logic related, if you print balance of address executing (that is the proxy) like
```Solidity
            console2.log("before send", address(this).balance);
            Address.sendValue(payable(config.tokenVaultAddress), reverseAmountInActual + projectFee);
            console2.log("after send", address(this).balance);
            // 2. transfer token from vault to user
            ITokenVault(config.tokenVaultAddress).transferAsset(recipient, tokenAmountOut);
            // 3. transfer eth platform fee to platform treasury
            Address.sendValue(payable(platformTreasury), platformFee);
            console2.log("after send value", address(this).balance);
```

logs shows:
```
  before send 12634021291730964
  after send 50536085166923
  after send value 0
```

so nothing left for weth.deposit call

```
   │   │   ├─ [0] console::log("before send", 12634021291730964 [1.263e16]) [staticcall]
    │   │   │   └─ ← [Stop] 
    │   │   ├─ [157] 0xB7293b069fFaA41EAb356d0B85b62aa319AAFa22::fallback{value: 12583485206564041}()
    │   │   │   ├─ [0] 0x0000000000000000000000000000000000000000::fallback{value: 12583485206564041}() [delegatecall]
    │   │   │   │   └─ ← [Stop] 
    │   │   │   └─ ← [Return] 
    │   │   ├─ [0] console::log("after send", 50536085166923 [5.053e13]) [staticcall]
    │   │   │   └─ ← [Stop] 
    │   │   ├─ [175] 0xB7293b069fFaA41EAb356d0B85b62aa319AAFa22::transferAsset(user1: [0x0000000000000000000000000000000000000041], 80000000000000001721828308 [8e25])
    │   │   │   ├─ [0] 0x0000000000000000000000000000000000000000::transferAsset(user1: [0x0000000000000000000000000000000000000041], 80000000000000001721828308 [8e25]) [delegatecall]
    │   │   │   │   └─ ← [Stop] 
    │   │   │   └─ ← [Return] 
    │   │   ├─ [0] platformTreasury::fallback{value: 50536085166923}()
    │   │   │   └─ ← [Stop] 
    │   │   ├─ [0] console::log("after send value", 0) [staticcall]
    │   │   │   └─ ← [Stop] 
```

**Comment by grandizzy** [comment]
ah, ok, yeah, it's annoying, we have this https://github.com/foundry-rs/foundry/issues/4141 to improve error reporting when interacting with undeployed contracts. Are you OK to close this tracker and follow up 4141? thanks

**Comment by mhxw** [comment]
OK, Thank you very much, grandizzy.

**Comment by mhxw** [comment]
Hi grandizzy, I previously submitted a PR to fix the image display issue. When you have some time, could you please review it?

<img width="925" alt="image" src="https://github.com/user-attachments/assets/9afc022b-d5b2-4ffd-af5a-0c808ef1586a">


Here’s the link:
https://github.com/foundry-rs/.github/pull/1
