### ISSUE TITLE
feat(`forge build`): `--watch` flag should watch foundry.toml config changes

### ISSUE THREAD

**Issue by radeksvarz** [foundry-rs/foundry#9099]
### Component

Forge

### Describe the feature you would like

currently build -w watches sol files, it would be helpful to watch also config files

**Comment by zerosnacks** [comment]
@Ifechukwudaniel no new argument, this should be added to `forge build --watch`

**Comment by eshumanohare** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/foundry).

### My background and how it can be leveraged
Previously I have worked on creating smart contracts in DeFI (creating my own AMM), NFT based card game that I built at ETH India' 23. I am currently trying to get into smart contract auditing. Participated in 1 contest related to a DeFI Protocol. Also I have extensive knowledge of the ethereum protocol, EVM opcodes and inline assembly. My favourite blockchain projects are Tornado Cash, Uniswap and curve.fi.

### How I plan on tackling this issue
As this is my first issue on OD. I will read through the required documentation to understand how the forge engine is working. Then see how other flags are utilising the foundry.toml config file and then try to replicate it.

**Comment by leovct** [comment]
I'd like to tackle this issue :)
