### ISSUE TITLE
Set `blobhash(i)` from test

### ISSUE THREAD

**Issue by HrikB** [foundry-rs/foundry#9121]
### Component

Forge

### Describe the feature you would like

Add a cheatcode for setting the `blobhash` within a test so that it can be tested.

**Comment by grandizzy** [comment]
the cheatcode is already available as
```Solidity
/// Sets the blobhashes in the transaction.
/// Not available on EVM versions before Cancun.
/// If used on unsupported EVM versions it will revert.
function blobhashes(bytes32[] calldata hashes) external;
```
an example on how can be used can be found here https://github.com/foundry-rs/foundry/blame/cc8e430cc9ad743265d8c897b855809128798d8f/testdata/cancun/cheats/Blobhashes.t.sol#L10

**Comment by grandizzy** [comment]
@HrikB please reopen if not what you're looking for or if any issues using it. Thank you!

**Comment by HrikB** [comment]
This is what I was looking for!

**Comment by HrikB** [comment]
This is what I was looking for!
