### ISSUE TITLE
Mismatched block number error when forking Arbitrum Mainnet in Foundry tests

### ISSUE THREAD

**Issue by xana-rahmani** [foundry-rs/foundry#9122]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (fd56528 2024-10-14T00:26:15.553566000Z)

### Operating System

macOS (Apple Silicon)

### Describe the bug

I’m encountering a block number mismatch error when forking the Arbitrum Mainnet in my Foundry tests. The test is configured to fork at block 260_000_000, but Foundry returns block 20_886_024 instead, leading to a failed assertion. This issue occurs despite using the correct Arbitrum Mainnet RPC URL.

Steps to Reproduce
1.	Fork the Arbitrum Mainnet using the following configuration:
```solidity
string public constant ARBITRUM_MAINNET_RPC_URL = "https://arb1.arbitrum.io/rpc";
uint256 public constant ARBITRUM_MAINNET_Block = 260000000;
```

2.	Create a fork in the setUp() function:
```solidity
vm.createSelectFork(ARBITRUM_MAINNET_RPC_URL, ARBITRUM_MAINNET_Block);
```

3.	Run the test and observe the mismatch between the expected and returned block numbers.

* Expected Behavior
  * The test should successfully fork at block 260_000_000 on the Arbitrum Mainnet, allowing the test suite to proceed.

* Actual Behavior
   * The block number returned by Foundry is 20_886_024, which is significantly lower than the specified block number, causing the test to fail with the following error:

```bash
[FAIL: setup failed: assertion failed: 20886024 != 260000000] setUp() (gas: 0)
```

_I have confirmed that the Arbitrum Mainnet RPC URL is correct and fully functional, having tested it with both Alchemy and Infura._

example:

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.13;

import "forge-std/Test.sol";

contract ForkArbitrumMainnetTest is Test {
    // Arbitrum Mainnet RPC URL & Block
string public constant ARBITRUM_MAINNET_RPC_URL = "https://arb1.arbitrum.io/rpc";
uint256 public constant ARBITRUM_MAINNET_Block = 260000000;

    function setUp() public {
        // Fork from Arbitrum Mainnet at a specific block
        vm.createSelectFork(ARBITRUM_MAINNET_RPC_URL, ARBITRUM_MAINNET_BLOCK);

        // Check if fork is at the correct block
        uint256 currentBlock = vm.getBlockNumber();
        assertEq(currentBlock, ARBITRUM_MAINNET_BLOCK, "Block number does not match the expected block");
    }
}
```

**Comment by grandizzy** [comment]
this happens due to Arbitrum returning L1 block, hence 20886024 instead 260000000 https://docs.arbitrum.io/build-decentralized-apps/arbitrum-vs-ethereum/block-numbers-and-time#ethereum-block-numbers-within-arbitrum
Maybe we could add the logic in `vm.getBlockNumber()` cheatcode to return Arbitrum block number instead L1

**Comment by DaniPopes** [comment]
`getBlockNumber` is the same as `block.number` which is L1 block number in Arbitrum, see https://github.com/foundry-rs/foundry/issues/5085 for L2 block number.
