### ISSUE TITLE
bug: `forge` Vyper incompatibility with PEP 440

### ISSUE THREAD

**Issue by pcaversaccio** [foundry-rs/foundry#9123]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

`forge 0.2.0 (cc8e430 2024-10-16T00:22:08.572482504Z)`

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

Foundry Vyper is not compatible with [PEP 440](https://peps.python.org/pep-0440/) version specifiers.

---

[OUTDATED]

All of my snekmate pipelines are currently broken (see, e.g. [here](https://github.com/pcaversaccio/snekmate/actions/runs/11358478120/job/31599777309)), due to the latest Vyper commit here: https://github.com/vyperlang/vyper/commit/039d36926cf19916ada19f36b7e8ee9b09c1eec5. `forge` will throw with:

```console
[⠰] Compiling...
Error:
Found Vyper sources, but no compiler versions are available for it
Build failed: ['forge', 'build', '--ast', '--root', 'snekmate', '--extra-output', 'storageLayout', 'metadata']
```

![image](https://github.com/user-attachments/assets/c019ae96-a564-4f51-9237-a5164c6b0e52)

But if you install one commit before:
```console
pip install git+https://github.com/vyperlang/vyper@8f9a8cac49aafb3fbc9dde78f0f6125c390c32f0
```
it will succeed. I haven't debugged it yet fully but it's probably related to the commit hash.

**Comment by zerosnacks** [comment]
Triaged this w/ @pcaversaccio over Telegram, appears to be unrelated to Foundry but rather related to new `pragma` formatting. There may be a follow-up on Foundry's side in regards to improving the `Found Vyper sources, but no compiler versions are available for it` error that is raised.

On the initial build w/ my existing Vyper installation of 0.4.0 it did raise so it might be related to the pragma not being recognized.

```
Location: src/snekmate/auth/access_control.vy
Version specification "~=0.4.1" is not compatible with compiler version "0.4.0"

  line 1:0 
  ---> 1 # pragma version ~=0.4.1
  -------^
       2 """
```

**Comment by pcaversaccio** [comment]
hmm actually it still fails if the `pragma` is fixed. You can do this in the snekmate repo:
```console
git grep -l '=0.4.1' | xargs sed -i 's/=0.4.1/=0.4.1b1/g'
```
> This will replace all pragma versions with a pragma version that compiles with Vyper commit https://github.com/vyperlang/vyper/commit/039d36926cf19916ada19f36b7e8ee9b09c1eec5.

After run again:

```console
forge build
```

**Comment by zerosnacks** [comment]
> hmm actually it still fails if the `pragma` is fixed.

Was able to track it down to a `SemverError(Error("unexpected character 'b' after patch version number"))` as `0.4.1b1` is invalid semver

**Comment by zerosnacks** [comment]
Turns out it `0.4.1b1` is valid `pep440` used since Vyper `0.4.0` but invalid SemVer cc @klkvr

**Comment by pcaversaccio** [comment]
Correct. The relevant PR is this [one](https://github.com/vyperlang/vyper/pull/3593). For the pre-releases, you can find the versioning specification [here](https://peps.python.org/pep-0440/#pre-releases):

```txt
X.YaN   # Alpha release
X.YbN   # Beta release
X.YrcN  # Release Candidate
X.Y     # Final release
```

Also, note that I use PEP 440 compatible version specifier `~` in snekmate (and not `^`): https://peps.python.org/pep-0440/#version-specifiers

**Comment by DaniPopes** [comment]
cc @klkvr
