### ISSUE TITLE
getting EvmError: NotActivated while deploying an erc20Token paymaster contract

### ISSUE THREAD

**Issue by shisukeUrahara** [foundry-rs/foundry#9126]
i am trying to deploy the old erc20 paymaster with my own mock oracles with hardcoded price values and a standard erc20 token , Will that work ?

I am getting these errors 

    │   ├─ emit OwnershipTransferred(previousOwner: 0xFd40b0823eD5072C0890f2a9f07E3Ec0eF9b4eBa, newOwner: 0x514F4734E12Ede815F98abaE0f126999dCb621E6)
    │   ├─ [63] MetaMultiSigWallet::decimals() [staticcall]
    │   │   └─ ← [NotActivated] EvmError: NotActivated
    │   └─ ← [Revert] EvmError: Revert
    └─ ← [Revert] EvmError: Revert

this is my mock oracle contract 

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.23;

interface AggregatorV3Interface {
  function decimals() external view returns (uint8);

  function description() external view returns (string memory);

  function version() external view returns (uint256);

  function getRoundData(
    uint80 _roundId
  ) external view returns (uint80 roundId, int256 answer, uint256 startedAt, uint256 updatedAt, uint80 answeredInRound);

  function latestRoundData()
    external
    view
    returns (uint80 roundId, int256 answer, uint256 startedAt, uint256 updatedAt, uint80 answeredInRound);
}

/**
 * @title MockV3Aggregator
 * @notice Based on the FluxAggregator contract
 * @notice Use this contract when you need to test
 * other contract's ability to read data from an
 * aggregator contract, but how the aggregator got
 * its answer is unimportant
 */
contract MockV3Aggregator is AggregatorV3Interface {
    uint256 public constant version = 4;

    uint8 public decimals;
    int256 public latestAnswer;
    uint256 public latestTimestamp;
    uint256 public latestRound;
    string public description;

    mapping(uint256 => int256) public getAnswer;
    mapping(uint256 => uint256) public getTimestamp;
    mapping(uint256 => uint256) private getStartedAt;

    constructor(uint8 _decimals, int256 _initialAnswer,string memory _description) {
        decimals = _decimals;
        updateAnswer(_initialAnswer);
        description=_description;
    }

    function updateAnswer(int256 _answer) public {
        latestAnswer = _answer;
        latestTimestamp = block.timestamp;
        latestRound++;
        getAnswer[latestRound] = _answer;
        getTimestamp[latestRound] = block.timestamp;
        getStartedAt[latestRound] = block.timestamp;
    }

    function updateRoundData(
        uint80 _roundId,
        int256 _answer,
        uint256 _timestamp,
        uint256 _startedAt
    ) public {
        latestRound = _roundId;
        latestAnswer = _answer;
        latestTimestamp = _timestamp;
        getAnswer[latestRound] = _answer;
        getTimestamp[latestRound] = _timestamp;
        getStartedAt[latestRound] = _startedAt;
    }

    function getRoundData(uint80 _roundId)
        external
        view
        returns (
            uint80 roundId,
            int256 answer,
            uint256 startedAt,
            uint256 updatedAt,
            uint80 answeredInRound
        )
    {
        return (
            _roundId,
            getAnswer[_roundId],
            getStartedAt[_roundId],
            getTimestamp[_roundId],
            _roundId
        );
    }

    function latestRoundData()
        external
        view
        returns (
            uint80 roundId,
            int256 answer,
            uint256 startedAt,
            uint256 updatedAt,
            uint80 answeredInRound
        )
    {
        return (
            uint80(latestRound),
            getAnswer[latestRound],
            getStartedAt[latestRound],
            getTimestamp[latestRound],
            uint80(latestRound)
        );
    }

}

// Mock Token (USDC) Oracle
contract MockTokenOracle is MockV3Aggregator {
    constructor() MockV3Aggregator(8,100000000,"AXR_USDC/USD") {} // $1.00 with 8 decimals
}

// Mock Native Asset (ETH) Oracle
contract MockNativeOracle is MockV3Aggregator {
    constructor() MockV3Aggregator(8,200000000000,"ETH/USD") {} // $2000.00 with 8 decimals
}

**Comment by grandizzy** [comment]
@shisukeUrahara this is likely related to https://github.com/foundry-rs/foundry/issues/6228, try setting `evm_version=cancun` and see if it fixes the issue

**Comment by shisukeUrahara** [comment]
> @shisukeUrahara this is likely related to #6228, try setting `evm_version=cancun` and see if it fixes the issue

Thanks a lot @grandizzy for your help. I was able to fix this issue by setting evm_version=cancun .
