### ISSUE TITLE
Mine real blocks with anvil through fork-block-number

### ISSUE THREAD

**Issue by peyha** [foundry-rs/foundry#9128]
### Component

Anvil

### Describe the feature you would like

Hey,
Would it be possible for anvil to mine real blocks when used with `fork-block-number` ?

For instance, suppose I use anvil to create a fork at block 19M on Ethereum and I want this fork to mine a canonical Ethereum block every 12 sec (the fork would mine Ethereum's block 19M+1 then Ethereum's block 19M+2). Note that new block transactions could revert but it should be fine if you only use `eth_call` JSON_RPC calls on the fork.

**Comment by zerosnacks** [comment]
Hi @peyha 

Do you mean you want Anvil to re-fork at every new block created on L1, applying any local state from the previous block?

**Comment by mattsse** [comment]
I think @peyha is describing a mode that follows the canonical blocks after being forked.

this feature is not very sound because once you change something the chains have diverged, executing real blocks would also be incredibly expensive in terms of the RPC budget

**Comment by zerosnacks** [comment]
At this point in time, marking the points above, I don't think this is feasible / brittle.

For now marking as `not planned`, feel free to leave a comment / reopen @peyha if we misunderstood your request.

**Comment by peyha** [comment]
I agree with you, it's brittle so one solution could be to disallow `eth_sendRawTransaction` JSON-RPC calls and users would rely on `eth_call`to prevent the state from being tampered with.
My use case is that I want to call a view function at each block so one solution would be to do this and to call the function at each block
