### ISSUE TITLE
feat(`cast`): add `--new` flag to `cast wallet import` to create a new private key and add it to the wallet by name

### ISSUE THREAD

**Issue by aviggiano** [foundry-rs/foundry#9135]
### Component

Cast

### Describe the feature you would like

Here's what I am doing:

```bash
cast wallet import WALLET_NAME --private-key $(cast wallet new | grep Private | awk -F 'Private key: ' '{print $2}')
```

So that I don't have to see my private key

Here's what I would like to do:

```bash
cast wallet import WALLET_NAME --new
```

**Comment by zerosnacks** [comment]
Thanks for your suggestion

It is recommended to add new private keys in the keystore as follows:

`$ cast wallet new --password ~/.foundry/keystores/`

**Comment by aviggiano** [comment]
Got it, thanks
