### ISSUE TITLE
feat(anvil): Support mining blocks with same timestamp as previous block

### ISSUE THREAD

**Issue by domob1812** [foundry-rs/foundry#9142]
### Component

Anvil

### Describe the feature you would like

As far as I am aware, EVM chains can support that a block has the same timestamp as a previous block, as that is required to support sub-second block times.  It seems that `anvil` does not allow me to mine a block with the same timestamp as the previous block's (with `evm_mine`), as it then complains with:

    Timestamp error: 1600000100 is lower than or equal to previous block's timestamp

I think it would be helpful to support this, so that we can actually test smart contracts handle a situation like this correctly (in case there is subtle time-dependent logic contained in them).

**Comment by grandizzy** [comment]
@domob1812 I think this scenario should be solved with https://github.com/foundry-rs/foundry/issues/7931 and set `--block-time` to 0

**Comment by Rubilmax** [comment]
I'm not sure it is related to this issue, but with the latest version of anvil, with auto mining, there are now some transactions that are mined in a new block with the same timestamp as the previous one

**Comment by grandizzy** [comment]
@Rubilmax mind to open a ticket with a way to reproduce the problem you see? thank you!
