### ISSUE TITLE
Command documentation for `forge build --sizes` indicating that constructor arguments are not accounted for

### ISSUE THREAD

**Issue by mgiagante** [foundry-rs/foundry#9144]
### Component

Forge

### Describe the feature you would like

As mentioned in [this review comment](https://github.com/foundry-rs/foundry/pull/9116/files#r1802833772)

It would be good to mention in the help for `forge build --sizes` that the initcode size check and data provided in the table do not count the size of any arguments in the constructor.

Something like this would do
```
   /// Print compiled contract sizes.
   /// Constructor argument length is not included in the calculation of initcode size.
    #[arg(long)]
    #[serde(skip)]
    pub sizes: bool,
```

**Comment by mgiagante** [comment]
I'm happy to send a PR for this.

**Comment by mgiagante** [comment]
https://github.com/foundry-rs/foundry/pull/9145

**Comment by grandizzy** [comment]
Solved with https://github.com/foundry-rs/foundry/pull/9145
