### ISSUE TITLE
block.number not working properly with `vm.roll` while using fork test

### ISSUE THREAD

**Issue by danielNg25** [foundry-rs/foundry#9159]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (2044fae 2024-10-22T00:21:22.585036000Z)

### What command(s) is the bug in?

forge test -vvv

### Operating System

macOS (Apple Silicon)

### Describe the bug

This is the piece of code that I was using

```solidity
uint256 blockNumber = block.number;
console2.log("blockNumber", block.number);
vm.roll(blockNumber + 1000);
blockNumber = block.number;
console2.log("blockNumber", block.number);
console2.log(blockNumber, blockNumber + 1, blockNumber - 1, (blockNumber + (blockNumber - 1)) / 2);
```

and this is the out put
```
    ├─ [0] console::log("blockNumber", 1660866 [1.66e6]) [staticcall]
    │   └─ ← [Stop] 
    ├─ [0] VM::roll(1661866 [1.661e6])
    │   └─ ← [Return] 
    ├─ [0] console::log("blockNumber", 1661866 [1.661e6]) [staticcall]
    │   └─ ← [Stop] 
    ├─ [0] console::log(1661866 [1.661e6], 1661867 [1.661e6], 1660865 [1.66e6], 1661365 [1.661e6]) [staticcall]
    │   └─ ← [Stop] 
```
as you can see:
The `blockNumber` was assigned to current `block.number` which is 1661866, but when I log `blockNumber - 1` the value is 1660865 (= block.number - 1 - 1000 (the number that i increased)). The same thing also happened when I just assigned `blockNumber` once and not assign again after `vm.roll`

I only able to get the middle number by doing `(blockNumber + (blockNumber - 1)) / 2`

**Comment by grandizzy** [comment]
@danielNg25 please provide more details re your test setup, I am getting proper values with a simple case
```
Logs:
  blockNumber 1660866
  blockNumber 1661866
  1661866 1661867 1661865 1661865
```
