### ISSUE TITLE
Built-in labels

### ISSUE THREAD

**Issue by onbjerg** [foundry-rs/foundry#916]
>Nit for other PR probably: Should we also add labels for precompiles? At the limit, should we start shipping our own 'opinionated' labels for popular contracts, perhaps using ethers-addressbook?

_Originally posted by @gakonst in https://github.com/gakonst/foundry/pull/867#discussion_r825235255_

>agree that would be nice - tho we should think about how we want to handle L2 precompiles. I would like to get to the point of easily supporting a different set of precompiles for various chains & L2s

_Originally posted by @brockelmore in https://github.com/gakonst/foundry/pull/867#discussion_r825305671_

We should figure out if we want to ship more built-in labels, and if so, which and under what conditions. We already ship with a built-in label for the cheatcode address ("VM"), but per the comments quoted it might make sense to also ship:

- Labels for precompiles depending on the chain in fork mode, and mainnet precompiles when not in fork mode
- Labels from `ethers-addressbook` (such as Dai, USDC etc.) in fork mode

**Comment by lucas-manuel** [comment]
Close-able? @mds1

**Comment by mds1** [comment]
I think we should leave this open as I believe some of the default addresses (test contract, default sender, maybe other) might not have default labels. I could be wrong, but want to leave this open to confirm. cc @Evalir might be a good quick one to knock out

posting a related question I have which affects which addresses to label below:

--------

```sh
$ cast compute-address --nonce 0 0x1804c8AB1F12E6bbf3894d4083f33e07309d1f38
Computed Address: 0x5b73C5498c1E3b4dbA84de0F1833c4a029d90519
$ cast compute-address --nonce 1 0x1804c8AB1F12E6bbf3894d4083f33e07309d1f38
Computed Address: 0x7FA9385bE102ac3EAc297483Dd6233D62b3e1496
```

The 0x1804 addr is the default sender. If I run `address(this)` in a test it returns the 0x7FA9 addr of nonce 1. This matches up with the below forge test: https://github.com/foundry-rs/foundry/blob/8d0099be497922b53cded74b77a3e0b3c1079336/testdata/core/ContractEnvironment.t.sol#L16

But why is the addr not the nonce 0 addr of 0x5b73, which is what we (erroneously?) have in forge-std here, i.e. what's the default sender doing with nonce 0 before they deploy the test contract? https://github.com/foundry-rs/forge-std/blob/f06ad8944e436e639bce09cfccc55466d99e79d8/src/Base.sol#L15
