### ISSUE TITLE
Foundry contract deployment fails on `Rootstock` chain

### ISSUE THREAD

**Issue by ahsan-javaiid** [foundry-rs/foundry#9161]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

latest (https://github.com/foundry-rs/foundry/releases/tag/nightly-2044faec64f99a21f0e5f0094458a973612d0712)

### What command(s) is the bug in?

forge script script/Counter.s.sol --rpc-url $ROOTSTOCK_RPC_URL --broadcast --legacy

### Operating System

macOS (Intel)

## Description

I am trying to test `Foundry` with [Rootstock](https://dev.rootstock.io/) chain by deploying a simple `Counter` contract. 

Contract code:

```
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

contract Counter {
    // State variable to store a number
    uint256 public number;

    function increment() public {
        number++;
    }

    // You need to send a transaction to write to a state variable.
    function setNumber(uint256 _num) public {
        number = _num;
    }

    // You can read from a state variable without sending a transaction.
    function get() public view returns (uint256) {
        return number;
    }
}


```

### On deployment i am facing below error

[⠒] Compiling...
No files changed, compilation skipped
Error: 
Failed to deploy script:
backend: failed while inspecting

### Deployment command
// Set priv key in .env file and the source it. 

```
forge script script/Counter.s.sol --rpc-url https://public-node.testnet.rsk.co--broadcast --legacy
```

### Debugging:
Upon debugging foundry source code I found following error is originating from this source files.

Error: `Header(PrevrandaoNotSet)`

https://github.com/foundry-rs/foundry/blob/2044faec64f99a21f0e5f0094458a973612d0712/crates/evm/core/src/backend/mod.rs#L773

Not sure if Randao error is related to missing `mixHash` field in `eth_getBlockByHash` response in case of Rootstock network or is it something else.

```
curl https://public-node.testnet.rsk.co/ -X POST -H "Content-Type: application/json" \
  --data '{"jsonrpc":"2.0","method":"eth_getBlockByHash","params":["0x05272bbdfc4fbc0b6f51c7241a53bb516293560cff03b9aed9c376b0e2ee3ef6",true],"id":1}'
```

Let me know how can i fix Error: `Header(PrevrandaoNotSet)` error in case of contract deployment on Rootstock network. 

Note: Previously Foundry was working fine with Rootstock in old builds (quite old).

**Comment by ahsan-javaiid** [comment]
@grandizzy Would be great if you can share thought's on this issue.

**Comment by grandizzy** [comment]
@ahsan-javaiid check if it works by setting `evm_version = london` in foundry.toml

**Comment by grandizzy** [comment]
confirming it works by setting evm version to london either in foundry.toml or passing as arg

```bash
forge script script/Counter.s.sol --rpc-url https://public-node.testnet.rsk.co --broadcast --legacy --evm-version london
[⠒] Compiling...
No files changed, compilation skipped
Script ran successfully.

## Setting up 1 EVM.

==========================

Chain 31

Estimated gas price: 0.007840395 gwei

Estimated total gas used for script: 138729

Estimated amount required: 0.000001087690157955 ETH

==========================
```

Please reopen if still issues
