### ISSUE TITLE
feat(`cheatcodes`): add `--fork-retry` + `--fork-retry-backoff` equivalent to `vm.create*Fork`

### ISSUE THREAD

**Issue by anajuliabit** [foundry-rs/foundry#9162]
### Component

Forge

### Describe the feature you would like

Most of our integration tests are multichain, meaning we use `vm.createFork` to set up the forks. We can't use the `--fork-url` option because we want to ensure that the fork IDs have the same order, regardless of which chain the tests belong to.

For example, we always instantiate the forks in the following order:

- ID 0: Moonbeam fork
- ID 1: Base fork
- ID 2: Optimism fork

When running a `Base` integration test, the `setUp` function first fetches the Moonbeam governor and executes any live proposals (that can be cross-chain).

This is why we cannot use `--fork-url` with `forge test`.

Please allow the `--fork-retry` and `--fork-retry-backoff` flags to be used without requiring the `--fork-url`.

**Comment by pheobeayo** [comment]
May I take this issue on?

**Comment by PedroRosalba** [comment]
Can I work on this, please?

**Comment by zerosnacks** [comment]
> Can I work on this, please?

I appreciate your enthusiasm but please do not claim tickets you are not intending to work on

You are already assigned to https://github.com/foundry-rs/foundry/issues/7248#issuecomment-2454222443 and others

**Comment by kien6034** [comment]
@zerosnacks  can i work on this? The #9201 is open, but i believe most of the works  is done

**Comment by zerosnacks** [comment]
Thanks Kien, all good - assigned to you

**Comment by kien6034** [comment]
@zerosnacks sorry for taking this long, i  forget that i'm assigned to this issue , i've been busy this month, never actually got the time to do this issue 

i've just un-assign myself for others to take the issue

**Comment by anukul** [comment]
@zerosnacks hi! i'm interested in working on this :)

**Comment by zerosnacks** [comment]
Thanks @anukul! Assigning to you - let me know if you have any questions

**Comment by anukul** [comment]
There are three versions of `vm.createFork` (similar for `vm.createSelectFork`):

```solidity
// Creates a new fork with the given endpoint and the _latest_ block and returns the identifier of the fork
function createFork(string calldata urlOrAlias) external returns (uint256)
// Creates a new fork with the given endpoint and block and returns the identifier of the fork
function createFork(string calldata urlOrAlias, uint256 block) external returns (uint256);
// Creates a new fork with the given endpoint and at the block the given transaction was mined in, and replays all transaction mined in the block before the transaction
function createFork(string calldata urlOrAlias, bytes32 transaction) external returns (uint256);
```

@zerosnacks thoughts on overloading it with a `retryArgs` parameter, for each existing version?

```solidity
/// Retry arguments for RPC requests to forks
struct RetryArgs {
    /// Maximum number of retries
    uint256 max_retries;
    /// Initial retry backoff (in milliseconds) on encountering errors
    uint256 backoff;
}
```

**Comment by zerosnacks** [comment]
Hi @anukul,

Looking at it again I think we possibly do not need to add these overrides as in `foundry.toml` one can add an `[rpc_endpoints]` section which includes the retries and backoff behavior as follows:

```
[rpc_endpoints]
mainnet = { endpoint = "${_CONFIG_MAINNET}", retries = 3, retry_backoff = 1000, compute_units_per_second = 1000, auth = "Bearer ${_CONFIG_AUTH}" }
```

One can then reference this by its alias (`vm.createSelectFork("mainnet");`) in the test and all the settings would be applied to the fork.

cc @anajuliabit would this resolve your issue? This is the preferred way to perform multichain tests over `--fork-url`

cc @grandizzy just to check, am I overlooking something?

**Comment by grandizzy** [comment]
@zerosnacks good point, yeah, they can be configured like this. Though from a quick test it seems like these configs are not propagated when building provider, should be pretty easy to do such

**Comment by zerosnacks** [comment]
I see, this is a bit more complex - would you be interested in looking into this @anukul?

The general idea I think could be to expand the `ResolvedRpcEndpoints`, changing the `endpoints` into a `BTreeMap<String, Result<RpcEndpointConfig, UnresolvedEnvVarError>>` so it results in and then modify the `evm_opts` in `create_fork_request` with the settings.

https://github.com/foundry-rs/foundry/blob/59f354c179f4e7f6d7292acb3d068815c79286d1/crates/cheatcodes/src/config.rs#L32-L33

https://github.com/foundry-rs/foundry/blob/59f354c179f4e7f6d7292acb3d068815c79286d1/crates/config/src/endpoints.rs#L408-L415

https://github.com/foundry-rs/foundry/blob/59f354c179f4e7f6d7292acb3d068815c79286d1/crates/cheatcodes/src/config.rs#L188

https://github.com/foundry-rs/foundry/blob/59f354c179f4e7f6d7292acb3d068815c79286d1/crates/cheatcodes/src/evm/fork.rs#L329-L330

Related PR: https://github.com/foundry-rs/foundry/pull/8570 for the `auth` field, looks like it is not connected up either. This should be folded into the `RpcEndpointConfig`.

**Comment by anukul** [comment]
Sure, happy to do it!
