### ISSUE TITLE
feat(cast) cast wallet add note - additional information

### ISSUE THREAD

**Issue by radeksvarz** [foundry-rs/foundry#9167]
### Component

Cast

### Describe the feature you would like

`cast wallet` is awesome, yet once there are many entries in the keystore, it is difficult to keep track on what is for.

I propose to add note field into the account structure. 

Related commands:

`cast wallet note <account_name>`  outputs attached note (similar behaviour to addr or dk)

`cast wallet noteimport <account_name> "<note>"` adds / rewrites note

**Comment by TropicalDog17** [comment]
Can I work on this issue @radeksvarz @zerosnacks?

**Comment by radeksvarz** [comment]
> Can I work on this issue @radeksvarz @zerosnacks?

It's up to @zerosnacks . I am just a humble issue maker ;)

**Comment by radeksvarz** [comment]
@zerosnacks WDYT about this?  I assume it has the impact on the keystore file structure.

**Comment by zerosnacks** [comment]
We rely on https://github.com/roynalnaruto/eth-keystore-rs here https://github.com/alloy-rs/alloy/blob/4632a88d60b5615ed021770fa30dfa6643d75cee/crates/signer-local/Cargo.toml#L32-L33 under the hood, I think it would be most suitable to implement it there are a functionality

**Comment by zerosnacks** [comment]
For now marking as `not planned`, if implemented upstream happy to support it in Foundry

**Comment by radeksvarz** [comment]
@zerosnacks Understood. What would be the ideal workaround for now? 
(I am playing with the idea to creata a TUI for the cast wallet.)

**Comment by zerosnacks** [comment]
> @zerosnacks Understood. What would be the ideal workaround for now? (I am playing with the idea to creata a TUI for the cast wallet.)

I would recommend adding a kind of storage mechanism alongside your TUI or alternatively we could add some kind of persistence in the global `.foundry` for cast, similar to how we do for the other binaries

**Comment by radeksvarz** [comment]
I will align to whatever would you think fits best for mid term. ( As I do not believe the mentioned eth-keystore package would include the notes any time in mid term future).

IMHO the notes should be somewhere close to the keys themselves, i.e. either within the file or aside in the same dir - for the better portability, backuping, etc.

Initially I hoped to have them within the file as they would be encrypted as well.

If we put them aside, the question is whether:
 - encrypt notes
 - do not encrypt notes
 - have an option to encrypt notes

**Comment by zerosnacks** [comment]
Though ambitious you could push for inclusion to the Web3 Secret Storage definition as an optional field. https://github.com/ethereum/wiki/wiki/web3-secret-storage-definition if your goal is for them to be included as part of the key definition
