### ISSUE TITLE
feat(fmt): `multiline_func_header` all option to multiline also single function parameter

### ISSUE THREAD

**Issue by ChiTimesChi** [foundry-rs/foundry#9173]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (2044fae 2024-10-23T00:22:09.499287069Z)

### What command(s) is the bug in?

forge fmt

### Operating System

Linux

### Describe the bug

Functions with a single paramater that need to be multilined does not have the parameter multilined.

## The config example
```toml
# ...

[fmt]
line_length = 120
multiline_func_header = 'all'
```

## Bug
`forge fmt` behaves differently for functions with single and multiple params:

```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

contract A {
    function a(uint256 param1)
        external
        pure
        returns (uint256 firstReturnValue, uint256 secondReturnValue, uint256 thirdReturnValue)
    {
        firstReturnValue = param1 + 1;
        secondReturnValue = param1 + 2;
        thirdReturnValue = param1 + 3;
    }

    function b(
        uint256 param1,
        uint256 param2
    )
        external
        pure
        returns (uint256 firstReturnValue, uint256 secondReturnValue)
    {
        firstReturnValue = param1 + 1;
        secondReturnValue = param2 + 2;
    }
}
```

## Expected behavior
I am expecting the following behaviour (which was enforced in one of the previous forge versions):
```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

contract A {
    function a(
        uint256 param1
    )
        external
        pure
        returns (uint256 firstReturnValue, uint256 secondReturnValue, uint256 thirdReturnValue)
    {
        firstReturnValue = param1 + 1;
        secondReturnValue = param1 + 2;
        thirdReturnValue = param1 + 3;
    }

    function b(
        uint256 param1,
        uint256 param2
    )
        external
        pure
        returns (uint256 firstReturnValue, uint256 secondReturnValue)
    {
        firstReturnValue = param1 + 1;
        secondReturnValue = param2 + 2;
    }
}
```

## Possibly related
- #8637
- #8761 
- #8762

**Comment by ChiTimesChi** [comment]
This change in formatting affects one of our repos, where the already deployed contracts are getting changed by `forge fmt`. Having the option to restore the original formatting behavior would be much appreciated.

**Comment by grandizzy** [comment]
hey @ChiTimesChi indeed, the prev behavior was reverted because people were already using fmt with the old style (no split on mulitline if single param) see https://github.com/foundry-rs/foundry/issues/8761
I don't think will be changing the behavior again, would be a biggie for you to just use new way of formatting?
(There's `multiline_func_header="params_first"` too but will format on new line only fns with single params)

**Comment by ChiTimesChi** [comment]
Hey @grandizzy , thanks for the swift response!

This is a kind of a biggie, as we really need to preserve the existing formatting. Some of the contracts are already deployed on a subset of chains, changing them will change the metadata hash. Which will not only lead to more workaround for verification, but also affect the create2 address derivation. Which in turn leads to the same contract residing on different addresses on old/new chains, and the whole create2 pipeline was designed for the consistent address in the first place.

I understand that the single param multilining might seem counter intuitive for a lot of users, so perhaps it could be a different config setting (similar to params_first vs params_first_multi)?

**Comment by grandizzy** [comment]
I see, will look into providing an `all_multi` for this
