### ISSUE TITLE
feat(`forge test`): inquiry for allowing to build and test specific files

### ISSUE THREAD

**Issue by jidalii** [foundry-rs/foundry#9175]
### Component

Forge

### Describe the feature you would like

For the current `forge test`, it automatically rebuilds all solidity files before running the test cases. I want to specify the files to build and test, while skipping the build during `forge test`. 
For instance:
```(shell)
>>> forge build --build-path src/Counter.sol
>>> forge test --match-path src/Counter.sol --skip-build
```
I wonder whether this feature is acceptable to the team. Thanks!

**Comment by grandizzy** [comment]
looks similar with https://github.com/foundry-rs/foundry/issues/9164 going to close this as dupe. Please reopen if you think different request. thank you!
