### ISSUE TITLE
bug(`cheatcodes`): `vm.createSelectFork` fails with `transaction validation error: blob versioned hashes not supported` if forked on `tx hash` after blobs

### ISSUE THREAD

**Issue by 0xdef1cafe** [foundry-rs/foundry#9184]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (b1e9365 2024-10-24T00:21:41.884762823Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### Describe the bug

consider a block containing blobs

https://etherscan.io/txs?block=20475448&isblob=true

the blobs are at position `86` and `117` in the block

running `vm.createSelectFork` on a tx hash after position `86` in the block will fail with the following error

`[FAIL: setup failed: vm.createSelectFork:  backend: failed committing transaction; transaction validation error: blob versioned hashes not supported; blob versioned hashes not supported;] setUp() (gas: 0)`

note that older versions of foundry aren't affected by this, e.g. this version works correctly

`foundryup --commit nightly-1710187c614f01598116e67aaf4cda76e7b532ec`

i haven't bisected between the bad comment in the template and the working commit listed immediately above

running against reth 1.1.0 locally

**Comment by yash-atreya** [comment]
We're incorrectly setting the `SpecId` for revm. Fixing

**Comment by grandizzy** [comment]
@0xdef1cafe can you try setting `evm_version = "cancun"` in foundry.toml file or `--evm-version cancun` arg and see if any better? currently foundry defaults to paris

**Comment by yash-atreya** [comment]
Yeah setting `evm_version` to cancun should fix this.
