### ISSUE TITLE
bug(`chisel`): displaying prev value after post-increment

### ISSUE THREAD

**Issue by yash-atreya** [foundry-rs/foundry#9189]
### Component

Chisel

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

chisel 0.2.0 (b1e9365 2024-10-24T00:21:42.963690000Z)

### What command(s) is the bug in?

chisel

### Operating System

None

### Describe the bug

In the below screenshot it can be observed that after `i++` the previous value i.e `0x0` of `i` is logged and not `0x1`

<img width="480" alt="Screenshot 2024-10-24 at 5 27 47 PM" src="https://github.com/user-attachments/assets/a6eae4e1-0de2-46b3-a262-0a8196d12734">

**Comment by klkvr** [comment]
I think this is expected? If you assing e.g `uint256 a = i++`, the previous value would be assigned, not the incremented one
