### ISSUE TITLE
feat(`cheatcodes`): Consider accepting bytes4 as data input to vm.mockCall

### ISSUE THREAD

**Issue by smartcontracts** [foundry-rs/foundry#9213]
`vm.mockCall` currently has the following function signatures:

```solidity
function mockCall(address where, bytes calldata data, bytes calldata retdata) external;
```

```solidity
function mockCall(
    address where,
    uint256 value,
    bytes calldata data,
    bytes calldata retdata
) external;
```

In its current state, this leads to an awkward syntax for using `vm.mockCall` for any call to a specific function signature. Foundry docs give the following example for how to do this:

```solidity
function testMockCall() public {
    vm.mockCall(
        address(0),
        abi.encodeWithSelector(MyToken.balanceOf.selector),
        abi.encode(10)
    );
    assertEq(IERC20(address(0)).balanceOf(address(1)), 10);
    assertEq(IERC20(address(0)).balanceOf(address(2)), 10);
}
```

This certainly works, but `abi.encodeWithSelector` has the semantic meaning of encoding a function call and is awkward when it's being deliberately abused as a way to basically just mean `abi.encodePacked(MyToken.balanceOf.selector)`. We could just change the docs to use `abi.encodePacked` but I think it would be beneficial to consider accepting two additional function signatures:

```solidity
function mockCall(address where, bytes4 data, bytes calldata retdata) external;
```

```solidity
function mockCall(
    address where,
    uint256 value,
    bytes4 data,
    bytes calldata retdata
) external;
```

This would mean we could improve the syntax to:

```solidity
function testMockCall() public {
    vm.mockCall(
        address(0),
        MyToken.balanceOf.selector,
        abi.encode(10)
    );
    assertEq(IERC20(address(0)).balanceOf(address(1)), 10);
    assertEq(IERC20(address(0)).balanceOf(address(2)), 10);
}
```

Which makes it much clearer what's going on.

**Comment by grandizzy** [comment]
@smartcontracts for similar situation with `expectRevert` we added new cheatcode `expectPartialRevert` in order to be avoid any breaking change, we could do the same here though not sure what's the best name for such cheatcode (maybe `mockAllCalls`, @mds1 wdyt?)

**Comment by smartcontracts** [comment]
Hmm would this be breaking? It's an extension of the existing ABI in theory. But happy either way, would just love a more semantically clear interface here. Makes it easier to validate test behavior.

**Comment by mds1** [comment]
I think the two cases are a bit different: `expectPartialRevert` was because we wanted all reverts with a similar four byte prefix to be caught, regardless of the remaining revert data. Here my understanding is that mock calls already do a partial match on the provided data, but adding a sig variant with `bytes4` instead of `bytes` is nicer UX for the partial case
