### ISSUE TITLE
Forge script cant deploy due to `prevrandao` not set

### ISSUE THREAD

**Issue by dung5ire** [foundry-rs/foundry#9228]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (3ff3d0562 2024-10-01T08:39:18.585271000Z)

### What command(s) is the bug in?

forge script script/deploy.s.sol --private-key <my private key>  --broadcast --legacy --rpc-url https://rpc.testnet.5ire.network/

### Operating System

macOS (Apple Silicon)

### Describe the bug

My script : 
```bash
forge script script/deploy.s.sol --private-key <my private key>  --broadcast --legacy --rpc-url https://rpc.testnet.5ire.network/
```

Network: `5ireChain testnet`

My issue:

```
- Error #0: header validation error: `prevrandao` not set
- Error #1: `prevrandao` not set
```

My forge version is : `forge 0.2.0 (3ff3d0562 2024-10-01T08:39:18.585271000Z)`

Note: 
+ 5ireChain is using `Frontier` to integrate EVM-layer in Polkadot SDK  
+ Current 5ireChain Client Version is not adding `prevrandao` number in `block` 

Relevant Issue: 
https://github.com/foundry-rs/foundry/issues/4232

**Comment by grandizzy** [comment]
@dung5ire you need to set london evm version either in foundry.toml `evm_version = "london"` or pass it to forge verify as `--evm-version london`, similar with https://github.com/foundry-rs/foundry/issues/9161
Closing this for now, thank you

**Comment by dung5ire** [comment]
Thanks so much @grandizzy
