### ISSUE TITLE
Foundry is getting panicked crash at /Users/runner/work/foundry-zksync/foundry-zksync/crates/script/src/broadcast.rs:89

### ISSUE THREAD

**Issue by FaizanNehal** [foundry-rs/foundry#9233]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.0.2 (b513e39 2024-10-16T00:24:58.499734000Z)

### What command(s) is the bug in?

forge script 

### Operating System

macOS (Apple Silicon)

### Describe the bug

I am trying to run `Uniswap v2` on my local `zksync` chain. For this purpose I am running my own chain locally, and have made necessary changes into `Uniswap v2` contract so that they can be deployed to `zksync` and can be compiled with `solidity ^0.8.13`. 

Uniswap v2 is successfully deployed and the token pair is also created but upon adding liquidity into the pair I am getting this error from the foundry.
<img width="976" alt="image" src="https://github.com/user-attachments/assets/e9542c35-8a8d-45e4-99ec-f60cf44a01c9">
<img width="959" alt="image" src="https://github.com/user-attachments/assets/51ab7811-092f-40ef-8991-63272000d6a7">

Just to make everything clear I am also adding the code in my script file:
```

// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import {Script, console} from "forge-std/Script.sol";
import {UniswapV2Router02} from "../contracts/UniswapV2Router02.sol";
import {UniswapV2Pair} from "../contracts/UniswapV2Pair.sol";
import {ERC20_Token_Sample} from "../contracts/Token.sol";


contract testScript is Script {
     UniswapV2Router02 public router =UniswapV2Router02(payable(0x3e193F7E8d75c81E66d222C1182e63A8Db54802A));
     UniswapV2Pair public pair =UniswapV2Pair(0x114642199eEd33e1ad1699345E12ca2bB145b9E8);
     ERC20_Token_Sample public tokenA= ERC20_Token_Sample(0xaE7F6b4f2fF21fC5Fc52932A25faea11Bf5F509e);
     ERC20_Token_Sample public tokenB= ERC20_Token_Sample(0x922a36d29b1e991DB35b8e14C08828eC31E64Ac0);


    function run() public {
        vm.startBroadcast();
        
        console.log("ADDRESS: ",router.getPair(0xaE7F6b4f2fF21fC5Fc52932A25faea11Bf5F509e,0x922a36d29b1e991DB35b8e14C08828eC31E64Ac0));
        // now adding liquidity in the pair

        console.log(tokenA.balanceOf(0xa61464658AfeAf65CccaaFD3a512b69A83B77618));
        console.log(tokenB.balanceOf(0xa61464658AfeAf65CccaaFD3a512b69A83B77618));
        tokenA.approve(0x3e193F7E8d75c81E66d222C1182e63A8Db54802A, 100000);
        tokenB.approve(0x3e193F7E8d75c81E66d222C1182e63A8Db54802A, 100000);
        router.addLiquidity(0xaE7F6b4f2fF21fC5Fc52932A25faea11Bf5F509e, 0x922a36d29b1e991DB35b8e14C08828eC31E64Ac0, 1200, 3600, 100, 300,0xa61464658AfeAf65CccaaFD3a512b69A83B77618,0);
        
        (uint112 reserve0, uint112 reserve1, uint32 blockTimestampLast) = pair.getReserves();
        console.log("RESERVE 0: ",reserve0);
        console.log("RESERVE 1: ",reserve1);
        console.log("TIMESTAMP: ",blockTimestampLast);
        vm.stopBroadcast();
    }
}
```

As you can see I am adding the liquidity and logging it. The liquidity is getting added as you can see here:
<img width="921" alt="image" src="https://github.com/user-attachments/assets/f94d605c-c7df-41bd-96b1-32cc15b371e3">

So I am assuming the foundry is panicking at line 
```
vm.stopBroadcast();
```

The output error was very different and told me that it might be issue with foundry itself.

**Comment by grandizzy** [comment]
@FaizanNehal this looks like https://github.com/matter-labs/foundry-zksync related, if so please close this ticket and open one in the proper repo. Thank you

**Comment by FaizanNehal** [comment]
@grandizzy Sure I can do that
