### ISSUE TITLE
Forge install errors on git ssh urls

### ISSUE THREAD

**Issue by OliverNChalk** [foundry-rs/foundry#924]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (1e1583b 2022-03-13T00:03:29.280028909+00:00)

### What command(s) is the bug in?

forge install

### Operating System

Linux

### Describe the bug

This is a minor issue as users can install via `Username/Repository` fine. This is to support `Ctrl + C`, `Ctrl + V` of the repo install URL as a valid source for `forge install`. This could be seen as a good first issue, minor polishing task.

Here is an example install via ssh-git url that fails:
```bash
oliver ~> forge install git@github.com:Rari-Capital/solmate.git
Installing git in "/home/oliver/ghq/github.com/OliverNChalk/custody-vault/lib/git", (url: https://github.com/git, tag: Some("github.com:Rari-Capital/solmate.git"))
Error:
   0: No such file or directory (os error 2)

Location:
   cli/src/cmd/install.rs:157

Backtrace omitted.
Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

**Comment by gakonst** [comment]
Yeah this should be as simple as parsing the `git@github.com:` prefix here https://github.com/gakonst/foundry/blob/master/cli/src/opts/forge.rs#L238

**Comment by onbjerg** [comment]
We should support it, but would generally suggest not using SSH URLs for submodules since not everyone is using SSH with git and the modules would fail to pull

**Comment by OliverNChalk** [comment]
Very valid point I hadn't considered, would it be acceptable to parse the ssh url and convert it to a standardized format/reference? I.e. not force install over ssh but rather parse out the user and repository from the url?

**Comment by gakonst** [comment]
Yeah maybe could replace `git@github.com:` -> `https://github.com/`

**Comment by sblOWPCKCR** [comment]
> not everyone is using SSH with git and the modules would fail to pull

@onbjerg genuinely curious, what's the story here? Windows users?

The biggest advantage of supportinf git@ URLs natively are private repositories - AFAIK there's no good way to make them work with https:// addresses. The best I've seen is interactive prompts for username/password, but that doesn't play well with CI

**Comment by sambacha** [comment]
Create token with these permissions:

repo:status
repo_deployment
public_repo
repo:invite
security_events

Set your token in your git clone string:

```shell
$ git clone https://${TOKEN}:x-oauth-basic@github.com/$username/$reponame
```

**Comment by sambacha** [comment]
More generally: 
```shell
usr/bin/git config --local --name-only --get-regexp core\.sshCommand
/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader

**Comment by sblOWPCKCR** [comment]
That is awesome!

Meta question: what’s the advantage of using https over git? In the latter case, you don’t need to do any extra configuration, the submodules ‘just work’. Why would I want to use https submodules in my project?

**Comment by sambacha** [comment]
credential.helper can cache/manage your Authentication, whereas you have to
use ssh-agent for ssh.

all in all, the command line client, gh, is the best way to interact with
github (the platform, not actually git

**Comment by sblOWPCKCR** [comment]
In my experience, for ssh you just add your ssh key to your github profile (gitlab, GHE and all others support this) and forget about authentication at all. No need to setup up ssh-agent or use custom tooling on the client side. This is the biggest benefit of ssh schema: set up once and it just works.

But this is really going on a tangent. I'm mostly curious about this: `not everyone is using SSH with git and the modules would fail to pull`. It contradicts my expectations/experience, so wondering if I'm missing some cases (Windows? that's my best guess)

**Comment by onbjerg** [comment]
> @onbjerg genuinely curious, what's the story here? Windows users?
> 
> The biggest advantage of supportinf git@ URLs natively are private repositories - AFAIK there's no good way to make them work with https:// addresses. The best I've seen is interactive prompts for username/password, but that doesn't play well with CI

I've worked with a lot of developers that do not use SSH URLs, not just Windows users. Some people just don't set it up :)

**Comment by sblOWPCKCR** [comment]
Woooot, you can't even **clone** from public repo over ssh without ssh credentials, that's wild (I thought the creds would only be needed for private repo or pushes):
```
/tmp/22 [master|✔] ❯❯❯ mv ~/.ssh ~/.ssh_old
/tmp/22 [master|✔] ❯❯❯ git submodule add git@github.com:gakonst/foundry.git external/foundry
Cloning into '/private/tmp/22/external/foundry'...
The authenticity of host 'github.com (192.30.255.113)' can't be established.
ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:gakonst/foundry.git' into submodule path '/private/tmp/22/external/foundry' failed
```

OK, now it makes sense

**Comment by sambacha** [comment]
> Woooot, you can't even **clone** from public repo over ssh without ssh credentials, that's wild (I thought the creds would only be needed for private repo or pushes):
> 
> ```
> /tmp/22 [master|✔] ❯❯❯ mv ~/.ssh ~/.ssh_old
> /tmp/22 [master|✔] ❯❯❯ git submodule add git@github.com:gakonst/foundry.git external/foundry
> Cloning into '/private/tmp/22/external/foundry'...
> The authenticity of host 'github.com (192.30.255.113)' can't be established.
> ED25519 key fingerprint is SHA256:+DiY3wvvV6TuJJhbpZisF/zLDA0zPMSvHdkr4UvCOqU.
> This key is not known by any other names
> Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
> Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> fatal: clone of 'git@github.com:gakonst/foundry.git' into submodule path '/private/tmp/22/external/foundry' failed
> ```
> 
> OK, now it makes sense

to be sure you just need to generate any valid SSH key on your end, does not have to be registered with github 

also @onbjerg is it possible to have on install foundry set a local git config?

 i.e. `git clone --local-only core.symlinks false` ?

**Comment by sambacha** [comment]
> Yeah this should be as simple as parsing the `git@github.com:` prefix here [https://github.com/gakonst/foundry/blob/master/cli/src/opts/forge.rs#L238](https://github.com/gakonst/foundry/blob/master/cli/src/opts/forge.rs?rgh-link-date=2022-03-13T18%3A20%3A23Z#L238)

To add to your point, using `git://` in GitHub actions workflow will cause it to fail in CI, see https://github.blog/2021-09-01-improving-git-protocol-security-github/

> We’re changing which keys are supported in SSH and removing unencrypted Git protocol. Only users connecting via SSH or git:// will be affected. If your Git remotes start with https://, nothing in this post will affect you. If you’re an SSH user, read on for the details and timeline.

The SSH pseudo-URL starting with `git@github.com:` will still require an updated SSH config 

using `git+https://` works too

**Comment by onbjerg** [comment]
Solved in #1311

**Comment by sakulstra** [comment]
This is quite annoying, any chance we could add a flag to allow ssh over https?

**Comment by sambacha** [comment]
> Having https over ssh is quite annoying(when working with private repos), any chance we could add a flag to allow ssh over https?

you can do something like this:

```yaml
      - uses: lhotari/action-upterm@v1
        with:
          ## limits ssh access and adds the ssh public key for the user which triggered the workflow
          limit-access-to-actor: true
          ## limits ssh access and adds the ssh public keys of the listed GitHub users
          limit-access-to-users: sambacha,sakulstra
```

**Comment by sakulstra** [comment]
@sambacha not sure how that would help.

I'm talking about github actions, but converting ssh to https in https://github.com/foundry-rs/foundry/pull/1311/files breaking the submodule setup for ppl using ssh. Would be nice if I could configure a project to always use ssh as for our team https://github.com/foundry-rs/foundry/issues/924#issuecomment-1079832953 is the default making https a bit cumbersome.

**Comment by sambacha** [comment]
> @sambacha not sure how that would help.
> 
> I'm talking about github actions, but converting ssh to https in [#1311 (files)](https://github.com/foundry-rs/foundry/pull/1311/files) breaking the submodule setup for ppl using ssh. Would be nice if I could configure a project to always use ssh as for our team [#924 (comment)](https://github.com/foundry-rs/foundry/issues/924#issuecomment-1079832953) is the default making https a bit cumbersome.
> 
> Or if not via a setting might make sense to just persists the version ppl install (if i install via ssh url i want the ssh url) if that makes sense.
> 
> edit: `breaking` as in "not picking it up automatically" - nothing is actually "broken"

Using that action lets you use ssh like a normal user, you could setup your env that way. It uses your github account's public key to auth, so you could access any repo you have access to using your github token

GitHub only recognizes the `git` user otherwise from actions workflow. you could maybe do something like this where your setting the git submodules remote's to use your github token to auth

```yaml
ssh://token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ git.submodule }}
```
then if needed you can replace the normal submodule remotes with the token-based one. here is an example replacing http with https 
```shell
git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
```

Open a new issue as this is closed

**Comment by jacobhjkim** [comment]
For all still having this issue, you can simply just add these lines in your `~/.gitconfig` file.
```
[url "https://github.com/"]
	insteadOf = git@github.com:
```
This config tells your git to use https instead of ssh.

**Comment by ferencdg** [comment]
just add it manually with git submodule add and change the solidity remappings manually, that is the only thing forge install does
