### ISSUE TITLE
Downstream issues emerging after `forge config` output changes

### ISSUE THREAD

**Issue by GlacierWalrus** [foundry-rs/foundry#9240]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (9d74675 2024-10-31T00:20:54.778420069Z)

### What command(s) is the bug in?

forge config --json

### Operating System

Linux

### Describe the bug

I'm using a typescript library which runs [forge config --json](https://github.com/NomicFoundation/hardhat/blob/1c491eb9fc8b399e480aa257d0f0832f66440be1/packages/hardhat-foundry/src/foundry.ts#L31) to acquire the forge config.

This library started crashing out of the blue recently when my build system was executing `hardhat compile`. The error looked like this:

```
An unexpected error occurred:
SyntaxError: Unexpected non-whitespace character after JSON at position 5069 (line 186 column 1)
    at JSON.parse (<anonymous>)
```

I wrote the buffer to file and inspected it
```
❯ hexdump dump.json -C | tail -n 5
000013c0  73 65 2c 0a 20 20 22 74  72 61 6e 73 61 63 74 69  |se,.  "transacti|
000013d0  6f 6e 5f 74 69 6d 65 6f  75 74 22 3a 20 31 32 30  |on_timeout": 120|
000013e0  2c 0a 20 20 22 65 6f 66  22 3a 20 66 61 6c 73 65  |,.  "eof": false|
000013f0  0a 7d 0a 1b 5b 30 6d                              |.}..[0m|
000013f7
```

and you can see an ANSI control code at the end of the output.

Given the nature of my setup I found the best workaround was to set `NO_COLOR=1` prior to running hardhat

[This line](https://github.com/foundry-rs/foundry/blame/17e0981a071fbd3b5a0a59affb4d638a28dfec89/crates/common/src/io/shell.rs#L299) might be the culprit?

I'd suggest perhaps checking if the output is a tty before writing ANSI codes.

**Comment by zerosnacks** [comment]
Hi @GlacierWalrus thanks for flagging this

I think the most practical way to fix this would be to ensure `--json` is always ran in a `NoColor` mode.

Related: https://github.com/foundry-rs/foundry/issues/8794 which plans to add a global `--json` flag which would make this easy to enforce https://github.com/foundry-rs/foundry/blob/6b0c27ed4ccfdb5a4805e9f53d487cca51c5e116/crates/cli/src/opts/shell.rs#L37

cc @DaniPopes

**Comment by GlacierWalrus** [comment]
That makes more sense, thank you for explaining your codebase to me.

**Comment by DaniPopes** [comment]
https://github.com/foundry-rs/foundry/blame/17e0981a071fbd3b5a0a59affb4d638a28dfec89/crates/common/src/io/shell.rs#L493-L500

This function should maybe check `stderr().is_tty()`
