### ISSUE TITLE
Keystore

### ISSUE THREAD

**Issue by PatrickAlphaC** [foundry-rs/foundry#926]
### Component

Forge

### Describe the feature you would like

Ideally, we have a way to encrypt and store keys so we don't have to enter our private keys every time we want to deploy a contract.

Something similar to the [ethsign](https://github.com/dapphub/dapptools/blob/master/src/ethsign/README.md) tool.

### Additional context

Right now, it looks like most template have you either:

1. Copy-paste your private key into a shell prompted terminal
2. Add your key as an environment variable

I think ideally you'd just be prompted for the password to unencrypt your private key when you go to deploy.

**Comment by onbjerg** [comment]
Ref #529

And similarly to my comment there, does `cast wallet` fix this? You can use `cast wallet` to create keystores, and you can use that keystore in `forge create` with `--keystore` and `--password` :smile:

**Comment by onbjerg** [comment]
> > Ideally, we have a way to encrypt and store keys so we don't have to enter our private keys every time we want to deploy a contract.
> 
> I think we don't have a way to encrypt/store the keys, so we just do the create/sign/verify part rn but would be maybe nice if we had named keyfiles under `~/.foundry` and `cast wallet encrypt` / `cast wallet decrypt`

If you create a new keystore, I think cast asks for a password. To unlock the keystore, you also pass `--password`

**Comment by gakonst** [comment]
REF: https://github.com/foundry-rs/foundry/pull/656 as well.
