### ISSUE TITLE
forge: make forge script create2deployer configurable.

### ISSUE THREAD

**Issue by cuiweixie** [foundry-rs/foundry#9266]
### Component

Forge

### Describe the feature you would like

when forge create using create2, the default deployer is 4e59b44847b379578588920ca78fbf26c0b4956c.
I think we need to make it configurable via cmd args or env or both.

**Comment by zerosnacks** [comment]
Thanks for your suggestion, marking as duplicate of https://github.com/foundry-rs/foundry/issues/2638
