### ISSUE TITLE
chore: `isFile` and `isDir` functions should be views

### ISSUE THREAD

**Issue by iainnash** [foundry-rs/foundry#9284]
https://github.com/foundry-rs/forge-std/blob/1eea5bae12ae557d589f9f0f0edae2faa47cb262/src/Vm.sol#L690

If `readFile` is a view, why are `isFile` and `isDir` not views?

**Comment by mds1** [comment]
cc @grandizzy, guessing these can also be view?

**Comment by grandizzy** [comment]
yep, they can be changed. additionally we may want to review all fns in vm and update sigs where needed.
