### ISSUE TITLE
`forge test --rerun` should re-run entire test file where `setUp()`  failed

### ISSUE THREAD

**Issue by 08xmt** [foundry-rs/foundry#9285]
### Component

Forge

### Describe the feature you would like

Currently if the `setUp()` function of a test file fails, the `--rerun` command will try to match with the `setUp()` function and the tests of the file will not rerun successfully. The `setUp()` function failing can be an issue for example when using an unreliable RPC for fork tests.

### Additional context

Output when running `forge test --rerun` purely for tests where `setUp()` failed:
```
No tests match the provided pattern:
	match-test: `setUp|setUp|setUp|setUp|setUp|setUp|setUp|setUp|setUp|setUp|setUp|setUp|setUp|setUp|setUp|setUp|setUp|setUp`
Error: 
No tests to run
```

**Comment by grandizzy** [comment]
I think the solution here would be to not include `setUp` fn at all in persisted failures - if there are tests failing due to setup failed then they'll be recorded and replayed, if they don't depend on setup then won't fail
