### ISSUE TITLE
forge-artifacts should include directory info

### ISSUE THREAD

**Issue by zhiqiangxu** [foundry-rs/foundry#9305]
### Component

Forge

### Describe the feature you would like

![image](https://github.com/user-attachments/assets/a50e6899-dc33-4658-9179-aea48eec5c38)

Currently `forge-artifacts` are stored like above, but it can conflict quite easily when there're contracts with the same name under two different directories.

**Comment by grandizzy** [comment]
thank you. same as https://github.com/foundry-rs/foundry/issues/3800 and https://github.com/foundry-rs/foundry/issues/1573, going to close as dupe
