### ISSUE TITLE
bug(`forge doc`): `@inheritdoc` doesn't work if package is coming from another repo

### ISSUE THREAD

**Issue by novaknole** [foundry-rs/foundry#9328]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (f479e94 2024-06-01T00:19:17.421178000Z)

### What command(s) is the bug in?

forge doc

### Operating System

macOS (Intel)

### Describe the bug

If `@inheritdoc` is used for the contract that is in another repo/package(not the main repo), descriptions don't end up in the documentation, but if `@inheritdoc` is used for the contract that is inside the main repo, then it works fine.

Seems like a bug, but not sure fully.

**Comment by grandizzy** [comment]
Bump @novaknole could you pls provide a repro? Thank you!

**Comment by grandizzy** [comment]
@novaknole I don't think that's an issue, please reopen with minimal repro if still a problem for you. thank you
