### ISSUE TITLE
Can we reopen #3357? A lot of people still having issues

### ISSUE THREAD

**Issue by Andriy-Kulak** [foundry-rs/foundry#9331]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### Operating System

macOS (Apple Silicon)

### Describe the bug

can we reopen: https://github.com/foundry-rs/foundry/issues/3357

`forget coverage --ir-minimum` still doesn't work for a lot of people. For example Im getting errors like below & a lot of others are experiencing same issues
```
Yul exception:Cannot swap Variable _50 with Variable expr_component_4: too deep in the stack by 1 slots in [ RET expr_52341_address expr_52371_address _50 expr_component_7 expr_52337_component_6 _52 expr_52337_component_5 expr_component_5 expr_52337_component_4 expr_52337_component_3 expr_component_3 expr_52337_component_2 expr_component_2 expr_52337_component_1 expr_52433_component expr_component expr_52337_component expr_component_1 expr_component_6 expr_component_4 ]
```

Solution presented in https://github.com/foundry-rs/foundry/issues/3357#issuecomment-1875666855 is suboptimal as we would have to break down sctucts into separate parts where it doesn't make sense from an organization perspective

**Comment by zerosnacks** [comment]
Hi @Andriy-Kulak thanks for your comment, I'll reopen the issue as it is active - unfortunately there is no good solution yet. Please also make sure to voice issues you are experiencing with the Solidity team.
