### ISSUE TITLE
Forge test auto create

### ISSUE THREAD

**Issue by tskoyo** [foundry-rs/foundry#9335]
### Component

Forge

### Describe the feature you would like

Hi team,

Hi team,

I was wondering if Foundry currently offers an option to automatically create a Solidity test file. I wasn’t able to find any such functionality and find it a bit tedious to manually create a new test file each time I write tests for a smart contract.

If this feature doesn’t exist yet, I’d like to propose adding a new command, something like:

`forge create-test ContractName`

This command would generate a basic test template for the specified contract, for example:

```
pragma solidity ^0.8.0;

import "forge-std/Test.sol";
import "../src/{contract_name}.sol";

contract {contract_name}Test is Test {
    {contract_name} public contractUnderTest;

    function setUp() public {
        contractUnderTest = new {contract_name}();
    }

    function testExample() public {
        // Add your test logic here
    }
}

```

### Optional Dependencies

To make this even more versatile, we could add an option to include additional dependencies during test file creation. For example:

`forge create-test ContractName --dependencies UniswapV2Library`

If specified, the tool would automatically resolve the dependency path using remappings.txt and include the correct import statement in the generated test file. Here’s an example of the output:

```
pragma solidity ^0.8.0;

import "forge-std/Test.sol";
import "../src/ContractName.sol";
import "@uniswap/v2-periphery/contracts/libraries/UniswapV2Library.sol";

contract ContractNameTest is Test {
    ContractName public contractUnderTest;

    function setUp() public {
        contractUnderTest = new ContractName();
    }

    function testExample() public {
        // Example test logic using UniswapV2Library
        uint256 value = UniswapV2Library.getAmountOut(1000, 5000, 10000);
        assertEq(value, 1666); // Replace with actual expected value
    }
}
```

**Comment by grandizzy** [comment]
@tskoyo please use `forge init hello-world` for such, see https://book.getfoundry.sh/reference/forge/forge-init

**Comment by grandizzy** [comment]
I could though misunderstood your request, reopening to clarify

**Comment by zerosnacks** [comment]
Hi @tskoyo, thanks for your suggestion.

I would recommend using snippets in your code editor / IDE. I don't think this should be part of Foundry.

See: https://code.visualstudio.com/docs/editor/userdefinedsnippets#_create-your-own-snippets

Marking as `not planned`
