### ISSUE TITLE
breaking(`nightly`): `Ambiguous import. Multiple matching files found inside base path and/or include paths`

### ISSUE THREAD

**Issue by 0xTimepunk** [foundry-rs/foundry#9365]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

nightly 

### What command(s) is the bug in?

forge build

### Operating System

None

### Describe the bug

Recent nightly from 2 days ago giving errors both on local and on CI

You can check a run https://github.com/superform-xyz/SuperVaults/actions/runs/11918496623/job/33216055316

If you run this repo on foundryup -C 9d74675bae8bfbd83428ff1343cbe2ae206c3383 the error won't exist

Note: this is urgent as it is breaking all of our CI runs

**Comment by zerosnacks** [comment]
Source of the error in `solc`: https://github.com/ethereum/solidity/blob/b0d991bd4b3bc2d48d40029c3303f67f604d7cc5/libsolidity/interface/FileReader.cpp#L128-L135

Possibly related to recent changes in https://github.com/foundry-rs/compilers? cc @klkvr / @DaniPopes / @grandizzy

**Comment by grandizzy** [comment]
yeah, was able to confirm was working before compilers update in https://github.com/foundry-rs/foundry/pull/8668
Workaround until a fix would be to change root prj remapping to `'forge-std/=lib/superform-core/lib/forge-std/src/',`  https://github.com/superform-xyz/SuperVaults/blob/main/foundry.toml#L20

**Comment by grandizzy** [comment]
pretty sure the right fix would be the one for https://github.com/foundry-rs/foundry/issues/9146 which should just ignore remappings from deps if already doen in project root remapping

**Comment by davidlaprade** [comment]
+1

I believe this is the source of the CI errors we're seeing on FlexVoting as well. CI was passing until nightly-e649e62, failing after. Pinning to e649e62f fixes it.
* [before](https://github.com/ScopeLift/flexible-voting/actions/runs/11821757268/attempts/1)
* [after](https://github.com/ScopeLift/flexible-voting/actions/runs/11821757268/attempts/2)

**Comment by grandizzy** [comment]
> I believe this is the source of the CI errors we're seeing on FlexVoting as well. CI was passing until nightly-e649e62, failing after. Pinning to [e649e62](https://github.com/foundry-rs/foundry/commit/e649e62f125244a3ef116be25dfdc81a2afbaf2a) fixes it.
> 

I am not sure is the same issue, I am not able to replicate the failure locally with master, did you try with latest nightly and still fails? thank you

**Comment by davidlaprade** [comment]
I can't reproduce our issue locally either, even after foundryup and forge clean. Happy to open another issue if you think this is different @grandizzy! But, yes, latest nightly [still fails](https://github.com/ScopeLift/flexible-voting/actions/runs/11821757268/job/33262662838)

**Comment by grandizzy** [comment]
> I can't reproduce our issue locally either, even after foundryup and forge clean. Happy to open another issue if you think this is different @grandizzy! But, yes, latest nightly [still fails](https://github.com/ScopeLift/flexible-voting/actions/runs/11821757268/job/33262662838)

I suspect that's a CI caching issue, on a successful run the missing deps are found and installed https://github.com/ScopeLift/flexible-voting/actions/runs/11821757268/job/32937233608#step:4:9 whereas on the failure it is starts building directly hence no file present in path https://github.com/ScopeLift/flexible-voting/actions/runs/11821757268/job/33208886192#step:4:9 @klkvr do you think this is the same issue as the original one? thanks

**Comment by klkvr** [comment]
It is not the same issue but probably also related to path resolution, unsure what exactly is happening there without a repro

**Comment by grandizzy** [comment]
👍 @davidlaprade please retry with tomorrow's build (that should include fix for this issue) and open a ticket if you still see the ptoblem. Thank you.

**Comment by davidlaprade** [comment]
Thanks! Will do
