### ISSUE TITLE
Remappings break CI builds using foundry > e649e62

### ISSUE THREAD

**Issue by davidlaprade** [foundry-rs/foundry#9375]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (25cc1ac 2024-11-21T00:22:12.782328000Z)

### What command(s) is the bug in?

forge test

### Operating System

Linux

### TLDR minimal reproduction [here](https://github.com/davidlaprade/foundry-ci-failure-repro)

I commented on this in [another issue yesterday](https://github.com/foundry-rs/foundry/issues/9365#issuecomment-2488570545).

We started seeing CI builds break for [flex-voting](https://github.com/ScopeLift/flexible-voting/) (as well as other internal projects) a [few days ago](https://github.com/ScopeLift/flexible-voting/actions/runs/11821757268/attempts/2). The errors happened during the `forge test` step:

```
Run forge test
2024-11-19T15:32:25.463715Z ERROR foundry_compilers_artifacts_solc::sources: error="/home/runner/work/flexible-voting/flexible-voting/lib/openzeppelin-contracts/contracts/utils/math/SafeCast.sol": No such file or directory (os error 2)
Error: failed to resolve file: "/home/runner/work/flexible-voting/flexible-voting/lib/openzeppelin-contracts/contracts/utils/math/SafeCast.sol": No such file or directory (os error 2); check configured remappings
	--> /home/runner/work/flexible-voting/flexible-voting/src/FlexVotingClient.sol
	@openzeppelin/contracts/utils/math/SafeCast.sol
```

Weirdly, we were never able to reproduce this locally. However, we resolved it in CI by pinning foundry to e649e62f125244a3ef116be25dfdc81a2afbaf2a in our workflow yaml, as seen [here](https://github.com/ScopeLift/flexible-voting/blob/893229bfc56b654208fc9611db755f865ae7749c/.github/workflows/ci.yml#L35-L38).

This morning we tried to reproduce the issue in [a clean repo](https://github.com/davidlaprade/foundry-ci-failure-repro). We found that the issue requires:
* `forge install`ing a library like OZ
* adding [a remapping](https://github.com/davidlaprade/foundry-ci-failure-repro/blob/956d1df3376ca7e991917791c8d79247e3cef409/foundry.toml#L4) for that repo in foundry.toml
* [using the remapping](https://github.com/davidlaprade/foundry-ci-failure-repro/blob/956d1df3376ca7e991917791c8d79247e3cef409/src/Counter.sol#L4) in a file compiled/run for testing

If the remapping is removed from the foundry.toml [the issue is fixed](https://github.com/davidlaprade/foundry-ci-failure-repro/actions/runs/11958002187/job/33336491775) -- `forge test` is able to run again in CI.

Open questions at this point:
1. How is the code able to compile if there are no remappings? `import {SafeCast} from "@openzeppelin/contracts/utils/math/SafeCast.sol";` should not compile without a remapping, but it does.
2. Why are the remappings breaking CI?
3. What changed in foundry to cause this to happen? Nothing obvious stands out in [the diff](https://github.com/foundry-rs/foundry/compare/nightly-e649e62f125244a3ef116be25dfdc81a2afbaf2a...nightly-c13d42e850da353c0856a8b0d4123e13cc40045d).

Thanks for your help!

**Comment by davidlaprade** [comment]
Operating system is linux because our CI uses ubuntu, and that's the only environment where this happened

**Comment by grandizzy** [comment]
@davidlaprade thank you for the detailed report and repro! the issue should be fix in tomorrow nightly build

> How is the code able to compile if there are no remappings? import {SafeCast} from "@openzeppelin/contracts/utils/math/SafeCast.sol"; should not compile without a remapping, but it does.
    Why are the remappings breaking CI?

There wasn't an issue with remappings but with project deps that were not installed in certain conditions (like CI), hence build failed since sources weren't found

>    What changed in foundry to cause this to happen? Nothing obvious stands out in [the diff](https://github.com/foundry-rs/foundry/compare/nightly-e649e62f125244a3ef116be25dfdc81a2afbaf2a...nightly-c13d42e850da353c0856a8b0d4123e13cc40045d).

This was related to the newly added feature, see https://github.com/foundry-rs/foundry/pull/9379#issue-2681518121

**Comment by davidlaprade** [comment]
Thanks @grandizzy and @yash-atreya!

Unfortunately #9379 didn't fix the issue for either [flex voting](https://github.com/davidlaprade/foundry-ci-failure-repro/actions/runs/11973217308/job/33381694155) or the [minimal repro](https://github.com/davidlaprade/foundry-ci-failure-repro/actions/runs/11973217308/job/33381694155). CI still fails with remappings on current nightly.

> There wasn't an issue with remappings but with project deps that were not installed in certain conditions

Got it, that explains why CI was broken. But I still don't understand how the project is able to compile locally without remappings. `@openzeppelin/contracts/utils/math/SafeCast.sol` is not a real path. How does forge know where to look for this file when remappings are removed from foundry.toml?

**Comment by davidlaprade** [comment]
Oh wait, I'm just realizing that @yash-atreya's (76a2cb0dd6d60684fd64a8180500f9d619ec94d2) wasn't in the current nightly (41b4359973235c37227a1d485cdb71dc56959b8b). So ignore my previous message about it not being fixed.

**Comment by davidlaprade** [comment]
Still curious about this part, though:

> I still don't understand how the project is able to compile locally without remappings. @openzeppelin/contracts/utils/math/SafeCast.sol is not a real path. How does forge know where to look for this file when remappings are removed from foundry.toml?

**Comment by klkvr** [comment]
> Still curious about this part, though:
> 
> > I still don't understand how the project is able to compile locally without remappings. @openzeppelin/contracts/utils/math/SafeCast.sol is not a real path. How does forge know where to look for this file when remappings are removed from foundry.toml?

This is happening because there's a `lib/openzeppelin-contracts/remappings.txt` which specifies `@openzeppelin/contracts/=contracts/`. So when finding remappings we find it and infer this remappings without requiring user to specify it in the root of the actual project.

**Comment by davidlaprade** [comment]
@klkvr Nice, I didn't know projects could do that. That's great to know and answers my question, thank you!
