### ISSUE TITLE
feature request: add support for fuzz/invariant timeouts

### ISSUE THREAD

**Issue by smartcontracts** [foundry-rs/foundry#9393]
### Component

Forge

### Describe the feature you would like

Would be great to have support for configurable timeouts in fuzz/invariant testing. General goal here is to be able to run these types of tests for a specific amount of time rather than a specific number of runs.

Example interface that might work would be to have some option `--fuzz-timeout-seconds` and `--invariant-timeout-seconds` that causes individual tests to time out after some number of seconds. Timeouts would ideally apply to individual tests (i.e., test A runs for X seconds and times out but test B that started after test A will continue running).

It probably makes sense for timeouts to be considered failures by default. However, it would be ideal to have options like `--allow-fuzz-timeout` and `--allow-invariant-timeout` that causes Forge to not report timeouts as failures. This opens up a lot of possibilities with long-running fuzzing jobs.

### Additional context

We've been messing with custom tooling to achieve this but doing it in forge is just way simpler.

**Comment by grandizzy** [comment]
thanks @smartcontracts would you be ok to adding your input to https://github.com/foundry-rs/foundry/issues/990 and tracking impl there?

**Comment by smartcontracts** [comment]
Yeah sorry thing, will do

**Comment by grandizzy** [comment]
Thank you, closing this one as dupe then, will add thoughts on pr
