### ISSUE TITLE
forge verify-contract errors with Fail - Unable to verify. Unable to locate ContractCode, yet Abi is compiled and available

### ISSUE THREAD

**Issue by 0xTimepunk** [foundry-rs/foundry#9398]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (d14a7b4 2024-11-24T00:24:44.637144000Z)

### What command(s) is the bug in?

forge verify-contract

### Operating System

None

### Describe the bug

Unable to locate ContractCode error, yet all Abi needed is available in the repository. Not sure what more information needs to be provided.

**Comment by grandizzy** [comment]
@0xTimepunk do you have a minimal repro to check, quite hard to figure out what's wrong without. Thank you

**Comment by grandizzy** [comment]
just tried verifying couple of contracts on sepolia and sepolia base and all working OK

**Comment by grandizzy** [comment]
for context: base related issue which was fixed and @0xTimepunk was able to verify
