### ISSUE TITLE
The reverted block.Time less than origin's

### ISSUE THREAD

**Issue by mask-pp** [foundry-rs/foundry#9410]
### Component

Anvil

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

nightly

### What command(s) is the bug in?

evm_revert

### Operating System

macOS (Apple Silicon)

### Describe the bug

Reverted `block.Time` less than the origin's.

the origin:
![image](https://github.com/user-attachments/assets/9af47b9b-205c-4c60-a8d9-85041e5a2424)

the reverted: 
![image](https://github.com/user-attachments/assets/e7c8c494-8e86-44a2-b807-1b2ae0ca2ea3)

**Comment by grandizzy** [comment]
@mask-pp please add more details of the issue you see and steps to reproduce it. Thank you
