### ISSUE TITLE
feat(`cast`): add ability to specify request headers

### ISSUE THREAD

**Issue by sebastiendan** [foundry-rs/foundry#9422]
### Component

Cast

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### Operating System

None

### Describe the bug

When using cast with an RPC endpoint behind Cloudflare Proxy, responses are 403s.
When testing the same rpc call with curl, it works fine. It seems that using curl without a user agent also returns 403s, so it could be that cast doesn't set any user agent.

I found no option in cast to set request headers.

**Comment by zerosnacks** [comment]
Generally supportive of this

We already support adding of custom headers in Alloy, should be relatively easy to add this to cast

https://github.com/alloy-rs/examples/blob/3b6d4a7cb465a0cb62a396735a8e26baa188ea55/examples/layers/examples/hyper_http_layer.rs#L92-L94

**Comment by yash-atreya** [comment]
I don't we need a layer for this, the current `foundy_common::provider` implementation supports adding custom headers to the underlying `reqwest::Client`. See: https://github.com/foundry-rs/foundry/blob/16a013fafb519395dc1aca810dabc3fffb7d02a0/crates/common/src/provider/mod.rs#L238.

We just need to expose a cli flag `headers: Vec<String>` in `RpcOpts` 
https://github.com/foundry-rs/foundry/blob/16a013fafb519395dc1aca810dabc3fffb7d02a0/crates/cli/src/opts/ethereum.rs#L19, then instantiate a provider with headers set. 

e.g usage:
`cast call 0x.. "balanceOf(address)" 0x. --rpc-url --headers name:value` 


> Generally supportive of this
> 
> We already support adding of custom headers in Alloy, should be relatively easy to add this to cast
> 
> https://github.com/alloy-rs/examples/blob/3b6d4a7cb465a0cb62a396735a8e26baa188ea55/examples/layers/examples/hyper_http_layer.rs#L92-L94

**Comment by zerosnacks** [comment]
> Would setting a default user-agent be a valid additional change? (might be tedious to keep specifying it)

Given that `cast` is meant to be invoked standalone - independent of the context of a foundry project it cannot rely on the `foundry.toml` configuration. I would recommend assigning it to an environment variable and passing that in.

**Comment by yash-atreya** [comment]
> > Would setting a default user-agent be a valid additional change? (might be tedious to keep specifying it)
> 
> Given that `cast` is meant to be invoked standalone - independent of the context of a foundry project it cannot rely on the `foundry.toml` configuration. I would recommend assigning it to an environment variable and passing that in.

We can use a env variable instead: `ETH_RPC_HEADERS`

**Comment by DaniPopes** [comment]
I think a default user-agent still makes sense, curl does this too
