### ISSUE TITLE
bug(`forge bind`): expected bytecode, found unlinked bytecode with placeholder

### ISSUE THREAD

**Issue by xiaoyu1998** [foundry-rs/foundry#9436]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (27cabbd 2024-11-29T00:26:52.751899000Z)

### What command(s) is the bug in?

forge bind --crate-name bindings-up

### Operating System

macOS (Intel)

### Describe the bug

I have a hardhat project ,and have foundry support and installed, I want to forge bind to get some rust file, but i seemed forge bind will check bytecode, in my project contract will call libraries, is foundry didn't support solidity librarly?

**Comment by xiaoyu1998** [comment]
Actually this project can be forge bind few month ago, it just has few variable names wrong, cus I have same named structs in defferent libraries, and i can update these variable names manually. but this time just can't forge bind. I am very curious why forge bind need check the bytecode?

**Comment by zerosnacks** [comment]
Hi @xiaoyu1998

You can pass the `--skip-build` flag to `forge bind` to skip compilation

Foundry does support Solidity libraries

If you still run into issues I would recommend re-running `forge bind`, there have been breaking updates to Alloy since then that may have an effect on your bindings

**Comment by xiaoyu1998** [comment]
thanks @zerosnacks,
I still run into this issue, you can download my repo to check it out.
https://github.com/xiaoyu1998/up-contracts-evm
below is my error message
[⠊] Compiling...
No files changed, compilation skipped
Generating bindings for 140 contracts
Error: failed to generate bindings for /Users/xiaoyu/work/up-contracts/out/BorrowHandler.sol/BorrowHandler.json:BorrowHandler

Context:
- Error #0: failed to parse input
- Error #1: invalid JSON: expected bytecode, found unlinked bytecode with placeholder: cde4a25c5cd794517f1425d10dbad6d2c4 at line 1 column 6209

**Comment by xiaoyu1998** [comment]
it is the external and public function in libraries run into this issue.

**Comment by xiaoyu1998** [comment]
replace all external and public function to internal, forge bind will be success.
