### ISSUE TITLE
wrong lines in "forge coverage --report lcov"

### ISSUE THREAD

**Issue by krakovia-evm** [foundry-rs/foundry#9437]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (27cabbd 2024-11-29T00:30:33.362570500Z)

### What command(s) is the bug in?

forge coverage --report -lcov

### Operating System

Windows

### Describe the bug

I just noticed "forge coverage --report -lcov" doesn't work anymore basically in all my repos.
Each coverage reports wrong lines, for example comments with green.
![image](https://github.com/user-attachments/assets/651736c9-15fb-4a29-a9ab-417f26294248)
![image](https://github.com/user-attachments/assets/cc7de299-65fd-488f-ad05-5dd5d87c3953)
![image](https://github.com/user-attachments/assets/1265def6-1cb2-404e-8a8c-828a3980a655)

did a test on virtual machine, clean vscode install and different addon to view .lcov files.
Same issues.
Here's a small project with the issue
(forge init --no-git, OZ 5 & a simple erc20 with tests)
[test.zip](https://github.com/user-attachments/files/17962709/test.zip)

**Comment by grandizzy** [comment]
@krakovia-evm moving discussion here, re https://github.com/foundry-rs/foundry/pull/9438#issuecomment-2508926251 I see the contract included even with the comment (that's before PR that fix this issue)

![image](https://github.com/user-attachments/assets/d131d623-b4d1-45ec-a581-d272447d2820)

**Comment by DaniPopes** [comment]
Cannot reproduce with the fix PR #9438

**Comment by krakovia-evm** [comment]
> Cannot reproduce with the fix PR #9438

i owe you a coffee ser.
It's working on all my workspaces now.
TY! o/
