### ISSUE TITLE
`cast call --chain` fails on custom chain ids

### ISSUE THREAD

**Issue by Rjected** [foundry-rs/foundry#9476]
### Component

Cast

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (e5dbb7a 2024-12-03T00:25:01.006590000Z)

### What command(s) is the bug in?

cast call

### Operating System

macOS (Apple Silicon)

### Describe the bug

When I run:
```
cast call --chain 55555
```
I get
```
Error: invalid type: found string "55555", expected u64
```

(with proper arguments for the rest). I printed the `Figment` object, and it shows:
```
          "chain_id": String(
              "41454",
          ),
```
The line that specifically errors seems to be this line:
https://github.com/foundry-rs/foundry/blob/805d7cee81e78e9163b8ce3d86a0c3beb39772d4/crates/cast/bin/cmd/call.rs#L121
The value parser for the `Chain` can properly parse this however.

**Comment by DaniPopes** [comment]
workaround is also to use --chain-id instead
