### ISSUE TITLE
Installing dependencies breaks `yarn install` in JS monorepo

### ISSUE THREAD

**Issue by woodpav** [foundry-rs/foundry#9488]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What command(s) is the bug in?

forge install

### Operating System

None

### Describe the bug

I am using yarn to install packages in turbo monorepo  for a JS project. 

I am using forge to install contract dependencies, namely openzeppelin.

`forge install OpenZeppelin/openzeppelin-contracts` in `packages/contracts`

This results in two folders in the `lib` directory in `packages/contracts` one for `forge-std` and the other for `openzeppelin`. 
The openzeppelin folder has another `lib` in `lib/openzeppelin/lib`  folder that includes a copy of `forge-std`. (Uh oh)
This means there are two directories with a `package.json` with a `name` field of `forge-std`. 
This breaks the yarn install command. 

Error:

    > yarn install
    error There are more than one workspace with name "forge-std"

Or:

    > npm install
    error There are more than one workspace with name "forge-std"

One solution is to change the `name` field of openzepplin's forge copy to something else. This fixes the installation but cannot be commited because it is a gitmodule. 

A suggested fix is to avoid duplicating `lib` folders when installing dependencies, this would require `openzeppelin` to reference the local version of `forge-std` instead of the version that is packaged with their code. 

Another possibility is a `yarn` or `npm` config setting that I do not know.

Thanks for reading.

How do I install contract dependencies using forge without duplicating the `package.json` for `forge-std`?

**Comment by grandizzy** [comment]
hi @woodpav please provide a way to replicate
> This results in two folders in the lib directory in packages/contracts one for forge-std and the other for openzeppelin.

this doesn't happen locally, only `openzeppelin` should be installed

thank you

**Comment by grandizzy** [comment]
please reopen with more details / way to replicate if still an issue. thank you
