### ISSUE TITLE
Unknown evm version: cancun causes panic in Foundry commands (forge clean, forge build, forge clean)

### ISSUE THREAD

**Issue by Austin5925** [foundry-rs/foundry#9495]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (02e430c 2023-07-21T12:38:42.023726000Z)

### What command(s) is the bug in?

forge test/ forge clean/ forge build

### Operating System

macOS (Apple Silicon)

### Describe the bug

forge clean

The application panicked (crashed).
Message:  failed to extract foundry config:
foundry config error: Unknown evm version: cancun for setting `evm_version`

Location: config/src/lib.rs:453

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

**Comment by zerosnacks** [comment]
Please run `foundryup`, you version is outdated

**Comment by zerosnacks** [comment]
I've tested against the latest version of Foundry and this works without issues.

Marking as `invalid`.

**Comment by Austin5925** [comment]
> Please run `foundryup`, your version is outdated

Thanks. I had run that, and was too careless to notice the "You may need to run 'rm /Users/xxx/.cargo/bin/chisel' ". Already solved.
