### ISSUE TITLE
snapshotGasLastCall weird folder removal behavior

### ISSUE THREAD

**Issue by sakulstra** [foundry-rs/foundry#9511]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge --version

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

When running a forge test containing `snapshotGasLastCall`, forge will remove the folder and recreate the files.
This behavior is quite problematic on bigger codebases as it's recommended to check the `snapshots` in git, but running test via `forge test --mc SomeTestContract` will remove all snapshots, but only recreate the ones created within the test I am running.

Imo it would be far less problematic & better UX, to just overwrite the affected file instead of removing the whole folder.

---

On some editors (at least `zed`) the current behavior is also problematic in regards to file watching as the removal and recreation will not be properly detected. Instead the stale(removed) file will be shown till a manual reload (close/open) by the user happens.

**Comment by zerosnacks** [comment]
Hi @sakulstra 

Thanks for flagging this, there is currently another ticket open in regards to the folder removal - would be great to receive you input there: https://github.com/foundry-rs/foundry/issues/9477

See: https://github.com/foundry-rs/foundry/issues/9477#issuecomment-2527250390

Marking as duplicate in favor of the linked ticket
