### ISSUE TITLE
`cast hash-message` wrong for multiline message

### ISSUE THREAD

**Issue by pcaversaccio** [foundry-rs/foundry#9512]
Example message:

```console
Welcome to OpenSea!

Click to sign in and accept the OpenSea Terms of Service (https://opensea.io/tos) and Privacy Policy (https://opensea.io/privacy).

This request will not trigger a blockchain transaction or cost any gas fees.

Wallet address:
0x657ff0d4ec65d82b2bc1247b0a558bcd2f80a0f1

Nonce:
8c6e353a-f145-4f55-ae76-a02c972db54a
```

If you use `ethers`:

```
> message = `Welcome to OpenSea!

Click to sign in and accept the OpenSea Terms of Service (https://opensea.io/tos) and Privacy Policy (https://opensea.io/privacy).

This request will not trigger a blockchain transaction or cost any gas fees.

Wallet address:
0x657ff0d4ec65d82b2bc1247b0a558bcd2f80a0f1

Nonce:
8c6e353a-f145-4f55-ae76-a02c972db54a`;

> hashMessage(message)
"0x4ec5fdf82c6c589fe380104d0b6df2daea557b49adf29e7bf7056236328597af"
```

If you use `cast hm` (save the message above as message.txt and run the bash script `./safe_messages.sh message.txt`):

```bash
# safe_messages.sh
calculate_offchain_message_hashes() {
    local message_file=$1
    message_raw=$(< "$message_file")
    local hashed_message=$(cast hash-message "$message_raw")
    echo "$hashed_message"
}

calculate_offchain_message_hashes "$@"
```

will output `0xa8741e52ffddee30191011bcdc3e7dcd4a277f2abc259182efc49d67252d238d`. The `ethers` result is correct (I verified it).

**Comment by grandizzy** [comment]
@pcaversaccio , I cannot reproduce the issue, the hashed message is the same with ethers, can you double check you're hashing same message?

![image](https://github.com/user-attachments/assets/6558d4b2-0c39-4e2f-bba7-db07586498ad)

**Comment by pcaversaccio** [comment]
> @pcaversaccio , I cannot reproduce the issue, the hashed message is the same with ethers, can you double check you're hashing same message?
> 
> ![image](https://private-user-images.githubusercontent.com/38490174/393723602-6558d4b2-0c39-4e2f-bba7-db07586498ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MzQ1OTcsIm5iZiI6MTczMzczNDI5NywicGF0aCI6Ii8zODQ5MDE3NC8zOTM3MjM2MDItNjU1OGQ0YjItMGMzOS00ZTJmLWJiYTctZGIwNzU4NjQ5OGFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDA4NTEzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwNjdjMTZkOTkzODFiZjgwM2IyMWQ1OGMwNGRmYmRlYTJiZGE5ZDNiZmM2YTg3ZThkODU0YTI3YTNkNDFkY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Pw3TyxvuNC4zEF2NtlcCHZRqZ7fCPNOjIM11PqqH208)

After debugging, I understand now the underlying issue. On Windows, if you save the message to a `txt` file for example, the default line breaks are CRLF. If you reformat them to LF, it will work. Can we fix this, so CRLF is transformed into LF before hashing?

**Comment by DaniPopes** [comment]
This is not the tool's responsibility, it just hashes the bytes provided in the input. If you're pasting into the node REPL then your shell is normalizing new-lines, otherwise if you're reading a file and passing it straight to stdin you'll have to do it manually.
