### ISSUE TITLE
cast: Not decoding tuple input correctly?

### ISSUE THREAD

**Issue by red-swan** [foundry-rs/foundry#9534]
### Component

Cast

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (aa69ed1 2024-12-10T00:24:07.060000503Z)

### What command(s) is the bug in?

forge cast abi-decode --input

### Operating System

Linux

### Describe the bug

I used cast to decode some input
```
cast abi-decode --input "run(address,(address,uint96))"  0xbd908912000000000000000000000000bbf3f1421d886e9b2c5d716b5192ac998af2012c000000000000000000000000bbf3f1421d886e9b2c5d716b5192ac998af2012c0000000000000000000000000000000000000000000000000000000067b2c250
```
The input is three values, two addresses (the same each time), and then the integer 1739768400 in hex form. Decoding this gets the addresses right but displays a very incorrect number.
```
0x00000000BbF3F1421D886E9B2C5D716b5192aC99
(0x00000000BbF3F1421D886E9B2C5D716b5192aC99, 62846758182151130748469830501530137713872804303009093102557276911061560197120 [6.284e76])
```
I am not confident that I'm doing everything perfect, but I believe this to be an issue if it's decoding the integer in the tuple incorrectly.

**Comment by grandizzy** [comment]
hey! proper way to do this is use `calldata-decode`, e.g.

```
cast calldata-decode "run(address,(address,uint96))"  0xbd908912000000000000000000000000bbf3f1421d886e9b2c5d716b5192ac998af2012c000000000000000000000000bbf3f1421d886e9b2c5d716b5192ac998af2012c0000000000000000000000000000000000000000000000000000000067b2c250
0xbbf3f1421D886E9b2c5D716B5192aC998af2012c
(0xbbf3f1421D886E9b2c5D716B5192aC998af2012c, 1739768400 [1.739e9])
```

please reopen if still issues
