### ISSUE TITLE
Incorrect 'Usage:' description of `forge create` (parameters in the wrong order)

### ISSUE THREAD

**Issue by dimitri-xyz** [foundry-rs/foundry#9535]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (59f354c 2024-12-11T00:24:56.327766786Z)

### What command(s) is the bug in?

forge create

### Operating System

Windows

### Describe the bug

Trying the following command on Windows WSL, we get the following error message. 
```
~/dev/ethernaut: forge create --from 0x14dC79964da2C08b23698B3D3cc7Ca32193d9955 --constructor-args "700" src/Token.sol:Token
error: the following required arguments were not provided:
  <CONTRACT>

Usage: forge create --from <ADDRESS> --constructor-args <ARGS>... <CONTRACT>

For more information, try '--help'.
```

It seems the options need to come _after_ the \<CONTRACT\>, not before. There are similar issues in many `--help` screens.

**Comment by grandizzy** [comment]
hey @dimitri-xyz thank you for reporting, this behavior is documented in https://book.getfoundry.sh/reference/forge/forge-create#forge-create

```
ℹ️ Note

The --constructor-args flag must be positioned last in the command, since it takes multiple values.
```

Going to close the ticket, please reopen if you find other inconsistencies. Thank you

**Comment by dimitri-xyz** [comment]
That makes sense! Thanks for pointing it out. I would just like to note that the command line with the `Usage:` line should then read (to match the other documentation):
```
Usage: forge create --from <ADDRESS> ... <CONTRACT> --constructor-args <ARGS>
```
