### ISSUE TITLE
bug: `vm.stopAndReturnDebugTraceRecording` consumes excessive amount of gas

### ISSUE THREAD

**Issue by NIC619** [foundry-rs/foundry#9536]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (59f354c 2024-12-11T00:29:25.224313000Z)

### What command(s) is the bug in?

forge test

### Operating System

None

### Describe the bug

The [erc4337-validation](https://github.com/rhinestonewtf/erc4337-validation) library [leverages startDebugTraceRecording](https://github.com/rhinestonewtf/erc4337-validation/blob/0a911c4c47bcfff05d02f0acee0bed0c264f906e/src/lib/Vm.sol#L40-L46) but the `stopAndReturnDebugTraceRecording` consumes tens or even hundreds of millions of gas thus when invoking the function many times, it will become increasingly more likely to result in OOG.

I forked the erc4337-validation repo and log the gas used (including `stopAndReturnDebugTraceRecording`) [here](https://github.com/NIC619/erc4337-validation/pull/2/files) and this is the sample output:
```shell
> forge test -vvvv --mt testSimulate
Ran 1 test for test/SimulatorV060.t.sol:SimulatorTest
[PASS] testSimulate() (gas: 122687982)
Logs:
  Gas used by stopAndReturnDebugTraceRecording 48967003
  ...
```

On my dev environment which uses erc4337-validation, the `stopAndReturnDebugTraceRecording` can cost up to `113205509` gas

**Comment by NIC619** [comment]
@grandizzy Thanks! pause/resume Gas Metering solve the OOG problem for me. But now I ran into other problems with my tests (they are updated with pause/resume Gas Metering):

1. Still some tests fail with `MemoryOOG`, they all fail right after calling `vm.stopAndReturnDebugTraceRecording`. If I bump the `gas_limit` param 10x, still `MemoryOOG`, if I bump it 100x, then I get `MemoryLimitOOG`. After I also bump `memory_limit` 10x, the test can finally pass.
2. Next, I try to run the whole test suites (including about 120 tests, each would invoke debug trace recording multiple times) but the process always gets killed.

Any idea how can I debug or solve this?

**Comment by grandizzy** [comment]
@NIC619 for point 1 try setting `gas_limit = "18446744073709551615"` in config
For point 2 - can you provide more details, how is getting killed, is that an OOM?

**Comment by NIC619** [comment]
> for point 1 try setting gas_limit = "18446744073709551615" in config

@grandizzy Setting the gas limit high enough would get rid of the `MemoryOOG` error but still gets `MemoryLimitOOG` error. Any recommendations about how to set the value of `memory_limit` in config?

> For point 2 - can you provide more details, how is getting killed, is that an OOM?

This is the log:
```shell
> npm run test:e2e:sepolia
> forge test -vvv --show-progress --fork-url sepolia --fork-block-number 7100540 --mp 'test/e2e/*.t.sol' --nmc 'SwitchBetweenOwnerValidatorsTest'

[⠊] Compiling...
No files changed, compilation skipped
test/e2e/ValidateUserOpCalls.t.sol:ValidateUserOpCallsTest
  ↪ Suite result: ok. 30 passed; 0 failed; 0 skipped; finished in 202.38ms (13.74ms CPU time)
test/e2e/gasPayment/GasPaymentWithoutPaymaster.t.sol:GasPaymentWithoutPaymasterTest
  ↪ Suite result: ok. 3 passed; 0 failed; 0 skipped; finished in 591.10ms (409.45ms CPU time)
test/e2e/initialization/InitializeEntryPoint.t.sol:InitializeEntryPointTest
  ↪ Suite result: ok. 1 passed; 0 failed; 0 skipped; finished in 377.92ms (186.00µs CPU time)
test/e2e/initialization/InitializeOwnerValidators.t.sol:InitializeOwnerValidatorsTest
  ↪ Suite result: FAILED. 2 passed; 3 failed; 0 skipped; finished in 216.22ms (3.43ms CPU time)
test/e2e/AccountsManagement.t.sol:AccountsManagementTest
  ↪ Suite result: FAILED. 2 passed; 3 failed; 0 skipped; finished in 3.19s (3.00s CPU time)
test/e2e/gasPayment/e2eOffChainPaymaster.t.sol:e2eOffChainPaymasterTest
  ↪ Suite result: FAILED. 13 passed; 3 failed; 0 skipped; finished in 3.94s (3.76s CPU time)
test/e2e/updateValidator/UpdateECDSAValidatorSettings.t.sol:UpdateECDSAValidatorSettingsTest
  ↪ Suite result: ok. 2 passed; 0 failed; 0 skipped; finished in 4.10s (2.29s CPU time)
test/e2e/DeployAccountEntryAndimAccount.t.sol:DeployAccountEntryAndimAccountTest
  ↪ Suite result: FAILED. 1 passed; 2 failed; 0 skipped; finished in 2.90s (2.69s CPU time)
test/e2e/AccountExecutor.t.sol:AccountExecutorTest
  ↪ Suite result: ok. 3 passed; 0 failed; 0 skipped; finished in 6.24s (6.06s CPU time)
test/e2e/imAccountFallback.t.sol:imAccountFallbackTest
  ↪ Suite result: ok. 16 passed; 0 failed; 0 skipped; finished in 258.94ms (14.33ms CPU time)
test/e2e/updateValidator/SetInvalidOwnerValidator.t.sol:SetInvalidOwnerValidatorTest
  ↪ Suite result: ok. 2 passed; 0 failed; 0 skipped; finished in 745.94ms (519.58ms CPU time)
test/e2e/AccountEntriesManagement.t.sol:AccountEntriesManagementTest
  ↪ Suite result: FAILED. 0 passed; 3 failed; 0 skipped; finished in 12.08s (10.32s CPU time)
test/e2e/updateValidator/UpdateSimpleMultiSigValidatorSettings.t.sol:UpdateSimpleMultiSigValidatorSettingsTest
  ↪ Suite result: ok. 4 passed; 0 failed; 0 skipped; finished in 8.77s (7.59s CPU time)
test/e2e/gasPayment/GasPaymentWithPaymaster.t.sol:GasPaymentWithPaymasterTest
  ↪ Suite result: ok. 7 passed; 0 failed; 0 skipped; finished in 10.92s (6.50s CPU time)
test/e2e/module/InstallAndUninstallModule.t.sol:InstallAndUninstallModuleTest
  ↪ Suite result: ok. 7 passed; 0 failed; 0 skipped; finished in 35.56s (35.19s CPU time)
test/e2e/updateValidator/UpdateUntrustedECDSAValidatorWithTrustedECDSAGuardianSettings.t.sol:UpdateUntrustedECDSAValidatorWithTrustedECDSAGuardianSettingsTest
  ↪ Suite result: ok. 8 passed; 0 failed; 0 skipped; finished in 37.57s (35.73s CPU time)
###############################---------      16/21      completed (with 10 threads)
⠁ test/e2e/updateValidator/UpdateTrustedWebAuthnValidatorWithUntrustedECDSAGuardianSettings.
⠁ test/e2e/guardian/e2eUntrustedECDSAValidatorWithTrustedECDSAGuardian.t.sol:e2eUntrustedECD
⠐ test/e2e/guardian/e2eUntrustedWebAuthnValidatorWithTrustedECDSAGuardian.t.sol:e2eUntrusted
⡀ test/e2e/guardian/e2eTrustedWebAuthnValidatorWithUntrustedECDSAGuardian.t.sol:e2eTrustedWe
⡀ test/e2e/updateValidator/UpdateWebAuthnValidatorSettings.t.sol:UpdateWebAuthnValidatorSett[1]    5062 killed     npm run test:e2e:sepolia
```

Are there other configs or options I can add to the command to provide more details?

**Comment by grandizzy** [comment]
@NIC619 what happens if you ignore the `updateValidator` test, does it work? is that an OOM happening?

**Comment by NIC619** [comment]
@grandizzy The process still gets killed after I ignore the `updateValidator` tests. My machine specs are MacBook Pro w/ M1 Pro chip, 10 cores and 16 GB memory.

This is the `top` command snapshot when I ran the test command:
![截圖 2024-12-13 晚上8 26 12](https://github.com/user-attachments/assets/baf9e987-746b-4073-85c5-a9a945fc487f)

Then I switch back to my main branch which does not contain changes related to `vm.startDebugTraceRecording`, the memory usage seems normal, compared to the one above:
![截圖 2024-12-13 晚上8 30 34](https://github.com/user-attachments/assets/8b8f03d7-4c8d-49bb-9529-8cc0b5675ac5)

> is that an OOM happening?

Is there a way I can tell if a process is terminated due to OOM?

**Comment by klkvr** [comment]
The issue here is that debug steps recording needs a lot of memory to store those steps both on foundry (Rust) and the test contract (Solidity) side. This is getting even worse when a lot of tests are run in parallel, especially if those are fuzz tests

@NIC619 is this happening if you set `--threads` flag to a lower value?

**Comment by NIC619** [comment]
@klkvr Thanks. After some trial and error, reducing the thread from the default (10) to 5 works. The tests are executed successfully on my machine.

**Comment by grandizzy** [comment]
@NIC619 that's great, mind to close the issue as don't think there's any action from our side. Thank you

**Comment by grandizzy** [comment]
Closing per above. Please reopen if still issues. Thank you.
