### ISSUE TITLE
bug(`forge verify-contract`): Unable to verify on explorer

### ISSUE THREAD

**Issue by duncancmt** [foundry-rs/foundry#9542]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (59f354c 2024-12-11T00:24:56.327766786Z)

### What command(s) is the bug in?

forge verify-contract

### Operating System

Linux

### Describe the bug

This bug is also present in fe2acca . Reference previous bug report #8470 .

As I promised in the previous report, I checked to see if the problem had been remedied by recent changes to foundry. Unfortunately, they have not.

## Steps to reproduce

If you check out 0xProject/0x-settler#265 (built from fe2acca; commit 883c3ee56df7143dcd82724c25309a1c6155fc9c [note: not on the `dcmt/taiko` branch]) or 0xProject/0x-settler#266 (built from 59f354c; commit 076e85ae5f119b845e1381d0e853d2f3c5af265e) you can reproduce this by attempting to verify the latest deployment of Settler on their respective chains (Taiko and World Chain).

```bash
forge clean
forge flatten -o src/flat/TaikoFlat.sol src/chains/Taiko.sol # substitute WorldChain if you want to test that instead
forge build -- src/flat/TaikoFlat.sol
forge verify-contract --watch --chain 167000 --verifier etherscan --etherscan-api-key 'YOUR_KEY_HERE' --verifier-url 'https://api.taikoscan.io/api' --constructor-args 0x883c3ee56df7143dcd82724c25309a1c6155fc9c000000000000000000000000 0xd36B8EA952EB37B842281788047E7C4501Cef91d 'src/flat/TaikoFlat.sol:TaikoSettlerMetaTxn' # substitute 0x076e85ae5f119b845e1381d0e853d2f3c5af265e000000000000000000000000 for the constructor argument and 0x271C15b2EB680e1EAb6435967f1D3600080aA8ce for deployed address if testing World Chain

### Output
# Start verifying contract `0xd36B8EA952EB37B842281788047E7C4501Cef91d` deployed on taiko
# Constructor args: 0x883c3ee56df7143dcd82724c25309a1c6155fc9c000000000000000000000000
# 
# Submitting verification for [src/flat/TaikoFlat.sol:TaikoSettlerMetaTxn] 0xd36B8EA952EB37B842281788047E7C4501Cef91d.
# Submitted contract for verification:
# 	Response: `OK`
# 	GUID: `ftvfgysjufjsjhdymzccnq4cdrbdntkn1rwr2ptnun8ehfivv3`
# 	URL: https://taikoscan.io/address/0xd36b8ea952eb37b842281788047e7c4501cef91d
# Contract verification status:
# Response: `NOTOK`
# Details: `Pending in queue`
# Warning: Verification is still pending...; waiting 15 seconds before trying again (7 tries remaining)
# Contract verification status:
# Response: `NOTOK`
# Details: `Fail - Unable to verify. Compiled contract deployment bytecode does NOT match the transaction deployment bytecode.`
# Error: Checking verification result failed
# 
# Context:
# - Contract failed to verify.
```

It's worth noting that the other contract deployed from that same flattened file on each chain verified just fine.

**Comment by grandizzy** [comment]
@duncancmt I suspect a block explorer related issue, are you able to manually verify the same contract?

**Comment by duncancmt** [comment]
The "SINGLE FILE / CONCATENATED METHOD" verification fails because I can't set `viaIR` as an optimization option. I don't know how I'd go about debugging an explorer-related issue. I don't have any contacts with the Etherscan team :(

**Comment by duncancmt** [comment]
After deploying yet another chain, I realized that the issue was actually in my deployment script. I'm therefore closing this issue because the technique of "`forge flatten` then `forge create`" solves my problem.

My sincere apologies for wasting y'all's time

**Comment by grandizzy** [comment]
no worries, glad it worked!
