### ISSUE TITLE
vm.expectRevert gets [FAIL: next call did not revert as expected] when function invocation has inline computations

### ISSUE THREAD

**Issue by y77cao** [foundry-rs/foundry#9549]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (c4fcf12 2024-12-12T00:23:11.758395000Z)

### What command(s) is the bug in?

forge test

### Operating System

macOS (Apple Silicon)

### Describe the bug

Previously I was invoking the method with vm.expectRevert as below:
```
 vm.expectRevert(Foo.InvalidInput.selector); // fails
 foo.settleRewards(
            address(0x123), rewardAmount * foo.feeBps() / 10000
        );
```
When running the test, it fails with error `[FAIL: next call did not revert as expected]`. If vm.expectRevert is commented out, the method will revert with expected error.

The test is fixed after I moved the inline calculation to a separate variable:
```
 uint256 amount = rewardAmount * foo.feeBps() / 10000;
 vm.expectRevert(Foo.InvalidInput.selector);
 foo.settleRewards(address(0x123), amount);
```
When running with -vvv, it seems that the test just halts at vm.expectRevert when the function invocation has inline calculations, and produced no tracing.

**Comment by grandizzy** [comment]
@y77cao that's the expected behaviour as next call to expect revert on is `foo.feeBps()`. Please update your test as you mentioned.
