### ISSUE TITLE
Local Simulation in Forge Scripts too slow

### ISSUE THREAD

**Issue by tHeMaskedMan981** [foundry-rs/foundry#9552]
### Component

Forge

### Describe the feature you would like

I am using Forge script for deployment and configuration of my project. 
While the deployment scripts run pretty quickly,  the standalone configuration scripts take a lot of time to run. 
As mentioned [here](https://book.getfoundry.sh/tutorials/solidity-scripting) , There is a local simulation step, where forge tries to run the script in the context of provided rpc URL.
But if the configuration step is complex, or is working with a lot of contracts on-chain, the scripts becomes very slow, sometimes taking > 2 mins just to simulate. 
Is it possible to add a flag to skip local simulation, something similar to --skip-simulation that we have for skipping on-chain simulation? 
Let me know if there is an easy way to speed up the local simulation step.

**Comment by grandizzy** [comment]
hey @tHeMaskedMan981 thank you for your report! We're looking to improve this post v1 as part of https://github.com/foundry-rs/foundry/issues/6825. Going to close this one as a dupe.
