### ISSUE TITLE
The behavior is changed by console.log(“h”);.

### ISSUE THREAD

**Issue by wshino** [foundry-rs/foundry#9555]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (dabacec 2024-12-14T00:22:42.684305000Z)

### What command(s) is the bug in?

forge test --match-test test_processCommand --ffi -vvv

### Operating System

macOS (Apple Silicon)

### Describe the bug

Currently, I am testing a verifier generated by Circom in the following repository:
https://github.com/zkemail/jwt-tx-builder/tree/ac2600cf6a1f3848575893d536eb069c9a62bf24

Typically, the Groth16Verifier.sol generated by Circom has the verifyProof function that takes `_pubSignals` as a fixed-length uint array.
I have confirmed that all calls to this function work correctly.

However, we want to make this fixed-length parameter variable-length to make the verifier call more flexible. In other words, we want to call this function with a variable-length argument and convert the argument back to a fixed length within the function.
The implementation looks like this:

```
at packages/contracts/src/utils/JwtAuthGroth16Verifier.sol

function verifyProof(uint[2] calldata _pA, uint[2][2] calldata _pB, uint[2] calldata _pC, uint[] calldata _receivedPubSignals) public view returns (bool) {
    console.log("h");
    // create fixed pubsignals
    uint[40] memory _pubSignals;
    for (uint i = 0; i < 40; i++) {
        _pubSignals[i] = _receivedPubSignals[i];
    }
}
```

In this repository, you can confirm that verifyProof works correctly with the generated proof and public signals by running
`forge test --match-test test_processCommand --ffi -vvv`.

However, the problem is related to the `console.log` before defining `_pubSignals`. If this `console.log` is commented out, the test fails.
I tried placing `console.log` in various parts of the process, and what I found is that the function works correctly only when the `console.log` is placed before defining `_pubSignals`.
Otherwise, the function returns false.

I saved the logs of successful test on gist, which you can check here:
https://gist.github.com/wshino/8b01217524b2286aca0afde75d6d8a18

I don't understand why a console.log, which shouldn't affect the logic, causes this behavior.
I am unsure if this is a Foundry issue, but I would like to understand why this console.log produces such a result.

**Comment by grandizzy** [comment]
Hi @wshino there's no packages/contracts/src/utils/JwtAuthGroth16Verifier.sol in https://github.com/zkemail/jwt-tx-builder/tree/b4eb4c2829c20d6b64aa30a34dfe1bc9e6677f54/packages/contracts/src/utils so hard to say what's the reason.

**Comment by wshino** [comment]
@grandizzy Thank you for your mention, and sorry I've updated the my question. 
You can see packages/contracts/src/utils/JwtAuthGroth16Verifier.sol in the commit hash [ac2600cf6a1f3848575893d536eb069c9a62bf24](https://github.com/zkemail/jwt-tx-builder/tree/ac2600cf6a1f3848575893d536eb069c9a62bf24)

https://github.com/zkemail/jwt-tx-builder/blob/ac2600cf6a1f3848575893d536eb069c9a62bf24/packages/contracts/src/utils/JwtAuthGroth16Verifier.sol

**Comment by grandizzy** [comment]
@wshino this is related to the fact you're console logging a string (which uses memory) and then your function assumes `_pubSignals` is written at the wrong address.  As a test, change `console.log("h");` to `console.log(true)` and you will get test failing.

Also, replacing with this pass:
```Solidity
        // string memory h1 = "h";
        string memory h = "h";
        console.log(h);
```

with this (2 strings in memory) fails:
```Solidity
        string memory h1 = "h";
        string memory h = "h";
        console.log(h);
```

I think test passing is only an effect of you not checking the proper memory slot for verifying proof, and you need to remove that line to get the real check. Hope this explains, going to close this for now, pls reopen if not agree. Thank you
