### ISSUE TITLE
Inheritance of struct in interface isn't supported 

### ISSUE THREAD

**Issue by buildlerdev** [foundry-rs/foundry#9561]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.2.0 (233bff2 2024-12-15T00:25:32.346944000Z)

### What command(s) is the bug in?

forge compile

### Operating System

macOS (Intel)

### Describe the bug

`forge` compile fails with following error on situations where struct is referenced from base interface during inheritance of struct.
```js
Error: Compiler run failed:
Error (9582): Member "PermitTransferFrom" not found or not visible after argument-dependent lookup in type(contract IPermit2).
    |
287 |             IPermit2.PermitTransferFrom({
```
The simplified file structure and example is as follows:

`IPermit2` is inherited from Uniswap `Permit2` repo: https://github.com/Uniswap/permit2/blob/main/src/interfaces/IPermit2.sol

C.sol
```js
import { IPermit2 } from "permit2/src/interfaces/IPermit2.sol";

contract C {

IPermit2 public permit2 = IPermit2(0x000000000022D473030F116dDEE9F6B43aC78BA3);

function _usePermit2(
        address _token,
        uint256 _amount,
        uint256 _nonce,
        uint256 _deadline,
        bytes calldata _signature
    )
        internal
    {
        PERMIT2.permitTransferFrom(
            IPermit2.PermitTransferFrom({
                permitted: IPermit2.TokenPermissions({ token: _token, amount: _amount }),
                nonce: _nonce,
                deadline: _deadline
            }),
            IPermit2.SignatureTransferDetails({ to: address(this), requestedAmount: _amount }),
            msg.sender,
            _signature
        );
    }

}
```

In the above snippet, `IPermit2.PermitTransferFrom` reference is failing with above mentioned error. Even though, `IPermit` inherits from struct `ISignatureTransfer` which contains `PermitTransferFrom` struct. Using, `ISignatureTransfer.PermitTransferFrom` works fine in this case.

However, the same file structure compiles fine in REMIX.

**Comment by zerosnacks** [comment]
Hi @buildlerdev 

This is very likely not related to Foundry.

A workaround I've used in the past is to import the underlying interface `IPermit2` inherits from.

For now marking as `out of scope`. 

I would recommend raising this issue in https://github.com/ethereum/solidity.
