### ISSUE TITLE
forge install not installing dependencies

### ISSUE THREAD

**Issue by thebraveman17** [foundry-rs/foundry#9582]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

0.2.0

### What command(s) is the bug in?

forge install

### Operating System

macOS (Apple Silicon)

### Describe the bug

Recently I've cloned a few projects from GitHub. Running `forge install` would just install the empty `lib` folder without any dependencies.

**Comment by grandizzy** [comment]
@thebraveman17 please provide steps to reproduce the issue. Thank you.

**Comment by zerosnacks** [comment]
^

from a basic test with https://github.com/Uniswap/v4-core.git I was unable to reproduce it

**Comment by thebraveman17** [comment]
Steps to reproduce:
1. Run `git clone https://github.com/Cyfrin/2024-12-christmas-dinner`.
2. Navigate to the directory.
3. Run `forge install`.

Only the empty lib folder is installed.

**Comment by grandizzy** [comment]
Thank you. Project you pointed has no deps (like in sample above https://github.com/Uniswap/v4-core/tree/main/lib)
You can add it yourself
`forge install foundry-rs/forge-std`
or open an issue in project `2024-12-christmas-dinner` to add missing deps.

**Comment by thebraveman17** [comment]
Oh, I see. Sorry for the lack of knowledge on my end and thank you @grandizzy for the explanation.
