### ISSUE TITLE
Failed to resolve solc versions for `testdata/default/cheats`

### ISSUE THREAD

**Issue by odyslam** [foundry-rs/foundry#9595]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.3.0 (3ba3d5f 2024-12-27T00:21:12.440798000Z)

### What command(s) is the bug in?

forge test 

### Operating System

macOS (Apple Silicon)

### Describe the bug

```
2024-12-27T13:42:33.596608Z ERROR foundry_compilers::resolver: failed to resolve versions
Error: Encountered invalid solc version in default/cheats/BlobBaseFee.t.sol: No solc version exists that matches the version requirement: ^0.8.25
Encountered invalid solc version in default/cheats/Blobhashes.t.sol: No solc version exists that matches the version requirement: ^0.8.25
Encountered invalid solc version in default/fork/DssExecLib.sol: No solc version exists that matches the version requirement: >=0.6.12, <0.7.0
Encountered invalid solc version in default/fork/LaunchFork.t.sol: No solc version exists that matches the version requirement: ^0.6.12
Encountered invalid solc version in multi-version/Importer.sol: No solc version exists that matches the version requirement: =0.8.17
Encountered invalid solc version in multi-version/cheats/GetCode17.t.sol: No solc version exists that matches the version requirement: =0.8.17
```

Goal: Run the forge tests in `testdata/default/cheats`

I have:
- Installed z3
- Enabled rosetta
- Nuked `~/.svm` multiple times
- Tried to manually install all the mentioned solc versions from the error

**Comment by grandizzy** [comment]
Hey @odyslam did you use `cargo test test_cheats_local` to run them or different command?

**Comment by odyslam** [comment]
@grandizzy I didn't, I run `forge test` from inside the testdata folder.  That command seems to be working, looking for the tests now to see how it setups the test environment
