### ISSUE TITLE
Validate gas costs for tests that contains SSTORE refunds

### ISSUE THREAD

**Issue by onbjerg** [foundry-rs/foundry#960]
See the original issue: https://github.com/gakonst/foundry/issues/812

The story after the REVM port is better, but still somewhat unvalidated: 

![image](https://user-images.githubusercontent.com/8862627/158793917-41d1c722-249d-4f3a-8138-92b296ab5e5d.png)

Currently there is still a small discrepancy of 42 gas that is unaccounted for between the trace of the root call and what REVM reports as the actual used gas after the call. This *only* happens when the test contains refunds which can *only* happen with `SSTORE`.

We need a sure-fire way to validate which number is correct and adjust the other one accordingly. An idea is to implement unit tests for the executor that test against the test cases in [EIP-3529](https://eips.ethereum.org/EIPS/eip-3529) as these cases have clearly defined gas costs. Note that the costs in the table assumes that all slots are hot, but our executor always starts with slots cold.

We have to assume that the number reported by REVM is truth, so the fault most likely lies in the tracer inspector.

**Comment by onbjerg** [comment]
Latest numbers dropped and it seems that we are still a little bit off: https://github.com/mds1/convex-shutdown-simulation/pull/16

If we add the instrinsic to Foundry's result it gives us 22,583,004 which is 2,995 gas higher than the 22,580,009 that Tenderly, Ganache and Hardhat agree on

**Comment by zerosnacks** [comment]
Would be good to re-evaluate this now that we have isolation mode (`--isolate`)

**Comment by zerosnacks** [comment]
Tentatively marking as resolved by isolation mode
