### ISSUE TITLE
Expand logging tests

### ISSUE THREAD

**Issue by onbjerg** [foundry-rs/foundry#968]
Expand the logging tests to include all `console.log` and DSTest-style logs

**Comment by shawnharmsen** [comment]
Apologies for any missteps as a newbie but I'd like to try to grok this better so would appreciate a little guidance.

I'd love to be able to flesh out more robust tests.

Are you looking for something like this?

my branch:
https://github.com/shawnharmsen/foundry/commit/bc8ae4d89ba5695b03a6155a43b330ec66b86c31

1. add more to [[testdata/logs/DebugLogs.t.sol]](https://github.com/foundry-rs/foundry/blob/master/testdata/logs/DebugLogs.t.sol)
2. add to [[forge/src/multi_runner.rs]](https://github.com/foundry-rs/foundry/blob/e3f14f68ebe45b8416974c49a7dc97d8d1517f65/forge/src/multi_runner.rs#L452)


Check the types from ds-test/test.sol
```
    event log                    (string);
    event logs                   (bytes);


    event log_address            (address);
    event log_bytes32            (bytes32);
    event log_int                (int);
    event log_uint               (uint);
    event log_bytes              (bytes);
    event log_string             (string);


    event log_named_address      (string key, address val);
    event log_named_bytes32      (string key, bytes32 val);
    event log_named_decimal_int  (string key, int val, uint decimals);
    event log_named_decimal_uint (string key, uint val, uint decimals);
    event log_named_int          (string key, int val);
    event log_named_uint         (string key, uint val);
    event log_named_bytes        (string key, bytes val);
    event log_named_string       (string key, string val);
```

https://github.com/dapphub/ds-test/blob/2c7dbcc8586b33f358e3307a443e524490c17666/src/test.sol#L19-L36

**Comment by onbjerg** [comment]
Yeah, essentially we should make sure we can decode all events from DSTest as well as all calls to `console.log`. These should be added to `DebugLogs.t.sol` as well as `HardhatLogs.t.sol`. We should then add the relevant assertions to `multi_runner.rs` :)
