### ISSUE TITLE
Add more positive fuzz tests to the test suite

### ISSUE THREAD

**Issue by onbjerg** [foundry-rs/foundry#971]
Wonder if we should add some more fuzzing unit tests that show the success case, given here I think we have a lot of "failign" ones which we use to gain confidence

_Originally posted by @gakonst in https://github.com/gakonst/foundry/pull/965#discussion_r829496068_

**Comment by shawnharmsen** [comment]
I'd like to take this one, do you know the best place for examples?

**Comment by gakonst** [comment]
Hey, check here for existing Forge fuzzing tests: https://github.com/foundry-rs/foundry/tree/master/testdata/fuzz

And you can see how a "good" set of fuzz tests look like in Solmate https://github.com/Rari-Capital/solmate/tree/main/src/test

**Comment by malik672** [comment]
assign me @onbjerg
