### ISSUE TITLE
Support overloaded functions in gas report

### ISSUE THREAD

**Issue by zaqk** [foundry-rs/foundry#977]
### Component

Forge

### Have you ensured that all of these are up to date?

- [X] Foundry
- [ ] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (db909f2 2022-03-18T00:07:32.053844+00:00)

### What command(s) is the bug in?

forge test --gas-report

### Operating System

macOS (amd)

### Describe the bug

Not sure if this is a bug or feature request. I have an overloaded function called getHp that accepts either one or three parameters. I see that the gas results are combined into one function.

Heres an example gas report with getHp as an overloaded function:
<img width="575" alt="image" src="https://user-images.githubusercontent.com/10659278/158915311-426e1835-40b9-4e5e-b23a-3ec8b747abba.png">

and heres me splitting getHp into two separate functions (getHp and getHp1), this is more how I would expect forge to show the gas cost for an overloaded function:
<img width="584" alt="image" src="https://user-images.githubusercontent.com/10659278/158915763-0e1ece6c-9106-45d0-9a4f-4203d680cbdf.png">

**Comment by jewei1997** [comment]
Hey looking for a good first issue, could I take this one?

**Comment by jewei1997** [comment]
@onbjerg Hey looking for a good first issue, could I take this on
