### ISSUE TITLE
Stack too deep error when passing many arguments to abi.encodePacked

### ISSUE THREAD

**Issue by wilsoncusack** [foundry-rs/foundry#980]
### Component

Forge

### Have you ensured that all of these are up to date?

- [ ] Foundry
- [X] Foundryup

### What version of Foundry are you on?

forge 0.1.0 (db909f2 2022-03-18T00:10:53.215991+00:00)

### What command(s) is the bug in?

forge build

### Operating System

macOS (M1)

### Describe the bug

I recently updated Foundry and noticed some of my repositories are no longer compiling. I get the error `CompilerError: Stack too deep when compiling inline assembly: Variable pos is 3 slot(s) too deep inside the stack.`. These repositories do compile with `aabfb0e - 2022-02-03`. 

After some investigation, I discovered the culprit is passing many args to `abi.encodePacked`, which is common in code for on-chain art. If you delete the last argument from here--22--it will compile. 
```
contract Contract {

    function test() external pure {
        abi.encodePacked(
            '1',
            '2',
            '3',
            '4',
            '5',
            '6',
            '7',
            '8',
            '9',
            '10',
            '11',
            '12',
            '13',
            '14',
            '15',
            '16',
            '17',
            '18',
            '19',
            '20',
            '21',
            '22'
        );
    }
}
```

**Comment by mattsse** [comment]
this is with default/unmodified config?

**Comment by wilsoncusack** [comment]
> this is with default/unmodified config?

I believe so! I made this example after just running forge init and have experienced on two different computers

**Comment by brockelmore** [comment]
@wilsoncusack is this still an issue?

**Comment by wilsoncusack** [comment]
> @wilsoncusack is this still an issue?

Will give it a shot, but the code is above if you want to try it :)

**Comment by brockelmore** [comment]
heh, just was wondering if you continued to use the above code and it just was fixed one day

**Comment by mattsse** [comment]
closing this since this is a solc error
if this was due to forge solc settings, they should be fixed since then
