### ISSUE TITLE
Add panic hook that checks if forge outdated

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#987]
### Component

Forge

### Describe the feature you would like

since we don't have a stable release yet and fixing issues frequently it might be useful to display whether the current forge build is significantly outdated once we panic, perhaps ~7 days or so

So could be useful as a temporary measure

**Comment by onbjerg** [comment]
Do we want this for stable? @mattsse

**Comment by mattsse** [comment]
don't think so, this will be less and less of a problem and since we made is thus for, closing this
