### ISSUE TITLE
Add --dry-run option or make compiling the flattened code locally the default before veryfying

### ISSUE THREAD

**Issue by mattsse** [foundry-rs/foundry#988]
### Component

Forge

### Describe the feature you would like

most verify endpoints return a cryptic "NOTOK" response or simply fail if the provided solidity code is errornous.

Since we already have the flattened code, we could try to compile it locally beforehand to ensure solc succeeds.

with `ethers::solc::TempProject` we already have everything we need to do this.

### Additional context

#982

https://github.com/gakonst/foundry/issues/982#issuecomment-1073016594_

**Comment by onbjerg** [comment]
I think you implemented this in a PR, right? At least this seems to be the behavior now:

```
    -f, --force
            Do not compile the flattened smart contract before verifying (if --flatten is passed).
```
