### ISSUE TITLE
Wishlist: Bytecode Size Measuring

### ISSUE THREAD

**Issue by transmissions11** [foundry-rs/foundry#992]
### Component

Forge

### Describe the feature you would like

`forge build --sizes` is cool, would be nice to build on it a bit to make it easier to work with:

- filter out test contracts
- see the delta between size limit and current
- have a flag in CI to fail the build if any of the non test contracts exceed the size limit
- some separate command to find the minimum optimizer runs that can fit your contracts into the limit

### Additional context

one of the major pains when writing smart contracts is hitting the bytecode size limit. allowing ppl to catch when their contracts go over the limit as early as possible would be a major relief

**Comment by onbjerg** [comment]
From #1133 (@mds1):

> ### Component
> 
> Forge
> ### Describe the feature you would like
> 
> We have `forge build --sizes` to print a table of contract sizes. `forge build --verify-sizes` would error if any src contract (not test contracts) are above the size limit, with the difference being that this version is much simpler to use in CI as it does not require users to manually parse the text output
> ### Additional context
> 
> _No response_

**Comment by mds1** [comment]
I want this pretty soon so might end up implementing myself if there's no objections. @onbjerg @mattsse any guidance you have on how to do this would save me a lot of time!

Here's my proposed implementation:
- Refactor output of `forge build --sizes` to display a table similar to gas report so it's easier to read
- Changes to the table:
    - No test contracts shown
    - Add a column that shows the delta between current size and max size
    - Color red if over limit, yellow if over 18kb, green otherwise (18 kB feels arbitrary, open to changing the thresholds, but over 75% seems like a good range for yellow)
- Add `forge build --sizes-ci` which behaves similarly, but after showing the table the process exits with `std::process::exit(1)` if any contracts are over over the size limit (pretty sure this should be enough to fail CI)
- "some separate command to find the minimum optimizer runs that can fit your contracts into the limit" — this feels like it can be pulled into a separate issue, and probably out of scope for my current implementation plan 😅

**Comment by mds1** [comment]
Instead of a separate `forge build --sizes-ci` command, @transmissions11 mentioned we can just have that behavior automatically if the env var `CI=true`, which github sets automatically. That way we can keep the interface clean with a single `forge build --sizes` command

**Comment by onbjerg** [comment]
Our definition of a test contract is pretty vague right now. I'd say you can filter out any contract that has a function that starts with `test`... and that's about all we can do right now 😅

The relevant snippet starts here:

https://github.com/foundry-rs/foundry/blob/ad253042bf842e4db90776c88a5a235ea4536545/cli/src/compile.rs#L113

`compiled_contracts` is of the type `BTreeMap<Version, Vec<(String, Contract)>>` where `Version` is the compiler version, string is the contract name (I presume, it might be the file path?) and `Contract` is this struct here, which contains an ABI:

https://github.com/gakonst/ethers-rs/blob/919a570237b0d92cfa34737d8803514caaa62612/ethers-solc/src/artifacts/contract.rs#L16

**Comment by transmissions11** [comment]
what about IS_TEST? https://github.com/dapphub/ds-test/blob/2c7dbcc8586b33f358e3307a443e524490c17666/src/test.sol#L38

**Comment by onbjerg** [comment]
It's not a guarantee that there is an `IS_TEST`, since tests don't even need to inherit from DSTest. A test can revert to signify failure, or set `failed` as DSTest does

**Comment by transmissions11** [comment]
imo we should change that and make some canonical test root but 🤷

**Comment by onbjerg** [comment]
I agree we should find a more concrete definition of what a test contract is, but it requires changes in a lot of places in the codebase, so I don't think this should be blocking @mds1 - also, whatever we decide on, it's likely going to be a breaking change, so we should probably bundle it with other breaking changes (e.g. breaking DT compatibility)

**Comment by transmissions11** [comment]
oh yeah def a separate issue dont wanna block this

**Comment by mds1** [comment]
Got it, all sounds good—thanks @onbjerg!

**Comment by mds1** [comment]
All items in this issue have been implemented except for "some separate command to find the minimum optimizer runs that can fit your contracts into the limit"

**Comment by onbjerg** [comment]
Maybe we should put that in a separate issue since it's a bit more complex, sort of like `forge test --sweep`. Not sure what we should call it, though

**Comment by mds1** [comment]
Created https://github.com/foundry-rs/foundry/issues/1342, so we can close this now. @transmissions11 let me know if that accurately describes what you had in mind

**Comment by transmissions11** [comment]
sounds good, thanks matt!

**Comment by sambacha** [comment]
> It's not a guarantee that there is an `IS_TEST`, since tests don't even need to inherit from DSTest. A test can revert to signify failure, or set `failed` as DSTest does

What about inheriting CI env? Most platforms treat any non empty string of CI to also mean NODE_TEST=true as an example.

**Comment by onbjerg** [comment]
That does not help us filter tests - the question is not *when* to filter tests, but *how*/what constitutes a test

**Comment by Fooooooooooox** [comment]
it will be nice if `forge build --sizes` can run without compiling with a flag like this: `forge build --sizes --no-compile`.
(sometimes you want to see immediate size changes when your code can not even compile successfully)
